### ISSUE TITLE
paddleinference推理ernie-tiny文本分类模型  batch_size大于4时报错

### ISSUE THREAD

**Issue by CCZGG** [PaddlePaddle/PaddleNLP#1002]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

版本：paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/python/predict.py

显卡：3090
描述：当batch_size小于4时，不报错，大于4时报错

![a28a2e08dca8a5a3c77a11221bf765a](https://user-images.githubusercontent.com/44726956/132655273-5a6d612b-bdc2-4d5d-a654-962f517ce705.png)

**Comment by CCZGG** [comment]
不是显存不足的问题，3090显卡，24G显存。

**Comment by linjieccc** [comment]
> 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
> 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
>   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> 版本：paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
> 
> 代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/python/predict.py
> 
> 显卡：3090
> 描述：当batch_size小于4时，不报错，大于4时报错
> 
> ![a28a2e08dca8a5a3c77a11221bf765a](https://user-images.githubusercontent.com/44726956/132655273-5a6d612b-bdc2-4d5d-a654-962f517ce705.png)

你好，麻烦换成paddlepaddle-gpu的release版本再试下呢？

**Comment by CCZGG** [comment]
> > 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
> > 在留下您的问题时，辛苦您同步提供如下信息：
> > 
> > * 版本、环境信息
> >   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
> >   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> > * 复现信息：如为报错，请给出复现环境、复现步骤
> > 
> > 版本：paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
> > 代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/python/predict.py
> > 显卡：3090
> > 描述：当batch_size小于4时，不报错，大于4时报错
> > ![a28a2e08dca8a5a3c77a11221bf765a](https://user-images.githubusercontent.com/44726956/132655273-5a6d612b-bdc2-4d5d-a654-962f517ce705.png)
> 
> 你好，麻烦换成paddlepaddle-gpu的release版本再试下呢？

怎么操作？你说的是这个吗？

<img width="1134" alt="1631237259(1)" src="https://user-images.githubusercontent.com/44726956/132784021-dc5e7fdf-104d-48bd-bae1-801ce08d4f87.png">

**Comment by CCZGG** [comment]
> > 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
> > 在留下您的问题时，辛苦您同步提供如下信息：
> > 
> > * 版本、环境信息
> >   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
> >   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> > * 复现信息：如为报错，请给出复现环境、复现步骤
> > 
> > 版本：paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
> > 代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/python/predict.py
> > 显卡：3090
> > 描述：当batch_size小于4时，不报错，大于4时报错
> > ![a28a2e08dca8a5a3c77a11221bf765a](https://user-images.githubusercontent.com/44726956/132655273-5a6d612b-bdc2-4d5d-a654-962f517ce705.png)
> 
> 你好，麻烦换成paddlepaddle-gpu的release版本再试下呢？

更换稳定版后，batch_size问题没有了，但是tensorRT报错：


ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration!

**Comment by linjieccc** [comment]
打开`use_tensorrt`开关需要带tensorrt的paddle运行环境，详情请参考这里：
https://paddle-inference.readthedocs.io/en/latest/optimize/paddle_trt.html#id2

**Comment by chenxiaozeng** [comment]
@CCZGG 您好，看到您正在使用PaddleNLP，我们想进一步和您沟通下需求背景以及使用场景，以便打磨更优秀的产品，更好得支持您的项目。这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
