### ISSUE TITLE
Where is the whole entity and phrase mask method for Ernie pretrain data?

### ISSUE THREAD

**Issue by AQA6666** [PaddlePaddle/PaddleNLP#1008]
Does anyone know where could find it?,it is import for me,thank you.

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0 Please try this one @AQA6666

**Comment by chenxiaozeng** [comment]
Issue Close. If you have other questions, please feel free to reopen it.
