### ISSUE TITLE
xlnet的get_offset_mapping方法支持

### ISSUE THREAD

**Issue by WenmuZhou** [PaddlePaddle/PaddleNLP#1010]
目前get_offset_mapping只支持了bert模型，但是我们在复现多模态方法的时候需要使用xlnet的get_offset_mapping方法，请求支持一下

**Comment by ZeyuChen** [comment]
@WenmuZhou 只是XLNet吗？现在的模型选型多模态这里是否有开源的参考？我们评估下是否需要整体来添加。
