### ISSUE TITLE
xpu服务器对应的paddlepaddle是cpu版本还是gpu版本呢

### ISSUE THREAD

**Issue by Clearloveplus7** [PaddlePaddle/PaddleNLP#1012]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by wawltor** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/09_hardware_support/xpu_docs/paddle_install_cn.html  

你好，xpu有特定的安装方式，具体安装如上。

**Comment by ZeyuChen** [comment]
XPU指的是昆仑芯片版本，属于ASIC芯片。@Clearloveplus7

**Comment by chenxiaozeng** [comment]
Issue Close. If you have other questions, please feel free to reopen it.
