### ISSUE TITLE
支持ernie-2.0预训练模型吗

### ISSUE THREAD

**Issue by yuanjie-ai** [PaddlePaddle/PaddleNLP#1013]
支持ernie-2.0预训练模型吗

**Comment by libertatis** [comment]
[PaddleNLP Transformer预训练模型汇总](https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers.html#transformer)
`PaddleNLP` 官方文档里写的有，`ernie-2.0` 目前只支持英文版预训练模型 `ernie-2.0-en` 和 `ernie-2.0-large-en`，还不支持中文版预训练模型~

**Comment by ZeyuChen** [comment]
![image](https://user-images.githubusercontent.com/1371212/133124787-512d6dee-b695-4f79-b40a-2321c8e8a939.png)

@Jie-Yuan 可以尝试下ERNIE-Gram，在中文benchmark上比ernie-2.0中文效果要更好。
https://arxiv.org/pdf/2010.12148.pdf

**Comment by chenxiaozeng** [comment]
Issue Close. If you have other questions, please feel free to reopen it.
