### ISSUE TITLE
快递单提取模型预测 deploy/python/predict.py中 test.txt 文件必须是已经打过标签的吗?如果 可以预测没有没有标注的数据吗?

### ISSUE THREAD

**Issue by cypqyc** [PaddlePaddle/PaddleNLP#1015]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by joey12300** [comment]
@cypqyc 你好，快递单信息抽取暂无预测未标注数据。可以暂时先参考lac的预测代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/deploy/predict.py

**Comment by wangruduo** [comment]
PaddleNLP 2.0.2，PaddlePaddle2.1.2
windows或者linux python3.7
快递单提取模型预测 deploy/python/predict.py中 test.txt 文件必须是已经打过标签的吗?如果 可以预测没有没有标注的数据吗?
