### ISSUE TITLE
有没有可以代替keras中的Tokenizer进行字符级标记的API

### ISSUE THREAD

**Issue by BaiEJi** [PaddlePaddle/PaddleNLP#1020]
在keras中的代码如下所示，其中author_A与author_B是两段文本
```python
# We use the Tokenizer class from Keras to convert the long texts into a sequence of characters (not words)
tokenizer = Tokenizer(char_level=True)
# Make sure to fit all characters in texts from both authors
tokenizer.fit_on_texts(all_authorA + all_authorB)
authorA_long_sequence = tokenizer.texts_to_sequences([all_authorA])[0]
authorB_long_sequence = tokenizer.texts_to_sequences([all_authorB])[0]
```
请问paddleNLP中有没有可以代替Keras中Tokenizer的fit_on_texts与texts_to_sequences方法的API

**Comment by ZeyuChen** [comment]
当前的PaddleNLP版本需要手动来实现这一功能，我们计划在2.2版本实现类似Keras Tokenizer的功能。 @BaiEJi 
目前您这类API通常用于实现哪些模型呢？

**Comment by BaiEJi** [comment]
> 当前的PaddleNLP版本需要手动来实现这一功能，我们计划在2.2版本实现类似Keras Tokenizer的功能。 @BaiEJi
> 目前您这类API通常用于实现哪些模型呢？

感谢您的回答，我现在是想要把手头上的一些其他框架的文本处理+深度学习小例子改写为Paddle实现，对于这个API的使用是在进行文本分类的问题上
