### ISSUE TITLE
paddlenlp git下来后pip install ./报这个错了，请问是什么原因呢

### ISSUE THREAD

**Issue by Zengpr** [PaddlePaddle/PaddleNLP#1025]
paddlenlp git下来后pip install ./报这个错了，请问是什么原因呢
![1631677652](https://user-images.githubusercontent.com/22451062/133367499-6f148758-a830-4df4-8868-a80ebe951eb4.png)

**Comment by ZeyuChen** [comment]
已线下解决。Issue Close.
