### ISSUE TITLE
ErnieModel 报错 

### ISSUE THREAD

**Issue by HuimengZhang** [PaddlePaddle/PaddleNLP#1026]
运行代码发现是paddlenlp的erniemodel报错 
抠出代码后错误可复现
跑例子可以，但是跑下面的x 会报错
paddle版本 gpu 2.1.2 paddlenlp 版本2.0.8

import paddle
import numpy as np
from paddlenlp.transformers import ErnieTokenizer, ErnieModel
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
text = tokenizer('aaa')
model = ErnieModel.from_pretrained('ernie-1.0')

y = paddle.to_tensor([text['input_ids']])
sequence_output, pooled_output = model(input_ids=y)

x = paddle.to_tensor([[1, 449, 431, 437, 78, 208, 585, 515, 208, 17, 589, 136, 249, 284, 139, 17963, 208, 701, 397, 515, 17, 317, 136, 208, 208, 139, 77, 4, 250, 132, 1587, 492, 1150, 17963, 329, 437, 403, 17963, 449, 431, 437, 78, 2251, 1675, 2205, 2744, 2481, 2420, 2251, 3156, 1545, 2496, 2251, 2552, 2744, 1671, 2052, 2420, 77, 4, 103, 31, 32, 61, 403, 514, 20, 1314, 241, 80, 391, 12043, 2 ]])
sequence_output, pooled_output = model(input_ids=x)
![image](https://user-images.githubusercontent.com/30888016/133386709-09e5d5e0-fb21-414a-8dfc-6419a1a3ebc3.png)

**Comment by wawltor** [comment]
辛苦提供一下用的GPU的型号和cuda版本，cudnn版本
