### ISSUE TITLE
bart-base模型精度问题

### ISSUE THREAD

**Issue by myboyliu** [PaddlePaddle/PaddleNLP#1027]
在复现Pegasus时候，我参考了bart,这2个模型很相似。但是对齐bart精度时候，发现误差很大。麻烦你看看。
mean difference: tensor(1.0486, grad_fn=<MeanBackward0>)
max difference: tensor(11.2015, grad_fn=<MaxBackward1>)
huggingface facebook/bart-base vs paddle bart-base
----------------------------------------------------------
from paddlenlp.transformers import BartTokenizer as PDBartTokenizer, BartModel as PDBartModel
from transformers import BartTokenizer, BartModel
from transformers import BartModel as PTBartModel
import paddle
import torch
import os,sys
base_dir=os.path.dirname(__file__)

sys.path.append(os.path.join(base_dir,'paddlenlp'))  #临时修改环境变量
paddle.set_device("cpu")

model_list = [
    ("facebook/bart-base", "bart-base")
    # ("google/Bart-xsum", "ErnieForGeneration")
]
text = "Welcome to use paddle paddle and paddlenlp!"

for model in model_list:
    bart_tokenizer = BartTokenizer.from_pretrained(model[0])
    pt_decoder_input_ids = bart_tokenizer("Studies show that", return_tensors="pt").input_ids
    pt_input_ids = bart_tokenizer("Studies have been shown that owning a dog is good for you", return_tensors="pt").input_ids
    #
    pt_model = PTBartModel.from_pretrained(model[0])
    outputs = pt_model(input_ids=pt_input_ids, decoder_input_ids=pt_decoder_input_ids)
    pt_outputs = outputs.last_hidden_state
    #paddle
    pd_model = PDBartModel.from_pretrained(model[1])

    with paddle.no_grad():
        tokenizer = PDBartTokenizer.from_pretrained(model[1])
        inputs = tokenizer("Studies have been shown that owning a dog is good for you")["input_ids"]
        decoder_input_ids = tokenizer("Studies show that")["input_ids"]
        pd_decoder_input_ids = paddle.to_tensor([decoder_input_ids])
        pd_input_ids = paddle.to_tensor([inputs])
        pd_outputs = torch.from_numpy(pd_model(input_ids=pd_input_ids, decoder_input_ids=pd_decoder_input_ids).numpy())
    print("mean difference:", (pt_outputs - pd_outputs).abs().mean())
    print("max difference:", (pt_outputs - pd_outputs).abs().max())
    print(f"huggingface {model[0]} vs paddle {model[1]}")

**Comment by gongel** [comment]
已和用户确认是自身环境问题。暂时先关闭issue，有需要后续可以再开启。
