### ISSUE TITLE
PaddleNLP/examples/language_model/ernie-doc/ 能否提供predict代码和deploy代码

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1032]
PaddleNLP/examples/language_model/ernie-doc/ 能否提供predict代码和deploy代码，想要训练好的模型进行预测和部署，试下效果，能否把这部分代码增加上，谢谢。

**Comment by joey12300** [comment]
@AI-Mart 您好，感谢您的建议，目前已经开始对predict和deploy的代码开发工作进行排期。

**Comment by AI-Mart** [comment]
大概什么时候能开发完呢，等着用哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/language_model/ernie-doc/ 能否提供predict代码和deploy代码 (#1032)





 
@AI-Mart 您好，感谢您的建议，目前已经开始对predict和deploy的代码开发工作进行排期。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
