### ISSUE TITLE
No module named 'data_tools.helpers

### ISSUE THREAD

**Issue by crrongyan** [PaddlePaddle/PaddleNLP#1039]
PaddleNLP==2.0.0
PaddlePaddle-gpu==2.1.3
ubuntu

根据此示例预训练ERNIE运行：

![屏幕截图 2021-09-16 180125](https://user-images.githubusercontent.com/46481479/133593204-b6250049-52b1-4ad2-93be-5a46810a5609.png)

报错：

![屏幕截图 2021-09-16 180125](https://user-images.githubusercontent.com/46481479/133592919-4b0f1554-de94-4b64-b09c-d0094f221c13.png)

我尝试了一下午，没能定位造成此问题的原因，能否帮忙看一下？

**Comment by libertatis** [comment]
`data_tools` 在这儿 [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools)

**Comment by ZeyuChen** [comment]
@crrongyan 更新下paddlenlp到最新版本2.0.8

**Comment by ZHUI** [comment]
应该是 helpers 编译失败了。可以参考，分析解决

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools#c%E4%BB%A3%E7%A0%81%E7%BC%96%E8%AF%91%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E

**Comment by crrongyan** [comment]
> 应该是帮助者编译失败了。可以参考，分析解决方法
> 
> [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools#c%E4%BB%A3%E7%A0%81%E7%BC%96%E8%AF%91%E5% A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools#c%E4%BB%A3%E7%A0%81%E7%BC%96%E8%AF%91%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E5%8A%9E)

确实是g++环境的问题，我换到AI Studio里执行 则把这个地方给跑过了，感谢您~
![屏幕截图 2021-09-16 232812](https://user-images.githubusercontent.com/46481479/133641187-10f81344-ada1-4d1b-9ca2-c7423e0bc329.png)

**Comment by chenxiaozeng** [comment]
@crrongyan 您好，看到您正在使用PaddleNLP，我们想进一步和您沟通下需求背景以及使用场景，以便打磨更优秀的产品，更好得支持您的项目。这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
