### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleNLP#1049]
paddle2.0 以上版本
1.paddlenlp 有类似paddleclas 利用配置 训练的例子吗？
2 我现在使用的是 ernie-tiny 模型 训练自己数据集   请问下 如果acc 想使用 top K  改怎么改？
3. 可以使用 worker_num 吗 linux 训练  我试了一下没找到办法

**Comment by wawltor** [comment]
你好，
1. paddlenlp目前不支持通过配置化的方式来进行训练，我们Readme上提供相应的python执行方式，写成bash脚本应该不难
2. https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/metric/accuracy_cn.html#accuracy  acc的topk 可以看上面的api
3. 这里的worker_num是指DataLoader还是只多卡训练了？
