### ISSUE TITLE
PaddleNLP里的预训练模型下载好慢，有没有办法全部打包下载

### ISSUE THREAD

**Issue by yuanjie-ai** [PaddlePaddle/PaddleNLP#1052]
PaddleNLP里的预训练模型下载好慢，有没有办法全部打包下载

**Comment by ZeyuChen** [comment]
目前没有提供全部打包下载的功能，模型存在在国内服务器，理论上在国内网络下载速度还是比较快的。

**Comment by yuanjie-ai** [comment]
怎么获取所有下载链接






yuanjie
***@***.***

小米互三
算法工程师



------------------ 原始邮件 ------------------
发件人: Zeyu Chen ***@***.***&gt;
发送时间: 2021年9月17日 23:38
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Betterme ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/PaddleNLP] PaddleNLP里的预训练模型下载好慢，有没有办法全部打包下载 (#1052)
