### ISSUE TITLE
wordtag实例运行，无法导入TaskFlow

### ISSUE THREAD

**Issue by Tellyang7** [PaddlePaddle/PaddleNLP#1054]
运行：
`from paddlenlp.taskflow import TaskFlow
task = TaskFlow("text2knowledge", model="wordtag")
task(["热梅茶是一道以梅子为主要原料制作的茶饮",
      "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
# Support the input text directly
task("热梅茶是一道以梅子为主要原料制作的茶饮")`

报错：
ImportError                               Traceback (most recent call last)
<ipython-input-1-ccf486dee422> in <module>
----> 1 from paddlenlp.taskflow import TaskFlow
      2 task = TaskFlow("text2knowledge", model="wordtag")
      3 task(["热梅茶是一道以梅子为主要原料制作的茶饮",
      4       "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
      5 # Support the input text directly

ImportError: cannot import name 'TaskFlow' from 'paddlenlp.taskflow' (C:\Users\XXX\AppData\Roaming\Python\Python38\site-packages\paddlenlp-2.0.0-py3.8.egg\paddlenlp\taskflow\__init__.py)

环境信息：
paddle2onnx                        0.7
paddlefsl                          1.0.0
paddlehub                          1.8.0
paddlenlp                          2.0.0
paddleocr                          2.2.0.1
paddlepaddle                       2.1.1

**Comment by wawltor** [comment]
from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp  import TaskFlow
我们更新一下文档

**Comment by Tellyang7** [comment]
> from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> 我们更新一下文档

多谢，导入没问题了。
我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv

**Comment by wawltor** [comment]
> > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > 我们更新一下文档
> 
> 多谢，导入没问题了。
> 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv

Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换  ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件

**Comment by Tellyang7** [comment]
> > > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > > 我们更新一下文档
> > 
> > 
> > 多谢，导入没问题了。
> > 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv
> 
> Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换 ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件
感谢！
我觉得判断一下文件是否存在也可以啊，不用每次都下载，自己加了句：
` term_schema_path = os.path.join(self._task_path,"termtree_type.csv")
        if not os.path.exists(term_schema_path):
....`

**Comment by wawltor** [comment]
> > > > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > > > 我们更新一下文档
> > > 
> > > 
> > > 多谢，导入没问题了。
> > > 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv
> > 
> > 
> > Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换 ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件
> > 感谢！
> > 我觉得判断一下文件是否存在也可以啊，不用每次都下载，自己加了句：
> > ` term_schema_path = os.path.join(self._task_path,"termtree_type.csv")         if not os.path.exists(term_schema_path): ....`

目前代码逻辑已经做了处理，不会每次都会下载，应该是md5值发生了变化，所以又下载了一次

**Comment by Tellyang7** [comment]
> > > > > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > > > > 我们更新一下文档
> > > > 
> > > > 
> > > > 多谢，导入没问题了。
> > > > 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv
> > > 
> > > 
> > > Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换 ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件
> > > 感谢！
> > > 我觉得判断一下文件是否存在也可以啊，不用每次都下载，自己加了句：
> > > ` term_schema_path = os.path.join(self._task_path,"termtree_type.csv")         if not os.path.exists(term_schema_path): ....`
> 
> 目前代码逻辑已经做了处理，不会每次都会下载，应该是md5值发生了变化，所以又下载了一次

救命，没有其他问题了，但是就是跑失败了，只有这个信息：

[2021-09-18 17:57:38,033] [    INFO] - Already cached XXX\models\wordtag\vocab.txt
[2021-09-18 17:57:38,046] [    INFO] - Already cached XXX\models\wordtag\wordtag_pos.pdparams

Process finished with exit code -1073741819 (0xC0000005)

有什么头绪吗？

**Comment by wawltor** [comment]
> > > > > > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > > > > > 我们更新一下文档
> > > > > 
> > > > > 
> > > > > 多谢，导入没问题了。
> > > > > 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv
> > > > 
> > > > 
> > > > Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换 ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件
> > > > 感谢！
> > > > 我觉得判断一下文件是否存在也可以啊，不用每次都下载，自己加了句：
> > > > ` term_schema_path = os.path.join(self._task_path,"termtree_type.csv")         if not os.path.exists(term_schema_path): ....`
> > 
> > 
> > 目前代码逻辑已经做了处理，不会每次都会下载，应该是md5值发生了变化，所以又下载了一次
> 
> 救命，没有其他问题了，但是就是跑失败了，只有这个信息：
> 
> [2021-09-18 17:57:38,033] [ INFO] - Already cached XXX\models\wordtag\vocab.txt
> [2021-09-18 17:57:38,046] [ INFO] - Already cached XXX\models\wordtag\wordtag_pos.pdparams
> 
> Process finished with exit code -1073741819 (0xC0000005)
> 
> 有什么头绪吗？

是不是内存不足？

**Comment by Tellyang7** [comment]
> > > > > > > from paddlenlp.taskflow import TaskFlow 替换成 from paddlenlp import TaskFlow
> > > > > > > 我们更新一下文档
> > > > > > 
> > > > > > 
> > > > > > 多谢，导入没问题了。
> > > > > > 我想问一下，可以通过本地路径读入这个文件嘛：：/models/transformers/ernie_ctm/termtree_type.csv
> > > > > 
> > > > > 
> > > > > Taskflow这里是一键式预测的，所以目前提供这样的接口来自定义TermTree，不过你可以尝试替换 ~/.paddlenlp/taskflow/text2knowledge/wordtag/这里的termtree_type.csv文件
> > > > > 感谢！
> > > > > 我觉得判断一下文件是否存在也可以啊，不用每次都下载，自己加了句：
> > > > > ` term_schema_path = os.path.join(self._task_path,"termtree_type.csv")         if not os.path.exists(term_schema_path): ....`
> > > 
> > > 
> > > 目前代码逻辑已经做了处理，不会每次都会下载，应该是md5值发生了变化，所以又下载了一次
> > 
> > 
> > 救命，没有其他问题了，但是就是跑失败了，只有这个信息：
> > [2021-09-18 17:57:38,033] [ INFO] - Already cached XXX\models\wordtag\vocab.txt
> > [2021-09-18 17:57:38,046] [ INFO] - Already cached XXX\models\wordtag\wordtag_pos.pdparams
> > Process finished with exit code -1073741819 (0xC0000005)
> > 有什么头绪吗？
> 
> 是不是内存不足？

虽然我觉得很可能是内存问题，但是32G应该不存在不够用的情况啊，还是说只适配了GPU环境？电脑没GPU倒是。。。
![image](https://user-images.githubusercontent.com/24445133/134276582-2f95d22e-db48-4dea-85e6-5c6a6b097d94.png)

**Comment by wawltor** [comment]
更新到最新develop版本，

from paddlenlp import TasKflow
task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行

**Comment by Tellyang7** [comment]
> 更新到最新develop版本，
> 
> from paddlenlp import TasKflow
> task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行

救命，还是报这个错误啊。。

![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)

**Comment by wawltor** [comment]
> > 更新到最新develop版本，
> > from paddlenlp import TasKflow
> > task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行
> 
> 救命，还是报这个错误啊。。
> 
> ![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)

我们在本地机器尝试后  cpu版本是可以的，要不再check一下机器

**Comment by wawltor** [comment]
> > 更新到最新develop版本，
> > from paddlenlp import TasKflow
> > task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行
> 
> 救命，还是报这个错误啊。。
> 
> ![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)

我们查了一下 应该是taskflow任务在windows环境下导入csv文件出错，已经提了PR修复 https://github.com/PaddlePaddle/PaddleNLP/pull/1062/files  如果比较急的话，可以根据PR做相应的修改

**Comment by Tellyang7** [comment]
> > > 更新到最新develop版本，
> > > from paddlenlp import TasKflow
> > > task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行
> > 
> > 
> > 救命，还是报这个错误啊。。
> > ![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)
> 
> 我们查了一下 应该是taskflow任务在windows环境下导入csv文件出错，已经提了PR修复 https://github.com/PaddlePaddle/PaddleNLP/pull/1062/files 如果比较急的话，可以根据PR做相应的修改

在我的环境中，这样修改也运行不了，我修改的方式是这样的：
![image](https://user-images.githubusercontent.com/24445133/134444015-114df3d1-386a-4db0-9a8a-392ef755d3e8.png)
即，编码格式应该是utf-8-sig，还要去掉delimiter

但是这个应该和我的问题无关，因为报错出现在数据内容导入之后。在执行任务语句
`task("热梅茶是一道以梅子为主要原料制作的茶饮")`
出错。。即无结果输出同时异常结束。。
麻烦再看看。。orz

**Comment by wawltor** [comment]
> > > > 更新到最新develop版本，
> > > > from paddlenlp import TasKflow
> > > > task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行
> > > 
> > > 
> > > 救命，还是报这个错误啊。。
> > > ![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)
> > 
> > 
> > 我们查了一下 应该是taskflow任务在windows环境下导入csv文件出错，已经提了PR修复 https://github.com/PaddlePaddle/PaddleNLP/pull/1062/files 如果比较急的话，可以根据PR做相应的修改
> 
> 在我的环境中，这样修改也运行不了，我修改的方式是这样的：
> ![image](https://user-images.githubusercontent.com/24445133/134444015-114df3d1-386a-4db0-9a8a-392ef755d3e8.png)
> 即，编码格式应该是utf-8-sig，还要去掉delimiter
> 
> 但是这个应该和我的问题无关，因为报错出现在数据内容导入之后。在执行任务语句
> `task("热梅茶是一道以梅子为主要原料制作的茶饮")`
> 出错。。即无结果输出同时异常结束。。
> 麻烦再看看。。orz


因为没有您的环境不太好复现问题，您看再确认一下下面的代码，这里的row是否为空
<img width="637" alt="图片" src="https://user-images.githubusercontent.com/16698950/134447730-10d446e2-270b-47ea-b488-2df50c52c9c2.png">

**Comment by Tellyang7** [comment]
> > > > > 更新到最新develop版本，
> > > > > from paddlenlp import TasKflow
> > > > > task = TaskFlow("text2knowledge", model="wordtag"， device_id=-1) # 支持cpu运行
> > > > 
> > > > 
> > > > 救命，还是报这个错误啊。。
> > > > ![image](https://user-images.githubusercontent.com/24445133/134294084-26867def-6538-4879-a4eb-680f36c51ce7.png)
> > > 
> > > 
> > > 我们查了一下 应该是taskflow任务在windows环境下导入csv文件出错，已经提了PR修复 https://github.com/PaddlePaddle/PaddleNLP/pull/1062/files 如果比较急的话，可以根据PR做相应的修改
> > 
> > 
> > 在我的环境中，这样修改也运行不了，我修改的方式是这样的：
> > ![image](https://user-images.githubusercontent.com/24445133/134444015-114df3d1-386a-4db0-9a8a-392ef755d3e8.png)
> > 即，编码格式应该是utf-8-sig，还要去掉delimiter
> > 但是这个应该和我的问题无关，因为报错出现在数据内容导入之后。在执行任务语句
> > `task("热梅茶是一道以梅子为主要原料制作的茶饮")`
> > 出错。。即无结果输出同时异常结束。。
> > 麻烦再看看。。orz
> 
> 因为没有您的环境不太好复现问题，您看再确认一下下面的代码，这里的row是否为空
> <img alt="图片" width="637" src="https://user-images.githubusercontent.com/16698950/134447730-10d446e2-270b-47ea-b488-2df50c52c9c2.png">
我这边按照源码直接读取文件，打印出row结果是：
`ROW: {'type-1,type-2,type-3,说明,主要对应词性,subtype示例(可扩展的开放集合),src(C表示cb基础概念库、E表示eb基础实体库)': '角色,,,角色类概念和实体,n/普通名词;nr/人名,群体,C/E'}`
去掉delimiter后，结果是：
`ROW: {'type-1': '角色', 'type-2': '', 'type-3': '', '说明': '角色类概念和实体', '主要对应词性': 'n/普通名词;nr/人名', 'subtype示例(可扩展的开放集合)': '群体', 'src(C表示cb基础概念库、E表示eb基础实体库)': 'C/E'}`
所以我去掉后可以正常读入数据。。。

而且直接使用“utf-8”后，读取结果中，会加上字符“\ufeff”，所以我是用的“utf-8-sig”格式读取的。
