### ISSUE TITLE
怎样打开TermTreeV1.0试用版文件？

### ISSUE THREAD

**Issue by geekchen007** [PaddlePaddle/PaddleNLP#1057]
PaddleNLP/examples/text_to_knowledge/termtree at develop · PaddlePaddle/PaddleNLP
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/termtree
 这个文件用什么工具可以打开？以及修改、维护

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/wordtag  这块有具体的使用方法，
<img width="600" alt="图片" src="https://user-images.githubusercontent.com/16698950/134337747-12a59a9e-82fe-4e00-887c-1353615c9a5d.png">

对于如何对TremTree进行修改以及维护，我们这块还没有放出API , 有兴趣的话可以看一下这块的代码，这里涉及TremTree的生成 https://github.com/PaddlePaddle/PaddleNLP/blob/499cbe4553d92c26ee2d7ac3a098b80fd1d6b27d/paddlenlp/taskflow/utils.py#L434

**Comment by qhpeklh5959** [comment]
可以使用paddlenlp.taskflow.utils.TermTree类来进行加载、增加、保存操作，因为涉及到数据结构整体性和一致性，暂不支持删除和修改操作。
建议使用离线配置表来维护自有数据，而非在线修改覆盖，这样有较高的容错能力，否则回退操作成本比较大。
这部分的特性刚刚更新，还没形成示例文档，后续会更新示例及文档，谢谢。
