### ISSUE TITLE
不知道是不是版本问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleNLP#1058]
paddlenlp 使用的是最新的版本
利用 ernie-tiny   在服务器 python3.7  paddle 2.0.2  GPU 训练好的 模型   在服务器预测cpu和GPU都是一样的

接着在本地调试的时候   本地环境是python3.6.5  paddle  2.1.1  cpu环境    同样的代码预测发现和服务器不一致  而且每次预测出来的数据 结果尽然还不一样 预测代码
![image](https://user-images.githubusercontent.com/53547082/133883130-98a18963-f95a-42fa-8b60-b0479556df7c.png)

**Comment by ZeyuChen** [comment]
请尝试使用paddlenlp和paddle最新版本再验证一下。

**Comment by wa3926** [comment]
@ZeyuChen  我不太清楚这个和训练模型的版本是否有关系   模型是用paddle 2.04 训练的    本地推理paddlenlp
 和paddle 都升级到最新的还是不一致
