### ISSUE TITLE
请教WebService 文本分类写法例子

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleNLP#1081]
请教一下 文本分类有 使用 WebService 
类似 
uci_service.prepare_pipeline_config("config.yml")  这样启动服务的例子吗 （在服务端处理参数）  请问下哪里能找到例子
我用的模型是使用 ernie-tiny 训练好的

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models  可以使用下面的例子 
<img width="1157" alt="图片" src="https://user-images.githubusercontent.com/16698950/134617357-20aa003b-11a0-475e-a02f-41f08b391e91.png">
