### ISSUE TITLE
ernie_gram 这个源码是不是有点问题

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#1089]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
网址 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_gram/modeling.py
287行   attention_mask = paddle.unsqueeze(
                (input_ids == self.pad_token_id
                 ).astype(self.pooler.dense.weight.dtype) * -1e9,
                axis=[1, 2])
这个  AttributeError: 'bool' object has no attribute 'astype'

**Comment by libertatis** [comment]
请参考 [https://github.com/PaddlePaddle/PaddleNLP/issues/799](https://github.com/PaddlePaddle/PaddleNLP/issues/799)

**Comment by Steffy-zxf** [comment]
@hl123-123 你好！你的输入数据是什么样的？请给出最小复现代码。

**Comment by hl123-123** [comment]
谢谢，我忽视了这个list转tensor的问题，== tensor运算符重载我没想到，不好意思打扰了。
https://github.com/PaddlePaddle/PaddleNLP/issues/799
