### ISSUE TITLE
albert-chinese-tiny 模型保存出现错误

### ISSUE THREAD

**Issue by stronger123-boa** [PaddlePaddle/PaddleNLP#1090]
1.我是按照官网的案例来写的

`
model = paddlenlp.transformers.ErnieForSequenceClassification.from_pretrained(
    MODEL_NAME, num_classes=len(label_list))
tokenizer = paddlenlp.transformers.ErnieTokenizer.from_pretrained(MODEL_NAME)
`

这样子执行模型训练是没有问题的，并且模型保存在指定的文件夹上

2.但是我改成albert模型就出错了

`
MODEL_NAME = "albert-chinese-tiny"  
model = AlbertForSequenceClassification.from_pretrained(MODEL_NAME, num_classes=2)
tokenizer = AlbertTokenizer.from_pretrained(MODEL_NAME)
`
3.模型训练没有问题，而是模型保存报错
`
model.save_pretrained('./checkpoint_CN')
tokenizer.save_pretrained('./checkpoint_CN')
`

4.报错信息

---> 39 tokenizer.save_pretrained('./checkpoint_CN')
     40 
     41 # model.save_pretrained('/home/aistudio/checkpoint_EN')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in save_pretrained(self, save_directory)
    624             f.write(json.dumps(tokenizer_config, ensure_ascii=False))
    625 
--> 626         self.save_resources(save_directory)
    627 
    628     def save_resources(self, save_directory):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/albert/tokenizer.py in save_resources(self, save_directory)
    221 
    222     def save_resources(self, save_directory):
--> 223         return self.tokenizer.save_resources(save_directory)
    224 
    225 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in save_resources(self, save_directory)
    635         """
    636         for name, file_name in self.resource_files_names.items():
--> 637             src_path = self.init_config[name]
    638             dst_path = os.path.join(save_directory, file_name)
    639             if os.path.abspath(src_path) != os.path.abspath(dst_path):
KeyError: 'vocab_file'

**Comment by yingyibiao** [comment]
#1102

**Comment by yingyibiao** [comment]
感谢反馈，该问题已提PR修复
