### ISSUE TITLE
关于多个任务的预训练模型的迁移学习

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1092]
Hi Team，

当有多个下游任务需要fine-tuning并且都使用ernie-gram时，预训练+下游任务模型一起调优时， 相同的预训练模型会或多或少发生变化， 这样当保存模型或者部署的时候将都需要同时保存或部署， 那么有没有一种方式可以只保存变化的部分呢， 看到下图有一种adapter的迁移学习模式（Parameter-Efficient Transfer Learning for NLP  https://arxiv.org/abs/1902.00751）似乎在解决这样的问题， 那么我的问题是，当前paddlenlp有提供这样的能力吗？

Thanks!

![image](https://user-images.githubusercontent.com/83859417/134795500-684ea857-b4b4-41ba-9738-073c2fb54c5b.png)

**Comment by ZeyuChen** [comment]
目前还未提供这样的功能，因为这种场景目前精度会比单任务下降，而且控制只finetune上层对bert这类模型的效果会打较大折扣，我们后续会继续调研下，如果有看到同样模型的开源版本也欢迎分享给我们。

**Comment by LangDaoAI** [comment]
> 目前还未提供这样的功能，因为这种场景目前精度会比单任务下降，而且控制只finetune上层对bert这类模型的效果会打较大折扣，我们后续会继续调研下，如果有看到同样模型的开源版本也欢迎分享给我们。

感谢回复！
