### ISSUE TITLE
快递单提取模型run_ernie.py中predict方法 和 deploy/python/predict.py 中预测结果差别很大，为什么呢？前者结果很好，后者结果很不好

### ISSUE THREAD

**Issue by cypqyc** [PaddlePaddle/PaddleNLP#1093]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by joey12300** [comment]
您好，请问是否可以提供最小测试代码？以及提供Paddle、PaddleNLP版本。可以先检查一下这两者是否加载同一套模型参数，示例中deploy是读取80轮的参数（`ernie_ckpt/model_80.pdparams`），并不是最终参数。

**Comment by cypqyc** [comment]
代码除了参数之外没有改动，deploy参数也已修改 选取的是我最后一轮模型（ernie_ckpt/model_3125.pdparams）
deploy参数代码如下：
# yapf: disable
parser = argparse.ArgumentParser(__doc__)
parser.add_argument("--model_dir", type=str, default='./output', help="The path to parameters in static graph.")
parser.add_argument("--data_dir", type=str, default="./waybill_ie/data", help="The folder where the dataset is located.")
parser.add_argument("--batch_size", type=int, default=16, help="The number of sequences contained in a mini-batch.")
parser.add_argument("--device", default="gpu", type=str, choices=["cpu", "gpu"] ,help="The device to select to train the model, is must be cpu/gpu.")
parser.add_argument('--use_tensorrt', default=False, type=eval, choices=[True, False], help='Enable to use tensorrt to speed up.')
parser.add_argument("--precision", default="fp32", type=str, choices=["fp32", "fp16", "int8"], help='The tensorrt precision.')
parser.add_argument('--cpu_threads', default=10, type=int, help='Number of threads to predict when using cpu.')
parser.add_argument('--enable_mkldnn', default=False, type=eval, choices=[True, False], help='Enable to use mkldnn to speed up when using cpu.')
parser.add_argument("--benchmark", type=eval, default=False, help="To log some information about environment and running.")
parser.add_argument("--save_log_path", type=str, default="./log_output/", help="The file path to save log.")
args = parser.parse_args()
# yapf: enable

以上参数只修改了 batch_size =16

paddle 版本 2.1.0
paddlenlp 版本 2.0.5

**Comment by chenxiaozeng** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/1137
Issue resolved. If you have other questions, please feel free to reopen it.
