### ISSUE TITLE
 文本相似度模型Simnet和“AI开放平台-短文本相似度”问题

### ISSUE THREAD

**Issue by Junshuai-Song** [PaddlePaddle/PaddleNLP#1094]
PaddleNLP开发者你们好，请问：
1. AI开放平台公布的接口是你们支持的吗？
2. 为什么不考虑补充上BERT、ERNIE相关模型，效果上不是显著好很多？
3. 请问AI开放接口中LSTM、CNN、BOW相关模型精度和这里给出的Simnet结果类似吗？使用开放接口优势在哪？（虽然模型一致，但内部有更多未公开的数据用于训练，所以开放接口性能更好？）

**Comment by Junshuai-Song** [comment]
<img width="1140" alt="截屏2021-09-27 上午10 17 17" src="https://user-images.githubusercontent.com/11649517/134836132-a81daa85-270e-4a01-826d-6e25459d9041.png">

来源：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/simnet

**Comment by wawltor** [comment]
> PaddleNLP开发者你们好，请问：
> 
>     1. AI开放平台公布的接口是你们支持的吗？
> 
>     2. 为什么不考虑补充上BERT、ERNIE相关模型，效果上不是显著好很多？
> 
>     3. 请问AI开放接口中LSTM、CNN、BOW相关模型精度和我们线下训练出来的类似吗？使用开放接口优势在哪？（虽然模型一致，但内部有更多未公开的数据用于训练，所以开放接口性能更好？）

1. AI开放平台目前不是我们提供的
2. Simnet是一种模型结构，基于非transformer的模型构建的；在text_matching目录有关于BERT/ERNIE相关的匹配模型。
3. AI开放接口模型的实现细节不太了解

**Comment by Junshuai-Song** [comment]
thx!
