### ISSUE TITLE
【论文复现】lstm无法与torch对齐

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleNLP#1101]
在torch中:
rnn = nn.LSTM(n_in, n_out, 1, batch_first=True, bidirectional=False)

输出的权重keys：
**odict_keys(['weight_ih_l0', 'weight_hh_l0', 'bias_ih_l0', 'bias_hh_l0'])**

在paddle中：
rnn = nn.LSTM(n_in, n_out, 1, time_major=False, direction="forward")

输出的权重keys：

**odict_keys(['weight_ih_l0', 'weight_hh_l0', 'bias_ih_l0', 'bias_hh_l0', '0.cell.weight_ih', '0.cell.weight_hh', '0.cell.bias_ih', '0.cell.bias_hh'])**

会多出0.cell的权重， 怎么保持一致？ 可将num_layers设置成0么？

**Comment by joey12300** [comment]
您好，请问您在复现哪一个模型呢？目前多出来的0.cell权重是为了保证兼容性，weight_ih_l0也会包含这部分权重，实际上并不影响正常的运行结果

**Comment by thunder95** [comment]
> 您好，请问您在复现哪一个模型呢？目前多出来的0.cell权重是为了保证兼容性，weight_ih_l0也会包含这部分权重，实际上并不影响正常的运行结果

您好，谢谢回复。 我在复现66号论文， 因为在尝试对齐检查，所以在排查问题。
