### ISSUE TITLE
Bert预训练模型如何设置'test'模式？

### ISSUE THREAD

**Issue by Junshuai-Song** [PaddlePaddle/PaddleNLP#1103]
对于这里的匹配任务，
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/sentence_transformers

使用Bert预训练模型fine-tune后，在同一个程序中多次预测同一组结果差距较大，请问如何设置为预测模式？想关闭Bert模型中本身dropout等带来的随机影响。
```
# bert-base-chinese
# model = ppnlp.transformers.BertModel.from_pretrained('bert-base-chinese')
# tokenizer = ppnlp.transformers.BertTokenizer.from_pretrained('bert-base-chinese')
```

当前设置xxx.ptm.mode='test'不起作用

**Comment by wawltor** [comment]
您好，可以设置eval状态来屏蔽一些随机性的影响，同时可以设置no_grad来避免反向变量的生成，来减少显存开销 
https://github.com/PaddlePaddle/PaddleNLP/blob/a88382d94043b2d6dc0d9ebcae90885a4dcaab01/examples/language_model/bert/run_glue.py#L186
https://github.com/PaddlePaddle/PaddleNLP/blob/a88382d94043b2d6dc0d9ebcae90885a4dcaab01/examples/language_model/bert/run_glue.py#L188
可以具体看这里

**Comment by Junshuai-Song** [comment]
thx!
