### ISSUE TITLE
UnifiedTransformer框架现在可以兼容ernie模型吗？

### ISSUE THREAD

**Issue by loujie0822** [PaddlePaddle/PaddleNLP#1106]
UnifiedTransformer框架现在可以兼容ernie模型吗？
或者UnifiedTransformer模型有直接从ernie模型转化的参数吗（包含LMHead参数）？

**Comment by ZeyuChen** [comment]
参数结构有一点点不一样。你可以使用ERNIE-Gen这个结构来适配ernie模型。
请问您具体是哪些什么应用场景呢？
