### ISSUE TITLE
关于阅读理解dureader_robust训练，训练损失不降低

### ISSUE THREAD

**Issue by Clearloveplus7** [PaddlePaddle/PaddleNLP#1107]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
关于阅读理解dureader_robust训练，训练损失不降低是怎么回事

**Comment by smallv0221** [comment]
![image](https://user-images.githubusercontent.com/33639025/136512802-74a11e64-1031-437e-95e3-d2839e983d52.png)
I'm using the newest PaddlePaddle and PaddleNLP package in Linux with python3.7. The loss decreases as expected.
