### ISSUE TITLE
AttributeError: module 'paddlenlp' has no attribute 'losses' #1095

### ISSUE THREAD

**Issue by taingload** [PaddlePaddle/PaddleNLP#1119]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
版本：
packaging              20.9           
paddlehub              2.0.4          
paddlenlp              2.0.8          
paddlepaddle-gpu       2.1.2.post101 

系统环境：
BML CodeLab 单卡版本

我把所有的代码贴到jupyter上去运行，在运行train的时候抛出了这个错误

`[2021-10-08 21:31:54,108] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
[2021-10-08 21:32:00,197] [    INFO] - Found /home/aistudio/.paddlenlp/models/ernie-gram-zh/vocab.txt
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-f21edcb16464> in <module>
    201 
    202 # if __name__ == "__main__":
--> 203 do_train()

<ipython-input-19-f21edcb16464> in do_train()
    125         trans_fn=trans_func)
    126 
--> 127     model = QuestionMatching(pretrained_model, rdrop_coef=args.rdrop_coef)
    128 
    129     if args.init_from_ckpt and os.path.isfile(args.init_from_ckpt):

<ipython-input-17-672d483082c6> in __init__(self, pretrained_model, dropout, rdrop_coef)
     17         self.classifier = nn.Linear(self.ptm.config["hidden_size"], 2)
     18         self.rdrop_coef = rdrop_coef
---> 19         self.rdrop_loss = paddlenlp.losses.RDropLoss()
     20 
     21     def forward(self,

AttributeError: module 'paddlenlp' has no attribute 'losses' `
麻烦帮忙看一下是什么问题，谢谢

**Comment by tianxin1860** [comment]
请首先检查一下使用的 paddlenlp 版本是否为 2.0.8，如果是 2.0.8 请在检查 losses 模块是否存在于 `${YOUT_PYTHON_PATH}/lib/python3.7/site-packages/paddlenlp/` 模块下？

**Comment by taingload** [comment]
> ${YOUT_PYTHON_PATH}/lib/python3.7/site-packages/paddlenlp/

你好，loss文件夹不存在于您说的目录下，我的目录的位置是
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/



--更新
你好，我换了个方式，卸载了之前的paddlenlp（2.0.7）再重新安装2.0.8版本，发现在路径下面有了losses文件，重新启用内核之后错误消失了。
谢谢
