### ISSUE TITLE
【Request】请求FP16

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1127]
Hi Team，

迫切需求FP16压缩模型size增强推理速度，以及利用GPU显存等。

希望Team能够给一下时间，谢谢！

**Comment by ZeyuChen** [comment]
是Fewshot的模型，还是普通的文本分类模型呢？

**Comment by LangDaoAI** [comment]
> 是Fewshot的模型，还是普通的文本分类模型呢？

Fewshot和普通文本分类模型，也就是涉及到底层预训练模型都需要

**Comment by LiuChiachi** [comment]
您好，我先验证下，今天晚些回复您～

**Comment by LiuChiachi** [comment]
您好，下周一给您回复时间。感谢关注～

**Comment by LangDaoAI** [comment]
感谢！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LiuChiachi** [comment]
HI @LangDaoAI 您好～
FP16下更快的推理加速功能预计在paddle 2.2正式版发布，在11月初。
感谢关注:)

**Comment by LangDaoAI** [comment]
好的，期待！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LangDaoAI** [comment]
> HI @LangDaoAI 您好～ FP16下更快的推理加速功能预计在paddle 2.2正式版发布，在11月初。 感谢关注:)

想问一下FasterTransformer 集成进来后， 是不是后面ERNIE系列的模型的底层都会做优化提供FasterTransformer 的支持，进而可以做高速推理？

**Comment by LiuChiachi** [comment]
是的，ERNIE系列模型需要用到的高性能推理API之后会开放～

**Comment by LangDaoAI** [comment]
> 是的，ERNIE系列模型需要用到的高性能推理API之后会开放～

好的
