### ISSUE TITLE
快递单提取模型run_ernie.py中predict方法 和 deploy/python/predict.py 中预测结果差别很大，前者结果很好，后者结果很不好

### ISSUE THREAD

**Issue by cypqyc** [PaddlePaddle/PaddleNLP#1137]
模型部署参数也修改了 params_path ernie_ckpt/model_80.pdparams 将model_80换成了迭代的最后一轮model_3125
deploy/python/predict.py 文件中只有batch_size 调整了 和 run_ernie中保持了一致  其他代码都没动
求解 🙏

**Comment by joey12300** [comment]
@cypqyc 您好，经检查发现是README写错了。导出模型的时候应该是`python export_model.py --params_path ernie_ckpt/model_80/model_state.pdparams --output_path=./output`，导出时出现下图红框所示，即表示成功导入参数
![image](https://user-images.githubusercontent.com/10826371/136804142-d7b53ff3-18f0-49fc-9e2f-6420980e4800.png)
