### ISSUE TITLE
readme 2.1版本发布？

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1141]
![image](https://user-images.githubusercontent.com/83859417/136766438-6ab2f049-5cb8-4656-93b0-da27fa5eac32.png)

tag分支并未看到2.1, 想确认一下，谢谢！

**Comment by yingyibiao** [comment]
今晚发布～

**Comment by ZeyuChen** [comment]
@LangDaoAI 2.1 pypi包已发，ReleaseNote待会更新。
