### ISSUE TITLE
Cublas error, `CUBLAS_STATUS_INTERNAL_ERROR`

### ISSUE THREAD

**Issue by JKsang** [PaddlePaddle/PaddleNLP#1152]
请问一下用官方的代码跑文本分类，这个报错是啥原因？[『NLP经典项目集』02：使用预训练模型ERNIE优化情感分析](https://aistudio.baidu.com/aistudio/projectdetail/1294333)
- 版本、环境信息
1）PaddleNLP==2.1.0，PaddlePaddle==2.0.2
2）系统环境：Linux, python==3.7.4
![image](https://user-images.githubusercontent.com/48127870/136905177-457168db-173e-40c8-9f8a-f00849b5cb29.png)
![image](https://user-images.githubusercontent.com/48127870/136905232-963d7207-8065-4b87-9e3a-f9e47b351bd9.png)

**Comment by wawltor** [comment]
麻烦提供一下GPU型号以及CUDA，CUDNN版本

**Comment by JKsang** [comment]
找到问题了，模型定义的类别数目和数据的类别没对上，但是为啥CrossEntropyLoss不提示错误，反而cuda报错呢？
Cuda compilation tools, release 10.1, V10.1.243
cudnn==7.3.1

**Comment by wawltor** [comment]
> CrossEntropyLo

看起来cudnn的版本也是比较低，可以升级cudnn版本到7.6再看看报错正常？

也可以提供一下CrossEntropyLoss的具体出错的shape，我们也排查一下是否op的报错有问题

**Comment by JKsang** [comment]
CrossEntropyLoss输入logits的shape是（32，88），label的shape是（32， 1），但是label中有大于等于88的数值。

**Comment by wawltor** [comment]
![image](https://user-images.githubusercontent.com/16698950/136933694-545ba075-4ee0-4829-9b06-d22a3ec83a93.png)
在即将发布的paddlepaddle 2.2 rc版本中，我们将在前端python拦截这个问题

**Comment by JKsang** [comment]
好的，谢谢！
