### ISSUE TITLE
如何提高ernie-tiny在cpu上生成向量的速度

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#1156]
1.可以使用paddle-inference来做？有案例？
2.有其他更好的方法？

**Comment by LiuChiachi** [comment]
您好～
可以使用paddle-inference来做，可以参考PaddleNLP里BERT预测的[案例](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert)，可以先查看README中的**预测**部分的教程，把模型替换成ernie-tiny即可。
- BERT导出模型使用的脚本：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/export_model.py
- BERT预测使用的脚本：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/predict_glue.py


有问题再交流，感谢关注:)

**Comment by tianchiguaixia** [comment]
有paddle-inferenc对ernie-tiny加速的脚本？

**Comment by LiuChiachi** [comment]
上面的链接，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert
这个里面的predict.p和predict_glue.py就是，参数model_type传ernie就可以了

**Comment by tianchiguaixia** [comment]
我本来使用的就是ernie-tiny。我是想在erine-tiny的基础上提速，不是在bert上提速。

**Comment by LiuChiachi** [comment]
明白你的意思，这个脚本是通用的，是可以给ernie-tiny模型使用的。

**Comment by tianchiguaixia** [comment]
使用这个，ernie-tiny会变快？生成句向量
