### ISSUE TITLE
ernie-csc的qps

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1161]
请问ernie-csc的qps能达到多少

**Comment by joey12300** [comment]
@zhentaoCoding 你好，请问你是指这里的模型吗？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc

**Comment by ZTurboX** [comment]
> @zhentaoCoding 你好，请问你是指这里的模型吗？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc

是的
