### ISSUE TITLE
如何离线使用Taskflow任务

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/PaddleNLP#1162]
### PaddleNLP安装
   pip install --upgrade paddlenlp  
   如果离线机器没有pip安装paddlenlp，可以尝试在有网络的机器上安装好paddlenlp，然后把python包迁移到离线机器上或者根据源码来安装paddlenlp

#### 创建任务目录
根据任务名和模型名创建本地目录，例如任务是word_segmentation任务，模型名lac，因此需要创建以下目录：
     **~/.paddlenlp/taskflow/word_segmentation/lac/** 
具体的任务名和模型之间的关系可以参考  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/taskflow.py      

#### 根据模型名下载模型
根据代码逻辑的URLS下载相应的模型，例如lac的模型下载地址在 https://paddlenlp.bj.bcebos.com/taskflow/lexical_analysis/lac/lac_params.tar.gz，    将模型参数下载到任务目录中，并解压
<img width="745" alt="图片" src="https://user-images.githubusercontent.com/16698950/137240371-5adb3c5b-c559-4516-8f1f-35bb242c4114.png">

#### 使用Taskflow
如果是分词任务即可在离线使用了
seg = Taskflow("word_segmentation")
seg("第十四届全运会在西安举办")

### 如何获取模型参数下载地址
如果对代码不是特别熟悉的同学，可能无法获取模型的资源的下载地址，可以在issue进行评论回复，我们会提供相应的下载地址给相应的同学。

**Comment by HaveF** [comment]
@wawltor 现在有更简单的方法吗? 谢谢!

**Comment by DebtVC2022** [comment]
请问可以提供UIE模型的下载地址吗 谢谢~

**Comment by wawltor** [comment]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/16698950/179434470-7deef201-ee88-4784-9679-a5b95be97105.png">
通过上面的方式即可使用UIE模型，具体的文档  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96  

上面的工具会把模型下载到 ~/.paddlenlp/taskflow/information_extraction目录下
