### ISSUE TITLE
关于文本纠错

### ISSUE THREAD

**Issue by di-osc** [PaddlePaddle/PaddleNLP#1163]
paddlenlp 2.1.0

**Comment by di-osc** [comment]
1 论文中的例子目前taskflow里面的文本纠错都不能实现
![image](https://user-images.githubusercontent.com/73778524/137239552-500e61ca-e407-444d-bc99-8deba9fc98d2.png)
他们的吵翻很不错,再说他们做的咖喱鸡也好吃!
结果:
吵 -> 炒
翻 ->  番
论文里面说的是:
吵 -> 炒
翻 -> 饭

2 文本比较长的时候会报错

paddlenlp和paddle都是最新版本

**Comment by joey12300** [comment]
@Ddream-ai   你好，论文中提到了两个提高纠错能力的方法：
1. 纠错模型结构中通过soft mask方式加入字音特征。
2. 在预训练阶段加入字音特征，提升预训练模型对同音字的召回能力。

论文中MLM-phonetics模型是在ERNIE基础上，加上字音特征在大规模无监督数据进行二次预训练，然后在纠错数据集上进行finetune得到的。目前由于论文中暂未开源该模型参数，所以TaskFlow提供的文本纠错模型是直接基于ERNIE-1.0的预训练模型进行finetune的（对应表格中ERNIE一行）。

**Comment by nghuyong** [comment]
@joey12300  您好，看到论文中提到了一个300万的预训练语料，这部分数据可以开源吗？或者有没有开源MLM-phonetics模型参数的计划？非常感谢！
