### ISSUE TITLE
[Feture Request]Taskflow dependency parsing task 追加已分词后解析语法树能力

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1167]
原DDParser功能中可以通过输入已分词来做语法树解析，请看下图：

![image](https://user-images.githubusercontent.com/83859417/137278053-d4d66691-97fe-4d63-9d79-a9c9f9b5c4f6.png)

当前taskflow/dependency_parsing.py 初始化时强制要求安装LAC， 如下图，

![image](https://user-images.githubusercontent.com/83859417/137278364-aa379b1f-f90c-48a0-8dbb-bc87c659217d.png)

我们实际测试中发现LAC有一些粒度分地有点大， 相反用jieba更好（也是在一些场景下或者用户自己的喜好），所以我们会先用jieba分好词之后再使用DDParser进行解析。

请确认一下该请求，谢谢！

**Comment by ZeyuChen** [comment]
@LangDaoAI 收到，我们评估下接口优化工作。
