### ISSUE TITLE
分词错误

### ISSUE THREAD

**Issue by Never-up** [PaddlePaddle/PaddleNLP#1168]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.1，PaddlePaddle2.0
2）系统环境：Linux     python版本3.7
错误：因为运行Taskflow分词报错
![20211014161513](https://user-images.githubusercontent.com/58769713/137279432-b08294cf-bf43-4d7b-9ec8-ffa6e7463b18.jpg)

**Comment by joey12300** [comment]
@Never-up 你好，根据您提供的信息，应该是paddle版本过旧引起的，请更新paddle至最新版本。

以下是我的测试结果
![image](https://user-images.githubusercontent.com/10826371/137280387-b3d15c4f-3a9b-483c-9d11-5c63696567eb.png)
