### ISSUE TITLE
taskflow函数加载错误

### ISSUE THREAD

**Issue by HuStanding** [PaddlePaddle/PaddleNLP#1170]
系统：Linux Ubuntu

环境：
paddlenlp        2.1.0
paddlepaddle     2.1.0

问题：使用教程加载下面的代码时出现错误
```
from paddlenlp import Taskflow

# 命名实体识别
ner = Taskflow("ner")
ner("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c0cd7ee3dffa> in <module>
      2 
      3 # 命名实体识别
----> 4 ner = Taskflow("ner")
      5 ner("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")

~/anaconda3/envs/paddle/lib/python3.6/site-packages/paddlenlp/taskflow/taskflow.py in __init__(self, task, model, device_id, **kwargs)
    179             model = TASKS[task]['default']['model']
    180         # Set the device for the task
--> 181         device = get_env_device()
    182         if device == 'cpu' or device_id == -1:
    183             paddle.set_device('cpu')

~/anaconda3/envs/paddle/lib/python3.6/site-packages/paddlenlp/utils/tools.py in get_env_device()
    115     elif paddle.is_compiled_with_npu():
    116         return 'npu'
--> 117     elif paddle.is_compiled_with_rocm():
    118         return 'rocm'
    119     elif paddle.is_compiled_with_xpu():

AttributeError: module 'paddle' has no attribute 'is_compiled_with_rocm'

```

请问这个是版本号的问题吗？是不是没有对应上？

**Comment by tianya092** [comment]
2.1.0 paddle 中 目前只有，paddle.is_compiled_with_cuda(  paddle.is_compiled_with_npu(   paddle.is_compiled_with_xpu ，还有看到is_compiled_with_rocm方法，不知道他们咋发布的，都不测试的吗？

**Comment by wawltor** [comment]
> 系统：Linux Ubuntu
> 
> 环境： paddlenlp 2.1.0 paddlepaddle 2.1.0
> 
> 问题：使用教程加载下面的代码时出现错误
> 
> ```
> from paddlenlp import Taskflow
> 
> # 命名实体识别
> ner = Taskflow("ner")
> ner("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
> ```
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-2-c0cd7ee3dffa> in <module>
>       2 
>       3 # 命名实体识别
> ----> 4 ner = Taskflow("ner")
>       5 ner("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
> 
> ~/anaconda3/envs/paddle/lib/python3.6/site-packages/paddlenlp/taskflow/taskflow.py in __init__(self, task, model, device_id, **kwargs)
>     179             model = TASKS[task]['default']['model']
>     180         # Set the device for the task
> --> 181         device = get_env_device()
>     182         if device == 'cpu' or device_id == -1:
>     183             paddle.set_device('cpu')
> 
> ~/anaconda3/envs/paddle/lib/python3.6/site-packages/paddlenlp/utils/tools.py in get_env_device()
>     115     elif paddle.is_compiled_with_npu():
>     116         return 'npu'
> --> 117     elif paddle.is_compiled_with_rocm():
>     118         return 'rocm'
>     119     elif paddle.is_compiled_with_xpu():
> 
> AttributeError: module 'paddle' has no attribute 'is_compiled_with_rocm'
> ```
> 
> 请问这个是版本号的问题吗？是不是没有对应上？

最新发版的Taskflow依赖于最新的版本PaddlePaddle，可以更新一下PaddlePaddle

**Comment by HuStanding** [comment]
我卸了PaddlePaddle2.1.0安装了PaddlePaddle2.1.3解决了，官方还是在README里面明确说明一下吧，按照README里面的>=2.1版本不太准确。

**Comment by wawltor** [comment]
> 我卸了PaddlePaddle2.1.0安装了PaddlePaddle2.1.3解决了，官方还是在README里面明确说明一下吧，按照README里面的>=2.1版本不太准确。

OK  我们在Taskflow的文档中加一下这个注释

**Comment by wawltor** [comment]
> > 我卸了PaddlePaddle2.1.0安装了PaddlePaddle2.1.3解决了，官方还是在README里面明确说明一下吧，按照README里面的>=2.1版本不太准确。
> 
> OK 我们在Taskflow的文档中加一下这个注释

https://github.com/PaddlePaddle/PaddleNLP/pull/1190  更新已合入
