### ISSUE TITLE
分布式训练相关问题

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#1174]
您好，请问在设置多卡训练后，报错：
assert self.sharding_degree > 1, "by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp."
AssertionError: by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp.
请问您知道这是什么原因吗？等待您的讲解，谢谢您！

**Comment by ZHUI** [comment]
> 您好，请问在设置多卡训练后，报错： assert self.sharding_degree > 1, "by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp." AssertionError: by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp. 请问您知道这是什么原因吗？等待您的讲解，谢谢您！

可以设置脚本 use_sharding=False 试一下？

**Comment by ZHUI** [comment]
龙哥看一下，use_sharding 这个静态图配置，是否要支持一下，纯dp，不用sharding的情况。  cc @sandyhouse

**Comment by sandyhouse** [comment]
> 龙

sharding optimizer里面不太建议增加纯dp功能的支持，理由如下：
1. 在sharding_optimizer里面支持dp功能会进一步增加sharding_optimizer的复杂度、可读性和可维护性；
2. dp功能是目前最常用的分布式训练方法，使用方法也比较简单，把常用功能放入到一个非常用里面功能里面，不太符合逻辑，且增加了使用的负责度；
3. 导致同一功能多套代码，比如对dp功能做了优化（如梯度fuse），就需要考虑是否需要对sharding里面的dp代码也同步修改，否则用户使用时会存在性能等方面差异，导致用户无所适从。

综上，最好还是采用松耦合的方式。

**Comment by ZHUI** [comment]
> > 龙
> 
> sharding optimizer里面不太建议增加纯dp功能的支持，理由如下：
> 
> 1. 在sharding_optimizer里面支持dp功能会进一步增加sharding_optimizer的复杂度、可读性和可维护性；
> 2. dp功能是目前最常用的分布式训练方法，使用方法也比较简单，把常用功能放入到一个非常用里面功能里面，不太符合逻辑，且增加了使用的负责度；
> 3. 导致同一功能多套代码，比如对dp功能做了优化（如梯度fuse），就需要考虑是否需要对sharding里面的dp代码也同步修改，否则用户使用时会存在性能等方面差异，导致用户无所适从。
> 
> 综上，最好还是采用松耦合的方式。

了解了，谢谢啦

我大概说一下我这边从使用的角度看到的部分问题哈

1.  只用dp，sharding_degree=1 的情况下，使用mp，pp，目前都是不合法的。功能完备性是有缺失的。如上述理由，存在一定技术上的困难。
2. 可能主要问题，是没有将 sharding 和 mp pp 解耦。或者说，目前sharding是一份不完备的dp的复制，维护成本也很大。

针对1的话，paddlenlp可以在训练参数配置中，屏蔽部分不合法的配置，不暴露use_sharding选项，并给用户参数提示、建议。
针对2的话，分布式这边可以长期看怎么样设计比较好，可否有更优的方案。

**Comment by sandyhouse** [comment]
> 我大概说一下我这边从使用的角度看到的部分问题哈
> 
> 1. 只用dp，sharding_degree=1 的情况下，使用mp，pp，目前都是不合法的。功能完备性是有缺失的。如上述理由，存在一定技术上的困难。
> 2. 可能主要问题，是没有将 sharding 和 mp pp 解耦。或者说，目前sharding是一份不完备的dp的复制，维护成本也很大。
> 
> 针对1的话，paddlenlp可以在训练参数配置中，屏蔽部分不合法的配置，不暴露use_sharding选项，并给用户参数提示、建议。 针对2的话，分布式这边可以长期看怎么样设计比较好，可否有更优的方案。

是的。所以，我们近期会把文档集中优化一波，在文档中把常见并行模式的使用方法解释清楚。
易用性提升也是我们持续在做的事情，最近我们也会收集易用性方面的反馈，来整体考量后面怎么整体优化分布式使用体验。

**Comment by ZHUI** [comment]
> 是的。所以，我们近期会把文档集中优化一波，在文档中把常见并行模式的使用方法解释清楚。 易用性提升也是我们持续在做的事情，最近我们也会收集易用性方面的反馈，来整体考量后面怎么整体优化分布式使用体验。

期待！

**Comment by shaitaiyangmie** [comment]
> > 您好，请问在设置多卡训练后，报错： assert self.sharding_degree > 1, "by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp." AssertionError: by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp. 请问您知道这是什么原因吗？等待您的讲解，谢谢您！
> 
> 可以设置脚本 use_sharding=False 试一下？

您好，我把use_sharding设置成了false，并且pretrain.sh中mp dp pp sharding均设置为1，topo = Topology( )中的参数num mp报错，请问这是为什么呢？如果我只想单纯使用多卡训练而并不使用sharding，则应该做什么修改呢？谢谢您指点。

**Comment by ZHUI** [comment]
> > > 您好，请问在设置多卡训练后，报错： assert self.sharding_degree > 1, "by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp." AssertionError: by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp. 请问您知道这是什么原因吗？等待您的讲解，谢谢您！
> > 
> > 
> > 可以设置脚本 use_sharding=False 试一下？
> 
> 您好，我把use_sharding设置成了false，并且pretrain.sh中mp dp pp sharding均设置为1，topo = Topology( )中的参数num mp报错，请问这是为什么呢？如果我只想单纯使用多卡训练而并不使用sharding，则应该做什么修改呢？谢谢您指点。

具体是哪一个 模型的训练代码呢？能给一个报错截图吗？

**Comment by shaitaiyangmie** [comment]
> > > > 您好，请问在设置多卡训练后，报错： assert self.sharding_degree > 1, "by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp." AssertionError: by now we only support five kind of hybrid dp: sharding_hybrid_dp, mp_sharding_hybrid_dp, pp_hybrid_dp, mp_sharding_pp_hybrid_dp, sharding_pp_hybrid_dp. 请问您知道这是什么原因吗？等待您的讲解，谢谢您！
> > > 
> > > 
> > > 可以设置脚本 use_sharding=False 试一下？
> > 
> > 
> > 您好，我把use_sharding设置成了false，并且pretrain.sh中mp dp pp sharding均设置为1，topo = Topology( )中的参数num mp报错，请问这是为什么呢？如果我只想单纯使用多卡训练而并不使用sharding，则应该做什么修改呢？谢谢您指点。
> 
> 具体是哪一个 模型的训练代码呢？能给一个报错截图吗？
您好，是language model里面的ernie预训练代码，现在好像没有了，我之前下载到本地用的。
<img width="946" alt="多卡报错1" src="https://user-images.githubusercontent.com/73834112/138021090-ce41d996-7429-4bb8-be37-cd96287cf7ae.png">
<img width="1099" alt="多卡报错2" src="https://user-images.githubusercontent.com/73834112/138021097-383d7439-ceee-477c-af24-46a6387c6d55.png">

**Comment by ZHUI** [comment]
我明白了。这套代码比较老了，不再推荐用户使用，已经放到了。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/experimental 

建议使用 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0 这一份代码去训练。
