### ISSUE TITLE
怎么把自己的数据集换成paddleNLP内置的数据集格式

### ISSUE THREAD

**Issue by millywang516** [PaddlePaddle/PaddleNLP#118]
~
原项目在这https://aistudio.baidu.com/aistudio/projectdetail/1294333?channelType=0&channel=0

问题：我自己的数据集应该是什么格式的？

例子中的数据集是PaddleNLP内置该数据集：

train_ds, dev_ds, test_ds = ppnlp.datasets.ChnSentiCorp.get_datasets(['train', 'dev', 'test'])

train_ds是'ChnSentiCorp' object
长下面这样

 
![image](https://user-images.githubusercontent.com/62973945/104553024-e26e3300-5674-11eb-88d4-82888f4534e7.png)

train_ds需要apply

train_ds.apply(trans_func, lazy=True)

其中trans_func需要train_ds是list
Apply貌似只能用dataframe，因为我试过list、set都报错没有apply属性

自定义数据集是（）包起来的，不能apply，内置数据集是【】包起来的。
![image](https://user-images.githubusercontent.com/62973945/104558415-b99e6b80-567d-11eb-871f-818353eeac19.png)

**Comment by ZeyuChen** [comment]
@millywang516 请参考自定义数据集文档 https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html
