### ISSUE TITLE
麻烦问下，生成式对话是理解上下文的吗？怎样利用自己的数据集进行训练呢？谢谢

### ISSUE THREAD

**Issue by andrew-begain** [PaddlePaddle/PaddleNLP#1187]

**Comment by tianxin1860** [comment]
你好，当前基于预训练模型的生成式对话解决方案都是对上下文进行理解建模的。基于自己的数据集进行训练可以参考 PaddleNLP 的对话示例: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer

**Comment by andrew-begain** [comment]
> 你好，当前基于预训练模型的生成式对话解决方案都是对上下文进行理解建模的。基于自己的数据集进行训练可以参考 PaddleNLP 的对话示例: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer

非常感谢，我仔细看下，谢谢
