### ISSUE TITLE
Taskflow可以多核CPU预测吗？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#1192]
- 版本、环境信息
1）PaddleNLP 2.1.0，PaddlePaddle2.1.3
2）CentOS 7，python 3.6.5
3）64核CPU，无GPU，内存16G
- 复现信息
Taskflow(
    'knowledge_mining',
    model='wordtag',
    batch_size=1,
    max_seq_length=128,
    linking=True)
- 业务上需要单个模型实例(内存限制，没法开多个模型实例)，单条语句输入(batch=1)，用CPU进行预测，发现只使用单核CPU，请问有办法修改配置调用多核吗？

**Comment by wawltor** [comment]
export OMP_NUM_THREADS=10 可以尝试打开这样开关，这个是一个多线程加速的方式

**Comment by Macxy2018** [comment]
输入export OMP_NUM_THREADS=10后可以用多核了

**Comment by Macxy2018** [comment]
按照export OMP_NUM_THREADS=10多线程加速后，运行时看确实是出现了多线程调度，但是预测速度却并没有啥明显的提升……
