### ISSUE TITLE
paddlenlp大预训练模型比如ernie如何通过paddleslim量化加速后部署到cpu，有没有相关的案例或者代码介绍

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1197]
paddlenlp大预训练模型比如ernie如何通过paddleslim量化加速后部署到cpu，有没有相关的案例或者代码介绍

**Comment by LiuChiachi** [comment]
您好～11月底我们会发布PaddleNLP2.2版本。我们计划在2.2开放BERT通过paddleslim量化加速后部署到cpu/gpu的案例～

**Comment by AI-Mart** [comment]
https://gitee.com/AI-Mart/PaddleNLP/tree/develop/examples/model_compression/ofa
这个是不是就是BERT通过paddleslim量化加速的案列呢？但是上面有说明说仅支持bert模型，能不能支持其他模型比如ernie-gram


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] paddlenlp大预训练模型比如ernie如何通过paddleslim量化加速后部署到cpu，有没有相关的案例或者代码介绍 (Issue #1197)





 
您好～11月底我们会发布PaddleNLP2.2版本。我们计划在2.2开放BERT通过paddleslim量化加速后部署到cpu/gpu的案例～
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiuChiachi** [comment]
这个链接是利用裁剪+蒸馏的策略对BERT进行压缩的一个例子，不包含量化。ernie-gram我们还没有测试过，但是和BERT网络结构类似，可以尝试把bert改成ernie-gram试一下～包含量化的例子也是近期会发布

**Comment by AI-Mart** [comment]
明白，希望这方面paddlenlp能加大力度，因为真正的产业落地，这些是必须要考虑，又要准，又要快。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] paddlenlp大预训练模型比如ernie如何通过paddleslim量化加速后部署到cpu，有没有相关的案例或者代码介绍 (Issue #1197)





 
这个链接是利用裁剪+蒸馏的策略对BERT进行压缩的一个例子，不包含量化。ernie-gram我们还没有测试过，但是和BERT网络结构类似，可以尝试把bert改成ernie-gram试一下～包含量化的例子也是近期会发布
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiuChiachi** [comment]
感谢关注！这一块会持续补充完整，有任何建议都欢迎反馈～:)

**Comment by AI-Mart** [comment]
https://gitee.com/AI-Mart/PaddleNLP/tree/develop/examples/model_compression/ofa


我想问下这个模型压缩案例是针对分类任务的，如果要改成实体识别的任务比如MSRA_NER&nbsp;代码应该怎么更改
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] paddlenlp大预训练模型比如ernie如何通过paddleslim量化加速后部署到cpu，有没有相关的案例或者代码介绍 (Issue #1197)





 
感谢关注！这一块会持续补充完整，有任何建议都欢迎反馈～:)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiuChiachi** [comment]
Duplicate of #1210
