### ISSUE TITLE
TypeError: download_file() takes from 3 to 4 positional arguments but 5 were given 请问如何解决呢

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleNLP#1199]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
paddlefsl               1.0.0
paddlenlp               2.1.0
paddlepaddle            2.1.3
使用的python是3.8.1

2）系统环境：请您描述系统类型：
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
- 复现信息：
![image](https://user-images.githubusercontent.com/40531744/138015283-dc86eb87-9ccb-44a7-a052-92504f25fbca.png)
运行脚本为在官方提供示例代码上修改的：
![image](https://user-images.githubusercontent.com/40531744/138015337-0fcbf0bd-f074-46bb-b91d-d51418dd4e14.png)

**Comment by wawltor** [comment]
请问一下 是使用最新的develop版本吗？

**Comment by ZZHHogan** [comment]
是的，NLP是使用最新的develop版本

**Comment by wawltor** [comment]
> 是的，NLP是使用最新的develop版本

可以拉取最新的develop版本，再试一下

**Comment by ZZHHogan** [comment]
好的，我是早上九点多拉取的develop，你们这边刚刚是更新了是吗，然后再重新拉取？

**Comment by wawltor** [comment]
> 好的，我是早上九点多拉取的develop，你们这边刚刚是更新了是吗，然后再重新拉取？

嗯呢 重新拉取 之前我们修复PR一直没有合入到develop版本上

**Comment by ZZHHogan** [comment]
你好，拉取之后好像并没有解决。
![image](https://user-images.githubusercontent.com/40531744/138202888-0019bafb-3aec-4d85-9c59-17b04efcdd53.png)
拉取后也更新了paddlenlp，请问怎么解决呢？
paddlefsl               1.0.0
paddlenlp               2.1.1
paddlepaddle            2.1.3

以下是代码内容：
![image](https://user-images.githubusercontent.com/40531744/138203034-9a0436dd-bfe3-4408-a774-9ed1c7327a40.png)
