### ISSUE TITLE
请问有提供SimCSE的模型吗？

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/PaddleNLP#1202]
请问有提供SimCSE的模型吗？目前这边的机器训练不了，所以想先使用SImCSE的模型进行推理测试，不知道官方哪里有提供？

**Comment by LangDaoAI** [comment]
这个问题是否延展到examples所有模型能够提供训练好的模型？

**Comment by ZZHHogan** [comment]
应该不需要，我现在只想试试这个效果

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/simcse @hhhhhhogan

**Comment by tianxin1860** [comment]
> 请问有提供SimCSE的模型吗？目前这边的机器训练不了，所以想先使用SImCSE的模型进行推理测试，不知道官方哪里有提供？

如果只想走推理测试效果的话，建议可以先使用语义索引模型来计算相似度，模型原理和 SimCSE 类似，这里发布了训练好的语义索引模型: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing

**Comment by ZZHHogan** [comment]
好的，目前就在测试semantic_indexing，感谢回复！
