### ISSUE TITLE
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`.

### ISSUE THREAD

**Issue by wht0948** [PaddlePaddle/PaddleNLP#1203]
重装了一个2.1.3的paddle版本之后就加载不了模型了，请问是什么原因

import paddle
import paddle.nn.functional as F
import paddle.nn as nn
from paddle.optimizer.lr import NoamDecay
from paddle.optimizer import AdamW
from paddle.io import DataLoader
from paddlenlp.transformers import UnifiedTransformerLMHeadModel, UnifiedTransformerTokenizer

model_name_or_path = 'unified_transformer-12L-cn'
model = UnifiedTransformerLMHeadModel.from_pretrained(model_name_or_path)

OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:107)
  [operator < uniform_random > error]

**Comment by wawltor** [comment]
辛苦提供一下 机器的Cuda版本和GPU的型号，可能是新安装的PaddlePaddle的cuda版本不对

**Comment by wht0948** [comment]
> 辛苦提供一下 机器的Cuda版本和GPU的型号，可能是新安装的PaddlePaddle的cuda版本不对

不好意思回复晚了，Cuda版本:11.0，GPU型号:2080ti，paddle安装版本:paddlepaddle-gpu==2.1.3.post110 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by wawltor** [comment]
> 2080ti

cudnn的版本是8.x吗？

**Comment by wht0948** [comment]
> > 2080ti
> 
> cudnn的版本是8.x吗？

torch.backends.cudnn.version()：7605

**Comment by wawltor** [comment]
> > > 2080ti
> > 
> > 
> > cudnn的版本是8.x吗？
> 
> torch.backends.cudnn.version()：7605

可以尝试提升一下cudnn的版本

**Comment by wht0948** [comment]
> > > > 2080ti
> > > 
> > > 
> > > cudnn的版本是8.x吗？
> > 
> > 
> > torch.backends.cudnn.version()：7605
> 
> 可以尝试提升一下cudnn的版本

这个不太方便，我的机器上能满足的最高版本paddle的安装命令能发一下吗？感谢

**Comment by wawltor** [comment]
可以尝试用conda来安装相应的环境，这个相对比较方便
<img width="797" alt="图片" src="https://user-images.githubusercontent.com/16698950/138396516-d163e6fd-ee95-4ea7-8e00-67a24f1dc68d.png">
https://www.paddlepaddle.org.cn/

**Comment by wht0948** [comment]
> 可以尝试用conda来安装相应的环境，这个相对比较方便 <img alt="图片" width="797" src="https://user-images.githubusercontent.com/16698950/138396516-d163e6fd-ee95-4ea7-8e00-67a24f1dc68d.png"> https://www.paddlepaddle.org.cn/

你发我的这个cuda版本和我机器不一样也可以装吗？我选cuda11.0上面显示conda不支持

**Comment by wawltor** [comment]
您好，可以使用的，上面的方式在指定的conda环境中去安装一个cuda版本，同时也不会干扰其他的python环境，按照我的截图安装即可。不过建议新增一个conda环境哈，避免干扰其他环境。
