### ISSUE TITLE
Wrong cross_entropy_loss computation in the text_matching example

### ISSUE THREAD

**Issue by lingyongyan** [PaddlePaddle/PaddleNLP#1204]
开发者你好，
我在参考你们的example代码的时候，发现text_matching的示例中，cross entropy loss的计算有点问题。
按照官网的介绍，paddle.nn.CrossEntropyLoss的输入应当是logits和label，但是示例中给的是probs。
我在ernie_matching 和sentence_transformers 两个示例中均发现了这个问题。
 
https://github.com/PaddlePaddle/PaddleNLP/blob/27917453b598dec9791f692b0a72395a19ba95fe/examples/text_matching/ernie_matching/model.py#L40

https://github.com/PaddlePaddle/PaddleNLP/blob/27917453b598dec9791f692b0a72395a19ba95fe/examples/text_matching/ernie_matching/train_pointwise.py#L166

**Comment by tianxin1860** [comment]
> 开发者你好， 我在参考你们的example代码的时候，发现text_matching的示例中，cross entropy loss的计算有点问题。 按照官网的介绍，paddle.nn.CrossEntropyLoss的输入应当是logits和label，但是示例中给的是probs。 我在ernie_matching 和sentence_transformers 两个示例中均发现了这个问题。
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/27917453b598dec9791f692b0a72395a19ba95fe/examples/text_matching/ernie_matching/model.py#L40
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/27917453b598dec9791f692b0a72395a19ba95fe/examples/text_matching/ernie_matching/train_pointwise.py#L166

感谢指出这个问题，非常欢迎提 PR 参与 PaddleNLP 的建设，这个问题我们会尽快修复，请关注~
