### ISSUE TITLE
ernie-1.0报错，make相关问题求助。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#1208]
您好，在进行ernie-1.0预训练过程中，出现ModuleNotFoundError: No module named 'data_tools.helpers'的情况，请问是否是make失败？检查了makefile中的CPPFLAGS和LIBEXT，python路径设置没问题，并且pybind11包已安装，g++、make工具正常，请问应该如何解决呢？具体报错和makefile设置情况如下图所示，感谢您的帮助。
<img width="995" alt="ernie-1 0报错" src="https://user-images.githubusercontent.com/73834112/138203852-1a58dfb9-b712-4068-9ec1-c01e11e6e947.png">
<img width="821" alt="ernie-1 0make设置" src="https://user-images.githubusercontent.com/73834112/138203974-89ce761a-579f-4c6b-b8a3-527252831aff.png">

**Comment by ZHUI** [comment]
```
CXXFLAGS += -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color
CPPFLAGS += $(shell python3 -m pybind11 --includes)
LIBNAME = helpers
LIBEXT = $(shell python3-config --extension-suffix)

default: $(LIBNAME)$(LIBEXT)

%$(LIBEXT): %.cpp
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $< -o $@
```

这里的Makefile，上面的`CPPFLAGS` 的`python3`路径修改是对的，下面`LIBEXT`应该是`python3-config`而不是`python3`

**Comment by shaitaiyangmie** [comment]
> ```
> CXXFLAGS += -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color
> CPPFLAGS += $(shell python3 -m pybind11 --includes)
> LIBNAME = helpers
> LIBEXT = $(shell python3-config --extension-suffix)
> 
> default: $(LIBNAME)$(LIBEXT)
> 
> %$(LIBEXT): %.cpp
> 	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $< -o $@
> ```
> 
> 这里的Makefile，上面的`CPPFLAGS` 的`python3`路径修改是对的，下面`LIBEXT`应该是`python3-config`而不是`python3`

您好，感谢您的回复，我将LIBEXT 后面改为了home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/bin/python-config，报错显示home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/bin/python-config: Command not found，结果仍然是make: Nothing to be done for 'default'.请问python3那里就是用which python查找到的当前应用的python的路径吧？

**Comment by ZHUI** [comment]
`whereis python`, 找一下`python-config`的位置，这个是我的结果
![image](https://user-images.githubusercontent.com/16911935/138237150-6377b992-85c4-4c93-9250-ca62bcbac3b4.png)

**Comment by shaitaiyangmie** [comment]
> `whereis python`, 找一下`python-config`的位置，这个是我的结果 ![image](https://user-images.githubusercontent.com/16911935/138237150-6377b992-85c4-4c93-9250-ca62bcbac3b4.png)
谢谢您！

**Comment by ZHUI** [comment]
不客气哈

**Comment by safehumeng** [comment]
我make之后生成的是helpers.cpython-36m-x86_64-linux-gnu.so，还是找不到，cp helpers.cpython-36m-x86_64-linux-gnu.so helpers.so之后能找到了

**Comment by ZHUI** [comment]
> 我make之后生成的是helpers.cpython-36m-x86_64-linux-gnu.so，还是找不到，cp helpers.cpython-36m-x86_64-linux-gnu.so helpers.so之后能找到了

出现这个情况，一般原因是 python-config 的版本，与使用的python 版本不一致导致的。您可以check一下版本

**Comment by safehumeng** [comment]
> python3-config

好的，谢谢啦

**Comment by safehumeng** [comment]
> > 我make之后生成的是helpers.cpython-36m-x86_64-linux-gnu.so，还是找不到，cp helpers.cpython-36m-x86_64-linux-gnu.so helpers.so之后能找到了
> 
> 出现这个情况，一般原因是 python-config 的版本，与使用的python 版本不一致导致的。您可以check一下版本

好的，谢谢啦
