### ISSUE TITLE
[Ask]关于对话上下文中的意图理解和槽位填充

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1209]
Hi, Team，

想确认一下关于对话上下文中的意图理解和槽位填充这两个领域， 有没有相关的模型实现参考，谢谢！

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/dgu
可以看看这个repo，基本都是基于预训练的finetune来完成。@LangDaoAI

**Comment by LangDaoAI** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/dgu 可以看看这个repo，基本都是基于预训练的finetune来完成。@LangDaoAI

我确认一下dgu是否有这两个场景
