### ISSUE TITLE
使用文本分类任务时自己的准备的样本在加载时被替换成官方样本(train.tsv, dev.tsv, dev.tev)怎么破,求指导

### ISSUE THREAD

**Issue by yizhipipixia** [PaddlePaddle/PaddleNLP#121]
项目链接:https://github.com/PaddlePaddle/models/tree/4d87afd6480737b64b5974c9c40a5b1c5a4600b3/PaddleNLP/examples/text_classification/rnn

加载的时候是从train.py的这里进去的(但是里面调的类有点复杂,就不知道怎么改了)
    train_ds, dev_ds, test_ds = ChnSentiCorp.get_datasets(
        ['train', 'dev', 'test'])

![11](https://user-images.githubusercontent.com/65219051/103256610-d7ef4080-49c8-11eb-8a4f-a30256b4ef0f.png)

**Comment by chenxiaozeng** [comment]
你好，请问这个问题，解决了吗？

**Comment by chenxiaozeng** [comment]
@yizhipipixia 您好，请问这个问题，解决了吗
