### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa实体识别案例咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1210]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa 目前这个案例是针对文本分类的，有没有这个类似针对实体识别的案例，如果要改成实体识别应该怎么更改？

**Comment by LiuChiachi** [comment]
建议你先简单看下readme了解一下大致流程，二者是类似的问题，都是下游任务，把分类相关的换成实体识别的就行了。比如用到的class替换成实体识别的class，数据集替换成实体识别的数据集，teacher模型也需要训一个实体识别的模型。

**Comment by AI-Mart** [comment]
好的，谢谢，只是换成实体的模型，底层包都是支持的那就好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa实体识别案例咨询 (Issue #1210)





 
建议你先简单看下readme了解一下大致流程，二者是类似的问题，都是下游任务，把分类相关的换成实体识别的就行了。比如用到的class替换成实体识别的class，数据集替换成实体识别的数据集，teacher模型也需要训一个实体识别的模型。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
