### ISSUE TITLE
关于LIC 2021对话比赛baseline的数据集

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1211]
Hi Team,

LIC 2021对话比赛baseline的数据集没有开放， 该比赛已经结束了几个月， 是不能集成到paddlenlp还是其他原因， 没有数据集， 这个示例没有办法参考，

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/lic2021_baseline

另外千言站点也没有公开该数据集

**Comment by ZeyuChen** [comment]
https://aistudio.baidu.com/aistudio/competition/detail/48/0/datasets
你在千言的那个比赛上报名一下，就能获得数据。数据暂时对报名选手公开。
![image](https://user-images.githubusercontent.com/1371212/138306087-8d676bb2-9531-45c9-bdd6-c26b7dd364d9.png)

**Comment by LangDaoAI** [comment]
> https://aistudio.baidu.com/aistudio/competition/detail/48/0/datasets 你在千言的那个比赛上报名一下，就能获得数据。数据暂时对报名选手公开。 ![image](https://user-images.githubusercontent.com/1371212/138306087-8d676bb2-9531-45c9-bdd6-c26b7dd364d9.png)

好的，希望能够尽快把数据整合进来

**Comment by LangDaoAI** [comment]
> https://aistudio.baidu.com/aistudio/competition/detail/48/0/datasets 你在千言的那个比赛上报名一下，就能获得数据。数据暂时对报名选手公开。 ![image](https://user-images.githubusercontent.com/1371212/138306087-8d676bb2-9531-45c9-bdd6-c26b7dd364d9.png)

好的，希望能够尽快把数据整合进来

**Comment by chenxiaozeng** [comment]
Issue close. If you have other questions, please feel free to reopen it.
