### ISSUE TITLE
paddlenlp/taskflow/text_correction.py 代码好像不对

### ISSUE THREAD

**Issue by max123ios** [PaddlePaddle/PaddleNLP#1221]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlenlp的version是2.0.0

报错： name 'max_seq_length' is not defined
opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/text_correction.py in _parse_decode(self, words, corr_preds, det_preds, lengths)
    310         rest_words = []
    311         if len(words) > self._max_seq_length - 2:
--> 312             rest_words = words[max_seq_length - 2:]
    313             words = words[:self._max_seq_length - 2]
查看源码，好像确实没有max_seq_length的定义，感觉应该是self._max_seq_length

**Comment by joey12300** [comment]
@max123ios 目前已经提了一个修复的PR：https://github.com/PaddlePaddle/PaddleNLP/pull/1225。除了提供bug信息以外，非常欢迎您给PaddleNLP贡献bug修复代码~
