### ISSUE TITLE
预训练加入layer_norm层后模型参数变为nan

### ISSUE THREAD

**Issue by wht0948** [PaddlePaddle/PaddleNLP#1222]
在使用plato-2进行预训练时，发现模型参数变为了nan，调试后发现lm_head层中只要一加入layer_norm层，模型第一次反向传播之后参数就会变成nan，如下图红框所示，如果注释掉就可以正常训练，请问是什么原因？
![image](https://user-images.githubusercontent.com/32132519/138550170-c25e7d82-4106-4404-b847-cefd5bc1929d.png)

**Comment by smallv0221** [comment]
您好，报错信息需要复现代码，请提供最小可复现代码和环境信息，我们复现后会尽快回复您～
