### ISSUE TITLE
【论文复现】paddlenlp.transformers.BertModel中的attention_mask

### ISSUE THREAD

**Issue by zhoucz97** [PaddlePaddle/PaddleNLP#1224]
文档中是这么说的：
*It is a tensor with shape broadcasted to `[batch_size, num_attention_heads, sequence_length, sequence_length]`. Defaults to `None`, which means nothing needed to be prevented attention to.*

看完这句话以为输入维度要 `[batch_size, num_attention_heads, sequence_length, sequence_length]`才行。

然而看了源码发现如果不给出`attention_mask`，那么模型初始化的`attention_mask`维度是`[batch_size, 1, 1, sequence_length]`，如下面代码：

```
if attention_mask is None:
    attention_mask = paddle.unsqueeze(
        (input_ids == self.pad_token_id
         ).astype(self.pooler.dense.weight.dtype) * -1e9,
        axis=[1, 2])
```

经过自己测试发现，输入的attention_mask维度为`[batch_size, 1, 1, sequence_length]`，没有问题。

所以是文档写错了？？？

**Comment by yingyibiao** [comment]
您好，感谢您的问题。这里的意思是attention_mask参数支持广播(broadcasting)机制：只要能够通过广播机制后得到形状为 [batch_size, num_attention_heads, sequence_length, sequence_length] 的tensor就支持传给attention_mask。
例如上述的 [batch_size, 1, 1, sequence_length] 可以通过广播机制后得到 [batch_size, num_attention_heads, sequence_length, sequence_length] 。
广播机制介绍可以参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/broadcasting_cn.html#broadcasting

**Comment by zhoucz97** [comment]
> 您好，感谢您的问题。这里的意思是attention_mask参数支持广播(broadcasting)机制：只要能够通过广播机制后得到形状为 [batch_size, num_attention_heads, sequence_length, sequence_length] 的tensor就支持传给attention_mask。 例如上述的 [batch_size, 1, 1, sequence_length] 可以通过广播机制后得到 [batch_size, num_attention_heads, sequence_length, sequence_length] 。 广播机制介绍可以参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/broadcasting_cn.html#broadcasting
明白了，我英文水平的问题hhh，没读懂那句话的意思。个人建议官方的BERT使用例子可以给一些带attention_mask的。
个人建议，仅供参考
非常感谢回复~~

**Comment by yingyibiao** [comment]
> 您好，感谢您的问题。这里的意思是attention_mask参数支持广播(broadcasting)机制：只要能够通过广播机制后得到形状为 [batch_size, num_attention_heads, sequence_length, sequence_length] 的tensor就支持传给attention_mask。 例如上述的 [batch_size, 1, 1, sequence_length] 可以通过广播机制后得到 [batch_size, num_attention_heads, sequence_length, sequence_length] 。 广播机制介绍可以参考： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/01_paddle2.0_introduction/basic_concept/broadcasting_cn.html#broadcasting
> 明白了，我英文水平的问题hhh，没读懂那句话的意思。个人建议官方的BERT使用例子可以给一些带attention_mask的。
> 个人建议，仅供参考
> 非常感谢回复~~

好的，感谢您的建议，我们补上例子～
