### ISSUE TITLE
emotion_detection 运行ernie evaluate报错

### ISSUE THREAD

**Issue by zhangxuanaj** [PaddlePaddle/PaddleNLP#123]
models/PaddleNLP/emotion_detection/run_ernie.sh   train完成后，运行eval报错，看报错信息，应该是在fluid.load(main_program, init_checkpoint_path, exe) 的时候出错了，error信息：

Error: When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::dims, or Tensor::Resize has been called first. The Tensor's shape is [-1, 768] now
  [Hint: Expected numel() >= 0, but received numel():-768 < 0:0.] at (/paddle/paddle/fluid/framework/tensor.cc:45)

**Comment by chenxiaozeng** [comment]
升级最新版本PaddleNLP即可～
