### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by caixu23** [PaddlePaddle/PaddleNLP#1230]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

PaddlePaddle2.1  , windows ,py3.7
执行
poetry = Taskflow("poetry_generation")
poetry("林密不见人")

显存充足，但是任然报:

Out of memory error on GPU 0. Cannot allocate 100.000244MB memory on GPU 0, 1.204346GB memory has been allocated and available memory is only 4.795654GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

**Comment by wawltor** [comment]
您好，poetry_generation这个模型相对比较大，需要16G的内存和显存的，辛苦check一下机器的内存、显存情况了

**Comment by applepieiris** [comment]
> 您好，poetry_generation这个模型相对比较大，需要16G的内存和显存的，辛苦check一下机器的内存、显存情况了

您好，我在使用命名实体识别模型的时候也遇到了相同的问题，请问开展命名实体识别的任务需要多大的显存呢？
