### ISSUE TITLE
BertTokenizer处理[MASK]问题

### ISSUE THREAD

**Issue by zhoucz97** [PaddlePaddle/PaddleNLP#1231]
您好，在使用过程中我发现`paddlenlp.BertTokenizer` 好像没有办法处理`[MASK]`, 下面是`BertTokenizer.__init__`中的三行代码，经测试发现，`self.basic_tokenizer`会把`[MASK]`切成`[`,`MASK`,`]`三部分，`self.wordpiece_tokenizer`会进一步切成`[`,`MA`, `##S`, `##K`,`]`五部分，即使`self.vocab`中有`[MASK]`.

_self.vocab = self.load_vocabulary(vocab_file, unk_token=unk_token)
self.basic_tokenizer = BasicTokenizer(do_lower_case=do_lower_case)
self.wordpiece_tokenizer = WordpieceTokenizer(vocab=self.vocab, unk_token=unk_token)_

**Comment by JunnYu** [comment]
我看`BartTokenizer`支持了特殊字符的识别。第186行左右
https://github.com/PaddlePaddle/PaddleNLP/blob/f59de0f1b3646b027ce64f7e7c2959110f788a1f/paddlenlp/transformers/bart/tokenizer.py#L176-L202
感觉可以抄一抄改一改

**Comment by zhoucz97** [comment]
> 我看`BartTokenizer`支持了特殊字符的识别。第186行左右
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/f59de0f1b3646b027ce64f7e7c2959110f788a1f/paddlenlp/transformers/bart/tokenizer.py#L176-L202
> 
> 
> 感觉可以抄一抄改一改

好滴，感谢~~
