### ISSUE TITLE
TaskFlow在paddle的CPU版上可以多核预测吗？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#1232]
版本、环境信息
1）PaddleNLP 2.1.0，PaddlePaddle2.1.3
2）CentOS 7，python 3.6.5
3）64核CPU，无GPU，内存16G
复现信息
Taskflow(
'knowledge_mining',
model='wordtag',
batch_size=1,
max_seq_length=128,
linking=True)
业务上需要单个模型实例(内存限制，没法开多个模型实例)，单条语句输入(batch=1)，用CPU进行预测，发现只使用单核CPU，请问有办法修改配置调用多核吗？
之前提到过export OMP_NUM_THREADS=10开启多线程加速，但是实际预测效果上速度并没有提升，和单核单线程在1000条生产数据上的测试时间基本没有差距，基本在1.2s/条。

**Comment by wawltor** [comment]
> 版本、环境信息 1）PaddleNLP 2.1.0，PaddlePaddle2.1.3 2）CentOS 7，python 3.6.5 3）64核CPU，无GPU，内存16G 复现信息 Taskflow( 'knowledge_mining', model='wordtag', batch_size=1, max_seq_length=128, linking=True) 业务上需要单个模型实例(内存限制，没法开多个模型实例)，单条语句输入(batch=1)，用CPU进行预测，发现只使用单核CPU，请问有办法修改配置调用多核吗？ 之前提到过export OMP_NUM_THREADS=10开启多线程加速，但是实际预测效果上速度并没有提升，和单核单线程在1000条生产数据上的测试时间基本没有差距，基本在1.2s/条。

您好，目前Taskflow还不支持多进程或者多线程预测，我们觉得Taskflow支持多核预测是一个很好建议，我们会考虑在下一个版本支持这个功能。如果目前想支持Taskflow支持多核预测，可能自己先用multiprocess库来封装一下Taskflow接口进行多核预测

**Comment by Macxy2018** [comment]
好的
