### ISSUE TITLE
paddle ErnieForGeneration 离线加载预训练模型

### ISSUE THREAD

**Issue by lemonliu1992** [PaddlePaddle/PaddleNLP#1236]
import paddlenlp
from paddlenlp.transformers import ErnieForGeneration

model = ErnieForGeneration.from_pretrained("/Users/liumengyue01/Downloads/model")

![image](https://user-images.githubusercontent.com/31071704/138806840-1f9501eb-a878-4120-8a80-5bbb081c90d2.png)

debug之后发现file_id 这个是来自字典resource_files 的keys，file_id='model_config_file' ，但是这个在      model_config_file = resolved_resource_files.pop("model_config_file",None) 被删掉了，因此报错。

**Comment by ZHUI** [comment]
> import paddlenlp from paddlenlp.transformers import ErnieForGeneration
> 
> model = ErnieForGeneration.from_pretrained("/Users/liumengyue01/Downloads/model")
> 
> ![image](https://user-images.githubusercontent.com/31071704/138806840-1f9501eb-a878-4120-8a80-5bbb081c90d2.png)
> 
> debug之后发现file_id 这个是来自字典resource_files 的keys，file_id='model_config_file' ，但是这个在 model_config_file = resolved_resource_files.pop("model_config_file",None) 被删掉了，因此报错。

这里的model的话，是怎么save下来的？能看一下这个文件夹的大概目录结构吗？

**Comment by geoyee** [comment]
@ZHUI  同问，遇到这个问题，使用的paddlenlp 2.3.0rc0，模型是`ErnieForGeneration`，训练是可以训练的，保存使用的`save_pretrained`，结果如下

![image](https://user-images.githubusercontent.com/71769312/167113540-978e946a-bb4e-417b-8b93-d4aa61c5f004.png)

![image](https://user-images.githubusercontent.com/71769312/167113592-5d2c49bc-b6c8-451e-9e6d-7a2180c519ea.png)

然后加载参数，`tokenizer`是能加载的，但是模型就报错

``` python
from paddlenlp.transformers import ErnieForGeneration

model = ErnieForGeneration.from_pretrained("ernie_output")
```

![image](https://user-images.githubusercontent.com/71769312/167113808-7be92bd1-9ad4-41ca-a936-253df430fc0c.png)
