### ISSUE TITLE
whole word mask相关问题请求讲解。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#1239]
您好，请问ernie-1.0代码中的，在对数据进行whole word mask时，需要调用data tool中的data utils.py的create_masked_lm_predictions函数，我想请问，对中文文本而言源码中如何判断分词的词头信息呢？vocab_id_to_token_dict中的中文token若不是词头，是以##开始的吗？
期待您的回复，感谢。

**Comment by ZHUI** [comment]
> 您好，请问ernie-1.0代码中的，在对数据进行whole word mask时，需要调用data tool中的data utils.py的create_masked_lm_predictions函数，我想请问，对中文文本而言源码中如何判断分词的词头信息呢？vocab_id_to_token_dict中的中文token若不是词头，是以##开始的吗？ 期待您的回复，感谢。

对的，是这样判断的。https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/data_tools/dataset_utils.py#L217 
这里中文文本也是这样判断。

可以看 ernie-1.0 的vocab也是这么设计的。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/tokenizer.py#L77
