### ISSUE TITLE
GPTChineseTokenizer加载失败

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#1242]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.1.0，PaddlePaddle2.1.1
2）系统环境：Aistudio
- 复现信息：如为报错，请给出复现环境、复现步骤
```python
from paddlenlp.transformers import GPTChineseTokenizer
tokenizer = GPTChineseTokenizer.from_pretrained('gpt-cpm-large-cn')
print(tokenizer('欢迎使用百度飞桨！'))
"""
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/gpt/tokenizer.py in __init__(self, model_file, max_len, unk_token, bos_token, eos_token, eol_token)
    138         self.max_len = max_len if max_len is not None else int(1e12)
    139         mod = try_import("sentencepiece")
--> 140         self.sp = mod.SentencePieceProcessor(model_file=model_file)
    141         self.translator = str.maketrans(" \n", "\u2582\u2583")
    142 

TypeError: __init__() got an unexpected keyword argument 'model_file'
"""
```
问题：
- `SentencePieceProcessor`加载代码问题。
- `_tokenize` 出错 self.sp没有encode。
- `convert_ids_to_string` 出错 self.sp没有decode。

**Comment by ZHUI** [comment]
看起来像是 `sentencepiece` 版本的问题，可以提供一下 `sentencepiece` 版本吗？

**Comment by JunnYu** [comment]
sentencepiece   0.1.96

**Comment by ZHUI** [comment]
我本地也是`0.1.96`，看起来是有 `model_file` 参数的。你可以尝试重新安装一下`sentencepiece`。
```
>>> import sentencepiece
>>> help(sentencepiece.SentencePieceProcessor)
```
![image](https://user-images.githubusercontent.com/16911935/139081161-51f93968-fae7-408a-840c-2547246c334e.png)

**Comment by JunnYu** [comment]
我使用aistudio自带的0.1.85版本运行会报错，安装最新版本的就不会报错了。个人感觉应该需要检查包的版本

**Comment by ZHUI** [comment]
感谢反馈，https://github.com/PaddlePaddle/PaddleNLP/pull/1248 给GPT的readme添加了版本要求
