### ISSUE TITLE
调用预训练模型RoBERTa时报错 TypeError: sequence item 0: expected str instance, RobertaModel found

### ISSUE THREAD

**Issue by coder-yuzhiwei** [PaddlePaddle/PaddleNLP#1243]
PaddleNLP和PaddlePaddle版本
![image](https://user-images.githubusercontent.com/45504684/139038224-30907b6c-f0fd-4ecf-a49e-ad65ef3f680c.png)
系统环境：
Python 3.8.12
cuda11.2

代码只有两行：
```python
import paddlenlp as ppnlp
pretrained_model = ppnlp.transformers.RobertaPretrainedModel.from_pretrained('roberta-wwm-ext-large')
```
经过下载预训练模型后，就报了如下错误：
```
  File "D:\ProgramData\Anaconda3\envs\ppnlp\lib\site-packages\paddle\fluid\unique_name.py", line 51, in __call__
    return self.prefix + "_".join([key, str(tmp)])
TypeError: sequence item 0: expected str instance, RobertaModel found
```

**Comment by coder-yuzhiwei** [comment]
NeZhaPretrainedModel也报同样的错误
![image](https://user-images.githubusercontent.com/45504684/139177645-3f8199e6-b7fd-4549-a51a-3a5a54d9b0a7.png)

**Comment by yingyibiao** [comment]
您好，非常感谢您的提问。调用预训练模型RoBERTa的正确加载方式是
import paddlenlp as ppnlp
pretrained_model = ppnlp.transformers.RobertaModel.from_pretrained('roberta-wwm-ext-large')

RobertaPretrainedModel这个类是RoBERTa模型的抽象类，我们不直接使用这个类进行加载，而是使用对应的具体的类进行加载，比如RobertaModel，RobertaForSequenceClassification等。

**Comment by coder-yuzhiwei** [comment]
感谢你的解答，原来每个预训练模型都有举例。[paddlenlp transformer](https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.transformers.html)
