### ISSUE TITLE
[功能需求]多分类任务的F1计算（confusion matrix）

### ISSUE THREAD

**Issue by tanhanzhuo** [PaddlePaddle/PaddleNLP#1247]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle2.1.3
2）系统环境：无

问题描述：
目前版本好像只支持二分类任务的precision recall f1计算，缺少原生的多分类confusion matrix计算：
![cae18394024dca1f533cf555088a8d59](https://user-images.githubusercontent.com/92439758/139073447-41ef0adc-6cb0-496e-bfbf-be2d1b59d5f5.png)
![0e6520fad8d62251f9ee77f675b9254a](https://user-images.githubusercontent.com/92439758/139073489-98882d1d-02a4-4f69-8d26-6b408caeb9ce.png)

sklearn中的多分类f1:

import numpy as np
#三分类问题
trueY = np.matrix([[1,2,3,2,1,3,1,3,1,1,3,2,3,2]]).T
testY = np.matrix([[1,2,3,2,2,3,1,3,1,1,3,2,3,2]]).T
from sklearn.metrics import f1_score, precision_score, recall_score
F1 = f1_score(trueY, testY, average="macro")
print("sklearn-f1:", oriF1)

**Comment by skpig** [comment]
@ZeyuChen 我愿意尝试实现多分类指标计算，但是这个feature需要直接在paddlenlp.metrics中实现，还是在paddle.metrics中实现呢？

**Comment by ZeyuChen** [comment]
@skpig 可以在paddlenlp.metrics中实现即可，期待你的开源贡献 :)

**Comment by skpig** [comment]
@ZeyuChen 您好，paddlenlp是否有提供CONTRIBUTING.md之类的贡献指南呢，我好像在README中没有看到详细的说明。

**Comment by ZeyuChen** [comment]
Resolved by #1282
