### ISSUE TITLE
ernie-1.0 分布式训练策略、fleet相关问题求助。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#1261]
您好，有几个sharding和fleet相关问题想请教，望指点一二，感激不尽！
1、请问fleet.worker_num和fleet.worker_index分别指的是什么呢？是总gpu个数和当前gpu索引还是总机器数和当前机器的索引呢？
2、请问在分布式训练中，当pp和mp均设置为1，只考虑dp和sharding时，是否是将全量数据先分成dp_num份放入不同主机，再将不同主机当中的数据分成sharding_num份，放入同一个主机下的不同显卡呢？倘若采用单机多卡的话，数据将如何分配？
3、在数据采样时，通过data_info.rank的不同，将数据采样生成data_info.size生成个生成器放入不同gpu，其中data_info.rank和dp_rank\sharding_rank相关，请问dp_rank， sharding_rank又和device_rank(fleet.worker_index)相关，请问每次训练，调用静态图的时候fleet.worker_index会交替变化吗？徘徊于各个gpu之间？通过fleet.worker_index来反推数据应该储存在哪一块显卡上，请问这个逻辑成立吗？
4、请问global_batch_size和micro_batch_size之间的关系是什么呢？若只考虑sharding和dp，是否意味着num_sharding * num_dp * micro_batch_size应该等于global_batch_size？
5、请问run_static.sh中num_workers的设定又有什么含义，和fleet.worker_num有何区别和联系呢？
6、我们在得到num_index后，在定义dataloader的时候，会根据num_index不同，把数据采样成num_index份，再放入不同卡，我想问的是这个fleet.num_index每次会变化吗？我看代码没有找到它变化的地方，如果是2卡训练的话，我理解它应该是0，1交替变化的，这样才能分别采样数据，放入不同的卡，这个num_index是每次跑静态图都会变吗，还是什么原理？

问题比较多，给您添麻烦了，期待您的指教，感谢！

**Comment by ZHUI** [comment]
1. `fleet.worker_num, fleet.worker_index` 两者都是全局的。比如四台8卡机器，`worker_num=32 (4*8)`, `worker_index=0,1,2,...,31`. 这里的 `worker_index` 相当于每张卡的唯一编号。
2. 对于数据流，你可以看成`dp、sharding`是一样的，总共`dp*sharding`路数据，可以看作`dp=dp*sharding`全部数据并行。数据是全局的，根据`data_info.rank`去获取数据。
3. 多机多卡指定ip配置，`worker_index`每次都是一样的。其实不一样也没关系，因为数据是全局的，只要`worker_index`相同，这张卡上的数据就和之前一样。
4. 对的`global_batch_size  = num_sharding * num_dp * micro_batch_size`。只有sharding、dp的情况下，` num_sharding * num_dp`=卡数。
5. `num_workers`是DataLoader采样的进程数。与分布式策略无关。
6. 最后根据的是`data_info.rank`，当然也是`fleet.worker_index`算出来的。取数据交替变化？根据 rank去取数据，这里用的是[DistributedBatchSampler](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html#distributedbatchsampler)。 

数据是全局的，根据`data_info.rank`取获取就好了。

**Comment by shaitaiyangmie** [comment]
> 1. `fleet.worker_num, fleet.worker_index` 两者都是全局的。比如四台8卡机器，`worker_num=32 (4*8)`, `worker_index=0,1,2,...,31`. 这里的 `worker_index` 相当于每张卡的唯一编号。
> 2. 对于数据流，你可以看成`dp、sharding`是一样的，总共`dp*sharding`路数据，可以看作`dp=dp*sharding`全部数据并行。数据是全局的，根据`data_info.rank`去获取数据。
> 3. 多机多卡指定ip配置，`worker_index`每次都是一样的。其实不一样也没关系，因为数据是全局的，只要`worker_index`相同，这张卡上的数据就和之前一样。
> 4. 对的`global_batch_size  = num_sharding * num_dp * micro_batch_size`。只有sharding、dp的情况下，` num_sharding * num_dp`=卡数。
> 5. `num_workers`是DataLoader采样的进程数。与分布式策略无关。
> 6. 最后根据的是`data_info.rank`，当然也是`fleet.worker_index`算出来的。取数据交替变化？根据 rank去取数据，这里用的是[DistributedBatchSampler](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html#distributedbatchsampler)。
> 
> 数据是全局的，根据`data_info.rank`取获取就好了。
非常感谢您的解答，给您添麻烦了！

**Comment by ZHUI** [comment]
嗯，不客气。这里面分布式策略比较多。后续我们还要加强一下README说明文档。
