### ISSUE TITLE
关于 csc-ernie 预训练

### ISSUE THREAD

**Issue by nghuyong** [PaddlePaddle/PaddleNLP#1262]
您好，感谢开源了csc-ernie，根据readme的指引也确实可以复现readme中的结果

但是该工作非常重要的一点就是预训练模型MLM-phonetics，readme中提到不开源预训练好的MLM-phonetics参数，可以理解。请问是否可以开源，预训练部分的代码，训练参数，以及预训练数据的构建脚本？

另外，观察到在detect和correct均算了一个bert，这样计算量是不是相当于传统bert模型的一倍了？

再次感谢，期待您的回复

@joey12300 @ZeyuChen

**Comment by joey12300** [comment]
您好，感谢关注ernie-csc！针对预训练流程开源的问题，目前团队暂无计划开源预训练部分的代码，一旦开源会第一时间通知您；第二个问题，detect和correct均调用了ernie的`encoder部分`，并非整个ernie，所以计算量是比传统transformer模型大一点，但不到一倍。

**Comment by nghuyong** [comment]
感谢回复！！

**Comment by nghuyong** [comment]
@joey12300 
您好，论文中训练数据sighan14有6000+，但是实际应该只有3000+；请问你们使用的sighan是官网的数据集吗
![image](https://user-images.githubusercontent.com/16462374/139824370-99678543-2e7b-4989-9620-109230de35b1.png)

**Comment by joey12300** [comment]
你好，请问你是在什么地方看到3000+呢？我们是用sighan官网的数据，转成简体字版本的

**Comment by nghuyong** [comment]
[Chunk-based Chinese Spelling Check with Global Optimization](https://aclanthology.org/2020.findings-emnlp.184.pdf)
[Read, Listen, and See: Leveraging Multimodal Information Helps Chinese Spell Checking](https://aclanthology.org/2021.findings-acl.64.pdf)

以上论文都是3000+，并且我实际从官网下载了sighan14的数据也是3000+，官网地址 http://ir.itc.ntnu.edu.tw/lre/clp14csc.html

@joey12300

**Comment by nghuyong** [comment]
@joey12300 
再请教您一个问题，在预训练阶段，loss仅仅计算被mask/修改/替换成拼音的部分（类似MLM），还是整个句子（类似纠错）？
![image](https://user-images.githubusercontent.com/16462374/139916491-34195f23-cb64-4f8f-971b-f2e2ada0ad3c.png)

**Comment by joey12300** [comment]
@nghuyong 预训练loss实际上跟ERNIE的预训练的loss是一样的，区别只在于使用了除`[MASK]`以外的token进行mask（混淆字token、拼音token），修改mask策略只为了使预训练任务与Finetune任务更接近一些，提高Finetune模型的纠错能力

**Comment by nghuyong** [comment]
@joey12300 ERNIE的预训练的loss是仅仅计算MASK部分的loss，这里也是吗？还是计算全部token的loss，因为这里有替换的操作了

**Comment by chenxiaozeng** [comment]
@nghuyong 您好，根据你提出的需求，我们想进一步和您沟通下需求背景以及使用场景，以便更好得解答您的问题。这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
