### ISSUE TITLE
ernie_pyreader数据维度和padding方式不一致

### ISSUE THREAD

**Issue by zhangxuanaj** [PaddlePaddle/PaddleNLP#127]
ernie_pyreader读取数据要求batch内均为max_seq_len长，但是调用的padding.py是按照batch内最大长度进行padding的。

ernie_pyreader： PaddleNLP/shared_modules/models/representation/ernie.py
padding.py：PaddleNLP/shared_modules/preprocess/padding.py

**Comment by songzy12** [comment]
https://github.com/PaddlePaddle/models/pull/4790 解决了这个问题，应该可以关闭当前 issue？
