### ISSUE TITLE
[Ask]跨语言的预训练模型

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1272]
Hi team，

想确认一下目前是否有类似https://arxiv.org/pdf/2001.08210v2.pdf 的跨语言的预训练模型， 我们有比较强的海外NLP场景。

谢谢！

**Comment by LangDaoAI** [comment]
http://research.baidu.com/Blog/index-view?id=151  是否已经公开

**Comment by ZeyuChen** [comment]
预计月底会发布，Stay tune. @LangDaoAI

**Comment by LangDaoAI** [comment]
> 预计月底会发布，Stay tune. @LangDaoAI

Great News!

**Comment by LangDaoAI** [comment]
@ZeyuChen 目前发布计划有确定吗？

**Comment by ZeyuChen** [comment]
因为发布会时间推迟了，所以模型发布时间相应推迟了两周，如无意外会在12.12之前发布会。@LangDaoAI 
@gongel  FYI

**Comment by LangDaoAI** [comment]
> 因为发布会时间推迟了，所以模型发布时间相应推迟了两周，如无意外会在12.12之前发布会。@LangDaoAI @gongel FYI

好的，感谢！再问一下，目前这个模型相比之前paper发布时，是否有新的能力追加， 从最新XTREME cross-lingual understanding benchmark看， 文心-M似乎掉了一些，：）
