### ISSUE TITLE
Bi-GRU+CRF中的模型  model.fit出错

### ISSUE THREAD

**Issue by lightCraft2020** [PaddlePaddle/PaddleNLP#1274]
[『NLP经典项目集』09 ：基于Bi-GRU+CRF的快递单信息抽取](https://aistudio.baidu.com/aistudio/projectdetail/1317771)
其中，

model.fit(train_data=train_loader,
              eval_data=dev_loader,
              epochs=1,
              save_dir='./results',
              log_freq=1)
[运行到上面的代码出错，具体如下，也可参见[网址](https://aistudio.baidu.com/aistudio/projectdetail/1317771)的评论部分，好多人都遇到了。](https://aistudio.baidu.com/aistudio/projectdetail/1317771)

The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/1
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)/tmp/ipykernel_104/2945169422.py in <module>
      3               epochs=1,
      4               save_dir='./results',
----> 5               log_freq=1)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1493         for epoch in range(epochs):
   1494             cbks.on_epoch_begin(epoch)
-> 1495             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1496             cbks.on_epoch_end(epoch, logs)
   1497 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1800             if mode != 'predict':
   1801                 outs = getattr(self, mode + '_batch')(data[:len(self._inputs)],
-> 1802                                                       data[len(self._inputs):])
   1803                 if self._metrics and self._loss:
   1804                     metrics = [[l[0] for l in outs[0]]]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    939               print(loss)
    940         """
--> 941         loss = self._adapter.train_batch(inputs, labels)
    942         if fluid.in_dygraph_mode() and self._input_info is None:
    943             self._update_inputs()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    654         else:
    655             outputs = self.model.network.forward(
--> 656                 * [to_variable(x) for x in inputs])
    657 
    658         losses = self.model._loss(*(to_list(outputs) + labels))
/tmp/ipykernel_104/1923813182.py in forward(self, x, lens)
     24         output, _ = self.gru(embs)
     25         output = self.fc(output)
---> 26         _, pred = self.decoder(output, lens)
     27         return output, lens, pred
     28 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/layers/crf.py in forward(self, inputs, lengths)
    392         else:
    393             alpha = paddle.zeros((batch_size, self.num_tags), dtype='float32')
--> 394         for i, logit in enumerate(inputs_t[:max_seq_len]):
    395             # if not with_start_stop_tag, the first label has not antecedent tag.
    396             if i == 0 and not self.with_start_stop_tag:
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows None or integers in slice item, but received Tensor. (at /paddle/paddle/fluid/pybind/imperative.cc:337)

**Comment by joey12300** [comment]
@lightCraft2020 这应该是paddle版本问题，请更新paddle 2.1版本以上

**Comment by lightCraft2020** [comment]
嗯，现在正常了
