### ISSUE TITLE
TaskFlow的NER任务输出的tag有解释说明吗？

### ISSUE THREAD

**Issue by HuStanding** [PaddlePaddle/PaddleNLP#1277]
TaskFlow的NER任务输出的tag有解释说明吗？，我看有些输出的结果感觉有点模糊，可以具体说明下每个tag的含义吗？

**Comment by wawltor** [comment]
输出的Tag主要是我们通过对百度百科树的一些归纳得到一个这样的Tag体系，具体的Tag体系标准可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_to_knowledge/termtree/termtree_type.csv

**Comment by HuStanding** [comment]
> 输出的Tag主要是我们通过对百度百科树的一些归纳得到一个这样的Tag体系，具体的Tag体系标准可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_to_knowledge/termtree/termtree_type.csv

非常感谢~
