### ISSUE TITLE
调用 语义索引模型来计算两个文本的相对度，多线程耗时特别长!啥原因?

### ISSUE THREAD

**Issue by shguan2018** [PaddlePaddle/PaddleNLP#1281]
if __name__ == '__main__':
    
    text_list, text2similar_text,two_list = gen_text_file('./data/same_semantic.tsv')
    print(len(two_list))
    flags = ["********","############"]
    for query_text in two_list:
        query_array = query_text.split(',')
        #print(query_text)
        '''
                    启动 10个线程访问
        '''
        for i in range(10):
            #threadid=random.randint(0,9)
            targetid = random.randint(0,len(two_list))
            targetText = two_list[targetid]
            '''
                               线程里面调用语义索引模型来计算相似度(model_state.pdparams),判断两文本相似度
            '''
            thread1 = myThread(i,"Thread-"+str(targetid),query_array[0],targetText)
            thread1.start()
        #time.sleep(0.1) 
    print('退出主线程')

**Comment by tianxin1860** [comment]
您好，请问是基于 CPU 在做预测吗？

**Comment by shguan2018** [comment]
谢谢, 使用 GPU 也不快，如果用一个线程耗时还可以接受,如果开启多个线程,耗时就成倍增加,没法用了,

**Comment by tianxin1860** [comment]
> 谢谢, 使用 GPU 也不快，如果用一个线程耗时还可以接受,如果开启多个线程,耗时就成倍增加,没法用了,
看你的代码是在 1 张 GPU 卡上用多线程？建议采用多卡多进程的方式来提升预测速度。

**Comment by tianxin1860** [comment]
看你的代码是在 1 张 GPU 卡上用多线程？建议采用每张 GPU 卡启动1个进程的方式来提升预测速度。

**Comment by shguan2018** [comment]
谢谢，我测试一下
