### ISSUE TITLE
能否做一个 semantic_index 生成的语义模型,然后在  paddle serving 上部署的例子

### ISSUE THREAD

**Issue by shguan2018** [PaddlePaddle/PaddleNLP#1286]
能否做一个 semantic_index 生成的语义模型,然后在  paddle serving 上部署的例子

**Comment by tianxin1860** [comment]
> 能否做一个 semantic_index 生成的语义模型,然后在 paddle serving 上部署的例子

您好，语义索引模型的工业级部署能力我们正在开发中，后续会开放出来，欢迎关注。

**Comment by shguan2018** [comment]
谢谢,希望尽快能用到

**Comment by wj-Mcat** [comment]
现在 PaddleNLP 中已经添加了 semantic_index 模块，详细可见：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/semantic_indexing/README.md

**Comment by shguan2018** [comment]
谢谢

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/in_batch_negative

paddle serving部署的示例，参考neural search
