### ISSUE TITLE
Bug Report: NameError: name 'TestElectraForSequenceClassification' is not defined

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#1305]
## Introduction

* paddle version: `2.2.0`
* macos
* python3.9
* ide: vscode
* test plugin: [Python Test Explorer for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter)

## Error Message

```shell
Failed to import test module: transformers.gpt.test_modeling
Traceback (most recent call last):
  File "/home/wj-Mcat/miniconda3/envs/paddle/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/wj-Mcat/miniconda3/envs/paddle/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/wj-Mcat/projects/paddle/PaddleNLP/tests/transformers/gpt/test_modeling.py", line 84, in <module>
    class TestGPTForTokenClassification(TestElectraForSequenceClassification):
NameError: name 'TestElectraForSequenceClassification' is not defined
```
## Reproduce

This is the abvious error which does't need to reproduce it: there is no `TestElectraForSequenceClassification` importing in `tests/transformers/gpt/test_modeling.py` file.  So it throws the NameError issue in testing panel.  

Although there is no error been thrown at runtime, but it's also a linting error which should be fixed. How do you think about it ?

**Comment by ZeyuChen** [comment]
@wj-Mcat Thanks for your feedbacks!

**Comment by ZeyuChen** [comment]
Resolve by #1306
