### ISSUE TITLE
PaddleNLP特定领域分词不准确问题

### ISSUE THREAD

**Issue by supercoderhawk** [PaddlePaddle/PaddleNLP#1316]
PaddleNLP: 2.1.1
PaddlePaddle: 2.1.3

```python
text = "短效GLP-1受体激动剂有阿斯利康的艾塞那肽、诺和诺德的利拉鲁肽、赛诺菲的利司那肽和上海仁会生物的贝那鲁肽。"
tag = Taskflow("pos_tagging")    
print(tag(text))
```

`[('短效', 'n'), ('GLP-1', 'nz'), ('受体', 'n'), ('激动剂', 'n'), ('有', 'v'), ('阿斯利康', 'ORG'), ('的', 'u'), ('艾塞', 'PER'), ('那', 'r'), ('肽', 'n'), ('、', 'w'), ('诺和', 'n'), ('诺德', 'PER'), ('的', 'u'), ('利拉鲁肽', 'nz'), ('、', 'w'), ('赛诺菲', 'ORG'), ('的', 'u'), ('利司', 'n'), ('那', 'r'), ('肽', 'n'), ('和', 'c'), ('上海仁', 'ORG'), ('会', 'v'), ('生物', 'n'), ('的', 'u'), ('贝', 'n'), ('那鲁肽', 'r'), ('。', 'w')]`

正确的应为:
`[('短效', 'n'), ('GLP-1', 'nz'), ('受体', 'n'), ('激动剂', 'n'), ('有', 'v'), ('阿斯利康', 'ORG'), ('的', 'u'), ('艾塞那肽', 'nz'), ('、', 'w'), ('诺和诺德', 'ORG'), ('的', 'u'), ('利拉鲁肽', 'nz'), ('、', 'w'), ('赛诺菲', 'ORG'), ('的', 'u'), ('利司那肽', 'nz'), ('和', 'c'), ('上海仁会生物', 'ORG'), ('的', 'u'), ('贝那鲁肽', 'nz'), ('。', 'w')]`

在此例子中, 只考虑分词, 准确率仅为51.7%,召回率为71.4%. 
在医药相关的新闻中, 类似例子的错误屡见不鲜.

**Comment by ZeyuChen** [comment]
@supercoderhawk 你试试综合下Taskflow('ner')这个解语模型的结果看看，可能一些生物类的准确率会高不少。

**Comment by supercoderhawk** [comment]
恩, 是准了不少, 但是还是有一个错误的. `艾塞那肽` 还是没有识别出来. 我先用ner这个好了

**Comment by ZeyuChen** [comment]
@supercoderhawk 您是学生还是企业开发者呢？您的这个场景用于解决什么问题，可否交流下。

**Comment by supercoderhawk** [comment]
企业开发者, 我们开发的新产品需要, 具体可以通过邮箱讨论, supercoderhawk@gmail.com

**Comment by ZeyuChen** [comment]
@supercoderhawk 好的。@chenxiaozeng 请跟进下

**Comment by lx1054331851** [comment]
@ZeyuChen 您好，我是纺织服装领域的，发现Taskflow在我们这个领域的分词效果也不是很好，如何能选择预训练模型，或者是我用自己的数据做一些微调呢？

**Comment by linjieccc** [comment]
@lx1054331851 你好，可以参考这里的增量训练示例定制自己的分词模型

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/ernie-ctm

**Comment by lx1054331851** [comment]
@linjieccc 好的，谢谢，我试试。
