### ISSUE TITLE
PaddleNLP/examples/dialogue/dgu/中对话状态管理dst和意图识别和槽填充如何结合？

### ISSUE THREAD

**Issue by conquer66666** [PaddlePaddle/PaddleNLP#1323]
请问对话状态管理和意图槽位等怎么结合使用？map_tag_id中值表示意图，槽位的一个名称还是什么？请帮解释一下，谢谢

**Comment by smallv0221** [comment]
The tags in `map_tag_id` means the current state of current conversation. They are cumulative during the conversation. DST and intents are both parts of a pipline dialogue system. You can see the lecture here for more information. https://www.bilibili.com/video/BV1fB4y1M7A3?p=19

**Comment by conquer66666** [comment]
谢谢，我再研究一下
