### ISSUE TITLE
nptag报错：The model name:nptag is not in task:[knowledge_mining]

### ISSUE THREAD

**Issue by funwoo0415** [PaddlePaddle/PaddleNLP#1331]
![image](https://user-images.githubusercontent.com/75667328/142357558-9ae15d56-7eaa-4833-8372-16e9ec456a7f.png)
windows，

另外，说明文档里是不是写错了？
![image](https://user-images.githubusercontent.com/75667328/142357779-edf0c50f-fb82-447d-a346-c96e8a80af2c.png)

**Comment by wawltor** [comment]
这个需要手动安装一下最新的develop PaddleNLP版本

**Comment by linjieccc** [comment]
@funwoo0415 感谢指出，我们修改下

**Comment by linjieccc** [comment]
Taskflow NPTag会在PaddleNLP2.1.2正式发布，预计是在这个月月底

**Comment by ZeyuChen** [comment]
月底是PaddleNLP 2.2哈

**Comment by funwoo0415** [comment]
感谢各位的解答，还想请教一个问题：
nptag和ner的分词结果有什么不同吗？是将ner中的名词都挑出来，再精细化一下？ @ZeyuChen @wawltor  @linjieccc

**Comment by linjieccc** [comment]
@funwoo0415 NPTag是专门针对名词短语的标注工具，包含2000+的细粒度名词短语类别。
NPTag不会对输入文本进行分词，而是直接预测其类别。
所以从输入角度看，NPTag要求输入是完整的名词短语，而ner任务的输入则是一个完整的中文句子了。

**Comment by chenpe32cp** [comment]
老师好，请问如果名词短语的类别数目扩展到两万+，请问该方法是否适用呢

**Comment by linjieccc** [comment]
你好，请问具体希望应用到什么场景中呢？
如果名词短语类别都有对应标注好的样本的话，可以参考这个示例在自己的样本集上进行增量训练，定制自己版本的NPTag：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/nptag
