### ISSUE TITLE
PaddleNLP/examples/information_extraction/DuIE/官方F1只有69.42的原因

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1332]
在训练过程中，模型保存在当前目录checkpoints文件夹下。同时在训练的同时使用官方评测脚本进行评估，输出P/R/F1指标。 在验证集上F1可以达到69.42。

官方源码，是把关系抽取模型转换为多标签的分类模型，正常的分类模型官方的F1值只有69.42的原因是什么？为何会这么低呢，一般普通的分类模型，随便一个预训练模型都能达到90以上，这个关系抽取转换的分类模型F1这么低的原因，能详细说下吗？

**Comment by ZeyuChen** [comment]
这个数据任务难度比较大，还是比较复杂的。

**Comment by AI-Mart** [comment]
要提升准确率的话，是要换模型方案吗？
