### ISSUE TITLE
text-to-sql 多卡训练报错

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/PaddleNLP#1334]
您好，在使用text-sql的代码训练nl2sql数据集，使用了多卡，在conf/text2sql_nl2sql.jsonnet中的use_data_parallel 设置为true,报错如下：
![4088288C-85B9-41b6-92B6-52AA37476B5A](https://user-images.githubusercontent.com/33194029/142395422-e6ca271f-e768-4ee3-b173-3db4cdfae9a3.png)

1）PaddleNLP和PaddlePaddle版本：PaddleNLP==2.1.0，paddlepaddle-gpu==2.1.3.post112
2）系统环境：ubuntuUbuntu 16.04.7 ，python==3.7，
      显卡型号为2080Ti 和3080Ti， cuda==11.2
代码地址为https://github.com/PaddlePaddle/Research/tree/master/NLP/Text2SQL-BASELINE，多卡训练报错如何修改？

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL

试试这个版本的代码？

**Comment by Xuanfang1121** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL
> 
> 试试这个版本的代码？
好的，我先试试

**Comment by Xuanfang1121** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL
> 
> 试试这个版本的代码？
您好，使用了https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL的代码，在text2sql下的global_config.py中设置--use-data-parallel设置为True，多卡训练报错如下
![image](https://user-images.githubusercontent.com/33194029/142561141-27058abd-7019-4d31-bd2c-e77ce9a9a46e.png)


如果在text2sql_main.py中添加指定显卡的代码
os.environ['FLAGS_eager_delete_tensor_gb'] = "0.0"
os.environ["CUDA_VISIBLE_DEVICES"] = '0,1'
模型训练卡住不动，如下图：
![image](https://user-images.githubusercontent.com/33194029/142561415-c2d9555d-76d4-4319-beba-6a5686b27559.png)
显卡使用情况如下：
![image](https://user-images.githubusercontent.com/33194029/142561517-977255b9-9cf1-4ed1-a988-499249ae024e.png)

想使用多卡进行训练，该如何设置代码，谢谢

**Comment by wawltor** [comment]
![图片](https://user-images.githubusercontent.com/16698950/142586108-acfa563d-cbc8-4119-ab84-5dd63e44787a.png)
这里需要设置一下并发数

**Comment by Xuanfang1121** [comment]
> ![图片](https://user-images.githubusercontent.com/16698950/142586108-acfa563d-cbc8-4119-ab84-5dd63e44787a.png) 这里需要设置一下并发数
您好，我设置了并发为2 ，执行命令如下：bash ./train.sh 2 output/ --config conf/text2sql_nl2sql.jsonnet --data-root data/NL2SQL/preproc
显卡使用如下：
![image](https://user-images.githubusercontent.com/33194029/142595533-81ea5fdf-b42c-4522-afc9-f03d23900b79.png)

如果修改conf/text2sql_nl2sql.jsonnet 中的**use_data_parallel: true**, 执行命令为bash ./train.sh 2 output/ --config conf/text2sql_nl2sql.jsonnet --data-root data/NL2SQL/preproc
报错如下：
![image](https://user-images.githubusercontent.com/33194029/142595914-7602ce50-a097-411f-b073-2332f4097d68.png)
