### ISSUE TITLE
NameError: name 'BertForMaskedLM' is not defined

### ISSUE THREAD

**Issue by HUAWilliam** [PaddlePaddle/PaddleNLP#1335]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.1.1，PaddlePaddle 2.1.3
2）系统环境：windows & linux 均有这个bug
- 
- Traceback (most recent call last):
  File "d:/Objects/temp/NER/main.py", line 19, in <module>
    from model import *
  File "d:\Objects\temp\NER\model.py", line 3, in <module>
    class BertMaskedModel(BertForMaskedLM):
 NameError: name 'BertForMaskedLM' is not defined
- 
![image](https://user-images.githubusercontent.com/29301643/142407442-ba141237-357f-41c1-92c9-143747825a1b.png)

**Comment by ZeyuChen** [comment]
试试头部加一下from paddlenlp.transformers import BertForMaskedLM

**Comment by HUAWilliam** [comment]
Traceback (most recent call last):
&nbsp; File "d:/Objects/temp/NER/main.py", line 19, in <module&gt;
&nbsp; &nbsp; from model import *
&nbsp; File "d:\Objects\temp\NER\model.py", line 2, in <module&gt;
&nbsp; &nbsp; from paddlenlp.transformers import BertForMaskedLM
ImportError: cannot import name 'BertForMaskedLM' from 'paddlenlp.transformers' (C:\Users\William\miniconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\__init__.py)



from paddlenlp.transformers import *
from paddlenlp.transformers import BertForMaskedLM

class BertMaskedModel(BertForMaskedLM):






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月18日(星期四) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] NameError: name 'BertForMaskedLM' is not defined (Issue #1335)





 
试试头部加一下from paddlenlp.transformers import BertForMaskedLM
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HUAWilliam** [comment]
加了也不好使啊
- Traceback (most recent call last):
  File "d:/Objects/temp/NER/main.py", line 19, in <module>
    from model import *
  File "d:\Objects\temp\NER\model.py", line 2, in <module>
    from paddlenlp.transformers import BertForMaskedLM
ImportError: cannot import name 'BertForMaskedLM' from 'paddlenlp.transformers' (C:\Users\William\miniconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\__init__.py)
- 而且这个bug在AIstudio上也能复现，估计是你们写的__init__漏了东西。

**Comment by HUAWilliam** [comment]
> 试试头部加一下from paddlenlp.transformers import BertForMaskedLM

加了也不好使啊

- Traceback (most recent call last):
File "d:/Objects/temp/NER/main.py", line 19, in
from model import *
File "d:\Objects\temp\NER\model.py", line 2, in
from paddlenlp.transformers import BertForMaskedLM
ImportError: cannot import name 'BertForMaskedLM' from 'paddlenlp.transformers' (C:\Users\William\miniconda3\envs\paddle\lib\site-packages\paddlenlp\transformers_init_.py)
- 而且这个bug在AIstudio上也能复现，估计是你们写的__init__漏了东西。

**Comment by yingyibiao** [comment]
您好，感谢您的issue，BertForMaskedLM这个类是最近新增的，目前PaddleNLP还没有发布包含这个类的release版本。如果您需要使用BertForMaskedLM，那么需要下载PaddleNLP源码进行安装。

**Comment by ZeyuChen** [comment]
请尝试clone paddlenlp最新代码，本地执行setup.py安装即可解决该问题。@HUAWilliam
