### ISSUE TITLE
text-to-sql中的max-seq-len问题

### ISSUE THREAD

**Issue by Xuanfang1121** [PaddlePaddle/PaddleNLP#1337]
您好，在使用text-to-sql中的RAT-SQL代码，数据集为NL2SQL，其中为conf/text2sql_nl2sql.jsonnet中的max_seq_len由原来的510修改为254或者其他长度，并且修改了text2sql/dataproc/dataloader.py中的第45行 if orig_input.value_indexes[-1] > 510: 将510修改为254或者其他长度，与max_seq_len保持一致，代码会报错，报错如下：
Error: /paddle/paddle/fluid/operators/gather.cu.h:62 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [254] and greater or equal to 0, but received [0]
环境如下：
1）PaddleNLP和PaddlePaddle版本：PaddleNLP==2.1.0;paddlepaddle-gpu==2.1.3.post112
2）系统环境：ubuntu 16.04 python版本为3.7

text-to-sql的最大长度只能是510吗？这个长度问题该如何解决在nl2sql数据集上，batch size=16，预训练模型为ernie-1.0，至少需要多大的显存？谢谢

**Comment by wawltor** [comment]
想问一下，训练到多少epoch的时候会有这个问题了？

**Comment by wawltor** [comment]
> 想问一下，训练到多少epoch的时候会有这个问题了？

您好，排查了你的配置修改和代码中max_seq_len要对齐，因为配置中是254，则需要把 if orig_input.value_indexes[-1] > 252（你的代码是254），才可以，因为后面后有2个特殊字符进行Concat  @Xuanfang1121

**Comment by Xuanfang1121** [comment]
嗯嗯，收到，修改为512是可以进行训练的，谢谢您的回复，非常感谢
