### ISSUE TITLE
关系抽取模型不全面

### ISSUE THREAD

**Issue by Clearloveplus7** [PaddlePaddle/PaddleNLP#1339]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

能否提供一个好一点的关系抽取模型，这个demo的无法解决真正的带有关系的判别

**Comment by Steffy-zxf** [comment]
@Clearloveplus7你好！是否能够提供更详细的背景说明呢，方便定位目前我们提供demo不足之处。

**Comment by AI-Mart** [comment]
![image](https://user-images.githubusercontent.com/63343847/146869408-a415f668-2564-4dad-977a-a37aa7b7eeba.png)
这里面假如输入文本存在多个配音的对应关系，除了图片里面的一条关系，比如 杜子涛是红楼梦里面贾宝玉的配音，按照官方的解码逻辑，解析结果会输出组合结果，比如王雪纯 配音 晴雯，王雪纯 配音 贾宝玉， 杜子涛 配音 晴雯，杜子涛 配音 贾宝玉。如何解决这种问题？谢谢
