### ISSUE TITLE
`compare_version` 未发布

### ISSUE THREAD

**Issue by m3ngyang** [PaddlePaddle/PaddleNLP#1341]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号

- PaddleNLP 2.1.1
- PaddlePaddle2.1.1

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

`compare_version` 函数未发布, 跑 demo https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie 会报错
```bash
~ python run_ernie_crf.py
```

**Comment by wawltor** [comment]
抱歉，compare_version需要使用最新的develop版本才支持，麻烦拉取一下最新的develop版本的代码，然后 python setup.py install 一下
