### ISSUE TITLE
paddlenlp enie-csc问题

### ISSUE THREAD

**Issue by han508** [PaddlePaddle/PaddleNLP#1342]
paddlenlp2.1 paddlepaddle 2.1.2 
您好，感谢开源，我在运行paddlenlp在运行train文件的时候刚训练了1个batch，他就提示开始报错，我用的数据是自己的数据集，我的数据与样例数据最大的区别就是我的数据集中有很长的句子大概length=300，我的数据集按照github给的案例数据集格式改的（raw \t correct \n）我经过不断的调试，发现我把--max_seq_length调大没用， 调节到50以下就会在第30epoch以后才报错，但是错误信息是一样的，请问把--max_seq_length 这个参数调小对结果有什么影响？怎么处理报错问题？
更详细的信息请参考我的aistudio：https://aistudio.baidu.com/aistudio/projectdetail/2793019?contributionType=1&shared=1
报错信息如下：
 File "train.py", line 239, in <module>
    do_train(args)
  File "train.py", line 200, in do_train
    corr_logits, corr_labels) * det_error_probs.max(axis=-1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 405, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1392, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:42 != labels_dims[i]:43.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:150)
  [operator < softmax_with_cross_entropy > error]

**Comment by han508** [comment]
有人吗

**Comment by joey12300** [comment]
你好，可以把出错的那个batch的logits和labels都打印出来吗？

**Comment by han508** [comment]
您好，之前在期中考试，这个问题被耽搁了，十分抱歉，我打印了print(corr_logits, corr_labels)这两个变量，是这样的
Tensor(shape=[32, 266, 18000], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[[-0.28014067, -0.09436500,  0.00859556, ..., -0.26180422,  0.03938470, -0.19187395],
         [-0.13715141, -0.18962234,  0.23461692, ...,  0.06818749, -0.25959399, -0.03632923],
         [-0.35479656, -0.32098797,  0.15350105, ...,  0.02387173, -0.13421634,  0.04377370],
         ...,
         [-0.26179343,  0.17059472,  0.19275531, ..., -0.39499468, -0.49979445, -0.13146624],
         [-0.36796921, -0.02799806,  0.40484104, ..., -0.38585806, -0.48132542,  0.16345292],
         [-0.18747002, -0.07410198,  0.29087427, ..., -0.40327170, -0.31085691,  0.06783945]],

        [[-0.09739988,  0.15159959, -0.06245610, ...,  0.11285284,  0.01460726, -0.05148781],
         [-0.11909575, -0.01053387,  0.15056826, ...,  0.03178213, -0.43661764,  0.32836300],
         [ 0.05146093,  0.00744659,  0.13208643, ...,  0.13050823, -0.36502114,  0.27307746],
         ...,
         [-0.11478766,  0.26121855, -0.11492400, ..., -0.60538954, -0.08110271, -0.00601894],
         [-0.23372930,  0.14968558,  0.03400032, ..., -0.66061157,  0.01004332,  0.05655146],
         [-0.08214907,  0.21466859,  0.10370243, ..., -0.57790357, -0.11307079,  0.09142857]],

        [[-0.25888595, -0.21000937,  0.02715327, ..., -0.30308008,  0.06529380, -0.22494248],
         [-0.22534123, -0.29669398,  0.18225141, ..., -0.19916677, -0.50673759, -0.02383251],
         [ 0.14631230, -0.17566510,  0.33770308, ..., -0.00637000, -0.37158450,  0.04984071],
         ...,
         [-0.30435580,  0.15276463,  0.17265256, ..., -0.70860940, -0.41752440, -0.25059465],
         [-0.17631650,  0.23410156,  0.27407661, ..., -0.61198521, -0.54487556, -0.34753031],
         [-0.20731834,  0.29170567,  0.39791575, ..., -0.64250273, -0.66061664, -0.23347303]],

        ...,

        [[-0.15620296,  0.13203631,  0.20899698, ...,  0.02928138,  0.21222699,  0.04908697],
         [ 0.19396996,  0.02194598, -0.32451573, ..., -0.33174619, -0.02602213, -0.03067683],
         [ 0.03364867,  0.23839767,  0.32926127, ..., -0.27810177, -0.47939867, -0.04317588],
         ...,
         [-0.11035054,  0.04807673,  0.38327935, ..., -0.27061644, -0.41747510,  0.17637426],
         [-0.27645490,  0.31847611,  0.05375297, ..., -0.70874220, -0.24790612, -0.49246374],
         [-0.19438745,  0.39509445,  0.00456252, ..., -0.73015916, -0.39836559, -0.32255211]],

        [[-0.05409917,  0.20245340,  0.08130223, ...,  0.24789375,  0.11584289, -0.10465068],
         [ 0.29740563,  0.27306801,  0.07031510, ..., -0.15419959, -0.42336231,  0.04964000],
         [-0.34771243, -0.20740041,  0.11588937, ..., -0.04574379, -0.17598905, -0.20132424],
         ...,
         [-0.30488154,  0.04897248,  0.51599115, ..., -0.17358492, -0.23748772, -0.05232092],
         [-0.17755896, -0.08661440,  0.21860906, ..., -0.44850412, -0.57252043, -0.09162412],
         [ 0.17120767,  0.00725704,  0.08780368, ..., -0.42144296, -0.49031240,  0.08179647]],

        [[-0.29985917,  0.08086371,  0.01292463, ...,  0.01708845,  0.09885545, -0.21553774],
         [-0.17514214,  0.13893232,  0.34498519, ..., -0.02937805, -0.32925510,  0.13086888],
         [-0.14823270,  0.17641036,  0.34645298, ...,  0.07149085, -0.49146965,  0.07456255],
         ...,
         [-0.38471210,  0.60383236,  0.40757096, ..., -0.63023943, -0.56723040, -0.21286681],
         [-0.13168952,  0.54877615,  0.18585317, ..., -0.74277794, -0.82628399, -0.18094690],
         [-0.33081040,  0.21903840,  0.33694059, ..., -0.32173327, -0.64221323,  0.02613494]]]) Tensor(shape=[32, 265], dtype=int64, place=CUDAPinnedPlace, stop_gradient=True,
       [[-1 , 169, 348, ...,  0 ,  0 ,  0 ],
        [-1 , 187,  83, ...,  0 ,  0 ,  0 ],
        [-1 ,  75,  89, ...,  0 ,  0 ,  0 ],
        ...,
        [-1 ,  13, 626, ...,  0 ,  0 ,  0 ],
        [-1 ,  23,  75, ...,  0 ,  0 ,  0 ],
        [-1 ,  48,  10, ...,  0 ,  0 ,  0 ]])

**Comment by han508** [comment]
dataset 是这样 
曾几何时，港口设备老旧、衰败不堪。	曾几何时，港口设备老旧、衰败不堪。
13时许，刘某被警方抓抓获。	13时许，刘某被警方抓获。
联合演练现场，6家省内物业企业代表队展示了义务消防队力量、紧急救护技能6项内容。	联合演练现场，6家省内物业企业代表队展示了义务消防队力量、紧急救护技能等6项内容。
天元街道白鹤社区的党员代表参观完记念馆说。	天元街道白鹤社区的党员代表参观完纪念馆说。
一名网友对此吐槽到。	一名网友对此吐槽道。

**Comment by lllulll** [comment]
配置文件中设置的最大预测长度和 模型中默认batch设置的长度不一致。更改head对应py文件的参数就可以了

**Comment by yijunL** [comment]
> 更改head对应py文

可以说的清楚一点吗？ 模型中默认batch设置的长度 是指的什么？ head对应py文件又是什么
