### ISSUE TITLE
[Ask]关于中长文本的相似度模型

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1346]
Hi Team，

想问一下关于中长文本的相似度模型目前有提供吗？

不是短文本。

谢谢！

**Comment by tianxin1860** [comment]
请问这里的`中长`文本大概是多长？

**Comment by LangDaoAI** [comment]
稍等，我们统计一下平均文本size后反馈，田老师

**Comment by LangDaoAI** [comment]
> Hi Team，
> 
> 想问一下关于中长文本的相似度模型目前有提供吗？
> 
> 不是短文本。
> 
> 谢谢！

统计了我们中长文本长度小于512，以512为考虑的长度，田老师
