### ISSUE TITLE
多标签文本分类任务

### ISSUE THREAD

**Issue by cypqyc** [PaddlePaddle/PaddleNLP#1347]
多标签文本分类支持中文吗？我看示例数据是英文

**Comment by linjieccc** [comment]
您好，中文多标签文本分类可以参考这个案例：
https://aistudio.baidu.com/aistudio/projectdetail/2540472?contributionType=1

**Comment by cypqyc** [comment]
我看了这个案例  它可以支持文章多标签分类吗？类似于新闻那种长篇的   示例里是短文本

**Comment by linjieccc** [comment]
建议文本长度不超过512，如果超过可能在效果上会有影响

**Comment by cypqyc** [comment]
也就是不会报错  但是训练效果可能会不好  因为篇幅太长了 ？

**Comment by linjieccc** [comment]
是的，模型本身在预训练阶段就不会用到过长的文本

**Comment by cypqyc** [comment]
我篇章级别的文本放进去  模型会自己把超出规定长度的字符截断吗？或者 咱们这个模型对字符的长度有要求吗？

**Comment by linjieccc** [comment]
示例中使用的ERNIE-1.0模型默认的文本最大长度是512，超过之后会进行截断哈

**Comment by cypqyc** [comment]
好 多谢
