### ISSUE TITLE
word_segmentation加载自定义词典

### ISSUE THREAD

**Issue by nghuyong** [PaddlePaddle/PaddleNLP#1350]
请教一下，针对分词的任务
`seg = Taskflow("word_segmentation")`
如何加载自定义的词典

**Comment by linjieccc** [comment]
您好，分词任务自定义词典功能我们会在这周更新

**Comment by nghuyong** [comment]
👍👍👍

**Comment by nghuyong** [comment]
word_segmentation, pos_tagging, ner 
这三个task都能进行分词，分词粒度一致吗？我需要识别出一句话中的人名，需要用ner ？

**Comment by nghuyong** [comment]
word_segmentation 性能貌似特别慢，均在在50-100ms，远高于LAC，jieba这种类似的分词，有加速的方法吗？

**Comment by linjieccc** [comment]
1.分词粒度
word_segmentation和pos_tagging使用的是同一个模型（BiGRUCRF），分词粒度一致
ner任务我们提供的是基于解语框架的方案，包含更丰富的专名类别标签，同样在实体词的切分粒度会更稳定

2.人名识别
pos_tagging和ner都可以实现人名的识别，不过ner除了识别人名实体词，还能识别人物相关的概念词
示例：
```
from paddlenlp import Taskflow

ner = Taskflow("ner")
ner("美人鱼的导演是周星驰")
# [('美人鱼', '作品类_实体'), ('的', '助词'), ('导演', '人物类_概念'), ('是', '肯定词'), ('周星驰', '人物类_实体')]
```

**Comment by nghuyong** [comment]
pos_tagging 对应的人名的label是什么？

**Comment by wawltor** [comment]
> pos_tagging 对应的人名的label是什么？

<img width="649" alt="图片" src="https://user-images.githubusercontent.com/16698950/143000008-b00207ae-8935-47e7-8bf4-3cf77b209fbe.png">

您好，上面是对应的pos_tagging对应label关系

**Comment by nghuyong** [comment]
@linjieccc 
您好，如果仓库已更新，可以支持加载自定义词典，辛苦同步一下;
另外发现`seg = Taskflow("word_segmentation")`的性能比LAC，jieba分词器慢了很多，应该如何提高性能？

**Comment by linjieccc** [comment]
@nghuyong 自定义词典功能已更新哈
分词的性能方面我们优化了viterbi解码，可以升级paddlepaddle到最新版本并使用develop分支的代码再尝试下

**Comment by nghuyong** [comment]
👍👍👍
