### ISSUE TITLE
在龙芯的服务器上对ernie-gen模型进行预测的时候报下面的错误，这是因为源码编译的spaddlepaddle或paddlenlp有问题吗

### ISSUE THREAD

**Issue by xuxiaobo-666** [PaddlePaddle/PaddleNLP#1352]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
![1Y$A~3XN2@N~NUOC48L2NIH](https://user-images.githubusercontent.com/64080571/142983255-5ce1b11d-d06d-449e-85f7-db43b43bd9b5.png)

**Comment by xuxiaobo-666** [comment]
系统是loongarch64

**Comment by xuxiaobo-666** [comment]
paddlepaddle==2.1.1，paddlenlp==2.0.8，python==3.8.2

**Comment by wawltor** [comment]
> paddlepaddle==2.1.1，paddlenlp==2.0.8，python==3.8.2

建议升级一下PaddlePaddle的版本，然后看看是否有问题；目前看是PaddlePaddle在Transpose Op上面有问题，如果升级版本之后建议去PaddlePaddle github提出相应的问题，有相关的同学进行解决。
