### ISSUE TITLE
ernie-1.0 sh run_static.sh报错

### ISSUE THREAD

**Issue by LuckyyySTA** [PaddlePaddle/PaddleNLP#1358]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

根据Ernie-1.0 预训练官方文档进行预训练时，首先根据data-tools生成训练数据，从『下载原始数据』到『原始数据转换 jsonl 格式』再到『数据ID化』一直都能成功运行，在ERNIR预训练时运行run_static.sh脚本时出现报错
1）PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：MacOS  python3.6  gcc version 11.2.0 
由于在本地预训练，无GPU环境，将脚本中的
paddle.distributed.launch \
    --gpus "0,1,2,3,4,5,6,7" \
    --log_dir "output/ernie-1.0-dp8-gb512/log" \
删除了，同时将run_pretrain_static.py 中 384行的places=paddle.static.cuda_places(),修改成了places=fluid.cpu_places()
出现了以下报错：
![image](https://user-images.githubusercontent.com/41715836/143285880-237896f2-c126-497f-8b83-2f3ca3c4b61a.png)

**Comment by wawltor** [comment]
您好，确认一下了目前PaddlePaddle 发布的版本还不支持多核多进程训练，但是目前多核单进程训练是有的，具体可以看这个API  https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/ParallelExecutor_cn.html#parallelexecutor 目前多进程训练的工作正在进行中。

**Comment by ZHUI** [comment]
如之前所述，目前放出了的版本是linux上、gpu的版本，暂时不支持cpu。我们将在readme给用户更明确的说明。

祝好！
