### ISSUE TITLE
[Ask] 关于wordtag paper

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#1359]
![image](https://user-images.githubusercontent.com/83859417/143375387-51f6cd8a-3452-4306-81d8-9f3a14a2fb32.png)

Hi team，

wordtag这篇paper找不到， 希望可以共享一下address，谢谢！

-Tang

**Comment by wawltor** [comment]
您好，目前WordTag这块还没有相关的Paper。

**Comment by LangDaoAI** [comment]
OK
