### ISSUE TITLE
关于PretrainedTokenizer.batch_encode的问题

### ISSUE THREAD

**Issue by safehumeng** [PaddlePaddle/PaddleNLP#1360]
您好，提个建议可否：在PretrainedTokenizer.batch_encode中提供一下padding到batch最大长度的方法
代码在paddlenlp/transformers/tokenizer_utils.py:1086行
1）PaddlePaddle版本：无影响，PaddleNLP版本：2.1.1
2）系统环境：无影响

**Comment by smallv0221** [comment]
当前的paddlenlp.data.Pad已经包含此功能，因此在tokenizer里就不加相同的功能了

**Comment by safehumeng** [comment]
> 当前的paddlenlp.data.Pad已经包含此功能，因此在tokenizer里就不加相同的功能了

了解了，谢谢🙏
