### ISSUE TITLE
模型推理结果不稳定

### ISSUE THREAD

**Issue by BlueSkyBubble** [PaddlePaddle/PaddleNLP#1377]
在paddle模型预测过程中，虽然使用了model.eval()，但每次模型的推理结果仍然不相同，比如PaddleNLP/examples/text_matching/ernie_matching/predict_pairwise.py，训练好模型后，通过如下命令每次执行这个predict.py文件得到的结果都不相同。
```
unset CUDA_VISIBLE_DEVICES
python -u -m paddle.distributed.launch --gpus "0" \
    predict_pairwise.py \
    --device gpu \
    --params_path "./checkpoints/model_20000/model_state.pdparams"\
    --batch_size 128 \
    --max_seq_length 64 \
    --input_file 'test.tsv'
```
请问这是哪里的问题？

**Comment by hermitgreen** [comment]
我在使用ernie1.0的时候发现了同样的问题，大概在小数点5位以后出现精度不对齐情况

**Comment by tianxin1860** [comment]
你好，可以 share 一下多次预测的结果对比图？

**Comment by sunhaha123** [comment]
sentence_transformers也是如此，醉了

**Comment by tianxin1860** [comment]
您好，我本地验分别验证了 ERNIE-Gram Point-wise、Pair-wise 2种训练范式的下推理结果，多次推理结果完全一致，具体数值如下:

`基于 ERNIE-Gram 的 Point-wise 范式 2 次推理结果`
![image](https://user-images.githubusercontent.com/6829601/144972005-7f287bca-8d7d-4e08-95be-313de2c8b4c7.png)

`基于 ERNIE-Gram 的 Pair-wise 范式 2 次推理结果`
![image](https://user-images.githubusercontent.com/6829601/144971916-d587edf3-cb76-4748-b8cd-c0ac49f99d0d.png)

本地测试环境如下:
```
paddlepaddle-gpu   2.2.0
paddlenlp develop 分支
```

可否提供多次推理结果不一致的可复现环境，我们可以帮助定位问题。具体包括: 
```
1. 使用的训练代码、启动脚本
2. 使用的预测代码、启动脚本
3. 多次推理结果不一致所加载的模型参数
4. 测试数据
5. PaddlePaddle 版本号
6. PaddleNLP 版本号
```

**Comment by tianxin1860** [comment]
@BlueSkyBubble @hermitgreen @sunhaha123

**Comment by sunhaha123** [comment]
@tianxin1860 是 nlp_example\text_matching\sentence_transformers ,
![2](https://user-images.githubusercontent.com/27773261/145167261-134d3ad2-9fe6-40f2-a679-6668645dbef5.png)
![3](https://user-images.githubusercontent.com/27773261/145167275-568d5670-1fc5-4b9e-b11b-45bc685621a1.png)
![4](https://user-images.githubusercontent.com/27773261/145167285-8e084cdb-0efb-48bd-a985-c76ca4609778.png)


，其次想问下nlp_example\text_matching\simbert 为什么没有train.py,谢谢？

**Comment by tianxin1860** [comment]
SimBERT 模型目前提供基于开源模型的预测能力，训练策略暂未集成。@sunhaha123

**Comment by Steffy-zxf** [comment]
@sunhaha123 是否能够提供最小复现代码？

**Comment by sunhaha123** [comment]
@Steffy-zxf  ![70595f2f77aef0799fe0cf40774af1b9_145167285-8e084cdb-0efb-48bd-a985-c76ca4609778](https://user-images.githubusercontent.com/27773261/146112692-17ed74f9-4644-43ce-ad94-11caf780313e.png) 这个图片我在aistudio里直接运行的，什么都没改。就是sentences_transform这个文件内下的模型，我看是可能因为导入了from model import SentenceTransformer。

**Comment by HarderThenHarder** [comment]
同样遇到这个问题。
使用自己的数据在 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/multi_label/train.py 任务下训练，在训练的时候看到dev_f1能够正常收敛（到96.6%），但是使用 predict.py 文件做推理发现正确很低（29.7%），推理数据集就是训练时候用的dev.csv，同一份数据在训练/推理阶段结果不一致，应该不会是模型overfitting问题。
进一步排查，发现是每一次用predict.py得到的样本的output都不一样（对output做了sigmoid并根据0.5的阈值对每一个标签做二分类的结果）:
![image](https://user-images.githubusercontent.com/36854507/147900758-1c714387-8a88-480e-8582-5a536956caa0.png)
![image](https://user-images.githubusercontent.com/36854507/147900777-e3ee3e86-3413-4331-a868-7a94db9c116b.png)
![image](https://user-images.githubusercontent.com/36854507/147900798-4a736577-6fe5-4f55-9852-1d06e5427889.png)
但是这个问题在我使用 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/multi_label/export.py 文件将动态图导出成静态图后，模型预测的结果就稳定了。
请问是我在动态图预测的时候哪里写的有问题吗？
我的predict.py代码如下：

```python
data = [
    "四川交通出行国道G213线 K2090150公里处汶川境内（青坡村养蜂场）交通中断处，已于8月20日9时10分抢通道路，已恢复双向通行。国省干道情况四川路网国省干道路况【恢复双向通行】今天（20号）凌晨4点左右，国道G213线 K2090150公里处汶川境内（青坡村养蜂场）交通中断处，受降雨影响发生泥石流。汶川公路部门已于8月20日9时10分抢通道路，已恢复双向通行。四川交通四川交通广播",
    "入口解封。交通状况发布受暴雨天气影响，G60沪昆高速昌金段新余入口封闭。--z江西交通广播",
    "高速公路畅通行动 880高速路况G20青银高速太旧段：因下雨，平定阳泉旧关匝道站入口封闭。",
    "截至9时27分 ，京哈高速宝山段榛子镇站迁安站开道唐山北站分流结束，车辆恢复正常通行。因雾，高速交警交通管制：孟姜站北京方向关闭，秦皇岛东站北京方向只允许九座以下客车上道玉田站分流沈阳方向车辆且车辆缓慢通行约2公里。"
    ]
    
    label_info = ['Class1', 'Class2', 'Class3']

    # pretrained_model = ppnlp.transformers.BertModel.from_pretrained("bert-base-chinese")
    # tokenizer = ppnlp.transformers.BertTokenizer.from_pretrained('bert-base-chinese')

    # pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained("ernie-tiny")
    # tokenizer = ppnlp.transformers.ErnieTinyTokenizer.from_pretrained('ernie-tiny')

    pretrained_model = ppnlp.transformers.AlbertModel.from_pretrained('albert-chinese-base')
    tokenizer = ppnlp.transformers.AlbertTokenizer.from_pretrained('albert-chinese-base')
    model = MultiLabelClassifier(pretrained_model, num_labels=len(label_info))

    if params_path and os.path.isfile(params_path):
        state_dict = paddle.load(params_path)
        model.set_dict(state_dict)
        print("Loaded parameters from %s" % params_path)

    examples = []
    for text in data:
        example = {"text": text}
        input_ids, segment_ids = convert_example(
            example,
            tokenizer,
            max_seq_length=300,
            is_test=True)
        examples.append((input_ids, segment_ids))

    batchify_fn = lambda samples, fn=Tuple(
        Pad(axis=0, pad_val=tokenizer.pad_token_id),  # input
        Pad(axis=0, pad_val=tokenizer.pad_token_id),  # segment
    ): fn(samples)

    batches = [
            examples[idx:idx + batch_size]
            for idx in range(0, len(examples), batch_size)
        ]
    
    results = []
    model.eval()
    for step, batch in enumerate(batches):
        input_ids, token_type_ids = batchify_fn(batch)

        input_ids = paddle.to_tensor(input_ids, dtype='int64')
        token_type_ids = paddle.to_tensor(token_type_ids, dtype='int64')
        # print('input_ids: ', input_ids)
        # print('token_type_ids: ', token_type_ids)

        logits = model(input_ids, token_type_ids)
        probs = F.sigmoid(logits)
        # print('probs: ', probs)
        preds = (probs.numpy() > 0.5).astype(int)
        results.extend(preds)
        # print('results: ', results)

    for idx, text in enumerate(data):
        print('Data: \t {}'.format(text))
        for i, k in enumerate(label_info):
            print('{}: \t {}'.format(k, results[idx][i]))
```

**Comment by ZeyuChen** [comment]
> 

@HarderThenHarder 明天我们的工程师会回复您这个问题。@Steffy-zxf 明天重点关注下哈

**Comment by Steffy-zxf** [comment]
@HarderThenHarder @sunhaha123 你好！请确认下训练后保存的模型参数是否被正确加载，如以下代码
```python
    if args.init_from_ckpt and os.path.isfile(args.init_from_ckpt):
        state_dict = paddle.load(args.init_from_ckpt)
        model.set_dict(state_dict)
```

**Comment by HarderThenHarder** [comment]
Fine-Tuning模型应该是被正确加载了的：
![image](https://user-images.githubusercontent.com/36854507/148015785-715bb4e1-d065-4e5c-a066-c1af095329fb.png)
您方便给个如流号吗，我通过如流联系您。

**Comment by Steffy-zxf** [comment]
@HarderThenHarder 你好， 我的如流号叫做 张雪菲。

**Comment by hermitgreen** [comment]
> @BlueSkyBubble @hermitgreen @sunhaha123

https://github.com/PaddlePaddle/PaddleNLP/issues/1604

**Comment by jeffzhengye** [comment]
这个bug 解决了没有，我也发现QuestionMatching 里面的inference结果不一样。
LQ那个数据集，test 推理跑了几次，每次acc都不一样。acc: 0.86576  acc: 0.86632, acc: 0.86512
虽然相隔不大
