### ISSUE TITLE
example中所提供的机器翻译任务，训练结束后，模型评估blue为0

### ISSUE THREAD

**Issue by springsprite** [PaddlePaddle/PaddleNLP#1385]
- 版本、环境信息
1）PaddleNLP v2.1.1，PaddlePaddle2.1.3
2）Linux，python3.7

采用examples/machine_translation/transformer/configs/transformer.base.yaml的默认配置

**valid log**
[2021-12-02 05:15:40,762] [    INFO]^[[0m - validation, step_idx: 140000, avg loss: 2.787584, normalized loss: 1.406631, ppl: 16.241730

**training log:**
2096 ^[[32m[2021-12-02 05:43:26,992] [    INFO]^[[0m - step_idx: 148100, epoch: 29, batch: 4840, avg loss: 2.304230, normalized loss: 0.923277, ppl: 10.016460, avg_speed: 4.96 step/sec, batch_cost: 0.20158 sec, reader_cost:

**Comment by springsprite** [comment]
模型推断所生成的predict.txt中好多空白行

**Comment by springsprite** [comment]
PaddleNLP 版本是v2.1.1

**Comment by FrostML** [comment]
已解决。确认是 输出格式是否是 time major 的原因。
