### ISSUE TITLE
DuReader_robust阅读理解，传入自定义数据路径报错

### ISSUE THREAD

**Issue by Quantum-Cheese** [PaddlePaddle/PaddleNLP#141]
其实是两个问题：
1. 完成训练后是否能用训练好的模型在无答案的数据集上预测
 跑示例DuReader_robust的时候发现，好像只能用 fine-tuning 训练模型，然后用 dev 数据集测试，输出测评结果。但如果把 load_dataset 的split参数从 ‘dev’ 改成 ‘test’ 以后就会报错 KeyError: 'answers'，应该是因为test数据里没有‘answers’，不知道如果要在这种数据上跑是否需要修改代码。
2. 传入自定义数据的路径就会报错
还有在使用 - - predict_file 后面加文件路径会报错：AssertionError: `data_files` should be a string or a dictionary whose key is split name ande value is a path of data file.

问题是我现在想要直接用训练好的模型在自己的数据上进行预测，因为我的数据集是没有答案的。就想要知道具体实现方式是什么，readme里面也没有这方面的说明

**Comment by smallv0221** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/142
你提到的两个问题在这个pr中修复了，可以先参照这个pr修改dureader_robust.py 和args.py中的代码，就能在自己的数据集上进行预测了。
