### ISSUE TITLE
knowledge_mining中切割长句函数_split_long_text_input有误？

### ISSUE THREAD

**Issue by JiaqiYao** [PaddlePaddle/PaddleNLP#1412]
WordTagTask中的函数 _split_long_text_input中的  temp_text_list = text.split("？。！")
这一行代码应该是想按照"？。！"或分割句子，但是python字符串的split函数不支持这种操作。

In [5]: test_str = "'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人"
In [6]: test_str.split("？。！")
Out[6]: ["'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人"]
In [7]: import re
In [8]: re.split("([？。！])", test_str)
Out[8]: ["'拉普兰特曾在奥巴", '。', '', '？', '马', '！', '政府期间担任美国空军采办负责人']

**Comment by wawltor** [comment]
> WordTagTask中的函数 _split_long_text_input中的 temp_text_list = text.split("？。！") 这一行代码应该是想按照"？。！"或分割句子，但是python字符串的split函数不支持这种操作。
> 
> In [5]: test_str = "'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人" In [6]: test_str.split("？。！") Out[6]: ["'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人"] In [7]: import re In [8]: re.split("([？。！])", test_str) Out[8]: ["'拉普兰特曾在奥巴", '。', '', '？', '马', '！', '政府期间担任美国空军采办负责人']

上面的split的方式是不是中英文混用导致的没有办法split的了？我本地环境是可以的，看了一下 上面的示例代码是英文的符号，所以导致没有办法分割。不过确实需要考虑一下中英文符号的问题
<img width="619" alt="图片" src="https://user-images.githubusercontent.com/16698950/145361090-de20a32a-1443-4cc8-9196-d7b3070a0e73.png">

**Comment by JiaqiYao** [comment]
> > WordTagTask中的函数 _split_long_text_input中的 temp_text_list = text.split("？。！") 这一行代码应该是想按照"？。！"或分割句子，但是python字符串的split函数不支持这种操作。
> > In [5]: test_str = "'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人" In [6]: test_str.split("？。！") Out[6]: ["'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人"] In [7]: import re In [8]: re.split("([？。！])", test_str) Out[8]: ["'拉普兰特曾在奥巴", '。', '', '？', '马', '！', '政府期间担任美国空军采办负责人']
> 
> 上面的split的方式是不是中英文混用导致的没有办法split的了？我本地环境是可以的，看了一下 上面的示例代码是英文的符号，所以导致没有办法分割。不过确实需要考虑一下中英文符号的问题 <img alt="图片" width="619" src="https://user-images.githubusercontent.com/16698950/145361090-de20a32a-1443-4cc8-9196-d7b3070a0e73.png">

字符串的split函数是支持单个字符的，也就是你给的示例。但是我理解代码中的temp_text_list = text.split("？。！")，是想以"？。！"任何一个字符分割句子，也就是或的关系，字符串的split函数是不支持的，可能需要re库里面的split

**Comment by wawltor** [comment]
> > > WordTagTask中的函数 _split_long_text_input中的 temp_text_list = text.split("？。！") 这一行代码应该是想按照"？。！"或分割句子，但是python字符串的split函数不支持这种操作。
> > > In [5]: test_str = "'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人" In [6]: test_str.split("？。！") Out[6]: ["'拉普兰特曾在奥巴。？马！政府期间担任美国空军采办负责人"] In [7]: import re In [8]: re.split("([？。！])", test_str) Out[8]: ["'拉普兰特曾在奥巴", '。', '', '？', '马', '！', '政府期间担任美国空军采办负责人']
> > 
> > 
> > 上面的split的方式是不是中英文混用导致的没有办法split的了？我本地环境是可以的，看了一下 上面的示例代码是英文的符号，所以导致没有办法分割。不过确实需要考虑一下中英文符号的问题 <img alt="图片" width="619" src="https://user-images.githubusercontent.com/16698950/145361090-de20a32a-1443-4cc8-9196-d7b3070a0e73.png">
> 
> 字符串的split函数是支持单个字符的，也就是你给的示例。但是我理解代码中的temp_text_list = text.split("？。！")，是想以"？。！"任何一个字符分割句子，也就是或的关系，字符串的split函数是不支持的，可能需要re库里面的split

OK  了解 我们提个PR来支持一下
