### ISSUE TITLE
launch.py: error: unrecognized arguments: --gpus

### ISSUE THREAD

**Issue by Andrewlesson** [PaddlePaddle/PaddleNLP#1421]
when i followed the README to train [machine_translation ](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer)model, but error occurs  below

![image](https://user-images.githubusercontent.com/10346684/145403329-8acfa418-4a49-4def-bd14-769a1223f3ec.png)

![image](https://user-images.githubusercontent.com/10346684/145403064-80c28e80-8867-40ed-845f-bbb423316df8.png)

**Comment by wawltor** [comment]
您好，能提供一下PaddlePaddle的版本吗？

**Comment by Andrewlesson** [comment]
> 您好，能提供一下PaddlePaddle的版本吗？

done，thx

**Comment by TBBTfans** [comment]
请问如何解决的
