### ISSUE TITLE
csc 比赛

### ISSUE THREAD

**Issue by han508** [PaddlePaddle/PaddleNLP#1428]
你好，感谢开源，我在参加一个文本纠错比赛的时候，用的ernie-csc的模型，数据集4000条，测试集3000条，但是我的模型实际效果一直不是很理想，尽管训练集检查错误f1=55，改错f1=39，但是测试集我的得分只有0.07（评分标准为maxmatch），我想请问一下，这是为什么，我在使用的时候直接把dataset装进去就训练了，大概训练了2个小时。

**Comment by joey12300** [comment]
你好，请问你参加的纠错比赛是只需改错字吗？有要求删除多字、添加少字的需求吗？

**Comment by han508** [comment]
你好，感谢回复，是这样的 多字、少字、乱序、标点等；拼写错误，包括同音字、近音字、形近字等。
