### ISSUE TITLE
PaddleNLP/examples/information_extraction/是否有关于实体属性抽取的案例，类似个人基本信息，姓名、年龄、身高

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1435]
PaddleNLP/examples/information_extraction/是否有关于实体属性抽取的案例，类似个人基本属性信息，姓名、年龄、身高，这些应该都是围绕某个人的一些属性实体，不是类似loc,per,time这种通用的实体抽取，有没有属性抽取的相关的案例代码？
另外有围绕实体抽取、属性抽取、关系抽取的联合抽取模型的案例吗？

**Comment by ZeyuChen** [comment]
我们根据你的需求，未来会考虑针对信息抽取这个领域提供针对信息抽取领域更专业的开发套件，Stay tuned

**Comment by AI-Mart** [comment]
好的，期待！

**Comment by ButyAfter** [comment]
有了吗
