### ISSUE TITLE
SKEP使用预训练模型的疑惑

### ISSUE THREAD

**Issue by cooljsz** [PaddlePaddle/PaddleNLP#1456]
您好:
SKEP真的是一个很好的开源项目,向你们致敬.在阅读README文档时,对于我这种AI渣渣来说,有一点小小的疑惑.
里面提到了可以加载更多的预训练模型,也给出了两个model和tokenizer的变量定义,但是--model_name "skep_ernie_1.0_large_ch" 这个参数应该是传入一个预训练模型工具的字符串名称,和下面两句之间是什么关系?没搞清楚,看了transformers的说明之后还更迷惑了.
请帮忙写一下更细致的使用方式,多谢!
model = paddlenlp.transformers.SkepForSequenceClassification.from_pretrained(
    "skep_ernie_1.0_large_ch")
tokenizer = paddlenlp.transformers.SkepTokenizer.from_pretrained(
    "skep_ernie_1.0_large_ch")

**Comment by Steffy-zxf** [comment]
@cooljsz 你好！感谢关注！`SkepForSequenceClassification()`和`SkepTokenizer() `是根据指定的model_name加载对应的SKEP模型和Tokenizer的。

> 更细致的使用方式

是指 什么样使用困惑呢？还有什么不明白的吗？

**Comment by cooljsz** [comment]
就是不在明白其他的预训练模型该怎么使用,最好能给出代码示例,谢谢
