### ISSUE TITLE
PaddleNLP/examples/text_classification/pretrained_models/train.py如何构建自己的数据集兵训练，这个地方没有文档？

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleNLP#1458]

**Comment by ZHUI** [comment]
你好！
可以参照新增数据集文档 https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html
也可以参考这个新增xnli数据集的PR， https://github.com/PaddlePaddle/PaddleNLP/pull/1336/files
