### ISSUE TITLE
文本相似度，InvalidArgumentError

### ISSUE THREAD

**Issue by yangchanglin324** [PaddlePaddle/PaddleNLP#1460]
问题：
文本相似度，样例报错，无法运行

环境：
paddle 2.2.0
PaddleNLP 2.2.0
操作系统 win10
python 3.7.3

复现代码：
from paddlenlp import Taskflow
similarity = Taskflow("text_similarity")
similarity([["世界上什么东西最小", "世界上什么东西最小？"]])

错误：
InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at C:\home\workspace\Paddle_release\paddle\fluid\framework\operator.cc:1603)
      [operator < equal > error]

**Comment by wawltor** [comment]
应该是是一个windows兼容的问题，咱们提个PR修复一下吧 @linjieccc

**Comment by linjieccc** [comment]
感谢指出问题~已提PR修复https://github.com/PaddlePaddle/PaddleNLP/pull/1465

**Comment by yangchanglin324** [comment]
好的，谢谢，我在本地修改你刚修改的那几行代码就可以了是吧。

**Comment by linjieccc** [comment]
@yangchanglin324 是的，不客气

**Comment by Wxs18337266838** [comment]
请问这个问题在windows系统上如何解决？

**Comment by ZeyuChen** [comment]
@Wxs18337266838 https://github.com/PaddlePaddle/PaddleNLP/pull/1465/files
请参考下这个PR，需要在数据类型上加上int64即可。或者你clone最新代码，这个issues的问题应该已经解决了。

**Comment by Scott-tao** [comment]
已用最新代码
环境：
paddlepaddle 2.3.2
PaddleNLP 2.3.7
操作系统 win10
python 3.8.8

还是同样的报错，请问怎么解决

**Comment by w5688414** [comment]
> 已用最新代码 环境： paddlepaddle 2.3.2 PaddleNLP 2.3.7 操作系统 win10 python 3.8.8
> 
> 还是同样的报错，请问怎么解决

int64的问题，升级到2.4.0，问题已经修复了
