### ISSUE TITLE
关于distill中ofa项目paddleslim，run_glue_ofa.py导出的超网络.pdiparams 和 export_model.py导出的模型.pdiparams，加载输出的.pdiparams模型并预测dev验证集，发现输出的logits存在很大问题，预测几乎不正确，输出的logits也几乎被锁死。

### ISSUE THREAD

**Issue by syc22** [PaddlePaddle/PaddleNLP#1466]
ofa文档说明里只是到了模型导出就没后文了。 实际在run_glue_ofa.py中评估超网络时的准确率还是很高的符合预期的，但是当模型保存后，甚至通过export_model.py导出后的小模型，其准确率没有得到保证，请问该如何使用导出的小模型.pdparams。我经过在dev验证集上验证小模型均存在问题，输出的logits几乎被锁死，准确率直接锁死在0.2333。

附问：ofa模型剪裁后的.pdparams可以像 预训练模型微调后的模型一样使用（如蒸馏到bilstm / 再次进行ofa剪裁）嘛？ 文档只到了导出的模型.pdparams，后续该如何使用？我在使用的过程中发现如上预测logits ,精度问题

**Comment by syc22** [comment]
![微信图片_20211215151240](https://user-images.githubusercontent.com/57344752/146140399-e42e9b99-d282-40d4-9c6a-cf14e9936254.png)
加载剪裁宽度后的模型 预测的输出

**Comment by syc22** [comment]
![111图片_20211215151458](https://user-images.githubusercontent.com/57344752/146140636-1e189c1f-0156-4c6d-9fda-39f9e8f36922.png)
加载输入run_glue_ofa.py之前微调的模型，预测是标准的正常的

**Comment by syc22** [comment]
![2222片_20211215152905](https://user-images.githubusercontent.com/57344752/146142399-dbab14de-547f-4a42-a1d4-e70b92c13bbe.png)
这是预测的数据

**Comment by syc22** [comment]
![3333片_20211215153937](https://user-images.githubusercontent.com/57344752/146143801-987dad97-0473-4f92-b293-c723ee2a35c5.png)
![444420211215153944](https://user-images.githubusercontent.com/57344752/146143815-eb032041-24d1-4bd9-a8d6-843272ba7c11.png)
加载模型 预测代码

**Comment by LiuChiachi** [comment]
通过OFA对宽度压缩后的模型，模型中的q, k, v的weight不再是[hidden_size, hidden_size]，而是[hidden_size, hidden_size * width_mul]，后者已经不符合transformer的组网，不能用原始的方法load了，动态图导入模型不太方便，OFA对模型裁剪的目的应该是后续直接接入预测部署，一般不会再继续训练。@ceci3

**Comment by syc22** [comment]
谢谢老师回复，我的想法是通过剪裁的模型再继续做训练 蒸馏，从结果看来是行不通了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiaqi ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 下午3:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 关于distill中ofa项目paddleslim，run_glue_ofa.py导出的超网络.pdiparams 和 export_model.py导出的模型.pdiparams，加载输出的.pdiparams模型并预测dev验证集，发现输出的logits存在很大问题，预测几乎不正确，输出的logits也几乎被锁死。 (Issue #1466)





 
通过OFA对宽度压缩后的模型，模型中的q, k, v的weight不再是[hidden_size, hidden_size]，而是[hidden_size, hidden_size * ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
