### ISSUE TITLE
PaddleNLP/examples/information_extraction/waybill_ie  测试推理时test.txt的问题

### ISSUE THREAD

**Issue by aishangmaxiaoming** [PaddlePaddle/PaddleNLP#1473]
PaddleNLP/examples/information_extraction/waybill_ie 测试推理时test.txt的必须是带label的吗
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/67897601/146329585-e99bc8a3-c70a-443d-a068-5e3c72dbbe14.png">
，都自己打好lable啦，模型推理还有什么用呢？

**Comment by aishangmaxiaoming** [comment]
怎么推理单条数据

**Comment by aishangmaxiaoming** [comment]
怎么推理无标注的单条数据

**Comment by aishangmaxiaoming** [comment]
比如我就是想从：’八马路与东平行路交叉口北40米韦业涛18600009172‘ 信息抽取出电话和地址？应该怎么改呢

**Comment by joey12300** [comment]
@aishangmaxiaoming 你好，目前暂时提供的预测脚本数据处理部分还是基于评估集的数据格式。可以先试试修改python/predict.py的read函数，修改数据读取方式。
![image](https://user-images.githubusercontent.com/10826371/146361814-7a0a2d73-5bf9-47c0-9ebf-53a6f7403dd1.png)

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/deploy/python/predict.py#L125

**Comment by aishangmaxiaoming** [comment]
> @aishangmaxiaoming 你好，目前暂时提供的预测脚本数据处理部分还是基于评估集的数据格式。可以先试试修改python/predict.py的read函数，修改数据读取方式。 ![image](https://user-images.githubusercontent.com/10826371/146361814-7a0a2d73-5bf9-47c0-9ebf-53a6f7403dd1.png)
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/deploy/python/predict.py#L125
输入：
<img width="535" alt="image" src="https://user-images.githubusercontent.com/67897601/146365647-3a80c122-d454-4803-a515-a897b071228b.png">


输出：
<img width="807" alt="image" src="https://user-images.githubusercontent.com/67897601/146365577-c977d5fe-b34c-4d7f-9b49-c83ea48bf557.png">
代码：
<img width="494" alt="image" src="https://user-images.githubusercontent.com/67897601/146365709-740271a6-ed43-496a-8d87-27b444d76143.png">
貌似不太行呢？

**Comment by joey12300** [comment]
words那一行，改成如下试试：
```
words=list(words)
```
