### ISSUE TITLE
请问如何使用paddle框架在distill学生模型Bilstm 后加Attention?

### ISSUE THREAD

**Issue by syc22** [PaddlePaddle/PaddleNLP#1479]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by LiuChiachi** [comment]
您好，
带有Attention的Bi-LSTM可以参考这里的实现，https://github.com/PaddlePaddle/PaddleNLP/blob/806ff6f9984afa56012270b666a7954ea31be952/examples/text_classification/rnn/model.py#L189
把这个模型作为学生模型即可～

**Comment by syc22** [comment]
老师，感谢您在百忙中阅读这封邮件，在这里麻烦帮忙答疑解惑：
1.为什么蒸馏出的bilstm学生模型 .pdparams参数是2.3个G，使用paddle.summary打印出的Total params有三个多亿，比老师模型还要大。附图如下：图1为打通过paddle.summary印蒸馏后的模型参数。&nbsp; 图2位蒸馏出的模型.pdparams为2.3个G
2.请问paddle如何查看ernie / bert等预训练模型微调后的模型的参数大小，flops等类似paddle.summary的功能？因为需要和蒸馏后的模型做模型参数大小 ， flops运算速度上的比较。请问老师应该怎么获取ernie / bert等预训练模型以及Bilstm学生模型 模型大小和flops参数?&nbsp;&nbsp;
3.对于上面问题2的另一种问法：如何官方定量的比较蒸馏后的模型与老师模型的预测速度，模型大小？

图1

图2


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月28日(星期二) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 请问如何使用paddle框架在distill学生模型Bilstm 后加Attention? (Issue #1479)





 
您好，
 带有Attention的Bi-LSTM可以参考这里的实现，https://github.com/PaddlePaddle/PaddleNLP/blob/806ff6f9984afa56012270b666a7954ea31be952/examples/text_classification/rnn/model.py#L189
 把这个模型作为学生模型即可～
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
