### ISSUE TITLE
关于LAC模型识别实体的效率

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#1482]
目前我使用LAC模型。使用自己的数据集训练了一个实体识别模型，使用python在自己的Windows电脑上的预测识别速度大约是一万条数据用时2.5秒，请问有什么办法能提升这个识别的速度吗？

paddlenlp 2.0.3
paddlepaddle 2.1.0
LAC 2.1.2
python 3.7.10

**Comment by wawltor** [comment]
可以升级一下PaddlePaddle和PaddleNLP的到最新的版本，最新的PaddleNLP的版本有对LAC依赖的CRF算子进行优化

**Comment by tom-tangqs** [comment]
>好的，我尝试一下，谢谢
