### ISSUE TITLE
taskflow是否支持tqdm显示进度？

### ISSUE THREAD

**Issue by cocoa0409** [PaddlePaddle/PaddleNLP#1485]
taskflow预测时不显示进度，挺不方便的。

两种方式，求问官方推荐哪一种？
1、按batch_size预先切分，然后每一次都喂一个batch
2、喂全量（有tqdm设置吗？）

**Comment by wawltor** [comment]
> taskflow预测时不显示进度，挺不方便的。
> 
> 两种方式，求问官方推荐哪一种？ 1、按batch_size预先切分，然后每一次都喂一个batch 2、喂全量（有tqdm设置吗？）

第二种方案目前不太好设置tqdm，目前Taskflow的预测使用了静态图图预测，预测的时候就是一次输入，一次预测，所以很难用tqdm。

**Comment by Liane-Wang** [comment]
期待taskflow可以支持tqdm
