### ISSUE TITLE
关于plato2_en_base模型的使用

### ISSUE THREAD

**Issue by VolcanoBin** [PaddlePaddle/PaddleNLP#1486]
按照官方的教程一步步来，但是就是没法使用官方的模型，出现广播的错误，请问这是什么问题呢
![2021122001](https://user-images.githubusercontent.com/49603008/146710086-4d7cea8c-c316-4ef5-8fae-663f5bfdc3ed.PNG)
![2021122002](https://user-images.githubusercontent.com/49603008/146710092-f8efe319-3792-4136-afa6-8ee15cc63e7b.PNG)

**Comment by VolcanoBin** [comment]
模型也删掉重新安装还是不行，用cmd也不行，换台笔记本也不行，显存没有爆

**Comment by VolcanoBin** [comment]
https://www.paddlepaddle.org.cn/hubdetail?name=plato2_en_base&en_category=TextGeneration
这是教程链接

**Comment by KPatr1ck** [comment]
> https://www.paddlepaddle.org.cn/hubdetail?name=plato2_en_base&en_category=TextGeneration 这是教程链接

你好，plato2_en_base的使用环境必须满足以下要求：
1.8.2 <= paddlepaddle < 2.0.0
1.7.0 <= paddlehub < 2.0.0

另外paddlehub接入的plato-mini模型也是可以用于对话场景的：
https://www.paddlepaddle.org.cn/hubdetail?name=plato-mini&en_category=TextGeneration

**Comment by VolcanoBin** [comment]
> > https://www.paddlepaddle.org.cn/hubdetail?name=plato2_en_base&en_category=TextGeneration 这是教程链接
> 
> 你好，plato2_en_base的使用环境必须满足以下要求： 1.8.2 <= paddlepaddle < 2.0.0 1.7.0 <= paddlehub < 2.0.0
> 
> 另外paddlehub接入的plato-mini模型也是可以用于对话场景的： https://www.paddlepaddle.org.cn/hubdetail?name=plato-mini&en_category=TextGeneration

好的我看看，谢谢

**Comment by VolcanoBin** [comment]
> > https://www.paddlepaddle.org.cn/hubdetail?name=plato2_en_base&en_category=TextGeneration 这是教程链接
> 
> 你好，plato2_en_base的使用环境必须满足以下要求： 1.8.2 <= paddlepaddle < 2.0.0 1.7.0 <= paddlehub < 2.0.0
> 
> 另外paddlehub接入的plato-mini模型也是可以用于对话场景的： https://www.paddlepaddle.org.cn/hubdetail?name=plato-mini&en_category=TextGeneration

请问有没有基于plato-mini模型的预训练的教程呢

**Comment by VolcanoBin** [comment]
> > https://www.paddlepaddle.org.cn/hubdetail?name=plato2_en_base&en_category=TextGeneration 这是教程链接
> 
> 你好，plato2_en_base的使用环境必须满足以下要求： 1.8.2 <= paddlepaddle < 2.0.0 1.7.0 <= paddlehub < 2.0.0
> 
> 另外paddlehub接入的plato-mini模型也是可以用于对话场景的： https://www.paddlepaddle.org.cn/hubdetail?name=plato-mini&en_category=TextGeneration

就是想用自己的数据微调plato-mini模型
