### ISSUE TITLE
PaddleNLP/examples/information_extraction/DuIE官方信息抽取方案疑问

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1493]
![image](https://user-images.githubusercontent.com/63343847/146866385-07798788-4fcd-481f-9b43-8097785576fe.png)

这里面假如输入文本存在多个配音的对应关系，除了图片里面的一条关系，比如 杜子涛是红楼梦里面贾宝玉的配音，按照官方的解码逻辑，解析结果会输出组合结果，比如王雪纯 配音 晴雯，王雪纯 配音 贾宝玉， 杜子涛 配音 晴雯，杜子涛 配音 贾宝玉。如何解决这种问题？谢谢

**Comment by BenfengXu** [comment]
> ![image](https://user-images.githubusercontent.com/63343847/146866385-07798788-4fcd-481f-9b43-8097785576fe.png)
> 
> 这里面假如输入文本存在多个配音的对应关系，除了图片里面的一条关系，比如 杜子涛是红楼梦里面贾宝玉的配音，按照官方的解码逻辑，解析结果会输出组合结果，比如王雪纯 配音 晴雯，王雪纯 配音 贾宝玉， 杜子涛 配音 晴雯，杜子涛 配音 贾宝玉。如何解决这种问题？谢谢

感谢关注我们的数据集与Baseline~
该Baseline实现，对于这种情况，会直接输出所有可能的组合，即以上四种s-o都会输出出来。理论上来说，只对S/O做一次线性复杂度的Tagging是无法完全解决平方复杂度的结构化输出空间的。基线只是为了提供给大家一个可参考的基础实现，所以在细节处理上是尽可能简化的。
如果想要进一步解决这种情况，对基线进行优化，可以尝试1）添加简单的规则，如根据s-o间的距离来决定匹配关系；2）尝试其他的Tagging方法，比如ACL21的PRGC[1]，在s/o Tagging的基础上，额外增加了一个alignment模块来计算匹配关系~
[1]PRGC: Potential Relation and Global Correspondence Based Joint Relational Triple Extraction

**Comment by AI-Mart** [comment]
感谢回复，我参考下，paddlenlp能否及时持续更新并且增加每个子领域目前最新的sota方案,我认为只有这样，才能相比其他的框架有绝对的优势，另外这个issu能否也关注下https://github.com/PaddlePaddle/PaddleNLP/issues/1476，谢谢
