### ISSUE TITLE
基于预训练模型的机器阅读理解例子里进行分词时出现的问题

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#1497]
在运行NLP打卡营第6天的例子时，在使用服务器和AIStudio运行第3块代码块 （- “3. 调用map()方法批量处理数据”）生成input_ids, token_type_ids, start_positions, end_positions时

AIStudio里的paddlepaddle版本为2.1.2. paddlenlp更新至最新版本2.2.1. 用的CPU模式跑的代码块3，出现如下错误。
--------------------------------------
C++ Traceback (most recent call last):

0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

Error Message Summary:

FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1640163504 (unix time) try "date -d @1640163504" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800000b0d) received by PID 2933 (TID 0x7fdb3c807700) from PID 2829 ***]。

（以上为AIStudio出现的报错信息）
![Q2](https://user-images.githubusercontent.com/96521059/147066362-101b9da7-4622-4f24-a020-dda860fd2ee3.JPG)

AIStudio的内存占用会疯涨，直至整个AIStudio报出“内存溢出”问题，结束运行。

![Q3](https://user-images.githubusercontent.com/96521059/147066754-d1e90897-0a26-4295-b59d-7f156a07d7bc.JPG)

在服务器上也出现一样的问题，但是能运行出结果，并且能运行后续的部分。
服务器上的paddlepaddle版本为2.2.1， paddlenlp版本为2.2.1. CUDA版本为10.2
报错为：

--------------------------------------
C++ Traceback (most recent call last):

No stack trace in paddle, may be caused by external reasons.

Error Message Summary:

FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1640162470 (unix time) try "date -d @1640162470" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x5000) received by PID 20570 (TID 0x7f69cf896700) from PID 20480 ***]

![Q1](https://user-images.githubusercontent.com/96521059/147066977-ac697542-a84b-4f21-b646-9c366eefa792.JPG)
但能运行结束，并且能成功运行后续的代码块。
能否针对此问题给予一定的解释

**Comment by smallv0221** [comment]
Thanks for your patience! We have fixed this bug in PaddleNLP 2.2.3. You can try again now.
