### ISSUE TITLE
关于ChineseBERT预训练

### ISSUE THREAD

**Issue by LuckyyySTA** [PaddlePaddle/PaddleNLP#1501]
（1）请问将来是否会有ChineseBERT的预训练代码放出
（2）README中说参考ELECTRA的预训练部分，但是二者的预训练任务却不一样呀，如何参考呢？

**Comment by 27182812** [comment]
关于ChineseBERT的预训练部分，建议咨询原作者，我看见有相关回复，“We followed Hugginface‘s pre-training scripts, you can replace the origin BertModel with our GlyceBertModel easily:
here is the link:
https://github.com/huggingface/transformers/tree/master/examples/pytorch/language-modeling ”

**Comment by LuckyyySTA** [comment]
好的，感谢回复！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 27182812 ***@***.***&gt;
发送时间: 2021年12月27日 18:58
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: init ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] 关于ChineseBERT预训练 (Issue #1501)





 
关于ChineseBERT的预训练部分，建议咨询原作者，我看见有相关回复，“We followed Hugginface‘s pre-training scripts, you can replace the origin BertModel with our GlyceBertModel easily:
 here is the link:
 https://github.com/huggingface/transformers/tree/master/examples/pytorch/language-modeling”
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
