### ISSUE TITLE
【cudaErrorIllegalAddress】在做古文词性标注时候报错

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/PaddleNLP#1502]
版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.8，PaddlePaddle2.2.0
2）系统环境：请您描述系统类型，本地win10，cuda11；aistudio上也报错
OSError: (External) CUDA error(700)， an illegal memory access was encountered.
[Hint: ' cudaErrorIlLegaLAddress'. The device encountered a Load or store instruction on an invalid memory address. This Leaves the process in an
inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and reLaunched. ] (at
. \paddLe\fLuid\pLatform\gpu. info. cc :440)
[operator < Lookup table _v2 > error ]
![e8aaefb2269af5f346a84e98050c547](https://user-images.githubusercontent.com/68314259/147176331-381628a0-2d14-441c-be5c-f4d8ae60ebea.png)
aistudio:https://aistudio.baidu.com/aistudio/projectdetail/3275842

**Comment by joey12300** [comment]
看报错信息像显存访问越界了，可以检查一下是否输入的input_ids超过了词表大小，导致Embedding查表越界了。

**Comment by jiaohuix** [comment]
额，一般不认识的词不是会替换成unk么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 中午12:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 【cudaErrorIllegalAddress】在做古文词性标注时候报错 (Issue #1502)





 
看报错信息像显存访问越界了，可以检查一下是否输入的input_ids超过了词表大小，导致Embedding查表越界了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sixyang** [comment]
我也遇到这个问题，暂时不知道怎么办，而且有时候会出现，但有时候不会……
