### ISSUE TITLE
Python训练LAC模型，Java调用，两边预测结果不一致

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#1504]
我使用LAC模型框架，用自己的数据训练了一个LAC模型识别实体，并且在原来四种实体是基础上新增了一些实体，用python进行训练，用java调用训练好的模型，出现了在Python中预测的结果和在java中预测的结果不一致的情况。

![image](https://user-images.githubusercontent.com/51399899/147183461-a9a3c162-f232-4175-9294-3c1db025e844.png)
![image](https://user-images.githubusercontent.com/51399899/147183504-016ac76e-cb5a-4371-a68a-f757b7b40c5f.png)
预测同一个时间，在python中可以预测出来，但java调用后就预测不出来。
但是预测其他的实体，识别结果都是一致的，这是什么原因呢？
![image](https://user-images.githubusercontent.com/51399899/147183820-2c97e9af-82f0-43e5-b4df-711afa271e6b.png)
![image](https://user-images.githubusercontent.com/51399899/147183833-3a26dfd9-a1ee-4deb-a136-2cbd27b97bff.png)
看到Java编译需要2.0以下的版本，所以将paddlepaddle的版本降到了1.8.0

Python训练中使用的版本
paddlepaddle ==1.8.0
paddlenlp == 2.2.1
lac == 2.1.1
Java编译的版本不清楚

**Comment by joey12300** [comment]
@tom-tangqs 你好，可能java一些jdk等环境问题，也可以尝试使用PaddleNLP的LAC模型进行预测部署：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis
