### ISSUE TITLE
faster_generation微调示例

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1513]
可否有faster_generation微调示例

**Comment by ZeyuChen** [comment]
FasterGeneration适用于生成场景加速的，您想要文本生成任务那个场景的微调呢？

**Comment by ZTurboX** [comment]
> 

文本续写

**Comment by ZeyuChen** [comment]
FasterGeneration主要是对预训练加速的生成，如果需要Finetune的话需要重新训练。
可以参考下 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_generation/ernie-gen
