### ISSUE TITLE
termtree添加新词，仍然无法识别

### ISSUE THREAD

**Issue by hebo1982** [PaddlePaddle/PaddleNLP#1514]
文档 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/termtree
增加关键词 "静磁场"

查看生成的termtree_data也包含了“静磁场”
![7EC54354-FF83-4C9D-B78D-0843FF989A35](https://user-images.githubusercontent.com/5362672/147440045-8031708f-ae1f-44ed-ae28-c716529fe186.png)

但是测试时并不是预期的静磁场为一个term。

复现代码如下：

```
import paddle
from paddlenlp import Taskflow
                 
knowledge_mining = Taskflow(
    "knowledge_mining", 
    term_schema_path="termtree_type.csv", term_data_path="termtree_data"                
    )
txts = ["静磁场中的磁场能与电场能。"]
r = knowledge_mining(txts)
print(r)

output:
[{'text': '静磁场中的磁场能与电场能。', 'items': [{'item': '静', 'offset': 0, 'wordtag_label': '修饰词', 'length': 1, 'termid': '修饰词_cb_静'}, {'item': '磁场', 'offset': 1, 'wordtag_label': '术语类', 'length': 2, 'termid': '物理术语_cb_磁场'}, {'item': '中', 'offset': 3, 'wordtag_label': '词汇用语', 'length': 1}, {'item': '的', 'offset': 4, 'wordtag_label': '助词', 'length': 1, 'termid': '助词_cb_的'}, {'item': '磁场', 'offset': 5, 'wordtag_label': '术语类', 'length': 2, 'termid': '物理术语_cb_磁场'}, {'item': '能', 'offset': 7, 'wordtag_label': '肯定词', 'length': 1, 'termid': '肯定否定词_cb_能'}, {'item': '与', 'offset': 8, 'wordtag_label': '介词', 'length': 1, 'termid': '介词_cb_与'}, {'item': '电场', 'offset': 9, 'wordtag_label': '术语类', 'length': 2, 'termid': '物理术语_cb_电场'}, {'item': '能', 'offset': 11, 'wordtag_label': '肯定词', 'length': 1, 'termid': '肯定否定词_cb_能'}, {'item': '。', 'offset': 12, 'wordtag_label': 'w', 'length': 1}]}]
```

运行环境
paddlenlp                                         2.2.1
paddlepaddle                                      2.2.0

**Comment by qhpeklh5959** [comment]
TermTree中收录的词语和WordTag的预测结果之间没有必然联系，出现这种情况一般是缺少样本，模型训不对
临时解决方案可以使用自主添加词表后处理的方式
后期我们也会保留case，定期优化
如果希望泛化可以自己定制训练WordTag模型，或者等待官方定制化接口发布

**Comment by hebo1982** [comment]
@qhpeklh5959 
感谢回复！

“临时解决方案可以使用自主添加词表后处理的方式”
这个没看到相应的接口参数或例子，希望指明一下。

**Comment by qhpeklh5959** [comment]
这个只需自行写规则处理即可，没有官方的接口

**Comment by hebo1982** [comment]
> 这个只需自行写规则处理即可，没有官方的接口

了解

**Comment by linjieccc** [comment]
> @qhpeklh5959 感谢回复！
> 
> “临时解决方案可以使用自主添加词表后处理的方式” 这个没看到相应的接口参数或例子，希望指明一下。

近期我们会在Taskflow开放一个接口来支持解语WordTag任务的自定义词典装载并适配与TermTree的linking
