### ISSUE TITLE
PaddleServing怎么部署自己训练的预训练模型？

### ISSUE THREAD

**Issue by wangqianyi2017** [PaddlePaddle/PaddleNLP#1516]
使用PaddleNLP-MIniLMv2 的训练脚本，进行模型压缩，但模型无法直接部署到paddleServing。怎么才能将model_state.pdparams的模型转化成paddleServing部署所需要的格式？

**Comment by LiuChiachi** [comment]
您好，

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/pp-minilm/finetuning/export_model.py

您可以参考这里的代码导出部署模型～

**Comment by wangqianyi2017** [comment]
报错：
![image](https://user-images.githubusercontent.com/30695606/147553517-193f98ca-bedd-475d-8443-110e0752774d.png)

**Comment by wangqianyi2017** [comment]
报错[AssertionError: pretrained base model should be BertModel]：![image](https://user-images.githubusercontent.com/30695606/147553652-021f4f59-fb6a-4c28-8c6f-52c70b531848.png)

**Comment by wangqianyi2017** [comment]
怎么样才能绕过modelType呢？

**Comment by LiuChiachi** [comment]
您好，因为example一般都是基于某个模型去展示的，目前还不能做到所有模型完全通用，所以需要您手动改一下代码，
https://github.com/PaddlePaddle/PaddleNLP/blob/4070783a5b61c7c6dc6fc603fc8c53fd99889dfe/examples/model_compression/pp-minilm/data.py#L20
这里加入"tinybert": (TinyBertForSequenceClassification, TinyBertTokenizer)，就可以支持 tinybert ，记得先在上面import一下

**Comment by ZeyuChen** [comment]
PaddleNLP v2.3会对模型提供完整的Paddle Serving支持哈 @wangqianyi2017 可以一起开源共建

**Comment by wangqianyi2017** [comment]
好的，收到，谢谢，已解决我当前遇到的问题了

**Comment by wangqianyi2017** [comment]
还有一个问题，pdparams格式的文件转成pdiparams、pdmodel、pdiparams.info无法直接在Serving中部署,仍旧需要在进行下一步的转化。
也就是说，训练好一个pdparams格式的文件，需先转化成pdiparams、pdmodel，再转换成serving_server的配置文件和模型文件？这个过程可以一步到位吗？
