### ISSUE TITLE
ernie与ernie-tiny

### ISSUE THREAD

**Issue by Fujiaoji** [PaddlePaddle/PaddleNLP#1524]
您好，请问paddlenlp对于 paddle.transformer 里面的Ernietokenizer.from_pretrain("ernie-tiny")与ErnieTinyTokenizer.from_pretrain("ernie-tiny")有什么区别吗，不太知道选择哪一个

**Comment by ZeyuChen** [comment]
ErnieTinyTokenizer.from_pretrain("ernie-tiny")
选择这个吧。@Fujiaoji
