### ISSUE TITLE
ERNIE/ernie-m/reader/task_reader.py issue with Jupyter Notebook

### ISSUE THREAD

**Issue by ericshijian** [PaddlePaddle/PaddleNLP#1525]
Hi there,

for ERNIE/ernie-m/reader/task_reader.py , line 36-40

```
if six.PY3:
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
```
may have "OutStream object has no attribute buffer" problem when using in Jupyter notebook.

One possible modification ?
```
if six.PY3:
    import io
    sys.stdout = io.TextIOWrapper(getattr(sys.stdout, "buffer", sys.stdout), encoding="utf-8")
    sys.stderr = io.TextIOWrapper(getattr(sys.stderr, "buffer", sys.stderr), encoding="utf-8")
```

Best

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-m
@ericshijian  Please try this dynamic graph version of ERNIE-M
