### ISSUE TITLE
球各位大佬帮忙解答一下，关于MRC的问题。使用自己的数据集，预测结果出现单个字的情况？

### ISSUE THREAD

**Issue by Minjuner-97** [PaddlePaddle/PaddleNLP#153]
球各位大佬帮忙解答一下~
在使用paddlepaddle的MRC代码的时候，出现以下迷惑情况。
之前使用自带数据集，预测结果是正常的；使用自己的数据集（2151个），也是正常的，预测结果还不错的；
正常结果如下：
"1612": "张国荣",
"1206": "张火丁",
"2025": "罗密欧",
"372": "刘霓娜",
"2885": "中井贵惠",
"2768": "鲁桓公",
"1969": "也遂皇后",
"4026": "钱韵玲",
"1451": "蒋友青",

后来使用自己的另外一个数据集（17199个），出现了一下情况：
"0": "唐",
"1": "作",
"2": "丁",
"3": "诺",
"4": "令",
"5": "沙",
"6": "穆",
"7": "周",
"8": "唐",
"9": "弟",

但其实，预测的是不对的，应该是正常的人名，且训练过程中，epoch = 1，batchsize = 12，在第509个batch之后，loss出现nan的情况；
目前尝试过的方法：
1、调小学习率，无用；
2、使用小数据集，不会出现loss为nan的情况。

球球各位大佬帮忙解答一下~

**Comment by smallv0221** [comment]
请问你用的是哪个代码，Dureader-robust的么，还有你使用的数据集确定格式正确么。

**Comment by Minjuner-97** [comment]
> 请问你用的是哪个代码，Dureader-robust的么，还有你使用的数据集确定格式正确么。

代码路径：paddlenlp -->example -->machine_reading_comprehension-->DuReader-robust 
使用的数据已经和源数据保持一致，但是因为我的任务和Dureader的任务不太一样， 我没有Question_id，故我使用的是每个样本的id作为questionid（可能会存在一个问题对应多个文本的情况，但是每个样本不一样）；并已经可以输入到模型当中。

**Comment by smallv0221** [comment]
训练和预测都是用的自己的数据集么

**Comment by smallv0221** [comment]
另外能给一下你使用的样例数据集么
