### ISSUE TITLE
sentiment_analysis下sh run_predict.sh报错：AssertionError: text len: 392, tag_seq len: 254

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#1537]
Traceback (most recent call last):
  File "predict.py", line 193, in <module>
    ext_results = predict_ext(args.ext_model_path, args.ext_label_path, args.test_path)
  File "predict.py", line 86, in predict_ext
    aps = decoding(text, tag_seq)
  File "/home/reclab/ai_projects/PaddleNLP-develop/applications/sentiment_analysis/utils.py", line 45, in decoding
    tag_seq), f"text len: {len(text)}, tag_seq len: {len(tag_seq)}"
AssertionError: text len: 392, tag_seq len: 254

**Comment by gongel** [comment]
你好，请问这个代码在哪呢 ？

**Comment by ArtificialZeng** [comment]
> 你好，请问这个代码在哪呢 ？

什么在哪，就是官方示例，sentiment_analysis应用里面的sh run_predict.sh 。仅仅是我用了我自己的数据。

**Comment by gongel** [comment]
好的，已经assign给负责人，麻烦 @1649759610 看看哈

**Comment by ArtificialZeng** [comment]
> 好的，已经assign给负责人，麻烦 @1649759610 看看哈
我再那个paddleNLP微信群里面。我同时安装有pp 和pp-gpu结果还是再cpu上运行的 ？？ 显存不涨，内存暴增

pip list

paddlenlp                     2.2.2
paddlepaddle                  2.2.1
paddlepaddle-gpu              2.2.1.post110

**Comment by 1649759610** [comment]
问题已解决，并已和 @ArtificialZeng 线下同步。

**Comment by luozhouyang** [comment]
这处代码其实很明显，当序列的长度大于设置的`max_seq_len`的时候，tokenizer会对序列进行截断，导致后面`decoding`的时候assert失败。解决方案要考虑：
1. 考虑设置`max_seq_len`不小于最大文本长度
2. 在文本长度超出`max_seq_len`，或者超过512的时候，对`text`也做截断处理

不知道现在代码修复了没有，如果没有我可以提供一个PR。

**Comment by luozhouyang** [comment]
哦没事了，我看到代码已经修复了。

**Comment by ZeyuChen** [comment]
Issue Resolved.
