### ISSUE TITLE
关于ERNIE-CSC的复现结果

### ISSUE THREAD

**Issue by LuckyyySTA** [PaddlePaddle/PaddleNLP#1538]
首先感谢开源ernie-csc的代码！
在尝试运行开源代码复现结果后，在sighan2013、sighan2014、sighan2015数据集上的f1结果和readme中报出的f1结果的确在一个level上，但是sighan2013数据集上的纠错和检错precision均为1，对比了当前其他的baseline在sighan2013数据集上的precision，在同样利用额外的271k数据和sighan数据集训练的情况下，在sentence级别上的最好结果应该在0.8左右。这个precision结果也比原论文的高出许多，但是在sighan2014和2015数据集上表现又正常不知是什么原因？

**Comment by joey12300** [comment]
@LuckyyySTA 实际上论文里的提到的模型是经过MLM-phonetics预训练的， 而咱们PaddleNLP的版本是直接基于ernie-1.0做finetune的，其泛化性能是不如论文中的模型，所以是可能出现在某个数据集上表现比较强，而其他数据集上效果比较一般的情况。

**Comment by LuckyyySTA** [comment]
> @LuckyyySTA 实际上论文里的提到的模型是经过MLM-phonetics预训练的， 而咱们PaddleNLP的版本是直接基于ernie-1.0做finetune的，其泛化性能是不如论文中的模型，所以是可能出现在某个数据集上表现比较强，而其他数据集上效果比较一般的情况。

感谢回复！我也注意到了，那请问readme中给出的sighan2013的结果也是precision近乎为1的结果对吗？

**Comment by joey12300** [comment]
@LuckyyySTA 合理吧，不过一般只看F1结果就行。
