### ISSUE TITLE
想实践一下语义检索，有些问题不明白想咨询一下。

### ISSUE THREAD

**Issue by dongandi** [PaddlePaddle/PaddleNLP#1545]
在neural_search项目下，的milvus里面的feature_extract.py这个路径在哪里修改呢？
![image](https://user-images.githubusercontent.com/59283713/147842714-bc65ff2d-a276-4af1-8282-9ef90bbad24c.png)
运行后，报缺少三个参数，我该怎么填写呢？感谢回复！

**Comment by tianxin1860** [comment]
你好，可以贴一下完整的运行命令？

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/milvus/scripts/feature_extract.sh

请参考这里面的参数设置

**Comment by dongandi** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/milvus/scripts/feature_extract.sh
> 
> 请参考这里面的参数设置

你好，在feature_extract.py里面需要补充的这三个参数在eature_extract.sh并没有，我就想进行第一步生成embedding向量，是需要运行feature_extract.py还是运行eature_extract.sh，
![image](https://user-images.githubusercontent.com/59283713/148668508-6f33f48b-fa36-4670-93a7-88c1da24d5ed.png)

我运行eature_extract.sh在虚拟机，报另外一个错误数据是从您们团队提供的lian链接下载的
![{AMH59N(04Y1HWQUBO@S~$2](https://user-images.githubusercontent.com/59283713/148668714-661babb6-dd11-4ebb-b6f3-3d4e601dc565.png)

**Comment by w5688414** [comment]
```
root_dir="checkpoints" 
python -u -m paddle.distributed.launch --gpus "3" --log_dir "recall_log/" \
        feature_extract.py \
        --device gpu \
        --params_path "${root_dir}/model_40/model_state.pdparams" \
        --batch_size 4096 \
        --output_emb_size 256\
        --max_seq_length 60 \
        --corpus_file "milvus/milvus_data.csv" 
```
params_path是模型的参数，corpus_file是你的文本文件，similar_text_pair是召回的测试文件，这个参数是多余的，我后面把它去除。

模型可以使用inbatchnegatives里面训练的模型：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/in_batch_negative

https://bj.bcebos.com/v1/paddlenlp/models/inbatch_model.zip

这是目录结构：

```
├── base_model.py
├── checkpoints
│   └── model_40
│       ├── model_state.pdparams
│       ├── tokenizer_config.json
│       └── vocab.txt
├── config.py
├── data.py
├── embedding_insert.py
├── embedding_recall.py
├── feature_extract.py
├── inference.py
├── milvus
│   └── milvus_data.csv
├── milvus_insert.py
├── milvus_recall.py
.......
```
