### ISSUE TITLE
使用ernie-1.0进行预处理的最后一步生成index文件，运行时时报错

### ISSUE THREAD

**Issue by MING8276** [PaddlePaddle/PaddleNLP#1546]
![ZW_`Y{QU 1UT3SYNH{)}{{E](https://user-images.githubusercontent.com/71618058/147845464-7011e853-dab5-4d2a-ae95-ee215ad40e7f.png)

报这个output文件找不到的错误

**Comment by ZHUI** [comment]
你试试，新建一下 output 文件夹？
