### ISSUE TITLE
aistudio paddle2.2.1 pip最新paddlenlp，加载roberttokenizer的vocab异常

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#1547]
notebook经典版，paddlepaddle2.2.1
!pip install --upgrade pip
!pip install --upgrade paddlenlp

执行以下语句
from functools import partial
import argparse
import os
import random
import time
import distutils.util
import collections

import numpy as np
import paddle
import paddle.nn.functional as F
import paddlenlp as ppnlp
from paddlenlp.data import Stack, Tuple, Pad
from paddlenlp.datasets import load_dataset
from paddlenlp.transformers import LinearDecayWithWarmup

# tokenizer = ppnlp.transformers.RobertaTokenizer.from_pretrained('roberta-wwm-ext')
# tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
tokenizer = ppnlp.transformers.RobertaTokenizer.from_pretrained('roberta-wwm-ext-large')
print(tokenizer.vocab)
报异常
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in __getattr__(self, name)
   1075             return self._convert_token_to_id(self.special_tokens_map[name[:-3]])
   1076         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1077             type(self).__name__, name))
   1078 
   1079     def truncate_sequences(self,
AttributeError: 'RobertaTokenizer' object has no attribute 'vocab'

如果是ernie-1.0没问题
roberta-wwm-ext有类似问题

**Comment by Steffy-zxf** [comment]
@bbbxixixixi 你好！`RoBERTaTokenizer`和 `ErnieTokenizer` 构造方式不同。

对于中文RoBERTa模型，通过以下方式获取词表:

```python
roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-wwm-ext')
roberta_tokenizer.tokenizer.vocab
```
