### ISSUE TITLE
neural_search/recall/simcse/train文件177行，前向传播计算loss的时候，报错

### ISSUE THREAD

**Issue by Wxs18337266838** [PaddlePaddle/PaddleNLP#1549]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by Wxs18337266838** [comment]
出错的原因可能是操作系统的问题吗？我用的是win10系统，

**Comment by ZeyuChen** [comment]
@Wxs18337266838 请补充详细错误的截图，好让我们更好的评估分析。

**Comment by Wxs18337266838** [comment]
您好：
&nbsp; &nbsp; &nbsp; 这是我的错误截图。我的系统是win10、paddlepaddle-gpu 2.2.1、 cuda11.2、&nbsp; cudnn8.2.1、&nbsp; paddlenlp2.2.0。
&nbsp; &nbsp; &nbsp; 另外我发现你们在飞浆官网上说cuda11.2配合cudnn v8.1.1使用，但是这样的会有警告，配合cudnn v8.2.1就不会有警告，希望你们更新一下。
感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] neural_search/recall/simcse/train文件177行，前向传播计算loss的时候，报错 (Issue #1549)





 
@Wxs18337266838 请补充详细错误的截图，好让我们更好的评估分析。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wxs18337266838** [comment]
问题已解决，请大家参考 [#1464](https://github.com/PaddlePaddle/PaddleNLP/pull/1465)

**Comment by Wxs18337266838** [comment]
您好，问题已解决。再次感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] neural_search/recall/simcse/train文件177行，前向传播计算loss的时候，报错 (Issue #1549)





 
@Wxs18337266838 请补充详细错误的截图，好让我们更好的评估分析。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
