### ISSUE TITLE
为什么distill_lstm文件夹下蒸馏出来的bilstm模型比教师模型ernie/bert还大啊？

### ISSUE THREAD

**Issue by syc22** [PaddlePaddle/PaddleNLP#1551]
老师，感谢您在百忙中阅读这封邮件，在这里麻烦帮忙答疑解惑：
蒸馏时学生模型bilstm 设置的是example/model_compression/distill_lstm/args文件中默认的参数。
![IUUCXD`8AVS{%94WU{}8F}N](https://user-images.githubusercontent.com/57344752/148019179-f909177e-7186-44a1-907f-b61e5f9b3065.png)

1.为什么蒸馏出的bilstm学生模型 .pdparams参数是2.3个G，使用paddle.summary打印出的Total params有三个多亿，比老师模型还要大。附图如下：图1为打通过paddle.summary印蒸馏后的模型参数。  图2位蒸馏出的模型.pdparams为2.3个G
2.请问paddle如何查看ernie / bert等预训练模型微调后的模型的参数大小，flops等类似paddle.summary的功能？因为需要和蒸馏后的模型做模型参数大小 ， flops运算速度上的比较。请问老师应该怎么获取ernie / bert等预训练模型以及Bilstm学生模型 模型大小和flops参数?
3.对于上面问题2的另一种问法：如何官方定量的比较蒸馏后的模型与老师模型的预测速度，模型大小？
![56582789-01F3-4f7f-A8D1-B329BA4C01EC](https://user-images.githubusercontent.com/57344752/148018974-bdaf2727-65d1-40d9-85b0-f20e8d3b9771.png)
图1
![65F9D474-7181-4deb-A536-80A8ED00CA52](https://user-images.githubusercontent.com/57344752/148018999-6cfce64b-bcc9-4806-967a-1b3be61f2f26.png)
图2

**Comment by ZeyuChen** [comment]
这个主要问题是因为词表比较大，导致的参数量较大，但实际的推理计算量时间会比ernie少很多。
实际上词表可以控制小一点，这样参数就会比较小了，因为150w词表中，大量是长尾词表。

**Comment by syc22** [comment]
可以提供一个小一点的词表嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 下午2:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 为什么distill_lstm文件夹下蒸馏出来的bilstm模型比教师模型ernie/bert还大啊？ (Issue #1551)





 
这个主要问题是因为词表比较大，导致的参数量较大，但实际的推理计算量时间会比ernie少很多。
 实际上词表可以控制小一点，这样参数就会比较小了，因为150w词表中，大量是长尾词表。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZeyuChen** [comment]
@syc22 你只需要在蒸馏的过程中
https://bj.bcebos.com/paddlenlp/data/senta_word_dict.txt
这个senta word dict的文件，砍掉尾部的词表，保留30w头部词表就习惯了。

**Comment by syc22** [comment]
请问老师，是前词典中的30W还是需要自己筛选30W出来？
如果是前30W的话，会不会存在有的词索引不到id？如果是自己筛选的话如何判断是不是尾部词呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiaqi ***@***.***&gt;; 
发送时间: 2022年1月4日(星期二) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 为什么distill_lstm文件夹下蒸馏出来的bilstm模型比教师模型ernie/bert还大啊？ (Issue #1551)





 
@syc22 你只需要在蒸馏的过程中
 https://bj.bcebos.com/paddlenlp/data/senta_word_dict.txt
 这个senta word dict的文件，砍掉尾部的词表，保留30w头部词表就习惯了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiuChiachi** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/1479

**Comment by LiuChiachi** [comment]
词表变成30w的话，砍掉的部分就是unk了吧
