### ISSUE TITLE
问个匪夷所思的问题

### ISSUE THREAD

**Issue by syc22** [PaddlePaddle/PaddleNLP#1564]
既然ernie是基于mask中文词组而非单个汉字训练出来的，那如何使用ernie1.0/ernie2.0来预测一个句子中被mask的中文词组？  因为一句话会被Ernietokernize分为一个一个的汉字，是字粒度的分词，选中一个字mask，继而id化，tensor化后送入ernie预测，仅仅能预测出对应mask位置的字。    如何来mask一个词语，继而预测一个词出来呢？   困扰了

**Comment by ZHUI** [comment]
ernie1.0 是字粒度的模型。
> 既然ernie是基于mask中文词组而非单个汉字训练出来的

这里的mask词组，可以看做同时mask掉多个字。
>  如何来mask一个词语，继而预测一个词出来呢？ 困扰了

可以选中连续的多个token一起mask。
