### ISSUE TITLE
module 'paddle' has no attribute 'inference'

### ISSUE THREAD

**Issue by githanyongjin** [PaddlePaddle/PaddleNLP#1565]
各位大佬，我安装的paddlepaddle-gpu版本是2.0.2.post100，在使用静态图进行推理时报了上面的错误，有知道是为啥的吗？

**Comment by githanyongjin** [comment]
已经解决，需要在导入包的时候不能按照案例直接导入import paddle，需要直接导入到Config：
from paddle.inference import Config，不太理解

**Comment by ZeyuChen** [comment]
首先推荐使用2.2以上更新版本哈。
应该是可以的paddle.infererence的，具体参照的是哪个案例？

**Comment by githanyongjin** [comment]
> 首先推荐使用2.2以上更新版本哈。 应该是可以的paddle.infererence的，具体参照的是哪个案例？

examples下面的rnn

**Comment by ZeyuChen** [comment]
@Steffy-zxf 看看text_classification/rnn 下的deploy脚本是否随着paddle的版本升级失效了。
