### ISSUE TITLE
如何设置差分学习率？还有如果想取bert某几层的encoder的cls信息融合后做文本分类，如何取得这些信息？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#1566]
比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？
另外就是如何提取bert 各层encoder的cls输出？
谢谢

**Comment by wawltor** [comment]
> 比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？ 另外就是如何提取bert 各层encoder的cls输出？ 谢谢

第一个问题可以这么解决 
![image](https://user-images.githubusercontent.com/16698950/148523778-0d90606c-144b-461f-9821-e1996c3c765f.png)

**Comment by wawltor** [comment]
> 比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？ 另外就是如何提取bert 各层encoder的cls输出？ 谢谢

第二个问题，这里需要改动PaddlePaddle的代码，这里的改动相对比较复杂，可以看看这块的代码，返回的时候返回中间结果https://github.com/PaddlePaddle/Paddle/blob/0883cf37bef9ca7db37ece787f3ccab3f817a9ae/python/paddle/nn/layer/transformer.py#L694

**Comment by bbbxixixixi** [comment]
> > 比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？ 另外就是如何提取bert 各层encoder的cls输出？ 谢谢
> 
> 第一个问题可以这么解决 ![image](https://user-images.githubusercontent.com/16698950/148523778-0d90606c-144b-461f-9821-e1996c3c765f.png)

我试了一下
lr_scheduler = LinearDecayWithWarmup(args.learning_rate, num_training_steps,
                                         args.warmup_proportion)
parameters = [
        {
            'params': model.classifier.parameters()
        },
        {
            'params': model.ernie.parameters(),
            'learning_rate': args.learning_rate * args.diff_lr_factor,
            'weight_decay': args.weight_decay * args.diff_lr_factor
        }
    ]

    optimizer = paddle.optimizer.AdamW(
        learning_rate=lr_scheduler,
        parameters=parameters,
        weight_decay=args.weight_decay,
        apply_decay_param_fun=lambda x: x in decay_params)

不管怎么调整diff_lr_factor（甚至设置为1，也就是无改变），训练出来的结果都比原来差很多（原来eval0.7acc，现在只有0.15左右）
是不是哪里没搞对？

**Comment by wawltor** [comment]
> > > 比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？ 另外就是如何提取bert 各层encoder的cls输出？ 谢谢
> > 
> > 
> > 第一个问题可以这么解决 ![image](https://user-images.githubusercontent.com/16698950/148523778-0d90606c-144b-461f-9821-e1996c3c765f.png)
> 
> 我试了一下 lr_scheduler = LinearDecayWithWarmup(args.learning_rate, num_training_steps, args.warmup_proportion) parameters = [ { 'params': model.classifier.parameters() }, { 'params': model.ernie.parameters(), 'learning_rate': args.learning_rate * args.diff_lr_factor, 'weight_decay': args.weight_decay * args.diff_lr_factor } ]
> 
> ```
> optimizer = paddle.optimizer.AdamW(
>     learning_rate=lr_scheduler,
>     parameters=parameters,
>     weight_decay=args.weight_decay,
>     apply_decay_param_fun=lambda x: x in decay_params)
> ```
> 
> 不管怎么调整diff_lr_factor（甚至设置为1，也就是无改变），训练出来的结果都比原来差很多（原来eval0.7acc，现在只有0.15左右） 是不是哪里没搞对？

看起来上面的使用方式是在 LinearDecayWithWarmup, 而不是在Optimizer，辛苦在Optimizer上使用该方式？

**Comment by zouhan6806504** [comment]
> > > > 比如ErnieForSequenceClassification中，我想ernie和classifier各自有不同的lr，要如何设置？ 另外就是如何提取bert 各层encoder的cls输出？ 谢谢
> > > 
> > > 
> > > 第一个问题可以这么解决 ![image](https://user-images.githubusercontent.com/16698950/148523778-0d90606c-144b-461f-9821-e1996c3c765f.png)
> > 
> > 
> > 我试了一下 lr_scheduler = LinearDecayWithWarmup(args.learning_rate, num_training_steps, args.warmup_proportion) parameters = [ { 'params': model.classifier.parameters() }, { 'params': model.ernie.parameters(), 'learning_rate': args.learning_rate * args.diff_lr_factor, 'weight_decay': args.weight_decay * args.diff_lr_factor } ]
> > ```
> > optimizer = paddle.optimizer.AdamW(
> >     learning_rate=lr_scheduler,
> >     parameters=parameters,
> >     weight_decay=args.weight_decay,
> >     apply_decay_param_fun=lambda x: x in decay_params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不管怎么调整diff_lr_factor（甚至设置为1，也就是无改变），训练出来的结果都比原来差很多（原来eval0.7acc，现在只有0.15左右） 是不是哪里没搞对？
> 
> 看起来上面的使用方式是在 LinearDecayWithWarmup, 而不是在Optimizer，辛苦在Optimizer上使用该方式？

parameters不是放在LinearDecayWithWarmup的，是放在optimizer中
 lr_scheduler = LinearDecayWithWarmup(args.learning_rate, num_training_steps, args.warmup_proportion)
这里已经结束定义了
optimizer里面使用了这种lr调整方法

**Comment by wawltor** [comment]
具体使用的是哪个示例了，麻烦提供一下复现环境，我们来debug一下

**Comment by zouhan6806504** [comment]
> 具体使用的是哪个示例了，麻烦提供一下复现环境，我们来debug一下

项目“网络事件分类”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/3401420/5421626e34284fc88f3af17af496b55f
逐行执行代码
更改启动参数diff_lr_factor即可，运行的类是train_netcase

**Comment by zouhan6806504** [comment]
> 具体使用的是哪个示例了，麻烦提供一下复现环境，我们来debug一下

我觉得找到问题了，似乎param里面的lr是乘到原始lr上，而不是替换，我是按照替换写的

**Comment by wawltor** [comment]
> > 具体使用的是哪个示例了，麻烦提供一下复现环境，我们来debug一下
> 
> 我觉得找到问题了，似乎param里面的lr是乘到原始lr上，而不是替换，我是按照替换写的

OK 解决问题就好
