### ISSUE TITLE
AssertionError: downloading from ./models/ernie-1.0/model_state.pdparams not a url

### ISSUE THREAD

**Issue by githanyongjin** [PaddlePaddle/PaddleNLP#1572]
使用ppnlp.transformers.ErnieForSequenceClassification.from_pretrained('./models/ernie-1.0/')参数为已经下载好的预训练模型的地址，报错AssertionError: downloading from ./models/ernie-1.0/model_state.pdparams not a url；这是为什么？
用 “ernie-1.0” 作为参数传入，然后让模型自己下载并加载预训练模型，这个没有报错。但是当我用下载路径指定的时候就报错了。

**Comment by ZeyuChen** [comment]
请确认下paddlenlp是否用的是最新版本，以及本地执行路径下./models/ernie-1.0/这个目录是否确实存在。@githanyongjin

**Comment by yingyibiao** [comment]
你好，使用from_pretrained接口加载本地的模型的时候需要传入模型所在文件夹地址（包含model_state.pdparams和model_config.json）。
上述方法一般是需要配合save_pretrained接口使用，先将模型通过save_pretrained接口保存在本地文件夹（会保存model_state.pdparams和model_config.json两个文件），再通过from_pretrained接口加载。
