### ISSUE TITLE
在做向量检索的时候如何处理超长文本？

### ISSUE THREAD

**Issue by tianxin1860** [PaddlePaddle/PaddleNLP#1576]
请问在做向量检索的时候，如果文档包含的文本很长，有几千字甚至上万字，而bert类模型输入token一般最多为512个，此时如何对文档向量化？

**Comment by tianxin1860** [comment]
1. 建议从超长文本中抽取出核心句子进行语义向量编码即可，核心句子长度一般不会超过 512，而且可以覆盖文档的核心语义。
2. 如果必须针对全文进行语义向量编码，建议将文档切分成多个 512 的片段即可，然后对多个片段分别进行向量编码，最后采用 mean_pooling 进行融合。

**Comment by zouhan6806504** [comment]
> 1. 建议从超长文本中抽取出核心句子进行语义向量编码即可，核心句子长度一般不会超过 512，而且可以覆盖文档的核心语义。
> 2. 如果必须针对全文进行语义向量编码，建议将文档切分成多个 512 的片段即可，然后对多个片段分别进行向量编码，最后采用 mean_pooling 进行融合。

如何确定核心句？如果也是智能抽取，那抽取过程的准确程度也会影响后面的向量编码吧

**Comment by tianxin1860** [comment]
一般通过人工先验规则抽取即可，例如: 全文每个自然段第一句话，默认是这个自然段的概括。智能抽取或者人工规则都没法做到 100% 准确，在业务系统上需要不断优化迭代。
