### ISSUE TITLE
ernie-doc imdb数据集 复现问题

### ISSUE THREAD

**Issue by zpp13** [PaddlePaddle/PaddleNLP#1578]
python3.7，paddlepaddle2.1.1，运行命令是python3.7 examples/language_model/ernie-doc/run_classifier.py --batch_size 8 --model_name_or_path ernie-doc-base-en
里面的参数没改，我看默认是imdb数据集，训练过程中，acc先上升到了0.7+，但是后来一直下降，请问有人碰到这种问题吗？
![1641885610(1)](https://user-images.githubusercontent.com/33889654/148898657-64a09c86-df71-42b7-b3f5-04a5d0a3b54d.png)
![1641885621(1)](https://user-images.githubusercontent.com/33889654/148898690-e6a47d62-4414-4c82-8515-7718efb3f1d3.png)

**Comment by zpp13** [comment]
最终训练结果是
![image](https://user-images.githubusercontent.com/33889654/149053380-db28633c-7b68-4ef9-bfd7-4638c731bfd1.png)
请问有人跑过ernie-doc的训练吗？会碰到这样的问题吗？

**Comment by joey12300** [comment]
@zpp13 由于不同任务、不同数据集所设的超参数差别较大，可查看[ERNIE-Doc](https://arxiv.org/abs/2012.15688)论文附录中具体超参设定。一般经验，batch size的值与学习率的值成正比。如下图所示，batch size为32时，学习率设为7e-5，那么当我们使用batch size为8时，那么学习率就可以往下调至1.75e-5。
![image](https://user-images.githubusercontent.com/10826371/149447206-5f6aa4a2-3583-4826-b386-a8e0b1347d2a.png)

**Comment by zpp13** [comment]
感谢回复，是我大意了，以为默认参数就是适合的参数了，我去改下参数，稍后会更新结果。

**Comment by zpp13** [comment]
记录一下：batch size=8,lr=1.75e-5,三个epoch，final Accuracy = 0.95572
