### ISSUE TITLE
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [5, 12, 12, 12] and the shape of Y = [5, 12]. Received [12] in X is not equal to [5] in Y at i:2.

### ISSUE THREAD

**Issue by ScottishFold007** [PaddlePaddle/PaddleNLP#1579]
你好！我在使用ErnieGramMode处理批量的语句的输入的时候，出现了如下报错，麻烦大牛给与指导：

![image](https://user-images.githubusercontent.com/36957508/148946063-4ee2a999-b4d4-4e6d-8c32-aff0a618dd5a.png)
代码如下：
```

inputs = {'attention_mask': 
        paddle.to_tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]),
 'input_ids': 
        paddle.to_tensor([[1 , 75, 10, 12, 20, 8 , 2 , 75, 479, 37, 12, 2 ],
         [1 , 75, 10, 12, 20, 8 , 2 , 75, 479, 37, 12, 2 ],
         [1 , 75, 10, 12, 20, 8 , 2 , 75, 479, 37, 12, 2 ],
         [1 , 75, 10, 12, 20, 8 , 2 , 75, 479, 37, 12, 2 ],
         [1 , 75, 10, 12, 20, 8 , 2 , 75, 479, 37, 12, 2 ]]),
 'token_type_ids':
       paddle.to_tensor( [[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1]])  }

print(inputs)
 
model = ErnieGramModel.from_pretrained("ernie-gram-zh")
last_hidden_state = model(**inputs)[0] 

```
报错如下：
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-64433bbcb6f2> in <module>()
     21 
     22 
---> 23 last_hidden_state = model(**inputs)[0]

8 frames
/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py in __impl__(self, other_var)
    262             axis = -1
    263             math_op = getattr(_C_ops, op_type)
--> 264             return math_op(self, other_var, 'axis', axis)
    265 
    266         comment = OpProtoHolder.instance().get_op_proto(op_type).comment

ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [5, 12, 12, 12] and the shape of Y = [5, 12]. Received [12] in X is not equal to [5] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]`

谢谢！

**Comment by JunnYu** [comment]
**首先分析报错信息：**
`Operands could not be broadcast together with the shape of X = [5, 12, 12, 12] and the shape of Y = [5, 12]` 表明在进行元素级别相加的op时候，由于两个输入的shape形状不一样，因此无法通过广播机制进行相加。
- 其中`X=[5,12,12,12]`表示的是`[batch_size, num_heads, sequence_length, sequence_length]`，这个是多头自注意力机制中`Q,K`通过矩阵乘法得到的结果。
- 而`Y=[5, 12]`表示的是模型输入`attention_mask`的维度，表示的是`[batch_size, sequence_length]`。
通过查看如下源码，发现模型当前不支持2D的`attention_mask`。
https://github.com/PaddlePaddle/PaddleNLP/blob/60608d3906862a71c96045bbbeac09b487f00e53/paddlenlp/transformers/ernie_gram/modeling.py#L286-L290
**解决方法话：**
```python
if attention_mask is None:
    attention_mask = paddle.unsqueeze(
        (input_ids == self.pad_token_id).astype(self.pooler.dense.weight.dtype) * -1e4,
        axis=[1, 2],
    )
else:
    attention_mask = paddle.unsqueeze(
        (1 - attention_mask).astype(self.pooler.dense.weight.dtype) * -1e4, axis=[1, 2]
    )
```

**Comment by ZeyuChen** [comment]
@JunnYu 这问题是否需要解决呢？需要的话提交一下pr解决下这个问题？

**Comment by JunnYu** [comment]
@ZeyuChen 现已提交PR https://github.com/PaddlePaddle/PaddleNLP/pull/1634 修复该问题。
