### ISSUE TITLE
想利用 paddleslim 来蒸馏  text_matching 中的  simcse 生成的模型,请问怎么操作?

### ISSUE THREAD

**Issue by shguan2018** [PaddlePaddle/PaddleNLP#1582]
现在 simcse 生成的模型很大, 有几百兆,  还有 simbert 中的 simbert-base-chinese 模型也很大,
怎样利用 paddleslim 来蒸馏，压缩这些模型使其变小?  有没有具体的例子可供参考?

**Comment by LiuChiachi** [comment]
您好，您可以参考
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression/ofa
进行实践，有问题欢迎再联系我们:)

感谢关注

**Comment by shguan2018** [comment]
谢谢，我试试

**Comment by shguan2018** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/simcse
此处训练以后，获得的模型比较大，400M 左右，我仅仅想获得 句子的 embedding, 但是速度慢 (CPU 环境下),  
请问，怎样能压缩，蒸馏 使模型变小，获得句向量更快?
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression  中没有类似的例子，搞不定.
谢谢

**Comment by LiuChiachi** [comment]
我理解是你需要把这里用到的ERNIE模型进行压缩，https://github.com/PaddlePaddle/PaddleNLP/blob/a5f8a3ec9d4a5363d4d3644ad06773db76a8a503/applications/neural_search/recall/simcse/model.py#L65
你可以参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression
下面的tinybert或者ofa，在下游任务上对模型进行蒸馏压缩，使模型规模减小，从而加快推理速度

**Comment by shguan2018** [comment]
多谢回复，是的，是这个意思，想对模型进行压缩蒸馏，使模型变小,可以加快推理速度（CPU 环境下）,奈何是初学者，看了好几天的 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression  文档，也没有搞定.

**Comment by LiuChiachi** [comment]
可以尝试下tinybert和ofa，先跑下例子～然后把模型和数据集换成自己的就可以实现了～

**Comment by shguan2018** [comment]
好的，谢谢， 我再试试吧
