### ISSUE TITLE
RNN文本分类模型训练命令有误

### ISSUE THREAD

**Issue by pyh13258102131** [PaddlePaddle/PaddleNLP#1590]
PaddleNLP/examples/text_classification/rnn/模块下，模型训练训练命令python train.py --vocab_path='./senta_word_dict.txt' --device=cpu --network=bilstm --lr=5e-4 --batch_size=64 --epochs=10 --save_dir='./checkpoints'中vocab_path参数多了空格，应改为python train.py --vocab_path=./senta_word_dict.txt --device=cpu --network=bilstm --lr=5e-4 --batch_size=64 --epochs=10 --save_dir='./checkpoints'，方可正常运行

**Comment by Steffy-zxf** [comment]
@pyh13258102131 感谢反馈！我们非常欢迎开发者对PaddleNLP repo贡献？不知您是否方便提PR修改其中的错误呢？

**Comment by pyh13258102131** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 下午2:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] RNN文本分类模型训练命令有误 (Issue #1590)





 
@pyh13258102131 感谢反馈！我们非常欢迎开发者对PaddleNLP repo贡献？不知您是否方便提PR修改其中的错误呢？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
