### ISSUE TITLE
小白求问：原始的数据集存在一个谓词对应两种客体的情况，所以设计的@value，但如果我要实现的关系抽取任务中，谓词与客体都是一对一的关系，不知道是否还需要设置@value呢？

### ISSUE THREAD

**Issue by Colourful10** [PaddlePaddle/PaddleNLP#1591]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by Steffy-zxf** [comment]
@Colourful10 你好！如果使用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuIE
需要添加@value
