### ISSUE TITLE
Word Tag部署

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1592]
如果想在服务端部署，并且提高推理性能，是不是可以用paddle serving对taskflow中的knowledge mining改造？

**Comment by wawltor** [comment]
> 如果想在服务端部署，并且提高推理性能，是不是可以用paddle serving对taskflow中的knowledge mining改造？

嗯嗯，后续Taskflow会增加相关的服务部署的功能。不过目前来说不太建议直接用paddle serving对Taskflow任务进行部署，更加倾向于Taskflow进行建议部署，我们后续会考虑在https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge相关目录增加部署相关代码

**Comment by chenxiaozeng** [comment]
@zhentaoCoding 您好，我们想了解下您使用knowledge mining的具体场景和推理性能要求，以便更好得支持您的需求。这是我们的联系方式：邮箱 paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下

**Comment by ZTurboX** [comment]
> 

用于合同抽取，对文章标注label。在cpu下单篇文章标注最好控制在3s内。目前我再考虑是不是可以对模型压缩蒸馏。联系方式zt950607@foxmail.com

**Comment by ZTurboX** [comment]
> @zhentaoCoding 您好，我们想了解下您使用knowledge mining的具体场景和推理性能要求，以便更好得支持您的需求。这是我们的联系方式：邮箱 [paddlenlp@baidu.com](mailto:paddlenlp@baidu.com)，方便的话可以留下您的联系方式，我们 1 对 1 沟通下

如果想对ErnieCtmWordtagModel模型做压缩，有示例吗
