### ISSUE TITLE
文本匹配当中的simbert 模型找不到，不支持

### ISSUE THREAD

**Issue by hongdd** [PaddlePaddle/PaddleNLP#1594]
Traceback (most recent call last):
  File "predict.py", line 89, in <module>
    'simbert-base-chinese', pool_act='linear')
  File "/data/miniconda3/envs/paddle2.1/lib/python3.6/site-packages/paddlenlp/transformers/model_utils.py", line 204, in from_pretrained
    ), pretrained_model_name_or_path))
ValueError: Calling BertModel.from_pretrained() with a model identifier or the path to a directory instead. The supported model identifiers are as follows: dict_keys(['bert-base-uncased', 'bert-large-uncased', 'bert-base-multilingual-uncased', 'bert-base-cased', 'bert-base-chinese', 'bert-base-multilingual-cased', 'bert-large-cased', 'bert-wwm-chinese', 'bert-wwm-ext-chinese']), but got: simbert-base-chinese

**Comment by wawltor** [comment]
simbert和BERTModel这块的是有区别的，所以功能没有通过from_pretrained来展示；可以直接使用Taskflow来使用相关功能 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E6%96%87%E6%9C%AC%E7%9B%B8%E4%BC%BC%E5%BA%A6
