### ISSUE TITLE
DNN语言模型

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1600]
百度AI开放平台中DNN语言模型计算词在句子中的概率和ppl是怎么做的？是用transformer类的预训练语言模型吗？有么有学习案例？

**Comment by smallv0221** [comment]
Could you please provide the link of the DNN lm project?

**Comment by ZTurboX** [comment]
> Could you please provide the link of the DNN lm project?

https://ai.baidu.com/ai-doc/NLP/0k6z52fb4
