### ISSUE TITLE
cannot import name 'ErnieGramTokenizer' from 'paddlenlp.transformers'

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#1601]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
![12](https://user-images.githubusercontent.com/75974455/149953270-8978e908-0b6d-4db2-9bc0-f29258acaa99.jpg)
我不懂为啥会出现这个导包的错误问题，https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.transformers.ernie_gram.tokenizer.html?highlight=ErnieGramTokenizer，我是直接复制其中案例的，是最近不支持吗

**Comment by wawltor** [comment]
辛苦提供一下PaddleNLP的版本

**Comment by hl123-123** [comment]
Successfully installed paddlenlp-2.2.3
