### ISSUE TITLE
Albert推理稳定性问题

### ISSUE THREAD

**Issue by hermitgreen** [PaddlePaddle/PaddleNLP#1604]
PaddleNLP 2.2.3，PaddlePaddle-gpu 2.2.1
Python 3.8.11 Linux

发现在使用过程中，不同的batch_size得到的结果截然不同的，
我尝试输出了一下pooled_output，发现batch_size分别为32和64的，总共长度为128的数据集，在L33出现了diff，

```python
import paddle
from paddlenlp.transformers import AlbertTokenizer
from paddlenlp.transformers import AlbertModel
from paddlenlp.data import Pad
paddle.set_device("gpu")
model = AlbertModel.from_pretrained('albert-chinese-small')
tokenizer = AlbertTokenizer.from_pretrained('albert-chinese-small')
model.eval()

batchify_fn = lambda samples, fn=Pad(
    axis=0,
    pad_val=tokenizer.pad_token_id,
): fn(samples)

raw_inputs = [f"Paddle{i}好用的不得了" for i in range(128)]
batch_size = 32 #调整这里的batch_size

encode_inputs = [
    tokenizer(text=raw_input, max_seq_len=128)
    for raw_input in raw_inputs
]
encode_input_ids = [
    encode_input['input_ids']
    for encode_input in encode_inputs
]
batches = [
    encode_input_ids[idx:idx + batch_size]
    for idx in range(0, len(encode_input_ids), batch_size)
]
batchify_fn = lambda samples, fn=Pad(
    axis=0,
    pad_val=tokenizer.pad_token_id,
): fn(samples)
pool_ = []
for batch in batches:
    input_ids = paddle.to_tensor(batchify_fn(batch))
    _sequence_output, pooled_output = model(input_ids=input_ids)
    pool_.extend(pooled_output.tolist())
for vec in pool_:
    print(vec)
```

**Comment by hermitgreen** [comment]
运行命令 python xxx.py > res
在上述的输出中，从L33开始出现diff

**Comment by yingyibiao** [comment]
感谢您的问题～
对于Albert模型，模型推理时候需要传入 attention_mask 来mask掉不需要的token。
可以通过 tokenizer(text=raw_input, max_seq_len=128, return_attention_mask=True) 输出相应的attention_mask。

**Comment by hermitgreen** [comment]
> 感谢您的问题～ 对于Albert模型，模型推理时候需要传入 attention_mask 来mask掉不需要的token。 可以通过 tokenizer(text=raw_input, max_seq_len=128, return_attention_mask=True) 输出相应的attention_mask。

加上这段以后，在L33仍然发现了diff

**Comment by yingyibiao** [comment]
> > 感谢您的问题～ 对于Albert模型，模型推理时候需要传入 attention_mask 来mask掉不需要的token。 可以通过 tokenizer(text=raw_input, max_seq_len=128, return_attention_mask=True) 输出相应的attention_mask。
> 
> 加上这段以后，在L33仍然发现了diff

同如流沟通，需要在模型输入处传入attention_mask参数～

**Comment by ZTurboX** [comment]
> > > 感谢您的问题～ 对于Albert模型，模型推理时候需要传入 attention_mask 来mask掉不需要的token。 可以通过 tokenizer(text=raw_input, max_seq_len=128, return_attention_mask=True) 输出相应的attention_mask。
> > 
> > 
> > 加上这段以后，在L33仍然发现了diff
> 
> 同如流沟通，需要在模型输入处传入attention_mask参数～

albert转静态图报错
![image](https://user-images.githubusercontent.com/5669444/154596982-ad4effd1-5d2b-4164-9cb5-4bf588a8f957.png)
代码：
`model = AlbertForMaskedLM.from_pretrained('../checkpoints/albert-chinese-tiny')
    model.eval()
    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64"),  
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64") ,
            paddle.static.InputSpec(
                shape=[None, None], dtype="int64"),
        ])

    paddle.jit.save(model, '../checkpoints/albert-chinese-tiny/static')`

**Comment by ZeyuChen** [comment]
> > > > 感谢您的问题～ 对于Albert模型，模型推理时候需要传入 attention_mask 来mask掉不需要的token。 可以通过 tokenizer(text=raw_input, max_seq_len=128, return_attention_mask=True) 输出相应的attention_mask。
> > > 
> > > 
> > > 加上这段以后，在L33仍然发现了diff
> > 
> > 
> > 同如流沟通，需要在模型输入处传入attention_mask参数～
> 
> albert转静态图报错 ![image](https://user-images.githubusercontent.com/5669444/154596982-ad4effd1-5d2b-4164-9cb5-4bf588a8f957.png) 代码： `model = AlbertForMaskedLM.from_pretrained('../checkpoints/albert-chinese-tiny') model.eval() model = paddle.jit.to_static( model, input_spec=[ paddle.static.InputSpec( shape=[None, None], dtype="int64"), paddle.static.InputSpec( shape=[None, None], dtype="int64") , paddle.static.InputSpec( shape=[None, None], dtype="int64"), ])
> 
> ```
> paddle.jit.save(model, '../checkpoints/albert-chinese-tiny/static')`
> ```

这一问题会在月底paddle 2.3rc版本发版后PaddleNLP同步解决 @zhentaoCoding
