### ISSUE TITLE
PaddleNLP/blob/develop/applications/neural_search/recall/in_batch_negative/  中的模型访问速度很慢

### ISSUE THREAD

**Issue by shguan2018** [PaddlePaddle/PaddleNLP#1607]
环境:
paddlenlp 2.2.3
paddlepaddle-gpu 2.21.post110
paddle-serving  0.7.0

使用的模型
https://bj.bcebos.com/v1/paddlenlp/models/inbatch_model.zip

in_batch_negative 项目中,使用 export_to_serving.py 导出将来在 paddle serving 所使用的模型，成功
然后,使用 deploy/python/web_service.py 来启动加载模型.
用 rpc_client.py 能访问,能获得句子向量, 但速度很慢.

但  deploy/python/predict.py 直接访问 inference.get_pooled_embedding.pdiparams,能获得句子向量,速度就非常快. (用 export_model.py 导出的模型)

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/requirements.txt
安装一下requirements：

```
paddle-serving-app>=0.7.0        
paddle-serving-client>=0.7.0        
paddle-serving-server-gpu>=0.7.0.post102
```

**Comment by shguan2018** [comment]
都装了.

**Comment by w5688414** [comment]
> 都装了.

paddle-server装gpu版本试试，paddle-serving-server-gpu
