### ISSUE TITLE
text_to_knowledge：ernie-ctm训练

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#1608]
您好：

在使用ERNIE-CTM微调wordtag中生成的模型文件为model_state.pdparams；
使用自定义模型 wordtag = Taskflow("knowledge_mining", task_path="./custom_task_path/")
程序加载过程中还是会去下载model_state.pdparms

请问model_state.pdparms和model_state.pdparams的区别是什么

使用环境
paddlenlp 2.2.3
paddlepaddle 2.2.1

**Comment by ZHUI** [comment]
应该都是，`pdparams` , 命名有误。

**Comment by kg-nlp** [comment]
手动修改ok

**Comment by linjieccc** [comment]
@kg-nlp  感谢反馈~已提PR修改
