### ISSUE TITLE
纠正错别字问题

### ISSUE THREAD

**Issue by dengmingD** [PaddlePaddle/PaddleNLP#1610]
纠正错别字：
输入：叁任伍佰万元整 
输出：叁年伍佰万元整 
目标输出：叁仟伍佰万元整
有什么好思路，谢谢

**Comment by dengmingD** [comment]
from paddlenlp import Taskflow
text_correction = Taskflow("text_correction")
res = text_correction('今天签了份大合同，金额有叁任伍佰万元整。')
print(res)


[{'source': '今天签了份大合同，金额有叁任伍佰万元整。', 'target': '今天签了份大合同，金额有叁年伍佰万元整。', 'errors': [{'position': 13, 'correction': {'任': '年'}}]}]

**Comment by joey12300** [comment]
@dengmingD  请问你有一套完整的纠错数据集吗？目前TaskFlow的纠错模型是基于Automatic Corpus Generation生成的中文纠错数据集以及SIGHAN数据集上训练的，如果你有一套详尽的纠错数据集，可以参考以下链接训练你的纠错模型：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc
