### ISSUE TITLE
seqeval 依赖问题

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleNLP#1611]
PaddleSpeech 目前的依赖有 paddlenlp, paddlenlp 有个依赖是 seqeval, 由于未知问题，PaddleSpeech 在 CI 流水线上安装 seqeval 的时候总会 hang 住，严重影响 CI ， seqeval 是否是 paddlenlp 的强依赖，是否可以删掉呢？
（当然 seqeval 可能是很多库的依赖，因为 ocr  CI 的时候不会下载 paddlenlp， 但是也下载 seqeval 了，也 hang 了）

**Comment by ZeyuChen** [comment]
@yt605155624 seqeval应该是个很常见下载量很大的依赖，本身不大，是否可以让QA检查下这块的CI流水线网络有问题？如果OCR也有同样问题的话，应该着重解决这个网络问题。
