### ISSUE TITLE
Taskflow 无法指定显卡

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#1613]
您好：

wordtag = Taskflow("knowledge_mining", model="wordtag", device_id=3,task_path="./custom_task_path/",linking=False)
指定显卡序列3 
但在程序运行时仍然要判断0号显卡
Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

使用环境
paddlenlp 2.2.3
paddlepaddle 2.2.1

**Comment by linjieccc** [comment]
您好，`unset CUDA_VISIBLE_DEVICES`后再试下呢
![image](https://user-images.githubusercontent.com/40840292/150338308-1665a87d-7755-4734-a9aa-0a81a09af619.png)

**Comment by kg-nlp** [comment]
您好，仍然存在问题

`[2022-01-21 09:09:58,123] [    INFO] - Already cached /home/zhangyj-n/.paddlenlp/models/wordtag/vocab.txt
[2022-01-21 09:09:58,158] [    INFO] - Already cached /home/zhangyj-n/.paddlenlp/models/wordtag/wordtag_pos.pdparams
W0121 09:09:58.161566 184825 device_context.cc:447] Please NOTE: device: 2, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0121 09:09:58.169664 184825 device_context.cc:465] device: 2, cuDNN Version: 7.6.
[2022-01-21 09:10:05,785] [    INFO] - Converting to the inference model cost a little time.
[2022-01-21 09:10:09,733] [    INFO] - The inference model save in the path:./custom_task_path/static/inference

InvalidArgumentError: The start row index must be less than the end row index.But received the start index = 1, the end index = 1.
      [Hint: Expected begin_idx < end_idx, but received begin_idx:1 >= end_idx:1.] (at /paddle/paddle/fluid/framework/tensor.cc:120)
      [operator < viterbi_decode > error]`

**Comment by kg-nlp** [comment]
设置为device_id = 0 程序正常运行

**Comment by a101269** [comment]
我也遇到同样问题

**Comment by linjieccc** [comment]
@joey12300 辛苦帮忙看下这个问题
