### ISSUE TITLE
wordTag是否支持自定义词典

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#1617]
您好：
      在使用taskflow 的 wordtag模式，有些词错误切分，是否支持自定义词典强制校正

使用环境
paddlenlp 2.2.3
paddlepaddle 2.2.1

**Comment by linjieccc** [comment]
您好，WordTag支持用户装载自定义词典对输出结果进行干预，可以参考这里的使用示例：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%8D%E5%85%B8-3

**Comment by hebo1982** [comment]
paddlenlp 2.2.3 不行的

需要用develop版本

**Comment by kg-nlp** [comment]
@linjieccc 谢谢，已经测试通过了
@ananas-hebo 
谢谢，我目前在paddlenlp 2.2.3这个环境测试是没有问题的
