### ISSUE TITLE
你好，我在复现语义检索但是出现一些问题

### ISSUE THREAD

**Issue by wozhendexihua1** [PaddlePaddle/PaddleNLP#1619]
环境是虚拟机，日志上出现了PaddleNLP-develop/applications/neural_search/venv/bin/python: can't open file 'feature_extract.py': [Errno 2] No such file or directory
我在使用milvus运行feature_extract.sh想生成向量
![image](https://user-images.githubusercontent.com/98111275/150379569-f9dcb5b2-d1f1-4aa8-9744-f1fddc39b488.png)
报的错如图所示

**Comment by w5688414** [comment]
确保你运行的目录有：

```
feature_extract.py
```
文件
教程里的运行是：

```
sh scripts/feature_extract.sh
```
在scripts外面运行的

**Comment by gaojing8500** [comment]
路径不对

**Comment by wozhendexihua1** [comment]
> 确保你运行的目录有：
> 
> ```
> feature_extract.py
> ```
> 
> 文件 教程里的运行是：
> 
> ```
> sh scripts/feature_extract.sh
> ```
> 
> 在scripts外面运行的

很感谢，我报的另外一个问题ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.查看日志后是模型没读进来吗？
![image](https://user-images.githubusercontent.com/98111275/150637044-9661bd17-18a0-4790-8708-75fde1065590.png)

**Comment by w5688414** [comment]
> > 确保你运行的目录有：
> > ```
> > feature_extract.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 文件 教程里的运行是：
> > ```
> > sh scripts/feature_extract.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在scripts外面运行的
> 
> 很感谢，我报的另外一个问题ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.查看日志后是模型没读进来吗？ ![image](https://user-images.githubusercontent.com/98111275/150637044-9661bd17-18a0-4790-8708-75fde1065590.png)

这看上去是你的gpu没配置正确，然后你现在使用的是cpu，有点慢
