### ISSUE TITLE
NLP数据标注

### ISSUE THREAD

**Issue by pyh13258102131** [PaddlePaddle/PaddleNLP#1623]
examples\information_extraction\msra_ner实体命名识别，目前想用自己的文本数据来进行训练模型，请问有没有什么办法或者工具可以将我自己的文本数据标注为符合训练格式的数据呢

**Comment by tianxin1860** [comment]
> examples\information_extraction\msra_ner实体命名识别，目前想用自己的文本数据来进行训练模型，请问有没有什么办法或者工具可以将我自己的文本数据标注为符合训练格式的数据呢

为了保证标注效果，建议人工将自己的数据按照标注格式处理好。
