### ISSUE TITLE
You are going to using gloo on windows, but currently is not supported

### ISSUE THREAD

**Issue by zy41796745** [PaddlePaddle/PaddleNLP#1625]
1）PaddlePaddle版本：PaddlePaddle2.2.2
2）系统环境：Windows
一运行就报：You are going to using gloo on windows, but currently is not supported

**Comment by tianxin1860** [comment]
请问运行什么代码报这个错？

**Comment by zy41796745** [comment]
您好老师，给我感觉像是model_state.pdparams这个文件格式不对导致的，我https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/question_matching下载的model_state.pdparams文件的文件夹是model_20000命名的，我看网页中示例代码中是model_10000文件夹命名的，所以我想是不是我下载的版本不对，详细的错误堆栈，我贴在下面了，老师帮忙指导一下哈，谢谢老师。
&nbsp;&nbsp;python -u \
    predict.py \     --device gpu \     --params_path "./checkpoints/model_10000/model_state.pdparams" \     --batch_size 128 \     --input_file "${test_set}" \     --result_file "predict_result"

(questionmatchevn) (base) ***@***.*** question_matching]# python -u&nbsp; &nbsp; &nbsp;predict.py&nbsp; &nbsp; &nbsp;--device cpu&nbsp; &nbsp; &nbsp;--params_path ./checkpoints/model_20000/model_state.pdparams&nbsp; &nbsp; &nbsp;--batch_size 128&nbsp; &nbsp; &nbsp;--input_file dev.txt&nbsp; &nbsp; &nbsp;--result_file result.txt
/home/questionmatchevn/lib/python3.7/site-packages/paddlenlp/transformers/funnel/modeling.py:31: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
&nbsp; from collections import Iterable
[2022-01-22 21:47:05,311] [&nbsp; &nbsp; INFO] - Already cached /root/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
[2022-01-22 21:47:13,460] [&nbsp; &nbsp; INFO] - Already cached /root/.paddlenlp/models/ernie-gram-zh/vocab.txt
Loaded parameters from ./checkpoints/model_20000/model_state.pdparams
Traceback (most recent call last):
&nbsp; File "predict.py", line 115, in <module&gt;
&nbsp; &nbsp; y_probs = predict(model, test_data_loader)
&nbsp; File "predict.py", line 71, in predict
&nbsp; &nbsp; batch_logits = np.concatenate(batch_logits, axis=0)
&nbsp; File "<__array_function__ internals&gt;", line 6, in concatenate
ValueError: need at least one array to concatenate





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 中午1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] You are going to using gloo on windows, but currently is not supported (Issue #1625)





 
请问运行什么代码报这个错？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
