### ISSUE TITLE
基于特定领域的多轮对话系统

### ISSUE THREAD

**Issue by QianMuluo** [PaddlePaddle/PaddleNLP#1626]
如何使用pddlenlp提供的预训练模型基础上，采用少量的对话样本（几百条），实现在特定领域的多轮对话呢？
目前现实场景是在心理咨询领域，针对用户提出的心理咨询问题进行回答或推荐有关资料，进行多轮对话，达到一定的心理咨询效果

**Comment by smallv0221** [comment]
您好，目前PaddleNLP的UnifiedTransformer系列模型可以实现多轮对话，您可以参考[unifiedtransformer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer)下的示例进行finetune，但是只有几百条数据可能得不到太好的效果。

**Comment by gaojing8500** [comment]
如果对话数据较少可以采用传统方式处理，比如词槽方式，随着冷启动方案数据增加后，在采用DNN系列算法

**Comment by QianMuluo** [comment]
> 您好，目前PaddleNLP的UnifiedTransformer系列模型可以实现多轮对话，您可以参考[unifiedtransformer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer)下的示例进行finetune，但是只有几百条数据可能得不到太好的效果。

好的，谢谢；目前这种策略估计不可行了，因为很难限定回答的领域或者方向，当前所需要的对话是需要结合一定的背景知识引导到某个特定方向

**Comment by QianMuluo** [comment]
> 如果对话数据较少可以采用传统方式处理，比如词槽方式，随着冷启动方案数据增加后，在采用DNN系列算法

谢谢。现在确实计划采用词槽+特定对话流程的方式，不过效果很差，需要构建一种相对丰富的对话逻辑，一旦跳转出来就会无法进行下去。

**Comment by smallv0221** [comment]
> > 您好，目前PaddleNLP的UnifiedTransformer系列模型可以实现多轮对话，您可以参考[unifiedtransformer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer)下的示例进行finetune，但是只有几百条数据可能得不到太好的效果。
> 
> 好的，谢谢；目前这种策略估计不可行了，因为很难限定回答的领域或者方向，当前所需要的对话是需要结合一定的背景知识引导到某个特定方向

UnifiedTransformer是可以做知识型对话的，可以将领域信息构造成知识引入训练。有可能成功引导对话方向。

**Comment by QianMuluo** [comment]
> 

多谢，几个小一些的模型试过了，问了几句之后陷入了死循环……最大的那个模型没有足够资源尝试；现在需求又发生了变化，这种对话机器人已经用不到了。
