### ISSUE TITLE
ERNIE-doc分类问题 出现CUDA

### ISSUE THREAD

**Issue by Maydaytyh** [PaddlePaddle/PaddleNLP#1627]
paddlepaddle和paddlenlp版本信息如下图所示
![image](https://user-images.githubusercontent.com/13815598/150632430-d8ef35ea-19f9-4264-8127-a256adcfa190.png)

当我设置max_seq_length为1024时，会出现如下报错，但是设置为512，便可以正常运行。
![image](https://user-images.githubusercontent.com/13815598/150686048-1d3fe629-47b4-4b6d-b78c-8ebc24bb5b08.png)

如果使用cpu运行会出现下图的错误看之前的issue出现这样的情况是词表和输入文本大小不匹配？这里不太理解，词表指的是什么呢，是vocab.txt吗？如果是vocab.txt的话，这个大小也对不上呀，求解答。
![image](https://user-images.githubusercontent.com/13815598/150686023-b059104c-541c-400a-9cd7-4d600b0bbcf4.png)

**Comment by joey12300** [comment]
@Maydaytyh 你好，ernie-doc是将长文本切成若干个等长的短文本，再分别输入到以ernie为核心的模型里。而ernie只能接受长度小于等于512的文本，输入1024长度的会出现错误。

**Comment by Maydaytyh** [comment]
> 
soga，了解了，其实ernie-doc是将长文本分割成若干个短文本后，在训练的时候也会同时考虑多个短文本，而不是把每个短文本当做一个独立的样本来进行训练对吧？

**Comment by Maydaytyh** [comment]
> @Maydaytyh 你好，ernie-doc是将长文本切成若干个等长的短文本，再分别输入到以ernie为核心的模型里。而ernie只能接受长度小于等于512的文本，输入1024长度的会出现错误。

@joey12300  soga，了解了，其实ernie-doc是将长文本分割成若干个短文本后，在训练的时候也会同时考虑多个短文本，而不是把每个短文本当做一个独立的样本来进行训练对吧？

**Comment by joey12300** [comment]
> > 
> 
> soga，了解了，其实ernie-doc是将长文本分割成若干个短文本后，在训练的时候也会同时考虑多个短文本，而不是把每个短文本当做一个独立的样本来进行训练对吧？

是的，以往的预训练模型都是采取截断的方式，将过长的部分舍弃掉。而ernie-doc是把长文本中所有部分都考虑到了，不存在舍弃。

**Comment by Maydaytyh** [comment]
> > > 
> > 
> > 
> > soga，了解了，其实ernie-doc是将长文本分割成若干个短文本后，在训练的时候也会同时考虑多个短文本，而不是把每个短文本当做一个独立的样本来进行训练对吧？
> 
> 是的，以往的预训练模型都是采取截断的方式，将过长的部分舍弃掉。而ernie-doc是把长文本中所有部分都考虑到了，不存在舍弃。
明白了，感谢！
