### ISSUE TITLE
ernie-gram运行添加attention_mask报错

### ISSUE THREAD

**Issue by turkeymz** [PaddlePaddle/PaddleNLP#1631]
- 版本、环境信息
1）PaddleNLP 2.2.3，PaddlePaddle-gpu 2.2.1.post101  
2）系统环境：aistudio python3.7
- 复现信息：
使用ernie-gram直接跑千言文本相似度时，如果输入加上attention_mask会报错。差不多的代码假设在pytorch里面能运行成功。
具体错误如下：
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [256, 12, 64, 64] and the shape of Y = [256, 64]. Received [64] in X is not equal to [256] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]

- 源码地址：
https://aistudio.baidu.com/aistudio/projectdetail/3433576

- 对应文件
裸跑BERT.ipynb：paddle使用ernie-gram
Torch版.ipynb：PyTorch使用chinese-bert-wwm-ext

**Comment by JunnYu** [comment]
问题与https://github.com/PaddlePaddle/PaddleNLP/issues/1579 一致

**Comment by turkeymz** [comment]
感谢回答。那能不能将这种转换添加到模型里面？因为现在感觉就像是tokenizer出来的数据不能直接用于模型

**Comment by JunnYu** [comment]
现在已经提交了 PR #1634  修复该问题
