### ISSUE TITLE
knowledge mining

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1639]
![image](https://user-images.githubusercontent.com/5669444/151083155-e175cfc9-3a84-49d9-86bb-5e3a760a38c5.png)
knowledge mining中batch_size是在_preprocess_text函数中通过 self.kwargs中拿到的，为什么在初始化中还要设置batch_size参数，而如果把初始化中batch_size参数去掉，在用TaskFlow中设置batch_size,输入多个文本，在_decode中会报IndexError: list index out of range

_decode中tags是否应该改成这样的
`tags = [
                self._index_to_tags[index]
                for index in batch_pred_tags[sent_index][self.summary_num:len(sent) + self.summary_num]
            ]
`

**Comment by linjieccc** [comment]
@zhentaoCoding 这里batch_size确实重复了，已提PR修复#1642，感谢指出！
