### ISSUE TITLE
plato2支持model.generate方法吗？

### ISSUE THREAD

**Issue by zhanghaoie** [PaddlePaddle/PaddleNLP#1644]

**Comment by smallv0221** [comment]
PLATO2 do not support model.generate(). Sorry for the inconvenience.

**Comment by zhanghaoie** [comment]
> PLATO2 do not support model.generate(). Sorry for the inconvenience.

Is there a tutorial that describes how to enable fast generation for unsupported models.

**Comment by smallv0221** [comment]
Do you mean FasterGeneration? FasterGeneration is only available for some of the models that support `model.generate()`. You can see [here](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/faster/faster_generation/README.md) for more information.

**Comment by zhanghaoie** [comment]
> Do you mean FasterGeneration? FasterGeneration is only available for some of the models that support `model.generate()`. You can see [here](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/faster/faster_generation/README.md) for more information.

yeah, thank you for you reply. The difference between plato2 generation part and unified language model is that plato2 has a latent embedding layer. If I add this layer in the code of unified language model, can the fast generation work?

**Comment by smallv0221** [comment]
I'm afraid not. PLATO2 doesn't  support `generate` because it is not in `PreTrainedModel` format like other models in `paddlenlp/transformers/`.

**Comment by zhanghaoie** [comment]
> I'm afraid not. PLATO2 doesn't support `generate` because it is not in `PreTrainedModel` format like other models in `paddlenlp/transformers/`.

ok, thank u. Do you have a plan to support it later?

**Comment by smallv0221** [comment]
Sorry We don't have that plan for now. You can use `unified_transformer-12L-cn` or `plato-mini` for dialogue generation.
