### ISSUE TITLE
ERNIE 1.0  预训练阶段, 三种mask的顺序

### ISSUE THREAD

**Issue by MosBest** [PaddlePaddle/PaddleNLP#1645]
你好! 想问一下,在ERNIE 1.0  预训练阶段  , 字-level,  短语-level, 实体-level   是
方式一:
        如源码一样,  
   
             `       for index, file_ in enumerate(files):

                             file_, mask_word_prob = file_.strip().split("\t")

                           mask_word = (np.random.random() < float(mask_word_prob))

                        if mask_word:

                             self.mask_type = "mask_word"

                        else:

                            self.mask_type = "mask_char"

                      ... 
                
                             sample.append(mask_word)
`
      对不同的文件, 通过random的方式 随机选择 是 mask_word 还是 mask_char?  那么文件是不复用吗?  mask_word和mask_char 是按文件交替进行?

还是
方式二:
    多阶段训练:
       比如 百科数据,  先全部进行mask  char ;  
      然后 所有数据都分词成短语, 全部进行mask word; 
      最后 所有数据都切成 实体, 全部进行mask word;
也就是每个数据集都会用3次, 然后  mask_word和mask_char 不是交替进行, 而是 mask_char 都预训练完后, 再继续mask_word  ?

**Comment by ZHUI** [comment]
@Meiyim  可以帮忙具体解答一下。

> 对不同的文件, 通过random的方式 随机选择 是 mask_word 还是 mask_char? 那么文件是不复用吗? mask_word和mask_char 是按文件交替进行?

看代码的话，多个epoch训练的话，文件是复用的。每次的  mask_word和mask_char 是随机的。

> 比如 百科数据, 先全部进行mask char ;
然后 所有数据都分词成短语, 全部进行mask word;
最后 所有数据都切成 实体, 全部进行mask word;
也就是每个数据集都会用3次, 然后 mask_word和mask_char 不是交替进行, 而是 mask_char 都预训练完后, 再继续mask_word ?

短语和实体应该是可以一起切分。应该是像上面说的，每次遇到的文件  mask_word和mask_char 是随机的。

我这边不是原始 ernie-1.0 的作者，一些细节上的问题。可以详细咨询 @Meiyim 同学。

PaddleNLP 这边提供的 ernie-1.0 复现版本，是基于的 wwm 方式，没有用mask_char混合：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
