### ISSUE TITLE
找不到README中介绍的程序文件

### ISSUE THREAD

**Issue by Wxs18337266838** [PaddlePaddle/PaddleNLP#1647]
请问“neural_search/recall.data_tools”的README文件中的这句话:“ernie预训练的代码在examples/language_model/ernie-1.0”中的”examples/language_model/ernie-1.0”文件在哪里？

**Comment by Wxs18337266838** [comment]
在该README中还有一句话“建议修改 run_static.sh 中的配置，将max_steps设置小一些。”，这里的 run_static.sh也找不到。

**Comment by JunnYu** [comment]
如果我没看错的话，应该是这里https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
