### ISSUE TITLE
预训练语言模型的工程落地实例

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1655]
希望paddleNLP多推出一些预训练语言模型的工程落地实例，比如预训练语言模型通用的模型压缩方法，目前的模型压缩实例，如果换了其他的模型，上手有点困难。

**Comment by LiuChiachi** [comment]
您好，感谢关注！
请问您是在使用哪个模型压缩实例的时候遇到了问题，可以举个例子吗～

**Comment by ZTurboX** [comment]
> 您好，感谢关注！ 请问您是在使用哪个模型压缩实例的时候遇到了问题，可以举个例子吗～

想使用ernie系列的模型做序列标注，感觉文档写的不是很明确

**Comment by shguan2018** [comment]
> 预训练语言模型的工程落地实例，比如预训练语言模型通用的模型压缩方法

同感, 前段时间试试 simcse 的模型压缩,搞了好几天，也搞不定,放弃了

**Comment by LiuChiachi** [comment]
感谢反馈，模型压缩这快我们之后会优化，包括文档，提升用户体验。感谢关注:)
