### ISSUE TITLE
The current variable type is (int64_t), but the previous variable type is (int)

### ISSUE THREAD

**Issue by liuyang77886** [PaddlePaddle/PaddleNLP#1660]
- 版本、环境信息
1）paddle2.2.2          ppnlp2.2.4
2）系统环境： Windows10，Python 3.8.10
运行 aistudio《动手搭建一套语义检索系统-学术文献检索 》 
在代码  模型训练  处报错

save_dir='checkpoint'
save_steps=100
time_start=time.time()
global_step = 0
tic_train = time.time()
for epoch in range(1, epochs + 1):
    for step, batch in enumerate(train_data_loader, start=1):
        query_input_ids, query_token_type_ids, title_input_ids, title_token_type_ids = batch
        print(type(query_input_ids),type(title_input_ids),type(query_token_type_ids),type(title_token_type_ids))
        print(query_input_ids.dtype,title_input_ids.dtype,query_token_type_ids.dtype,title_token_type_ids.dtype)
        loss = model(
                query_input_ids=query_input_ids,
                title_input_ids=title_input_ids,
                query_token_type_ids=query_token_type_ids,
                title_token_type_ids=title_token_type_ids)

报错信息：

<class 'paddle.Tensor'> <class 'paddle.Tensor'> <class 'paddle.Tensor'> <class 'paddle.Tensor'>
paddle.int32 paddle.int32 paddle.int32 paddle.int32
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-723e6ca6ba6f> in <module>
      9         print(type(query_input_ids),type(title_input_ids),type(query_token_type_ids),type(title_token_type_ids))
     10         print(query_input_ids.dtype,title_input_ids.dtype,query_token_type_ids.dtype,title_token_type_ids.dtype)
---> 11         loss = model(
     12                 query_input_ids=query_input_ids,
     13                 title_input_ids=title_input_ids,

E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py in __call__(self, *inputs, **kwargs)
    915 
    916     def __call__(self, *inputs, **kwargs):
--> 917         return self._dygraph_call_func(*inputs, **kwargs)
    918 
    919     def forward(self, *inputs, **kwargs):

E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py in _dygraph_call_func(self, *inputs, **kwargs)
    905             self._built = True
    906 
--> 907         outputs = self.forward(*inputs, **kwargs)
    908 
    909         for forward_post_hook in self._forward_post_hooks.values():

<ipython-input-7-9ba70d7d78ea> in forward(self, query_input_ids, title_input_ids, query_token_type_ids, query_position_ids, query_attention_mask, title_token_type_ids, title_position_ids, title_attention_mask)
    103         # 第 1 次编码: 文本经过无监督语义索引模型编码后的语义向量
    104         # [N, 768]
--> 105         query_cls_embedding = self.get_pooled_embedding(
    106             query_input_ids, query_token_type_ids, query_position_ids,
    107             query_attention_mask)

E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py in __call__(self, *args, **kwargs)
    374             error_data = getattr(e, error.ERROR_DATA, None)
    375             if error_data:
--> 376                 error_data.raise_new_exception()
    377             else:
    378                 logging_utils.warn(

E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py in raise_new_exception(self)
    334             # 2. Use exec to bypass syntax error checking in Python 2.
    335 
--> 336             six.exec_("raise new_exception from None")
    337         else:
    338             raise new_exception

E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py in <module>

ValueError: In transformed code:

    File "<ipython-input-7-9ba70d7d78ea>", line 36, in get_pooled_embedding
                             with_pooler=True):

        # Note: cls_embedding is poolerd embedding with act tanh 
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids,
                                                  position_ids, attention_mask)

    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\tmpnlmoyrcr.py", line 92, in forward
	attention_mask = paddle.jit.dy2static.convert_ifelse(attention_mask is
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 211, in convert_ifelse
	out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 257, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 372, in forward
	).astype(self.pooler.dense.weight.dtype) * -1e4,
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 342, in __impl__
	current_block(self).append_op(
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
	op = Operator(
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
	for frame in traceback.extract_stack():

    InvalidArgumentError: The DataType of equal Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at ..\paddle\fluid\framework\operator.cc:1604)
      [operator < equal > error]  [operator < run_program > error]

**Comment by liuyang77886** [comment]
第一次paddle2.1.2也报这个错，后来升级到2.2.2 还是一样的错
python -m pip install paddlepaddle-gpu==2.2.2.post101 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

**Comment by KeoYang** [comment]
同样的BUG：
版本、环境信息
1）paddle2.2.2  ppnlp2.3.0
2）系统环境： Windows10，Python 3.7.7

but，Linux work fine ..

**Comment by tianxin1860** [comment]
你好，windows 系统上数据类型的支持 bug, 辛苦给一下是运行哪个脚本报这个错？我们会尽快修复。

**Comment by tianxin1860** [comment]
你好，windows 系统上数据类型的支持 bug, 辛苦给一下是运行哪个脚本报这个错？我们会尽快修复。

**Comment by KeoYang** [comment]
> 你好，windows 系统上数据类型的支持 bug, 辛苦给一下是运行哪个脚本报这个错？我们会尽快修复。

hi, env：
1）paddle2.2.2 ppnlp2.3.0
2）系统环境： Windows10，Python 3.7.7
当重复代码 [train.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/faq_finance/train.py)的时候，出现相同的bug 


https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/faq_finance/train.py

**Comment by tianxin1860** [comment]
这个问题已经修复了，可以拉取最新的 develop 分支代码再运行。
