### ISSUE TITLE
请问@register_base_model修饰符的用途是什么？

### ISSUE THREAD

**Issue by Wu-Jiayang** [PaddlePaddle/PaddleNLP#1661]
我看到UnifiedTransformerModel类带有修饰符@register_base_model，请问该修饰符的用途是什么？
我想重写UnifiedTransformerModel类，请问是继承UnifiedTransformerPretrainedModel类写一个新类好一点，还是继承UnifiedTransformerModel类重写forward方法？
我自己写的类需要加该修饰符吗？
![未命名文件](https://user-images.githubusercontent.com/62842862/152079556-969f0550-375d-4c71-b084-4b53ed764b22.png)

**Comment by Wu-Jiayang** [comment]
我发现一旦使用此修饰符修饰新类则无法正常使用旧类，
而不使用此修饰符则无法正常使用新类，
请问该怎么办？

**Comment by guoshengCS** [comment]
> 我看到UnifiedTransformerModel类带有修饰符@register_base_model，请问该修饰符的用途是什么？

引入该修饰符主要是为了能够正确的加载模型：

考虑BERT模型，对于`BERTModel`表示的骨干网络或者是`BertForSequenceClassification`等下游任务网络都要能够从同一份参数配置和权重中创建和加载，我们既需要`BertForSequenceClassification.from_pretrained('bert-base-uncased')`，也需要`BERTModel.from_pretrained('bert-base-uncased')`。

注意参数权重作为key-value对提供，而骨干网络和下游任务网络要求参数权重的key是不一样的，下游任务网络中参数权重的key会多一个`bert.`的前缀；除参数权重外，`BERTModel`还是`BertForSequenceClassification`的init方法需要的参数也是不同的；要根据当前创建的对象是`BERTModel`还是`BertForSequenceClassification`对同一份参数配置和权重进行相应的调整适配。而目前骨干网络和下游任务网络的区分是通过`register_base_model`修饰显示标识的，这是当前采用的实现方式。

`register_base_model`修饰的class对象`BERTModel`将被设置为BERT预训练模型基类`BertPretrainedModel` class对象的`base_model_class`属性，以此来标识骨干网络；UnifiedTransformer中由于下游任务较少不那么明显，但也是相同的情况。

**Comment by guoshengCS** [comment]
> 我发现一旦使用此修饰符修饰新类则无法正常使用旧类，
而不使用此修饰符则无法正常使用新类，
请问该怎么办？

建议写一个新类，一方面可以减少对上面说的那些底层实现的考量；另一方面预训练模型作为一个生态系统，其实也会假设不同的模型是由不同的开发者贡献的，相对松散，不同模型之间不做过多依赖。 

感谢支持，也欢迎贡献~

**Comment by Wu-Jiayang** [comment]
> > 我发现一旦使用此修饰符修饰新类则无法正常使用旧类，
> > 而不使用此修饰符则无法正常使用新类，
> > 请问该怎么办？
> 
> 建议写一个新类，一方面可以减少对上面说的那些底层实现的考量；另一方面预训练模型作为一个生态系统，其实也会假设不同的模型是由不同的开发者贡献的，相对松散，不同模型之间不做过多依赖。
> 
> 感谢支持，也欢迎贡献~

@guoshengCS 
所以假如我想沿用预训练权重的话就应该以继承`UnifiedTransformerPretrainedModel`类的方式实现新类，并使用`register_base_model`修饰，但是就不能同时使用`UnifiedTransformerPretrainedModel`下的其他带有该修饰的子类了是吗？
