### ISSUE TITLE
input_token_type是用来干什么的

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleNLP#1663]
from paddlenlp.transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
token_, input_token_type = bert_tokenizer.encode(data).values()

编码时，input_token_type 在我的数据上永远是0，不知道该参数的意义。麻烦知道的解释一下~

**Comment by wawltor** [comment]
> from paddlenlp.transformers import BertTokenizer bert_tokenizer = BertTokenizer.from_pretrained('bert-base-chinese') token_, input_token_type = bert_tokenizer.encode(data).values()
> 
> 编码时，input_token_type 在我的数据上永远是0，不知道该参数的意义。麻烦知道的解释一下~

这里的就是BERT的segment信息，判断句子上下句关系，因为您可能输入的是单个句子，所以都是0。

**Comment by wj-Mcat** [comment]
`input_token_type` is to identify the sentence type of input. And it's the same as the `token_type_ids`  in [transformers](https://github.com/huggingface/transformers), and you can refer to: [token-type-ids](https://huggingface.co/docs/transformers/glossary#token-type-ids). Here is the simple code:

```python
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
input_sentence = "[CLS] HuggingFace is based in NYC [SEP] Where is HuggingFace based? [SEP]"

result = tokenizer(input_sentence)
assert result['token_type_ids'] == [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
```

`HuggingFace is based in NYC` is the first sentence so the value of `token_type_ids`(`input_token_type`) is **0**. `Where is HuggingFace based? ` is the second sentence so the value of `token_type_ids`(`input_token_type`) is **1**.  

If you want get more details about `BERT`, you can read:

* [BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding](https://arxiv.org/abs/1810.04805)
* [source code of bert](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py)

Hope the above description can help to understand the `input_token_type`.

**Comment by xu-peng-7** [comment]
非常感谢
