### ISSUE TITLE
bash typo

### ISSUE THREAD

**Issue by tao-hpu** [PaddlePaddle/PaddleNLP#1665]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/embeddings.md

执行完毕后会在当前路径下生成一个visualize目录，并将日志存放在其中，我们在命令行启动VisualDL即可进行查看，启动命令为：

visualdl logdir ./visualize

---------------->

执行完毕后会在当前路径下生成一个visualize目录，并将日志存放在其中，我们在命令行启动VisualDL即可进行查看，启动命令为：

visualdl --logdir ./visualize

**Comment by ZeyuChen** [comment]
@tonyanhq 感谢反馈！是否可以给我们提交的PR修复下文档的typo，十分期待你的开源贡献 :)

**Comment by tao-hpu** [comment]
> visualdl --logdir ./visualize

https://github.com/PaddlePaddle/PaddleNLP/pull/1675
