### ISSUE TITLE
PaddleNLP/applications/neural_search/recall/milvus/直接用动态图模型做向量转换，不用静态图转换的原因是什么

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1668]
正常工业落地的部署，是要转换成静态图然后做向量转换吧？看案例是直接用的动态图模型做向量转换，是出于什么考虑呢？

**Comment by w5688414** [comment]
感谢您对语义索引的关注，静态图抽取向量代码已经ready了，近期准备提交。

**Comment by AI-Mart** [comment]
好的，感谢回复，我以为用动态度是出于什么考虑，如果最终是需要转换成静态图，我后面做了也可以贡献PR

**Comment by ZTurboX** [comment]
> 好的，感谢回复，我以为用动态度是出于什么考虑，如果最终是需要转换成静态图，我后面做了也可以贡献PR

paddleNLP有些预训练语言模型不支持静态图导出，需要怎么做可以转成静态图呢？

**Comment by AI-Mart** [comment]
具体那个不支持，可以提个issue看下的

**Comment by ZTurboX** [comment]
> 具体那个不支持，可以提个issue看下的

albert
