### ISSUE TITLE
information_extraction DuEE 中训练模型时vocab_path=./conf/vocab.dict指的是什么？

### ISSUE THREAD

**Issue by gongshaojie12** [PaddlePaddle/PaddleNLP#167]
information_extraction DuEE 中训练模型时vocab_path=./conf/vocab.dict指的是什么？在哪里获取？谢谢

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！`vocab_path=./conf/vocab.dict`是多余无关的数据，请忽略。我们会删除这个数据， 修复pr： #172

**Comment by ZeyuChen** [comment]
Problem solve，please check the PR #172 , it has merged into develop branch.

**Comment by gongshaojie12** [comment]
好的，谢谢
