### ISSUE TITLE
PaddleNLP/blob/develop/applications/neural_search/recall/in_batch_negative 开源模型咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1670]
https://bj.bcebos.com/v1/paddlenlp/models/inbatch_model.zip
以上官方开源的有监督模型，是以下圈起来的哪种方案组合的训练结果？官方是否开源了最后那个效果最优的方案（预训练+无监督+有监督）训练出的模型，可以直接拿来验证效果，不用我们从预训练，到无监督，到有效监督这样从头到尾训练一遍。
![image](https://user-images.githubusercontent.com/63343847/153529400-8ca1eafa-e4dd-405e-a1bd-937028f0a832.png)

**Comment by w5688414** [comment]
https://paddlenlp.bj.bcebos.com/models/inbatch_model_best.zip
试试这个

**Comment by AI-Mart** [comment]
感谢回复，这个就是以下截图方案的模型吗
![image](https://user-images.githubusercontent.com/63343847/154009938-d861efe5-eb5a-45c1-8fa4-ead89077d096.png)

**Comment by w5688414** [comment]
> 感谢回复，这个就是以下截图方案的模型吗 ![image](https://user-images.githubusercontent.com/63343847/154009938-d861efe5-eb5a-45c1-8fa4-ead89077d096.png)

对的

**Comment by AI-Mart** [comment]
好的，我试下
