### ISSUE TITLE
PaddleNLP/applications/neural_search/recall/milvus/ 运行报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1673]
系统：linux centos7.9
安装包：
astor                     0.8.1
Babel                     2.9.1
bce-python-sdk            0.8.64
cached-property           1.5.2
certifi                   2021.10.8
cfgv                      3.3.1
charset-normalizer        2.0.11
click                     7.1.2
colorama                  0.4.4
colorlog                  6.6.0
cycler                    0.11.0
decorator                 5.1.1
dill                      0.3.4
distlib                   0.3.4
filelock                  3.4.2
flake8                    4.0.1
Flask                     1.1.4
Flask-Babel               2.0.0
fonttools                 4.29.1
func-timeout              4.3.5
future                    0.18.2
grpcio                    1.33.2
grpcio-tools              1.33.2
h5py                      3.6.0
hnswlib                   0.6.1
identify                  2.4.9
idna                      3.3
importlib-metadata        4.2.0
itsdangerous              1.1.0
jieba                     0.42.1
Jinja2                    2.11.3
joblib                    1.1.0
kiwisolver                1.3.2
MarkupSafe                1.1.1
matplotlib                3.5.1
mccabe                    0.6.1
multiprocess              0.70.12.2
nodeenv                   1.6.0
numpy                     1.21.5
opencv-python             4.2.0.32
packaging                 21.3
paddle-serving-app        0.7.0
paddle-serving-client     0.7.0
paddle-serving-server-gpu 0.7.0.post1028
paddlenlp                 2.2.4
paddlepaddle-gpu          2.2.2
pandas                    0.25.1
Pillow                    9.0.1
pip                       21.3.1
platformdirs              2.5.0
pre-commit                2.17.0
protobuf                  3.19.4
pybind11                  2.9.1
pyclipper                 1.3.0.post2
pycodestyle               2.8.0
pycryptodome              3.14.1
pyflakes                  2.4.0
pymilvus                  1.1.2
pyparsing                 3.0.7
python-dateutil           2.8.2
pytz                      2021.3
PyYAML                    6.0
requests                  2.27.1
scikit-learn              1.0.2
scipy                     1.3.1
sentencepiece             0.1.92
seqeval                   1.2.2
setuptools                60.1.1
Shapely                   1.8.0
shellcheck-py             0.8.0.4
six                       1.16.0
threadpoolctl             3.1.0
toml                      0.10.2
tqdm                      4.62.3
typing_extensions         4.0.1
ujson                     5.1.0
urllib3                   1.26.8
virtualenv                20.13.1
visualdl                  2.2.3
Werkzeug                  1.0.1
wheel                     0.37.1
zipp                      3.7.0

运行：
(venv) [root@gpusmr milvus]# python3 -u -m paddle.distributed.launch --gpus "0" --log_dir "recall_log/"         feature_extract.py         --device gpu         --params_path "inbatch_model/model_40/model_state.pdparams"         --batch_size 4096         --output_emb_size 256        --max_seq_length 60         --corpus_file "../../literature_search_data/milvus/milvus_data.csv"

报错：
Error: Can not import avx core while this file exists: /mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mart/neural_search/venv/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /mart/neural_search/venv/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

**Comment by Steffy-zxf** [comment]
@AI-Mart 你好！根据报错信息，
```
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by
```

应该是环境导致的问题。请参考paddle安装指南，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/compile/linux-compile.html
检查是否正确安装paddle。

**Comment by AI-Mart** [comment]
感谢回复，底层包升级就好了，参考链接https://blog.csdn.net/qq_15821487/article/details/122886625?spm=1001.2014.3001.5502
