### ISSUE TITLE
快递单信息抽取示例预测真实数据

### ISSUE THREAD

**Issue by chenglong-do** [PaddlePaddle/PaddleNLP#1679]
刚开始接触 NLP，按照示例已经完成训练和模型导出，预测时发现预测文件还是  test.txt，标注过的文件，请问下怎么预测"张三18625584663广东省深圳市南山区学府路东百度国际大厦"这样的内容啊？

**Comment by chenglong-do** [comment]
已修改 predict.py 代码实现，原来 predict.py 里面最终也只取的 text_a 的内容

**Comment by xialei2821212670** [comment]
有示例？

**Comment by chenglong-do** [comment]
> 

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie

**Comment by xialei2821212670** [comment]
> > 
> 
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie

修改后的predict.py
