### ISSUE TITLE
nlp产业化案例的neural_search，SimCSE+ In-batch Negatives 具体如何结合的？

### ISSUE THREAD

**Issue by ydnnh2008** [PaddlePaddle/PaddleNLP#1680]
说明中没看出来SimCSE+ In-batch Negatives是怎么结合的，

个人理解是：
SimCSE 的top k结果 和 In-batch Negatives 的top k结果 做平均加权，然后在排序后的top k结果作为召回？

不知道理解对不对

**Comment by w5688414** [comment]
SimCSE只是一个训练策略，使用的是无监督数据，SimCSE在大量的无监督数据集上训练以后，保存checkpoint。然后利用有监督的In-batch Negative加载该checkpoint，继续进行训练，最终得到的checkpoint来计算topK
