### ISSUE TITLE
albert转静态图报错

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1690]
- 版本、环境信息
1）PaddleNLP 2.2.0
2）Windows
- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/5669444/154607497-1252f6d9-258d-40f3-ad09-4f0a307a15c0.png)

`
input_ids = paddle.static.InputSpec(
        name="input_ids", shape=[-1, -1], dtype="int64")
    token_type_ids = paddle.static.InputSpec(
        name="token_type_ids", shape=[-1, -1], dtype="int64")
    attention_mask = paddle.static.InputSpec(
        name="attention_mask", shape=[-1,  -1], dtype="int64")
    model = AlbertForMaskedLM.from_pretrained('../checkpoints/albert-chinese-tiny/dy')
    model.eval()
    model = paddle.jit.to_static(
        model,
        input_spec=[input_ids, attention_mask, token_type_ids])

    paddle.jit.save(model, '../checkpoints/albert-chinese-tiny/static')
`

**Comment by yingyibiao** [comment]
您好，目前albert模型动转静还没有打通～
