### ISSUE TITLE
serve model error

### ISSUE THREAD

**Issue by ghtwht** [PaddlePaddle/PaddleNLP#1691]
When I serve the default en_de machine_translation/transformer model, I get the error:
" /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1.0.1_EC' not found (required by /data/venv/py3.8/lib/python3.8/site-packages/paddle_serving_client/serving_client.so)"
How can I solve it? 
when I run "openssl version", I can get "OpenSSL 1.1.1f  31 Mar 2020"

**Comment by FrostML** [comment]
You can follow this issue. 
https://github.com/PaddlePaddle/Serving/issues/1040
