### ISSUE TITLE
albert转静态图

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1695]
albert如何转静态图？修改了代码，可以成功转静态图，但使用时总是报错 InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [17, 312], X's size = 5304, 'shape' is [17, 312, 12, 26], the capacity of 'shape' is 1654848.

**Comment by wj-Mcat** [comment]
You should post your simple code which can reproduce this issue. So we can find the key problem with least time. Waiting for your next comment.

**Comment by ZTurboX** [comment]
> You should post your simple code which can reproduce this issue. So we can find the key problem with least time. Waiting for your next comment.

error caused in AlbertAttention

![image](https://user-images.githubusercontent.com/5669444/155465453-99cf01ed-9fd2-4693-9171-63e343859fd4.png)

**Comment by yingyibiao** [comment]
您好，目前albert模型动转静还没有打通～

**Comment by wj-Mcat** [comment]
> 您好，目前albert模型动转静还没有打通～

Have this issue been fixed? If not, I want to have a try.

What’s more, If there are some suggested docs or codes to help us to complete it?
