### ISSUE TITLE
Layoutxlm推理部署转成静态图模型报错

### ISSUE THREAD

**Issue by lan11** [PaddlePaddle/PaddleNLP#1703]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
版本、环境信息
1）PaddleNLP和PaddlePaddle版本：paddlenlp 2.2.4 paddlepaddle 2.2.0
2）系统环境：linux

训练保存后模型转换成静态图模型代码：

        self.model = paddle.jit.to_static(
            self.model,
            input_spec=[
                paddle.static.InputSpec(
                    shape=[None, 512], dtype="int64"),
                paddle.static.InputSpec(
                    shape=[None, 512, 4], dtype="int64"),
                paddle.static.InputSpec(
                    shape=[None, 3, 224, 224], dtype="float32"),
                paddle.static.InputSpec(
                    shape=[None, 512], dtype="int64"),
                paddle.static.InputSpec(
                    shape=[None, 512], dtype="int64")
        ])
        save_path = os.path.join("./export", "inference")
        paddle.jit.save(self.model, save_path)

报错误信息：

ValueError: In transformed code:

    File "/usr/local/lib/python3.6/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 880, in forward
        head_mask=head_mask, )
    File "/usr/local/lib/python3.6/dist-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 774, in forward
                visual_bbox_y[1:].expand(expand_shape[::-1]).transpose([1, 0]),
            ],
            axis=-1, ).reshape([-1, bbox.shape[-1]])
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        visual_bbox = visual_bbox.expand([final_shape[0], -1, -1])
        final_bbox = paddle.concat([bbox, visual_bbox], axis=1)

    File "/usr/local/lib/python3.6/dist-packages/paddle/tensor/manipulation.py", line 798, in stack
        return layers.stack(x, axis, name)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 10203, in stack
        attrs={'axis': axis})
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
        return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 3184, in append_op
        attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2344, in __init__
        self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) Dims of all Inputs(X) must be the same, but received input 1 dim is:7, -1 not equal to input 0 dim:-1, 7.
  [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:7, -1 != input_dims[0]:-1, 7.] (at /paddle/paddle/fluid/operators/stack_op.cc:46)
  [operator < stack > error]

**Comment by yingyibiao** [comment]
您好，目前LayoutXLM模型动转静还没有打通～

**Comment by lan11** [comment]
好的，谢谢。请问后面有安排吗？我看你们PaddleNLP2.3版本规划是支持现有所以模型支持Paddle Serving部署，请问包含该模型吗？

**Comment by wennyHou** [comment]
我在使用uie-x的推理代码的时候也遇到了同样的问题，报错是一致的。
