### ISSUE TITLE
paddlenlp中的erniegram中的tokenizer调用出错

### ISSUE THREAD

**Issue by Bais-art** [PaddlePaddle/PaddleNLP#1706]
tokenizer = paddlenlp.transformers.ErnieGramTokenizer.from_pretrained('ernie-gram-zh')

AttributeError: module 'paddlenlp.transformers' has no attribute 'ErnieGramTokenizer'

**Comment by wj-Mcat** [comment]
Please update your version  of `paddlenlp` to get latest features.  I test your code in my env, it works for me. Here are my related packages.

```shell
paddlenlp                     2.2.4
paddlepaddle                  2.2.0
```

I hope it can help you fix your issue. Please feel free to comment more details.

**Comment by Bais-art** [comment]
thank you
