### ISSUE TITLE
文档给的wget方法有误，不能加最后的./

### ISSUE THREAD

**Issue by hohdiy** [PaddlePaddle/PaddleNLP#1709]
![image](https://user-images.githubusercontent.com/20314800/155641608-4c92630c-c147-458e-a9bc-041a9fcf7cf8.png)

链接：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/gpt

AI studio下载不了，是否可以提供一下国内的源，或者内置到AI studio上。

**Comment by ZHUI** [comment]
这个数据集比较大，有37G。你试试去官方网页 https://openwebtext2.readthedocs.io/en/latest/index.html#download-plug-and-play-version 这边能下载吗？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/1710 已经提PR修复

**Comment by hohdiy** [comment]
按照文档，安装了文档中提供的python依赖，还是不够。
需要单独安装pip install lac 和 pip install zstandard 才能使用，不然直接报告缺少模块。后者会导致coredump
。
请更新到文档上。

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/data_tools#%E7%8E%AF%E5%A2%83%E4%BE%9D%E8%B5%96  这里有依赖说明，我在GPT的页面也加上一下。

> 需要单独安装pip install lac 和 pip install zstandard 才能使用，不然直接报告缺少模块。后者会导致coredump

import zstandard 出错后，不会立刻停止，而是直接 coredump？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/1718 文档更新

**Comment by hohdiy** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/gpt 这个页面我看没有更新依赖说明，按照文档，直接执行就会缺少那两个库。
