### ISSUE TITLE
RuntimeError: Can't load tokenizer for 'gpt-cpm-large-cn'

### ISSUE THREAD

**Issue by hermitgreen** [PaddlePaddle/PaddleNLP#1719]
paddlepaddle-gpu 2.2.2.post112
paddlenlp 2.2.4
python 3.8.12

```python
from paddlenlp.transformers import AutoModel, AutoTokenizer
AutoTokenizer.from_pretrained('gpt-cpm-large-cn')
```

then I got
```
Traceback (most recent call last):
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 195, in from_pretrained
    resolved_vocab_file = get_path_from_url(community_config_path,
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 163, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 199, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/gpt-cpm-large-cn/tokenizer_config.json failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 199, in from_pretrained
    raise RuntimeError(
RuntimeError: Can't load tokenizer for 'gpt-cpm-large-cn'.
Please make sure that 'gpt-cpm-large-cn' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant tokenizer files.
```

**Comment by hermitgreen** [comment]
same problem while
```python
AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
```

then I got
```python
>>> AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
[2022-03-02 12:12:44,215] [    INFO] - Downloading model_config.json from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json
[2022-03-02 12:12:44,297] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!
Traceback (most recent call last):
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 190, in _from_pretrained
    resolved_vocab_file = get_path_from_url(community_config_path,
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 163, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 199, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 299, in from_pretrained
    return cls._from_pretrained(pretrained_model_name_or_path, task,
  File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 194, in _from_pretrained
    raise RuntimeError(
RuntimeError: Can't load weights for 'roberta-base-ft-chinanews-chn'.
Please make sure that 'roberta-base-ft-chinanews-chn' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).
```

**Comment by yingyibiao** [comment]
> 

Thanks for your question abour AutoTokenizer, you can use GPTChineseTokenizer.from_pretrained('gpt-cpm-large-cn') instead. We'll upgrade AutoTokenizer to support more cases!

**Comment by yingyibiao** [comment]
> same problem while
> 
> ```python
> AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
> ```
> 
> then I got
> 
> ```python
> >>> AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
> [2022-03-02 12:12:44,215] [    INFO] - Downloading model_config.json from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json
> [2022-03-02 12:12:44,297] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!
> Traceback (most recent call last):
>   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 190, in _from_pretrained
>     resolved_vocab_file = get_path_from_url(community_config_path,
>   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 163, in get_path_from_url
>     fullpath = _download(url, root_dir, md5sum)
>   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 199, in _download
>     raise RuntimeError("Downloading from {} failed with code "
> RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 299, in from_pretrained
>     return cls._from_pretrained(pretrained_model_name_or_path, task,
>   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 194, in _from_pretrained
>     raise RuntimeError(
> RuntimeError: Can't load weights for 'roberta-base-ft-chinanews-chn'.
> Please make sure that 'roberta-base-ft-chinanews-chn' is:
> - a correct model-identifier of built-in pretrained models,
> - or a correct model-identifier of community-contributed pretrained models,
> - or the correct path to a directory containing relevant modeling files(model_weights and model_config).
> ```

We have updated our documents about weight names, see https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers.html
You can use AutoModel.from_pretrained('nosaydomore/uer-roberta-base-ft-chinanews-chn') to load it.

**Comment by hermitgreen** [comment]
> > same problem while
> > ```python
> > AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then I got
> > ```python
> > >>> AutoModel.from_pretrained('roberta-base-ft-chinanews-chn')
> > [2022-03-02 12:12:44,215] [    INFO] - Downloading model_config.json from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json
> > [2022-03-02 12:12:44,297] [   ERROR] - Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!
> > Traceback (most recent call last):
> >   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 190, in _from_pretrained
> >     resolved_vocab_file = get_path_from_url(community_config_path,
> >   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 163, in get_path_from_url
> >     fullpath = _download(url, root_dir, md5sum)
> >   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/utils/downloader.py", line 199, in _download
> >     raise RuntimeError("Downloading from {} failed with code "
> > RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/transformers/community/roberta-base-ft-chinanews-chn/model_config.json failed with code 404!
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 299, in from_pretrained
> >     return cls._from_pretrained(pretrained_model_name_or_path, task,
> >   File "/home/yangbo25/software/conda/lib/python3.8/site-packages/paddlenlp/transformers/auto/modeling.py", line 194, in _from_pretrained
> >     raise RuntimeError(
> > RuntimeError: Can't load weights for 'roberta-base-ft-chinanews-chn'.
> > Please make sure that 'roberta-base-ft-chinanews-chn' is:
> > - a correct model-identifier of built-in pretrained models,
> > - or a correct model-identifier of community-contributed pretrained models,
> > - or the correct path to a directory containing relevant modeling files(model_weights and model_config).
> > ```
> 
> We have updated our documents about weight names, see https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers.html You can use AutoModel.from_pretrained('nosaydomore/uer-roberta-base-ft-chinanews-chn') to load it.

work properly
