### ISSUE TITLE
想咨询一下ERNIE版本升级计划

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/PaddleNLP#1720]
目前测试了一下paddlenlp的几个API，比如“text_correction”，“knowledge_mining”等等，发现基本上都用的ernie1.0，想请问一下有没有升级ernie版本的计划

**Comment by ZeyuChen** [comment]
有的，后面会升级到最新的ERNIE 3.0版本，效果提升会很显著。

**Comment by Godlikemandyy** [comment]
@ZeyuChen 大概什么时间升级

**Comment by ZeyuChen** [comment]
Q2内完成发布升级。

**Comment by Godlikemandyy** [comment]
有没有升级所涵盖的大致范围，比如说那些api会升级，期待一下！
