### ISSUE TITLE
MultiLabelsMetric import语句导入问题，望修复。

### ISSUE THREAD

**Issue by ChrisMengxl** [PaddlePaddle/PaddleNLP#1729]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
PaddleNLP 2.2
——————————————————————————
[PaddleNLP/blob/release/2.2/paddlenlp/metrics/__init__.py文件](https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.2/paddlenlp/metrics/__init__.py)
无 ：MultiLabelsMetric
应：
from .glue import AccuracyAndF1, Mcc, PearsonAndSpearman, MultiLabelsMetric

**Comment by smallv0221** [comment]
感谢您提出这个问题，您愿意提个pr帮我们修复这个地方么
