### ISSUE TITLE
How to download wikicorpus_en dataset in HDF5 format? 

### ISSUE THREAD

**Issue by xueeinstein** [PaddlePaddle/PaddleNLP#173]
I noticed that the Bert benchmark requires the wikicorpus_en dataset in HDF5 format. But I only have [raw text data](https://www.cs.upc.edu/~nlp/wikicorpus/). How to download this dataset or convert it from raw text?

**Comment by wawltor** [comment]
You could use the python script to convert the raw wiki text file to HDF5 file, the script url is https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/create_pretraining_data.py, more message is in doc of bert directory.  And we will support the script that convert the raw chinese text file to HDF5 file later.
