### ISSUE TITLE
roberta-en-base  roberta-en-large模型缺失

### ISSUE THREAD

**Issue by tanhanzhuo** [PaddlePaddle/PaddleNLP#1730]
```
from paddlenlp.transformers import RobertaTokenizer, RobertaModel
RobertaTokenizer.from_pretrained('roberta-en-base')
RobertaModel.from_pretrained('roberta-en-base')
```
其中tokenizer正常载入，导入模型显示：
```
RuntimeError: Can't load weights for 'roberta-en-base'.
Please make sure that 'roberta-en-base' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).
```
模型列表中显示提供roberta-en-base和roberta-en-large
(https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers.html)
在源代码中
https://github.com/PaddlePaddle/PaddleNLP/blob/487162262196bead8d9b4c2306f313b8f64edf9b/paddlenlp/transformers/roberta/modeling.py#L96
遗漏robert-en-base等模型 （另一个issue中也有开发者遇到类似问题https://github.com/PaddlePaddle/PaddleNLP/issues/1719）

另：
Paddle的roberta-en-base的tokenizer，pad_token, mask_token等和原roberta模型不同（e.g. [PAD] vs <pad>），虽然pad_token_id相同，但可能会导致误解

**Comment by yingyibiao** [comment]
模型列表文档已更新。
分别使用 RobertaModel.from_pretrained('nosaydomore/roberta-en-base') & RobertaModel.from_pretrained('nosaydomore/roberta-en-large') 进行加载。
