### ISSUE TITLE
纯英语对话任务能使用plato-mini分词器吗

### ISSUE THREAD

**Issue by Wu-Jiayang** [PaddlePaddle/PaddleNLP#1731]
请问对于纯英语对话任务，用plato-mini分词器分词和英语分词器有区别吗

plato-mini词表只有30000，会不会导致词根比较少，分词比较细，从而导致效果下降？

**Comment by smallv0221** [comment]
plato-mini是中文模型，不建议拿来做英文任务的

**Comment by Wu-Jiayang** [comment]
> plato-mini是中文模型，不建议拿来做英文任务的

哦好的，谢谢
