### ISSUE TITLE
【PaddlePaddle Hackathon 2】79、PLATO-2 接入预训练模型和生成API

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/PaddleNLP#1735]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：PLATO-2 接入预训练模型和生成API

- 技术标签：python、开放域对话

- 任务难度：中等

- 详细描述：PLATO-2 是百度自研的开放域对话模型，当前在PaddleNLP中已提供使用示例，希望能够提供和其他预训练模型一样的使用方式和体验。

【提交内容】

- 任务 PR 到 PaddleNLP

- 相关技术文档（模型效果验证符合预期）

【技术要求】

- 熟练掌握 python

- 理解深度学习模型原理

- 了解开放域对话基础算法

【参考资料】

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/plato-2

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by Zhiyuan-Fan** [comment]
请问具体要实现哪些功能？任务描述中的“希望能够提供和其他预训练模型一样的使用方式和体验。”其他预训练模型是指哪些？谢谢！

**Comment by Zhiyuan-Fan** [comment]
@yingyibiao 请问具体要实现哪些功能？任务描述中的“希望能够提供和其他预训练模型一样的使用方式和体验。”其他预训练模型是指哪些？谢谢！

**Comment by guoshengCS** [comment]
@Elvisambition  当前已经接入paddlenlp.transformers组件中的对话预训练模型包括 [UnifiedTransformer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer) 、[PLATO-mini](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/faster/faster_generation/samples/plato_sample.py)和[PLATO-XL](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/plato-xl)，可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/unified_transformer/modeling.py 。

> 请问具体要实现哪些功能?

可以参考这些模型将 [PLATO-2](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/plato-2) 接入paddlenlp.transformers组件，并且将原PLATO-2 example代码基于接入paddlenlp.transformers后的的PLATO-2模型实现，并利用[高性能文本生成能力](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/faster/faster_generation)进行预测加速
