### ISSUE TITLE
【PaddlePaddle Hackathon 2】76、基于pointer_summarizer完成中文文本摘要任务

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/PaddleNLP#1738]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：基于pointer_summarizer完成中文文本摘要任务

- 技术标签：Python, PaddleNLP，文本摘要

- 任务难度：简单

- 详细描述：参考[论文](https://arxiv.org/abs/1704.04368)以及[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_summarization/pointer_summarizer)，完成在[LCSTS_new](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/lcsts_new.py)数据集上的文本摘要任务。

【提交流程】

- 请将相关代码提交到 [PaddleNLP repo](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples)

【提交内容】

- 完整代码：包括数据、训练、预测、动转静
- 指标
- readme文档：参考[文档](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie)

【合入标准】

- 指针网络在PaddleNLP内置数据集[LCSTS_new](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/lcsts_new.py)上，ROUGE-1 验证集0.3553，测试集0.3396

【技术要求】

- 模型使用

【参考内容】

- [PaddleNLP repo](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie)
- [相关repo](https://github.com/LowinLi/Text-Summarizer-Pytorch-Chinese)

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by lxsyz** [comment]
【队名】：无言以对

【序号】：76

【状态】：提交

【链接】：https://github.com/PaddlePaddle/PaddleNLP/issues/1738

**Comment by skywalk163** [comment]
项目中使用到了tensorflow代码，如`from tensorflow.core.example import example_pb2`
请问“example_pb2”这个也要复现成飞桨代码吗？
