### ISSUE TITLE
【PaddlePaddle Hackathon 2】75、PaddleNLP 英文文档完善

### ISSUE THREAD

**Issue by TCChenlong** [PaddlePaddle/PaddleNLP#1739]
（此 ISSUE 为 PaddlePaddle Hackathon 第二期活动的任务 ISSUE，更多详见 [【PaddlePaddle Hackathon 第二期】任务总览](https://github.com/PaddlePaddle/Paddle/issues/40234)）

【任务说明】

- 任务标题：PaddleNLP 英文文档完善

- 技术标签：英文文档，NLP

- 任务难度：困难

- 详细描述：完善 [PaddleNLP 英文文档](https://paddlenlp.readthedocs.io/en/latest/)，视完成情况分别给予简单、中等、困难难度奖金。

【提交流程】

请将英文文档相关内容提交到 PaddleNLP repo 的 [docs/locale/en/LC_MESSAGES](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/docs/locale/en/LC_MESSAGES) 目录

【提交内容】

- PaddleNLP repo 的 [docs/locale/en/LC_MESSAGES](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/docs/locale/en/LC_MESSAGES) 目录里 .po 相关文件的英文内容

【合入标准】

- 英文文档语言通顺
- 英文文档内容完整

【技术要求】

- 了解 readthedocs 网站
- 熟悉英文文档撰写

【参考内容】

- [PaddleNLP 中文文档](https://paddlenlp.readthedocs.io/zh/latest/index.html)

【答疑交流】

- 如果在开发中对于上述任务有任何问题，欢迎在本 ISSUE 下留言交流。
- 对于开发中的共性问题，在活动过程中，会定期组织答疑，请大家关注官网&QQ群的通知，及时参与。

**Comment by holazzer** [comment]
.po文件是2021年4月生成的，会不会有点老了

**Comment by yingyibiao** [comment]
> .po文件是2021年4月生成的，会不会有点老了

我稍后来更新一下～

**Comment by holazzer** [comment]
> > .po文件是2021年4月生成的，会不会有点老了
> 
> 我稍后来更新一下～

更新了记得戳我一下哦 ~

**Comment by yingyibiao** [comment]
> > > .po文件是2021年4月生成的，会不会有点老了
> > 
> > 
> > 我稍后来更新一下～
> 
> 更新了记得戳我一下哦 ~

已更新～

**Comment by franva** [comment]
@yingyibiao  已经翻译完了, 结果上来已更新, 发现好多文件发送改变了.......... 咱们这个任何我用的branch是develop.
