### ISSUE TITLE
RobertaTokenizer不能载入本地模型

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/PaddleNLP#1745]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

请问有人遇到过RobertaTokenizer不能载入本地模型的问题吗
![4bbc4c4cc24ce1cf5380ddf6743e5de8](https://user-images.githubusercontent.com/16911935/157436759-f104a058-4d3a-441b-9642-d700e83ee181.png)

用RobertaBPETokenizer不会报错

**Comment by ZHUI** [comment]
RobertaBPETokenizer 里面是设置了 special token的。但是 RobertaTokenizer  在外面又套了一层，导致get 不到属性。待修复

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/1730 
> 另：
Paddle的roberta-en-base的tokenizer，pad_token, mask_token等和原roberta模型不同（e.g. [PAD] vs ），虽然pad_token_id相同，但可能会导致误解

**Comment by yejiahaoye** [comment]
这个问题怎么修复，我也遇到了

**Comment by smallv0221** [comment]
> 这个问题怎么修复，我也遇到了

可以拉最新的develop版本试一下，这个pr中应该已经修复了 #1798
