### ISSUE TITLE
examples中的electra支持中文的预训练吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#175]
仿造bert的预训练，生成了一个中文的训练文本，每行一个句子，字符以空格分隔，启动命令
python -u run_pretrain.py \
    --model_type electra \
    --model_name_or_path chinese-electra-base \
    --input_dir /home/aistudio/work \
    --output_dir /home/aistudio/work/pretrained_models/ \
    --train_batch_size 64 \
    --learning_rate 5e-4 \
    --max_seq_length 320 \
    --weight_decay 1e-2 \
    --adam_epsilon 1e-6 \
    --warmup_steps 10000 \
    --num_train_epochs 50 \
    --logging_steps 20 \
    --save_steps 20000 \
    --max_steps 1000000
结果报异常了
Traceback (most recent call last):
  File "run_pretrain.py", line 661, in <module>
    do_train(args)
  File "run_pretrain.py", line 429, in do_train
    args.model_name_or_path + "-generator"]))
KeyError: 'chinese-electra-base-generator'
看样子目前只支持electra-small、electra-base、electra-large？中文的不行吗？

**Comment by guoshengCS** [comment]
这个目前代码中确实是还不支持，`KeyError: 'chinese-electra-base-generator'`报错是因为目前electra预训练没有添加中文的配置支持，fine-tune是添加了中文的配置支持的。

进行中文预训练的话应该也可以临时先直接在 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/electra/modeling.py#L525 这里参考英文模型electra-base-generator和electra-base-discriminator的配置加下chinese-electra-base-generator和chinese-electra-base-discriminator的配置试下，也请 @jeff41404  看下

**Comment by hitwangshuai** [comment]
想问下，这里的chinese-electra-base预训练模型参数包括generator部分吗
