### ISSUE TITLE
为何使用Taskflow和使用WordtagTask跑wordtag模型的答案不一样？

### ISSUE THREAD

**Issue by Desperado-Jia** [PaddlePaddle/PaddleNLP#1751]
如题，
task_path = '../../../conf/wordtag'
    task_instance = WordTagTask(model=task_path, task=task_path, task_path=task_path)

    r = task_instance(
        [
            '26岁女儿崩溃大哭,现场控诉母亲罪行是哪一期'
        ]
    )
跑的结果是错误的，
但是
app = Taskflow(task='knowledge_mining', model='wordtag')

    text = '26岁女儿崩溃大哭,现场控诉母亲罪行是哪一期'
    r = app.__call__(text)
跑的结果是对的，Taskflow里使用的就是WordTagTask啊，很奇怪

**Comment by linjieccc** [comment]
你好，方便提供下复现代码吗？另外直接用WordTagTask而不用Taskflow来载入是不是有什么定制需求，我们看下能不能满足
