### ISSUE TITLE
paddlenlp 如何实现 自定义数据集+预训练  完成情感分析

### ISSUE THREAD

**Issue by stronger123-boa** [PaddlePaddle/PaddleNLP#176]
我将《使用预训练模型ERNIE优化情感分析》的预训练模型和《快来选一顿好吃的年夜饭》的自定义数据集整合一起完成自定义数据集+预训练。但是总是在报错。请问自定义数据集的类需要做什么调整吗？

**Comment by Steffy-zxf** [comment]
你好！自定义数据集参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/data_prepare/dataset_self_defined.rst
