### ISSUE TITLE
动态图导出为静态图报错：AttributeError: 'builtin_function_or_method' object has no attribute 'transpose'

### ISSUE THREAD

**Issue by githanyongjin** [PaddlePaddle/PaddleNLP#1760]
文本分类 rnn中使用bilstm_attn训练好模型后，导出静态图报错AttributeError: 'builtin_function_or_method' object has no attribute 'transpose'

**Comment by tianxin1860** [comment]
请问具体使用的那个示例代码？

**Comment by Steffy-zxf** [comment]
@githanyongjin 你好。请问具体环境，paddle/paddlenlp/python版本是多少？具体代码是什么样的？
