### ISSUE TITLE
模型问题吗？

### ISSUE THREAD

**Issue by liaoxuewei** [PaddlePaddle/PaddleNLP#1762]
之前的代码，正常运行，今天运行的时候会自动更新模型，然后执行会出错，截图所示，是不是哪里问题？

# 中文分词
xprint("中文分词：")
seg = Taskflow("word_segmentation")
xprint(seg("第十四届全运会在西安举办"))

# 词性标注
xprint("词性标注：")
tag = Taskflow("pos_tagging")
xprint(tag("第十四届全运会在西安举办"))

![image](https://user-images.githubusercontent.com/970765/158002118-fd3d6147-36b3-4271-a144-0913212bf4ae.png)

**Comment by liaoxuewei** [comment]
运行的时候会在控制台打印下面文字：
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m

**Comment by linjieccc** [comment]
@liaoxuewei 你好，请问是执行`xprint(tag("第十四届全运会在西安举办"))`的时候程序异常退出吗？另外能否提供下PaddleNLP和PaddlePaddle的版本号和系统环境信息，谢谢。
