### ISSUE TITLE
can't tokenize [MASK] token

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#1763]
## Environment
```python
# python 3.8
paddlenlp                     2.1.1
paddlepaddle-gpu              2.0.2.post100
```

## Reproduction

```python
from paddlenlp.transformers.bert.tokenizer import  BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-chinese')
text = '我喜欢中国[MASK]'

result = tokenizer.encode(text, truncation_strategy='tail', return_special_tokens_mask=True)
print(tokenizer.convert_ids_to_tokens(result['input_ids']))
print(tokenizer.all_special_tokens)
```

the output of above code is:
```shell
['[CLS]', '我', '喜', '欢', '中', '国', '[', '[UNK]', ']', '[SEP]']
['[SEP]', '[PAD]', '[CLS]', '[UNK]', '[MASK]']
```

so, it's abvious that it can't tokenize the special token in sentence. Why ？ How to handle it ??

***

btw, I check the [code](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/few_shot/pet/data.py#L76) from example dir, it replace the `<unk>` special token by hard way.  Is that the only way I can handle it ？

**Comment by wj-Mcat** [comment]
After review the code of BertTokenizer, there are multi special tokens not used. please refer to: 

* [BertTokenizer](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/tokenizer.py#L373)
* [ErnieTokenzier](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/tokenizer.py#L128)
* [ReformerTokenizer](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/reformer/tokenizer.py#L72)

And I notice that the [example data process code](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/few_shot/pet/data.py#L76) of pet, it handle the special token by hand, so Can I say: the tokenizer can't tokenize the special token ?

**Comment by gongel** [comment]
升级paddlenlp即可
```python
pip install -U paddlenlp
```

**Comment by wj-Mcat** [comment]
Thanks for your reply, it fixs this issue.
