### ISSUE TITLE
Emotion_detection 任务还有吗

### ISSUE THREAD

**Issue by Fengwills** [PaddlePaddle/PaddleNLP#1766]
Emotion detection 任务还有吗？在哪个目录下？

**Comment by linjieccc** [comment]
你好，可以看下这个目录下的这两个示例：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/sentiment_analysis

**Comment by ZeyuChen** [comment]
@Fengwills 是指对话情绪识别的模型场景吗？
