### ISSUE TITLE
变更batch_size，预测值发生变化

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/PaddleNLP#1774]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP == 2.2.4， PaddlePaddle == 2.2.2
2）系统环境：CentOS 7.5.1804，python 3.8
- 复现信息：
1）batch_size=1与batch_size=8时预测结果有diff
2）batch_size=8时，mask掉padding值，预测结果还是有diff

相关issue #1604

**Comment by wawltor** [comment]
可以尝试安装一下develop版本的PaddleNLP，看看是否已经解决？

**Comment by guoshengCS** [comment]
可否提供下复现代码呢，按照 https://github.com/PaddlePaddle/PaddleNLP/issues/1604 中测试预测值是没有变化的

**Comment by barrierye** [comment]
> 可否提供下复现代码呢，按照 #1604 中测试预测值是没有变化的

可以在如流上交流代码吗？不方便放在github。如流账号：yebaiwei

已在如流上提供复现代码

**Comment by barrierye** [comment]
求问这个解决了吗

**Comment by guoshengCS** [comment]
请问具体是哪个模型呢，我们找下相关模型负责人
