### ISSUE TITLE
ErnieForGeneration 多卡训练 paddle.load模型报错：“EOFError: Ran out of input”

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleNLP#1794]
模型是paddlenlp的ErnieForGeneration，用model.save_pretrianed保存的

**Comment by chenxiaozeng** [comment]
麻烦提供一下具体的报错信息，以及最小可复现代码哦

**Comment by renmada** [comment]
> 麻烦提供一下具体的报错信息，以及最小可复现代码哦

我提供pdparams文件可以吗

**Comment by FrostML** [comment]
最好也能有可复现的代码哈
另外，文件大小是多少以及用对应的 `from_pretrained` 能正常 load 吗？这种报错也有可能是误操作清空了文件，或是损坏、错误地修改了文件导致的。
也可重新 save check 下。

**Comment by renmada** [comment]
> 最好也能有可复现的代码哈 另外，文件大小是多少以及用对应的 `from_pretrained` 能正常 load 吗？这种报错也有可能是误操作清空了文件，或是损坏、错误地修改了文件导致的。 也可重新 save check 下。

 不是每次都会出错。主要这个模型训练了好久，保存下来发现不能load很伤。
有没有办法修复这个权重？权重大小是正常的

**Comment by FrostML** [comment]
如果是文件损坏那可能不太好恢复，可能还是得重新训。
之前遇到一种用法导致类似的情况，是因为有位用户用多卡训练，然后每张卡对应的进程都在执行保存模型的操作，相当于是同一个文件反复被多个进程“可能是同时”读写导致的偶发性文件损坏。可以在代码里面先自查下有无这种情况。

可以用以下代码段试试读取这个文件，如果确定是 `pickle` 这里报错那可能没有太好恢复的方法。
``` python
import pickle
with open("model.pdparams", 'rb') as f:
    state = pickle.load(f, encoding='latin1')
```

**Comment by renmada** [comment]
是多卡训练，但是只有在rank=0的时候才会保存

```python
                if (global_step % args.save_steps == 0 or global_step == num_training_steps) and paddle.distributed.get_rank(
                ) == 0:
                    output_dir = args.output_dir
                    if not os.path.exists(output_dir):
                        os.makedirs(output_dir)
                    model_to_save = model._layers if isinstance(
                        model, paddle.DataParallel) else model
                    model_to_save.save_pretrained(output_dir)
```

**Comment by kongdebug** [comment]
> 是多卡训练，但是只有在rank=0的时候才会保存
> 
> ```python
>                 if (global_step % args.save_steps == 0 or global_step == num_training_steps) and paddle.distributed.get_rank(
>                 ) == 0:
>                     output_dir = args.output_dir
>                     if not os.path.exists(output_dir):
>                         os.makedirs(output_dir)
>                     model_to_save = model._layers if isinstance(
>                         model, paddle.DataParallel) else model
>                     model_to_save.save_pretrained(output_dir)
> ```

我跑脚本任务时也遇到了相同的错误，请问您解决了吗
