### ISSUE TITLE
ERNIE-CTM模型落地

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#1803]
ERNIE-CTM模型太大，达不到落地需求，如何优化？

**Comment by joey12300** [comment]
> ERNIE-CTM模型太大，达不到落地需求，如何优化？

您好，请问您期望的模型大小大致是多大呢？是速度问题还是模型体积问题？你需要在什么环境下落地呢？

**Comment by ZTurboX** [comment]
> > ERNIE-CTM模型太大，达不到落地需求，如何优化？
> 
> 您好，请问您期望的模型大小大致是多大呢？是速度问题还是模型体积问题？你需要在什么环境下落地呢？

速度问题。想在cpu环境下部署。是否有tiny版的模型

**Comment by linjieccc** [comment]
您好，目前ernie-ctm-small/tiny已经在开发计划中了，有进展同步反馈给您
