### ISSUE TITLE
ERNIE-DOC预训练模型用于paddlenlp做文本分类的Demo

### ISSUE THREAD

**Issue by llllearner** [PaddlePaddle/PaddleNLP#1819]
有大佬成功使用ERNIE-DOC的预训练模型进行文本分类的吗？我按照ERNIE-1.0的代码报错了，提示缺少att_mask。。。

**Comment by ZeyuChen** [comment]
@EEeEhh https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc 可以看看这个example示例
