### ISSUE TITLE
PaddleNLP训练模型如何转推理模型

### ISSUE THREAD

**Issue by Nicole1983** [PaddlePaddle/PaddleNLP#182]
使用ernie-tiny进行训练，得到训练模型如下：
checkpoints/
├── model_100
│   ├── model_config.json
│   ├── model_state.pdparams
│   ├── tokenizer_config.json
│   └── vocab.txt
└── ...
怎么才能把训练模型转成推理模型呢？
最终目的是想把训练过的NLP模型部署到Paddle Serving上，该怎么操作呢？

**Comment by guoshengCS** [comment]
训练模型转成推理模型可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert#预测 。Paddle Serving等更多预测相关内容暂时还未合入，可以先参考这个PR https://github.com/PaddlePaddle/PaddleNLP/pull/164

**Comment by Nicole1983** [comment]
参照该样例，已经转成推理模型了，非常感谢！！
