### ISSUE TITLE
动态图转静态图，同一个句子的预测结果不一致

### ISSUE THREAD

**Issue by wke22** [PaddlePaddle/PaddleNLP#1823]
环境：python 3.9、PaddlePaddle 2.2.2、PaddleNLP 2.2.4、windows、device：cpu
1.运行examples/sentiment_analysis/skep/train_sentence.py，加载自定义数据集，训练模型
2.运行examples/sentiment_analysis/skep/export_model.py，导出静态图
      参数：--params_path "./checkpoint/model_900/model_state.pdparams"
3.运行examples/sentiment_analysis/skep/deploy/python/predict.py，预测句子情感（静态图方式）
      参数：--model_file "../../static_graph_params.pdmodel" --params_file "../../static_graph_params.pdiparams"
      句子预测结果：Data: 这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般 	 Label: negative
4.运行examples/sentiment_analysis/skep/predict_sentence.py，预测句子情感（动态图方式）
      参数：--params_path "checkpoints/model_900/model_state.pdparams"
      句子预测结果：Data: 这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般 	 Label: positive

自定义数据集示例：0（消极）1（中性）2（积极）
label	text_a
2	25.4寸笔记本的键盘确实爽，基本跟台式机差不多了，蛮喜欢数字小键盘，输数字特方便，样子也很美观，做工也相当不错
0	房间太小。其他的都一般。。。。。。。。。
1	今天是星期一

重要代码改动：
chnsenticorp.py：return ["0", "1"]  改为  return ["0", "1", "2"]

train_sentence.py：
1）train_ds, dev_ds = load_dataset(dataset_name, splits=["train", "dev"])  改为 train_ds,dev_ds = load_dataset(dataset_name,data_files=["~\\.paddlenlp\\datasets\\ChnSentiCorp\\ChnSentiCorp\\ChnSentiCorp\\train.tsv", "~\\.paddlenlp\\datasets\\ChnSentiCorp\\ChnSentiCorp\\ChnSentiCorp\\dev.tsv"])
2）label_map = {0: 'negative', 1: 'positive'}  改为 label_map = {0: 'negative', 1: 'positive', 2: 'other'}

export_model.py：label_map = {0: 'negative', 1: 'positive'} 改为 label_map = {0: 'negative', 1: 'other', 2: 'positive'}

predict.py和predict_sentence.py改动部分同export_model.py

**Comment by tianxin1860** [comment]
你好，可以提供一份你改完之后的完整可运行的脚本。

**Comment by wke22** [comment]
> 你好，可以提供一份你改完之后的完整可运行的脚本。

[更改后的脚本代码及数据.zip](https://github.com/PaddlePaddle/PaddleNLP/files/8359064/default.zip)
