### ISSUE TITLE
textcnn/deploy/python下的predict.py要引入的data文件是哪一个

### ISSUE THREAD

**Issue by wke22** [PaddlePaddle/PaddleNLP#1826]
环境：python 3.9、PaddlePaddle 2.2.2、PaddleNLP 2.2.4、windows、device：cpu

1.前提已经根据https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/textcnn/README.md中的步骤进行到用finetune好的模型进行预测的那步了。
2.运行textcnn/predict.py可以正常预测
3.运行textcnn/deploy/python/predict.py，首先from data import preprocess_prediction_data报错
![image](https://user-images.githubusercontent.com/67145269/159763455-d9de601f-7fad-4d35-8e01-ed7f48d4ece1.png)
然后把textcnn/下的data.py引入到predict.py中，运行后又报错：TypeError: In copy_from_cpu, we only support numpy ndarray and list[str] data type.
![image](https://user-images.githubusercontent.com/67145269/159763741-808d1a57-b452-447c-8feb-86d4a28d425e.png)
不清楚textcnn/deploy/python下的predict.py要引入的data文件是哪一个，希望大佬可以指点一下

**Comment by tianxin1860** [comment]
predict.py 用的 data 是 textcnn 下的 data.py。

**Comment by wke22** [comment]
> predict.py 用的 data 是 textcnn 下的 data.py。


引入textcnn 下的 data.py报错 In copy_from_cpu, we only support numpy ndarray and list[str] data type.
