### ISSUE TITLE
预训练模型的whole word mask数据处理问题

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/PaddleNLP#1829]
whole word mask 把中文拆成了 ##开头的token，但是在使用阶段ErnieTokenizer处理中文时都是按单字拆的，导致##开头的中文token完全不会用到
https://github.com/PaddlePaddle/PaddleNLP/blob/c11a1465e167e494934e61d86c04d69167997fe2/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/create_pretraining_data.py#L168-L181)

**Comment by wawltor** [comment]
这里用##表示的含义是这个词不是一个中文或者英文单词开始的token，在ERNIE预训练的过程中可以通过##来将同一组单词识别处理，并且进行whole word mask

**Comment by renmada** [comment]
比如"样本"，预训练处理时“本”-> '##本'->token id，也就是在预训练中“本”的token id是 '##本'的token_id；但是在下游任务中“本”的token id是 '本'的token_id。
以上是我的理解，请问对吗？
https://github.com/PaddlePaddle/PaddleNLP/blob/c11a1465e167e494934e61d86c04d69167997fe2/applications/neural_search/recall/domain_adaptive_pretraining/data_tools/create_pretraining_data.py#L268-L273

**Comment by wawltor** [comment]
> 
嗯嗯 是这样的，预训练和下游任务finetune的tokenizer处理方式不太一样

**Comment by renmada** [comment]
所以目前预训练whole word mask数据处理是不是不合理，应该优化
