### ISSUE TITLE
ImportError: cannot import name 'einsum' from 'paddle' 

### ISSUE THREAD

**Issue by jaykay233** [PaddlePaddle/PaddleNLP#1833]
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
paddlenlp 2.2.5
paddlepaddle-gpu       2.1.2.post101
2）系统环境：
https://aistudio.baidu.com/aistudio/projectdetail/2017202, 就ai studio自己的环境
- 复现信息：运行这个notebook就能发现出错
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/58713995/159923527-bc6de0c8-2ec7-41b1-98bf-f73df9d7a9e8.png">

**Comment by wawltor** [comment]
您好，Paddle的版本低了导致这个问题，可以升级Paddle的版本到最新的版本。

**Comment by jaykay233** [comment]
> 您好，Paddle的版本低了导致这个问题，可以升级Paddle的版本到最新的版本。

感谢

**Comment by jaykay233** [comment]
> 您好，Paddle的版本低了导致这个问题，可以升级Paddle的版本到最新的版本。

感谢

**Comment by xiaolinpeter** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/27184803/179887505-587c6d6f-0416-4ad4-abc1-aa40a00c61a1.png">
@wawltor 您好，我在cpu运行报上面错误，paddlenlp版本是2.3.3
