### ISSUE TITLE
stacl.utils.tokenizer导入STACLTokenizer报错

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/PaddleNLP#1834]
- 版本、环境信息
1）PaddlePaddle2.2.2
2）Aistudio 至尊版
- 复现信息：如为报错，请给出复现环境、复现步骤

1. ~/PaddleNLP/examples/simultaneous_translation/stacl目录下执行以下代码报错

from utils.tokenizer import STACLTokenizer

报错信息为

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_192/326717331.py in <module>
----> 1 from utils.tokenizer import STACLTokenizer

~/PaddleNLP/examples/simultaneous_translation/stacl/utils/tokenizer.py in <module>
     15 import _locale
     16 import jieba
---> 17 from subword_nmt import subword_nmt
     18 
     19 # By default, the Windows system opens the file with GBK code,

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/subword_nmt/subword_nmt.py in <module>
     93     sys.stdin = codecs.getreader('UTF-8')(sys.stdin)
     94 else:
---> 95     sys.stderr = codecs.getwriter('UTF-8')(sys.stderr.buffer)
     96     sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer)
     97     sys.stdin = codecs.getreader('UTF-8')(sys.stdin.buffer)

AttributeError: 'OutStream' object has no attribute 'buffer'

2. 如果执行stacl推理，只需要将txt文档按行分词后缀为.bpe即可吗

3. 希望提供示例代码中的文件data/nist2m/test_08.zh.bpe作为格式参考，如果有test_08.zh的源文件和转化bpe后的文件作为格式参考就更好啦

**Comment by guoshengCS** [comment]
> AttributeError: 'OutStream' object has no attribute 'buffer'

这个报错是发生在了subword_nmt包中，查了下按照 https://github.com/ipython/ipykernel/issues/786 中的回复`sys.stdout.buffer`这种用法是不建议的（` it should be considered a bug anywhere sys.stdout.buffer is accessed unconditionally`），可否试下换下subword_nmt的版本。另外按照那个issue中的描述也可以看下在非Jupyter的python环境是否可以。

2、3 还请 @gongel 看下

**Comment by gongel** [comment]
你好
2. 对的，和[配置文件](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/config/transformer.yaml#L20)中一致即可
3. 数据格式见[README.md](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)，源文件和转化bpe后的格式可以参考[分词的输入和输出](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/README.md#%E6%95%B0%E6%8D%AE%E5%88%86%E8%AF%8D)

**Comment by Liyulingyue** [comment]
> > 属性错误："外流"对象没有属性"缓冲区"
> 
> 这个报错是发生在了subword_nmt包中，查了下按照 [ipython/ipykernel#786](https://github.com/ipython/ipykernel/issues/786) 中的回复这种用法是不建议的（），可否试下换下subword_nmt的版本。另外按照那个issue中的描述也可以看下在非Jupyter的python环境是否可以。`sys.stdout.buffer`` it should be considered a bug anywhere sys.stdout.buffer is accessed unconditionally`
> 
> 2、3 还请 @gongel 看下

感谢回复~ 试了一下，不能再ipynb环境中调用，但是可以通过脚本调用

**Comment by Liyulingyue** [comment]
> 你好 2. 对的，和[配置文件](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/config/transformer.yaml#L20)中一致即可 3. 数据格式见[README.md](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/README.md#%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F)，源文件和转化bpe后的格式可以参考[分词的输入和输出](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/README.md#%E6%95%B0%E6%8D%AE%E5%88%86%E8%AF%8D)

好的~ 感谢~
