### ISSUE TITLE
关于 T5 的对齐问题

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/PaddleNLP#1836]
在[Transformers API](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/transformers.rst)看到 PaddleNLP 现在支持了 T5，有两个问题请教一下：
- 文档中没有写 T5-3B，请问是否现在还不支持？
- T5 的所有参数是和 transformers 对齐的吗？

**Comment by FrostML** [comment]
麻烦 @yingyibiao 关注下

**Comment by yingyibiao** [comment]
非常感谢你的关注。
1. 目前还没支持 T5-3B，预计本周会完成支持。
2. 参数是对齐的。

**Comment by ShaneTian** [comment]
感谢回复！

1. 好的。
2. 请问 forward 和 backward 有验证过可以完全对齐是吗？
3. 是否有推荐的参数迁移工具？（pytroch -> paddle）

**Comment by yingyibiao** [comment]
1. forward 和 backward 均验证过可以完全对齐。
2. 目前没有通用的迁移工具，需要针对不同的结构进行适配。

**Comment by ShaneTian** [comment]
1. 好的。
2. 针对 `transformers.T5ForConditionalGeneration` 有迁移的脚本/工具吗？

**Comment by yingyibiao** [comment]
参考：https://github.com/JunnYu/paddle_t5/blob/main/convert.py

**Comment by ShaneTian** [comment]
收到，非常感谢！我试试看~

**Comment by Yoshiko-Arsenault** [comment]
Also, is there a plan to adapt `t5-11b`?

**Comment by ShaneTian** [comment]
> 非常感谢你的关注。
> 
> 1. 目前还没支持 T5-3B，预计本周会完成支持。
> 2. 参数是对齐的。

@yingyibiao 请问 3b 有进展吗？

**Comment by yingyibiao** [comment]
> Also, is there a plan to adapt `t5-11b`?

已经支持 t5-11b

**Comment by yingyibiao** [comment]
> > 非常感谢你的关注。
> > 
> > 1. 目前还没支持 T5-3B，预计本周会完成支持。
> > 2. 参数是对齐的。
> 
> @yingyibiao 请问 3b 有进展吗？

已经支持 t5-3b

**Comment by ShaneTian** [comment]
谢谢。
看到 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/transformers.rst 还未更新，请问在 `paddlenlp=2.2.5` 还是 `develop` 代码？传入 `t5-3b` 即可吗？ @yingyibiao

**Comment by yingyibiao** [comment]
文档已更新。
