### ISSUE TITLE
TextCNN模型运行textcnn/deploy/python/predict.py时报错：In copy_from_cpu, we only support numpy ndarray and list[str] data type.

### ISSUE THREAD

**Issue by wke22** [PaddlePaddle/PaddleNLP#1837]
环境：python 3.9、PaddlePaddle 2.2.2、PaddleNLP 2.2.4、windows、device：cpu

1。根据https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/textcnn/README.md中的步骤进行到用finetune好的模型进行预测的那步了。
2。运行textcnn/deploy/python/predict.py报错信息如下
![image](https://user-images.githubusercontent.com/67145269/160316553-7b9cb436-2947-46f0-a254-c4272b83a534.png)

**Comment by wawltor** [comment]
您好，修复PR已经合入，https://github.com/PaddlePaddle/PaddleNLP/pull/1839  辛苦再试一下
