### ISSUE TITLE
Embedding的输入为什么使[batch_size,1],而不是[batch_size,vocabulary_size]

### ISSUE THREAD

**Issue by Taoboan1999** [PaddlePaddle/PaddleNLP#1853]
Embedding的输入应该是one-hot向量，也就是[batch_size,vocabulary_size]
为什么是[batch_size,1],而不是[batch_size,vocabulary_size]
具体代码如下：测试Skipgram的网络部分，我想观察经过embedding的shape变化
        print(center_words.shape)
        print(type(center_words))
        print(target_words.shape)
        print(type(target_words))
        center_words_emb = self.embedding(center_words)
        target_words_emb = self.embedding_out(target_words)
        print(center_words_emb.shape)
        print(type(center_words_emb))
        print(target_words_emb.shape)
        print(type(target_words_emb))
结果如下：
[512, 1]
<class 'paddle.Tensor'>
[512, 1]
<class 'paddle.Tensor'>
[512, 1, 200]
<class 'paddle.Tensor'>
[512, 1, 200]
<class 'paddle.Tensor'>
我认为的结果应该是：
[512, vocabulary_size]
<class 'paddle.Tensor'>
[512, vocabulary_size]
<class 'paddle.Tensor'>
[512, 1, 200]
<class 'paddle.Tensor'>
[512, 1, 200]
<class 'paddle.Tensor'>

**Comment by joey12300** [comment]
你好，embedding的输入是id，所以是[batch_size,1]

**Comment by Taoboan1999** [comment]
您好，您的意思是说embedding内部就先把那个id转成one-hot向量，再用onehot向量做矩阵乘法吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] Embedding的输入为什么使[batch_size,1],而不是[batch_size,vocabulary_size] (Issue #1853)





 
你好，embedding的输入是id，所以是[batch_size,1]

**Comment by joey12300** [comment]
embedding内部直接根据id返回id对应行的向量，这个向量是稠密的，不是onehot向量

**Comment by Taoboan1999** [comment]
啊，那零基础学习深度学习 自然语言处理开源的那个skipgram代码的注释有问题啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] Embedding的输入为什么使[batch_size,1],而不是[batch_size,vocabulary_size] (Issue #1853)





 
embedding内部直接根据id返回id对应行的向量，这个向量是稠密的，不是onehot向量
