### ISSUE TITLE
efl静态图和动态图预测结果不一致

### ISSUE THREAD

**Issue by lastrei** [PaddlePaddle/PaddleNLP#1865]
paddlenlp版本：2.2.4
paddle版本2.2.2.post112
操作系统windows 11

动态图代码与efl分支下代码没有太大差别，除了数据集改用本地数据集，预测结果正常，在本地业务数据下有85+%的准确率
转换为静态图后发现预测结果完全不同，转换代码与efl/export_model.py 一致，预训练模型都使用ernie 1.0
转换后静态图后的预测代码如下:
具体标签名称已经替换为0-42的数字，表示一共43个类别
[issue.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8378992/issue.txt)
劳烦看一下可能是哪里发生的问题?.

**Comment by lastrei** [comment]
动态图转换静态图代码如下.
```python
import paddle
import paddlenlp as ppnlp
import os

label_map = {0: 'negative', 1: 'positive'}

model = ppnlp.transformers.ErnieForSequenceClassification.from_pretrained(
    'ernie-1.0', num_classes=2)
tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')

state_dict = paddle.load('./few_shot_train_model/model_119663/model_state.pdparams')

model.eval()

model = paddle.jit.to_static(
    model,
    input_spec=[
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64"),  # input_ids
        paddle.static.InputSpec(
            shape=[None, None], dtype="int64")  # segment_ids
    ])

save_path = os.path.join('./infer_model/few/', "inference")
paddle.jit.save(model, save_path)
```

**Comment by ZHUI** [comment]
看起来是模型的 state_dict 没有 set_state_dict到模型。

这样试试：
```python
state_dict = paddle.load('./few_shot_train_model/model_119663/model_state.pdparams')
model.set_state_dict(state_dict)
model.eval()
```

**Comment by lastrei** [comment]
> 看起来是模型的 state_dict 没有 set_state_dict到模型。
> 
> 这样试试：
> 
> ```python
> state_dict = paddle.load('./few_shot_train_model/model_119663/model_state.pdparams')
> model.set_state_dict(state_dict)
> model.eval()
> ```

赞美太阳！看了半天都没发现 导出的时候只写了load没有set_state_dict
感谢您的帮助！
