### ISSUE TITLE
ASR Text Correction

### ISSUE THREAD

**Issue by quicksandznzn** [PaddlePaddle/PaddleNLP#1875]
想咨询下有没有比较好的ASR的文本纠错模型

**Comment by zh794390558** [comment]
目前只有 ernie-csc模型，参看： https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_correction/ernie-csc/README.md

**Comment by quicksandznzn** [comment]
谢谢回复，已经看过这篇文章了~
