### ISSUE TITLE
Tokenizer 的 batch_encode 和 encode 接口暂未支持 add_special_tokens 开关，默认会直接加上 special tokens

### ISSUE THREAD

**Issue by tianxin1860** [PaddlePaddle/PaddleNLP#1876]
HF Tokenzier 提供了这个开关选项
![image](https://user-images.githubusercontent.com/6829601/160965853-96bd2302-4a19-4462-b0ae-66ddba11a7d8.png)

**Comment by wj-Mcat** [comment]
This feature is vital for tokenizer, but not required. Even so I hope this feature should be supported at later version.

**Comment by smallv0221** [comment]
> This feature is vital for tokenizer, but not required. Even so I hope this feature should be supported at later version.

This is now supported in develop branch. You are welcome to try.
