### ISSUE TITLE
是否有 Trainer 使用教程

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/PaddleNLP#1893]
看到现在 Transformers API 包含了 [Trainer](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/trainer)，想问下是否有对应的使用教程，还是说完全和 Hugging Face 的 Trainer 对齐？

**Comment by ZHUI** [comment]
你好，具体使用的例子可以参考这里
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0/finetune 

目前提供的是初步版本，需要改进迭代，功能上基本对齐 Hugging Face 的 Trainer，部分功能可能支持不全，欢迎使用反馈！

这里有个最新代码适配的PR，也可以参考这个 https://github.com/PaddlePaddle/PaddleNLP/pull/1892

**Comment by ShaneTian** [comment]
好的。
- 是否有正式版本的排期计划？
- 是否后续会出使用教程？

**Comment by ZHUI** [comment]
你好，4月底paddlenlp预计会发布 2.3 版本。届时会退出trainer的 aplha 初步版本，并配套教程。

基本功能是对齐 Hugging Face 的，也可先尝试 使用

**Comment by ShaneTian** [comment]
赞 👍
