### ISSUE TITLE
`Tokenizer` 未提供完整的 `padding` 策略

### ISSUE THREAD

**Issue by ShaneTian** [PaddlePaddle/PaddleNLP#1897]
现在的 Tokenizer 提供的 padding 方式只有：
- `True`：pad 到 `max_seq_len`
- `False`：不 pad
https://github.com/PaddlePaddle/PaddleNLP/blob/2000ea2ea88f5ef7804d1ee31f6b57f9feb6f006/paddlenlp/transformers/tokenizer_utils.py#L622-L625

而 Hugging Face 的 Tokenizer 提供了多一种：
- `longest`：pad 到当前 batch 的最大长度
https://github.com/huggingface/transformers/blob/3dc82427166239e2764196c07fa4c5dcc25b1590/src/transformers/tokenization_utils_base.py#L1256-L1264
![image](https://user-images.githubusercontent.com/42370681/161675324-f8b0908f-f29c-43d2-bdd7-16092330b387.png)
该选项在数据长度分布不均匀的时候还是比较有用的。

**Comment by wj-Mcat** [comment]
Agree with @ShaneTian . Although most of time we can only use max-mode to handle the inputs, but if user want to use more dynamic sequence length to full use info and gpu, longest-mod is vital for developers. How so you think about it?

**Comment by smallv0221** [comment]
您好，现在dynamic pad功能是通过paddlenlp.data中的collate function支持的，您可以参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/train.py#L132

**Comment by smallv0221** [comment]
我们有计划在后续版本中支持tokenizer的相应功能了
