### ISSUE TITLE
运行模型可解释性评估脚本时发现没有golden目录，缺少golden证据文件

### ISSUE THREAD

**Issue by lichade-son** [PaddlePaddle/PaddleNLP#1898]
运行模型可解释性评估脚本时发现没有golden目录，缺少golden证据文件
![image](https://user-images.githubusercontent.com/65451118/161717905-abf3a8ed-57b8-4dee-ad86-5bfe559466ba.png)
![image](https://user-images.githubusercontent.com/65451118/161717383-b8fed790-7df6-4c7f-b726-11cfd251d1df.png)

**Comment by guoshengCS** [comment]
@binlinquge  还请帮忙看下这个问题

**Comment by binlinquge** [comment]
你好，可解释性这块正在赛事中，golden数据集暂时还没有开源，可以移步https://aistudio.baidu.com/aistudio/competition/detail/159/0/submit-result进行结果提交和评估，谢谢~
