### ISSUE TITLE
AutoConfig is required

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#1899]
## Environment

```shell
paddlenlp                     2.2.5
paddlepaddle                  2.2.2
```

## Description

If I want to fetch the hidden_size of PLMs which I don't know the specific the type of PretrainedModel.  So how do I get the hidden size of the output. 

```python
from paddlenlp.transformers.auto.modeling import AutoModel
pretrained_model = AutoModel.from_pretrained(pretrained_model)

# get the hidden_size of the output. 
```

It's easy to achieve this in pytorch with transformers:
```python
from transformers import AutoConfig
config = AutoConfig.from_pretrained('bert-base-uncased')
print(config.hidden_size)
```

So, how can I achieve this in paddlenlp ?

**Comment by guoshengCS** [comment]
Currently,  code like `getattr(model, model.base_model_prefix).config['hidden_size']` can be used to get the value of `hidden_size` or any other configuration. However it is not no so plain. Thanks for the suggestion. We also plan to provide easier way to get the configurations, though maybe not use `AutoConfig`.

**Comment by wj-Mcat** [comment]
So glad to hear that, if you have any progress, you can link this issue so that I can get the it quickly.  Thanks.

**Comment by wj-Mcat** [comment]
Closed by fixed. 

All of I need is:

```shell
pip install --upgrade paddlenlp
```
