### ISSUE TITLE
paddlenlp.ops.ColumnParallelLiner 中合并output的API有有typo？

### ISSUE THREAD

**Issue by HoratioJSY** [PaddlePaddle/PaddleNLP#1903]
paddlenlp：2.2.5， paddlepaddle-gpu：2.2.0.post112，操作系统：Linux

在调用paddlenlp.ops.ColumnParallelLiner时发现，如果gather_out=True会报错，paddle不存在paddle.distributed.collective._concat。

在[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/distributed/parallel.py#L233](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/distributed/parallel.py#L233)，是不是需要改成 paddle.distributed.collective._c_concat？

**Comment by ZHUI** [comment]
这份代码比较早，应该是api发生了变动:


目前代码在这里，确实为`paddle.distributed.collective._c_concat`
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/fleet/meta_parallel/parallel_layers/mp_layers.py#L97

```python
    def forward(self, x):
        # use inner api to process identity
        if self.is_mp:
            input_parallel = paddle.distributed.collective._c_identity(
                x, group=self.model_parallel_group)
        else:
            input_parallel = x

        output_parallel = F.linear(
            input_parallel, self.weight, self.bias, name=self._name)

        if self.gather_output and self.is_mp:
            output = paddle.distributed.collective._c_concat(
                output_parallel, group=self.model_parallel_group)
        else:
            output = output_parallel
        return output
```

另 GPT 大模型可以参考，gpt-3  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/gpt-3/dygraph/modeling.py#L109-L114
模型并行的这几个 api 是动、静态图通用的。
