### ISSUE TITLE
Paddlenlp加载模型出错

### ISSUE THREAD

**Issue by ColaFei** [PaddlePaddle/PaddleNLP#1904]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
paddlePaddle-gpu: 2.2.2
PaddleNLP: 2.2.5
Python: 3.7.10
CUDA: 11.0
CUDNN: 8.0
![image](https://user-images.githubusercontent.com/37499167/161924304-90ed3ead-3a1f-41c6-920a-16db4b2d7abe.png)

**Comment by w5688414** [comment]
进入python解释器，输入import paddle ，再输入 paddle.utils.run_check()

**Comment by w5688414** [comment]
安装正确版本的paddle： https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by guoshengCS** [comment]
这个可能是因为安装的Paddle包和CUDA环境不匹配，还请再确认下是否安装了和CUDA环境对应的Paddle包
<img width="829" alt="image" src="https://user-images.githubusercontent.com/14105589/161933173-b2087290-7099-48bb-b036-2f6a25b2dcca.png">
