### ISSUE TITLE
【BUG】clue tnews 在不指定 split 参数的情况下，load_datasets 会报错

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/PaddleNLP#1908]
clue tnews 在不指定 split 参数的情况下，load_datasets 会报错， 如图
<img width="1037" alt="05d0aeb5abfdcda9138422002998d26f" src="https://user-images.githubusercontent.com/16911935/162115458-a164d824-7fe3-4ac3-9973-319a71d07775.png">

**Comment by LiuChiachi** [comment]
这个定位到tnews的splits有个test1.0的问题，这个问题@smallv0221 已经在看了
