### ISSUE TITLE
ernie-health-chinese预训练权重404

### ISSUE THREAD

**Issue by Paul0M** [PaddlePaddle/PaddleNLP#1912]
paddlenlp 2.2.5
使用cblue, NER训练出现

**Comment by LiuChiachi** [comment]
HI，我刚看了下代码，可能下载链接更新了，现在是这个下载链接：
"https://paddlenlp.bj.bcebos.com/models/transformers/ernie-health-chinese/ernie-health-chinese.pdparams"
最新的代码在这里，https://github.com/PaddlePaddle/PaddleNLP/blob/00af227211e904521cc627aaf81d20b2383a8841/paddlenlp/transformers/electra/modeling.py#L352
这部分可能没有进入paddlenlp 2.2.5版本中

**Comment by Paul0M** [comment]
跑训练命令，出现的下载路径是：https://bj.bcebos.com/paddlenlp/models/transformers/community/ernie-health-chinese/model_state.pdparams

但在对应的site-packages里搜，没有上述路径，
```
./electra/tokenizer.py:            "ehealth-chinese":
./electra/tokenizer.py:            "https://paddlenlp.bj.bcebos.com/models/transformers/ehealth_chinese/vocab.txt"
./electra/tokenizer.py:        "ehealth-chinese": {
./electra/modeling.py:        "ehealth-chinese": {
./electra/modeling.py:            "ehealth-chinese":
./electra/modeling.py:            "https://paddlenlp.bj.bcebos.com/models/transformers/ehealth_chinese/ehealth-chinese.pdparams"
```

将key改为ehealth-chinese就可以跑了，只是不知这样改是否对应ernie-health-chinese？

**Comment by LemonNoel** [comment]
这是因为在develop版本中更新了模型名称，ehealth-chinese和ernie-health-chinese对应的参数是相同的，后续版本发布后会统一使用ernie-health-chinese。

**Comment by Paul0M** [comment]
还有一个小问题，如果想在医疗健康领域做NER，数据集比较小，类别可能和CMeEE有很大差别，下面哪种方案你们比较推荐：
1. 在ernie-health-chinese上直接fine-tune自己的小数据集
2. 在ernie-health-chinese上fine-tune CMeEE，再基于得到的结果fine-tune自己的小数据集

**Comment by LemonNoel** [comment]
这个可能要看类别差异具体有多大，数据质量也会有影响。之前我在单张V100上fine-tune CMeEE耗时都在五分钟以内，可以两种方案都尝试一下，直接对比一下结果哈。

**Comment by Paul0M** [comment]
谢谢，请问fine-tune NER，每个类别至少出现多少次，才会达到不错的泛化效果，有没有经验值参考？毕竟真正转化成标签时类别会是3-4倍的量
