### ISSUE TITLE
roberta-wwm-ext的tokenizer会把文本中的空格忽略掉

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#1913]
tokenizer = paddlenlp.transformers.RobertaTokenizer.from_pretrained('roberta-wwm-ext').tokenizer
text = '京侠 加热鼠标垫超大号桌垫发热保暖手桌垫电脑办公室电热学生写字桌面来图定制 36*60神器女神'
text = '一 二 三'
a = tokenizer.basic_tokenizer.tokenize(text)
print(a)

结果
['一', '二', '三']

不想让它忽略要怎么办？

**Comment by smallv0221** [comment]
您好，roberta中文预训练模型分词的时候会忽略中文字符，词表中也没有空格字符。请问您需要保留空格的原因是什么呢

**Comment by zouhan6806504** [comment]
> 您好，roberta中文预训练模型分词的时候会忽略中文字符，词表中也没有空格字符。请问您需要保留空格的原因是什么呢

ner，空格会出现在一些非O的标记中，目前是用“|”替换了空格
