### ISSUE TITLE
[Feature Request] T5 的FastTransformer支持

### ISSUE THREAD

**Issue by luyaojie** [PaddlePaddle/PaddleNLP#1914]
尝试使用BART[Transformer高性能加速](https://paddlenlp.readthedocs.io/zh/latest/advanced_guide/fastergeneration/fastertransformer.html#transformer)，提速非常明显（3090测试约10倍）。

请问同样采用encoder-decoder架构的T5上是否也可以支持该特性？

**Comment by jiuwuxiaohun** [comment]
@FrostML 啥时候支持T5的Fast啊，排个期啊感谢
