### ISSUE TITLE
KeyError: 1 When I run simcse predict.py

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#1916]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/simcse/deploy/python/predict.py

Traceback (most recent call last):
  File "deploy/python/predict.py", line 278, in <module>
    res = predictor.predict(corpus_list, tokenizer)
  File "deploy/python/predict.py", line 227, in predict
    idx: text[1]
KeyError: 1

Env:
Name: paddlepaddle
Version: 2.2.1
Name: paddlenlp
Version: 2.2.2
Python 3.7.4

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by w5688414** [comment]
问题修复了，感谢反馈。https://github.com/PaddlePaddle/PaddleNLP/pull/1918
