### ISSUE TITLE
PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/ 运行预训练，报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1921]
报错如下

`aistudio@jupyter-271421-3579112:~/23_12345_96166/model/train/domain_adaptive_pretraining$ python -u  -m paddle.distributed.launch \
>     --gpus "0" \
>     --log_dir "output/ernie-1.0-dp8-gb1024/log" \
>     run_pretrain_static.py \
>     --model_type "ernie" \
>     --model_name_or_path "ernie-1.0" \
>     --input_dir "./data" \
>     --output_dir "output/ernie-1.0-dp8-gb1024" \
>     --max_seq_len 512 \
>     --micro_batch_size 1 \
>     --global_batch_size 1 \
>     --sharding_degree 1 \
>     --dp_degree 1 \
>     --use_sharding false \
>     --use_amp true \
>     --use_recompute false \
>     --max_lr 0.0001 \
>     --min_lr 0.00001 \
>     --max_steps 200000 \
>     --save_steps 100000 \
>     --checkpoint_steps 5000 \
>     --decay_steps 1980000 \
>     --weight_decay 0.01 \
>     --warmup_rate 0.01 \
>     --grad_clip 1.0 \
>     --num_workers 1 \
>     --logging_freq 20 \
>     --eval_freq 1000 \
>     --device "gpu"
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: output/ernie-1.0-dp8-gb1024/log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: run_pretrain_static.py
training_script_args: ['--model_type', 'ernie', '--model_name_or_path', 'ernie-1.0', '--input_dir', './data', '--output_dir', 'output/ernie-1.0-dp8-gb1024', '--max_seq_len', '512', '--micro_batch_size', '1', '--global_batch_size', '1', '--sharding_degree', '1', '--dp_degree', '1', '--use_sharding', 'false', '--use_amp', 'true', '--use_recompute', 'false', '--max_lr', '0.0001', '--min_lr', '0.00001', '--max_steps', '200000', '--save_steps', '100000', '--checkpoint_steps', '5000', '--decay_steps', '1980000', '--weight_decay', '0.01', '--warmup_rate', '0.01', '--grad_clip', '1.0', '--num_workers', '1', '--logging_freq', '20', '--eval_freq', '1000', '--device', 'gpu']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-04-09 10:45:43,605 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-04-09 10:45:43,610 launch_utils.py:528] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:48708               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:48708               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-04-09 10:45:43,610 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in output/ernie-1.0-dp8-gb1024/log/endpoints.log, and detail running logs maybe found in output/ernie-1.0-dp8-gb1024/log/workerlog.0
launch proc_id:2682 idx:0
[2022-04-09 10:45:45,127] [    INFO] - paddle commit id    :b031c389938bfa15e15bb20494c76f86289d77b0
[2022-04-09 10:45:45,127] [    INFO] - model_type          :ernie
[2022-04-09 10:45:45,127] [    INFO] - model_name_or_path  :ernie-1.0
[2022-04-09 10:45:45,127] [    INFO] - input_dir           :./data
[2022-04-09 10:45:45,127] [    INFO] - output_dir          :output/ernie-1.0-dp8-gb1024
[2022-04-09 10:45:45,127] [    INFO] - split               :949,50,1
[2022-04-09 10:45:45,127] [    INFO] - max_seq_len         :512
[2022-04-09 10:45:45,127] [    INFO] - micro_batch_size    :1
[2022-04-09 10:45:45,127] [    INFO] - global_batch_size   :1
[2022-04-09 10:45:45,127] [    INFO] - weight_decay        :0.01
[2022-04-09 10:45:45,127] [    INFO] - grad_clip           :1.0
[2022-04-09 10:45:45,128] [    INFO] - max_lr              :0.0001
[2022-04-09 10:45:45,128] [    INFO] - min_lr              :1e-05
[2022-04-09 10:45:45,128] [    INFO] - warmup_rate         :0.01
[2022-04-09 10:45:45,128] [    INFO] - adam_beta1          :0.9
[2022-04-09 10:45:45,128] [    INFO] - adam_beta2          :0.999
[2022-04-09 10:45:45,128] [    INFO] - adam_epsilon        :1e-08
[2022-04-09 10:45:45,128] [    INFO] - num_train_epochs    :1
[2022-04-09 10:45:45,128] [    INFO] - max_steps           :200000
[2022-04-09 10:45:45,128] [    INFO] - checkpoint_steps    :5000
[2022-04-09 10:45:45,128] [    INFO] - save_steps          :100000
[2022-04-09 10:45:45,128] [    INFO] - decay_steps         :1980000
[2022-04-09 10:45:45,128] [    INFO] - logging_freq        :20
[2022-04-09 10:45:45,128] [    INFO] - eval_freq           :1000
[2022-04-09 10:45:45,128] [    INFO] - eval_iters          :10
[2022-04-09 10:45:45,128] [    INFO] - use_sharding        :False
[2022-04-09 10:45:45,128] [    INFO] - sharding_degree     :1
[2022-04-09 10:45:45,128] [    INFO] - dp_degree           :1
[2022-04-09 10:45:45,128] [    INFO] - mp_degree           :1
[2022-04-09 10:45:45,128] [    INFO] - pp_degree           :1
[2022-04-09 10:45:45,128] [    INFO] - use_recompute       :False
[2022-04-09 10:45:45,128] [    INFO] - use_amp             :True
[2022-04-09 10:45:45,129] [    INFO] - enable_addto        :True
[2022-04-09 10:45:45,129] [    INFO] - scale_loss          :128
[2022-04-09 10:45:45,129] [    INFO] - hidden_dropout_prob :0.1
[2022-04-09 10:45:45,129] [    INFO] - attention_probs_dropout_prob:0.1
[2022-04-09 10:45:45,129] [    INFO] - seed                :1234
[2022-04-09 10:45:45,129] [    INFO] - num_workers         :1
[2022-04-09 10:45:45,129] [    INFO] - check_accuracy      :None
[2022-04-09 10:45:45,129] [    INFO] - device              :gpu
[2022-04-09 10:45:45,129] [    INFO] - lr_decay_style      :cosine
[2022-04-09 10:45:45,129] [    INFO] - share_folder        :None
[2022-04-09 10:45:45,129] [    INFO] - masked_lm_prob      :0.15
[2022-04-09 10:45:45,129] [    INFO] - short_seq_prob      :0.1
[2022-04-09 10:45:45,129] [    INFO] - test_iters          :100
[2022-04-09 10:45:45,130] [    INFO] - The topo of hybrid parallelism:
dp_info:
         GroupInfo(size=1, rank=0, world=[0]), 
pp_info:
         GroupInfo(size=1, rank=0, world=[0]), 
sharding_info:
         GroupInfo(size=1, rank=0, world=[0]), 
mp_info:
         GroupInfo(size=1, rank=0, world=[0])
data_info:
         GroupInfo(size=1, rank=0, world=[0])
[2022-04-09 10:45:45,131] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/ernie-1.0/vocab.txt
 > building dataset index ...
 > finished creating indexed dataset in 0.004987 seconds
 > indexed dataset stats:
    number of documents: 110
    number of sentences: 530
949,50,1
[0, 104, 110, 110]
 > dataset split:
    train:
     document indices in [0, 104) total of 104 documents
     sentence indices in [0, 506) total of 506 sentences
    validation:
     document indices in [104, 110) total of 6 documents
     sentence indices in [506, 530) total of 24 sentences
    test:
     document indices in [110, 110) total of 0 documents
     sentence indices in [530, 530) total of 0 sentences
 > WARNING: could not find index map file ./data/baike_sample_train_indexmap_200000mns_509msl_0.10ssp_1234s.npy, building the indices on rank 0 ...
int32
 > building sapmles index mapping for train ...
make: Entering directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
    using uint32 for data mapping...
    using:
     number of documents:            104
     sentences range:                [0, 506)
     total number of sentences:      506
     number of epochs:               2147483646
     maximum number of samples:      200000
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 200000 samples after 1825 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 200010 samples
 > done building sapmles index maping
 > saved the index mapping in ./data/baike_sample_train_indexmap_200000mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.071237
 > loading indexed mapping from ./data/baike_sample_train_indexmap_200000mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 200010
 > WARNING: could not find index map file ./data/baike_sample_valid_indexmap_2010mns_509msl_0.10ssp_1234s.npy, building the indices on rank 0 ...
int32
 > building sapmles index mapping for valid ...
make: Entering directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
    using uint32 for data mapping...
    using:
     number of documents:            6
     sentences range:                [506, 530)
     total number of sentences:      24
     number of epochs:               2147483646
     maximum number of samples:      2010
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 2010 samples after 332 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 2011 samples
 > done building sapmles index maping
 > saved the index mapping in ./data/baike_sample_valid_indexmap_2010mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.041837
 > loading indexed mapping from ./data/baike_sample_valid_indexmap_2010mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 2011
Traceback (most recent call last):
  File "run_pretrain_static.py", line 676, in <module>
    do_train(config)
  File "run_pretrain_static.py", line 388, in do_train
    current_step=global_step)
  File "run_pretrain_static.py", line 143, in create_pretrained_dataset
    test_dl = loader(test_ds, 0)
  File "run_pretrain_static.py", line 127, in loader
    consumed_samples=consumed_samples)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/batch_sampler.py", line 120, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
TypeError: object of type 'NoneType' has no len()
INFO 2022-04-09 10:45:50,637 launch_utils.py:341] terminate all the procs
ERROR 2022-04-09 10:45:50,637 launch_utils.py:604] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-04-09 10:45:54,641 launch_utils.py:341] terminate all the procs`

**Comment by w5688414** [comment]
看上去是数据集的问题，具体要看具体是怎样操作的，请问是在aistudio上运行的吗？如果是，能否提供一下项目地址。

**Comment by AI-Mart** [comment]
项目地址：https://aistudio.baidu.com/aistudio/projectdetail/3774711?shared=1

安装文档提示，按以下步骤操作的

1、
pip install tqdm numpy pybind11 lac zstandard

2、
mkdir data && cd data
wget https://paddlenlp.bj.bcebos.com/models/transformers/data_tools/baike.txt
cd ..

3、
python trans_to_json.py  --input_path ./data --output_path baike_sample

4、
python -u  create_pretraining_data.py \
    --model_name ernie-1.0 \
    --tokenizer_name ErnieTokenizer \
    --input_path baike_sample.jsonl \
    --split_sentences\
    --chinese \
    --cn_whole_word_segment \
    --output_prefix baike_sample  \
    --workers 1 \
    --log_interval 5

5、
cd ..
mkdir data
mv ./data_tools/baike_sample* ./data

6、
python -u  -m paddle.distributed.launch \
    --gpus "0" \
    --log_dir "output/ernie-1.0-dp8-gb1024/log" \
    run_pretrain_static.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-1.0" \
    --input_dir "./data" \
    --output_dir "output/ernie-1.0-dp8-gb1024" \
    --max_seq_len 512 \
    --micro_batch_size 1 \
    --global_batch_size 1 \
    --sharding_degree 1 \
    --dp_degree 1 \
    --use_sharding false \
    --use_amp true \
    --use_recompute false \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 200000 \
    --save_steps 100000 \
    --checkpoint_steps 5000 \
    --decay_steps 1980000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --num_workers 1 \
    --logging_freq 20 \
    --eval_freq 1000 \
    --device "gpu"

**Comment by skywangch** [comment]
这个问题是因为在进行数据划分的时候，原始数据集太小，按照比例得到的验证集大小为0
解决方法：
编辑 args.py 文件，找到
parser.add_argument("--split", type=str, default='949,50,1', help="Train/valid/test data split.")
这一行，这个就是数据集划分比例，其中test只占了 1/1000，如果数据集太小，就会约等于0

可以改成 '8,1,1'，这样test、val分别占到 1/10 
或者，使原始数据集足够大

**Comment by w5688414** [comment]
parser.add_argument("--split", type=str, default='50,50,50', help="Train/valid/test data split.")

**Comment by w5688414** [comment]
parser.add_argument("--split", type=str, default='8,1,1', help="Train/valid/test data split.")

看看

```
python -u  -m paddle.distributed.launch \
    --gpus "0" \
    --log_dir "output/ernie-1.0-dp8-gb1024/log" \
    run_pretrain_static.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-1.0" \
    --input_dir "./data" \
    --output_dir "output/ernie-1.0-dp8-gb1024" \
    --max_seq_len 512 \
    --micro_batch_size 2 \
    --global_batch_size 2 \
    --sharding_degree 1 \
    --dp_degree 1 \
    --use_sharding false \
    --use_amp true \
    --use_recompute false \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 200000 \
    --save_steps 100000 \
    --checkpoint_steps 5000 \
    --decay_steps 1980000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --num_workers 1 \
    --logging_freq 20 \
    --eval_freq 1000 \
    --device "gpu"
```

建议使用大量数据集进行训练

**Comment by AI-Mart** [comment]
> parser.add_argument("--split", type=str, default='8,1,1', help="Train/valid/test data split.")
> 
> 看看
> 
> ```
> python -u  -m paddle.distributed.launch \
>     --gpus "0" \
>     --log_dir "output/ernie-1.0-dp8-gb1024/log" \
>     run_pretrain_static.py \
>     --model_type "ernie" \
>     --model_name_or_path "ernie-1.0" \
>     --input_dir "./data" \
>     --output_dir "output/ernie-1.0-dp8-gb1024" \
>     --max_seq_len 512 \
>     --micro_batch_size 2 \
>     --global_batch_size 2 \
>     --sharding_degree 1 \
>     --dp_degree 1 \
>     --use_sharding false \
>     --use_amp true \
>     --use_recompute false \
>     --max_lr 0.0001 \
>     --min_lr 0.00001 \
>     --max_steps 200000 \
>     --save_steps 100000 \
>     --checkpoint_steps 5000 \
>     --decay_steps 1980000 \
>     --weight_decay 0.01 \
>     --warmup_rate 0.01 \
>     --grad_clip 1.0 \
>     --num_workers 1 \
>     --logging_freq 20 \
>     --eval_freq 1000 \
>     --device "gpu"
> ```
> 
> 建议使用大量数据集进行训练

谢谢，这么更改后可以了，建议把这个更新到官方源代码和readme,毕竟我是按照官方文档一路操作过来的，想验证试试能否运行跑通。其他的小伙伴安装文档操作估计也会遇到。

**Comment by AI-Mart** [comment]
1、运行/domain_adaptive_pretraining/data_tools/trans_to_json.py，生产的样本，相比原数据增加了一倍，不知道是否正常
2、用自己的数据集，大概一千条左右，每条都当做单独的doc,即每个doc只有一条数据一个\n，doc之间用空格隔开，启动run_pretrain_static.py 预训练后代码卡主了，没往下运行

`aistudio@jupyter-271421-3579112:~/23_12345_96166/model/train/domain_adaptive_pretraining$     python -u  -m paddle.distributed.launch \
>     --gpus "0" \
>     --log_dir "../model_pretrein/ernie-1.0-dp8-gb1024/log" \
>     run_pretrain_static.py \
>     --model_type "ernie" \
>     --model_name_or_path "ernie-1.0" \
>     --input_dir "./data" \
>     --output_dir "../model_pretrein/ernie-1.0-dp8-gb1024" \
>     --max_seq_len 512 \
>     --micro_batch_size 32 \
>     --global_batch_size 32 \
>     --sharding_degree 1 \
>     --dp_degree 1 \
>     --use_sharding false \
>     --use_amp true \
>     --use_recompute false \
>     --max_lr 0.0001 \
>     --min_lr 0.00001 \
>     --max_steps 200000 \
>     --save_steps 100000 \
>     --checkpoint_steps 5000 \
>     --decay_steps 1980000 \
>     --weight_decay 0.01 \
>     --warmup_rate 0.01 \
>     --grad_clip 1.0 \
>     --num_workers 1 \
>     --logging_freq 20 \
>     --eval_freq 1000 \
>     --device "gpu"
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: ../model_pretrein/ernie-1.0-dp8-gb1024/log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: run_pretrain_static.py
training_script_args: ['--model_type', 'ernie', '--model_name_or_path', 'ernie-1.0', '--input_dir', './data', '--output_dir', '../model_pretrein/ernie-1.0-dp8-gb1024', '--max_seq_len', '512', '--micro_batch_size', '32', '--global_batch_size', '32', '--sharding_degree', '1', '--dp_degree', '1', '--use_sharding', 'false', '--use_amp', 'true', '--use_recompute', 'false', '--max_lr', '0.0001', '--min_lr', '0.00001', '--max_steps', '200000', '--save_steps', '100000', '--checkpoint_steps', '5000', '--decay_steps', '1980000', '--weight_decay', '0.01', '--warmup_rate', '0.01', '--grad_clip', '1.0', '--num_workers', '1', '--logging_freq', '20', '--eval_freq', '1000', '--device', 'gpu']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-04-15 17:19:34,808 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-04-15 17:19:34,813 launch_utils.py:528] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:40861               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:40861               |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                        0                      |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-04-15 17:19:34,813 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in ../model_pretrein/ernie-1.0-dp8-gb1024/log/endpoints.log, and detail running logs maybe found in ../model_pretrein/ernie-1.0-dp8-gb1024/log/workerlog.0
launch proc_id:9804 idx:0
[2022-04-15 17:19:36,631] [    INFO] - paddle commit id    :b031c389938bfa15e15bb20494c76f86289d77b0
[2022-04-15 17:19:36,631] [    INFO] - model_type          :ernie
[2022-04-15 17:19:36,631] [    INFO] - model_name_or_path  :ernie-1.0
[2022-04-15 17:19:36,631] [    INFO] - input_dir           :./data
[2022-04-15 17:19:36,631] [    INFO] - output_dir          :../model_pretrein/ernie-1.0-dp8-gb1024
[2022-04-15 17:19:36,631] [    INFO] - split               :8,1,1
[2022-04-15 17:19:36,632] [    INFO] - max_seq_len         :512
[2022-04-15 17:19:36,632] [    INFO] - micro_batch_size    :32
[2022-04-15 17:19:36,632] [    INFO] - global_batch_size   :32
[2022-04-15 17:19:36,632] [    INFO] - weight_decay        :0.01
[2022-04-15 17:19:36,632] [    INFO] - grad_clip           :1.0
[2022-04-15 17:19:36,632] [    INFO] - max_lr              :0.0001
[2022-04-15 17:19:36,632] [    INFO] - min_lr              :1e-05
[2022-04-15 17:19:36,632] [    INFO] - warmup_rate         :0.01
[2022-04-15 17:19:36,632] [    INFO] - adam_beta1          :0.9
[2022-04-15 17:19:36,632] [    INFO] - adam_beta2          :0.999
[2022-04-15 17:19:36,632] [    INFO] - adam_epsilon        :1e-08
[2022-04-15 17:19:36,632] [    INFO] - num_train_epochs    :1
[2022-04-15 17:19:36,632] [    INFO] - max_steps           :200000
[2022-04-15 17:19:36,632] [    INFO] - checkpoint_steps    :5000
[2022-04-15 17:19:36,632] [    INFO] - save_steps          :100000
[2022-04-15 17:19:36,632] [    INFO] - decay_steps         :1980000
[2022-04-15 17:19:36,632] [    INFO] - logging_freq        :20
[2022-04-15 17:19:36,632] [    INFO] - eval_freq           :1000
[2022-04-15 17:19:36,632] [    INFO] - eval_iters          :10
[2022-04-15 17:19:36,632] [    INFO] - use_sharding        :False
[2022-04-15 17:19:36,633] [    INFO] - sharding_degree     :1
[2022-04-15 17:19:36,633] [    INFO] - dp_degree           :1
[2022-04-15 17:19:36,633] [    INFO] - mp_degree           :1
[2022-04-15 17:19:36,633] [    INFO] - pp_degree           :1
[2022-04-15 17:19:36,633] [    INFO] - use_recompute       :False
[2022-04-15 17:19:36,633] [    INFO] - use_amp             :True
[2022-04-15 17:19:36,633] [    INFO] - enable_addto        :True
[2022-04-15 17:19:36,633] [    INFO] - scale_loss          :128
[2022-04-15 17:19:36,633] [    INFO] - hidden_dropout_prob :0.1
[2022-04-15 17:19:36,633] [    INFO] - attention_probs_dropout_prob:0.1
[2022-04-15 17:19:36,633] [    INFO] - seed                :1234
[2022-04-15 17:19:36,633] [    INFO] - num_workers         :1
[2022-04-15 17:19:36,633] [    INFO] - check_accuracy      :None
[2022-04-15 17:19:36,633] [    INFO] - device              :gpu
[2022-04-15 17:19:36,633] [    INFO] - lr_decay_style      :cosine
[2022-04-15 17:19:36,633] [    INFO] - share_folder        :None
[2022-04-15 17:19:36,633] [    INFO] - masked_lm_prob      :0.15
[2022-04-15 17:19:36,633] [    INFO] - short_seq_prob      :0.1
[2022-04-15 17:19:36,633] [    INFO] - test_iters          :100
[2022-04-15 17:19:36,635] [    INFO] - The topo of hybrid parallelism:
dp_info:
         GroupInfo(size=1, rank=0, world=[0]), 
pp_info:
         GroupInfo(size=1, rank=0, world=[0]), 
sharding_info:
         GroupInfo(size=1, rank=0, world=[0]), 
mp_info:
         GroupInfo(size=1, rank=0, world=[0])
data_info:
         GroupInfo(size=1, rank=0, world=[0])
[2022-04-15 17:19:36,636] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/ernie-1.0/vocab.txt
 > building dataset index ...
 > finished creating indexed dataset in 0.005913 seconds
 > indexed dataset stats:
    number of documents: 2002
    number of sentences: 2002
8,1,1
[0, 1602, 1802, 2002]
 > dataset split:
    train:
     document indices in [0, 1602) total of 1602 documents
     sentence indices in [0, 1602) total of 1602 sentences
    validation:
     document indices in [1602, 1802) total of 200 documents
     sentence indices in [1602, 1802) total of 200 sentences
    test:
     document indices in [1802, 2002) total of 200 documents
     sentence indices in [1802, 2002) total of 200 sentences
 > WARNING: could not find index map file ./data/baike_sample_train_indexmap_6400000mns_509msl_0.10ssp_1234s.npy, building the indices on rank 0 ...
int32
 > building sapmles index mapping for train ...
make: Entering directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/aistudio/23_12345_96166/model/train/domain_adaptive_pretraining/data_tools'
    using uint32 for data mapping...
    using:
     number of documents:            1602
     sentences range:                [0, 1602)
     total number of sentences:      1602
     number of epochs:               2147483646
     maximum number of samples:      6400000
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234`

**Comment by AI-Mart** [comment]
代码地址：https://aistudio.baidu.com/aistudio/projectdetail/3774711?contributionType=1&shared=1 

`   
# 1
 python trans_to_json.py \
        --input_path ../data/data_origin \
        --output_path ../data/baike_sample \

# 2
    python -u  create_pretraining_data.py \
        --model_name ernie-1.0 \
        --tokenizer_name ErnieTokenizer \
        --input_path ../data/baike_sample.jsonl \
        --split_sentences\
        --chinese \
        --cn_whole_word_segment \
        --output_prefix ../data/baike_sample  \
        --workers 10 \
        --log_interval 5

# 3
    python -u  -m paddle.distributed.launch \
    --gpus "0" \
    --log_dir "../model_pretrein/ernie-1.0-dp8-gb1024/log" \
    run_pretrain_static.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-1.0" \
    --input_dir "./data" \
    --output_dir "../model_pretrein/ernie-1.0-dp8-gb1024" \
    --max_seq_len 512 \
    --micro_batch_size 32 \
    --global_batch_size 32 \
    --sharding_degree 1 \
    --dp_degree 1 \
    --use_sharding false \
    --use_amp true \
    --use_recompute false \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 200000 \
    --save_steps 100000 \
    --checkpoint_steps 5000 \
    --decay_steps 1980000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --num_workers 1 \
    --logging_freq 20 \
    --eval_freq 1000 \
    --device "gpu"`

**Comment by w5688414** [comment]
预训练数据的格式变一下：

一个句子占一行
两个doc之间有一个空行

**Comment by AI-Mart** [comment]
嗯，一个句号结束代表一个句子，已解决，谢谢
