### ISSUE TITLE
roberta预训练处理数据用到了hf 的transformer，没法在aistudio上运行

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#1923]
aistudio禁了torch，导致create_data.py没法运行
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/roberta

如果要继续预训练roberta，自己准备数据，格式是怎么样的？

**Comment by ZHUI** [comment]
收到，我这边尝试下，是否可以切换为 Paddlenlp 的 AutoTokenizer，感谢反馈

**Comment by ZHUI** [comment]
> aistudio禁了torch，导致create_data.py没法运行 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/roberta
> 
> 如果要继续预训练roberta，自己准备数据，格式是怎么样的？

这里我们跟 HF 采用的是一样的数据格式，也可以本地create 之后，在上传处理之后的数据集
