### ISSUE TITLE
语义检索模型，请问下面两个文件在哪里呢？

### ISSUE THREAD

**Issue by BaiIIzt** [PaddlePaddle/PaddleNLP#1925]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/75989862/162621627-1d9f5d1a-bdee-4f67-99aa-5bd242636221.png)

**Comment by BaiIIzt** [comment]
请问，inference.get_pooled_embedding.pdiparams和inference.get_pooled_embedding.pdmodel这个模型在哪里呢，是什么呢？我替换成用自己训练出了的simcse模型的话会出现报错
![image](https://user-images.githubusercontent.com/75989862/162624510-9568e138-1b3b-4a48-83db-a8428b5da608.png)
我的配置是
![image](https://user-images.githubusercontent.com/75989862/162624542-ebc8d5a3-f4bc-47e1-9a08-6fb72c58e635.png)

**Comment by w5688414** [comment]
是使用下面的脚本导出的静态图参数：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/simcse/scripts/export_model.sh

**Comment by BaiIIzt** [comment]
已解决 谢谢
