### ISSUE TITLE
examples/language_model/pretraining_data_prepare/main.py准备数据很慢

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#1926]
版本最新develop，环境aistudio
我的数据200w，每行150字符以内，已经安装标准准备好

```
甘斯（GANSI）︱不锈钢带齿镊子︱加硬︱镊子︱圆头镊子12/14/16/18/20/25/30cm︱弯头25cm

送钢化膜vivoV1732A直边手机壳y81s纯色V1732T二代硅胶保护套Y81

得力同款4空白无酸牛皮封面封底纸装订纸档案专用纸档案盒纸封皮卷皮纸︱无酸纸80克A4型200装

包邮︱10个价史努比饼干包装拉链袋︱ins卡通史努比自封袋口罩袋

创意中国风复古礼盒高档实用商务礼品套装公司企业会议年会聚会活动纪念品刻字定制LOGO鼠标垫鼠标精美小︱清明上河图鼠标+垫
```

使用命令
```
!python /home/aistudio/PaddleNLP-develop/examples/language_model/pretraining_data_prepare/main.py --skip_formatting True \
    --formatted_file /home/aistudio/work/pretrain/unlabel_train_and_ali.txt \
    --output_dir /home/aistudio/pre_datas/unlabel_train_and_ali/ \
    --model_name bert-wwm-chinese \
    --n_train_shards 256 \
    --n_test_shards 1 \
    --fraction_test_set 0.1 \
    --max_seq_length 128 \
    --max_predictions_per_seq 20 \
    --masked_lm_prob 0.15  
```

在处理train那一部分时很快，但是处理test的时候，就是一个一个来，约0.8s到1s处理一条。那个shards为1的时候影响这么大吗？我看了下最后生成的数据，每个shards也就是生成一个txt文件，约520kb左右，test文件14mb

**Comment by ZHUI** [comment]
我简单算一下，train的话，一个shard是0.5M， 总共是128M多，test是 14M，跟` --fraction_test_set 0.1`比较一致。
这边建议的话，可以将 ` --fraction_test_set 0.1` 设置小一点，比如 0.01
```
    --n_train_shards 256 \
    --n_test_shards 1 \
    --fraction_test_set 0.1 \
```

另外想问一下，您这边主要的需求是什么？想训练哪一个模型，如果是 ernie的话，可以参考  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0

**Comment by zouhan6806504** [comment]
> 我简单算一下，train的话，一个shard是0.5M， 总共是128M多，test是 14M，跟` --fraction_test_set 0.1`比较一致。 这边建议的话，可以将 ` --fraction_test_set 0.1` 设置小一点，比如 0.01
> 
> ```
>     --n_train_shards 256 \
>     --n_test_shards 1 \
>     --fraction_test_set 0.1 \
> ```
> 
> 另外想问一下，您这边主要的需求是什么？想训练哪一个模型，如果是 ernie的话，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0

数据的切分是没什么问题的，就是当参数设置为1的时候生成很慢。比如保持fraction_test_set=0.1，设置n_test_shards=1 ，n_test_shards=100，这两者处理耗费的时间能差约100倍
