### ISSUE TITLE
examples/language_model/bert/create_pretraining_data.py处理数据内存溢出

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#1927]
版本最新develop，环境aistudio
数据由examples/language_model/pretraining_data_prepare/main.py准备完成，共256个train.txt,每个520kb，一个test.txt，14mb
执行命令
```
!python /home/aistudio/PaddleNLP-develop/examples/language_model/bert/create_pretraining_data.py \
  --input_file=/home/aistudio/pre_datas/single_from_unlabel_train/sharded_train_shards_256_test_shards_1_fraction_0.1/sharding_train_0.txt \
  --output_file=/home/aistudio/pre_datas/training_data_single_from_unlabel_train.hdf5 \
  --bert_model=bert-wwm-chinese \
  --max_seq_length=128 \
  --max_predictions_per_seq=20 \
  --masked_lm_prob=0.15 \
  --random_seed=12345 \
  --dupe_factor=5
```
内存不断升高，最后超过16g环境崩溃
我看了下代码，是将所有文本都通过编码转成features，最后再一次性存成h5py文件，这个是不是正常现象，数据稍微多点就没法继续预训练了

**Comment by ZHUI** [comment]
内存只有16G吗？建议采用大一点的机器试试。我这边也看看能否改进。

同之前issue，如果是训练 ernie-1.0 的话，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0 

虽然数据制造还是放在内存，如果有需要，我这边可以支持一下 mmap 到硬盘
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/data_tools/create_pretraining_data.py#L314

**Comment by zouhan6806504** [comment]
> 内存只有16G吗？建议采用大一点的机器试试。我这边也看看能否改进。
> 
> 同之前issue，如果是训练 ernie-1.0 的话，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
> 
> 虽然数据制造还是放在内存，如果有需要，我这边可以支持一下 mmap 到硬盘 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/data_tools/create_pretraining_data.py#L314

aistudio的配置就只有这么大，我写了个循环，每个文件都单独生成一次，算是绕过去了
因为后续的训练支持读取多个hdf5文件，其实可以每个txt单独生成hdf5，而不是全部txt合起来生成一个
