### ISSUE TITLE
bert run_pretrain不会一边训练一边eval，但是生成数据集的时候有test，这是为什么?

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#1929]

**Comment by ZHUI** [comment]
确实存在这个问题，十分抱歉

同之前 issue，ernie-1.0 这块的 train valid test是完善的。 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
