### ISSUE TITLE
paddleNLP对百度的DDparser的支持？

### ISSUE THREAD

**Issue by wdhxek** [PaddlePaddle/PaddleNLP#193]
感谢paddleNLP的开源工作!
想问下，百度自家发布的依存句法分析树 DDParser这个工具，后续是否计划融合到paddlenlp中？
[DDparser](https://github.com/baidu/DDParser/), 目前DDparser还不支持paddlepaddle2.0，后续各个工具版本之间融合和同步，是否会统一到PaddleNLP中？

祝好！

**Comment by wawltor** [comment]
您好，目前我们正在对PaddleNLP的句法分析模块正进行升级，DDparser也在计划中，后续有进度反馈给您！
