### ISSUE TITLE
切换paddle版本后paddlenlp运行出错

### ISSUE THREAD

**Issue by AhriZ08** [PaddlePaddle/PaddleNLP#1931]
paddlepaddle-gpu:2.1.3
paddlenlp:2.2.5
之前安装paddlepaddle-gpu:2.2版本提示cudnn需要8.2，但是已经安装了cuda11.2+cudnn8.2.0，然后尝试降低paddlepaddle-gpu版本，安装2.1.3版本的paddle后，没有改变原来paddlenlp版本，运行报错cannot import name 'einsum' from 'paddle'

**Comment by ZHUI** [comment]
建议使用 paddle 2.2，paddlenlp这边使用了一些最新的 paddle api，比如 这里的 `einsum `
出现一些版本提示，是正常现象
可以参考官网教程安装
https://www.paddlepaddle.org.cn/ 
```shell
python -m pip install paddlepaddle-gpu==2.2.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
