### ISSUE TITLE
PaddleNLP搭建命名实体识别模型，到第七轮，GPU就运行不动？

### ISSUE THREAD

**Issue by yangnianen** [PaddlePaddle/PaddleNLP#1935]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
paddlenlp                          2.2.5
paddlepaddle-gpu                   0.0.0.post102

2）系统环境：Windows10，python 3.8
- 复现信息：如为报错，请给出复现环境、复现步骤

![image](https://user-images.githubusercontent.com/17618881/162692348-d768950f-0e7a-4316-bf76-983ea3a057ce.png)

**Comment by ZHUI** [comment]
可否贴一下使用的代码地址？

**Comment by yangnianen** [comment]
```python
import paddle
import paddle.nn as nn
# paddle.set_device('cpu')
import paddlenlp
from functools import partial
from paddlenlp.datasets import MapDataset
from paddlenlp.data import Stack, Tuple, Pad
from paddlenlp.layers import LinearChainCrf, ViterbiDecoder, LinearChainCrfLoss
from paddlenlp.metrics import ChunkEvaluator
from utils import load_dict, evaluate, predict, parse_decodes1, parse_decodes2
from paddlenlp.transformers import ErnieTokenizer, ErnieForTokenClassification, ErnieGramTokenizer, ErnieGramForTokenClassification
from utils import convert_example
def load_dataset(datafiles):
    def read(data_path):
        with open(data_path, 'r', encoding='utf-8') as fp:
            next(fp)
            for line in fp.readlines():
                words, labels = line.strip('\n').split('\t')
                words = words.split('\002')
                labels = labels.split('\002')
                yield words, labels
    if isinstance(datafiles, str):
        return MapDataset(list(read(datafiles)))
    elif isinstance(datafiles, list) or isinstance(datafiles, tuple):
        return [MapDataset(list(read(datafile))) for datafile in datafiles]

train_ds, dev_ds, test_ds = load_dataset(datafiles=(
        './express_ner/train.txt', './express_ner/dev.txt', './express_ner/test.txt'))
# train_ds, dev_ds, test_ds = load_dataset(datafiles=('express_ner/train.txt', 'express_ner/dev.txt', 'express_ner/test.txt'))


label_vocab = load_dict('./express_ner/tag.dic')

# 设置想要使用模型的名称
MODEL_NAME = "ernie-1.0"
tokenizer = ErnieTokenizer.from_pretrained(MODEL_NAME)

trans_func = partial(convert_example, tokenizer=tokenizer, label_vocab=label_vocab)

train_ds.map(trans_func)
dev_ds.map(trans_func)
test_ds.map(trans_func)
ignore_label = -1
batchify_fn = lambda samples, fn=Tuple(
    Pad(dtype='int64',axis=0, pad_val=tokenizer.pad_token_id),  # input_ids
    Pad(dtype='int64',axis=0, pad_val=tokenizer.pad_token_type_id),  # token_type_ids
    Stack(dtype='int64'),  # seq_len
    Pad(dtype='int64',axis=0, pad_val=ignore_label)  # labels
): fn(samples)

train_loader = paddle.io.DataLoader(
    dataset=train_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)
dev_loader = paddle.io.DataLoader(
    dataset=dev_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)
test_loader = paddle.io.DataLoader(
    dataset=test_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)


# Define the model netword and its loss
model = ErnieForTokenClassification.from_pretrained("ernie-1.0", num_classes=len(label_vocab))

metric = ChunkEvaluator(label_list=label_vocab.keys(), suffix=True)
loss_fn = paddle.nn.loss.CrossEntropyLoss(ignore_index=ignore_label)
optimizer = paddle.optimizer.AdamW(learning_rate=2e-5, parameters=model.parameters())

step = 0
for epoch in range(10):
    # Switch the model to training mode
    model.train()
    for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
        logits = model(input_ids, token_type_ids)
        loss = paddle.mean(loss_fn(logits, labels))
        loss.backward()
        optimizer.step()
        optimizer.clear_grad()
        step += 1
        print("epoch:%d - step:%d - loss: %f" % (epoch, step, loss))
    evaluate(model, metric, dev_loader)

    paddle.save(model.state_dict(),
                './ernie_result/model_%d.pdparams' % step)
# model.save_pretrained('./checkpoint')
# tokenizer.save_pretrained('./checkpoint')

preds = predict(model, test_loader, test_ds, label_vocab)
file_path = "ernie_results.txt"
with open(file_path, "w", encoding="utf8") as fout:
    fout.write("\n".join(preds))
# Print some examples
print(
    "The results have been saved in the file: %s, some examples are shown below: "
    % file_path)
print("\n".join(preds[:10]))
```

**Comment by yangnianen** [comment]
`import paddle
import paddle.nn as nn
# paddle.set_device('cpu')
import paddlenlp
from functools import partial
from paddlenlp.datasets import MapDataset
from paddlenlp.data import Stack, Tuple, Pad
from paddlenlp.layers import LinearChainCrf, ViterbiDecoder, LinearChainCrfLoss
from paddlenlp.metrics import ChunkEvaluator
from utils import load_dict, evaluate, predict, parse_decodes1, parse_decodes2
from paddlenlp.transformers import ErnieTokenizer, ErnieForTokenClassification, ErnieGramTokenizer, ErnieGramForTokenClassification
from utils import convert_example

def load_dataset(datafiles):
    def read(data_path):
        with open(data_path, 'r', encoding='utf-8') as fp:
            next(fp)
            for line in fp.readlines():
                words, labels = line.strip('\n').split('\t')
                words = words.split('\002')
                labels = labels.split('\002')
                yield words, labels

    if isinstance(datafiles, str):
        return MapDataset(list(read(datafiles)))
    elif isinstance(datafiles, list) or isinstance(datafiles, tuple):
        return [MapDataset(list(read(datafile))) for datafile in datafiles]

train_ds, dev_ds, test_ds = load_dataset(datafiles=(
        './express_ner/train.txt', './express_ner/dev.txt', './express_ner/test.txt'))
# train_ds, dev_ds, test_ds = load_dataset(datafiles=('express_ner/train.txt', 'express_ner/dev.txt', 'express_ner/test.txt'))


label_vocab = load_dict('./express_ner/tag.dic')

# 设置想要使用模型的名称
MODEL_NAME = "ernie-1.0"
tokenizer = ErnieTokenizer.from_pretrained(MODEL_NAME)

trans_func = partial(convert_example, tokenizer=tokenizer, label_vocab=label_vocab)

train_ds.map(trans_func)
dev_ds.map(trans_func)
test_ds.map(trans_func)
ignore_label = -1
batchify_fn = lambda samples, fn=Tuple(
    Pad(dtype='int64',axis=0, pad_val=tokenizer.pad_token_id),  # input_ids
    Pad(dtype='int64',axis=0, pad_val=tokenizer.pad_token_type_id),  # token_type_ids
    Stack(dtype='int64'),  # seq_len
    Pad(dtype='int64',axis=0, pad_val=ignore_label)  # labels
): fn(samples)

train_loader = paddle.io.DataLoader(
    dataset=train_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)
dev_loader = paddle.io.DataLoader(
    dataset=dev_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)
test_loader = paddle.io.DataLoader(
    dataset=test_ds,
    batch_size=200,
    return_list=True,
    collate_fn=batchify_fn)


# Define the model netword and its loss
model = ErnieForTokenClassification.from_pretrained("ernie-1.0", num_classes=len(label_vocab))

metric = ChunkEvaluator(label_list=label_vocab.keys(), suffix=True)
loss_fn = paddle.nn.loss.CrossEntropyLoss(ignore_index=ignore_label)
optimizer = paddle.optimizer.AdamW(learning_rate=2e-5, parameters=model.parameters())

step = 0
for epoch in range(10):
    # Switch the model to training mode
    model.train()
    for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
        logits = model(input_ids, token_type_ids)
        loss = paddle.mean(loss_fn(logits, labels))
        loss.backward()
        optimizer.step()
        optimizer.clear_grad()
        step += 1
        print("epoch:%d - step:%d - loss: %f" % (epoch, step, loss))
    evaluate(model, metric, dev_loader)

    paddle.save(model.state_dict(),
                './ernie_result/model_%d.pdparams' % step)
# model.save_pretrained('./checkpoint')
# tokenizer.save_pretrained('./checkpoint')

preds = predict(model, test_loader, test_ds, label_vocab)
file_path = "ernie_results.txt"
with open(file_path, "w", encoding="utf8") as fout:
    fout.write("\n".join(preds))
# Print some examples
print(
    "The results have been saved in the file: %s, some examples are shown below: "
    % file_path)
print("\n".join(preds[:10]))`

**Comment by yangnianen** [comment]
不知道为什么，贴上去，会变成如上那样挺乱的。
[code.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8462293/code.txt)

**Comment by yangnianen** [comment]
paddleNlP 挺多BUG，这框架，有点让人苦恼。

**Comment by ZHUI** [comment]
这样，我建议，你卡住的地方，直接 crtl-c中断，看看卡住在哪里？

**Comment by ZHUI** [comment]
Windows 平台，使用测试得比较少，如有问题，敬请谅解，我们一发现会快速修复的。

**Comment by yangnianen** [comment]
嗯，谢谢了，工具很强大，但在教学和生产开发过程中遇到太多问题了，还是换回pytorch。

**Comment by ZHUI** [comment]
可不能是，evaluate 的耗时比较长，没有日志输出，让人误以为卡住？

**Comment by yangnianen** [comment]
到第7轮时候，就定住了，没有打印任何内容，程序就挂掉了。可能命名实体识别训练比较消耗GPU，GPU不够导致的，把batch_size搞成32就可以运行完。为了教学方便用了spyder作为开发工具，这应该是我们的问题。
然后paddlehub，运行 model = hub.Module(name='ernie', task='token-cls', label_map=label_map) 会报错，提示没有 ernie这个模块。显然有问题

**Comment by yangnianen** [comment]
ModuleNotFoundError: No module named 'ernie.module' ， 有没有教学文档可以通过离线下载，解决这个问题？

**Comment by ZHUI** [comment]
好的，辛苦 @linjieccc 看一下PaddleHub的问题

**Comment by linjieccc** [comment]
> ModuleNotFoundError: No module named 'ernie.module' ， 有没有教学文档可以通过离线下载，解决这个问题？

你好，方便提供下PaddleHub的版本号么

**Comment by yangnianen** [comment]
> > ModuleNotFoundError: No module named 'ernie.module' ， 有没有教学文档可以通过离线下载，解决这个问题？
> 
> 你好，方便提供下PaddleHub的版本号么

paddlehub      2.2.0

**Comment by linjieccc** [comment]
可以参考下这个issue看能不能解决问题哈 https://github.com/PaddlePaddle/PaddleHub/issues/1394

**Comment by zhanghaok** [comment]
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：
>   paddlenlp                          2.2.5
>   paddlepaddle-gpu                   0.0.0.post102
> 
> 2）系统环境：Windows10，python 3.8
> 
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> ![image](https://user-images.githubusercontent.com/17618881/162692348-d768950f-0e7a-4316-bf76-983ea3a057ce.png)

你好请问能否将你的Linux下的paddnlp环境打包分享一下啊，我尝试装paddle装了好久一直失败，呜呜呜谢谢了，我的邮箱是3250514239@qq.com
