### ISSUE TITLE
使用 feature_extract.py 进行向量抽取结果不正确

### ISSUE THREAD

**Issue by WangJieWJ** [PaddlePaddle/PaddleNLP#1943]
``欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

直接使用的docker环境 registry.baidubce.com/paddlepaddle/paddle:2.2.2
PaddlePaddle : 2.2.2
PaddleNLP : 2.2.5 手动做过升级

**向量抽取的结果如下：**
![image](https://user-images.githubusercontent.com/16323371/162936406-bf448fc2-f6de-42ad-a627-9684b4ceb1c5.png)

1、首先使用下面的脚本导出的静态图参数：
model_state.pdparams 来自于 https://bj.bcebos.com/v1/paddlenlp/models/simcse_model.zip
代码位置：PaddleNLP/applications/neural_search/recall/simcse/export_model.py
```
python export_model.py \
    --params_path /data/robot/simcse_model/model_20000/model_state.pdparams \
    --output_path /data/robot/simcse_model/output
```

2、进行语义向量提取
代码位置：PaddleNLP/applications/neural_search/recall/milvus/feature_extract.py
```
python feature_extract.py \
        --model_dir "/data/robot/simcse_model/output" \
        --corpus_file "data/milvus_data.csv" \
        --device "cpu" \
        --max_seq_length 64 \
        --batch_size 32
```

3、以下是使用AiStudio上的GPU资源运行的结果
```
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ python feature_extract.py \
>         --model_dir "/home/aistudio/neural_search/output" \
>         --corpus_file "data/milvus_data.csv" \
>         --device "gpu" \
>         --max_seq_length 64 \
>         --batch_size 32
W0412 17:50:22.347800   618 analysis_predictor.cc:795] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
I0412 17:50:23.054283   618 fuse_pass_base.cc:57] ---  detected 2 subgraphs
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
I0412 17:50:23.130518   618 fuse_pass_base.cc:57] ---  detected 148 subgraphs
--- Running IR pass [map_matmul_v2_to_matmul_pass]
I0412 17:50:23.137193   618 fuse_pass_base.cc:57] ---  detected 25 subgraphs
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0412 17:50:23.350721   618 fuse_pass_base.cc:57] ---  detected 148 subgraphs
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
I0412 17:50:23.431000   618 fuse_pass_base.cc:57] ---  detected 48 subgraphs
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0412 17:50:23.481848   618 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0412 17:50:23.959134   618 analysis_predictor.cc:714] ======= optimize end =======
I0412 17:50:23.983723   618 naive_executor.cc:98] ---  skip [feed], feed -> title_input_ids
I0412 17:50:23.983779   618 naive_executor.cc:98] ---  skip [feed], feed -> query_input_ids
I0412 17:50:23.991245   618 naive_executor.cc:98] ---  skip [mean_0.tmp_0], fetch -> fetch
[2022-04-12 17:50:23,991] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/ernie-1.0/vocab.txt
  0%|                                                                                                                                 | 0/271 [00:00<?, ?it/s]W0412 17:50:24.028337   618 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0412 17:50:24.032928   618 device_context.cc:465] device: 0, cuDNN Version: 7.6.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 271/271 [00:03<00:00, 85.15it/s]
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ ls
base_model.py         data                 embedding_recall.py  inference.py      openApi.py   remark.txt
config.py             data.py              ernieEncoder.py      milvus_insert.py  __pycache__  scripts
corpus_embedding.npy  embedding_insert.py  feature_extract.py   milvus_recall.py  README.md    server_config.yml
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ ls -al
总用量 112
drwxr-xr-x 5 aistudio aistudio  4096 4月  12 17:50 .
drwxr-xr-x 6 aistudio aistudio  4096 4月  11 10:57 ..
-rw-r--r-- 1 aistudio aistudio  7182 2月  25 17:57 base_model.py
-rw-r--r-- 1 aistudio aistudio   925 2月  25 17:57 config.py
-rw-r--r-- 1 aistudio aistudio   136 4月  12 17:50 corpus_embedding.npy
drwxr-xr-x 2 aistudio aistudio  4096 4月  12 17:48 data
-rw-r--r-- 1 aistudio aistudio  6427 2月  25 17:57 data.py
-rw-r--r-- 1 aistudio aistudio  1413 2月  25 17:57 embedding_insert.py
-rw-r--r-- 1 aistudio aistudio  1418 2月  25 17:57 embedding_recall.py
-rw-r--r-- 1 aistudio aistudio  2638 4月  12 10:45 ernieEncoder.py
-rw-r--r-- 1 aistudio aistudio  7047 4月  12 14:46 feature_extract.py
-rw-r--r-- 1 aistudio aistudio  3398 2月  25 17:57 inference.py
-rw-r--r-- 1 aistudio aistudio  4034 2月  25 17:57 milvus_insert.py
-rw-r--r-- 1 aistudio aistudio  1693 2月  25 17:57 milvus_recall.py
-rw-r--r-- 1 aistudio aistudio   902 4月  11 16:57 openApi.py
drwxr-xr-x 2 aistudio aistudio  4096 4月  12 17:48 __pycache__
-rw-r--r-- 1 aistudio aistudio  6420 4月  12 14:46 README.md
-rw-r--r-- 1 aistudio aistudio   228 4月  12 13:44 remark.txt
drwxr-xr-x 2 aistudio aistudio  4096 4月  12 14:46 scripts
-rw-r--r-- 1 aistudio aistudio 19792 2月  25 17:57 server_config.yml
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> b = np.load('corpus_embedding.npy')
>>> print (b)
[4.6151204 4.6151204]
>>> exit()
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ more ./data/
milvus_data.csv       .milvus_data.csv.swp
aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ more ./data/milvus_data.csv
出了花月瑶的鞋
黄电容信仰加持
y从废柴到欧洲巡演发唱片到学会了一个人生活，errol长大了声线粗了也有了自己的同龄朋友，这是我看过最好的英剧前三。
结语：随着国家“二孩”政策的放开，越来越多的消费者倾向于购买空间更宽敞，舒适性更强的mpv车型。
玩一慧？
```

**Comment by tianxin1860** [comment]
基于我们开源的数据抽取向量有问题吗？

**Comment by WangJieWJ** [comment]
> 

嗯嗯，我使用的数据只是从开源的数据中截取了一部分

**Comment by w5688414** [comment]
> ``欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
>   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> * 复现信息：如为报错，请给出复现环境、复现步骤
> 
> 直接使用的docker环境 registry.baidubce.com/paddlepaddle/paddle:2.2.2 PaddlePaddle : 2.2.2 PaddleNLP : 2.2.5 手动做过升级
> 
> **向量抽取的结果如下：** ![image](https://user-images.githubusercontent.com/16323371/162936406-bf448fc2-f6de-42ad-a627-9684b4ceb1c5.png)
> 
> 1、首先使用下面的脚本导出的静态图参数： model_state.pdparams 来自于 https://bj.bcebos.com/v1/paddlenlp/models/simcse_model.zip 代码位置：PaddleNLP/applications/neural_search/recall/simcse/export_model.py
> 
> ```
> python export_model.py \
>     --params_path /data/robot/simcse_model/model_20000/model_state.pdparams \
>     --output_path /data/robot/simcse_model/output
> ```
> 
> 2、进行语义向量提取 代码位置：PaddleNLP/applications/neural_search/recall/milvus/feature_extract.py
> 
> ```
> python feature_extract.py \
>         --model_dir "/data/robot/simcse_model/output" \
>         --corpus_file "data/milvus_data.csv" \
>         --device "cpu" \
>         --max_seq_length 64 \
>         --batch_size 32
> ```
> 
> 3、以下是使用AiStudio上的GPU资源运行的结果
> 
> ```
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ python feature_extract.py \
> >         --model_dir "/home/aistudio/neural_search/output" \
> >         --corpus_file "data/milvus_data.csv" \
> >         --device "gpu" \
> >         --max_seq_length 64 \
> >         --batch_size 32
> W0412 17:50:22.347800   618 analysis_predictor.cc:795] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
> --- Running analysis [ir_graph_build_pass]
> --- Running analysis [ir_graph_clean_pass]
> --- Running analysis [ir_analysis_pass]
> --- Running IR pass [is_test_pass]
> --- Running IR pass [simplify_with_basic_ops_pass]
> --- Running IR pass [conv_affine_channel_fuse_pass]
> --- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
> --- Running IR pass [conv_bn_fuse_pass]
> --- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
> --- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
> I0412 17:50:23.054283   618 fuse_pass_base.cc:57] ---  detected 2 subgraphs
> --- Running IR pass [multihead_matmul_fuse_pass_v2]
> --- Running IR pass [squeeze2_matmul_fuse_pass]
> --- Running IR pass [reshape2_matmul_fuse_pass]
> --- Running IR pass [flatten2_matmul_fuse_pass]
> --- Running IR pass [map_matmul_v2_to_mul_pass]
> I0412 17:50:23.130518   618 fuse_pass_base.cc:57] ---  detected 148 subgraphs
> --- Running IR pass [map_matmul_v2_to_matmul_pass]
> I0412 17:50:23.137193   618 fuse_pass_base.cc:57] ---  detected 25 subgraphs
> --- Running IR pass [map_matmul_to_mul_pass]
> --- Running IR pass [fc_fuse_pass]
> I0412 17:50:23.350721   618 fuse_pass_base.cc:57] ---  detected 148 subgraphs
> --- Running IR pass [fc_elementwise_layernorm_fuse_pass]
> I0412 17:50:23.431000   618 fuse_pass_base.cc:57] ---  detected 48 subgraphs
> --- Running IR pass [conv_elementwise_add_act_fuse_pass]
> --- Running IR pass [conv_elementwise_add2_act_fuse_pass]
> --- Running IR pass [conv_elementwise_add_fuse_pass]
> --- Running IR pass [transpose_flatten_concat_fuse_pass]
> --- Running IR pass [runtime_context_cache_pass]
> --- Running analysis [ir_params_sync_among_devices_pass]
> I0412 17:50:23.481848   618 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
> --- Running analysis [adjust_cudnn_workspace_size_pass]
> --- Running analysis [inference_op_replace_pass]
> --- Running analysis [ir_graph_to_program_pass]
> I0412 17:50:23.959134   618 analysis_predictor.cc:714] ======= optimize end =======
> I0412 17:50:23.983723   618 naive_executor.cc:98] ---  skip [feed], feed -> title_input_ids
> I0412 17:50:23.983779   618 naive_executor.cc:98] ---  skip [feed], feed -> query_input_ids
> I0412 17:50:23.991245   618 naive_executor.cc:98] ---  skip [mean_0.tmp_0], fetch -> fetch
> [2022-04-12 17:50:23,991] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/ernie-1.0/vocab.txt
>   0%|                                                                                                                                 | 0/271 [00:00<?, ?it/s]W0412 17:50:24.028337   618 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
> W0412 17:50:24.032928   618 device_context.cc:465] device: 0, cuDNN Version: 7.6.
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 271/271 [00:03<00:00, 85.15it/s]
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ ls
> base_model.py         data                 embedding_recall.py  inference.py      openApi.py   remark.txt
> config.py             data.py              ernieEncoder.py      milvus_insert.py  __pycache__  scripts
> corpus_embedding.npy  embedding_insert.py  feature_extract.py   milvus_recall.py  README.md    server_config.yml
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ ls -al
> 总用量 112
> drwxr-xr-x 5 aistudio aistudio  4096 4月  12 17:50 .
> drwxr-xr-x 6 aistudio aistudio  4096 4月  11 10:57 ..
> -rw-r--r-- 1 aistudio aistudio  7182 2月  25 17:57 base_model.py
> -rw-r--r-- 1 aistudio aistudio   925 2月  25 17:57 config.py
> -rw-r--r-- 1 aistudio aistudio   136 4月  12 17:50 corpus_embedding.npy
> drwxr-xr-x 2 aistudio aistudio  4096 4月  12 17:48 data
> -rw-r--r-- 1 aistudio aistudio  6427 2月  25 17:57 data.py
> -rw-r--r-- 1 aistudio aistudio  1413 2月  25 17:57 embedding_insert.py
> -rw-r--r-- 1 aistudio aistudio  1418 2月  25 17:57 embedding_recall.py
> -rw-r--r-- 1 aistudio aistudio  2638 4月  12 10:45 ernieEncoder.py
> -rw-r--r-- 1 aistudio aistudio  7047 4月  12 14:46 feature_extract.py
> -rw-r--r-- 1 aistudio aistudio  3398 2月  25 17:57 inference.py
> -rw-r--r-- 1 aistudio aistudio  4034 2月  25 17:57 milvus_insert.py
> -rw-r--r-- 1 aistudio aistudio  1693 2月  25 17:57 milvus_recall.py
> -rw-r--r-- 1 aistudio aistudio   902 4月  11 16:57 openApi.py
> drwxr-xr-x 2 aistudio aistudio  4096 4月  12 17:48 __pycache__
> -rw-r--r-- 1 aistudio aistudio  6420 4月  12 14:46 README.md
> -rw-r--r-- 1 aistudio aistudio   228 4月  12 13:44 remark.txt
> drwxr-xr-x 2 aistudio aistudio  4096 4月  12 14:46 scripts
> -rw-r--r-- 1 aistudio aistudio 19792 2月  25 17:57 server_config.yml
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ python
> Python 3.7.4 (default, Aug 13 2019, 20:35:49)
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy as np
> >>> b = np.load('corpus_embedding.npy')
> >>> print (b)
> [4.6151204 4.6151204]
> >>> exit()
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ more ./data/
> milvus_data.csv       .milvus_data.csv.swp
> aistudio@jupyter-260643-3496450:~/neural_search/recall/milvus$ more ./data/milvus_data.csv
> 出了花月瑶的鞋
> 黄电容信仰加持
> y从废柴到欧洲巡演发唱片到学会了一个人生活，errol长大了声线粗了也有了自己的同龄朋友，这是我看过最好的英剧前三。
> 结语：随着国家“二孩”政策的放开，越来越多的消费者倾向于购买空间更宽敞，舒适性更强的mpv车型。
> 玩一慧？
> ```

只抽取了3维的向量？能否提供一下aistudio项目地址呢？

**Comment by WangJieWJ** [comment]
@w5688414 你好，aistudio地址：https://aistudio.baidu.com/aistudio/projectdetail/3496450

**Comment by tianxin1860** [comment]
请问是直接运行 AIStudio 项目用我们开源的数据吗？还是做了一些什么修改？

**Comment by WangJieWJ** [comment]
> 请问是直接运行 AIStudio 项目用我们开源的数据吗？还是做了一些什么修改？

没做任何修改
1、代码直接下载的https://github.com/PaddlePaddle/PaddleNLP/archive/refs/heads/develop.zip
2、预训练模型用的是https://bj.bcebos.com/v1/paddlenlp/models/simcse_model.zip
3、数据用的是https://bj.bcebos.com/v1/paddlenlp/data/literature_search_data.zip 中的 milvus/milvus_data.csv

**Comment by w5688414** [comment]
模型调错了，simcse应该调用inference.get_pooled_embedding，feature_extract.py改一下这两行就行。
```

        model_file = model_dir + "/inference.get_pooled_embedding.pdmodel"
        params_file = model_dir + "/inference.get_pooled_embedding.pdiparams"
```
