### ISSUE TITLE
GPTModel.from_pretrained 加载报错

### ISSUE THREAD

**Issue by yingyibiao** [PaddlePaddle/PaddleNLP#1944]
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.2.5，PaddlePaddle 2.2.1
2）系统环境：MacOS，3.8.2
在一段代码中加载多个 gpt 模型（并不一定需要同一个权重）：
m = GPTModel.from_pretrained("gpt2-medium-en")
m = GPTModel.from_pretrained("gpt2-medium-en")
会出现报错： ValueError: parameter name [word_embeddings] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers
3）原因分析：
![image](https://user-images.githubusercontent.com/52000032/162965749-f719f1e2-7f4c-41e6-9328-0e1d07cbb070.png)
GPTEmbeddings 使用了 name="word_embeddings" 的 weight_attr，这个 weight_attr 在一个 python 程序中的作用域是全局的，会导致加载第二个 gpt 模型时候出现 parameter name [word_embeddings] have be been used 的现象。
4）解决方法：去除对 ParamAttr 的使用。

**Comment by wj-Mcat** [comment]
All of you need is to upgrade the version of PaddleNLP:

```shell
pip install --upgrade paddlenlp
```

**it works for me.**
