### ISSUE TITLE
skep_ernie_1.0_large_ch动转静预测报错

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#1946]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.2.5，PaddlePaddle 2.2.0
2）系统环境：Linux，Python 3.7.13

- 问题
skep_ernie_1.0_large_ch使用原始参数实现动转静
动转静代码使用
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/skep/export_model.py
预测代码使用
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/skep/deploy/python/predict.py

报错信息：
--- Running analysis [ir_graph_build_pass]
Traceback (most recent call last):
  File "/test.py", line 127, in <module>
    args.max_seq_length)
  File "/test.py", line 64, in __init__
    self.predictor = paddle.inference.create_predictor(config)
RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at /paddle/paddle/fluid/operators/load_combine_op.h:85)
  [operator < load_combine > error]

**Comment by gongel** [comment]
你好，保存的模型文件有问题吗？

**Comment by wjddd** [comment]
> 你好，保存的模型文件有问题吗？

已解决，感谢。

**Comment by Zachary199604** [comment]
请问楼主解决方法是啥呀

**Comment by Young-GG** [comment]
> > 你好，保存的模型文件有问题吗？
> 
> 已解决，感谢。

楼主 ，请问下是怎么解决的呢，最近也遇到这个问题，感谢感谢
