### ISSUE TITLE
『NLP打卡营』实践课4 基于预训练模型完成实体关系抽取结果出错 

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/PaddleNLP#1948]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/16698950/163169512-d3d57c6b-00d3-487b-a637-bd53f11993da.png">

**Comment by linjieccc** [comment]
对应AIStudio项目已更新，模型评估结果示例：
![image](https://user-images.githubusercontent.com/40840292/163578281-f9d56958-a0b4-4532-af02-f9ebc78fbd1b.png)

**Comment by kol66** [comment]
我也遇到这个问题，请问是如何解决的呀？

**Comment by linjieccc** [comment]
> 我也遇到这个问题，请问是如何解决的呀？

你好，我们对该AIStudio项目进行了升级，可以用最新版本再试下
