### ISSUE TITLE
在FasterTransformer的decoding中，word_embeding的forward是emb_dim**0.5*word_embeding还是直接word_embeding？

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/PaddleNLP#1951]
paddlenlp                          2.2.5
paddlepaddle-gpu                   2.2.2.post112

**Comment by FrostML** [comment]
是 `emb_dim**0.5 * word_embeding`，FasterTransformer 的实现细节可以参考 PaddleNLP 中 [Transformer 代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/transformer/modeling.py#L95) .

**Comment by janelu9** [comment]
> 是 `emb_dim**0.5 * word_embeding`，FasterTransformer 的实现细节可以参考 PaddleNLP 中 [Transformer 代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/transformer/modeling.py#L95) .

是一样的就好
