### ISSUE TITLE
篇章级事件抽取问题

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/PaddleNLP#1968]
参考文档：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuEE
环境:Linux paddle-gpu=2.2.2 paddlenlp=2.2.5
在进行触发词识别模型训练时出现一下错误：
![17A6F502-786A-4dac-B2B0-A097701BDA1D](https://user-images.githubusercontent.com/94336500/163740330-48a7d52d-5707-41a1-bcba-1f122df2d1ed.png)

该怎样解决?

**Comment by wawltor** [comment]
安装的是非GPU版本，可以尝试更新安装成GPU版本
