### ISSUE TITLE
如何把embedding直接输入到预训练模型中？

### ISSUE THREAD

**Issue by seancoding1** [PaddlePaddle/PaddleNLP#1969]
模型中的forward(input_ids, token_type_ids=None, position_ids=None, attention_mask=None, output_hidden_states=False)

paddle的RobertaModel中，输入的参数好像只允许input_ids,能否把input_embeds直接输入进模型中呢？

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by guoshengCS** [comment]
这个暂时还不支持，不过已经在评估中了，请 @yingyibiao 关注
