### ISSUE TITLE
建议增加ErnieModel对文本长度限制的检测

### ISSUE THREAD

**Issue by geekhch** [PaddlePaddle/PaddleNLP#1971]
当输入文本长度max_len_len的长度过大时，会导致tokenizer的编码输出序列超出512，在模型embedding阶段会出现` (External) CUDA error(700), an illegal memory access was encountered. `错误，直接退出程序，并没有其他进一步的异常debug提示，导致开发者debug困难。

**Comment by guoshengCS** [comment]
抱歉带来困扰，感谢建议，我们评估看下，这个加到`Paddle.nn.Embedding` api中支持更多情况可能会更好一些
