### ISSUE TITLE
paddlenlp DuEE篇章级事件抽取相关问题

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/PaddleNLP#1975]
参考文档：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuEE
环境 paddlepaddle-gpu=2.2.2, ubuntu1604,paddlenlp=2.2.5
触发词识别模型训练完成，在进行触发词识别的预测时，出现以下问题：
![800457cb6326c6a111901ebbf665fec](https://user-images.githubusercontent.com/94336500/163933827-c6128f67-a757-4459-8bde-ba72b51632f4.png)
应该如何解决

**Comment by LemonNoel** [comment]
有运行 sh run_duee_fin.sh data_prepare 这个脚本吗

**Comment by LemonNoel** [comment]
这种情况看起来是dict_path的设置不对。可以提供下其他信息吗，比如是否有什么代码上的修改？可以在utils.py 第60行打印出来dict_path路径，检查下该路径下是否有对应的文件。
