### ISSUE TITLE
如何关闭日志？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#1976]
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
I0419 15:54:17.632876  8963 fuse_pass_base.cc:57] ---  detected 146 subgraphs
--- Running IR pass [map_matmul_v2_to_matmul_pass]
I0419 15:54:17.640677  8963 fuse_pass_base.cc:57] ---  detected 24 subgraphs
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0419 15:54:18.470705  8963 fuse_pass_base.cc:57] ---  detected 146 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0419 15:54:18.747023  8963 analysis_predictor.cc:717] ======= optimize end =======
I0419 15:54:18.757560  8963 naive_executor.cc:98] ---  skip [feed], feed -> pinyin_ids
I0419 15:54:18.757620  8963 naive_executor.cc:98] ---  skip [feed], feed -> input_ids
I0419 15:54:18.766016  8963 naive_executor.cc:98] ---  skip [argmax_0.tmp_0], fetch -> fetch
I0419 15:54:18.766057  8963 naive_executor.cc:98] ---  skip [argmax_1.tmp_0], fetch -> fetch

**Comment by FrostML** [comment]
`config.disable_glog_info()`

**Comment by wjddd** [comment]
![image](https://user-images.githubusercontent.com/65559675/164164501-40ff80da-7c97-42ac-ac6c-783a57e31cce.png)

添加`config.disable_glog_info()`后日志继续打印。

**Comment by wjddd** [comment]
已解决，感谢。
