### ISSUE TITLE
 PaddleNLP/ applications / sentiment_analysis这个案例没有服务化部署的示例吗？

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1982]
PaddleNLP/ applications / sentiment_analysis这个案例没有服务化部署的示例吗？

**Comment by ZeyuChen** [comment]
@AI-Mart 欢迎给我们贡献一个 :)

**Comment by AI-Mart** [comment]
😊尝试下，哈哈


------------------ 原始邮件 ------------------
发件人: Zeyu Chen ***@***.***&gt;
发送时间: 2022年4月23日 00:15
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: AI-Mart ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP]  PaddleNLP/ applications / sentiment_analysis这个案例没有服务化部署的示例吗？ (Issue #1982)





 
@AI-Mart 欢迎给我们贡献一个 :)

**Comment by zck573693104** [comment]
老铁尝试如何了？？？ 想跟你借鉴下

**Comment by AI-Mart** [comment]
> 老铁尝试如何了？？？ 想跟你借鉴下

还没有呢，最近忙其他的，过几天有空了弄一下，到时可以分享出来
