### ISSUE TITLE
PaddleNLP/ applications / sentiment_analysis里面的观点和属性抽取咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#1984]
addleNLP/ applications / sentiment_analysis里面的观点和属性抽取是通过规则组合，会不会有一定的错误率，是不是转换成关系抽取的任务直接把实体和实体的关系抽取出来会更准确？

**Comment by 1649759610** [comment]
会有一定的错误率，不过匹配规则是按照人们表达习惯来定的，实验效果表现还不错。
关系抽取任务可能不太适合，因为观点词本身并不是一个实体。

**Comment by 1649759610** [comment]
> addleNLP/ applications / sentiment_analysis里面的观点和属性抽取是通过规则组合，会不会有一定的错误率，是不是转换成关系抽取的任务直接把实体和实体的关系抽取出来会更准确？

会有一定的错误率，不过匹配规则是按照人们表达习惯来定的，实验效果表现还不错。
关系抽取任务可能不太适合，因为观点词本身并不是一个实体。

**Comment by AI-Mart** [comment]
观点词可以当做一个实体来对待吧？如果弄成关系抽取的任务，实体之间不漏检的匹配，准确率应该能大幅度提升

**Comment by AI-Mart** [comment]
观点词也可以当做实体来对待吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Milen ***@***.***&gt;
发送时间: 2022年4月22日 10:34
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: AI-Mart ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] addleNLP/ applications / sentiment_analysis里面的观点和属性抽取咨询 (Issue #1984)





  
addleNLP/ applications / sentiment_analysis里面的观点和属性抽取是通过规则组合，会不会有一定的错误率，是不是转换成关系抽取的任务直接把实体和实体的关系抽取出来会更准确？
  
会有一定的错误率，不过匹配规则是按照人们表达习惯来定的，实验效果表现还不错。
 关系抽取任务可能不太适合，因为观点词本身并不是一个实体。
