### ISSUE TITLE
导入Taskflow报错

### ISSUE THREAD

**Issue by codecat0** [PaddlePaddle/PaddleNLP#1990]
ImportError: cannot import name 'Taskflow' from 'paddlenlp' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/__init__.py)

**Comment by wawltor** [comment]
> ImportError: cannot import name 'Taskflow' from 'paddlenlp' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/**init**.py)

您好，看起来是PaddleNLP的版本太老了，可以升级一下PaddleNLP的版本。

**Comment by HonestDeng** [comment]
我也遇到了这个问题。上午的时候可以用，现在突然就不行了。

**Comment by HonestDeng** [comment]
> 

!pip install --upgrade paddlenlp 就可以了

**Comment by ZeyuChen** [comment]
Issues solved by upgrade paddlenlp.

**Comment by allurelzh** [comment]
最新的版本taskflow无法使用,paddlenlp-2.4.0
