### ISSUE TITLE
bert继续预训练，当预训练材料都是100字符左右的文本时，要怎样准备nsp任务?

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#1994]
每个句子之间没什么关联关系，组合不成逻辑上的文章

**Comment by joey12300** [comment]
@zouhan6806504 你好。BERT的NSP任务是判断两个句子是不是同一篇文章的。预训练预处理的时候是把若干文章拆分成若干个句子，把来自同一篇文章的句子对标记为1，不同则标记为0，是自动化标记label的。

**Comment by zouhan6806504** [comment]
> @zouhan6806504 你好。BERT的NSP任务是判断两个句子是不是同一篇文章的。预训练预处理的时候是把若干文章拆分成若干个句子，把来自同一篇文章的句子对标记为1，不同则标记为0，是自动化标记label的。

所以问题就在这里，我的预训练语料不是来源于文章，就只是一句一句100字左右的文本。或者bert能自动将这些语句拆分成几十个字一句话的组合，但这样会不会影响bert预训练的效果？我将一句话当作一篇文章，按照这样的格式使用paddlenlp提供的examples/language_model/pretraining_data_prepare/main.py，examples/language_model/bert/create_pretraining_data.py生成训练数据，但是最后的效果没有使用原来的bert在下游任务表现好，我觉得是NSP任务没充分训练的结果。所以我想了解如果是这种不成文章的预训练材料，有没有更好的基于bert的训练方法
