### ISSUE TITLE
句子级事件抽取-触发器预测结果

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#2000]
我自己参照duee1.0中event_schema.json事件模板构建自己的事件模版，例如
{"event_type": "移动-出行", "role_list": [{"role": "主体"}, {"role": "活动名称"}, {"role": "开始时间"}, {"role": "结束时间"}, {"role": "地点"}], "class": "移动"}  
{"event_type": "交流-访问", "role_list": [{"role": "访问者"}, {"role": "被访问者"}, {"role": "活动名称"}, {"role": "时间"}, {"role": "地点"}], "class": "交流"}
使用的句子文本是都是长度小于300的短文本，大部分的长度都小于200。**但是**我在构建数据集的时候不是完全按照duee1.0中把事件类型"event-trigger"中的trigger作为唯一的触发词。具体来说，在duee1.0的 _"event_type": "交往-点赞"_  中是把"点赞"作为该"交往-点赞"事件的唯一触发词，但是我在构建事件 _"event_type": "移动-出行"_ 数据集的时候，不仅把"出行"最为该事件的触发词，而且把诸如“到达”，“来到”，“去”等与 **“出行”** 含义相似的词都作为事件 _"event_type": "移动-出行"_ 的触发词了。
按照这种构建数据集的方式，我具体 **构建了5种事件类型，总共构建了200条训练样本，使用120条样本作为训练集** 。但是当我做完触发器训练和预测后，发现预测的触发器序列标签是全部是"O" 不能预测出触发词。   我起初以为是模型训练欠拟合，于是特定使用了训练集来做预测，但是预测的结果仍然全部为"O",不能预测出正确的事件触发词。
我列出一个数据样本，
{"text": "当地时间4月15日，德国联邦总理朔尔茨表示，德国愿意为军事援助拨款20亿欧元，而其中大部分将提供给乌克兰。 据悉，此次拨款并不包括在之前德国联邦政府提出的1000亿欧元国防特别预算之内，而是会单独支出", "event_list": [**{"event_type": "交流-表态", "trigger": "表示"**, "trigger_start_index": 19, "arguments": [{"argument_start_index": 10, "role": "主体", "argument": "德国联邦总理朔尔茨"}, {"argument_start_index": 49, "role": "对象", "argument": "乌克兰"}, {"argument_start_index": 27, "role": "议题", "argument": "军事援助"}, {"argument_start_index": 0, "role": "时间", "argument": "当地时间4月15日"}], "class": "交流"}]}
在这个例子中，对于 **事件"交流-表态"**,我使用了 **"表示"** 作为触发词。
**我模型训练后，做的触发器预测和事件角色预测得到的模型输出BIO标签，均是全为'O'的序列标签**。
**如能尽快答复，则万分感谢。**

**Comment by Mnanazi** [comment]
又测试一下，当使用原始的duee1.0的evet_schema.json，但是只是要120条数据来训练时，在完成触发器模型的训练后，直接使用一样的数据集来做触发器预测，发现得到的输出预测标签全部为”O“标签，无触发词标签。
**请问，这是不是说明导致触发器预测全为”O“是由于训练数据集太小导致的？**
如果该问题是仅有训练集太小导致的，**那么使用deuu1.0模型至少多少条数据？**
 **另外，按照我上面说的构建数据集的方式是否可行？** 即当有事件"交流-表态",我使用了 "表示" 作为触发词，而不单单使用”表态“一词作为该事件的触发词？Ernie模型能通过训练数据学习到”表示“和”表态“的语义相近吗？从而将”表示“也作为事件”交流-表态“的触发词。
**如能答复，万分感谢**

**Comment by tianxin1860** [comment]
请问训练、预测分别使用的哪个脚本？

**Comment by Mnanazi** [comment]
我是把sequence_label.py中的parse参数按照sh脚本的参数设置，直接分为了trigger_train.py 和 trigger_predict.py，然后执行的。
因为我一开始在colab上按照sequence_label.sh分别执行trigger训练和预测时出错了。但是没解决这个问题。之后就直接把parse参数写到对应的py文件中了。
我今天上午安装这个方法，将duee1.0完整的数据集执行了trigger的训练和预测，查看预测文件，发现预测的很正确。
我认为我提问的问题应该是训练集太小导致的，只有120条样本。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月25日 10:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] 句子级事件抽取-触发器预测结果 (Issue #2000) |

请问训练、预测分别使用的哪个脚本？

**Comment by tianxin1860** [comment]
可以给一下项目链接地址。

**Comment by Mnanazi** [comment]
> 不会把本地项目上传到github（试了半小时一直失败），我把项目传到了百度网盘。这是链接
链接：https://pan.baidu.com/s/1KC-d2ARcNQqq3ZVqBKIPsg?pwd=xiao 
提取码：xiao 
--来自百度网盘超级会员V3的分享

**Comment by Mnanazi** [comment]
只会这种低级操作

**Comment by Mnanazi** [comment]
我把模型参数删除了，它占了1个多g。我本地使用的paddle2.2

**Comment by Mnanazi** [comment]
我本地使用的paddle2.2

**Comment by Mnanazi** [comment]
> 可以给一下项目链接地址。

要不要我在colab上的项目，里面是一样的内容？不过要链接到我自己的谷歌云，分享后可能不能正常使用了

**Comment by tianxin1860** [comment]
运行的原始项目地址是什么？比如说 AISudio 的哪个项目吗？

**Comment by Mnanazi** [comment]
duee1.0。我就只是把用shell脚本运行传参从而执行sequence_labeling.py改了下，因为本地执行时shell传参出错了，我就把对应的过程分成了四个py文件



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月25日 16:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] 句子级事件抽取-触发器预测结果 (Issue #2000) |

运行的原始项目地址是什么？比如说 AISudio 的哪个项目吗？

**Comment by Mnanazi** [comment]
> 运行的原始项目地址是什么？比如说 AISudio 的哪个项目吗？

![image](https://user-images.githubusercontent.com/75676487/165047476-7245058d-6e52-4b2a-83e6-749c030a0d1c.png)

**Comment by Mnanazi** [comment]
> 可以给一下项目链接地址。

我像重点问下，当有事件"交流-表态",我使用了 "表示" 作为触发词，而不单单使用”表态“一词作为该事件的触发词，按照这样的方式来构建事件数据集可行吗？即使用语义相近的词语作为触发词。
