### ISSUE TITLE
ernie-csc训练

### ISSUE THREAD

**Issue by you567** [PaddlePaddle/PaddleNLP#2004]
您好，

-  #在尝试运行开源代码复现结果后，在仅用sighan2013、sighan2014、sighan2015数据集上训练20epoch的score如下图所示，f1结果最高的是sighan2015,和官方复现的结果不一致，且结果相差比较大，这个正常吗？官方的训练结果是连同Automatic Corpus Generation生成的中文纠错数据集一起训练的吗？需要训练多少epoch才能达到官方的结果啊？
![2OD(T}CZ6D}L}%Q 6VB`$@D](https://user-images.githubusercontent.com/35205404/165035179-440ad06f-6159-403e-9991-0a3db14c77de.png)

**Comment by joey12300** [comment]
@you567 您好。示例中的结果是与基于Automatic Corpus Generation生成的中文纠错数据集和Sighan数据集一起训练的。因为Automatic Corpus Generation的数据集比较大，模型训练会更充分，效果会更好。至于训练的超参，可参考该示例：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc#%E5%A4%9A%E5%8D%A1%E8%AE%AD%E7%BB%83

**Comment by you567** [comment]
奥奥，好的，多谢！

**Comment by you567** [comment]
您好，我现在加入数据集之后，经常报显存不足，我已经把batchsize调小到8，显卡是RTX2080Ti ，11GB的专用GPU内存，训练时间有点长，担心爆显存。我在飞浆的APi种看到 如下的显存优化策略，这个有没有使用的实例啊？

#一旦不再使用即释放内存垃圾，=1.0 垃圾占用内存大小达到10G时，释放内存垃圾
export FLAGS_eager_delete_tensor_gb=0.0
#启用快速垃圾回收策略，不等待cuda kernel 结束，直接释放显存
export FLAGS_fast_eager_deletion_mode=1
#该环境变量设置只占用0%的显存
export FLAGS_fraction_of_gpu_memory_to_use=0
