### ISSUE TITLE
lac分词器

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#2009]
paddlepaddle==2.2.2, lac==2.1.2
把lac分词器封装成web服务，启动6个worker,内存一直增长，占用很高，是不是存在内存泄漏？

**Comment by LemonNoel** [comment]
LAC的问题建议到相应的repo下提issue哈。

另外，PaddleNLP的[Taskflow](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md)也有分词的功能，可以尝试一下～ 
![截屏2022-04-28 上午10 31 51](https://user-images.githubusercontent.com/25607475/165664901-887dcecc-6ca7-4c1b-bfa8-2a9992e67a2d.png)
