### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by jackychancjcjcj** [PaddlePaddle/PaddleNLP#2029]
运行问答系统代码出现问题，macos系统 python3.7
运行代码
python -u -m paddle.distributed.launch \
	train.py \
	--device cpu \
	--save_dir ./checkpoints/ \
	--batch_size 64 \
	--learning_rate 5E-5 \
	--epochs 3 \
	--save_steps 50 \
	--eval_steps 50 \
	--max_seq_length 64 \
	--dropout 0.2 \
	--dup_rate 0.1 \
	--rdrop_coef 0.1 \
	--output_emb_size 256 \
	--train_set_file "./data/train.csv"

问题：
from six.moves import collections_abc
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)

**Comment by wawltor** [comment]
建议升级一下six   `pip install six --upgrade`
