### ISSUE TITLE
AutoModel预测阶段必须使用model.eval才能保证同一输入有同一结果，与huggingface不一致，体验不好

### ISSUE THREAD

**Issue by JizxGit** [PaddlePaddle/PaddleNLP#2030]
AutoModel预测阶段必须使用model.eval才能保证同一输入有同一结果，与huggingface不一致，体验不好

1）Paddle  2.2.1；PaddleNLP 2.2.3；
2）系统环境：Linux，python3.6.2
3）问题代码：
```python
    import paddle
    from paddlenlp.transformers import BertModel, BertTokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-wwm-chinese')
    model = BertModel.from_pretrained('bert-wwm-chinese')
    inputs = tokenizer("欢迎使用百度飞桨!")
    inputs = {k:paddle.to_tensor([v]) for (k, v) in inputs.items()}
    # model.eval()  不使用这一行的话，下面的结果不一致
    output = model(**inputs)
    print(output[0])
    output = model(**inputs)
    print(output[0])
```

**Comment by yingyibiao** [comment]
您好，感谢您的反馈。关于您所反馈的差异点：huggingface 是通过 from_pretrained 函数内置 model.eval() 代码进行评估模式的默认设置。关于这个体验的差异我们内部会进行综合评估～
https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L2080

**Comment by JizxGit** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，我已收到您的E-mail，会尽快查看，必要时会回复您。
