### ISSUE TITLE
想测试一下信息抽取任务，报错

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/PaddleNLP#2036]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：paddlepaddle == 2.2.2；paddlenlp == 2.2.6
2）系统环境：macos，python=3.8
报错信息：
AssertionError: The task name:information_extraction is not in Taskflow list, please check your task name.

貌似是任务流里面没有“信息抽取”，想问一下为什么会没有这个任务流，是版本的问题吗？
多谢！！！

**Comment by wawltor** [comment]
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：paddlepaddle == 2.2.2；paddlenlp == 2.2.6
>   2）系统环境：macos，python=3.8
>   报错信息：
>   AssertionError: The task name:information_extraction is not in Taskflow list, please check your task name.
> 
> 貌似是任务流里面没有“信息抽取”，想问一下为什么会没有这个任务流，是版本的问题吗？ 多谢！！！

您好，信息抽取的功能刚合入到develop分支上，有需要的话可以通过拉取develop分支，然后安装最新版本的PaddleNLP

**Comment by ZeyuChen** [comment]
请尝试安装PaddleNLP最新版本2.3并拉取最新代码，即可解决此问题。
