### ISSUE TITLE
关于p-tuning中训练loss变为nan

### ISSUE THREAD

**Issue by effort-yq** [PaddlePaddle/PaddleNLP#2045]
利用开源的代码，在自己的数据集上跑p-tuning，发现loss变为nan，查了之后模型输出的logit中的数据变为nan，这是什么原因啊，求助。请问有大佬知道吗

**Comment by guoshengCS** [comment]
> 查了之后模型输出的logit中的数据变为nan

这个可能不一定是NAN首次出现的位置和直接原因，可以先参考下 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/check_nan_inf_cn.html#check-nan-inf 这里的文档再确认看看NAN或者INF首次出现在哪里

**Comment by tianxin1860** [comment]
小样本场景下模型收敛比较敏感，可以试试调整下 batch_size 看看是否稳定会出现 nan ?
