### ISSUE TITLE
关于保险问答中SimCSE的问题

### ISSUE THREAD

**Issue by qishibo** [PaddlePaddle/PaddleNLP#2046]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/faq_finance/model.py#L60-L78
![10fbae41488b36a0aca05f3d615f63a](https://user-images.githubusercontent.com/5136418/166128676-7a9cf1f3-ef97-4e84-abd8-5e746ac1c0f6.png)

ptm预训练模型里面含有dropout的，为什么后面输出又手动dropout了一遍呢？这样不就dropout两遍了么，正常SimCSE应该只利用了Encoder本身的dropout吧

**Comment by qishibo** [comment]
还有一个问题，计算KL散度这里，两个logits经过了线性层后求得KL散度，Linear为什么要是二分类呢？

![image](https://user-images.githubusercontent.com/5136418/166150999-ad649cdf-ae3a-444e-b4f8-5519bc67a3ba.png)

![image](https://user-images.githubusercontent.com/5136418/166150987-8db3c332-88ac-4a23-b43b-a33f2ed1e75a.png)

**Comment by w5688414** [comment]
@qishibo  这是我们在做保险问答过程中想的一个优化方式，即接入一个全连接层，做二分类计算rdrop损失，类似于语义匹配任务。当然这里面还有很多改进的空间，有兴趣可以一起交流合作。

**Comment by qishibo** [comment]
@w5688414 感谢回复，我这也跑了个测试，一个是换成16分类，效果区别不大；另一个就是尺寸不变，直接output_emb_size输出，得分反而降低了，所以问问你们的思路

还有dropout那个问题能解答一下么，为什么dropout两次呢

**Comment by w5688414** [comment]
@qishibo  好的，2次有点不准确，额外的dropout不是必须的，可以根据个人的情况添加，因为bert等预训练模型里面已经有dropout（bert里面的dropout不只1处有，可以看源代码，Transformer里面的每一个Encoder都有dropout）。另外，官方的SimCSE是直接使用预训练语言模型的dropout，跟您说的思路一样，可以比较一下差异有多大。

**Comment by qishibo** [comment]
好的，我试试看这额外的dropout有什么影响
