### ISSUE TITLE
ernie3.0词表问题，出现重复字符。

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#2048]
在`base`和`medium`版本的`ernie3.0`词表中，发现重复字符。
下标从零开始，第`12084`位置和第`18005`位置的字符重复，都为`$`这个符号。
请问这个词表中，哪个是正确的。

**Comment by nghuyong** [comment]
与这个issue一致：https://github.com/PaddlePaddle/ERNIE/issues/795
