### ISSUE TITLE
paddlenlp中BERT自动下载存在问题

### ISSUE THREAD

**Issue by Zhangbeibei1991** [PaddlePaddle/PaddleNLP#2050]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
- 
- paddlenlp=2.3.0rc0
- 
![image](https://user-images.githubusercontent.com/29685955/166390032-2b8c0855-69fa-431d-8c6f-1623b5c37299.png)
-希望能检查一下
代码：
from paddlenlp.transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path="allenai/scibert_scivocab_uncased")

**Comment by guoshengCS** [comment]
在 https://github.com/PaddlePaddle/PaddleNLP/pull/2101 这个PR里进行了修复，抱歉带来困扰

**Comment by guoshengCS** [comment]
在 https://github.com/PaddlePaddle/PaddleNLP/pull/2101 这个PR里进行了修复，抱歉带来困扰
