### ISSUE TITLE
利用paddle inference 预测 在win10 中出现数据类型问题

### ISSUE THREAD

**Issue by BaiIIzt** [PaddlePaddle/PaddleNLP#2051]
环境 win10   paddlenlp  2.2.5

应该是和以下问题出现了相同相同的情况，但是不太清楚他是如何解决的
https://github.com/PaddlePaddle/PaddleNLP/issues/732

代码deploy/python/predict.py 报错 ：
![Uploading image.png…]()

**Comment by BaiIIzt** [comment]
![image](https://user-images.githubusercontent.com/75989862/166446045-a512ac32-3fa4-4d32-b495-0e0c248649a0.png)

**Comment by JunnYu** [comment]
windows默认`int`使用的是`int32`，linux环境下默认`int`使用的是`int64`，因此在win环境下指定一下`dtype="int64"`就好了。
比如
np格式
` input_ids = np.array([[1,2,3,4]], dtype="int64")`
paddle格式
` input_ids = paddle.to_tensor([[1,2,3,4]], dtype="int64")`

**Comment by BaiIIzt** [comment]
还是出现同样报错，我将export_model.py进行了如下修改
![image](https://user-images.githubusercontent.com/75989862/166655956-f9207cf7-1981-4319-b06a-c2b08d069776.png)
可能修改的不全面还是存在相同报错，请问predict.py有需要修改的地方吗，(非nlp方向,不太专业)
![image](https://user-images.githubusercontent.com/75989862/166656431-e4902f36-d15f-4b1f-88be-00e71e7fd0e5.png)

**Comment by BaiIIzt** [comment]
报错
![image](https://user-images.githubusercontent.com/75989862/166659574-5df20d10-6022-435a-aed3-4143ebbd6d68.png)

**Comment by BaiIIzt** [comment]
![image](https://user-images.githubusercontent.com/75989862/166661485-ef0df187-41c9-4515-81c6-61736e277988.png)

**Comment by JunnYu** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/793eee08ee3be5ebaacdd11a0a66eee716703b07/examples/text_classification/pretrained_models/deploy/python/predict.py#L130-L133

这个改成 dtype="int64", 主要是为了返回int64类型的numpy
```python
 batchify_fn = lambda samples, fn=Tuple( 
     Pad(axis=0, pad_val=tokenizer.pad_token_id, dtype="int64"),  # input 
     Pad(axis=0, pad_val=tokenizer.pad_token_id, dtype="int64"),  # segment 
 ): fn(samples)
```

**Comment by BaiIIzt** [comment]
XIEXIE
