### ISSUE TITLE
ernie3.0结构

### ISSUE THREAD

**Issue by JaheimLee** [PaddlePaddle/PaddleNLP#2052]
最新的ernie3.0模型结构和2.0，1.0是一样吗？我看model类和config跟之前没什么结构区别。但是3.0论文里使用的时transformer-xl，这次开源的3.0版本跟论文里模型结构不一致是吗？

**Comment by ZeyuChen** [comment]
是的，这次开源的模型版本和论文的结构不完全一致。
主要是个小的网络结构，考虑普适性做了一些调整，主要体现中文效果上的提升。

**Comment by JaheimLee** [comment]
了解，3Q
