### ISSUE TITLE
ErnieDoc根本无法调用！

### ISSUE THREAD

**Issue by alao556** [PaddlePaddle/PaddleNLP#2053]
PaddleNLP版本2.2：
（1）ErnieDocModel.from_pretrain(....) 会报错
（2）ErnieDocTokenizer没有英文版本，而ErnieDocModel却有英文版的

**Comment by joey12300** [comment]
@alao556 您好，我在是paddle 2.2.2下运行得到的结果如下：
1）  调用`ErnieDocModel.from_pretrained('ernie-doc-base-zh')`:
![image](https://user-images.githubusercontent.com/10826371/166634804-ee20928a-812a-4060-9d46-966891a580ea.png)

2) ErnieDoc的中文Tokenizer采用wordpiece方式切词，所以使用的是`ErnieDocTokenizer `；而其英文Tokenizer采用BPE的切词方式，所以其使用的是`ErnieDocBPETokenizer`。ErnieDoc的分类任务示例中分别有中英文的语料，均使用不同的模型以及Tokenizer，详细可参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/ernie-doc/run_classifier.py#L65

**Comment by alao556** [comment]
> 

谢谢你的回答，但我又出现了另外一个问题，ErnieForMaskedLM.from_pretrained(...)和ErnieDocPretrainedModel.from_pretrained(...)都会以下报错，是因为没有公开ErnieDoc的MLM Head权重？

============================================
RuntimeError: Can't load weights for ernie-doc-base-en.
Please make sure that ernie-doc-base-en is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant modeling files(model_weights and model_config).
==============================================

**Comment by alao556** [comment]
> @alao556 您好，我在是paddle 2.2.2下运行得到的结果如下： 1） 调用`ErnieDocModel.from_pretrained('ernie-doc-base-zh')`: ![image](https://user-images.githubusercontent.com/10826371/166634804-ee20928a-812a-4060-9d46-966891a580ea.png)
> 
> 2. ErnieDoc的中文Tokenizer采用wordpiece方式切词，所以使用的是`ErnieDocTokenizer `；而其英文Tokenizer采用BPE的切词方式，所以其使用的是`ErnieDocBPETokenizer`。ErnieDoc的分类任务示例中分别有中英文的语料，均使用不同的模型以及Tokenizer，详细可参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/ernie-doc/run_classifier.py#L65

谢谢你的回答，但我又出现了另外一个问题，ErnieForMaskedLM.from_pretrained(...)和ErnieDocPretrainedModel.from_pretrained(...)都会以下报错，是因为没有公开ErnieDoc的MLM Head权重？

============================================
RuntimeError: Can't load weights for ernie-doc-base-en.
Please make sure that ernie-doc-base-en is:

a correct model-identifier of built-in pretrained models,
or a correct model-identifier of community-contributed pretrained models,
or the correct path to a directory containing relevant modeling files(model_weights and model_config).
==============================================

**Comment by hchhtc123** [comment]
ErnieDoc文档：
[https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.transformers.ernie_doc.html](https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.transformers.ernie_doc.html)
