### ISSUE TITLE
为什么没有ErnieDoc的MLM Head可使用？

### ISSUE THREAD

**Issue by alao556** [PaddlePaddle/PaddleNLP#2054]
没有ErnieDocForMaskedLM，也没ErnieDocForPretraining类调用，网上也没有ErnieDoc的MLM Head权重？

**Comment by joey12300** [comment]
@alao556 你好，请问你目前有什么需求需要使用ErnieDoc？目前ErnieDoc只提供了Finetune的参数，并未提供MLM的参数以及预训练流程

**Comment by alao556** [comment]
> @alao556 你好，请问你目前有什么需求需要使用ErnieDoc？目前ErnieDoc只提供了Finetune的参数，并未提供MLM的参数以及预训练流程

由于我目前在做Prompt tuning的工作，是类似于完形填空的研究，而且还文本较长（超过512），所以需要ErnieDoc的MLM
