### ISSUE TITLE
pytorch预训练模型转paddle

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#2059]
paddle暂不支持的预训练语言模型，用pytorch训练好，如何转成paddle inference版本的？

**Comment by ZHUI** [comment]
建议使用 x2paddle 进行转换。https://github.com/PaddlePaddle/X2Paddle

或者可以尝试自己使用paddle组网，对齐torch。

**Comment by ZHUI** [comment]
具体是什么模型呢？我们这边也可提供帮助，可以一起开源，丰富paddlenlp生态。
