### ISSUE TITLE
import paddlenlp报错!

### ISSUE THREAD

**Issue by menghonghan** [PaddlePaddle/PaddleNLP#2062]
PaddlePaddle 2.2.2
PaddleNLP 2.2.6
MacOS 
Python3.7

下好paddlenlp之后 import paddlenlp就会报错 报错如下：

<img width="997" alt="image" src="https://user-images.githubusercontent.com/61367724/166890997-4a4a6a1b-c968-4fed-87ec-dcc87f144732.png">

**Comment by menghonghan** [comment]
请问datasets版本要求多少啊？？？？

**Comment by ZHUI** [comment]
您好，单独尝试 `import datasets`试试？

**Comment by skywalk163** [comment]
好像我也碰到过了，mark一下。
```
[2022-05-05 22:35:44,247] [ WARNING] - Detected that datasets module was imported before paddlenlp. This may cause PaddleNLP datasets to be unavalible in intranetPlease import paddlenlp before datasets module to avoid download issues
...
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 48, in <module>
    from datasets import load_dataset as origin_load_dataset
ImportError: cannot import name 'load_dataset' from 'datasets' (/home/aistudio/BEiT/datasets.py)
```

**Comment by ZHUI** [comment]
> 好像我也碰到过了，mark一下。
> 
> ```
> [2022-05-05 22:35:44,247] [ WARNING] - Detected that datasets module was imported before paddlenlp. This may cause PaddleNLP datasets to be unavalible in intranetPlease import paddlenlp before datasets module to avoid download issues
> ...
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 48, in <module>
>     from datasets import load_dataset as origin_load_dataset
> ImportError: cannot import name 'load_dataset' from 'datasets' (/home/aistudio/BEiT/datasets.py)
> ```

您好，这个问题是：当前运行目录，刚好有`datasets.py (/home/aistudio/BEiT/datasets.py)`， 此处datasets.py的优先级更高，没调用到 `datasets`这个包。
建议还个目录运行。
