### ISSUE TITLE
Benchmark中run_clue_classifier.py错误。

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#2065]
https://github.com/PaddlePaddle/PaddleNLP/blob/fa8fe0ef257a48b6517b01b177513391a6dfa8c2/examples/benchmark/clue/classification/run_clue_classifier.py#L470-L485
![image](https://user-images.githubusercontent.com/50394665/167052063-4fb3017b-41f7-411a-b1d3-eeecf0b62e95.png)

- 这个代码的482行存在错误，idx的范围只是一个batch中的index。不是全局的index，预测时提交到clue排行榜会出现错误。
- 然后预测的结果无法直接提交到clue排行榜，因为有的任务的有2种版本测试集，1.0版本和1.1版本，需要指定版本名。

**Comment by ZeyuChen** [comment]
@JunnYu 是否可以提供个修改的PR支持可以提交到CLUE的？

**Comment by LiuChiachi** [comment]
Hello，已提 PR #2142 修复所说的这个问题，非常感谢指出错误~
