### ISSUE TITLE
Taskflow API: word_segmentation 和 ner等 example无法运行

### ISSUE THREAD

**Issue by xixilllll** [PaddlePaddle/PaddleNLP#2067]
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.2.6，PaddlePaddle2.2.2
2）系统环境：Windows，python版本  3.8.8 
sentiment_analysis使用正常，但是word_segmentation或者ner任务运行，python自动停止，显示Process finished with exit code -1073741819 (0xC0000005)
![image](https://user-images.githubusercontent.com/40450302/167076011-ecec5f24-e623-4ed1-9ee1-fe3f71d4cb6a.png)

![image](https://user-images.githubusercontent.com/40450302/167076309-64ac864c-ed81-4d0e-acca-28622a66de0f.png)

**Comment by xixilllll** [comment]
![image](https://user-images.githubusercontent.com/40450302/167098266-5bdd9bf9-c447-4c9f-a6d1-86bd70b428b0.png)
为什么没有information_extraction这个接口

**Comment by wawltor** [comment]
> ![image](https://user-images.githubusercontent.com/40450302/167098266-5bdd9bf9-c447-4c9f-a6d1-86bd70b428b0.png) 为什么没有information_extraction这个接口

需要最新的版本，pip install paddlenlp==2.3rc0 --upgrade

**Comment by linjieccc** [comment]
> 

辛苦提供下内存，GPU显存配置

**Comment by xixilllll** [comment]
> > ![image](https://user-images.githubusercontent.com/40450302/167098266-5bdd9bf9-c447-4c9f-a6d1-86bd70b428b0.png) 为什么没有information_extraction这个接口
> 
> 需要最新的版本，pip install paddlenlp==2.3rc0 --upgrade

谢谢，已解决

**Comment by xixilllll** [comment]
> > 
> 
> 辛苦提供下内存，GPU显存配置

你好，我在另一个conda环境重新装了一下，现在可以了。只是会有pillow的warning。
![image](https://user-images.githubusercontent.com/40450302/167101374-aa6f8d36-61c9-4fe9-a630-7b0f63c4370e.png)

**Comment by datalee** [comment]
> > > ![image](https://user-images.githubusercontent.com/40450302/167098266-5bdd9bf9-c447-4c9f-a6d1-86bd70b428b0.png) 为什么没有information_extraction这个接口
> > 
> > 
> > 需要最新的版本，pip install paddlenlp==2.3rc0 --upgrade
> 
> 谢谢，已解决

最讨厌的就是这个，天天变版本，谁会长期用？？？

**Comment by wawltor** [comment]
> > > > ![image](https://user-images.githubusercontent.com/40450302/167098266-5bdd9bf9-c447-4c9f-a6d1-86bd70b428b0.png) 为什么没有information_extraction这个接口
> > > 
> > > 
> > > 需要最新的版本，pip install paddlenlp==2.3rc0 --upgrade
> > 
> > 
> > 谢谢，已解决
> 
> 最讨厌的就是这个，天天变版本，谁会长期用？？？

因为是新增功能，需要通过发布新版本的方式给大家使用
