### ISSUE TITLE
中文阅读理解竞赛，run_squad.py，提示TypeError: map() got an unexpected keyword argument 'batched'

### ISSUE THREAD

**Issue by zcp789** [PaddlePaddle/PaddleNLP#207]
raceback (most recent call last):
  File "./run_squad.py", line 351, in <module>
    run(args)
  File "./run_squad.py", line 210, in run
    train_ds.map(prepare_train_features, batched=True)
TypeError: map() got an unexpected keyword argument 'batched'
我下载文件后可一丝未改，怎么回事呢？

**Comment by smallv0221** [comment]
您好，这个问题可能是您的PaddleNLP版本问题。建议您升级到最新版本的PaddleNLP。
