### ISSUE TITLE
ErnieForGeneration加载训练后的模型报错

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/PaddleNLP#2071]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0rc0，PaddlePaddle 2.2.2.post101
2）系统环境：AI Studio V100 32GB 版本
- 复现信息：

0. 问题同 #1236

1. 使用ErnieForGeneration模型，可以进行训练。定义模型如下：

``` python
from paddlenlp.transformers import ErnieForGeneration

model = ErnieForGeneration.from_pretrained("ernie-1.0")
```

2. 训练完成后使用`model.save_pretrained(output_dir)`和`tokenizer.save_pretrained(output_dir)`保存模型参数与tokenizer的参数，文件夹内结果如下：

![image](https://user-images.githubusercontent.com/71769312/167164578-0779018c-a45c-45d3-84b1-d2a582915d9e.png)

3. 尝试加载模型和tokenizer的参数进行预测，加载代码如下：

``` python
from paddlenlp.transformers import ErnieTokenizer
from paddlenlp.transformers import ErnieForGeneration

tokenizer = ErnieTokenizer.from_pretrained(output_dir)
model = ErnieForGeneration.from_pretrained(output_dir)
```

4. 加载报错，错误如下：

```
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/ernie_gen/modeling.py in from_pretrained(cls, pretrained_model_name_or_path, *args, **kwargs)
    349 
    350         # import pdb; pdb.set_trace()
--> 351         if not os.path.exists(resolved_resource_files[file_id]):
    352             raise ValueError('pretrain dir not found: %s' %
    353                              resolved_resource_files[file_id])
KeyError: 'model_config_file'
```

**Comment by ZHUI** [comment]
有点奇怪, ErnieForGeneration的预训练模型是 ernie_gen, 内置的预训练权重是这些，没有 "ernie-1.0"才对。
https://github.com/PaddlePaddle/PaddleNLP/blob/e728f037d9a110c934ebb9188eee3ea638ac7f56/paddlenlp/transformers/ernie_gen/modeling.py#L268-L276

**Comment by ZeyuChen** [comment]
@ZHUI 也支持ernie-1.0， roberta同样结构模型的加载的。可以看看ernie-gen的文档
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_generation/ernie-gen

**Comment by geoyee** [comment]
@ZHUI 我看的就是这个下面的带的AI Studio链接的项目：[https://aistudio.baidu.com/aistudio/projectdetail/1339888](https://aistudio.baidu.com/aistudio/projectdetail/1339888)，这就是加载的"ernie-1.0"

![image](https://user-images.githubusercontent.com/71769312/167365346-9d8d000b-3424-4a0c-ba68-c13ac441d83f.png)

![image](https://user-images.githubusercontent.com/71769312/167365384-91e1ac6e-07b4-4ff0-8391-a1c9346d66bf.png)

**Comment by ZHUI** [comment]
嗯嗯，抱歉，这里是针对ernie_gen重写很多 PretrainModel的方法。是我疏忽了。

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/e728f037d9a110c934ebb9188eee3ea638ac7f56/paddlenlp/transformers/ernie_gen/modeling.py#L350-L359

这部分代码应该有问题。`model_config_file`之前就pop了。所以不应该出现。这里应该是判断weight权重的代码。
```python
        # import pdb; pdb.set_trace()
        if not os.path.exists(resolved_resource_files["model_state"]):
            raise ValueError('pretrain dir not found: %s' %
                             resolved_resource_files["model_state"])

        name_prefix = kwargs.pop('name', None)
        model = cls(init_kwargs, name=name_prefix)

        weight_path = resolved_resource_files["model_state"]
        logger.info('loading pretrained model from %s' % weight_path)
```

**Comment by ZHUI** [comment]
@ZeyuChen 这里有点代码hack的意思，大部分模型PretrainedModel的代码都是在`model_utils.py`，可能出现这里ernie_gen单独重写了。可能存在些潜在的兼容风险。
https://github.com/PaddlePaddle/PaddleNLP/blob/e728f037d9a110c934ebb9188eee3ea638ac7f56/paddlenlp/transformers/model_utils.py#L153-L182

https://github.com/PaddlePaddle/PaddleNLP/blob/e728f037d9a110c934ebb9188eee3ea638ac7f56/paddlenlp/transformers/ernie_gen/modeling.py#L299-L309

**Comment by geoyee** [comment]
所以这部分我是需要等待修复吗 😃

**Comment by ZHUI** [comment]
不是，你这边可以先试一下，可以正常加载吗？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2092 可以试一下这个PR

**Comment by geoyee** [comment]
> #2092 可以试一下这个PR

好的收到，晚上试一下

**Comment by ZHUI** [comment]
PR已合入 https://github.com/PaddlePaddle/PaddleNLP/pull/2092

**Comment by geoyee** [comment]
> PR已合入 #2092

现在需要重新训练吗？之前训练的参数不能用了吗？加载`Tokenizer`时报错

![image](https://user-images.githubusercontent.com/71769312/168089441-611bd597-b71c-411a-981b-de28a63353ca.png)

![image](https://user-images.githubusercontent.com/71769312/168089567-33617234-f578-4192-889f-55bbe55722ae.png)

**Comment by ZHUI** [comment]
权重可以正常加载了吗？`Tokenizer ` 这边我再测试一下

**Comment by geoyee** [comment]
> 权重可以正常加载了吗？`Tokenizer ` 这边我再测试一下

还是不行，我clone了paddlenlp然后安装了develop分支，重新训练后，Tokenizer可以加在但是model还是一样的。

![image](https://user-images.githubusercontent.com/71769312/168455408-e0518218-ff96-4af1-bb7c-aade3dc73b87.png)

**Comment by geoyee** [comment]
可以使用了
