### ISSUE TITLE
PaddleNLP/applications/question_answering/和PaddleNLP/applications/neural_search/咨询

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#2074]
看官方案例，PaddleNLP/applications/question_answering的相似度检索召回效优于 PaddleNLP/applications/neural_search/的效果。

PaddleNLP/applications/question_answering是否相当于 PaddleNLP/applications/neural_search/的升级，在检索领域假如只有无标注数据的话，是不是推荐用PaddleNLP/applications/question_answering？

**Comment by w5688414** [comment]
@AI-Mart 您好，question_answering里面的检索模型使用的是RocketQA预训练的检索模型，RocketQA本身就是开放领域问答预训练模型，如果业务跟问答相关，并且只有少量的数据，推荐使用question_answering，里面包含了很多优化方法。neural_search的技术栈更完善一点，有召回也有排序，另外，question_answering里面的trick也可以用于neural_search，可能数据量大了之后，neural_search调参调起来不大方便，实际使用的时候需要考虑一下成本代价。

**Comment by AI-Mart** [comment]
好的，感谢回复，如果针对无监督的召回模型，把RocketQA借鉴过来效果应该会更好

**Comment by AI-Mart** [comment]
保险问答系统
`  pretrained_model = AutoModel.from_pretrained("ernie-1.0")

    tokenizer = AutoTokenizer.from_pretrained('ernie-1.0')
    model = SimCSE(pretrained_model, output_emb_size=output_emb_size)`


政务系统
`  pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained(
        "ernie-1.0")

    tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('ernie-1.0')
    model = SimCSE(pretrained_model, output_emb_size=output_emb_size)`


动态图转静态图的时候，这里面用的API不一样，是什么原因呢？以哪个为准，还是两个效果一样？

**Comment by AI-Mart** [comment]
> @AI-Mart 您好，question_answering里面的检索模型使用的是RocketQA预训练的检索模型，RocketQA本身就是开放领域问答预训练模型，如果业务跟问答相关，并且只有少量的数据，推荐使用question_answering，里面包含了很多优化方法。neural_search的技术栈更完善一点，有召回也有排序，另外，question_answering里面的trick也可以用于neural_search，可能数据量大了之后，neural_search调参调起来不大方便，实际使用的时候需要考虑一下成本代价。

RocketQA不管是在无监督还是有监督，效果都都比之前的neural_search提升非常多，很棒的工作，建议大家直接用最优的，faq_finance的版本作为基线。
