### ISSUE TITLE
ERNIE-CSC训练loss下降问题

### ISSUE THREAD

**Issue by you567** [PaddlePaddle/PaddleNLP#2082]
您好，在text_correction --> ernie-csc任务中添加Automatic Corpus Generationreadme增强数据后，按照readme中参数 python train.py --batch_size 32 --logging_steps 100 --epochs 10 --learning_rate 5e-5 --model_name_or_path ernie-1.0 --output_dir ./checkpoints/ --extra_train_ds_dir ./extra_train_ds/ --max_seq_length 192,
 执行(我的显存只有11g，将learning_rate 5e-5改为了1.25-5;-batch_size 改为了8)，这是指是在 10个epochs里都采用learning_rate=5e-5？我在第2个epoch里loss基本都在某一个范围内变化，这个还需要减少learning_rate吗？
<img width="320" alt="80147d0992f674bda363df62e3c92f2" src="https://user-images.githubusercontent.com/35205404/167336812-9ba03ebb-0414-4d04-9aa7-07ad02eb396a.png">
？

**Comment by tianxin1860** [comment]
1. lr=5E-5 表示在整个训练过程中学习率峰值是 5E-5, 因为训练过程中学习率会随着训练过程进行限行衰减，最终降低为 0。
2. 可以贴一下完整的收敛曲线，我们看下收敛是否符合预期？
3. lr = 1.25E-5 已经比较小了，基本没必要再继续降学习率了。

**Comment by you567** [comment]
奥奥，好的，谢谢！这是前三轮的loss曲线（训练比较慢，基本上epoch/天），您看正常吗？
另外，是不是用sighan的数据集作为测试指标相对于其他领域(比如政务)的高些，实际领域测试的话可能没有这么高的F1值？
![0-2epoch](https://user-images.githubusercontent.com/35205404/167550132-fb83acff-1b69-4bd9-bf5e-eb828a003d6c.png)
？

**Comment by tianxin1860** [comment]
看整体收敛曲线是正常的，除了`突刺` 可能是因为脏数据引起的以外，其余部分挺正常的。

**Comment by you567** [comment]
奥奥，好的，非常感谢！

**Comment by joey12300** [comment]
> 奥奥，好的，谢谢！这是前三轮的loss曲线（训练比较慢，基本上epoch/天），您看正常吗？ 另外，是不是用sighan的数据集作为测试指标相对于其他领域(比如政务)的高些，实际领域测试的话可能没有这么高的F1值？ ![0-2epoch](https://user-images.githubusercontent.com/35205404/167550132-fb83acff-1b69-4bd9-bf5e-eb828a003d6c.png) ？

实际领域测试的F1可能会低一些。Sighan所有数据集本身也是机器生成的，跟实际数据的分布不太一样。

**Comment by you567** [comment]
好的，谢谢！

**Comment by ZeyuChen** [comment]
Issues solved.
