### ISSUE TITLE
T5在动转静的时候，报错，

### ISSUE THREAD

**Issue by jiuwuxiaohun** [PaddlePaddle/PaddleNLP#2083]
大概代码如下：
```
# 动态图转换静态图
import paddle
from paddlenlp.transformers import T5ForConditionalGeneration,  T5Tokenizer

model_name_or_model_path = "t5_ckpt_model"

model = T5ForConditionalGeneration.from_pretrained(model_name_or_model_path)
tokenizer = T5Tokenizer.from_pretrained(model_name_or_model_path)


model.eval()

# Convert to static graph with specific input description
jit_model = paddle.jit.to_static(
    model,
    input_spec=[
        paddle.static.InputSpec(shape=[None, None], dtype="int64"),
    ])
# Save in static graph model.
paddle.jit.save(model,"ckpt_jit_model")  #这里报错。
```
----------

  File "动态图转换静态图.py", line 37, in <module>
    paddle.jit.save(model, jit_model_path)
  File "<decorator-gen-101>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 741, in save
    static_func = getattr(inner_layer, attr_func, None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/t5/modeling.py", line 699, in dummy_inputs
    input_ids = paddle.to_tensor(DUMMY_INPUTS, dtype=paddle.int64)
  File "<decorator-gen-134>", line 2, in to_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 228, in __impl__
    ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

----------
是因为  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/t5/modeling.py 的 699行有用到 to_tensor吗？不会处理，请指导下或者修复哦，谢谢
```
    # /PaddleNLP/blob/develop/paddlenlp/transformers/t5/modeling.py 699行
    @property
    def dummy_inputs(self):
        DUMMY_INPUTS = [[7, 6, 0, 0, 1], [1, 2, 3, 0, 0], [0, 0, 0, 4, 5]]
        DUMMY_MASK = [[1, 1, 1, 1, 1], [1, 1, 1, 0, 0], [0, 0, 0, 1, 1]]
        input_ids = paddle.to_tensor(DUMMY_INPUTS, dtype=paddle.int64)
        input_mask = paddle.to_tensor(DUMMY_MASK, dtype=paddle.int64)
        dummy_inputs = {
            "decoder_input_ids": input_ids,
            "input_ids": input_ids,
            "decoder_attention_mask": input_mask,
        }
        return dummy_inputs
```

**Comment by tianxin1860** [comment]
t5_ckpt_model 这个模型从哪里来的？可以贴下链接。

**Comment by tianxin1860** [comment]
这行代码写错了: `paddle.jit.save(model,"ckpt_jit_model")`  -> `paddle.jit.save(jit_model, "ckpt_jit_model")`

**Comment by jiuwuxiaohun** [comment]
> 这行代码写错了: `paddle.jit.save(model,"ckpt_jit_model")` -> `paddle.jit.save(jit_model, "ckpt_jit_model")`
------
# 联网下载
model = T5ForConditionalGeneration.from_pretrained("Langboat/mengzi-t5-base")
tokenizer = T5Tokenizer.from_pretrained("Langboat/mengzi-t5-base")
------
写成save jit_model，也是一样的错误。

**Comment by FrostML** [comment]
辛苦 @yingyibiao 看看

**Comment by yingyibiao** [comment]
您好，我们目前还没有支持T5模型的动转静功能，近期应该会进行支持，到时候会在此处同步～

**Comment by jiuwuxiaohun** [comment]
谢谢。那就辛苦你们了。

**Comment by jiuwuxiaohun** [comment]
> 您好，我们目前还没有支持T5模型的动转静功能，近期应该会进行支持，到时候会在此处同步～

```
# paddlepaddle <= 2.2.2
# paddlenlp <= 2.3.1

import paddle
from paddlenlp.transformers import *

model = T5ForConditionalGeneration.from_pretrained("t5-small")
jit_model = paddle.jit.to_static(model, 
input_spec=[
    paddle.static.InputSpec(shape=[None, 512], dtype='int64'), 
    paddle.static.InputSpec(shape=[None, 512], dtype='int64'),
    ])
paddle.jit.save(jit_model, "./export")
```
所有的T5模型都无法转换哦，这动态图是不是不好用于部署啊
