### ISSUE TITLE
!bash predict1.sh预测出现问题

### ISSUE THREAD

**Issue by hfy-only** [PaddlePaddle/PaddleNLP#2106]
采用官网ai studio训练完数据后，然后!bash predict1.sh预测出现问题，下面是所用的版本信息，环境选择是V100 32GB
Name: paddlepaddle-gpu
Version: 2.2.2.post101
Summary: Parallel Distributed Deep Learning
Home-page: UNKNOWN
Author: 
Author-email: Paddle-better@baidu.com
License: Apache Software License
Location: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages
Requires: astor, decorator, numpy, Pillow, protobuf, requests, six
Required-by: 
Name: paddlenlp
Version: 2.0.7
Summary: PaddlePaddle NLP Model Core Library
Home-page: https://github.com/PaddlePaddle/PaddleNLP
Author: PaddlePaddle Speech and Language Team
Author-email: paddlesl@baidu.com
License: Apache 2.0
Location: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages
Requires: colorama, colorlog, h5py, jieba, multiprocess, seqeval
Required-by: paddlehub
[Errno 2] No such file or directory: 'relation_extraction/'
/home/aistudio/relation_extraction
![(R)4S9$4F_ZKKVIC6Z$79M7](https://user-images.githubusercontent.com/31085549/167748950-99fa5d8a-0596-4026-9e81-282514b8be93.png)

**Comment by hfy-only** [comment]
![image](https://user-images.githubusercontent.com/31085549/167750219-8e945408-b482-4ccb-8594-fcb6cd1dca88.png)
![image](https://user-images.githubusercontent.com/31085549/167750289-5bbe1d94-425f-49a1-bbc5-3c1767549cf0.png)

**Comment by hfy-only** [comment]
还是预测出错
![image](https://user-images.githubusercontent.com/31085549/167751893-2f14be06-e16e-4125-92c1-cf257b9c7495.png)

![image](https://user-images.githubusercontent.com/31085549/167751826-1dca5b66-740e-46d1-9227-5f4eb39b39aa.png)

**Comment by LemonNoel** [comment]
请问有AI Studio的链接吗？具体跑的是哪份代码呢？

**Comment by hfy-only** [comment]
就跑!bash predict1.sh这部分代码，链接如下   https://aistudio.baidu.com/aistudio/projectdetail/3975868?shared=1

**Comment by LemonNoel** [comment]
看起来是版本问题，在终端输入``nvidia-smi``检查当前CUDA版本。检查完从 [官网安装文档](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)复制相应设备上的安装脚本。

<img width="740" alt="截屏2022-05-11 下午4 30 55" src="https://user-images.githubusercontent.com/25607475/167805203-f779fa90-c8f4-4fa9-8ae1-a5a39b8fa20a.png">

我这边测试的V100 32GB是10.1，因此把安装脚本替换为
```shell
# 安装paddlenlp最新版本
!python -m pip install paddlepaddle-gpu==2.2.2.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
!pip install paddlenlp==2.2.5 -i https://pypi.tuna.tsinghua.edu.cn/simple
```
之后依次运行代码就没有报错了。

**Comment by hfy-only** [comment]
谢谢，说的非常正确，我再试试看

**Comment by hfy-only** [comment]
我把batch调到2还是会溢出，环境选择是V100 32GB，所以有什么好办法呢

![1652263395(1)](https://user-images.githubusercontent.com/31085549/167829374-cf5fa836-f974-44f5-b656-8fc7f4053c7d.jpg)

**Comment by hfy-only** [comment]
我把batch调到1还是会溢出，环境选择是V100 32GB，所以请教下有什么好办法呢
![image](https://user-images.githubusercontent.com/31085549/167832869-fc47af1d-69f0-462d-8129-837219a317a2.png)

**Comment by LemonNoel** [comment]
提示是内存溢出，一般在使用CPU计算时会出现，建议在代码中``print(paddle.device.get_device())``查看运行设备，在运行前用``free -h``查看下可用内存大小。

**Comment by hfy-only** [comment]
这是溢出时的，默认的设置
![image](https://user-images.githubusercontent.com/31085549/167973837-f2821b79-966a-4bfe-afd7-947834975211.png)
![image](https://user-images.githubusercontent.com/31085549/167974121-c796588f-a334-477c-8baa-ad4a2bc6509d.png)

**Comment by LemonNoel** [comment]
是在执行到哪一步报错的呢？

**Comment by LemonNoel** [comment]
测试了一下110G内存确实不够，如果要在AIStudio上运行，可以把``max_seq_length``设置为256

**Comment by hfy-only** [comment]
实在抱歉，目前max_seq_length设置小了没有内存溢出了，但是又遇到了新的问题predict1.sh: line 15: --batch_size: command not found
![image](https://user-images.githubusercontent.com/31085549/168228814-27b6a43c-5b8e-4877-8eb4-5cb5d94a0f04.png)

**Comment by LemonNoel** [comment]
可以截图看一下predict1.sh的内容吗？

**Comment by hfy-only** [comment]
predict1.sh的内容如下：
![image](https://user-images.githubusercontent.com/31085549/168509172-cc98cc9a-b2c6-4ce0-93c9-b62ebd2bfdcc.png)

**Comment by LemonNoel** [comment]
报错是因为第15行重复的``batch_size``设置，删掉就可以了，前边脚本是正常运行的。在参数换行的时候需要用``\``来连接，没有``\``下一行会被认为是新的命令，所以这里报错了。
