### ISSUE TITLE
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.

### ISSUE THREAD

**Issue by GMfatcat** [PaddlePaddle/PaddleNLP#2112]
看了下issue，發現這個好像是paddleNLP在windows老問題。在Seq2Seq對聯生成的範例中出現這個情況

![image](https://user-images.githubusercontent.com/58526756/167765516-f04e4c8e-3a72-413b-8b05-ebe1d6aa7ddb.png)

Example Code 今天早上剛剛clone下來，paddleNLP版本2.2.6

感覺問題還是出在np array window 默認 int32 非 int64，做了以下改動後還是出現錯誤
![image](https://user-images.githubusercontent.com/58526756/167765954-a2a2bcec-8149-413c-b268-c2d44073c9e5.png)

請問如何解決?

**Comment by GMfatcat** [comment]
@LiuChiachi 請問問題有解決嗎?

**Comment by LiuChiachi** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/a389a72c56e4445e74405b0716a99989cdc5d3a3/examples/text_generation/couplet/data.py#L75

```
    tgt, tgt_length = Pad(pad_val=pad_id, ret_length=True, dtype="int64")(
        [inst[1] for inst in insts])
```


建议`Pad()`里面指定`dtype`为`int64`这样试一下，另一个非常类似的例子是这样修复的，#1198, #1216

**Comment by GMfatcat** [comment]
加上就可以train了
