### ISSUE TITLE
MacBERT是否有小型化模型

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#2122]
macbert有tiny版的吗

**Comment by wawltor** [comment]
> macbert有tiny版的吗

您好，没有这个macbert有tiny了，想问一下具体想进行什么样的工作了

**Comment by ZeyuChen** [comment]
@zhentaoCoding 可以试试最新的ernie 3.0-medium这个6层的小模型，阅读理解上的效果也是相当好的，如果有轻量级模型需求的话，可以试试这个。

**Comment by ZTurboX** [comment]
> @zhentaoCoding 可以试试最新的ernie 3.0-medium这个6层的小模型，阅读理解上的效果也是相当好的，如果有轻量级模型需求的话，可以试试这个。

ernie 3.0-medium在cpu下预测速度怎么样

**Comment by tianxin1860** [comment]
ERNIE3.0 系列模型 CPU 上的预测提供了做量化、裁剪等提升性能的方法，具体性能数据可以参考这里: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0#CPU%E6%80%A7%E8%83%BD

**Comment by ZTurboX** [comment]
> ERNIE3.0 系列模型 CPU 上的预测提供了做量化、裁剪等提升性能的方法，具体性能数据可以参考这里: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0#CPU%E6%80%A7%E8%83%BD

ERNIE3.0 在mask任务上效果如何

**Comment by tianxin1860** [comment]
mask 任务具体是指 MLM 任务还是什么具体的下游任务？

**Comment by ZTurboX** [comment]
> MLM 任务

MLM 任务

**Comment by tianxin1860** [comment]
MLM 任务在预训练阶段通过  PPL 来评估的，具体需求是什么呢？是要用 MLM 任务来做完形填空还是？

**Comment by ZTurboX** [comment]
> MLM 任务在预训练阶段通过 PPL 来评估的，具体需求是什么呢？是要用 MLM 任务来做完形填空还是？

做拼写纠错，类似于完型填空

**Comment by tianxin1860** [comment]
纠错的话，可以参考下 PaddleNLP 提供的纠错模型: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc
