### ISSUE TITLE
信息抽取keyerror错误

### ISSUE THREAD

**Issue by Sarchpr** [PaddlePaddle/PaddleNLP#2128]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.2.1
2）系统环境：请您描述系统类型，例如Linux/，python3.7
- 复现信息：如为报错，请给出复现环境、复现步骤
复现baseline,训练模型出错：KeyError: 'B-股东减持'
已经查看utils.py和dataprepare.py，读取文件都有utf8编码。

**Comment by wawltor** [comment]
> 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.2.1
>   2）系统环境：请您描述系统类型，例如Linux/，python3.7
> * 复现信息：如为报错，请给出复现环境、复现步骤
>   复现baseline,训练模型出错：KeyError: 'B-股东减持'
>   已经查看utils.py和dataprepare.py，读取文件都有utf8编码。

辛苦发一下具体执行的脚本是哪个吗？

**Comment by Sarchpr** [comment]
> 

信息抽取-事件抽取任务基线系统-duee

**Comment by LemonNoel** [comment]
根据现在的信息我没办法判断。请问PaddleNLP和PaddlePaddle版本分别是多少呢，具体执行哪个路径下的哪个shell脚本，以及报错的截图可以提供一下吗？

**Comment by Sarchpr** [comment]
paddlenlp  版本2.2.6      paddle  版本 2.2.1
执行notebook位置:   PaddleNLP-develop\examples\information_extraction\DuEE.   我在这个路径下建的notebook.代码是粘贴的："PaddleNLP实战——LIC2021事件抽取任务基线"  如下图：
![图片](https://user-images.githubusercontent.com/105440801/168262610-8b9b3eca-9ccc-446a-8aaa-d27f0efe4e42.png)

在执行到训练模型的时候，出现错误：  如下图这个cell:
![图片](https://user-images.githubusercontent.com/105440801/168263488-b8c10102-ba24-497f-af79-21cbd0d370b3.png)

报错信息：
![图片](https://user-images.githubusercontent.com/105440801/168263586-25335a94-7792-4fff-b9fc-a99963930deb.png)

昨天我在issues上看到一个类似的错误，但是解决方法不适用我遇到的这个。https://github.com/PaddlePaddle/PaddleNLP/issues/1964

**Comment by Sarchpr** [comment]
已解决，谢谢你的关注。

**Comment by wj-Mcat** [comment]
@Sarchpr 你能分享一下你的解决方案吗？这样其他遇到这个问题开发者就可以快速找到解决方案了。

非常期待你的分享
