### ISSUE TITLE
DUEE 事件抽取任务基线系统  aistudio运行报错：

### ISSUE THREAD

**Issue by xixilllll** [PaddlePaddle/PaddleNLP#2129]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP 2.3.0，PaddlePaddle2.2.2
2）系统环境：请您描述系统类型，例如aistudio
DUEE这个项目，在aisudio运行出错。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuEE
![image](https://user-images.githubusercontent.com/40450302/168097848-85a9bc91-6f39-4a06-a0a8-5a75c64163d0.png)

报错信息：
check and create directory
dir ./ckpt exist
dir ./ckpt/DuEE-Fin exist
dir ./submit exist

start DuEE-Fin data prepare

=================DUEE FINANCE DATASET==============

=================start schema process==============
input path ./conf/DuEE-Fin/event_schema.json
Traceback (most recent call last):
  File "duee_fin_data_prepare.py", line 226, in <module>
    tags_trigger = schema_process(schema_path, "trigger")
  File "duee_fin_data_prepare.py", line 108, in schema_process
    for line in read_by_lines(path):
  File "/home/aistudio/utils.py", line 27, in read_by_lines
    with open(path, "r", encoding="utf8") as infile:
FileNotFoundError: [Errno 2] No such file or directory: './conf/DuEE-Fin/event_schema.json'
end DuEE-Fin data prepare

**Comment by LemonNoel** [comment]
数据的路径问题。可以先把``./data/DuEE-fin/duee_fin_event_schema.json``重命名并移动到``./conf/DuEE-Fin/event_schema.json``作为暂时解决方案，包括train.json等文件也需要重命名放在相应目录。

后续我们会提PR来改善这部分的体验。
