### ISSUE TITLE
paddlenlp进行interence报错

### ISSUE THREAD

**Issue by zhaojingtong1231** [PaddlePaddle/PaddleNLP#2133]
- paddlenlp 2.2.6 paddlepaddle 2.2.2
- linux python3.7
- 项目链接
- 项目“ernietiiny_time”共享链接(有效期三天
- 在inference脚本中是部署推理
- savemodel.py是保存模型到model目录下
![image](https://user-images.githubusercontent.com/73507164/168209460-564a26ff-3d70-4ef1-8474-8f42a94141ef.png)

**Comment by guoshengCS** [comment]
我在note中运行会报不一样的错误，请问可否在终端环境运行看下，也可以提供下能在终端环境运行的python代码，notebook不太方便排查
<img width="948" alt="image" src="https://user-images.githubusercontent.com/14105589/168227553-30db74ca-2c75-4440-ba4b-f9ee2e4894fd.png">

**Comment by zhaojingtong1231** [comment]
> * paddlenlp 2.2.6 paddlepaddle 2.2.2
> * linux python3.7
> * 项目链接
> * 项目“ernietiiny_time”共享链接(有效期三天)：
> * 在inference脚本中是部署推理
> * savemodel.py是保存模型到model目录下
>   ![image](https://user-images.githubusercontent.com/73507164/168209460-564a26ff-3d70-4ef1-8474-8f42a94141ef.png)
