### ISSUE TITLE
paddlenlp.layers.crf中LinearChainCrf有办法转成静态图吗？

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#2141]
版本、环境信息为
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.1，PaddlePaddle2.2.2
2）系统环境：centos7，python3.6

**Comment by ZeyuChen** [comment]
@Macxy2018 可以的，可以参考这个示例
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/export_model.py

这里免就包含LinearChainCRF导出成静态图模型进行部署。

**Comment by Macxy2018** [comment]
好的，已经参考，并且转换成功
