### ISSUE TITLE
TaBERT 与 RAT-SQL的使用问题

### ISSUE THREAD

**Issue by badaoxiaojie** [PaddlePaddle/PaddleNLP#2143]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

你好，我想问一下，你们用的是ERNIE这个模型进行的预训练，如果我换成TABERT这个预训练语言模型，由于paddle它不支持PyTorch，有什么方法能解决嘛？我还有一个疑问，因为你们这个是对RAT-SQL模型的增强，支持多种语言是不是指支持中文和英文的实现？你们还提到了对value的识别能力，是怎么体现的？我还想问一下，你们在对问题和数据库进行编码的时候，还是使用的GNN去编码嘛？是否考虑了对value的编码？

**Comment by ZeyuChen** [comment]
我们目前还没有TaBERT，可以issues这里给我们个feature request，我们的生态开发伙伴可能会将这个模型转进来。
RAT-SQL这个模型你是否跑起来了？以及TaBERT的结构与BERT结构区别大吗？
