### ISSUE TITLE
通用信息抽取 -- 基于UIE的基线系统 相关问题

### ISSUE THREAD

**Issue by snoopy1316** [PaddlePaddle/PaddleNLP#2153]
环境信息：Windows10 cpu python=3.7 paddlepaddle=2.2.3 paddlenlp=2.2.6
参考文档：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE#quick-start
在进行多任务模型训练时输入命令：python3 run_seq2struct.py   --multi_task_config config/multi-task-duuie.yaml  --negative_keep 1.0   --do_train   --metric_for_best_model=all-task-ave     --model_name_or_path=./uie-char-small   --num_train_epochs=6   --per_device_train_batch_size=8    --per_device_eval_batch_size=64  --output_dir=output/duuie_multi_task_b32_lr5e-4      --logging_dir=output/duuie_multi_task_b32_lr5e-4_log   --learning_rate=5e-4       --overwrite_output_dir          --gradient_accumulation_steps  无结果输出 无日志，该怎样解决

**Comment by luyaojie** [comment]
您好，可能是 CPU 运行较久，尝试使用使用较小的 --logging_steps=1 ，看是否有输出。

也可以使用在 Aistudio 提供的[基线](https://aistudio.baidu.com/aistudio/projectdetail/3913877)，可以方便运行。

**Comment by snoopy1316** [comment]
> 您好，可能是 CPU 运行较久，尝试使用使用较小的 --logging_steps=1 ，看是否有输出。
> 
> 也可以使用在 Aistudio 提供的[基线](https://aistudio.baidu.com/aistudio/projectdetail/3913877)，可以方便运行。

感谢回复，但是目前的情况是输入命令之后就会立刻结束进程，没有训练结果的输出（没有训练）；不是等待好长时间之后没有结果

**Comment by luyaojie** [comment]
原始命令中的 `--gradient_accumulation_steps` 似乎缺少默认的参数，可以在后面添加参数  `--gradient_accumulation_steps 1` 试一下。
另外 cpu 运行需要添加 `--device=cpu` 。

请试一下下面的代码能否正常运行，我在 Windows 11 上测试可以运行到训练部分 (`python3.8` 可以根据实际修改)。

python3.8 run_seq2struct.py --multi_task_config config/multi-task-duuie.yaml --negative_keep 1.0 --do_train --metric_for_best_model=all-task-ave --model_name_or_path=./uie-char-small --num_train_epochs=6 --per_device_train_batch_size=8 --per_device_eval_batch_size=64 --output_dir=output/duuie_multi_task_b32_lr5e-4 --logging_dir=output/duuie_multi_task_b32_lr5e-4_log --learning_rate=5e-4 --overwrite_output_dir  --device cpu --gradient_accumulation_steps 1

如果还是有错误，方便的话可以截一下图，或者看看前序的命令有没有执行错误。

**Comment by snoopy1316** [comment]
> python3.8 run_seq2struct.py --multi_task_config config/multi-task-duuie.yaml --negative_keep 1.0 --do_train --metric_for_best_model=all-task-ave --model_name_or_path=./uie-char-small --num_train_epochs=6 --per_device_train_batch_size=8 --per_device_eval_batch_size=64 --output_dir=output/duuie_multi_task_b32_lr5e-4 --logging_dir=output/duuie_multi_task_b32_lr5e-4_log --learning_rate=5e-4 --overwrite_output_dir --device cpu --gradient_accumulation_steps 1

之前的命令全部都成功执行：生成有 data/DuUIE_pre 
按照您这边的输入，还是出现相同的结果（立即结束运行）
![image](https://user-images.githubusercontent.com/94336500/168547689-c6ce301e-e2ea-4b78-8ab7-a8f7c18ac74a.png)

**Comment by snoopy1316** [comment]
python3 xxxxxxxxxxxx.py  xxxxxxxxxxxxxxxx改为python xxxxxxxx.py xxxxxxxxxxxxxxxx有正常训练日志等的输出。。。
