### ISSUE TITLE
TaskFlow/information_extraction/UIETask 中的 schema tree 被重复构建

### ISSUE THREAD

**Issue by Spico197** [PaddlePaddle/PaddleNLP#2165]
- 版本、环境信息
1）PaddleNLP==2.3.0，paddlepaddle-gpu==2.3.0
2）系统环境：Ubuntu18.04
- 复现信息：如为报错，请给出复现环境、复现步骤

如这里所示，`_run_model`函数中多次调用了`self._build_tree`，而 task 在实例化时，会先调用一次 `self._build_tree`，但是未保存建树的结果。多次建树的步骤十分影响系统预测时的性能。
https://github.com/PaddlePaddle/PaddleNLP/blob/f2085e65d686e6f5369dfa8ff6a43092c95850cb/paddlenlp/taskflow/information_extraction.py#L331-L336

https://github.com/PaddlePaddle/PaddleNLP/blob/f2085e65d686e6f5369dfa8ff6a43092c95850cb/paddlenlp/taskflow/information_extraction.py#L122-L125

https://github.com/PaddlePaddle/PaddleNLP/blob/f2085e65d686e6f5369dfa8ff6a43092c95850cb/paddlenlp/taskflow/information_extraction.py#L462-L485

请问是否接受个人的PR？我可以帮忙修一下。

**Comment by wawltor** [comment]
您好，我们非常乐意看到个人体检PR哈，欢迎对开源社区贡献力量！

**Comment by Spico197** [comment]
感谢您的回复，我已提交了相关的PR
