### ISSUE TITLE
albertforquestion导入报错

### ISSUE THREAD

**Issue by 2627020811** [PaddlePaddle/PaddleNLP#2174]
使用ai studio的jupter book环境导入albertforquestion不成功.
cannot import name 'AlbertForQuestionAnswering' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddlenlp/transformers/__init__.py)  

可是我查看源码是存在这个模型的
同理,xlnetforquestionanswering也导入不了

**Comment by yingyibiao** [comment]
感谢您的反馈，我们没有在 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/albert/modeling.py#L24 里面添加 AlbertForQuestionAnswering，所以导致无法使用命令 from paddlenlp.transformers import AlbertForQuestionAnswering。
不过您可以使用 from paddlenlp.transformers.albert.modeling import AlbertForQuestionAnswering 进行调用。

**Comment by 2627020811** [comment]
> 感谢您的反馈，我们没有在 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/albert/modeling.py#L24 里面添加 AlbertForQuestionAnswering，所以导致无法使用命令 from paddlenlp.transformers import AlbertForQuestionAnswering。 不过您可以使用 from paddlenlp.transformers.albert.modeling import AlbertForQuestionAnswering 进行调用。

from paddlenlp.transformers.xlnet.modeling import XLNetForQuestionAnswering 我导入Xlnet的问答模型仍然报错，看源码也是有的，望解答，谢谢

**Comment by yingyibiao** [comment]
我本地测试是可以的，建议更新一下您的PaddleNLP版本。

**Comment by 2627020811** [comment]
我是在ai studio的在线jupter book环境写代码的，要不您帮我看一下第一部分导入有啥问题，我试了实在不行，而且我挺急的。。。非常抱歉 and 万分感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午2:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] albertforquestion导入报错 (Issue #2174)





 
我本地测试是可以的，建议更新一下您的PaddleNLP版本。

**Comment by yingyibiao** [comment]
! pip install --upgrade paddlenlp
! pip show paddlenlp
在项目开始前先运行着这两行代码～

**Comment by 2627020811** [comment]
报了一个pip的error呢，这个也不知道咋回事
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] albertforquestion导入报错 (Issue #2174)





 
! pip install --upgrade paddlenlp
 ! pip show paddlenlp
 在项目开始前先运行着这两行代码～

**Comment by yingyibiao** [comment]
可以发个截图，我这边显示乱码了

**Comment by 2627020811** [comment]
这是执行指令后的信息，麻烦您看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] albertforquestion导入报错 (Issue #2174)





 
可以发个截图，我这边显示乱码了

**Comment by yingyibiao** [comment]
我这边看不到截图

**Comment by 2627020811** [comment]
附件里面没有png格式照片吗？可能qq邮箱太垃圾了吧，我换个网易邮箱给您发一下吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] albertforquestion导入报错 (Issue #2174)





 
我这边看不到截图

**Comment by 2627020811** [comment]
您好，我用网易邮箱重发给您一遍，实在抱歉


| |
zyl2627020811
|
|
***@***.***
|
签名由网易邮箱大师定制

**Comment by yingyibiao** [comment]
不要用邮箱回复，你直接在github上添加图片即可。

**Comment by 2627020811** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] albertforquestion导入报错 (Issue #2174)





 
不要用邮箱回复，你直接在github上添加图片即可。
