### ISSUE TITLE
UIE信息抽取模型中关系抽取的schema定义

### ISSUE THREAD

**Issue by jiangix-paper** [PaddlePaddle/PaddleNLP#2176]
请问UIE信息抽取模型中关系抽取的schema定义是什么样的？

**Comment by wawltor** [comment]
具体可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96 这块的文档，
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/16698950/168620161-21b27a69-9cf1-45bd-9c47-0e74bcf7c4bb.png">
用dict的方式来抽取关系，key是实体，value的是relation的集合

**Comment by willqq** [comment]
同问，想了解哪里可以查询到schema目前内置了哪些定义？ 例如我要抽取“地点”这类信息，scheme = ['地区'(不能设置为'地点')]

**Comment by willqq** [comment]
找到了，定义在termtree_type.csv里了

**Comment by linjieccc** [comment]
> 同问，想了解哪里可以查询到schema目前内置了哪些定义？ 例如我要抽取“地点”这类信息，scheme = ['地区'(不能设置为'地点')]

因为是开放域的信息抽取，schema里的类别没有限制，用户可以自己定义。这里`地区`和`地点`都是支持的，也可以针对地点定义更细粒度的类别信息（比如县、区、街道等）。

**Comment by CANMIDO** [comment]
为什么说ie is not defined啊
