### ISSUE TITLE
UIE 在paddle-gpu下无法复线cpu模式下的结果

### ISSUE THREAD

**Issue by xrzlizheng** [PaddlePaddle/PaddleNLP#2181]
- 版本、环境信息
-linux下  python  3.6.1
packaging                          21.0
paddle-bfloat                      0.1.2
paddle2onnx                        0.9.5
paddlefsl                          1.1.0
paddlenlp                          2.3.0
paddlepaddle-gpu                   2.3.0
pandarallel                        1.6.1
`# 实体抽取
from pprint import pprint
from paddlenlp import Taskflow
schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！")) `
相同环境下paddlepaddle   2.3.0  可以正确返回结果
`[{'时间': [{'end': 6, 'probability': 0.9857378532924486, 'start': 0, 'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,'probability': 0.8503089953268272,'start': 6,'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,'probability': 0.8981548639781138,'start': 28,'text': '谷爱凌'}]}]
`
但是paddlepaddle-gpu 结果为`[{}]`

**Comment by xrzlizheng** [comment]
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.is_compiled_with_cuda()
True
>>> from pprint import pprint
>>> from paddlenlp import Taskflow
>>> schema = ['时间', '选手', '赛事名称']
>>> ie = Taskflow('information_extraction', schema=schema,device_id=-1)
[2022-05-17 10:24:19,199] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-05-17 10:24:19,200] [    INFO] - Already cached /home/zli/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
>>> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
[{'时间': [{'end': 6,
          'probability': 0.9857379716035553,
          'start': 0,
          'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,
            'probability': 0.8503085040929115,
            'start': 6,
            'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,
          'probability': 0.8981545683581942,
          'start': 28,
          'text': '谷爱凌'}]}]
>>> schema = ['时间', '选手', '赛事名称'] # Define the schema for entity
获得金牌！"))>>> ie = Taskflow('information_extraction', schema=schema,device_id=0)
[2022-05-17 10:25:02,083] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-05-17 10:25:02,083] [    INFO] - Already cached /home/zli/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
>>> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
[{}]
>>>

**Comment by linjieccc** [comment]
麻烦提供下CUDA、cuDNN版本信息

**Comment by wawltor** [comment]
经排查，是安装GPU版本的PaddlePaddle有问题，通过conda安装即可 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/linux-conda.html
