### ISSUE TITLE
ERNIE 3.0能否用于文本匹配任务中？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#2182]
例如这个：
[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching](url)

**Comment by wawltor** [comment]
> 例如这个： [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching](url)

可以的，只要把相关模型名称改成ernie-3.0-base-zh 或者ernie-3.0-medium-zh即可

**Comment by wjddd** [comment]
> > 例如这个： [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching](url)
> 
> 可以的，只要把相关模型名称改成ernie-3.0-base-zh 或者ernie-3.0-medium-zh即可

谢谢，已经测试成功，model_config.json是在https://github.com/PaddlePaddle/PaddleNLP/blob/d0a5ea9691b64e458b747cffa37a3db4cb5ae540/model_zoo/uie/utils.py中找到的
