### ISSUE TITLE
UIE支持英文吗？

### ISSUE THREAD

**Issue by mingwei-liu** [PaddlePaddle/PaddleNLP#2184]
你好，目前的通用信息抽取模块支持英文吗，比如我的输入语料和schema都是英文的？原始论文似乎是中文英文都有的？

**Comment by solar2ain** [comment]
你好，暂时还不支持英文，后续会支持

**Comment by shan23chen** [comment]
> 你好，暂时还不支持英文，后续会支持

您好，会pretrain 一个英文 medical domain的 UIE 吗？ 多谢！

**Comment by DraymondHIT** [comment]
> 你好，暂时还不支持英文，后续会支持

你好，可以加入UIE英文模型的事件抽取（Event Extraction）吗？

**Comment by xinj7** [comment]
> 你好，暂时还不支持英文，后续会支持

你好 现在似乎还没有支持？
