### ISSUE TITLE
 PLATO-2 模型文件的来源

### ISSUE THREAD

**Issue by zhangxu999** [PaddlePaddle/PaddleNLP#2185]
1. paddle2.0版本的 PLATO-2 相关模型文件是基于paddle1.x 模型转化的，还是在paddle2.0上重新训练的？

2.为什么没有发布paddle2.0 版本的用于对话回复排序的NSP模型呢？

**Comment by ZeyuChen** [comment]
@zhangxu999 
1. 是基于1.x模型转换的，不是重新训练的。
2. 未来会有的，但以前的模型可能不会用重复的计算资源换个版本重新训一遍，会有额外的成本。可能会选择把这个成本放在研发新模型上会更好。

**Comment by FrostML** [comment]
1. PaddleNLP 这里是基于 1.x 模型转化的
2. 可以看看这里的代码，这里用到的 [`Plato2InferModel `](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/interaction.py#L57) 包括了 [`nsp`](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/model.py#L301) 的

**Comment by zhangxu999** [comment]
> @zhangxu999
> 
> 1. 是基于1.x模型转换的，不是重新训练的。
> 2. 未来会有的，但以前的模型可能不会用重复的计算资源换个版本重新训一遍，会有额外的成本。可能会选择把这个成本放在研发新模型上会更好。

@ZeyuChen 

感谢解答，不知能否提供下模型转换的代码（或者相应的教程），我想转化一个中文的1.x的NSP模型。
（对paddle的代码还不是很熟，我研究了  [兼容载入旧格式模型](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/load_old_format_model_cn.html) ，但是还是没能搞定，），谢谢！

**Comment by zhangxu999** [comment]
> 1. PaddleNLP 这里是基于 1.x 模型转化的
> 2. 可以看看这里的代码，这里用到的 [`Plato2InferModel `](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/interaction.py#L57) 包括了 [`nsp`](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/model.py#L301) 的

@FrostML 
感谢您的解答，我看到了相关代码，但是对应的模型文件只有英文版的，我需要在plato-mini模型后接上一个中文的NSP模型。

**Comment by FrostML** [comment]
目前没有从 1.x 到 2.x 直接的转换教程或是代码，我可以提供一个思路。

首先需要说明是，模型中的参数在框架里面是通过参数本身的名称确定的，需要构建一个名称之间的对应关系。

### PaddlePaddle 1.x
如果您 1.x 的版本是使用的静态图的话，对于某一个参数，可以通过以下方式获取其值：
``` python
import paddle.fluid as fluid
import numpy as np
param = np.array(fluid.global_scope().find_var(var_name).get_tensor())
```
`var_name` 其实就是参数的名称，构建一个名称到值的字典，可以 dump 下来：

其次，如果是 1.x 的动态图版本，那么对应某个参数 tensor，只需要：
``` python
tensor.numpy()
```
即可。

### PaddlePaddle 2.x
对于 2.x 的动态图版本，比如我们已经构造好模型的实例：
``` python
model = NSP(...)
```

可以基于 state_dict 来获取 tensor 本身或是 tensor 的名称：
``` python
for item in model.state_dict():
    param = model
    item_list = item.split('.')
    for s in item_list:
        param = getattr(param, s)
    param  # tensor 本身
    param.name  # tensor 的名称
```

读取之前获取的字典，使用：
``` python
param.set_value(value) 
```
完成赋值。之后可以正常用 `paddle.save` 以及 `paddle.load` 直接存储和载入模型。

1.x 和 2.x 的参数的对应关系的构建可能会是一个比较复杂的地方，有一些比较快捷的方式，比如说，在模型组网的时候，将相同的参数的名称指定为一样的，那对应关系就比较好构建。
