### ISSUE TITLE
使用information_extraction进行实体识别，未输出任何结果便退出，退出代码-1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by newbby123** [PaddlePaddle/PaddleNLP#2194]
PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0，PaddlePaddle 2.2.0
系统环境：Windows10，python3.6

代码：
```
from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] 
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
```

控制行输出：
```
Connected to pydev debugger (build 202.6397.98)
[2022-05-17 17:46:40,047] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-05-17 17:46:40,047] [    INFO] - Already cached C:\Users\26966\.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by joey12300** [comment]
您好，我在最新版本的paddle上运行如下。您可以尝试更新一下最新版本的Paddle，看看还会不会报错？

![image](https://user-images.githubusercontent.com/10826371/168801181-9516fe42-b8a9-4f0f-bfc9-efa033adaee4.png)

**Comment by taishan1994** [comment]
> 您好，我在最新版本的paddle上运行如下。您可以尝试更新一下最新版本的Paddle，看看还会不会报错？
> 
> ![image](https://user-images.githubusercontent.com/10826371/168801181-9516fe42-b8a9-4f0f-bfc9-efa033adaee4.png)

同样遇到了这个问题：windows10 python3.6 paddle2.3.0 paddlenlp2.3.0

**Comment by taishan1994** [comment]
> PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0，PaddlePaddle 2.2.0 系统环境：Windows10，python3.6
> 
> 代码：
> 
> ```
> from pprint import pprint
> from paddlenlp import Taskflow
> 
> schema = ['时间', '选手', '赛事名称'] 
> ie = Taskflow('information_extraction', schema=schema)
> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
> ```
> 
> 控制行输出：
> 
> ```
> Connected to pydev debugger (build 202.6397.98)
> [2022-05-17 17:46:40,047] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
> [2022-05-17 17:46:40,047] [    INFO] - Already cached C:\Users\26966\.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt
> e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
> e[37m---    fused 0 pairs of fc gru patternse[0m
> 
> Process finished with exit code -1073741819 (0xC0000005)
> ```

我解决了，将scipy降低至1.3.1，不知道你能不能这样解决。

**Comment by newbby123** [comment]
> 

非常感谢，我把scipy降至1.3.1也解决了
