### ISSUE TITLE
使用语义检索系统中的example semantic_search_example.py报错

### ISSUE THREAD

**Issue by liuhj2015** [PaddlePaddle/PaddleNLP#2198]
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 513, but got 513. Please check input value.   [Hint: Expected ids[i] < row_number, but received ids[i]:513 >= row_number:513.] (at /home/Paddle/paddle/fluid/operators/lookup_table_v2_op.h:77)   [operator < lookup_table_v2 > error]。
查看代码好像是tokenizer query和paragraph没有设置max_seq_len

**Comment by tianxin1860** [comment]
请问使用的 CPU 环境还是 GPU 环境？

**Comment by liuhj2015** [comment]
> 请问使用的 CPU 环境还是 GPU 环境？

cpu

**Comment by tianxin1860** [comment]
因为模型和数据量不小，建议基于 GPU 环境跑哈，目前仅支持 GPU 环境， CPU 环境我们会尽快支持，欢迎关注。

**Comment by liuhj2015** [comment]
> 因为模型和数据量不小，建议基于 GPU 环境跑哈，目前仅支持 GPU 环境， CPU 环境我们会尽快支持，欢迎关注。

ok，我gpu环境上试下，不过看报错好像不是环境问题。

**Comment by tianxin1860** [comment]
我刚提 PR 修复了 CPU 上运行的问题: https://github.com/PaddlePaddle/PaddleNLP/pull/2201

**Comment by tianxin1860** [comment]
这个问题已经修复了，可以拉一下最新的代码哈，CPU 和 GPU 都支持了。

**Comment by liuhj2015** [comment]
好的，谢谢～
