### ISSUE TITLE
paddleNLP lexical_analysis的使用问题

### ISSUE THREAD

**Issue by Adrian-Yan16** [PaddlePaddle/PaddleNLP#220]
> 我完全按照github的文档做的，什么都没改动，但在运行 sh run.sh train_single_gpu 时，报错 run.sh: 7: run.sh: Syntax error: "(" unexpected ，我在aistudio上面运行的

**Comment by songzy12** [comment]
如果这个问题已经得到了解决（使用 bash 而不是 sh），可以关闭这个 issue?

**Comment by ZeyuChen** [comment]
问题已解决。
