### ISSUE TITLE
请问之后会开放下载已经过微调的ERNIE 3.0模型吗？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#2205]
像是文本匹配任务中使用LCQMC训练的ERNIE-1.0-Base
[https://github.com/PaddlePaddle/PaddleNLP/tree/e6dff46fc2cfd7838d5da2f81ad767f2d7d56e8a/examples/text_matching/ernie_matching#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD](url)

**Comment by wawltor** [comment]
您好，这块目前不会开放下载微调的模型哈，因为LCQMC的这个数据集相对来说一个通用数据集，大家可以通过自己的微调的数据来训练，同时该微调后的模型并不是一个通用模型，对于产业落地是比较难的；如果想用相似度判断的模型可以用 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E6%96%87%E6%9C%AC%E7%9B%B8%E4%BC%BC%E5%BA%A6 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/16698950/168960703-7df4c98a-3083-4ef7-be36-d4e364193750.png">

**Comment by wjddd** [comment]
了解，感谢~
