### ISSUE TITLE
代码中中文服务导致unicode显示异常

### ISSUE THREAD

**Issue by LeoMax-Xiong** [PaddlePaddle/PaddleNLP#2206]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/downloader.py#L387
代码里面 '~' 是中文服务，导致有下面问题。

```
UnicodeEncodeError: 'ascii' codec can't encode character '\uff5e' in position 0: ordinal not in range(128)
```

**Comment by yingyibiao** [comment]
Python3 默认使用 utf-8 编码，所以是支持 '~' 符号的，这里需要看一下你的环境的编码设置。
可以通过 sys.getdefaultencoding() 查看默认编码方式，另外可以查看一下 LC_ALL、LC_CTYPE、LANG 这三个环境变量有没有额外设置。

**Comment by yt605155624** [comment]
我们在 paddlespeech/__init__.py 里面加了个
```python
# limitations under the License.
import _locale

_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

```
你们要不也加上？

**Comment by yingyibiao** [comment]
> 我们在 paddlespeech/**init**.py 里面加了个
> 
> ```python
> # limitations under the License.
> import _locale
> 
> _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])
> ```
> 
> 你们要不也加上？

Good suggestion!
