### ISSUE TITLE
想问下能否将huggingface的bart模型load到paddlenlp仓库的bart模型当中

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleNLP#2210]
如题，想问下有没有办法将huggingface的torch版bart模型load到paddlenlp仓库的bart模型上，主要是考虑到线上inference耗时的问题，目前采用的torch版本bart在输入长度为40的时候推理耗时为0.4s/条，不知道paddlenlp仓库bart模型推理耗时是多少，有没有相应的trt部署方法呢。如果有转换的方法能否提供些指导或例子，十分感谢～

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_summarization/bart

@will-wiki BART在PaddleNLP上已经有了。
请问你要用BART是做生成任务吗？如果是生成任务我们要高性能的加速版本，这块我们可以更近一步对接一下。

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/faster_generation

这是我们FasterGeneration的介绍，随时讨论。

**Comment by will-wiki** [comment]
> 

感谢回复，是用BART模型做生成任务，就是目前我有一个已经训练好的huggingface的torch版本BART模型，但是inference的速度在bs=1的情况下较慢，是发现了PaddleNLP实现了BART模型，想问下有没有办法加速BART模型的推理速度，是需要把torch模型转成paddle模型才能使用吗

**Comment by gongel** [comment]
你好，可以尝试使用我们的FasterGeneration，更多的细节欢迎加微信群来讨论。
![wc](https://user-images.githubusercontent.com/24390500/168974767-3824479d-1436-4cec-943f-86037f8f3bf9.png)

**Comment by will-wiki** [comment]
@gongel 按照这个方法的话，想问下有没有办法将现在已经训练好的torch版本的模型转换到paddle版的模型上呢

**Comment by gongel** [comment]
可以转换的。

**Comment by FrostML** [comment]
https://paddlenlp.readthedocs.io/zh/latest/community/contribute_models/convert_pytorch_to_paddle.html  模型转换的方式，这个链接里面内容可以提供些参考。
