### ISSUE TITLE
XLNetForQuestionAnswering导入报错

### ISSUE THREAD

**Issue by 2627020811** [PaddlePaddle/PaddleNLP#2212]
from paddlenlp.transformers.xlnet.modeling import XLNetForQuestionAnswering
显示报错：cannot import name 'XLNetForQuestionAnswering' from 'paddlenlp.transformers.xlnet.modeling' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/xlnet/modeling.py)

经查看源码是存在这个模型的

**Comment by yingyibiao** [comment]
您好，请问您使用的PaddleNLP版本是什么呢？可以更新一下PaddleNLP版本。

**Comment by 2627020811** [comment]
> 您好，请问您使用的PaddleNLP版本是什么呢？可以更新一下PaddleNLP版本。

执行更新仍报错呢。。。

**Comment by yingyibiao** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/52000032/168978628-f93e5fca-3287-49c3-acd3-d9382e0009dd.png">
我这边尝试了两种加载方式都是OK的。

**Comment by 2627020811** [comment]
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/52000032/168978628-f93e5fca-3287-49c3-acd3-d9382e0009dd.png">
> 
> 我这边尝试了两种加载方式都是OK的。

<img width="830" alt="pip报错" src="https://user-images.githubusercontent.com/48877760/168986377-7c49a0ac-b3ef-4905-894c-3e0348346b11.png">
按照您给的指令执行之后的结果，pip那里显示有conflict

**Comment by yingyibiao** [comment]
你试试能否正常加载

**Comment by 2627020811** [comment]
> 你试试能否正常加载

不可以的，唉

**Comment by yingyibiao** [comment]
我在ai-studio上进行测试，没有问题的～
