### ISSUE TITLE
关于命名实体识别问题

### ISSUE THREAD

**Issue by testliu123** [PaddlePaddle/PaddleNLP#2219]
运行代码
str1="小区内有大量空置车位"
ner = Taskflow("ner")
print(ner(str1))
结果：[('小区', '场所类'), ('内', '词汇用语'), ('有', '肯定词'), ('大量', '修饰词'), ('空置', '场景事件'), ('车位', '位置方位')]
其中 “车位”的 WordTag标签有问题？

**Comment by wawltor** [comment]
您好，NER这块的准确率不能保证百分百的了，这种case的话麻烦看看是否可以用我们最新的开源UIE能解决  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
