### ISSUE TITLE
uie-medical-base似乎权值有问题，uie-base能够正常训练，更换medical后F1一直都是0（医疗数据集）

### ISSUE THREAD

**Issue by CodeFrontWang** [PaddlePaddle/PaddleNLP#2221]
您好，我们在使用uie训练时，只将uie-base更换为uie-medical-base，但每次验证时，F1都是0，在uie-base上则没有这个问题，多次测试后，感到疑惑，忘解答~
![image](https://user-images.githubusercontent.com/88528512/168996380-a2416614-0c50-4759-9d22-ebee4fc040f8.png)

**Comment by LemonNoel** [comment]
医疗数据集具体是什么任务呢？uie-medical-base是在uie-base的基础上使用医疗NER数据finetune后的模型参数，如果数据类别相差较大，基于uie-base来训练的效果可能更好。

**Comment by CodeFrontWang** [comment]
您好，感谢回复，就是NER的任务，在uie-base上训练F1大概是接近60，但是在uie-medical-base上直接变成0了，所以感到很疑惑，
![image](https://user-images.githubusercontent.com/88528512/169004496-f29ee77e-0ba9-4af6-a395-1c6555600803.png)

**Comment by CodeFrontWang** [comment]
> 

如果是效果好或者不好，那很正常，但我不是很能理解，我只修改了这个参数，parser.add_argument("--model", choices=["uie-base", "uie-tiny", "uie-medical-base"], default="uie-medical-base",  结果F1就变成0了，如果这个参数是uie-base，那么F1都是50+的

**Comment by CodeFrontWang** [comment]
老师您好，我的数据是医疗NER的，在uie-base上训练验证集F1大概为60，但将模型改成uie-medical-base，无论怎么训练，P，R，F1一直都是0，其他参数没有动过，只改了模型。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] uie-medical-base似乎权值有问题，uie-base能够正常训练，更换medical后F1一直都是0（医疗数据集） (Issue #2221)




 
医疗数据集具体是什么任务呢？uie-medical-base是在uie-base的基础上使用医疗NER数据finetune后的模型参数，如果数据类别相差较大，基于uie-base来训练的效果可能更好。

**Comment by CodeFrontWang** [comment]
> 医疗数据集具体是什么任务呢？uie-medical-base是在uie-base的基础上使用医疗NER数据finetune后的模型参数，如果数据类别相差较大，基于uie-base来训练的效果可能更好。

老师您好，我再次测试了一下，使用CBLUE的CMeEE数据集，还是会有这个问题，在uie-base上能正常训练验证，uie-medical-base上验证的F1就会是0

**Comment by LemonNoel** [comment]
如果不训练，直接在uie-medical-base上验证F1是多少呢？

**Comment by LemonNoel** [comment]
另外PaddleNLP的版本号以及参数配置是多少呢？我这边也尝试复现一下

**Comment by CodeFrontWang** [comment]
老师您好，配置为paddlenlp&nbsp; 2.3.0，paddlepaddle-gpu&nbsp; &nbsp;2.2.2.post101，finetune参数为：

直接用代码下载的uie-medical-base验证的结果也是3个0，数据集为天池CBLUE2中的CMeEE。
今天测试了在该数据集下微调uie-base，验证集的F1能达到71，如果不微调，uie-base的直接效果为Evaluation precision: 0.46667, recall: 0.00069, F1: 0.00138。
感谢老师的回复！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] uie-medical-base似乎权值有问题，uie-base能够正常训练，更换medical后F1一直都是0（医疗数据集） (Issue #2221)





 
另外PaddleNLP的版本号以及参数配置是多少呢？我这边也尝试复现一下

**Comment by LemonNoel** [comment]
paddlenlp 2.3.0版本还没有uie-medical-base的参数，是develop版本吗？还是自己修改加载的呢？另外，现在沟通效率比较低，这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下联系方式，我们 1 对 1 沟通下。

**Comment by CodeFrontWang** [comment]
***@***.***，我是在AI STUDIO中，安装的2.3.0，那请问我是应该安装2.2.0吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] uie-medical-base似乎权值有问题，uie-base能够正常训练，更换medical后F1一直都是0（医疗数据集） (Issue #2221)




 
paddlenlp ***@***.***，方便的话可以留下联系方式，我们 1 对 1 沟通下。

**Comment by LemonNoel** [comment]
还是用2.3.0。可能是过拟合了，可以降低学习率或者减少训练步数。

**Comment by wawltor** [comment]
或者您在用户群里面吗？可以群里面叫一下我们，我们加你微信聊一下

**Comment by CodeFrontWang** [comment]
您好，我还未在用户群中，请问如何加呢？我的v13592886226


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] uie-medical-base似乎权值有问题，uie-base能够正常训练，更换medical后F1一直都是0（医疗数据集） (Issue #2221)





 
或者您在用户群里面吗？可以群里面叫一下我们，我们加你微信聊一下
