### ISSUE TITLE
cannot import name 'Taskflow' from 'paddlenlp' 

### ISSUE THREAD

**Issue by deathpooool** [PaddlePaddle/PaddleNLP#2227]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0，PaddlePaddle-gpu2.3.0.post101
2）系统环境：Linux，python版本3.7 
- 
from paddlenlp import Taskflow

ImportError: cannot import name 'Taskflow' from 'paddlenlp' 

初始版本paddlenlp不是2.3.0，根据issue#1990 执行pip install --upgrade paddlenlp后依然存在该问题

**Comment by ZeyuChen** [comment]
请确认下是否升级成功，这个现象应该是PaddleNLP没有被正确安装到最新版本。可以尝试Conda创建独立环境重新安装下。

**Comment by Nelsonlin0321** [comment]
Face this issue as well, which cannot be solved by upgrading, Mac M1.

**Comment by xxllp** [comment]
why？？？？？？？
