### ISSUE TITLE
readme里的doccano的版本的是什么？我觉得有必要写一下

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2234]
doccano1.6.0到1.6.3 都有数据集标注完导出后，标注全部消失的bug
doccano1.5.0又没有jsonl(relation)格式
现在怎么选择版本?

**Comment by linjieccc** [comment]
您好，UIE标注示例中用到的doccano版本是1.6.2。感谢反馈，我们会尽快补充到文档中。

**Comment by jiweizhangxu** [comment]
> 

不行,1.6.2还是有导出数据集标注全部消失的bug
![微信截图_20220519103852](https://user-images.githubusercontent.com/88191580/169193305-a254a5e7-825b-4a44-9f7f-a5951d1405cb.png)
![微信截图_20220519104337](https://user-images.githubusercontent.com/88191580/169193336-29602b63-b5d9-4509-8261-042f6b840abe.png)
![微信截图_20220519104353](https://user-images.githubusercontent.com/88191580/169193345-4086770f-297f-4469-9097-79262900d0b0.png)
![微信截图_20220519104305](https://user-images.githubusercontent.com/88191580/169193365-5cf33888-26e3-433d-ae36-b187e364c0f5.png)
![微信截图_20220519104424](https://user-images.githubusercontent.com/88191580/169193375-e35ecfdf-71a8-4bd6-9a84-2adfe209c189.png)

**Comment by taishan1994** [comment]
> > 
> 
> 不行,1.6.2还是有导出数据集标注全部消失的bug ![微信截图_20220519103852](https://user-images.githubusercontent.com/88191580/169193305-a254a5e7-825b-4a44-9f7f-a5951d1405cb.png) ![微信截图_20220519104337](https://user-images.githubusercontent.com/88191580/169193336-29602b63-b5d9-4509-8261-042f6b840abe.png) ![微信截图_20220519104353](https://user-images.githubusercontent.com/88191580/169193345-4086770f-297f-4469-9097-79262900d0b0.png) ![微信截图_20220519104305](https://user-images.githubusercontent.com/88191580/169193365-5cf33888-26e3-433d-ae36-b187e364c0f5.png) ![微信截图_20220519104424](https://user-images.githubusercontent.com/88191580/169193375-e35ecfdf-71a8-4bd6-9a84-2adfe209c189.png)

临时解决：https://github.com/taishan1994/doccano_export
