### ISSUE TITLE
PaddleNLP的Taskflow如何更改模型缓存的路径？

### ISSUE THREAD

**Issue by Dinxin** [PaddlePaddle/PaddleNLP#2243]
版本、环境信息：
1）PaddleNLP 2.3.0 PaddlePaddle-gpu 2.2.2.post101
2）CentOS, python 3.8

比如说，我想使用`Taskflow("information_extraction")`来做信息抽取任务，但是默认的缓存路径的存储空间不够，我想另外指定一个缓存路径。

**Comment by linjieccc** [comment]
您好，可以在任务初始化的时候通过`home_path`自定义修改缓存路径，示例如下：

```python
from paddlenlp import Taskflow

ie = Taskflow("information_extraction", home_path="/workspace")
```

其他关于Taskflow的使用问题也可以参考这里的FAQ：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#faq
