### ISSUE TITLE
请问基于Dureader的阅读理解任务使用的模型原文可以提供吗

### ISSUE THREAD

**Issue by Minjuner-97** [PaddlePaddle/PaddleNLP#225]

**Comment by Minjuner-97** [comment]
请问可以输出“没有答案”这种结果吗？

**Comment by smallv0221** [comment]
请问模型原文是什么意思。Dureader-robust对没有答案的输出是 ""

**Comment by Minjuner-97** [comment]
> 请问模型原文是什么意思。Dureader-robust对没有答案的输出是 ""

谢谢，因为我想知道这个模型具体是怎么写的，想看下模型图，或者有没有解释的相关文档呢？

如果理解为，  基于BERT的阅读理解模型，输入为【CLS】+ 问句+【SEP】+文本，经过BERT编码，输出是两个起始位置、结束位置的分类器，损失函数是两个分类器的损失函数的平均， 这样对吗？
另外，对于没有答案这种类型的输出，具体是怎么做到的呢？

**Comment by smallv0221** [comment]
您说的输入和loss设计是对的。对于没有答案的输出，是通过score-diff判断的，具体实现可以参见paddlenlp/metrics/squad.py  中的compute_prediction函数

**Comment by Minjuner-97** [comment]
> 您说的输入和loss设计是对的。对于没有答案的输出，是通过score-diff判断的，具体实现可以参见paddlenlp/metrics/squad.py 中的compute_prediction函数

好的 感谢~
