### ISSUE TITLE
Taskflow接口怎么指定线程数

### ISSUE THREAD

**Issue by zhuangAnjun** [PaddlePaddle/PaddleNLP#2258]
请问，Luixu下，Taskflow接口推理的时候怎么指定线程数呢

**Comment by zhuangAnjun** [comment]
在单个50左右长度句子用Taskflow接口做uie 预测耗时要5s，cpu环境

**Comment by wawltor** [comment]
> 在单个50左右长度句子用Taskflow接口做uie 预测耗时要5s，cpu环境

应该不需要5s的，第一次调用相对比较慢，接口启动再多次跑一下速度不至于5s

**Comment by zhuangAnjun** [comment]
> 

是不是用了lazy load？

**Comment by zhuangAnjun** [comment]
> > 在单个50左右长度句子用Taskflow接口做uie 预测耗时要5s，cpu环境
> 
> 应该不需要5s的，第一次调用相对比较慢，接口启动再多次跑一下速度不至于5s
是不是使用了惰性加载？

**Comment by wawltor** [comment]
第一次启动的时候，是因为加载了模型构建计算图，这块的框架开销会大点

**Comment by zhuangAnjun** [comment]
非第一次，后面几次的推理耗时也很长
还有这个怎么指定线程数呢

**Comment by wawltor** [comment]
您好，我们正在针对UIE在预测性能上优化，下周会同步出来，到时候可以进行多线程的预测

**Comment by zhuangAnjun** [comment]
请问这里多线程版本放出来了吗

**Comment by zhuxindong** [comment]
NLP的代码生成模型怎样指定CPU多线程加速？观察了一下一直只有一个核心在运行

**Comment by jiaohuix** [comment]
同问？
