### ISSUE TITLE
加载模型报错：OSError:   [operator < uniform_random > error]

### ISSUE THREAD

**Issue by wht0948** [PaddlePaddle/PaddleNLP#227]
from paddlenlp.transformers import UnifiedTransformerLMHeadModel, UnifiedTransformerTokenizer
model_name_or_path = 'unified_transformer-12L-cn'

model = UnifiedTransformerLMHeadModel.from_pretrained(model_name_or_path)
tokenizer = UnifiedTransformerTokenizer.from_pretrained(model_name_or_path)

报错：OSError:   [operator < uniform_random > error]

环境：
paddle：2.0.1
CUDA：11.0
CUDNN：10.0.130

**Comment by wht0948** [comment]
> 麻烦还请附下更为完整的报错信息，也请 @xiemoyuan 帮忙看下

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-dd859799c34a> in <module>
      6 model_name_or_path = 'unified_transformer-12L-cn'
      7 
----> 8 model = UnifiedTransformerLMHeadModel.from_pretrained(model_name_or_path)
      9 tokenizer = UnifiedTransformerTokenizer.from_pretrained(model_name_or_path)

~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *args, **kwargs)
    219         else:
    220             # Update with newly provided args and kwargs for derived model
--> 221             base_model = cls.base_model_class(*base_args, **base_kwargs)
    222             if base_arg_index is not None:
    223                 derived_args[base_arg_index] = base_model

~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/utils.py in __impl__(self, *args, **kwargs)
     81         def __impl__(self, *args, **kwargs):
     82             # keep full configuration
---> 83             init_func(self, *args, **kwargs)
     84             # registed helper by `_wrap_init`
     85             if help_func:

~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/unified_transformer/modeling.py in __init__(self, vocab_size, hidden_size, num_hidden_layers, num_attention_heads, intermediate_size, hidden_act, hidden_dropout_prob, attention_probs_dropout_prob, normalize_before, max_position_embeddings, type_vocab_size, initializer_range, unk_token_id, pad_token_id, bos_token_id, eos_token_id, mask_token_id)
    159         self.initializer_range = initializer_range
    160 
--> 161         self.embeddings = UnifiedTransformerEmbeddings(
    162             vocab_size, hidden_size, hidden_dropout_prob,
    163             max_position_embeddings, type_vocab_size)

~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/unified_transformer/modeling.py in __init__(self, vocab_size, hidden_size, hidden_dropout_prob, max_position_embeddings, type_vocab_size)
    114                  type_vocab_size=2):
    115         super(UnifiedTransformerEmbeddings, self).__init__()
--> 116         self.word_embeddings = nn.Embedding(vocab_size, hidden_size)
    117         self.position_embeddings = nn.Embedding(max_position_embeddings,
    118                                                 hidden_size)

~/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/common.py in __init__(self, num_embeddings, embedding_dim, padding_idx, sparse, weight_attr, name)
   1348         self._remote_prefetch = False
   1349         self._name = name
-> 1350         self.weight = self.create_parameter(
   1351             attr=self._weight_attr,
   1352             shape=self._size,

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py in create_parameter(self, shape, attr, dtype, is_bias, default_initializer)
    405         if isinstance(temp_attr, six.string_types) and temp_attr == "":
    406             temp_attr = None
--> 407         return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
    408                                              default_initializer)
    409 

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py in create_parameter(self, attr, shape, dtype, is_bias, default_initializer, stop_gradient, type)
    365                     "Please check the parameter attr value passed to self.create_parameter or "
    366                     "constructor of dygraph Layers".format(attr.name))
--> 367             return self.main_program.global_block().create_parameter(
    368                 dtype=dtype,
    369                 shape=shape,

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py in create_parameter(self, *args, **kwargs)
   2982                 pass
   2983             else:
-> 2984                 initializer(param, self)
   2985         return param
   2986 

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/initializer.py in __call__(self, var, block)
    555         if self._uniform:
    556             limit = np.sqrt(6.0 / float(fan_in + fan_out))
--> 557             op = block._prepend_op(
    558                 type="uniform_random",
    559                 inputs={},

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py in _prepend_op(self, *args, **kwargs)
   3094                 self, None, type=type, inputs=None, outputs=None, attrs=attrs)
   3095 
-> 3096             _dygraph_tracer().trace_op(type,
   3097                                        kwargs.get("inputs", {}),
   3098                                        kwargs.get("outputs", {}), attrs

~/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     41 
     42     def trace_op(self, type, inputs, outputs, attrs, stop_gradient=False):
---> 43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._has_grad and
     45                    not stop_gradient)

OSError: (External)  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  (at /paddle/paddle/fluid/platform/device_context.h:255)
  [operator < uniform_random > error]


不知道是不是因为加载模型时显存不够，如果是的话，我要怎么指定加载到哪张卡里。

**Comment by xiemoyuan** [comment]
> > 麻烦还请附下更为完整的报错信息，也请 @xiemoyuan 帮忙看下
> 
> OSError Traceback (most recent call last)
> in
> 6 model_name_or_path = 'unified_transformer-12L-cn'
> 7
> ----> 8 model = UnifiedTransformerLMHeadModel.from_pretrained(model_name_or_path)
> 9 tokenizer = UnifiedTransformerTokenizer.from_pretrained(model_name_or_path)
> 
> ~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *args, **kwargs)
> 219 else:
> 220 # Update with newly provided args and kwargs for derived model
> --> 221 base_model = cls.base_model_class(*base_args, **base_kwargs)
> 222 if base_arg_index is not None:
> 223 derived_args[base_arg_index] = base_model
> 
> ~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/utils.py in **impl**(self, *args, **kwargs)
> 81 def **impl**(self, *args, **kwargs):
> 82 # keep full configuration
> ---> 83 init_func(self, *args, **kwargs)
> 84 # registed helper by `_wrap_init`
> 85 if help_func:
> 
> ~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/unified_transformer/modeling.py in **init**(self, vocab_size, hidden_size, num_hidden_layers, num_attention_heads, intermediate_size, hidden_act, hidden_dropout_prob, attention_probs_dropout_prob, normalize_before, max_position_embeddings, type_vocab_size, initializer_range, unk_token_id, pad_token_id, bos_token_id, eos_token_id, mask_token_id)
> 159 self.initializer_range = initializer_range
> 160
> --> 161 self.embeddings = UnifiedTransformerEmbeddings(
> 162 vocab_size, hidden_size, hidden_dropout_prob,
> 163 max_position_embeddings, type_vocab_size)
> 
> ~/anaconda3/lib/python3.8/site-packages/paddlenlp/transformers/unified_transformer/modeling.py in **init**(self, vocab_size, hidden_size, hidden_dropout_prob, max_position_embeddings, type_vocab_size)
> 114 type_vocab_size=2):
> 115 super(UnifiedTransformerEmbeddings, self).**init**()
> --> 116 self.word_embeddings = nn.Embedding(vocab_size, hidden_size)
> 117 self.position_embeddings = nn.Embedding(max_position_embeddings,
> 118 hidden_size)
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/nn/layer/common.py in **init**(self, num_embeddings, embedding_dim, padding_idx, sparse, weight_attr, name)
> 1348 self._remote_prefetch = False
> 1349 self._name = name
> -> 1350 self.weight = self.create_parameter(
> 1351 attr=self._weight_attr,
> 1352 shape=self._size,
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py in create_parameter(self, shape, attr, dtype, is_bias, default_initializer)
> 405 if isinstance(temp_attr, six.string_types) and temp_attr == "":
> 406 temp_attr = None
> --> 407 return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
> 408 default_initializer)
> 409
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py in create_parameter(self, attr, shape, dtype, is_bias, default_initializer, stop_gradient, type)
> 365 "Please check the parameter attr value passed to self.create_parameter or "
> 366 "constructor of dygraph Layers".format(attr.name))
> --> 367 return self.main_program.global_block().create_parameter(
> 368 dtype=dtype,
> 369 shape=shape,
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py in create_parameter(self, *args, **kwargs)
> 2982 pass
> 2983 else:
> -> 2984 initializer(param, self)
> 2985 return param
> 2986
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/initializer.py in **call**(self, var, block)
> 555 if self._uniform:
> 556 limit = np.sqrt(6.0 / float(fan_in + fan_out))
> --> 557 op = block._prepend_op(
> 558 type="uniform_random",
> 559 inputs={},
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py in _prepend_op(self, *args, **kwargs)
> 3094 self, None, type=type, inputs=None, outputs=None, attrs=attrs)
> 3095
> -> 3096 _dygraph_tracer().trace_op(type,
> 3097 kwargs.get("inputs", {}),
> 3098 kwargs.get("outputs", {}), attrs
> 
> ~/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
> 41
> 42 def trace_op(self, type, inputs, outputs, attrs, stop_gradient=False):
> ---> 43 self.trace(type, inputs, outputs, attrs,
> 44 framework._current_expected_place(), self._has_grad and
> 45 not stop_gradient)
> 
> OSError: (External) Cudnn error, CUDNN_STATUS_INTERNAL_ERROR (at /paddle/paddle/fluid/platform/device_context.h:255)
> [operator < uniform_random > error]
> 
> 不知道是不是因为加载模型时显存不够，如果是的话，我要怎么指定加载到哪张卡里。

请问paddlenlp是哪个版本呢？
指定GPU可以在运行python程序前设置环境变量进行设置：export CUDA_VISIBLE_DEVICES=0

**Comment by wht0948** [comment]
感谢您的回复，我之前的服务器好像不能指定使用第几张卡，我把0号卡的显存清空了就加载成功了，现在遇到了另一个问题，我在另一台服务器上安装paddle时  !python -m pip install paddlepaddle-gpu==2.0.1 -i https://mirror.baidu.com/pypi/simple 遇到了一个报错
Collecting decorator (from paddlepaddle-gpu==2.0.1)
  Downloading https://mirror.baidu.com/pypi/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n8VoXg/decorator/setup.py", line 4, in <module>
        exec(open('src/decorator.py').read(), dic)  # extract the __version__
      File "<string>", line 162
        print('Error in generated code:', file=sys.stderr)
                                              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n8VoXg/decorator/

这个要怎么解决？

**Comment by xiemoyuan** [comment]
> 感谢您的回复，我之前的服务器好像不能指定使用第几张卡，我把0号卡的显存清空了就加载成功了，现在遇到了另一个问题，我在另一台服务器上安装paddle时 !python -m pip install paddlepaddle-gpu==2.0.1 -i https://mirror.baidu.com/pypi/simple 遇到了一个报错
> Collecting decorator (from paddlepaddle-gpu==2.0.1)
> Downloading https://mirror.baidu.com/pypi/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "", line 1, in
> File "/tmp/pip-build-n8VoXg/decorator/setup.py", line 4, in
> exec(open('src/decorator.py').read(), dic) # extract the **version**
> File "", line 162
> print('Error in generated code:', file=sys.stderr)
> ^
> SyntaxError: invalid syntax
> 
> ```
> ----------------------------------------
> ```
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n8VoXg/decorator/
> 
> 这个要怎么解决？

安装paddle请参考 https://www.paddlepaddle.org.cn/install/quick ，选择相应的操作系统以及cuda版本等选项，按给定的安装命令再尝试一下。
