### ISSUE TITLE
RocketQA在CPU上 预测速度慢

### ISSUE THREAD

**Issue by zhaoyiyong** [PaddlePaddle/PaddleNLP#2271]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
 paddle版本2.2.2 paddlenlp 2.2.4，Rocketqa 加faiss
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
我使用的环境是在centos 7.8服务器上，python 3.7
A、）问题就是推理速度太慢，无法使用。下面是我做的测试，大概一次推理就要13s，而且是单一请求的。
“”“
(paddle_env) [eyundl@eyun98 faiss_example]$ date
2022年 05月 20日 星期五 14:20:32 CST
(paddle_env) [eyundl@eyun98 faiss_example]$ curl -i -X POST -H "'Content-type':'application/json'" -d '{"query":"网点在哪里","topk":3}' http://192.168.0.98:8889/rocketqa
{"error_code": 0, "error_message": "", "answer": [{"probability": 0.5840879678726196, "title": "如何查询网点信息", "para": "<p>您可登陆我行官网，点击页面底部“网点及ATM”，查询指定地区的营业网点、自助银行及ATM的地址、电话、营业时间等信息。此外，您也可以通过我行手机银行查询网点信息。</p>"}, {"probability": 5.298304313328117e-05, "title": "如何查询银行卡开户行", "para": "<p>查询本人储蓄账户开户行，您可关注“客户服务”官方微信，通过“信息查询—开户行查询”菜单查询。</p><p>我行客服提示您，以上方式需验证开户预留手机号，如操作不成功，您还可编辑手机短信“khcx#账户全账号”发送至XXXXX查询本人开户行。</p><p><br/></p>"}, {"probability": 5.279778633848764e-05, "title": "如何查询储蓄卡账户明细", "para": "<p>1、登录我行官网首页，在轮播广告栏下点击“账户查询”的“马上查询”按钮，选择“储蓄账户查询—马上查询”，输入卡号/存折号、查询密码等进行查询。</p><p><br/></p><p>2、请登录个人网银，通过“我的账户—账户查询”菜单，点击“明细”查询。</p><p><br/></p>"}]}(paddle_env) [eyundl@eyun98 faiss_example]$ date
2022年 05月 20日 星期五 14:20:43 CST
”“”
B、）我使用的是duread-encode，我看模型不是常用的扩展名是.pdparams的文件，而是在目录下很多文件，像是中间的模型文件。

**Comment by tianxin1860** [comment]
你好，cpu 版本预测速度慢符合预期，cpu 上的预测加速需求我们已经纳入研发计划了，欢迎关注。
