### ISSUE TITLE
duee事件抽取中数据集负例

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#2282]
您好，我知道在事件抽取的数据集中正例就是一个对句子标注好对应事件类型的论元的标注样本。但是我不知道事件抽取中数据集的一个负例是什么？

**Comment by LemonNoel** [comment]
负例即不包含任何事件类型的样本，也就是所有的标签都是O。

**Comment by Mnanazi** [comment]
那我在duee1.0句子事件抽取数据集中的训练集、验证集，貌似没发现不包含事件的句子样本，即负俐？都是包含事件的样本。请问，在duee的训练集、验证集中是确实没有负俐吗？

另外，为了评价duee1.0事件抽取系统的效果，应该要在测试集中专门放入负俐吧？因为这样有计算精确率P的伪正例TP。请问，在测试集中是否要放入负俐，以使有TP来计算精确率P？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月23日 11:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] duee事件抽取中数据集负例 (Issue #2282) |

负例即不包含任何事件类型的样本，也就是所有的标签都是O。

**Comment by LemonNoel** [comment]
duee 1.0数据集中没有样本级别的负例，这里和上边讨论的“负例”定义其实是来自[DuEE-fin数据集的介绍](https://aistudio.baidu.com/aistudio/competition/detail/65/0/task-definition)，即：
```
DuEE-fin是百度最新发布的金融领域篇章级事件抽取数据集，包含13个事件类型的1.17万个篇章，同时存在部分非目标篇章作为负样例。
```
从事件抽取任务的角度看，它本质上是token级别的多分类任务，而多分类任务本身是没有负例的概念的。或者可以理解为当前类型的标注文本为正例，而其他的非当前类型或者非准确标注文本为负例。

**Comment by Mnanazi** [comment]
多谢答复













在 2022-05-23 17:32:28，"Noel" ***@***.***> 写道：

duee 1.0数据集中没有样本级别的负例，这里和上边讨论的“负例”定义其实是来自DuEE-fin数据集的介绍，即：

DuEE-fin是百度最新发布的金融领域篇章级事件抽取数据集，包含13个事件类型的1.17万个篇章，同时存在部分非目标篇章作为负样例。


从事件抽取任务的角度看，它本质上是token级别的多分类任务，而多分类任务本身是没有负例的概念的。或者可以理解为当前类型的标注文本为正例，而其他的非当前类型或者非准确标注文本为负例。
