### ISSUE TITLE
多卡多进程训练时，_get_sub_home (paddlenlp/utils/env.py)函数存在竞争导致失败

### ISSUE THREAD

**Issue by sandyhouse** [PaddlePaddle/PaddleNLP#2284]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，PaddleNLP develop，PaddlePaddle develop
2）系统环境：请您描述系统类型，Linux，python版本: 3.7
- 复现信息：如为报错，请给出复现环境、复现步骤

训练模型：gpt-3/static/gpt2-medium-en

报错信息：
<img width="989" alt="image" src="https://user-images.githubusercontent.com/6737864/169742033-863ac93d-0cd3-4c9a-9914-e686302de3c2.png">

<img width="497" alt="image" src="https://user-images.githubusercontent.com/6737864/169742233-adc9cea2-10b0-4f10-8276-b808d0409693.png">
如上图所示，初步定位是没有处理进程竞争；例如，当进程1和进程2同时进入``if not os.path.exists(home):``条件，其中一个进程先执行目录创建，另一个进程再创建时失败，

**Comment by ZHUI** [comment]
可以这样，启动多卡训练脚本之前，先import paddlenlp一次，这个只初始化一次
```shell
python -c "import paddlenlp"
```
