### ISSUE TITLE
doccano上传文件后，页面一直转圈圈

### ISSUE THREAD

**Issue by jerryxu010** [PaddlePaddle/PaddleNLP#2287]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by jerryxu010** [comment]
PaddleNLP2.3.1,paddle2.3.0

> 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
>   2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
> * 复现信息：如为报错，请给出复现环境、复现步骤

PaddleNLP2.3.1,paddle2.3.0

**Comment by LemonNoel** [comment]
方便看下doccano页面的截图吗？这种情况一般是文件类型选择错误，文件类型请选择TextLine，准备的数据文件格式为.txt，每条文本数据占一行。

**Comment by ttyuuuuuuuuuu** [comment]
![image](https://user-images.githubusercontent.com/51437324/169788621-688b4657-8171-4b7f-8ac4-4831c51c15ed.png)

**Comment by linjieccc** [comment]
> ![image](https://user-images.githubusercontent.com/51437324/169788621-688b4657-8171-4b7f-8ac4-4831c51c15ed.png)

你好，出现文件一直在上传的状态可能是在doccano任务初始化的时候少了以下步骤：

![image](https://user-images.githubusercontent.com/40840292/169814396-7d299983-8dbc-43a4-b2a7-115d70a30448.png)

**Comment by jerryxu010** [comment]
是的，再开一个命令行，命令doccano task 搞定了。

**Comment by ZhangYH321** [comment]
您好，我使用doccano时，一直无法上传relation的标签信息
![image](https://user-images.githubusercontent.com/59766081/171633961-d39418e7-62f6-4d34-b72a-d5c494c9e834.png)
actions就一直上传不了

**Comment by hopegithub** [comment]
还要关闭防火墙，防火墙阻止访问
