### ISSUE TITLE
一直报operator < load_combine > error

### ISSUE THREAD

**Issue by yeahyeahcc** [PaddlePaddle/PaddleNLP#2294]
paddlenlp 2.3.1
paddlepaddle-gpu 2.3.0
windows python=3.7
![image](https://user-images.githubusercontent.com/87855208/169887048-39f389d5-7b5c-4617-9e8e-7b8bcfe83618.png)
尝试运行实体抽取，一直失败，如果pip install paddlepaddle-core
![image](https://user-images.githubusercontent.com/87855208/169887263-b29b8e6e-ebb9-42f6-8864-9c97e61abe41.png)

**Comment by wawltor** [comment]
1. 首先吧 ~/.paddlenlp目录删除
2. check 内存是否足够，一版需要6G内存是否足够

**Comment by wawltor** [comment]
问题通过删除 ~/.paddlenlp 解决问题

**Comment by yeahyeahcc** [comment]
解决了，感谢！

**Comment by yeahyeahcc** [comment]
> 

解决了，感谢！
