### ISSUE TITLE
能提供一下UIE同时对文本进行实体抽取和关系抽取的定制示例吗

### ISSUE THREAD

**Issue by nlper-77** [PaddlePaddle/PaddleNLP#2295]

**Comment by wawltor** [comment]
是说要微调吗？

**Comment by nlper-77** [comment]
嗯嗯 是的

**Comment by wawltor** [comment]
> 嗯嗯 是的

只要标注数据没有问题(同时标注实体和关系)，我们在UIE的文档中提供微调示例，是可以直接进行微调的https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by nlper-77** [comment]
嗯嗯 谢谢 我参考着关系抽取的标注示例，做了标注已经跑通，效果确实还可以
