### ISSUE TITLE
Ernie 3.0 zh可以提供Config和Vocab文件吗？

### ISSUE THREAD

**Issue by Davion-Liu** [PaddlePaddle/PaddleNLP#2300]
您好，我希望使用Ernie 3.0 zh的 config以及Vocab文件做一些初始化工作，请问相关文件和Ernie 1.0一样吗？
如果不是，请问可以提供吗？

**Comment by ZeyuChen** [comment]
可否更具体一点说一下是哪些初始化工作呢？格式应该和ERNIE 1.0一样的。
