### ISSUE TITLE
doccano_ext.json中的entities的id是怎么得来的，会影响doccano.py的运行结果吗

### ISSUE THREAD

**Issue by ttyuuuuuuuuuu** [PaddlePaddle/PaddleNLP#2301]
是这样的，我想用uie的模型对ccks的比赛数据（train.json，图右侧）做一个评估，想看下效果。我的切入点是把train.json的格式转为doccano_ext.json（图左侧）。

（1）看到doccano_ext.json第一条数据，我以为entities的id是针对text从0开始计数：
![微信截图_20220524174008](https://user-images.githubusercontent.com/51437324/170018101-e364fdcf-015e-4f60-80c7-7f2caf5c611b.png)

（2）但是第二、三、四。。条标注数据的entities id不是从0开始的，而且好像在递增：
![image](https://user-images.githubusercontent.com/51437324/170018560-9e13e75d-5b95-4c14-b12e-4e714eaa2821.png)

（3）但是我发现对于“目的地”这个label来说，他的entity id有时候是一样的，有时候又是不一样的：
![image](https://user-images.githubusercontent.com/51437324/170018870-76f1eb3a-6f86-485b-87e4-23dc1c22a93d.png)

如果这个entity id的重要性是会影响到标注数据到训练数据的转换过程（doccano.py）的话，还麻烦大佬帮忙解答下orz......

**Comment by linjieccc** [comment]
这个entity id是对不同实体的唯一标识，目的地这个label，例如『上海』和『北京』分别对应一个唯一的entity_id，所以才会有entity id有时候是一样的，有时候又是不一样的这种情况哈

**Comment by ttyuuuuuuuuuu** [comment]
新的一天新的问题~

（1）事件抽取的数据一般有以下几种情况：
a. 一条text中只包括一个事件类型
![image](https://user-images.githubusercontent.com/51437324/170171935-93675f33-c7f3-4909-af97-07f7d4d2d27e.png)

b. 一条text包括多个事件类型，事件类型不同
![image](https://user-images.githubusercontent.com/51437324/170172218-111a3892-9441-4e9c-841c-dbf9c5689c71.png)

c. 一条text包括多个事件类型，且部分事件类型相同
![image](https://user-images.githubusercontent.com/51437324/170171664-fa9a30d1-78fd-42c9-aa42-a482897d557c.png)


从doccano_ext.json中还看不出多个事件类型，咱们目前的事件抽取是不是暂时还没有考虑到多个事件类型的情况？

（2）doccano_ext.json数据是用来做事件抽取的，但从doccano标注工具导出的结果（doccano_ext.json）中只看得出text中存在哪些实体，没有看到事件抽取相关的“事件类型”，咱们是如何仅根据事件中存在的实体去做事件抽取呢？
![image](https://user-images.githubusercontent.com/51437324/170170879-4868a825-9e92-41ee-827f-f219cf54cb03.png)

**Comment by laosuan** [comment]
同问，请问有转换格式的工具吗
