### ISSUE TITLE
NER任务：doccano.py和utils.py在处理验证集时会导致验证集中无实体的样本被剔除，可能影响真实验证效果

### ISSUE THREAD

**Issue by CodeFrontWang** [PaddlePaddle/PaddleNLP#2302]
NER任务中，doccano.py在将数据集添加负样本时，会跳过数据集中无实体的样本，这个步骤会被用到验证集的分割转换中，导致验证集中的无实体样本被跳过，可能无法得到有效的验证。
![8c61b25a70aa236b1b216b856e01019](https://user-images.githubusercontent.com/88528512/170022101-b465e7a6-fdaf-42b3-b14b-e0896f68d207.jpg)

**Comment by linjieccc** [comment]
@CodeFrontWang 感谢反馈，修复PR已合入#2304
