### ISSUE TITLE
无法固定复现的few-shot/p-tuning效果，随机种子已固定

### ISSUE THREAD

**Issue by Armorhtk** [PaddlePaddle/PaddleNLP#2303]
1）版本、环境信息
- PaddleNLP 2.2.6
- PaddlePaddle-gpu 2.2.2
2）系统环境
windows10，CUDA 11.0  Python3.8
3）复现信息
您好，在复现[examples\few_shot\p-tuning](https://github.com/PaddlePaddle/PaddleNLP/tree/61685f0e5013d58e26162c23d11e9c234e859467/examples/few_shot/p-tuning)的代码过程，根据README.md要求在Terminal中成功运行了训练&评估代码，如下：
`python -u -m paddle.distributed.launch --gpus "0" ptuning.py --task_name "tnews" --device gpu --save_dir "checkpoints" --batch_size 32 --learning_rate 5E-5 --epochs 10 --max_seq_length 128 --rdrop_coef 0 
`
发现在验证和测试阶段会出现不同的答案，如图所示，验证和测试分数有这明显差异
![image](https://user-images.githubusercontent.com/68628239/170041954-63b890a4-35f9-4e55-b271-b525aed6cd0c.png)
![image](https://user-images.githubusercontent.com/68628239/170042033-ad5734ae-a0d8-47d9-b5ae-b65b57492084.png)
随后我检查了代码中的随机种子，和model.eval()，代码并无缺失可正常运行。
通过排查发现在train阶段模型能够参数能被固定，但在传入验证和测试阶段时，模型每一次得到的参数都不一样，请问这有可能是什么造成的，如何解决呢？

**Comment by Armorhtk** [comment]
使用AI Studio运行也发现了同样的问题，在固定随机种子和开启model.eval()的情况下，使用原始example运行两次，得到的结果并不一致，如下：
![image](https://user-images.githubusercontent.com/68628239/170061210-0dcf6919-a4df-4d59-a348-a86e5e6d80f9.png)
![image](https://user-images.githubusercontent.com/68628239/170061409-e46fa036-fa74-4526-8f8b-8dfc99e7fcc5.png)

**Comment by tianxin1860** [comment]
是说多次训练得到的验证集指标不一致么？

**Comment by Armorhtk** [comment]
> 是说多次训练得到的验证集指标不一致么？

不是多次训练，是指每次从零开始训练得到的验证集指标不一致，无法复现同一个随机种子下的结果。
在运行其他paddle提供的few-shot代码（如EFL）时，每次从零开始训练可以得到一样的验证集复现指标，但是p-tuning的代码不行。
