### ISSUE TITLE
搭建semantic-search，启动RestAPI模型服务，出现问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleNLP#2305]
python rest_api/application.py 8891

Exception: Failed loading pipeline component 'Retriever': Failed loading pipeline component 'DocumentStore': Initial connection to Elasticsearch failed. Make sure you run an Elasticsearch instance at `[{'host': 'localhost', 'port': 9200}]` and that it has finished the initial ramp up (can take > 30s).

**Comment by tianxin1860** [comment]
你好，看起来是 ElasticSearch 服务没有正常启动，请先检查下 ElasticSearch 是否正常安装并成功启动？

**Comment by tianxin1860** [comment]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/6829601/170194520-fcd14e7c-097d-4c8c-b525-a9a8b005e635.png">

**Comment by xialei2821212670** [comment]
> 检查下 ElasticSearch 是否正常安装并成功启动
我用的是7.13.2
![image](https://user-images.githubusercontent.com/57654726/170194734-ce884ed6-9384-4854-b5c2-8fc8b19ac2aa.png)
，我尝试跟换下版本

**Comment by tianxin1860** [comment]
另外，检查下，这些依赖都安装成功了么？
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/6829601/170196821-fa80c056-ceef-4f58-82eb-0adc406b7808.png">

**Comment by xialei2821212670** [comment]
export CUDA_VISIBLE_DEVICES=0
python examples/semantic-search/semantic_search_example.py --device cpu
![image](https://user-images.githubusercontent.com/57654726/170517099-133a3f47-d9ea-4a22-ac59-8b1ca65bee75.png)

**Comment by tianxin1860** [comment]
如果基于 CPU 执行的话，不需要执行 `export CUDA_VISIBLE_DEVICES=0`, 这句命令是为 GPU 执行配置 GPU 卡号的。
