### ISSUE TITLE
DuEE可用于英文文本事件抽取吗，如果可用，修改源代码中的哪些部分就可以了呢

### ISSUE THREAD

**Issue by greattang123** [PaddlePaddle/PaddleNLP#2306]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by guoshengCS** [comment]
当前的DuEE代码不能直接用于英文，其中使用的预训练模型ernie-1.0-base-zh是中文的。需要将模型换成英文的预训练模型，另外数据处理部分应该也需要调整下按照你那边的数据来。也请 @LemonNoel 帮忙看下

**Comment by greattang123** [comment]
我这边数据格式调成和DuEE一样了，但不知道如何修改预处理代码，如何更换预训练模型。真诚希望您能指导一下

**Comment by greattang123** [comment]
> 当前的DuEE代码不能直接用于英文，其中使用的预训练模型ernie-1.0-base-zh是中文的。需要将模型换成英文的预训练模型，另外数据处理部分应该也需要调整下按照你那边的数据来。也请 @LemonNoel 帮忙看下

我这边数据格式调成和DuEE一样了，但不知道如何修改预处理代码，如何更换预训练模型。真诚希望您能指导一下

**Comment by greattang123** [comment]
> 当前的DuEE代码不能直接用于英文，其中使用的预训练模型ernie-1.0-base-zh是中文的。需要将模型换成英文的预训练模型，另外数据处理部分应该也需要调整下按照你那边的数据来。也请 @LemonNoel 帮忙看下

谢谢您的回复。我这边数据（英文）格式调成和DuEE一样了，但不知道如何修改预处理代码，如何更换预训练模型。真诚希望您能指导一下

**Comment by LemonNoel** [comment]
可以将代码中中文相关的逻辑替换掉，例如在duee_1_data_prepare.py第38行中文分隔符可以换为英文","，sequence_labeling.py文件中第144和147行是分词器和模型的加载，"ernie-1.0"是中文模型，可以替换为英文预训练模型，具体模型名可以在[ernie](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L163-L175)目录下查看，``en``结尾的是英文模型。

**Comment by greattang123** [comment]
> 可以将代码中中文相关的逻辑替换掉，例如在duee_1_data_prepare.py第38行中文分隔符可以换为英文","，sequence_labeling.py文件中第144和147行是分词器和模型的加载，"ernie-1.0"是中文模型，可以替换为英文预训练模型，具体模型名可以在[ernie](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L163-L175)目录下查看，`en`结尾的是英文模型。

谢谢您，我试试

**Comment by terry** [comment]
> > 可以将代码中中文相关的逻辑替换掉，例如在duee_1_data_prepare.py第38行中文分隔符可以换为英文","，sequence_labeling.py文件中第144和147行是分词器和模型的加载，"ernie-1.0"是中文模型，可以替换为英文预训练模型，具体模型名可以在[ernie](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L163-L175)目录下查看，`en`结尾的是英文模型。
> 
> 谢谢您，我试试

请问这个部分测试成功了否？
