### ISSUE TITLE
faq_finance保险问答未提供处理后的数据集

### ISSUE THREAD

**Issue by yaleimeng** [PaddlePaddle/PaddleNLP#2308]
页面上只提供了原始数据集的下载链接。代码不能直接跑起来。
将政务问答的数据集挪过来用，又提示缺少train_aug.csv。如果就用train.csv代替，则模型训练感觉不太正常。在checkpoints/下仅生成了model0的模型。而不像政务问答那样会每训练50步保存一次，根据batch_size不同，会训练200~400步左右。
奇怪的是，就使用得到的model0进行build_index和evaluate，成绩也跟政务问答差不多，大概是82、94、96。
总之希望还是提供能直接运行代码的数据集，便于验证代码是否正常运行。

**Comment by w5688414** [comment]
您好，数据集由于没有license，不方便开源，这里有aistudio链接有相关的数据，可以参考：

https://aistudio.baidu.com/aistudio/projectdetail/3882519
