### ISSUE TITLE
事件抽取的结果是实体，怎么组合成事件

### ISSUE THREAD

**Issue by ttyuuuuuuuuuu** [PaddlePaddle/PaddleNLP#2316]
你好，我用taskflow对一个text进行事件抽取，但是抽取返回的结果看上去像是实体抽取结果：
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/51437324/170295629-01b59025-914d-46eb-afe4-0ef673c32b82.png">
想请教下这样的返回是如何跟 “事件抽取：是要抽取出事件” 联系起来，如何将这抽取到的实体组合成事件呢？

**Comment by guoshengCS** [comment]
事件抽取的话schema需要类似这种，需要组织成dict结构并将事件类别触发词作为key，事件要素作为作为value，这样抽取出来的结构也会是和这个一样的事件结构
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/14105589/170321901-88a9f6d9-a9b8-48d6-9def-0f24c518ea4b.png">

我这边试了下这样的schema，得到的结果如下

```
schema = {"战争触发词": ["发动方", "地点", "时间", "目标"]}
ie = Taskflow('information_extraction', schema=schema)
ie.set_schema(schema)
pprint(ie("阿利伯克号与2014年9月23日，在红海航行期间，向伊拉克伊斯兰国目标发射了战斧巡航导弹，实施打击。"))
```
<img width="798" alt="image" src="https://user-images.githubusercontent.com/14105589/170326473-ce8b7833-0577-485e-a97f-15ca56aec0f5.png">

也请 @wawltor 再确认下这个

**Comment by ttyuuuuuuuuuu** [comment]
但是对于一段”不确认是否包含事件“的text，想对其进行事件抽取，那么如何做到根据抽取出来的词，组织成一句连贯的时间表达？是否有什么类似”拼接规则“的东西？
