### ISSUE TITLE
cudnn版本问题

### ISSUE THREAD

**Issue by zhangyan-833** [PaddlePaddle/PaddleNLP#232]
![image](https://user-images.githubusercontent.com/57338670/113818431-561e6880-97aa-11eb-99d2-c8f83b96d06c.png)

cudnn安装了7.6，但是说我的cudnn是5.0，有冲突，这要怎么解决

**Comment by ZeyuChen** [comment]
升级cudnn至7+版本以上，建议使用conda方式安装，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/linux-conda.html
conda创建独立环境安装conda会根据cuda版本自动适配最佳的cudnn环境。

**Comment by ZeyuChen** [comment]
同时也检查下cudnn的环境变量设置是否有误。

**Comment by zhangyan-833** [comment]
谢谢，已解决！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] cudnn版本问题 (#232)





 
同时也检查下cudnn的环境变量设置是否有误。

**Comment by ZeyuChen** [comment]
Issues solved.
