### ISSUE TITLE
TaskFlow使用batch size提速不明显

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/PaddleNLP#2321]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，

使用的 docker安装，：paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8

paddle-bfloat         0.1.2
paddle2onnx           0.9.6
paddlefsl             1.1.0
paddlenlp             2.3.1
paddleocr             2.5.0.3
paddlepaddle-gpu      2.3.0.post112

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

使用 batch size参数，从默认的（默认的是多少？）到设置为140，显存能观察到占用的增加了，但是预测速度几乎没有提升。

```python
 Taskflow('information_extraction', schema=schema, batch_size=140)
```

请问会有哪些原因导致的？

**Comment by wawltor** [comment]
想问一下，输入的是一个list还是一行文本了？

**Comment by aixuedegege** [comment]
输入是list，其中有100个元素

**Comment by wawltor** [comment]
> 输入是list，其中有100个元素

这块可能要再等等我们，我们马上发出一个CPU性能优化的版本

**Comment by aixuedegege** [comment]
有gpu优化的吗

**Comment by wawltor** [comment]
> 有gpu优化的吗

有的，有半精度预测会提升很多

**Comment by aixuedegege** [comment]
taskflow可以设置半精度预测么

**Comment by wawltor** [comment]
> taskflow可以设置半精度预测么

这个功能还在集成开发中
