### ISSUE TITLE
UIE是否支持事件抽取的finetune？若支持，要求的标注数据格式是什么样的？

### ISSUE THREAD

**Issue by thupx** [PaddlePaddle/PaddleNLP#2324]
已经尝试过UIE对NER的finetune，想请问一下是否支持事件抽取的finetune？
如果支持的话，应该提供什么格式的标注数据？试用了一下doccano，好像不支持标注事件？

**Comment by wawltor** [comment]
可以支持的，具体看文档 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md 
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/16698950/170436260-555a8d3f-d728-4eaa-9ba4-27e5611bb985.png">

**Comment by thupx** [comment]
> 可以支持的，具体看文档 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md
> <img alt="image" width="1117" src="https://user-images.githubusercontent.com/16698950/170436260-555a8d3f-d728-4eaa-9ba4-27e5611bb985.png">

谢谢，已成功标注了。

出现了新的问题，导出JSON(relation)格式数据后，运用
`python doccano.py --doccano_file ./data/admin.json --task_type 'ext' --save_dir ./data --negative_ratio 5`
生成`train.txt`、`dev.txt`、`test.txt`，再进行训练的时候load数据就报错了，
![image](https://user-images.githubusercontent.com/16662071/170471259-97aaff11-4010-45ab-ac02-c520e7ea6564.png)

直接用python检查了`train.txt`的内容，能用`json.loads`正常读取成dict格式。

**Comment by wawltor** [comment]
这块您使用一下最新的脚本，这个问题解决了

**Comment by thupx** [comment]
> 这块您使用一下最新的脚本，这个问题解决了

问题已解决，能够正常finetune了，感谢回复。

**Comment by MachineSheep** [comment]
你好你好，UIE事件抽取模型输入的数据格式是什么样的呢？
