### ISSUE TITLE
ernie_csc纠错

### ISSUE THREAD

**Issue by you567** [PaddlePaddle/PaddleNLP#2325]
您好，有2个问题请教下：
1.在尝试运行开源代码复现结果后，在Automatic Corpus Generation生成的中文纠错数据集以及SIGHAN数据集上训练 11epoch的score如下图所示，结果与官方相差比较大，这个正常吗？是不是学习率过低导致导致的啊？收敛曲线如下图
（我训练参数如下，前3个epoch  max_seq_length =128(没注意)，
由于机器显存只有11G，我把参数设置了batch_size =8，learning_rate= 1.25e-5 ）

python train.py --batch_size 8 --logging_steps 100 --epochs 11 --learning_rate  1.25e-5 --model_name_or_path ernie-1.0 --output_dir ./checkpoints/ --extra_train_ds_dir ./extra_train_ds/ --max_seq_length 192

2.能否在ernie_csc中将ernie3.0替换ernie1.0进行纠错
<img width="320" alt="0-10" src="https://user-images.githubusercontent.com/35205404/170430943-8f4cd123-35c0-4b7c-8d94-ff61ec2cdcc8.png">
<img width="1035" alt="157f8ca49da53ac661095ab307fdfd3" src="https://user-images.githubusercontent.com/35205404/170430960-206726c6-b2a8-4487-9d11-733a171bfc7f.png">

**Comment by wawltor** [comment]
1） 可能是学习率低导致的
2）可以换成ERNIE 3.0来切换模型

**Comment by you567** [comment]
好的，谢谢！还想再问下：
1.如果我在batch_size=8的情况下，使用官方原来的learning_rate= 5e-5 可以吗？或者我可以在learning_rate= 1.25e-5的情况下多训练几个epoch?
2.如果切换成ERNIE 3.0对于ernie_csc项目来说的话，是不是只要把模型加载改成ernie3.0，其他的地方不需要修改了？

**Comment by ZeyuChen** [comment]
@you567 是的 不过最佳学习率你可能需要试一下，理论上是会比ernie 1.0有所提升

**Comment by you567** [comment]
好的，谢谢
