### ISSUE TITLE
UIE评论抽取中情感倾向的标注方式？

### ISSUE THREAD

**Issue by JaheimLee** [PaddlePaddle/PaddleNLP#2326]
如题，观点词的情感倾向是作为关系类别与评价维度进行连接的，还是作为实体类别单独对观点词进行标注的？

**Comment by wawltor** [comment]
您好，观点词的情感倾向没有还没有开发出来，下周我们会放出一个版本
我们另外一个工具也可以进行情感分析，具体可以看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis
