### ISSUE TITLE
ERNIE 3.0 有英文版本吗？

### ISSUE THREAD

**Issue by mingwei-liu** [PaddlePaddle/PaddleNLP#2328]
1. 你好，请问ERNIE 3.0有英文版本的模型吗，或者是跨语言的模型（即同时支持中文英文的预训练模型）？因为目前我的文本很多是英文或者中英混杂的。
2. 或者之前的版本的模型有支持英文或者跨语言的吗？
3. 目前我有一个特定领域的知识图谱，有什么办法让预训练模型ERNIE继续训练将知识图谱中的三元组知识吸收进去？

**Comment by wawltor** [comment]
1. 目前ERNIE 3.0没有开源英文模型，但是可以使用我们的ERNIE-M多语言模型的
2. 多语言模型的链接见 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-m 
3. 你可以尝试使用KG-BERT  https://arxiv.org/abs/1909.03193 论文来组织样本，预训练的方式可以看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0

**Comment by mingwei-liu** [comment]
非常感谢！
