### ISSUE TITLE
ERNIE 3.0未使用 transformer-XL效果是否有影响？

### ISSUE THREAD

**Issue by yang9112** [PaddlePaddle/PaddleNLP#2330]
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.1
2）系统环境：Linux，python3.7

3）验证过程
1. 为了快速验证下 ERNIE 在现有生产上的效果，而生产系统使用的是 pytorch。
2. 通过参数映射，将 ernie-3.0参数映射到 BERT 的结构中，进行模型训练。
3. 效果无法复现 2021年 ERNIE 3.0中阐述的效果，比如 Cluener 上只能达到80.86左右，但是论文中可以提高至81.2+
4. 在个别数据集上，比如 CCKS2019-TASK1，ERNIE 3.0效果只有不到0.75，而 RoBERTa 能达到0.8+【暂不确定是否是模型训练的问题，待进一步验证】

4）我的问题
目前提供的导入 ERNIE3.0的方式是通过`AutoModelForTokenClassification`进行导入，那么使用的应该还是 ERNIE 2.0的结构，而21年发表的论文中阐述 ERNIE 3.0使用的是 transformer-XL，而最新的 ERNIE 3.0参数中默认支持的文本也是2048的长度。那么显然如果要支持超过512长度的话，应该是需要支持 transformer-XL。

那么是否是因为使用 transformer结构导入 ERNIE3.0对效果产生的影响呢？这块是否有什么建议？

**Comment by wawltor** [comment]
ERNIE 3.0 transformer-XL结构是一个千亿大模型，考虑到大家的使用成本，目前开源的ERNIE 3.0的版本是在千亿大模型蒸馏出来的，效果方向我们做了优化，我们开源的ERNIE 3.0的模型还是比较突出的，具体的对比效果可以见  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0
