### ISSUE TITLE
bug in paddlenlp/transformers/tokenizer_utils.py

### ISSUE THREAD

**Issue by bigbrother666sh** [PaddlePaddle/PaddleNLP#2331]
paddlenlp/transformers/tokenizer_utils.py
中 [954行](https://github.com/PaddlePaddle/PaddleNLP/blob/7c3a7e4e3b01f72b590f862def7b749af6d8fd3b/paddlenlp/transformers/tokenizer_utils.py#:~:text=self.-,build_inputs_with_special_tokens,-(token_ids_0%2C )

和

[1201行](https://github.com/PaddlePaddle/PaddleNLP/blob/7c3a7e4e3b01f72b590f862def7b749af6d8fd3b/paddlenlp/transformers/tokenizer_utils.py#:~:text=%3D%20self.-,build_inputs_with_special_tokens,-( )

分别引用了build_inputs_with_special_tokens函数，但这个函数在2.3的tokenizer_utils.py已经被删除……

**Comment by wawltor** [comment]
收到，我看看这个问题，谢谢反馈！

**Comment by yingyibiao** [comment]
我们将 build_inputs_with_special_tokens 函数挪到 tokenizer_utils_base.py 文件下了，具体可见：https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.3/paddlenlp/transformers/tokenizer_utils_base.py#L2620

**Comment by bigbrother666sh** [comment]
> 我们将 build_inputs_with_special_tokens 函数挪到 tokenizer_utils_base.py 文件下了，具体可见：https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.3/paddlenlp/transformers/tokenizer_utils_base.py#L2620

看到了，原来是继承……
