### ISSUE TITLE
cuda一来问题。

### ISSUE THREAD

**Issue by charlesfufu** [PaddlePaddle/PaddleNLP#2335]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

为什么会缺少以来libcudnn.so和libcublas.so文件？后面优化难道不会把这些依赖包整合到安装文件里面吗？

**Comment by wawltor** [comment]
您好，建议您使用conda来装Paddle，具体的方式  https://www.paddlepaddle.org.cn/
 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/16698950/170496175-853f6618-efce-49d2-8778-462bb334aa73.png">
