### ISSUE TITLE
ERNIE 3.0模型的分类任务模型的压缩和部署中compress_seq_cls文件有不清楚的地方

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2338]
1.utils这些参数是什么？
![图片](https://user-images.githubusercontent.com/88191580/170669876-29c42919-2258-4f16-acf9-62d0ed1cbe0e.png)

2.args是什么？加载我训练好的模型参数的吗？
![图片](https://user-images.githubusercontent.com/88191580/170666386-887a7bcd-24be-4891-9cbd-d172e49ba37b.png)
1.快速上手的法律分类案例上能不能增加压缩，部署的部分，当做教程
![图片](https://user-images.githubusercontent.com/88191580/170666679-47d2e0bf-39f0-4e81-b770-9b82c8dcdb68.png)

**Comment by 1649759610** [comment]
同学你好：
1. utils中的这些参数是对应的功能代码，可以参考文件：https://github.com/PaddlePaddle/PaddleNLP/blob/d405b2d85a5064bd4a10bdca56fc3a240a340a67/model_zoo/ernie-1.0/finetune/utils.py
2. args是训练时设定的参数，可以自定义设定这些参数。
3. 这个案例后续我们会考虑加上这些功能，敬请期待。

希望能够帮到你，使用过程中，有任何问题，欢迎与我们沟通。

**Comment by jiweizhangxu** [comment]
> 同学你好：
> 
>     1. utils中的这些参数是对应的功能代码，可以参考文件：https://github.com/PaddlePaddle/PaddleNLP/blob/d405b2d85a5064bd4a10bdca56fc3a240a340a67/model_zoo/ernie-1.0/finetune/utils.py
> 
>     2. args是训练时设定的参数，可以自定义设定这些参数。
> 
>     3. 这个案例后续我们会考虑加上这些功能，敬请期待。
> 
> 
> 希望能够帮到你，使用过程中，有任何问题，欢迎与我们沟通。

我还是压缩不了，我模型已经训练好，数据文件如下，现在该怎么进行压缩呢？readme的dataset也不知道里面是什么形式的，还有best_models/TNEWS也不知道里面是什么形式？
数据集：

![b9fed96ad2157331ccb11d9f6f3a4d2](https://user-images.githubusercontent.com/88191580/170926293-70fc1077-d309-4690-9b72-6e574480c863.png)

模型：
![c54ee756e85c8243c3765b73e490e8d](https://user-images.githubusercontent.com/88191580/170926303-533d1335-bdfb-4b8d-873a-9d7a155f740c.png)
尝试用命令行形式，它一直找不到tokenizer_config.json
![图片](https://user-images.githubusercontent.com/88191580/170926475-785af989-2455-4145-986d-fe834d9332a3.png)

**Comment by jiweizhangxu** [comment]
> 同学你好：
> 
>     1. utils中的这些参数是对应的功能代码，可以参考文件：https://github.com/PaddlePaddle/PaddleNLP/blob/d405b2d85a5064bd4a10bdca56fc3a240a340a67/model_zoo/ernie-1.0/finetune/utils.py
> 
>     2. args是训练时设定的参数，可以自定义设定这些参数。
> 
>     3. 这个案例后续我们会考虑加上这些功能，敬请期待。
> 
> 
> 希望能够帮到你，使用过程中，有任何问题，欢迎与我们沟通。

另外我尝试把out_dir写到utils里面，但是报错str类型冲突，但是我看文档里也是一个字符串啊？很奇怪
![图片](https://user-images.githubusercontent.com/88191580/170928855-4bd3521f-d85d-4a54-930e-074e48667877.png)

**Comment by LiuChiachi** [comment]
是分类任务吗？
使用自定义的数据集，
您可以创建一个tokenizer文件，

1.readme的dataset也不知道里面是什么形式的：
答：readme里的dataset是paddlenlp内置的CLUE分类数据集。您的数据是自定义数据，需要参考自定义数据集的读取方式，并且需要将数据集转换成类似下面的格式，即每条样本转成`input_ids`, 'token_type_ids`, `labels`为key的dict
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/26483581/170929470-dd777563-46b5-449f-bea6-e81ae1be7921.png">

2.还有best_models/TNEWS也不知道里面是什么形式？
这是您已经训好的模型的路径，里面 应该有model_state.pdparams, model_config.json, tokenier_config.json和vocab.txt

**Comment by jiweizhangxu** [comment]
> 
您说自己创建一个tokenizer文件，里面是什么样的呢？我该向里面写入什么？
您说参考自定义数据集的读取方式，并且需要将数据集转换成类似下面的格式，这个是模型中有现成可以使用的.py文件，还是要自己想？readme里好像也没有介绍自定义数据集的读取方式的地方呀？

**Comment by jiweizhangxu** [comment]
> 是分类任务吗？ 使用自定义的数据集， 您可以创建一个tokenizer文件，
> 
> 1.readme的dataset也不知道里面是什么形式的： 答：readme里的dataset是paddlenlp内置的CLUE分类数据集。您的数据是自定义数据，需要参考自定义数据集的读取方式，并且需要将数据集转换成类似下面的格式，即每条样本转成`input_ids`, 'token_type_ids`, `labels`为key的dict <img alt="image" width="1438" src="https://user-images.githubusercontent.com/26483581/170929470-dd777563-46b5-449f-bea6-e81ae1be7921.png">
> 
> 2.还有best_models/TNEWS也不知道里面是什么形式？ 这是您已经训好的模型的路径，里面 应该有model_state.pdparams, model_config.json, tokenier_config.json和vocab.txt

您说自己创建一个tokenizer文件，里面是什么样的呢？我该向里面写入什么？
您说参考自定义数据集的读取方式，并且需要将数据集转换成类似下面的格式，这个是模型中有现成可以使用的.py文件，还是要自己想？readme里好像也没有介绍自定义数据集的读取方式的地方呀？

**Comment by LiuChiachi** [comment]
tokenizer文件，您的模型目录应该已经具备了
<img width="316" alt="image" src="https://user-images.githubusercontent.com/26483581/171115845-5d254dd9-59d1-4ed4-9efa-64a4e4fad39f.png">

自定义数据集的读取，https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_load.html，可以参考这个文档
