### ISSUE TITLE
UIE能使用GPU推理吗？

### ISSUE THREAD

**Issue by Gavingx** [PaddlePaddle/PaddleNLP#2339]
1）PaddleNLP和PaddlePaddle版本：
     PaddleNLP 2.3.1，PaddlePaddle 2.3.0 paddlepaddle-gpu 2.3.0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
    系统： linux
    python：3.8

你好，我看taskflow源码里面is_compiled_with_cuda默认是False，是不能使用GPU推理么？

**Comment by 1649759610** [comment]
是的， 可以将is_compiled_with_cuda设置为True，开启GPU推理。

**Comment by linjieccc** [comment]
您好，支持的。只要正确安装GPU版本的paddlepaddle，Taskflow就会自动选择gpu环境来推理
可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L135

**Comment by Gavingx** [comment]
> 您好，支持的。只要正确安装GPU版本的paddlepaddle，Taskflow就会自动选择gpu环境来推理 可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L135

paddlenlp 2.3.1和paddlepaddle-gpu 2.3.0可以适配吗？ 安装之后依然还是用的cpu，taskflow也没有自动选择，关于这块有文档可以参考吗？

**Comment by wawltor** [comment]
> > 您好，支持的。只要正确安装GPU版本的paddlepaddle，Taskflow就会自动选择gpu环境来推理 可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L135
> 
> paddlenlp 2.3.1和paddlepaddle-gpu 2.3.0可以适配吗？ 安装之后依然还是用的cpu，taskflow也没有自动选择，关于这块有文档可以参考吗？

那可能是GPU版本安装的有问题，使用conda来安装  https://www.paddlepaddle.org.cn/ 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/16698950/170946216-d740ef5e-3976-45df-bff9-6db9f83c086b.png">

**Comment by Gavingx** [comment]
> > > 您好，支持的。只要正确安装GPU版本的paddlepaddle，Taskflow就会自动选择gpu环境来推理 可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L135
> > 
> > 
> > paddlenlp 2.3.1和paddlepaddle-gpu 2.3.0可以适配吗？ 安装之后依然还是用的cpu，taskflow也没有自动选择，关于这块有文档可以参考吗？
> 
> 那可能是GPU版本安装的有问题，使用conda来安装 https://www.paddlepaddle.org.cn/ <img alt="image" width="835" src="https://user-images.githubusercontent.com/16698950/170946216-d740ef5e-3976-45df-bff9-6db9f83c086b.png">

可以考虑支持下docker吧，配环境太麻烦了，各种奇怪问题。= _ = !!

**Comment by wawltor** [comment]
> > > > 您好，支持的。只要正确安装GPU版本的paddlepaddle，Taskflow就会自动选择gpu环境来推理 可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L135
> > > 
> > > 
> > > paddlenlp 2.3.1和paddlepaddle-gpu 2.3.0可以适配吗？ 安装之后依然还是用的cpu，taskflow也没有自动选择，关于这块有文档可以参考吗？
> > 
> > 
> > 那可能是GPU版本安装的有问题，使用conda来安装 https://www.paddlepaddle.org.cn/ <img alt="image" width="835" src="https://user-images.githubusercontent.com/16698950/170946216-d740ef5e-3976-45df-bff9-6db9f83c086b.png">
> 
> 可以考虑支持下docker吧，配环境太麻烦了，各种奇怪问题。= _ = !!

docker也是有的，你可以看这里 https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by Gavingx** [comment]
用你们的docker gpu环境推理uie给的案例，平均50ms，但是用自己的容器安装gpu版本的paddle（conda 安装的），推理速度和用CPU差不多，差不多5s左右。好像并没有用到GPU,是我安装的版本不对吗？
![image](https://user-images.githubusercontent.com/43789460/171128703-8624269f-f520-41c5-9240-5f18178b8d4a.png)
