### ISSUE TITLE
develop 分支里 education 的内容被迁移了？

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#2343]
在看paddlenlp的视频教程，里面提到了很多次在paddlenlp，develop 分支，education文件夹里的文档，但是现在这些内容已经不存在了，是否被迁移了？

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.2/education

**Comment by godlockin** [comment]
cheers
