### ISSUE TITLE
模型压缩裁剪之后的模型导出时，报错ValueError: (InvalidArgument) Invalid enum data type `0`

### ISSUE THREAD

**Issue by githanyongjin** [PaddlePaddle/PaddleNLP#2349]
使用的案例是https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/pp-minilm/pruning/export_model.py

具体报错为：
    out = _C_ops.cast(x, 'in_dtype', x.dtype, 'out_dtype', dtype)
ValueError: (InvalidArgument) Invalid enum data type `0`. (at /paddle/paddle/phi/kernels/cpu/cast_kernel.cc:29)
  [operator < cast > error]

**Comment by LiuChiachi** [comment]
您好，能麻烦把整个报错部分截个图吗，上面有些信息需要看一下。同时我也复现一下。

**Comment by githanyongjin** [comment]
> 您好，我把paddle换成2.2.2版本没有报错了，可能是版本问题，之前用的是2.3版本，谢谢
