### ISSUE TITLE
paddlenlp.transformers » chinesebert » tokenizer    其中ChineseBertTokenizer存在问题，其中代码使用了pinyin = try_import("pypinyin.pinyin")，这是错误的

### ISSUE THREAD

**Issue by iwanglei1** [PaddlePaddle/PaddleNLP#2352]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by iwanglei1** [comment]
~/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/chinesebert/tokenizer.py in pinyin_locs_map(self, text)
    732             dict: the map of pinyin locations and pinyin tensor.
    733         """
--> 734         pinyin = try_import("pypinyin.pinyin")
    735         Style = try_import("pypinyin.Style")
    736         pinyin_list = pinyin(

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/utils/lazy_import.py in try_import(module_name)
     38             "manually installed (usually with `pip install {}`). ").format(
     39                 module_name, install_name)
---> 40         raise ImportError(err_msg)

ImportError: Failed importing pypinyin.pinyin. This likely means that some paddle modules require additional dependencies that have to be manually installed (usually with `pip install pypinyin`).

**Comment by iwanglei1** [comment]
其中pinyin = try_import("pypinyin.pinyin")  代码执行错误

使用from pypinyin import pinyin时不会报错
但是程序中使用import pypinyin.pinyin 报错
导致ChineseBertTokenizer 无法使用

**Comment by wawltor** [comment]
> 其中pinyin = try_import("pypinyin.pinyin") 代码执行错误
> 
> 使用from pypinyin import pinyin时不会报错 但是程序中使用import pypinyin.pinyin 报错 导致ChineseBertTokenizer 无法使用

好的，收到 我们研究一下，谢谢给我们指出问题！
