### ISSUE TITLE
ERNIE 3.0分类模型部署的问题

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2354]
关于部署，我看示例wget到的模型文件是完整的模型文件，而我微调得到的只有参数，我该怎么部署？
![图片](https://user-images.githubusercontent.com/88191580/170947214-bc75ef0a-0912-45c0-a610-cb33db3a6cb8.png)

**Comment by guoshengCS** [comment]
抱歉这里没有明确给出如何将微调后的模型转换为部署的模型文件，侧重导出压缩的模型把这个漏掉了，可以参考下这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/compress_trainer.py#L171 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/14105589/170969339-0643be57-4919-41a8-9e64-3c9df8357aa8.png"> 
或者是BERT这里的模型导出 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/export_model.py#L51 
 ERNIE-3.0 这个是一样的，我们后面也针对当前这个问题进行完善更新

**Comment by jiweizhangxu** [comment]
> 抱歉这里没有明确给出如何将微调后的模型转换为部署的模型文件，侧重导出压缩的模型把这个漏掉了，可以参考下这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/compress_trainer.py#L171 <img alt="image" width="714" src="https://user-images.githubusercontent.com/14105589/170969339-0643be57-4919-41a8-9e64-3c9df8357aa8.png"> 或者是BERT这里的模型导出 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/export_model.py#L51 ERNIE-3.0 这个是一样的，我们后面也针对当前这个问题进行完善更新

能请您先快完善一下实例吗？就是法研杯的那个多分类实战，加上压缩，剪枝量化和部署模块吗，这样咱们也算是完整的把项目弄好了，我这样的笨蛋也能一步步照猫画虎实际应用一下，如果弄好了，请在微信群通知一下，感谢
