### ISSUE TITLE
RAT-SQL训练代码与推理问题

### ISSUE THREAD

**Issue by umbraclet16** [PaddlePaddle/PaddleNLP#2357]
- 版本、环境信息
1）PaddleNLP 2.0.8，PaddlePaddle2.1.0.post101
2）Ubuntu 18.04.5 lts，python 3.7.5
- 复现信息：
1.推理：依照readme，下载官方提供的模型进行推理，三个数据集的结果都很差，执行评估结果准确率基本为0，无法复现基线效果。

2.训练：text2sql/launch/trainer.py中，每个epoch后进行评估的函数_eval_during_train()并未进行真正的评估操作，返回为无意义内容。因此无法在训练过程中评估训练情况。

**Comment by wawltor** [comment]
您好，谢谢指出这些问题！
1.  这块我们尽快会修复一下脚本
2. 训练这块因为之前的代码贡献者为了节省evaluate的时间，所以做了这样的很trick的事情，目前这个开发者很难找得到，这块我们尽量来修复一下
