### ISSUE TITLE
使用taskflow进行信息抽取时，提示没有这个任务名称

### ISSUE THREAD

**Issue by qustfmy** [PaddlePaddle/PaddleNLP#2358]
使用官方例子
`from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称']  # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
# Better print results using pprint
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))`
报错信息：information_extraction is not in Taskflow list, please check your task name

**Comment by wawltor** [comment]
您好，需要更新一下PaddleNLP的版本 pip install paddlenlp --upgrade
