### ISSUE TITLE
在执行onnx推理代码,PaddleNLP/model_zoo/ernie-3.0/deploy/paddle2onnx/infer.py,对于推理数据的预处理有错误,应该转为list

### ISSUE THREAD

**Issue by apexg** [PaddlePaddle/PaddleNLP#2370]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.1和PaddlePaddle 2.2.2.post111，
2）系统环境：请您描述系统类型，ubuntu18 python3.8
- 复现信息：如下截图1,输入给的是一个整句list,但图2显示,在处理输入的时候没有分字,导致分词返回的结果不正确,是否应该将第二红框内容改为: [list(data[0])]
- 
![image](https://user-images.githubusercontent.com/6739219/171125132-6e4dcc22-8988-437c-8321-34ae02845a32.png)
![image](https://user-images.githubusercontent.com/6739219/171125463-8a039378-1f21-4809-8ed9-3dd9f9d864e4.png)

**Comment by heliqi** [comment]
这里是没问题的， 我验证推理的结果也正确。
这里的text =  list[input1, input2 .... inputn] 表示是 batch为n的输入 ， 图二就是对整个batch的句子一起切词。
其中inputX 必须为统一的格式。 
如果inputX为句子，比如: "北京的涮肉，重庆的火锅，成都的小吃都是极具特色的美食"，就会先按字分词； 
如果 inputX为切好的词 ，则是个list 比如 ["北", "京", "的", "涮", "肉",  ......  ] 。 ( 通过图二中is_split_into_words 参数控制）
