### ISSUE TITLE
paddle有实现longformer吗？或者能从已实现的torch版中导出paddle的预训练模型？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#2378]
如题

**Comment by ZeyuChen** [comment]
@zouhan6806504 我们有BigBird，综合能力应该不比longformer差，您是看中longformer哪个版本的预训练模型呢？

**Comment by zouhan6806504** [comment]
> @zouhan6806504 我们有BigBird，综合能力应该不比longformer差，您是看中longformer哪个版本的预训练模型呢？

只是想获得长文本的表示，并不一定要longformer或者他的特定版本，bigbird有简介么？

**Comment by zouhan6806504** [comment]
> > @zouhan6806504 我们有BigBird，综合能力应该不比longformer差，您是看中longformer哪个版本的预训练模型呢？
> 
> 只是想获得长文本的表示，并不一定要longformer或者他的特定版本，bigbird有简介么？

还有希望是中文版的

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-doc
如果中文的话可以试试ERNIE-Doc，是中文的而且支持长文档
