### ISSUE TITLE
Please release Pointer Generator implementation 

### ISSUE THREAD

**Issue by Pzoom522** [PaddlePaddle/PaddleNLP#238]
Hi,

[Pointer Generator](https://arxiv.org/abs/1704.04368) is one of the most popular baseline in text summarisation studies. It also serves as the building block of several very competitive models. Therefore, if Pointer Summariser can be included into your model zoo, it will greatly encourage the development of Paddle-based summarisation systems:wink:

Many thanks!

**Comment by guoshengCS** [comment]
Update: The implementation of Pointer Generator is under review now https://github.com/PaddlePaddle/PaddleNLP/pull/235 .

**Comment by Pzoom522** [comment]
Thanks for your hard work! 辛苦了! ☕

**Comment by logan-siyao-peng** [comment]
Hi @Pzoom522, feel free to use the most current version here. We are still reconstructing the code to better align with the PaddleNLP framework but the current version is sufficient to reproduce the SOTA results in the source paper.
Let us know if you have any questions.

https://github.com/logan-siyao-peng/PaddleNLP/tree/60246220447f598c7a4f2ebed7a548fc83f8f0e7/examples/text_summarization/pointer_summarizer
