### ISSUE TITLE
UIE doccano.py 脚本划分数据集报错

### ISSUE THREAD

**Issue by Haibarayu** [PaddlePaddle/PaddleNLP#2383]
版本、环境信息
1）PaddleNLP 2.3.1，PaddlePaddle-GPU 2.3.0
2）系统环境：Linux，python3.8.12

使用 doccano.py 脚本处理 doccano 平台导出的数据，发生以下错误：
1）未按参数比例划分数据集
![image](https://user-images.githubusercontent.com/50996772/171371909-091d645e-2ca3-41c0-86f3-9a77a65d2c54.png)

2）使用『0.7 0.2 0.1』比例时发生报错：ValueError: Please set correct splits, sum of elements in splits should be equal to 1.
![image](https://user-images.githubusercontent.com/50996772/171372699-e4ecb948-bbf7-4c35-82f0-3faa2b4840e5.png)

**Comment by linjieccc** [comment]
您好，

1）可以适当增加原始标注数据，从截图来看原始标注数据应该只有5条
2）感谢反馈，问题已修复，可以用最新代码再试下

**Comment by Haibarayu** [comment]
> 您好，
> 
> 1）可以适当增加原始标注数据，从截图来看原始标注数据应该只有5条 2）感谢反馈，问题已修复，可以用最新代码再试下

感谢回复，
1）似乎是 int() 造成的，影响不大
2）问题已解决
