### ISSUE TITLE
UIE源码疑惑

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleNLP#2384]
看了下源代码，发现taskflow里的UIE代码跟原始的不太一样，怎么感觉是阅读理解范式呢？
标签名直接与原文拼接，输入模型预测start, end。这个不是prompt吧？

**Comment by linjieccc** [comment]
Taskflow里接入的UIE中文版是抽取式的，在零样本和小样本上的效果更好，模型结构可以参考下图
<div align="center">
    <img src=https://user-images.githubusercontent.com/40840292/167236006-66ed845d-21b8-4647-908b-e1c6e7613eb1.png height=400 hspace='10'/>
</div>
和传统prompt有区别的是UIE固定了prompt的构造方式，就是条件+抽取标签，省去了传统prompt选择太多的问题

**Comment by FrankWhh** [comment]
多谢回复，UIE确实是解决了传统prompt模板构造问题。ps: 我只是觉得这个与阅读理解范式没啥区别，当然NLP里这种还是很常见的

**Comment by kahitomi** [comment]
现在广义的prompt指代可能比较大，大家想做的是怎么用适当的prompt引导模型给出正确答案，这里利用的是预训练阶段的无监督知识。很多prompt看起来和阅读理解的构造一致，因为这个符合自然语言理解的表达，可以让模型顺着往下说。问题是怎么构造prompt更好，常常多一个『吗』之类的词也会对结果影响很大。所以taskflow的UIE才有了用大量信息抽取数据让模型适配固定prompt的方法。

**Comment by FrankWhh** [comment]
感谢回复 说的很有道理

**Comment by xxllp** [comment]
如果是固定的prompt的其实跟阅读理解的差别已经不大了
