### ISSUE TITLE
有没有比较现成的，能识别一句话是正常有意义的话的预训练模型

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#2388]
在语音识别时，通常都是基于普通话，如果遇到方言，就会出现一些无意义的话语，比如：“你知你想我转开咪呢，诶，印尼垂头宿舍就是入嚟瞓醒啊，我打佢我诶坐落去嚟瞓啊，佢我哋回到你哋人类啊，佢啊佢手持嚟，”
我想判断这种情况，可否有现成不用自己再训练的模型用？

**Comment by wawltor** [comment]
这个功能没有了，这个功能相对来说是比较和场景相关的，从场景角度来说是需要通过你的场景数据来进行微调的，如果任务标注数据过多的话，可以使用UIE的小样本分类来提升标注效率和训练效率，具体功能可以见  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
