### ISSUE TITLE
PaddleNLP 如何从百万级数据中查找出与给定文本相似的文本集合？

### ISSUE THREAD

**Issue by Nicole1983** [PaddlePaddle/PaddleNLP#239]
目前PaddleNLP文本匹配算法ernie_tiny只支持每次输入一对 （query，title)， 但是在实际应用场景中，经常需要从几万甚至百万个title中，寻找和query相似的title，这种场景使用ernie_tiny该如何进行提速呢？或者PaddleNLP有其它算法适用上述场景呢？
请大佬指点一二，感激不尽！

**Comment by tianxin1860** [comment]
> 目前PaddleNLP文本匹配算法ernie_tiny只支持每次输入一对 （query，title)， 但是在实际应用场景中，经常需要从几万甚至百万个title中，寻找和query相似的title，这种场景使用ernie_tiny该如何进行提速呢？或者PaddleNLP有其它算法适用上述场景呢？
> 请大佬指点一二，感激不尽！

你的需求是给定 query 在海量 title 库中进行 ANN 检索，可以基于 ERNIE_tiny 或其它预训练模型热启，然后进行 query、title 双塔结构的训练，然后通过对 title 端进行 ANN 建库，就可以满足你的需求。另外，PaddleNLP Q2 计划推出面向语义索引场景的算法，欢迎关注。

**Comment by Nicole1983** [comment]
感谢回复！
我们在训练阶段也是使用ernie_tiny预训练模型热启动 + 双塔结构进行的训练，title特征已经提前计算好并保存在库中，在预测阶段，需要将query特征和库里面每个title的特征进行相似度计算，最终从库里获取最相似的title。
现在预测阶段的速度非常慢，输入一个query获取相似title需用时13s，当前库里只有170个title的特征，怎样才能提高预测的速度呢？

**Comment by tianxin1860** [comment]
> 感谢回复！
> 我们在训练阶段也是使用ernie_tiny预训练模型热启动 + 双塔结构进行的训练，title特征已经提前计算好并保存在库中，在预测阶段，需要将query特征和库里面每个title的特征进行相似度计算，最终从库里获取最相似的title。
> 现在预测阶段的速度非常慢，输入一个query获取相似title需用时13s，当前库里只有170个title的特征，怎样才能提高预测的速度呢？

13s 包括计算 query 表示和 用 query 表示去进行 ann 检索所花费的总时间么？建议分别统计这 2 阶段的耗时，先明确性能瓶颈在哪里。

**Comment by Nicole1983** [comment]
你好，13s只是用query表示去进行检索所花费的时间。

**Comment by tianxin1860** [comment]
> 你好，13s只是用query表示去进行检索所花费的时间。

ann 检索引擎用的是什么？检查一下用法吧，应该是没用对，170 个 titile 的检索耗时应该非常小(不超过 ms 级别) 才符合预期。

**Comment by Nicole1983** [comment]
你好！非常感谢您的回复！
ann检索这部分确实做的不太好，这部分不是很了解，请推荐个性能比较高的ann检索引擎可以吗？如果能给个例子链接就更好了。

**Comment by tianxin1860** [comment]
> 你好！非常感谢您的回复！
> ann检索这部分确实做的不太好，这部分不是很了解，请推荐个性能比较高的ann检索引擎可以吗？如果能给个例子链接就更好了。

可以了解下 FAISS、Annoy、Milvus, 任意一款都可以。

**Comment by Nicole1983** [comment]
感谢指点！我们把ann检索这部分再做一下，谢谢！

**Comment by tianxin1860** [comment]
> 感谢指点！我们把ann检索这部分再做一下，谢谢！

我们开源了语义索引策略库和模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing ，欢迎使用，有问题欢迎反馈。
