### ISSUE TITLE
跑神经搜索里recall  in_batch_neg.py  evaluate.py时报错。

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2399]
我用官方数据集跑通了整个流程，用自建数据集报错。不知道数据集哪里错了

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "evaluate.py", line 61, in <module>
    text, similar_text = line.rstrip().split("\t")
ValueError: too many values to unpack (expected 2)

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by w5688414** [comment]
请提供一下您的数据集
