### ISSUE TITLE
paddlenlp==2.0.0rc 木有封装 LinearDecayWithWarmup

### ISSUE THREAD

**Issue by loujie0822** [PaddlePaddle/PaddleNLP#24]
既然是中文Readme，我就直接写中文了。如题。

**Comment by LiuChiachi** [comment]
hello，`LinearDecayWithWarmup`是上次发包后合入的API
为了支持后面补充的API，刚才更新发布了rc2版本的新包，可以使用`pip install paddlenlp==2.0.0rc2`更新一下，会支持` LinearDecayWithWarmup`这类API

**Comment by ZeyuChen** [comment]
Issues solved, please try the latest version of PaddleNLP.Thanks for your feedback.
@loujie0822
