### ISSUE TITLE
如何使用自己训练的BPE分词器训练GPT模型？

### ISSUE THREAD

**Issue by cdj0311** [PaddlePaddle/PaddleNLP#2402]
大佬好，请问两个问题：
1. 能否用tokenizers库训练的BPE词表训练GPT模型？
2. 如果1不能，那能否用PaddleNLP训练一个词表使用？

**Comment by gongel** [comment]
可以加载自定义的BPE词表，传入vocab_file和merges_file即可。
```python
GPTTokenizer(vocab_file, merges_file)
```
