### ISSUE TITLE
您好，taskflow，ddparser问题求助。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#2408]
您好，我在调用ddparser的时候遇到了如下问题，
![image](https://user-images.githubusercontent.com/73834112/171641583-289dc585-c57a-4948-9724-ca9a32755aa6.png)
我的代码就是按照usage写的：
![image](https://user-images.githubusercontent.com/73834112/171641679-928f2a53-b74e-41a8-8d18-0e5e278ac2d0.png)
paddlenlp是2.3.2，新更新的，请问为啥会这样呢？
另外想请教一下，如何把ddparser的结果保存起来呢？
感谢。

**Comment by linjieccc** [comment]
您好，可能是框架版本比较低，可以升级paddlepaddle到最新版本再试下哈。ddparser结果保存是指将输出结果存入文件么？

**Comment by shaitaiyangmie** [comment]
> 您好，可能是框架版本比较低，可以升级paddlepaddle到最新版本再试下哈。ddparser结果保存是指将输出结果存入文件么？

感谢您的回复！对的，就是输出结果存入文件，请问该如何操作呢？

**Comment by linjieccc** [comment]
> > 您好，可能是框架版本比较低，可以升级paddlepaddle到最新版本再试下哈。ddparser结果保存是指将输出结果存入文件么？
> 
> 感谢您的回复！对的，就是输出结果存入文件，请问该如何操作呢？

可以通过json dumps的方式来写入文件：

```python
import json
from paddlenlp import Taskflow

ddp = Taskflow("dependency_parsing")
results = ddp(["三亚是一座美丽的城市", "他送了一本书"])
with open("example.txt", "a") as f:
    for result in results:
        line = json.dumps(result, ensure_ascii=False)
        f.write(line + "\n")
```

**Comment by shaitaiyangmie** [comment]
> 

非常感谢您，问题已解决。

**Comment by linjieccc** [comment]
@shaitaiyangmie 不客气，更多Taskflow的使用方法可以参考这个AI Studio项目：https://aistudio.baidu.com/aistudio/projectdetail/3696243

**Comment by shaitaiyangmie** [comment]
> 

好的好的，感谢！！
