### ISSUE TITLE
基于 LambdaDecay 实现的 LinearDecayWithWarmup，训练中途挂掉后热启动继续训练，学习率还是按 step = 0 开始迭代

### ISSUE THREAD

**Issue by nbcc** [PaddlePaddle/PaddleNLP#241]
ci 见 https://github.com/PaddlePaddle/models/commit/fee616e868262a7b791f3801bd0d1380f56d0e36

**Comment by guoshengCS** [comment]
这个目前是会按step=0迭代的，可以先试下将`LinearDecayWithWarmup`的last_epcoh 参数设置为上次中断的step来恢复，参考文档 https://paddlenlp.readthedocs.io/en/latest/source/paddlenlp.transformers.optimization.html#paddlenlp.transformers.optimization.LinearDecayWithWarmup ，也请 @LiuChiachi  确认下 ， 保存与恢复训练我们后续也会继续完善，感谢~

**Comment by LiuChiachi** [comment]
你好！如果以后还可能会有这样继续训练的使用场景，可以将lr, optimizer等用`paddle.save(lr_scheduler.state_dict(), "xx")`保存下来，在恢复训练的时候再load：`lr_scheduler.set_state_dict(paddle.load("xx"))`。
