### ISSUE TITLE
基于ERNIE垂直领域二次预训练效果为什么不佳呢？

### ISSUE THREAD

**Issue by dldragonking** [PaddlePaddle/PaddleNLP#2418]
通过paddlenlp里面的预训练全流程的指引https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0 ，我在AISTUDIO实现了领域垂类数据的二次预训练：先用
[create_pretraining_data.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/data_tools/create_pretraining_data.py)处理领域数据，然后使用[run_pretrain.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/run_pretrain.py)在ernie-1.0-base-zh模型上对领域数据进行二次预训练，最后在领域语料finetune完成NER任务，但效果很不好。在ernie-1.0-base-zh模型下finetune得到的F1为0.7，在二次预训练模型下fintune得到F1为0.2，差距很大：
```shell
python -u  -m paddle.distributed.launch \
    --gpus "0" \
    --log_dir "output/ernie-lib/log" \
    run_pretrain.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-1.0-base-zh" \
    --input_dir "./data" \
    --output_dir "output/ernie-lib" \
    --max_seq_len 512 \
    --micro_batch_size 64 \
    --use_amp true \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 10000 \
    --save_steps 1000 \
    --checkpoint_steps 1000 \
    --decay_steps 99000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --logging_freq 20\
    --num_workers 2 \
    --eval_freq 1000 \
    --device "gpu"\
```
以上，请问：
1、这样做的二次预训练模型是在ernie-1.0-base-zh通用模型上对领域数据二次预训练，还是直接对领域数据预训练呢？
2、最后finetune效果没有通用模型好是什么原因呢？数据不够，还是方法不对呢？
3、二次预训练的正确做法是怎样呢？

**Comment by ZHUI** [comment]
>  以上，请问：
  1、这样做的二次预训练模型是在ernie-1.0-base-zh通用模型上对领域数据二次预训练，还是直接对领域数据预训练呢？
  2、最后finetune效果没有通用模型好是什么原因呢？数据不够，还是方法不对呢？
  3、二次预训练的正确做法是怎样呢？

您好，主要问题在于目前的预训练流程是，默认随机初始化开始训练。您可以稍微修改一些这段代码，走else分支，加载提供的预训练参数。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/run_pretrain.py#L323-L334 
1. 是后者。您想要的是前者，可以根据上面建议修改
2. 同上，应为是随机初始化，需要训练很久(100w steps)，才会有好效果
3. 可以根据上面建议修改

我们将修改提供选项给用户，让用户可以加载 已有的 参数，进行预训练。

**Comment by dldragonking** [comment]
@ZHUI    下面代码不是加载model_name_or_path预训练参数吗？
```python
     model = model_class.from_pretrained(
            args.model_name_or_path,
            hidden_dropout_prob=args.hidden_dropout_prob,
            attention_probs_dropout_prob=args.attention_probs_dropout_prob)
```

1、请问如何加载ernie-1.0-base-zh的预训练参数，能给一段代码吗？
2、把--model_name_or_path 设为"ernie-gram" 能否在ernie-gram模型上进行二次预训练呢？
谢谢！

**Comment by ZHUI** [comment]
原始代码
```python
    # 这里是 启动一个 随机初始化的分支，默认是这个分支
    if args.model_name_or_path in pretrained_models_list:
        model_config = model_class.pretrained_init_configuration[
            args.model_name_or_path]
        model_config["hidden_dropout_prob"] = args.hidden_dropout_prob
        model_config[
            "attention_probs_dropout_prob"] = args.attention_probs_dropout_prob
        model = model_class(base_class(**model_config))
    else:
        # 这个分支 是为了加载 出入 model_name_or_path 为路径的时候。
        model = model_class.from_pretrained(
            args.model_name_or_path,
            hidden_dropout_prob=args.hidden_dropout_prob,
            attention_probs_dropout_prob=args.attention_probs_dropout_prob)
```

修改为，即可，不要上面的 if 分支
```python
    model = model_class.from_pretrained(
        args.model_name_or_path,
        hidden_dropout_prob=args.hidden_dropout_prob,
        attention_probs_dropout_prob=args.attention_probs_dropout_prob)
```

设置为 "ernie-gram" 是不可以的，"ernie-gram" 的权重 不在 ernie/modeling.py 问价中。

**Comment by dldragonking** [comment]
谢谢解答，可以在ernie-1.0-base-zh通用模型上对领域数据二次预训练，达到预期效果。
