### ISSUE TITLE
information_extraction 情感分析传入数组时返回个别数据返回为空

### ISSUE THREAD

**Issue by zhaozhaozhaozzz** [PaddlePaddle/PaddleNLP#2421]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

PaddlePaddle版本号:2.3
系统环境：Linux hi-prod-20 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

场景：情感分析
参考案例：https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.3/docs/model_zoo/taskflow.md#%E6%83%85%E6%84%9F%E5%80%BE%E5%90%91%E5%88%86%E6%9E%90

异常描述：当传入情感分析的为数组时，有部分返回为空，如图：
![image](https://user-images.githubusercontent.com/106967897/172153070-305a59fd-c31c-4b80-ba23-9af5337b5582.png)

schema = '情感倾向[正向，中性，负向]'
 ie = Taskflow("information_extraction", schema=schema, model='uie-tiny')
 res_tmp = ie(arr)  #arr为一个需做情感分析的数组

数组数据：
[数据.xlsx](https://github.com/PaddlePaddle/PaddleNLP/files/8844091/default.xlsx)

**Comment by wawltor** [comment]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/16698950/172154660-5f33882e-2f52-428e-8472-905693161a20.png">

1. 当行文本输入的时候，也是出现了空结果，出现空结果的原因是模型没有判断出具体哪个分类是正确的，如果每行都想输出的结果，可以设置 position_prob 概率来输出结果的置信度

```python
 e = Taskflow('information_extraction', schema=schema, model='uie-tiny', position_prob=0.01) 
```
2. 看schema UIE对三分类的情感分类识别效果不好，这是因为UIE在基础数据微调的时候主要是进行二分类情感分析，如果想提升效果可以标注一些数据进行微调
