### ISSUE TITLE
借楼请教一下Bert输入问题

### ISSUE THREAD

**Issue by 2627020811** [PaddlePaddle/PaddleNLP#2435]
Bert论文里面写Bert的输入为：词向量、句向量和位置信息三者之和，可是在代码里我们却是将tokenizer的处理结果：input_ids和token_ids输入Bert，请问二者有何关联？

**Comment by guoshengCS** [comment]
词向量对应input_ids，句向量对应token_ids，位置信息会在模型forward过程中自动生成 ，可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py#L55
