### ISSUE TITLE
pip 用百度源安装的时候报错

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#244]
具体信息如下：更新了pip 和 setuptool 也不行
(paddle) root@7eae298bd17a:/app# pip install --upgrade paddlenlp -i https://mirror.baidu.com/pypi/simple
Looking in indexes: https://mirror.baidu.com/pypi/simple
Collecting paddlenlp
  Downloading https://mirror.baidu.com/pypi/packages/e9/89/812c1f3683f8296114ca91d591601515352741d37d9847114836a9dfa188/paddlenlp-2.0.0rc16-py3-none-any.whl (295 kB)
     |████████████████████████████████| 295 kB 37 kB/s 
Requirement already satisfied: colorlog in /home/user/miniconda/envs/paddle/lib/python3.7/site-packages (from paddlenlp) (4.6.2)
Requirement already satisfied: visualdl in /home/user/miniconda/envs/paddle/lib/python3.7/site-packages (from paddlenlp) (2.0.5)
Collecting colorama
  Downloading https://mirror.baidu.com/pypi/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting h5py
  Downloading https://mirror.baidu.com/pypi/packages/b3/c5/94e2444eb691f658fb8e3cf6cde3ae29540cf6d9ce76f0561afcdbb89136/h5py-3.2.1-cp37-cp37m-manylinux1_x86_64.whl (4.1 MB)
     |████████████████████████████████| 4.1 MB 5.3 MB/s 
Requirement already satisfied: numpy>=1.14.5 in /home/user/miniconda/envs/paddle/lib/python3.7/site-packages (from h5py->paddlenlp) (1.20.2)
Collecting cached-property
  Downloading https://mirror.baidu.com/pypi/packages/48/19/f2090f7dad41e225c7f2326e4cfe6fff49e57dedb5b53636c9551f86b069/cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting jieba
  Downloading https://mirror.baidu.com/pypi/packages/c6/cb/18eeb235f833b726522d7ebed54f2278ce28ba9438e3135ab0278d9792a2/jieba-0.42.1.tar.gz (19.2 MB)
     |████████████████████████████████| 19.2 MB 3.4 MB/s 
Collecting seqeval
  Downloading https://mirror.baidu.com/pypi/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 182 kB/s 

    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda/envs/paddle/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkj_eaq_/seqeval_d5672f0a3725468cbd6a8798b8f5322f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkj_eaq_/seqeval_d5672f0a3725468cbd6a8798b8f5322f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vvkzmp1g
         cwd: /tmp/pip-install-wkj_eaq_/seqeval_d5672f0a3725468cbd6a8798b8f5322f/
    Complete output (37 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5d04358090>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5d04358510>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5d04358890>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5d04358c10>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f5d04358fd0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools-scm/
    ERROR: Could not find a version that satisfies the requirement setuptools_scm
    ERROR: No matching distribution found for setuptools_scm
    Traceback (most recent call last):
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/user/miniconda/envs/paddle/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6kn85bnu', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wkj_eaq_/seqeval_d5672f0a3725468cbd6a8798b8f5322f/setup.py", line 56, in <module>
        'Programming Language :: Python :: Implementation :: PyPy'
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/user/miniconda/envs/paddle/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/user/miniconda/envs/paddle/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6kn85bnu', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zhiyongLiu1114** [comment]
后来还是报了这个错，但是报错后又继续安装了。。。。

**Comment by ZeyuChen** [comment]
pip install --upgrade paddlenlp -i https://pypi.org/simple

请尝试使用官方源安装，由于目前paddlenlp还是rc版本，百度源没同步rc版本非正式版的包。

**Comment by ZeyuChen** [comment]
@zhiyongLiu1114 
我细看了下发现百度pypi上是有包的
`ERROR: Could not find a version that satisfies the requirement setuptools_scm
ERROR: No matching distribution found for setuptools_scm`
看上去是环境的这个setuptools_scm有问题，是否有创建个独立的conda环境进行安装

**Comment by zhiyongLiu1114** [comment]
> @zhiyongLiu1114
> 我细看了下发现百度pypi上是有包的
> `ERROR: Could not find a version that satisfies the requirement setuptools_scm ERROR: No matching distribution found for setuptools_scm`
> 看上去是环境的这个setuptools_scm有问题，是否有创建个独立的conda环境进行安装

好的，我试试，谢谢
