### ISSUE TITLE
时间序列分类问题？？？

### ISSUE THREAD

**Issue by SongCoder** [PaddlePaddle/PaddleNLP#2442]
![2](https://user-images.githubusercontent.com/86814482/172546454-e6461299-2997-432c-89cf-a7d996a1157e.png)
![3](https://user-images.githubusercontent.com/86814482/172546513-403bc298-ceee-4737-bb91-cc7ab8d897e3.png)
![4](https://user-images.githubusercontent.com/86814482/172546518-a5c097c9-d929-4923-8c22-6e18487d49fe.png)
![5](https://user-images.githubusercontent.com/86814482/172546519-0d2f7115-4d79-439d-9a22-c9071da2b61f.png)
![6](https://user-images.githubusercontent.com/86814482/172546523-23f61636-f764-4db3-a31b-0c9c47d09e15.png)
![7](https://user-images.githubusercontent.com/86814482/172546524-d80cd1b9-9dc4-4bb5-9463-96763c374ca5.png)
![8](https://user-images.githubusercontent.com/86814482/172546527-a02b3d87-56cb-4c36-a7d6-eed9dcf405c2.png)
![1](https://user-images.githubusercontent.com/86814482/172546535-158a5b5b-2457-424f-ae47-2bcd47e07eea.png)

有没有大佬 帮忙看看

**Comment by wawltor** [comment]
看起来是RNN输出的parameter参数和输入的数据类型不一致，你可以check一下RNN的parameter是不是double类型，而输入确实float类型

**Comment by SongCoder** [comment]
抱歉，我没太搞清楚怎么去做。


在2022年6月8日 ***@***.***> 写道：

看起来是RNN输出的parameter参数和输入的数据类型不一致，你可以check一下RNN的parameter是不是double类型，而输入确实float类型

**Comment by wawltor** [comment]
可以打印一下  代码中 `self.rnn ` 该对象的parameter数据类型` print(self.rnn.parameters())` ， 同时 打印 `print(x_data)` 数据类型，比对一下 两个对象的数据类型是否一致

**Comment by SongCoder** [comment]
好的 ，谢谢  我看一下


在2022年6月8日 ***@***.***> 写道：

可以打印一下 代码中 self.rnn 该对象的parameter数据类型 print(self.rnn.parameters()) ， 同时 打印 print(x_data) 数据类型，比对一下 两个对象的数据类型是否一致

**Comment by SongCoder** [comment]
哥，方便加个联系方式吗？
在2022年6月8日 ***@***.***> 写道：

可以打印一下 代码中 self.rnn 该对象的parameter数据类型 print(self.rnn.parameters()) ， 同时 打印 print(x_data) 数据类型，比对一下 两个对象的数据类型是否一致

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleTS
关于时间序列分类问题可以使用PaddleTS开发套件。
@wawltor PaddleNLP这里可以考虑下掉time series examples或者引导到PaddleTS去
