### ISSUE TITLE
from . import core_avx paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by EvanSong77** [PaddlePaddle/PaddleNLP#2443]
请问这个错误是跟linux版本有关吗？我的服务器版本是ubuntu22.04  我该如何解决？

**Comment by wawltor** [comment]
建议使用conda来安装PaddlePaddle    https://www.paddlepaddle.org.cn/ 
<img width="925" alt="image" src="https://user-images.githubusercontent.com/16698950/172563692-5f15f4fa-f541-4502-8e9d-93ec3df46e9e.png">
