### ISSUE TITLE
想问一下语义检索系统

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2447]
1.ern1.0训练完的模型，叫它模型1号，模型1号先过simcase策略训练得到一个模型2号，模型2号再过In_batch_negative策略等到模型3号，之后只需要部署一个模型，这样吗？但我看In_batch_negative没有参数model_name_or_path啊？

2.还是ern1.0训练完的模型，叫它模型1号，模型1号先过simcase策略训练得到一个模型2号，模型1号再过In_batch_negative策略等到模型3号，这样有两个模型经过不同策略训练出来的模型，之后需要部署两个模型？

3.不太理解双塔和单塔的意思

**Comment by tianxin1860** [comment]
1

> 1.ern1.0训练完的模型，叫它模型1号，模型1号先过simcase策略训练得到一个模型2号，模型2号再过In_batch_negative策略等到模型3号，之后只需要部署一个模型，这样吗？但我看In_batch_negative没有参数model_name_or_path啊？
> 
> 2.还是ern1.0训练完的模型，叫它模型1号，模型1号先过simcase策略训练得到一个模型2号，模型1号再过In_batch_negative策略等到模型3号，这样有两个模型经过不同策略训练出来的模型，之后需要部署两个模型？
> 
> 3.不太理解双塔和单塔的意思

1. 这种方案适用于你既有海量无监督数据及少量有监督数据的场景。理解的没问题，部署3号模型。可以通过 `--init_from_ckpt` 参数指定要加载的预训练模型参数。
2. 只有无监督数据的话就部署 2 号模型，有大量监督数据的话就部署3号模型。
3. 双塔表示 query 和 title 在抽取语义表示向量的时候没有发生 attention 交互，单塔模型则是发生了 attention 交互的。
