### ISSUE TITLE
uie 微调问题

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleNLP#2455]
报错信息如下
Traceback（最近一次调用最后）：
文件“finetune.py”，第159行，在
do_train（）
文件“finetune.py”，第68行，在do_train
train_batch_sampler = paddle.io.BatchSampler（
文件“/Users/ miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/ init .py”，第 176 行，在 _patch_batch_sampler_init
self.sampler = RandomSampler(dataset)
文件“/Users/miniconda3/envs/paddle/lib/python3 .8/site-packages/paddle/fluid/dataloader/sampler.py", line 210, init
raise ValueError("num_samples should be an positive integer, "
ValueError: num_samples should be a positive integer, but got num_samples=0

**Comment by wawltor** [comment]
是不是训练集和测试集的样本是不是空的，可以检查一下 train.txt dev.txt是不是正常

**Comment by sunshineyg2018** [comment]
> 是不是训练集和测试集的样本不是空的，可以检查一下 train.txt dev.txt 不是正常

python doccano.py --doccano_file ./data/waybill.jsonl --splits 1 0 0. 只有train.txt 有数据 其他两个 dev.txt 和test.txt 没有数据

**Comment by sunshineyg2018** [comment]
但是用的是=轻量级定制，直接就是验证集  dev.txt 和test.txt 空的也是正常吧

**Comment by wawltor** [comment]
> 但是用的是=轻量级定制，直接就是验证集 dev.txt 和test.txt 空的也是正常吧

在代码设计过程中是需要dev.txt不为空，因为最终要做验证的工作 ，可以简单设置一下 0.9 0.1 0.0这种比例
