### ISSUE TITLE
关于UIE耗时问题

### ISSUE THREAD

**Issue by YiTSu** [PaddlePaddle/PaddleNLP#2458]
使用UIE通过模型微调进行信息抽取，抽取耗时一直稳定在50ms左右，请问可以做到时间更短和更快吗？

目前用的是paddle的docker环境，机器上是一张T4的8G的显卡。我想了解下是因为模型训练时的参数设置限制了信息抽取耗时还是我的显存不够大导致的。

看其他人的反馈，也都是大多数在50ms左右。不过也有看到更快的，所以想看看下一步如何优化能使得时间比50ms更短。

**Comment by YiTSu** [comment]
不过我也有看到更快的，所以想看看下一步如何优化能使得时间比50ms更短。

**Comment by wawltor** [comment]
> 使用UIE通过模型微调进行信息抽取，抽取耗时一直稳定在50ms左右，请问可以做到时间更短和更快吗？
> 
> 目前用的是paddle的docker环境，机器上是一张T4的8G的显卡。我想了解下是因为模型训练时的参数设置限制了信息抽取耗时还是我的显存不够大导致的。
> 
> 看其他人的反馈，也都是大多数在50ms左右。不过也有看到更快的，所以想看看下一步如何优化能使得时间比50ms更短。

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/16698950/172751884-22998c33-2482-40c8-96cb-d18e785a4698.png">
可以根据文档，设置一下precision=fp16，这个可以加速；不过要注意一下环境设置以及相应的环境安装

```python
ie = Taskflow('information_extraction', schema=schema, precision='fp16')
```

**Comment by YiTSu** [comment]
> > 使用UIE通过模型微调进行信息抽取，抽取耗时一直稳定在50ms左右，请问可以做到时间更短和更快吗？
> > 目前用的是paddle的docker环境，机器上是一张T4的8G的显卡。我想了解下是因为模型训练时的参数设置限制了信息抽取耗时还是我的显存不够大导致的。
> > 看其他人的反馈，也都是大多数在50ms左右。不过也有看到更快的，所以想看看下一步如何优化能使得时间比50ms更短。
> 
> <img alt="image" width="1017" src="https://user-images.githubusercontent.com/16698950/172751884-22998c33-2482-40c8-96cb-d18e785a4698.png">
> 
> 可以根据文档，设置一下precision=fp16，这个可以加速；不过要注意一下环境设置以及相应的环境安装
> ```python
> ie = Taskflow('information_extraction', schema=schema, precision='fp16')
> ```

好的，我去尝试一下，刚好paddle的docker环境就是CUDA11.2和cuDNN8.1.1。那也就是说如果不设置加速的话，50ms符合预期吗？应该不是显卡显存不够大导致的预测速度慢是吧。

**Comment by wawltor** [comment]
你可以设置一下batch_size, 如果一次多输入几条样本，然后设置一下batch_size,  让利用率打满
例如 ie输入的样本是10条样本，然后设置batch_size=4
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/16698950/172756098-8270023e-a5b5-4e47-8081-3e2ac67279be.png">

**Comment by YiTSu** [comment]
> 你可以设置一下batch_size, 如果一次多输入几条样本，然后设置一下batch_size, 让利用率打满 例如 ie输入的样本是10条样本，然后设置batch_size=4 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/16698950/172756098-8270023e-a5b5-4e47-8081-3e2ac67279be.png">

precision和batch_size都设置尝试了一下，看起来时间并没缩短，没有起到作用。CUDA为11.2，cuDNN为8.1.1。

**Comment by wawltor** [comment]
> > 你可以设置一下batch_size, 如果一次多输入几条样本，然后设置一下batch_size, 让利用率打满 例如 ie输入的样本是10条样本，然后设置batch_size=4 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/16698950/172756098-8270023e-a5b5-4e47-8081-3e2ac67279be.png">
> 
> precision和batch_size都设置尝试了一下，看起来时间并没缩短，没有起到作用。CUDA为11.2，cuDNN为8.1.1。

应该是会work的，因为你的T4卡，我们内部测试的也是T4，能不能给一下跑的日志了，有没有安装onnxruntime-gpu了?

**Comment by YiTSu** [comment]
> > > 你可以设置一下batch_size, 如果一次多输入几条样本，然后设置一下batch_size, 让利用率打满 例如 ie输入的样本是10条样本，然后设置batch_size=4 <img alt="image" width="1145" src="https://user-images.githubusercontent.com/16698950/172756098-8270023e-a5b5-4e47-8081-3e2ac67279be.png">
> > 
> > 
> > precision和batch_size都设置尝试了一下，看起来时间并没缩短，没有起到作用。CUDA为11.2，cuDNN为8.1.1。
> 
> 应该是会work的，因为你的T4卡，我们内部测试的也是T4，能不能给一下跑的日志了，有没有安装onnxruntime-gpu了?

我用的咱们的Linux Docker镜像——paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8，这个Docker里面不清楚有没有预装onnxruntime-gpu，日志我找一下后面发一下。

**Comment by wawltor** [comment]
嗯嗯 可以看一下，应该日志里面是有提示安装onnxruntime-gpu的

**Comment by YiTSu** [comment]
> 嗯嗯 可以看一下，应该日志里面是有提示安装onnxruntime-gpu的

看到日志中的输出了，是fp16没有成功开启。通过安装onnxruntime-gpu onnx onnxconverter-common paddle2onnx这几个必备的支持解决了，抽取时间降低到了20ms。辛苦您啦~后续有问题我继续更新。

**Comment by wawltor** [comment]
您好，该issue问题目前已无回复，关闭该issue，后续有需求可以继续给我们提issue

**Comment by YiTSu** [comment]
> 您好，该issue问题目前已无回复，关闭该issue，后续有需求可以继续给我们提issue

还有个后续问题想咨询下，你们那边用T4卡测试的时候，耗时最短能做到多少呢？目前我这边是20ms，想看看还能不能继续缩短一些。

**Comment by BasicCoder** [comment]
<img width="438" alt="image" src="https://user-images.githubusercontent.com/7875392/182027138-d24213b5-bfa5-43c0-86b0-9e457ea84113.png">

经过优化，在T4后端，uie-base 模型单个prompt在seq_len=512可以优化到11ms左右。

**Comment by BasicCoder** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/7875392/182027397-f0700c4a-61d7-4c63-9e96-e62468819d37.png">

After optimization, on the T4 backend, the uie-base model can reach 11ms for a single prompt at seq_len=512.

**Comment by watertianyi** [comment]
我用自己的数据训练进行信息抽取，没有用到fp16的推理时间是112ms，用到fp16的推理时间是67ms，还有没有优化的空间，将推理时间降到50ms以内

I use my own data training for information extraction. The inference time without fp16 is 112ms, and the inference time with fp16 is 67ms. Is there any room for optimization to reduce the inference time to less than 50ms?
@BasicCoder @wawltor @YiTSu
