### ISSUE TITLE
安装完使用from paddlenlp import Taskflow报错

### ISSUE THREAD

**Issue by immortal-shuan** [PaddlePaddle/PaddleNLP#2460]
linux环境，
paddlenlp   2.3.3
paddlepaddle-gpu  2.2.2.post112

ImportError: cannot import name 'array_cast' from 'datasets.table' (/home/zjlab/.conda/envs/gputorch/lib/python3.7/site-packages/datasets/table.py)

**Comment by immortal-shuan** [comment]
已经解决了

**Comment by wawltor** [comment]
是说固定了datasets的版本吗？

**Comment by immortal-shuan** [comment]
pyarrow 和dataset版本冲突了

**Comment by immortal-shuan** [comment]
出现了新的问题Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.

**Comment by immortal-shuan** [comment]
Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
[Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:59)
  [operator < uniform_random > error]

**Comment by wawltor** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/16698950/172761939-81bd0893-f61c-43a9-ae7d-ab94153fc2c7.png">
建议conda的方式来安装飞桨 
https://www.paddlepaddle.org.cn/

**Comment by immortal-shuan** [comment]
我的cuda版本是11.0，conda无法使用

**Comment by wawltor** [comment]
> 我的cuda版本是11.0，conda无法使用

可以选择其他的cuda版本，他会自动在相应的conda环境安装特定的cuda版本
