### ISSUE TITLE
paddle复现IGSQL，效果无法打平

### ISSUE THREAD

**Issue by yujiate** [PaddlePaddle/PaddleNLP#247]
paddle复现IGSQL中，验证了代码编码器和解码器都没有问题，模型无法和torch版本的效果打平，torch原版的学习率为1e-3，paddle需要使用5e-3才能有效训练，而且最终结果也无法达到原版的效果

**Comment by ZeyuChen** [comment]
可否提供一下你用paddle复现的代码Repo地址，以及对应参考的IGSQL模型官方实现地址？ @yujiate

**Comment by ZeyuChen** [comment]
另外是否对pytorch和paddle的实现，随机输入tensor，验证过forward出来的结果和pytorch是否有对齐？ @yujiate

**Comment by ZeyuChen** [comment]
已转为内部跟进中，issues closed.
