### ISSUE TITLE
RocketQA 预训练模型下载问题

### ISSUE THREAD

**Issue by Abefocuson** [PaddlePaddle/PaddleNLP#2470]
PaddleNLP  2.2.4
PaddlePaddle 2.1.1

Linux,Python版本 3.8

模型下载报错：
https://bj.bcebos.com/paddlenlp/models/transformers/community/rocketqa-zh-dureader-query-encoder\model_state.pdparams 

直接访问模型路径下载也报错：
{"code":"NoSuchKey","message":"The specified key does not exist.","requestId":"6b91039a-9a83-4013-8dec-dc95b2e13f64"}

**Comment by Abefocuson** [comment]
https://bj.bcebos.com/paddlenlp/models/transformers/rocketqa/rocketqa_zh_dureader_query_encoder.pdparams

**Comment by Abefocuson** [comment]
已解决。

**Comment by ArtificialZeng** [comment]
升级paddlenlp到3.1

**Comment by Change0028** [comment]
请问你是怎么解决的呢？我也有类似的问题，找不到如下链接：https://bj.bcebos.com/paddlenlp/models/community/linly-ai/chinese-llama-2-7b/
