### ISSUE TITLE
微调 训练时间问题

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleNLP#2472]
微调会生成多个model 文件夹，大概多少数据生成一个？有没有办法查看预估训练完成时间的办法？

**Comment by wawltor** [comment]
> 微调会生成多个model 文件夹，大概多少数据生成一个？有没有办法查看预估训练完成时间的办法？

1. 生成模型这块是根据valid_steps来确定，例如valid_steps是100，就训练100个step就会生成一个文件夹
2. 时间预估需要根据一个epoch的时间，例如一个epoch是10s，100个epoch就是1000s，日志中会打印一个epoch等相关信息，可以预估一个epoch的时间
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/16698950/172993052-aeda0f7f-28c6-45f5-81f8-8d8e2bfd8a7b.png">

**Comment by sunshineyg2018** [comment]
感谢
