### ISSUE TITLE
一个实体标签如果有多个实体，UIE当前只能识别出其中的一个，发现部分标签存在这个问题

### ISSUE THREAD

**Issue by jikuibu** [PaddlePaddle/PaddleNLP#2473]
例子1：”2018年4月4日，财政部和税务总局正式发文，从2018年5月1日起，纳税人发生增值税应税销售行为或者进口货物“
schema=[‘日期’]
识别结果中只有：2018年5月1日

例子2：”2018年4月4日，美国和英国正式发文"
schema=[“国家”]
识别结果就有“美国”和“英国”两个

**Comment by sunshineyg2018** [comment]
可以吧。。。我就能识别出两个

**Comment by wawltor** [comment]
> 例子1：”2018年4月4日，财政部和税务总局正式发文，从2018年5月1日起，纳税人发生增值税应税销售行为或者进口货物“ schema=[‘日期’] 识别结果中只有：2018年5月1日
> 
> 例子2：”2018年4月4日，美国和英国正式发文" schema=[“国家”] 识别结果就有“美国”和“英国”两个

这个是因为UIE-base的效果是通用模型，在一些特例的数据会有模型偏差；这个建议自己微调一下模型，具体可以文档 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
