### ISSUE TITLE
在使用UIE工具进行分类任务时碰到一些问题

### ISSUE THREAD

**Issue by tianjiansmile** [PaddlePaddle/PaddleNLP#2474]
1. 利用evaluate.py进行评估时发现评估结果有些异常
 pred_set {(61, 64)} label_set {(61, 64)} num_correct 1
pred_set set() label_set {(61, 64)} num_correct 0
pred_set {(81, 84)} label_set {(76, 79), (81, 84)} num_correct 1
pred_set set() label_set {(76, 79), (81, 84)} num_correct 0
pred_set {(36, 40)} label_set {(66, 69), (36, 40)} num_correct 1
pred_set {(66, 69)} label_set {(66, 69), (36, 40)} num_correct 1
metric num_correct_spans 4 num_correct_spans 4 num_label_spans 10
实际上num_label_spans是5个
2. 利用Taskflow进行预测时，多标签的样本只能预测出一个标签，但是evaluate评  估时却可以预测出多个
3. Taskflow进行预测时，预测结果发生偏移

欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）paddlenlp=2.3.1，paddlepaddle-gpu=2.3.0
2）系统环境=Linux ，python版本=python3.7

**Comment by linjieccc** [comment]
1）请问训练数据有多少条，分类任务对分类标签的长度和数量有一定限制，方便提供一条训练数据看下吗
2）预测结果在prompt为英文时确实有偏移的问题，感谢指出，我们已经修复了 #2453，您可以拉下最新develop分支的代码再试下
