### ISSUE TITLE
关系抽取数据集转换相关问题

### ISSUE THREAD

**Issue by Chikeke** [PaddlePaddle/PaddleNLP#2476]
您好, 我的数据集是关系抽取数据集, 有2000条, 其中训练集1600条,验证测试集各200条, 用doccano.py进行转换后, 训练集目前没发现问题, 验证集和测试集出现很多重复数据, 具体是这样的, 第一阶段(实体层面)的转换都没有错, 但是第二阶段(关系层面)的转换好像只对其中一条数据生效了, 并且每个关系转换了200次(也就是我原验证集和测试集的数量), 这200条全部都是一样的, 也就是说,所有prompt为某种关系的数据的text都是同一条, 每种关系重复200次, 而剩余的199条数据的关系在完全没有体现出来, 我觉得这是不对的, 您可以解释一下这是为什么吗?或者是我哪里操作错了?
下面是转换后部分数据, 我用了最新的代码, 试过很多次都是这样的
![image](https://user-images.githubusercontent.com/95728480/173019216-5f1bfb8a-0381-4380-94d6-19454121528e.png)

- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.3，PaddlePaddle-gpu2.3.0
2）系统环境：Linux, python3.6, cuda11.2

**Comment by linjieccc** [comment]
@Chikeke 抱歉，今天合入的代码有点bug，已修复，辛苦拉下最新的develop分支重新试下

**Comment by Chikeke** [comment]
@linjieccc 感谢!重新试了一下没问题了.

**Comment by guoxiaoyue111111** [comment]
@Chikeke 您好，麻烦问下，您的关系抽取做精调了吗？精调效果相对于基线模型，效果有提升吗？

**Comment by Chikeke** [comment]
@guoxiaoyue111111 我做了的，效果和论文中结果差不多，测试集F1=0.76，但这是用经过doccano.py转换的测试集测试的，如果是用输入schema的方式预测的话F1只有0.6左右，我用的数据集是百度的关系抽取数据集，schema一次性输入了很多个，我觉得跟这个有关。

**Comment by dymyyc** [comment]
@Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by Chikeke** [comment]
中文有7461条，其中有关系的样本只有4022条



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: douyameiyingyang ***@***.***&gt;
发送时间: 2022年10月30日 19:11
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Chikeke ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)





 
@Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by dymyyc** [comment]
好的，请问ACE2005关系抽取英文部分又有多少条样本呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 上午10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)




 中文有7461条，其中有关系的样本只有4022条 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: douyameiyingyang ***@***.***&amp;gt; 
 发送时间: 2022年10月30日 19:11 
 收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;gt; 
 抄送: Chikeke ***@***.***&amp;gt;, Mention ***@***.***&amp;gt; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
 
   
 @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by Chikeke** [comment]
英文一共16312条，有关系的有11582条



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: douyameiyingyang ***@***.***&gt;
发送时间: 2022年11月7日 10:08
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Chikeke ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)





 好的，请问ACE2005关系抽取英文部分又有多少条样本呢？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年11月7日(周一) 上午10:06 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
  中文有7461条，其中有关系的样本只有4022条  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: douyameiyingyang ***@***.***&amp;amp;gt;  
  发送时间: 2022年10月30日 19:11  
  收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;gt;  
  抄送: Chikeke ***@***.***&amp;amp;gt;, Mention ***@***.***&amp;amp;gt;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   
     
  @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by dymyyc** [comment]
我处理出来差不多也是这么多，我看到有些论文ACE2005预处理出来有40000多条，感觉是做了数据增强，请问这种情况一般是不是加了一个no_relation来处理的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)




 英文一共16312条，有关系的有11582条 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: douyameiyingyang ***@***.***&amp;gt; 
 发送时间: 2022年11月7日 10:08 
 收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;gt; 
 抄送: Chikeke ***@***.***&amp;gt;, Mention ***@***.***&amp;gt; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
 
  好的，请问ACE2005关系抽取英文部分又有多少条样本呢？  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年11月7日(周一) 上午10:06  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   中文有7461条，其中有关系的样本只有4022条   
     
     
     
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: douyameiyingyang ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年10月30日 19:11   
   收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;gt;   
   抄送: Chikeke ***@***.***&amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;gt;   
   主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)   
     
     
     
     
     
       
   @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by Chikeke** [comment]
我没有尝试过数据增强，也不知道四万多条是怎么来的，但是ace05里每个实体都有一个head实体，不知道跟这个有没有关系



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: douyameiyingyang ***@***.***&gt;
发送时间: 2022年11月7日 10:17
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Chikeke ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)





 我处理出来差不多也是这么多，我看到有些论文ACE2005预处理出来有40000多条，感觉是做了数据增强，请问这种情况一般是不是加了一个no_relation来处理的？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年11月7日(周一) 上午10:11 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
  英文一共16312条，有关系的有11582条  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: douyameiyingyang ***@***.***&amp;amp;gt;  
  发送时间: 2022年11月7日 10:08  
  收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;gt;  
  抄送: Chikeke ***@***.***&amp;amp;gt;, Mention ***@***.***&amp;amp;gt;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   
   好的，请问ACE2005关系抽取英文部分又有多少条样本呢？   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年11月7日(周一) 上午10:06   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)   
     
     
     
     
    中文有7461条，其中有关系的样本只有4022条    
       
       
       
    发自我的iPhone    
       
       
    ------------------ 原始邮件 ------------------    
    发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2022年10月30日 19:11    
    收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;gt;    
    抄送: Chikeke ***@***.***&amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;gt;    
    主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)    
       
       
       
       
       
         
    @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by dymyyc** [comment]
请问，每个实体都有一个head实体，这是怎么关联起来的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)




 我没有尝试过数据增强，也不知道四万多条是怎么来的，但是ace05里每个实体都有一个head实体，不知道跟这个有没有关系 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: douyameiyingyang ***@***.***&amp;gt; 
 发送时间: 2022年11月7日 10:17 
 收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;gt; 
 抄送: Chikeke ***@***.***&amp;gt;, Mention ***@***.***&amp;gt; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
 
  我处理出来差不多也是这么多，我看到有些论文ACE2005预处理出来有40000多条，感觉是做了数据增强，请问这种情况一般是不是加了一个no_relation来处理的？  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年11月7日(周一) 上午10:11  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   英文一共16312条，有关系的有11582条   
     
     
     
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: douyameiyingyang ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年11月7日 10:08   
   收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;gt;   
   抄送: Chikeke ***@***.***&amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;gt;   
   主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)   
     
     
     
     
     
    好的，请问ACE2005关系抽取英文部分又有多少条样本呢？    
       
       
       
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2022年11月7日(周一) 上午10:06    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)    
       
       
       
       
     中文有7461条，其中有关系的样本只有4022条     
         
         
         
     发自我的iPhone     
         
         
     ------------------ 原始邮件 ------------------     
     发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;amp;gt;     
     发送时间: 2022年10月30日 19:11     
     收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;amp;gt;     
     抄送: Chikeke ***@***.***&amp;amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;amp;gt;     
     主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)     
         
         
         
         
         
           
     @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by Chikeke** [comment]
你可以看一下原始的标注数据



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: douyameiyingyang ***@***.***&gt;
发送时间: 2022年11月7日 13:06
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Chikeke ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)





 请问，每个实体都有一个head实体，这是怎么关联起来的？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年11月7日(周一) 中午11:00 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
  我没有尝试过数据增强，也不知道四万多条是怎么来的，但是ace05里每个实体都有一个head实体，不知道跟这个有没有关系  
   
   
   
  发自我的iPhone  
   
   
  ------------------ 原始邮件 ------------------  
  发件人: douyameiyingyang ***@***.***&amp;amp;gt;  
  发送时间: 2022年11月7日 10:17  
  收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;gt;  
  抄送: Chikeke ***@***.***&amp;amp;gt;, Mention ***@***.***&amp;amp;gt;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   
   我处理出来差不多也是这么多，我看到有些论文ACE2005预处理出来有40000多条，感觉是做了数据增强，请问这种情况一般是不是加了一个no_relation来处理的？   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年11月7日(周一) 上午10:11   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.******@***.***&amp;amp;amp;gt;;   
   主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)   
     
     
     
     
    英文一共16312条，有关系的有11582条    
       
       
       
    发自我的iPhone    
       
       
    ------------------ 原始邮件 ------------------    
    发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2022年11月7日 10:08    
    收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;gt;    
    抄送: Chikeke ***@***.***&amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;gt;    
    主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)    
       
       
       
       
       
     好的，请问ACE2005关系抽取英文部分又有多少条样本呢？     
         
         
         
     ---原始邮件---     
     发件人: ***@***.***&amp;amp;amp;amp;amp;gt;     
     发送时间: 2022年11月7日(周一) 上午10:06     
     收件人: ***@***.***&amp;amp;amp;amp;amp;gt;;     
     抄送: ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)     
         
         
         
         
      中文有7461条，其中有关系的样本只有4022条      
           
           
           
      发自我的iPhone      
           
           
      ------------------ 原始邮件 ------------------      
      发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      发送时间: 2022年10月30日 19:11      
      收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      抄送: Chikeke ***@***.***&amp;amp;amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)      
           
           
           
           
           
             
      @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？

**Comment by dymyyc** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月24日(周四) 上午9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)




 你可以看一下原始的标注数据 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: douyameiyingyang ***@***.***&amp;gt; 
 发送时间: 2022年11月7日 13:06 
 收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;gt; 
 抄送: Chikeke ***@***.***&amp;gt;, Mention ***@***.***&amp;gt; 
 主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476) 
 
 
 
 
 
  请问，每个实体都有一个head实体，这是怎么关联起来的？  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年11月7日(周一) 中午11:00  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)  
   
   
   
   
   我没有尝试过数据增强，也不知道四万多条是怎么来的，但是ace05里每个实体都有一个head实体，不知道跟这个有没有关系   
     
     
     
   发自我的iPhone   
     
     
   ------------------ 原始邮件 ------------------   
   发件人: douyameiyingyang ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年11月7日 10:17   
   收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;gt;   
   抄送: Chikeke ***@***.***&amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;gt;   
   主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)   
     
     
     
     
     
    我处理出来差不多也是这么多，我看到有些论文ACE2005预处理出来有40000多条，感觉是做了数据增强，请问这种情况一般是不是加了一个no_relation来处理的？    
       
       
       
    ---原始邮件---    
    发件人: ***@***.***&amp;amp;amp;amp;gt;    
    发送时间: 2022年11月7日(周一) 上午10:11    
    收件人: ***@***.***&amp;amp;amp;amp;gt;;    
    抄送: ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)    
       
       
       
       
     英文一共16312条，有关系的有11582条     
         
         
         
     发自我的iPhone     
         
         
     ------------------ 原始邮件 ------------------     
     发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;amp;gt;     
     发送时间: 2022年11月7日 10:08     
     收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;amp;gt;     
     抄送: Chikeke ***@***.***&amp;amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;amp;gt;     
     主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)     
         
         
         
         
         
      好的，请问ACE2005关系抽取英文部分又有多少条样本呢？      
           
           
           
      ---原始邮件---      
      发件人: ***@***.***&amp;amp;amp;amp;amp;amp;gt;      
      发送时间: 2022年11月7日(周一) 上午10:06      
      收件人: ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      抄送: ***@***.******@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)      
           
           
           
           
       中文有7461条，其中有关系的样本只有4022条       
             
             
             
       发自我的iPhone       
             
             
       ------------------ 原始邮件 ------------------       
       发件人: douyameiyingyang ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;       
       发送时间: 2022年10月30日 19:11       
       收件人: PaddlePaddle/PaddleNLP ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;       
       抄送: Chikeke ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;, Mention ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;       
       主题: Re: [PaddlePaddle/PaddleNLP] 关系抽取数据集转换相关问题 (Issue #2476)       
             
             
             
             
             
               
       @Chikeke 请问，ace2005关系抽取数据集预处理下来有多少个样本？
