### ISSUE TITLE
有关simcse训练，paddle::experimental::CppTypeToDataType问题

### ISSUE THREAD

**Issue by flymushroom** [PaddlePaddle/PaddleNLP#2481]
paddle 2.3,2.2.2都有，paddlenlp2.3.3
情况是这样的，大佬您的语义检索教程里每次input_ids都要自己去改int64，否则就会报类型错，我不太清楚是我操作的问题还是啥问题，如果没问题就打扰了........拜谢

**Comment by wawltor** [comment]
辛苦贴一下整体的报错截图？
以及改成int64之后是修复了问题是吗？

**Comment by w5688414** [comment]
> paddle 2.3,2.2.2都有，paddlenlp2.3.3 情况是这样的，大佬您的语义检索教程里每次input_ids都要自己去改int64，否则就会报类型错，我不太清楚是我操作的问题还是啥问题，如果没问题就打扰了........拜谢

请问具体是那个py文件需要修改？您是windows是不？

**Comment by flymushroom** [comment]
> 辛苦贴一下整体的报错截图？ 以及改成int64之后是修复了问题是吗？

![Snipaste_2022-06-21_18-01-52](https://user-images.githubusercontent.com/90736820/174773666-0faf4f2d-978c-4d6d-8ca2-44a45146bcde.png)
对不起，中间有事没看见，就是大概这种地方（很多类似的地方），不改类型会报下面红色的错误

**Comment by flymushroom** [comment]
> 辛苦贴一下整体的报错截图？ 以及改成int64之后是修复了问题是吗？

是的，改了就可以运行了

**Comment by flymushroom** [comment]
> > paddle 2.3,2.2.2都有，paddlenlp2.3.3 情况是这样的，大佬您的语义检索教程里每次input_ids都要自己去改int64，否则就会报类型错，我不太清楚是我操作的问题还是啥问题，如果没问题就打扰了........拜谢
> 
> 请问具体是那个py文件需要修改？您是windows是不？

已经贴图，大大们辛苦了。
