### ISSUE TITLE
仅训练一条数据，训练时F1=1，推断时和标注结果不一致

### ISSUE THREAD

**Issue by songbaiTalk** [PaddlePaddle/PaddleNLP#2484]
{"id": 35020, "text": "章三从一点科技离职，里斯辞去风篷的CEO职位。6月1日，在夏威夷度假的扎克伯格，接到了他14年的工作搭档雪莉·桑德伯格的辞职电话。 虽然扎克伯格社交帝国一半的瓦片是由桑德伯格垒起来的，但这通电话并不让人意外。在过去几年里，关于“桑德伯格离职”的话题早就在员工之间悄悄发酵。", "relations": [{"id": 151, "from_id": 227, "to_id": 226, "type": "原公司"}, {"id": 152, "from_id": 227, "to_id": 225, "type": "离职人物"}, {"id": 153, "from_id": 236, "to_id": 228, "type": "离职人物"}, {"id": 154, "from_id": 236, "to_id": 229, "type": "原公司"}, {"id": 155, "from_id": 236, "to_id": 230, "type": "原职位"}, {"id": 156, "from_id": 232, "to_id": 231, "type": "离职人物"}, {"id": 157, "from_id": 235, "to_id": 234, "type": "离职人物"}], "entities": [{"id": 225, "start_offset": 0, "end_offset": 2, "label": "人物"}, {"id": 226, "start_offset": 3, "end_offset": 7, "label": "公司"}, {"id": 227, "start_offset": 7, "end_offset": 9, "label": "离职触发词"}, {"id": 228, "start_offset": 10, "end_offset": 12, "label": "人物"}, {"id": 229, "start_offset": 14, "end_offset": 16, "label": "公司"}, {"id": 230, "start_offset": 17, "end_offset": 20, "label": "职位"}, {"id": 231, "start_offset": 52, "end_offset": 59, "label": "人物"}, {"id": 232, "start_offset": 60, "end_offset": 62, "label": "离职触发词"}, {"id": 234, "start_offset": 114, "end_offset": 118, "label": "人物"}, {"id": 235, "start_offset": 118, "end_offset": 120, "label": "离职触发词"}, {"id": 236, "start_offset": 12, "end_offset": 14, "label": "离职触发词"}]}

![middle_img_v2_87ca9b21-acc0-4a7c-ac10-1132ef50c4fg](https://user-images.githubusercontent.com/42830244/173083072-72d1f3c9-2c3e-43d7-9e75-5193554ade46.jpg)
近训练这一条数据，F1=1后，重新推断这条数据，得到结果如下：
![image](https://user-images.githubusercontent.com/42830244/173083355-e2b842ff-18f7-46e9-9f3c-35628f822ada.png)

**Comment by linjieccc** [comment]
您好，F1=1后case中的预测结果如下，麻烦排查下是否正确使用了定制模型：
![image](https://user-images.githubusercontent.com/40840292/173275975-60cf8833-a9f1-4a8e-bdfd-366118032e4b.png)
目前还不能区分字面相同的情况，有两种方法避免：
1）按照句子级别标注，训练和预测，把这种冲突情况降低到最小
2）不用容易字面相同的触发词，比如可以把离职人物作为抽取主体
