### ISSUE TITLE
ERNIE 3.0 在进行离线量化后，预测代码没有办法进行部署

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/PaddleNLP#2486]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/16698950/173170104-43749567-1013-408b-9a3c-9c7d601d7b9a.png">
![image](https://user-images.githubusercontent.com/16698950/173170117-205b5aa1-8dce-498d-8fb5-289849c7e2d3.png)

**Comment by githanyongjin** [comment]
部署的时候cpu预测支持裁剪之后的模型，但是不能直接支持量化后的模型
