### ISSUE TITLE
Ernie3.0 词表存在问题

### ISSUE THREAD

**Issue by Davion-Liu** [PaddlePaddle/PaddleNLP#2487]
vocab.txt
在base和medium版本的ernie3.0词表中，发现重复字符。
下标从零开始，第12084位置和第18005位置的字符重复，都为$这个符号。
请问这个词表中，哪个是正确的。
与这个issue一致:[issue](https://github.com/PaddlePaddle/ERNIE/issues/795)

**Comment by wawltor** [comment]
您好，这个是ERNIE-3.0的词表设计的时候的一个BUG，由于是工具生成的词表没有检查词表的重复性；会使用18005位置，因为在PaddleNLP的Vocab类会对词表进行重复检查，最终会使用两个重复token中的后面一个token

**Comment by Davion-Liu** [comment]
好的谢谢！

**Comment by 1225hao** [comment]
抛异常   ValueError: Invalid name "cmrc2018". Should be one of ['afqmc', 'tnews', 'iflytek', 'ocnli', 'cmnli', 'cluewsc2020', 'csl'].怎么解决
