### ISSUE TITLE
多模态key value打标模型只能输入512个token

### ISSUE THREAD

**Issue by Duum** [PaddlePaddle/PaddleNLP#2490]
多模态key value打标模型只能输入512个token，这个显然是不合理的，不知道这个512限制，有没有计划解除

**Comment by wawltor** [comment]
具体是使用哪份代码，辛苦提供一下链接

**Comment by Duum** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/layoutlmv2/modeling.py

**Comment by wawltor** [comment]
这个是没有办法限制不定长，这个和整个预训练模型有关，在BERT、ERNIE这样的预训练模型结构中有一个Position id的限制，需要知道这个id在什么位置，才能不同刻画Token的关系，这个是预训练的一个特性。后续我们看看能不能支持更大的模型，来支持更长的字符串输入

**Comment by yingyibiao** [comment]
这个在我们的计划中了，我们计划提供模型最大长度扩充的功能。

**Comment by yingyibiao** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2513
