### ISSUE TITLE
UIE通用信息抽取的关系抽取和事件抽取任务有什么不同?

### ISSUE THREAD

**Issue by YYGe01** [PaddlePaddle/PaddleNLP#2491]
您好:
问下` https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie` 的两个任务,关系抽取和事件抽取有什么区别?

我只看到关系抽取和事件抽取的schema结构一模一样,  后面的数据处理, 模型训练和预测结果格式也一样,

只是事件抽取的schema只是加了一个xx触发词而已, 如果一样, 我做事件抽取,不加触发词三个字, 把这个任务当作关系抽取来做, 会有什么问题吗.

不知道我理解的是否正确, 谢谢!

**Comment by wawltor** [comment]
是的，关系抽取和事件抽取的schema是一样的；事件抽取和关系抽取最大的区别在于是一个事件(动词)来触发的，例如裁员(事件)的人数，关系抽取是头实体来触发一个关系，例如xxx公司(头实体)裁员的人数；
使用关系抽取没有问题，我们也是建议尽量使用关系抽取的方式来做信息抽取
