### ISSUE TITLE
运行ernie3.0目录下的微调程序run_qa.py时出错

### ISSUE THREAD

**Issue by Jaybore** [PaddlePaddle/PaddleNLP#2493]
萌新求助：
在使用该程序：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_qa.py
运行ernie模型时可以正常进行微调，
但是当把模型名换为'bert-base-chinese'等其它模型时程序便会报错
求解怎么破？
![image](https://user-images.githubusercontent.com/100829033/173279392-3d807b02-e922-40b4-bbe0-e688baebbaa8.png)

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/tokenizer_utils.py#L1337-L1340

看起来这里是预处理的时候，有token没有找到，@yingyibiao 这个是不是触发了上面"##"字符的逻辑，导致问题？
```python
            if token[:2] == '##':
                token = token[2:]

            start = text[offset:].index(token) + offset
```

**Comment by Jaybore** [comment]
看起来是这样的，请问如何进行规避？ ：）

**Comment by ZHUI** [comment]
> 看起来是这样的，请问如何进行规避？ ：）

辛苦您测试一下，就在报错前后打印看看，确认下是不是这个问题？
```python
            print(token)
            if token[:2] == '##':
                token = token[2:]
            print(token)
            start = text[offset:].index(token) + offset
```

**Comment by Jaybore** [comment]
[log.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8888842/log.txt)
这个是运行时的呈现

**Comment by Jaybore** [comment]
> 

请问从这个log.txt文件中可以确定是这里出的问题嘛？
已经被卡了好几天了 ：(

**Comment by joey12300** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_qa.py

您好！感谢您提供错误case，这边已经提了一个PR修复，您可以先在本地按照这个pr的修改进行修复。PR：https://github.com/PaddlePaddle/PaddleNLP/pull/2508

**Comment by Jaybore** [comment]
万分感谢！
