### ISSUE TITLE
ERNIE3.0如何本地加载？

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/PaddleNLP#2506]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
您好，请问ERNIE3.0模型如何本地加载？

**Comment by yingyibiao** [comment]
可以参考这个FAQ：https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#q1-3-paddlenlp

**Comment by Chucy2020** [comment]
> 可以参考这个FAQ：https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#q1-3-paddlenlp

您好，我尝试将你们提供的下载网址将ernie-3.0-xbase-zh文件下载保存到文件夹，但是使用
MODEL_NAME = "ernie-3.0-xbase-zh"
ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME)时报错，无法加载，请问这是怎么回事？

**Comment by yingyibiao** [comment]
可以通过 ernie_model.save_pretrained("./checkpoint/') 保存模型，
之后可以 ernie_model.from_pretrained("./checkpoint/') 加载模型。

**Comment by Chucy2020** [comment]
> 可以通过 ernie_model.save_pretrained("./checkpoint/') 保存模型， 之后可以 ernie_model.from_pretrained("./checkpoint/') 加载模型。

感谢您的回复和提醒，我是想加载使用你们提供的ernie-3.0-xbase-zh预训练模型，已经通过你们提供的网址下载到本地，但是不知道怎么加载使用，请问你们这个刚公布的ernie-3.0-xbase-zh预训练模型是不可以直接使用ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME)加载吗？

**Comment by yingyibiao** [comment]
可以通过 ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME) 加载

**Comment by yingyibiao** [comment]
总结一下就是：
1. 先通过 ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME) 联网加载模型
2. 接着通过 ernie_model.save_pretrained("./checkpoint/') 保存模型和配置文件到本地（./checkpoint/目录）
3. 最后可以通过 ernie_model.from_pretrained("./checkpoint/') 进行模型的本地加载（./checkpoint/目录）

**Comment by Chucy2020** [comment]
> 总结一下就是：
> 
> 1. 先通过 ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME) 联网加载模型
> 2. 接着通过 ernie_model.save_pretrained("./checkpoint/') 保存模型和配置文件到本地（./checkpoint/目录）
> 3. 最后可以通过 ernie_model.from_pretrained("./checkpoint/') 进行模型的本地加载（./checkpoint/目录）

        您好，感谢您耐心回答，如果可以直接联网的话应该是可以的，我现在没法联网使用，因为内网没法联网，所以只能根据你们代码中提供的地址下载字典和模型，以及复制你们代码中的config内容当作config.json文件，之后加载，但是我这个加载一直有问题。
        但是您刚说可以加载，所以可能是我自己的问题，不知是不是我的模型下载文件的路径有问题或者其他，我正在排查，很感谢您的回复。

**Comment by xiaocod** [comment]
你好，请问如何对下载到本地的ernie3.0-zeus 进行精调？

**Comment by xiaocod** [comment]
你好，如何用自己的数据集训练预训练模型比如ERNIE3.0模型？

**Comment by xiaocod** [comment]
你好，如何用自己的数据集训练预训练模型比如ERNIE3.0模型？

**Comment by xiaocod** [comment]
你好，如何用自己的数据集训练下载到本地的ERNIE3.0预训练模型？可以对下载到本地的ERNIE3.0预训练模型进行自定义的微调或者精调吗？
