### ISSUE TITLE
applications/experimental/pipelines/examples/question-answering 官方源码运行报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#2510]
linux和windows系统都报同样的错误，日志见附件，看下是什么原因，谢谢
[log.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8898444/log.txt)

**Comment by sunshineyg2018** [comment]
sqlalchemy 的错误？

**Comment by AI-Mart** [comment]
是的，不知道什么原因，官方源码运行的，还没做定制化更改，附件是我用docker在linux制作的镜像，可以运行复现下我的问题
[deploy1.zip](https://github.com/PaddlePaddle/PaddleNLP/files/8899455/deploy1.zip)
下

**Comment by AI-Mart** [comment]
docker镜像安装报错，conda本地安装是可以运行的，官方的文档有些地方建议优化更新下：1、requirments要包配置全，见附件，2、步骤上做下补充说明，先pip install -r requirments，然后执行pip install paddlepaddle-gpu==2.3.0.post101 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html，再执行python setup.py install
[requirements.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8908072/requirements.txt)

**Comment by AI-Mart** [comment]
[requirements.txt](https://github.com/PaddlePaddle/PaddleNLP/files/8908126/requirements.txt)

**Comment by tianxin1860** [comment]
非常感谢您的反馈，我们更新下文档。

**Comment by AI-Mart** [comment]
docker 已经可以运行，整理在链接https://blog.csdn.net/qq_15821487/article/details/125282152?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125282152%22%2C%22source%22%3A%22qq_15821487%22%7D&ctrtid=6KoKf

**Comment by chenxiaozeng** [comment]
> docker 已经可以运行，整理在链接https://blog.csdn.net/qq_15821487/article/details/125282152?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125282152%22%2C%22source%22%3A%22qq_15821487%22%7D&ctrtid=6KoKf

@AI-Mart 点赞，欢迎帮PaddleNLP提个PR，优化下文档体验~

**Comment by AI-Mart** [comment]
> > docker 已经可以运行，整理在链接https://blog.csdn.net/qq_15821487/article/details/125282152?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125282152%22%2C%22source%22%3A%22qq_15821487%22%7D&ctrtid=6KoKf
> 
> @AI-Mart 点赞，欢迎帮PaddleNLP提个PR，优化下文档体验~


好的
