### ISSUE TITLE
小样本学习添加了词后又要加新的词,必须重新从头训练吗

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleNLP#2512]
如题

**Comment by tianxin1860** [comment]
是说词典更新加入了新的单词么？

**Comment by sunshineyg2018** [comment]
> 是说词典更新加入了新词么？
嗯，就是我已经用一些词训练出了一个best_model,但是我发现自己漏掉了一些,我想在我best_model 基础上再加

**Comment by sunshineyg2018** [comment]
> 是说词典更新加入了新词么？

@tianxin1860

**Comment by tianxin1860** [comment]
这样的话建议基于 best_model 做参数初始化，然后继续训练。

**Comment by sunshineyg2018** [comment]
> 这样的话建议基于 best_model 做参数初始化，然后继续训练。

我是准备替换 uie-base 下的文件？可以这样操作吗 

基于best_model 是通过 --init_from_ckpt 这个参数吗？
这样操作 会重复训练以前已经训练过的数据吗？
