### ISSUE TITLE
PaddleNLP动态图中cpu只能使用单核

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#252]

**Comment by ZHUI** [comment]
您好！
目前Paddle动态图，暂时还不支持cpu并行计算。正在开发中。

**Comment by ghost** [comment]
> 您好！
> 目前Paddle动态图，暂时还不支持cpu并行计算。正在开发中。

今年有希望吗？

**Comment by ZHUI** [comment]
有计划的，分布式的同学正在开发中。功能ready后，PaddleNLP会第一时间跟进支持cpu并行。
