### ISSUE TITLE
ERNIE3.0模型性能问题

### ISSUE THREAD

**Issue by GZ1220** [PaddlePaddle/PaddleNLP#2524]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.3，PaddlePaddle2.3.0
2）系统环境：Linux系统，python版本3.7，cpu为Inter(R) Xeon(R) Silver 4214，线程数为12，batch_size=32
在使用ernie-3.0-medium-zh模型进行训练的参数与官方文档一致的前提下，训练好的模型进行模型推理后，预测的代码也与官方一致，数据集为Tnews，在ernie-3.0-medium-zh+fp32预测时的吞吐量仅为136.95，ernie-3.0-medium-zh+fp32+剪裁的吞吐量仅为172.43。
在运行infer.py调用量化后的模型时，一直出现段错误，请问这是为何呢？仅仅CPU不一样，性能会相差这么多吗？

**Comment by wawltor** [comment]
1. 不同机器的性能差别是比较大的
2. infer.py这个具体报什么错误了，辛苦可以截图给我们看看

**Comment by GZ1220** [comment]
![批注 2022-06-16 092726](https://user-images.githubusercontent.com/90749831/173972131-d1f37fe6-f38f-428d-a8a8-9bc1ac1172c7.png)
以上为截图，我的运行日志是不报错的，但是加载完模型就出现了  段错误  。
官方的CPU为cpu为Intel(R) Xeon(R) Gold 6271C ，主频为2.6ghz，我的只比它低了0.2ghz，性能不应该差这么多呀

**Comment by wawltor** [comment]
> ![批注 2022-06-16 092726](https://user-images.githubusercontent.com/90749831/173972131-d1f37fe6-f38f-428d-a8a8-9bc1ac1172c7.png) 以上为截图，我的运行日志是不报错的，但是加载完模型就出现了 段错误 。 官方的CPU为cpu为Intel(R) Xeon(R) Gold 6271C ，主频为2.6ghz，我的只比它低了0.2ghz，性能不应该差这么多呀

是说复现不了readme中的结果是吗？具体是哪项指标了

**Comment by GZ1220** [comment]
readme中ernie-3.0-medium-zh+fp32和ernie-3.0-medium-zh+fp32+剪裁在tnews数据集上使用CPU预测的性能。
官方性能为311.95和408.65，而我这里只有136.95和172.43，batch_size为32，cpu线程数为12

**Comment by GZ1220** [comment]
段错误 是我在量化过后进行部署时出现的问题，和性能无关。。

**Comment by yeliang2258** [comment]
请问你的CPU型号是？

**Comment by GZ1220** [comment]
cpu为Inter(R) Xeon(R) Silver 4214

**Comment by yeliang2258** [comment]
CPU的推理速度不只是依据主频来判断，还得看cpu支持的指令集， 比如avx2, avx512, avx512vnni等

**Comment by GZ1220** [comment]
请问咱们官网的CPU支持的指令集有哪些呢，我这边支持SSE4.2，AVX，AVX2，AVX-512，64bit

**Comment by yeliang2258** [comment]
6271C支持avx2, avx512, avx512vnni

**Comment by GZ1220** [comment]
如果是指令集不一样而造成的性能差异，除了换CPU还有办法提升吗？

**Comment by yeliang2258** [comment]
请问你运行infer.py时的指令是？

**Comment by GZ1220** [comment]
就python3 infer.py --model_path '...'

**Comment by yeliang2258** [comment]
你试试这个：python3 infer.py --model_path '...'  --device cpu  --num_threads 8 --use_onnxruntime True --perf

**Comment by GZ1220** [comment]
用了您发的运行命令，线程数为8的时候吞吐量变小了，medium-zh+fp32+裁剪吞吐量为125，线程数为12时，和之前没有太大变化，吞吐量为170
