### ISSUE TITLE
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by ChaohuaZhang** [PaddlePaddle/PaddleNLP#2525]
uie finetune时报这个错怎么解决啊
![image](https://user-images.githubusercontent.com/65476824/173781531-4fba0ac8-55b9-4a57-93ca-887d53ba1d3c.png)

**Comment by wawltor** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/16698950/173800025-df587824-067a-4de9-967e-3eb9aae4eb34.png">
可以降低一下papandas的版本

**Comment by wawltor** [comment]
可以更新pandas的版本到1.3.4版本

**Comment by tianmafly** [comment]
pandas就是1.3.4还是报这个错误。python3.7.4.
一开始的错误是：
 from _lzma import *
ModuleNotFoundError: No module named '_lzma'
![Screenshot from 2022-07-02 19-06-23](https://user-images.githubusercontent.com/38370307/176998131-af83eb75-168f-4b06-ad5b-9b3d12dde0a0.png)
按照网上说的，改了lzma.py文件：
把 from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
改成
try:
    from _lzma import *
    from _lzma import _encode_filter_properties, _decode_filter_properties
except:
    from backports.lzma import *
    from backports.lzma import _encode_filter_properties, _decode_filter_properties
不报错误了from _lzma import *
ModuleNotFoundError: No module named '_lzma'。
开始报
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input' 
如何解决？

**Comment by tianmafly** [comment]
@wawltor @ChaohuaZhang 请问解决了吗，怎么解决的？谢谢哈。

**Comment by ChaohuaZhang** [comment]
> @wawltor @ChaohuaZhang 请问解决了吗，怎么解决的？谢谢哈。



> @wawltor @ChaohuaZhang 请问解决了吗，怎么解决的？谢谢哈。

应该是python环境依赖有问题，拉paddlepaddle镜像构建容器运行吧

**Comment by tianmafly** [comment]
已解决，python3.7.4改为python3.8就可以了

**Comment by Adherer** [comment]
python3.10.9 遇到了一样的问题，不太方便降Python版本，这块有解决方案吗？

**Comment by Cats-smile** [comment]
你好，这个问题您解决了吗

**Comment by Cats-smile** [comment]
> 

我也是3.10，您解决了吗

**Comment by couldn** [comment]
可以试试重装下python，我的解决了

**Comment by galen2027** [comment]
我是python

> 
你的问题解决了吗？ 我也是3.10.12的，如果实在找不到解决帮扶，我打算重新编译安装，只是安装的依赖较多，是麻烦事。
