### ISSUE TITLE
微调Albert模型时 报错 not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Jaybore** [PaddlePaddle/PaddleNLP#2529]
![image](https://user-images.githubusercontent.com/100829033/173797367-e94f3649-fd49-4323-953b-8ee9dbaf5565.png)
看起来是在加载模型时遇到的错误？ 

微调程序使用的是
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_qa.py
这个程序可以对ernie bert等模型进行正常微调

**Comment by LiuChiachi** [comment]
您好！感谢反馈问题，
为了快速解决您的问题，
https://github.com/PaddlePaddle/PaddleNLP/blob/4a23b50ade85dae6796591f6c4fdba9b0eae5183/paddlenlp/transformers/albert/modeling.py#L1623
您可以在您的paddlenlp包的这一个文件这一行给num_labels加个默认参数2：
```python
   def __init__(self, albert, num_labels=2):
```
并将
https://github.com/PaddlePaddle/PaddleNLP/blob/4a23b50ade85dae6796591f6c4fdba9b0eae5183/model_zoo/ernie-3.0/run_qa.py#L317
和
https://github.com/PaddlePaddle/PaddleNLP/blob/4a23b50ade85dae6796591f6c4fdba9b0eae5183/model_zoo/ernie-3.0/run_qa.py#L393

`max_seq_len`改成`max_length`

在仓库内我们也会尽快修复，感谢关注:)

**Comment by Jaybore** [comment]
非常感谢！

**Comment by Jaybore** [comment]
![image](https://user-images.githubusercontent.com/100829033/176861041-9c85a663-9512-406f-b7a7-e744f01effb2.png)
在修改代码之后出现了如上的报错 请问如何调整？
