### ISSUE TITLE
如何将模型下载到本地加载？

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/PaddleNLP#2531]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

请问上述模型能否下载后在本地加载？如何加载已经下载的模型？本地加载时除了.pdparams模型文件还需要什么文件，文件怎么命名呢？

**Comment by wawltor** [comment]
https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#4-1 

可以看一下这块的文档，可以本地加载模型，除了.pdparams，还在加载相应的模型配置，具体可以参考上面的文档

**Comment by Chucy2020** [comment]
> https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#4-1
> 
> 可以看一下这块的文档，可以本地加载模型，除了.pdparams，还在加载相应的模型配置，具体可以参考上面的文档
![image](https://user-images.githubusercontent.com/73978694/173828088-3ddb0240-7ee4-470b-baef-3b2e7e1c7391.png)
您好这是的加载时出现的问题，请问这是由于什么原因？左上方是config,.pdparams,vocab文件，下面是我加载时使用的代码
![image](https://user-images.githubusercontent.com/73978694/173828715-e6d95e49-b5d9-4e6e-8975-e63f8e148147.png)
https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#4-1

**Comment by wawltor** [comment]
from_pretrained 填写路径，而不是名字

**Comment by Chucy2020** [comment]
> from_pretrained 填写路径，而不是名字

我的这个输入的是路径，请问除了上述三个文件还需要其他的吗？以及是我命名有问题吗？

**Comment by wawltor** [comment]
> > from_pretrained 填写路径，而不是名字
> 
> 我的这个输入的是路径，请问除了上述三个文件还需要其他的吗？以及是我命名有问题吗？

看起来路径名有问题，因为和之前的模型名字同名了，这样还是走下载的方式

**Comment by daozhi0921** [comment]
您好， 我这边对于plato-mini本地加载有一个问题请教一下~

**- 版本、环境信息**
paddlehub           2.2.0
paddlenlp            2.3.3
paddlepaddle      2.3.0
Linux，python3.6.13

问题：想要将模型放到指定路径并进行加载，目前尝试了以下方式：  
（1）指定paddlehup文件夹所在的路径，   
         model_1 = hub.Module(directory='C:/Users/Administrator/.paddlehub/modules/plato-mini')  【不会报错，因为路径为之前代码执行过程中模型的默认路径】    
         model_2 = hub.Module(directory='C:/Users/**ml_models**/.paddlehub/modules/plato-mini')  【会报错，将.paddlehub 文件夹移动到指定的ml_models中，代码预测的时候，会继续下载.paddlenlp 和 .paddlehup 到默认路径C:/Users/Administrator 下，并报错， 也就是说我指定没有起作用】   
     
（2）利用paddlenlp， 执行 model =  UnifiedTransformerModel.from_pretrained('C:/Users/**ml_models**/.paddlenlp/models/plato-mini')，**报错**：assert is_url(url), "downloading from {} not a url".format(url)
