### ISSUE TITLE
doc_vqa 项目问题

### ISSUE THREAD

**Issue by ljcljc** [PaddlePaddle/PaddleNLP#2535]
我在进行第6步时 “跨模态阅读理解模块”

运行 bash run_test.sh 后备箱怎么开
提示 FileNotFoundError: [Errno 2] No such file or directory: './data/decode_res.json'

文档中没有提示哪里可以生成decode_res.json这个文件。

另外，在阅读理解训练集中的训练数据格式是否可以说明一下，document_id的图片链接在本地我都没找到，请问是否训练集有错误？谢谢
{"document_id": "data_labeled_10_weilai/doc_ocrs/demo_pics2_00008.png", "ocr_results": [{"id": "data_labeled_20220415/docvqa-crowdsourcing-20220415/cf227a2f9112234dd5d255bf738e16bf/00008.png", "text": "解锁", "bbox": [[2521.0, 96.0], [2658.0, 96.0], [2658.0, 180.0], [2521.0, 180.0]], "ocr_confidence_score": 0.9996302723884583}

**Comment by ljcljc** [comment]
我看了应该是训练后会生成这个decode_res.json文件的，但是我的训练结束后没有生成，也没有报错，就这样结束了，请问是为什么

06/16/2022 14:50:39 - INFO - __main__ -   [epoch 0/50][iter: 0/7] lr: 0.00000, train loss: 185.56476,
06/16/2022 14:51:05 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-40
06/16/2022 14:51:10 - INFO - __main__ -   [epoch 7/50][iter: 1/7] lr: 0.00003, train loss: 19.58628,
06/16/2022 14:51:31 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-80
06/16/2022 14:51:41 - INFO - __main__ -   [epoch 14/50][iter: 2/7] lr: 0.00002, train loss: 10.21441,
06/16/2022 14:51:59 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-120
06/16/2022 14:52:14 - INFO - __main__ -   [epoch 21/50][iter: 3/7] lr: 0.00002, train loss: 3.07817,
06/16/2022 14:52:26 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-160
06/16/2022 14:52:55 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-200
06/16/2022 14:52:55 - INFO - __main__ -   [epoch 28/50][iter: 4/7] lr: 0.00002, train loss: 15.77061,
06/16/2022 14:53:25 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-240
06/16/2022 14:53:30 - INFO - __main__ -   [epoch 35/50][iter: 5/7] lr: 0.00001, train loss: 0.66145,
06/16/2022 14:53:55 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-280
06/16/2022 14:54:06 - INFO - __main__ -   [epoch 42/50][iter: 6/7] lr: 0.00001, train loss: 1.11934,
06/16/2022 14:54:23 - INFO - __main__ -   Saving model checkpoint to output/checkpoint-320

**Comment by ljcljc** [comment]
我发现aistudio里的文件和github上的不一致，是不是更新过版本了，有一个decode_res.json文件github上没有

**Comment by 1649759610** [comment]
同学你好：

1. decode_res文件在调用评估evaluate函数的时候会默认生成，即在执行评估脚本run_test.sh，会生成
   a. 如果遇到decode_res文件不存在的情况，请确保是否evaluate函数是否正常执行完成。
   b. 训练过程中，如果没有调用evaluate函数，是不会生成该文件的
2. 目前该数据集中存在一些多余的字段，请重点关注question，document，document_bbox， labels, 其他的字段暂时可以忽略。
3. 目前github上更新过一版，decode_res文件已经设置成了参数，可以在Extraction/run_test.sh文件中通过参数save_path进行指定。备注：如果该文件名成有变化，同时也需要在view.py的文件中进行更新

如果还有问题，欢迎与我们继续沟通。

**Comment by 1649759610** [comment]
@ljcljc 同学你好：

1. decode_res文件在调用评估evaluate函数的时候会默认生成，即在执行评估脚本run_test.sh，会生成
    a. 如果遇到decode_res文件不存在的情况，请确保是否evaluate函数是否正常执行完成。
    b. 训练过程中，如果没有调用evaluate函数，是不会生成该文件的
2. 目前该数据集中存在一些多余的字段，请重点关注question，document，document_bbox， labels, 其他的字段暂时可以忽略。
3. 目前github上更新过一版，decode_res文件已经设置成了参数，可以在Extraction/run_test.sh文件中通过参数save_path进行指定。备注：如果该文件名成有变化，同时也需要在view.py的文件中进行更新

如果还有问题，欢迎与我们继续交流。

**Comment by ljcljc** [comment]
我在运行Extration/run_test.sh的时候，还是报错没有这个文件。请问是哪里的问题呢，谢谢

[2022-06-22 15:54:54,698] [    INFO] - Already cached /Users/jiechaoli/.paddlenlp/models/layoutxlm-base-uncased/sentencepiece.bpe.model
100%|██████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 682.11it/s]
***** Running evaluation  *****
  Num examples = 1
  Batch size = 1
Traceback (most recent call last):
  File "./run_docvqa.py", line 455, in <module>
    main(args)
  File "./run_docvqa.py", line 93, in main
    evaluate(
  File "./run_docvqa.py", line 390, in evaluate
    outputs = model(
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/jiechaoli/Documents/zhipei/project/PaddleNLP/applications/doc_vqa/Extraction/model.py", line 194, in forward
    outputs = self.layoutxlm(
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 810, in forward
    visual_emb = self._calc_img_embeddings(
  File "/Users/jiechaoli/miniconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/layoutxlm/modeling.py", line 725, in _calc_img_embeddings
    self.visual(image.astype(paddle.float32)))
AttributeError: 'NoneType' object has no attribute 'astype'
Traceback (most recent call last):
  File "view.py", line 46, in <module>
    with open(res_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/decode_res.json'

**Comment by ljcljc** [comment]
如何使用doccano来标注我自己的训练数据，请问是否有一些参考文档，谢谢

**Comment by 1649759610** [comment]
同学你好，

这里没有生成decode_res.json，是因为在执行run_test.sh脚本中的run_docvqa.py命令时出现问题，请按以下操作排查一下，确保python3 run_docvqa.py正确执行完成，正确执行后会生成decode_res.json文件。

1. 确保已经使用paddleOCR正确解析图片，并生成demo_test.json，放于data目录下
2. 可以进一步排查一下run_docvqa.py的输入是否正确

也可以参考AiStudio教程，从上到下依次运行：
https://aistudio.baidu.com/aistudio/projectdetail/4049663?channelType=0&channel=0

**Comment by 1649759610** [comment]
> 如何使用doccano来标注我自己的训练数据，请问是否有一些参考文档，谢谢

目前没有标注文档，可以参考如下步骤进行标注：
1. 使用paddleOCR解析图片，并结合LayoutXLM的tokenizer将解析的文字进行分词，同时保证每个词具有合适的bbox布局信息，可参考OCR_proecss/ocr_process.py文件
2. 设定问题，和标注对应的答案。在执行完run_test.sh后，会生成data/demo_test.json文件，可参考该文件格式进行标注，请注意标注的主要字段是document，document_bbox, question 和 label

**Comment by JDanielWu** [comment]
没有标注工具，纯人工成本好高啊
