### ISSUE TITLE
ERNIE 3.0 triton deploy 失败

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/PaddleNLP#2541]
nvcr.io/nvidia/tritonserver:21.10-py3

Python 3.8.10
paddlenlp           2.3.3
paddlepaddle-gpu    2.3.0.post111

按照https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/deploy/triton/README.md

文件进行环境准备，部署命令：

```
tritonserver --model-repository=/home/work/deploy/models --model-control-mode=explicit --load-model=ernie_tokencls
```
程序会一直卡在这里，也不报错
```
I0616 12:07:36.160177 11581 metrics.cc:298] Collecting metrics for GPU 0: Tesla V100-PCIE-32GB
I0616 12:07:36.664980 11581 libtorch.cc:1092] TRITONBACKEND_Initialize: pytorch
I0616 12:07:36.665025 11581 libtorch.cc:1102] Triton TRITONBACKEND API version: 1.6
I0616 12:07:36.665066 11581 libtorch.cc:1108] 'pytorch' TRITONBACKEND API version: 1.6
2022-06-16 12:07:37.183610: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0616 12:07:37.258054 11581 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I0616 12:07:37.258105 11581 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.6
I0616 12:07:37.258118 11581 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.6
I0616 12:07:37.258127 11581 tensorflow.cc:2210] backend configuration:
{}
I0616 12:07:37.260896 11581 onnxruntime.cc:1999] TRITONBACKEND_Initialize: onnxruntime
I0616 12:07:37.260925 11581 onnxruntime.cc:2009] Triton TRITONBACKEND API version: 1.6
I0616 12:07:37.260936 11581 onnxruntime.cc:2015] 'onnxruntime' TRITONBACKEND API version: 1.6
I0616 12:07:37.295621 11581 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I0616 12:07:37.295667 11581 openvino.cc:1203] Triton TRITONBACKEND API version: 1.6
I0616 12:07:37.295676 11581 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.6
I0616 12:07:37.608747 11581 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f3c78000000' with size 268435456
I0616 12:07:37.610392 11581 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0616 12:07:37.617398 11581 model_repository_manager.cc:1022] loading: ernie_tokencls_model:1
I0616 12:07:37.717707 11581 model_repository_manager.cc:1022] loading: ernie_tokenizer:1
I0616 12:07:37.718704 11581 onnxruntime.cc:2058] TRITONBACKEND_ModelInitialize: ernie_tokencls_model (version 1)
I0616 12:07:37.725323 11581 onnxruntime.cc:2101] TRITONBACKEND_ModelInstanceInitialize: ernie_tokencls_model_0 (GPU device 0)
```

**Comment by heliqi** [comment]
1. 有把模型放在 ernie_tokencls_model/1/ 目录下吗？
2. 启动容器时有设置shm大小吗？ triton的python后端默认需要64M

**Comment by thomaszheng** [comment]
@heliqi 模型路径是没有问题，之前试过也有问题

```
tritonserver --model-repository=/models --backend-config=python,shm-default-byte-size=10485760
```

又试了试`--backend-config=python,shm-default-byte-size=24485760` 可以执行，不过报新的错误：

```
I0617 02:35:19.907372 5202 metrics.cc:298] Collecting metrics for GPU 0: Tesla V100-PCIE-32GB
I0617 02:35:20.236833 5202 libtorch.cc:1092] TRITONBACKEND_Initialize: pytorch
I0617 02:35:20.236862 5202 libtorch.cc:1102] Triton TRITONBACKEND API version: 1.6
I0617 02:35:20.236869 5202 libtorch.cc:1108] 'pytorch' TRITONBACKEND API version: 1.6
2022-06-17 02:35:20.615644: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
I0617 02:35:20.667227 5202 tensorflow.cc:2170] TRITONBACKEND_Initialize: tensorflow
I0617 02:35:20.667260 5202 tensorflow.cc:2180] Triton TRITONBACKEND API version: 1.6
I0617 02:35:20.667267 5202 tensorflow.cc:2186] 'tensorflow' TRITONBACKEND API version: 1.6
I0617 02:35:20.667273 5202 tensorflow.cc:2210] backend configuration:
{}
I0617 02:35:20.793296 5202 onnxruntime.cc:1999] TRITONBACKEND_Initialize: onnxruntime
I0617 02:35:20.793329 5202 onnxruntime.cc:2009] Triton TRITONBACKEND API version: 1.6
I0617 02:35:20.793336 5202 onnxruntime.cc:2015] 'onnxruntime' TRITONBACKEND API version: 1.6
I0617 02:35:20.929568 5202 openvino.cc:1193] TRITONBACKEND_Initialize: openvino
I0617 02:35:20.929600 5202 openvino.cc:1203] Triton TRITONBACKEND API version: 1.6
I0617 02:35:20.929614 5202 openvino.cc:1209] 'openvino' TRITONBACKEND API version: 1.6
I0617 02:35:21.283564 5202 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7ff0d0000000' with size 268435456
I0617 02:35:21.284986 5202 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0617 02:35:21.292204 5202 model_repository_manager.cc:1022] loading: ernie_tokencls_model:1
I0617 02:35:21.392410 5202 model_repository_manager.cc:1022] loading: ernie_tokenizer:1
I0617 02:35:21.393201 5202 onnxruntime.cc:2058] TRITONBACKEND_ModelInitialize: ernie_tokencls_model (version 1)
I0617 02:35:21.397773 5202 onnxruntime.cc:2101] TRITONBACKEND_ModelInstanceInitialize: ernie_tokencls_model_0 (GPU device 0)
I0617 02:35:21.573198 5202 model_repository_manager.cc:1022] loading: ernie_tokencls_postprocess:1
I0617 02:35:24.747778 5202 onnxruntime.cc:2135] TRITONBACKEND_ModelInstanceFinalize: delete instance state
I0617 02:35:24.747836 5202 onnxruntime.cc:2081] TRITONBACKEND_ModelFinalize: delete model state
E0617 02:35:24.747857 5202 model_repository_manager.cc:1186] failed to load 'ernie_tokencls_model' version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 222: the provided PTX was compiled with an unsupported toolchain. ; GPU=0 ; hostname=ms-34805-portal-bert-pp-20220617-0617095205-5b5d687fd8-xsqg8 ; expr=cudaDeviceSynchronize(); 
```

看情况是加载转换的onnx的模型时出现的问题？

**Comment by heliqi** [comment]
@thomaszheng 有报错代表跑起来了， 之前卡住应该是shm不够。当前报错可能是两个问题(很大概率是第一个问题，先检查driver):
1. 你机器的CUDA driver版本太低了， 检查下driver版本。21.10的要求是

Release 21.10 is based on [NVIDIA CUDA 11.4.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) with [cuBLAS 11.6.5.2](https://docs.nvidia.com/cuda/cublas/index.html), which requires [NVIDIA Driver](http://www.nvidia.com/Download/index.aspx?lang=en-us) release 470 or later. However, if you are running on Data Center GPUs (formerly Tesla), for example, T4, you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), or 460.27 (or later R460).
The CUDA driver's compatibility package only supports particular drivers. [3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#fnsrc_3)


2.  ERNIE 3.0模型通过最新的paddle2onnx转化后，onnx version比较高， 有些模型可能需要1.10.0版本及以上的onnxruntime。 
    21.10版本的triton镜像内的onnxruntime版本是1.9.0，需要升级onnxruntime版本(有些erinie模型不需要升级)

**Comment by heliqi** [comment]
@thomaszheng 升级onnxruntime版本有两个方法解决：
一.下载22.03的Triton镜像，其他都按文档操作
二. 替换21.10镜像中的backend： 分源码编译onnxruntime backend 和 只替换onnxruntime.so两种方式 (2选1)
1. 进入镜像，下载[github官网](https://github.com/microsoft/onnxruntime/releases) 1.10.0 及以上的压缩包并解压,比如:
    wget https://github.com/microsoft/onnxruntime/releases/download/v1.10.0/onnxruntime-linux-x64-gpu-1.10.0.tgz
    tar -zxvf onnxruntime-linux-x64-gpu-1.10.0.tgz
    将onnxruntime-linux-x64-gpu-1.10.0/lib中的.so替换 /opt/tritonserver/backends/onnxruntime/ 中的 libonnxruntime.so
2. 源码编译 ： 参照[官网文档](https://github.com/triton-inference-server/onnxruntime_backend)代码,并切换到21.10分支，进行编译, 编译时需要制定onnxruntime版本,修改官网cmake指令为：
    cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_ENABLE_ONNXRUNTIME_TENSORRT=ON -DTRITON_ONNXRUNTIME_LIB_PATHS=onnxruntime-linux-x64-gpu-1.10.0/lib/ -DTRITON_ONNXRUNTIME_INCLUDE_PATHS=onnxruntime-linux-x64-gpu-1.10.0/include  -DTRITON_BACKEND_REPO_TAG=r21.10 -DTRITON_CORE_REPO_TAG=r21.10 -DTRITON_COMMON_REPO_TAG=r21.10 ..

**Comment by ZeyuChen** [comment]
> @thomaszheng 有报错代表跑起来了， 之前卡住应该是shm不够。当前报错可能是两个问题:
> 
> 1. 你机器的CUDA driver版本太低了， 检查下driver版本。21.10的要求是
> 
> Release 21.10 is based on [NVIDIA CUDA 11.4.2](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) with [cuBLAS 11.6.5.2](https://docs.nvidia.com/cuda/cublas/index.html), which requires [NVIDIA Driver](http://www.nvidia.com/Download/index.aspx?lang=en-us) release 470 or later. However, if you are running on Data Center GPUs (formerly Tesla), for example, T4, you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), or 460.27 (or later R460). The CUDA driver's compatibility package only supports particular drivers. [3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#fnsrc_3)
> 
> 2. ERNIE 3.0模型通过最新的paddle2onnx转化后，onnx version比较高， 可能需要1.10.0版本及以上的onnxruntime。
>    21.10版本的triton镜像内的onnxruntime版本是1.9.0，需要升级onnxruntime版本

这个问题看记一下到时提给NV的同学

**Comment by thomaszheng** [comment]
@heliqi 
我这边通过下载`onnxruntime-linux-x64-gpu-1.10.0.tgz`替换so的方式，是不行的。
通过升级22.04的镜像可以了。
还有就是这个目录`model_zoo/ernie-3.0/deploy/triton/models/ernie_tokencls` 下面是不是需要建个模型版本的目录，比如现在的例子里面的`1`,这个目录感觉也可以在git里面维护吧

**Comment by heliqi** [comment]
1. 可能你的机器不匹配那个压缩包，需要从源码编译onnxruntime-backend。 升级到22.04能解决是一样的
2. 代码中确实漏掉了那个1目录， 我等下提个PR增加下这个目录
