### ISSUE TITLE
想要修改 tensor的数值，但是又不希望被autograd记录，有没有ptorch中 tensor.data 的替代API

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/PaddleNLP#2546]
想要操作修改 tensor的数值，但是又不希望被autograd记录，不会影响梯度计算，有没有类似ptorch中 tensor.data 的替代API

**Comment by guoshengCS** [comment]
可以使用`with paddle.no_grad():`或者`tensor.stop_gradient=True`试下呢
