### ISSUE TITLE
领域预训练win报错：domain_adaptive_pretraining\data_tools\dataset_utils.py", line 127, in compile_helper ret = subprocess.run(['make', '-C', path])

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2547]
我知道这是个只在win下出现的错误，没有make，但是装了minGW 有了make命令，还是在win下出错。

develop\applications\neural_search\recall\domain_adaptive_pretraining\data_tools\dataset_utils.py", line 127, in compile_helper
ret = subprocess.run(['make', '-C', path])
File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\subprocess.py", line 472, in run
with Popen(*popenargs, **kwargs) as process:
File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\subprocess.py", line 775, in init
restore_signals, start_new_session)
File "E:\A_IDE\Anaconda3\envs\pp212_gpu\lib\subprocess.py", line 1178, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

跑预训练，一直找一个 baike_sample_train_indexmap_12800000mns_509msl_0.10ssp_1234s.npy 这样一个文件。 不知道哪里有问题

**Comment by w5688414** [comment]
可以使用最新版的ernie1.0预训练。 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0

**Comment by ZHUI** [comment]
你可以试一下 makefile 那里自己 mingw 编译成 so 文件

**Comment by ArtificialZeng** [comment]
> 你可以试一下 makefile 那里自己 mingw 编译成 so 文件

domain_adaptive_pretraining 这个还是训练不了吗， 我已经换到linux了

**Comment by ArtificialZeng** [comment]
> building sapmles index mapping for valid ...
make: 进入目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
make: 对“default”无需做任何事。
make: 离开目录“/media/reclab/新加卷/nlp_projects/PaddleNLP-develop/PaddleNLP-develop/model_zoo/ernie-1.0/data_tools”
    using uint32 for data mapping...
    using:
     number of documents:            13
     sentences range:                [981, 1033)
     total number of sentences:      52
     number of epochs:               2147483646
     maximum number of samples:      640640
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234
    reached 640640 samples after 40297 epochs ...
   number of empty documents: 0
   number of documents with one sentence: 0
   number of documents with long sentences: 0
   will create mapping for 640654 samples
 > done building sapmles index maping
 > saved the index mapping in /media/reclab/新加卷/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.122083
 > loading indexed mapping from /media/reclab/新加卷/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data/baike_sample_valid_indexmap_640640mns_509msl_0.10ssp_1234s.npy
    loaded indexed file in 0.001 seconds
    total number of samples: 640654
Traceback (most recent call last):
  File "run_pretrain.py", line 615, in <module>
    do_train(config)
  File "run_pretrain.py", line 403, in do_train
    current_step=global_step)
  File "run_pretrain.py", line 133, in create_pretrained_dataset
    test_dl = loader(test_ds, 0)
  File "run_pretrain.py", line 119, in loader
    consumed_samples=consumed_samples)
  File "/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/paddlenlp/utils/batch_sampler.py", line 120, in __init__
    self.num_samples = int(math.ceil(len(self.dataset) * 1.0 / self.nranks))
TypeError: object of type 'NoneType' has no len()
INFO 2022-06-20 10:49:37,372 launch_utils.py:343] terminate all the procs
