### ISSUE TITLE
如何解决detach不能被赋值的问题？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/PaddleNLP#2548]
![AC423I1I46L H6 @CJ${U~A](https://user-images.githubusercontent.com/82072274/174207147-55df13d1-91c4-46ee-920b-67fbcfdbb52b.png)

**Comment by linjieccc** [comment]
您好，因为`m = yr.detach.clone()`已经进行了detach操作，直接`x = m`即可
