### ISSUE TITLE
名词短语标注出错

### ISSUE THREAD

**Issue by thep0y** [PaddlePaddle/PaddleNLP#2553]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP：2.3.3 PaddlePaddle：2.3.0-gpu-post112
2）系统环境：Linux，python：3.9.12(conda)，cuda：11.7

所有词的标签都是“艺艺艺艺艺”：
```python
> from paddlenlp import Taskflow
> nptag = Taskflow("knowledge_mining", model="nptag")
[2022-06-17 13:03:40,225] [    INFO] - Already cached /home/thepoy/.paddlenlp/models/nptag/vocab.txt
> nptag("糖醋排骨")
[{'text': '糖醋排骨', 'label': '艺艺艺艺艺'}]
> nptag(["糖醋排骨", "红曲霉菌"])
[{'text': '糖醋排骨', 'label': '艺艺艺艺艺'}, {'text': '红曲霉菌', 'label': '艺艺艺艺艺'}]
> nptag = Taskflow("knowledge_mining", model="nptag", linking=True)
> nptag(["糖醋排骨", "红曲霉菌"])
[{'text': '糖醋排骨', 'label': '艺艺艺艺艺'}, {'text': '红曲霉菌', 'label': '艺艺艺艺艺'}]
```

**Comment by wawltor** [comment]
您好，我在py37和py39的机器上，在gpu和cpu上都没有复现您的问题；
我看您的cuda版本和paddle的版本看起来不太一致，paddle的cuda版本最高到11.2，可以进行以下尝试
1）conda安装 paddlepaddle-gpu   https://www.paddlepaddle.org.cn/ 
2）删除 ~/.paddlenlp目录再进行尝试

**Comment by thep0y** [comment]
是` ~/.paddlenlp`的问题，删除后重新下载就可以了
