### ISSUE TITLE
构建预训练索引是不是特别慢？卡了十几分钟不动弹 /ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data_tools”

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2555]
sentence indices in [380997, 381378) total of 381 sentences
 > WARNING: could not find index map file /media/reclab/新加卷1/nlp_projects/jd_data/baike_sample_train_indexmap_6400000mns_509msl_0.10ssp_1234s.npy, building the indices on rank 0 ...
int32
 > building sapmles index mapping for train ...
make: 进入目录“/media/reclab/新加卷1/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data_tools”
g++ -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color -I/home/reclab/anaconda3/envs/pp230_gpu/include/python3.7m -I/home/reclab/anaconda3/envs/pp230_gpu/lib/python3.7/site-packages/pybind11/include helpers.cpp -o helpers.cpython-37m-x86_64-linux-gnu.so
make: 离开目录“/media/reclab/新加卷1/nlp_projects/ernie_matching/PaddleNLP/applications/neural_search/recall/domain_adaptive_pretraining/data_tools”
    using uint32 for data mapping...
    using:
     number of documents:            361928
     sentences range:                [0, 361928)
     total number of sentences:      361928
     number of epochs:               2147483646
     maximum number of samples:      6400000
     maximum sequence length:        509
     short sequence probability:     0.1
     short sequence ration (1/prob): 10
     seed:                           1234

**Comment by ZHUI** [comment]
你好，请检查一下数据，确保每一个 doc 中，含有至少两行数据。

**Comment by ArtificialZeng** [comment]
> 你好，请检查一下数据，确保每一个 doc 中，含有至少两行数据。

晕，昨天在微信群里问您 您都不告诉我。 我用pandas 每行分一个，看来现在要重新数据准备。

**Comment by ZHUI** [comment]
不好意思，可能漏消息了，群里人比较多
