### ISSUE TITLE
同样的best_model 在不同的机器下 抽取效果差别很大。

### ISSUE THREAD

**Issue by sunshineyg2018** [PaddlePaddle/PaddleNLP#2559]
同样的best_model 在不同的机器下 抽取效果差别很大,有什么解决办法吗

**Comment by linjieccc** [comment]
您好，是指同一份模型文件，在不同机器上的抽取结果不同吗？

**Comment by sunshineyg2018** [comment]
是的

**Comment by linjieccc** [comment]
> 是的

理论上抽取结果应该是一致的，请问两边的paddlenlp、paddle版本是否一致，方便给个具体的例子么
