### ISSUE TITLE
自己写了一个BertModle的子类，使用from_pretrained('bert-wwm-chinese')，报错无法解决，怎么讲将预加载的模型参数传递到子类？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/PaddleNLP#2565]
![屏幕截图 2022-06-18 164842](https://user-images.githubusercontent.com/82072274/174431615-fc8ac885-063f-452d-840e-360690ebb719.png)
![屏幕截图 2022-06-18 164924](https://user-images.githubusercontent.com/82072274/174431619-8af91b4f-1524-4a7c-953c-56d076a6bf3a.png)
![屏幕截图 2022-06-18 165012](https://user-images.githubusercontent.com/82072274/174431621-dadd217b-6d4f-4ef4-8377-a0e9f43972e1.png)
![屏幕截图 2022-06-18 165038](https://user-images.githubusercontent.com/82072274/174431622-f2fd8380-5e17-4fc1-a671-eeae28d83e0e.png)
![屏幕截图 2022-06-18 165115](https://user-images.githubusercontent.com/82072274/174431624-0ddb5e47-dc7c-491d-aecd-02f60bab5db3.png)
![屏幕截图 2022-06-18 165130](https://user-images.githubusercontent.com/82072274/174431625-6abdc619-f99d-4d72-9e84-02c43515513b.png)
![屏幕截图 2022-06-18 165147](https://user-images.githubusercontent.com/82072274/174431627-afcbbffb-192f-4de5-9c02-76b963930542.png)

问题1：如何解决这个bug呢？
问题2：没有BertConfig讲么将1处获得的预加载模型测参数传递给2处BertModel的子类呢？

**Comment by LemonNoel** [comment]
目前的初始化方式有点问题，可以参考下下边的代码和注释哈

<img width="679" alt="截屏2022-06-18 下午6 10 58" src="https://user-images.githubusercontent.com/25607475/174433313-6b79b034-a73c-4332-878e-85d0d12517c9.png">

**Comment by MARKLIN1000** [comment]
![image](https://user-images.githubusercontent.com/82072274/174434760-51b6dbc5-63b7-416f-9ee8-6fbb093e8270.png)
![image](https://user-images.githubusercontent.com/82072274/174434782-19dc6563-a99f-48ea-8cdd-36fb79579104.png)
![image](https://user-images.githubusercontent.com/82072274/174434803-b523806a-c37b-467d-ad4f-4572d2413b51.png)
S
![image](https://user-images.githubusercontent.com/82072274/174434817-a0e9bd14-52d5-47e0-ad02-26bd0a2d1a1f.png)
![image](https://user-images.githubusercontent.com/82072274/174434827-ed1a1b32-184c-45b9-acc6-dce133ef58f4.png)
这么初始化还是报错了啊，没进入到MYBert里面

**Comment by LemonNoel** [comment]
![debug](https://user-images.githubusercontent.com/25607475/174435408-1357d26d-c278-4a6f-9e81-aef8926ddbce.png)

这里说明预训练模型参数已经load结束了，执行到你实现的__init__了，可以学习一下python中类的初始化是在做什么以及类的方法怎么用：https://www.liaoxuefeng.com/wiki/1016959663602400/1017496031185408

如果你想用self.encoder替换self.bert.encoder，直接self.encoder=self.bert.encoder就可以了，加了括号就是传参数直接调用方法了。

然后搜相关类的初始化函数，看看都需要哪些参数，不是单纯传bert进去，这里self.bert是个BertModel类型的对象，要初始化BertEmbeddings，需要看这里需要什么参数，然后按顺序传进去：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py#L46-L51

**Comment by MARKLIN1000** [comment]
好的，非常感谢您回答



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月18日(星期六) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 自己写了一个BertModle的子类，使用from_pretrained(&#39;bert-wwm-chinese&#39;)，报错无法解决，怎么讲将预加载的模型参数传递到子类？ (Issue #2565)





 

 
这里说明预训练模型参数已经load结束了，执行到你实现的__init__了，可以学习一下python中类的初始化是在做什么以及类的方法怎么用：https://www.liaoxuefeng.com/wiki/1016959663602400/1017496031185408
 
如果你想用self.encoder替换self.bert.encoder，直接self.encoder=self.bert.encoder就可以了，加了括号就是传参数直接调用方法了。
 
然后搜相关类的初始化函数，看看都需要哪些参数，不是单纯传bert进去，这里self.bert是个BertModel类型的对象，要初始化BertEmbeddings，需要看这里需要什么参数，然后按顺序传进去：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py#L46-L51
