### ISSUE TITLE
[CLUE] CHID 数据集可能存在评估缺失问题

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/PaddleNLP#2571]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/benchmark/clue/mrc/run_chid.py#L529-L533
```python
                if global_step >= num_training_steps:
                    logger.info("best_result: %.2f" % (best_acc * 100))
                    return
            tic_eval = time.time()
            acc = evaluate(model, dev_data_loader)
```
此处会出现，最后一个 epoch 训练完，没有评估，直接返回结果的问题。

**Comment by LiuChiachi** [comment]
Thanks! https://github.com/PaddlePaddle/PaddleNLP/pull/2574 will solve this bug.
