### ISSUE TITLE
neural search 的milvus，尝试用simcse模型，在插入向量时报错TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2579]
报错如下：
![4](https://user-images.githubusercontent.com/88191580/174536752-f11d5830-f47f-4831-a90e-31a6f4d3da49.png)
微信群大佬已经提供解决方案，请后期添加这两个参数到feature-extract.py参数配置模块
![5](https://user-images.githubusercontent.com/88191580/174537122-4ee3e89b-8566-412a-9f67-598c53829057.png)

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2588 感谢您的反馈，路径已经统一成inferene.get_pooled_embedding
