### ISSUE TITLE
always save vocab file in xlnet tokenizer

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/PaddleNLP#2582]
## Introduction

when reading the source code, I find that there is vital bug:

```python
    def save_resources(self, save_directory):
        """
        Saves `SentencePiece <https://github.com/google/sentencepiece>`__ file
        (ends with '.spm') under `save_directory`.
        Args:
            save_directory (str):
                Directory to save files into.
        """
        for name, file_name in self.resource_files_names.items():
            save_path = os.path.join(save_directory, file_name)
            if os.path.abspath(self.vocab_file) != os.path.abspath(save_path):
                copyfile(self.vocab_file, save_path)
```

you can refer to: https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/xlnet/tokenizer.py#L384

from the above code, you can get that xlnet tokenizer **always** save the vocab_file as the differnet resouce file.

**Comment by guoshengCS** [comment]
Since XLNet only uses `vocab_file` as resource currently, it has no effect actually. Sure it is not good.
