### ISSUE TITLE
输入长度大于512的怎么处理

### ISSUE THREAD

**Issue by DeqianBai** [PaddlePaddle/PaddleNLP#2586]
> max_seq_len: 文本最大切分长度，输入超过最大长度时会对输入文本进行自动切分，默认为512。

关于输入长度有几个疑问：
1、输入超过最大长度时会对输入文本进行自动切分，具体是怎么切分的，直接取前512个字符吗
2、统计准确率的时候是怎么统计的，是用start_id和end_id完全匹配上才算正确，还是对匹配到的内容一致就算正确
3、我的数据很多都是大于512的，平均3-5倍，这种怎么处理呢，怎么统计准确率

**Comment by guoshengCS** [comment]
输入超过指定长度（默认512）会将输入切分成多段 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/information_extraction.py#L240 

切分的逻辑是对每条输入按`max_text_len`指定的大小slice切成多段，对应这里的代码 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/task.py#L301

每一段都会进行一次预测，多次预测的结果会进行合并，对应这里的代码 
 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/information_extraction.py#L328

整个切分和合并对用户是透明的，准确率指标的统计按照合并后的结果统计即可。

也请 @linjieccc  确认下

**Comment by linjieccc** [comment]
是的。补充一下~UIE微调阶段也是按照`max_seq_len`指定的大小进行分段训练和评估，需要注意的是，因为是基于prompt的形式，这里切分后每段的实际文本切分长度需要减去prompt的长度，可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/utils.py#L133。

评估阶段会通过start_id和end_id得到预测的span的位置，只有和GroundTruth完全匹配才算正确，具体可以参考这里的代码实现：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/metrics/span.py
