### ISSUE TITLE
paddlenlp没有早停嘛？看我的训练loss一直都到零了。 什么时候能预训练rocketqa

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2590]
global step 770, epoch: 1, batch: 770, loss: 0.00000, speed: 1.35 step/s
global step 780, epoch: 1, batch: 780, loss: 0.00000, speed: 1.36 step/s
global step 790, epoch: 1, batch: 790, loss: 0.00000, speed: 1.36 step/s
global step 800, epoch: 1, batch: 800, loss: 0.00026, speed: 1.35 step/s
global step 810, epoch: 1, batch: 810, loss: 0.00000, speed: 1.36 step/s
global step 820, epoch: 1, batch: 820, loss: 0.00000, speed: 1.35 step/s
global step 830, epoch: 1, batch: 830, loss: 0.00000, speed: 1.35 step/s
global step 840, epoch: 1, batch: 840, loss: 0.00000, speed: 1.34 step/s
global step 850, epoch: 1, batch: 850, loss: 0.00000, speed: 1.31 step/s
global step 860, epoch: 1, batch: 860, loss: 0.00000, speed: 1.35 step/s
global step 870, epoch: 1, batch: 870, loss: 0.00000, speed: 1.34 step/s
global step 880, epoch: 1, batch: 880, loss: 0.00000, speed: 1.35 step/s
global step 890, epoch: 1, batch: 890, loss: 0.00000, speed: 1.35 step/s
global step 900, epoch: 1, batch: 900, loss: 0.00000, speed: 1.35 step/s
global step 1110, epoch: 1, batch: 1110, loss: 0.00000, speed: 1.35 step/s
global step 1120, epoch: 1, batch: 1120, loss: 0.00000, speed: 1.34 step/s
global step 1130, epoch: 1, batch: 1130, loss: 0.00000, speed: 1.35 step/s
global step 1140, epoch: 1, batch: 1140, loss: 0.00000, speed: 1.34 step/s
global step 1150, epoch: 1, batch: 1150, loss: 0.00000, speed: 1.35 step/s
global step 1160, epoch: 1, batch: 1160, loss: 0.00000, speed: 1.34 step/s
global step 1170, epoch: 1, batch: 1170, loss: 0.00000, speed: 1.35 step/s
global step 1180, epoch: 1, batch: 1180, loss: 0.00000, speed: 1.35 step/s
global step 1190, epoch: 1, batch: 1190, loss: 0.00000, speed: 1.35 step/s
global step 1200, epoch: 1, batch: 1200, loss: 0.00000, speed: 1.34 step/s
global step 1210, epoch: 1, batch: 1210, loss: 0.00000, speed: 1.35 step/s
global step 1220, epoch: 1, batch: 1220, loss: 0.00000, speed: 1.35 step/s
global step 1230, epoch: 1, batch: 1230, loss: 0.00000, speed: 1.35 step/s
global step 1240, epoch: 1, batch: 1240, loss: 0.00000, speed: 1.34 step/s
global step 1250, epoch: 1, batch: 1250, loss: 0.00000, speed: 1.34 step/s
global step 1260, epoch: 1, batch: 1260, loss: 0.00000, speed: 1.34 step/s
global step 1270, epoch: 1, batch: 1270, loss: 0.00000, speed: 1.34 step/s
global step 1280, epoch: 1, batch: 1280, loss: 0.00000, speed: 1.34 step/s
global step 1290, epoch: 1, batch: 1290, loss: 0.00000, speed: 1.32 step/s
global step 1300, epoch: 1, batch: 1300, loss: 0.00000, speed: 1.32 step/s
global step 1310, epoch: 1, batch: 1310, loss: 0.00000, speed: 1.31 step/s
global step 1320, epoch: 1, batch: 1320, loss: 0.00000, speed: 1.34 step/s
global step 1330, epoch: 1, batch: 1330, loss: 0.00000, speed: 1.34 step/s
global step 1340, epoch: 1, batch: 1340, loss: 0.00000, speed: 1.34 step/s
global step 1350, epoch: 1, batch: 1350, loss: 0.00000, speed: 1.34 step/s
global step 1360, epoch: 1, batch: 1360, loss: 0.00000, speed: 1.35 step/s
global step 1370, epoch: 1, batch: 1370, loss: 0.00000, speed: 1.35 step/s
global step 1380, epoch: 1, batch: 1380, loss: 0.00000, speed: 1.31 step/s
global step 1390, epoch: 1, batch: 1390, loss: 0.00071, speed: 1.35 step/s
global step 1400, epoch: 1, batch: 1400, loss: 0.00000, speed: 1.34 step/s
global step 1410, epoch: 1, batch: 1410, loss: 0.00000, speed: 1.34 step/s
global step 1420, epoch: 1, batch: 1420, loss: 0.00000, speed: 1.35 step/s
global step 1430, epoch: 1, batch: 1430, loss: 0.00000, speed: 1.33 step/s

**Comment by tianxin1860** [comment]
1. 看看是不是自己的训练集太简单了。
2. RocketQA 的训练能力预计 7 月发布，欢迎关注。
