### ISSUE TITLE
缺少模型

### ISSUE THREAD

**Issue by Geministudents** [PaddlePaddle/PaddleNLP#2592]
请问文档中不存在的预训练模型是因为没有权重参数无法导入的么
模型是哈工大的 Cino模型
也是中文，少数民族的方言，建议可以转换下权重

**Comment by wawltor** [comment]
能提供一下具体的模型链接吗？ 我们来评估一下

**Comment by Geministudents** [comment]
https://huggingface.co/hfl/cino-base-v2
https://github.com/ymcui/Chinese-Minority-PLM
可以比较好的解决低资源语言的问题

**Comment by wawltor** [comment]
嗯嗯 好的，收到，我们内部评估一下
