### ISSUE TITLE
class paddle.nn.Transformer中memory_mask参数怎么获得？

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/PaddleNLP#2593]
class paddle.nn.Transformer中memory_mask参数怎么获得？

**Comment by FrostML** [comment]
可以直接参考 Transformer 这段代码 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/transformer/modeling.py#L806 其实就是 source 和 target 之间的 mask。
