### ISSUE TITLE
UIE框架什么时候更新模型压缩和蒸馏的功能？

### ISSUE THREAD

**Issue by lijiaqi0612** [PaddlePaddle/PaddleNLP#2598]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by wawltor** [comment]
1. 目前UIE的蒸馏主要是在底座模型，uie的base和tiny模型都是基于ENRIE-3.0蒸馏后的模型，同时最近我们会开源基于更小的蒸馏的UIE模型
2. 模型这块分为两个部分，1）模型裁减这块，后续我们可能排上去 2）量化模型，我们经过测试损点比较验证，目前没有计划开源
