### ISSUE TITLE
层次化文本分类有此功能嘛？ 能否用paddleNLP实现

### ISSUE THREAD

**Issue by ArtificialZeng** [PaddlePaddle/PaddleNLP#2600]
例如腾讯的Neural Classifier 的类似功能。

**Comment by lugimzzz** [comment]
层次分类模块功能正在开发中，目前处于pr阶段[层次分类PR](https://github.com/PaddlePaddle/PaddleNLP/pull/2501/)。未来PaddleNLP将搭建文本分类应用模块，支持多分类、多标签分类、层次分类的训练、预测和多种部署方式。

**Comment by ArtificialZeng** [comment]
> 层次分类模块功能正在开发中，目前处于pr阶段[层次分类PR](https://github.com/PaddlePaddle/PaddleNLP/pull/2501/)。未来PaddleNLP将搭建文本分类应用模块，支持多分类、多标签分类、层次分类的训练、预测和多种部署方式。

能用于 商品同款匹配嘛  https://cloud.tencent.com/developer/article/1063204

**Comment by ArtificialZeng** [comment]
> 层次分类模块功能正在开发中，目前处于pr阶段[层次分类PR](https://github.com/PaddlePaddle/PaddleNLP/pull/2501/)。未来PaddleNLP将搭建文本分类应用模块，支持多分类、多标签分类、层次分类的训练、预测和多种部署方式。

怎么用于 中文， 商品的同款匹配

**Comment by ArtificialZeng** [comment]
> 层次分类模块功能正在开发中，目前处于pr阶段[层次分类PR](https://github.com/PaddlePaddle/PaddleNLP/pull/2501/)。未来PaddleNLP将搭建文本分类应用模块，支持多分类、多标签分类、层次分类的训练、预测和多种部署方式。

数据集没给，到哪里下载？ 如果直接运行， 报那个链接404：
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/2.2.2/datasets/wos/wos.py (ConnectionError(MaxRetryError("HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /huggingface/datasets/2.2.2/datasets/wos/wos.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013E9C199048>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))")))

**Comment by lugimzzz** [comment]
wos数据集已内置在PaddleNLP中,使用
```python
from paddlenlp.datasets import load_dataset
train_ds, dev_ds, test_ds = load_dataset("wos", splits=["train", "dev", "test"])
train_ds[0]
# {'sentence': 'traditional fluid-structure interaction techniques are based on arbitrary lagrangian-eulerian method, where strong coupling method is used to solve fundamental discretized equations. after discretization, resulting nonlinear systems are solved using an iterative method leading to set of linear subsystems. the resulting linear subsystem matrices are sparse non-symmetric indefinite with small or zero diagonal entries. the small pivots of these matrices may render the incomplete lu factorization unstable or inaccurate. to improve that, this paper proposes an approach that can be used together with a stabilization and offers an additional feature to be used to gain an advantage in its parallelization. (c) 2016 published by elsevier ltd.', 'level 1': ['CS'], 'level 2': ['Parallel computing']}
```

**Comment by lugimzzz** [comment]
本层次文本分类任务目前主要用于对文本片段进行分类，确定文本在不同层次标签中所属的类别。中文商品匹配可以参考application中[语义索引任务](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search)进行搭建

**Comment by ArtificialZeng** [comment]
> wos数据集已内置在PaddleNLP中,使用
> 
> ```python
> from paddlenlp.datasets import load_dataset
> train_ds, dev_ds, test_ds = load_dataset("wos", splits=["train", "dev", "test"])
> train_ds[0]
> # {'sentence': 'traditional fluid-structure interaction techniques are based on arbitrary lagrangian-eulerian method, where strong coupling method is used to solve fundamental discretized equations. after discretization, resulting nonlinear systems are solved using an iterative method leading to set of linear subsystems. the resulting linear subsystem matrices are sparse non-symmetric indefinite with small or zero diagonal entries. the small pivots of these matrices may render the incomplete lu factorization unstable or inaccurate. to improve that, this paper proposes an approach that can be used together with a stabilization and offers an additional feature to be used to gain an advantage in its parallelization. (c) 2016 published by elsevier ltd.', 'level 1': ['CS'], 'level 2': ['Parallel computing']}
> ```

FileNotFoundError: Couldn't find a dataset script at G:\googleDownload\PaddleNLP-hierarchical\PaddleNLP-hierarchical\applications\text_classification\hierarchical_classification\wos\wos.py or any data file in the same directory.

**Comment by lugimzzz** [comment]
目前层次分类任务处于开发阶段，wos层次分类数据集读入方式出现变动，预计本周会重新提交新的pr

**Comment by lugimzzz** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical
文本分类应用已支持层次分类
