### ISSUE TITLE
ernie3.0 裁剪量化问题

### ISSUE THREAD

**Issue by yrg5101** [PaddlePaddle/PaddleNLP#2601]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP 2.3.0.dev，PaddlePaddle2.3.0
2）系统环境：Windows，python：3.7

场景：给ernie-3.0-medium-zh进行裁剪量化操作。参考ernie-3.0文档
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0

我们的场景是做文本语义相似，所有不属于分类、序列标注、阅读理解三大场景，安装文档我使用了
compress_token_cls.py 进行压缩裁剪操作，但是有几点疑问：

1.我的场景不属于分类、序列标注、阅读理解三大场景， 我可以直接用你们提供的compress_token_cls.py 进行压缩裁剪操作？ 对结果有没有什么影响？

2.
trainer = Trainer(model=model,
                      criterion=loss_fct,
                      args=training_args,
                      data_collator=data_collator,
                      train_dataset=train_dataset,
                      eval_dataset=eval_dataset,
                      tokenizer=tokenizer)
里面的train_dataset和eval_dataset 使用了默认的MSRA_NER数据集，  但是我们本身业务是科技行业， 想问用默认的数据集进行操作，会不会对结果有什么影响？  如果有，我该怎么准备自己的dataset? 什么格式的？

谢谢

**Comment by LiuChiachi** [comment]
文本语义相似可以当成分类任务来解决，您需要使用自己场景的数据参考`compress_seq_cls.py`进行fine tuning微调，先得到下游任务上的模型，然后用您这份业务上的数据集对微调得到的模型进行压缩操作。

不能使用MSRA_NER数据集，因为这个数据集和您的业务场景数据差别可能很大。
