### ISSUE TITLE
在使用正则化L2Decay时,报错

### ISSUE THREAD

**Issue by MARKLIN1000** [PaddlePaddle/PaddleNLP#2605]
![image](https://user-images.githubusercontent.com/82072274/174929568-313ba7a8-979e-4166-b3d8-ad6c7262e564.png)
![image](https://user-images.githubusercontent.com/82072274/174929606-a8319bcb-b4f8-4422-8973-dd1573c1dd74.png)

在使用正则化L2Decay时，optimizer=AdamW(weight_dency=L2Deacy（coeff=0.0003）)时报错，说coeff不是float类型或者tensor这是怎么回事啊，我这明明是0.0003啊

**Comment by wawltor** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/16698950/174930434-e9e8dc06-97d5-4676-b440-ae116e4af7d7.png">

weight_decay=0.0003就可以，在优化器里面已经默认是L2Decay方式  
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw
