### ISSUE TITLE
关于UIE

### ISSUE THREAD

**Issue by jiangix-paper** [PaddlePaddle/PaddleNLP#2606]
您好，如果是篇章级的事件抽取。对于UIE中的事件抽取而言，是直接预测一整篇文档中的事件效果较好呢？还是将文章拆成句子，逐句预测呢？谢谢

**Comment by wawltor** [comment]
文章拆成句子，逐句预测的效果会更好，因为UIE在开源模型训练的时候就是单句微调的，因此咱们在自己的数据微调或者预测的时候单句的效果会更好

**Comment by jiangix-paper** [comment]
好的，非常感谢

**Comment by jiangix-paper** [comment]
再请教两个问题：
（1）如果是金融领域的事件抽取微调，假设我们自定义了100个金融事件，如果微调的话，是否需要每个事件都提供5条左右的样本才会得到比较好的效果？
（2）如果篇章级事件抽取，采用逐句方式来做。是否需要对每个句子的抽取结果做后续的清洗呢？比如：事件去重，事件主体关联等

**Comment by jiangix-paper** [comment]
能否帮忙看下这个问题，感谢
