### ISSUE TITLE
对通用信息抽取模型uie做精调，精调效果为什么不升反降？

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleNLP#2608]
参考 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md文档 做关系抽取的精调，优化后的效果没有基线模型uie-tiny的效果好，不知道是哪块出现了问题~
具体操作如下：1）使用doccano标注自己的数据40个样例，标注完并导出为jsonl；2）使用doccano.py处理数据，划分为训练集、验证集和测试集；3）使用finetune.py做精调，参数使用官方默认的参数。
结果：1）应该抽取的没抽取出来，2）抽取出来的，抽取内容不对。
麻烦可以指点一二，非常感谢~

- 版本、环境信息
- 1）PaddleNLP ：2.3   PaddlePaddle ：2.3
- 2）系统环境，linux，python：3.7.9

**Comment by wawltor** [comment]
想问一下，微调之后选择最好的模型的F1值指标是多少了？

**Comment by guoxiaoyue111111** [comment]
最好的f1得分是0.688

**Comment by wawltor** [comment]
> 最好的f1得分是0.688
微调的数据是多少了，看起来F1值并不是特别高，这样的F1值确实会出现一些badcase

**Comment by wawltor** [comment]
> 

微调的数据是多少了，看起来F1值并不是特别高，这样的F1值确实会出现一些badcase

**Comment by guoxiaoyue111111** [comment]
用doccano.py处理后，train有450+，dev有50条。人工将一些样本去掉（因为在负样本的生成中，生成的一些关系和实体的组合，不符合常规的说话逻辑和习惯），最终，用于微调的train有250多条，dev有50条。

**Comment by wawltor** [comment]
> 用doccano.py处理后，train有450+，dev有50条。人工将一些样本去掉（因为在负样本的生成中，生成的一些关系和实体的组合，不符合常规的说话逻辑和习惯），最终，用于微调的train有250多条，dev有50条。

能贴一下你标注的样本吗？

**Comment by guoxiaoyue111111** [comment]
不好意思~可以给我一个您私人的邮箱吗？数据有点不方便发网上~

**Comment by guoxiaoyue111111** [comment]
非常开心您能将邮箱给我，标注样本已发送至您邮箱。


另外，在排查问题的过程中，我又发现了两个问题。

问题一：
1）在mac本运行 ie = Taskflow("information_extraction",schema=schema,model="uie-tiny")时，会在uie目录下创建uie-tiny文件夹，并下载2个文件，model_config.json和model_state.pdparams。
2）但是在windows本运行ie = Taskflow("information_extraction",schema=schema,model="uie-tiny")时，会在uie目录下创建uie-tiny文件夹，并下载5个文件，model_config.json和model_state.pdparams之外，还有special_tokens_map.json、tokenizer_config.json和vocab.txt，比mac本多下载3个文件。
     为什么会有这种情况呢？而且多余的3个文件似乎没有作用~这会对模型精调产生不利影响吗？

问题二：
init_from_ckpt参数不传递值会造成精调效果不好吗？我试着传参，但是提示我 error:unrecognized arguments:--init_from_ckpt，不识别该参数。我想问，是我传的参数不对吗？（--init_from_ckpt “”./uie-tiny/model_state.pdparams“” 想把uie-tiny的参数作为初始参数）还是因为没必要传这个参数。

如果不传参的话，会跳过下面的if语句，那么model获得不到指定的初始化参数。如果获取不到指定参数的话，model的参数会和uie-tiny的参数一样吗？
    if args.init_from_ckpt and os.path.isfile(args.init_from_ckpt):
        state_dict = paddle.load(args.init_from_ckpt)
        model.set_dict(state_dict)

**Comment by wawltor** [comment]
> 非常开心您能将邮箱给我，标注样本已发送至您邮箱。
> 
> 另外，在排查问题的过程中，我又发现了两个问题。
> 
> 问题一： 1）在mac本运行 ie = Taskflow("information_extraction",schema=schema,model="uie-tiny")时，会在uie目录下创建uie-tiny文件夹，并下载2个文件，model_config.json和model_state.pdparams。 2）但是在windows本运行ie = Taskflow("information_extraction",schema=schema,model="uie-tiny")时，会在uie目录下创建uie-tiny文件夹，并下载5个文件，model_config.json和model_state.pdparams之外，还有special_tokens_map.json、tokenizer_config.json和vocab.txt，比mac本多下载3个文件。 为什么会有这种情况呢？而且多余的3个文件似乎没有作用~这会对模型精调产生不利影响吗？
> 
> 问题二： init_from_ckpt参数不传递值会造成精调效果不好吗？我试着传参，但是提示我 error:unrecognized arguments:--init_from_ckpt，不识别该参数。我想问，是我传的参数不对吗？（--init_from_ckpt “”./uie-tiny/model_state.pdparams“” 想把uie-tiny的参数作为初始参数）还是因为没必要传这个参数。
> 
> 如果不传参的话，会跳过下面的if语句，那么model获得不到指定的初始化参数。如果获取不到指定参数的话，model的参数会和uie-tiny的参数一样吗？ if args.init_from_ckpt and os.path.isfile(args.init_from_ckpt): state_dict = paddle.load(args.init_from_ckpt) model.set_dict(state_dict)


**问题一**
应该是mac和windows机器安装的paddlenlp的版本不一致导致的，最新的版本会下载5个文件，不过两个版本不影响训练效果

**问题二**
1. 传的参数方式可能要检查一下是不是一些换行符导致的
2. 不传入参数的话，会加载uie-base或者uie-tiny模型，`--model` 和这个参数有关

**Comment by wawltor** [comment]
我看了一下数据，看起来还挺正常的，想问一下不对负样本过滤的话，训练效果是怎么样的了？因为看这个任务相对比较简单，F1值是0.68有点不太正常，UIE挺适合做该类任务的

**Comment by guoxiaoyue111111** [comment]
除了数据问题，还有其他导致精调效果不好的原因吗？

以上的提问全部为windows精调train 250，dev 50条的结果，f1最优是0.68。不对负样本过滤的实验没做（因为使用cpu，训练特别慢，250条样本训练了3天多。既然您这么问，应该是负样本会有影响，那我接下来也实验一次）。

-----------------------------------------------------------------------------------------------------------------------------------------

以下是我用mac本，基于昨天发您的6条样本，运行doccano.py和finetune.py，最优f1为0.75（未人工过滤负样本）这么看，是否能说明负样本确实会起作用？和官网5-shot的其他领域相比，0.75能否算作正常范围？

**Comment by wawltor** [comment]
> 除了数据问题，还有其他导致精调效果不好的原因吗？
> 
> 以上的提问全部为windows精调train 250，dev 50条的结果，f1最优是0.68。不对负样本过滤的实验没做（因为使用cpu，训练特别慢，250条样本训练了3天多。既然您这么问，应该是负样本会有影响，那我接下来也实验一次）。
> 
> 以下是我用mac本，基于昨天发您的6条样本，运行doccano.py和finetune.py，最优f1为0.75（未人工过滤负样本）这么看，是否能说明负样本确实会起作用？和官网5-shot的其他领域相比，0.75能否算作正常范围？

看起来是一个合理值，可以增加一些样本，预计效果还能提升不少，因为本身这个任务看起来并不是特别难

**Comment by guoxiaoyue111111** [comment]
非常感谢您耐心的回答~~您的回复对我帮助很大，再次感谢~~~

**Comment by guoxiaoyue111111** [comment]
不好意思，有个奇怪的现象还需要请教您一下~

问题一：模型迁移与系统是否有关
就是我用mac基于6条标注数据精调的模型，f1是0.75，在mac上做测试，抽取效果也不错，这应该是正常的。但是，当我把精调后的模型迁移到windows上做预测时，使用同样的样例句子抽取，结果什么都抽取不出来（这太奇怪了）。我想问下，这种模型迁移和系统有关系吗？

问题二：模型复现问题
然后我又用windows电脑复现mac的精调模型，用同样的6个样本，训练得到的best model的f1是0.89。但是使用精调后的模型抽取样例，本应该抽取出来的结果抽取不出来，即使能抽出来的，抽取结果也是乱七八糟，没有合理的。

另外，想问下，在模型训练或者预测的过程中有没有debug的功能，这样，我可以保证能够跟踪每步的执行情况。之前用pycharm，还有其他更好的方法吗？

**Comment by wawltor** [comment]
问题一：
模型应该是和系统没有关系的
问题二：
你看看在model_best目录下是不是有生成一个static目录，建议在测试的时候把这个目录先删除，然后再测试效果

**Comment by guoxiaoyue111111** [comment]
收到，非常感谢您的回复～～

**Comment by watertianyi** [comment]
我使用doccano标注了1814条数据进行信息抽取，其中
`python doccano.py \
    --doccano_file ./data/doccano_ext.json \
    --task_type ext \
--negative_ratio 5 \
    --save_dir ./data \
    --splits 0.8 0.1 0.1 \
    --schema_lang ch`
```
export finetuned_model=./checkpoint/model_best
python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 8 \
    --per_device_train_batch_size  8 \
    --num_train_epochs 20 \
    --learning_rate 1e-5 \
    --label_names "start_positions" "end_positions" \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1
```
为什么--num_train_epochs 20
checkpoint已经到了checkpoint-8700，占用125G内存，这个能不能不保存这么多？
训练+测试+dev数据在doccanno数据1814条需要多久才可以结束呢
训练还没有停止，还在继续，所有结果都在达不到60%，如下：
[2024-04-15 14:26:24,380] [    INFO] - ***** Running Evaluation *****
[2024-04-15 14:26:24,380] [    INFO] -   Num examples = 4525
[2024-04-15 14:26:24,380] [    INFO] -   Total prediction steps = 566
[2024-04-15 14:26:24,380] [    INFO] -   Pre device batch size = 8
[2024-04-15 14:26:24,380] [    INFO] -   Total Batch size = 8
[2024-04-15 14:27:37,686] [    INFO] - eval_loss: 0.00044721903395839036, eval_precision: 0.4975845410628019, eval_recall: 0.5567567567567567, eval_f1: 0.5255102040816326, eval_runtime: 73.3051, eval_samples_per_second: 61.728335980187374, eval_steps_per_second: 7.721157605477581, progress_or_epoch: 4.6831
[2024-04-15 14:27:37,687] [    INFO] - Saving model checkpoint to ./checkpoint/model_best/checkpoint-9900
[2024-04-15 14:27:37,687] [    INFO] - tokenizer config file saved in ./checkpoint/model_best/checkpoint-9900/tokenizer_config.json
[2024-04-15 14:27:37,687] [    INFO] - Special tokens file saved in ./checkpoint/model_best/checkpoint-9900/special_tokens_map.json
[2024-04-15 14:27:37,690] [    INFO] - Configuration saved in ./checkpoint/model_best/checkpoint-9900/config.json
[2024-04-15 14:27:38,961] [    INFO] - Model weights saved in ./checkpoint/model_best/checkpoint-9900/model_state.pdparams
[2024-04-15 14:27:38,961] [    INFO] - Saving optimizer files.
上述正常吗？
