### ISSUE TITLE
uie导出后的模型预测时如何指定gpu编号？

### ISSUE THREAD

**Issue by Chikeke** [PaddlePaddle/PaddleNLP#2612]
uie模型导出后运行infer_gpu.py进行预测时，如何指定gpu编号？

**Comment by wawltor** [comment]
在windows机器可以设置一下环境变量， set CUDA_VISIBLE_DEVICES=0   （id号可以自己选）
Linux机器可以设置一下环境变量，export CUDA_VISIBLE_DEVICES=0 

同时也可以直接使用Taskflow来进行预测
`my_ie = Taskflow("information_extraction", schema=schema, task_path='./checkpoint/model_best', device_id=0) #device_id可以自己选`

**Comment by Chikeke** [comment]
@wawltor 我是linux机器，在命令行输入export CUDA_VISIBLE_DEVICES=3之后，运行infer_gpu.py，报错信息中依然显示gpu=0，在infer_gpu.py中设置os.environ["CUDA_VISIBLE_DEVICES"] = "3"之后，也不能改变使用的gpu，我在同一个服务器运行着finetune.py，用的是0卡，是否跟这个有关系？

**Comment by wawltor** [comment]
> @wawltor 我是linux机器，在命令行输入export CUDA_VISIBLE_DEVICES=3之后，运行infer_gpu.py，报错信息中依然显示gpu=0，在infer_gpu.py中设置os.environ["CUDA_VISIBLE_DEVICES"] = "3"之后，也不能改变使用的gpu，我在同一个服务器运行着finetune.py，用的是0卡，是否跟这个有关系？

好的，我们看看这个问题，如果急着使用可以使用Taskflow的方式，这个也是可以支持半精度的写法，我们先测试一下相关predictor

**Comment by linjieccc** [comment]
@Chikeke 您好，执行以下命令试下呢，可以用`nvidia-smi`观察看看

```shell
export CUDA_VISIBLE_DEVICES=3 & python deploy/python/infer_gpu.py --model_path_prefix export/inference --use_fp16
```

**Comment by Chikeke** [comment]
@linjieccc  感谢，现在可以了！

**Comment by Chikeke** [comment]
@linjieccc 另外我还有几个问题想请教，我运行infer_gpu.py时需要预测大量数据，一次性把数据都加入texts中预测会占用很大的显存，需要将max_len调小到128才勉强够用，因此想问下：
1.  在用fp16加速的情况下，uie_predictor.py中的预测过程能否像taskflow预测时一样使用batch_size? 
2.  如果可以，使用batch_size会比现在预测速度更快，占用显存更小吗？

**Comment by linjieccc** [comment]
> @linjieccc 另外我还有几个问题想请教，我运行infer_gpu.py时需要预测大量数据，一次性把数据都加入texts中预测会占用很大的显存，需要将max_len调小到128才勉强够用，因此想问下：
> 
> 1. 在用fp16加速的情况下，uie_predictor.py中的预测过程能否像taskflow预测时一样使用batch_size?
> 2. 如果可以，使用batch_size会比现在预测速度更快，占用显存更小吗？

@Chikeke 
1.目前uie_predictor已支持使用batch_size分批预测，可以拉最新的develop分支代码再试下。
2.设置较小的batch_size可以避免显存占用过大的问题，可以结合机器情况适当调整
