### ISSUE TITLE
ernie3.0x性能问题

### ISSUE THREAD

**Issue by GZ1220** [PaddlePaddle/PaddleNLP#2613]
![image](https://user-images.githubusercontent.com/90749831/174967825-6880b1d4-a518-49db-8efa-5056a2a1b5ca.png)
请问这两张图的横坐标表示的什么？10个任务的平均时延？如果平均时延的话没有什么意义呀。num_treads=8,batch_size=32时，ernie-3.0-medium-zh的时延在15-20毫秒之间，按15毫秒算的话，吞吐量也才66.67，和下面展示的CPU性能相比差距相当大啊

**Comment by LiuChiachi** [comment]
您好，感谢关注
横坐标表示的在IFLYTEK任务上的时延，不是平均时延，这里没有表述清楚，抱歉，我们立即修复。

**Comment by GZ1220** [comment]
好的好的，感谢回复
