### ISSUE TITLE
ImportError: cannot import name 'einsum' from 'paddle'

### ISSUE THREAD

**Issue by dielianhua** [PaddlePaddle/PaddleNLP#2614]
https://aistudio.baidu.com/aistudio/projectdetail/2461530?channelType=0&channel=0， Paddlepaddle-gpu升级到2.3.0还是报错

**Comment by dielianhua** [comment]
升级后还有新的错，The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is /usr/lib/x86_64-linux-gnu/libcuda.so: file too short)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Segmentation fault (core dumped)

**Comment by 1649759610** [comment]
同学你好：

请参照一下方式调试一下：
1. 在import paddle之前，更新paddlepaddle至2.3.0（可以在最上边的代码块更新paddle）
2. 如更新后还是报错，重启一下AiStudio的内核

如有问题，欢迎与我们交流。

**Comment by dielianhua** [comment]
已收到，辛苦啦

**Comment by dielianhua** [comment]
更新成paddle paddle2.3目前cpu的能跑，但是太慢了，gpupaddle paddle2.3更新还是跑不了



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 22, 2022 17:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PaddlePaddle/PaddleNLP] ImportError: cannot import name 'einsum'from 'paddle' (Issue #2614)




 
同学你好：
 
请参照一下方式调试一下：
  
在import paddle之前，更新paddlepaddle至2.3.0（可以在最上边的代码块更新paddle） 

如更新后还是报错，重启一下AiStudio的内核 
 
如有问题，欢迎与我们交流。

**Comment by wawltor** [comment]
> 更新成paddle paddle2.3目前cpu的能跑，但是太慢了，gpupaddle paddle2.3更新还是跑不了
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Jun 22, 2022 17:11 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [PaddlePaddle/PaddleNLP] ImportError: cannot import name 'einsum'from 'paddle' (Issue #2614) 同学你好： 请参照一下方式调试一下： 在import paddle之前，更新paddlepaddle至2.3.0（可以在最上边的代码块更新paddle） 如更新后还是报错，重启一下AiStudio的内核 如有问题，欢迎与我们交流。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

GPU的话建议使用conda来安装

**Comment by dielianhua** [comment]
你好，我按照上边的方式更新了，也重启内核了，现在不报第一个错了，但是还是跑不过去，我第二行写的错就是更新后在aistudio自带的终端下跑的，在notebook下每次跑到这个位置就断了

**Comment by wawltor** [comment]
> 你好，我按照上边的方式更新了，也重启内核了，现在不报第一个错了，但是还是跑不过去，我第二行写的错就是更新后在aistudio自带的终端下跑的，在notebook下每次跑到这个位置就断了

麻烦贴一下报错信息

**Comment by 1649759610** [comment]
我运行了一下，用GPU跑是没有问题的，试一下这个链接：
https://aistudio.baidu.com/aistudio/projectdetail/4258016?forkThirdPart=1
