### ISSUE TITLE
一个小小小小小的建议

### ISSUE THREAD

**Issue by flymushroom** [PaddlePaddle/PaddleNLP#2615]
![Snipaste_2022-06-22_17-16-01](https://user-images.githubusercontent.com/90736820/174993910-00b38554-613c-4071-9eeb-9c58c883631d.png)
我在加载uie的predictor时，即使本地有‘ernie-3.0-base-zh’的文件夹，也会默认去下载，加载缓存，除非我把它整个换个名称再把其他uie的token和vocab放进去，才能自动加载本地。有点反直觉，，对无外网的环境不友好，如果不是问题请忽略，打扰了

**Comment by wawltor** [comment]
麻烦提供一下你现在使用的PaddleNLP版本

**Comment by flymushroom** [comment]
> 麻烦提供一下你现在使用的PaddleNLP版本

直接安装的最新版

**Comment by wawltor** [comment]
> > 麻烦提供一下你现在使用的PaddleNLP版本
> 
> 直接安装的最新版

微调的时候会在uie-base和uie-tiny的目录下载所需的资源，当训练完毕之后，可以将best_model目录下的  `model_state.pdparams` 替换到 uie-base或者uie-tiny目录下即可

**Comment by wj-Mcat** [comment]
Thanks for your great suggestion, we have take it into plan a week before. I believe that these prs will fix your problem:

* https://github.com/PaddlePaddle/PaddleNLP/pull/2521
* https://github.com/PaddlePaddle/PaddleNLP/pull/2578

all you need is to wait for next version of paddlepaddle. please keep eyes on the released info to get the latest info. 

Or, you can install it from the source code in develop branch to get the feature: [Installation Guid](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/get_started/installation.rst#%E4%BB%A3%E7%A0%81%E5%AE%89%E8%A3%85).

 After the new version released, you can install it with pip command. Hope that can help you fix the problem.  Please feel free to tell us more about your later issue.
