### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing的模型服务化部署报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#2616]
<img width="558" alt="95df41ea65d63a966e05dbdef969a10" src="https://user-images.githubusercontent.com/63343847/174998596-11d03aa9-7efe-4947-a8ae-0feb994bc5b8.png">
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing案例里面开源的模型，下载下来后，放到https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/in_batch_negative里面，导出模型并做模型服务化部署后报错
<img width="696" alt="8f0e9cf82660a312d277009b7713c5f" src="https://user-images.githubusercontent.com/63343847/174998851-55adbcfe-d88f-4444-b92c-aba3663cda85.png">

**Comment by 1649759610** [comment]
同学你好：

根据报错提示，你的input为null，请检查你的input是否符合要求。

如有问题，欢迎与我们交流。

**Comment by AI-Mart** [comment]
paddleserving服务的trt可能出问题了，把trt模式换成gpu模型，就好了，后面会进一步测试下trt
