### ISSUE TITLE
ERNIR3.0文本生成

### ISSUE THREAD

**Issue by ssrssrcode** [PaddlePaddle/PaddleNLP#2617]
您好，请问一下开源的ERNIE3.0模型是否支持文本生成任务(不是指去调用EasyDL等里面的api)。因为看到给出的ernie3.0 example中并未涉及到生成类型任务

**Comment by 1649759610** [comment]
同学你好：

目前Ernie3.0 暂未支持文本生成任务

**Comment by code-wd** [comment]
您好，请问下Ernie3.0 有支持文本生成任务的计划吗？我看官网上显示是支持文本生成任务的：https://wenxin.baidu.com/moduleApi/ernie3
