### ISSUE TITLE
提问，可以提供一个把uie用paddle serving 部署的方式例子吗

### ISSUE THREAD

**Issue by flymushroom** [PaddlePaddle/PaddleNLP#2619]
看官方例子里，是有prototxt等文件的，但现在的uie部署例子里，export_model文件只输出inference等参数文件。
我不清楚是不是我没找到地方，能给提供一个例子吗
谢谢大佬

**Comment by LiuChiachi** [comment]
您好，感谢关注

您可以先参考 ERNIE 3.0 服务化部署的 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0/deploy/serving 这个例子，二者是类似的

**Comment by wawltor** [comment]
```python
from paddlenlp import Taskflow
from flask import Flask, request, jsonify
import traceback
import threading

lock = threading.Lock()

ie = Taskflow('information_extraction', schema=schema)
app = Flask(__name__)

@app.route('/uie', methods=['post'])
def uie():
    body = request.json
    text = body.get('text')
    lock.acquire()
    try:
        res = str(ie(text))
        lock.release()
        return jsonify(res)
    except Exception as e:
        lock.release()
        traceback.print_exc()
        return jsonify(e)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8020, debug=True)

```python


你可以按照这个方式来设置一下Server，后续我们会放出官方的服务部署方式

**Comment by TherChenYang** [comment]
> ```python
> from paddlenlp import Taskflow
> from flask import Flask, request, jsonify
> import traceback
> import threading
> 
> lock = threading.Lock()
> 
> ie = Taskflow('information_extraction', schema=schema)
> app = Flask(__name__)
> 
> @app.route('/uie', methods=['post'])
> def uie():
>     body = request.json
>     text = body.get('text')
>     lock.acquire()
>     try:
>         res = str(ie(text))
>         lock.release()
>         return jsonify(res)
>     except Exception as e:
>         lock.release()
>         traceback.print_exc()
>         return jsonify(e)
> 
> if __name__ == "__main__":
>     app.run(host='0.0.0.0', port=8020, debug=True)
> 
> ```python
> 
> 
> 你可以按照这个方式来设置一下Server，后续我们会放出官方的服务部署方式
> ```

大佬 请问一下 UIE 通过paddle serving部署游官方的示例了嘛 新手使用 没有示例确实有点困难 麻烦您了
