### ISSUE TITLE
 no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by shanliang1992** [PaddlePaddle/PaddleNLP#262]
使用PaddleNLP中的text_classification/rnn这个demo时报错

路径为PaddleNLP/examples/text_classification/rnn
执行的指令为python3.7 train.py --vocab_path='./senta_word_dict.txt'     --device=gpu     --network=lstm     --lr=5e-4     --batch_size=64     --epochs=10 --save_dir='./checkpoints'

相关包版本为：
paddlenlp (2.0.0rc17)
paddlepaddle (2.0.2)
paddlepaddle-gpu (2.0.2)

GPU型号为A100
Driver Version: 460.32.03    CUDA Version: 11.2  cuDNN Version: 8.1

报错信息为

SystemError: (Fatal) Operator uniform_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

**Comment by ZeyuChen** [comment]
有可能是cuda驱动问题。
飞桨框架2.0版本对cuda11.0的支持是experimental的，如果您使用的是非安培架构（A100）的GPU，建议使用CUDA10.2
@shanliang1992 
可以看一下官网的安装文档有说明。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
