### ISSUE TITLE
评论观点抽取打标问题

### ISSUE THREAD

**Issue by xulangping** [PaddlePaddle/PaddleNLP#2622]
您好，请问想用doccano打标评论观点抽取任务的话，要怎么操作呀，感觉是不是不支持呀，[正向，负向]这个好像无法嵌入原文中

**Comment by wawltor** [comment]
docanno的具体使用文档可以见 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/16698950/175288172-ac35261e-644b-44be-9194-68d0d9c63d66.png">

如果需要对评论观点词进行分类
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/16698950/175288272-d8660f0e-cb5f-4c0f-be94-1a77b47fd47b.png">

并在在做数据转化的过程中可以见脚本 
```python
python doccano.py \
    --doccano_file ./data/doccano_ext.json \
    --task_type "ext" \
    --save_dir ./data \
    --splits 0.8 0.1 0.1 \
    --prompt_prefix "情感倾向" \
    --options "正向" "负向" \
    --seperator "##"
```
