### ISSUE TITLE
paddlenlp 提示信息 无法使用GPU

### ISSUE THREAD

**Issue by Dicksilk** [PaddlePaddle/PaddleNLP#2627]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
PaddleNLP 0.0.0.0post （develop版本） PaddlePaddle-gpu 2.3.0post110

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
Windows python3.8

提示信息：
W0623 16:31:42.227226 22028 pybind.cc:2057] Cannot use get_all_custom_device_type because you have installedCPU/GPU version PaddlePaddle.
If you want to use get_all_custom_device_type, please try to install CustomDevice version PaddlePaddle by: pip install paddlepaddle-core

**Comment by Dicksilk** [comment]
![image](https://user-images.githubusercontent.com/51978627/175267345-7ec7b169-8884-4551-b7a6-342cf4d8ebc9.png)

**Comment by wawltor** [comment]
这个问题可以这个issue有点类似 https://aistudio.baidu.com/paddle/forum/topic/show/1729451 

想问一下GPU的型号是啥了？

**Comment by Dicksilk** [comment]
是的 有两个显卡 一个集显一个独显 
![image](https://user-images.githubusercontent.com/51978627/175437846-731beda9-b71b-4b25-8d66-ddcbccd65896.png)

**Comment by wawltor** [comment]
你看看能不能通过device_id的设置来访问独显

**Comment by Dicksilk** [comment]
> 你看看能不能通过device_id的设置来访问独显

如果要用taskflow的话，要在哪个位置设置device_id

**Comment by Dicksilk** [comment]
> 你看看能不能通过device_id的设置来访问独显
device_id只能为0 不然会报错
我在环境里输出了一下GPU信息，只有一张GPU
![image](https://user-images.githubusercontent.com/51978627/175459200-f53688b5-946a-4fd8-b1f4-36df23fabf10.png)

**Comment by wawltor** [comment]
> > 你看看能不能通过device_id的设置来访问独显
> > device_id只能为0 不然会报错
> > 我在环境里输出了一下GPU信息，只有一张GPU
> > ![image](https://user-images.githubusercontent.com/51978627/175459200-f53688b5-946a-4fd8-b1f4-36df23fabf10.png)

嗯嗯  因为集显没有想要的版本了，只能用到nvidia的独显那块

**Comment by Dicksilk** [comment]
那应该怎么去调整呢
