### ISSUE TITLE
问一下有没有能输入一个三四百字的文件，之后模型能抽出文件主要内容的模型？

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2635]
最好是训练时能输入文件和人工总结的主要内容，模型能学习到，是不是这块还没有表现很好的模型？

**Comment by wawltor** [comment]
这个看起来是文本摘要的模型，目前业界还没有非常的文本摘要模型，目前我们也在做一些文本摘要的尝试性工作
