### ISSUE TITLE
UIE问题

### ISSUE THREAD

**Issue by jiangix-paper** [PaddlePaddle/PaddleNLP#2639]
有几个问题请教一下：
（1）如果是金融领域的事件抽取微调，假设我们自定义了100个金融事件，如果微调的话，是否需要每个事件都提供5条左右的样本才会得到比较好的效果？
（2）如果篇章级事件抽取，采用逐句方式来做。是否需要对每个句子的抽取结果做后续的清洗呢？比如：事件去重，事件主体关联等

**Comment by wawltor** [comment]
（1）是的，尽可能让模型看到更多的样本
（2）这里说的事件去重、事件主体关联具体含义可以解释一下吗？
