### ISSUE TITLE
examples里lm预训练数据的创建，这里是不是有问题

### ISSUE THREAD

**Issue by cheerser** [PaddlePaddle/PaddleNLP#264]
https://github.com/PaddlePaddle/PaddleNLP/blob/0e37041a286be7274e6e2b637767d0b5ad428667/examples/language_model/bert/create_pretraining_data.py#L214

这里的 segment 是一个字典，所以取 len 并没实际的什么意义，返回永远是2。

**Comment by Steffy-zxf** [comment]
你好！上述的`segment`应该是一个字符串，表示一个句子。所以取length，是获取当前句子的字数。

**Comment by cheerser** [comment]
您好！感谢回复。我仔细看了一下，segment的含义是一行的分词结果，按理应该是一个列表。也就是156行 `tokens = tokenizer.tokenize(line)` 是正常的。然而被注释掉，改成了第157行 `tokens = tokenizer(line)` 。这种`__call__` 的方式，会返回一个字典，导致出问题。

**Comment by Steffy-zxf** [comment]
感谢反馈！由于tokenizer api后续升级变动导致的，确实应该修改为`tokenizer.tokenize(line)`。

修复pr：https://github.com/PaddlePaddle/PaddleNLP/pull/276/files
