### ISSUE TITLE
分布式程序产生的 main_shardin* 和 start_sharding* 的作用是什么？可以删除或者隐藏么？ 

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/PaddleNLP#2645]
分布式程序产生的 main_shardin* 和 start_sharding* 的作用是什么？可以删除或者隐藏么？ 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/3206718/175776251-53f9952d-cf5b-4c40-83c8-a9afa74f3883.png">

**Comment by joey12300** [comment]
请问你运行的是哪个模型的脚本呢

**Comment by ZHUI** [comment]
您好，是厂内用户吗？可以加入如流用户群咨询，5165068
