### ISSUE TITLE
如何多GPU并行训练？

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/PaddleNLP#2646]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
请问训练时如何使用多卡并行训练？

**Comment by wawltor** [comment]
您好，具体是哪个任务了？ 一般都是python -m paddle.distributed.launch --gpus "0,1,2" xxx.py

**Comment by Chucy2020** [comment]
> 您好，具体是哪个任务了？ 一般都是python -m paddle.distributed.launch --gpus "0,1,2" xxx.py

![Uploading image.png…]()

您好，我的任务是我使用paddlenlp自己写的关于阅读理解方面的任务，当没加python -m paddle.distributed.launch --gpus "0,1,2"这个语句时，会默认第一张卡，使用这个语句时会报上面错误。即没有日志。请问这个日志是怎么回事？该怎么处理？

**Comment by wawltor** [comment]
上面的图片展示不出来了

**Comment by Chucy2020** [comment]
> 上面的图片展示不出来了

![image](https://user-images.githubusercontent.com/73978694/175849942-2baf9b5d-d372-4b6e-9cc3-0166cab23b8a.png)

您好，图片我重新上传了。

**Comment by wawltor** [comment]
你看看执行的目录下是不是有个log目录

**Comment by Chucy2020** [comment]
> 你看看执行的目录下是不是有个log目录

您好，请问您说的执行目录是我xxx.py文件所在目录下，还是报的错误.../fleet/launch_utils.py目录下？我的xxx.py所在目录下是有个log文件，但是是其他py文件生成的。

**Comment by Chucy2020** [comment]
> 你看看执行的目录下是不是有个log目录

![image](https://user-images.githubusercontent.com/73978694/175852690-c5110118-89b9-429d-887f-cd03b2d1bcf1.png)
我删除了我py目录下的log文件，使用python -m paddle.distributed.launch --gpus "0,1,2" xxx.py时出现上面这个问题。请问这个问题是什么方面的问题？

**Comment by LiuChiachi** [comment]
xxx.py文件所在目录下的log看下worker.log1文件，看起来是第卡1有报错

**Comment by Chucy2020** [comment]
> xxx.py文件所在目录下的log看下worker.log1文件，看起来是第卡1有报错

![image](https://user-images.githubusercontent.com/73978694/175854473-077d55a9-5d14-4632-84fc-fa24bf449858.png)
您好，是您说的那个问题，但是我有个疑惑，为什么我不用这个语句，就可以使用第一张卡训练，现在使用了这个语句就会出现这个问题？还有我该怎么解决这个问题？谢谢。

**Comment by LiuChiachi** [comment]
unset CUDA_VISIBLE_DEVICES试一下？

**Comment by Chucy2020** [comment]
> unset CUDA_VISIBLE_DEVICES试一下？

问题已解决，感谢大佬们的热心解答。

**Comment by wawltor** [comment]
看问题已经解决，我们将关闭ISSUE，后续有问题可以继续打开该ISSUE。
