### ISSUE TITLE
自定義vocab.txt

### ISSUE THREAD

**Issue by NatLee** [PaddlePaddle/PaddleNLP#2649]
各位先進大家好

想請問預訓練的`ernie-1.0`是否能夠自行擴增`vocab.txt`

例如以下的tokenizer

```py
import paddlenlp as ppnlp
tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained("ernie-1.0")
```

我們是否可以再自行新增token？

查詢了一下issue表發現有人問`ErnieGramTokenizer`

https://github.com/PaddlePaddle/PaddleNLP/issues/2022

但不知道`ErnieForSequenceClassification`是不是也無法自行擴增

謝謝！

**Comment by ZHUI** [comment]
ernie-1.0 的词表中，有部分unused 的 token，如果你新加的token不多的话，可以试一试替换 unused

**Comment by NatLee** [comment]
@ZHUI 謝謝回覆！

可是`unused`的token只有九十多個，如果超過的話是不是就無法新增了？

**Comment by ZHUI** [comment]
需要的话，可以自己 resize 一下 vocab, 这里有一个 resize_position_embeddings 的例子。  https://github.com/PaddlePaddle/PaddleNLP/pull/2513

**Comment by NatLee** [comment]
@ZHUI 謝謝回覆！

那個例子看起來是`resize_position_embeddings`的參數

我看預設的設置內，`init_args`的`vocab_size`只有`18000`

![image](https://user-images.githubusercontent.com/10178964/175881122-ff984189-ea0b-4759-903a-4e60a245cddc.png)

想請問就是如果我取用預訓練模型，我有辦法去更改這個設置嗎？

謝謝！

**Comment by ZHUI** [comment]
没有关系的，这里是重新赋值了一遍 embedding

https://github.com/PaddlePaddle/PaddleNLP/blob/c92810b1ffc6a4becfadf6cc59a7575f2a2bd49a/paddlenlp/transformers/layoutlmv2/modeling.py#L825-L834

**Comment by NatLee** [comment]
@ZHUI 這個功能大約什麼時候會被merge進主分支呢？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2423 
抱歉，好像已经支持了

**Comment by ZHUI** [comment]
抱歉，可以试一下这个 https://github.com/PaddlePaddle/PaddleNLP/pull/2423/files
resize_token_embeddings

**Comment by NatLee** [comment]
@ZHUI 這個在develop分支，之後預計會release？

**Comment by ZHUI** [comment]
本周内应该会有release
