### ISSUE TITLE
bvar is busy at sampling for 2 seconds! 模型训练的时候报这个错误

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleNLP#2653]
bvar is busy at sampling for 2 seconds! 
模型训练的时候报这个错误! 使用的是py3.7, paddlepaddle是paddlepaddle-gpu -2.3.0.post112

**Comment by LiuChiachi** [comment]
跑的代码是？是否有最小可复现代码呢，欢迎提供

**Comment by chinesejunzai12** [comment]
就是实体识别的代码,直接使用的ernie模型, 就是数据量比较大而已

**Comment by syy-love** [comment]
大佬这个问题解决了吗 我也遇到了

**Comment by LiuChiachi** [comment]
我简单搜了一下，
https://github.com/apache/incubator-brpc/issues/1383，
这个报错可能是机器的原因。如果还是无法解决可以提供代码，我们可以排除下是否是代码的原因。尽管我们这边的模型通常有监控，在看到你的代码之前也不能直接下结论～
如果 @chinesejunzai12 解决问题了，也欢迎分享下解决方案～

**Comment by chinesejunzai12** [comment]
目前还没有解决, 你解决了没



------------------------------------------------------------------
发件人：syy-love ***@***.***>
发送时间：2022年7月21日(星期四) 11:11
收件人：PaddlePaddle/PaddleNLP ***@***.***>
抄　送：侯晓君 ***@***.***>; Author ***@***.***>
主　题：Re: [PaddlePaddle/PaddleNLP] bvar is busy at sampling for 2 seconds! 模型训练的时候报这个错误 (Issue #2653)

大佬这个问题解决了吗 我也遇到了

**Comment by gongel** [comment]
PaddleCloud上分布式训练遇到同类问题
```
W1010 12:09:33.116123  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1010 12:28:02.186561  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1010 12:37:58.280712  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1010 12:45:28.541734  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1010 13:01:37.161469  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1010 13:14:19.418007  2635 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
```

**Comment by gongel** [comment]
一般是内存爆了，常见于GPT3等的预训练任务
