### ISSUE TITLE
paddleNLP使用在名片抽取任务

### ISSUE THREAD

**Issue by xuhui1994** [PaddlePaddle/PaddleNLP#2654]
我想paddleNLP使用在名片信息抽取任务上，比如schema = ["姓名","职位","部门","公司","地址","邮箱","手机","电话"]，我也自定义了20条数据微调了一下，效果提升了一点，但是特别是手机，电话号码，邮箱这些抽取时经常出错，请问怎么样能更加提升精度

**Comment by linjieccc** [comment]
@xuhui1994 可以在评估阶段通过`debug`模式，分别看下每个类别的精确度和召回率，针对性地增加一些标注数据
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#%E6%A8%A1%E5%9E%8B%E8%AF%84%E4%BC%B0
