### ISSUE TITLE
neural_search中召回和排序是独立的，缺一个能连接起来的程序，能否提供一下？

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2664]
能将
召回的inference.py
排序的predict_pairwise.py
连接起来的程序，执行一个.py文件就能过召回和排序，直接输出排序结果

**Comment by w5688414** [comment]
排序模型的serving的代码已经完成，这是pr。

https://github.com/PaddlePaddle/PaddleNLP/pull/2721

整个流程连接起来正在开发中，serving服务都出来了，您可以尝试一下串联，直接发请求，这个应该不难

**Comment by gg22mm** [comment]
> 能将
> 召回的inference.py
> 排序的predict_pairwise.py
> 连接起来的程序，执行一个.py文件就能过召回和排序，直接输出排序结果

搞定了吗？

**Comment by gg22mm** [comment]
> serving服务

不用serving服务行不行，想直接运行代码简单测试，也不用那些Document Store
