### ISSUE TITLE
FasterTokenizer和Tokenizer的兼容问题

### ISSUE THREAD

**Issue by SunYanCN** [PaddlePaddle/PaddleNLP#2673]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！

**两个实现的API不兼容**：
1. FasterTokenizer需要用to_tensor转换，建议改到FasterTokenizer内部转换
2. FasterTokenizer 没有.pad 方法，建议两个形式的Tokenizer API对齐，可以一键切换

**Comment by joey12300** [comment]
您好，请问您是用的这个吗？https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/experimental/faster_tokenizer.py

您具体在什么场景使用呢？我看看如何升级一下。
