### ISSUE TITLE
faq_system 预训练模型404问题

### ISSUE THREAD

**Issue by luxu1220** [PaddlePaddle/PaddleNLP#2674]
执行无监督训练时报错
RuntimeError: Downloading from https://paddlenlp.bj.bcebos.com/models/transformers/community/rocketqa-zh-dureader-query-encoder/model_state.pdparams failed with code 404!

环境是 aistudio

**Comment by tianxin1860** [comment]
可以贴一下具体的 AIStudio 项目地址。

**Comment by tianxin1860** [comment]
请确保 paddlenlp 升级到最新版本 2.3.4

**Comment by luxu1220** [comment]
确实是进项目需要更新paddlenlp的版本
