### ISSUE TITLE
为什么文本分类的模型，每次预测的结果都不一样呢

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleNLP#2676]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/predict.py

**Comment by wawltor** [comment]
您好，有可能是模型加载不成功，看看路径是否正确，可以通过下面的日志来确认
<img width="487" alt="image" src="https://user-images.githubusercontent.com/16698950/176342178-cad475cf-642c-4335-a3ba-d7ccd6c4090b.png">

**Comment by sweetboxwwy** [comment]
懂啦。我训练用的是bert，但是预测那里用的是ernie。这样即便加载的路径没问题，但是预测一样会有问题，请问预测那里的model怎么修改为bert的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月29日(星期三) 中午11:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 为什么文本分类的模型，每次预测的结果都不一样呢 (Issue #2676)





 
您好，有可能是模型加载不成功，看看路径是否正确，可以通过下面的日志来确认

**Comment by sweetboxwwy** [comment]
谢谢！我训练模型是bert，但是预测模型用的ernie~

**Comment by tianxin1860** [comment]
> 

不建议这样哈，建议训练和预测阶段的模型保值一致。

**Comment by sweetboxwwy** [comment]
好滴谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 上午8:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 为什么文本分类的模型，每次预测的结果都不一样呢 (Issue #2676)





   
不建议这样哈，建议训练和预测阶段的模型保值一致。
