### ISSUE TITLE
重复调用代码和显示

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/PaddleNLP#2677]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
Linux 
python 3.8
paddle --> 2.3
paddlenlp --> 2.3.3

![image](https://user-images.githubusercontent.com/73978694/176339104-e2ed1f3d-55f3-4193-b0d4-3fa7a8cf6c19.png)

使用代码 python -m paddle.distributed.launch --gpus "0,1,2,3"  train.py 请问这是什么问题？

**Comment by wawltor** [comment]
您好，这个是因为多卡训练，每张卡都要输出自己的日志，日志部分重复是没有问题的，想问一下目前多卡训练存在其他问题吗？

**Comment by Chucy2020** [comment]
> 

多卡暂时还没有什么问题，只是有时使用多卡时运行还是在单卡上，后续有问题会及时提issue，请教你们。
另外，为什么我用了四张卡这里只显示两个重复的日志？
