### ISSUE TITLE
信息抽取在精调模型中schema的定义问题

### ISSUE THREAD

**Issue by guoxiaoyue111111** [PaddlePaddle/PaddleNLP#2688]
您好，关于在信息抽取的精调中schema的定义，需要请教一个问题~
 
在实际业务中，schema的定义比较复杂，一个关系抽取的schema可能涵盖十多个甚至更多的关系，但是在抽取文本中，这些关系散落在多个不同的段落。这种情况下，是要调整schema（减少关系对）吗还是调整抽取文本（多段合并在一起）？那么，schema设置为多少个关系对最优呢？

**Comment by wawltor** [comment]
理论上是不要调整schema和调整文本段落的，因为schema的设置会在某在文档都是预测所有的关系，没有关系的置信度太低就不会输出，这个最大的问题是在于预测性能的问题，UIE的性能是和schema的大小有关。
对于性能问题，我们会在后续发布模型蒸馏的功能，逻辑是先用UIE的小样本功能快速得到一个效果不错的模型，然后通过UIE对大量的样本进行打标签，最终我们把打标签的样本在BIO体系的模型上进行训练，得到的模型在预测速度上会大大提升！

**Comment by guoxiaoyue111111** [comment]
收到，非常感谢您的回答~
