### ISSUE TITLE
huggingFace模型转换为paddle

### ISSUE THREAD

**Issue by cdj0311** [PaddlePaddle/PaddleNLP#2689]
大佬好！
   paddnlenlp提供了很多直接从huaggingface转换过来的模型，请问这些转换脚本在哪儿呢？

**Comment by linjieccc** [comment]
您好，这里有个转换脚本可以参考下：
https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.3/community/Langboat/convert_bert.py

**Comment by cdj0311** [comment]
好的，感谢！
