### ISSUE TITLE
sentiment_analysis/skep/下的predict_sentence.py文件每次运行的结果不一样

### ISSUE THREAD

**Issue by LoveCloud** [PaddlePaddle/PaddleNLP#2703]
paddlenlp 版本2.3.3
直接运行predict_sentence.py --params_path D:\doc\package\models\skep_ernie_1.0_large_ch\skep_ernie_1.0_large_ch.pdparams --device cpu

第一次结果
Loaded parameters from D:\doc\package\models\skep_ernie_1.0_large_ch\skep_ernie_1.0_large_ch.pdparams
Data: 这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般 	 Label: negative
Data: 怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片 	 Label: negative
Data: 作为老的四星酒店，房间依然很整洁，相当不错。机场接机服务很好，可以在车上办理入住手续，节省时间。 	 Label: positive
Data: 肯德基的牛肉煲太好吃了。 	 Label: negative
Data: 皮太厚了，味道还不如吃个汉堡，不好吃，还很贵 	 Label: negative
Data: KFC的服务员服务态度太好了 	 Label: negative
Data: 对于不吃PIZZA的来说不太友好，没有满减优惠券 	 Label: positive

第二次结果

Loaded parameters from D:\doc\package\models\skep_ernie_1.0_large_ch\skep_ernie_1.0_large_ch.pdparams
Data: 这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般 	 Label: negative
Data: 怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片 	 Label: negative
Data: 作为老的四星酒店，房间依然很整洁，相当不错。机场接机服务很好，可以在车上办理入住手续，节省时间。 	 Label: negative
Data: 肯德基的牛肉煲太好吃了。 	 Label: negative
Data: 皮太厚了，味道还不如吃个汉堡，不好吃，还很贵 	 Label: negative
Data: KFC的服务员服务态度太好了 	 Label: negative
Data: 对于不吃PIZZA的来说不太友好，没有满减优惠券 	 Label: negative

第三次结果

Loaded parameters from D:\doc\package\models\skep_ernie_1.0_large_ch\skep_ernie_1.0_large_ch.pdparams
Data: 这个宾馆比较陈旧了，特价的房间也很一般。总体来说一般 	 Label: positive
Data: 怀着十分激动的心情放映，可是看着看着发现，在放映完毕后，出现一集米老鼠的动画片 	 Label: positive
Data: 作为老的四星酒店，房间依然很整洁，相当不错。机场接机服务很好，可以在车上办理入住手续，节省时间。 	 Label: positive
Data: 肯德基的牛肉煲太好吃了。 	 Label: positive
Data: 皮太厚了，味道还不如吃个汉堡，不好吃，还很贵 	 Label: positive
Data: KFC的服务员服务态度太好了 	 Label: positive
Data: 对于不吃PIZZA的来说不太友好，没有满减优惠券 	 Label: positive

模型配置信息也能打印

**Comment by wawltor** [comment]
预训练参数只是部分参数，需要微调之后才能加载全部参数
