### ISSUE TITLE
语义检索 Pipelines 安装运行报错找不到 faiss

### ISSUE THREAD

**Issue by tianxin1860** [PaddlePaddle/PaddleNLP#2704]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

```
export CUDA_VISIBLE_DEVICES=0
python examples/semantic-search/[semantic_search_example.py](https://github.com/PaddlePaddle/PaddleNLP/issues/semantic_search_example.py) --device gpu
```

报错如下:
![image](https://user-images.githubusercontent.com/6829601/176818396-11b99457-6ab0-4feb-9268-c25fee873855.png)

**Comment by tianxin1860** [comment]
解决方案如下:
pip install faiss-cpu or pip install faiss-gpu 即可

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2709
