### ISSUE TITLE
taskflow 中 question_answer 的md5 问题

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#2705]
每次使用gpt-cpm-large-cn初始化qa模型，都会
Updating static/inference.pdiparams from https://bj.bcebos.com/paddlenlp/taskflow/text_generation/gpt-cpm/gpt-cpm-large-cn_params.tar
查看代码是utils.py文件中有校验md5操作：
if os.path.exists(fullname):
        if md5 and (not md5file(fullname) == md5):
            logger.info("Updating {} from {}".format(filename, url))
            logger.disable()
            get_path_from_url(url, save_dir, md5)
经过测试，md5file(fullname) 更新前后都不变，为64d8dd294b9cda055ec62844f88a99cc
而 传入的md5 为 
URLS = {
    "gpt-cpm-large-cn": [
        "https://bj.bcebos.com/paddlenlp/taskflow/text_generation/gpt-cpm/gpt-cpm-large-cn_params.tar",
        "5aad6f81053cfdbba4797f044fcf66d1"
    ],
}
导致每次都会执行一次update，
麻烦修正一下，谢谢

**Comment by wawltor** [comment]
谢谢指正，我们快速查对一下！

**Comment by linjieccc** [comment]
多谢反馈，已PR修复 #2707
