### ISSUE TITLE
Pipeline 系统示例必须保证系统默认编码为 UTF8, 否则示例会报错

### ISSUE THREAD

**Issue by tianxin1860** [PaddlePaddle/PaddleNLP#2706]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

系统默认编码:
![image](https://user-images.githubusercontent.com/6829601/176825502-c24de85c-c190-4ca2-870c-f8b1e87bf4dd.png)

报错如下:
![image](https://user-images.githubusercontent.com/6829601/176825471-1edeb35f-83a8-4b38-8673-b341198ab679.png)

**Comment by tianxin1860** [comment]
解决方法: export LANG=zh_CN.UTF-8

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2709
