### ISSUE TITLE
生成的模型搜索不准确，而且每次执行的结果都不一致

### ISSUE THREAD

**Issue by yspyhp** [PaddlePaddle/PaddleNLP#2708]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）paddlenlp 2.3.3  paddlepaddle-gpu 2.3.0.post101
2）linux python3.9
- 复现信息：如为报错，请给出复现环境、复现步骤
- https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/simcse
根据这个文档操作有些疑问，生成的模型搜索不准确，而且每次执行的结果都不一致，哪位大佬能帮忙看下
![48a50f7f7a9919d6c88f10b717ce4136](https://user-images.githubusercontent.com/23613386/176849789-2a4116c6-d5ec-4cd0-bf8f-d7766013ce18.png)

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/2710
