### ISSUE TITLE
如何加载PaddleNLP文档中提及的其它团队的模型？

### ISSUE THREAD

**Issue by Jaybore** [PaddlePaddle/PaddleNLP#2711]
诸如这里的一些模型：
(https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/BERT/contents.html)
其中对于不是百度官方的模型，
通过复制名称的方式会提示没有找到模型。

请问如何才能加载它们？

**Comment by LemonNoel** [comment]
可以使用``AutoModel``和``AutoTokenizer``来加载，更多模型结构可以参考[源代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/auto/modeling.py#L25-L32)

```
from paddlenlp.transformers import AutoModel, AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
```

**Comment by Jaybore** [comment]
您好，这种方法确实可以对百度官方发布的模型进行加载，但是在doc里面有提到其他的诸如“uer/chinese-roberta-medium”的模型，使用这种方式进行加载的时候会提示没有对应的模型，请问如何解决？

**Comment by wawltor** [comment]
> 您好，这种方法确实可以对百度官方发布的模型进行加载，但是在doc里面有提到其他的诸如“uer/chinese-roberta-medium”的模型，使用这种方式进行加载的时候会提示没有对应的模型，请问如何解决？

可以看看PaddleNLP的版本，可以先升级一下PaddleNLP的版本，有些模型需要最新的版本才能使用

**Comment by Jaybore** [comment]
更新后可以使用了，非常感谢
