### ISSUE TITLE
example中的mrc2018报错，看了一下貌似是tokenizer_utils_base.py和chineseberttoken不兼容了

### ISSUE THREAD

**Issue by zltgo** [PaddlePaddle/PaddleNLP#2712]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.0
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
tokenizer_utils_base.py中调用self.batch_encode()时实际调用的是chinesebert的batch_encode,而后者输入参数中没有max_length
导致运行时报错
TypeError: batch_encode() got an unexpected keyword argument 'max_length'

**Comment by LemonNoel** [comment]
辛苦贴下代码的链接

**Comment by LemonNoel** [comment]
感谢指正！这里确实存在不兼容的问题，我们修复一下。请问具体跑的哪份代码呢？
