### ISSUE TITLE
ernie-health可不可以用于疾病诊断

### ISSUE THREAD

**Issue by tianmafly** [PaddlePaddle/PaddleNLP#2714]
输入一份病历，ernie-health给出疾病种类。
可以做到吗，或者训练少量病历数据，达到输出疾病种类

**Comment by wawltor** [comment]
这个应该就是病例分类，ernie-health可以做病例分类，不过数据量需要根据任务难度来

**Comment by tianmafly** [comment]
@wawltor 
请教几个问题哈，我不是算法工程师，所以有些问题比较基础：
1. "PaddleNLP中提供了ERNIE-Health训练好的模型参数。该版本为160G医疗文本数据上的训练结果"。 这个指的是ernie-health-chinese.pdparams模型吗？
2. "数据量应尽可能接近ERNIE-Health论文中训练数据的量级，以获得好的预训练模型效"。这个数据量指的是160G吗？
3. ernie-health的run_pretrain_trainer.py是为了生成预训练模型吗？不是已经有了预训练模型ernie-health-chinese.pdparams？
4. 输入一份病历，ernie-health给出疾病种类。需要用run_pretrain_trainer.py生成预训练模型，还是直接用预训练模型ernie-health-chinese.pdparams就可以了
谢谢

**Comment by wawltor** [comment]
1. ernie-health-chinese.pdparams 是 160G语料训练的结果
2. 是的 
3. 这里的预训练是说用户对自己的场景有更高的要求，可以尝试进行预训练
4. 不需要run_pretrain_trainer.py再次训练，可以ernie-health-chinese.pdparams来进行微调，这里需要加入一些有标签病例种类的样本然后进行微调

**Comment by tianmafly** [comment]
ernie-health中的cblue的train_classification.py例子中，带有的KUAKE-QIC多分类数据集可达到0.8的准确率。
但使用真实病例数据，两种疾病，batch_size=256，epoch=100，其他的都是默认参数。训练集准确率在0.99左右，验证集准确率在0.5左右。
python -m paddle.distributed.launch --gpus 0 train_classification_cdss.py --dataset CHIP-CDN-2C --batch_size 256 --max_seq_length 32 --learning_rate 3e-5 --epochs 100 --device gpu
两种疾病训练集均为1200份，验证集均为300份。
![Screenshot from 2022-07-08 14-45-35](https://user-images.githubusercontent.com/38370307/177933093-beaa4021-ae64-4948-aa85-e475fe6b7512.png)

请问是病历不准确，还是训练集数据量不够？还是其他原因导致准确率这么低？
@wawltor

**Comment by LemonNoel** [comment]
验证集准确率最高是0.5左右吗？KUAKE- QIC有将近7000条训练样本，CHIP-CDN-2C更多。这个场景有可能是过拟合了，可以适当减小下valid_steps和epoch再看看效果
