### ISSUE TITLE
Albert微调报错：not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Jaybore** [PaddlePaddle/PaddleNLP#2715]
继上次的bug之后（https://github.com/PaddlePaddle/PaddleNLP/issues/2529），
在根据提供的方法修改代码后出现了新的报错，报错代码如下
![image](https://user-images.githubusercontent.com/100829033/176995878-e23e1268-5cdc-4b34-acd9-d80f7ffaf100.png)

请问如何解决？

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/f6a8a5a26185c046279c3a3cda744f80c0bf2bf5/paddlenlp/transformers/albert/modeling.py#L1720

<img width="724" alt="image" src="https://user-images.githubusercontent.com/16698950/177004808-4986c139-ebf3-4e86-bb85-6f2c978fcc46.png">

您好，您把 num_or_sections=1 改成  num_or_sections=2试试

**Comment by Jaybore** [comment]
可以了 非常感谢
