### ISSUE TITLE
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by tianmafly** [PaddlePaddle/PaddleNLP#2716]
pandas是1.3.4。python3.7.4.
一开始的错误是：
from _lzma import *
ModuleNotFoundError: No module named '_lzma'

按照网上说的，改了lzma.py文件：
把 from _lzma import *
from _lzma import _encode_filter_properties, _decode_filter_properties
改成
try:
from _lzma import *
from _lzma import _encode_filter_properties, _decode_filter_properties
except:
from backports.lzma import *
from backports.lzma import _encode_filter_properties, _decode_filter_properties
不报错误了from _lzma import *
ModuleNotFoundError: No module named '_lzma'。

但报错
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'
如何解决？

**Comment by wawltor** [comment]
这个issue可以看看 https://github.com/pytorch/vision/issues/2921

**Comment by wawltor** [comment]
然后再不行的话，可以升级python版本到3.8试试

**Comment by tianmafly** [comment]
谢谢，换成python3.8后可以了
发现自动安装的pandas的版本是最新的1.4.3，python3.7.4安装不了pandas1.4.3。可能和这个也有关系。

**Comment by tianmafly** [comment]
也不用修改lzma.py这个文件了

**Comment by joy0921** [comment]
python版本就是3.8也报这个错

**Comment by starevelyn** [comment]
其他地方找到的：
需要安装liblzma-dev后重新编译安装Python
apt-get install liblzma-dev
重新安装Python

**Comment by galen2027** [comment]
我也遇到这样的问题。我当前的版本是python3.10.12
之前有类似的报错，是按照楼主的方式解决的，现在楼主是升级版本解决，但是我这边目前还没有找到解决办法
root@h3c-amd:~# pip3 list |grep  torchvision
torchvision              0.15.2
root@h3c-amd:~# apt  list  --installed  |grep liblzma
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
liblzma-dev/oldstable,now 5.2.5-2.1~deb11u1 amd64 [installed]
liblzma5/oldstable,now 5.2.5-2.1~deb11u1 amd64 [installed]

**Comment by yusuhua** [comment]
> 我也遇到这样的问题。我当前的版本是python3.10.12 之前有类似的报错，是按照楼主的方式解决的，现在楼主是升级版本解决，但是我这边目前还没有找到解决办法 root@h3c-amd:~# pip3 list |grep torchvision torchvision 0.15.2 root@h3c-amd:~# apt list --installed |grep liblzma WARNING: apt does not have a stable CLI interface. Use with caution in scripts. liblzma-dev/oldstable,now 5.2.5-2.1~deb11u1 amd64 [installed] liblzma5/oldstable,now 5.2.5-2.1~deb11u1 amd64 [installed]

我的python版本是3.10.13，遇到这个问题，用@starevelyn 的方法解决了。
apt-get install liblzma-dev
然后重新编译安装Python
