### ISSUE TITLE
使用微调程序run_qa.py微调RoFormer模型时报错

### ISSUE THREAD

**Issue by Jaybore** [PaddlePaddle/PaddleNLP#2717]
同我之前的操作一样，https://github.com/PaddlePaddle/PaddleNLP/issues/2493

使用了https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_qa.py
运行ernie模型时可以正常进行微调，之前Bert不能正常微调，但已经修复。

近期在我使用RoFormer模型尝试微调时，在tokenize数据集时出现了同样的报错：substring not found
再次劳烦问下如何解决？

**Comment by joey12300** [comment]
@Jaybore 您好，请问可以提供一下复现的代码，命令行参数吗？我这边试着复现一下

**Comment by Jaybore** [comment]
我使用的就是官方提供的这个代码，只不过更改了模型名称
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/run_qa.py

**Comment by joey12300** [comment]
@Jaybore 嗯嗯，请问您具体使用的roformer模型是哪个呢？目前使用jieba作为预切词器的tokenizer是不支持offset mapping功能的，即不支持阅读理解任务。现阶段RoFormer模型中，`roformer-chinese-small`和`roformer-chinese-base`的模型由于使用jieba作为预切词器，所以这两个模型暂时不支持阅读理解任务。后续将会发布功能齐全的高性能切词工具的`faster tokenizer`，支持不同类别的tokenizer offset mapping功能。
