### ISSUE TITLE
RuntimeError:  mkdir failed!

### ISSUE THREAD

**Issue by gjr666** [PaddlePaddle/PaddleNLP#2718]
paddlenlp                 2.3.4
paddlepaddle              2.3.0
python                    3.6.10
在windows 环境下运行示例报错，
![image](https://user-images.githubusercontent.com/56302085/177041793-3e5853e8-e38f-48c8-bc61-ffda5d7eca53.png)
错误如下：
![image](https://user-images.githubusercontent.com/56302085/177041816-bad5ebf2-cfd4-4a49-8eda-cc0c1681c377.png)
![image](https://user-images.githubusercontent.com/56302085/177041818-81a4f04e-3a36-41f8-b486-293f0f20c140.png)

**Comment by wawltor** [comment]
看看硬盘空间是否足够，同时排查下面的路径是否有文件读写权限
<img width="339" alt="image" src="https://user-images.githubusercontent.com/16698950/177070263-d0ce6c4f-e970-466d-a941-dcaeeaea6e60.png">
