### ISSUE TITLE
plato-mini tokenizer

### ISSUE THREAD

**Issue by ssrssrcode** [PaddlePaddle/PaddleNLP#2723]
你好，请问一下像plato-mini模型的词表没有预留unused如何添加自定义的特殊字符呢？另外，发现UnifiedTransformerTokenizer对于词表中已有的[MASK],[SEP]等token也无法正确识别，请问是什么原因呢

**Comment by FrostML** [comment]
1. 只能说重新构造 embedding，比如现有词表 30001，需要额外增加 100 个特殊字符，只能先 load 模型，将参数 dump 下来，将多的 100 个 embedding 拼接到已有的词表上面，构造新的词表 30101，并在此基础上构造新的模型，重新 load。

2. 可以给段代码看看具体的问题或是报错么？

**Comment by ssrssrcode** [comment]
`from paddlenlp.transformers import UnifiedTransformerTokenizer
tokenizer = UnifiedTransformerTokenizer.from_pretrained('plato-mini')
tokenizer._tokenize('A [SEP] B')`
`['▁A', '▁[', 'S', 'E', 'P', ']', '▁B']`
`tokenizer.vocab._token_to_idx['[SEP]']`
`2`

**Comment by ssrssrcode** [comment]
```
from paddlenlp.transformers import UnifiedTransformerTokenizer
tokenizer = UnifiedTransformerTokenizer.from_pretrained('plato-mini')
tokenizer._tokenize('A [SEP] B')
['▁A', '▁[', 'S', 'E', 'P', ']', '▁B']
```

**Comment by FrostML** [comment]
了解了，目前无法 tokenize special token，可以先 `tokenizer.dialogue_encode(["A", "B"])`，会自动加上 `[SEP]` 所表示的 id 2。

这个问题我详细定位下。
