### ISSUE TITLE
python -u -m paddle.distributed.launch --gpus "0" finetune.py怎么在IDE添加前面的参数

### ISSUE THREAD

**Issue by pengfan7758258** [PaddlePaddle/PaddleNLP#2725]
python -u -m paddle.distributed.launch --gpus "0" finetune.py
这个前面的-u -m paddle.distributed.launch --gpus "0"这些参数怎么在pycharm或者vscode这些ide里面添加并指定

**Comment by wawltor** [comment]
如果你是单卡训练，直接 python  finetune.py即可

**Comment by pengfan7758258** [comment]
emmm，询问一下多卡

**Comment by wawltor** [comment]
> emmm，询问一下多卡

如果已经安装了paddlepaddle-gpu的版本，理论上是可以直接 python -u -m paddle.distributed.launch --gpus "0,1 " finetune.py  （--gpus 可以设定卡号）

**Comment by pengfan7758258** [comment]
@wawltor 不是在命令行运行程序，我想点击后运行，譬如下图的红色框
<img width="1557" alt="log" src="https://user-images.githubusercontent.com/62168810/177515997-c47671bb-478f-4a24-90ce-13df4347d604.png">

vscode当中我应该怎么操作或者说加上什么代码能让我用多个gpu

**Comment by wawltor** [comment]
多卡执行的方式目前只能通过ide的方式来执行了
