### ISSUE TITLE
unimo-text-1.0模型FasterTransformer加速cmake报错

### ISSUE THREAD

**Issue by shukhg** [PaddlePaddle/PaddleNLP#2726]
11

**Comment by shukhg** [comment]
“按照相似问题修改后” 是按照 “FrostML commented May 6, 2022 Commit” 说到的把 try-catch 去除后看报错信息

**Comment by gongel** [comment]
看上去是网络问题，[这个](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/CMakeLists.txt#L377)没下载下来，你看看能手动git clone吗

**Comment by shukhg** [comment]
已经解决，git 网络有问题，修复即可。
建议先看看 git 是否可用，如果可用的话则没问题
