### ISSUE TITLE
semantic-search用CPU跑时出现ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 513

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#2729]
centos：7.5
anaconda->python：3.8.5
PaddlePaddle2.3.0（CPU）

尝试搭建：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/experimental/pipelines/examples/semantic-search中的CPU版本时：
unset CUDA_VISIBLE_DEVICES
python examples/semantic-search/semantic_search_example.py --device cpu，之后，出现如下错误：
![微信截图_20220704214439](https://user-images.githubusercontent.com/100854336/177167449-a3d31416-3886-439d-8e11-3c5d79394f7f.png)

请问什么情况？如何处理？谢谢

**Comment by FrostML** [comment]
单看报错信息是因为输入的 id 超过了 embedding 所能表示的词表最大的大小，可以确认下输入的 id 是否都在 embedding 所能表示的 id 范围内。
