### ISSUE TITLE
文本分类任务如果要做四分类的话需要修改哪些地方呢

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleNLP#2731]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models
想要修改chnsenticorp数据集的情感分类二分类任务为四分类任务，应该要修改哪些地方呢

**Comment by lugimzzz** [comment]
建议直接使用[文本多分类application](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class)，参考文档中从本地文件创建数据集的方式处理自己的数据集(建议划分成训练集和开发集)就可以直接进行训练了。
按照下面的格式组织数据就可以自定义训练自己的数据，可以见文档
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/16698950/177238820-ac8c1d49-8eaa-4b39-9e59-881273b9f8a7.png">

**Comment by sweetboxwwy** [comment]
请问如果我想使用bert训练的话应该怎么修改model呢

**Comment by lugimzzz** [comment]
可以通过修改参数实现，更多可配置参数参考[文本多分类模型微调](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class#%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83)，PaddleNLP已内置了多种bert模型，详情可以参考[BERT模型汇总](https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/BERT/contents.html)。
```shell
python train.py --warmup --dataset_dir data --model_name bert-base-uncased
```
![image](https://user-images.githubusercontent.com/63761690/177284214-70ae69a3-21f3-4d4f-b3f0-309279332438.png)

**Comment by lugimzzz** [comment]
对于中文分类任务推荐使用ERNIE3.0系列模型，ERNIE 3.0 在精度和性能上的综合表现已全面领先于其他中文预训练模型，模型效果详见[ERNIE 3.0 模型效果](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0#%E6%A8%A1%E5%9E%8B%E6%95%88%E6%9E%9C)可以根据设备和精度需求选择合适的ERNIE 3.0模型，多分类application默认推荐使用ernie-3.0-base-zh。英文文本分类任务推荐使用ernie-2.0-base-en。

**Comment by sweetboxwwy** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月5日(星期二) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 文本分类任务如果要做四分类的话需要修改哪些地方呢 (Issue #2731)





 
对于中文分类任务推荐使用ERNIE3.0系列模型，ERNIE 3.0 在精度和性能上的综合表现已全面领先于其他中文预训练模型，模型效果详见ERNIE 3.0 模型效果可以根据设备和精度需求选择合适的ERNIE 3.0模型，多分类application默认推荐使用ernie-3.0-base-zh。英文文本分类任务推荐使用ernie-2.0-base-en。

**Comment by ZeyuTeng96** [comment]
4分类，直接用ernie_3.0_base_zh与训练模型就好了。然后用下面链接里的ernieForSequenceClassification类即可，使用时记得修改num_classes = 4. 具体使用样例就是：

 import paddle
from paddlenlp.transformers import ErnieForSequenceClassification, ErnieTokenizer

tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
model = ErnieForSequenceClassification.from_pretrained('ernie-1.0', num_classes = 4)

Loss就用CrossEntropyLoss即可

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py

**Comment by lugimzzz** [comment]
问题已解决
