### ISSUE TITLE
信息抽取指定模型路径

### ISSUE THREAD

**Issue by jiangix-paper** [PaddlePaddle/PaddleNLP#2733]
您好，在使用taskflow的information_extraction功能时，需要指定模型的路径，是采用如下命令吗？
ie = Taskflow('information_extraction', schema=schema, task_path='../../')

**Comment by wawltor** [comment]
可以的，可以按照下面的方式来定制模型路径 
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/16698950/177246512-d3efcb6e-c485-4494-8fa9-27ea8ffa332e.png">
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by wawltor** [comment]
@jiangix-paper 您好 自定义路径上面还有问题吗？
