### ISSUE TITLE
在 Machine Translation 例子中，缺失 数据准备 这一步的教程。

### ISSUE THREAD

**Issue by gpengzhi** [PaddlePaddle/PaddleNLP#2740]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer
在我们的基于 Transformer 的 Machine Translation 例子中，数据准备这一步奏仅提供了一个预处理好的 WMT14 en-de 数据，并没有告诉读者该怎么处理数据，每一步应该怎么做，可否像 fairseq (https://github.com/facebookresearch/fairseq/tree/main/examples/translation) 一样，将每一个步奏都提供出来。

另外，我们的PaddleNLP数据处理看起来和代码高度耦合。意思就是我每想用新的机器翻译数据训练模型，我需要在PaddleNLP里先写一些支持该数据的新的代码。这从用户的视角看并不是很好用，可否参照fairseq-preprocess，将 从 bpe tokenized text 到 data-bin 这步与代码库解耦。

**Comment by ZeyuChen** [comment]
@gpengzhi 感谢反馈！欢迎继续多提建议，我们一起看看怎么优化翻译这里的体验。
