### ISSUE TITLE
关于开源的预训练模型plato-xl的疑问

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#2743]
请问下面链接里，提供给用户下载的plato-xl是中文版的还是英文版的？是适用于中文多轮对话任务还是英文呢？其次就是，为什么plato-xl的vocab_size只有8001，竟然比mini的还小。谢谢大佬回答

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/unified_transformer/modeling.py

**Comment by FrostML** [comment]
英文版，适用于英文对话。plato-mini 是中文版，词表也会大些。

**Comment by ZeyuTeng96** [comment]
> 英文版，适用于英文对话。plato-mini 是中文版，词表也会大些。

请问后续有开放中文版本的较大的plato预训练模型的计划嘛？max_seq_length和position_embedding只到512，个人想尝试更大一点的长度。还有一个问题是plato-xl的vocab_size为什么会只有8001，相比于库里一些英文版本的gpt模型，这个vocab_size是否有点过小了？

**Comment by FrostML** [comment]
这个问题可以移步在 https://github.com/PaddlePaddle/Knover/issues 问下~ 关于较大的 plato 预训练模型计划能得到更详细的解释~
