### ISSUE TITLE
UIE训练时卡在Special tokens file saved in ./checkpoint/model_100/special_tokens_map.json

### ISSUE THREAD

**Issue by YiTSu** [PaddlePaddle/PaddleNLP#2746]
UIE使用40W条左右的数据进行模型微调，训练时卡在Special tokens file saved in ./checkpoint/model_100/special_tokens_map.json是什么原因呢？是因为数据量太大还是其他原因呢？
如图所示：
![截屏2022-07-06 15 11 43](https://user-images.githubusercontent.com/16937245/177491594-bb56aed4-6509-450d-9e49-feca2013ec06.png)

**Comment by YiTSu** [comment]
之前训练3W条左右数据的时候都是可以正常生成的。

**Comment by wawltor** [comment]
> 之前训练3W条左右数据的时候都是可以正常生成的。

这个是保存模型，这个不影响训练效果，可以忽略

**Comment by YiTSu** [comment]
> > 之前训练3W条左右数据的时候都是可以正常生成的。
> 
> 这个是保存模型，这个不影响训练效果，可以忽略

但到这一步就卡住了啊🤣 不能继续训练了

**Comment by wawltor** [comment]
> > > 之前训练3W条左右数据的时候都是可以正常生成的。
> > 
> > 
> > 这个是保存模型，这个不影响训练效果，可以忽略
> 
> 但到这一步就卡住了啊🤣 不能继续训练了

你的验证集是不是特别大

**Comment by YiTSu** [comment]
> > > > 之前训练3W条左右数据的时候都是可以正常生成的。
> > > 
> > > 
> > > 这个是保存模型，这个不影响训练效果，可以忽略
> > 
> > 
> > 但到这一步就卡住了啊🤣 不能继续训练了
> 
> 你的验证集是不是特别大

是的。。后面把验证集调小后解决了这个问题。
