### ISSUE TITLE
弱弱问下，能否支持下MarkupLM中文版模型，对网页做信息抽取时MarkupLM蛮有用的

### ISSUE THREAD

**Issue by nlper-77** [PaddlePaddle/PaddleNLP#2748]
[MarkupLM: Pre-training of Text and Markup Language for Visually Rich Document Understanding](https://arxiv.org/pdf/2110.08518.pdf)

**Comment by LiuChiachi** [comment]
如果您感兴趣的话，能否实现然后给我们贡献代码呢:)我们会无比欢迎和外部开发者一起建设~

**Comment by linjieccc** [comment]
UIE多模态版本目前在我们的开发计划中，欢迎持续关注~另外我们也非常欢迎您给我们贡献新的模型，在PaddleNLP信息抽取相关功能体验上也欢迎您给我们多提意见和建议

**Comment by nlper-77** [comment]
> 

UIE蛮好用的  期待多模态版本
