### ISSUE TITLE
文本相似度问题

### ISSUE THREAD

**Issue by shuangxunian** [PaddlePaddle/PaddleNLP#2749]
环境：Win10
版本：pip下载最新的paddleNLP
code：
from paddlenlp import Taskflow
similarity = Taskflow("text_similarity")

在多次调用（3-4次）之后，有一些句子对准确度会明显错误：
{'text1': '呃', 'text2': '哪位', 'similarity': 0.99999994}
{'text1': '您是在抖音上有留下您的信息', 'text2': '搞错啦', 'similarity': 0.8418089}
{'text1': '哎', 'text2': '我们已经在试用了', 'similarity': 0.8253542}

请问这种情况是什么原因呢，是我这边调用错了吗

**Comment by w5688414** [comment]
模型使用的数据集可能不太适合您的场景，定制化的需求可以用数据集重新训练一下。 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching

**Comment by shuangxunian** [comment]
> 模型使用的数据集可能不太适合您的场景，定制化的需求可以用数据集重新训练一下。 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching

emmm
你可能理解错我的意思了 我的意思是明明一样的对话对 重复请求多次后为什么结果会变 同时还会超过1

**Comment by linjieccc** [comment]
@shuangxunian 
您好，猜测是有多个请求同时调用了一个Taskflow实例。Taskflow目前还不支持多个请求同时调用，您可以通过在服务端加锁的方式来实现交替调用，示例：

```python
import threading
from paddlenlp import Taskflow
from flask import Flask, request, jsonify

lock = threading.Lock()

sim = Taskflow('text_similarity')
app = Flask(__name__)

@app.route('/similarity', methods=['post'])
def sim():
    body = request.json
    text = body.get('text')
    lock.acquire()
    res = str(sim(text))
    lock.release()
    return jsonify(res)
```

最近我们会提供一个统一的Taskflow任务的服务化部署方式，欢迎持续关注

**Comment by shuangxunian** [comment]
> 

十分感谢！目前来看就是这个问题！！！

**Comment by helloHKTK** [comment]
> 服务化部署
你好，我发现使用flask这种部署方法会导致内存持续占用，不释放，模型使用的是：simil = Taskflow("text_similarity", model="simbert-base-chinese", batch_size=32, home_path="simi_model/")
