### ISSUE TITLE
aistudio项目运行到一半莫名终止，对paddle的crf代码有两处疑惑

### ISSUE THREAD

**Issue by Wangyongdi** [PaddlePaddle/PaddleNLP#275]
项目“『2021语言与智能技术竞赛』- 事件抽取任务基线系统”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1802353/5df64ff3da34404aaad63bf5fa15fea3
论元识别训练部分运行一段时间后会报错。

paddle_crf里面有根据个人理解针对paddle的crf的两处修改，一个为Z的初值问题，一个为求转移得分时转移矩阵是否需要转置的问题，解码部分的代码忽略即可。

**Comment by Steffy-zxf** [comment]
你好！请问对crf具体的修改代码是什么样的？

只看到了对构建crf网络

![image](https://user-images.githubusercontent.com/48793257/115132802-12dbb980-a036-11eb-8db4-cf554de19808.png)

**Comment by Wangyongdi** [comment]
paddle_crf里面有的，
这里是初值修改：
if i == 0 and not self.with_start_stop_tag:
    mat = input_exp[:,:,:1]#防止被加num_tags次
这里是转移得分计算时矩阵转置：
  flattened_transition_indices = transition_indices.reshape([-1])
  flattened_transition_params = self.transitions.transpose([1,0]).reshape([-1])#矩阵转置

**Comment by Wangyongdi** [comment]
reshape可能重复了，复制的时候没注意，下面自己写的解码有两行写错了复制的时候忘记了修改，所以效果较差，改过来后整体效果在其他模型上跑还是可以的。

**Comment by Steffy-zxf** [comment]
如果不修改crf网络实现，是否还会遇到CuBlas问题呢

**Comment by Wangyongdi** [comment]
不好意思，转置的地方也写错了，要不我重新生成个版本把，转置应该在矩阵那里转置的，我这临时在别的版本里面复制的，好多东西没注意。

**Comment by Wangyongdi** [comment]
会的，一样的，我之前用的就是原装的，后来才试的自己改的。
项目“『2021语言与智能技术竞赛』- 事件抽取任务基线系统”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1802353/4c8e1946b6ac4c5f88b717d8e98eee25

**Comment by Wangyongdi** [comment]
我用自己改的crf接在关系抽取的基线上稍作修改后跑过，没加gru不会出现问题，加gru的没试过，但接在事件抽取的基线上就会出现这种Cublas错误，加不加gru都一样，用paddle原装crf也一样，都是报Cublas这种错误。

**Comment by joey12300** [comment]
> 我用自己改的crf接在关系抽取的基线上稍作修改后跑过，没加gru不会出现问题，加gru的没试过，但接在事件抽取的基线上就会出现这种Cublas错误，加不加gru都一样，用paddle原装crf也一样，都是报Cublas这种错误。

您好，请重新共享一下项目链接。自己也可以尝试安装最新版的PaddleNLP，并拉取最新版的PaddleNLP代码，再运行。

**Comment by Wangyongdi** [comment]
不好意思，好久没看这个了。刚试了一下，还是之前的错误，PaddleNLP运行都会安装最新的。
项目“『2021语言与智能技术竞赛』- 事件抽取任务基线系统”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1802353/06c4619206fd4c92a3757c87a9ff374c

**Comment by ares89** [comment]
loss值为0，无法bp了
