### ISSUE TITLE
环境问题libcuda.so一直检索不到

### ISSUE THREAD

**Issue by pengfan7758258** [PaddlePaddle/PaddleNLP#2750]
1）PaddleNLP和PaddlePaddle版本：例如paddlenlp 2.3.4，paddlepaddle 2.3.0.post112
2）系统环境：Linux-ubuntu20.04，python 3.8.3
<img width="447" alt="log" src="https://user-images.githubusercontent.com/62168810/177675659-75f34924-9b94-4f80-a394-950f5d8787fe.png">
<img width="457" alt="log" src="https://user-images.githubusercontent.com/62168810/177675737-d911fafd-4bb3-4140-ab95-e65887cd6fd3.png">
<img width="399" alt="log" src="https://user-images.githubusercontent.com/62168810/177675821-ab9e7197-6041-44e4-98a1-fc5f6e01680f.png">

在uie运行finetune.py文件的时候报出如下错误:
<img width="1465" alt="log" src="https://user-images.githubusercontent.com/62168810/177675941-7b4ec5ff-96d2-4ff4-8c17-13f73e881d8b.png">
试了网上给出的方法，在/home/用户名下的.bashrc添加了环境变量，并source激活
注:注释部分是都尝试过的环境变量
<img width="421" alt="log" src="https://user-images.githubusercontent.com/62168810/177676209-c74c5d20-623d-4449-b6d1-5cb951421438.png">

**Comment by wawltor** [comment]
这种情况一般都是paddle和cuda安装的问题，建议从以下方式来安装

1. 新建一个conda环境
2. 使用conda来安装paddlepaddle-gpu
<img width="919" alt="image" src="https://user-images.githubusercontent.com/16698950/177678801-f624f517-4ee7-4c5e-90d0-fbf44836758c.png">

https://www.paddlepaddle.org.cn/

**Comment by pengfan7758258** [comment]
@wawltor 就是这样安装的不过选择的是linux下的conda下的CUDA11.2 的命令

**Comment by pengfan7758258** [comment]
@wawltor 并且CUDA10.2的也尝试过，错误都是一样

**Comment by pengfan7758258** [comment]
@wawltor 并且把Anaconda卸载重新装了，然后重新创的虚拟环境后还是一样的错误.............

**Comment by wawltor** [comment]
你可以尝试先把.bashrc的有关cuda的环境给删除，然后再尝试新建conda环境再次安装，因此这个问题就是cuda版本和paddle版本不对齐，只能多尝试一下 ~~

**Comment by w5688414** [comment]
如果还是不行，可以使用docker安装

**Comment by BrightXiaoHan** [comment]
我也遇到了同样的问题
![image](https://user-images.githubusercontent.com/25839309/218412238-238b623b-3f03-4f48-a476-0926ee7231be.png)
我将conda环境中的lib加到环境变量中也没用，目录下面根本没有libcuda.so这个文件

![image](https://user-images.githubusercontent.com/25839309/218412523-5c674c0e-6d56-49c0-9068-6d1500525d11.png)

**Comment by BrightXiaoHan** [comment]
> @wawltor 并且把Anaconda卸载重新装了，然后重新创的虚拟环境后还是一样的错误.............

请问这个问题您解决了么？
