### ISSUE TITLE
请问是否有将uie训练好的模型转为trt的示列

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#2757]
感谢提供的uie示列，目前已把模型训练，转onnx, 以及serving整个流程打通，但由于性能问题，想将onnx转为trt进行部署，请问有具体paddlenlp部署trt的server示列吗?

**Comment by wawltor** [comment]
我们测试过onnx的性能是比TRT的性能好的，想问一下你有打开半精度预测吗？

**Comment by leon-cas** [comment]
> 我们测试过onnx的性能是比TRT的性能好的，想问一下你有打开半精度预测吗？

没有打开半精度预测，目前预测时长50ms左右，正常吗？。 onnx打开半精度相比trt性能会好多少？。 请问打开半精度后，有评估过预测效果差异吗？对预测准确度影响大吗？

**Comment by wawltor** [comment]
> > 我们测试过onnx的性能是比TRT的性能好的，想问一下你有打开半精度预测吗？
> 
> 没有打开半精度预测，目前预测时长50ms左右，正常吗？。 onnx打开半精度相比trt性能会好多少？。 请问打开半精度后，有评估过预测效果差异吗？对预测准确度影响大吗？

预测效果差距不大，基本没有效果损失；但是性能会有较大的提升，下面是ERNIE-3.0上的一个性能提升指标，可以参考
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/16698950/177761611-71478d89-9e48-416a-b987-becc38a28886.png">

同时也是建议多试试UIE Tiny系列的模型，目前我们发布了不同size的模型，可以尝试
<img width="508" alt="image" src="https://user-images.githubusercontent.com/16698950/177761789-d44834b5-73fa-436b-a583-e1c27a3df892.png">

**Comment by leon-cas** [comment]
谢谢。刚刚试了下使用fp16， 但基于fp16_model.onnx进行推理时，预测没有任何结果。 同样的代码，不使用fp16时，基于model.onnx测试预测结果没问题。

使用fp32, 日志如下
[2022-07-08 11:40:49,510] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-07-08 11:40:49,510] [    INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./checkpoint/goods/export/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 15 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
>>> [InferBackend] Use GPU to inference ...
model file ./checkpoint/goods/export/model.onnx
n_cpu 64
>>> [InferBackend] Engine Created ...
-----------------------------
1. Input text: 
洛德蒙瑜伽套装女夏天薄款美背短袖跑步运动服性感时尚专业高端健
2. Input schema: 
['品牌名', '商品名', '商品概念', '商品卖点']
3. Result: 
{'品牌名': [{'end': 3, 'probability': 0.9999839, 'start': 0, 'text': '洛德蒙'}],
 '商品卖点': [{'end': 25, 'probability': 0.85936844, 'start': 21, 'text': '性感时尚'}],
 '商品名': [{'end': 21, 'probability': 0.99982655, 'start': 18, 'text': '运动服'}],
 '商品概念': [{'end': 7, 'probability': 0.9996761, 'start': 3, 'text': '瑜伽套装'},
          {'end': 21, 'probability': 0.99996376, 'start': 16, 'text': '跑步运动服'}]}

使用fp16，日志如下：
[2022-07-08 11:38:02,991] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-07-08 11:38:02,991] [    INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./checkpoint/goods/export/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./checkpoint/goods/export/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 15 for ONNX export.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
>>> [InferBackend] Use GPU to inference ...
>>> [InferBackend] Use FP16 to inference ...
>>> [InferBackend] Use GPU to inference ...
>>> [InferBackend] Use FP16 to inference ...
model file ./checkpoint/goods/export/fp16_model.onnx
n_cpu 64
2022-07-08 11:38:12.853465400 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.4'
2022-07-08 11:38:12.967629413 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.4'
>>> [InferBackend] Engine Created ...
-----------------------------
1. Input text: 
洛德蒙瑜伽套装女夏天薄款美背短袖跑步运动服性感时尚专业高端健
2. Input schema: 
['品牌名', '商品名', '商品概念', '商品卖点']
3. Result: 
{}

**Comment by wawltor** [comment]
> 谢谢。刚刚试了下使用fp16， 但基于fp16_model.onnx进行推理时，预测没有任何结果。 同样的代码，不使用fp16时，基于model.onnx测试预测结果没问题。
> 
> 使用fp32, 日志如下 [2022-07-08 11:40:49,510] [ INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'. [2022-07-08 11:40:49,510] [ INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
> 
> > > > [InferBackend] Creating Engine ...
> > > > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > > > [Paddle2ONNX] Model file path: ./checkpoint/goods/export/inference.pdmodel
> > > > [Paddle2ONNX] Paramters file path: ./checkpoint/goods/export/inference.pdiparams
> > > > [Paddle2ONNX] Start to parsing Paddle model...
> > > > [Paddle2ONNX] Use opset_version = 15 for ONNX export.
> > > > [Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
> > > > [InferBackend] Use GPU to inference ...
> > > > [InferBackend] Use GPU to inference ...
> > > > model file ./checkpoint/goods/export/model.onnx
> > > > n_cpu 64
> > > > [InferBackend] Engine Created ...
> 
> 1. Input text:
>    洛德蒙瑜伽套装女夏天薄款美背短袖跑步运动服性感时尚专业高端健
> 2. Input schema:
>    ['品牌名', '商品名', '商品概念', '商品卖点']
> 3. Result:
>    {'品牌名': [{'end': 3, 'probability': 0.9999839, 'start': 0, 'text': '洛德蒙'}],
>    '商品卖点': [{'end': 25, 'probability': 0.85936844, 'start': 21, 'text': '性感时尚'}],
>    '商品名': [{'end': 21, 'probability': 0.99982655, 'start': 18, 'text': '运动服'}],
>    '商品概念': [{'end': 7, 'probability': 0.9996761, 'start': 3, 'text': '瑜伽套装'},
>    {'end': 21, 'probability': 0.99996376, 'start': 16, 'text': '跑步运动服'}]}
> 
> 使用fp16，日志如下： [2022-07-08 11:38:02,991] [ INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'. [2022-07-08 11:38:02,991] [ INFO] - Already cached /root/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
> 
> > > > [InferBackend] Creating Engine ...
> > > > [Paddle2ONNX] Start to parse PaddlePaddle model...
> > > > [Paddle2ONNX] Model file path: ./checkpoint/goods/export/inference.pdmodel
> > > > [Paddle2ONNX] Paramters file path: ./checkpoint/goods/export/inference.pdiparams
> > > > [Paddle2ONNX] Start to parsing Paddle model...
> > > > [Paddle2ONNX] Use opset_version = 15 for ONNX export.
> > > > [Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
> > > > [InferBackend] Use GPU to inference ...
> > > > [InferBackend] Use FP16 to inference ...
> > > > [InferBackend] Use GPU to inference ...
> > > > [InferBackend] Use FP16 to inference ...
> > > > model file ./checkpoint/goods/export/fp16_model.onnx
> > > > n_cpu 64
> > > > 2022-07-08 11:38:12.853465400 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.4'
> > > > 2022-07-08 11:38:12.967629413 [W:onnxruntime:, constant_folding.cc:179 ApplyImpl] Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.4'
> > > > [InferBackend] Engine Created ...
> 
> 1. Input text:
>    洛德蒙瑜伽套装女夏天薄款美背短袖跑步运动服性感时尚专业高端健
> 2. Input schema:
>    ['品牌名', '商品名', '商品概念', '商品卖点']
> 3. Result:
>    {}

能提供一下你具体怎么使用PF16的吗? 以及你的显卡型号

**Comment by wawltor** [comment]
或者你可以加速试一下Taskflow来加载训练好的模型，Taskflow里面已经集成了FP16加速
1. Taskflow加载微调模型 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/16698950/177914899-819fec17-0072-4789-8108-64d52848a842.png">
2. 使用Taskflow 半精度预测
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/16698950/177914978-24d06eb1-2f28-4678-bf9b-7d1204a4b234.png">

**Comment by leon-cas** [comment]
> 
使用fp16方式： 直接使用的infer_gpu代码， 设置use_fp16，只是替换了main函数中的示列，其他的没有任何变化

环境配置如下：
cuda 11.2,  cudnn 8, paddle:2.3.0
onnx                   1.12.0         
onnxconverter-common   1.9.0          
onnxruntime-gpu        1.11.1 
paddle2onnx            0.9.8               
paddlenlp              2.3.3          
paddlepaddle-gpu       2.3.0.post112

**Comment by wawltor** [comment]
> 或者你可以加速试一下Taskflow来加载训练好的模型，Taskflow里面已经集成了FP16加速
> 
> 1. Taskflow加载微调模型
> 
> <img alt="image" width="1030" src="https://user-images.githubusercontent.com/16698950/177914899-819fec17-0072-4789-8108-64d52848a842.png">
> 
> 2. 使用Taskflow 半精度预测 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96
> <img alt="image" width="1079" src="https://user-images.githubusercontent.com/16698950/177914978-24d06eb1-2f28-4678-bf9b-7d1204a4b234.png">

你可以先试试Taskflow里面的，试试   我们在很多业务线测试过，FP16是不影响精度的，不确定是不是使用过程中的问题；建议先用Taskflow来加载一下模型，看看半精度是否Work

**Comment by leon-cas** [comment]
> 
直接使用Taskflow+fp16预测没有问题，gpu为2080，延时30ms;   使用fp32 50ms；

能帮忙评估下使用fp16, onnx的预测无结果的问题吗？

**Comment by wawltor** [comment]
这个可能需要提供一下你的代码和模型、测试数据了, 因为我们本地测试自己的模型和数据是没有问题的，您看看是否方便把相关通过邮件发给我们？

**Comment by leon-cas** [comment]
> 

请问通过什么方式发送比较方便？

**Comment by wawltor** [comment]
> > 
> 
> 请问通过什么方式发送比较方便？

980627148@qq.com

**Comment by wawltor** [comment]
@leon-cas 想问一下，现在还有疑问吗？

**Comment by leon-cas** [comment]
> 

通过taskflow的方式, 用fp16调用生成的onnx模型，调用结果没问题。 谢谢解答

**Comment by mingo-doer** [comment]
> fp16

想问一下  您这种打通的方式有教程或者资料可以参考吗

**Comment by mingo-doer** [comment]
> > 
> 
> 通过taskflow的方式, 用fp16调用生成的onnx模型，调用结果没问题。 谢谢解答

@leon-cas  想问一下 您这种打通的方式 有资料可以参考吗

**Comment by zhangzef** [comment]
麻烦问一下有UIE转onnx的示例吗，我这里转onnx后模型预测效果直接崩了
