### ISSUE TITLE
Pipelines语义索引 ImagetoTextConverter缺失问题和语义索引docdir路径问题

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PaddleNLP#2761]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
![image](https://user-images.githubusercontent.com/12107462/177905807-322b2b27-fd71-412a-84fd-ccda1d60cceb.png)

![image](https://user-images.githubusercontent.com/12107462/177905815-48e9a939-3a60-4e27-b3c4-70ee953bcdf8.png)

昨天运行这一步的时候，会出现图中错误，我注释掉图中那两处后，才执行通过

![image](https://user-images.githubusercontent.com/12107462/177905855-8437b04b-11cd-4929-a30f-14b2b314e410.png)

再就是UI搭建起来之后，运行会有这个错误

![image](https://user-images.githubusercontent.com/12107462/177905885-6b8e2c5a-47c9-47e1-a994-547506459bab.png)

我将doc_dir路径修改后，才能运行搜索出结果，怀疑是写入 ANN 索引库
数据是不是有问题

rest_api/pipeline/semantic_search.yaml

**Comment by bruce0210** [comment]
环境配置为：
2xCPU 16GiB内存
centos7.5
anaconda->python3.8.5
paddlepaddle==2.3.0（cpu）
paddleNLP==2.3.4
----------------------------------
即：按照文档中步骤依次执行到该步骤时，出现下图中报错信息：
![image](https://user-images.githubusercontent.com/100854336/177935558-13b86907-3e3f-4ed4-8351-d49688780c4d.png)
----------------------------------
BTW：
在执行时会先抛出如下提示：
![image](https://user-images.githubusercontent.com/100854336/177937673-e75589e7-15b2-4368-8c51-bae58954d519.png)
参考：https://github.com/jalan/pdftotext；做如下操作，需先完成pdftotext的安装；
wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.04.tar.gz
tar -xvf xpdf-tools-linux-4.04.tar.gz
sudo cp xpdf-tools-linux-4.04/bin64/pdftotext /usr/local/bin
sudo yum install gcc-c++ pkgconfig poppler-cpp-devel python3-devel
pip install pdftotext

**Comment by bruce0210** [comment]
关于下图出现的问题：
![image](https://user-images.githubusercontent.com/100854336/177939441-fae76867-5e44-47b8-93b9-584a0646c65c.png)
我修改了：rest_api/pipeline/semantic_search.yaml中的：index: baike_cities
并注释掉了：
# - name: ImageFileConverter
#   type: ImageToTextConverter
详见下图中位置：
![image](https://user-images.githubusercontent.com/100854336/177939825-f2ab6956-68f8-48ea-b7d2-872088c1f714.png)
然后依次重新启动服务，可正常输出查询结果。

**Comment by w5688414** [comment]
![image](https://user-images.githubusercontent.com/12107462/177975495-033c529f-42ff-4b92-beca-99088eaf2bb3.png)
```
pip install opencv-python==4.5.5.64
pip install opencv-contrib-python-headless==4.2.0.32
```
