### ISSUE TITLE
model_zoo/uie定制训练出现错误AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'

### ISSUE THREAD

**Issue by 1689665417** [PaddlePaddle/PaddleNLP#2769]
环境如下：Ubuntu 180.4  python3.6.10 
![image](https://user-images.githubusercontent.com/43131195/178097444-5517aa5b-a81c-460c-adde-ecbe401956b3.png)
![image](https://user-images.githubusercontent.com/43131195/178097462-8e0fa125-997a-42d8-86bb-ea68dbd5c59e.png)
![image](https://user-images.githubusercontent.com/43131195/178097472-f8a66d17-fc5b-47e6-9fde-db56e977b7bb.png)
错误提示如下：
![image](https://user-images.githubusercontent.com/43131195/178097560-127e0086-9ce0-4e02-92b8-21733d05f2bd.png)

请帮忙看看，谢谢。

**Comment by ZHUI** [comment]
`pip install paddlenlp --upgrade` 需要安装最新的  paddlenlp 版本

**Comment by ZHUI** [comment]
你好，问题可以解决了吗？

**Comment by 1689665417** [comment]
昨天试着paddlepaddle-gpu和paddlenlp版本退回到2.3.0，同时取消onnx相关三个依赖的安装，得到解决。你说的方式暂时没有尝试。

**Comment by 1689665417** [comment]
不清楚在保持paddlepaddle-gpu和paddlenlp版本是2.3.1的情况下，取消onnx三个依赖，能否成功。
可能是onnx加速依赖的问题上，pip 一直无法正常安装onnx，随后使用
conda install -c conda-forge numpy protobuf==3.16.0 libprotobuf=3.16.0
conda install -c conda-forge onnx 完成安装，但是运行时得到上述错误。


由于不太清楚哪里出现问题，暂用2.3.0 版本，取消onnx相关三个依赖，解决此问题。

**Comment by ZHUI** [comment]
这个错误是已知的，跟 onnx 关系不大。
升级 paddlenlp 或者 降级 paddle版本，都可以解决 DataLoader 报错。

onnx 安装还有问题吗？

**Comment by 1689665417** [comment]
使用conda 可以安装成功。

**Comment by GYuanchengxu** [comment]
升级paddle解决了这个问题   pip install paddlenlp --upgrade
