### ISSUE TITLE
使用Ernietokenizer加载自定义字典时会报错

### ISSUE THREAD

**Issue by Wangyongdi** [PaddlePaddle/PaddleNLP#277]
from paddlenlp.transformers import ErnieTokenizer
tokenizer = ErnieTokenizer('./vocab.txt')
加载ernie默认使用的vocab同样报错

**Comment by wawltor** [comment]
您好，您上面的用法稍微有点问题，具体的使用方式是这样的
```python
     from paddlenlp.transformers import ErnieTokenizer
     ErnieTokenizer.from_pretrained("./model_20")
```
在model_20的目录下是tokenizer保存下来的文件, 具体的接口如下
```python
     tokenizer.save_pretrained(dir)
```
保存下来信息如下：
  1)  vocab.txt  词表
  2)  tokenizer_config.json  tokenizer具体的配置  

下面tokenizer_config.json的配置示例：
<img width="1143" alt="图片" src="https://user-images.githubusercontent.com/16698950/115178592-353c0880-a104-11eb-94da-473f8cacfad1.png">

**Comment by Wangyongdi** [comment]
好的，我再看看，谢谢大佬
