### ISSUE TITLE
使用PaddleNLP自定义的本地csv数据集做机器阅读理解，报错，救救我吧

### ISSUE THREAD

**Issue by abc-w** [PaddlePaddle/PaddleNLP#2770]
因为手头有一份数据，格式是csv，使用PaddleNLP自定义的本地csv数据集做机器阅读理解，在map()方法来进行批量数据集处理报错，救救我吧

**Comment by abc-w** [comment]
![屏幕截图 2022-07-09 194343](https://user-images.githubusercontent.com/84693075/178104648
![屏幕截图 2022-07-09 194531](https://user-images.githubusercontent.com/84693075/178104655-2a92a6a8-bf69-4cc9-b2bf-4b962bc3e527.png)
-9e36e491-8896-4d9f-b009-51033b67ca0c.png)
![屏幕截图 2022-07-09 194427](https://user-images.githubusercontent.com/84693075/178104651-b6fc9f8e-d37c-4954-b572-5b896a90e285.png)

**Comment by abc-w** [comment]
![屏幕截图 2022-07-09 194343](https://user-images.githubusercontent.com/84693075/178104683-2cc26a46-8b3d-433a-af34-8c7ff096e2b6.png)
![屏幕截图 2022-07-09 194427](https://user-images.githubusercont
![屏幕截图 2022-07-09 194531](https://user-images.githubusercontent.com/84693075/178104692-34988df7-a8bf-4583-a69c-dbdcffa7578e.png)
ent.com/84693075/178104689-77292c0c-c620-4f5a-858a-55db8688c6f8.png)

**Comment by abc-w** [comment]
![屏幕截图 2022-07-09 194343](https://user-images.githubusercontent.com/84693075/178104713-3eef92a1-5d8c-48a7-9259-12fb2bf4e3ee.png)
![屏幕截图 2022-07-09 194427](https://user-images.githubusercontent.com/84693075/178104718-d710409b-225c-4618-a502-5679dc58e18c.png)
![屏幕截图 2022-07-09 194531](https://user-images.githubusercontent.com/84693075/178104723-b815c58e-8487-4d2b-b66f-7f62caf32470.png)

**Comment by ZHUI** [comment]
应该是传人的格式处理问题，可以现在 prepare_train_feature 哪里加入一行打印，看看传入的是啥

**Comment by abc-w** [comment]
> 
![image](https://user-images.githubusercontent.com/84693075/178136172-556e669c-fbcc-4e62-8608-98d3048733df.png)

**Comment by abc-w** [comment]
> 应该是传人的格式处理问题，可以现在 prepare_train_feature 哪里加入一行打印，看看传入的是啥

![image](https://user-images.githubusercontent.com/84693075/178136210-32cc6735-1b6f-4c69-8471-d24ccdeb9b83.png)

**Comment by abc-w** [comment]
> 应该是传人的格式处理问题，可以现在 prepare_train_feature 哪里加入一行打印，看看传入的是啥

查不出来啥问题

**Comment by guoshengCS** [comment]
如果`.map(batch=True)`的话`train_trans_func`接受的输入会是example的list，这里`train_trans_func`是如何实现的呢

**Comment by abc-w** [comment]
> 

是内置的partial()实现的，我照着示例代码改的

**Comment by guoshengCS** [comment]
还请提供下train_trans_func的代码或链接看看呢

**Comment by abc-w** [comment]
> 还请提供下train_trans_func的代码或链接看看呢
https://aistudio.baidu.com/aistudio/projectdetail/4306696?shared=1

**Comment by guoshengCS** [comment]
> https://aistudio.baidu.com/aistudio/projectdetail/4306696?shared=1

运行了下，这里的examples是个list
<img width="795" alt="image" src="https://user-images.githubusercontent.com/14105589/178395146-682172a6-059b-48d2-8ef6-124eb623f80a.png">
用str从中取值所以报了这个错，tokenizer处理之后的结果才是dict
<img width="877" alt="image" src="https://user-images.githubusercontent.com/14105589/178395279-6da98188-8286-411b-8f37-0deaa58debbd.png">

**Comment by abc-w** [comment]
> Collaborator
![image](https://user-images.githubusercontent.com/84693075/178408363-44175953-b540-4f85-9f3b-ecdfb160c606.png)
已经加了 tokenizer处理，还是报这个错，有啥解决办法吗，麻烦了
https://aistudio.baidu.com/aistudio/projectdetail/4306696?shared=1

**Comment by guoshengCS** [comment]
因为您那边目前使用的是paddlenlp中的`load_dataset`，而不是使用的HF的`load_dataset`和数据集，这两个在使用时会有些差异：

- 下面这种是在使用HF的`load_dataset`和数据集使用的，需要将examples当做dict使用，是dict of list

```python
contexts = examples["context"]
questions = examples["question"]
```
<img width="848" alt="image" src="https://user-images.githubusercontent.com/14105589/178645109-f69e9017-d66e-427f-a8b4-788ba9cb2546.png">

- 而您这边因为使用的是paddlenlp中的`load_dataset`和数据集，还是需要原来的（注释中的）这种，需要将examples当做list使用，是list of dict

```python
contexts = [examples[i]['context'] for i in range(len(examples))]
questions = [examples[i]['question'] for i in range(len(examples))]
```

**Comment by abc-w** [comment]
> 因为您那边目前使用的是paddlenlp中的`load_dataset`，而不是使用的HF的`load_dataset`和数据集，这两个在使用时会有些差异：
> 
> * 下面这种是在使用HF的`load_dataset`和数据集使用的，需要将examples当做dict使用，是dict of list
> 
> ```python
> contexts = examples["context"]
> questions = examples["question"]
> ```
> 
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/14105589/178645109-f69e9017-d66e-427f-a8b4-788ba9cb2546.png">
> 
> * 而您这边因为使用的是paddlenlp中的`load_dataset`和数据集，还是需要原来的（注释中的）这种，需要将examples当做list使用，是list of dict
> 
> ```python
> contexts = [examples[i]['context'] for i in range(len(examples))]
> questions = [examples[i]['question'] for i in range(len(examples))]
> ```
![image](https://user-images.githubusercontent.com/84693075/178673959-69c8e7ba-b048-4020-8b0f-6d72072ff856.png)
按您的改了还是报错，不太明白该怎么改了，麻烦了
https://aistudio.baidu.com/aistudio/projectdetail/4306696?contributionType=1&shared=1

**Comment by guoshengCS** [comment]
这里应该是另一个报错了，之前这个问题应该已经没有了。
<img width="496" alt="image" src="https://user-images.githubusercontent.com/14105589/178951194-b8636006-2988-48f6-b2e0-ea473c712e49.png">

我们这边再看下当前这个问题
<img width="805" alt="image" src="https://user-images.githubusercontent.com/14105589/178951324-aebbf6c5-9c65-45be-89e5-7505ba40a8e9.png">

**Comment by guoshengCS** [comment]
我这里debug了下，看好像确实有些不是str的输入
<img width="963" alt="image" src="https://user-images.githubusercontent.com/14105589/178981891-f6de1c88-73a8-4698-b2c1-98da3940c883.png">
去看了下csv文件，好像第269条数据有些问题，这个还麻烦确认下呢
<img width="990" alt="image" src="https://user-images.githubusercontent.com/14105589/178982099-6073ea3d-a874-489a-b51c-8e0b6d7231c7.png">

**Comment by abc-w** [comment]
> 我这里debug了下，看好像确实有些不是str的输入 <img alt="image" width="963" src="https://user-images.githubusercontent.com/14105589/178981891-f6de1c88-73a8-4698-b2c1-98da3940c883.png"> 去看了下csv文件，好像第269条数据有些问题，这个还麻烦确认下呢 <img alt="image" width="990" src="https://user-images.githubusercontent.com/14105589/178982099-6073ea3d-a874-489a-b51c-8e0b6d7231c7.png">

我用了另一个baseline把空值删除后，可以了，但是数据缺少‘answer_start’，飞桨内置的数据集都是有的，但是正常的业务里的数据没有这一项，请问一下这块该怎么处理，也没查到相关的代码

**Comment by guoshengCS** [comment]
> 我用了另一个baseline把空值删除后，可以了，但是数据缺少‘answer_start’，飞桨内置的数据集都是有的，但是正常的业务里的数据没有这一项，请问一下这块该怎么处理，也没查到相关的代码

这个应该是需要在context里查找下answer的位置，然后设置下answer_start

**Comment by abc-w** [comment]
> 
是的，不会要手动标注吧，没有找到相关代码

**Comment by guoshengCS** [comment]
不需要手动标注，在代码里字符串匹配下就行

**Comment by abc-w** [comment]
> 不需要手动标注，在代码里字符串匹配下就行

![image](https://user-images.githubusercontent.com/84693075/179176475-c9c6608f-4b8c-4fde-a6e3-7b6c111006f1.png)
https://aistudio.baidu.com/aistudio/projectdetail/4340434?contributionType=1&shared=1
全部改好了，就是最后成测试集预测数据的时候又报错了，完全懵逼了，麻烦帮我看下，很急

**Comment by guoshengCS** [comment]
那当前是训练没问题了，测试还有问题是吗

**Comment by abc-w** [comment]
没有了，已经全部解决了，感谢您的帮助



---原始邮件---
发件人: "Guo ***@***.***&gt;
发送时间: 2022年7月18日(周一) 上午9:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleNLP] 使用PaddleNLP自定义的本地csv数据集做机器阅读理解，报错，救救我吧 (Issue #2770)




 
那当前是训练没问题了，测试还有问题是吗
