### ISSUE TITLE
使用model_zoo/uie训练关系抽取DuIE指标较低

### ISSUE THREAD

**Issue by moming11** [PaddlePaddle/PaddleNLP#2772]
使用model_zoo/uie下代码finetune数据集DuIE时，指标仅达到 f1 0.7左右，距离该数据集上较好的结果均有很大的差距，模型是基于uie-base 进行finetune的，请问如何提高呢？

**Comment by linjieccc** [comment]
您好，在doccano.py数据转换阶段可以尝试使用sample_ratio调整下正负样本的比例

**Comment by moming11** [comment]
请问DuIE这个数据集比例用多少比较合适呢？在这个数据集上使用UIE指标一般能达到多少呢？
我自己尝试了1：1效果不好，而且用doccano.py数据转换生成负例速度很慢。

**Comment by AbuNLP** [comment]
@moming11 您好，想问下您使用UIE解决DuIE得到的结论怎么样呀？
我最近也在做这方面的工作，望交流，微信 15516886282。
谢谢。
