### ISSUE TITLE
使用通用信息抽取模块finetune微调出现ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by AhriZ08** [PaddlePaddle/PaddleNLP#2773]
PaddleNLP 2.3.0，PaddlePaddle2.2.2
系统环境：Windows，python3.7.0
按照说明步骤执行
python finetune.py \
    --train_path "./data/train.txt" \
    --dev_path "./data/dev.txt" \
    --save_dir "./checkpoint" \
    --learning_rate 1e-5 \
....
微调训练命令出错
提示
 File "finetune.py", line 105, in do_train
    pos_ids)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by wawltor** [comment]
你可以先升级一下PaddleNLP的版本到最新的版本试试

**Comment by linjieccc** [comment]
@AhriZ08 您好，请问目前微调还有问题吗

**Comment by AhriZ08** [comment]
更新版本后还是存在以上问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 晚上8:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 使用通用信息抽取模块finetune微调出现ValueError: not enough values to unpack (expected 2, got 1) (Issue #2773)





 
@AhriZ08 您好，请问目前微调还有问题吗

**Comment by linjieccc** [comment]
可以拉最新的develop分支的代码再试下

**Comment by AhriZ08** [comment]
我换成了使用GPU训练，又报新的错误，我已经降低batch size，并且显卡占用率只有2%。
Out of memory error on GPU 0. Cannot allocate 12.000000MB memory on GPU 0, 5.999512GB memory has been allocated and available memory is only 0.000000B.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 晚上8:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 使用通用信息抽取模块finetune微调出现ValueError: not enough values to unpack (expected 2, got 1) (Issue #2773)





 
可以拉最新的develop版本再试下

**Comment by linjieccc** [comment]
可以先用下面的命令训练试试，显存没有溢出的话再逐步调大batch_size

```shell
python finetune.py \
    --train_path ./data/train.txt \
    --dev_path ./data/dev.txt \
    --save_dir ./checkpoint \
    --learning_rate 1e-5 \
    --batch_size 1 \
    --model uie-medium
```

**Comment by AhriZ08** [comment]
升级到develop版本运行又报这个错误......
'utf-8' codec can't decode bytes in position 325-326: 'utf-8' codec can't decode bytes in position 325-326: invalid continuation byte in field: paddle.framework.proto.OpProto.Attr.comment




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 使用通用信息抽取模块finetune微调出现ValueError: not enough values to unpack (expected 2, got 1) (Issue #2773)





 
可以先用下面的命令训练试试，显存没有溢出的话再逐步调大batch_size
 python finetune.py \     --train_path ./data/train.txt \     --dev_path ./data/dev.txt \     --save_dir ./checkpoint \     --learning_rate 1e-5 \     --batch_size 1 \     --model uie-medium

**Comment by linjieccc** [comment]
您的protobuf版本是多少

**Comment by AhriZ08** [comment]
3.20.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 中午11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 使用通用信息抽取模块finetune微调出现ValueError: not enough values to unpack (expected 2, got 1) (Issue #2773)





 
您的protobuf版本是多少
