### ISSUE TITLE
Paddlenlp运行问题

### ISSUE THREAD

**Issue by Shawnc00** [PaddlePaddle/PaddleNLP#2774]
我每次执行Taskflow函数之后，会出现如下的报错信息，测试时包括4项指标，且这些报错信息重复出现了4次。
但程序在报错后可以正常运行出结果。
e[37m---    fused 0 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m

python版本为：
3.7.9

paddlenlp版本为：
2.3.4

程序截图附在最后：
![image](https://user-images.githubusercontent.com/93563539/178195931-901e76bf-49e3-455b-af4d-c34c9040c2e5.png)
![image](https://user-images.githubusercontent.com/93563539/178195850-07f98353-ef6f-459e-9326-9114e1a19558.png)

**Comment by wawltor** [comment]
您好，这个并不是报错信息，是正常中间日志信息，你可以忽略；同时我们看看能不能把这些日志给隐藏掉，防止干扰！

**Comment by Shawnc00** [comment]
> 您好，这个并不是报错信息，是正常中间日志信息，你可以忽略；同时我们看看能不能把这些日志给隐藏掉，防止干扰！

好的，感谢您的回复，解决了一直以来的疑惑~

**Comment by xieyu0214** [comment]
> 您好，这个并不是报错信息，是正常中间日志信息，你可以忽略；同时我们看看能不能把这些日志给隐藏掉，防止干扰！

请问怎么隐藏日志？？

**Comment by xmzhuxm** [comment]
> 您好，这个并不是报错信息，是正常中间日志信息，你可以忽略；同时我们看看能不能把这些日志给隐藏掉，防止干扰！

您好，这个问题现在解决了吗
