### ISSUE TITLE
python API模型推理能否增加NLP案例

### ISSUE THREAD

**Issue by diandian11** [PaddlePaddle/PaddleNLP#278]
在export model 之后，通过infference加载静态图模型，可以增加一个学习的案例吗？

**Comment by ZeyuChen** [comment]
@diandian11 这块正在进行中，估计这两天能看到相关教程和代码示例。

**Comment by Steffy-zxf** [comment]
@diandian11 你好！感谢反馈！Paddle Inference预测示例已添加。
pr：https://github.com/PaddlePaddle/PaddleNLP/pull/281

参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification
各目录下的deploy/python/predict.py脚本
