### ISSUE TITLE
in_batch_negative加载simcse生成的预训练模型地址继续训练报错

### ISSUE THREAD

**Issue by hanfeng11** [PaddlePaddle/PaddleNLP#2783]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.3，PaddlePaddle 2.3.0
2）系统环境：win10 ; python3.9
- 复现信息：**in_batch_negative加载simcse生成的预训练模型地址继续训练报错**
- `pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained('./output/model_1200') #这边加载报错`
    `tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained('./output/model_1200')`

- `Traceback (most recent call last):`
 ` File "D:\Temp_demo\PaddleNLP-develop\applications\neural_search\recall\in_batch_negative\train_batch_neg.py", line 176, in <module>`
    `do_train()`
  `File "D:\Temp_demo\PaddleNLP-develop\applications\neural_search\recall\in_batch_negative\train_batch_neg.py", line 90, in do_train`
   ` pretrained_model = ppnlp.transformers.ErnieModel.from_pretrained('./output/model_1200')`
  `File "D:\Temp_demo\PaddleNLP-develop\paddlenlp\transformers\model_utils.py", line 252, in from_pretrained`
    `resolved_resource_files[file_id] = get_path_from_url(`
 ` File "D:\Temp_demo\PaddleNLP-develop\paddlenlp\utils\downloader.py", line 154, in get_path_from_url`
    `assert is_url(url), "downloading from {} not a url".format(url)`
`AssertionError: downloading from ./output/model_1200\model_config.json not a url`

- model_1200下面有四个文件，分别是：model_state.pdparams ；special_tokens_map.json ；tokenizer_config.json；vocab.txt，是通过save_pretrained接口保存到本地的，但并没有保存model_config.json文件。

**Comment by w5688414** [comment]
```
python -u -m paddle.distributed.launch --gpus "0,1,2,3" \
    train_batch_neg.py \
    --device gpu \
    --save_dir ./checkpoints/simcse_inbatch_negative \
    --batch_size 64 \
    --learning_rate 5E-5 \
    --epochs 3 \
    --output_emb_size 256 \
    --save_steps 10 \
    --max_seq_length 64 \
    --margin 0.2 \
    --train_set_file data/${root_path}/train.csv  \
    --init_from_ckpt simcse/model_20000/model_state.pdparams
```
这样加载试试
