### ISSUE TITLE
import paddlenlp 出现  from paddle.nn.layer.transformer import _convert_attention_mask ImportError: cannot import name '_convert_attention_mask'

### ISSUE THREAD

**Issue by HeziLiu** [PaddlePaddle/PaddleNLP#2785]
- 版本信息
paddle 0.0.0 
(在飞腾/鲲鹏下从源码编译的版本,编译过程参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html)拉取的是paddle最新develop分支  应该是2.3.1 但因为是develop，所以版本号默认为0.0.0）
paddlenlp 2.3.4
- 系统环境
python3.6.7
gcc 8.2
linux aarch64架构
- 复现步骤
安装完import paddlenlp之后会出现
![image](https://user-images.githubusercontent.com/28861483/178461064-f8600063-bde9-4ef4-9530-0f14803c3f46.png)

**Comment by tianxin1860** [comment]
是出于什么考虑必须从 develop 分支编译 paddle 源码呢？一般推荐安装官方发布的稳定版 paddle 版本: `python -m pip install paddlepaddle-gpu==2.3.1 -i https://mirror.baidu.com/pypi/simple`

**Comment by HeziLiu** [comment]
> 

需要适配国产芯片 paddle安装必须源码安装 且官方教程里说是要在develop分支下进行编译https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/arm-compile.html
<img width="875" alt="image" src="https://user-images.githubusercontent.com/28861483/178462718-fe9bf44b-798e-4b84-ac96-3ab8fee692bd.png">

**Comment by HeziLiu** [comment]
> 是出于什么考虑必须从 develop 分支编译 paddle 源码呢？一般推荐安装官方发布的稳定版 paddle 版本: `python -m pip install paddlepaddle-gpu==2.3.1 -i https://mirror.baidu.com/pypi/simple`

想问一下这个错误的原因 是因为paddlenlp依赖 paddle>=2.2吗？

**Comment by tianxin1860** [comment]
可以手动检查下您安装的 paddle 框架  `${your_python_path}/site-packages/paddle/nn/layer/transformer.py` 中是否定义了`_convert_attention_mask` 函数？
