### ISSUE TITLE
ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

### ISSUE THREAD

**Issue by nan534582559** [PaddlePaddle/PaddleNLP#2794]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
paddlenlp                      2.3.4
paddlepaddle-gpu       2.2.1.post112
2）系统环境：
Linux version 4.17.11-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)) #1 SMP Sat Jul 28 09:33:09 EDT 2018
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4  
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
3）采用案例代码：
https://github.com/PaddlePaddle/PaddleNLP/tree/f4969098f675edbe41c6562496754acff37b0717/examples/text_classification/rnn
4）现象
<img width="889" alt="image" src="https://user-images.githubusercontent.com/42995334/178684858-4bc82866-ffde-488e-8e74-443d28c61e1d.png">

**Comment by wawltor** [comment]
你可以看看 logs/下面的具体日志，有错误日志可以发我们看一下

**Comment by nan534582559** [comment]
log 日志没有报错信息
[log.zip](https://github.com/PaddlePaddle/PaddleNLP/files/9101153/log.zip)

**Comment by wawltor** [comment]
看日志没有看出明显的错误，你可以尝试一下 执行以下的命令，看看是否有问题？

也可以检查一下硬盘空间是否充足 

```python
python  train.py \
    --vocab_path='./vocab.json' \
    --device=gpu \
    --network=bilstm \
    --lr=5e-4 \
    --batch_size=64 \
    --epochs=10 \
    --save_dir='./checkpoints'
```

**Comment by nan534582559** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/42995334/178924962-e8bae2c3-831a-4c57-bca5-5dfb804b485e.png">
之前是这个训练方式，现在缺少vocab.json 文件,磁盘空间足够的还有100G 可用

**Comment by wawltor** [comment]
> <img alt="image" width="690" src="https://user-images.githubusercontent.com/42995334/178924962-e8bae2c3-831a-4c57-bca5-5dfb804b485e.png">
> 
> 之前是这个训练方式，现在缺少vocab.json 文件,磁盘空间足够的还有100G 可用

方便分享一下aistudio教程吗？

**Comment by nan534582559** [comment]
这个不是在aistudio里面，可以用如流联系吗

**Comment by wawltor** [comment]
> 这个不是在aistudio里面，可以用如流联系吗

你是公司百度内部的同学？ 找方泽阳

**Comment by nan534582559** [comment]
好的

**Comment by wawltor** [comment]
重启环境后代码执行问题，该issue关闭，后续有问题可以重启issue。
