### ISSUE TITLE
Taskflow API调用后无响应

### ISSUE THREAD

**Issue by lcneyc** [PaddlePaddle/PaddleNLP#2796]
1）PaddleNLP和PaddlePaddle版本：paddlepaddle-gpu==2.3.0.post112  paddlenlp==2.3.4
2）系统环境：python==3.8.13   CentOS==7.9.2009 
>>> from paddlenlp import Taskflow
>>> seg = Taskflow("word_segmentation")
[2022-07-14 11:35:11,901] [    INFO] - Downloading model_state.pdparams from https://bj.bcebos.com/paddlenlp/taskflow/lexical_analysis/lac/model_state.pdparams
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.3M/32.3M [00:08<00:00, 4.11MB/s]
[2022-07-14 11:35:25,582] [    INFO] - Downloading tag.dic from https://bj.bcebos.com/paddlenlp/taskflow/lexical_analysis/lac/tag.dic
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 425/425 [00:00<00:00, 240kB/s]
[2022-07-14 11:35:30,776] [    INFO] - Downloading q2b.dic from https://bj.bcebos.com/paddlenlp/taskflow/lexical_analysis/lac/q2b.dic
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44.1k/44.1k [00:00<00:00, 404kB/s]
[2022-07-14 11:35:36,073] [    INFO] - Downloading word.dic from https://bj.bcebos.com/paddlenlp/taskflow/lexical_analysis/lac/word.dic
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 745k/745k [00:00<00:00, 2.83MB/s]
W0714 11:35:41.619335 111111 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0714 11:35:41.625015 111111 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
后服务器无响应，谢谢解答！

**Comment by wawltor** [comment]
seg = Taskflow("word_segmentation"， device_id='-1') 试试

**Comment by lcneyc** [comment]
您好，谢谢解答。
但其实我理解深层是gpu无法调用，但在这之前paddle框架我做ocr的时候是可以使用gpu的，就是在安装paddlenlp后gpu无法调用了。

**Comment by wawltor** [comment]
> 您好，谢谢解答。 但其实我理解深层是gpu无法调用，但在这之前paddle框架我做ocr的时候是可以使用gpu的，就是在安装paddlenlp后gpu无法调用了。

是说执行上面device_id=-1代码就可以是吗？ 想问一下你的设备显存多大了？

**Comment by lcneyc** [comment]
您好，谢谢，我之前卸载了paddlenlp，现在重新安装后试验：
>>> seg = Taskflow("word_segmentation", device_id='-1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tjidc/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 319, in __init__
    paddle.set_device(device + ":" + str(device_id))
  File "/home/tjidc/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/device/__init__.py", line 313, in set_device
    place = _convert_to_place(device)
  File "/home/tjidc/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/device/__init__.py", line 247, in _convert_to_place
    raise ValueError(
ValueError: The device must be a string which is like 'cpu', 'gpu', 'gpu:x', 'xpu', 'xpu:x', 'npu', 'npu:x', 'mlu', 'mlu:x'
我的设备为两张rtx 3090 24gb每张

**Comment by wawltor** [comment]
显卡应该是可以用的，seg = Taskflow("word_segmentation"， device_id=-1) 试试， device_id是int类型数据

**Comment by lcneyc** [comment]
device_id=-1之后可用，现在paddlenlp无法调用gpu应该与paddle框架有关，我已经在paddle的issue中提问，如果您知道如何解决更好了
W0714 11:35:41.619335 111111 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0714 11:35:41.625015 111111 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
run_check()/每次都卡在这里

**Comment by wawltor** [comment]
一般情况下都是paddle版本安装的问题，建议通过conda来安装paddlepaddle-gpu版本，cuda的版本选择11.2版本 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/16698950/178936175-0d764714-c941-4b83-aaba-b9bd4453a615.png">
https://www.paddlepaddle.org.cn/

**Comment by lcneyc** [comment]
您好，谢谢解答，之前就按照官网conda命令新配了环境，然而问题仍未解决，所以感觉有些奇怪，谢谢！

**Comment by wawltor** [comment]
> 您好，谢谢解答，之前就按照官网conda命令新配了环境，然而问题仍未解决，所以感觉有些奇怪，谢谢！

3090的显卡需要安装cuda11的版本，之前遇到的问题基本是这样解决的

**Comment by lcneyc** [comment]
您好，谢谢，但我现在确实是cuda11.2 cudnn8.1.1，这个在runcheck时候也体现了
W0714 11:35:41.619335 111111 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0714 11:35:41.625015 111111 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.

**Comment by linjieccc** [comment]
> device_id=-1之后可用，现在paddlenlp无法调用gpu应该与paddle框架有关，我已经在paddle的issue中提问，如果您知道如何解决更好了 W0714 11:35:41.619335 111111 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2 W0714 11:35:41.625015 111111 gpu_context.cc:306] device: 0, cuDNN Version: 8.1. run_check()/每次都卡在这里

@lcneyc 您好，请问目前问题解决了吗
