### ISSUE TITLE
机器阅读理解将官方的baseline里的内置数据集改为本地的数据集报错，改了好久，一直不知道啥问题

### ISSUE THREAD

**Issue by abc-w** [PaddlePaddle/PaddleNLP#2799]
https://aistudio.baidu.com/aistudio/projectdetail/4306696?shared=1
![image](https://user-images.githubusercontent.com/84693075/178921919-e4c16ae9-f3e3-4c42-a470-191f2b5a77c0.png)
![image](https://user-images.githubusercontent.com/84693075/178921966-1c90e13e-e92f-48e5-8f44-47f1b14a9a01.png)
![image](https://user-images.githubusercontent.com/84693075/178922326-2bef3907-9fac-4cdd-8337-2b3b26a28536.png)
![image](https://user-images.githubusercontent.com/84693075/178921845-8f58338f-b107-4aad-8196-57680f83bb3b.png)

**Comment by LemonNoel** [comment]
尝试运行了一下，现在在prepare_train_features就报错了。看数据格式只有label的部分是不一样的，可以从原有代码改起，着重检查下修改后label的格式。

**Comment by guoshengCS** [comment]
same as #2770
