### ISSUE TITLE
关于 信息抽取 功能的一个疑问

### ISSUE THREAD

**Issue by czcz1024** [PaddlePaddle/PaddleNLP#2806]
我按照文档上的例子，
`schema = ['时间', '选手', '赛事名称','名次']
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))`
增加了抽取名次，但是结果中没有抽取到这个信息。
从人类的角度，信息中有 金牌，那名次是第一名，这个是可以理解的。
请问是我使用的方式不对，还是目前这个模块无法抽取这种信息？

**Comment by wawltor** [comment]
您好，你现在使用的模型是一个zero-shot的模型(模型在宽泛的场景能力比较有限)，在具体的应用场景中，需要针对需求来进行微调，UIE的一个特性就是小样本学习能力，通过少量标注数据可以快速提升效果，具体微调的方式 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
