### ISSUE TITLE
请问利用PaddleNLP机器阅读理解时，本地数据不像内置数据有answer_start这一项该怎么做

### ISSUE THREAD

**Issue by abc-w** [PaddlePaddle/PaddleNLP#2807]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
- 
请问利用PaddleNLP机器阅读理解时，本地数据不像内置数据有answer_start这一项该怎么做，手动标注吗，没有看到相关的代码

**Comment by guoshengCS** [comment]
same as #2770

**Comment by abc-w** [comment]
> same as #2770

![image](https://user-images.githubusercontent.com/84693075/179150160-a9cb082a-3b0a-4a6c-880b-8ea249f25f2b.png)
利用正则表达式re.search()匹配下标，但是有的正常数据会出现匹配不到，有没有其他好的方法

**Comment by abc-w** [comment]
> > same as #2770
> 
> ![image](https://user-images.githubusercontent.com/84693075/179150160-a9cb082a-3b0a-4a6c-880b-8ea249f25f2b.png) 利用正则表达式re.search()匹配下标，但是有的正常数据会出现匹配不到，有没有其他好的方法
不用了，已解决，谢谢
