### ISSUE TITLE
你好，我用uie做100多个实体识别的时候发现特别耗时，看过代码后发现预测是一个类别一个进行预测的，每个都判断一次，所以很耗时，请问是这样吗？原论文的实现方法也是这样吗？

### ISSUE THREAD

**Issue by Heihaierr** [PaddlePaddle/PaddleNLP#2808]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by KyleWang-Hunter** [comment]
cpu无法玩啊，速度太慢了。

**Comment by wawltor** [comment]
在UIE是一个抽取目标都会计算一次，原论文的实现的方式是一种生成方式，稍有不同，但是都会面临差不多的性能问题；目前我们正在做一个开放域UIE到封闭域模型蒸馏的工作，生成一个UIE模型之后然后通过UIE自动标注，然后将标注的样本自动转成封闭域模型，来缓解性能问题
