### ISSUE TITLE
Fast Generation生成结果不一致

### ISSUE THREAD

**Issue by ssrssrcode** [PaddlePaddle/PaddleNLP#2809]
你好，我发现使用fast generation进行生成推理时，会出现生成结果明显比不使用要短，而且质量下降。请问其内部原理是否会影响生成结果？

**Comment by guoshengCS** [comment]
请问是哪个模型，使用的生成策略是哪个呢，也可以提供下代码

**Comment by ssrssrcode** [comment]
plato-mini 策略是topk采样

**Comment by guoshengCS** [comment]
topk的话因为Faster和非加速版本生成随机的方式不太一样，这个确实不保证生成结果的一致。

另外因为Faster版本会使用gelu的近似实现来加速，这个会造成些差异，可以试下将非加速版本也修改为近似的看看是否能缩小两者的差异，方式可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/pull/1288  在init_weights里加下下面的代码：
```python
        elif isinstance(layer, (nn.TransformerEncoderLayer,
                                nn.TransformerDecoderLayer)):
            if layer.activation == F.gelu:
                layer.activation = partial(F.gelu, approximate=True)
```

之前内部测试UnifiedTransformer使用FasterGeneration的topk生成结果的质量是没有明显下降的

**Comment by ssrssrcode** [comment]
好的谢谢。另外请问一下，在部署成服务的时候出现FasterTransformer is not available because CUDA can not be found的问题，但是同一台机器另外测试inference文件却正常，请问有可能是什么情况呢

**Comment by ssrssrcode** [comment]
我又反复测试了一下，至少可以确认，plato-mini在fine-tune后使用fast generation生成效果确实稳定不如使用正常inference。语法问题和复读现象明显加重以及长度明显偏短。
