### ISSUE TITLE
请问ner支持自己的数据集吗

### ISSUE THREAD

**Issue by CoinCheung** [PaddlePaddle/PaddleNLP#2810]
https://github.com/PaddlePaddle/PaddleNLP/blob/7745db00b4ae00fd7a02a87cffc4ecd69cbb00fe/examples/information_extraction/msra_ner/train.py#L46

请问在数据格式应该是啥，在哪里指定数据集的目录?

貌似这个repo里面，除了uie之外，都没有说怎么使用自己的数据集做ner任务?

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie  可以看看这个示例，
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/16698950/179167683-64847d06-c0c9-4776-88c1-9b5c73a74268.png">

**Comment by CoinCheung** [comment]
@wawltor 是不是给的脚本里面没有加载自定义数据集的选项呢，只能在下载的数据集基础上来改，是这样吗?

**Comment by wawltor** [comment]
> @wawltor 是不是给的脚本里面没有加载自定义数据集的选项呢，只能在下载的数据集基础上来改，是这样吗?

嗯嗯，是的 目前你有BIO的数据还是说需要手动标注了？

**Comment by CoinCheung** [comment]
好的，现在work了，非常感谢!!! 还是建议完善一下这部分，代码还有文档啥的，刚开始看的时候有点懵
