### ISSUE TITLE
基于预训练模型结合本地csv数据集训练阅读理解模型，模型输出预测结果报错

### ISSUE THREAD

**Issue by abc-w** [PaddlePaddle/PaddleNLP#2812]
![image](https://user-images.githubusercontent.com/84693075/179177584-c2b50454-d43f-44e1-835d-c0c31804dd03.png)
https://aistudio.baidu.com/aistudio/projectdetail/4340434?contributionType=1&shared=1
麻烦帮忙看下很急

**Comment by wawltor** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/16698950/179191906-8ee4832b-bec4-42d1-af30-9970aa3004c1.png">
在保存模型结果的时候，传入到json.dumps是一个dict，dict的key不能是int64的类型数据，需要自己转化一下数据，将int64的key转化str对象

**Comment by abc-w** [comment]
> <img alt="image" width="895" src="https://user-images.githubusercontent.com/16698950/179191906-8ee4832b-bec4-42d1-af30-9970aa3004c1.png">
> 
> 在保存模型结果的时候，传入到json.dumps是一个dict，dict的key不能是int64的类型数据，需要自己转化一下数据，将int64的key转化str对象
好的，感谢，已解决，已经可以输出了，但我换了个测试集，数据就读不进来了test_ds = load_dataset(read, filename='通讯数据测试集.csv', lazy=False)这行报错
https://aistudio.baidu.com/aistudio/projectdetail/4340434?shared=1
![image](https://user-images.githubusercontent.com/84693075/179209510-ccc5832f-baa0-43d3-b1d0-83f2fa755442.png)

**Comment by abc-w** [comment]
> > <img alt="image" width="895" src="https://user-images.githubusercontent.com/16698950/179191906-8ee4832b-bec4-42d1-af30-9970aa3004c1.png">
> > 在保存模型结果的时候，传入到json.dumps是一个dict，dict的key不能是int64的类型数据，需要自己转化一下数据，将int64的key转化str对象
> > 好的，感谢，已解决，已经可以输出了，但我换了个测试集，数据就读不进来了test_ds = load_dataset(read, filename='通讯数据测试集.csv', lazy=False)这行报错
> > https://aistudio.baidu.com/aistudio/projectdetail/4340434?shared=1
> > ![image](https://user-images.githubusercontent.com/84693075/179209510-ccc5832f-baa0-43d3-b1d0-83f2fa755442.png)

不用了，已解决
