### ISSUE TITLE
plato-mini use_faster失败

### ISSUE THREAD

**Issue by Wu-Jiayang** [PaddlePaddle/PaddleNLP#2814]
- PaddleNLP 2.2.3
- PaddlePaddle-gpu2.2.1-post112
- Windows10
- 报错：
- Failed to run command: <built-in function compile>, errors: Command 'cd /d C:\Users\Wu Jiayang\AppData\Local\Programs\Python\Python38\Lib\site-packages\paddlenlp\ops\extenstions && C:\Users\Wu Jiayang\AppData\Local\Programs\Python\Python38\python.exe FasterTransformer_setup.py build' returned non-zero exit status 1.
- 手动运行cmd后
![image](https://user-images.githubusercontent.com/62842862/179203863-65e580d0-a141-47b2-b80f-b1df48665d40.png)

**Comment by wawltor** [comment]
目前faster_toeknizer还不支持windows系统，我们会在下个小版本来做兼容

**Comment by Wu-Jiayang** [comment]
> 

哦，好的

**Comment by Wu-Jiayang** [comment]
谢谢
