### ISSUE TITLE
使用CPU对UIE进行finetune时只能利用单核

### ISSUE THREAD

**Issue by qiudywzh** [PaddlePaddle/PaddleNLP#2815]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
paddlenlp==2.3.3
paddlepaddle-gpu==2.3.0
2）系统环境：
Ubuntu 7.5.0-3ubuntu1~18.04
Python 3.7.9
- 复现信息：如为报错，请给出复现环境、复现步骤

查阅了一些issue，是否因为paddle2动态图模式模型训练下无法支持cpu多核？
实测UIE推理是支持的多核CPU的，因为会生成一个inference model。

**Comment by wawltor** [comment]
目前paddle2动态图是在支持多核上功能已经开发完成，功能效果需要验证一下
预测是可以支持多核的，训练的时候需要多核之间有通信，因为训练需要梯度merge；预测的时候多核之间不需要通信，相对来说比较简单

**Comment by qiudywzh** [comment]
> 目前paddle2动态图是在支持多核上功能已经开发完成，功能效果需要验证一下 预测是可以支持多核的，训练的时候需要多核之间有通信，因为训练需要梯度merge；预测的时候多核之间不需要通信，相对来说比较简单

感谢。我试过升级到最新paddlepaddle 2.3.1和paddlenlp 2.3.4发现还没支持，期待更新。

我也试过用to_static方式将UIE改造为静态图，但是目前还没找到读取UIE权重到静态图的方法

**Comment by wawltor** [comment]
> > 目前paddle2动态图是在支持多核上功能已经开发完成，功能效果需要验证一下 预测是可以支持多核的，训练的时候需要多核之间有通信，因为训练需要梯度merge；预测的时候多核之间不需要通信，相对来说比较简单
> 
> 感谢。我试过升级到最新paddlepaddle 2.3.1和paddlenlp 2.3.4发现还没支持，期待更新。
> 
> 我也试过用to_static方式将UIE改造为静态图，但是目前还没找到读取UIE权重到静态图的方法

嗯嗯 目前的版本还没有支持多核训练，这个工作还在UIE上验证
