### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by CoinCheung** [PaddlePaddle/PaddleNLP#2818]
https://github.com/PaddlePaddle/PaddleNLP/blob/0a618c70f95eeea29ac084d6cf16d26fad289dd5/model_zoo/uie/utils.py#L345

Given a sample to be converted, if we the original line, the generated line would be something like this:
```
{"content": "江阴U17四国赛，广州恒大U17成大赢家或将为国青出战", "result_list": [{"text": "体", "start": -25, "end": -24}, {"text     ": "育", "start": -3, "end": -2}], "prompt": "文本类型[文化,军事,电竞,证券,旅游,农业,民生,体育,汽车,国际,科技,财经,娱乐,房产,教>     育]"}
```
But when we change that line into this:
```
 start = prompt.rfind(label[0]) - len(prompt)
```
The generated line woule be:
```
{"content": "江阴U17四国赛，广州恒大U17成大赢家或将为国青出战", "result_list": [{"text": "体", "start": -24, "end": -23}, {"text     ": "育", "start": -2, "end": -1}], "prompt": "文本类型[文化,军事,电竞,证券,旅游,农业,民生,体育,汽车,国际,科技,财经,娱乐,房产,教>     育]"}
``` 

Both of the two would work, if we only use uie to train classification task. But the original implementation seems not to align with annotation style of ner task. An example of generated ner line is like this:
```
{"content": "阿尔法协议》项目组。公司在昨日的新闻公告中这样描述今秋面市的《阿尔法协议》：", "result_list": [{"text": "阿尔法协       议》", "start": 0, "end": 6}, {"text": "《阿尔法协议》", "start": 30, "end": 37}], "prompt": "游戏"}
```
Seems that for ner task, the span is left-close-right-open without position offset, but classification annotation has that.

Is this expected behavior?

**Comment by linjieccc** [comment]
@CoinCheung Hi, can you provide an example of your classification annotation exported from doccano?

**Comment by CoinCheung** [comment]
@linjieccc Hi, it is in the original post: 
```
{"content": "江阴U17四国赛，广州恒大U17成大赢家或将为国青出战", "result_list": [{"text": "体", "start": -25, "end": -24}, {"text     ": "育", "start": -3, "end": -2}], "prompt": "文本类型[文化,军事,电竞,证券,旅游,农业,民生,体育,汽车,国际,科技,财经,娱乐,房产,教>     育]"}
````

**Comment by linjieccc** [comment]
> @linjieccc Hi, it is in the original post:
> 
> ```
> {"content": "江阴U17四国赛，广州恒大U17成大赢家或将为国青出战", "result_list": [{"text": "体", "start": -25, "end": -24}, {"text     ": "育", "start": -3, "end": -2}], "prompt": "文本类型[文化,军事,电竞,证券,旅游,农业,民生,体育,汽车,国际,科技,财经,娱乐,房产,教>     育]"}
> ```

The data format has been converted to train data format of UIE, the original data format exported from doccano is something like:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/40840292/179438354-b5fff838-f942-4193-a425-cbfa5461a7e3.png">

**Comment by CoinCheung** [comment]
It is something like this: 

```
 {"data": "勇士记者：克莱想要待在勇士 已和球队商讨提前续约", "label": "体育"}
 {"data": "北欧版兄弟连，芬兰的二战史诗《无名战士》(2017)", "label": "军事"}
 {"data": "网友偶遇黄圣依带安迪游玩，母子手拉手暖心有爱，旁边美女抢镜啦", "label": "娱乐"}
 {"data": "微屏玉指书佳句，下局怎么接？", "label": "文化"}
 {"data": "国家为什么不允许用红砖建房？", "label": "旅游"}
 {"data": "上亿资产被21岁娇妻榨尽，无奈带女儿租住凶宅，网友：真悲催！", "label": "娱乐"}
 {"data": "都只要10多万！有大众有丰田，这7款即将上市的爆款SUV值得等半年", "label": "汽车"}
 {"data": "发现自己上空被空投了原子弹，还有什么补救的措施吗？", "label": "军事"}
 {"data": "上联，东启明西长更，南箕北斗，如何对下联？", "label": "文化"}
```

**Comment by linjieccc** [comment]
> 

Please change it to the following format, the value format of `label` should be list of strings

```text
{"data": "勇士记者：克莱想要待在勇士 已和球队商讨提前续约", "label": ["体育"]}
{"data": "北欧版兄弟连，芬兰的二战史诗《无名战士》(2017)", "label": ["军事"]}
{"data": "网友偶遇黄圣依带安迪游玩，母子手拉手暖心有爱，旁边美女抢镜啦", "label": ["娱乐"]}
{"data": "微屏玉指书佳句，下局怎么接？", "label": ["文化"]}
{"data": "国家为什么不允许用红砖建房？", "label": ["旅游"]}
{"data": "上亿资产被21岁娇妻榨尽，无奈带女儿租住凶宅，网友：真悲催！", "label": ["娱乐"]}
{"data": "都只要10多万！有大众有丰田，这7款即将上市的爆款SUV值得等半年", "label": ["汽车"]}
{"data": "发现自己上空被空投了原子弹，还有什么补救的措施吗？", "label": ["军事"]}
{"data": "上联，东启明西长更，南箕北斗，如何对下联？", "label": ["文化"]}
```

**Comment by CoinCheung** [comment]
OK, I will try.Thanks for replying!!

**Comment by CoinCheung** [comment]
@linjieccc Hi, I think the problem is not solved.
One sample is like this:
```
{data: 肠道菌群对人的意识，行为，习惯，思维会产生怎样的影响？, label: [教育]}
```
and the generated sample is like this:
```
{"content": "肠道菌群对人的意识，行为，习惯，思维会产生怎样的影响？", "result_list": [{"text": "教育", "start": -46, "end": -44}], "prompt": "文本类型[教育,科技,文化,旅游,农业,房产,民生,娱乐,财经,军事,汽车,体育,国际,证券,电竞]"}
```
