### ISSUE TITLE
使用UIE做分类问题遇到的问题

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#2820]
首先按照开发文档，情感分类是在抽取哪里说明了，但是使用信息提取会报错
schema = '情感倾向[正向，负向]'
few_ie = Taskflow('information_extraction', schema=schema, batch_size=32,task_path='./checkpoint/model_best')
few_ie('这个产品用起来真的很流畅，我非常喜欢')
错误：
  374                 self.input_handles[0].copy_from_cpu(input_ids.numpy())
    375                 self.input_handles[1].copy_from_cpu(token_type_ids.numpy())
--> 376                 self.input_handles[2].copy_from_cpu(pos_ids.numpy())
    377                 self.input_handles[3].copy_from_cpu(att_mask.numpy())
    378                 self.predictor.run()

IndexError: list index out of range

**Comment by linjieccc** [comment]
@dingidng 辛苦贴下微调命令和训练数据示例，从报错来看应该是模型输入没有对上

**Comment by dingidng** [comment]
{"id":1286,"text":"這間酒店環境和服務態度亦算不錯,但房間空間太小~~不宣容納太大件行李~~且房間格調還可以~~ 中餐廳的廣東點心不太好吃~~要改善之~~~~但算價錢平宜~~可接受~~ 西餐廳格調都很好~~但吃的味道一般且令人等得太耐了~~要改善之~~\t","label":["正向"]}
{"id":1287,"text":"<荐书> 推荐所有喜欢<红楼>的红迷们一定要收藏这本书,要知道当年我听说这本书的时候花很长时间去图书馆找和借都没能如愿,所以这次一看到当当有,马上买了,红迷们也要记得备货哦!\t","label":["正向"]}

上面是jsonl训练是用的模型，
[2022-07-17 11:33:11,966] [    INFO] - Save 8 examples to ./data/train.txt.
[2022-07-17 11:33:11,967] [    INFO] - Save 1 examples to ./data/dev.txt.
[2022-07-17 11:33:11,967] [    INFO] - Save 2 examples to ./data/test.txt.
没有问题训练可用，
训练结果：
[2022-07-17 11:34:36,700] [    INFO] - global step 90, epoch: 90, loss: 0.00003, speed: 1.62 step/s
[2022-07-17 11:34:42,851] [    INFO] - global step 100, epoch: 100, loss: 0.00002, speed: 1.63 step/s
[2022-07-17 11:34:42,897] [    INFO] - Evaluation precision: 1.00000, recall: 1.00000, F1: 1.00000

最后模型预测数据：
酒店环境和服务都还不错，地理位置也不错，尤其是酒店北面的川北凉粉确实好吃。
设施老化，紧靠马路噪音太大。晚上楼上卫生间的水流声和空调噪音非常大，无法入眠。
schema = '情感倾向[正向，负向]'
# few_ie = Taskflow('information_extraction', schema=schema, batch_size=32)
few_ie = Taskflow('sentiment_analysis', schema=schema, batch_size=32,task_path='./checkpoint/model_best')
few_ie('这个产品用起来真的很流畅，我非常喜欢')
这里就出问题了

**Comment by dingidng** [comment]
{"content": "商品的不足暂时还没发现，京东的订单处理速度实在.......周二就打包完成，周五才发货...\t", "result_list": [{"text": "负向", "start": -4, "end": -2}], "prompt": "情感倾向[正向,负向]"}
{"content": "本来想没事的时候翻翻，可惜看不下去，还是和张没法比，他的书能畅销大部分还是受张的影响，对这个男人实在是没好感，不知道怎么买的，后悔\t", "result_list": [{"text": "负向", "start": -7, "end": -5}], "prompt": "情感倾向[负向,正向]"}

**Comment by dingidng** [comment]
命令：
!python doccano.py \
    --doccano_file ./data/cla.jsonl \
    --task_type 'cls' \
    --save_dir ./data \
    --splits 0.8 0.1 0.1 \
    --negative_ratio 5 \
    --prompt_prefix "情感倾向" \
    --options "正向" "负向"

!python finetune.py \
    --train_path "./data/train.txt" \
    --dev_path "./data/dev.txt" \
    --save_dir "./checkpoint" \
    --learning_rate 1e-5 \
    --batch_size 16 \
    --max_seq_len 512 \
    --num_epochs 100 \
    --model "uie-base" \
    --seed 1000 \
    --logging_steps 10 \
    --valid_steps 50 \
    --device "gpu"

schema = '情感倾向[正向，负向]'
 few_ie = Taskflow('information_extraction', schema=schema, batch_size=32,task_path='./checkpoint/model_best')
#few_ie = Taskflow('sentiment_analysis', schema=schema, batch_size=32,task_path='./checkpoint/model_best')
few_ie('这个产品用起来真的很流畅，我非常喜欢')

374 self.input_handles[0].copy_from_cpu(input_ids.numpy())
375 self.input_handles[1].copy_from_cpu(token_type_ids.numpy())
--> 376 self.input_handles[2].copy_from_cpu(pos_ids.numpy())
377 self.input_handles[3].copy_from_cpu(att_mask.numpy())
378 self.predictor.run()

IndexError: list index out of range

**Comment by linjieccc** [comment]
我这边试了下应该是可以正常使用，试试把``./checkpoint/model_best``删了clone最新develop分支代码重新训练以及更新下paddlenlp的版本看还有没有问题

**Comment by tingaicompass** [comment]
解决了，居然是./checkpoint/model_best删除就好了，可能加载了别的模型导致覆盖了出错，谢谢啦，
