### ISSUE TITLE
UIE性能

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#2821]
当UIE模型设置标签数多时，性能会很慢

**Comment by wawltor** [comment]
目前UIE的模型的特性确实会在较多的标签的时候导致性能变慢，目前我们正在做一个工作就是将UIE的模型转化成封闭域的信息抽取模型(传统BIO体系的模型)，这样的速度会快很多，目前这个工作正在进行中

**Comment by ZTurboX** [comment]
> 目前UIE的模型的特性确实会在较多的标签的时候导致性能变慢，目前我们正在做一个工作就是将UIE的模型转化成封闭域的信息抽取模型(传统BIO体系的模型)，这样的速度会快很多，目前这个工作正在进行中

那么也可以是小样本微调吗？

**Comment by wawltor** [comment]
> > 目前UIE的模型的特性确实会在较多的标签的时候导致性能变慢，目前我们正在做一个工作就是将UIE的模型转化成封闭域的信息抽取模型(传统BIO体系的模型)，这样的速度会快很多，目前这个工作正在进行中
> 
> 那么也可以是小样本微调吗？

可以小样本微调，我们的思路是这样的：
1. 先使用小样本训练一个UIE模型
2. 使用UIE模型来给大量无标签的数据打上标签
3. 使用封闭域模型(预测速度相对UIE快很多)来学习自动标签数据
