### ISSUE TITLE
机器翻译seq2seq训练loss 出现nan

### ISSUE THREAD

**Issue by 1689665417** [PaddlePaddle/PaddleNLP#2822]
系统环境：ubuntu18.04,py36,paddlepaddle-gpu2.3.0,paddlenlp2.3.0

训练代码：位于examples/machine_translation/seq2seq，只是加载的自定义的数据集和修改越南语为中文，其它未做修改，源语言是英文，目标是简体中文

数据集较大：约1500W对英-->中，vocab文件英中各6W词汇，英文是nltp分词的，中文是jieba分词的，分词后均是空格间隔的，已核对平行训练集无误

训练参数：learning_rate0.001，num_layers2，hidden_size512，batch_size32，max_epoch8，max_len64，dropout0.2，init_scale0.1，max_grad_norm5.0，beam_size10

训练过程1到3epoch显示好像是正常的，如图：
![image](https://user-images.githubusercontent.com/43131195/179436083-cb2d6218-8f37-4134-bd02-e5ed0fc1ced9.png)

在第四次epoch过程loss出现nan，如图：
![image](https://user-images.githubusercontent.com/43131195/179436289-229aa4f5-dce7-438f-b977-1d228bfdd018.png)

想请问有没有解决办法，谢谢~
另外请问第3次epoch保存的文件能否使用呢？

**Comment by LiuChiachi** [comment]
前3个epoch的训练是否正常呢，loss和perplexity的下降趋势是正常的吗。如果是正常的，可以再使用下第三个epoch保存的文件用一些case尝试预测一下看结果是否正常。
debug的建议：可以load第3个epoch之后保存的模型继续训练，把log_freq设为1，看下是具体哪一步变成nan的，检查这一步的输入输出看有没有问题，看看nan是怎么算出来的，然后再具体排查。
