### ISSUE TITLE
关于文本摘要开源例子的问题

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#2825]
您好，请问如下链接中开源的3个文本摘要的例子，其中的哪个模型适用于中文的文本摘要任务呢？我记得好像3个开源例子所使用的数据集都是英文数据集。

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_summarization

**Comment by gongel** [comment]
中文可以参考这个哈：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_generation/unimo-text

**Comment by ZeyuTeng96** [comment]
谢谢您，

请问还有其他模型做文本摘要的例子嘛？还有就是有考虑把您给我的那个链接的例子放到[text_summarization](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_summarization)下吗？或者这个目录下后续再提供一些中文的生成式文本摘要例子？

有这些后续的打算吗？

非常谢谢您

**Comment by gongel** [comment]
后续这些会在考虑之中哈，有其他的进展会及时同步给你，敬请期待

**Comment by ZeyuTeng96** [comment]
谢谢您，

还请问您一下，unimo-text-1.0-large的vocab-size为何会小于unimo-text-1.0呢？是在做预训练任务的时候所见到的数据量少于unimo-text-1.0？还请您指教下。 模型参数链接：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/unimo/modeling.py

> 后续这些会在考虑之中哈，有其他的进展会及时同步给你，敬请期待

**Comment by gongel** [comment]
> 谢谢您，
> 
> 还请问您一下，unimo-text-1.0-large的vocab-size为何会小于unimo-text-1.0呢？是在做预训练任务的时候所见到的数据量少于unimo-text-1.0？还请您指教下。 模型参数链接：

可以看下对应的论文哈
