### ISSUE TITLE
faster-generation使用随机batch_size 6-16请求10w次 后续耗时增加

### ISSUE THREAD

**Issue by zhanghaoie** [PaddlePaddle/PaddleNLP#2828]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
PaddleNLP 2.3.3 paddlepaddle 2.3.0.post112
2）系统环境：
- 复现信息：系统Linux nvcr.io/nvidia/tritonserver:20.12-py3 docker环境，python 3.8
   测试数据：
 context = [
        "你好",
        "你好啊，你叫什么名字",
        "我叫李明，你呢？"
    ]
请求batch_size 随机6-16，请求10w次，最开始请求耗时是在50-80ms之间，请求2个小时之后，请求耗时保持在120ms以上。

**Comment by zhanghaoie** [comment]
模型使用的plato_mini

**Comment by zhanghaoie** [comment]
请求大概50分钟之后，再次可以复现。

**Comment by zhanghaoie** [comment]
测试了paddlenlp paddlecloud/paddlenlp:develop-gpu-cuda10.2-cudnn7-latest的镜像，也存在这个问题。

**Comment by FrostML** [comment]
可以试试看这个 [PR #2910](https://github.com/PaddlePaddle/PaddleNLP/pull/2910) 能否优化这个问题。

**Comment by zhanghaoie** [comment]
> 可以试试看这个 [PR #2910](https://github.com/PaddlePaddle/PaddleNLP/pull/2910) 能否优化这个问题。

问题解决了，多谢
