### ISSUE TITLE
使用语义检索系统中的example semantic_search_example.py报错  （已使用最新代码）

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleNLP#2832]
PaddleNLP 2.3.4   ，PaddlePaddle-gpu 2.3.1   

使用CPU 运行

问题和https://github.com/PaddlePaddle/PaddleNLP/issues/2198 一致，但是我已拉取最新代码，仍旧报错

 File "/root/anaconda3/envs/paddlenlp/lib/python3.7/site-packages/paddle/nn/functional/input.py", line 206, in embedding
    'remote_prefetch', False, 'padding_idx', padding_idx)
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 513, but got 513. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:513 >= row_number:513.] (at /paddle/paddle/phi/kernels/cpu/embedding_kernel.cc:63)
  [operator < lookup_table_v2 > error]

**Comment by w5688414** [comment]
请贴一下您的硬件环境，还有更详细的信息吗？我这里并没有复现您说的问题。

![image](https://user-images.githubusercontent.com/12107462/179661526-17ca04c2-54f1-4faa-86f2-be327eafee2b.png)

**Comment by tianxin1860** [comment]
请问是使用 cpu 还是 gpu 环境在运行？

**Comment by mingo-doer** [comment]
> 请问是使用 cpu 还是 gpu 环境在运行？

使用cpu环境
GPU 环境可以正常运行
硬件环境：
![image](https://user-images.githubusercontent.com/28819717/179673356-cdf3ff66-75fd-4d54-a025-4ea2f70d1188.png)
gpu： T4

**Comment by w5688414** [comment]
> > 请问是使用 cpu 还是 gpu 环境在运行？
> 
> 使用cpu环境 GPU 环境可以正常运行 硬件环境： ![image](https://user-images.githubusercontent.com/28819717/179673356-cdf3ff66-75fd-4d54-a025-4ea2f70d1188.png) gpu： T4

没看出什么问题，重新创建一个虚拟的python环境看看，能不能复现这个cpu的问题

**Comment by tianxin1860** [comment]
在 cpu 环境下运行时时，请确保执行了 `unset CUDA_VISIBLE_DEVICES` 命令。

**Comment by tianxin1860** [comment]
![image](https://user-images.githubusercontent.com/6829601/179715322-1e2ecb07-21e5-49a9-904d-6ce389f084df.png)
