### ISSUE TITLE
怎么对rocketqa做预训练和fintune呢,根据官方教程,在小数据集上很差,怎么才能固定部分权重训练呢

### ISSUE THREAD

**Issue by allendred** [PaddlePaddle/PaddleNLP#2835]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
- paddlepaddle-gpu    2.3.1.post112
- cuda 11.2
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by tianxin1860** [comment]
请问是基于哪份代码进行 RocketQA 训练发现效果很差？可以贴一下链接

**Comment by allendred** [comment]
> 请问是基于哪份代码进行 RocketQA 训练发现效果很差？可以贴一下链接

https://github.com/PaddlePaddle/RocketQA
rocketqa的官方训练样例,可能是因为数据太少了,只有1万多条的训练数据,根据marco v1的权重的生成top8 做的数据集,总共大概8万条数据
