### ISSUE TITLE
关于信息抽取的关系抽取几点问题

### ISSUE THREAD

**Issue by HK-13** [PaddlePaddle/PaddleNLP#2837]
在目前taskflow的关系抽取中对schema的定义如：
``` python 
>>>  schema = {'竞赛名称': ['主办方', '承办方', '已举办次数']}
``` 
但是，这样的定义不支持对关系名称的定义，例如知识图谱中的**实体 - 关系- 实体**的定义，其关系名称是需要明确定义的。
具体到以上schema可能会变成  **竞赛 - 主办方 - 人**，**竞赛- 承办方-人**。

以上的问题，可能和知识标注场景有点类似，但是知识标注仅支持内置标签类型，对限定域的场景好像支持不足，目前不论知识标注或UIE似乎都没能提供直接的解决方案。

个人更倾向于使用UIE达到我所述场景，请问是否可以提供相关思路。

**Comment by linjieccc** [comment]
@4613 您好，可以参考以下思路来定制UIE模型

**一、schema设计**

结合领域知识图谱及领域数据设计一个定制schema集合

这里关系类型和客体类别需要一一对应，例如**竞赛-主办方-人**，**竞赛-主办方-机构**这种一个关系类型可能对应多个客体类别的情况，可以将关系类别进行拆分，改为**竞赛-主办者-人**，**竞赛-主办机构-机构**。

**二、模型定制（数据标注+模型微调）**

基于步骤一的schema集合，按照预先定义好的关系、实体类别标注数据并进行模型微调，通过Taskflow装载定制模型。

**Comment by HK-13** [comment]
> @4613 您好，可以参考以下思路来定制UIE模型
> 
> **一、schema设计**
> 
> 结合领域知识图谱及领域数据设计一个定制schema集合
> 
> 这里关系类型和客体类别需要一一对应，例如**竞赛-主办方-人**，**竞赛-主办方-机构**这种一个关系类型可能对应多个客体类别的情况，可以将关系类别进行拆分，改为**竞赛-主办者-人**，**竞赛-主办机构-机构**。因为UIE是开放域
> 
> **二、模型定制（数据标注+模型微调）**
> 
> 基于步骤一的schema集合，按照预先定义好的关系、实体类别标注数据并进行模型微调，通过Taskflow装载定制模型。

非常感谢回复！！！

1. 我指的是官方是否会在后续提供，schema直接定义关系名称的关系抽取能力，目前关系 schema定义其实有点类似属性抽取。
2. 你指的定制schema集合，是否可理解为：
     一、如果是不同关系名称对应相同实体类别，则根据目前的方式直接根据关系名称判定尾实体类别
     二、如果是不同关系名称对应不同实体类型，则建议通过定义可区分的关系名称来解决判断尾实体类别？
    当然，以上方式，需要在官方的schema上二次定制转换
3. 如果可以，希望官方给与相关example针对以上问题

**Comment by linjieccc** [comment]
您说的直接定义关系名称的方式可能不行，目前需要按照第二点所述方式结合预先定义的schema和UIE推断用到的schema对关系类别和尾实体类别做下映射。

例如：

预定义schema：
```text
{
    "object_type": "音乐专辑", 
    "predicate": "所属专辑", 
    "subject_type": "歌曲"
}
```
UIE推断用的schema：
```text
{
    "歌曲": "所属专辑"
}
```
我们最近有个正在开展的开放域到封闭域模型蒸馏的工作会提供一个相关的例子，欢迎持续关注~
