### ISSUE TITLE
ernie-3.0 序列标注任务 模型压缩样例代码compress_token_cls.py报错

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#2843]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：paddlenlp 2.3.4，paddlepaddle-gpu 2.3.1.post101，paddleslim 2.3.2
2）系统环境：AIStudio V100 16GB
- 复现信息：如为报错，请给出复现环境、复现步骤
参照ernie 3.0序列标注任务进行模型压缩报错

-代码目录结构
|-best_msra_ner_model/        # 模型msra_ner数据，run_token_cls训练结果文件夹
|--compress/                          # 压缩结果，目前是空文件夹
|--model_config.json
|--model_state.pdparams
|--special_tokens_map.json
|--vocab.txt
|--tokenizer_config.json
|-compress_trainer.py
|-config.yaml
|-infer.py
|-run_token_cls.py
|-compress_token_cls.py
|-token_classification.py        # ernie-1.0中文件
|-utils.py                                # ernie-1.0中文件

-代码修改处
compress_token_cls.py中
    import部分，将datasets在paddlenlp后导入
    ernie-1.0中文件复制到当前目录下，直接import

-报错信息：
Traceback (most recent call last):
  File "compress_token_cls.py", line 150, in <module>
    main()
  File "compress_token_cls.py", line 146, in main
    compress_config=compress_config)
  File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 158, in compress
    self.prune(output_dir, compress_config.prune_config)
  File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 189, in prune
    _dynabert(self, self.model, output_dir, prune_config)
  File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 239, in _dynabert
    output_dir)
  File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 468, in _dynabert_training
    width_mult=100)
  File "<decorator-gen-439>", line 2, in evaluate
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 362, in evaluate
    batch['seq_len'], preds, batch['labels'])
KeyError: 'seq_len'

-疑问：
是否是数据加载格式问题？
应该如何修改？
如何使用自建ner数据压缩模型？

**Comment by wawltor** [comment]
> 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：paddlenlp 2.3.4，paddlepaddle-gpu 2.3.1.post101，paddleslim 2.3.2
>   2）系统环境：AIStudio V100 16GB
> * 复现信息：如为报错，请给出复现环境、复现步骤
>   参照ernie 3.0序列标注任务进行模型压缩报错
> 
> -代码目录结构 |-best_msra_ner_model/ # 模型msra_ner数据，run_token_cls训练结果文件夹 |--compress/ # 压缩结果，目前是空文件夹 |--model_config.json |--model_state.pdparams |--special_tokens_map.json |--vocab.txt |--tokenizer_config.json |-compress_trainer.py |-config.yaml |-infer.py |-run_token_cls.py |-compress_token_cls.py |-token_classification.py # ernie-1.0中文件 |-utils.py # ernie-1.0中文件
> 
> -代码修改处 compress_token_cls.py中 import部分，将datasets在paddlenlp后导入 ernie-1.0中文件复制到当前目录下，直接import
> 
> -报错信息： Traceback (most recent call last): File "compress_token_cls.py", line 150, in main() File "compress_token_cls.py", line 146, in main compress_config=compress_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 158, in compress self.prune(output_dir, compress_config.prune_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 189, in prune _dynabert(self, self.model, output_dir, prune_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 239, in _dynabert output_dir) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 468, in _dynabert_training width_mult=100) File "", line 2, in evaluate File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function return func(*args, **kwargs) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 362, in evaluate batch['seq_len'], preds, batch['labels']) KeyError: 'seq_len'
> 
> -疑问： 是否是数据加载格式问题？ 应该如何修改？ 如何使用自建ner数据压缩模型？

想问一下PaddleNLP版本的是多少了？

**Comment by Macxy2018** [comment]
> > 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！ 在留下您的问题时，辛苦您同步提供如下信息：
> > 
> > * 版本、环境信息
> >   1）PaddleNLP和PaddlePaddle版本：paddlenlp 2.3.4，paddlepaddle-gpu 2.3.1.post101，paddleslim 2.3.2
> >   2）系统环境：AIStudio V100 16GB
> > * 复现信息：如为报错，请给出复现环境、复现步骤
> >   参照ernie 3.0序列标注任务进行模型压缩报错
> > 
> > -代码目录结构 |-best_msra_ner_model/ # 模型msra_ner数据，run_token_cls训练结果文件夹 |--compress/ # 压缩结果，目前是空文件夹 |--model_config.json |--model_state.pdparams |--special_tokens_map.json |--vocab.txt |--tokenizer_config.json |-compress_trainer.py |-config.yaml |-infer.py |-run_token_cls.py |-compress_token_cls.py |-token_classification.py # ernie-1.0中文件 |-utils.py # ernie-1.0中文件
> > -代码修改处 compress_token_cls.py中 import部分，将datasets在paddlenlp后导入 ernie-1.0中文件复制到当前目录下，直接import
> > -报错信息： Traceback (most recent call last): File "compress_token_cls.py", line 150, in main() File "compress_token_cls.py", line 146, in main compress_config=compress_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 158, in compress self.prune(output_dir, compress_config.prune_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 189, in prune _dynabert(self, self.model, output_dir, prune_config) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 239, in _dynabert output_dir) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 468, in _dynabert_training width_mult=100) File "", line 2, in evaluate File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function return func(*args, **kwargs) File "/home/aistudio/ernie3_token_cls/compress_trainer.py", line 362, in evaluate batch['seq_len'], preds, batch['labels']) KeyError: 'seq_len'
> > -疑问： 是否是数据加载格式问题？ 应该如何修改？ 如何使用自建ner数据压缩模型？
> 
> 想问一下PaddleNLP版本的是多少了？

paddlenlp版本是2.3.4

**Comment by LiuChiachi** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/3787da1f158d06629fe8460e99328dfc02f5ea09/model_zoo/ernie-1.0/finetune/token_classification.py#L26
`return_length=False` 改为 `return_length=True`

**Comment by Macxy2018** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/3787da1f158d06629fe8460e99328dfc02f5ea09/model_zoo/ernie-1.0/finetune/token_classification.py#L26
> 
> 
> `return_length=False` 改为 `return_length=True`

好的，我现在是在metric.compute前加了这一行代码临时处理的，我试一下return_length改成True
batch['seq_len'] = [((a != -100) == True).sum()[0] for a in batch['labels']]
