### ISSUE TITLE
模型已经训练完成，如何使用多卡进行信息抽取任务？

### ISSUE THREAD

**Issue by YiTSu** [PaddlePaddle/PaddleNLP#2844]
当前机器上有两张16G的显卡，模型已经训练完成，目前进行信息抽取任务时只使用到了一张卡，如何使用两张卡进行信息抽取任务以提升预测速度呢？

**Comment by wawltor** [comment]
这个可以启动两个Taskflow任务，Taskflow(device_id) 来控制卡号

**Comment by YiTSu** [comment]
> 这个可以启动两个Taskflow任务，Taskflow(device_id) 来控制卡号

有没有利用NCCL使用多卡，然后让单个任务都使用多卡的方法呢。每个任务分别使用一张卡其实没有速度的提升。

**Comment by wawltor** [comment]
> > 这个可以启动两个Taskflow任务，Taskflow(device_id) 来控制卡号
> 
> 有没有利用NCCL使用多卡，然后让单个任务都使用多卡的方法呢。每个任务分别使用一张卡其实没有速度的提升。

预测的时候没有办法使用NCCL的，训练NCCL的作用是梯度merge，但是预测时是没有同步梯度的

**Comment by YiTSu** [comment]
> > > 这个可以启动两个Taskflow任务，Taskflow(device_id) 来控制卡号
> > 
> > 
> > 有没有利用NCCL使用多卡，然后让单个任务都使用多卡的方法呢。每个任务分别使用一张卡其实没有速度的提升。
> 
> 预测的时候没有办法使用NCCL的，训练NCCL的作用是梯度merge，但是预测时是没有同步梯度的

哦哦好的

**Comment by xikakera** [comment]
> 这个可以启动两个Taskflow任务，Taskflow(device_id) 来控制卡号

你好，我使用multiprocessing 的Process 打开两个进程进行计算， 使用两个显卡， 运行一会之后会整个机子卡死。只有鼠标能动，只能重启。
单个显卡运行没有问题， 一起启动就会卡死。显示第二张卡err

一个是 RTX 3060
一个是 GTX 1080Ti
用的是 paddlepaddle-gpu          2.3.1      py38_gpu_cuda11.2_many_linux
