### ISSUE TITLE
 The models name:uie-nano is not in task:[information_extraction]

### ISSUE THREAD

**Issue by YiTSu** [PaddlePaddle/PaddleNLP#2847]
The models name:uie-nano is not in task:[information_extraction]
 这是什么原因呢？已经有了nano的模型。
 ![截屏2022-07-21 20 04 54](https://user-images.githubusercontent.com/16937245/180209444-1a12b69a-1834-4f81-9b01-a22acc1d9233.png)

**Comment by linjieccc** [comment]
@YiTSu 需要确保paddlenlp的版本>=2.3.4
