### ISSUE TITLE
ValueError: Operator "gen_nccl_id" has not been registered.

### ISSUE THREAD

**Issue by guochongjun** [PaddlePaddle/PaddleNLP#2848]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/doc_vqa按文档操作报错
![1658407352744](https://user-images.githubusercontent.com/66577364/180216189-a346fb5d-b461-4d5c-bacb-9482a67e25a0.jpg)
![1658407376633](https://user-images.githubusercontent.com/66577364/180216196-c490461c-6171-432d-a95c-6726fd3be3e3.jpg)
![1658407405960](https://user-images.githubusercontent.com/66577364/180216199-7fb8eec9-0e85-4bbf-9ed4-7eacb3b3290d.jpg)
![1658407425360](https://user-images.githubusercontent.com/66577364/180216202-a1331c83-ab6e-42db-92b0-b4205a5fcd46.jpg)

**Comment by wawltor** [comment]
麻烦提供一下PaddlePaddle的版本

**Comment by wshzd** [comment]
我也遇到了同样的问题，我的paddlepaddle版本是
paddlenlp             2.3.1
paddleocr             2.5
paddlepaddle          2.3.0

**Comment by guochongjun** [comment]
PaddlePaddle2..1

**Comment by guochongjun** [comment]
PaddlePaddle2.3.1

**Comment by adamlin2000** [comment]
paddlenlp 2.3.7
paddleocr 2.6
paddlepaddle 2.3.2
我也碰到

**Comment by Deepx-China** [comment]
paddlenlp 2.3.7
paddleocr 2.6
paddlepaddle 2.3.2
我也碰到
