### ISSUE TITLE
DuEE sequence_labeling.py导包错误

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#2852]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.4，PaddlePaddle2.1.1
2）系统环境：Linux
- 报错信息：![image](https://user-images.githubusercontent.com/50394665/180337159-dbaf45fd-135e-4169-b8ba-62237bf167e4.png)
- 修改建议：改成`AutoModelForTokenClassification`

https://github.com/PaddlePaddle/PaddleNLP/blob/4d18e4d648fadde639575b6de3e0b3c3a38bb906/examples/information_extraction/DuEE/sequence_labeling.py#L30

https://github.com/PaddlePaddle/PaddleNLP/blob/4d18e4d648fadde639575b6de3e0b3c3a38bb906/tests/ernie_information_extraction/export_model.py#L37-L38

**Comment by wj-Mcat** [comment]
Great post for this issue, I think you can fire a pr to fix it. How do you think about?

**Comment by JunnYu** [comment]
@wj-Mcat  done
