### ISSUE TITLE
关于UIE模型的训练negative_ratio负例比例 

### ISSUE THREAD

**Issue by YYGe01** [PaddlePaddle/PaddleNLP#2858]
hi，我正在使用UIE模型，标注了一批数据用于做微调，想问下这个negative_ratio负例比例的合理范围大概是什么区间呢，我看默认是5，我这边的数据，最大可以构造20倍的负例数量。
想问下是否negative_ratio可以设置的大点，这样训练数据会多点，但是否会影响模型正例判断呢，谢谢！

**Comment by wawltor** [comment]
> hi，我正在使用UIE模型，标注了一批数据用于做微调，想问下这个negative_ratio负例比例的合理范围大概是什么区间呢，我看默认是5，我这边的数据，最大可以构造20倍的负例数量。 想问下是否negative_ratio可以设置的大点，这样训练数据会多点，但是否会影响模型正例判断呢，谢谢！

我们的经验值5就可以了，当然如果不考虑训练时间的话，可以增加负样本多试试
