### ISSUE TITLE
RuntimeError: C:\Users\**\.paddlenlp mkdir failed!

### ISSUE THREAD

**Issue by YangYu-Li** [PaddlePaddle/PaddleNLP#2860]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
PaddleNlp 2.3.4
Paddle 2.3.1
windows, python3.7
![c8ccfa43acb91c6cca09ff3562283eb](https://user-images.githubusercontent.com/60566349/180492574-7a707c38-ada6-4d71-abaf-d6316a58e7b9.png)
![42fc781255267ad2270326d08c160bd](https://user-images.githubusercontent.com/60566349/180492593-49cf385a-d4e0-4bbd-b368-38af9c155d35.png)

**Comment by wawltor** [comment]
看起来是python环境的版本和windows的版本不太兼容，导致无法生成一个中文的路径，可以尝试以下操作
1. 可以尝试将python版本提升3.8+ 
2. 不提升python环境，ie = Taskflow('information_extraction', schema=schema, home_path="./") ，可以设置一个home_path来生成一个目录，这个文件目录来存放下载的模型文件
