### ISSUE TITLE
模型下载的方式

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/PaddleNLP#2861]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！

下载预训练模型，只能通过AutoModel.from_pretrained这种方式吗，可以自己到网页上面下载吗

**Comment by wawltor** [comment]
可以手动下载模型，https://github.com/PaddlePaddle/PaddleNLP/blob/e568e07329f50a68bb18c95643a8a0a7edd61cf1/paddlenlp/transformers/bert/modeling.py#L379 ，在各个模型的modeling.py提供了相应的下载链接，例如 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/16698950/180716878-440ae900-3652-4437-88b8-21bf9cc7caa2.png">

同时也可以从一个目录下来加载模型(例如把模型下载到特定的目录)
```python 
ernie = ErnieModel.from_pretrained('/path/xxx')
````

**Comment by kennyLSN** [comment]
> 

可以的，谢谢
