### ISSUE TITLE
ernie-1.0预测后相同predicate相同subject不同object的关系只有第一个subject被标记 

### ISSUE THREAD

**Issue by DuChongyang** [PaddlePaddle/PaddleNLP#2862]
+ 我在使用ernie-1.0时发现，在同一句话中出现的具有相同predicate的同一个subject但对应不同object的关系只有第一个subject被标记
+ 例如：
   + “李白是《静夜思》的作者，杜甫是《登高》的作者，李白写了《将进酒》。”
   + 第二个“李白”在输出的labels中并未标记，我无法准确decode出正确的关系。
+ 请问是什么原因有人知道吗？是我在使用模型时忽略掉了一些参数，还是ernie-1.0本身就是这样的？

**Comment by wawltor** [comment]
麻烦提供一下具体执行的什么代码或者代码地址

**Comment by DuChongyang** [comment]
> 麻烦提供一下具体执行的什么代码或者代码地址

代码地址是这个https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuIE

在我用训练好的模型对“李白是《静夜思》的作者，杜甫是《登高》的作者，李白写了《将进酒》。”这句话进行预测时，模型输出的logits只对“**李白**是《**静夜思**》的作者，**杜甫**是《**登高**》的作者，李白写了《**将进酒**》。”（黑体）进行了标记，即找到的实体只有
subjects：静夜思、登高、将进酒，
objects：李白、杜甫，
接下来utils.py中的decode中的：
 for subject_ in subjects:
                    for object_ in objects:
则更加离谱，根本无法得到正确的三元组。

**Comment by LemonNoel** [comment]
- 第二个`李白`的问题是因为在抽取实体的时候使用了集合，因此去重了。https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/DuIE/utils.py#L44
- `utils.py`中的`decode`可以处理的是同一实体对应不同的关系或者实体。对于同一关系下的多实体和多实体间的映射关系确实没有考虑，这个例子有点偏消歧问题，如果实际应用中这种情况较多可以根据数据的特点加以修改限制。

**Comment by DuChongyang** [comment]
> * 第二个`李白`的问题是因为在抽取实体的时候使用了集合，因此去重了。https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/DuIE/utils.py#L44
> * `utils.py`中的`decode`可以处理的是同一实体对应不同的关系或者实体。对于同一关系下的多实体和多实体间的映射关系确实没有考虑，这个例子有点偏消歧问题，如果实际应用中这种情况较多可以根据数据的特点加以修改限制。

+ 起初我也以为是set的原因，但仔细观察传入的predictions：
![image](https://user-images.githubusercontent.com/66300928/180905120-b8fe4942-19b1-4d66-91f9-c63c136f4c6a.png)
‘李白是《静夜思》的作者，杜甫是《登高》的作者，李白写了《将进酒》。’
对照发现确实是第二个`李白`没有标记。

**Comment by LemonNoel** [comment]
这里可能是因为在训练集中较少或者没有相似的句式，因此模型抽取效果不够好，如果有需求可以通过数据构造来改进模型。
