### ISSUE TITLE
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie里面没有做paddleserving服务化部署的案例吗?

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#2863]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie里面没有做paddleserving服务化部署的案例吗?

**Comment by wawltor** [comment]
> [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie里面没有做paddleserving服务化部署的案例吗](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie%E9%87%8C%E9%9D%A2%E6%B2%A1%E6%9C%89%E5%81%9Apaddleserving%E6%9C%8D%E5%8A%A1%E5%8C%96%E9%83%A8%E7%BD%B2%E7%9A%84%E6%A1%88%E4%BE%8B%E5%90%97)?

目前我们的计划是基于FlaskAPI / FastAPI 来建设PaddleNLP的服务化，目前这个工作还在进行，UIE的服务化的代码可以
```python
from paddlenlp import Taskflow
from flask import Flask, request, jsonify
import traceback
import threading

lock = threading.Lock()

ie = Taskflow('information_extraction', schema=schema, precision="fp16")
app = Flask(__name__)

@app.route('/uie', methods=['post'])
def uie():
    body = request.json
    text = body.get('text')
    lock.acquire()
    try:
        res = str(ie(text))
        lock.release()
        return jsonify(res)
    except Exception as e:
        lock.release()
        traceback.print_exc()
        return jsonify(e)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8020, debug=True)
```

**Comment by AI-Mart** [comment]
感谢回复，这样设计是出于什么原因呢？flask这样部署的话，模型服务只能这个应用单独使用了，不能给其他应用共享一个模型服务了,另外假如追求效率要C++部署的话，是不是也不行了？

**Comment by wawltor** [comment]
> 感谢回复，这样设计是出于什么原因呢？flask这样部署的话，模型服务只能这个应用单独使用了，不能给其他应用共享一个模型服务了,另外假如追求效率要C++部署的话，是不是也不行了？

目前C++部署比较适用于高QPS的应用场景，对于QPS相对来说比较低的场景Flask这样的API并不会影响它的预测速度，同时考虑到Taskflow这样的使用方式，相对来说偏向于离线或者低QPS的场景，所以Flask相对比较适宜；后续我们也会加上paddle serving这样的服务化的方式

**Comment by AI-Mart** [comment]
好的，是的，目前这个偏向于离线服务，在线服务还是需要高可用的，期待你们加上服务化部署的案例

**Comment by wawltor** [comment]
> 好的，是的，目前这个偏向于离线服务，在线服务还是需要高可用的，期待你们加上服务化部署的案例

嗯嗯，这个工作正在增加，谢谢反馈！
我们暂时关闭issue，有问题可以再次打开改issue。
