### ISSUE TITLE
运行ernie3.0压缩后的推理时遇到报错

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleNLP#2880]
文本分类模型，执行 python run_seq_cls.py  --task_name tnews --model_name_or_path ernie-3.0-medium-zh --do_train 对预训练模型进行微调，执行 python compress_seq_cls.py --dataset "clue tnews"  --model_name_or_path best_models/TNEWS  --output_dir ./ 对微调结果进行压缩和剪枝。推理 python infer.py --task_name tnews --model_path best_models/TNEWS/compress/0.75/float --use_trt 遇到报错：

Enable TensorRT is: True
W0726 08:50:51.320725   304 analysis_predictor.cc:1118] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0726 08:50:51.345453   304 analysis_predictor.cc:881] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
Traceback (most recent call last):
  File "infer.py", line 567, in <module>
    main()
  File "infer.py", line 508, in main
    predictor = Predictor.create_predictor(args)
  File "infer.py", line 270, in create_predictor
    predictor = paddle.inference.create_predictor(config)
ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)

**Comment by wawltor** [comment]
麻烦提供一下PaddlePaddle和PaddleNLP的版本

**Comment by LiuChiachi** [comment]
可以先确保Paddle Inference以及TensorRT是否正确安装了，可以参考官网，https://www.paddlepaddle.org.cn/inference/user_guides/download_lib.html，或者ernie-3.0/deploy的文档～

**Comment by ezekielqu** [comment]
> 麻烦提供一下PaddlePaddle和PaddleNLP的版本

paddlenlp           2.3.4          
paddlepaddle-gpu    2.3.1.post112

paddle的版本是paddle提供的docker中自带的
