### ISSUE TITLE
请教：某种情况下uie如何设计schema

### ISSUE THREAD

**Issue by YYGe01** [PaddlePaddle/PaddleNLP#2882]
您好,  我有这么个例子.
```text
协和医院的面积不小于1000m2，总高度大于20m。
```
schema为：
```python
{'组织': ['面积, '高度']}
```

请问这里的‘不小于’和‘大于’，可以怎么设计schema才能提取出来呢？谢谢！

**Comment by wawltor** [comment]
看起来有两种设计方式，
1. 在数据标注的过程中，将不小于1000m2 作为面积，大于20m作为高度
2. 第二种方式增加一种的新的高度，{'组织': ['范围', '面积, '高度']}  将‘不小于’和‘大于’ 作为范围字段输出

**Comment by YYGe01** [comment]
> 看起来有两种设计方式，
> 
> 1. 在数据标注的过程中，将不小于1000m2 作为面积，大于20m作为高度
> 2. 第二种方式增加一种的新的高度，{'组织': ['范围', '面积, '高度']}  将‘不小于’和‘大于’ 作为范围字段输出

谢谢指导，第二种方式中，如果新增关系 `范围`，这个例子中，协和医院的范围是：
```text
不小于  大于
```
一个问题是因为这里是共用一个主体，没法判断`不小于`是和`1000m2` 是一组，我这边能想到的是新增后处理，通过字符距离就近原则分组，虽然是个办法，但感觉模型没有一步到位，有点遗憾。

**Comment by wawltor** [comment]
> > 看起来有两种设计方式，
> > 
> > 1. 在数据标注的过程中，将不小于1000m2 作为面积，大于20m作为高度
> > 2. 第二种方式增加一种的新的高度，{'组织': ['范围', '面积, '高度']}  将‘不小于’和‘大于’ 作为范围字段输出
> 
> 谢谢指导，第二种方式中，如果新增关系 `范围`，这个例子中，协和医院的范围是：
> 
> ```
> 不小于  大于
> ```
> 
> 一个问题是因为这里是共用一个主体，没法判断`不小于`是和`1000m2` 是一组，我这边能想到的是新增后处理，通过字符距离就近原则分组，虽然是个办法，但感觉模型没有一步到位，有点遗憾。

这里可以继续将范围作为关系抽取的方式来做，例如  {'组织': ['面积':{'范围'}, '高度':{'范围'}]}
