### ISSUE TITLE
tqdm版本冲突

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#2884]
![image](https://user-images.githubusercontent.com/109952192/181008429-9ae52616-2308-43e5-892f-e5e5e5cf8161.png)

pip install paddlenlp==2.3.3 报tqdm包版本冲突

**Comment by wawltor** [comment]
可以升级一下tqdm的版本

**Comment by MachineSheep** [comment]
> 可以升级一下tqdm的版本

是pip安装过程中,版本冲突导致的报错，然后安装进程结束，单独装tqdm最新版之后还是会报错

**Comment by wawltor** [comment]
更新tqdm的版本是什么版本了？

**Comment by MachineSheep** [comment]
> 更新tqdm的版本是什么版本了？

你好，是4.62.1

**Comment by MachineSheep** [comment]
> 更新tqdm的版本是什么版本了？
