### ISSUE TITLE
paddleNLP 机器翻译Demo问题

### ISSUE THREAD

**Issue by qjxjy123** [PaddlePaddle/PaddleNLP#2887]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/faster_generation/samples/mbart_sample.py
在paddlenlp机器翻译内置权重的使用过程中，当输入纯数字进行英译中的时候，会出现一些异常情况：在预测结果前面加入『小行星』、『號』等文字，在demo里将输入的英文改为纯数字即可复现结果。
![image](https://user-images.githubusercontent.com/38102868/181146624-8988004f-f87e-42c8-8dde-97a3d721057e.png)
![image](https://user-images.githubusercontent.com/38102868/181146636-67cb79a1-6013-455c-aa28-8e09fbe7e819.png)

**Comment by gongel** [comment]
你好，我测试过HF的源代码，结果是一致的哈。该模型对数字支持确实不是很好，可以尝试换成`mbart-large-50-many-to-many-mmt`或者做些后处理。
