### ISSUE TITLE
按照API进行下游任务Fine-tuning时，这段代码分开执行没有问题，但在一个jupyter单元块中执行会报错。

### ISSUE THREAD

**Issue by zoeChen119** [PaddlePaddle/PaddleNLP#2888]
`from functools import partial
import numpy as np

import paddle
from paddlenlp.datasets import load_dataset
from paddlenlp.transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained("ernie-1.0-base-zh", num_classes=3)

tokenizer = AutoTokenizer.from_pretrained("ernie-1.0-base-zh")

def convert_example(example, tokenizer):
    encoded_inputs = tokenizer(text=example["text"], max_seq_len=512, pad_to_max_seq_len=True)
    return tuple([np.array(x, dtype="int64") for x in [
            encoded_inputs["input_ids"], encoded_inputs["token_type_ids"], [example["label"]]]])
train_ds = train_ds.map(partial(convert_example, tokenizer=tokenizer))

batch_sampler = paddle.io.BatchSampler(dataset=train_ds, batch_size=8, shuffle=True)
train_data_loader = paddle.io.DataLoader(dataset=train_ds, batch_sampler=batch_sampler, return_list=True)

optimizer = paddle.optimizer.AdamW(learning_rate=0.001, parameters=model.parameters())

criterion = paddle.nn.loss.CrossEntropyLoss()

for input_ids, token_type_ids, labels in train_data_loader():
    logits = model(input_ids, token_type_ids)
    loss = criterion(logits, labels)
    loss.backward()
    optimizer.step()
    optimizer.clear_grad()`
这些代码放在一个jupyter单元块中执行报以下错误：

> [2022-07-27 02:24:06,766] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieForSequenceClassification'> to load 'ernie-1.0-base-zh'.
[2022-07-27 02:24:06,769] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0-base-zh/ernie_v1_chn_base.pdparams
[2022-07-27 02:24:08,826] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-1.0-base-zh'.
[2022-07-27 02:24:08,828] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0-base-zh/vocab.txt
[2022-07-27 02:24:08,858] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/ernie-1.0-base-zh/tokenizer_config.json
[2022-07-27 02:24:08,860] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/ernie-1.0-base-zh/special_tokens_map.json
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/paddle/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 277, in __getitem__
    ) if self._transform_pipline else self.new_data[idx]
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 267, in _transform
    data = fn(data)
  File "/tmp/ipykernel_3000/920667017.py", line 34, in convert_example
    encoded_inputs = tokenizer(text=example[0], max_seq_len=512, pad_to_max_seq_len=True)
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 2195, in __call__
    "text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) "
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

但是当我将前半段放在一个单元块中执行，

`from functools import partial
import numpy as np

import paddle
from paddlenlp.datasets import load_dataset
from paddlenlp.transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained("ernie-tiny", num_classes=3)

tokenizer = AutoTokenizer.from_pretrained("ernie-tiny")

def convert_example(example, tokenizer):
    encoded_inputs = tokenizer(text=example["text"], max_seq_len=512, pad_to_max_seq_len=True)
    return tuple([np.array(x, dtype="int64") for x in [
            encoded_inputs["input_ids"], encoded_inputs["token_type_ids"], [example["label"]]]])
train_ds = train_ds.map(partial(convert_example, tokenizer=tokenizer))

batch_sampler = paddle.io.BatchSampler(dataset=train_ds, batch_size=8, shuffle=True)
train_data_loader = paddle.io.DataLoader(dataset=train_ds, batch_sampler=batch_sampler, return_list=True)

optimizer = paddle.optimizer.AdamW(learning_rate=0.001, parameters=model.parameters())

criterion = paddle.nn.loss.CrossEntropyLoss()`

后半段放在第二个单元块执行，

`
for input_ids, token_type_ids, labels in train_data_loader():
    logits = model(input_ids, token_type_ids)
    loss = criterion(logits, labels)
    loss.backward()
    optimizer.step()
    optimizer.clear_grad()
`

便不会报错。请问这是为什么？感谢回答。
这段代码来自于[https://paddlenlp.readthedocs.io/zh/latest/model_zoo/index.html](url)

**Comment by wawltor** [comment]
看起来你上面使用的模型是ernie-1.0模型，下面使用的是ernie-tiny模型，
能具体提供一下你的数据集、paddlenlp的版本吗？

**Comment by zoeChen119** [comment]
> 

我的paddle版本是2.3.1
嗯，这里是的，不过我有逐个尝试ernie的不同版本，至少在api文档中的前三个ernie版本都是model_names = [ 'ernie-1.0-base-zh', 'ernie-tiny',  'ernie-2.0-base-en']都是如此。
我的数据集是这样的：

> text	label
坐席:你好请问什么帮您？#客户:你好我看一下我宽带现在怎么回事儿。#坐席:好的，您号码，请您提供一下。#客户:幺五三，五三四九，二七五五。#坐席:二七五五是吗？请您稍等一下，姓名麻烦报一下。#客户:农万星。#坐席:好的，这里没有两条网线竹路还是二线。#客户:应该是主路途中是不是一个月那个。#坐席:我给您看看啊，您刚才说这个地址目前是在哪。#客户:北京颐和俊。#坐席:好的谢谢您，现在通过系统帮您测试中请您稍等一下。#客户:听清。#坐席:系统这边帮您测试了一下显示是线路正常。#客户:一。#坐席:对您那边有什么提示呢？#客户:我提示我现在看不到但是我，刚把猫的线拔了一下您毛怎么样啊。#坐席:您那的小区名字叫什么呢？#客户:就这一个g小区。#坐席:那就，不对呀，你等一下啊，请您稍等一下，是一和俊是吧。#客户:没有。#坐席:这两个地址都不是。#客户:你说的地址不是啥意思。#坐席:就是您所报的地址跟我这边，的地址核对了一下是不一样的，不是。#客户:就是我这个号码跟这个，不一样吗？#坐席:您的号码对吧我给您报一遍幺五三五三四九二七五五。#客户:对呀机主叫没。#坐席:对相关联的宽带，对这个是机主姓名没问题，您关联的这个宽带，	宽带类
坐席:七七，您好请问什么可以帮您你好？#客户:哎你好，嗯，我知道我家里这个宽带上不了网了。#坐席:好的你等一下我给您看一下啊。#客户:嗯嗯，这不是手机绑定这一步。#坐席:不是这个吗那您说一下那个账号？#客户:呃那个手机是幺七七，七八九六幺九，七幺，七幺。#坐席:幺七七七八九六幺九七幺。#客户:对。#坐席:好宽带地址在哪里跟您确认。#客户:呃，西铁铲吧生态院二十三号楼二幺零。#坐席:好稍等一下。#客户:嗯。#坐席:我看一下它显示账号绑定错了，小。#客户:账号绑政策。#坐席:对是的账号连接时出现了点问题，嗯，一下。#客户:嗯好。#坐席:啊。#客户:嗯，好。#坐席:说。#客户:啊。#坐席:嗯，好的您先这样先生您满意。#客户:嗯，嗯。#坐席:不限不挂机咱在线测试好。#客户:好好。#坐席:哎。#客户:我把电话了，现在重启了。#坐席:你。#客户:刚说他这个是咋咋回事上不去网了。#坐席:有账号绑定错了，账号连接时出现问题您看您的那个账号有没有增核实呀。#客户:账号咋了。#坐席:绑，错了就您登录的时候把账号给输错。#客户:我没有输呀，昨天一直好好的早上起来这样，就上不了网了我想是今年十月一号，然后扣费了，然后又交了二百块话费	宽带类

**Comment by wawltor** [comment]
可以尝试先升级到paddlenlp 2.3.4吗？如果不行的话，最好能把少量数据和你现在使用的全部代码发给我们，我们来测试一下

**Comment by wawltor** [comment]
> 可以尝试先升级到paddlenlp 2.3.4吗？如果不行的话，最好能把少量数据和你现在使用的全部代码发给我们，我们来测试一下

**Comment by zoeChen119** [comment]
> 可以尝试先升级到paddlenlp 2.3.4吗？如果不行的话，最好能把少量数据和你现在使用的全部代码发给我们，我们来测试一下

好的，我先试下升级
