### ISSUE TITLE
关于UIE中文训练数据集

### ISSUE THREAD

**Issue by JLtwoP** [PaddlePaddle/PaddleNLP#2891]
“基于ERNIE 3.0知识增强预训练模型，训练并开源了首个中文通用信息抽取模型UIE”
    
-- 请问UIE（中文）的训练数据是否开源？如果不开源，请问数据源和数据结构是否可以给出介绍？

**Comment by LemonNoel** [comment]
UIE训练数据主要是来在于公司内部数据标注，因为数据有一定的数据隐私性，不适合开源；数据结构和微调数据一致，包括了实体抽取、事件抽取、关系抽取、评论观点抽取、情感分类等数据。不同任务的schema构造可以参考下[UIE文档](https://github.com/PaddlePaddle/PaddleNLP/tree/0722c85fedaf2e1ef5e7a172bc53736c24bc6e7a/model_zoo/uie#3-%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)。

**Comment by JLtwoP** [comment]
> UIE训练数据主要是来在于公司内部数据标注，因为数据有一定的数据隐私性，不适合开源；数据结构和微调数据一致，包括了实体抽取、事件抽取、关系抽取、评论观点抽取、情感分类等数据。不同任务的schema构造可以参考下[UIE文档](https://github.com/PaddlePaddle/PaddleNLP/tree/0722c85fedaf2e1ef5e7a172bc53736c24bc6e7a/model_zoo/uie#3-%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)。
请问实体抽取，是传统的几大类，还是更细粒度的实体类别？

**Comment by wawltor** [comment]
> > UIE训练数据主要是来在于公司内部数据标注，因为数据有一定的数据隐私性，不适合开源；数据结构和微调数据一致，包括了实体抽取、事件抽取、关系抽取、评论观点抽取、情感分类等数据。不同任务的schema构造可以参考下[UIE文档](https://github.com/PaddlePaddle/PaddleNLP/tree/0722c85fedaf2e1ef5e7a172bc53736c24bc6e7a/model_zoo/uie#3-%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)。
> > 请问实体抽取，是传统的几大类，还是更细粒度的实体类别？

有更细粒度的实体类别

**Comment by JLtwoP** [comment]
> > > UIE训练数据主要是来在于公司内部数据标注，因为数据有一定的数据隐私性，不适合开源；数据结构和微调数据一致，包括了实体抽取、事件抽取、关系抽取、评论观点抽取、情感分类等数据。不同任务的schema构造可以参考下[UIE文档](https://github.com/PaddlePaddle/PaddleNLP/tree/0722c85fedaf2e1ef5e7a172bc53736c24bc6e7a/model_zoo/uie#3-%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)。
> > > 请问实体抽取，是传统的几大类，还是更细粒度的实体类别？
> 
> 有更细粒度的实体类别

方便透露下，更细粒度的实体类别，是人工设计和标注，还是有参考其他数据资料嘛？

**Comment by wawltor** [comment]
> > > > UIE训练数据主要是来在于公司内部数据标注，因为数据有一定的数据隐私性，不适合开源；数据结构和微调数据一致，包括了实体抽取、事件抽取、关系抽取、评论观点抽取、情感分类等数据。不同任务的schema构造可以参考下[UIE文档](https://github.com/PaddlePaddle/PaddleNLP/tree/0722c85fedaf2e1ef5e7a172bc53736c24bc6e7a/model_zoo/uie#3-%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)。
> > > > 请问实体抽取，是传统的几大类，还是更细粒度的实体类别？
> > 
> > 
> > 有更细粒度的实体类别
> 
> 方便透露下，更细粒度的实体类别，是人工设计和标注，还是有参考其他数据资料嘛？

在训练的过程中，主要的数据是不同领域的数据，例如互联网、医疗、金融、法律的数据，数据的来源主要是人工标注

**Comment by JLtwoP** [comment]
> 

了解，多谢！另有一个问题请教，因为缺乏标注人力，我正在调研无监督或者半监督的实体识别/信息抽取技术，这块您有什么意见？或是推荐的方法？

**Comment by wawltor** [comment]
> > 
> 
> 了解，多谢！另有一个问题请教，因为缺乏标注人力，我正在调研无监督或者半监督的实体识别/信息抽取技术，这块您有什么意见？或是推荐的方法？

目前我们的思路还是预训练模型 + 有监督训练的思路，通过不断提升预训练模型的效果和性能来减少模型落地门槛，同时结合有监督继续提升效果

**Comment by JLtwoP** [comment]
> > > 
> > 
> > 
> > 了解，多谢！另有一个问题请教，因为缺乏标注人力，我正在调研无监督或者半监督的实体识别/信息抽取技术，这块您有什么意见？或是推荐的方法？
> 
> 目前我们的思路还是预训练模型 + 有监督训练的思路，通过不断提升预训练模型的效果和性能来减少模型落地门槛，同时结合有监督继续提升效果

好的，多谢！

**Comment by Fea1n** [comment]
请问有哪些可用的schema呢，比如“时间”，“地点”，“赛事名称”什么的
