### ISSUE TITLE
pet.py 执行报错

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#2892]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- paddle 2.3.1
- paddlenlp 2.3.4
- cuda version 10.2

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
liunx python3.7
- 复现信息：如为报错，请给出复现环境、复现步骤
- 在PaddleNLP/examples/few_shot/pet目录下执行
python \
    pet.py \
        --task_name "tnews" \
        --device cpu \
    --pattern_id 0 \
        --save_dir ./tnews \
        --index 0 \
        --batch_size 16 \
        --learning_rate 1E-4 \
        --epochs 10 \
        --max_seq_length 30 \
        --language_model "ernie-1.0" \
    --rdrop_coef 0 \
报错
Traceback (most recent call last):
  File "pet.py", line 318, in <module>
    do_train(args)
  File "pet.py", line 213, in do_train
    loss.backward()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 293, in backward
    framework._dygraph_tracer())
IndexError: (OutOfRange) The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than 512, but received 512
  [Hint: Expected index_val < max_index, but received index_val:512 >= max_index:512.] (at /paddle/paddle/phi/kernels/funcs/scatter.h:206)

**Comment by tianxin1860** [comment]
你好，请问能否稳定复现这个错误？

**Comment by zhiyongLiu1114** [comment]
> 你好，请问能否稳定复现这个错误？

你好，可以稳定复现，每次执行都是这样的。我安装了paddnlp 2.3.0.dev 也是这样的

**Comment by wawltor** [comment]
> > 你好，请问能否稳定复现这个错误？
> 
> 你好，可以稳定复现，每次执行都是这样的。我安装了paddnlp 2.3.0.dev 也是这样的

有改变数据集之类的吗？

**Comment by zhiyongLiu1114** [comment]
> > > 你好，请问能否稳定复现这个错误？
> > 
> > 
> > 你好，可以稳定复现，每次执行都是这样的。我安装了paddnlp 2.3.0.dev 也是这样的
> 
> 有改变数据集之类的吗？

没有，脚本什么的全都没变

**Comment by wawltor** [comment]
您好，我这里执行相关命令是没有问题，下面是我环境配置
Paddle  Version: 2.3.1 
PaddleNLP Version: 2.3.4 

辛苦check一下paddle的版本

**Comment by Tygors** [comment]
您好，我也遇到了类似的问题，PET代码未作任何更改，windows系统下运行出错。
\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 293, in backward
    framework._dygraph_tracer())
IndexError: (OutOfRange) The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than 752, but received 752
  [Hint: Expected index_val < max_index, but received index_val:752 >= max_index:752.] (at ..\paddle/phi/kernels/funcs/scatter.h:206)
同一个环境下，GPU运行没问题，可以运行，选择CPU则报上面的错误。
当前版本为：
paddlenlp            2.4.0
paddlepaddle-gpu     2.3.1.post116
换了一台只有CPU的电脑，同样报上述错误。
试了：Paddle Version: 2.3.1 PaddleNLP Version: 2.3.4，故障依旧。
