### ISSUE TITLE
关于semantic-search上传txt格式文件中，多行换行的问题

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#2898]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/experimental/pipelines/pipelines/nodes/file_converter/txt.py
目前全都是手动回车为一个换行后，上传建立索引；
麻烦能否处理成上传txt文档，txt中难免有多个换行的情况，也不会影响数据的索引建立呢？

**Comment by w5688414** [comment]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/12107462/181449672-288f831b-ff92-4c33-ad26-8d3ea07ee737.png">


我试了一下，会出现很多空文本，不过影响不大
