### ISSUE TITLE
服务器无法联网，load_dataset()数据下载问题。

### ISSUE THREAD

**Issue by Chucy2020** [PaddlePaddle/PaddleNLP#2899]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

请问DuReader_yesno和DuReader_Robust数据集你们给的代码是由load_dataset()自动调用的，我现在服务器没有网络，请问该怎么处理？

**Comment by LemonNoel** [comment]
可以从原始代码的URL手动下载数据集再传到服务器上。
- [DuReader_Robust URL](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/dureader_robust.py#L34)是https://bj.bcebos.com/paddlenlp/datasets/dureader_robust-data.tar.gz 
- [DuReader_yesno URL](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/dureader_yesno.py#L36)是https://bj.bcebos.com/paddlenlp/datasets/dureader_yesno-data.tar.gz

**Comment by Chucy2020** [comment]
> 可以从原始代码的URL手动下载数据集再传到服务器上。
> 
> * [DuReader_Robust URL](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/dureader_robust.py#L34)是https://bj.bcebos.com/paddlenlp/datasets/dureader_robust-data.tar.gz
> * [DuReader_yesno URL](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/dureader_yesno.py#L36)是https://bj.bcebos.com/paddlenlp/datasets/dureader_yesno-data.tar.gz

好的，非常感谢大佬的回复与解答，后续有问题再请教你们。谢谢。
