### ISSUE TITLE
UIE 分类问题咨询

### ISSUE THREAD

**Issue by usstroot** [PaddlePaddle/PaddleNLP#2904]
您好，
1、我尝试用UIE解决一个多分类问题，如 ‘方向[上，下，左，右]' 的时候：
!python doccano.py \
    --prompt_prefix "方向" \
    --options "上" "下" "左" "右" 
发现结果中会打乱："prompt":’方向[上，下，左，右]' 或 "prompt":’方向[左，右，上，下]' 
最后预测的时候：定义 schema=方向[上，下，左，右]' 或 schema=[’方向[左，右，上，下]' ] 预测同一个句子，得出的结果不一样，请问这是一个bug嘛？
2、如果预测一个多分类问题 如 ‘方向[上，下，左，右]' ，其中某一句子不属于 上，下，左，右任一分类，应如何定义schema 表示出不属于其中的任一分类？

**Comment by linjieccc** [comment]
1.分类任务构造prompt的时候会随机打乱各个类别的顺序，否则模型容易对位置顺序过拟合；预测结果不一致可能是模型效果问题，请问您的训练数据有多少呢，一般分类任务需要的训练数据会多一些模型才能学好

2.可以试下增加一个类别，例如 schema=方向[上，下，左，右，未知]
