### ISSUE TITLE
tokenizer 和 model 的 vocab_size 不一致如何理解

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#2905]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
- 
![Uploading image.png…]()

**Comment by zhiyongLiu1114** [comment]
![Uploading image.png…]()
如图，
from paddlenlp.transformers.ernie.tokenizer import ErnieTokenizer
from paddlenlp.transformers.ernie.modeling import ErnieForMaskedLM
plm = ErnieForMaskedLM.from_pretrained('ernie-1.0')
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')
print(plm.ernie.config)
print(tokenizer.vocab_size)
上述plm 和 tokenizer 的 vocab_size 不一样，前者为18000，后者为17964.
请问下这个如何理解呢？谢谢

**Comment by zhiyongLiu1114** [comment]
![image](https://user-images.githubusercontent.com/47651345/181400615-7e1dc748-1c4d-419c-82c1-4ae78eab2be1.png)

**Comment by wawltor** [comment]
ERNIE 1.0在设计初期，主要是想vocab的预留了一些位置，如果有想新增一些token进行二次预训练，这个时候不需要进行模型结构的改变

**Comment by zhiyongLiu1114** [comment]
> ERNIE 1.0在设计初期，主要是想vocab的预留了一些位置，如果有想新增一些token进行二次预训练，这个时候不需要进行模型结构的改变

收到，谢谢
