### ISSUE TITLE
关于UIE fintune 之后效果不如zero-shot的问题

### ISSUE THREAD

**Issue by wireless911** [PaddlePaddle/PaddleNLP#2906]
我在医疗实体关系抽取任务中采用了开源数据集对UIE进行了测试（我的评价指标采用的是对spo三元组计算P，R，F1）：

    1. TaskFlow zero-shot  F1：0.2
    2. few-shot  F1：0.19

fintune 之后结果反而更差一点儿，训练阶段在dev开发集（SpanEvaluator）最好的F1值为0.547 ，麻烦帮我看下

版本、环境信息
paddlenlp：2.3.4 
paddle：2.3.0
环境：aistudio

**Comment by linjieccc** [comment]
@wireless911 您好，能否提供下AI Studio的项目地址并设置为公开

**Comment by wireless911** [comment]
感谢回复，我的aistudio 的地址：https://aistudio.baidu.com/aistudio/projectdetail/4374394?shared=1

**Comment by linjieccc** [comment]
似乎没有数据转换和训练部分的代码，请问您的训练/验证集是通过doccano.py进行构造的么

**Comment by wireless911** [comment]
> 似乎没有数据转换和训练部分的代码，请问您的训练/验证集是通过doccano.py进行构造的么

我有一个finetune.ipynb 的文件，你只能看到main.ipynb吗

**Comment by linjieccc** [comment]
请问目前训练集正负样本的比例是多少，从预测结果来看错误召回比较多，可以适当增加负样本的比例
