### ISSUE TITLE
自建问答模型的数据集

### ISSUE THREAD

**Issue by hanfu** [PaddlePaddle/PaddleNLP#2913]
你好 我试图在问答模型中使用自建数据集
数据集训练集为`(context, question, start, end)`, 测试集为`(context, question) `
我尝试了`paddle.io.Dataset`和`paddlenlp.datasets.MapDataset`, 都会在传入`paddle.io.DataLoader`的时候失败
可以提供一个案例么， 从`[(context,question,start,end)...]`列表对开始 步步建立数据集

我找到的教程要么是内置dataset 要么就是其他任务的，主要是视觉任务 我水平有限参考不出来
感谢

**Comment by guoshengCS** [comment]
> 都会在传入paddle.io.DataLoader的时候失败

请问这个报错是怎样的呢，另外之前有一个自建问答模型的数据集的issue #2770 可以参考下
