### ISSUE TITLE
想要提交一个prompt learning 的 pr

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#2915]
您好，可以合并下[pr](https://github.com/PaddlePaddle/PaddleNLP/pull/2875)吗？
我想要提交一个支持prompt learning的pr，但是依赖上述这个方法

**Comment by chenxiaozeng** [comment]
感谢您的贡献，依赖pr已经合入了~ 我们最近也在做Prompt learning相关工作，期待和您有进一步的技术交流，这是我们的联系方式：邮箱 paddlenlp@baidu.com，方便的话可以留下您的联系方式，期待交流！

**Comment by zhiyongLiu1114** [comment]
> 感谢您的贡献，依赖pr已经合入了~ 我们最近也在做Prompt learning相关工作，期待和您有进一步的技术交流，这是我们的联系方式：邮箱 [paddlenlp@baidu.com](mailto:paddlenlp@baidu.com)，方便的话可以留下您的联系方式，期待交流！

发邮件被拒了。。。。
由于此组限定只接收经过身份验证的发件人所发送的邮件，无法传递你的邮件。如果问题仍然存在，请与你的电子邮件管理员联系。
我的邮箱 liuzhiyong1995@163.com

**Comment by wawltor** [comment]
您好，我们收到您的邮件，根据你的邮件有以下问题可以探讨了

1. issue #2892 执行报错
   我们线下尝试了一下，是没有问题，您可以尝试升级一下Paddle的版本
2. paddle 框架对tensor的切片支持
    目前Paddle对tensor的切片支持还不是很完备，我们在Paddle 2.4版本支持类似操作，您可以手动slice一下tensor，具体的API可以见 
   https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/slice_cn.html#slice 
3. optimizer 没有生效
    是否提供一下全部代码给我们尝试一下，目前提供的代码不太好定位问题

**Comment by zhiyongLiu1114** [comment]
> 您好，我们收到您的邮件，根据你的邮件有以下问题可以探讨了
> 
> 1. issue [pet.py 执行报错 #2892](https://github.com/PaddlePaddle/PaddleNLP/issues/2892) 执行报错
>    我们线下尝试了一下，是没有问题，您可以尝试升级一下Paddle的版本
> 2. paddle 框架对tensor的切片支持
>    目前Paddle对tensor的切片支持还不是很完备，我们在Paddle 2.4版本支持类似操作，您可以手动slice一下tensor，具体的API可以见
>    https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/slice_cn.html#slice
> 3. optimizer 没有生效
>    是否提供一下全部代码给我们尝试一下，目前提供的代码不太好定位问题

您好，optimizer 没有生效这个问题我定位应该是template 和 verbalizer 没有加到模型当中，不是模型的参数，导致梯度回传失败，没有梯度值。这个我后续解决下看。

**Comment by wawltor** [comment]
目前问题已私下沟通解决，暂时关闭该issue，如有问题可以重新打开该issue。
