### ISSUE TITLE
UIE 多分类问题咨询

### ISSUE THREAD

**Issue by Lavender-SK** [PaddlePaddle/PaddleNLP#2919]
您好，
我准备用UIE解决一个多分类or多标签问题，但是标签类别特别多，有100多类，如果将prompt构造成：
XX分类[类别1，类别2，类别3，...]，那么整个prompt的长度就会非常长，甚至达到或超过512，不知道有没有好的解决方法

**Comment by wawltor** [comment]
如果是这样的场景就不太建议使用UIE来做多标签分类，你可以尝试使用我们下面的链接来说使用多标签分类  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification
