### ISSUE TITLE
请问cg policy 多轮对话策略模型开源了吗？没开源的话，想许愿一下

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2920]
业务中用到多轮对话，只有plato模型的单轮对话无法满足要求，看b站你们的录播，上下两层的知识图谱的结合，看着效果真的很好，想探索探索，许愿开源一下

**Comment by guoshengCS** [comment]
感谢支持，后续如果开源的话会在这里进行同步~

另外对于当前已开源模型的话，也可以试下将多轮的内容拼起来作为模型输入，tokenizer是可以接受list输入的 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/unified_transformer/tokenizer.py#L464 ，如PLATO-XL这里的用法 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/plato-xl/infer.py#L144
