### ISSUE TITLE
关于用uie模型微调后生成的模型文件中的static文件

### ISSUE THREAD

**Issue by uncleunclelu** [PaddlePaddle/PaddleNLP#2921]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
你好，想问一下用uie模型微调后生成的模型文件中的static文件的作用是什么，里面包含inference.pdiparams，inference.pdiparams.info，inference.pdmodel这三个文件

**Comment by wawltor** [comment]
在UIE训练的过程中使用的是动态图训练，在部署的过程中将动态图生成了静态图模型文件，静态图预测的速度会有很大的提升，静态图模型文件就是在static目录下

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，有疑问的话可以再次打开issue。
