### ISSUE TITLE
UIE英文模型的事件抽取任务

### ISSUE THREAD

**Issue by DraymondHIT** [PaddlePaddle/PaddleNLP#2922]
您好，请问可以加入UIE事件抽取（Event Extraction）的英文预训练模型吗？

**Comment by linjieccc** [comment]
目前英文版本还没有加入事件抽取的数据，预计在下一个版本提供支持，欢迎持续关注

**Comment by wawltor** [comment]
暂时关闭该issue，如有问题可以重新打开该issue。
