### ISSUE TITLE
plato-xl是不是只能适用于英文对话，无法用于中文对话？

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#2923]
如题

**Comment by wawltor** [comment]
目前开源出来的plato-xl是英文版本的，plato-xl中文版本目前还没有开源计划

**Comment by jiweizhangxu** [comment]
> 目前开源出来的plato-xl是英文版本的，plato-xl中文版本目前还没有开源计划

英文版本的plato-xl有什么办法能调整的适用于中文吗？

**Comment by wawltor** [comment]
> > 目前开源出来的plato-xl是英文版本的，plato-xl中文版本目前还没有开源计划
> 
> 英文版本的plato-xl有什么办法能调整的适用于中文吗？

这个看起来只能把输入翻译成英文，再把输出结果翻译成中文
