### ISSUE TITLE
UIE模型如何添加新字符到vocab.txt中，并重新训练

### ISSUE THREAD

**Issue by xmadog** [PaddlePaddle/PaddleNLP#2927]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
     paddlepaddle-gpu           2.2.0.post111
     paddlenlp                         2.3.4
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
      linux，python3.6
- 复现信息：
采用uie模型做信息提取时，发现对“HRB400Φ16"这个词的提取结果有误。
预期结果为:
'HRB400Φ16' = {'牌号':'HRB400','公称直径':'Φ16'}
实际训练后的预测结果:
'HRB400Φ16' = {'牌号':'HRB400Φ16','公称直径':'HRB400Φ16'}

阅读这部分源代码之后，发现是wordpiece的分词的问题，调用代码得到结果如下：
标准分类/黑色及有色金属/工字钢 钢筋 HRB400Φ16 品牌:河北鑫达;单位:吨;
分词结果 = ['标', '准', '分', '类', '/', '黑', '色', '及', '有', '色', '金', '属', '/', '工', '字', '钢', '钢', '筋', '[UNK]', '品', '牌', ':', '河', '北', '鑫', '达', ';', '单', '位', ':', '吨', ';']
发现‘HRB400Φ16’不能被wordpiece分词器处理，最后被识别为'[UNK]'
之后继续定位问题，发现对应的vocab.txt中确实没有'##Φ'这样的子词，导致wordpiece不能正常分词

因此目前这种情况如何处理，或者如何添加新字符到vocab.txt，并重新训练当前模型？多谢

**Comment by ZHUI** [comment]
你好，非常抱歉，这个确实是ernie词表带来的类似问题。这边建议您，可以
1. 对特殊字符之间，添加空格符号，单独表示这个符号`HRB400 Φ 16`
2. 像您提到的，添加 `##Φ` 字符，使用 `Φ`字符的 embedding 初始化，可以不用重新训练。

**Comment by xmadog** [comment]
> 你好，非常抱歉，这个确实是ernie词表带来的类似问题。这边建议您，可以
> 
> 1. 对特殊字符之间，添加空格符号，单独表示这个符号`HRB400 Φ 16`
> 2. 像您提到的，添加 `##Φ` 字符，使用 `Φ`字符的 embedding 初始化，可以不用重新训练。

感谢 @ZHUI 的解答，按照您的建议，首先将 ##Φ添加到了vocab.txt中，观察到分词正确了，但是uie预测结果还是不正确。
怀疑应该是分词导致了特征改变，所以对uie进行迁移训练，之后再次对这个bad case进行预测，得到了正确结果。问题解决，再次感谢
