### ISSUE TITLE
请问有没有遇到flask+gunicorn+UIE 基于docker封装服务的请求响应时间是本地gunicorn直接起的响应时间的1倍？

### ISSUE THREAD

**Issue by xsqiii** [PaddlePaddle/PaddleNLP#2928]
1）PaddleNLP 2.3.4，PaddlePaddle2.3.1
2）系统环境：MacOS，python3.8

基于Flask + gunicorn + UIE框架（uie-nano抽取自定义8种实体类型）
本地gunicorn直接起服务，一句的响应时间约500ms；
配置一致，build docker后进行调用，同一句的响应时间约1s。

请问有遇到过这种问题吗？

**Comment by wawltor** [comment]
测试了一下，并没有出现这个问题，不太确定是不是docker的网络的设置是否有问题？

**Comment by KyleWang-Hunter** [comment]
> 1）PaddleNLP 2.3.4，PaddlePaddle2.3.1 2）系统环境：MacOS，python3.8
> 
> 基于Flask + gunicorn + UIE框架（uie-nano抽取自定义8种实体类型） 本地gunicorn直接起服务，一句的响应时间约500ms； 配置一致，build docker后进行调用，同一句的响应时间约1s。
> 
> 请问有遇到过这种问题吗？
我也有这样的问题，使用docker部署之后的推理速度变慢。

**Comment by xxllp** [comment]
我擦 坑啊

**Comment by KyleWang-Hunter** [comment]
> 我擦 坑啊

如何解决，大佬 ？

**Comment by xxllp** [comment]
> > 我擦 坑啊
> 
> 如何解决，大佬 ？

我还没上手部署呢 放弃了

**Comment by xxllp** [comment]
> > > 我擦 坑啊
> > 
> > 
> > 如何解决，大佬 ？
> 
> 我还没上手部署呢 放弃了

我最终选择用pytorch版本的uie 来训练部署
