### ISSUE TITLE
CNN文本分类出错

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/PaddleNLP#2929]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16698950/182100088-c6e570f4-0217-48c6-9be9-b1bbc5e07196.png">

**Comment by wawltor** [comment]
> <img alt="image" width="1439" src="https://user-images.githubusercontent.com/16698950/182100088-c6e570f4-0217-48c6-9be9-b1bbc5e07196.png">

{"text": "落户", "label": "1"}
{"text": "征兵政策", "label": "1"}
{"text": "土地政策", "label": "1"}
{"text": "企业合并", "label": "0"}
{"text": "社保卡怎么用", "label": "0"}
{"text": "森林防火命令", "label": "1"}
{"text": "全民健身计划", "label": "1"}
{"text": "疫情防控政策", "label": "1"}

停用词表： https://github.com/goto456/stopwords

**Comment by lugimzzz** [comment]
文本长度较短，jieba分词后序列长度短于CNN模型中卷积核大小（目前设为3），可以将CNN模型中卷积核大小设为1或2。具体代码修改[model.py 358行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/rnn/model.py#L358)

`ngram_filter_sizes=(3, )  -> ngram_filter_sizes=(1, )`

![image](https://user-images.githubusercontent.com/63761690/182122221-4af06856-3be4-404b-84a9-cba85b205e96.png)

**Comment by hongdd** [comment]
问题已解决，谢谢
