### ISSUE TITLE
PretrainedTokenizer在处理pandas数据时能否并行？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#293]

**Comment by ZeyuChen** [comment]
@illcat 可否提供下你想使用的例子，目前还不太理解处理padnas并行的使用样例和目的。

**Comment by ghost** [comment]
目前paddlenlp的tokenizer不支持python多线程

**Comment by guoshengCS** [comment]
目前paddlenlp数据处理部分确实没有对多线程做太多支持，如果是像[这里这样](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/run_glue.py#L267)使用的`dataset.map(lazy=True,)`的话，可以考虑先使用DataLoader的多进程支持，将`num_workers`设置为进程数看下速度呢
<img width="637" alt="image" src="https://user-images.githubusercontent.com/14105589/115677532-26af5480-a383-11eb-9f2b-0a5737e9e4a0.png">


dataset的多线程支持我们也看下，多谢支持与建议~

**Comment by ghost** [comment]
谢谢，我自己搞了个分词器
