### ISSUE TITLE
UIE支持一对多标注吗？

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleNLP#2932]
doccano做UIE的信息提取标注，如果一句话是“主要分布在广东，在四川、云南、西藏也有分布，偶见湖北、湖南一带”，我想要提取的信息是分布省份，这样我做标注的时候，label可以一对多么，比如{"分布省份":['广东','四川','云南','西藏','湖南','湖北']}，还是只能以这句话为一个整体提取？

**Comment by wawltor** [comment]
UIE可以做到一对多标注
