### ISSUE TITLE
关于解语和Lac哪个工具比较强的问题？

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#2942]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：pp2.3
2）系统环境：linux
我想问一下解语和Lac在分词和专名识别方面哪个比较强大

**Comment by wawltor** [comment]
解语和LAC属于不同粒度的分词和NER工具，LAC的粒度更粗，解语是更细粒度的NER工具，包含了91种标签；
目前大家使用的过程中更偏向于更细粒度的NER和分词方式，这个方面解语的效果更好，但是预测的速度相对LAC速度慢点
