### ISSUE TITLE
模型下载问题

### ISSUE THREAD

**Issue by weichen12345** [PaddlePaddle/PaddleNLP#2943]
PaddleNLP 2.3.4，PaddlePaddle2.3.1
macos python 3.8
您好，加载预训练模型卡在- We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'uie-base' 然后程序就自动停掉了。

**Comment by weichen12345** [comment]
hao

**Comment by foreverxyhj** [comment]
我也遇到了类似的问题，想问一下是如何解决的？
详细情况：
代码
from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

报错：
在Jupyter notebook跑的时候显示内核挂掉了
放到Pycharm跑，停在We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load …… uie-base这一步，然后Process finished with exit code -1073741819 (0xC0000005)
想问一下这种问题如何解决。
