### ISSUE TITLE
UIE预训练流程

### ISSUE THREAD

**Issue by Lavender-SK** [PaddlePaddle/PaddleNLP#2947]
您好，请问下UIE的预训练流程是怎样的？
    1. 是将所有的标注数据混合在一起训练么？如果是的话，如何避免负迁移的情况发生？
    2. 实体关系抽取，或者事件抽取的数据会拆分成多条标注数据？
    3. 有可能开放预训练代码么？

**Comment by wawltor** [comment]
您好，
1. 可以一起训练，这样说到负迁移具体是什么含义了？ 
2. 实体抽取、事件抽取可以在一条标注数据里面，但是训练的时候会拆成多条数据来训练
3. UIE本身来说是没有预训练，底座是依赖于ERNIE-3.0系列的模型，ERNIE系列的模型预训练地址: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0

**Comment by Lavender-SK** [comment]
我提到的多个数据集混合是指不同领域、不同任务的数据混合，比如A领域的NER任务-数据集AA，B领域的NER任务-数据集BB，C领域的分类任务-数据集CC，如果训练的时候将AA、BB、CC混合在一起，会不会互相有影响，影响模型性能

**Comment by linjieccc** [comment]
如果不同NER任务的标签体系不冲突的话基本影响不大，可以混合训练

**Comment by Lavender-SK** [comment]
看https://github.com/PaddlePaddle/PaddleNLP/issues/2891 这里的介绍：“在训练的过程中，主要的数据是不同领域的数据，例如互联网、医疗、金融、法律的数据，数据的来源主要是人工标注”
我的理解不同领域的NER标签还是很不一样的，比如医疗和法律肯定会不同，那你们在训练的时候也是混合在一起训练的？还是其他训练策略？

**Comment by wawltor** [comment]
> 看#2891 这里的介绍：“在训练的过程中，主要的数据是不同领域的数据，例如互联网、医疗、金融、法律的数据，数据的来源主要是人工标注” 我的理解不同领域的NER标签还是很不一样的，比如医疗和法律肯定会不同，那你们在训练的时候也是混合在一起训练的？还是其他训练策略？

没有特殊的策略，直接拿这些样本一起混合训练

**Comment by kevinuserdd** [comment]
> 您好，
> 
> 1. 可以一起训练，这样说到负迁移具体是什么含义了？
> 2. 实体抽取、事件抽取可以在一条标注数据里面，但是训练的时候会拆成多条数据来训练
> 3. UIE本身来说是没有预训练，底座是依赖于ERNIE-3.0系列的模型，ERNIE系列的模型预训练地址: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0

UIE本身没有预训练？？不对吧，论文里面不是提到用的wiki数据预训练的么

**Comment by wanghia** [comment]
可以理解为uie-base是在ERNIE-3.0基础上基于大量的不同领域的数据训练得到的吗？这个训练的过程是不是和微调一致呢？主要就是start_loss+end_loss?
