### ISSUE TITLE
关于semantic-search的web服务页面搜索框交互问题

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#2949]
（1）semantic-search搭建起web服务后，其前端页面搜索框中：总是会在输入下一次搜索内容后，跳回上一次的搜索输入内容。。
请问是什么情况？该如何解决？

（2）btw：再就是有个小小的建议期望：
搜索框能否通过js还是什么办法  实现我点击搜索框，默认的框内文字就不显示了；
![c9ab326339e3b57e1477dc41a2fe4de](https://user-images.githubusercontent.com/100854336/182517296-4046e9f2-4116-4782-b6dc-a78dbaf54374.png)
因为，现在这个在代码中设定的框内默认内容  需要人手动删。

上述（1）、（2）在实际业务场景中交互体验频率会比较高，看老师们有什么好的解决办法，感谢！

**Comment by w5688414** [comment]
这是pr，看能不能满足您的需求。 https://github.com/PaddlePaddle/PaddleNLP/pull/2954
