### ISSUE TITLE
question_answering 使用指定的其他model失败

### ISSUE THREAD

**Issue by fallbernana123456** [PaddlePaddle/PaddleNLP#2951]
在Taskflow("question_answering")中会自动使用gpt-cpm-large-cn ，但是 由于太大了Out of memory error on GPU，也不支持多个GPU，　所以我找到还有一个
gpt-cpm-small-cn-distill 模型，但是通过model参数指定，发现配置里没有。我该如果配置才能使用gpt-cpm-small-cn-distill？

**Comment by wawltor** [comment]
目前Taskflow里面还不支持gpt-cpm-small-cn-distill，我们可以把这个放到计划列表上
