### ISSUE TITLE
最近在学习nlp客户机器人，在ai studio上有不少案例，但发觉通用性不强，有没有简单点的对话机器人案例

### ISSUE THREAD

**Issue by mjx18** [PaddlePaddle/PaddleNLP#2955]
最近在学习nlp客户机器人，在ai studio上有不少案例，但发觉通用性不强，有没有简单点的对话机器人案例，我只要上传txt或excel问答，经过短信训练，马上就能生成对话了呢？多谢。

**Comment by joey12300** [comment]
@mjx18 你好，这里有个基于UnifiedTransformer的人机对话示例，你看看是否可以解决你的问题？如果数据量小、对话简单的话，可以尝试使用参数量较少的`plato-mini`预训练模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer

**Comment by mjx18** [comment]
好的，多谢。




--
发自我的网易邮箱手机智能版



在 2022-08-04 10:43:05，"Jack Zhou" ***@***.***> 写道：


@mjx18 你好，这里有个基于UnifiedTransformer的人机对话示例，你看看是否可以解决你的问题？如果数据量小、对话简单的话，可以尝试使用参数量较少的plato-mini预训练模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer
