### ISSUE TITLE
UIE微调速度异常慢

### ISSUE THREAD

**Issue by 18140663659** [PaddlePaddle/PaddleNLP#2957]
1）PaddleNLP 2.2，PaddlePaddle2.3.4
2）系统环境：Ubuntu 18.04.1 LTS，python3.6.4

使用官网提供的UIE微调代码，cpu下运行特别慢，一个晚上没跑完10epoch

**Comment by ZHUI** [comment]
请问有GPU资源吗？CPU跑可能会慢一些。

**Comment by 18140663659** [comment]
> 请问有GPU资源吗？CPU跑可能会慢一些。

打算切gpu试一下，但是cpu跑的速度也过于慢了，怀疑哪里有问题

**Comment by ZHUI** [comment]
可能，使用的cpu线程数有点少，可以看一下 cpu 利用率。

**Comment by hjing100** [comment]
是的 很慢，一晚上没盘10个epoch

**Comment by linjieccc** [comment]
uie-base模型大一些CPU下会比较慢，建议在GPU环境下进行微调，CPU下推荐用tiny系列模型

<img width="544" alt="image" src="https://user-images.githubusercontent.com/40840292/182766268-c4005bcb-607d-4573-9c6b-4b125eacccb7.png">

**Comment by 18140663659** [comment]
gpu下训练正常

**Comment by 18140663659** [comment]
已解决

**Comment by ghost** [comment]
> 请问有GPU资源吗？CPU跑可能会慢一些。

请问一下，如果使用GPU的话，uie-base 预计会占用多少显存？

我用 **10** 块 NVIDIA Tesla K80 都跑不起来 uie-base，是不是我的操作哪里有问题？

```bash
python3 -u -m paddle.distributed.launch --gpus "0,1,2,3,4,5,6,7,8,9" \
  finetune.py \
  --learning_rate 1e-5 \
  --batch_size 16 \
  --max_seq_len 512 \
  --num_epochs 50 \
  --model uie-base \
  --seed 1000 \
  --logging_steps 10 \
  --valid_steps 100 \
  --device gpu \
  --save_dir /mnt/ckpt/ \
  --train_path /mnt/CMeEE-PaddleNLP-0.8-0.2-0.2/train.txt \
  --dev_path /mnt/CMeEE-PaddleNLP-0.8-0.2-0.2/dev.txt
```

**Comment by ghost** [comment]
> gpu下训练正常

请问一下，您使用了几块什么型号的GPU？
