### ISSUE TITLE
和model_zero/uie有什么不同

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleNLP#2960]
请问，examples/information_extraction/duuie中的训练测试代码和项目中model_zero/uie下面的训练有什么不同？

**Comment by wawltor** [comment]
examples/information_extraction/duuie 这个版本是UIE的paper的版本，通过生成模型来进行信息抽取，偏向于学术；
model_zoo/uie是通过大量语料微调出来的模型，使用的是阅读理解式的抽取模型，在工业使用效果相对好

**Comment by kevinuserdd** [comment]
> examples/information_extraction/duuie 这个版本是UIE的paper的版本，通过生成模型来进行信息抽取，偏向于学术； model_zoo/uie是通过大量语料微调出来的模型，使用的是阅读理解式的抽取模型，在工业使用效果相对好

请问有torch版本的uie预训练模型吗？  目前找的uie-base和uie-tiny预训练模型都是在paddle框架里

**Comment by wawltor** [comment]
> > examples/information_extraction/duuie 这个版本是UIE的paper的版本，通过生成模型来进行信息抽取，偏向于学术； model_zoo/uie是通过大量语料微调出来的模型，使用的是阅读理解式的抽取模型，在工业使用效果相对好
> 
> 请问有torch版本的uie预训练模型吗？ 目前找的uie-base和uie-tiny预训练模型都是在paddle框架里

您好，目前UIE只有paddle的开源版本。

**Comment by kevinuserdd** [comment]
> > > examples/information_extraction/duuie 这个版本是UIE的paper的版本，通过生成模型来进行信息抽取，偏向于学术； model_zoo/uie是通过大量语料微调出来的模型，使用的是阅读理解式的抽取模型，在工业使用效果相对好
> > 
> > 
> > 请问有torch版本的uie预训练模型吗？ 目前找的uie-base和uie-tiny预训练模型都是在paddle框架里
> 
> 您好，目前UIE只有paddle的开源版本。

请问一下，论文里提到的方法，包括使用了wiki数据做预训练，这个生成的预训练模型是哪个？？ 难道uie-base预训练模型的任务，不是使用论文中的方法？？

**Comment by wawltor** [comment]
> > > > examples/information_extraction/duuie 这个版本是UIE的paper的版本，通过生成模型来进行信息抽取，偏向于学术； model_zoo/uie是通过大量语料微调出来的模型，使用的是阅读理解式的抽取模型，在工业使用效果相对好
> > > 
> > > 
> > > 请问有torch版本的uie预训练模型吗？ 目前找的uie-base和uie-tiny预训练模型都是在paddle框架里
> > 
> > 
> > 您好，目前UIE只有paddle的开源版本。
> 
> 请问一下，论文里提到的方法，包括使用了wiki数据做预训练，这个生成的预训练模型是哪个？？ 难道uie-base预训练模型的任务，不是使用论文中的方法？？

uie-base的模型结构和论文版本中的结果是一致的，uie-base的底座预训练模型是ernie-3.0的模型，论文版本的使用在examples/information_extraction/duuie

**Comment by wawltor** [comment]
暂时关闭该issue，如有问题可以重新该issue。
