### ISSUE TITLE
使用UIE进行事件抽取的训练数据格式的要求是什么，可否给个例子说明一下

### ISSUE THREAD

**Issue by mfxss** [PaddlePaddle/PaddleNLP#2961]
请问手上已经有事件抽取的语料，需要处理成什么样的格式才能进行fine tune。
doccano_ext.json处理后的结果，也只是实体标注的样例。

**Comment by linjieccc** [comment]
您好，事件抽取的数据格式可以参考这个例子

```text
{
    "id": 39, 
    "text": "泰安今早发生2.9级地震！靠近这个国家森林公园。", 
    "relations": [
        {
            "id": 23, 
            "from_id": 58, 
            "to_id": 57, 
            "type": "震级"
        }, 
        {
            "id": 24, 
            "from_id": 58, 
            "to_id": 56, 
            "type": "时间"
        }
    ], 
    "entities": [
        {
            "id": 56, 
            "start_offset": 2, 
            "end_offset": 4, 
            "label": "时间"
        }, 
        {
            "id": 57, 
            "start_offset": 6, 
            "end_offset": 10, 
            "label": "等级"
        }, 
        {
            "id": 58, 
            "start_offset": 10, 
            "end_offset": 12, 
            "label": "地震触发词"
        }
    ]
}
```

**Comment by mfxss** [comment]
> 您好，事件抽取的数据格式可以参考这个例子
> 
> ```
> {
>     "id": 39, 
>     "text": "泰安今早发生2.9级地震！靠近这个国家森林公园。", 
>     "relations": [
>         {
>             "id": 23, 
>             "from_id": 58, 
>             "to_id": 57, 
>             "type": "震级"
>         }, 
>         {
>             "id": 24, 
>             "from_id": 58, 
>             "to_id": 56, 
>             "type": "时间"
>         }
>     ], 
>     "entities": [
>         {
>             "id": 56, 
>             "start_offset": 2, 
>             "end_offset": 4, 
>             "label": "时间"
>         }, 
>         {
>             "id": 57, 
>             "start_offset": 6, 
>             "end_offset": 10, 
>             "label": "等级"
>         }, 
>         {
>             "id": 58, 
>             "start_offset": 10, 
>             "end_offset": 12, 
>             "label": "地震触发词"
>         }
>     ]
> }
> ```
{"content": "泰安今早发生2.9级地震！靠近这个国家森林公园。", "result_list": [{"text": "今早", "start": 2, "end": 4}], "prompt": "时间"}
{"content": "泰安今早发生2.9级地震！靠近这个国家森林公园。", "result_list": [{"text": "2.9级", "start": 6, "end": 10}], "prompt": "等级"}
{"content": "泰安今早发生2.9级地震！靠近这个国家森林公园。", "result_list": [{"text": "地震", "start": 10, "end": 12}], "prompt": "地震触发词"}
{"content": "泰安今早发生2.9级地震！靠近这个国家森林公园。", "result_list": [{"text": "2.9级", "start": 6, "end": 10}], "prompt": "地震的震级"}
{"content": "泰安今早发生2.9级地震！靠近这个国家森林公园。", "result_list": [{"text": "今早", "start": 2, "end": 4}], "prompt": "地震的时间"}
您好，使用脚本处理后得到了这个格式的数据，但是我发现貌似不支持同一个句子中有多个同类触发词的情况。因为在这里，触发词与实体之间的关系，是以“...的...”的promopt来表示的，如果出现多个"地震的触发词",要怎么表示如果不同的触发词与实体之间的关系呢？需要处理成什么样的格式呢？谢谢

**Comment by linjieccc** [comment]
多个同类型事件共用同一个触发词的情况目前UIE还不支持，这种情况可以看下能否用关系抽取的方式来做，修改下第一阶段的抽取目标
