### ISSUE TITLE
每次导出的onnx测试精度不一样

### ISSUE THREAD

**Issue by pengaoao** [PaddlePaddle/PaddleNLP#2966]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！
版本信息：
paddle-bfloat           0.1.7
paddle2onnx             0.9.8
paddlefsl               1.1.0
paddlenlp               2.3.4
paddlepaddle            2.3.1
导出静态图脚本：
    tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh")
    model = AutoModelForSequenceClassification.from_pretrained("ernie-3.0-base-zh")
    model.eval()
    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(shape=[-1, -1],
                                    dtype="int64"),
            paddle.static.InputSpec(shape=[-1, -1],
                                    dtype="int64"),
        ]
    )

    save_path = os.path.join("./ernie/", "inference")
    paddle.jit.save(model, save_path)

导出onnx:
paddle2onnx --model_dir ernie/ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file model.onnx --opset_version 11 --enable_onnx_checker 1
测试精度：
python3 infer.py --task_name csl --model_path model.onnx --use_onnxruntime 1 --device cpu --batch_size 8 --model_name_or_path ernie-3.0-base-zh
虽然模型我没微调，但是上述流程每次测出来的精度为啥不一样呢？也没指定数据集，数据集应该是脚本里面默认的
dev_ds = ppnlp_load_dataset('clue', args.task_name, splits='dev')这行指定的clue
测试四次打印分别为：
task name: csl, acc: 0.468
task name: csl, acc: 0.49966666666666665
task name: csl, acc: 0.4483333333333333
task name: csl, acc: 0.5793333333333334

为啥差距这么大呢？

**Comment by pengaoao** [comment]
是否是我导出onnx流程有误？ 如果不是为啥每次导出的onnx，测试acc不同？

**Comment by wawltor** [comment]
这个是因为AutoModelForSequenceClassification的模型中存在一个linear层，这个层每次初始化的时候都是随机初始化参数的，所以导致你导出的模型每次都不同；比较合理的方式，你在AutoModelForSequenceClassification加载数据进行微调，然后保存一个固定的参数，才能保证导出的模型是一致的
<img width="690" alt="image" src="https://user-images.githubusercontent.com/16698950/182818787-da4a119f-8200-49c9-8858-6b663f2ed046.png">

**Comment by pengaoao** [comment]
> 这个是因为AutoModelForSequenceClassification的模型中存在一个linear层，这个层每次初始化的时候都是随机初始化参数的，所以导致你导出的模型每次都不同；比较合理的方式，你在AutoModelForSequenceClassification加载数据进行微调，然后保存一个固定的参数，才能保证导出的模型是一致的 <img alt="image" width="690" src="https://user-images.githubusercontent.com/16698950/182818787-da4a119f-8200-49c9-8858-6b663f2ed046.png">

好的，感谢
