### ISSUE TITLE
在aistudio上运行样例的时候，提示information_extraction不在Taskflow list中

### ISSUE THREAD

**Issue by estuday** [PaddlePaddle/PaddleNLP#2967]
`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_182/1763430471.py in <module>
      3 
      4 schema = ['时间', '选手', '赛事名称']
----> 5 ie = Taskflow('information_extraction', schema=schema)
      6 pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py in __init__(self, task, model, device_id, **kwargs)
    182     def __init__(self, task, model=None, device_id=0, **kwargs):
    183         assert task in TASKS, "The task name:{} is not in Taskflow list, please check your task name.".format(
--> 184             task)
    185         self.task = task
    186         if model is not None:

AssertionError: The task name:information_extraction is not in Taskflow list, please check your task name.`

**Comment by estuday** [comment]
paddlenlp的版本是2.2.6

**Comment by wawltor** [comment]
> paddlenlp的版本是2.2.6

升级一下paddlenlp的版本到最新的2.3.5版本

**Comment by wawltor** [comment]
暂时关闭该issue，如有问题可以重新该issue。
