### ISSUE TITLE
 ErnieModel 如何冻结梯度

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#297]
我的模型中包含一个ernie，我使用self.ernie.stop_gradient = True 貌似无效

**Comment by wawltor** [comment]
self.ernie是一个module，在module设置stop_gradient是无效的；
如果想冻结参数，最直接的办法的是在optimizer上进行处理，可以过滤一下parameter，不让parameter进行更新，例如下图
<img width="633" alt="图片" src="https://user-images.githubusercontent.com/16698950/115648885-d7ecc500-a358-11eb-8852-34590ea5de76.png">
model.parameters是一个list，可以通过parameters的name进行一定的过滤, 例如
```python
     [ p for p in model.parameters() if 'linear' not in p.name]  # 这里就可以过滤一下linear层，具体过滤策略可以根据需要来设定
```

**Comment by guoshengCS** [comment]
除了上面的方法也可以试下为ernie输出的tensor设置stop_gradient为True试下。可以使用[register_forward_post_hook](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/dygraph/layers/Layer_cn.html#register_forward_post_hook)按照下面的方式试下：

```
def forward_post_hook(layer, input, output):
    output.stop_gradient=True

self.ernie.register_forward_post_hook(forward_post_hook)
```

**Comment by ZeyuChen** [comment]
> self.ernie是一个module，在module设置stop_gradient是无效的；
> 如果想冻结参数，最直接的办法的是在optimizer上进行处理，可以过滤一下parameter，不让parameter进行更新，例如下图
> <img alt="图片" width="633" src="https://user-images.githubusercontent.com/16698950/115648885-d7ecc500-a358-11eb-8852-34590ea5de76.png">
> model.parameters是一个list，可以通过parameters的name进行一定的过滤, 例如
> 
> ```python
>      [ p for p in model.parameters() if 'linear' not in p.name]  # 这里就可以过滤一下linear层，具体过滤策略可以根据需要来设定
> ```

这一做法是否要对参数的name有所了解，而在动态图组网中其实不是太清楚这些name的规则？ @wawltor

**Comment by wawltor** [comment]
> > self.ernie是一个module，在module设置stop_gradient是无效的；
> > 如果想冻结参数，最直接的办法的是在optimizer上进行处理，可以过滤一下parameter，不让parameter进行更新，例如下图
> > <img alt="图片" width="633" src="https://user-images.githubusercontent.com/16698950/115648885-d7ecc500-a358-11eb-8852-34590ea5de76.png">
> > model.parameters是一个list，可以通过parameters的name进行一定的过滤, 例如
> > ```python
> >      [ p for p in model.parameters() if 'linear' not in p.name]  # 这里就可以过滤一下linear层，具体过滤策略可以根据需要来设定
> > ```
> 
> 这一做法是否要对参数的name有所了解，而在动态图组网中其实不是太清楚这些name的规则？ @wawltor

嗯嗯 上诉的方法需要对网络结构的名字需要整体了解一下，因为网络结构的实体名字决定了参数的名字，这个使用方法有一定的门槛

**Comment by ghost** [comment]
在forward里用paddle.no_grad()包裹一下应该可以吧？ @ZeyuChen @guoshengCS @wawltor
不想搞得太麻烦

**Comment by guoshengCS** [comment]
可以的，如果要用paddle.no_grad()包裹的话也注意只包裹ernie部分的就好，比如`paddlenlp.transformers.ErnieForSequenceClassification`不能整个都包，如果愿意改包里的代码的话可以简单许多的，比如直接让ernie的forward里给输出的tensor设置stop_gradient为True，上面给的都是在不侵入paddlenlp包中代码情况下的一些方案
