### ISSUE TITLE
阅读理解 DuReader-robust 如何使用自定义数据集训练？

### ISSUE THREAD

**Issue by Quantum-Cheese** [PaddlePaddle/PaddleNLP#298]
想要用自定义的数据集对模型进行 fine-tuning 训练，自定义数据集的格式已经修改成为与 DuReader-robust数据集格式一致的格式。通过 --train_file传入数据集路径，启动fine-tuning后，程序可以正常运行，无报错。但是没有任何输出（正常情况下应该会打印训练日志），运行完成后也没有保存 checkpoint文件。
请问这是怎么回事呢？

**Comment by smallv0221** [comment]
程序是一点输出都没有么，可以打印一下train_data_loader里的batch看看数据有没有正常读入
