### ISSUE TITLE
UIE实体识别评价指标

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#2981]
**uie实体识别评价指标是实体边界预测正确即为正确，不考虑预测的实体类型是否正确？**

![image](https://user-images.githubusercontent.com/109952192/183323009-449dad45-c8b1-41f4-b2fb-7a8487e8a70d.png)

![image](https://user-images.githubusercontent.com/109952192/183323054-1d2e28d9-3dfc-45f9-b243-df15043e380e.png)

**Comment by linjieccc** [comment]
您好，UIE在实体抽取中实体的标签类别会作为prompt与原文本进行拼接作为模型的输入，所以需要实体标签类别+实体边界完全一致才判定为正确

**Comment by MachineSheep** [comment]
> 您好，UIE在实体抽取中实体的标签类别会作为prompt与原文本进行拼接作为模型的输入，所以需要实体标签类别+实体边界完全一致才判定为正确

源码中比较预测的实体类别和标注的实体类别在哪呢？

**Comment by linjieccc** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/03dcbeff745fb18f230c5bc07a2e3c0d23b8617a/model_zoo/uie/evaluate.py#L41-L42

这里的input_ids会把prompt的token_ids和输入文本的token_ids进行拼接，prompt（实体标签类别）不同时，对应的start_prob和end_prob输出不同

**Comment by MachineSheep** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/03dcbeff745fb18f230c5bc07a2e3c0d23b8617a/model_zoo/uie/evaluate.py#L41-L42
> 
> 这里的input_ids会把prompt的token_ids和输入文本的token_ids进行拼接，prompt（实体标签类别）不同时，对应的start_prob和end_prob输出不同

start_prob，end_prob是预测的实体标签类别的起止位置tensor？如果是这样的话，那在哪里判断类别是否正确呢？

**Comment by linjieccc** [comment]
类别信息已经包含在模型的输入input_ids里面了，不同类别对应的input_ids不同，可以print出来看下

**Comment by MachineSheep** [comment]
> 类别信息已经包含在模型的输入input_ids里面了，不同类别对应的input_ids不同，可以print出来看下

这个我是清楚的，应该是input_ids前4位是表示类别信息，我咨询的是
` start_prob, end_prob = model(input_ids, token_type_ids, att_mask,`
这里输出的start_prob, end_prob中有类别信息吗？

**Comment by MachineSheep** [comment]
> 类别信息已经包含在模型的输入input_ids里面了，不同类别对应的input_ids不同，可以print出来看下

已经弄明白了，谢谢
