### ISSUE TITLE
更新paddlenlp时，发现卡住，其余包都是whl 但是seqeval-1.2.2.tar.gz (43 kB)

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#2982]
Collecting paddlefsl
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fb/4a/25d1959a8f1fe5ee400f32fc9fc8b56d4fd6fc25315e23c0171f6e705e2a/paddlefsl-1.1.0-py3-none-any.whl (101 kB)
Collecting dill<0.3.5
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl (86 kB)
Collecting seqeval
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/

- [ ] seqeval-1.2.2.tar.gz (43 kB)

**Comment by wawltor** [comment]
是否可以直接安装一下 seqeval试试了

**Comment by skywalk163** [comment]
对AIStudio环境，发现问题出在pip -U更新上，若更新了pip，则安装seqeval就会卡住。如果不更新，则不会卡住，会显示：
```
Requirement already satisfied: seqeval in /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages (from paddlenlp) (1.2.2)
```

**Comment by tingaicompass** [comment]
> 

是的，这边没更新后不会出现这个问题

**Comment by balancejia** [comment]
看这个
https://blog.csdn.net/qq_34451909/article/details/123629121
