### ISSUE TITLE
LIC2021 DuEE 事件抽取基线bug

### ISSUE THREAD

**Issue by WWWindrunner** [PaddlePaddle/PaddleNLP#2984]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.5，PaddlePaddle2.3.1，PaddlePaddle-gpu2.3.1
2）系统环境：Linux，python3.8.10
- 复现信息：复现LIC2021 DuEE 事件抽取基线出现bug
- 详细说明：代码版本为最新版本，默认的dev分支
- `a149af9a5a2000592d50921f853b3654b0fd7194`
- 
![企业微信截图_8ecbfba1-af89-4561-8bbb-2e2668d16208](https://user-images.githubusercontent.com/26530928/183354871-98403bdf-c0d7-437f-8e3a-2b8c7c1920c7.png)

- 执行到最后一步枚举分类预测时出现报错，原因见下图
![企业微信截图_6fca3845-4737-4591-a196-6e3f4fb6d8eb](https://user-images.githubusercontent.com/26530928/183355396-7b80a94c-1bf6-4313-84d7-36e0a5ea250b.png)

- 报错见下图
![企业微信截图_2987b0bc-0ee9-410e-8b84-7b8502546194](https://user-images.githubusercontent.com/26530928/183355569-44a0198c-e55f-4431-9ef6-515d5f1fd626.png)

- `ErnieTokenizer -> AutoTokenizer`后一切正常

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

**Comment by WWWindrunner** [comment]
@LiuChiachi

**Comment by LemonNoel** [comment]
非常感谢！我们更新修复了这个问题。https://github.com/PaddlePaddle/PaddleNLP/pull/2985
