### ISSUE TITLE
UIE事件抽取数据格式疑问

### ISSUE THREAD

**Issue by miaodog** [PaddlePaddle/PaddleNLP#2986]
按照这个文档
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md#53-%E4%BA%8B%E4%BB%B6%E6%8A%BD%E5%8F%96
的描述，事件抽取需要标注实体类别以及关系，那么一些开源的数据是不是就无法使用了？比如下面这条数据：

{"id": 7285, "text": "约翰逊（图：BBC）星岛环球网消息：【海外网4月6日|战疫全时区】据英国天空新闻网5日报道，英国首相约翰逊住院接受新冠病毒测试，10天前即3月27日他在社交媒体上发文称，自己新冠病毒检测结果呈阳性，正在自我隔离", "labels": [{"trigger": ["接受", 55], "object": ["英国首相约翰逊", 46], "subject": ["新冠病毒测试", 57], "time": "", "location": ""}], "distant_trigger": ["隔离", "测试", "接受", "检测"]}

这样的数据可以作为UIE的训练数据么？如果可以的话该怎么修改呢？

**Comment by linjieccc** [comment]
方便提供下这份数据不同字段的说明么，从这条数据来看应该少了论元（argument）和论元角色（role）的信息

**Comment by miaodog** [comment]
> 方便提供下这份数据不同字段的说明么，从这条数据来看应该少了论元（argument）和论元角色（role）的信息

case来源于这个比赛：http://challenge.xfyun.cn/topic/info?type=hotspot&option=ssgy
具体的data可以参考这个repo: https://github.com/WuHuRestaurant/xf_event_extraction2020Top1/blob/master/data/preliminary/raw_data/train.json

**Comment by linjieccc** [comment]
了解，上例中的论元角色是`主体`、`客体`、`时间`和`地点`，论元是`英国首相约翰逊`和`新冠病毒测试`，可以转为如下格式与doccano的标注导出格式对齐：

```text
{
    "id": 7285, 
    "text": "约翰逊（图：BBC）星岛环球网消息：【海外网4月6日|战疫全时区】据英国天空新闻网5日报道，英国首相约翰逊住院接受新冠病毒测试，10天前即3月27日他在社交媒体上发文称，自己新冠病毒检测结果呈阳性，正在自我隔离", 
    "relations": [
        {
            "id": 0, 
            "from_id": 2, 
            "to_id": 0, 
            "type": "主体"
        }, 
        {
            "id": 1, 
            "from_id": 2, 
            "to_id": 1, 
            "type": "客体"
        }
    ], 
    "entities": [
        {
            "id": 0, 
            "start_offset": 46, 
            "end_offset": 53, 
            "label": "主体"
        }, 
        {
            "id": 1, 
            "start_offset": 57, 
            "end_offset": 63, 
            "label": "客体"
        }, 
        {
            "id": 2, 
            "start_offset": 55, 
            "end_offset": 60, 
            "label": "接受触发词"
        }
    ]
}
```
