### ISSUE TITLE
看 报错信息应该具体是这几行，看起来是数据的dtype不匹配

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#2996]
看 报错信息应该具体是这几行，看起来是数据的dtype不匹配

```
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
[Hint: Expected dtype() == paddle::experimental::CppTypeToDataType::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType::Type():7.] (at ..\paddle\phi\core\dense_tensor.cc:137)
```

可以先检查一下模型的输入需要的dtype，和dataset/data_loader出来的数据的dtype是否匹配，常见的有int32和int64等~

_Originally posted by @LiuChiachi in https://github.com/PaddlePaddle/PaddleNLP/issues/2987#issuecomment-1208022136_

**Comment by Fmaj7** [comment]
1、data_loader出来的type：
{'input_ids': Tensor(shape=[32, 127], dtype=int64, place=Place(gpu:0), stop_gradient=True
2、裁剪的时候dtype配置为int32：
elif quantization:
        input_dir = compress_config.quantization_config.input_dir
        if input_dir is None:
            compress_config.quantization_config.input_filename_prefix = "model"
            input_spec = [
                paddle.static.InputSpec(shape=[None, None],
                                        dtype="int32"),  # input_ids
                paddle.static.InputSpec(shape=[None, None],
                                        dtype="int32")  # segment_ids
            ]
3、量化成功
4、打开 set_dynamic_shape 开关，自动配置动态shape出现新问题，看样子还是那个int64问题：
python infer_gpu.py --task_name token_cls --model_path ./msra_ner_quant_infer_model/int8 --shape_info_file dynamic_shape_info.txt --set_dynamic_shape
错误如下：
Traceback (most recent call last):
  File "./deploy/python/infer_gpu.py", line 94, in <module>
    main()
  File "./deploy/python/infer_gpu.py", line 82, in main
    predictor = ErniePredictor(args)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 296, in __init__
    self.set_dynamic_shape(args.max_seq_length, args.batch_size)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 405, in set_dynamic_shape
    self.inference_backend.infer(batch)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 203, in infer
    self.predictor.run()
RuntimeError: (NotFound) Operator (quantize_linear) does not have kernel for {data_type[int64_t]; data_layout[Undefined(AnyLayout)]; place[Place(gpu:0)]; library_type[PLAIN]}.
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at ..\paddle\fluid\framework\operator.cc:1712)
  [operator < quantize_linear > error]

我的dtype配置int32或int64也不行：
def token_cls_preprocess(self, data: list):
        # tokenizer + pad
        is_split_into_words = False
        if isinstance(data[0], list):
            is_split_into_words = True
        data = self.tokenizer(data,
                              max_length=self.max_seq_length,
                              padding=True,
                              truncation=True,
                              is_split_into_words=is_split_into_words)

        input_ids = data["input_ids"]
        token_type_ids = data["token_type_ids"]
        return {
            "input_ids": np.array(input_ids, dtype="int64"),
            "token_type_ids": np.array(token_type_ids, dtype="int64")
        }

**Comment by zcg-joker** [comment]
我是在误差反向传播时报错，请问是什么原因呢

File "train.py", line 134, in <module>
    train(model,train_loader,test_loader)
  File "train.py", line 100, in train
    all_loss.backward()
  File "<decorator-gen-157>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():10 != paddle::experimental::CppTypeToDataType<T>::Type():2.] (at /paddle/paddle/phi/core/dense_tensor.cc:143)

**Comment by LiuChiachi** [comment]
这个Issue已经关闭了，你重新提一个新的吧。把你跑的代码链接也发出来一下
