### ISSUE TITLE
事件抽取是否支持句子内存在多个事件类型，以及一个论元角色存在多个论元的场景

### ISSUE THREAD

**Issue by KgLearner** [PaddlePaddle/PaddleNLP#2998]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

**Comment by linjieccc** [comment]
UIE支持对句子中包含多个事件类型（触发词不同）和论元角色有多个论元的事件抽取
