### ISSUE TITLE
ernie3.0量化模型部署错误：Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end()

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3000]
版本、环境信息
    1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.4，paddlepaddle-gpu 2.3.1.post116
    2）系统环境：Windows10企业版，python38，cuda11.6，cudnn8.4
    复现信息：
***********
dataloader的数据类型为int64：'input_ids': Tensor(shape=[32, 90], dtype=int64, place=Place(gpu:0), stop_gradient=True
训练评估、裁剪、量化分别执行，其中训练和裁剪顺利执行
单独执行量化的时候有两种情况：paddle.static.InputSpec的dtype设置为int32时可顺利完成量化，其他则不行，配置如下 :
input_spec = [
                paddle.static.InputSpec(shape=[None, None],
                                        dtype="int64"),  # input_ids
                paddle.static.InputSpec(shape=[None, None],
                                        dtype="int64")  # segment_ids
            ]
当paddle.static.InputSpec的dtype设置为int32，完成量化后执行量化模型部署：
python infer_gpu.py --task_name token_cls --model_path ./msra_ner_quant_infer_model/int8 --shape_info_file dynamic_shape_info.txt --set_dynamic_shape，出现如下错误
**************************
[InferBackend] Engine Created ...
Traceback (most recent call last):
  File "infer_gpu.py", line 94, in <module>
    main()
  File "infer_gpu.py", line 82, in main
    predictor = ErniePredictor(args)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 296, in __init__
    self.set_dynamic_shape(args.max_seq_length, args.batch_size)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 405, in set_dynamic_shape
    self.inference_backend.infer(batch)
  File "D:\AI\PaddleNLP-develop\model_zoo\ernie-3.0\deploy\python\ernie_predictor.py", line 203, in infer
    self.predictor.run()
RuntimeError: (NotFound) Operator (quantize_linear) does not have kernel for {data_type[int64_t]; data_layout[Undefined(AnyLayout)]; place[Place(gpu:0)]; library_type[PLAIN]}.
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at ..\paddle\fluid\framework\operator.cc:1712)
  [operator < quantize_linear > error]

**Comment by LiuChiachi** [comment]
如上个issue #2987 ，`set_dynamic_shape`函数中用的是int64类型自己构造的数据，https://github.com/PaddlePaddle/PaddleNLP/blob/2a4a2fb69f577d9622bdb51ecb44b98a5b0145da/model_zoo/ernie-3.0/deploy/python/ernie_predictor.py#L379
您可以点开详细看一下
不是您的输入数据，可能需要您组网这里统一下dtype
