### ISSUE TITLE
2w条训练数据长度为256的文本，4ktest和dev过拟合正常吗？

### ISSUE THREAD

**Issue by zoeChen119** [PaddlePaddle/PaddleNLP#3001]
![image](https://user-images.githubusercontent.com/35884699/183578691-e036f657-9a9e-45eb-a860-4db257b41b05.png)

![image](https://user-images.githubusercontent.com/35884699/183578750-87d946e8-a746-45ac-93e4-7865ef04926b.png)

**Comment by LemonNoel** [comment]
有可能过拟合的，可以使用[VisualDL](https://github.com/PaddlePaddle/VisualDL/blob/develop/README_CN.md)等可视化工具分析下loss曲线变化。
