### ISSUE TITLE
当TrainingArguments中的report_to参数不指定时，将会报错

### ISSUE THREAD

**Issue by CatIIIIIIII** [PaddlePaddle/PaddleNLP#3002]
![图片](https://user-images.githubusercontent.com/28768547/183584490-7bb1c5ad-b073-442a-9c0c-ce417e58925e.png)
文档中https://paddlenlp.readthedocs.io/zh/latest/trainer.html?highlight=TrainingArguments#trainingarguments 说明可以不指定，应该是哪里赋值出了问题

**Comment by LemonNoel** [comment]
想问下paddlenlp版本是多少呢，或者TrainingArguments实现有修改吗？默认代码如果为`None`会后处理为`all`，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/training_args.py#L586

**Comment by CatIIIIIIII** [comment]
> 想问下paddlenlp版本是多少呢，或者TrainingArguments实现有修改吗？默认代码如果为`None`会后处理为`all`，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/training_args.py#L586

版本是2.3.0rc，我按照ernie的py文件配置的：https://github.com/PaddlePaddle/PaddleNLP/blob/70e6a31d134df7c018e57256872e14755bfd90eb/model_zoo/ernie-1.0/run_pretrain_trainer.py#L303 。
奇怪的是PreTrainingArguments.report_to的确是"visualdl"
然而在line303行：
```
parser = PdArgumentParser(
        (ModelArguments, DataArguments, PreTrainingArguments))
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
```
之后，training_args.report_to就为None了。

**Comment by LemonNoel** [comment]
可以更新下paddlenlp的版本，最新版本应该修复了这个问题
