### ISSUE TITLE
Hierarchical Multi-Label Classification

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/PaddleNLP#3005]
希望补充一下关于带层级多标签分类实现，这样就可以把文本分类的任务都覆盖了

**Comment by LemonNoel** [comment]
当前版本已经支持带层级的多标签分类了，可以看下[hierachical](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical)目录。或者可以再详细描述下所述任务和已有实现的区别么？

**Comment by jiaqianjing** [comment]
好的，感谢
