### ISSUE TITLE
simcse中为什么要对正例的相似度减去一个margin?

### ISSUE THREAD

**Issue by shawroad** [PaddlePaddle/PaddleNLP#3007]
cosine_sim = paddle.matmul(query_cls_embedding, title_cls_embedding, transpose_y=True)
margin_diag = paddle.full(
            shape=[query_cls_embedding.shape[0]],
            fill_value=self.margin,
            dtype=paddle.get_default_dtype())
cosine_sim = cosine_sim - paddle.diag(margin_diag)

在标准的simcse实现中，没有发现margin的存在。但是看paddle的实现时，发现对正例的相似度减去了一个margin。这样做，有什么根据或者好处吗？

**Comment by w5688414** [comment]
margin会构造一个对角矩阵，主要会影响对自身到自身向量的相似度计算，比如原来的相似度是1，增加了margin了0.2之后，自身和自身的相似度就变成了0.8，主要是降低本身自己的相似度的影响，给模型增加了难度，margin也是可以调的参数，以往的直播中有讲解。
```
# input paddle.diag(margin_diag): [[0.2,0],[0,0.2]]
        # input cosine_sim : [[1.0,0.6],[0.6,1.0]]
        # output cosine_sim: [[0.8,0.6],[0.6,0.8]]
        cosine_sim = cosine_sim - paddle.diag(margin_diag)

```

**Comment by shawroad** [comment]
明白了~    非常感谢。    这个有对应的实验证明吗？ 减margin和不减margin的对比？

**Comment by w5688414** [comment]
> 

没有做学术上那种严格的对比，您可以做一下实验，margin是可调的参数

**Comment by shawroad** [comment]
OK   感谢~
