### ISSUE TITLE
如何使用PaddleNlp 做些非中、英文语种的任务？比如葡萄牙语，越南等

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleNLP#3009]
比如我想用paddlenlp的 neural_search，但里面只有中英文的预训练模型。
有写好的完整的例子把huggingface embedding 转换成PaddleNlp 支持的吗？
或者你们是否已经有了好的解决方案？

**Comment by wawltor** [comment]
可以试试ERNIE-M模型  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-m

**Comment by jeffzhengye** [comment]
> 可以试试ERNIE-M模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-m

这个我看过，很多小语种还是没有啊。

**Comment by wawltor** [comment]
> > 可以试试ERNIE-M模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-m
> 
> 这个我看过，很多小语种还是没有啊。
有写好的完整的例子把huggingface embedding 转换成PaddleNlp 支持的吗？  这里是说HF有相关的模型是吗？

**Comment by wawltor** [comment]
> 比如我想用paddlenlp的 neural_search，但里面只有中英文的预训练模型。 有写好的完整的例子把huggingface embedding 转换成PaddleNlp 支持的吗？ 或者你们是否已经有了好的解决方案？

这里是说Huggingface有这样的模型是吗？

**Comment by jeffzhengye** [comment]
> 

有： https://huggingface.co/neuralmind/bert-base-portuguese-cased

paddlenlp 中GPT 有个支持我需要的语言葡萄牙语的。
https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/GPT/contents.html

**Comment by wawltor** [comment]
> > 
> 
> 有： https://huggingface.co/neuralmind/bert-base-portuguese-cased
> 
> paddlenlp 中GPT 有个支持我需要的语言葡萄牙语的。 https://paddlenlp.readthedocs.io/zh/latest/model_zoo/transformers/GPT/contents.html

就是葡萄语是吗？ 我记得ERNIE-M模型是支持葡萄语的， GPT模型是生成模型，不是语义模型

**Comment by jeffzhengye** [comment]
@wawltor 是支持的葡萄牙语的，刚才看漏了。
其它不支持的语言有提供转化工具吗？

**Comment by wawltor** [comment]
> @wawltor 是支持的葡萄牙语的，刚才看漏了。 其它不支持的语言有提供转化工具吗？
语言转化工具是有的，目前还没有开源出来，我问一下进度

**Comment by wawltor** [comment]
> @wawltor 是支持的葡萄牙语的，刚才看漏了。 其它不支持的语言有提供转化工具吗？

转化工具预计下周会有一个开源版本

**Comment by jeffzhengye** [comment]
@wawltor 已经发布了吗？
