### ISSUE TITLE
使用PaddleNLP训练文本多标签分类，多核心CPU只使用到了一个核心，怎么使用多核心进行训练？

### ISSUE THREAD

**Issue by ht896632** [PaddlePaddle/PaddleNLP#3010]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP，PaddlePaddle
使用的是docker直接部署：docker pull paddlecloud/paddlenlp:develop-cpu-latest

2）系统环境：系统类型：Linux，Python 3.7.13
启动训练脚本命令：python -m paddle.distributed.launch train.py --device cpu --dataset_dir ./data

**问题：启动训练后，只能用CPU其中的一个核心进行训练,怎么使用多核心？**

系统CPU占用情况：
![微信图片_20220810121728](https://user-images.githubusercontent.com/8132404/183815925-52682216-17cf-4d4e-87ef-49f007a66571.jpg)

**Comment by wawltor** [comment]
您好，我们经过多核训练测试，下面的方式可以进行多核训练，确保paddle的版本是在2.3.1版本
```bash 
python -m paddle.distributed.launch --nproc_per_node=8 --backend='gloo' train.py \
    --device "cpu" \
    --dataset_dir "data" \
    --save_dir "./checkpoint" \
    --max_seq_length 128 \
    --model_name "ernie-3.0-medium-zh" \
    --batch_size 32 \
    --early_stop \
    --learning_rate 3e-5 \
    --epochs 100 \
    --logging_steps 5
```
