### ISSUE TITLE
UIE是否支持英文事件抽取

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3021]
我看主页README里有这样一段话
![image](https://user-images.githubusercontent.com/109952192/184098929-46d1d4bf-0ecb-4ce9-9591-e75aeb90cbcb.png)

在UIE的README里有这样一段话
![image](https://user-images.githubusercontent.com/109952192/184099123-dc69d3c6-54d2-4af6-ae8d-841f0432075e.png)

是不是UIE其他信息抽取任务支持英文，事件抽取不支持？

**Comment by linjieccc** [comment]
因为效果问题目前英文版本还没有加入事件抽取相关的数据，后续会提供支持

**Comment by MachineSheep** [comment]
> 因为效果问题目前英文版本还没有加入事件抽取相关的数据，后续会提供支持

好的好的，非常感谢

**Comment by MachineSheep** [comment]
> 因为效果问题目前英文版本还没有加入事件抽取相关的数据，后续会提供支持

大佬目前对英文的事件论元抽取有什么论文或者模型建议吗？感谢

**Comment by linjieccc** [comment]
当前只是zero-shot的方式不支持英文事件抽取哈，如果手上有英文的事件抽取数据的话同样可以用UIE来训练

封闭域模型的话可以看下GPLinker

**Comment by disperaller** [comment]
> 当前只是zero-shot的方式不支持英文事件抽取哈，如果手上有英文的事件抽取数据的话同样可以用UIE来训练
> 
> 封闭域模型的话可以看下GPLinker

这个GPLinker貌似不支持英文
