### ISSUE TITLE
UIE实体识别预测的效率

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3022]
用uie做实体识别，Taskflow预测的时间与schema内的实体类别数量成正比，schema里面有多少个实体类别，模型预测就循环多少次吗？还是说多个类别模型跑一边就行了？

**Comment by linjieccc** [comment]
是的，实体识别中每次取一个类别作为prompt与原文本拼接作为模型的输入，所以schema中有多个实体类别时会预测多次

**Comment by MachineSheep** [comment]
> 是的，实体识别中每次取一个类别作为prompt与原文本拼接作为模型的输入，所以schema中有多个实体类别时会预测多次

那这个效率也太低了，我实体类别有几十个，效率真的很低

**Comment by MachineSheep** [comment]
> 是的，实体识别中每次取一个类别作为prompt与原文本拼接作为模型的输入，所以schema中有多个实体类别时会预测多次

有什么改进的办法吗

**Comment by linjieccc** [comment]
1.使用tiny系列模型进行提速
<img width="572" alt="image" src="https://user-images.githubusercontent.com/40840292/184124518-09ffc232-7076-4e00-a2aa-e4c64bc17b7f.png">
2.如果硬件满足要求的话可以尝试用FP16推理
![image](https://user-images.githubusercontent.com/40840292/184125047-3c44028e-710d-4449-9b17-063c394edc77.png)

**Comment by MachineSheep** [comment]
> 1.使用tiny系列模型进行提速 <img alt="image" width="572" src="https://user-images.githubusercontent.com/40840292/184124518-09ffc232-7076-4e00-a2aa-e4c64bc17b7f.png"> 2.如果硬件满足要求的话可以尝试用FP16推理 ![image](https://user-images.githubusercontent.com/40840292/184125047-3c44028e-710d-4449-9b17-063c394edc77.png)

好的，非常感谢

**Comment by liz9923** [comment]
可以把prompt分组，多线程求解汇总么？
