### ISSUE TITLE
UIE Taskflow中的batch_size参数没有作用

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3025]
![image](https://user-images.githubusercontent.com/109952192/184134575-4adab9fc-34c4-4baf-a6e7-2137dfcbdbbc.png)
```
text = ["xxxxx", "xxxxx”, "xxxxx"]
ie(text, batch_size=3......) 
```
预测消耗的时间和batch_size=1的消耗的时间是一致的， batch_size参数没有作用？

**Comment by guoshengCS** [comment]
主要是觉得时间上没差别吗，预测消耗的时间是如何评估的呢，输出的效果是符合batch_size设置的不

**Comment by MachineSheep** [comment]
> 主要是觉得时间上没差别吗，预测消耗的时间是如何评估的呢，输出的效果是符合batch_size设置的不

预测消耗的时间是用time.time()相减得到的结果。

batch_size的设置会导致输出效果有什么不同吗？都是一个列表，列表里面是字典

**Comment by MachineSheep** [comment]
@linjieccc 实体识别Taskflow的参数batch_size对模型预测的效率没有作用？

**Comment by linjieccc** [comment]
可以看下GPU利用率，如果速度没有变化可能是利用率已经打满了

**Comment by MachineSheep** [comment]
> 可以看下GPU利用率，如果速度没有变化可能是利用率已经打满了

batch_size设置为1或者其他,gpu的利用率都是80%左右，gpu的现存利用率都是20%左右。多条文本时模型的预测效率不受batch_size的影响。

**Comment by MachineSheep** [comment]
> 可以看下GPU利用率，如果速度没有变化可能是利用率已经打满了

模型是我定制训练之后的，用的是下面调用方法
Taskflow("information_extraction", schema=schema,batch_size=3, task_path='./checkpoint/model_best')
