### ISSUE TITLE
请大佬指教下unimo_text的训练和生成过程

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#3026]
百度大佬好，

如下AI Studio链接中是我使用unimo_text_1.0训练一个'基于相似FAQ，根据用户新的提问，生成答案'的项目。训练集和验证集中的title是相似问题的答案，有的不存在相似问题即为None. Source是用户的提问. Target是应当生成的回答。测试集类似，但不包含Target。麻烦大佬看看我的训练日志，目前是在loss等于3左右就停止训练了，请问大佬还有后续训练的必要？微调过程是否有存在问题呢？

关于生成结果，存在比较大的问题，1是生成结果不停的重复相同的一句话，其次就是貌似不同batch的数据，生成结果是一样的。每个batch生成了结果，我会print一下总共生成的结果数量，但是后面打印生成的结果却是一样的。还麻烦大佬指教指教。

AI studio链接：https://aistudio.baidu.com/studio/project/partial/verify/4420934/ab7d991a45344333b2e70849f895d0e4

**Comment by ZeyuTeng96** [comment]
"其次就是貌似不同batch的数据，生成结果是一样的。每个batch生成了结果，我会print一下总共生成的结果数量，但是后面打印生成的结果却是一样的"

这个地方，pred_ref是在循环内不停的extend生成结果。然后在for loop里面打开文件写入生成结果，造成感觉batch输入不一样，生成的结果却是一样的的错觉的。其他问题还麻烦大佬再看看。

**Comment by gongel** [comment]
你好
1. “生成结果不停的重复相同”这个问题可以继续训练看看
2. “不同batch的数据，生成结果是一样的”是不是后面的测试集数据一致呢

**Comment by tianxin1860** [comment]
可以详细描述一下应用场景需求么？

**Comment by ZeyuTeng96** [comment]
> 基于相似FAQ，根据用户新的提问，生成答案

应用场景需求是金融论坛上有用户对一些金融现象进行讨论或者对金融问题进行提问。当用户提出相似问题的时候，模型能够基于已经提出过的或者讨论过的现象或者问答生成一个答案。因此，在模型训练阶段、验证、预测阶段都引入了相似问题的答案。但是，从训练结果来看，生成的效果并不是很理想？训练过程能否也请大佬看看是否存在什么问题？gongel大佬让我继续训练看看，这个步骤我已经做了，问题是模型在loss等于3左右基本就不下降了，难道是我的训练数据量不够嘛？

**Comment by ZeyuTeng96** [comment]
> 应用场景需求是金融论坛上有用户对一些金融现象进行讨论或者对金融问题进行提问。当用户提出相似问题的时候，模型能够基于已经提出过的或者讨论过的现象或者问答生成一个答案。因此，在模型训练阶段、验证、预测阶段都引入了相似问题的答案。但是，从训练结果来看，生成的效果并不是很理想？训练过程能否也请大佬看看是否存在什么问题？gongel大佬让我继续训练看看，这个步骤我已经做了，问题是模型在loss等于3左右基本就不下降了，难道是我的训练数据量不够嘛？

**Comment by ZeyuTeng96** [comment]
> 应用场景需求是金融论坛上有用户对一些金融现象进行讨论或者对金融问题进行提问。当用户提出相似问题的时候，模型能够基于已经提出过的或者讨论过的现象或者问答生成一个答案。因此，在模型训练阶段、验证、预测阶段都引入了相似问题的答案。但是，从训练结果来看，生成的效果并不是很理想？训练过程能否也请大佬看看是否存在什么问题？gongel大佬让我继续训练看看，这个步骤我已经做了，问题是模型在loss等于3左右基本就不下降了，难道是我的训练数据量不够嘛？

**Comment by ZeyuTeng96** [comment]
> 可以详细描述一下应用场景需求么？

应用场景需求是金融论坛上有用户对一些金融现象进行讨论或者对金融问题进行提问。当用户提出相似问题的时候，模型能够基于已经提出过的或者讨论过的现象或者问答生成一个答案。因此，在模型训练阶段、验证、预测阶段都引入了相似问题的答案。但是，从训练结果来看，生成的效果并不是很理想？训练过程能否也请大佬看看是否存在什么问题？gongel大佬让我继续训练看看，这个步骤我已经做了，问题是模型在loss等于3左右基本就不下降了，难道是我的训练数据量不够嘛？

**Comment by tianxin1860** [comment]
我理解你的需求使用 FAQ 问答系统解决比较合适。

**Comment by ZeyuTeng96** [comment]
>

> 我理解你的需求使用 FAQ 问答系统解决比较合适。

我说句实在话，我的需求就是想用生成式模型来生成回答，您让我用FAQ 问答系统解决该问题。那您真的解决我的问题了？

**Comment by gongel** [comment]
你好，上述我同事提到的 FAQ 问答系统更偏向于检索式问答，如果不要求答案多样性的话，可以考虑采用。如果要使用unimo_text_1.0来做生成，可以适当增加数据和增加epoch来训练，我这边实测loss可以降到2.x的。

**Comment by ZeyuTeng96** [comment]
> 我这边实测loss可以降到2.x的。

问题是我肯定是想使用生成式模型来提供答案那，不然我找你们请教的意义是什么呢？

其次问题是您是用我提供的数据实测达到了2点几的loss吗？还是怎么样？这样是否会存在过拟合问题呢？

**Comment by ZeyuTeng96** [comment]
> 你好，上述我同事提到的 FAQ 问答系统更偏向于检索式问答，如果不要求答案多样性的话，可以考虑采用。如果要使用unimo_text_1.0来做生成，可以适当增加数据和增加epoch来训练，我这边实测loss可以降到2.x的。

如果您是使用我的数据集和代码，只是通过调参达到了2点几，能否把相关的超数据告诉我一下呢？

**Comment by gongel** [comment]
每次训练会有做评估，验证集上的BLEU指标没有下降，就不会过拟合。我看了你的数据，量较大，可以加大epoch到10，loss可以降到2.x

**Comment by ZeyuTeng96** [comment]
> 每次训练会有做评估，验证集上的BLEU指标没有下降，就不会过拟合。我看了你的数据，量较大，可以加大epoch到10，loss可以降到2.x

大佬，能否把训练日志和训练过程发我看看？谢谢大佬
