### ISSUE TITLE
ernie-3.0为什么不开放large模型

### ISSUE THREAD

**Issue by tanklandry** [PaddlePaddle/PaddleNLP#3028]
你们既然说比同业其他厂商的模型效果好，结果只开源个打不过roberta large的base，又想要推广paddle，有什么意义呢

**Comment by ZHUI** [comment]
你好，我们这边开源了 `ernie-3.0-xbase-zh` 20层模型，可以超过 roberta large，欢迎使用。
另外，我们开源了 `ernie-1.0-large-cw` 也可以超过robert-large，这个是24层的

**Comment by ZHUI** [comment]
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/16911935/184304631-fd961b13-0ae7-4b76-a706-0e6c1a7e88b8.png">

**Comment by tanklandry** [comment]
> 你好，我们这边开源了 `ernie-3.0-xbase-zh` 20层模型，可以超过 roberta large，欢迎使用。 另外，我们开源了 `ernie-1.0-large-cw` 也可以超过robert-large，这个是24层的

问题是近2年超过roberta large的模型太多了，不开源sota的模型，大家都用huggingface不就行了

**Comment by ZHUI** [comment]
> 问题是近2年超过roberta large的模型太多了，不开源sota的模型，大家都用huggingface不就行了

您好，这些模型可能英文的多一些，中文这块产出的开源预训模型并不特别多， 像  `Mengzi UER RoFormer` 之类的中文模型我们都有支持。
https://paddlenlp.readthedocs.io/zh/latest/model_zoo/index.html 

你有其他的中文模型的使用需求，特别欢迎提需求给我们。我们这边也可以 和 `ernie-3.0-xbase-zh` 模型比较效果。

**Comment by Gavingx** [comment]
> ernie-1.0-large-cw

ernie-1.0-large-cw模型有链接吗？

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L729-L730

直接 
```python
from paddlenlp.transformers import *

ernie = AutoModel.from_pretrained('ernie-1.0-large-cw')
```
即可
