### ISSUE TITLE
similarity 效率提升问题

### ISSUE THREAD

**Issue by zhaoyiyong** [PaddlePaddle/PaddleNLP#3034]
我的环境是：CPU：16核，128G内存。
需求：使用sim=Taskflow('similarity',batch_size=512)进行查找文档中和输入的句子最相似的句子。
使用：result = sim([insentece,docsentece],与文档中的每个句子进行对比，获得相似度值，然后取最大值。
问题：如果文档中的句子多，速度就很慢。对比一个句子耗时约0.2s。
请问，有什么办法提速吗？

**Comment by 1649759610** [comment]
如果文档句子比较多，可以在前边加一个阶段用于检索出部分比较相关的句子（比如基于语义检索），
先初步过滤一遍句子，选择比较相关的句子之后再基于TaskFlow对过滤的句子进行比较精确的相似度计算。或者选择一些参数量比较小的模型，加快模型推理速度。

**Comment by zhaoyiyong** [comment]
谢谢。这可能是个好方法，我试试。
