### ISSUE TITLE
句法依存关系

### ISSUE THREAD

**Issue by zhaoyiyong** [PaddlePaddle/PaddleNLP#3036]
请问一下，在进行句法依存关系分析时，返回结果如下：
[{'word': ['2月8日', '谷爱凌', '夺得', '北京冬奥会', '第三金'], 'head': [3, 3, 0, 5, 3], 'deprel': ['ADV', 'SBV', 'HED', 'ATT', 'VOB']}]
其中 head：3，0， 5 分别代表什么意思？

**Comment by linjieccc** [comment]
输出结果里面的head表示Token间的依存关系，上例中0，3，5分别是『ROOT』、『夺得』、『第三金』的TOKEN ID

可视化图例如下：
<img width="430" alt="image" src="https://user-images.githubusercontent.com/40840292/184567224-fa72d9c8-e83d-4b3c-b3bb-c599c03ee0e9.png">

完整定义可以参考这篇Paper对CONLL-X格式的定义：

![image](https://user-images.githubusercontent.com/40840292/184567430-69a3f568-6802-455d-9241-cee6aa358a84.png)

URL：https://ilk.uvt.nl/~emarsi/download/pubs/14964.pdf
