### ISSUE TITLE
doccano有问题

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3037]
改前：
![I$X4 F}EV1A6HDYW3J0BI3P](https://user-images.githubusercontent.com/50041220/184560865-3ff4277d-2a32-48dc-82ac-4f798145804f.png)
改后：
![R2 %%RX_W9~$L 1KJ}_75@R](https://user-images.githubusercontent.com/50041220/184560870-1dffb7eb-657b-41bf-9889-e9bbf9e82dad.png)

**Comment by linjieccc** [comment]
您好，能否提供下报错信息以及doccano版本

**Comment by Fmaj7** [comment]
![(Z`1LI}}`EM0(DRXHCPQ3UT](https://user-images.githubusercontent.com/50041220/184590550-4bf12a06-b538-4440-bfa9-702a67ef8270.png)
1.6.2

**Comment by linjieccc** [comment]
@lugimzzz 麻烦帮忙看下这个问题

**Comment by lugimzzz** [comment]
你好，请问为什么修改读取代码？输入的文件如果是根据[文本doccano指南](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/doccano.md)获得的jsonl文件，应该先按行读取，然后加载json得到字典。

**Comment by Fmaj7** [comment]
到处的数据结构如下 ：
![C@5XZ1B@)XU12~ (@~(}HZG](https://user-images.githubusercontent.com/50041220/184784608-c537ce63-c339-433d-a91c-091545a3d02a.png)

**Comment by lugimzzz** [comment]
> 到处的数据结构如下 ： ![C@5XZ1B@)XU12~ (@~(}HZG](https://user-images.githubusercontent.com/50041220/184784608-c537ce63-c339-433d-a91c-091545a3d02a.png)

改为下面这个代码：
```python
    with open(args.doccano_file, "r", encoding="utf-8") as f:
        raw_examples = f.readlines()[0]
    f.close()

    examples = []
    label_list = []
    with tqdm(total=len(raw_examples)) as pbar:
        for line in raw_examples:
            items = json.loads(line)
            # Compatible with doccano >= 1.6.2
            if "data" in items.keys():
                text, labels = items["data"], items["label"]
```

**Comment by Fmaj7** [comment]
嗯嗯，效果一样

**Comment by lugimzzz** [comment]
你是用什么方式导出doccano标注文本的？理论上导出的格式是这样
![image](https://user-images.githubusercontent.com/63761690/184785271-bb2cfdff-3a1b-44bb-9f22-4883268e0264.png)

**Comment by lugimzzz** [comment]
> 嗯嗯，效果一样

问题是否被解决？

**Comment by Fmaj7** [comment]
解决了
