### ISSUE TITLE
doccano.py 生成数据中的start,end 的意义是什么，

### ISSUE THREAD

**Issue by fuqiang-benz** [PaddlePaddle/PaddleNLP#3038]
doccano.py 分类生成数据中的start,end 的意义是什么，如果是是标签的下边，也对不上啊

{"content": "大元股份传闻王 上演逼空大戏", "result_list": [{"text": "stocks", "start": -3, "end": 3}], "prompt": "新闻分类[finance,sports,science,society,game,education,stocks,realty,politics]"}
{"content": "门将第95分钟头球破门 他改写西甲81年历史(视频)", "result_list": [{"text": "sports", "start": -3, "end": 3}], "prompt": "新闻分类[stocks,society,finance,education,realty,sports,game,science,politics]"}
{"content": "A股短期反弹空间有限 逢低或可介入黄金", "result_list": [{"text": "stocks", "start": -9, "end": -3}], "prompt": "新闻分类[science,game,finance,stocks,realty,sports,politics,education,society]"}

**Comment by linjieccc** [comment]
麻烦贴下doccano.py的执行方式

**Comment by fuqiang-benz** [comment]
[data.txt](https://github.com/PaddlePaddle/PaddleNLP/files/9334748/data.txt)
> 麻烦贴下doccano.py的执行方式

    data_file = r'D:\megrez\upload\data\20220809_152727_230536\data_20220809_152727_230536.jsonl'
    file_dir = r'D:\megrez\upload\data\20220809_152727_230536'
    basedir='r/megrez/'
    task_type = "cls"
    options =["finance","realty","stocks","education","science","society","politics","sports","game"]
    prompt_prefix = "新闻分类"
do_convert(time_id, data_file, task_type, options, prompt_prefix, file_dir, basedir)
训练数据已上传，用doccano生成的事文本分类数据

**Comment by wawltor** [comment]
> [data.txt](https://github.com/PaddlePaddle/PaddleNLP/files/9334748/data.txt)
> 
> > 麻烦贴下doccano.py的执行方式
> 
> ```
> data_file = r'D:\megrez\upload\data\20220809_152727_230536\data_20220809_152727_230536.jsonl'
> file_dir = r'D:\megrez\upload\data\20220809_152727_230536'
> basedir='r/megrez/'
> task_type = "cls"
> options =["finance","realty","stocks","education","science","society","politics","sports","game"]
> prompt_prefix = "新闻分类"
> ```
> 
> do_convert(time_id, data_file, task_type, options, prompt_prefix, file_dir, basedir) 训练数据已上传，用doccano生成的事文本分类数据

麻烦贴一下怎么执行docanno.py脚本了，如果是分类的任务的话在执行脚本的时候参数稍有不同
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/16698950/184568815-87054703-4437-45e3-802c-61f01db0baf2.png">

**Comment by fuqiang-benz** [comment]
> > [数据.txt](https://github.com/PaddlePaddle/PaddleNLP/files/9334748/data.txt)
> > > 麻烦贴下doccano.py的执行方式
> > 
> > 
> > ```
> > data_file = r'D:\megrez\upload\data\20220809_152727_230536\data_20220809_152727_230536.jsonl'
> > file_dir = r'D:\megrez\upload\data\20220809_152727_230536'
> > basedir='r/megrez/'
> > task_type = "cls"
> > options =["finance","realty","stocks","education","science","society","politics","sports","game"]
> > prompt_prefix = "新闻分类"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do_convert(time_id, data_file, task_type, options, prompt_prefix, file_dir, basedir) 训练数据已上传，用doccano生成的事文本分类数据
> 
> 麻烦贴一下怎么执行docanno.py脚本了，如果是分类的任务的话在执行脚本的时候参数有点不同 <img alt="图片" width="1030" src="https://user-images.githubusercontent.com/16698950/184568815-87054703-4437-45e3-802c-61f01db0baf2.png">

python doccano.py \
    --doccano_file ./data/doccano_ext.json \
    --task_type cls \
    --save_dir ./data \
    --splits 0.8 0.2 0 \
    --negative_ratio 5 \ 
   --prompt_prefix "新闻分类" \
   --options "finance" "realty" "stocks" "education" "science" "society" "politics" "sports" "game"

**Comment by fuqiang-benz** [comment]
> 

![image](https://user-images.githubusercontent.com/64388539/184569621-0ac84b30-8640-4cd1-9730-395206529994.png)

**Comment by fuqiang-benz** [comment]
> > > [数据.txt](https://github.com/PaddlePaddle/PaddleNLP/files/9334748/data.txt)
> > > > 麻烦贴下doccano.py的执行方式
> > > 
> > > 
> > > ```
> > > data_file = r'D:\megrez\upload\data\20220809_152727_230536\data_20220809_152727_230536.jsonl'
> > > file_dir = r'D:\megrez\upload\data\20220809_152727_230536'
> > > basedir='r/megrez/'
> > > task_type = "cls"
> > > options =["finance","realty","stocks","education","science","society","politics","sports","game"]
> > > prompt_prefix = "新闻分类"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > do_convert(time_id, data_file, task_type, options, prompt_prefix, file_dir, basedir) 训练数据已上传，用doccano生成的事文本分类数据
> > 
> > 
> > 贴一下怎么执行docanno.py脚本了，如果是分类的任务的话在执行脚本的时候参数有点<img alt="图片" width="1030" src="https://user-images.githubusercontent.com/16698950/184568815-87054703-4437-45e3-802c-61f01db0baf2.png">
> 
> python doccano.py --doccano_file ./data/doccano_ext.json --task_type cls --save_dir ./data --splits 0.8 0.2 0 --negative_ratio 5 \ --prompt_prefix "新闻分类" --options "finance" "realty “股票”“教育”“科学”“社会”“政治”“体育”“游戏”
![image](https://user-images.githubusercontent.com/64388539/184570966-99ae270e-cdca-4b6e-9fad-b55fd5635149.png)

![image](https://user-images.githubusercontent.com/64388539/184570996-605362d4-399e-430e-b7dc-c9d055c4e1f9.png)
我用下标输入找的标签，有的是空，有的还输出两个标签

**Comment by linjieccc** [comment]
您好，可以先将
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/utils.py#L345
修改为如下形式，
```python
start = prompt.rfind(label) - len(prompt) - 1
```
这里doccano.py对英文标签的处理有个bug我们修复下，多谢反馈。

另外使用中文模型的话建议将分类任务的标签类别改为中文，例如sports->运动

**Comment by fuqiang-benz** [comment]
> 你好，可以先将 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/utils.py#L345 修改为如下形式，
> 
> ```python
> start = prompt.rfind(label) - len(prompt) - 1
> ```
> 
> 这里中文doccano对标签的处理问题谢了我们.py修复下，多反馈。
> 
> 使用中文模型的话建议将另外分类任务的标签类别改为中文，例如sports->运动

![image](https://user-images.githubusercontent.com/64388539/184587861-66c43cbf-d53c-413a-b62d-f0cc2bb9dc39.png)
你好我把标签改成了中文，代码也按照你给的改了，输入标签还是不完整，麻烦帮忙看看

**Comment by linjieccc** [comment]
因为prompt与text拼接的时候是[CLS]prompt[SEP]text[SEP]，所以这里的start和end的index要算上[SEP] token
```python
prompt[start + 1: end + 1]
```

**Comment by fuqiang-benz** [comment]
> 因为prompt与text拼接的时候是[CLS]prompt[SEP]text[SEP]，所以这里的start和end的index要算上[SEP] token
> 
> ```python
> prompt[start + 1: end + 1]
> ```

好的 感谢

**Comment by fuqiang-benz** [comment]
> > 因为prompt与text拼接的时候是[CLS]prompt[SEP]text[SEP]，所以这里的start和end的index要算上[SEP] token
> > ```python
> > prompt[start + 1: end + 1]
> > ```
> 
> 好的 感谢

![image](https://user-images.githubusercontent.com/64388539/184597318-b59834a6-48ef-45d9-97a6-b16162e0c688.png)
您好,老师能在帮我看看一下吗，我按照你给我发的代码，转换数据，然后执行 python finetune.py 准确率 f1分值一直是0

**Comment by fuqiang-benz** [comment]
> > > 因为prompt与text拼接的时候是[CLS]prompt[SEP]text[SEP]，所以这里的start和end的index要算上[SEP] token
> > > ```python
> > > prompt[start + 1: end + 1]
> > > ```
> > 
> > 
> > 好的 感谢
> 
> ![image](https://user-images.githubusercontent.com/64388539/184597318-b59834a6-48ef-45d9-97a6-b16162e0c688.png) 您好,老师能在帮我看看一下吗，我按照你给我发的代码，转换数据，然后执行 python finetune.py 准确率 f1分值一直是0

![image](https://user-images.githubusercontent.com/64388539/184597657-dff86867-f383-409d-bcf6-35e710de634c.png)
这是 finetune. 代码执行的参数

**Comment by linjieccc** [comment]
麻烦提供下train.txt和dev.txt，我尝试复现下

**Comment by fuqiang-benz** [comment]
> 麻烦提供下train.txt和dev.txt，我尝试复现下

不好意思我这边参数的问题，麻烦你了，现在已经调好了

**Comment by linjieccc** [comment]
OK，不客气

**Comment by fuqiang-benz** [comment]
> OK，不客气

您好，打扰了，想请教个问题，UIE在finetune时，cpu只能使用单核这个问题，有什么好的解决办法吗，只使用一块cpu训练有点慢啊，350条数据已经训练12个小时了
