### ISSUE TITLE
neural_search语义检索代码BUG

### ISSUE THREAD

**Issue by SuperTangW** [PaddlePaddle/PaddleNLP#3039]
升级milvus支持2.x后，以下文件未更新，导致各种错误
applications/neural_search/search_system/config.py 
applications/neural_search/search_system/milvus_util.py

**Comment by w5688414** [comment]
> 

感谢反馈，我修复一下

**Comment by w5688414** [comment]
> 升级milvus支持2.x后，以下文件未更新，导致各种错误 applications/neural_search/search_system/config.py applications/neural_search/search_system/milvus_util.py

感谢反馈，我修复一下

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/3047
