### ISSUE TITLE
UIE 实体抽取CPU infer 效率问题

### ISSUE THREAD

**Issue by syw2014** [PaddlePaddle/PaddleNLP#3044]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
PaddleNLP 2.3.2

2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
- 采用aistudio，创建cpu基础环境，采用的是python/deploy下的代码进行预测，batch_size 为4，
总共2860条数据，schema 标签有5个，跑了3个小时，仍然没有结束；有没有什么优化的方法，以提高cpu下的预测效率？

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

**Comment by wawltor** [comment]
你可以直接使用Taskflow加载模型试试，这里集成了mkldnn加速和多核预测加速，不需要手动设置 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/16698950/184605323-04391eb7-dd10-4cc0-ade1-164dce58de59.png">

**Comment by syw2014** [comment]
> 你可以直接使用Taskflow加载模型试试，这里集成了mkldnn加速和多核预测加速，不需要手动设置 <img alt="image" width="960" src="https://user-images.githubusercontent.com/16698950/184605323-04391eb7-dd10-4cc0-ade1-164dce58de59.png">

您好，这个在**CPU环境**下能运行吗？我在aistudio 上测试是不行的，
![image](https://user-images.githubusercontent.com/6802806/185012348-c43c2eac-f41c-4432-8f0b-35734667e163.png)

**Comment by linjieccc** [comment]
被kill了，可以观察下内存情况，看是不是其他程序占用内存过多
![image](https://user-images.githubusercontent.com/40840292/185030262-60a09a8e-f2e6-42a1-b539-489f84fdd804.png)
