### ISSUE TITLE
from eval import evaluate

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/PaddleNLP#3045]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

**Comment by kennyLSN** [comment]
from eval import evaluate  
这个eval是啥，如何下载

https://aistudio.baidu.com/aistudio/projectdetail/3986803?channelType=0&channel=0

**Comment by wawltor** [comment]
需要进入到aistudio环境，才能看到eval.py

**Comment by wawltor** [comment]
您好，我们将关闭该iSSUE，如有问题可以再Open这个issue。

**Comment by chinochankawai** [comment]
你好，我使用pip install eval，import eval但仍然显示No module named 'eval'
请问可以提供eval模块，并在本地（比如pycharm）而非aistudio的环境下运行吗？


参照教程https://aistudio.baidu.com/aistudio/projectdetail/3955163
In [7]
# 开始训练
import time
import paddle.nn.functional as F

from eval import evaluate
