### ISSUE TITLE
datasets读取自定义的数据，这是啥问题

### ISSUE THREAD

**Issue by kennyLSN** [PaddlePaddle/PaddleNLP#3048]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

如还有问题可以到 PaddleNLP github 主页面的**[社区交流](https://github.com/PaddlePaddle/PaddleNLP#%E7%A4%BE%E5%8C%BA%E4%BA%A4%E6%B5%81)**扫描加入微信群，相关值班同学将会为您解答！

from paddlenlp.datasets import load_dataset

def read(data_path):
    with open(data_path, 'r', encoding='utf-8') as f:
        # 跳过列名
        next(f)
        for line in f:
            if len(line.strip('\n').split('\t')) ==3:
                q1, q2, label = line.strip('\n').split('\t')
                yield {'query': q1, "title":q2,'label': int(label)}
                          

train_ds = load_dataset(read, data_path='./dataset/train0803_clean.txt',lazy=False)
print("数据类型:", type(train_ds))
print("训练集样例:", train_ds[0])
len(train_ds.label_list)

打印如下错误
数据类型: <class 'paddlenlp.datasets.dataset.MapDataset'>
训练集样例: {'query': '可以看天气吗', 'title': '商品功能有哪些', 'label': 1}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-c94531dfa7cc> in <module>
     14 print("数据类型:", type(train_ds))
     15 print("训练集样例:", train_ds[0])
---> 16 len(train_ds.label_list)

TypeError: object of type 'NoneType' has no len()

**Comment by wawltor** [comment]
label_list是需要手动传入进去的， 可以参考下面的代码
<img width="728" alt="image" src="https://user-images.githubusercontent.com/16698950/184611816-cd130a4e-9a3d-4c8c-9069-232f9b92522c.png">
https://github.com/PaddlePaddle/PaddleNLP/blob/42ec8e31b40e1be77523a224cf66f76b4e1c65b5/applications/text_classification/multi_class/train.py#L156
