### ISSUE TITLE
多机多卡运行失败问题请求帮助

### ISSUE THREAD

**Issue by scuyjzh** [PaddlePaddle/PaddleNLP#3051]
运行脚本：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/run_pretrain.py

首先脚本在各自机器执行单机多卡时都正常运行，训练迭代一切正常，但是使用多机多卡就会报错。

主机执行命令：
python -m paddle.distributed.launch --ips="100.71.36.11,100.73.36.1" --gpus "1" run_pretrain.py ...
从机执行命令：
python -m paddle.distributed.launch --ips="100.71.36.11,100.73.36.1" --gpus "1" run_pretrain.py ...

两台机器都可以互ping通：
![image](https://user-images.githubusercontent.com/12816241/184562837-9e5cb82d-2ef9-4d82-a6c6-3767c7d343be.png)
![image](https://user-images.githubusercontent.com/12816241/184562879-8519b6c5-cccf-4083-a9b9-1f83e6f16cf2.png)

操作步骤：先运行从机命令，再运行主机命令
从机显示报错信息：
![image](https://user-images.githubusercontent.com/12816241/184563099-34b15e16-582e-46e5-beec-d2af1607f6d6.png)

主机一直卡在这里不动：
![image](https://user-images.githubusercontent.com/12816241/184563086-df5d715c-bb49-405a-9fe7-b042fbd64300.png)

两台机器的NCCL版本都是2.8.4，CUDA版本主机是11.2，从机11.1

贴一下从机的log
![image](https://user-images.githubusercontent.com/12816241/184563551-8bf6e831-d8d5-4c90-b1bf-70c2aaf58f93.png)

**Comment by ZHUI** [comment]
可能的情况比较多：

1. paddle版本不同，建议请检查一下Paddle各自的版本。
2. nccl版本不同，这个的话，cuda 11.2 和 cuda 11.1差异应该较小，建议也检查一下NCCL版本

这些都有可能导致多机 huang 住。可以`export NCCL_DEBUG=INFO`看是否有更多debug信息。

如果是厂内用户的话，可以加 如流群: 5165068 与我们交流，也可以尝试机器接入 paddlecloud。

**Comment by scuyjzh** [comment]
> 

非厂内用户
paddle版本都是一样的
唯一可排查的报错信息是从机显示的
socket read failed with ret_val=0
这可能是什么原因造成的呢 明明机器之间互ping都是通的

**Comment by ZHUI** [comment]
`export NCCL_DEBUG=INFO`  `export GLOG_v=5` 看一下日志，检查一下 两机的 NCCL 版本。

**Comment by ZHUI** [comment]
这种情况是 通信 卡住了，一般是 环境 哪里出现了不匹配的情况。

**Comment by scuyjzh** [comment]
这是从机的日志
![image](https://user-images.githubusercontent.com/12816241/184639734-5ccb6096-2e77-4bed-8f6f-3ea29f5a129a.png)

这是主机的日志
![image](https://user-images.githubusercontent.com/12816241/184639788-2d015a0b-8362-4238-b8fa-535365ba6700.png)

@ZHUI

**Comment by scuyjzh** [comment]
我把防火墙关闭之后，还是卡住
从机：
![image](https://user-images.githubusercontent.com/12816241/184643206-bcd4e499-8a4e-40c4-a377-63fd2bfd64e7.png)

主机：
![image](https://user-images.githubusercontent.com/12816241/184643283-3426184f-4ddf-4d66-8536-23b0d2018956.png)

@ZHUI

**Comment by ZHUI** [comment]
你的详细启动命令我看一眼？你看一下本机下面日志是不是有 workerlog.0 workerlog.1 两个？
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/16911935/184785310-402e3ddf-fab6-4ab1-99dd-412f1de4983e.png">

可以加入我们的交流群沟通，更快一些。
<img width="319" alt="image" src="https://user-images.githubusercontent.com/16911935/184785257-4110b2ab-dd3c-4132-a2ec-843b36edb188.png">

**Comment by scuyjzh** [comment]
解决了，需要添加export NCCL_SOCKET_IFNAME的环境变量

@ZHUI 谢谢答疑

**Comment by ZHUI** [comment]
好的，指定NCCL的通信口就可以了是吧，赞👍🏻
