### ISSUE TITLE
有中文转图片和图片转中文的比较好的开源模型吗？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleNLP#3054]
ERNIE-ViLG能做，但貌似没开源

**Comment by joey12300** [comment]
@zouhan6806504 你好，文图生成的模型暂时还没开源，但文图生成的功能体验已经在文心官网上提供了：https://wenxin.baidu.com/moduleApi/ernieVilg

**Comment by JunnYu** [comment]
目前的话paddlenlp可以使用这两个文图生成模型。可以clone最新的paddlenlp，然后参考这个PR https://github.com/PaddlePaddle/PaddleNLP/pull/2988 生成图片。

![58b8decf189e815dccfa8d7f372af420](https://user-images.githubusercontent.com/50394665/184873832-492aad69-9b13-4e06-b093-36752f709f86.png)

**Comment by zouhan6806504** [comment]
> 目前的话paddlenlp可以使用这两个文图生成模型。可以clone最新的paddlenlp，然后参考这个PR #2988 生成图片。
> 
> ![58b8decf189e815dccfa8d7f372af420](https://user-images.githubusercontent.com/50394665/184873832-492aad69-9b13-4e06-b093-36752f709f86.png)

我有数据想继续训练，有没有例子参考一下？

**Comment by JunnYu** [comment]
目前还没有关于训练流程的，后续我们会考虑增加的，到时候您可以关注下。
