### ISSUE TITLE
UIE 信息抽取中schema问题

### ISSUE THREAD

**Issue by heng3366** [PaddlePaddle/PaddleNLP#3060]
如果我要做三元组抽取，正常来说schema是有很多个的，taskflow引入自定义的schema可以有多个吗，还是只能弄一个schema，如果可以，有无多个chema定义格式参考

**Comment by linjieccc** [comment]
参考这个例子：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#36-%E8%B7%A8%E4%BB%BB%E5%8A%A1%E6%8A%BD%E5%8F%96

该例中定义了两个关系类型的schema：
```python
[
  {
      "原告": "委托代理人"
  },
  {
      "被告": "委托代理人"
  }
]
```
