### ISSUE TITLE
NLP 分词的日志如何关闭

### ISSUE THREAD

**Issue by hmwdt** [PaddlePaddle/PaddleNLP#3061]
PaddleNLP 2.3.4，PaddlePaddle2.3.0 Linux & MacOS

使用uwsgi 启动
[uwsgi]
user=root
http=0.0.0.0:8000
chdir=/data/www
callable=_app
wsgi-file=app.py
master=true
processes=2
pidfile=/data/www/uwsgi.pid
logto=/data/www/uwsgi.log
vacuum = true
logfile-chmod = 644
log-format = [uwsgi-log] | %(ltime) | %(host) | %(method) | %(uri) | %(proto) | %(status) | %(size) | "%(referer)" | "%(uagent)" | %(msecs) | %(time) | %(user)

使用paddlenlp进行分词时，

@staticmethod
    def word_segmentation(text):
        seg = Taskflow("word_segmentation", device_id=-1)
        return seg(text)

总会输出一堆日志
[uwsgi-log] | 16/Aug/2022:15:58:30 +0800 | 127.0.0.1:8000 | POST | /test | HTTP/1.1 | 200 | 252 | "-" | "PostmanRuntime/7.6.1" | 547 | 1660636710 | root
---    fused 0 elementwise_add with relu activation
---    fused 0 elementwise_add with tanh activation
---    fused 0 elementwise_add with leaky_relu activation
---    fused 0 elementwise_add with swish activation
---    fused 0 elementwise_add with hardswish activation
---    fused 0 elementwise_add with sqrt activation
---    fused 0 elementwise_add with abs activation
---    fused 0 elementwise_add with clip activation
---    fused 0 elementwise_add with gelu activation
---    fused 0 elementwise_add with relu6 activation
---    fused 0 elementwise_add with sigmoid activation
---    fused 0 elementwise_sub with relu activation
---    fused 0 elementwise_sub with tanh activation
---    fused 0 elementwise_sub with leaky_relu activation
---    fused 0 elementwise_sub with swish activation
---    fused 0 elementwise_sub with hardswish activation
---    fused 0 elementwise_sub with sqrt activation
---    fused 0 elementwise_sub with abs activation
---    fused 0 elementwise_sub with clip activation
---    fused 0 elementwise_sub with gelu activation
---    fused 0 elementwise_sub with relu6 activation
---    fused 0 elementwise_sub with sigmoid activation
---    fused 0 elementwise_mul with relu activation
---    fused 0 elementwise_mul with tanh activation
---    fused 0 elementwise_mul with leaky_relu activation
---    fused 0 elementwise_mul with swish activation
---    fused 0 elementwise_mul with hardswish activation
---    fused 0 elementwise_mul with sqrt activation
---    fused 0 elementwise_mul with abs activation
---    fused 0 elementwise_mul with clip activation
---    fused 0 elementwise_mul with gelu activation
---    fused 0 elementwise_mul with relu6 activation
---    fused 0 elementwise_mul with sigmoid activation

每一次请求都会产生这些日志，非常占用系统存储，请问这些日志如何关闭？

**Comment by linjieccc** [comment]
您好，这个问题目前修复了 https://github.com/PaddlePaddle/Paddle/pull/44316

可以安装nightly build版本再试下：
```shell
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
```
