### ISSUE TITLE
ernie3.0模型下载

### ISSUE THREAD

**Issue by fly2** [PaddlePaddle/PaddleNLP#3067]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.5，PaddlePaddle2.1.1
2）系统环境：Linux，python:3.8

目前https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0页面下的模型下载只提供了pdparams文件，
model.json和vocab.txt需要在AutoModel，AutoTokenizer模块中找对应模型文件的下载地址，建议可以在下载链接中一并提供。

**Comment by guoshengCS** [comment]
> model.json和vocab.txt需要在AutoModel，AutoTokenizer模块中找对应模型文件的下载地址，建议可以在下载链接中一并提供。

好的，感谢建议，也看到 #3071 的issue了
