### ISSUE TITLE
用paddle_serving部署分类模型，怎么获取label的置信度？

### ISSUE THREAD

**Issue by ht896632** [PaddlePaddle/PaddleNLP#3073]
迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！：

版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP，PaddlePaddle2.3.1
使用的是docker直接部署：docker pull paddlecloud/paddlenlp:develop-cpu-latest
2）系统环境：系统类型：Linux，Python 3.7.13

目前采用如下方式进行部署：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_class/deploy/paddle_serving

service.py 里面看到了获取标签的逻辑，尝试获取置信度目前还没解决
def postprocess(self, input_dicts, fetch_dict, data_id, log_id):

        results = fetch_dict[self.fetch_names[0]]
        label = results.argmax(axis=-1)

        return {"label": label}, None, ""

问题：用paddle_serving部署分类模型，怎么获取置信度？

**Comment by guoshengCS** [comment]
那个results里存的应该是置信度，可以用`results [labels]`或者 `results.max(axis=-1)`取出来看下呢

**Comment by ht896632** [comment]
> 那个results里存的应该是置信度，可以用`results [labels]`或者 `results.max(axis=-1)`取出来看下呢

感谢，已经解决
