### ISSUE TITLE
UIE部署时报错Could not find a CPU kernel and hence can't constant fold Mul node 'p2o.Mul.4'

### ISSUE THREAD

**Issue by sysuls1** [PaddlePaddle/PaddleNLP#3076]
![image](https://user-images.githubusercontent.com/36253898/185093173-51317808-5de5-4d84-802c-438dd19d66eb.png)

**Comment by linjieccc** [comment]
您好，这个是onnxruntime的Warning，提示Mul node不支持constant folding，不影响推理

**Comment by sysuls1** [comment]
> 您好，这个是onnxruntime的Warning，提示Mul node不支持constant folding，不影响推理

那这个部署之后，接口在哪里呢？好像没看到任何接口信息呀

**Comment by linjieccc** [comment]
serving的部署方式我们正在开发，还没有集成，可以先参考这个PR：https://github.com/PaddlePaddle/PaddleNLP/pull/2845

**Comment by sysuls1** [comment]
> serving的部署方式我们正在开发，还没有集成，可以先参考这个PR：#2845

from paddlenlp import SimpleServer
这里好像要求paddlenlp>=2.3.6，现在最高只能安装到2.3.5，好像暂时还不能部署。
