### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'io'

### ISSUE THREAD

**Issue by moonlang-vvv** [PaddlePaddle/PaddleNLP#3082]
版本：paddlenlp==2.3.5 python==3.6 paddlepaddle==2.3.1 
重装也不行，一直在报这个错，该怎么办呀？

**Comment by MachineSheep** [comment]
建议python版本升级一下

**Comment by gongel** [comment]
你好，可以确认下你跑代码的Python环境和你安装PaddlePaddle==2.3.1是否为同一个Python环境。
