### ISSUE TITLE
文图生成api是否还未能使用？

### ISSUE THREAD

**Issue by Japhlvicy** [PaddlePaddle/PaddleNLP#3085]
通过pip安装的paddlenlp，版本是2.3.5，按照git页面上的taskflow文档调用文图生成api，提示text_to_image任务还未加入 taskflow list中，请问目前文图生成功能是否还未更新？

**Comment by guoshengCS** [comment]
目前还没有在最新的2.3.5版本的包里，可以先行通过git clone PaddleNLP的repo并将PYTHONPATH指向下载下了的PaddleNLP目录来使用

**Comment by ZeyuChen** [comment]
@guoshengCS 可以考虑在安装文档这里新增一个源码安装的文档 作为后续这类需求的faq
