### ISSUE TITLE
可以提供下【快速上手】情感分析项目中的eval这个模块吗？

### ISSUE THREAD

**Issue by chinochankawai** [PaddlePaddle/PaddleNLP#3088]
你好，请问能提供下eval这个模块，并在本地（比如pycharm）而非aistudio的环境下运行吗？
本地pycharm中运行项目中代码from eval import evaluate 显示No module named 'eval'
pip install eval后，仍然显示No module named 'eval'

参照教程
https://aistudio.baidu.com/aistudio/projectdetail/3955163
In [7]
开始训练
import time
import paddle.nn.functional as F

from eval import evaluate
-----------
ModuleNotFoundError: No module named 'eval'

参照issue
https://github.com/PaddlePaddle/PaddleNLP/issues/3045

**Comment by chinochankawai** [comment]
已解决 到aistudio下载eval.py后放在python根目录

**Comment by wzhslap** [comment]
eval文件的代码如下：
import paddle
import numpy as np


# 构建验证集evaluate函数
@paddle.no_grad()
def evaluate(model, criterion, metric, data_loader):
    model.eval()
    metric.reset()
    losses = []
    for batch in data_loader:
        input_ids, token_type_ids, labels = batch['input_ids'], batch['token_type_ids'], batch['labels']

        logits = model(input_ids, token_type_ids)
        loss = criterion(logits, labels)
        losses.append(loss.numpy())
        correct = metric.compute(logits, labels)
        metric.update(correct)
        
    accu = metric.accumulate()
    print("eval loss: %.5f, accuracy: %.5f" % (np.mean(losses), accu))
    model.train()
    metric.reset()
    return accu
