### ISSUE TITLE
ImportError: cannot import name 'Taskflow' from 'paddlenlp' 

### ISSUE THREAD

**Issue by moonlang-vvv** [PaddlePaddle/PaddleNLP#3098]
有一个很神奇的bug。
在命令行输入python，一行一行敲，from paddlenlp import Taskflow，偶尔是可以运行的。
但是使用python xx.py，运行一个脚本文件，便会报错ImportError: cannot import name 'Taskflow' from 'paddlenlp' 。
我目前已使用官方提供的docker image，仍旧报这个错。

**Comment by LemonNoel** [comment]
请问paddlenlp版本是多少呢

**Comment by moonlang-vvv** [comment]
> 请问paddlenlp版本是多少呢
2.3.5

**Comment by LemonNoel** [comment]
python、paddlepaddle的版本分别是多少呢？以及运行的系统环境？`python -m pip show paddlenlp` 看下当前环境中 python 安装的 paddlenlp 版本路径指向是否正确？
