### ISSUE TITLE
请问以下， ANN 建库、召回，产出召回结果数据很准确，但是用Milvus进行召回的结果却很不准确

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3113]
模型一样，抽取的向量一样
![1661219341698](https://user-images.githubusercontent.com/50041220/186051263-f5c00b42-7055-482a-a3c9-d13749bcfdab.png)
![1661219382236](https://user-images.githubusercontent.com/50041220/186051267-6e98cba9-1529-4e56-b92c-268aad53e720.png)

**Comment by w5688414** [comment]
请问您是用的哪个应用？

**Comment by Fmaj7** [comment]
语义检索系统，in-batch-negative评估召回很准确，然后milvus很不准确

**Comment by w5688414** [comment]
> 语义检索系统，in-batch-negative评估召回很准确，然后milvus很不准确

能贴一下测试代码吗？请确保使用的是同一个模型抽取向量和建库

**Comment by Fmaj7** [comment]
代码没改，只是加了自定义的数据集，还有修改了部分脚本执行参数，脚本依次如下执行：
训练、召回：python -u -m paddle.distributed.launch --gpus "0" 
train_batch_neg.py 
--device gpu 
--save_dir ./checkpoints/recall 
--batch_size 64 
--learning_rate 5E-5 
--epochs 3 
--output_emb_size 256 
--save_steps 10 
--max_seq_length 64 
--margin 0.2 
--train_set_file data/train.csv 
--evaluate 
--recall_result_dir "recall_result_dir" 
--recall_result_file "recall_result.txt" 
--hnsw_m 100 
--hnsw_ef 100 
--recall_num 50 
--similar_text_pair "data/dev.csv" 
--corpus_file "data/corpus.csv"  
--similar_text_pair "data/dev.csv"
--------------------------------------------------------------------------
动转静导出：python export_model.py 
--params_path checkpoints/recall/model_best/model_state.pdparams 
--output_path=./output
-----------------------------------------------------------------------------
生成 embedding 向量：python feature_extract.py 
--model_dir=/home/lijiahong/PaddleNLP-develop-20220819/applications/neural_search/recall/in_batch_negative/output 
--corpus_file "data/milvus_data.csv"
*生成embedding向量步骤使用的model_dir是动转静导出的静态图*
----------------------------------------------------------------------------
向量插入数据：python milvus_ann_search.py 
--data_path data/milvus_data.csv 
--embedding_path corpus_embedding.npy --batch_size 100000 --insert
----------------------------------------------------------------------------
单独执行 召回：python -u -m paddle.distributed.launch --gpus "0" 
--log_dir "recall_log/" recall.py 
--device gpu 
--recall_result_dir "recall_result_dir" 
--recall_result_file "recall_result.txt" 
--params_path "checkpoints/recall/model_best/model_state.pdparams" 
--hnsw_m 100 
--hnsw_ef 100 
--batch_size 64 
--output_emb_size 256 
--max_seq_length 60 
--recall_num 50 
--similar_text_pair "data/dev.csv" 
--corpus_file "data/corpus.csv"
召回脚本修改代码如下：
![1661302870473](https://user-images.githubusercontent.com/50041220/186294379-f707937b-d2ee-4714-94b4-98df8b795834.png)
---------------------------------------------------------
milvus检索：python inference.py
检索脚本修改代码如下：
![1661302910222](https://user-images.githubusercontent.com/50041220/186294811-28576f09-1907-4307-94a9-5fa9f0692da3.png)
-----------------------------------------------------
milvus检索的结果完全不相关，但召回的结果相关性很高

**Comment by w5688414** [comment]
我看您换成了ernie 3.0, 请问feature_extract.py有修改没。

<img width="695" alt="image" src="https://user-images.githubusercontent.com/12107462/186296189-3a3de80b-fe9c-4e74-9f41-fc7349406cc4.png">

这里需要换成ernie 3.0的tokenizer

**Comment by Fmaj7** [comment]
feature_extract.py这个也换成ernie3了，好像全都换成e3了
![1661304020543(1)](https://user-images.githubusercontent.com/50041220/186296665-9adec669-37c2-456a-a352-c8ee874090c7.png)

**Comment by Fmaj7** [comment]
export_model也需要换成e3？这个没换
![1661304161514](https://user-images.githubusercontent.com/50041220/186296959-8abfe9a3-af61-4bf7-9d20-7b5f16014d04.png)

**Comment by Fmaj7** [comment]
可以了，我将export_model的pretrained_model和tokenizer都改为e3，太感谢了！

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/in_batch_negative/export_model.py
好的

**Comment by Fmaj7** [comment]
是这个

**Comment by Fmaj7** [comment]
用milvus检索的速度有点慢，我将初始化的final_index保存在内存检索速度会快得多，前提是向量不能太大
![1661306748812(1)](https://user-images.githubusercontent.com/50041220/186302001-4d9fa93f-dfd0-474e-bcb2-0375ec165c7b.png)

**Comment by w5688414** [comment]
> 

这是milvus吗？Mlivus我理解速度不会太慢，这看上去是hnswlib

**Comment by Fmaj7** [comment]
对，这是hnswlib

**Comment by w5688414** [comment]
好的，欢迎提一个pr哈

**Comment by gg22mm** [comment]
python inference.py 运行后是这样的怎么变成中文？：

Loaded parameters from ./checkpoints/model_2000/model_state.pdparams
[1, 256]
[[ 3.27459387e-02 -9.72712860e-02  2.02848762e-02 -2.73989756e-02
   7.02287033e-02  6.17552735e-03  8.05804972e-03 -1.67142190e-02
   4.89935800e-02  2.15973724e-02 -1.07276235e-02 -7.41445869e-02
   4.30856571e-02  3.78125943e-02 -5.42958565e-02  1.84978694e-02
   1.42500103e-02  3.24762613e-02  1.31560648e-02 -1.19557366e-01
   1.45828784e-01  1.56512409e-01 -1.49011150e-01  4.13696170e-02
   4.20428440e-02 -1.07830785e-01  6.79431781e-02  2.70863436e-02
   2.71195415e-02  3.66553180e-02 -7.51346648e-02  4.96917889e-02
  -6.00067712e-02  1.98381040e-02 -2.77707297e-02  4.48626615e-02
  -2.33972948e-02  1.08798482e-01 -2.84181740e-02 -3.61172743e-02
  -3.23930494e-02  3.05630602e-02 -3.02683767e-02 -6.10884055e-02
  -4.67345613e-04  5.42971790e-02 -2.95002591e-02  6.43469766e-02
  -1.83522142e-02  1.39867198e-02  1.17194559e-02  9.28665027e-02
  -2.19119098e-02 -6.20636065e-03 -5.24700340e-03 -7.78076425e-02
  -1.29748797e-02  4.86904122e-02  2.89473720e-02 -5.20914309e-02
   2.00103899e-03 -2.96290871e-02 -6.17215317e-03 -2.39068065e-02
  -5.60948923e-02  1.26619548e-01 -2.18852013e-02 -6.14241473e-02
  -3.66722532e-02 -3.99388857e-02  8.44140649e-02  3.78560349e-02
   6.35477155e-02 -4.53270786e-02 -1.06319711e-02  6.28683493e-02
  -3.05142272e-02  4.99091595e-02 -7.16505498e-02  2.08734602e-01
  -3.11767180e-02  1.46573670e-02 -6.20398186e-02 -1.03412546e-01
  -4.67108041e-02  7.07830787e-02 -3.78672779e-02 -7.10915625e-02
  -7.38523528e-02 -5.56926727e-02  9.42259748e-03  2.26089042e-02
   6.84704706e-02 -5.17666340e-02 -3.23755555e-02 -1.73463970e-02
  -2.97451317e-02 -2.09439788e-02  1.93901528e-02 -3.46361175e-02
  -4.47258055e-02  7.94796497e-02  5.21428213e-02 -5.58816008e-02
   4.55406085e-02  9.79084298e-02  4.59354296e-02  5.94964111e-03
   2.75901686e-02  2.90829106e-03 -6.06804341e-03 -5.01241954e-03
  -1.09540440e-01  8.22238531e-03  7.78441355e-02  2.46278159e-02
  -1.29102580e-02 -2.37203743e-02  5.47747426e-02 -1.06657371e-01
  -9.93065909e-02 -3.00029851e-02 -1.41284289e-02 -9.24551580e-03
  -3.87500152e-02  8.08484554e-02 -4.40116860e-02  4.60889041e-02
   6.27038330e-02  5.94897531e-02  2.11419538e-02  8.71581398e-03
   2.03491360e-01 -7.64892995e-02 -4.85688597e-02  5.47882058e-02
   1.00222439e-01 -5.94685897e-02 -6.13528453e-02  3.62539440e-02
  -7.53100738e-02 -9.01033729e-02 -8.62690136e-02  9.30769891e-02
  -4.94472720e-02  1.09816305e-02 -1.02636561e-01  7.74588529e-03
   1.50131667e-03  5.37286997e-02 -3.39223556e-02  1.43760415e-02
   3.10080089e-02 -3.29479724e-02  1.19579006e-02 -3.93688418e-02
   7.76157081e-02  3.95097509e-02  6.75730594e-03  7.27871880e-02
  -8.51070508e-02  2.79237777e-02  3.10718510e-02  1.58718135e-02
  -7.68187083e-03  9.62512859e-04  2.40610726e-02 -8.39263294e-03
   1.39089311e-02 -1.13117114e-01 -9.94322170e-03 -8.44173133e-02
  -4.22584005e-02  1.08737191e-02  1.48886982e-02 -9.98095274e-02
  -4.19363268e-02 -8.00100788e-02  5.32860644e-02 -9.32270214e-02
   1.40066385e-01 -4.07950021e-02  1.08947307e-01 -1.36540011e-01
  -6.27449667e-03 -2.68573128e-02 -4.06387076e-02 -4.55324240e-02
  -8.10586959e-02 -5.08973897e-02  7.66059682e-02 -1.14148101e-02
   2.86167562e-02 -1.35142565e-01  6.72752708e-02 -2.75197141e-02
  -1.28887390e-04 -6.08089939e-02  6.10710569e-02  2.15346478e-02
   4.74820472e-02 -4.29798476e-02  9.23516229e-02  9.54240374e-03
  -1.97848640e-02 -5.44486232e-02 -6.83147088e-02  1.50062934e-01
  -2.05641821e-01  8.08583274e-02  4.69410932e-03 -4.54050004e-02
  -2.30016187e-02  5.15998062e-03  6.65279999e-02 -7.35110119e-02
  -7.11363479e-02  3.96000361e-03 -5.37912995e-02  8.80645588e-02
   2.35670041e-02 -4.20905910e-02 -9.95127577e-03 -2.07562987e-02
   2.97646131e-02 -2.68991888e-02 -1.61567461e-02 -1.51794553e-02
  -4.64376770e-02  1.56993903e-02  1.32143283e-02  2.60084681e-02
  -8.49136896e-03  5.45199439e-02  1.56344771e-01 -5.30702621e-02
  -4.94938381e-02  9.09899995e-02  4.31619473e-02 -8.15913081e-02
   4.48965020e-02  1.25659222e-03 -7.42304921e-02  4.98398393e-02
  -6.54533505e-02 -2.45724227e-02 -1.25559680e-02  3.70679013e-02
   2.91025708e-03 -5.55095486e-02 -1.41658202e-01  9.06999335e-02
  -1.29310668e-01 -1.56049593e-03  4.20869514e-02  8.84904712e-02]]

怎么变成中文？
