### ISSUE TITLE
parallel_for failed: cudaErrorMemoryAllocation: out of memory

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3121]
请问这种情况如何处理，batch_size调整过，不起作用。我挂了个后端服务调用模型，每调用一次内存上升一点，不会释放，多调用几次就满了，必须要重启后端服务才能释放内存

**Comment by wj-Mcat** [comment]
就这一个描述，我们完全没法找到问题所在。

建议，给出本地paddle相关包版本，最小可复现代码，这样才能帮你快速定位问题。

**Comment by Fmaj7** [comment]
gc.collect()，加这个解决了

**Comment by wj-Mcat** [comment]
很高兴你的问题解决了。

不过以后如果把问题描述的更清楚一点非常完美了，这样我们也可以快速定位问题，其他开发者遇到类似问题也可以找到解决方案。
