### ISSUE TITLE
PaddleNLP 2.3.6 Release Note Candidate

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PaddleNLP#3122]
# New Features

## Pipelines

+ Pipelines融入RocketQA轻量化小模型。https://github.com/PaddlePaddle/PaddleNLP/pull/3078
+ 新增基于ERNIE3.0的RocketQA召回模型。 https://github.com/PaddlePaddle/PaddleNLP/pull/3033
+ 新增基于ERNIE3.0的RocketQA排序模型。 https://github.com/PaddlePaddle/PaddleNLP/pull/3019

## 文本分类Application
+ 新增analysis模块 。https://github.com/PaddlePaddle/PaddleNLP/pull/3011
+ 新增基于检索的文本分类。 https://github.com/PaddlePaddle/PaddleNLP/pull/2836
+ 新增小样本场景下的文本分类。https://github.com/PaddlePaddle/PaddleNLP/pull/2894

## Neural Search

+ Milvus升级到2.1版本。 https://github.com/PaddlePaddle/PaddleNLP/pull/2945

## Taskflow

+ Taskflow集成RocketQA的排序模型，用于语义相似度计算。 https://github.com/PaddlePaddle/PaddleNLP/pull/3003

## 文本生成
+ Generation API 支持自定义 `logits_processor` https://github.com/PaddlePaddle/PaddleNLP/pull/3018
+ Generation API 支持 `get_decoder_start_token_id()` 方法获取模型 `decoder_start_token_id` https://github.com/PaddlePaddle/PaddleNLP/pull/3018
+ BART 模型支持 `get_input_embeddings()` 和 `set_input_embeddings()` 方法获取 embeddings https://github.com/PaddlePaddle/PaddleNLP/pull/3018
+ GPT 模型支持 `get_vocab()` 方法获取词表 https://github.com/PaddlePaddle/PaddleNLP/pull/3018

## 预训练 ERNIE
+ 支持`ernie-3.0-base-zh`等其他权重进行预训练
+ 支持多个数据集组合输入，支持重计算功能 https://github.com/PaddlePaddle/PaddleNLP/pull/2849
+ 支持从内置权重开始训练
+ 优化了日志显示，默认展示全局loss https://github.com/PaddlePaddle/PaddleNLP/pull/2667

## 文图生成
- 新增Dalle-mini文图生成模型。https://github.com/PaddlePaddle/PaddleNLP/pull/2917
- 新增阿里EasyNLP中的文图文图生成模型。https://github.com/PaddlePaddle/PaddleNLP/pull/2968
- 新增文图生成的TaskFLow。https://github.com/PaddlePaddle/PaddleNLP/pull/2988

# Bug Fix
+ 修复 BART tokenizer 获取 `bos_token_id` 出错问题 https://github.com/PaddlePaddle/PaddleNLP/pull/3058
+ 修复 BART tokenizer 无法设置 `model_max_length` 问题 https://github.com/PaddlePaddle/PaddleNLP/pull/3018
+ 修复 Pipelines的随机问题生成按钮报错问题和搜索问题回退到上一个搜索结果的问题。 https://github.com/PaddlePaddle/PaddleNLP/pull/2954
+ 修复Pipelines在python3.7上利用faiss抽向量引起的问题。 https://github.com/PaddlePaddle/PaddleNLP/pull/2965
* 修复tokenizer resize-token-embeddings 方法 https://github.com/PaddlePaddle/PaddleNLP/pull/2763
* 修复OPT 示例代码 https://github.com/PaddlePaddle/PaddleNLP/pull/3064

# 其他

- 支持FasterGPT的word_embeddings 和 lm_head.decoder_weight的权重不共享。https://github.com/PaddlePaddle/PaddleNLP/pull/2953
- 重构RoFormer，新增RoFormerForCausalLM类，支持roformer-sim相似句生成 。https://github.com/PaddlePaddle/PaddleNLP/pull/3049
- 更新Ernie模型，当type_vocab_size=0时，表示不使用token_type_id。 https://github.com/PaddlePaddle/PaddleNLP/pull/3075

## 模型单测

* 新增Ernie-Gram模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/3059
* 新增TinyBert模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2992
* 新增Roformer 模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2991
* 新增Ernie-M模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2964
* 新增Skep模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2941
* 新增Electra和 XLNet模型单测  https://github.com/PaddlePaddle/PaddleNLP/pull/3031
* 新增 RoBERTa, ALBERT 和 ERNIE模型的单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2972

# New Contributors

**Comment by wj-Mcat** [comment]
## 模型单测

* 新增Ernie-Gram模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/3059
* 新增TinyBert模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2992
* 新增Roformer 模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2991
* 新增Ernie-M模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2964
* 新增Skep模型单测 https://github.com/PaddlePaddle/PaddleNLP/pull/2941

## Bug Fix

* 修复tokenizer resize-token-embeddings 方法 https://github.com/PaddlePaddle/PaddleNLP/pull/2763
* 修复OPT 示例代码 https://github.com/PaddlePaddle/PaddleNLP/pull/3064

**Comment by JunnYu** [comment]
## 文图生成
- 新增Dalle-mini文图生成模型。https://github.com/PaddlePaddle/PaddleNLP/pull/2917
- 新增阿里EasyNLP中的文图文图生成模型。https://github.com/PaddlePaddle/PaddleNLP/pull/2968
- 新增文图生成的TaskFLow。https://github.com/PaddlePaddle/PaddleNLP/pull/2988
## 其他
- 支持FasterGPT的word_embeddings 和 lm_head.decoder_weight的权重不共享。https://github.com/PaddlePaddle/PaddleNLP/pull/2953
- 重构RoFormer，新增RoFormerForCausalLM类，支持roformer-sim相似句生成 。https://github.com/PaddlePaddle/PaddleNLP/pull/3049
- 更新Ernie模型，当type_vocab_size=0时，表示不使用token_type_id。 https://github.com/PaddlePaddle/PaddleNLP/pull/3075
