### ISSUE TITLE
请问Paddle的TransformerEncoder没有实现Position Encoding的功能吗

### ISSUE THREAD

**Issue by psychocosine** [PaddlePaddle/PaddleNLP#3123]
在ESIM模型中我尝试用TransformerEncoder去代替bi-lstm，发现效果更差了，而且训练变慢了。是因为没有做Position Encoding吗？
![ESIM](https://user-images.githubusercontent.com/62004255/186154333-80ff7ccb-b5cc-41a4-af4e-425abf013320.png)

**Comment by FrostML** [comment]
`paddle.nn.TransformerEncoder` 仅包含 encoder 部分，不包含 embedding
