### ISSUE TITLE
UIE事件抽取模型输入的数据格式

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3128]
请问UIE事件抽取训练的时候是怎么识别到触发词的？
事件抽取训练数据通过doccano打标后的导出的json数据格式如下：
{"id":1,"text":"雀巢裁员4000人：时代抛弃你时，连招呼都不会打！","label":[[0,2,"裁员方"],[2,4,"裁员触发词"],[4,8,"裁员人数"]]}

经过doccano.py拆分数据集的结果如下：
{"content": "雀巢裁员4000人：时代抛弃你时，连招呼都不会打！", "result_list": [{"text": "雀巢", "start": 0, "end": 2}], "prompt": "裁员方"}
{"content": "雀巢裁员4000人：时代抛弃你时，连招呼都不会打！", "result_list": [{"text": "4000", "start": 4, "end": 8}], "prompt": "裁员人数"}
{"content": "雀巢裁员4000人：时代抛弃你时，连招呼都不会打！", "result_list": [{"text": "裁员", "start": 2, "end": 4}], "prompt": "裁员触发词"}

第一条样本和第二条样本在训练的时候，模型怎么知道触发词是哪个呢？第三条样本是让模型学习到什么呢？
事件抽取的数据集格式和实体识别是一样的吗？还是我做事件抽取的时候，把数据集标注错了，导致数据的格式错了？

**Comment by linjieccc** [comment]
doccano导出后的数据格式有一点问题，正确格式的例子： #2961 

事件抽取的标注方式可以参考这里，触发词和事件论元会由有向实线关联起来：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md#53-%E4%BA%8B%E4%BB%B6%E6%8A%BD%E5%8F%96
