### ISSUE TITLE
uie-base模型事件抽取预训练有用到DuEE1.0中文事件抽取数据集吗？

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3140]
在用UIE模型做事件抽取任务，找到开源数据集DuEE1.0中文事件抽取数据集，想在上面进行微调，看看事件抽取的效果，如果uie-base模型事件抽取预训练用到DuEE1.0中文事件抽取数据集，那还在这个数据集上进行试算，效果肯定会偏好

**Comment by linjieccc** [comment]
DuIE和DuEE都有加入训练
