### ISSUE TITLE
使用 FasterTokenizer 加速

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3141]
![}HOFX{PV2~LXCCDQGS(E3HS](https://user-images.githubusercontent.com/50041220/186604993-2ac1b9d7-b2aa-4c77-af76-f3f5e10644dc.png)
------------------
训练阶段加这个参数还是发布的时候加这个参数，发布的时候加好像没用
----------------------------

**Comment by Fmaj7** [comment]
----------------------------
模型抽向量速度太慢了，用neural_search这个应用，抽向量10s，可以参考ernie3裁剪、量化吗？
cpu：Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
----------------------------------------

**Comment by w5688414** [comment]
> 

您是在cpu上抽取向量的吗？在gpu上有试过吗？

**Comment by Fmaj7** [comment]
gpu抽取向量5s，cpu10s
gpu主机cpu：AMD Ryzen 9 5900HX with Radeon Graphics

**Comment by w5688414** [comment]
> 

哦哦，您那是amd的显卡是吧，推荐使用英伟达的gpu，英伟达的gpu支持加速，安装好cuda，cudnn那些

**Comment by Fmaj7** [comment]
笔记本gpu：NVIDIA GeForce RTX 3060 Laptop GPU，cpu：AMD Ryzen 9 5900HX with Radeon Graphics
服务器cpu：Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
我的模型是用笔记本gpu训练的，我用笔记本的cpu抽向量是5s，服务器的cpu跑是10s
问：1、gpu才支持fastertokenizer加速？训练阶段加use_faster=True这个参数还是发布的时候加？
       2、neural_search这个应用能否参考ernie3裁剪、量化？

**Comment by Fmaj7** [comment]
@w5688414 我用paddle serving方式部署用cpu跑响应时间0.3s，还可以

**Comment by joey12300** [comment]
> 模型抽向量速度太慢了，用neural_search这个应用，抽向量10s，可以参考ernie3裁剪、量化吗？

添加use_faster=True，需要先安装faster_tokenizer。试试使用`pip install faster_tokenizer`
