### ISSUE TITLE
UIE 定制模型一键预测中Taskflow模型预测时间很久的问题，有好的解决办法吗？

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#3142]
在数据文本：1.14MB 样本量为10072下：

batch_size=2
数据模型载入运行时间为1.5587928295135498s
模型计算运行时间为266.18130588531494s
数据导出运行时间为0.07100987434387207s
数据结果已导出

batch_size=32
数据模型载入运行时间为1.546999454498291s
模型计算运行时间为253.65821027755737s
数据导出运行时间为0.07125997543334961s

batch_size=64
数据模型载入运行时间为1.6438007354736328s
 #模型计算运行时间为257.333233833313s
数据导出运行时间为0.07118725776672363s

除了添加多个taskflow方法，还有更优的方法吗？ #3079

**Comment by MachineSheep** [comment]
建议看一下[#3022](https://github.com/PaddlePaddle/PaddleNLP/issues/3022)
