### ISSUE TITLE
在使

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#3143]

**Comment by LiuChiachi** [comment]
裁剪后的模型会导出为静态图模型，无法再通过动态图的方式加载再训练。预测的话可以在静态图下或者使用PaddleInference进行预测，这样可以直接加载.pdmodel, .pdiparams进行推理。预测可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0/deploy/python

**Comment by dingidng** [comment]
> 裁剪后的模型会导出为静态图模型，无法再通过动态图的方式加载再训练。预测的话可以在静态图下或者使用PaddleInference进行预测，这样可以直接加载.pdmodel, .pdiparams进行推理。预测可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0/deploy/python
好的，我去试一下，感谢！
