### ISSUE TITLE
请问UIE能否进行文档级别的信息抽取？

### ISSUE THREAD

**Issue by alderpaw** [PaddlePaddle/PaddleNLP#3147]
您好，请问UIE能否进行文档级别的信息抽取？如果可以的话，是否需要对输入做一些处理，比如句子间用类似[SEP]的特殊字符隔开？
直接将文档拆成单句输入的话效果会不理想，因为会存在一些跨句子的实体和属性。

**Comment by linjieccc** [comment]
当前是按照最大长度对文档级输入进行切分，实体之间间隔不远的话可以抽取，间隔较长的话目前还不支持

**Comment by MSZLean** [comment]
请问文档级的实体关系抽取后续会支持吗
