### ISSUE TITLE
uie-base-en模型安装链接

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3149]
直接在Taskflow中使用model='uie-base-en'，是查找不到的，怎么手动安装uie-base-en模型？

**Comment by linjieccc** [comment]
需要确保paddlenlp的版本 >= 2.3.5

**Comment by MachineSheep** [comment]
> 需要确保paddlenlp的版本 >= 2.3.5

好的，感谢
