### ISSUE TITLE
how to deploy a rocketqa model in paddle serving?

### ISSUE THREAD

**Issue by weileehh** [PaddlePaddle/PaddleNLP#3152]
I can't find any instruction on how to deploy rocketqa model in paddle serving. I think this is very basic need for using rocketqa. So could someone give me some advice?

**Comment by w5688414** [comment]
Please follow the instructions of question answering. https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/faq_finance

it's similar
