### ISSUE TITLE
piplines在前端上传文件时，报413error

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#3153]
如下图所示：
![913ae436096b41577a963f9e56f4916](https://user-images.githubusercontent.com/100854336/187082625-61f7c3c8-0ced-4d8d-8b87-077b1ebeb43f.jpg)

上传docx时，抛出该异常；
而且只要文件大于1MB就会报413error；
之前未升级时，上传txt格式文件，只要超过1MB，同样会报该错误。
（如果不能超过1MB，会限制很多文档的上传...）

**Comment by w5688414** [comment]
![image](https://user-images.githubusercontent.com/12107462/187384363-7ea73cb5-3a6a-411b-a4e8-8c154d605c34.png)
https://docs.bitnami.com/installer/infrastructure/ruby/administration/increase-upload-limit-nginx/#:~:text=The%20maximum%20size%20for%20uploaded,default%20in%20the%20NGINX%20configuration.

看看是不是nginx引起的
