### ISSUE TITLE
为什么ERNIE 3.0 轻量级模型获取到的模型和官网文档描述的大小相差很大？

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#3170]
官网给出的：
ernie-3.0-base-zh | Chinese | 12-layer, 768-hidden, 12-heads, 118M parameters. 
-- | -- | --
ernie-3.0-medium-zh | Chinese | 6-layer, 768-hidden, 12-heads, 75M parameters. 
ernie-3.0-mini-zh | Chinese | 6-layer, 384-hidden, 12-heads, 27M parameters. 
ernie-3.0-micro-zh | Chinese | 4-layer, 384-hidden, 12-heads, 23M parameters. 
ernie-3.0-nano-zh | Chinese | 4-layer, 312-hidden, 12-heads, 18M parameters. 

[实际通过链接：](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0#%E6%A8%A1%E5%9E%8B%E6%95%88%E6%9E%9C)

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/deploy/python/README.md

![image](https://user-images.githubusercontent.com/34392683/187639142-581b46d1-b813-4eb3-a1fd-a632e0189849.png)

和描述差太大了，nano下载下来78MB、而base有450MB左右。

 想请问一下是加载方式不对吗，还是描述有误？

**Comment by wawltor** [comment]
上面的base模型118M parameters是指base模型的参数个数，因为同一个模型可以被不同的精度来表示，例如float16，float32，下载下来是450M左右(存储空间大小)，是因为下载的模型是float32，118M * 4 大概是存储空间的量级。

**Comment by tingaicompass** [comment]
原来如此，十分感谢解答！

> 上面的base模型118M parameters是指base模型的参数个数，因为同一个模型可以被不同的精度来表示，例如float16，float32，下载下来是450M左右(存储空间大小)，是因为下载的模型是float32，118M * 4 大概是存储空间的量级。
