### ISSUE TITLE
训练集、验证集疑问

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3181]
语义检索应用neural_search，用的训练集和验证集一样可以吗？

**Comment by w5688414** [comment]
可以的，但不太推荐这种方式，验证集应该是训练集未出现的样本，这样才能更好的评估模型的泛化能力。

最近升级了Neural Search, 可以使用最新的模型。https://github.com/PaddlePaddle/PaddleNLP/pull/3172

想快速体验语义检索，可以使用最新的应用。 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines

**Comment by Fmaj7** [comment]
ok，还有doccano推荐的训练集、验证集比例为8:1，然而neural_search的in-batch-negative的 验证集却大很多

**Comment by w5688414** [comment]
> 
Neural Search  设计的时候考虑了在大数据上的搜索能力，验证集并没有规定是多少。如果您没有那么多数据，可以进行缩减，不过建议召回集合大一点，才能更好的体现评估的性能。

**Comment by Fmaj7** [comment]
好
