### ISSUE TITLE
前端上传docx，换行拆分的问题

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#3185]
![1fe4847776f508fdc1ed57dee839b3a](https://user-images.githubusercontent.com/100854336/188251265-c60e7178-b179-4af8-95f2-3349feea32ef.png)
docx文件中，该部分是一个完整的内容块

![2dbf11f05528c9003a615833b383c7d](https://user-images.githubusercontent.com/100854336/188251287-4123fe41-1d3b-4b04-abe6-43208079d1c3.jpg)
但是在上传建立索引后，并没有按照docx中回车键的换行来区分，而是按照docx普通的每一行来拆分，影响搜索时内容返回完整性。

![f0cf83c48865bb6e1c20df158ed9b2c](https://user-images.githubusercontent.com/100854336/188251345-f7100328-f884-4cc4-b869-fb468cc4ccad.png)
ES中查看的确是单行拆分了。
--------------------------------------------------------------
如何能像之前txt那样，以回车换行来区分完整内容呢？

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/3172
