### ISSUE TITLE
RocketQA

### ISSUE THREAD

**Issue by zhaoyiyong** [PaddlePaddle/PaddleNLP#3187]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleNLP version: (please specify the branch as well，e.g. PaddleNLP v2.2.1)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/3.7/3.8)
 5. CUDA/cuDNN version: (e.g. CUDA 10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleNLP使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleNLP版本：（请提供版本号和分支信息，如PaddleNLP v2.2.1）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/3.7/3.8）
 5. CUDA/cuDNN版本：（ 如CUDA 10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by zhaoyiyong** [comment]
Add ERNIE 3.0 based rocketqa DualEncoder models #3033 中的模型，能够被rocketqa.load_model调用使用吗？
我使用
de_conf = {
            "model":’rocketqa-zh-medium-query-encoder‘,
            "use_cuda": False,
            "device_id": 0,
            "batch_size": 32
    }
rocketqa.load_model（**de_conf) 报错：Config file [rocketqa-zh-medium-query-encoder] not found

**Comment by w5688414** [comment]
> 

您好，暂时不支持rocketqa.load_model 进行加载。使用方法请参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/semantic_search/modeling.py
