### ISSUE TITLE
[BUG] Tokenizer is_split_into_words 参数选项不符合预期。

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/PaddleNLP#3195]
欢迎您反馈PaddleNLP使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleNLP版本：develop

Tokenizer `is_split_into_words` 参数选项不符合预期。

```python
>>> ernie_tokenizer = paddlenlp.transformers.AutoTokenizer.from_pretrained("ernie-2.0-base-zh")
>>> ernie_tokenizer.convert_tokens_to_ids(["241", "##5","人"])
[5494, 9486, 8]
>>> ernie_tokenizer(["241", "##5","人"], is_split_into_words=True)
{'input_ids': [1, 5494, 9474, 9474, 317, 8, 2], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0]}
```

虽然加了`is_split_into_words`选项， 这里的 `##5` 没有转化成一个单独token，而是切分为 `# # 5`

**Comment by ZHUI** [comment]
该问题导致了`examples/benchmark/clue/mrc/run_c3.py` tokenizer之后数据超过`max_seq_len`。

**Comment by wj-Mcat** [comment]
## 描述

目前paddlenlp的tokenizer是和transformers对齐，我用paddlenlp确实复现了这个**问题**，并且结果和hf一致，测试代码如下：

```python
>>> from transformers.models.bert.tokenization_bert import BertTokenizer
>>> tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
>>> tokenizer(["241", "##5","人"], is_split_into_words=True)
{'input_ids': [101, 22343, 1001, 1001, 1019, 1756, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}
```

不过这个问题也是比较好解决：
* 先转化为string： 因为tokens中包含subword，转化为string的过程中会将subword给合并
* 再直接调用`tokenizer.__call__`

示例代码如下所示：
```python
>>> import paddlenlp
>>> ernie_tokenizer = paddlenlp.transformers.AutoTokenizer.from_pretrained("ernie-2.0-base-zh")
>>> sentence = ernie_tokenizer.convert_tokens_to_string(["241", "##5","人"])
>>> sentence
'2415 人'
>>> ernie_tokenizer(sentence, return_attention_mask=True)
{'input_ids': [1, 5494, 9486, 8, 2], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}
```

## 总结

新版本tokenizer fix了一些问题，也添加了一些新特性，所以老版本可能会有些不兼容的地方。

其实examples中的一些写法可以精简代码，减少一些与huggingface transformers概念上的不一致，比如Pad、Stack等。

**Comment by ZHUI** [comment]
1. `is_split_into_words`参数的目前行为，不符合参数预期？如果是的话，还是框架尽快修复。
2.  @LiuChiachi  此处 c3 数据集，由于此问题，导致 input_ids 超过 max_seq_len，辛苦尽快修复。

https://github.com/PaddlePaddle/PaddleNLP/blob/c195224a8fe8fffec84450c7bb9422755e909715/examples/benchmark/clue/mrc/run_c3.py#L250-L261

**Comment by wj-Mcat** [comment]
此[PR](https://github.com/PaddlePaddle/PaddleNLP/pull/3204)的offline测试代码如下所示：

```python
def test_bad_case():
    ernie_tokenizer: PretrainedTokenizer = paddlenlp.transformers.AutoTokenizer.from_pretrained("ernie-2.0-base-zh")
    tokens = ["241", "##5","人"]
    assert ernie_tokenizer([tokens], is_split_into_words='token')['input_ids'] == [[1, 5494, 9486, 8, 2]]
````
