### ISSUE TITLE
UIE文本分类

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#3199]
UIE可以做文本分类吗

**Comment by wawltor** [comment]
> UIE可以做文本分类吗

可以做文本分类，不过是建议直接使用applications来使用文本分类，分类方案相对比较齐全   https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification

**Comment by ZTurboX** [comment]
> > UIE可以做文本分类吗
> 
> 可以做文本分类，不过是建议直接使用applications来使用文本分类，分类方案相对比较齐全 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification

分类标签只有id信息，用applications中的prompt方法可以做吗

**Comment by wawltor** [comment]
> > > UIE可以做文本分类吗
> > 
> > 
> > 可以做文本分类，不过是建议直接使用applications来使用文本分类，分类方案相对比较齐全 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification
> 
> 分类标签只有id信息，用applications中的prompt方法可以做吗

prompt没有办法直接使用id信息，可以有以下两个方法
1）使用预训练微调方式，可以直接使用标签id方法
2）将id转成id对应的标签文本信息，就可以使用prompt方式

**Comment by tingaicompass** [comment]
可以参考Paddlenlp之UIE分类模型【以情感倾向分析新闻分类为例】含智能标注方案）
https://aistudio.baidu.com/aistudio/projectdetail/4337189?contributionType=1
