### ISSUE TITLE
examples样例中的 DuReader-yesno 出现小问题

### ISSUE THREAD

**Issue by wjunneng** [PaddlePaddle/PaddleNLP#32]
run_du.py 第 94 行代码
`tokens_raw = [tokenizer(l) for l in example]`出现如下问题：
  ```
  SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
    [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
  ```

原因：[https://github.com/PaddlePaddle/PaddleNLP/commit/e67c2c554043edae36e76f25e8bbcecfc29dd8cf](url) 提交删除了 tokenizer.py 文件中 BertTokenizer 类的 __call__() 方法，更改为了 tokenize() 。

因此，建议修改为`tokens_raw = [tokenizer.tokenize(l) for l in example]`问题可解。

**Comment by smallv0221** [comment]
感谢提出，已修复

**Comment by ZeyuChen** [comment]
Issue Solved.
