### ISSUE TITLE
如何通过调整数据集改变模型的预测方向

### ISSUE THREAD

**Issue by Fmaj7** [PaddlePaddle/PaddleNLP#3203]
下图为neural_search模型测试集输出结果，三列：检索语句、目标理想结果、当前模型输出结果，可否通过调整数据集引导模型预测输出倾向目标理想结果。
![1662425782246](https://user-images.githubusercontent.com/50041220/188525464-ca479084-6794-4f56-916a-e3756274192d.png)

**Comment by w5688414** [comment]
可以的，我感觉可以把您的检索语句和目标理想结果构成句子对，放入模型进行训练

**Comment by Fmaj7** [comment]
了解，我也这么认为！

**Comment by Fmaj7** [comment]
@w5688414 目前我有大概1千句子对，训练集、验证集比例多少为宜

**Comment by w5688414** [comment]
> 

8:2， 9:1都可以，请问有碰见什么问题吗？

**Comment by Fmaj7** [comment]
我的召回库大概4w多条，训练集1k不知道会不会太少

**Comment by w5688414** [comment]
> 

召回库为什么这么大？请问您是在做什么应用吗？另外您可以把一些召回的bad case放到训练集里面，这样能够提升召回的准确率

**Comment by Fmaj7** [comment]
了解，类似检索系统，语音转文本，通过文本从召回库检索目标，按此召回库的大小，训练集多大为宜啊

**Comment by w5688414** [comment]
> 了解，类似检索系统，语音转文本，通过文本从召回库检索目标，按此召回库的大小，训练集多大为宜啊

没有明确的多少，感觉几千条就ok，当然训练集合也希望是越多越好，一般搜索线上的召回库会上千万上亿的规模

**Comment by Fmaj7** [comment]
@w5688414 你好，感觉语义召回系统有个问题：有些检索显然是没有结果的，但是系统始终会召回一些结果，例如：
检索语句为：我我要找南方水城，可对嗯水城电话号码。
检索结果：新城水店
这个召回结果存在召回库，但是这个检索语句召回结果显然是不正确的，像这样有什么办法控制召回结果为空或直接输出个查无之类的？
