### ISSUE TITLE
UIE Slim 数据蒸馏

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleNLP#3213]
文档中的示例数据为：
![image](https://user-images.githubusercontent.com/44918749/188773807-c094aeb3-a1df-4524-bd50-36ab1beaca67.png)

**Comment by wawltor** [comment]
想问一下，具体的问题是什么了？

**Comment by linjieccc** [comment]
@KyleWang-Hunter 您好，示例数据的下载链接已修复，可以用最新的代码试下
