### ISSUE TITLE
pipelines的requirements.txt建议添加htbuilder github源码安装

### ISSUE THREAD

**Issue by paopjian** [PaddlePaddle/PaddleNLP#3216]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.4
2）系统环境：windows

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/requirements.txt st-annotated-text依赖htbuilder,但是pypi中的版本不是最新版,windows安装会出现gkb错误,建议添加 
```shell
git+https://github.com/tvst/htbuilder.git
```
到requirements.txt,以减少出错概率

**Comment by w5688414** [comment]
Thank you for your valuable advice

**Comment by ghost** [comment]
请问添加了吗？我也遇到了该问题。

**Comment by w5688414** [comment]
> 请问添加了吗？我也遇到了该问题。

暂时可以参考：
```
git clone https://github.com/tvst/htbuilder.git
cd htbuilder/
python setup install
```
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md
