### ISSUE TITLE
[General Issue]该说不说，文本匹配模型效果不咋地

### ISSUE THREAD

**Issue by shiwl0329** [PaddlePaddle/PaddleNLP#3223]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleNLP version: (please specify the branch as well，e.g. PaddleNLP v2.2.1)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/3.7/3.8)
 5. CUDA/cuDNN version: (e.g. CUDA 10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/13725297/189050565-d45632d1-697d-4460-b4ac-4d59302374c4.png">

欢迎您反馈PaddleNLP使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleNLP版本：（请提供版本号和分支信息，如PaddleNLP v2.2.1）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/3.7/3.8）
 5. CUDA/cuDNN版本：（ 如CUDA 10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by wawltor** [comment]
您好，是否可以把整个代码贴图一下？

**Comment by LiuChiachi** [comment]
您好，感谢关注
从您的代码我们看不出您遇到的具体问题，麻烦把你跑的代码或者是问题详细叙述一下：）
