### ISSUE TITLE
语义检索系统问题

### ISSUE THREAD

**Issue by panmyuan** [PaddlePaddle/PaddleNLP#3225]
Linux系统：
python 3.8.8
paddlepaddle-gpu 2.3.0
paddlenlp 2.3.3
无GPU
运行python examples/semantic-search/semantic_search_example.py --device cpu 报错，信息如下：
![image](https://user-images.githubusercontent.com/48192787/189060060-dd5b50d5-cb4f-4c89-b58f-2b9a436cccbd.png)
自己去点权重也下不了
![image](https://user-images.githubusercontent.com/48192787/189060188-e72ee972-709e-41ef-8604-803370a49aee.png)

**Comment by w5688414** [comment]
请升级paddlenlp：

```
pip install paddlenlp --upgrade
```

**Comment by panmyuan** [comment]
好的，谢谢，已经解决了
