### ISSUE TITLE
[General Issue] 请问UIE模型微调支持事件抽取的模型微调吗？

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3226]
请问UIE模型微调支持事件抽取的模型微调吗？如果支持的话，那么输入的标注数据格式应该是什么样的？

**Comment by wawltor** [comment]
可以的，可以看看这个链接 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md  
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/16698950/189080404-26cc9436-a0cb-4fbf-9fcf-2055c91eb1e8.png">

**Comment by FFinchR** [comment]
> 可以的，可以看看这个链接 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md <img alt="image" width="1070" src="https://user-images.githubusercontent.com/16698950/189080404-26cc9436-a0cb-4fbf-9fcf-2055c91eb1e8.png">

好的！感谢。
