### ISSUE TITLE
[UIE Issue] 用UIE做二分类问题，遇到预测结果除了0,1之外还有01以及为空的情况？吃惊！

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#3229]
[UIE Issue] 用UIE做二分类问题，遇到预测结果除了0,1之外还有01以及为空的情况？吃惊！
 result: {'fk[1,0]': [{'text': '1,0', 'probability': 0.2707405044412532}]}
result: {'fk[1,0]': [{'text': '1,0', 'probability': 0.28205075657191614}]}

而且还有结果会是空：{}

查看文档发现是有一个超参数：
position_prob=0.52
position_prob：模型对于span的起始位置/终止位置的结果概率在0~1之间，返回结果去掉小于这个阈值的结果，默认为0.5，span的最终概率输出为起始位置概率和终止位置概率的乘积。
但是这个值设置过高的话会导致输出为空。

感觉在二分类问题是，应该不是0 就是1 呀。而且那个'probability': 0.2707405非常低呀。应该是 0才对，有点不解！

关于position_prob在分类问题的影响，

**Comment by wawltor** [comment]
UIE采用的分类方式并不是传统的分类方式，例如下面的分类的schema如下
```python
schema = ['情感分类[正向，负向]']
```
在分类的时候是对对正向、负向这两个词进行位置抽取，所以模型的准确性有问题的时候，可能两个位置都抽取不出来，就存在上面的问题

**Comment by aixuedegege** [comment]
@wawltor 请问情感分类具体推理的逻辑是什么样的？我看finetune里面就是训练start end的预测，“正向”“负向”这些分类的词在原文中没有出现过的是怎么预测的？

**Comment by wawltor** [comment]
> @wawltor 请问情感分类具体推理的逻辑是什么样的？我看finetune里面就是训练start end的预测，“正向”“负向”这些分类的词在原文中没有出现过的是怎么预测的？

情感分类设置分类是咱们自己自定义的， 例如在schema中我们就需要设置情感分类的类别，然后在预测的过程中会将这个schema，例如 `schema = ['情感分类[正向，负向]']` 和待预测的文本拼接在一起，因此不需要预测的文本中出现这些词，使用的方法是一种prompt提示词的方式

**Comment by aixuedegege** [comment]
哦 我知道了，预测的是prompt里面的起始位置，是吧，哈哈。会有中文的t5模型版的uie么

**Comment by wawltor** [comment]
> 哦 我知道了，预测的是prompt里面的起始位置，是吧，哈哈。会有中文的t5模型版的uie么

t5中文的UIE模型目前还没有计划，基于ERNIE 3.0的UIE的模型目前从我们收集的反馈而言效果还是不错的

**Comment by wawltor** [comment]
您好！我们暂时关闭该issue，如有疑问可以再次打开该issue，谢谢！
