### ISSUE TITLE
CodeGen 服务无法被vscode copilot 插件调用

### ISSUE THREAD

**Issue by KenyonY** [PaddlePaddle/PaddleNLP#3235]
在vscode copilot 没有被激活时，更改插件的[用户配置](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6)，似乎也无法使用本地运行的codeGen服务：
```bash
[INFO] [auth] [2022-09-09T07:23:22.316Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2022-09-09T07:23:22.317Z] GitHub Copilot could not connect to server. Extension activation failed: "User not authorized" 
```
这是否意味着必须激活copilot才能使配置更改生效？ 那么关于在未激活状态下使用有任何建议吗

**Comment by gongel** [comment]
你好，`127.0.0.1`有改为服务器对外IP地址吗？服务器对外IP地址本地可访问吗？

**Comment by wawltor** [comment]
想问一下vscode copilot 配合 codegen，是在哪里看到相关信息的了？

**Comment by KenyonY** [comment]
你好，
@gongel  服务器地址是正确设置的，服务也是可以被访问的。  
@wawltor  codegen目录的README中： [GithubCopilot插件配置](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#githubcopilot%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE) 和 [配置插件](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/code_generation/codegen#%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6)

**Comment by gongel** [comment]
@beidongjiedeguang 你好，确实是的，Copilot确实是需要先激活。如果不激活的话，可以使用另外一个插件，我们也是支持的，可以看下这个[fauxpilot（注意事项的最后一点）](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/code_generation/codegen/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by anyxgit** [comment]
It don't work! When I use fauxpilot extension in vscode, the server said:
INFO:     127.0.0.1:54744 - "POST /v1/engines/codegen/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
……
RuntimeError: (NotFound) There are no kernels which are registered in the unsqueeze2 operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < unsqueeze2 > error]


> @beidongjiedeguang 你好，确实是的，Copilot确实是需要先激活。如果不激活的话，可以使用另外一个插件，我们也是支持的，可以看下这个[fauxpilot（注意事项的最后一点）](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/code_generation/codegen/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by Tindtily** [comment]
我在mac上跑，只有cpu，没有nvdia的gpu，出现类似问题。

```RuntimeError: (NotFound) The kernel with key (CPU, NCHW, float16) of kernel `unsqueeze_with_xshape` is not registered.
  [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /home/Paddle/paddle/phi/core/kernel_factory.cc:147)```
  
 关掉FastGeneration，可以执行，但就太慢了，直接卡不动，有没有方法只用cpu就可以加速的，谢谢。

> 我只有一丢丢python经验，搞了一个晚上都没搞定，如果只有CPU用不了注明一下，我就放弃了😅。

**Comment by gongel** [comment]
> 我在mac上跑，只有cpu，没有nvdia的gpu，出现类似问题。
> 
> `` RuntimeError: (NotFound) The kernel with key (CPU, NCHW, float16) of kernel `unsqueeze_with_xshape` is not registered. [Hint: Expected kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU != true, but received kernel_iter == iter->second.end() && kernel_key.backend() == Backend::CPU:1 == true:1.] (at /home/Paddle/paddle/phi/core/kernel_factory.cc:147) ``
> 
> 关掉FastGeneration，可以执行，但就太慢了，直接卡不动，有没有方法只用cpu就可以加速的，谢谢。
> 
> > 我只有一丢丢python经验，搞了一个晚上都没搞定，如果只有CPU用不了注明一下，我就放弃了😅。

只有cpu的话会比较慢，暂时不支持cpu加速。
