### ISSUE TITLE
text_summarization怎么进行商品短语抽取？

### ISSUE THREAD

**Issue by aircov** [PaddlePaddle/PaddleNLP#3239]
梵西驻颜六胜肽精华霜-金装版
梵西红石榴焕颜睡眠面膜
梵西六胜肽电动按摩眼霜 20g
梵西六胜肽御纹亮眼精华 15ml
梵西贵妇黑茶眼膜贴 去眼袋细纹补水紧致抗皱眼纹消黑眼圈学生女

例如这些商品标题数据，想要抽取短语，怎么抽取
期望结果：
梵西精华霜
梵西面膜
梵西眼霜
梵西眼膜贴
。。。等
主要是在搜索联想时可以使用这些短语进行联想

**Comment by gongel** [comment]
你好，可以参考这里在自己的数据上做微调。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/README.md
