### ISSUE TITLE
PaddlePaddle v1.5生成的simnet模型在PaddleNLP v2.3中加载

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#3253]
欢迎您反馈PaddleNLP使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleNLP版本：调用模型的代码版本PaddleNLP v.2.3.3
 2. PaddlePaddle版本：训练模型的版本为v1.5.1，调用模型的代码版本为v.2.3.0
 3. 操作系统信息：Linux
 4. Python版本号：Python3.9

使用PaddlePaddlev1.5.1版本训练SimNet-BOW模型，模型路径中有五个文件：

```
__model__
embd
info.yml
tanh.b
tanh.w
```

现在希望使用这个代码加载这个模型进行预测[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_matching/simnet/predict.py]()。

目前已参考[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/load_old_format_model_cn.html#paddle-fluid-io-save-inference-model]()中的
`fc = paddle.jit.load(model_path)`
和
`load_param_dict = paddle.load(model_path)`
进行加载，但是失败。

**Comment by wawltor** [comment]
您好，确认了一下 PaddlePaddle v1.5属于静态图的模式，而PaddleNLP从发版以来只支持PaddlePaddle v2.0的动态图模型加载，同时PaddlePaddle v1.5和PaddlePaddle v2.0在静态图的参数保存格式有些区别，因此没有办法加载模型。

**Comment by wjddd** [comment]
> 您好，确认了一下 PaddlePaddle v1.5属于静态图的模式，而PaddleNLP从发版以来只支持PaddlePaddle v2.0的动态图模型加载，同时PaddlePaddle v1.5和PaddlePaddle v2.0在静态图的参数保存格式有些区别，因此没有办法加载模型。

了解，感谢。
