### ISSUE TITLE
浮点数例外（核心已转储）

### ISSUE THREAD

**Issue by cingtiye** [PaddlePaddle/PaddleNLP#3256]
感谢百度开源！

在用Taskflow的question_answering时，执行以下代码：
```python
from paddlenlp import Tasflow
qa = Taskflow("question_answering", home_path="/data1/.paddlenlp")
qa("中国最大的河流是？")
```
1. 如果在cpu上，设置`device_id=-1`，代码可以执行
2. 如果在gpu上，设置`device_id=0`，代码出现以下错误

> ....
> Prefix dict has been built successfuly.
> 浮点数例外（核心已转储）

然后程序直接退出！

版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.3.3，PaddlePaddle-gpu 2.3.0
2）系统环境：Linux
3）python版本 3.85

**Comment by linjieccc** [comment]
@cingtiye 您好，可以参考这里检查下paddlepaddle gpu版本是否正确安装：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/run_check_cn.html#run-check

**Comment by cingtiye** [comment]
> @cingtiye 您好，可以参考这里检查下paddlepaddle gpu版本是否正确安装：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/run_check_cn.html#run-check

您好，我测试了一下，上面说是在一个GPU是被正确安装了，目前我的机器上有两个GPU。
```shell
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
PaddlePaddle works well on 1 GPU.
W0914 09:27:02.323796 183442 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
WARNING:root:PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: (External) CUDA error(209), no kernel image is available for execution on the device.
  [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at /paddle/paddle/fluid/framework/details/all_reduce_op_handle.cc:299)

PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
```

**Comment by linjieccc** [comment]
您的CUDA版本是多少？

**Comment by cingtiye** [comment]
> 您的CUDA版本是多少？

11.3

**Comment by wawltor** [comment]
> > @cingtiye 您好，可以参考这里检查下paddlepaddle gpu版本是否正确安装：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/run_check_cn.html#run-check
> 
> 您好，我测试了一下，上面说是在一个GPU是被正确安装了，目前我的机器上有两个GPU。
> 
> ```shell
> >>> import paddle
> >>> paddle.utils.run_check()
> Running verify PaddlePaddle program ...
> PaddlePaddle works well on 1 GPU.
> W0914 09:27:02.323796 183442 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
> WARNING:root:PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
>  1. There is not enough GPUs visible on your system
>  2. Some GPUs are occupied by other process now
>  3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
>  to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
> WARNING:root:
>  Original Error is: (External) CUDA error(209), no kernel image is available for execution on the device.
>   [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at /paddle/paddle/fluid/framework/details/all_reduce_op_handle.cc:299)
> 
> PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
> ```

是不是有个显卡是集显？

**Comment by cingtiye** [comment]
> 
两张都是A100 
![image](https://user-images.githubusercontent.com/32251546/190065289-dd52e7f5-f5bc-4f30-b815-d85f5853925e.png)

**Comment by cingtiye** [comment]
> > > @cingtiye 您好，可以参考这里检查下paddlepaddle gpu版本是否正确安装：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/utils/run_check_cn.html#run-check
> > 
> > 
> > 您好，我测试了一下，上面说是在一个GPU是被正确安装了，目前我的机器上有两个GPU。
> > ```shell
> > >>> import paddle
> > >>> paddle.utils.run_check()
> > Running verify PaddlePaddle program ...
> > PaddlePaddle works well on 1 GPU.
> > W0914 09:27:02.323796 183442 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
> > WARNING:root:PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
> >  1. There is not enough GPUs visible on your system
> >  2. Some GPUs are occupied by other process now
> >  3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
> >  to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
> > WARNING:root:
> >  Original Error is: (External) CUDA error(209), no kernel image is available for execution on the device.
> >   [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at /paddle/paddle/fluid/framework/details/all_reduce_op_handle.cc:299)
> > 
> > PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
> > ```
> 
> 是不是有个显卡是集显？

两张都是A100

![image](https://user-images.githubusercontent.com/32251546/190065417-cdb57140-8a19-4da0-b8a1-662a5f7fe58e.png)

**Comment by linjieccc** [comment]
试试安装指定CUDA11.2版本的paddlepaddle

```shell
python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

**Comment by cingtiye** [comment]
> 试试安装指定CUDA11.2版本的paddlepaddle
> 
> ```shell
> python -m pip install paddlepaddle-gpu==2.3.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> ```

不行 放弃了 我换了个环境（版本都一样）和卡 （A100换成V100）现在可以了

谢谢~
