### ISSUE TITLE
pipelines可以直接导入非txt的文件

### ISSUE THREAD

**Issue by lugangmail** [PaddlePaddle/PaddleNLP#3268]
### Feature request

对于pipelines，目前导入的数据似乎只能是目录下的txt文件。
而目前手头的资料，有一些是word和pdf文件。
因此希望能直接导入word和pdf文件。

### Motivation

避免用户将精力放到处理非AI核心业务以外。

### Your contribution

我觉得以我目前的水平，只能对产品提出改进意见作为我的贡献。
例如增加可视化部分。类似easydl，全程向导。

**Comment by w5688414** [comment]
please refer to this pr https://github.com/PaddlePaddle/PaddleNLP/pull/3439
