### ISSUE TITLE
pipeline semantic-search怎样进行增量数据更新

### ISSUE THREAD

**Issue by aircov** [PaddlePaddle/PaddleNLP#3273]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/semantic-search

参照这个例子https://aistudio.baidu.com/aistudio/projectdetail/4534674 使用faiss进行向量检索，当文件有更新时怎样增量更新索引，实时检索？

**Comment by w5688414** [comment]
您好，更新索引的方法已经在aistudio项目中有描述，请参考。https://aistudio.baidu.com/aistudio/projectdetail/4442670

如果想使用API实时更新，请参考下面的api：

```
# 更新元数据
document_store.write_documents(dicts)
# 更新embedding
document_store.update_embeddings(retriever)
```

**Comment by aircov** [comment]
> @w5688414 
你好
pipe = SemanticSearchPipeline(retriever, ranker) pipeline在实例化之后已经加载了一次retriever，再更新数据，retriever不会变的吧，会将最新的文档召回吗？

**Comment by aircov** [comment]
@w5688414 
还有个问题
![image](https://user-images.githubusercontent.com/43372380/190325908-1860a987-e69f-438e-b0f3-327b9d585597.png)

在aistudio上可以运行，在windows上报错，查询sql变量太多了？查了一下sqlite在查询时有limit个数限制？需要修改SQLITE_MAX_VARIABLE_NUMBER，不知道怎么改

**Comment by w5688414** [comment]
> 

您使用的是3.7版本吗？这似乎是一个已知的问题。请参考FAQ文档。

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/FAQ.md

**Comment by aircov** [comment]
> 

好的，谢谢。已解决
