### ISSUE TITLE
[Question]: pipeline semantic-search如何使用自己经过预训练和无监督训练 SimCSE后的模型？

### ISSUE THREAD

**Issue by ydnnh2008** [PaddlePaddle/PaddleNLP#3276]
### 请提出你的问题

pipeline semantic-search如何使用自己经过预训练和无监督训练 SimCSE后的模型？

**Comment by w5688414** [comment]
> ### 请提出你的问题
> pipeline semantic-search如何使用自己经过预训练和无监督训练 SimCSE后的模型？

请参考Neural Search模型的加载方式。
https://github.com/PaddlePaddle/PaddleNLP/blob/b1ad85171e6258cc8d4facc2d73a7f110c9126bc/pipelines/rest_api/pipeline/semantic_search_custom.yaml#L17
