### ISSUE TITLE
The models name: uie-m-base is not in task:[information_extraction]

### ISSUE THREAD

**Issue by wxzwxz131** [PaddlePaddle/PaddleNLP#3281]
### 请提出你的问题

使用uie-m-base时候出现这个错误The models name: uie-m-base is not in task:[information_extraction]，麻烦帮忙看一下

**Comment by wawltor** [comment]
uie-m-base 的使用需要更新到最新的PaddleNLP的版本

**Comment by wawltor** [comment]
您好，我们先暂且关闭该issue，有疑问您可以继续打开该issue，谢谢！！

**Comment by GCDAT** [comment]
在使用uie-senta-base出现错误AssertionError: The models name: uie-senta-base is not in task:[sentiment_analysis]，麻烦看一下
