### ISSUE TITLE
[Question]:  在aistudio运行run_moe_pretrain.py失败

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/PaddleNLP#3287]
### 请提出你的问题

您好！ 我在运行run_moe_pretrain的时候报错：ImportError: cannot import name '_legacy_C_ops' from 'paddle'，这该怎么解决呢？
除此之外，使用moe进行模型并行只要用group_sharded_parallel替换DataParallel吗？？
![~ZXG%TEVAQ71IKSNMFZ)~XL](https://user-images.githubusercontent.com/68314259/190837878-74070157-a9f2-471b-b89e-c3218f18ae19.png)

**Comment by LemonNoel** [comment]
报错可以试下把paddlepaddle-gpu升级到最新版本

**Comment by jiaohuix** [comment]
好的我试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月17日(星期六) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Question]:  在aistudio运行run_moe_pretrain.py失败 (Issue #3287)





 
报错可以试下把paddlepaddle-gpu升级到最新版本

**Comment by jiaohuix** [comment]
> 报错可以试下把paddlepaddle-gpu升级到最新版本

您好，paddle需要哪个版本呢？ 升级到最新版本报错了。

**Comment by jiaohuix** [comment]
> 报错可以试下把paddlepaddle-gpu升级到最新版本

您好，我已经安装了nightly版本paddle，基本上可以运行了，只不过加载数据时候格式似乎不对，这是什么原因呢？

复现流程：

1.安装moe_pretrain需要的依赖

pip install regex LAC
2.安装paddle nightly
    

cuda11.2
python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

3.设置环境变量
若不设置会在安装paddlenlp后报错：   importError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
参考：https://github.com/deepmind/acme/issues/47#issuecomment-661126129
           [ https://blog.csdn.net/weixin_45392674/article/details/126300556](https://blog.csdn.net/weixin_45392674/article/details/126300556)

找到python或conda的lib
export LD_LIBRARY_PATH=/opt/conda/envs/python35-paddle120-env/lib/

4.安装paddlenlp

git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP
pip install -r requirements.txt
python setup.py install

5.下载数据
参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0

cd examples/language_model/moe/dygraph/
mkdir data && cd data
wget https://bj.bcebos.com/paddlenlp/models/transformers/data_tools/wudao_200g_sample_ernie-3.0-base-zh_ids.npy
wget https://bj.bcebos.com/paddlenlp/models/transformers/data_tools/wudao_200g_sample_ernie-3.0-base-zh_idx.npz
cd ..

6.run_moe

sed -i "s/0,1,2,3,4,5,6,7/0/g" run.sh
bash run.sh

![Image](https://user-images.githubusercontent.com/68314259/192298133-0d5a0217-66d0-4ce3-aad5-8a839f283c34.png)

![Image](https://user-images.githubusercontent.com/68314259/192297686-d5c30391-079d-46eb-86fc-78ffa625df51.png)

**Comment by ZHUI** [comment]
moe 需要最新develop运行
