### ISSUE TITLE
如何制作在不同CUDA版本的镜像？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#3291]
需要部署的设备使用CUDA 11.0，可是提供的镜像registry.baidubce.com/paddlepaddle/paddlenlp:2.4.0-gpu-cuda10.2-cudnn7要求的版本是10.2。请问有提供不同CUDA版本的镜像吗？

**Comment by w5688414** [comment]
cuda 11.2版本的pipelines计划会提供，但时间没那么快，需要提交给qa测试：

如果想自己编译一个镜像，请拉取官方的cuda 11.2的镜像

```
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8
```
将paddle的源码放进去，然后参考：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker

**Comment by w5688414** [comment]
Please refer to this pr for compiling you own cuda version's Docker. https://github.com/PaddlePaddle/PaddleNLP/pull/3315
