### ISSUE TITLE
[Bug]: model_zoo/utils.py, #744, all_relation_examples在is_train=True下均为空。

### ISSUE THREAD

**Issue by Q-amazing** [PaddlePaddle/PaddleNLP#3294]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
model_zoo/utils.py, #744, all_relation_examples在is_train=True下均为空。
print（all_relation_examples）
# all_relation_examples=[]
导致doccano.py在转换uie模型数据进行微调训练任务中，关系抽取的语料为空。
```

### 稳定复现步骤 & 代码

python doccano.py \
    --doccano_file ./data/doccano_ext.json \
    --task_type ext \
    --save_dir ./data \
    --splits 0.8 0.2 0

**Comment by wawltor** [comment]
您好，你提的问题我们已经修复了，谢谢给我们提出问题！
