### ISSUE TITLE
Where is  function squad_json_to_jsonl  defined 

### ISSUE THREAD

**Issue by LiemLin** [PaddlePaddle/PaddleNLP#3297]
https://github.com/PaddlePaddle/PaddleNLP/blob/f6e0068a45eaeb67aced52c5d76a62e5012c296e/pipelines/pipelines/document_stores/base.py#L397

**Comment by w5688414** [comment]
Thank you, please refer to this pr: https://github.com/PaddlePaddle/PaddleNLP/pull/3298

**Comment by LiemLin** [comment]
already fixed, thanks
