### ISSUE TITLE
[Question]: 手把手搭建一个语义检索系统的问题

### ISSUE THREAD

**Issue by ydnnh2008** [PaddlePaddle/PaddleNLP#3304]
### 请提出你的问题

我正实验 手把手搭建一个语义检索系统：
实验的是 Domain-adaptive Pretraining + SimCSE + In-batch Negatives

如下图所示：
我用第一、二步训练好的模型，加载到第三步的In-batch Negatives训练会报错。如果不是这样做的话，那第三步怎么和前两步结合？
![image](https://user-images.githubusercontent.com/47730754/190980148-cf3e325d-3ea2-4720-925d-9d873719973f.png)

**Comment by w5688414** [comment]
请参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/in_batch_negative

使用下面的方式加载：
```
--init_from_ckpt simcse/model_20000/model_state.pdparams
```
