### ISSUE TITLE
[Question]: EPRSTMT数据集不存在

### ISSUE THREAD

**Issue by HongLouyemeng** [PaddlePaddle/PaddleNLP#3312]
### 请提出你的问题

Couldn't find 'eprstmt' on the Hugging Face Hub either: FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/main/datasets/eprstmt/eprstmt.py

**Comment by HongLouyemeng** [comment]
> ### 请提出你的问题
> Couldn't find 'eprstmt' on the Hugging Face Hub either: FileNotFoundError: Couldn't find file at https://raw.githubusercontent.com/huggingface/datasets/main/datasets/eprstmt/eprstmt.py

 No module named 'paddlenlp.datasets.EPRSTMT'

**Comment by LemonNoel** [comment]
FewCLUE 中的 EPRSTMT 加载方式为
```
from paddlenlp.datasets import load_dataset
data_ds = load_dataset("fewclue", name="eprstmt", splits=["train_0"])
```

**Comment by HongLouyemeng** [comment]
> FewCLUE 中的 EPRSTMT 加载方式为
> 
> ```
> from paddlenlp.datasets import load_dataset
> data_ds = load_dataset("fewclue", name="eprstmt", splits=["train_0"])
> ```

thankyou
