### ISSUE TITLE
where function convert_from_path defined

### ISSUE THREAD

**Issue by LiemLin** [PaddlePaddle/PaddleNLP#3313]
https://github.com/PaddlePaddle/PaddleNLP/blob/77b65d3999046a501ca1383a8cdc329fe51e4dea/pipelines/pipelines/nodes/file_converter/pdf.py#L216

**Comment by w5688414** [comment]
请问您有碰到什么问题吗？这是pdf2image的一个函数，目前这个函数没有用上

https://pypi.org/project/pdf2image/

**Comment by LiemLin** [comment]
> 请问您有碰到什么问题吗？这是pdf2image的一个函数，目前这个函数没有用上
> 
> https://pypi.org/project/pdf2image/

您好,在pdf.py里216行提示这个函数找不到定义, 现在在头部加了from pdf2image import convert_from_path 可以了，谢谢
