### ISSUE TITLE
UIE多域/跨域事件抽取，schema如何构造，以及多个域都会得到抽取结果

### ISSUE THREAD

**Issue by LiZeng001** [PaddlePaddle/PaddleNLP#3314]
### 请提出你的问题

请问使用UIE框架进行事件抽取推理时，输入必须包含 句子+schema 这两部分吗？
如果必须包含schema，那么对于本身就不确定事件类型的语料(实际中语料都只有文本，不包含事件类型)，是无法给出对应的schema的，这个时候如何构造schema进行事件抽取呢？

查看了issue: https://github.com/PaddlePaddle/PaddleNLP/issues/3060
将多个领域的schema放入列表，进行了实验：

exp1: 
schema = [{"财经/交易-涨价触发词": ["涨价幅度", "涨价物", "涨价方"]}, 
                  {"灾害/意外-地震触发词": ["时间", "死亡人数", "震级", "震源深度", "震中", "受伤人数"]}, 
                  {"竞赛行为-胜负触发词": ["时间", "败者", "胜者", "赛事名称"]}]

sentence = "中国地震台网正式测定：05月08日04时39分在青海海西州直辖区（北纬37.37度，东经95.25度）发生3.6级地震，震源深度9千米。"

抽取结果：

     '灾害/意外-地震触发词': [{'end': 59,
                   'probability': 0.9999727012420863,
                   'relations': {'时间': [{'end': 23,
                                         'probability': 0.9999411114233254,
                                         'start': 11,
                                         'text': '05月08日04时39分'}],
                                 '震中': [{'end': 51,
                                         'probability': 0.9999450452525593,
                                         'start': 24,
                                         'text': '青海海西州直辖区（北纬37.37度，东经95.25度）'}],
                                 '震源深度': [{'end': 67,
                                           'probability': 0.9998922375800134,
                                           'start': 64,
                                           'text': '9千米'}],
                                 '震级': [{'end': 57,
                                         'probability': 0.999979019260536,
                                         'start': 53,
                                         'text': '3.6级'}]},
                   'start': 57,
                   'text': '地震'}],

      '竞赛行为-胜负触发词': [{'end': 59,
                  'probability': 0.9994660035402916,
                  'relations': {'时间': [{'end': 23,
                                        'probability': 0.9999411114233254,
                                        'start': 11,
                                        'text': '05月08日04时39分'}],
                                '败者': [{'end': 51,
                                        'probability': 0.41481362284264023,
                                        'start': 24,
                                        'text': '青海海西州直辖区（北纬37.37度，东经95.25度）'}],
                                '赛事名称': [{'end': 51,
                                          'probability': 0.8808113206599799,
                                          'start': 24,
                                          'text': '青海海西州直辖区（北纬37.37度，东经95.25度）'}]},
                  'start': 57,
                  'text': '地震'}]

可以看到，该句也被认为可能是"竞赛行为-胜负"事件，并抽出了对应的role.

exp2：将duee_event_schema.json中的65个schema全部放入列表，进行抽取：
![image](https://user-images.githubusercontent.com/38687113/191157079-6e9d29d3-6608-4453-8c2f-b70203598bc5.png)

sentence = "法国当地时间5月24日晚，备受瞩目的第72届戛纳国际电影节终于迎来了它的闭幕式。和开幕式不同的是，遭到群嘲的中国“毯星”这一次没有出现在红毯上，亮相的不是巨星就是大牌，可以说是星光熠熠，璀璨夺目。"

执行时间很长，其实就是遍历了所有65个schema，且有43个域都被认为是可能的事件，抽出了对应的role，而真正正确的事件"组织行为-闭幕"的trigger概率并不是最高(0.9364732009919194)，结果如下：

    ......
     '财经/交易-跌停触发词': [{'end': 39,
                   'probability': 0.9995230367354324,
                   'relations': {'时间': [{'end': 12,
                                         'probability': 0.5083692776870592,
                                         'start': 0,
                                         'text': '法国当地时间5月24日晚'}]},
                   'start': 36,
                   'text': '闭幕式'}],

     '财经/交易-降价触发词': [{'end': 39,
                   'probability': 0.997306709221661,
                   'relations': {'时间': [{'end': 12,
                                         'probability': 0.5083692776870592,
                                         'start': 0,
                                         'text': '法国当地时间5月24日晚'}],
                                 '降价方': [{'end': 60,
                                          'probability': 0.9833840301492813,
                                          'start': 54,
                                          'text': '中国“毯星”'}],
                                 '降价物': [{'end': 60,
                                          'probability': 0.8853744640833838,
                                          'start': 54,
                                          'text': '中国“毯星”'}]},
                   'start': 36,
                   'text': '闭幕式'}],

     '组织行为-罢工触发词': [{'end': 39,
                  'probability': 0.9974859105896172,
                  'relations': {'所属组织': [{'end': 29,
                                          'probability': 0.9872974361417661,
                                          'start': 22,
                                          'text': '戛纳国际电影节'}],
                                '时间': [{'end': 12,
                                        'probability': 0.5083692776870592,
                                        'start': 0,
                                        'text': '法国当地时间5月24日晚'}]},
                  'start': 36,
                  'text': '闭幕式'}],

    '组织行为-闭幕触发词': [{'end': 39,
                  'probability': 0.9364732009919194,
                  'relations': {'地点': [{'end': 2,
                                        'probability': 0.9999485021373715,
                                        'start': 0,
                                        'text': '法国'}],
                                '时间': [{'end': 12,
                                        'probability': 0.5083692776870592,
                                        'start': 0,
                                        'text': '法国当地时间5月24日晚'}],
                                '活动名称': [{'end': 29,
                                          'probability': 0.9999808073864926,
                                          'start': 18,
                                          'text': '第72届戛纳国际电影节'}]},
                  'start': 36,
                  'text': '闭幕式'}],

      '财经/交易-出售/收购触发词': [{'end': 39,
                      'probability': 0.8433823223027588,
                      'relations': {'时间': [{'end': 12,
                                            'probability': 0.5083692776870592,
                                            'start': 0,
                                            'text': '法国当地时间5月24日晚'}]},
                      'start': 36,
                      'text': '闭幕式'}],
     .......

所以总结起来问题就是：
1. 对于不知道事件域的语料，schema如何构造？
2. 采用遍历现有schemas的方式，开销巨大，且会出现多个不相关事件域也抽取出信息，导致无法判断哪个是正确的域。请问有什么解决思路吗？
谢谢!

**Comment by linjieccc** [comment]
@LiZeng001 你好，

1. 因为是开放域抽取，所以输入必须包含schema以引导模型抽取相应结果。对于事件域未知的语料，一阶段的抽取目标可以用『触发词』代替，例如：
```text
{"触发词": ["时间", "赛事名称"]}
```
相比零样本直接调用，更推荐在场景相关的语料上标注少量数据进行微调定制

2. 我们提供了UIE数据蒸馏的解决方案，可以将开放域抽取转为封闭域抽取，这样就不会有schema遍历的问题，具体可以参考这里的例子：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie/data_distill

**Comment by LiZeng001** [comment]
> @LiZeng001 你好，
> 
> 1. 因为是开放域抽取，所以输入必须包含schema以引导模型抽取相应结果。对于事件域未知的语料，一阶段的抽取目标可以用『触发词』代替，例如：
> 
> ```
> {"触发词": ["时间", "赛事名称"]}
> ```
> 
> 相比零样本直接调用，更推荐在场景相关的语料上标注少量数据进行微调定制
> 
> 2. 我们提供了UIE数据蒸馏的解决方案，可以将开放域抽取转为封闭域抽取，这样就不会有schema遍历的问题，具体可以参考这里的例子：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie/data_distill

您好，谢谢回答。仍存在一些问题：
对于#1，如果语料事件域未知，则整个schema都未知，那对应的role列表也是未知的，所以示例中的["时间", "赛事名称"]也是无法给出的啊。

对于#2，建议的思路是转化为封闭域，对于数据的要求是同域同分布。而实际的情况是，所有语料可能涉及N个不同的事件域，但是每条语料具体属于哪个域未知，因此无法转为封闭域抽取。除了[LIC2021事件抽取任务基线](https://aistudio.baidu.com/aistudio/projectdetail/1639964 )中给出的枚举分类的思路(需要增加一级pipiline)，有没有什么方法可以获得语料的事件域呢？这样就可以映射到预定义好的schema了。

**Comment by Yewx0310** [comment]
> 

请问您之前提到的问题解决了嘛

**Comment by zywang03** [comment]
请问您之前的问题是否得到解决？

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.
