### ISSUE TITLE
在finetune的时候，模型训练不进行

### ISSUE THREAD

**Issue by wxzwxz131** [PaddlePaddle/PaddleNLP#3317]
### 请提出你的问题

您好，finetune的时候，一直只出现下面的字样，不进行训练，过一段时间就自动关闭了

W0920 12:04:15.214025 399505 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.1
W0920 12:04:15.216866 399505 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.

**Comment by linjieccc** [comment]
@wxzwxz131 可以先参考官网的方式验证下paddlepaddle gpu版本是否安装成功：

```python
import paddle
paddle.utils.run_check()
```

完整文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
