### ISSUE TITLE
[Question]: HTTPSConnectionPool

### ISSUE THREAD

**Issue by Gavingx** [PaddlePaddle/PaddleNLP#3318]
### 请提出你的问题

paddlenlp==2.4
paddlepaddle-gpu==2.3
python==3.8

运行https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class    
下的案例时，下载ernie3词表错误。
![image](https://user-images.githubusercontent.com/43789460/191179619-d156fa1d-d81e-4660-80a9-baf349d03048.png)

**Comment by lugimzzz** [comment]
看上去是你运行环境SSL认证有问题，建议百度SSL: CERTIFICATE_VERIFY_FAILED报错对应的解决方式。

**Comment by Gavingx** [comment]
> 看上去是你运行环境SSL认证有问题，建议百度SSL: CERTIFICATE_VERIFY_FAILED报错对应的解决方式。

好的已经解决了，我把paddlenlp的源码拉下来直接在源码上改了
