### ISSUE TITLE
使用多标签分类中的提示学习训练新模型之后，运行预测代码infer.py出现问题

### ISSUE THREAD

**Issue by moshizhiyin** [PaddlePaddle/PaddleNLP#3319]
具体报错：
 [E:onnxruntime:, sequential_executor.cc:364 Execute] Non-zero status code returned while running Mul node. Name:'p2o.Mul.118' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:523 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 255 by 256

Traceback (most recent call last):
  File "infer_fewshot.py", line 239, in <module>
    predictor.predict(text_list)
  File "infer_fewshot.py", line 139, in predict
    infer_result = self.infer_batch(encoded_inputs)
  File "infer_fewshot.py", line 159, in infer_batch
    results = self._infer(input_dict)
  File "infer_fewshot.py", line 146, in _infer
    infer_data = self.inference_backend.infer(input_dict)
  File "infer_fewshot.py", line 119, in infer
    result = self.predictor.run(None, input_dict)
  File "/home/oem/anaconda3/envs/paddleuie/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'p2o.Mul.118' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:523 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 255 by 256

这里我修改了最大句子长度到256，与训练时保持一致了

**Comment by LemonNoel** [comment]
这个应该是模型转换成 onnx 格式引起的问题，安装 paddlepaddle 的 develop 版本再导出模型应该可以解决。 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by moshizhiyin** [comment]
> 这个应该是转换成onnx格式引发的问题，安装paddlepaddle的develop版本再导出模型可以解决。[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop /install/pip/linux-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)

多谢解答！我试了一下，确实，重装develop版可以解决。

**Comment by liuzhipengchd** [comment]
> 这个应该是模型转换成 onnx 格式引起的问题，安装 paddlepaddle 的 develop 版本再导出模型应该可以解决。 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

现在的版本不会解决这个问题吗？？每次训练完还需要专门去构建一个新环境转换onnx吗

**Comment by liuzhipengchd** [comment]
> > 这个应该是转换成onnx格式引发的问题，安装paddlepaddle的develop版本再导出模型可以解决。[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop /install/pip/linux-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)
> 
> 多谢解答！我试了一下，确实，重装develop版可以解决。

我也遇到了同样的问题
 return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'p2o.Mul.120' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 127 by 128


我装了develop版本，但是还是没有解决这个问题。训练的时候paddle 也必须是develop的版本吗？
paddle2onnx                      1.0.0
paddlepaddle                     0.0.0

**Comment by liuzhipengchd** [comment]
> > 这个应该是转换成onnx格式引发的问题，安装paddlepaddle的develop版本再导出模型可以解决。[https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop /install/pip/linux-pip.html](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)
> 
> 多谢解答！我试了一下，确实，重装develop版可以解决。

我也遇到了同样的问题
 return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'p2o.Mul.120' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 127 by 128


我装了develop版本，但是还是没有解决这个问题。训练的时候paddle 也必须是develop的版本吗？
paddle2onnx                      1.0.0
paddlepaddle                     0.0.0

**Comment by LemonNoel** [comment]
不需要重新训练，重装完develop版本，加载已保存的模型使用[模型导出命令](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label/few-shot#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)重新导出即可。
我再看看当前paddlepaddle版本这个能不能绕过去。

**Comment by liuzhipengchd** [comment]
> 不需要重新训练，重装完develop版本，加载已保存的模型使用[模型导出命令](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label/few-shot#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)重新导出即可。 我再看看当前paddlepaddle版本这个能不能绕过去。

我重装完develop版本了，然后对gpu训练的模型进行export，还是遇到了 ONNXRuntimeError  dimension other than 1. 127 by 128 这个错误

**Comment by LemonNoel** [comment]
也是在推理时报错么，方便提供下系统环境以及paddlepaddle、paddlenlp、paddle2onnx、onnxruntime的版本么？我这边尝试复现一下。另外如果之前安装的就是 `paddlepaddle` 的develop版本，需要先 `pip uninstall` 才能安装最新版本。

**Comment by liuzhipengchd** [comment]
> 也是在推理时报错么，方便提供下系统环境以及paddlepaddle、paddlenlp、paddle2onnx、onnxruntime的版本么？我这边尝试复现一下。另外如果之前安装的就是 `paddlepaddle` 的develop版本，需要先 `pip uninstall` 才能安装最新版本。

对的，是在执行CPU端推理样例时候报错

1、paddlepaddle 安装使用的
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/mac/cpu/develop.html

paddle2onnx                      1.0.0
paddlepaddle                     0.0.0
onnxruntime                      1.9.0

paddlenlp  使用的是git的develop分支

2、export_checkpoint中的文件包括 
model.pdiparams		model.pdiparams.info	model.pdmodel		template.json		verbalizer.json

执行命令
python infer.py --model_path_prefix export_checkpoint/export/model --data_dir ./data --batch_size 32 --device cpu

**Comment by liuzhipengchd** [comment]
> 也是在推理时报错么，方便提供下系统环境以及paddlepaddle、paddlenlp、paddle2onnx、onnxruntime的版本么？我这边尝试复现一下。另外如果之前安装的就是 `paddlepaddle` 的develop版本，需要先 `pip uninstall` 才能安装最新版本。

转换失败会生成一个onnx模型文件，可以加载，也可以打印出输入层 ['input_ids', 'mask_ids', 'soft_token_ids']，输出层['tmp_53']
但是执行推理的时候就会报错
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Mul node. Name:'p2o.Mul.120'

这个nodename ，和export模型时候的错误是一样的 Name:'p2o.Mul.120'

**Comment by LemonNoel** [comment]
export模型时也会报错吗？有的话可以贴下图么

**Comment by liuzhipengchd** [comment]
> export模型时也会报错吗？有的话可以贴下图么
@LemonNoel 
export的不会报错，可以正常导出。
就是infer的时候会报错
