### ISSUE TITLE
where RayPipeline define? 

### ISSUE THREAD

**Issue by LiemLin** [PaddlePaddle/PaddleNLP#3326]
https://github.com/PaddlePaddle/PaddleNLP/blob/31a8dc5c247dc73641ffab52effc784ebf610b9b/pipelines/pipelines/pipelines/base.py#L207

**Comment by w5688414** [comment]
you can remove the following code, because the `RayPipeline ` is not used in this release, this function may be added in a future relsease:

```
elif pipeline_definition["type"] == "RayPipeline":
            return RayPipeline.load_from_config(
                pipeline_config=pipeline_config,
                pipeline_name=pipeline_name,
                overwrite_with_env_variables=overwrite_with_env_variables,
            )```

**Comment by LiemLin** [comment]
ok thanks
