### ISSUE TITLE
where MultiLabel define?

### ISSUE THREAD

**Issue by LiemLin** [PaddlePaddle/PaddleNLP#3327]
https://github.com/PaddlePaddle/PaddleNLP/blob/31a8dc5c247dc73641ffab52effc784ebf610b9b/pipelines/pipelines/pipelines/base.py#L382

**Comment by w5688414** [comment]
```
from pipelines.schema import Document, Label, MultiLabel
```
https://github.com/PaddlePaddle/PaddleNLP/blob/31a8dc5c247dc73641ffab52effc784ebf610b9b/pipelines/pipelines/schema.py#L514

请问您是在什么环境下碰见这部分有问题的

**Comment by LiemLin** [comment]
git clone https://github.com/PaddlePaddle/PaddleNLP.git
在Mac上用pycharm打开项目，发现代码里提示红色，找不到方法或类型

**Comment by LiemLin** [comment]
from pipelines.pipelines.schema import Document,MultiLabel
在import后面补上了MultiLabel可以了，谢谢
