### ISSUE TITLE
内置的检索模型是基于第几代ERINE？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#3331]
<center><img width="606" alt="288d93785cdec56f5cae2e74b8169e0" src="https://user-images.githubusercontent.com/57492327/191410903-ac43431c-df16-4f8d-99f0-d9bfce60d541.png"><img width="607" alt="724e96597a4a4849d84cd93f0dec41d" src="https://user-images.githubusercontent.com/57492327/191410923-df4e546a-efac-41e5-96c2-26ebcaaf6ba3.png"></center>

**Comment by w5688414** [comment]
ERNIE 3.0
