### ISSUE TITLE
PaddleNLP有关于：实体对齐、知识推理的相关算法嘛，或者推荐。看OpenKG有提供一些算法和知识图谱？

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#3340]
### Feature request

觉得目前UIE中提供实体命名、关系抽取以及其他预训练模型在一些数据集表现都挺好的，想自己构建一个demo图谱，问问有什么好的建议，在paddlenlp侧。

### Motivation

相关链接：

http://openkg.cn/home

https://kg.alibaba.com/tools/index.html

### Your contribution

PaddleNLP有关于：实体对齐、知识推理的相关算法嘛，或者推荐。看OpenKG有提供一些算法和知识图谱？

**Comment by wawltor** [comment]
在PaddleNLP没有构建知识图谱、知识推理的相关工作，在Paddle的套件有个PGL的工作可以做知识图谱的构建 
https://github.com/PaddlePaddle/PGL/tree/main/apps/Graph4KG
