### ISSUE TITLE
[Question]: UIE关系抽取时实体关系对应有误的问题

### ISSUE THREAD

**Issue by tianlu-1996** [PaddlePaddle/PaddleNLP#3341]
### 请提出你的问题

UIE模型微调后，进行关系抽取，实体的关系抽取有误
比如：文本中A的电话号存在，B、C的电话号不存在，但是抽取结果会把A的电话号也都匹配给B、C 且probability都0.99多
请问该如何调优呢？

**Comment by linjieccc** [comment]
推荐少量标注微调下，在评估阶段可以开debug模式看下每个类别的准确和召回率
