### ISSUE TITLE
[Question]: 关系抽取任务中，如何转换数据为UIE模型输入数据格式

### ISSUE THREAD

**Issue by hurun** [PaddlePaddle/PaddleNLP#3342]
### 请提出你的问题

提问之前，已完成以下行动：
1、百度谷歌未找到相关参考资料或脚本
2、官网文档提供的uie输入格式为doccano标注平台导出，业务数据未使用doccanno平台进行标注
3、已在历史issue通过doccanno、uie数据等关键词搜索，未找到解决方法。比较相似的提问为以下issue，但不是同一个类型且未提供相应脚本。https://github.com/PaddlePaddle/PaddleNLP/issues/2301

想使用自己的数据对uie进行微调，官方文档给的数据微调样例是docano标注导出的格式，尝试自行写脚本，但受限于doccano文档及多个id无法理解问题，未成功。想请教下普通标注的格式，如何进行转换为uie模型的输入格式，以下是真实业务场景数据及标注结果，还请指点一下。
每一行是json格式：
第一行
{"ID": "001", "sentence": "9号汽车故障报告综合情况:运行中发动机温度突然过高：故障判定：真故障。", "spo": [{"head": {"name": "发动机", "position": [16, 19]}, "tail": {"name": "温度突然过高", "position": [19, 25]}, "relation": "部件故障"}]}　	
	
第二行
{"ID": "002", "sentence": "诊断过程先观察中控锁控制单元线路，是否有线路断开，没发现有断开，查看电路图，发现车身和门子连接处有连接插头，拔下其插头，发现有腐蚀现象，用清洗剂清洗之后，发现连接插头已经腐蚀断开，经过清洗之后，用接线工具箱中的插头及工具进行接线，插入插头，进行试验，左前门各项功能恢复，最后用黄油涂抹插头，安装密封圈并涂抹密封胶，以防漏水，最后用5051清除故障码，故障消失。", "spo": [{"head": {"name": "连接插头", "position": [49, 53]}, "tail": {"name": "腐蚀", "position": [63, 65]}, "relation": "部件故障"}, {"head": {"name": "连接插头", "position": [79, 83]}, "tail": {"name": "腐蚀断开", "position": [85, 89]}, "relation": "部件故障"}]}

**Comment by linjieccc** [comment]
你好，

除了`start_offset`，`end_offset`和`label`可以直接从已有数据格式转换，这里需要给每个实体新增一个对应的id。
关系抽取数据格式相关的字段说明可以参考这里：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md#61-%E5%AF%BC%E5%87%BA%E6%8A%BD%E5%8F%96%E5%BC%8F%E5%92%8C%E5%AE%9E%E4%BD%93%E8%AF%84%E4%BB%B7%E7%BB%B4%E5%BA%A6%E7%BA%A7%E5%88%86%E7%B1%BB%E4%BB%BB%E5%8A%A1%E6%95%B0%E6%8D%AE

可以尝试把业务场景数据在doccano上标几条看下输出格式。

**Comment by wawltor** [comment]
```json
{
    "id": 38,
    "text": "百科名片你知道我要什么，是歌手高明骏演唱的一首歌曲，1989年发行，收录于个人专辑《丛林男孩》中",
    "relations": [
        {
            "id": 20,
            "from_id": 51,
            "to_id": 53,
            "type": "歌手"
        },
        {
            "id": 21,
            "from_id": 51,
            "to_id": 55,
            "type": "发行时间"
        },
        {
            "id": 22,
            "from_id": 51,
            "to_id": 54,
            "type": "所属专辑"
        }
    ],
    "entities": [
        {
            "id": 51,
            "start_offset": 4,
            "end_offset": 11,
            "label": "作品名"
        },
        {
            "id": 53,
            "start_offset": 15,
            "end_offset": 18,
            "label": "人物名"
        },
        {
            "id": 54,
            "start_offset": 42,
            "end_offset": 46,
            "label": "作品名"
        },
        {
            "id": 55,
            "start_offset": 26,
            "end_offset": 31,
            "label": "时间"
        }
    ]
}
```

**Comment by hurun** [comment]
> 你好，
> 
> 除了`start_offset`，`end_offset`和`label`可以直接从已有数据格式转换，这里需要给每个实体新增一个对应的id。 关系抽取数据格式相关的字段说明可以参考这里：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md#61-%E5%AF%BC%E5%87%BA%E6%8A%BD%E5%8F%96%E5%BC%8F%E5%92%8C%E5%AE%9E%E4%BD%93%E8%AF%84%E4%BB%B7%E7%BB%B4%E5%BA%A6%E7%BA%A7%E5%88%86%E7%B1%BB%E4%BB%BB%E5%8A%A1%E6%95%B0%E6%8D%AE
> 
> 可以尝试把业务场景数据在doccano上标几条看下输出格式。

entity id和relation id 是递增么，我在docanno标了一些数据，发现是递增的，即使是相同的实体和同一种关系
比如羡慕两条数据，head:故障灯，tail:亮，relation: 部件故障

{"id":1496,"text":"故障现象：发动;机怠速不规则抖动，故障灯亮","entities":[{"id":12,"label":"head","start_offset":17,"end_offset":20},{"id":13,"label":"tail","start_offset":20,"end_offset":21}],"relations":[{"id":2,"from_id":12,"to_id":13,"type":"部件故障"}]}

{"id":1500,"text":"故障现象：发动机和EPC故障灯亮","entities":[{"id":29,"label":"head","start_offset":12,"end_offset":15},{"id":30,"label":"tail","start_offset":15,"end_offset":16}],"relations":[{"id":9,"from_id":29,"to_id":30,"type":"部件故障"}]}

**Comment by wawltor** [comment]
是的，是一种递增关系

**Comment by hurun** [comment]
感谢回答，已完成转换脚本
