### ISSUE TITLE
uie在读取数据阶段内存溢出[Question]: 

### ISSUE THREAD

**Issue by natureLanguageQing** [PaddlePaddle/PaddleNLP#3343]
在自己的数据集上进行uie训练
数据集本身2000条不到 实体类别40+
目前调整过负样本比例 构建出来超过5万条训练语聊
因为uie的数据加载关闭了lazy loader在aistudio的A100 96GB内存的服务器上训练发生了数据预加载过程内存溢出问题
公开数据集测试未发现相关问题 因为公开数据集的类别更少

**Comment by linjieccc** [comment]
你好，可以排查下是否prompt或者result_list里面的结果太长了

**Comment by natureLanguageQing** [comment]
如果2000条数据都会占用巨大的内存。那怎么能避免占用巨大的内存呢？我改不明白了。拜托了。

**Comment by linjieccc** [comment]
@natureLanguageQing 按理说2000条数据不应该占用这么大的内存，可以排查下是不是训练数据的问题，导致reader出现死循环而出现内存溢出的情况

**Comment by westfish** [comment]
> 

请问你的训练或测试数据里面存不存在目标抽取片段，即result_list中的text，过长的情况，比如说下面这种情况：

'{"content": "俗话说“冬吃萝卜夏吃姜，不劳医生开药方”，自古以来中医也有“生姜治百病”的说法，称其有明显的解热、抗菌及消炎作用。但中国中医科学院研究生院教授杨力告诉《生命时报》记者，姜虽有非常高的食疗和药用价值，但也不是人人都适合吃，下面几类人尤其要注意。手脚心发热的人。这类人属于阴虚体质，是体内津液不足所导致。而生姜性温，会容易耗损津液，加重阴虚的程度，使津液亏损得更厉害，还会出现口干、眼干、心烦易怒、失眠等症状。眩晕耳鸣的人。有此症状的人多是由于肝火过旺导致的一些并发症所致，这类人本来就阳热亢盛，如果再吃过多的姜，相当于“火上浇油”。肝炎病人。一般情况下，肝炎病人都是忌吃姜的，因为常吃姜会加重其症状，生姜引起的燥热对炎症的消除不利。口臭的人。中医认为口臭是由胃热所致，生姜性温，胃热的人吃会加重原有的胃热，甚至引起牙痛、头痛、痔疮出血等症状。便秘人群。便秘多属于肠热，此时如果过食生姜，也会加重症状。咳痰较黄的人。痰黄的人是因为肺热肺燥，生姜性温，食用姜易加重症状。脱发的人。中医认为，头发与肾有密切关系，老年人肾精不足，肾阴亏虚，头发得不到充足的滋养，就会脱发，生姜性温，脱发的人食用，肾阴虚更甚，会加重脱发的程度。", "result_list": [{"text": "俗话说“冬吃萝卜夏吃姜，不劳医生开药方”，自古以来中医也有“生姜治百病”的说法，称其有明显的解热、抗菌及消炎作用。但中国中医科学院研究生院教授杨力告诉《生命时报》记者，姜虽有非常高的食疗和药用价值，但也不是人人都适合吃，下面几类人尤其要注意。手脚心发热的人。这类人属于阴虚体质，是体内津液不足所导致。而生姜性温，会容易耗损津液，加重阴虚的程度，使津液亏损得更厉害，还会出现口干、眼干、心烦易怒、失眠等症状。眩晕耳鸣的人。有此症状的人多是由于肝火过旺导致的一些并发症所致，这类人本来就阳热亢盛，如果再吃过多的姜，相当于“火上浇油”。肝炎病人。一般情况下，肝炎病人都是忌吃姜的，因为常吃姜会加重其症状，生姜引起的燥热对炎症的消除不利。口臭的人。中医认为口臭是由胃热所致，生姜性温，胃热的人吃会加重原有的胃热，甚至引起牙痛、头痛、痔疮出血等症状。便秘人群。便秘多属于肠热，此时如果过食生姜，也会加重症状。咳痰较黄的人。痰黄的人是因为肺热肺燥，生姜性温，食用姜易加重症状。脱发的人。中医认为，头发与肾有密切关系，老年人肾精不足，肾阴亏虚，头发得不到充足的滋养，就会脱发，生姜性温，脱发的人食用，肾阴虚更甚，会加重脱发的程度。", "start": 0, "end": 508}], "prompt": "答案"}\n'

**Comment by natureLanguageQing** [comment]
超长的话不会自动截断吗，ernie的max len也就 512呀。

**Comment by westfish** [comment]
实际上UIE的处理是将过长的输入分割为多个实例。但是目前这里可能有一个bug，就是UIE的reader在面对过长输入分割实例时,如果待抽取result超过最大输入上限会导致无限分割，最后内存溢出。

所以，就目前来说，你可以先对输入数据进行一下过滤或预处理控制一下待抽取内容的长度，后面我们会解决这个bug的。

**Comment by natureLanguageQing** [comment]
唉 关了关了 限制了数据集后  没异常了 解决了好多天
