### ISSUE TITLE
SemanticSearchPipeline生成的pipeline支持并行吗？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleNLP#3351]
在[简单！PaddleNLP带你十分钟搭建检索系统 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/4442670?channelType=0&channel=0)使用 `pipelines.pipelines.SemanticSearchPipeline`生成管道，然后每次输入1个query。
现有一个数据集，有办法一次输入多个query然后并行查询吗？如果有，请问如何实现？

**Comment by yt605155624** [comment]
你好，已经 assign 给 PaddleNLP 相关的同学跟进了，之后相关问题可以直接到 PaddleNLP 提问

**Comment by w5688414** [comment]
> ### 请提出你的问题 Please ask your question
> 在[简单！PaddleNLP带你十分钟搭建检索系统 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/4442670?channelType=0&channel=0)使用 `pipelines.pipelines.SemanticSearchPipeline`生成管道，然后每次输入1个query。 现有一个数据集，有办法一次输入多个query然后并行查询吗？如果有，请问如何实现？

目前暂时可以使用FastAPI后端进行异步并发访问并行，请问您是什么场景的搜索？为啥有并行的需求？

**Comment by ghost** [comment]
如何用FastAPI实现有样例脚本吗？
目前有个私有的数据集，每条数据集是用户输入的问题和相匹配的标准问题，我想测试PaddleNLP内置的模型能否将输入的问题匹配到相应的问题上。因为有数万条数据，如果一次只输入1条好慢。

**Comment by w5688414** [comment]
@Ywandung-Lyou  please refer to this pr. https://github.com/PaddlePaddle/PaddleNLP/pull/3432
