### ISSUE TITLE
paddlenlp.layers.GPLinkerForEventExtraction 参数label_maps["label2id"]询问，及UIE蒸馏询问。

### ISSUE THREAD

**Issue by Alone749-i** [PaddlePaddle/PaddleNLP#3354]
### 软件环境

```Markdown
-paddle-bfloat             0.1.7
-paddle-serving-app        0.9.0
-paddle-serving-client     0.9.0
-paddle-serving-server-gpu 0.9.0.post1028
-paddle2onnx               0.9.8
-paddlefsl                 1.1.0
-paddlenlp                 2.4.0
-paddlepaddle-gpu          2.3.1.post111
```

### 详细描述

```Markdown
class GPLinkerForEventExtraction(nn.Layer):

    def __init__(self, encoder, label_maps, head_size=64):
        super().__init__()
        self.encoder = encoder
        hidden_size = encoder.config["hidden_size"]
        num_labels = len(label_maps['label2id'])
        gpcls = GlobalPointer

        self.argu_output = gpcls(hidden_size, num_labels, head_size=head_size)
        self.head_output = gpcls(hidden_size,
                                 1,
                                 head_size=head_size,
                                 RoPE=False)
        self.tail_output = gpcls(hidden_size,
                                 1,
                                 head_size=head_size,
                                 RoPE=False)

    def forward(self, input_ids, attention_mask):
        # input_ids, attention_mask, token_type_ids: (batch_size, seq_len)
        context_outputs = self.encoder(input_ids, attention_mask=attention_mask)
        # last_hidden_state: (batch_size, seq_len, hidden_size)
        last_hidden_state = context_outputs[0]

        argu_output = self.argu_output(last_hidden_state, attention_mask)
        head_output = self.head_output(last_hidden_state, attention_mask)
        tail_output = self.tail_output(last_hidden_state, attention_mask)
        aht_output = (argu_output, head_output, tail_output)
        return aht_output

您好，想请问一下我想讲UIE-base微调后的模型蒸馏到GPLinkerForEventExtraction这个模型上面，这里的label_maps中的label2id应当如何构造，方便的话可以举一个例子吗？
在UIE蒸馏的文档中，task_typy="event_extraction" utils文档并没有看到根据schema生成 label_maps中的label2id相关信息。可以帮助解答一下疑惑吗，非常感谢。
```

**Comment by xxllp** [comment]
这种跨模型的也能蒸馏吗

**Comment by linjieccc** [comment]
你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是``GPLinkerForRelationExtraction``这个组网实现。``GPLinkerForEventExtraction``需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到

**Comment by Alone749-i** [comment]
> 这种跨模型的也能蒸馏吗

目前阅读UIE蒸馏压缩代码后，实现方式就是将UIE微调学习到的知识蒸馏到一个更快的模型上。这里的实现就是蒸馏到GPLinkerForRelationExtraction这个模型上，参考地址是科学空间中有一篇博客介绍到。

**Comment by Alone749-i** [comment]
> 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件]
(https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到

大佬请问UIE蒸馏可以用GPLinkerForEventExtraction这个做吗。

**Comment by Alone749-i** [comment]
> 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到

谢谢大佬解答，顺便向提另外一个疑问不知道是否方便解答。
schema = ["省份", {"地震触发词": ["范围", "损失"]}]如果是这样的，生成label_maps时对于实体 "省份" 会出现问题。

**Comment by Alone749-i** [comment]
> 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到

[Add data distillation for UIE](https://github.com/PaddlePaddle/PaddleNLP/pull/3136/commits/7ee1828b8b3b09ff55907a2489928779d7b9b39c#top)
#3136

大佬我看到在这个里面utils已经添加了对事件抽取的判断了，是打算针对事件抽取添加独立的蒸馏策略吗？

**Comment by Alone749-i** [comment]
> 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到

paddlenlp 2.4
paddlenlp/taskflow/information_extraction.py中函数 _run_model中的代码
        all_preds = ([], []) if self._task_type in [
            "opinion_extraction", "relation_extraction"
        ] else []
如果想事件抽取的话只能改task_type = "relation" 吗？

**Comment by linjieccc** [comment]
> > 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到
> 
> 谢谢大佬解答，顺便向提另外一个疑问不知道是否方便解答。 schema = ["省份", {"地震触发词": ["范围", "损失"]}]如果是这样的，生成label_maps时对于实体 "省份" 会出现问题。

是说实体省份会丢失还是？可以再详细描述下问题

**Comment by linjieccc** [comment]
> > 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到
> 
> paddlenlp 2.4 paddlenlp/taskflow/information_extraction.py中函数 _run_model中的代码 all_preds = ([], []) if self._task_type in [ "opinion_extraction", "relation_extraction" ] else [] 如果想事件抽取的话只能改task_type = "relation" 吗？

可以先在源码加上"event_extraction"，我们修复下，多谢提醒~

**Comment by Alone749-i** [comment]
> > > 你好，UIE事件抽取的蒸馏方法和关系抽取类似，用的是`GPLinkerForRelationExtraction`这个组网实现。`GPLinkerForEventExtraction`需要训练数据能够[析出独立事件](https://spaces.ac.cn/archives/8926#%E5%AE%8C%E5%85%A8%E5%AD%90%E5%9B%BE)，这个在UIE蒸馏中没有用到
> > 
> > 
> > 谢谢大佬解答，顺便向提另外一个疑问不知道是否方便解答。 schema = ["省份", {"地震触发词": ["范围", "损失"]}]如果是这样的，生成label_maps时对于实体 "省份" 会出现问题。
> 
> 是说实体省份会丢失还是？可以再详细描述下问题

在  uie/data_distill/utils.py 程序文件中函数schema2label_maps内

https://github.com/PaddlePaddle/PaddleNLP/blob/adf6fcad61fb843fba3b1836424e59a319e9bed9/model_zoo/uie/data_distill/utils.py#L338

当 task_type = relation时，若schema并非完全标准的只含有关系的结构例如：
               schema = ["省份", {"地震触发词": ["范围", "损失"]}]
此时省份会出现问题
node.children = [] 直接跳过。

entity2id = {}
    relation2id = {}
    schema_tree = build_tree(schema)
    schema_list = schema_tree.children[:]
    while len(schema_list) > 0:
    node = schema_list.pop(0)
    # print(node.children)
    if node.name not in entity2id.keys() and len(node.children) != 0:
    entity2id[node.name] = len(entity2id)

            # 添加了一个写死的判断不知道是否合适？
            elif node.name not in entity2id.keys() and node.name in ["疑问词"]:
                entity2id[node.name] = len(entity2id)
