### ISSUE TITLE
有关自定义数据集的问题

### ISSUE THREAD

**Issue by Biggg888** [PaddlePaddle/PaddleNLP#336]
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-10-b3285e4d9a69> in <module>
     10 
     11 # data_path为read()方法的参数
---> 12 map_ds = load_dataset(read, data_path='train.txt')
     13 iter_ds = load_dataset(read, data_path='train.txt')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/experimental/dataset.py in load_dataset(path, name, data_files, splits, lazy, **kwargs)
     60                  lazy=None,
     61                  **kwargs):
---> 62     module_path = DATASETS_MODULE_PATH + path
     63 
     64     reader_cls = import_main_class(module_path)
TypeError: can only concatenate str (not "function") to str

是按照https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_list.html的写法但是报错了

**Comment by smallv0221** [comment]
这里需要指定一下lazy参数
map_ds = load_dataset(read, data_path='train.txt',lazy=False)
iter_ds = load_dataset(read, data_path='train.txt',lazy=True)

并且确定安装了最新版本的paddlenlp

**Comment by Biggg888** [comment]
> 这里需要指定一下
> lazyParametermap_ds = load_dataset（read，data_path ='train.txt'，lazy = False）
> iter_ds = load_dataset（read，data_path ='train.txt'，lazy = True）
> 
> 并且确定安装了最新版本的paddlenlp

加了也没用  就是 加了没用之后取消掉才发了issues

**Comment by Biggg888** [comment]
13 # data_path为read()方法的参数
---> 14 map_ds = load_dataset(read, data_path='train.txt',lazy=False)
     15 iter_ds = load_dataset(read, data_path='train.txt',lazy=True)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/experimental/dataset.py in load_dataset(path, name, data_files, splits, lazy, **kwargs)
     60                  lazy=None,
     61                  **kwargs):
---> 62     module_path = DATASETS_MODULE_PATH + path
     63 
     64     reader_cls = import_main_class(module_path)
TypeError: can only concatenate str (not "function") to str

**Comment by smallv0221** [comment]
检查一下paddlenlp版本呢

**Comment by Biggg888** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/346


大佬可以帮我看一下新提的issue吗&nbsp; paddlenlp已升级到rc21




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午2:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 有关自定义数据集的问题 (#336)





 
检查一下paddlenlp版本呢
