### ISSUE TITLE
[NewFeature]: 离线下载模型

### ISSUE THREAD

**Issue by turkeymz** [PaddlePaddle/PaddleNLP#3360]
### 请提出你的问题

希望paddlenlp搭建建议的预训练模型HUB，在实际使用中遇到两个问题：

1. 在线加载模型（from_pretrained）时经常出现http异常，特别在词典这里，导致需要手动下载
2. 离线加载模型时，由于不知道模型地址，必须重复运行，通过错误信息获取下载地址

基于上面两个问题，希望paddlenlp搭建简单的HUB。不需要和huggingface一样完善，但起码可以通过页面找模型，再通过模型下载需要的文件。这个相对迫切，实在人手不够，也可以搭建框架，让外围开发者加入共同构建。

**Comment by wawltor** [comment]
你好，目前类似于huggingface hub的工作目前在产品的设计上已经有初步计划，后续我们可能将这部分工作放在paddlehub的产品来承接这个工作，后续可以在hub上手动下载模型

**Comment by turkeymz** [comment]
> 你好，目前类似于huggingface hub的工作目前在产品的设计上已经有初步计划，后续我们可能将这部分工作放在paddlehub的产品来承接这个工作，后续可以在hub上手动下载模型

请问大约什么时候开展paddlehub的产品？因为我们的服务器都是离线的，这导致我们不得不放弃paddlenlp而使用更容易获取模型的pytorch。

**Comment by wawltor** [comment]
> > 你好，目前类似于huggingface hub的工作目前在产品的设计上已经有初步计划，后续我们可能将这部分工作放在paddlehub的产品来承接这个工作，后续可以在hub上手动下载模型
> 
> 请问大约什么时候开展paddlehub的产品？因为我们的服务器都是离线的，这导致我们不得不放弃paddlenlp而使用更容易获取模型的pytorch。

您好，我们预计在Q4会开展这项工作，PaddleNLP在代码中提供具体的下载方式，如果在下载模型的时候有疑问可以将问题抛给开发的同学。

**Comment by turkeymz** [comment]
> > > 你好，目前类似于huggingface hub的工作目前在产品的设计上已经有初步计划，后续我们可能将这部分工作放在paddlehub的产品来承接这个工作，后续可以在hub上手动下载模型
> > 
> > 
> > 请问大约什么时候开展paddlehub的产品？因为我们的服务器都是离线的，这导致我们不得不放弃paddlenlp而使用更容易获取模型的pytorch。
> 
> 您好，我们预计在Q4会开展这项工作，PaddleNLP在代码中提供具体的下载方式，如果在下载模型的时候有疑问可以将问题抛给开发的同学。

收到，感谢回复
