### ISSUE TITLE
[Question]: 运行ernie-health，获取不到结果

### ISSUE THREAD

**Issue by yuwojiusi** [PaddlePaddle/PaddleNLP#3366]
### 请提出你的问题

通过paddle提供的AI studio 执行ernie-health 中的医疗关系抽取任务spo一直得不到结果，请问是什么问题啊？结果一直都是：

[2022-09-26 10:09:08,698] [    INFO] - input data: 慢性胰腺炎@从概念上讲，外照射可以起到抗炎和止痛作用，并且已经开始被用于非肿瘤性疼痛的治疗。
[2022-09-26 10:09:08,698] [    INFO] - detected entities and relations:

运行中提示一个警告：The tokenizer <class 'paddlenlp.transformers.electra.tokenizer.ElectraTokenizer'> doesn't have the faster version. Please check the map `paddlenlp.transformers.auto.tokenizer.FASTER_TOKENIZER_MAPPING_NAMES` to see which faster tokenizers are currently supported.

**Comment by JunnYu** [comment]
你好，aistudio上的paddlenlp版本可能有点老，你可以更新一下paddlenlp试一下。
`pip install -U paddlenlp`。

**Comment by yuwojiusi** [comment]
> 你好，aistudio上的paddlenlp版本可能有点老，你可以更新一下paddlenlp试一下。 `pip install -U paddlenlp`。

没有用呢，更新到最新的还是不行呢

**Comment by JunnYu** [comment]
那麻烦能不能提供一下你训练的代码以及参数或者aistudio项目链接？

**Comment by JunnYu** [comment]
你是用的默认参数运行的吧，默认参数是每隔100步的时候就会评估模型，而仅仅训练100步就开始评估，模型效果通常来说是不好的。可以发现loss是非常大的。
![image](https://user-images.githubusercontent.com/50394665/192183088-91198c30-97ea-40f7-a401-8777144067cf.png)
![image](https://user-images.githubusercontent.com/50394665/192183362-ccb37711-afba-49c0-aea0-0aaaeaaa7f00.png)

**Comment by yuwojiusi** [comment]
b

> 那麻烦能不能提供一下你训练的代码以及参数或者aistudio项目链接？

我用的是就是git上提供的demo代码，paddlenlp——model_zoo——ernie-health——cblue 下的train_spo 先训练拿到checkpoint模型，然后通过export_model导出静态模型图，在进入到paddlenlp——model_zoo——ernie-health——cblue-deploy-predictor执行infer_spo.py代码，全部用的demo代码，只在训练的时候改成对应的CMeIE库


[2022-09-26 10:29:35,902] [    INFO] - input data: 骶髂关节炎是明确诊断JAS的关键条件。若有肋椎关节病变会使胸部扩张度减小。
[2022-09-26 10:29:35,902] [    INFO] - detected entities and relations:
[2022-09-26 10:29:35,902] [    INFO] - -----------------------------
[2022-09-26 10:29:35,902] [    INFO] - input data: 稳定型缺血性心脏疾病@肥胖与缺乏活动也导致高血压增多。
[2022-09-26 10:29:35,903] [    INFO] - detected entities and relations:
[2022-09-26 10:29:35,903] [    INFO] - -----------------------------

**Comment by yuwojiusi** [comment]
> 你是用的默认参数运行的吧，默认参数是每隔100步的时候就会评估模型，而仅仅训练100步就开始评估，模型效果通常来说是不好的。可以发现loss是非常大的。 ![image](https://user-images.githubusercontent.com/50394665/192183088-91198c30-97ea-40f7-a401-8777144067cf.png) ![image](https://user-images.githubusercontent.com/50394665/192183362-ccb37711-afba-49c0-aea0-0aaaeaaa7f00.png)

对，但是checkpoint 我用的model-2000的。请教下这里你一般是怎么弄的？

**Comment by JunnYu** [comment]
我现在正在跑这个模型，等出结果了再给您反馈。
建议可以让模型多跑一会儿。因为默认参数使用了100个epoch了。
此外还可以关注一下loss，loss在非常大的情况下评估是没有意义的。

**Comment by JunnYu** [comment]
我咨询了一下做这个的同事。
她说SPO这个任务模型参数比较多，前期eval都是0的，loss大和model-2000推理不出结果都符合预期。
至少9000steps之后SPO F1才不为0，大概0.46左右，如果要达到README中的结果需要按给定的脚本训练完

**Comment by yuwojiusi** [comment]
> 我现在正在跑这个模型，等出结果了再给您反馈。 建议可以让模型多跑一会儿。因为默认参数使用了100个epoch了。 此外还可以关注一下loss，loss在非常大的情况下评估是没有意义的。

好的十分感谢！

**Comment by yuwojiusi** [comment]
> 我咨询了一下做这个的同事。 她说SPO这个任务模型参数比较多，前期eval都是0的，loss大和model-2000推理不出结果都符合预期。 至少9000steps之后SPO F1才不为0，大概0.46左右，如果要达到README中的结果需要按给定的脚本训练完

好的，谢谢，我试一下呢

**Comment by JunnYu** [comment]
你好，我训练了这么多后，结果终于不为0了，你也可以试一下。
```
15000 step
eval loss: 340.67661, entity f1: 0.76924, spo f1: 0.54797

```

**Comment by yuwojiusi** [comment]
> :



> 你好，我训练了这么多后，结果终于不为0了，你也可以试一下。
> 
> ```
> 15000 step
> eval loss: 340.67661, entity f1: 0.76924, spo f1: 0.54797
> ```

15000，那我还要几个小时。感谢反馈，我已经follow你了，希望能和你保持联系

**Comment by JunnYu** [comment]
你可以这么改，修改`valid_steps`每多少step评估一次和`save_steps`每多少步保存一次。
（原先的100步保存和评估太密集了，速度太慢了。）
```bash
export CUDA_VISIBLE_DEVICES=0
python train_spo.py --batch_size 12 --max_seq_length 300 --learning_rate 6e-5 --epochs 100 --save_steps 1000 --valid_steps 1000
```

**Comment by yuwojiusi** [comment]
> 你可以这么改，修改`valid_steps`每多少step评估一次和`save_steps`每多少步保存一次。 （原先的100步保存和评估太密集了，速度太慢了。）
> 
> ```shell
> export CUDA_VISIBLE_DEVICES=0
> python train_spo.py --batch_size 12 --max_seq_length 300 --learning_rate 6e-5 --epochs 100 --save_steps 1000 --valid_steps 1000
> ```

好的，我试一下呢
