### ISSUE TITLE
[Question]: UIE的词表以及预训练模型是怎么构建的

### ISSUE THREAD

**Issue by umbrellabeach** [PaddlePaddle/PaddleNLP#3368]
### 请提出你的问题

你好，uie-base模型的vocab词表包含了39980个词，比bert_zh版本多了快一倍，请问这个词表是怎么构建的？还想问一下，uie-base的预训练任务和使用的数据是什么样的，谢谢！

**Comment by linjieccc** [comment]
1.词表的构造可以参考这里，方法是类似的：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-1.0/vocab#2-%E5%85%A8%E5%AD%97%E7%AC%A6%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8%E5%88%B6%E4%BD%9C
2.UIE预训练会用到大量信息抽取数据让模型适配固定prompt，数据格式和微调阶段一致
