### ISSUE TITLE
[Question]: mac进行词性标注时会报MKLDNN的错，这个加速库不支持Mac，请问怎么解决？

### ISSUE THREAD

**Issue by we-enjoy-today** [PaddlePaddle/PaddleNLP#3369]
### 请提出你的问题

mac进行词性标注时会报MKLDNN的错，这个加速库不支持Mac，请问怎么解决？
![WechatIMG349](https://user-images.githubusercontent.com/96770068/192253329-f0afb839-c878-43b4-bfca-36c16523fe12.png)

**Comment by JunnYu** [comment]
你好，这个问题已经在微信群里解答。
MKLDNN不支持M1，上面的报错应该是warning，实际使用不影响效果。
```python
from paddlenlp import Taskflow
tag = Taskflow("pos_tagging")
output = tag(["第十四届全运会在西安举办"])
print(output)
# [('第十四届', 'm'), ('全运会', 'nz'), ('在', 'p'), ('西安', 'LOC'), ('举办', 'v')]
```

**Comment by we-enjoy-today** [comment]
> 你好，这个问题已经在微信群里解答。 MKLDNN不支持M1，上面的报错应该是warning，实际使用不影响效果。
> 
> ```python
> from paddlenlp import Taskflow
> tag = Taskflow("pos_tagging")
> output = tag(["第十四届全运会在西安举办"])
> print(output)
> # [('第十四届', 'm'), ('全运会', 'nz'), ('在', 'p'), ('西安', 'LOC'), ('举办', 'v')]
> ```

好的，谢谢~~
