### ISSUE TITLE
[Question]: 請問如何在run_c3.py 使用自己的dataset?

### ISSUE THREAD

**Issue by tobias861222** [PaddlePaddle/PaddleNLP#3372]
目前使用ERNIE3.0-medium-zh, 已完成fine-tuning可以用run_c3.py - do predict去預測c3的test dataset.

我的需求是 想使用自己的資料來做預測
作法的部分
因為c3的公開資料集格式是採用.json
因此自己也想用.json來做預測，所以直接先用讀取c3的.json做預測
做法如下
在run_c3.py內修改test_ds讀取的方式
![image](https://user-images.githubusercontent.com/96098258/192296707-be5a7a5f-ae74-4ff2-85b7-85ea954f5f1e.png)

但會出現以下error
![image](https://user-images.githubusercontent.com/96098258/192296819-e0f59d82-db50-4e55-b0ac-be685a3677f4.png)
之前爬過文
看到可能的解決方法是.json裡的資料形態要採用.jsonl的方式
因此將.json裡的型態改成以下型態
![image](https://user-images.githubusercontent.com/96098258/192297192-1651c77e-b3c8-4a4a-8e2b-351d520d1ab6.png)

雖可以run，但預測輸出結果都不正確。
例如我嘗試測試五題相同的題目，但output的結果居然會不同。
![image](https://user-images.githubusercontent.com/96098258/192297789-f3ffe2ac-7c14-4f57-89a5-bf725dedd2b4.png)
![image](https://user-images.githubusercontent.com/96098258/192297829-bcfc334d-0012-4d17-9817-588cb1020cd0.png)

因此問題是
是否可以用.json作預測，若可以應該使用什麼形式?
感謝!

**Comment by LiuChiachi** [comment]
如果您的测试数据和原始examples的测试数据格式相同，网络能接受输入、进行前向计算，并且最终有输出，那么应该不是格式的问题。
关于预测结果不一样，您可以尝试下在预测之前设置以下代码：
```
model.eval()
```
应该能关闭随机性进行正常预测。
如果有问题我们继续交流

**Comment by tobias861222** [comment]
非常感謝 預測結果正常了!
