### ISSUE TITLE
Electra代码问题疑惑

### ISSUE THREAD

**Issue by THCNF** [PaddlePaddle/PaddleNLP#3374]
### 问题描述

![cc0323effdb6bdba4b5af5677d3dcd0](https://user-images.githubusercontent.com/47071679/192453780-de0d725e-8f1a-47d9-8311-e4b18ced4a75.jpg)
请问一下在paddleNLP包里面class ElectraPretrainedModel这个类包含的
tie_word_embeddings = True   （1）
untied_generator_embeddings = False   （2）
这两个分别是控制什么的呢？我看代码和实验发现第一个是会控制到electra的生成器的word-embeding是否参与训练，第二个是控制生成器和判别器的word-embeding是否绑定为一起。
然后我的目的是想要修改代码让这个模型的生成器和判别器分别独自训练不共享word-embeding的参数，但是我发现第二个控制设置为不共享词嵌入的时候，并且（1）设置为True的时候结果为生成器的词嵌入层会梯度回传进行学习，但是判别器的词嵌入固定住不会进行训练。然后我试着将（1）设置为False的时候发先生成器和判别器的词嵌入层都会固定住不进行学习。
所以我发现这个electra的判别器本身不会自己学习词嵌入层，得绑定的和生成器一样跟着生成器一起学习才行。
以上是我实验发现的，如有不对麻烦指导一下我。
总结：
electra的判别器如果不用（2）绑定的和生成器一样的话，生成器的word-embeding不会梯度回传学习要怎么解决？
或者我就是想要让生成器和判别器能独自的训练，如有更好的实现方式请指教一下。

**Comment by LemonNoel** [comment]
- `tie_word_embeddings`是generator的参数，若为 `True`，则生成器最后一层隐藏层到词表的转换直接使用 `word_embedding`，否则额外定义一层网络。
- `untied_generator_embeddings`决定了生成器和判别器的`word_embedding`是否共享。这个是 [Electra 原论文](https://arxiv.org/pdf/2003.10555.pdf) 中的一个策略，不想共享的话设为`True`即可。

生成器 `word_embedding` 不会梯度回传的问题可以再详细描述一下么，如果计算了生成器的loss，理论上是有梯度的。

**Comment by THCNF** [comment]
好的谢谢，梯度回传的问题好像有回传了，不知道可能是我前面那里搞错了
