### ISSUE TITLE
Electra 代码问题

### ISSUE THREAD

**Issue by THCNF** [PaddlePaddle/PaddleNLP#3379]
### 问题描述

你好，在electra的论文中说到有生成器和判别器组成，而且判别器的模型结构和bert-base的一样，请问在paddle github上发布的electra代码中初始化好一个从0开始的框架后，我想要把官方发布的bert-base-uncase的模型参数加载到他的判别器中请问要怎么修改代码呢？
![图片](https://user-images.githubusercontent.com/47071679/192680694-b6fa687d-cbf1-4b45-9650-30455f044a81.png)
![图片](https://user-images.githubusercontent.com/47071679/192680816-031c56f3-94eb-444e-90e8-93e055956031.png)

源码中有这个判别器的加载参数的代码，我直接把bert-base-uncase的pdparams的文件替换掉这个要加载参数的文件中的pdparams文件。但是发现模型判别器的参数加载没有报错但是也没有加载成功！
这个左边是electra判别器的模型配置，右边是bert的。

总结：我想要把bert-base的预训练好的文件加载到刚初始化好的electra的判别器中要怎么操作呢？

**Comment by THCNF** [comment]
![图片](https://user-images.githubusercontent.com/47071679/192681597-9b379433-9cd1-44c0-9545-af19bf5190a2.png)
对应的配置文件图

**Comment by LemonNoel** [comment]
参数加载时是按照参数名逐一赋值的，不同模型名字不对应所以会直接跳过不会赋值也不会报错。大致的加载步骤如下：
1. ElectraModel初始化之后打印 discriminator.state_dict().keys()得到各层参数的名称
2. `paddle.load`加载BERT模型后也会得到一个参数的字典，将key逐一替换为ElectraModel对应层的名称
3. 因为BERT和ElectraModel的字典大小不一样，需要处理一下生成一个和ElectraModel `word_embedding`大小相同的参数矩阵，比如拼6个[UNK]向量。
4. 用`set_state_dict`把处理后的字典赋值给ElectraModel

**Comment by THCNF** [comment]
我找到了一个方式实现但不知有没有问题：
具体如下：
![image](https://user-images.githubusercontent.com/47071679/192784591-2e01b09e-bc21-4da8-937b-b05d4ca422c3.png)
![image](https://user-images.githubusercontent.com/47071679/192784843-ca36e25b-53e3-4e83-999e-f9d5c099144c.png)
![image](https://user-images.githubusercontent.com/47071679/192787874-64d54f78-13fd-436a-8b4d-26c25d34cd62.png)

我根据代码把ElectraDiscriminator需要的参数由ElectraModel变成BertModel并加载上预训练参数，然后关掉ElectraDiscriminator里面的self.init_weights() 随机初始化，然后关于字典大小的不同，我发现是由第三个图造成electra的字典比bert大了6个，我将其注释掉，综上好像实现了我想要的功能，但是我发现加载了700多M的bert-base预训练的参数后训练几个步保存的判别器的pdparam文件大小确只有400多M的大小。然后我使用这个400多M的参数文件去跑了下glue的sst-2任务跑了2W步的结果为：
![image](https://user-images.githubusercontent.com/47071679/192791149-7588d4f9-93b3-4271-9362-737d248f0e6a.png)
不知道这个参数文件运行变小现象是正常还是我加载参数出了问题没有全部加载上。

**Comment by THCNF** [comment]
![image](https://user-images.githubusercontent.com/47071679/192937820-575e1411-7886-4797-a571-ffee2a0d34bc.png)
下载的预训练模型为700多M，立马保存下来只有400M是正常现象吗

**Comment by LemonNoel** [comment]
可以打印下每层参数的均值，看看是否初始化成功。
第三个图是为了将其变为8的倍数，优化AMP训练，具体vocab看config参数。
模型保存是用的哪个API呢？
