### ISSUE TITLE
[Docs]: PaddleNLP/applications/neural_search/recall/in_batch_negative/

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#3380]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 详细描述

```Markdown
代码与readme内容不一致
```

**Comment by w5688414** [comment]
> 

请问是哪个地方不一致呢？有详细信息吗？

**Comment by kg-nlp** [comment]
![image](https://user-images.githubusercontent.com/58376804/192993767-e925f226-01fb-4437-ab09-584043cb8600.png)

命令行参数similar_text_pair 重复，实际源码中train_batch_neg是similar_text_pair_file

**Comment by kg-nlp** [comment]
neural_serch/ranking/cross_encoder/deploy/python/web_service.py  第69行
![image](https://user-images.githubusercontent.com/58376804/192994499-5d11a1fa-309b-4426-b4d0-441f6dcdb892.png)
str(sim_score) 应该为 str(sim_score.tolist())

**Comment by w5688414** [comment]
> similar_text_pair_file

请问您用的是什么环境？为什么需要转list？

**Comment by kg-nlp** [comment]
下载的最新版的代码，cross_encoder 模型服务返回的分数类型为numpy,不转成 list,在客户端请求
result = np.array(eval(ret.value[0])) ，ret.value[0] 会报错

**Comment by w5688414** [comment]
我在0.9的环境测试没问题，请问您的是什么serving环境：
```
paddle-serving-app             0.9.0
paddle-serving-client          0.9.0
paddle-serving-server          0.9.0
```


> 下载的最新版的代码，cross_encoder 模型服务返回的分数类型为numpy,不转成 list,在客户端请求 result = np.array(eval(ret.value[0])) ，ret.value[0] 会报错
