### ISSUE TITLE
Electra 模型增加对输入 `past_key_values` 和 `inputs_embeds` 的支持

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/PaddleNLP#3382]
### Feature request

Electra 模型增加对输入 `past_key_values` 和 `inputs_embeds` 的支持。可以参考 [ERNIE 中对应的代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L890)

### Motivation

通过 `past_key_values` 和 `inputs_embeds` 输入可以支持 Prefix-Tuning、P-Tuning这样一些工作。

**Comment by sijunhe** [comment]
Hi @guoshengCS. I'll be happy to take this. Would you assign this to me?

**Comment by sijunhe** [comment]
I will break `past_key_values` and `inputs_embeds` into two separate PRs for easy reviews.
The PR for `inputs_embeds` is ready for review at #3401

**Comment by sijunhe** [comment]
#3411 ready for review as well

**Comment by guoshengCS** [comment]
>  I'll be happy to take this. Would you assign this to me?
I will break past_key_values and inputs_embeds into two separate PRs for easy reviews.

Good start and no problem !  And sorry for the missing of messages in holidays.
