### ISSUE TITLE
版本变动太大，无缘无故出现bug

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleNLP#3387]
### 请提出你的问题

本地开发的环境，之前一直运行没问题； 今天再跑模型，就出现以下bug，很奇怪，我也没有重新安装新的版本

/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 3 positional arguments but 5 were given

**Comment by guoshengCS** [comment]
请问是使用的哪个代码，使用的paddlenlp的版本是什么呢，我们复现排查看下。

> 本地开发的环境，之前一直运行没问题； 今天再跑模型，就出现以下bug，很奇怪，我也没有重新安装新的版本

如果使用代码没变，paddlenlp版本也没变，突然跑不通是有些奇怪的

**Comment by kevinuserdd** [comment]
> 请问是使用的哪个代码，使用的paddlenlp的版本是什么呢，我们复现排查看下。
> 
> > 本地开发的环境，之前一直运行没问题； 今天再跑模型，就出现以下bug，很奇怪，我也没有重新安装新的版本
> 
> 如果使用代码没变，paddlenlp版本也没变，突然跑不通是有些奇怪的

paddlenlp              2.3.4
paddlepaddle           2.2.0
我也搞不懂，之前conda里面的环境都训练没问题，今天再跑一下就报这个错

**Comment by guoshengCS** [comment]
可否也提供下出问题的代码呢，我们复现下

**Comment by kevinuserdd** [comment]
> 可否也提供下出问题的代码呢，我们复现下

finetune.py里面的”            start_prob, end_prob = model(input_ids, token_type_ids, att_mask, pos_ids)“ 这里开始报错的； 因为之前我本地pip 安装的paddle和paddlenlp包，按道理不会自动更新，我没有更新版本； 之前没问题，今天服务器和本地都是这个错，你们复现估计有难度，我这个版本是没问题吧？ paddlenlp=2.3.4,paddle=2.2.0

**Comment by kevinuserdd** [comment]
> 可否也提供下出问题的代码呢，我们复现下

而且，我想说，你们的文档能不能准时的更新？ 比如paddlenlp的安装文档里面写的”pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple“  这个根本就不能执行，至少安装教程要写的很正确，。。。哎

**Comment by gongel** [comment]
你好，可以提供下复现代码吗？我们更新下对应的文档和版本
