### ISSUE TITLE
在同时具备cpu和gpu的环境中，希望支持使用cpu执行Taskflow

### ISSUE THREAD

**Issue by YoungHector** [PaddlePaddle/PaddleNLP#3389]
### Feature request

![6E48899D660CF1F74F30EC1847649492](https://user-images.githubusercontent.com/19471295/192949020-321b4879-2448-4e64-843a-6ccbd2d7b377.jpg)
当前使用 get_env_device方法来获取设备，但get_env_device是根据paddle编译方式来获取的，在cuda环境中默认返回gpu. 因此即使存在cpu，也无法人为设置使用cpu运行taskflow.

希望改为在Taskflow当中通过paddle.get_device 方式获取当前任务设置的设备，使Taskflow与当前脚本全局的设备设置兼容.

### Motivation

有关，在开发阶段希望对比cpu和gpu上的运算效率差异等场合，需要Taskflow支持使用cpu运行。

### Your contribution

改动较小，暂不另起pr，辛苦相关开发人员了。

**Comment by linjieccc** [comment]
你好，GPU环境下如果希望使用CPU运行Taskflow可以指定device_id=-1

```python
from paddlenlp import Taskflow

uie = Taskflow('information_extraction', device_id=-1)
```

**Comment by gongel** [comment]
```python
# 指定2号卡
uie = Taskflow('information_extraction', device_id=2)
```
微信群已沟通解决，如果有问题可重开issue。
