### ISSUE TITLE
UIE关系抽取时同一句话存在多个关系怎么构建schema？

### ISSUE THREAD

**Issue by PanZheng-2021** [PaddlePaddle/PaddleNLP#3390]
### 请提出你的问题

1、比如一句话：交通很方便，房间小了一点，但是干净整洁，很有香港的特色，性价比较高，推荐一下哦

同时标注：
![image](https://user-images.githubusercontent.com/87333406/193006928-10e932eb-4dfc-47c5-a9dd-fdbf0dfbcffa.png)

分开标注：
![image](https://user-images.githubusercontent.com/87333406/193007200-9745c39a-e418-4ee5-b5f8-f5abffd68081.png)
![image](https://user-images.githubusercontent.com/87333406/193007447-a235c324-9ec9-4d9b-85b2-89fd584e7dd7.png)
![image](https://user-images.githubusercontent.com/87333406/193007596-10dd6d9f-9343-4d13-add3-89e36768453b.png)

这两种标注方式哪一种可行？

2、对于这两种标注的schema如何构造呢？

schema = [{'方面': ['具体描述']}]
schema = [{'方面': ['概括描述', '具体描述', '性能描述']}]

哪一种呢？

**Comment by PanZheng-2021** [comment]
还有就是关系数量不确定的时候，该怎么标注数据和构建schema？

**Comment by linjieccc** [comment]
推荐同时标注更高效一些，按照你的标注标签定义对应的schema应该是[{'方面': ['概括描述', '具体描述', '性能描述']}]

**Comment by PanZheng-2021** [comment]
那如果一句话里存在多个相同的关系，最后只会输出一个算法认为概率最大的关系。
能不能把所有可能的关系都提取出来。


比如对于这句话：早餐很好并且房间很干净


我想提取出（早饭，很好）和（房间，很干净）这两个（方面，意见）对。
这怎么操作呢？？


感觉这是个很重要的需求，因为一句话往往很长，会存在多个相同关系。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 晚上6:52
***@***.***&gt;;
抄送:&nbsp;"2021级  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] UIE关系抽取时同一句话存在多个关系怎么构建schema？ (Issue #3390)





 
推荐同时标注更高效一些，按照你的标注标签定义对应的schema应该是[{'方面': ['概括描述', '具体描述', '性能描述']}]

**Comment by linjieccc** [comment]
UIE默认会输出所有大于概率阈值的抽取结果

```python
>>> ie = Taskflow("information_extraction", schema={"评价维度":"观点词"})
>>> ie("早餐很好并且房间很干净")
>>> pprint(ie("早餐很好并且房间很干净"))
[{'评价维度': [{'end': 8,
            'probability': 0.9876017673144375,
            'relations': {'观点词': [{'end': 11,
                                   'probability': 0.989785349373669,
                                   'start': 9,
                                   'text': '干净'}]},
            'start': 6,
            'text': '房间'},
           {'end': 2,
            'probability': 0.9910050824061045,
            'relations': {'观点词': [{'end': 4,
                                   'probability': 0.9465834966908346,
                                   'start': 3,
                                   'text': '好'}]},
            'start': 0,
            'text': '早餐'}]}]
```

**Comment by PanZheng-2021** [comment]
> UIE默认会输出所有大于概率阈值的抽取结果
> 
> ```python
> >>> ie = Taskflow("information_extraction", schema={"评价维度":"观点词"})
> >>> ie("早餐很好并且房间很干净")
> >>> pprint(ie("早餐很好并且房间很干净"))
> [{'评价维度': [{'end': 8,
>             'probability': 0.9876017673144375,
>             'relations': {'观点词': [{'end': 11,
>                                    'probability': 0.989785349373669,
>                                    'start': 9,
>                                    'text': '干净'}]},
>             'start': 6,
>             'text': '房间'},
>            {'end': 2,
>             'probability': 0.9910050824061045,
>             'relations': {'观点词': [{'end': 4,
>                                    'probability': 0.9465834966908346,
>                                    'start': 3,
>                                    'text': '好'}]},
>             'start': 0,
>             'text': '早餐'}]}]
> ```

英文的提取能力是弱一点吗？
下面这个好像只能提取出来一个

schema = {'Aspect': 'Opinion'}
my_ie_en = Taskflow(task="information_extraction", schema=schema, model='uie-base-en')
pprint(my_ie_en('The teacher is very nice and lobby was club-like'))

结果：
[{'Aspect': [{'end': 34,
              'probability': 0.37996890862800115,
              'relations': {'Opinion': [{'end': 48,
                                         'probability': 0.637887301421145,
                                         'start': 39,
                                         'text': 'club-like'}]},
              'start': 29,
              'text': 'lobby'}]}]

**Comment by FrancisJ7** [comment]
> UIE默认会输出所有大于概率阈值的抽取结果
> 
> ```python
> >>> ie = Taskflow("information_extraction", schema={"评价维度":"观点词"})
> >>> ie("早餐很好并且房间很干净")
> >>> pprint(ie("早餐很好并且房间很干净"))
> [{'评价维度': [{'end': 8,
>             'probability': 0.9876017673144375,
>             'relations': {'观点词': [{'end': 11,
>                                    'probability': 0.989785349373669,
>                                    'start': 9,
>                                    'text': '干净'}]},
>             'start': 6,
>             'text': '房间'},
>            {'end': 2,
>             'probability': 0.9910050824061045,
>             'relations': {'观点词': [{'end': 4,
>                                    'probability': 0.9465834966908346,
>                                    'start': 3,
>                                    'text': '好'}]},
>             'start': 0,
>             'text': '早餐'}]}]
> ```

你好，请问这个UIE提取模块如何把输入文本的长度限制提升呢？我想改成max_seq_len=512，但没找到api
