### ISSUE TITLE
[Question]: 为什么没把ERNIE-Search放进来？

### ISSUE THREAD

**Issue by datalee** [PaddlePaddle/PaddleNLP#3397]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/13651873/193243922-d17806da-1e13-4ac1-8efb-b94fb438bd08.png)

**Comment by ZeyuChen** [comment]
@datalee 敬请期待，正在路上。

**Comment by sijunhe** [comment]
您好，@datalee. Ernie-Search已在v2.4.4发布
