### ISSUE TITLE
[Question]: UIE finetune Recall和F1始终在10%～20%

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/PaddleNLP#3403]
### 请提出你的问题

fine tune uie-base-en 模型， Recall和F1始终在10%～20%； 求大神指教。

![image](https://user-images.githubusercontent.com/30545972/194578488-16e4de4e-bed3-4fa0-a7f8-810667bba23e.png)

**Comment by wawltor** [comment]
是否可以发一些训练数据看看？

**Comment by jack-gits** [comment]
{"content": " ZKSMLQPWTBDURXYNF NH658IUL2501JF4 VAUFEROKCSDQX HCSETRPYAFUDKM", "result_list": [{"text": "NH658IUL2501JF4", "start": 19, "end": 34}], "prompt": "vin"}
{"content": " ZKSMLQPWTBDURXYNF  VAUFEROKCSDQX HCSETRPYAFUDKM", "result_list": [], "prompt": "vin"}
{"content": " NIGWPJKCSAYBL ULPDZHJTWANCXFKMV XUCIDKQWZMONYPT D1604MX4C0R72PT90", "result_list": [{"text": "D1604MX4C0R72PT90", "start": 49, "end": 66}], "prompt": "vin"}
{"content": " NIGWPJKCSAYBL ULPDZHJTWANCXFKMV XUCIDKQWZMONYPT ", "result_list": [], "prompt": "vin"}
{"content": " AOPWGHZYXNSLQJTE MHSFAJXWRCQUPVZTYG NZVWHPFCKEMLT TKWSNDUOYPHJXVLR 8H9D9X08937FBL1W", "result_list": [{"text": "8H9D9X08937FBL1W", "start": 68, "end": 84}], "prompt": "vin"}
{"content": " AOPWGHZYXNSLQJTE MHSFAJXWRCQUPVZTYG NZVWHPFCKEMLT TKWSNDUOYPHJXVLR ", "result_list": [], "prompt": "vin"}
{"content": " 26Q7FA019Y6M5CB8 VPSJFYGUKWENOZ OAJRQVPSULIHKGWM", "result_list": [{"text": "26Q7FA019Y6M5CB8", "start": 1, "end": 17}], "prompt": "vin"}
{"content": "  VPSJFYGUKWENOZ OAJRQVPSULIHKGWM", "result_list": [], "prompt": "vin"}
{"content": " INDXUFJOYLMETCW 2FI681LC784N9A5", "result_list": [{"text": "2FI681LC784N9A5", "start": 17, "end": 32}], "prompt": "vin"}
{"content": " INDXUFJOYLMETCW ", "result_list": [], "prompt": "vin"}

**Comment by jack-gits** [comment]
@wawltor 都是模拟生成的数据。

**Comment by wawltor** [comment]
看起来是数据是没有什么语义信息，如果是这份数据上做信息抽取看起来是很难做到很好的抽取效果；真实的数据也是这种吗？
