### ISSUE TITLE
[Bug]: https://bj.bcebos.com/paddlenlp/models/community/ernie-doc-base-en\vocab.txt failed with code 404!

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleNLP#3405]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.3.2.post112
- paddlenlp: 2.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
下载地址中不存在此文件
```

### 稳定复现步骤 & 代码

直接在浏览器中访问这个地址报文件不存在：
https://bj.bcebos.com/paddlenlp/models/community/ernie-doc-base-en/vocab.txt

**Comment by wj-Mcat** [comment]
### 建议
就像描述中写的，你应该贴上可稳定复现问题的步骤和代码，这样才能够帮你定位问题。

### 分析

通过以下测试代码，是可以正常工作的：

```python
from paddlenlp.transformers import AutoTokenizer, AutoModel
model = AutoModel.from_pretrained("ernie-doc-base-en")
tokenizer = AutoTokenizer.from_pretrained("ernie-doc-base-en")

# or
from paddlenlp.transformers.ernie_doc.modeling import ErnieDocModel
from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
model = ErnieDocModel.from_pretrained("ernie-doc-base-en")
tokenizer = ErnieDocTokenizer.from_pretrained("ernie-doc-base-en")
```

通过文件名可猜测你是想初始化Tokenizer，所以推荐使用标准写法，而不是使用一些看起来比较tricky的方法。

***

我很**好奇**：
1. 你为什么直接通过url来下载文件呢？
2. 你是如何知道可以通过以上链接可以下载`vocab.txt`？

非常期待你的回复，这样我们就可以不断优化项目使用体验。

**Comment by yangy996** [comment]
> 2\. vocab.txt

下载vocab.txt是PaddleNLP代码里自带的，初始化的时候会检测有没有vocab.txt这个文件，没有会自动下载，自动下载时候发现这个链接已经无法下载到文件了

**Comment by yangy996** [comment]
> ### 建议
> 就像描述中写的，你应该贴上可稳定复现问题的步骤和代码，这样才能够帮你定位问题。
> 
> ### 分析
> 通过以下测试代码，是可以正常工作的：
> 
> ```python
> from paddlenlp.transformers import AutoTokenizer, AutoModel
> model = AutoModel.from_pretrained("ernie-doc-base-en")
> tokenizer = AutoTokenizer.from_pretrained("ernie-doc-base-en")
> 
> # or
> from paddlenlp.transformers.ernie_doc.modeling import ErnieDocModel
> from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
> model = ErnieDocModel.from_pretrained("ernie-doc-base-en")
> tokenizer = ErnieDocTokenizer.from_pretrained("ernie-doc-base-en")
> ```
> 
> 通过文件名可猜测你是想初始化Tokenizer，所以推荐使用标准写法，而不是使用一些看起来比较tricky的方法。
> 
> 我很**好奇**：
> 
> 1. 你为什么直接通过url来下载文件呢？
> 2. 你是如何知道可以通过以上链接可以下载`vocab.txt`？
> 
> 非常期待你的回复，这样我们就可以不断优化项目使用体验。

![image](https://user-images.githubusercontent.com/15188456/194697518-bdcb10db-9e86-44a3-922a-538f6e1d1df1.png)

**Comment by wj-Mcat** [comment]
@yangy996 兄弟：**最小可稳定复现代码**，你截这个图还是很难复现你的问题，毕竟上下文太少。

我给你一个可复现代码模板，你用这个来复现你的问题吧：

```python
from paddlenlp.transformers import AutoTokenizer
from paddlenlp.utils.env import MODEL_HOME

model_name = 'ernie-doc-base-en'

# 1. 下载相关文件
tokenizer = AutoTokenizer.from_pretrained(model_name) 

# 2. 删除MODEL_HOME的文件
import os
# 你也可以罗列出你缓存目录下的文件名列表
os.remove(os.path.join(MODEL_HOME, model_name, 'vocab.txt'))

# 3. 重新加载Tokenizer，从而复现你的问题
tokenizer = AutoTokenizer.from_pretrained(model_name)
```

**Comment by yangy996** [comment]
> @yangy996 兄弟：**最小可稳定复现代码**，你截这个图还是很难复现你的问题，毕竟上下文太少。
> 
> 我给你一个可复现代码模板，你用这个来复现你的问题吧：
> 
> ```python
> from paddlenlp.transformers import AutoTokenizer
> from paddlenlp.utils.env import MODEL_HOME
> 
> model_name = 'ernie-doc-base-en'
> 
> # 1. 下载相关文件
> tokenizer = AutoTokenizer.from_pretrained(model_name) 
> 
> # 2. 删除MODEL_HOME的文件
> import os
> # 你也可以罗列出你缓存目录下的文件名列表
> os.remove(os.path.join(MODEL_HOME, model_name, 'vocab.txt'))
> 
> # 3. 重新加载Tokenizer，从而复现你的问题
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> ```

复现代码跟你发我的一样，红框截图就是加载Tokenizer的代码
ErnieDocTokenizer.from_pretrained('ernie-doc-base-en')

**Comment by wj-Mcat** [comment]
我复现出你的问题了，可并不是你引用的示例代码，而是：

```python
from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
from paddlenlp.utils.env import MODEL_HOME

model_name = 'ernie-doc-base-en'

# 1. 下载相关文件
tokenizer = ErnieDocTokenizer.from_pretrained(model_name) 

# 2. 删除MODEL_HOME的文件
import os
os.remove(os.path.join(MODEL_HOME, model_name, 'vocab.txt'))

# 3. 重新加载Tokenizer，从而复现你的问题
tokenizer = ErnieDocTokenizer.from_pretrained(model_name)
```

原因在于：在`ernie-doc-base-en`模型权重下，需要使用`ErnieDocBPETokenizer`，而不是`ErnieDocTokenizer`，前者是针对于英文场景，后者针对于中文场景。

所以，你需要做的调整是：`ErnieDocTokenizer` -> `ErnieDocBPETokenizer`.

**Comment by yangy996** [comment]
> 我复现出你的问题了，可并不是你引用的示例示例代码，而是：
> 
> ```python
> from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
> from paddlenlp.utils.env import MODEL_HOME
> 
> model_name = 'ernie-doc-base-en'
> 
> # 1. 下载相关文件
> tokenizer = ErnieDocTokenizer.from_pretrained(model_name) 
> 
> # 2. 删除MODEL_HOME的文件
> import os
> os.remove(os.path.join(MODEL_HOME, model_name, 'vocab.txt'))
> 
> # 3. 重新加载Tokenizer，从而复现你的问题
> tokenizer = ErnieDocTokenizer.from_pretrained(model_name)
> ```
> 
> 原因在于：在`ernie-doc-base-en`模型权重下，需要使用`ErnieDocBPETokenizer`，而不是`ErnieDocTokenizer`，前者是针对于英文场景，后者针对于中文场景。
> 
> 所以，你需要做的调整是：`ErnieDocTokenizer` -> `ErnieDocBPETokenizer`.

> 我复现出你的问题了，可并不是你引用的示例示例代码，而是：
> 
> ```python
> from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
> from paddlenlp.utils.env import MODEL_HOME
> 
> model_name = 'ernie-doc-base-en'
> 
> # 1. 下载相关文件
> tokenizer = ErnieDocTokenizer.from_pretrained(model_name) 
> 
> # 2. 删除MODEL_HOME的文件
> import os
> os.remove(os.path.join(MODEL_HOME, model_name, 'vocab.txt'))
> 
> # 3. 重新加载Tokenizer，从而复现你的问题
> tokenizer = ErnieDocTokenizer.from_pretrained(model_name)
> ```
> 
> 原因在于：在`ernie-doc-base-en`模型权重下，需要使用`ErnieDocBPETokenizer`，而不是`ErnieDocTokenizer`，前者是针对于英文场景，后者针对于中文场景。
> 
> 所以，你需要做的调整是：`ErnieDocTokenizer` -> `ErnieDocBPETokenizer`.

多谢大佬，这块文档没有细说，还以为可以混用。再问下，为什么release/2.4分支没有ernie-doc这个目录了

**Comment by wj-Mcat** [comment]
有`model_zoo/ernie-doc`目录啊。

你所说的目录具体是？

**Comment by yangy996** [comment]
> 有`model_zoo/ernie-doc`目录啊。
> 
> 你所说的目录具体是？

好的，找到了，多谢，2.4结构目录变了，我没找到

**Comment by wj-Mcat** [comment]
Glad to see that your issue has been fixed. 

BTW, if you post your mvp code which can reproduce your issue stably, I believe this small problem can be fixed in less time.    Please feel free to post other issues which you work hard on.

**Comment by Change0028** [comment]
> ### 建议
> 就像描述中写的，你应该贴上可稳定复现问题的步骤和代码，这样才能够帮你定位问题。
> 
> ### 分析
> 通过以下测试代码，是可以正常工作的：
> 
> ```python
> from paddlenlp.transformers import AutoTokenizer, AutoModel
> model = AutoModel.from_pretrained("ernie-doc-base-en")
> tokenizer = AutoTokenizer.from_pretrained("ernie-doc-base-en")
> 
> # or
> from paddlenlp.transformers.ernie_doc.modeling import ErnieDocModel
> from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
> model = ErnieDocModel.from_pretrained("ernie-doc-base-en")
> tokenizer = ErnieDocTokenizer.from_pretrained("ernie-doc-base-en")
> ```
> 
> 通过文件名可猜测你是想初始化Tokenizer，所以推荐使用标准写法，而不是使用一些看起来比较tricky的方法。
> 
> 我很**好奇**：
> 
> 1. 你为什么直接通过url来下载文件呢？
> 2. 你是如何知道可以通过以上链接可以下载`vocab.txt`？
> 
> 非常期待你的回复，这样我们就可以不断优化项目使用体验。

大佬你好，我想在内网使用，所以必须手动下载，但链接https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_base_zh_vocab.txt打开是乱码，请问有更新链接吗？

**Comment by yangy996** [comment]
> > ### 建议
> > 就像描述中写的，你应该贴上可稳定复现问题的步骤和代码，这样才能够帮你定位问题。
> > ### 分析
> > 通过以下测试代码，是可以正常工作的：
> > ```python
> > from paddlenlp.transformers import AutoTokenizer, AutoModel
> > model = AutoModel.from_pretrained("ernie-doc-base-en")
> > tokenizer = AutoTokenizer.from_pretrained("ernie-doc-base-en")
> > 
> > # or
> > from paddlenlp.transformers.ernie_doc.modeling import ErnieDocModel
> > from paddlenlp.transformers.ernie_doc.tokenizer import ErnieDocTokenizer
> > model = ErnieDocModel.from_pretrained("ernie-doc-base-en")
> > tokenizer = ErnieDocTokenizer.from_pretrained("ernie-doc-base-en")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 通过文件名可猜测你是想初始化Tokenizer，所以推荐使用标准写法，而不是使用一些看起来比较tricky的方法。
> > 我很**好奇**：
> > 
> > 1. 你为什么直接通过url来下载文件呢？
> > 2. 你是如何知道可以通过以上链接可以下载`vocab.txt`？
> > 
> > 非常期待你的回复，这样我们就可以不断优化项目使用体验。
> 
> 大佬你好，我想在内网使用，所以必须手动下载，但链接[https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_base_zh_vocab.txt打开是乱码，请问有更新链接吗？](https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_base_zh_vocab.txt%E6%89%93%E5%BC%80%E6%98%AF%E4%B9%B1%E7%A0%81%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89%E6%9B%B4%E6%96%B0%E9%93%BE%E6%8E%A5%E5%90%97%EF%BC%9F)

可以在有网的环境下，调用下面的，会自动去下载模型，把这些模型和txt文件拷贝到内网就可以了
from paddlenlp.transformers import AutoTokenizer, AutoModel
model = AutoModel.from_pretrained("ernie-3.0-base-zh")
tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh")
