### ISSUE TITLE
请问UIE使用的标签库是哪些呢

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#3408]
### 请提出你的问题

请问UIE 训练所使用的标签库是哪些呢？有文档吗?

类似这些  {'竞赛名称': ['主办方', '承办方', '已举办次数']}  {'地震触发词': ['地震强度', '时间', '震中位置', '震源深度']}   所对应的标签与关系名称
即类似  Doccano 中的  labels 下的  span及 relation

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 请问UIE 训练所使用的标签库是哪些呢？有文档吗?
> 
> 类似这些 {'竞赛名称': ['主办方', '承办方', '已举办次数']} {'地震触发词': ['地震强度', '时间', '震中位置', '震源深度']} 所对应的标签与关系名称 即类似 Doccano 中的 labels 下的 span及 relation

UIE 没有限制标签体系，UIE是一个开放域信息抽取，和之前的封闭域信息抽取有区别，对于如何设置标签，只要有语义相关性即可；

**Comment by zchengzhong** [comment]
谢谢
