### ISSUE TITLE
想问下UIE抽取有加速方法吗，现在感觉预测太慢了，能否做并发，我用多进程试了跑不了

### ISSUE THREAD

**Issue by Zengpr** [PaddlePaddle/PaddleNLP#3414]
### 请提出你的问题

想问下UIE抽取有加速方法吗，现在感觉预测太慢了，能否做并发，我用多进程试了跑不了

**Comment by wawltor** [comment]
目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？

**Comment by Zengpr** [comment]
> 目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？

是的
ie = Taskflow('information_extraction', schema=schema)
res = ie(texts)

**Comment by jack-gits** [comment]
taskflow支持多线程吗？

**Comment by wawltor** [comment]
> > 目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？
> 
> 是的 ie = Taskflow('information_extraction', schema=schema) res = ie(texts)

如果是最新版本的Taskflow，已经支持了多线程和MKLDNN 加速了

**Comment by wawltor** [comment]
> > > 目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？
> > 
> > 
> > 是的 ie = Taskflow('information_extraction', schema=schema) res = ie(texts)
> 
> 如果是最新版本的Taskflow，已经支持了多线程和MKLDNN 加速了

如果速度还不行的话，可以将model设置成更小的模型 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/16698950/194740462-6962f341-68ad-4bca-b2a6-ce5317a69b2f.png">

**Comment by Zengpr** [comment]
> > > > 目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？
> > > 
> > > 
> > > 是的 ie = Taskflow('information_extraction', schema=schema) res = ie(texts)
> > 
> > 
> > 如果是最新版本的Taskflow，已经支持了多线程和MKLDNN 加速了
> 
> 如果速度还不行的话，可以将model设置成更小的模型 <img alt="image" width="643" src="https://user-images.githubusercontent.com/16698950/194740462-6962f341-68ad-4bca-b2a6-ce5317a69b2f.png">

噢噢，好的，感谢，刚刚试了下是可以了~

**Comment by wawltor** [comment]
您好，我们将暂时关闭该ISSUE，如有问题后续可以继续打开该ISSUE！

**Comment by Zengpr** [comment]
> > > > 目前使用的是什么方式来做预测的了？是Taskflow来做预测吗？
> > > 
> > > 
> > > 是的 ie = Taskflow('information_extraction', schema=schema) res = ie(texts)
> > 
> > 
> > 如果是最新版本的Taskflow，已经支持了多线程和MKLDNN 加速了
> 
> 如果速度还不行的话，可以将model设置成更小的模型 <img alt="image" width="643" src="https://user-images.githubusercontent.com/16698950/194740462-6962f341-68ad-4bca-b2a6-ce5317a69b2f.png">

为什么多线程跑的非常不稳定，每次结果都不一样，而且经常会失败，报错
![image](https://user-images.githubusercontent.com/22451062/195554360-6ffe2d01-d3db-4044-bea4-39eafa1fbe94.png)
这是同一批数据跑三次的结果，两次结果不一样，一次失败，是什么原因啊？

**Comment by yifeizhou980429** [comment]
同样的问题，paddlenlp ==2.4.0  paddlepaddle == 2.3.2 python ==3.6.8 ，跑多进程（10个，100个）
if "relations" not in relations[k][i].keys(): 这一行会报错keyerror，这是什么原因啊？
