### ISSUE TITLE
[Question]: faq_finance requirements依赖需要修改

### ISSUE THREAD

**Issue by suzhou-Second** [PaddlePaddle/PaddleNLP#3419]
### 请提出你的问题

requirements中paddle_serving_server-gpu需要指定0.9.0.post112，不然无法运行

**Comment by suzhou-Second** [comment]
docker 镜像registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8

**Comment by w5688414** [comment]
Please refer to this pr https://github.com/PaddlePaddle/PaddleNLP/pull/3430 . Thanks
