### ISSUE TITLE
请问目前paddlenlp schema已经支持的实体关系抽取类型列表清单有吗？

### ISSUE THREAD

**Issue by springwings** [PaddlePaddle/PaddleNLP#3421]
### 请提出你的问题

请问目前paddlenlp schema已经支持的实体关系抽取类型列表清单有吗？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 请问目前paddlenlp schema已经支持的实体关系抽取类型列表清单有吗？

paddlenlp uie的schema相对比较多，目前没有考虑放出来，主要是因为UIE的schema放出来并不会提升zero-shot的效果，咱们不同的文本在同一个schema的效果是不一样的，因此还是需要针对自己文本来进行微调
