### ISSUE TITLE
UIE关系抽取，用自己的数据微调训练后，有些抽取的关系会乱串

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#3427]
### 问题描述

找到的核心原因是数据增强的问题，建议官方的数据增强类别需要增加，不单要做同一批次不同样本的增强，还需要做同一样本，不同关系的增强，在转换样本的那个utils.py文件，需要加上这些增强的负样本，即使为空也得加上，这样预测的时候多关系，才不会乱窜，增加的代码如下

**Comment by AI-Mart** [comment]
```
            relation_dict = {'时间': ['交通工具', '地点', '行为', '接触者']}
            for subject_id in subject_id_list:
                if entity_map[subject_id]["label"] in relation_dict:
                    for rel in relation_dict[entity_map[subject_id]["label"]]:
                        prompt_new = entity_map[subject_id]["name"] + "的" + rel
                        if prompt_new not in relation_example_map:
                            relation_example_map[prompt_new] = {
                                "content": text,
                                "result_list": [],
                                "prompt": prompt_new
                            }
```

**Comment by linjieccc** [comment]
感谢反馈问题！关于多关系乱窜的情况以及自己标注的正样本数据能否给几个例子看下。

当前UIE关系抽取任务的负例构造主要是包含以下三种形式

1) 反关系负例（如：b的B，b为A的B的抽取结果）

2) 随机替换A负例（如：C的B，C为文本中不包含的实体）

3) 随机替换B负例（如：A的D，D为文本中不包含的实体类型）

**Comment by AI-Mart** [comment]
你好，比如issue里面举的例子，假如某个时间主体，只有接触者的关系，其他的关系都为空，此时标注工具标注出来的结果只有接触者的关系样本，没有其他关系为空的负样本，此时应该额外通过代码增强，把为空的关系样本补上，如果不补上的话，当一段文本存在多个时间主体的时候，为空的这个时间主体，会从后面不为空的时间主体抽取出来其他关系，而实际情况是没有的，关系也就乱了
