### ISSUE TITLE
[Question]: 基于Paddle Serving的服务化部署，内存不释放的问题

### ISSUE THREAD

**Issue by helloHKTK** [PaddlePaddle/PaddleNLP#3429]
### 请提出你的问题

参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/paddle_serving的部署方法。通过python service.py --max_seq_length 128 --model_name "ernie-3.0-micro-zh"启动服务后，运行rpc_client.py中的代码（rpc_client.py代码只改了"texts = []"和label_list = []，其中"texts = []"中元素个数为1000），发现运行rpc_client.py后内存占用不释放! 
备注：使用CPU预测，config.yml内容如下：
`rpc_port: 18090
http_port: 9878
worker_num: 1
build_dag_each_worker: False
dag:
    is_thread_op: True
    retry: 1
    use_profile: True
    tracer:
        interval_s: 10
op:
    seq_cls:
        concurrency: 1
        local_service_conf:            
            client_type: local_predictor
            model_config: serving_server
            fetch_list: ["linear_51.tmp_1"] # fetch_list: ["linear_75.tmp_1"]
            device_type: 0
            devices: ""
            use_mkldnn: True
            thread_num: 12
            ir_optim: True
`

**Comment by helloHKTK** [comment]
内存不释放附图：
![图片](https://user-images.githubusercontent.com/28376852/194983552-58e6622d-d186-4b0c-a41e-abaecd36780f.png)

**Comment by lugimzzz** [comment]
我看这里是服务端还在启动所以占用内存，你运行rpc_client.py后内存会增加吗

**Comment by helloHKTK** [comment]
您好：    很高兴收到您的来信，我会尽快阅读并回复您！祝您工作顺利、生活愉快！

**Comment by helloHKTK** [comment]
> 

会增加，这个场景很容易复现，只需要修改rpc_client.py中的"texts = []"和label_list = []，其中"texts = []"中元素个数为1000或者更多，这个内存不释放的问题很明显

**Comment by lugimzzz** [comment]
paddleserving 的pipeline确实有这个问题，可以考虑使用C++  paddleserving。对于python部署我们推荐使用triton部署 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/triton_serving

**Comment by helloHKTK** [comment]
您好：    很高兴收到您的来信，我会尽快阅读并回复您！祝您工作顺利、生活愉快！
