### ISSUE TITLE
[Question]: PaddleNLP是否能够从复杂的docx文件中直接抽取信息？

### ISSUE THREAD

**Issue by hehuang139** [PaddlePaddle/PaddleNLP#3442]
### 请提出你的问题

我是nlp方面的新人，最近要了解信息抽取的方案。
我的需求是要从一个大的docx文件中抽取信息，比如说合同文件，标书文件（比如抽取投标人，投标资质然后在对相对信息做指定的规则校验），这是一个很常见的应用场景。
这个问题应该是属于信息抽取的范畴，但是看了很多关于信息抽取的资料，发现输入都是一段文字，我想知道的paddleNLP的信息抽取能力，是否对文本长度有限制？比如我通过python-docx把整个docx转化成一个字符串，是否支持抽取这样的信息。或者paddleNLP有其他更正确的方式。
关于标书要素提取这块，是否能够使用paddleNLP的信息抽取直接实现？
同时我了解到微软有一个layoutLM，似乎能够做这方面的事情，是否这种富文本只能用类似的模型？

**Comment by wawltor** [comment]
可以的，我们最新要发布Layout SOTA 模型 ERNIE-Layout，具备一定的抽取能力，以及多模态UIE的也在进行，具体ERNIE-Layout目录可以见 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layoutx

**Comment by hehuang139** [comment]
> 可以的，我们最新要发布Layout SOTA 模型 ERNIE-Layout，具备一定的抽取能力，以及多模态UIE的也在进行，具体ERNIE-Layout目录可以见 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layoutx

太棒了，这块大约什么时候正式发布，是否有提供相关的标注工具，如果没有的标注工具的话，标注要怎么去做
目前这块是否可以用于生产环境，并且如果短期内没有发布的话，是否有替代方案，来做这块的场景，像标书的要素提取

**Comment by hehuang139** [comment]
在咨询个问题，ocr这部分，是否能增加自己的ocr识别，是否提供扩展方式，比如说公章，营业执照的识别

**Comment by wawltor** [comment]
> > 可以的，我们最新要发布Layout SOTA 模型 ERNIE-Layout，具备一定的抽取能力，以及多模态UIE的也在进行，具体ERNIE-Layout目录可以见 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layoutx
> 
> 太棒了，这块大约什么时候正式发布，是否有提供相关的标注工具，如果没有的标注工具的话，标注要怎么去做 目前这块是否可以用于生产环境，并且如果短期内没有发布的话，是否有替代方案，来做这块的场景，像标书的要素提取

预计整个标注方式、微调方式预计在11月份发布

**Comment by wawltor** [comment]
> 在咨询个问题，ocr这部分，是否能增加自己的ocr识别，是否提供扩展方式，比如说公章，营业执照的识别

可以支持自定义ocr方式

**Comment by hehuang139** [comment]
目前develop分支是否能用于生产环境？

**Comment by wawltor** [comment]
> 目前develop分支是否能用于生产环境？

可以的

**Comment by hehuang139** [comment]
这块对于标书或者合同这种几百页的文档，是否会有文档大小限制，解析的性能如何，对于我们场景而已，当然也不需要太高的性能，想了解下大致的性能情况

**Comment by wawltor** [comment]
不会有文档大小限制，解析的性能和设备相关，同时我们会提供不同尺寸的模型供大家选择

**Comment by hehuang139** [comment]
感谢！

**Comment by hehuang139** [comment]
感谢！

**Comment by ZzyChris97** [comment]
> 

您好，我想请问一下DocPrompt的标注、微调方式也会在11月份发布吗？
