### ISSUE TITLE
[Bug]: paddlenlp debug一致提示找不到cv2模块。

### ISSUE THREAD

**Issue by YYGe01** [PaddlePaddle/PaddleNLP#3443]
### 软件环境

```Markdown
- paddlepaddle: 2.3.2
- paddlepaddle-gpu: 无
- paddlenlp: 2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
用pycharm debug，显示未找到cv2模块。
```

### 稳定复现步骤 & 代码

```python
from paddlenlp.transformers import AutoTokenizer
print("fsfsdfsf")
```

[](用pycharm在print处打断点，一致提示未找到cv2模块。虽然可以不用管，不会报错，但是每次调试都会跳出这多余的一步，比较烦。发现和问题[850](https://github.com/PaddlePaddle/PaddleNLP/issues/850) 一样，需要安装opencv-python模块，才不会跳出。不确认这是否是一个bug，建议默认安装opencv库。
![image](https://user-images.githubusercontent.com/45594167/195232806-04d41be9-4429-4280-b35e-db29ce0c9169.png)

**Comment by wawltor** [comment]
您好，很高兴您给我提出这个问题。我们解释一下为什么把opencv依赖放到paddlenlp依， paddlenlp在依赖性管理相对比较严格，因为opencv在安装的时候有一定的环境依赖性，依赖安装会导致成本大家安装paddlenlp成本变高，所以对这个处理比较谨慎。
