### ISSUE TITLE
[Question]: 使用预训练模型skep微调不收敛

### ISSUE THREAD

**Issue by qdchenxiaoyan** [PaddlePaddle/PaddleNLP#3444]
你好，想请教下，结合https://aistudio.baidu.com/aistudio/projectdetail/2603746和https://aistudio.baidu.com/aistudio/projectdetail/2110026?channelType=0&channel=0的目标级情感使用说明，使用自己数据对skep模型进行微调，但是loss一直震荡，请问有什么建议么？

数据格式：{"label": 0, "text": "南昌新岚房地产开发有限公司", "text_pair": "海报新闻记者注意到，今年5月，南昌市房管局公示了《行政处罚决定书（洪住建罚决字[2022]第1号）》，该决定书显示，南昌新岚房地产开发有限公司开发的“新力江悦”项目，因存在未将通过赣州银行股份有限公司南昌分行出具保函释放的3900万元预售监管资金(属于商品房预售所得款项)用于有关工程建设的违法行为，导致工程逾期。根据《中华人民共和国城市房地产管理法》第四十五条中“商品房预售所得款项，必须用于有关的工程建设”和《城市商品房预售管理办法》第十一条及第十四条等有关规定，决定：对新岚公司的违法行为处罚款人民币叁万元整。"}

loss：
training 1 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 1 - global_step: 50/16520 - loss:0.716577
epoch: 1 - global_step: 100/16520 - loss:0.528214
epoch: 1 - global_step: 150/16520 - loss:0.659212
epoch: 1 - global_step: 200/16520 - loss:1.127822
epoch: 1 - global_step: 250/16520 - loss:0.839687
epoch: 1 - global_step: 300/16520 - loss:0.809158
epoch: 1 - global_step: 350/16520 - loss:0.957018
epoch: 1 - global_step: 400/16520 - loss:0.632032
epoch: 1 - global_step: 450/16520 - loss:0.784654
epoch: 1 - global_step: 500/16520 - loss:0.758400
epoch: 1 - global_step: 550/16520 - loss:0.694705
epoch: 1 - global_step: 600/16520 - loss:0.628938
epoch: 1 - global_step: 650/16520 - loss:0.705516
epoch: 1 - global_step: 700/16520 - loss:0.669104
epoch: 1 - global_step: 750/16520 - loss:0.915877
epoch: 1 - global_step: 800/16520 - loss:0.628685
epoch: 1 - global_step: 850/16520 - loss:0.234711
epoch: 1 - global_step: 900/16520 - loss:0.640560
epoch: 1 - global_step: 950/16520 - loss:0.698337
epoch: 1 - global_step: 1000/16520 - loss:0.835556
epoch: 1 - global_step: 1050/16520 - loss:0.906022
epoch: 1 - global_step: 1100/16520 - loss:0.670552
epoch: 1 - global_step: 1150/16520 - loss:0.835417
epoch: 1 - global_step: 1200/16520 - loss:0.992108
epoch: 1 - global_step: 1250/16520 - loss:1.857247
epoch: 1 - global_step: 1300/16520 - loss:0.813761
epoch: 1 - global_step: 1350/16520 - loss:0.382434
epoch: 1 - global_step: 1400/16520 - loss:0.769316
epoch: 1 - global_step: 1450/16520 - loss:0.816513
epoch: 1 - global_step: 1500/16520 - loss:1.242949
epoch: 1 - global_step: 1550/16520 - loss:0.770690
epoch: 1 - global_step: 1600/16520 - loss:0.741173
epoch: 1 - global_step: 1650/16520 - loss:1.022041
training 2 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 2 - global_step: 1700/16520 - loss:0.356128
epoch: 2 - global_step: 1750/16520 - loss:0.577629
epoch: 2 - global_step: 1800/16520 - loss:1.031393
epoch: 2 - global_step: 1850/16520 - loss:2.493135
epoch: 2 - global_step: 1900/16520 - loss:0.635206
epoch: 2 - global_step: 1950/16520 - loss:0.609651
epoch: 2 - global_step: 2000/16520 - loss:1.411938
epoch: 2 - global_step: 2050/16520 - loss:0.813437
epoch: 2 - global_step: 2100/16520 - loss:0.669755
epoch: 2 - global_step: 2150/16520 - loss:0.843861
epoch: 2 - global_step: 2200/16520 - loss:0.709998
epoch: 2 - global_step: 2250/16520 - loss:0.620129
epoch: 2 - global_step: 2300/16520 - loss:1.770987
epoch: 2 - global_step: 2350/16520 - loss:0.864026
epoch: 2 - global_step: 2400/16520 - loss:0.749243
epoch: 2 - global_step: 2450/16520 - loss:0.612622
epoch: 2 - global_step: 2500/16520 - loss:0.888792
epoch: 2 - global_step: 2550/16520 - loss:0.671772
epoch: 2 - global_step: 2600/16520 - loss:1.464395
epoch: 2 - global_step: 2650/16520 - loss:0.858568
epoch: 2 - global_step: 2700/16520 - loss:1.061859
epoch: 2 - global_step: 2750/16520 - loss:0.863369
epoch: 2 - global_step: 2800/16520 - loss:0.700395
epoch: 2 - global_step: 2850/16520 - loss:0.927700
epoch: 2 - global_step: 2900/16520 - loss:1.546754
epoch: 2 - global_step: 2950/16520 - loss:0.676515
epoch: 2 - global_step: 3000/16520 - loss:0.939346
epoch: 2 - global_step: 3050/16520 - loss:1.149918
epoch: 2 - global_step: 3100/16520 - loss:0.916524
epoch: 2 - global_step: 3150/16520 - loss:0.776519
epoch: 2 - global_step: 3200/16520 - loss:0.792636
epoch: 2 - global_step: 3250/16520 - loss:0.960047
epoch: 2 - global_step: 3300/16520 - loss:0.922232
training 3 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 3 - global_step: 3350/16520 - loss:1.229074
epoch: 3 - global_step: 3400/16520 - loss:0.821760
epoch: 3 - global_step: 3450/16520 - loss:0.736908
epoch: 3 - global_step: 3500/16520 - loss:1.696778
epoch: 3 - global_step: 3550/16520 - loss:0.403662
epoch: 3 - global_step: 3600/16520 - loss:1.413893
epoch: 3 - global_step: 3650/16520 - loss:1.167368
epoch: 3 - global_step: 3700/16520 - loss:0.530821
epoch: 3 - global_step: 3750/16520 - loss:0.729730
epoch: 3 - global_step: 3800/16520 - loss:1.382530
epoch: 3 - global_step: 3850/16520 - loss:0.697900
epoch: 3 - global_step: 3900/16520 - loss:0.832310
epoch: 3 - global_step: 3950/16520 - loss:1.390921
epoch: 3 - global_step: 4000/16520 - loss:0.990277
epoch: 3 - global_step: 4050/16520 - loss:0.849723
epoch: 3 - global_step: 4100/16520 - loss:0.649490
epoch: 3 - global_step: 4150/16520 - loss:0.898770
epoch: 3 - global_step: 4200/16520 - loss:0.614956
epoch: 3 - global_step: 4250/16520 - loss:1.825683
epoch: 3 - global_step: 4300/16520 - loss:1.376330
epoch: 3 - global_step: 4350/16520 - loss:1.080279
epoch: 3 - global_step: 4400/16520 - loss:0.745707
epoch: 3 - global_step: 4450/16520 - loss:0.642185
epoch: 3 - global_step: 4500/16520 - loss:0.858576
epoch: 3 - global_step: 4550/16520 - loss:1.555259
epoch: 3 - global_step: 4600/16520 - loss:0.680879
epoch: 3 - global_step: 4650/16520 - loss:1.122554
epoch: 3 - global_step: 4700/16520 - loss:0.722971
epoch: 3 - global_step: 4750/16520 - loss:0.668658
epoch: 3 - global_step: 4800/16520 - loss:1.186475
epoch: 3 - global_step: 4850/16520 - loss:0.745899
epoch: 3 - global_step: 4900/16520 - loss:0.511936
epoch: 3 - global_step: 4950/16520 - loss:0.714024
training 4 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 4 - global_step: 5000/16520 - loss:0.575064
epoch: 4 - global_step: 5050/16520 - loss:0.892719
epoch: 4 - global_step: 5100/16520 - loss:0.815307
epoch: 4 - global_step: 5150/16520 - loss:0.865820
epoch: 4 - global_step: 5200/16520 - loss:2.045037
epoch: 4 - global_step: 5250/16520 - loss:0.786144
epoch: 4 - global_step: 5300/16520 - loss:0.517725
epoch: 4 - global_step: 5350/16520 - loss:0.706402
epoch: 4 - global_step: 5400/16520 - loss:1.532683
epoch: 4 - global_step: 5450/16520 - loss:0.885179
epoch: 4 - global_step: 5500/16520 - loss:0.935505
epoch: 4 - global_step: 5550/16520 - loss:0.975088
epoch: 4 - global_step: 5600/16520 - loss:0.811637
epoch: 4 - global_step: 5650/16520 - loss:0.589426
epoch: 4 - global_step: 5700/16520 - loss:1.084513
epoch: 4 - global_step: 5750/16520 - loss:0.616463
epoch: 4 - global_step: 5800/16520 - loss:0.585220
epoch: 4 - global_step: 5850/16520 - loss:0.867953
epoch: 4 - global_step: 5900/16520 - loss:1.096074
epoch: 4 - global_step: 5950/16520 - loss:0.917175
epoch: 4 - global_step: 6000/16520 - loss:1.556435
epoch: 4 - global_step: 6050/16520 - loss:1.124402
epoch: 4 - global_step: 6100/16520 - loss:0.807449
epoch: 4 - global_step: 6150/16520 - loss:0.821322
epoch: 4 - global_step: 6200/16520 - loss:1.202100
epoch: 4 - global_step: 6250/16520 - loss:0.656716
epoch: 4 - global_step: 6300/16520 - loss:0.725825
epoch: 4 - global_step: 6350/16520 - loss:1.331386
epoch: 4 - global_step: 6400/16520 - loss:0.699887
epoch: 4 - global_step: 6450/16520 - loss:0.890315
epoch: 4 - global_step: 6500/16520 - loss:0.748469
epoch: 4 - global_step: 6550/16520 - loss:0.652060
epoch: 4 - global_step: 6600/16520 - loss:0.756684
training 5 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 5 - global_step: 6650/16520 - loss:0.851623
epoch: 5 - global_step: 6700/16520 - loss:0.708027
epoch: 5 - global_step: 6750/16520 - loss:0.892512
epoch: 5 - global_step: 6800/16520 - loss:0.599440
epoch: 5 - global_step: 6850/16520 - loss:1.123723
epoch: 5 - global_step: 6900/16520 - loss:0.675510
epoch: 5 - global_step: 6950/16520 - loss:0.565623
epoch: 5 - global_step: 7000/16520 - loss:0.805585
epoch: 5 - global_step: 7050/16520 - loss:0.812385
epoch: 5 - global_step: 7100/16520 - loss:0.899239
epoch: 5 - global_step: 7150/16520 - loss:0.935836
epoch: 5 - global_step: 7200/16520 - loss:1.210015
epoch: 5 - global_step: 7250/16520 - loss:1.453121
epoch: 5 - global_step: 7300/16520 - loss:0.652275
epoch: 5 - global_step: 7350/16520 - loss:1.906464
epoch: 5 - global_step: 7400/16520 - loss:1.007298
epoch: 5 - global_step: 7450/16520 - loss:0.732395
epoch: 5 - global_step: 7500/16520 - loss:1.476077
epoch: 5 - global_step: 7550/16520 - loss:1.012201
epoch: 5 - global_step: 7600/16520 - loss:0.890507
epoch: 5 - global_step: 7650/16520 - loss:0.798012
epoch: 5 - global_step: 7700/16520 - loss:1.350209
epoch: 5 - global_step: 7750/16520 - loss:0.855555
epoch: 5 - global_step: 7800/16520 - loss:1.140696
epoch: 5 - global_step: 7850/16520 - loss:0.942602
epoch: 5 - global_step: 7900/16520 - loss:0.768822
epoch: 5 - global_step: 7950/16520 - loss:1.156442
epoch: 5 - global_step: 8000/16520 - loss:0.843490
epoch: 5 - global_step: 8050/16520 - loss:1.574699
epoch: 5 - global_step: 8100/16520 - loss:0.747544
epoch: 5 - global_step: 8150/16520 - loss:2.050897
epoch: 5 - global_step: 8200/16520 - loss:0.762975
epoch: 5 - global_step: 8250/16520 - loss:0.747557
training 6 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 6 - global_step: 8300/16520 - loss:0.536888
epoch: 6 - global_step: 8350/16520 - loss:0.777289
epoch: 6 - global_step: 8400/16520 - loss:0.598628
epoch: 6 - global_step: 8450/16520 - loss:0.711060
epoch: 6 - global_step: 8500/16520 - loss:0.817866
epoch: 6 - global_step: 8550/16520 - loss:1.582634
epoch: 6 - global_step: 8600/16520 - loss:1.208243
epoch: 6 - global_step: 8650/16520 - loss:1.241921
epoch: 6 - global_step: 8700/16520 - loss:0.666081
epoch: 6 - global_step: 8750/16520 - loss:0.686016
epoch: 6 - global_step: 8800/16520 - loss:0.573195
epoch: 6 - global_step: 8850/16520 - loss:1.290332
epoch: 6 - global_step: 8900/16520 - loss:0.614691
epoch: 6 - global_step: 8950/16520 - loss:0.838853
epoch: 6 - global_step: 9000/16520 - loss:1.948421
epoch: 6 - global_step: 9050/16520 - loss:0.697725
epoch: 6 - global_step: 9100/16520 - loss:0.565864
epoch: 6 - global_step: 9150/16520 - loss:0.680103
epoch: 6 - global_step: 9200/16520 - loss:0.781016
epoch: 6 - global_step: 9250/16520 - loss:0.844059
epoch: 6 - global_step: 9300/16520 - loss:0.953347
epoch: 6 - global_step: 9350/16520 - loss:0.699276
epoch: 6 - global_step: 9400/16520 - loss:0.740541
epoch: 6 - global_step: 9450/16520 - loss:1.244172
epoch: 6 - global_step: 9500/16520 - loss:0.674145
epoch: 6 - global_step: 9550/16520 - loss:0.737950
epoch: 6 - global_step: 9600/16520 - loss:0.846848
epoch: 6 - global_step: 9650/16520 - loss:0.581591
epoch: 6 - global_step: 9700/16520 - loss:0.501377
epoch: 6 - global_step: 9750/16520 - loss:1.284387
epoch: 6 - global_step: 9800/16520 - loss:0.665290
epoch: 6 - global_step: 9850/16520 - loss:0.710528
epoch: 6 - global_step: 9900/16520 - loss:0.899720
training 7 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 7 - global_step: 9950/16520 - loss:0.751720
epoch: 7 - global_step: 10000/16520 - loss:0.614250
epoch: 7 - global_step: 10050/16520 - loss:0.612572
epoch: 7 - global_step: 10100/16520 - loss:0.595999
epoch: 7 - global_step: 10150/16520 - loss:0.813228
epoch: 7 - global_step: 10200/16520 - loss:1.083411
epoch: 7 - global_step: 10250/16520 - loss:0.697892
epoch: 7 - global_step: 10300/16520 - loss:0.905783
epoch: 7 - global_step: 10350/16520 - loss:1.284270
epoch: 7 - global_step: 10400/16520 - loss:0.610757
epoch: 7 - global_step: 10450/16520 - loss:0.687269
epoch: 7 - global_step: 10500/16520 - loss:0.812790
epoch: 7 - global_step: 10550/16520 - loss:0.421897
epoch: 7 - global_step: 10600/16520 - loss:0.505692
epoch: 7 - global_step: 10650/16520 - loss:0.674128
epoch: 7 - global_step: 10700/16520 - loss:1.190385
epoch: 7 - global_step: 10750/16520 - loss:0.692849
epoch: 7 - global_step: 10800/16520 - loss:0.798454
epoch: 7 - global_step: 10850/16520 - loss:1.188076
epoch: 7 - global_step: 10900/16520 - loss:0.775154
epoch: 7 - global_step: 10950/16520 - loss:1.112552
epoch: 7 - global_step: 11000/16520 - loss:0.959534
epoch: 7 - global_step: 11050/16520 - loss:0.610340
epoch: 7 - global_step: 11100/16520 - loss:1.195153
epoch: 7 - global_step: 11150/16520 - loss:0.780809
epoch: 7 - global_step: 11200/16520 - loss:0.609516
epoch: 7 - global_step: 11250/16520 - loss:1.881078
epoch: 7 - global_step: 11300/16520 - loss:0.716868
epoch: 7 - global_step: 11350/16520 - loss:1.395456
epoch: 7 - global_step: 11400/16520 - loss:0.656616
epoch: 7 - global_step: 11450/16520 - loss:0.756871
epoch: 7 - global_step: 11500/16520 - loss:0.720165
epoch: 7 - global_step: 11550/16520 - loss:0.673455
training 8 epoch ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
epoch: 8 - global_step: 11600/16520 - loss:0.509315
epoch: 8 - global_step: 11650/16520 - loss:0.756321
epoch: 8 - global_step: 11700/16520 - loss:0.851239
epoch: 8 - global_step: 11750/16520 - loss:0.727489
epoch: 8 - global_step: 11800/16520 - loss:0.553005
epoch: 8 - global_step: 11850/16520 - loss:0.703860
epoch: 8 - global_step: 11900/16520 - loss:0.749722
epoch: 8 - global_step: 11950/16520 - loss:1.229206
epoch: 8 - global_step: 12000/16520 - loss:0.746111
epoch: 8 - global_step: 12050/16520 - loss:0.711232
epoch: 8 - global_step: 12100/16520 - loss:0.903621
epoch: 8 - global_step: 12150/16520 - loss:0.683219
epoch: 8 - global_step: 12200/16520 - loss:0.824055
epoch: 8 - global_step: 12250/16520 - loss:0.850068
epoch: 8 - global_step: 12300/16520 - loss:0.912544
epoch: 8 - global_step: 12350/16520 - loss:0.678398
epoch: 8 - global_step: 12400/16520 - loss:1.041229
epoch: 8 - global_step: 12450/16520 - loss:0.560242
epoch: 8 - global_step: 12500/16520 - loss:1.005061
epoch: 8 - global_step: 12550/16520 - loss:0.624461
epoch: 8 - global_step: 12600/16520 - loss:0.688411
epoch: 8 - global_step: 12650/16520 - loss:0.628823
epoch: 8 - global_step: 12700/16520 - loss:0.702352

**Comment by wawltor** [comment]
具体的数据能分享给我们，我们来测试一下？后者你尝试调整一下学习率，把学习率调小一点试试

**Comment by qdchenxiaoyan** [comment]
> 

感谢回复，不过已经没问题了，可能是我两部分结合的时候出现了问题，直接使用train_aspect.py训练没有问题~😄
