### ISSUE TITLE
[Bug]: ERNIE-LayoutX 按照示例程序运行demo 报错： IndexError: list index out of range

### ISSUE THREAD

**Issue by CycloneBoy** [PaddlePaddle/PaddleNLP#3451]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu:  2.3.0.post112
- paddlenlp:  2.4.0
- paddleocr： 2.6.0.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
dev 分支：

bug原因分析： paddleocr 识别的结果赋值有误
文件： paddlenlp/taskflow/document_intelligence.py  106 

            example["ocr_result"] = ocr_result
```

改成 

```
            example["ocr_result"] = ocr_result[0]
```

修改后 示例运行无误，结果正确

### 稳定复现步骤 & 代码

```
>>> from pprint import pprint
>>> from paddlenlp import Taskflow

>>> docprompt = Taskflow("document_intelligence")
>>> docprompt([{"doc": "./resume.png", "prompt": ["五百丁本次想要担任的是什么职位?", "五百丁是在哪里上的大学?", "大学学的是什么专业?"]}])
[{'prompt': '五百丁本次想要担任的是什么职位?',
  'result': [{'end': 183, 'prob': 1.0, 'start': 180, 'value': '客户经理'}]},
 {'prompt': '五百丁是在哪里上的大学?',
  'result': [{'end': 38, 'prob': 1.0, 'start': 32, 'value': '广州五百丁学院'}]},
 {'prompt': '大学学的是什么专业?',
  'result': [{'end': 45, 'prob': 0.74, 'start': 39, 'value': '金融学(本科）'}]}]

```
![image](https://user-images.githubusercontent.com/13173452/195325943-fd40a05d-12f7-4c71-a769-dc560cf30384.png)

修改后：
bug原因分析： paddleocr 识别的结果赋值有误
文件： paddlenlp/taskflow/document_intelligence.py  第 106  行 ocr结果取值有些问题
```
            example["ocr_result"] = ocr_result
```

改成 

```
            example["ocr_result"] = ocr_result[0]
```

修改后 示例运行无误，结果正确

![image](https://user-images.githubusercontent.com/13173452/195326982-2c76ad67-5f93-4303-85f0-1bc255a6ac6a.png)

**Comment by CycloneBoy** [comment]
![image](https://user-images.githubusercontent.com/13173452/195327154-60bd38c7-6f57-4e93-8693-e4a633a299a3.png)
![image](https://user-images.githubusercontent.com/13173452/195327178-5ad065f9-4213-42d3-8881-6f4f8cac0999.png)

**Comment by linjieccc** [comment]
感谢反馈~paddleocr 新版本（>=2.6.0.2）对输出格式做了更新，我们修复下这个问题

**Comment by wencan** [comment]
@linjieccc 请问哪个版本修复了这个问题？
