### ISSUE TITLE
transformer 模型用paddle-lite opt工具优化出错

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleNLP#3452]
### 问题描述

paddle=v2.3.2
paddlenlp = v2.3.2
paddle-lite = v2.10  or  v2.11
用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer/static训练出一个中英翻译模型，Linux环境下python可以推理，结果正确。用paddle lite 工具opt优化时，提示出错信息，如下：
Loading topology data from ./transformer.pdmodel
Loading params data from ./transformer.pdiparams
1. Model is successfully loaded!
[F 10/12 19:13:30.981 ...-Lite/lite/operators/fill_constant_op.cc:66 AttachImpl] Check failed: (param_.value_tensor->numel() == 1): 512!==1 When use Tensor as value to set Tensor value in fill_cosntant, value input(ValueTensor) size must be 1, but get 512
Aborted (core dumped)

**Comment by hong19860320** [comment]
看起来是非法的算子行为，能把 paddle推理模型发上啦吗，我看看是哪里有问题。

**Comment by dlkht** [comment]
> 看起来是非法的算子行为，能把 paddle推理模型发上啦吗，我看看是哪里有问题。

谢谢回答，下面是模型链接：
链接：https://pan.baidu.com/s/1-C4CF1PV1a9Up9UCxQ24iA 
提取码：omfy
