### ISSUE TITLE
[Question]: layoutX是否支持直接传入原始文档，如docx文件，而不是图片？

### ISSUE THREAD

**Issue by hehuang139** [PaddlePaddle/PaddleNLP#3454]
### 环境
* branch  devolops分支
* paddle2onnx           1.0.1
* paddlefsl             1.1.0
* paddleocr             2.6.0.2
* paddlepaddle          2.4.0rc0

如题。

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layoutx  中提供的demo和说明中，入参必须图片或者图片链接，也可以是自己orc解析的结果wordboxes。
我想知道是否支持直接传入docx文件,试过docx路径传入wordboxes报错。因为原始的docx其实在业务中用途更广泛。

以下是我的测试

第一次先将文档截图是能够正常提取信息

第二次直接传入docx文件是报错

>>> docprompt([{"doc": "/home/hehuang/tmp/2.png", "prompt": ["应聘人是谁", "应聘人叫什么", "应聘人联系方式", "移动电话", "到岗时间", "应聘岗位"]}])
[{'prompt': '应聘人是谁', 'result': [{'value': '何妨', 'prob': 0.97, 'start': 8, 'end': 9}]}, {'prompt': '应聘人叫什么', 'result': [{'value': '何妨', 'prob': 0.99, 'start': 8, 'end': 9}]}, {'prompt': '应聘人联系方式', 'result': [{'value': '862193830', 'prob': 0.79, 'start': 63, 'end': 63}]}, {'prompt': '移动电话', 'result': [{'value': '18943241039', 'prob': 1.0, 'start': 45, 'end': 45}]}, {'prompt': '到岗时间', 'result': [{'value': '一个月内', 'prob': 1.0, 'start': 402, 'end': 405}]}, {'prompt': '应聘岗位', 'result': [{'value': '高级软件工程师', 'prob': 0.85, 'start': 428, 'end': 434}]}]
>>> docprompt([{"wordboxes": ["/home/hehuang/tmp/1.docx"], "prompt": ["应聘人是谁", "应聘人叫什么", "应聘人联系方式", "移动电话", "到岗时间", "应聘岗位"]}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hehuang/dev/git/PaddleNLP/paddlenlp/taskflow/taskflow.py", line 536, in __call__
    results = self.task_instance(inputs)
  File "/home/hehuang/dev/git/PaddleNLP/paddlenlp/taskflow/task.py", line 363, in __call__
    inputs = self._preprocess(*args)
  File "/home/hehuang/dev/git/PaddleNLP/paddlenlp/taskflow/document_intelligence.py", line 98, in _preprocess
    preprocess_results = self._check_input_text(inputs)
  File "/home/hehuang/dev/git/PaddleNLP/paddlenlp/taskflow/document_intelligence.py", line 226, in _check_input_text
    "Invalid inputs, the inputs should contain an url to an image or a local path."
ValueError: Invalid inputs, the inputs should contain an url to an image or a local path.

**Comment by wawltor** [comment]
不支持docx了，因为模型的输入只能是图片，可以先通过一些工作将docx转成图片然后再做模型预测
后续我们的工作会做智能文档的部署，会支持docx的输入

**Comment by hehuang139** [comment]
我有个思路，直接在docx文档上直接标注，然后使用工具解析出text，text对应的bbox，还有人工标注的信息，最后还要把docx文档转成图片，这样模型训练所需要的数据集就准备完成了。您看这种思路是否是可行的。但是我不确定这种方式对超大文档是否可以支持

**Comment by wawltor** [comment]
> 我有个思路，直接在docx文档上直接标注，然后使用工具解析出text，text对应的bbox，还有人工标注的信息，最后还要把docx文档转成图片，这样模型训练所需要的数据集就准备完成了。您看这种思路是否是可行的。但是我不确定这种方式对超大文档是否可以支持

这块还是依赖于标注工具解析能力，目前我们是计划在label studio进行这样的工作，目前看label studio是具备这样的能力
