### ISSUE TITLE
pipelines的rest-api里query请求，如何指定index？

### ISSUE THREAD

**Issue by superzhaoyy** [PaddlePaddle/PaddleNLP#3455]
### 请提出你的问题

有这样一个需求：有多个租户，每个租户会维护自己的数据，做法是针对每个租户建立一个index。
看了下pipeline相关源代码，发现insert document的时候是可以指定index的。但是rest-api中的query接口似乎无法指定index？

**Comment by wawltor** [comment]
curl -X POST -k http://localhost:8891/query -H 'Content-Type: application/json' -d '{"query": "衡量酒水的价格的因素有哪些?","params": {"Retriever": {"top_k": 5,"index":"insurance"}, "Ranker":{"top_k": 5}}}'  
可以通过上面的方式来处理
