### ISSUE TITLE
如何将UIE模型转成saved_model模式

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#3458]
### 请提出你的问题

你好，如何将UIE模型（checkpoint格式）转成saved_model格式？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 你好，如何将UIE模型（checkpoint格式）转成saved_model格式？

saved_model是说转成inference状态吗？

**Comment by zchengzhong** [comment]
> 
就是说，咱paddleNlp的UIE模型是tensorflow 的checkpoint格式，我想把它整成saved_model格式
 
>

**Comment by zchengzhong** [comment]
> > ### 请提出你的问题
> > 你好，如何将UIE模型（checkpoint格式）转成saved_model格式？
> 
> saved_model是说转成inference状态吗？

就是说，咱paddleNlp的UIE模型是tensorflow 的checkpoint格式，我想把它整成saved_model格式

**Comment by zchengzhong** [comment]
为了部署到推理服务上（比如非paddle相关的推理服务）

**Comment by wawltor** [comment]
> > > ### 请提出你的问题
> > > 你好，如何将UIE模型（checkpoint格式）转成saved_model格式？
> > 
> > 
> > saved_model是说转成inference状态吗？
> 
> 就是说，咱paddleNlp的UIE模型是tensorflow 的checkpoint格式，我想把它整成saved_model格式

目前我们提供了onnx的格式做部署，具体的代码可以看   https://github.com/PaddlePaddle/PaddleNLP/blob/a6b46912d26f5cd4688dcb8057936df73c23465c/model_zoo/uie/deploy/python/uie_predictor.py#L44

**Comment by zchengzhong** [comment]
谢谢
