### ISSUE TITLE
基于预训练模型的数据处理问题

### ISSUE THREAD

**Issue by Biggg888** [PaddlePaddle/PaddleNLP#346]
https://paddlenlp.readthedocs.io/zh/latest/data_prepare/data_preprocess.html

notebook中paddlenlp已更新至最新版本 
按照教程中将batched设为true 但是最后报错

---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-53-406413e02d0d> in <module>
     13 trans_func = partial(convert_examples, tokenizer=tokenizer)
     14 
---> 15 map_ds.map(trans_func, batched=True)
     16 print(map_ds[0]) # {'input_ids': [101, 1599, 3614, 2802, 5074, 4413, 4638, 4511, 4495,
     17                    #                1599, 3614, 784, 720, 3416, 4638, 1957, 4495, 102,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py in map(self, fn, lazy, batched, num_workers)
    317             return self
    318         else:
--> 319             return self._map(fn, lazy=lazy, batched=batched)
    320 
    321     def _map(self, fn, lazy=True, batched=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py in _map(self, fn, lazy, batched)
    321     def _map(self, fn, lazy=True, batched=False):
    322         if batched:
--> 323             self.new_data = fn(self.new_data)
    324         elif lazy:
    325             self._transform_pipline.append(fn)
<ipython-input-53-406413e02d0d> in convert_examples(examples, tokenizer)
      1 def convert_examples(examples, tokenizer):
      2     tokens = [example['tokens'] for example in examples]
----> 3     tokenized_examples = tokenizer(text=tokens)
      4 
      5     # 加上label用于训练
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in __call__(self, text, text_pair, max_seq_len, stride, is_split_into_words, pad_to_max_seq_len, truncation_strategy, return_position_ids, return_token_type_ids, return_attention_mask, return_length, return_overflowing_tokens, return_special_tokens_mask)
    219                 return_length=return_length,
    220                 return_overflowing_tokens=return_overflowing_tokens,
--> 221                 return_special_tokens_mask=return_special_tokens_mask)
    222         else:
    223             return self.encode(
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in batch_encode(self, batch_text_or_text_pairs, max_seq_len, pad_to_max_seq_len, stride, is_split_into_words, truncation_strategy, return_position_ids, return_token_type_ids, return_attention_mask, return_length, return_overflowing_tokens, return_special_tokens_mask)
   1103                         return_length=return_length,
   1104                         return_overflowing_tokens=return_overflowing_tokens,
-> 1105                         return_special_tokens_mask=return_special_tokens_mask))
   1106 
   1107         return batch_encode_inputs
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in encode(self, text, text_pair, max_seq_len, pad_to_max_seq_len, truncation_strategy, return_position_ids, return_token_type_ids, return_attention_mask, return_length, return_overflowing_tokens, return_special_tokens_mask)
    725                 )
    726 
--> 727         ids = get_input_ids(text)
    728         pair_ids = get_input_ids(text_pair) if text_pair is not None else None
    729 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/tokenizer_utils.py in get_input_ids(text)
    722             else:
    723                 raise ValueError(
--> 724                     "Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers."
    725                 )
    726 
ValueError: Input is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

**Comment by Biggg888** [comment]
![image](https://user-images.githubusercontent.com/49727302/117493026-01d2f800-afa5-11eb-8616-35b2e2f988fb.png)

**Comment by Biggg888** [comment]
![image](https://user-images.githubusercontent.com/49727302/117493143-2929c500-afa5-11eb-816e-d8ab577e60aa.png)

**Comment by Biggg888** [comment]
![image](https://user-images.githubusercontent.com/49727302/117493331-6aba7000-afa5-11eb-8692-a9c1b75d3b9c.png)
数据

**Comment by smallv0221** [comment]
您好，这里尝试用您的实例数据模拟了一个数据集，设置为batched=True后没有出现问题。
![image](https://user-images.githubusercontent.com/33639025/117530306-f9170c00-b00e-11eb-835d-ecd14d4b1dc8.png)
建议您检查一下您数据集中的数据是否都是格式正确的呢。

**Comment by Biggg888** [comment]
您好，这是我的数据集，如果您方便的话，麻烦您帮我看一下，我实在找不出来了
这是ai studio项目链接
项目“zero_ner”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1907688/d9d3b13a09ad4be29dcaf185f09452e7


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月8日(星期六) 下午3:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 基于预训练模型的数据处理问题 (#346)





 
您好，这里尝试用您的实例数据模拟了一个数据集，设置为batched=True后没有出现问题。
 
 建议您检查一下您数据集中的数据是否都是格式正确的呢。

**Comment by smallv0221** [comment]
看了一下，‘tokens’里面有的只有一个空格，空格在tokenize之后变成了一个空的list。会导致报错。
您是要做ner任务吧，建议读取数据的时候不要一个字符就是一条数据，参考一下example里的msra_ner还有dataset里面的msra_ner的数据读取。

**Comment by Biggg888** [comment]
**工程师很好，值得加薪**
