### ISSUE TITLE
[Question]: DataLoader与Gunicorn的gevent模式存在兼容性问题

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3466]
### 请提出你的问题

我的项目使用了Gunicorn部署了训练服务。
当将Gunicorn的进程设置为gevent模式时，训练服务会卡死，疑似卡死在train_data_loader的迭代器。
搜索后发现可能是兼容性导致的问题：
[Gunicorn 的使用手册](https://zhuanlan.zhihu.com/p/463699772)
> **使用gevent模式会出现一些兼容性问题。**
> 
> 
> 使用gevent时，系统会使用monkey patch。系统的部分函数会被修改， 有些库会兼容gevent的类型， 例如，任务调度的库apscheduler，web socket需要socketio的库等，需要专门选择gevent的函数。 而有些库则直接无法使用，例如多进程multiprocess。 例如，在一个api请求中，如果需要使用多核cpu资源，采用multiprocess进行多进程计算。则会出现卡死的问题。**gevent中，不能使用multiprocess库。**
>

想请问一下这个问题是否确实因DataLoader使用了multiprocess库或相关的原因导致？
是否有满足训练服务要求的情况下又满足高并发需求的解决方案？

**Comment by gongel** [comment]
你好，Gunicorn和DataLoader的兼容问题可以向[PaddlePaddle](https://github.com/PaddlePaddle/Paddle)的库提个issue看下哈。另外你跑的具体是我们的哪份代码呢?

**Comment by FFinchR** [comment]
> 你好，Gunicorn和DataLoader的兼容问题可以向[PaddlePaddle](https://github.com/PaddlePaddle/Paddle)的库提个issue看下哈。另外你跑的具体是我们的哪份代码呢?

好的。
我跑的是uie的[finetune](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/finetune.py)代码。

**Comment by FFinchR** [comment]
> 你好，Gunicorn和DataLoader的兼容问题可以向[PaddlePaddle](https://github.com/PaddlePaddle/Paddle)的库提个issue看下哈。另外你跑的具体是我们的哪份代码呢?

你好，我在官方的API文档下找到了解释，确实暂不支持子进程下运行DataLoader，感谢。
[DataLoader-API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader)
