### ISSUE TITLE
[Bug]: 两个词的词向量结果获取的是一样的

### ISSUE THREAD

**Issue by sxf20220704** [PaddlePaddle/PaddleNLP#3473]
### 软件环境

```Markdown
- paddlepaddle:2.3.2
- paddlenlp: 2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
按照官方例子测试查询embedding结果，官方文档地址为https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/embeddings.md，输入列表['我们去运动','中国人民']两个词，返回的词向量是一样的
```

### 稳定复现步骤 & 代码

from paddlenlp.embeddings import TokenEmbedding

token_embedding = TokenEmbedding()
print(token_embedding.search(['我们去运动','中国人民']))

**Comment by w5688414** [comment]
您好，search会把这两句话解析成相同的token，请输入单词。https://github.com/PaddlePaddle/PaddleNLP/blob/7c06b02e3161bd398e0decd439d47efd15f3feee/paddlenlp/embeddings/token_embedding.py#L238

```
token_embedding = TokenEmbedding()
print(token_embedding.search(['运动','中国']))

index =  token_embedding.get_idx_from_word('我们去运动')
print(index)
index =  token_embedding.get_idx_from_word('中国人民')
print(index)
```
