### ISSUE TITLE
[Bug]: 安装paddle-pipelines一直失败

### ISSUE THREAD

**Issue by superzhaoyy** [PaddlePaddle/PaddleNLP#3477]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.2.post112
- paddlenlp: 2.4.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
执行python -m pip install --upgrade paddle-pipelines -i https://pypi.tuna.tsinghua.edu.cn/simple   这个一直失败，提示Polygon3安装不上。
```

### 稳定复现步骤 & 代码

执行python -m pip install --upgrade paddle-pipelines -i https://pypi.tuna.tsinghua.edu.cn/simple   这个一直失败，提示Polygon3安装补上。

**Comment by w5688414** [comment]
推荐使用miniconda环境安装。 https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/
