### ISSUE TITLE
[Question]: 关于使用uie-base-en定制训练长文本的问题

### ISSUE THREAD

**Issue by TSAIJK** [PaddlePaddle/PaddleNLP#3480]
### 请提出你的问题

您好！
首先感谢https://github.com/PaddlePaddle/PaddleNLP/issues/3345 中的回答。
目前在使用uie-base-en进行【实体识别和关系抽取】定制训练时效果不佳，主要指标为：
Evaluation Precision: 0.40741 | Recall: 0.16418 | F1: 0.23404
主要研判有两部分原因：
一、大部分训练文本超过512，仅有少部分训练文本短于512个字符。不知是否可以通过直接调节 finetune.py运行命令行中的“max_seq_len”参数来直接达到更好的效果？抑或是需要其他的改动？
二 考虑是否能添加用户词典（或其他先验知识），对实体识别的性能进行提升？
或者可能的其他问题（例如标注？）
我的实验数据取出3条附在下面，盼复：
{"id":1,"text":"On kinetics of phage adsorption.Adsorption of lambda-phage on sensitive bacteria Escherichia coli is a classical problem but not all issues have been resolved. One of the outstanding problems is the rate of adsorption, which in some cases appears to exceed the theoretical limit imposed by the law of random diffusion. We revisit this problem by conducting experiments along with new theoretical analyses. Our measurements show that upon incubating lambda-phage with bacteria Ymel, the population of unbound phage in a salt buffer decreases with time and in general obeys a double-exponential function characterized by a fast (tau(1)) and a slow (tau(2)) decay time. We found that both the fast and the slow processes are specific to interactions between lambda-phage and its receptor LamB. Such specificity motivates a kinetic model that describes the interaction between the phage and the receptor as an on-and-off process followed by an irreversible binding. The latter may be a signature of the initiation of DNA translocation. The kinetic model successfully predicts the double exponential behavior seen in the experiment and allows the corresponding rate constants to be extracted from single measurements. The weak temperature dependence of the reversible and the irreversible binding rate suggests that phage retention by the receptor is entropic in nature and that a molecular key-lock interaction may be an appropriate description of the interaction between the phage tail and the receptor.","entities":[{"id":3,"label":"Phage","start_offset":755,"end_offset":767},{"id":4,"label":"Receptor","start_offset":785,"end_offset":789},{"id":5,"label":"Bacteria","start_offset":476,"end_offset":480},{"id":6,"label":"Bacteria","start_offset":81,"end_offset":97}],"relations":[{"id":1,"from_id":4,"to_id":3,"type":"Is_Receptor_Of"},{"id":2,"from_id":4,"to_id":5,"type":"Is_Receptor_Of"},{"id":3,"from_id":4,"to_id":6,"type":"Is_Receptor_Of"}]}
{"id":2,"text":"Structure of the receptor-binding protein of bacteriophage det7: a podoviral tail spike in a myovirus.A new Salmonella enterica phage Det7, was isolated from sewage and shown by electron microscopy to belong to the Myoviridae morphogroup of bacteriophages. Det7 contains a 75-kDa protein with 50% overall sequence identity to the tail spike endorhamnosidase of podovirus P22. Adsorption of myoviruses to their bacterial hosts is normally mediated by long and short tail fibers attached to a contractile tail, whereas podoviruses do not contain fibers but attach to host cells through stubby tail spikes attached to a very short, noncontractile tail. The amino-terminal 150 residues of the Det7 protein lack homology to the P22 tail spike and are probably responsible for binding to the base plate of the myoviral tail. Det7 tail spike lacking this putative particle-binding domain was purified from Escherichia coli, and well-diffracting crystals of the protein were obtained. The structure, determined by molecular replacement and refined at a 1.6-A resolution, is very similar to that of bacteriophage P22 tail spike. Fluorescence titrations with an octasaccharide suggest Det7 tail spike to bind its receptor lipopolysaccharide somewhat less tightly than the P22 tail spike. The Det7 tail spike is even more resistant to thermal unfolding than the already exceptionally stable homologue from P22. Folding and assembly of both trimeric proteins are equally temperature sensitive and equally slow. Despite the close structural, biochemical, and sequence similarities between both proteins, the Det7 tail spike lacks both carboxy-terminal cysteines previously proposed to form a transient disulfide during P22 tail spike assembly. Our data suggest receptor-binding module exchange between podoviruses and myoviruses in the course of bacteriophage evolution.","entities":[{"id":7,"label":"Receptor","start_offset":1212,"end_offset":1230},{"id":8,"label":"Phage","start_offset":1175,"end_offset":1179},{"id":11,"label":"Bacteria","start_offset":108,"end_offset":127},{"id":12,"label":"Phage","start_offset":1262,"end_offset":1265}],"relations":[{"id":4,"from_id":7,"to_id":8,"type":"Is_Receptor_Of"},{"id":5,"from_id":7,"to_id":11,"type":"Is_Receptor_Of"},{"id":6,"from_id":7,"to_id":12,"type":"Is_Receptor_Of"}]}
{"id":3,"text":"Identification of host receptor and receptor-binding module of a newly sequenced T5-like phage EPS7.The virulent bacteriophage EPS7 active against a number of Salmonella serovar and Escherichia coli strains, isolated from the local sewage in Korea, belongs to the family Siphoviridae. The ESP7 genome constitutes a linear double-stranded DNA of 111 382 bp. DNA sequencing and genomic analysis of EPS7 showed that it belongs to the phage T5 family. We identified the EPS7 genes involved in DNA repair, replication, viral structure and bacterial lysis by comparing the EPS7 genome with that of T5. In contrast, the tail genes encoding for putative host receptor-binding protein and the putative receptor-blocking lipoprotein precursor of EPS7 exhibit high homologies with the corresponding gene products of BF23, another member of the T5-family. BF23 binds to BtuB, a surface receptor in the host and involved in vitamin B12 uptake, but its infection is independent of TonB. By constructing a series of deletion mutants in Salmonella and in E. coli and studying phage infection in the mutant hosts, we showed that BtuB is also the host receptor of the phage EPS7. Whether EPS7 infection depends on TonB needs to be further studied.","entities":[{"id":13,"label":"Receptor","start_offset":858,"end_offset":862},{"id":14,"label":"Phage","start_offset":736,"end_offset":740},{"id":15,"label":"Bacteria","start_offset":159,"end_offset":177},{"id":16,"label":"Bacteria","start_offset":182,"end_offset":198},{"id":17,"label":"Receptor","start_offset":1112,"end_offset":1116},{"id":18,"label":"Phage","start_offset":1150,"end_offset":1160},{"id":19,"label":"Bacteria","start_offset":1021,"end_offset":1031},{"id":20,"label":"Bacteria","start_offset":1039,"end_offset":1046}],"relations":[{"id":7,"from_id":13,"to_id":14,"type":"Is_Receptor_Of"},{"id":8,"from_id":13,"to_id":15,"type":"Is_Receptor_Of"},{"id":9,"from_id":13,"to_id":16,"type":"Is_Receptor_Of"},{"id":10,"from_id":17,"to_id":18,"type":"Is_Receptor_Of"},{"id":11,"from_id":17,"to_id":20,"type":"Is_Receptor_Of"},{"id":12,"from_id":17,"to_id":19,"type":"Is_Receptor_Of"}]}

**Comment by TSAIJK** [comment]
补充一点，目前将max_seq_len提升为1024则显示显存不足，而调整到768可以运行，且前几个epoch的效果有较大提升

**Comment by linjieccc** [comment]
你好~UIE英文版本中关系schema的构造是按照``B + " of " + A``的形式，看下是否把关系的标签改成``receptor``，更符合自然语义的表达；另外看下是否可以将标注数据拆成短句，微调的效果会更好些

**Comment by TSAIJK** [comment]
> 你好~UIE英文版本中关系schema的构造是按照`B + " of " + A`的形式，看下是否把关系的标签改成`receptor`，更符合自然语义的表达；另外看下是否可以将标注数据拆成短句，微调的效果会更好些

你好！请教一个有关于标注的问题，同样还是在这个文本。比如”受体实体1“和”细菌实体1“之间的关系为您建议的”receptor“，那么标注时的箭头指向应该是什么呢？
（目前我标注的是”受体实体1“---（receptor）--->”细菌实体1“，想达到的语义是”受体实体1 是 细菌实体1 的受体“）
但是通过阅读验证集，其中出现了”receptor of 某个受体“的prompts，不知道是负例的影响还是我应该调整标注时箭头的方向？
