### ISSUE TITLE
[Question]: 希望提供分词、词性标准、NER这些常用功能在GPU条件下的rps测试报告

### ISSUE THREAD

**Issue by we-enjoy-today** [PaddlePaddle/PaddleNLP#3482]
### 请提出你的问题

https://mp.weixin.qq.com/s/dZDCaCskUeNQYl7sFfHTQQ
以这篇文章为例，已按照里面的步骤在GPU条件下测试了分词、词性标注、NER，但是测下来qps性能比较低，离上生产有距离：在GPU条件下，qps不到10。
所以希望官方使用Locust之类的性能测试工具，在提供api之余也提供性能测试标杆作为参考
我想知道我这里qps这么低是什么原因，有无办法能够提高？
因为在实际生产过程中，不仅关注精度也关注性能，在GPU条件下的qps性能就意味着成本、意味着从若干种NLP分词工具中如何选择的问题。

**Comment by ZeyuChen** [comment]
这个需求会在FastDeploy项目中满足，欢迎关注。

https://github.com/PaddlePaddle/FastDeploy

@we-enjoy-today

**Comment by we-enjoy-today** [comment]
> 这个需求会在FastDeploy项目中满足，欢迎关注。
> 
> https://github.com/PaddlePaddle/FastDeploy
> 
> @we-enjoy-today

哈哈哈，在FastDeploy中再次遇到了这个问题

https://github.com/PaddlePaddle/FastDeploy/issues/1033
