### ISSUE TITLE
[Question]: LAC有提供预训练模型的计划吗？

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleNLP#3486]
### 请提出你的问题

想在此基础上训练自己的词法分析模型

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/msra_ner  
可以看看这个，这个是定义词法分析模型 
不过是建议使用UIE来进行实体抽取的一些工作 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by KyleWang-Hunter** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/msra_ner 可以看看这个，这个是定义词法分析模型 不过是建议使用UIE来进行实体抽取的一些工作 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
但是使用UIE在速度方面确实达不到要求，只有CPU的环境。

**Comment by wawltor** [comment]
> > https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/msra_ner 可以看看这个，这个是定义词法分析模型 不过是建议使用UIE来进行实体抽取的一些工作 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
> > 但是使用UIE在速度方面确实达不到要求，只有CPU的环境。

考虑到速度问题，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie  可以看看这个，底做使用LSTM来encoder

**Comment by KyleWang-Hunter** [comment]
> > > https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/msra_ner 可以看看这个，这个是定义词法分析模型 不过是建议使用UIE来进行实体抽取的一些工作 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
> > > 但是使用UIE在速度方面确实达不到要求，只有CPU的环境。
> 
> 考虑到速度问题，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie 可以看看这个，底做使用LSTM来encoder

感谢
