### ISSUE TITLE
[Question]: 为啥感觉ernie-layout的attention实现方式和论文中写的不一样？

### ISSUE THREAD

**Issue by wantsjean** [PaddlePaddle/PaddleNLP#3489]
### 为啥感觉ernie-layout的attention实现方式和论文中写的不一样

论文中的 spatial-aware disentangled attention
![image](https://user-images.githubusercontent.com/20296222/196109633-4275ecf0-ea18-44e6-82f1-80c9e0559623.png)
ernie-layout代码中的实现:https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_layout/modeling.py#L315
这个attention和layoutlmv2一样的吧？

**Comment by wawltor** [comment]
考虑到商用，目前为降级开源，当前开出版本仍旧好于LayoutXLM，后续会适当的时候对外开源spatial-aware disentangled attention版本，如商业有需求请联系https://ai.baidu.com/tech/nlp/Textanalysis

**Comment by wantsjean** [comment]
@wawltor 我对比了下整个实现方式，当前版本的ErnieLayout和LayoutLMv2(XLM)似乎只有一个nn.GLEU的区别(加在了visul backbone后面)，其余都一样，这是否说明当前版本是否就是在LayoutXLM基础上增加了个阅读顺序预测的预训练？

**Comment by paulpaul91** [comment]
> @wawltor 我对比了下整个实现方式，当前版本的ErnieLayout和LayoutLMv2(XLM)似乎只有一个nn.GLEU的区别(加在了visul backbone后面)，其余都一样，这是否说明当前版本是否就是在LayoutXLM基础上增加了个阅读顺序预测的预训练？

当前版本与LayoutXLM没有直接关系（同为多语言文档预训练模型），我们使用百度自研的ERNIE-M 为文本侧基底https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-m， 图像侧只取了resnet101 前两层，没有使用FPN结构，layout 的embeding 我们采用的是相加的方案并非concat方案，预训练任务为论文中所说的四个。
