### ISSUE TITLE
[Question]: UIE Slim 数据蒸馏, 学生模型评估代码

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3501]
### 请提出你的问题

UIE Slim 数据蒸馏, 有学生模型评估的代码吗

**Comment by linjieccc** [comment]
学生模型的评估代码可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/data_distill/evaluate.py

示例：

```shell
python evaluate.py \
    --task_type relation_extraction \
    --test_path ./student_data/dev_data.json \
    --label_maps_path ./student_data/label_maps.json \
    --model_path ../checkpoint/model_best \
    --encoder ernie-3.0-base-zh
```

**Comment by MachineSheep** [comment]
> 学生模型的评估代码可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/data_distill/evaluate.py
> 
> 示例：
> 
> ```shell
> python evaluate.py \
>     --task_type relation_extraction \
>     --test_path ./student_data/dev_data.json \
>     --label_maps_path ./student_data/label_maps.json \
>     --model_path ../checkpoint/model_best \
>     --encoder ernie-3.0-base-zh
> ```

好的，感谢，可以补充在README里面

**Comment by linjieccc** [comment]
> > 学生模型的评估代码可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/data_distill/evaluate.py
> > 示例：
> > ```shell
> > python evaluate.py \
> >     --task_type relation_extraction \
> >     --test_path ./student_data/dev_data.json \
> >     --label_maps_path ./student_data/label_maps.json \
> >     --model_path ../checkpoint/model_best \
> >     --encoder ernie-3.0-base-zh
> > ```
> 
> 好的，感谢，可以补充在README里面

感谢指出，也欢迎给我们贡献PR~我们会无比欢迎和外部开发者一起建设
