### ISSUE TITLE
[Question]: 使用BiGRU + CRF训练实体抽取算法，导出静态图之后无法识别结果

### ISSUE THREAD

**Issue by KyleWang-Hunter** [PaddlePaddle/PaddleNLP#3507]
### 请提出你的问题

参照https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/waybill_ie文档，使用BiGRU + CRF训练了中文简历数据实体抽取模型，动态图的预测结果正常，如下图所示：
![image](https://user-images.githubusercontent.com/44918749/196634183-f8e735ee-a9d0-43f6-83ac-3745831c80d8.png)
但是zai在导出为动态图模型之后，无法识别结果，如下图所示：
![image](https://user-images.githubusercontent.com/44918749/196634509-0ce72d5f-734b-435d-8506-8366d3d30989.png)
请问下我是哪里出错了吗？

**Comment by wawltor** [comment]
看起来是export_model.py目前只是支持了 ERNIE + CRF这种模型，不支持BIGRU+CRF 
 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/export_model.py

我们看看能不能快速支持一下

**Comment by KyleWang-Hunter** [comment]
> 看起来是export_model.py目前只是支持了 ERNIE + CRF这种模型，不支持BIGRU+CRF https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/export_model.py
> 
> 我们看看能不能快速支持一下

感谢

**Comment by wawltor** [comment]
相关代码已经提交PR： https://github.com/PaddlePaddle/PaddleNLP/pull/3516

**Comment by KyleWang-Hunter** [comment]
> 相关代码已经提交PR： #3516
导出模型时报错，如下图所示：

![image](https://user-images.githubusercontent.com/44918749/196838825-30486456-bfb0-4031-8ba0-3eccc4697585.png)
![image](https://user-images.githubusercontent.com/44918749/196838867-a6613d2c-57ae-4089-bca6-d9a0057e2396.png)

**Comment by wawltor** [comment]
你的paddle版本是啥了？

**Comment by KyleWang-Hunter** [comment]
> 你的paddle版本是啥了？

2.3.2

**Comment by wawltor** [comment]
> > 你的paddle版本是啥了？
> 
> 2.3.2

麻烦把python段报错的信息再截图多一点

**Comment by wawltor** [comment]
> > > 你的paddle版本是啥了？
> > 
> > 
> > 2.3.2
> 
> 麻烦把python段报错的信息再截图多一点
而且需要使用的是 export_bigru_crf_model.py  脚本，而不是 export_ernie_crf_model.py

**Comment by wawltor** [comment]
而且需要使用的是 export_bigru_crf_model.py  脚本，而不是 export_ernie_crf_model.py

**Comment by KyleWang-Hunter** [comment]
> 而且需要使用的是 export_bigru_crf_model.py 脚本，而不是 export_ernie_crf_model.py

抱歉，模型路径配置错了，可以导出模型了。但是识别结果还是很差，跟动态图完全不一样。

**Comment by wawltor** [comment]
> > 而且需要使用的是 export_bigru_crf_model.py 脚本，而不是 export_ernie_crf_model.py
> 
> 抱歉，模型路径配置错了，可以导出模型了。但是识别结果还是很差，跟动态图完全不一样。

确认一下，export_bigru_crf_model.py 执行的输出有没有打印出  
```python
print("Loaded parameters from %s" % args.params_path) 
```
同时确保预测的时候使用的  `predict_bigru_crf.py`

**Comment by KyleWang-Hunter** [comment]
> > > 而且需要使用的是 export_bigru_crf_model.py 脚本，而不是 export_ernie_crf_model.py
> > 
> > 
> > 抱歉，模型路径配置错了，可以导出模型了。但是识别结果还是很差，跟动态图完全不一样。
> 
> 确认一下，export_bigru_crf_model.py 执行的输出有没有打印出
> 
> ```python
> print("Loaded parameters from %s" % args.params_path) 
> ```
> 
> 同时确保预测的时候使用的 `predict_bigru_crf.py`
![image](https://user-images.githubusercontent.com/44918749/196846525-cb839fb2-eccb-4eca-8d5a-8415311dfcfa.png)
![image](https://user-images.githubusercontent.com/44918749/196846590-63f8719c-bf13-4034-854a-bea22ba8a6d3.png)
![image](https://user-images.githubusercontent.com/44918749/196846681-fbfa3aa2-f44f-4cdb-bb7b-5922edc797be.png)

**Comment by wawltor** [comment]
如果方便的话 能提供一下数据，我们测试一下吗？

**Comment by KyleWang-Hunter** [comment]
> 如果方便的话 能提供一下数据，我们测试一下吗？

[data.zip](https://github.com/PaddlePaddle/PaddleNLP/files/9825912/data.zip)

**Comment by wawltor** [comment]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/16698950/196851403-e474add6-b8a3-4895-8008-d8d8142b66c1.png">
用你的数据最终微调的效果看起来f1都是0

**Comment by KyleWang-Hunter** [comment]
> <img alt="image" width="559" src="https://user-images.githubusercontent.com/16698950/196851403-e474add6-b8a3-4895-8008-d8d8142b66c1.png">
> 
> 用你的数据最终微调的效果看起来f1都是0

我是自己构造的数据集，所以在读取数据的时候修改了部分代码
![image](https://user-images.githubusercontent.com/44918749/196851877-071ed38c-6346-4291-867f-bb2cb561aa09.png)

**Comment by KyleWang-Hunter** [comment]
> <img alt="image" width="559" src="https://user-images.githubusercontent.com/16698950/196851403-e474add6-b8a3-4895-8008-d8d8142b66c1.png">
> 
> 用你的数据最终微调的效果看起来f1都是0
我是自己构造的数据集，所以在读取数据的时候需要修改部分代码
![image](https://user-images.githubusercontent.com/44918749/196851972-d0924f54-43c7-4ece-94a5-d575ad77dec9.png)

**Comment by wawltor** [comment]
那是不是在predict的脚本的数据处理也要同步修改？

**Comment by KyleWang-Hunter** [comment]
> 那是不是在predict的脚本的数据处理也要同步修改？

哎，实在抱歉，确实是。现在没问题了，感谢解答。

**Comment by wawltor** [comment]
好的 我们暂时关闭该issue，如有疑问 后续可以打开该issue。

**Comment by KyleWang-Hunter** [comment]
> 好的 我们暂时关闭该issue，如有疑问 后续可以打开该issue。
再请教下，如果是预测自己的没有标签的数据，predictor.predict里面的逻辑应该怎么写？
