### ISSUE TITLE
请问paddlenlp 有没有非自回归的语言模型

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleNLP#3508]
### 请提出你的问题

比如做到并行解码的

**Comment by wawltor** [comment]
能列举一下想要的模型吗？

**Comment by dlkht** [comment]
> 能列举一下想要的模型吗？

比如论文 ACL2021 "Glancing Transformer for Non-Autoregressive Neural Machine Translation"实现的模型

**Comment by wawltor** [comment]
> Non-Autoregressive

目前在机器模型翻译的模型中我们目前还没有Non-Autoregressive的模型，目前还是依赖于token by token，不过目前这种模型整体而言效果还是比 Non-Autoregressive 效果好点

**Comment by guoshengCS** [comment]
如果是说觉得自回归速度慢希望更快的生成的话，PaddleNLP针对GPU环境是有预测加速支持的可以试下
