### ISSUE TITLE
[Bug]: tokenizer.save_pretrained 报错

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/PaddleNLP#3514]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu: 2.3.2
- paddlenlp: 2.4.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
tokenizer.save_pretrained时，如果__init__的参数中含有lambda表达式，save_pretrained时会一起保存，导致json.dumps报错：TypeError: Object of type function is not JSON serializable。HF没有此类问题。

该问题目前仓库应该不会触发，若有类似写法则会触发：https://github.com/IDEA-CCNL/Fengshenbang-LM/blob/main/fengshen/examples/pegasus/tokenizers_pegasus.py#L110
```

### 稳定复现步骤 & 代码

-

**Comment by wj-Mcat** [comment]
在`__init__`中传入`lambda` or `function`其实是属于定制化的功能，且只在此tokenizer当中存在，所以在实现层可使用其他实现方式，伪代码如下所示：

```python

# 已经内置了默认的`pre_tokenizer`method
tokenizer = PegasusTokenizer.from_pretrained("model-name", pre_tokenizer="hmm")
```

然后在构造函数中根据字符串生成不同的`pre_tokenizer method`。

@gongel @guoshengCS 你们觉得如何？

**Comment by gongel** [comment]
目前我这边是把`pre_tokenizer`移到了构造函数来规避这个问题。但huggingface目前是支持`__init__`中传入`lambda or function`的，我们保存参数的时候是否没有做参数的筛选？

**Comment by wj-Mcat** [comment]
目前所有的参数都是存放在`init_config`、`init_args`，保存的时候主要是处理`init_args`这个特性。

如果`pre_tokenizer`的实现是固定的，我们可将其设置为字符串；如果灵活性非常高，那就在`PegasusTokenizer`中重写`save_pretrained`函数来实现function的序列化保存，核心逻辑还是：保存function or lambda的code object，反序列化的时候将其翻译成function object，具体可使用：`marshal`。
