### ISSUE TITLE
 ernie_doc关于长文本摘要生成的应用示例

### ISSUE THREAD

**Issue by Heimdall-Nss** [PaddlePaddle/PaddleNLP#3515]
### 请提出你的问题

请问ernie_doc有关于摘要生成的示例吗，目前应该提供了QA 分类等
或者对于长文本的摘要生成有更好的建议吗。简介中ernie_doc针对长文本的处理比较有意思，而长文本的摘要生成在某些应用场景更加需要，例如新闻稿，论文速览等。
我目前找到的途径是基于预训练模型unimo-text-1.0-summary进行微调 ，不知道此流程下能否导入ernie-doc进行训练和部署

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 请问ernie_doc有关于摘要生成的示例吗，目前应该提供了QA 分类等 或者对于长文本的摘要生成有更好的建议吗。简介中ernie_doc针对长文本的处理比较有意思，而长文本的摘要生成在某些应用场景更加需要，例如新闻稿，论文速览等。 我目前找到的途径是基于预训练模型unimo-text-1.0-summary进行微调 ，不知道此流程下能否导入ernie-doc进行训练和部署

目前我们没有计划使用ERNIE-DOC来做文本摘要，这样的文本摘要偏向于片段抽取，目前在技术方向上我们认为使用生成模型来文本摘要能更好做文本摘要的工作

**Comment by Heimdall-Nss** [comment]
谢谢回复，目前有看到基于ernie_gen和UNIMO-Text提供的预训练+微调框架，是利用这个吗

**Comment by wawltor** [comment]
> 谢谢回复，目前有看到基于ernie_gen和UNIMO-Text提供的预训练+微调框架，是利用这个吗

第一版主要是通过UNIMO-text来进行微调，目前我们正在做中文版本的[Pegasus摘要模型]，这个也是业内比较SOTA的模型

**Comment by Heimdall-Nss** [comment]
UNIMO-text的预训练模型目前好像没法下载了？
报错：
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 237, in from_pretrained
    file_path, default_root)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 168, in get_path_from_url
    fullpath = _download(url, root_dir, md5sum)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 205, in _download
    "{}!".format(url, req.status_code))
RuntimeError: Downloading from https://paddlenlp.bj.bcebos.com/models/transformers/community/unimo-text-1.0-summary/model_state.pdparams failed with code 404!

**Comment by wawltor** [comment]
> UNIMO-text的预训练模型目前好像没法下载了？ 报错： Traceback (most recent call last): File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 237, in from_pretrained file_path, default_root) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 168, in get_path_from_url fullpath = _download(url, root_dir, md5sum) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/downloader.py", line 205, in _download "{}!".format(url, req.status_code)) RuntimeError: Downloading from https://paddlenlp.bj.bcebos.com/models/transformers/community/unimo-text-1.0-summary/model_state.pdparams failed with code 404!

你可以提供一下运行代码吗？我们尝试一下

**Comment by Heimdall-Nss** [comment]
你好，今晚测试了相同代码发现能下载了

**Comment by wawltor** [comment]
嗯嗯 收到
