### ISSUE TITLE
同时使用paddlenlp-2.4.0 和 rocketqa-1.1.0时 AttributeError: 'paddle.fluid.core_avx.Tensor' object has no attribute 'numpy'

### ISSUE THREAD

**Issue by PhoneixT** [PaddlePaddle/PaddleNLP#3520]
### 请提出你的问题

AttributeError: 'paddle.fluid.core_avx.Tensor' object has no attribute 'numpy'
![image](https://user-images.githubusercontent.com/46696725/196861151-ae7c1313-96e7-460a-9711-03c9aa62aba8.png)
![image](https://user-images.githubusercontent.com/46696725/196861170-20d56a32-2a86-4ab4-86e4-ce0c674abfaf.png)

**Comment by wawltor** [comment]
这个是因为rocketqa发布的版本是静态图的版本，但是PaddleNLP目前是一个全动态图版本，两者在底层Tensor表示有冲突的，你可以import rocketqa之后切换到静态图了，而Taskflow是动态图的
