### ISSUE TITLE
[Question]: 使用uie-m-large模型报错

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3523]
### 请提出你的问题

**完整的报错信息如下**

RuntimeError                              Traceback (most recent call last)
Input In [7], in <cell line: 2>()
      1 schema = ['Time', "date"]
----> 2 ie2 = Taskflow('information_extraction', schema=schema, model="uie-m-large", schema_lang="en")

File ~/work/202211/event/paddlenlp/taskflow/taskflow.py:543, in Taskflow.__init__(self, task, model, mode, device_id, **kwargs)
    541 self.kwargs = kwargs
    542 task_class = TASKS[self.task][tag][self.model]['task_class']
--> 543 self.task_instance = task_class(model=self.model,
    544                                 task=self.task,
    545                                 priority_path=self.priority_path,
    546                                 **self.kwargs)
    547 task_list = TASKS.keys()
    548 Taskflow.task_list = task_list

File ~/work/202211/event/paddlenlp/taskflow/information_extraction.py:360, in UIETask.__init__(self, task, model, schema, schema_lang, **kwargs)
    358 self._check_task_files()
    359 self._check_predictor_type()
--> 360 self._get_inference_model()
    361 self._usage = usage
    362 self._is_en = True if model in ['uie-base-en'
    363                                 ] or schema_lang == 'en' else False

File ~/work/202211/event/paddlenlp/taskflow/task.py:254, in Task._get_inference_model(self)
    251 if self._predictor_type == "paddle-inference":
    252     self._config = paddle.inference.Config(self._static_model_file,
    253                                            self._static_params_file)
--> 254     self._prepare_static_mode()
    255 else:
    256     self._prepare_onnx_mode()

File ~/work/202211/event/paddlenlp/taskflow/task.py:174, in Task._prepare_static_mode(self)
    172 if self.task in ["document_intelligence", "knowledge_mining"]:
    173     self._config.switch_ir_optim(False)
--> 174 self.predictor = paddle.inference.create_predictor(self._config)
    175 self.input_names = [name for name in self.predictor.get_input_names()]
    176 self.input_handles = [
    177     self.predictor.get_input_handle(name)
    178     for name in self.predictor.get_input_names()
    179 ]

RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at /paddle/paddle/fluid/operators/load_combine_op.h:86)
  [operator < load_combine > error]

**Comment by linjieccc** [comment]
看报错应该是模型文件下载的问题，删除~/.paddlenlp/taskflow/information_extraction重新下载试试

**Comment by MachineSheep** [comment]
> 看报错应该是模型文件下载的问题，删除~/.paddlenlp/taskflow/information_extraction重新下载试试

删除了这个文件夹下的uie-m-large文件夹，然后重新下载，还是报错了

**Comment by MachineSheep** [comment]
> 看报错应该是模型文件下载的问题，删除~/.paddlenlp/taskflow/information_extraction重新下载试试
uie-m-large文件夹内容如下
![image](https://user-images.githubusercontent.com/109952192/196907710-8d8f08d0-6f2b-475d-bef8-24e018e772ea.png)

**Comment by linjieccc** [comment]
large模型比较大，有可能还是下载的问题，或者试试手动下载模型文件到这个目录~/.paddlenlp/taskflow/information_extraction/uie-m-large，链接：https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_m_large_v1.0/model_state.pdparams

**Comment by MachineSheep** [comment]
> 

手动下载之后，windows和linux系统上都还是报最初的错误

**Comment by MachineSheep** [comment]
> large模型比较大，有可能还是下载的问题，或者试试手动下载模型文件到这个目录~/.paddlenlp/taskflow/information_extraction/uie-m-large，链接：https://bj.bcebos.com/paddlenlp/taskflow/information_extraction/uie_m_large_v1.0/model_state.pdparams

model_state.pdparams详细属性如下
![image](https://user-images.githubusercontent.com/109952192/197101235-50634a0c-4b91-40c8-a2e6-aecdc58b29f9.png)

**Comment by linjieccc** [comment]
paddlenlp的版本是多少？

**Comment by MachineSheep** [comment]
> paddlenlp的版本是多少？

2.4.0

**Comment by linjieccc** [comment]
可以尝试看下model_state.pdparams这个文件对应的md5值是否是 75f3989c515f05f6842e314d3f75ee27

**Comment by MachineSheep** [comment]
> 可以尝试看下model_state.pdparams这个文件对应的md5值是否是 75f3989c515f05f6842e314d3f75ee27

![image](https://user-images.githubusercontent.com/109952192/197442780-796bd635-f2ad-48b8-82b1-223cc255d105.png)

md5值没有问题

**Comment by myboyliu** [comment]
我的也是同样问题。看看解决了吗？
-----------------------------------------
  File "D:\Anaconda3\envs\py3.8\lib\site-packages\paddlenlp\taskflow\task.py", line 174, in _prepare_static_mode
    self.predictor = paddle.inference.create_predictor(self._config)
RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:86)
  [operator < load_combine > error]
python-BaseException

**Comment by MachineSheep** [comment]
> ## 我的也是同样问题。看看解决了吗？
> File "D:\Anaconda3\envs\py3.8\lib\site-packages\paddlenlp\taskflow\task.py", line 174, in _prepare_static_mode self.predictor = paddle.inference.create_predictor(self._config) RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged. [Hint: Expected static_cast(*buffer) == true, but received static_cast(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:86) [operator < load_combine > error] python-BaseException

没有解决

**Comment by linjieccc** [comment]
Hi，可以check下机器的内存使用情况，看下是否有内存不足的问题

**Comment by xiahexiang2** [comment]
你好，我也遇到该问题了。请问是内存不足还是显存不足导致？至少需要多少内存或显存才能加载uie-m-larege

**Comment by xiahexiang2** [comment]
> Hi，可以check下机器的内存使用情况，看下是否有内存不足的问题

你好，我也遇到该问题了。请问是内存不足还是显存不足导致？至少需要多少内存或显存才能加载uie-m-larege

**Comment by jianxiaojin** [comment]
现在解决了吗？

**Comment by minghua-123** [comment]
现在解决了吗
