### ISSUE TITLE
[Question]:  安装paddlenlp后import报错

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#3528]
- 系统环境：Linux Centos7
- 没有使用conda环境，当前无法使用conda环境安装

![image](https://user-images.githubusercontent.com/65559675/197087829-45397951-cce2-4759-99ab-dcba0e7bafee.png)

**Comment by wawltor** [comment]
这个看起来是disutils安装有问题，你看看要不要重新安装一下

**Comment by wjddd** [comment]
已解决，感谢~
