### ISSUE TITLE
[Bug]: 根据官网部署说明，部署多标签分类报错

### ISSUE THREAD

**Issue by sxf20220704** [PaddlePaddle/PaddleNLP#3529]
### 软件环境

```Markdown
环境：
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server-gpu 0.9.0.post112
paddle2onnx               1.0.1
paddlefsl                 1.1.0
paddlenlp                 2.4.1
paddlepaddle-gpu          2.3.2.post112
```

### 重复问题

- [x] I have searched the existing issues

### 错误描述

```Markdown
根据官网使用 conda 部署 GPU 推理服务：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_label/deploy/paddle_serving/README.md，部署后报错，报错信息如下：
ERROR 2022-10-21 09:24:17,167 [error_catch.py:125] 
Log_id: 0
Traceback (most recent call last):
  File "/home/wb/miniconda3/envs/ke-nlp/lib/python3.9/site-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/home/wb/miniconda3/envs/ke-nlp/lib/python3.9/site-packages/paddle_serving_app/local_predict.py", line 286, in create_predictor_check
    predictor = paddle_infer.create_predictor(config)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)

Classname: LocalPredictor.load_model_config.<locals>.create_predictor_check
FunctionName: create_predictor_check
CRITICAL 2022-10-21 09:24:17,167 [local_predict.py:290] failed to create predictor: Log_id: 0  Raise_msg: (External) CUDA error(3), initialization error. 
  [Hint: cudaErrorInitializationError. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)
  ClassName: LocalPredictor.load_model_config.<locals>.create_predictor_check  FunctionName: create_predictor_check
```

### 稳定复现步骤 & 代码

官网的 multi_label 代码没有修改过，只是改过 config.yml 文件，模型也是用的官方数据训练出来的

**Comment by sxf20220704** [comment]
config.yml 配置如下所示：

#rpc端口, rpc_port和http_port不允许同时为空。当rpc_port为空且http_port不为空时，会自动将rpc_port设置为http_port+1
rpc_port: 18090

#http端口, rpc_port和http_port不允许同时为空。当rpc_port可用且http_port为空时，不自动生成http_port
http_port: 9878

#worker_num, 最大并发数。
#当build_dag_each_worker=True时, 框架会创建worker_num个进程，每个进程内构建grpcSever和DAG
#当build_dag_each_worker=False时，框架会设置主线程grpc线程池的max_workers=worker_num
worker_num: 1

#build_dag_each_worker, False，框架在进程内创建一条DAG；True，框架会每个进程内创建多个独立的DAG
build_dag_each_worker: false

dag:
    #op资源类型, True, 为线程模型；False，为进程模型
    is_thread_op: False

    #重试次数
    retry: 1

    #使用性能分析, True，生成Timeline性能数据，对性能有一定影响；False为不使用
    use_profile: false
    tracer:
        interval_s: 10

op:
    seq_cls:
        #并发数，is_thread_op=True时，为线程并发；否则为进程并发
        concurrency: 1

        #当op配置没有server_endpoints时，从local_service_conf读取本地服务配置
        local_service_conf:
            #client类型，包括brpc, grpc和local_predictor.local_predictor不启动Serving服务，进程内预测
            client_type: local_predictor

            #模型路径
            model_config: /home/wb/ke-nlp/multi_label/deploy/paddle_serving/serving_server

            #Fetch结果列表，以client_config中fetch_var的alias_name为准
            fetch_list: ["linear_75.tmp_1"]
            
            # device_type, 0=cpu, 1=gpu, 2=tensorRT, 3=arm cpu, 4=kunlun xpu
            device_type: 1

            #计算硬件ID，当devices为""或不写时为CPU预测；当devices为"0", "0,1,2"时为GPU预测，表示使用的GPU卡
            devices: "0"

            #开启MKLDNN加速
            use_mkldnn: False

            #thread_num
            thread_num: 12

            #ir_optim
            ir_optim: True
            
            #开启tensorrt后，进行优化的子图包含的最少节点数
            #min_subgraph_size: 10

**Comment by lugimzzz** [comment]
可能是cuda环境的问题，你启动docker使用nvidia-docker run的方式吗
