### ISSUE TITLE
[Question]: 使用压缩脚本压缩Ernie-CTM模型，报错operator < reshape2 > error

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/PaddleNLP#3531]
### 请提出你的问题

在按照https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/compression.md教程针对Ernie-CTM压缩时，运行报错，v reshape失败。
![image](https://user-images.githubusercontent.com/12699033/197141257-21a483f8-df46-44d2-bcf7-395dfc21b4a4.png)
综合情况，看起来是v的mutil-head数目减少了但是得到的特征没有减少。
比较奇怪的是测试q与k均正常，只是v不行了。
辛苦帮忙看一下。

**Comment by LiuChiachi** [comment]
您好，请问您的paddlenlp版本是？建议更新到最新版本再重试下。如果还是报错可以在`../paddlenlp/trainer/trainer_compress.py` 的`set_config`调用之前（下面第433行之前）帮忙打印下`print(net_config)`看下嘛

https://github.com/PaddlePaddle/PaddleNLP/blob/fb0cb9b35b94ee90d55e454e3bac4a5d9d4e7c47/paddlenlp/trainer/trainer_compress.py#L430-L433

<img width="656" alt="image" src="https://user-images.githubusercontent.com/26483581/197167532-e81684fd-7eec-4de0-a16d-cc5ad027b237.png">

**Comment by Fordacre** [comment]
@LiuChiachi 使用的是2.4版本，但是好像看起来最近有改动，所以又重新拉取了最新的代码，报错的地方变了，但是看起来仍然是一个问题。
![image](https://user-images.githubusercontent.com/12699033/197191211-a43f7800-7de4-4d7b-8604-1373c83ab24e.png)
下面是net_config.
`{'ernie_ctm.embeddings.word_embeddings': {'expand_ratio': 1.0}, 'ernie_ctm.embeddings.position_embeddings': {'expand_ratio': 1.0}, 'ernie_ctm.embeddings.token_type_embeddings': {'expand_ratio': 1.0}, 'ernie_ctm.embedding_hidden_mapping_in': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.0.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.0.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.0.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.0.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.0.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.0.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.1.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.1.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.1.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.1.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.1.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.1.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.2.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.2.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.2.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.2.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.2.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.2.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.3.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.3.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.3.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.3.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.3.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.3.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.4.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.4.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.4.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.4.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.4.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.4.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.5.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.5.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.5.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.5.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.5.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.5.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.6.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.6.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.6.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.6.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.6.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.6.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.7.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.7.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.7.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.7.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.7.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.7.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.8.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.8.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.8.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.8.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.8.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.8.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.9.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.9.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.9.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.9.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.9.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.9.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.10.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.10.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.10.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.10.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.10.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.10.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.11.self_attn.q_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.11.self_attn.k_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.11.self_attn.v_proj': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.11.self_attn.out_proj': {'expand_ratio': 1.0}, 'ernie_ctm.encoder.layers.11.linear1': {'expand_ratio': 0.75}, 'ernie_ctm.encoder.layers.11.linear2': {'expand_ratio': 1.0}, 'ernie_ctm.pooler.dense': {'expand_ratio': 0.75}, 'ernie_ctm.feature_fuse': {'expand_ratio': 0.75}, 'ernie_ctm.feature_output': {'expand_ratio': 1.0}, 'tag_classifier': {'expand_ratio': 0.75}, 'sent_classifier': {'expand_ratio': 1.0}, 'major_classifier': {'expand_ratio': 1.0}}`

**Comment by LiuChiachi** [comment]
您好，看了下可能是config这块的生成有bug以至于不能灵活适配所有类似结构的模型

麻烦尝试这样做一下，在`set_net_config`执行之前加上下面几行：
```
net_config['tag_classifier']['expand_ratio'] = 1.0
net_config['ernie_ctm.embedding_hidden_mapping_in']['expand_ratio'] = 1.0
net_config['ernie_ctm.pooler.dense']['expand_ratio'] = 1.0
net_config['ernie_ctm.feature_fuse']['expand_ratio'] = 1.0
```
如果没有解决，欢迎继续反馈，我后面会复现之后做下修复。

**Comment by Fordacre** [comment]
@LiuChiachi 问题已解决，感谢。
但是出现了另外一个问题，embedding层在export的时候报错了，后面通过修改这里得到了解决（将[1,1]改为了[1,8]，请问这样是可以的嘛？
![image](https://user-images.githubusercontent.com/12699033/197461146-88b8d097-040c-4659-b472-c43c444ccb9d.png)
另外请问一下，现在的压缩是不支持depth维度的压缩嘛，看文档好像没有相关介绍。

**Comment by LiuChiachi** [comment]
将[1,1]改为了[1,8]是可以的，可以用visualdl或者netron可视化下.pdmodel，结构应该是正常的。
之前 DynaBERT 的 depth 维度的压缩效果不好，掉点比较多，所以暂时没有接入，您有depth压缩的这方面的需求吗？

这里的体验我们会持续优化，感谢您提出的问题：)

**Comment by Fordacre** [comment]
是的，模型只是用宽度压缩感觉达不到预期的运行速度需求，所以也在看如何进行深度压缩。期待后续加入类似功能。感谢答疑。
