### ISSUE TITLE
[Question]: 测试集指的是test.txt还是data.txt?

### ISSUE THREAD

**Issue by coder-duibai** [PaddlePaddle/PaddleNLP#3544]
### 请提出你的问题

你好，请问测试集指的是test.txt还是data.txt，这两个txt之间有什么区别呢？

**Comment by lugimzzz** [comment]
test.txt一般是指带有数据标注的测试数据，文本分类应用中可以用于analysis/evaluate.py 评测模型的效果
data.txt一般是指不具有数据标注待预测的数据，文本分类应用中可以用于predict.py、deploy目录等，预测这些数据的分类结果

**Comment by coder-duibai** [comment]
你好，我有三个问题：
第一个问题是：我看evaluate.py中并未读取test.txt文件，读取的好像是dev.txt才算出的精确率和召回率，是这样的吗？
第二个问题是：predict.py如果读取的是data.txt，那么predict预测的时候没法计算精确率和召回率，这该怎么办呢？
第三个问题是：我想算test.txt文件中的精确率和召回率，那么test.txt实在evaluate.py中读取还是在predict.py中读取呢？

**Comment by lugimzzz** [comment]
Q1:因为有些数据集没有test.txt所以evaluate.py默认为'dev.txt',你可以修改参数 --dev_file 'test.txt'
Q2:predict.py针对待预测数据集（也就是没有标签的数据）预测结果，如果你要计算模型精度，请使用 analysis/evaluate.py
Q3:evaluate.py

**Comment by coder-duibai** [comment]
好的，还有一个问题，在训练的时候如果使用early_stop，则参数设置的时候是填True还是False，我看early_stop的默认参数是False，这个False是开启早停还是不开启呢？

**Comment by lugimzzz** [comment]
如果使用早停方式，则运行时加上--early_stop，不使用则不加。具体可搜索store_true用法
![image](https://user-images.githubusercontent.com/63761690/198180543-c71d374f-9818-4485-96fa-9357aaa86947.png)

**Comment by coder-duibai** [comment]
好的谢谢，我现在在使用evaluate.py运行test.txt，但日志一直停留在以下几行：

[2022-10-27 10:55:26,113] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieForSequenceClassification'> to load './checkpoint'.
W1027 10:55:26.114681 38326 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.1
W1027 10:55:26.118435 38326 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
W1027 10:55:26.118454 38326 gpu_resources.cc:101] WARNING: device: 0. The installed Paddle is compiled with CUDA 11.1, but CUDA runtime version in your machine is 11.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDA version.
[2022-10-27 10:55:28,943] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint'.

请问这种属于报错吗，一般评估结果需要多久才能出来？

**Comment by lugimzzz** [comment]
因为要跑一轮训练集和测试集，请耐心等待

**Comment by coder-duibai** [comment]
好的，谢谢。
还有一个问题向你请教：我这边是一个评论识别的文本分类任务，目前在使用ERNIE3.0-medium-zh测试效果，并需要作为在线模型进行使用。请问在ERNIE3.0中，选择哪一个模型可以更好的支持在线预测且效果相对不错，我这边qps满足300-500就行。

**Comment by lugimzzz** [comment]
这个还是要你去尝试，因为不同任务难度不同。如果特别简单的任务nano和medium效果基本没有差别，具体还是要去测试。

**Comment by coder-duibai** [comment]
好的，谢谢

**Comment by coder-duibai** [comment]
你好，我在运行evaluate.py后报了如下错误：
^[[32m[2022-10-27 10:55:28,943] [    INFO]^[[0m - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint'.^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - -----Evaluate model-------^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Train dataset size: 663232^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Dev dataset size: 221078^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Accuracy in dev dataset: 85.96%^[[0m
Traceback (most recent call last):
  File "analysis/evaluate.py", line 212, in <module>
    evaluate()
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "analysis/evaluate.py", line 163, in evaluate
    labels=list(range(len(label_list)))) * 100))
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 1707, in top_k_accuracy_score
    y_score = column_or_1d(y_score) if y_type == "binary" else y_score
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/sklearn/utils/validation.py", line 1039, in column_or_1d
    "y should be a 1d array, got an array of shape {} instead.".format(shape)
ValueError: y should be a 1d array, got an array of shape (221078, 2) instead.

请问这个报错是什么原因？
