### ISSUE TITLE
数据集寻找求助

### ISSUE THREAD

**Issue by THCNF** [PaddlePaddle/PaddleNLP#3548]
### 问题描述

你好，请问一下我由于研究需要，想要探究文本中一些关键字的谐音字的替换对文本分类准确度的影响。
请问有这样的数据集么，替换了文本中的字为其他谐音字。然后会导致模型输出的判断会失误。我想用这样的数据集来训练一个对谐音字有免疫效果的模型。如有，麻烦推荐一些数据集或者相关项目给我。谢谢！

**Comment by sijunhe** [comment]
@THCNF 
您好。如果是想模拟谐音字的话，应使用音近混淆集。这一块比较常用的应该是wang271k数据中的[混淆集](https://github.com/wdimmy/Automatic-Corpus-Generation/blob/master/corpus/confusion.txt). 音近的混淆集也比较容易自己构建，可以利用类似pypinyin这种库，最简单的逻辑大致是`你好 -> ni3 hao3 -> 拟好`
