### ISSUE TITLE
[Bug]: TaskFlow抽取摘要模型报错CUDA error 719

### ISSUE THREAD

**Issue by softpeng** [PaddlePaddle/PaddleNLP#3550]
### 软件环境

```Markdown
- paddlepaddle: --
- paddlepaddle-gpu: 2.3.2.post116
- paddlenlp: 2.4.1
```

### 重复问题

- [x] I have searched the existing issues

### 错误描述

```Markdown
WINDOWS SERVER 2012, NAVDIA A100, 安培架构，按照安装教程，推荐安培架构使用11.x。
我安装了
CUDA Toolkit 11.6.0:  https://developer.download.nvidia.com/compute/cuda/11.6.0/local_installers/cuda_11.6.0_511.23_windows.exe
cuDNN 8.4.0: 
https://developer.nvidia.com/compute/cudnn/secure/8.4.0/local_installers/11.6/cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive.zip 

运行TaskFlow进行摘要抽取时候报如下错误：
Exception has occurred: OSError

(External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:258)
  File "C:\Users\Administrator\Desktop\paddle\testSummary.py", line 14, in <module>
    result=summarizer(text)
```

### 稳定复现步骤 & 代码

import paddlenlp

from paddlenlp import Taskflow
summarizer = Taskflow("text_summarization", model='unimo-text-1.0-summary')
text="根据“十个工作日”原则，下轮调价窗口为8月23日24时。卓创资讯分析，原油价格或延续震荡偏弱走势，且新周期的原油变化率仍将负值开局，消息面对国内成品油市场并无提振。受此影响，预计国内成品油批发价格或整体呈现稳中下滑走势，但“金九银十”即将到来，卖方看好后期市场，预计跌幅较为有限。"
result=summarizer(text)

print(result)

**Comment by wawltor** [comment]
可以先看看是不是paddle的安装的问题
```python
import paddle 
paddle.utils.run_check()
```
如果check信息显示安装有问题，建议conda安装  
https://www.paddlepaddle.org.cn/

**Comment by softpeng** [comment]
![image](https://user-images.githubusercontent.com/13324817/197723520-e90ca9d4-217c-4ae4-9c4e-333b30768383.png)
run_check()没有问题。分词和信息抽取都没有问题。目前只发现 text_summarization和text_similarity有问题。

**Comment by softpeng** [comment]
> 可以先看看是不是paddle的安装的问题
> 
> ```python
> import paddle 
> paddle.utils.run_check()
> ```
> 
> 如果check信息显示安装有问题，建议conda安装 https://www.paddlepaddle.org.cn/

![image](https://user-images.githubusercontent.com/13324817/197726711-175d165a-6fe0-4055-a08e-27c0afc7def1.png)
run_check()没有问题。分词和信息抽取都没有问题。目前只发现 text_summarization和text_similarity有问题

**Comment by wawltor** [comment]
> > 可以先看看是不是paddle的安装的问题
> > ```python
> > import paddle 
> > paddle.utils.run_check()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果check信息显示安装有问题，建议conda安装 https://www.paddlepaddle.org.cn/
> 
> ![image](https://user-images.githubusercontent.com/13324817/197726711-175d165a-6fe0-4055-a08e-27c0afc7def1.png) run_check()没有问题。分词和信息抽取都没有问题。目前只发现 text_summarization和text_similarity有问题

显存是否有溢出了？

**Comment by softpeng** [comment]
> > > 可以先看看是不是paddle的安装的问题
> > > ```python
> > > import paddle 
> > > paddle.utils.run_check()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果check信息显示安装有问题，建议conda安装 https://www.paddlepaddle.org.cn/
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13324817/197726711-175d165a-6fe0-4055-a08e-27c0afc7def1.png) run_check()没有问题。分词和信息抽取都没有问题。目前只发现 text_summarization和text_similarity有问题
> 
> 显存是否有溢出了？

没有显存溢出

**Comment by gongel** [comment]
你好，我本地没有复现你的问题，看错误提示，应该是Paddle环境的问题。可以重装Paddle试试看：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html

**Comment by Adachi324** [comment]
请问这个问题解决了吗
