### ISSUE TITLE
[Bug]: 使用rocketqa-zh-nano-query-encoder后，上传文档数据报错

### ISSUE THREAD

**Issue by bruce0210** [PaddlePaddle/PaddleNLP#3555]
### 软件环境

```Markdown
- paddlepaddle:2.3.0
- paddlepaddle-gpu: false（cpu）
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用rocketqa-zh-nano-query-encoder后，上传文档数据报错，但同样的文档使用rocketqa-zh-base-query-encoder上传后是OK的。
```

### 稳定复现步骤 & 代码

这是使用rocketqa-zh-nano-query-encoder时的异常
![a8b3717e8d511d33e9675217c0f67c2](https://user-images.githubusercontent.com/100854336/197957754-178a9dc8-d32e-4553-baf6-8dc582f9e189.jpg)

这是继续使用rocketqa-zh-base-query-encoder上传后成功
![0e2adcdd9b3b6d74757355179f85a95](https://user-images.githubusercontent.com/100854336/197957802-ad9601d8-8708-408a-ade7-cefb5639d5b9.jpg)

**Comment by w5688414** [comment]
nano模型的维度是312，请参考这个配置进行修改。https://github.com/PaddlePaddle/PaddleNLP/blob/553ba12211133b78e3f4a4eda98a1334ce5dfaee/pipelines/rest_api/pipeline/semantic_search.yaml#L10
