### ISSUE TITLE
[Bug]: pipelines前端页面会重复上传文件

### ISSUE THREAD

**Issue by superzhaoyy** [PaddlePaddle/PaddleNLP#3564]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
我上传了文件，然后去点击检索，文件会被再次上传一遍。
另外我依次上传三个文件，每次新增文件会把老的也上传一遍
```

### 稳定复现步骤 & 代码

页面测试可以得出

**Comment by w5688414** [comment]
please refer to this pr. https://github.com/PaddlePaddle/PaddleNLP/pull/3568
