### ISSUE TITLE
[Question]: 使用evaluate评估模型没有结果

### ISSUE THREAD

**Issue by coder-duibai** [PaddlePaddle/PaddleNLP#3565]
### 请提出你的问题

你好，我在使用evaluate.py评估测试集test.txt的效果时，日志一直停留在以下几行：
`[2022-10-27 10:55:26,113] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieForSequenceClassification'> to load './checkpoint'.
W1027 10:55:26.114681 38326 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.1
W1027 10:55:26.118435 38326 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
W1027 10:55:26.118454 38326 gpu_resources.cc:101] WARNING: device: 0. The installed Paddle is compiled with CUDA 11.1, but CUDA runtime version in your machine is 11.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDA version.
[2022-10-27 10:55:28,943] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint'.`
请问这属于报错吗？

**Comment by lugimzzz** [comment]
请耐心等待
