### ISSUE TITLE
[Question]: 端到端文档抽取运行失败

### ISSUE THREAD

**Issue by lastrei** [PaddlePaddle/PaddleNLP#3567]
### 请提出你的问题

版本信息：
paddle-pipelines               0.3.0
paddlenlp                      2.4.1
paddlepaddle-gpu               2.3.1.post112
系统
windows 11

使用example/document-intelligence/docprompt_example.py 能够得到正常的返回值
按readME构建端到端流水线时：
从webui提交图片时出现错误：
webapp_docprompt_gradio.py端错误提示如下：
![image](https://user-images.githubusercontent.com/32331131/198207362-2f23536c-ea49-4c6f-a552-134adb72fd61.png)
res_api端错误提示如下：
![image](https://user-images.githubusercontent.com/32331131/198207715-9e8ba0c9-fa74-4915-aab3-39a00d0500a1.png)

检查res_api端接收的bs64后的图片代码无误

完整参数和错误提示如下
Exception: Exception while running node `Retriever` with input `{'root_node': 'Query', 'params': {'Query': {'debug': False}, 'Retriever': {'debug': False}}, 'meta': {'doc': '/9j/4AAQSkZJRgABAQEAYABgAAD/2wBD
AAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCABbAkMDASIAAhEBAxEB/8
QAGgABAQEBAQEBAAAAAAAAAAAAAAEDAgQFBv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIQAxAAAAH9+QrMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGjMaMxozGnPXJ0AAAzGjnk0YdmjKmjL
k3MDdlqGWoeb0gAAAAAAAAAAAAAAAAAAAAAAADnrk6y18xe8OE19Xh9R8ze50nr8Z3ePScLyZ875nq8/p85eu+oxdeo8Pv8AP6FAAAAAAAAAAAAAAAAAAAAAAAAc9cnQGegx2AAAAADnoAAAAAAAAAAAAAAAAAAAAAAAAAAAEo5tEURRFEURRFEURRFEURRFEURRFEURRFEURR
FEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFEURRFH//EACYQAAMBAAIBAgYDAQAAAAAAAAACEQEDEhNBYAQQIzEyUBQgITD/2gAIAQEAAQUC9laQhCEIQhCEIQhCEIQhCEIQhCEIQhCEIQhCEIQhCEIQhCEIQhCE
IQhCEIQhCE+W/f2R6/2755GfFN2Yr4wnKrtrou+RTHVt3kXG8q58m5kRs5E3TyZ3M5+Jm/Y+o79Fx278j9MV38hu5/J41V8/zeG7rb+PI+s3ftyI+efdzzPNS3j79BG4q/1OTMzfieL78v1N/Y+pzcfkTjTMbk1m4k3EdNbVzF4/iH7M2MvTY+7n1Hu8nErZw/fmx378dzPzXd
jYmu3dF3o3JuZmYmbnJ+x9fmyY+LxZm/8APVxv3Hr7KpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSl9lUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKUpSlKX2V/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAwEB
PwFe/8QAFBEBAAAAAAAAAAAAAAAAAAAAcP/aAAgBAgEBPwFe/8QAMhAAAQMDAgMFBQkAAAAAAAAAAQACERIhQQMxIlFhEBMyUOFicYGh8DBSY3CAkZKTsf/aAAgBAQAGPwL846MxKE5XojGOiIGFBcB8Va/uEqBM+5U3noFer+J7A0m6s9v79hby7IDr+aczgKl4AnaFtJNgqH
NHPfsNnFoF7pzqWAY4dk4Boq9kbrUANMnNlIpbRaZ9EzTiTu6Fpvh1MHCeTInaQnOqbB/EhEVN/uXC8CNyjRBZzP1dVnUBchp4F3LUB2hFni08FDSbuPl5pbBmFPc0oVNhxdsrtfU7LlxCCulGUTpA0kcShrg2OeFqXLrWdE/4h4oJk8JWmWjnuhxOb0hNdLiGg3cIXeUu7tGT
qNv930XUZc1AsPeOz9YVWp8Goxc+yrikfMqAnktAnPPza6mST1P2lwD+qT//xAAnEAACAwEAAgECBwEBAAAAAAAAEQFhkVEhMUEQcSBQYIGhsdEw8f/aAAgBAQABPyH9FSUHl78i8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4L
wXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXgvBeC8F4LwXn09H6Jn1/H8BIJnzKSfCN0v8AaUkvCcv2iZQhm7/mPDuSh3THs0P4Jz4iGplH9ko8kPcSyTGmURHzP+REuImPUnmILjwQyJEz8RD6fK4mLmZ9DhN+OkYitU/mU+v2+nmkyV0kjRmkHKTEcwwRZLUV
HlHw+kD1geXwNUHqn7pOP6J9UH7hEQIpfOSrwSSL/glKpexMTyEf18iRNwz/AEehJiHIcR7JMJZCn/ElDmzHU/2RGPwyETEoeXoPKIn7iY3/AMzKX2g8c7kfxBApEyi4kmoHzV1IsB8kTMrxH8yn1+30mgSJnyHyIBsR7cERoDxnz+wgelRJEuiBzXNiA1DymVnoNqST+x6Fny
nmBGChyEQez38BkkxKJ3oj7HnV8fJA0Uonwh/hDkJET4r+IJE2EURHv7o91ScqCUIhz6P/ABkSZZ8Pfj+hDEePR6j/AGSYxZiDn90TIzFP4mI/mkgUCiPUEcgl4hP5kn1+34IpDeJcTEqYGfDepcv+kUozkwyIiIUeI/N59P0TMOBzHuMEvBLwS8EvBLwS8EvBLwS8EvBLwS8E
vBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvP0V+7BLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS
8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvBLwS8EvP0V//2gAMAwEAAgADAAAAEOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPKHPPPPPMNMPOPPPPPPPPPPPPPPPPPPPPPPPPPPPj9+icTV
wdy9vPPPPPPPPPPPPPPPPPPPPPPPPPPHPPPPPLPPPPPPPPPPPPPPPPPPPPPPPPPPPPLDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDP/8QAFhEAAwAAAAAAAAAAAAAAAAAAAWBw/9oACAEDAQE/EE0RH//EABwRAAICAgMAAA
AAAAAAAAAAAAERABAgIUBQcP/aAAgBAgEBPxDq1S5wi3DQwFOHwj//xAApEAACAwACAQIGAgMBAAAAAAAAARFhkSHRMUFREGBxgaHBULEgMOHw/9oACAEBAAE/EPkrlolvhIlzf7iphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUw
qYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVMKmFTCphUwqYVM+HJdP9CXHyR+K/0Lx/l9xDHETGieVIdVw3pPtJAt1McziTY7oak6ZeOGkNOZ3LcQniV7qThB8wmxskSbZ20jQ8pJhtjxPBDJNWnAc+PCYppdLQpBT1KJToU2874E
vu22o/sYl6Eyb/AD8E16Bxyg7kandEinlxHuPTmQk0Jv6tR/Jfmv0LwLROiUcSeEOnmc0ceU5S5ONgZMJt7sYXKU858OE17/BuKWhPaTy/MtJvleBuOONa0jj6nmGNo+WTL4CByuH9OTl/Ic1GEpcG+VPmhSfNHb0tvAc/9GrYDrhwpSOH15HEgOlMptxD5ezEZF4DoluVwNsF
MmULn1t/cfCMJL+lwf3EckQjlHPMwnbkTuvKSuZhtv6qlikhkJKP2Z4X5YzY3Inn/j3FE00OGh7i2Q8ijw/1UKvrRfgP2/b+S/NfoXgVKHJ4Y+Uc34w7ufZQ3orioJFtD9Xo49RJSIfDAp5J8YSBeZVIfc40vn6o+bb+okeq8G+6tqXEofRZUljsJtQ7fH1Fk1uCRb9hxx6EMF
qolAj1OXXoI86qSCVK9eG190PB5Icxy/RuxIsUKSUQEnKn/hP352CJskz7TTfD5b+xKWNpbSn7pNcvoNEQbOcuHDX6J9TyjsvS33b/AOBELI3zssH6cwIUvKJpXojwqTf1Ft1oR4SFi0tw2inlqXH4/kvzX6F4+MaZ8zh7piGozUoR+Y9F/sgeTmEk/cQkJChJKEl/L+fTX9dC
8fJCovHs/YXEd9Ukq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3Ktyrcq3+Soeq2Kt+irfoq36Kt+irfoq36K
t+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36Kt+irfoq36+Sv/9k=', 'prompt': ['校验码是多少？']}, 'node_id': 'Retriever'}`: either dataset or sampler should be set, full stack trace: Traceback (most recent call last):

**Comment by lugimzzz** [comment]
看起来是后端的问题，你是否在启动后端前在命令行运行：
```
# 指定智能问答系统的Yaml配置文件
export PIPELINE_YAML_PATH=rest_api/pipeline/docprompt.yaml
export QUERY_PIPELINE_NAME=query_documents
```
看上去启动的不是docprompt yaml

启动完成后运行下面命令检查后端是否成功运行：

curl --request POST --url 'http://0.0.0.0:8891/query_documents' -H "Content-Type: application/json"  --data '{"meta": {"doc": "https://bj.bcebos.com/paddlenlp/taskflow/document_intelligence/images/invoice.jpg", "prompt": ["发票号码是多少?", "校验码是多少?"]}}'

**Comment by lastrei** [comment]
解决
问题出在
export PIPELINE_YAML_PATH=rest_api/pipeline/docprompt.yaml
export QUERY_PIPELINE_NAME=query_documents

windows 下使用set PIPELINE_YAML_PATH=rest_api/pipeline/docprompt.yaml 未生效造成启动的不是doc prompt服务
感谢
