### ISSUE TITLE
[Question]: pipeline ip地址访问限制

### ISSUE THREAD

**Issue by JaylonXiwei** [PaddlePaddle/PaddleNLP#3570]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/ernie_matching

我根据这个文档运行并且部署pipeline server，能够在linux本机使用8089端口号访问。但是我想在别的机器上通过ip访问我本机上的服务无法成功。

请问config_nlp.yml中如何设置ip地址为"0.0.0.0"，这样可以被其他机器访问到？谢谢

**Comment by wawltor** [comment]
ip地址为"0.0.0.0" 是本地地址，你可以把这个地址改成机器的ip地址

**Comment by w5688414** [comment]
Paddle Serving没有远程访问的限制，请检查一下linux的端口号是否开启，是否有防火墙那些
