### ISSUE TITLE
[Question]: ValueError: y should be a 1d array, got an array of shape (221078, 2) instead.

### ISSUE THREAD

**Issue by coder-duibai** [PaddlePaddle/PaddleNLP#3571]
### 请提出你的问题

你好，我在运行evaluate.py中报了如下错误：

^[[32m[2022-10-27 10:55:28,943] [    INFO]^[[0m - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint'.^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - -----Evaluate model-------^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Train dataset size: 663232^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Dev dataset size: 221078^[[0m
^[[32m[2022-10-27 13:39:57,670] [    INFO]^[[0m - Accuracy in dev dataset: 85.96%^[[0m
Traceback (most recent call last):
  File "analysis/evaluate.py", line 212, in <module>
    evaluate()
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "analysis/evaluate.py", line 163, in evaluate
    labels=list(range(len(label_list)))) * 100))
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 1707, in top_k_accuracy_score
    y_score = column_or_1d(y_score) if y_type == "binary" else y_score
  File "/data/user/lijinze/miniconda3/envs/env1/lib/python3.7/site-packages/sklearn/utils/validation.py", line 1039, in column_or_1d
    "y should be a 1d array, got an array of shape {} instead.".format(shape)
ValueError: y should be a 1d array, got an array of shape (221078, 2) instead.

根据报错提示，好像是top_k_accuracy_score的问题，源代码地址为：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_class/analysis/evaluate.py

请问我该如何修改呢？

**Comment by lugimzzz** [comment]
你测试少量数据，打印一下 top_k_accuracy_score 输入labels，probs，list(range(len(label_list)))看看，看起来是输入的问题

**Comment by lugimzzz** [comment]
是不是二分类任务，建议直接删掉top_k_accuracy_score 相关代码，这块代码我们也会相应优化
```python
logger.info("Top-2 accuracy in dev dataset: {:.2f}%".format(
    top_k_accuracy_score(y_true=labels,
                        y_score=probs,
                        k=2,
                        labels=list(range(len(label_list)))) * 100))
logger.info("Top-3 accuracy in dev dataset: {:.2f}%".format(
    top_k_accuracy_score(y_true=labels,
                        y_score=probs,
                        k=3,
                        labels=list(range(len(label_list)))) * 100))
```
