### ISSUE TITLE
[Question]: uie-m-base模型不能直接用evaluate.py进行评估

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3572]
### 请提出你的问题

uie-m-base模型直接用evaluate.py进行评估报下面的错误

AssertionError: pretrained base model should be ErnieModel

该如果对uie-m-base模型进行0-shot评估呢？

**Comment by wawltor** [comment]
支持ENRIE-M的RP： https://github.com/PaddlePaddle/PaddleNLP/pull/3227/files

**Comment by MachineSheep** [comment]
好的，感谢
