### ISSUE TITLE
[Question]: Error of Taskflow("question_generation")

### ISSUE THREAD

**Issue by myloveduoduo0920** [PaddlePaddle/PaddleNLP#3574]
### 请提出你的问题

When I try the example of the question_generation module in Taskflow, there is a error.

![1](https://user-images.githubusercontent.com/29173642/198226119-0295a21a-d6d5-4d01-8647-546b5ecc40ab.PNG)
![2](https://user-images.githubusercontent.com/29173642/198226151-f3e0ec2e-8359-4216-97a0-29eeb9368898.PNG)

How can I solve it?

**Comment by wawltor** [comment]
请升级到最新的PaddleNLP develop版本，或者等到明天也可以，今天晚上我们会发布2.4.2版本  https://github.com/PaddlePaddle/PaddleNLP/issues/3563
