### ISSUE TITLE
[Question]:bert  static目录下pretrain代码bug

### ISSUE THREAD

**Issue by rGitcy** [PaddlePaddle/PaddleNLP#3575]
### 请提出你的问题

您好，
使用https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.4/model_zoo/bert/static/run_pretrain.py做训练时程序会卡在：
![image](https://user-images.githubusercontent.com/8943172/198232705-b4bed714-6bca-49b9-ba50-dd401ebd7811.png)
经debug发现代码有个bug:
![image](https://user-images.githubusercontent.com/8943172/198233022-fffad947-3c97-475c-baa6-3277fbdb7e60.png)
按照此写法两个值都是1，程序不会执行，修改f_start_id+1->f_start_id程序可以跑起来。
![image](https://user-images.githubusercontent.com/8943172/198233331-3e20d734-01ef-45be-bd18-72cc907c072d.png)
想跟官方确认此处bug以及修改是否合理。

**Comment by ZHUI** [comment]
此为bug，可以的，这样修改是合理的。

**Comment by rGitcy** [comment]
> 此为bug，可以的，这样修改是合理的。

非常感谢，我先按这个修改即可对吧？请问官网上会更新修复后的代码吗？
