### ISSUE TITLE
[Question]: 文图生成

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleNLP#3580]
### 请提出你的问题

1.您好，文图生成的有提供离线模型吗？谢谢

**Comment by JunnYu** [comment]
请问您是需要使用什么模型呢？
如果是当前比较热门的StableDiffusion的话，可以查看一下这个目录 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers
