### ISSUE TITLE
[Question]: 请问ernie-layout的预训练code会开源吗？

### ISSUE THREAD

**Issue by NextGuido** [PaddlePaddle/PaddleNLP#3581]
### 请提出你的问题

请问ernie-layout的预训练code会开源吗？我目前想做阅读顺序检测，想参考一下预训练的代码看看怎么实现

**Comment by wawltor** [comment]
目前还没有开源计划，因为预训练模型的训练流程比较复杂，最近还在代码整理的工作，后续看看是否能放开预训练流程。

**Comment by NextGuido** [comment]
恩恩，感谢这么棒的项目！期待开源
