### ISSUE TITLE
[Question]: 文图生成模块如何运行

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleNLP#3583]
### 请提出你的问题

请问这个地方如何运行啊？我是把这个代码贴到python文件中来执行吗？如果是，放到哪个目录下呢？如果不是，该怎么使用这个代码来实现文图生成功能的呢？谢谢了

![image](https://user-images.githubusercontent.com/43515926/198281625-cc428af2-48cd-4ffe-9702-3fd0bce2b0a9.png)

**Comment by JunnYu** [comment]
StableDiffusion模型推荐查看这里的文档。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/diffusers_paddle
非StableDiffusion模型推荐使用Taskflow快速调用。
详细命令如下：
### 步骤1. 安装依赖
```bash
# 安装paddle，参考 https://www.paddlepaddle.org.cn/
# 安装paddlenlp
pip install "paddlenlp>=2.4.1"
```
### 步骤2. 开始使用 (注意删除里面的 >>>)
```bash 
from paddlenlp import Taskflow
# 默认模型为 pai-painter-painting-base-zh
text_to_image = Taskflow("text_to_image")
# 单条输入， 默认返回2张图片。
image_list = text_to_image("风阁水帘今在眼，且来先看早梅红")
image_list[0][0].save("painting-figure-1.png")
image_list[0][1].save("painting-figure-2.png")
```

**Comment by zcswdt** [comment]
> StableDiffusion模型推荐查看这里的文档。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/diffusers_paddle 非StableDiffusion模型推荐使用Taskflow快速调用。 详细命令如下：


谢谢大佬回复，还有下列模型在哪里下载呢？
![image](https://user-images.githubusercontent.com/43515926/198286199-967214c0-be74-47c5-8c73-f524fa884f99.png)

**Comment by JunnYu** [comment]
您只需要将model中的xxxxxx替换成上面就可以了。
```python
text_to_image = Taskflow("text_to_image", model="xxxxxxxxxxxx")
```

**Comment by zcswdt** [comment]
> 您只需要将model中的xxxxxx替换成上面就可以了。
> 
> ```python
> text_to_image = Taskflow("text_to_image", model="xxxxxxxxxxxx")
> ```

我看使用默认模型的时候，生成的图片只有256*256，那么如何改变生成图片大小？还有就是其他模型都哪里下载呢？谢谢你

**Comment by JunnYu** [comment]
![image](https://user-images.githubusercontent.com/50394665/198539081-c41d5dea-cff1-479e-894f-065157b8aed8.png)
目前部分模型不支持修改图片大小，StableDiffusion支持修改图片大小。
文件下载可能比较复杂，当前没有统一的下载方式。
当前可以使用上述命令自动下载，然后可以查看自动下载所对应的文件目录。

**Comment by zcswdt** [comment]
> 前部分模型不支持修改图片大小，StableDiffusion支持修改图片大小。
> 文件下载可能比较复杂，当前没有统一的下载方式。
> 当前可以使用上述命令自动下载，然后可以查看自动下载所

可以发一下实验命令下载的地址吗？我想去下载一下模型，试试效果。

**Comment by JunnYu** [comment]
你好，只需要有网络，模型会自动加载缓存下来的
```python
from paddlenlp import Taskflow
# 默认模型为 pai-painter-painting-base-zh
text_to_image = Taskflow("text_to_image")
# 单条输入， 默认返回2张图片。
image_list = text_to_image("风阁水帘今在眼，且来先看早梅红")
image_list[0][0].save("painting-figure-1.png")
image_list[0][1].save("painting-figure-2.png")
```
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/50394665/198755353-fbb9e0f5-6224-409e-82f9-adeb333a050b.png">

**Comment by zcswdt** [comment]
> xxxxx替换成上面就
比如说以下的这些网络呢？也是加载了直接可以下载下来吗？
![image](https://user-images.githubusercontent.com/43515926/198803372-b75419c1-050c-45bc-9d3e-bcf5c7b6eb03.png)
