### ISSUE TITLE
[Question]: stable-diffusion-v1-5

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleNLP#3588]
### 请提出你的问题

请问这个模型是如何下载呢？我去了diffusion官网，是下载如下的模型吗？如果不是，该zen'm怎么下载呢？
![image](https://user-images.githubusercontent.com/43515926/198309264-c41e14cd-4563-4865-a7fb-610758dc9c40.png)

**Comment by JunnYu** [comment]
你好，你是需要下载原版模型吗？还是要下载paddle版本的模型？
如果是当前paddle版本的话，目前还没有统一的下载方式。
你可以在机器上
```python
from ppdiffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.save_pretrained("你需要保存的文件夹地址")

```

**Comment by zcswdt** [comment]
> ```python
> pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
> ```
您好，运行你这个代码，还是下载不了这个模型，我环境配置都没问题，请问怎么解决呢？或者是方便发给我一份模型吗？谢谢你。
![image](https://user-images.githubusercontent.com/43515926/198970537-496a4c96-33e4-4bc8-bd57-cf63f065e202.png)

**Comment by JunnYu** [comment]
windwos环境下"/"可能跟linux不太一样，所以有问题，
<img width="520" alt="image" src="https://user-images.githubusercontent.com/50394665/199004476-fa88ad97-1066-4835-956f-02daeb9e34d5.png">
你好，我大约知道是什么问题了，我给你个脚本吧，可以下载

**Comment by zcswdt** [comment]
> 我大约知道是什么问题了，我给你个

好的，脚本怎么给我呢，谢谢了

**Comment by zcswdt** [comment]
> windwos环境下"/"可能跟linux不太一样，所以有问题， <img alt="image" width="520" src="https://user-images.githubusercontent.com/50394665/199004476-fa88ad97-1066-4835-956f-02daeb9e34d5.png"> 你好，我大约知道是什么问题了，我给你个脚本吧，可以下载

我邮箱jhsignal@126.com

> > 
> 
谢谢谢谢！脚本可以发给我邮箱吗？jhsignal@126.com

**Comment by JunnYu** [comment]
```python
from paddlenlp.utils.downloader import get_path_from_url
def download(model_name, cache_dir):
    file = [
     'model_index.json',
     'tokenizer/vocab.json',
     'tokenizer/special_tokens_map.json',
     'tokenizer/merges.txt',
     'tokenizer/tokenizer_config.json',
     'tokenizer/added_tokens.json',
     'text_encoder/model_config.json',
     'text_encoder/model_state.pdparams',
     'unet/model_state.pdparams',
     'unet/config.json',
     'feature_extractor/preprocessor_config.json',
     'safety_checker/model_config.json',
     'safety_checker/model_state.pdparams',
     'scheduler/scheduler_config.json',
     'vae/model_state.pdparams',
     'vae/config.json']
    base_url = "https://bj.bcebos.com/paddlenlp/models/community/"
    for f in file:
        url = base_url + model_name + "/" + f
        suffix = f.split("/")[0]
        new_cache_dir = cache_dir + "/" + suffix if suffix!='model_index.json' else cache_dir
        get_path_from_url(url, new_cache_dir)
        
# 输入你的想要下载的模型名称
model_name = "runwayml/stable-diffusion-v1-5"
# 保存的路径
cache_dir = "./stable-diffusion-v1-5"
download(model_name, cache_dir)
```

**Comment by zcswdt** [comment]
> ```python
> from paddlenlp.utils.downloader import get_path_from_url
> def download(model_name, cache_dir):
>     file = [
>      'model_index.json',
>      'tokenizer/vocab.json',
>      'tokenizer/special_tokens_map.json',
>      'tokenizer/merges.txt',
>      'tokenizer/tokenizer_config.json',
>      'tokenizer/added_tokens.json',
>      'text_encoder/model_config.json',
>      'text_encoder/model_state.pdparams',
>      'unet/model_state.pdparams',
>      'unet/config.json',
>      'feature_extractor/preprocessor_config.json',
>      'safety_checker/model_config.json',
>      'safety_checker/model_state.pdparams',
>      'scheduler/scheduler_config.json',
>      'vae/model_state.pdparams',
>      'vae/config.json']
>     base_url = "https://bj.bcebos.com/paddlenlp/models/community/"
>     for f in file:
>         url = base_url + model_name + "/" + f
>         suffix = f.split("/")[0]
>         new_cache_dir = cache_dir + "/" + suffix if suffix!='model_index.json' else cache_dir
>         get_path_from_url(url, new_cache_dir)
>         
> # 输入你的想要下载的模型名称
> model_name = "runwayml/stable-diffusion-v1-5"
> # 保存的路径
> cache_dir = "./stable-diffusion-v1-5"
> download(model_name, cache_dir)
> ```

您好，我下载玩模型了，加载模型的这个函数，pipe = StableDiffusionPipeline.from_pretrained("路径")，这“路径”是替换模型的路径吗？

**Comment by zcswdt** [comment]
> > ```python
> > from paddlenlp.utils.downloader import get_path_from_url
> > # 输入你的想要下载的模型名称
> > model_name = "runwayml/stable-diffusion-v1-5"
> > # 保存的路径
> > cache_dir = "./stable-diffusion-v1-5"
> > download(model_name, cache_dir)
> > ```
> 

您好，我下载玩模型了，加载模型的这个函数，pipe = StableDiffusionPipeline.from_pretrained("路径")，这“路径”是替换模型的路径吗？

**Comment by JunnYu** [comment]
是的，替换成cache_dir = "./stable-diffusion-v1-5"，这个路径，当然你也可以改名字

**Comment by zcswdt** [comment]
> 是的，替换成cache_dir = "./stable-diffusion-v1-5"，这个路径，当然你也可以改名字

好的，那谢谢你了！可以加个V吗？如果可以，可以给V发到我邮箱，jhsignal@126.com，我加你，谢谢了！
