### ISSUE TITLE
[Question]: 关于UIE微调参数问题

### ISSUE THREAD

**Issue by crackso** [PaddlePaddle/PaddleNLP#3593]
### 关于UIE微调参数问题

老师你好，非常荣幸找到uie模型，我在使用uie当中，有几个问题咨询下。

在CMeEE中表格里面提示bert模型采用的learning_rate 采用4e-5，num_epochs使用5，
在ernie-health模型中num_epochs是2，learning_rate 6e-5，
但在uie中给出的示例num_epochs写了100，然后learning_rate 默认1e-5，具体上这样会有什么区别呢。

我在aistudio上走了4200步左右花了大约8小时，后续由于网络原因中断了。目前还不清楚，这样是否正常，需要调整这些参数么？谢谢

**Comment by wawltor** [comment]
不同的模型的学习率、num_epochs、batch_size都是调整的，这里没有一个确定的数据，e-5是一个经验值，在这个范围的学习率训练出来的模型相对稳定，具体的值可以自己调整；UIE可以直接使用默认参数训练

**Comment by crackso** [comment]
感谢老师！
1，目前有关于uie在CMeEE上的表现情况吗？
2，uie模型在除了实体任务外，其他任务的表现如何？如果需要让模型拥有其他类型任务能力的话，可以继续在uie上微调呢还是建议使用别的ernie-base或者ernie-medical模型去微调；

**Comment by wawltor** [comment]
> 感谢老师！ 1，目前有关于uie在CMeEE上的表现情况吗？ 2，uie模型在除了实体任务外，其他任务的表现如何？如果需要让模型拥有其他类型任务能力的话，可以继续在uie上微调呢还是建议使用别的ernie-base或者ernie-medical模型去微调；

1. CMeEE 我们之前做过实验，效果好于ERNIE-Health效果 
2. UIE的效果在关系抽取、观点抽取效果都不错，这个是业务经验，具体的效果和数据、场景有关系；建议uie-base微调

**Comment by crackso** [comment]
嗯。感谢。
1，那我是否可以这样理解，其实uie模型在多任务上的效果和其他模型相差不大，尤其实体方面会更优秀一点对吗？
2，另外我目前使用默认参数，在CMeEE的数据层面上做了点优化，训练大约11000步。提交cblue的F1值为56。老师给评价下是否和预期相符合呢？

**Comment by wawltor** [comment]
> 嗯。感谢。 1，那我是否可以这样理解，其实uie模型在多任务上的效果和其他模型相差不大，尤其实体方面会更优秀一点对吗？ 2，另外我目前使用默认参数，在CMeEE的数据层面上做了点优化，训练大约11000步。提交cblue的F1值为56。老师给评价下是否和预期相符合呢？

1. 实体抽取的效果相对好
2. CMeEE理论上还是提升一点，ERNIE-Health效果可以持平 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-health

**Comment by crackso** [comment]
好的，老师。目前我准备了两个方案正在验证，uie这边目前还在训练中，33次，69300步。
best F1 performence has been updated: 0.72082 --> 0.72499
有好消息我在回复老师。

**Comment by crackso** [comment]
训练完成了，花了8天左右，20多w步，训练了2次，感觉分数始终没有什么提高。目前还只是uie-base的上的微调，从cblue上的原始数据中整理出了2份数据（相差5k），少的那份数据集上分数高点，多的反而分数降低了。目前不清楚该从什么方向再去调整。老师帮忙指点下。

**Comment by crackso** [comment]
跑了快一个月了，总结下：
全量cblue数据微调，13w的训练数据，4w的验证数据，100步计算一次，约1天跑一个ep，基本上bestF1出现在4~9个ep之间（后面又跑了10几天基本上无变化）。目前f1，CMeEE，v1版本60分，v2版本75，成绩还是比较理想的。后续还准备对ernie-health模型做个对比。

另外不知道老师是否有可以提高f1的方案，感谢老师。

**Comment by ProximaMonkey** [comment]
> 跑了快一个月了，总结下：
> 
> 全量cblue数据微调，13w的训练数据，4w的验证数据，100步计算一次，约1天跑一个ep，基本上bestF1出现在4~9个ep之间（后面又跑了10几天基本上无变化）。目前f1，CMeEE，v1版本60分，v2版本75，成绩还是比较理想的。后续还准备对ernie-health模型做个对比。
> 
> 
> 
> 另外不知道老师是否有可以提高f1的方案，感谢老师。

请问后来研究ernie-health模型对比了吗？效果如何？
