### ISSUE TITLE
[Docs]: 想问下就是关于一些token具体代表的含义

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#3611]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 详细描述

```Markdown
eos_id = vocab[tokenizer.sep_token]
sos_id = vocab[tokenizer.cls_token]
pad_id = vocab[tokenizer.pad_token]
unk_id = vocab[tokenizer.unk_token]
就是其中sep_token cls_token 这些token具体的实际在句子中的意义，可以在哪里看到每个模型相关这方面的东西呢
```

**Comment by wawltor** [comment]
sep_token 是 分割token，表示上下两句的分隔符，CLS这个是BERT系列的模型结构有关，建议去看一下BERT模型结构

具体的模型结构代码可以看 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/transformers/ernie  
BERT模型结构详解  https://blog.csdn.net/u011412768/article/details/108015783
