### ISSUE TITLE
[Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp

### ISSUE THREAD

**Issue by vesper1012** [PaddlePaddle/PaddleNLP#3613]
### 请提出你的问题

在paddle里运行2021 CCF BDCI 千言-问题匹配鲁棒性评测Baseline时, 运行至
import paddlenlp as ppnlp报错: TypeError: can't apply this __setattr__ to type object

**Comment by w5688414** [comment]
请详细说一下您的环境，您是使用的这里的代码吗？

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/question_matching

请确保安装了paddlenlp，并升级最新版本：
```
pip install --upgrade paddlenlp
```

**Comment by vesper1012** [comment]
您好&nbsp;
我是在AIstudio平台里面运行的&nbsp;
https://aistudio.baidu.com/bd-gpu-01/user/2913358/4922366/notebooks/4922366.ipynb




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
请详细说一下您的环境，您是使用的这里的代码吗？
 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/question_matching
 
请确保安装了paddlenlp，并升级最新版本：
 pip install --upgrade paddlenlp

**Comment by vesper1012** [comment]
您好 
我是在AIstudio平台里面运行的 
https://aistudio.baidu.com/bd-gpu-01/user/2913358/4922366/notebooks/4922366.ipynb
paddlenlp已经安装好了

运行报错:
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)/tmp/ipykernel_145/2093448463.py in <module&gt;      10 import paddle.nn.functional as F      11  ---&gt; 12 import paddlenlp as ppnlp      13 from paddlenlp.data import Stack, Tuple, Pad      14 from paddlenlp.datasets import load_dataset /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/__init__.py in <module&gt;      22         "Please import paddlenlp before datasets module to avoid download issues"      23     ) ---&gt; 24 from . import data      25 from . import datasets      26 from . import embeddings /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/data/__init__.py in <module&gt;      14       15 from .collate import * ---&gt; 16 from .data_collator import *      17 from .vocab import *      18 from .sampler import * /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/data/data_collator.py in <module&gt;      21 import warnings      22 from dataclasses import dataclass ---&gt; 23 from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy      24       25 __all__ = [ /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py in <module&gt;      13 # limitations under the License.      14  ---&gt; 15 from .model_utils import PretrainedModel, register_base_model      16 from .tokenizer_utils import PretrainedTokenizer, BPETokenizer, tokenize_chinese_chars, is_chinese_char, AddedToken, normalize_chars, tokenize_special_chars, convert_to_unicode      17 from .processing_utils import ProcessorMixin /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py in <module&gt;      76       77 @six.add_metaclass(InitTrackerMeta) ---&gt; 78 class PretrainedModel(Layer, GenerationMixin):      79     """      80     The base class for all pretrained models. It mainly provides common methods /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py in wrapper(cls)     892         if hasattr(cls, '__qualname__'):     893             orig_vars['__qualname__'] = cls.__qualname__ --&gt; 894         return metaclass(cls.__name__, cls.__bases__, orig_vars)     895     return wrapper     896  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py in __init__(cls, name, bases, attrs)     130                                  None) if '__init__' in attrs else None     131         cls.__init__ = InitTrackerMeta.init_and_track_conf( --&gt; 132             init_func, pre_init_func, post_init_func)     133         super(InitTrackerMeta, cls).__init__(name, bases, attrs)     134  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/utils.py in __setattr__(self, name, value)     170     def __setattr__(self, name, value):     171         value = adapt_stale_fwd_patch(self, name, value) --&gt; 172         return super(InitTrackerMeta, self).__setattr__(name, value) TypeError: can't apply this __setattr__ to type object


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
请详细说一下您的环境，您是使用的这里的代码吗？
 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/question_matching
 
请确保安装了paddlenlp，并升级最新版本：
 pip install --upgrade paddlenlp

**Comment by w5688414** [comment]
@vesper1012 Hi，请把项目分享一下，这个链接我打不开

**Comment by vesper1012** [comment]
您好:
项目地址是这个 不知道您是否可以打开:
https://aistudio.baidu.com/aistudio/projectdetail/4922366?forkThirdPart=1






Vesper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
@vesper1012 Hi，请把项目分享一下，这个链接我打不开

**Comment by vesper1012** [comment]
是这个比赛的baseline:
https://aistudio.baidu.com/aistudio/competition/detail/130/0/introduction
我点击直接在aistudio里面运行, 进入以后环境正常但是会出现上述报错




Vesper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
@vesper1012 Hi，请把项目分享一下，这个链接我打不开

**Comment by w5688414** [comment]
@vesper1012  Hi, 升级Paddle版本就能解决这个问题。我重新发布了一个升级成2.4版本的项目，请参考。

https://aistudio.baidu.com/aistudio/projectdetail/4942734

**Comment by vesper1012** [comment]
您好:
收到 可以run成功了 感谢回复~




Vesper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
@vesper1012  Hi, 升级Paddle版本就能解决这个问题。我重新发布了一个升级成2.4版本的项目，请参考。
 
https://aistudio.baidu.com/aistudio/projectdetail/4942734

**Comment by vesper1012** [comment]
您好:
请问百度的分词工具LAC中有一个model是rank, 用于词重要程度排序, 请问方便提供这个工具的开源代码吗, GitHub上仅有API的调用方式, 没有详细介绍每个词的重要性是如何算的.






Vesper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: erine-gram作为千言数据集：问题匹配鲁棒性baseline运行时无法下载paddlenlp (Issue #3613)





 
@vesper1012  Hi, 升级Paddle版本就能解决这个问题。我重新发布了一个升级成2.4版本的项目，请参考。
 
https://aistudio.baidu.com/aistudio/projectdetail/4942734

**Comment by w5688414** [comment]
Hi, @vesper1012 ， LAC的问题建议重新提一个issue，会有专门的人解答
