### ISSUE TITLE
[Question]: 如果有不同类型的文本特征，该如何输入到ERNIE3.0中分别获得Embedding？

### ISSUE THREAD

**Issue by coder-duibai** [PaddlePaddle/PaddleNLP#3616]
### 请提出你的问题

你好，我是一个新闻分类的任务，新闻文本包含标题、正文、摘要等不同类型的特征，请问如何通过ERNIE3.0分别获得标题、正文和摘要的Embedding呢？

**Comment by lugimzzz** [comment]
基于目前transformer结构，可以选择三个不同的模型，分别将标题、正文、摘要输入到模型中；或者选择将标题、正文、摘要分别输入到同一个模型中获得

**Comment by coder-duibai** [comment]
你好，根据你的回答：”基于目前transformer结构，可以选择三个不同的模型，分别将标题、正文、摘要输入到模型中"，请问如何选择三个不同的模型呢？

**Comment by lugimzzz** [comment]
可以选择同一个模型，比如ernie 3.0系列，然后使用不同的数据微调
