### ISSUE TITLE
关于在paddlepaddle-gpu docker容器中安装新包的问题

### ISSUE THREAD

**Issue by xdnjust** [PaddlePaddle/PaddleNLP#3617]
### 请提出你的问题

楼主你好，我使用了官网推荐的“Linux下的Docker安装paddlepaddle-gpu”版本，然后跑代码时候发现需要一些其它的包，比如cv2等等，我直接执行pip install cv2，好像安装不了，请问应该如何操作？

![image](https://user-images.githubusercontent.com/38311101/198957387-e0c0b940-8b72-4bd3-98fa-002dccdb3758.png)

**Comment by wawltor** [comment]
这个看起来是网络有问题？ 你看看docker启动容器的时候 你试试桥接模式
