### ISSUE TITLE
stable-diffusion-v1-4

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleNLP#3618]
### 请提出你的问题

您好，请问这个模型如何下载呢？谢谢

**Comment by JunnYu** [comment]
建议使用库下载，
`pip install ppdiffusers`
```python
from ppdiffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe.save_pretrained("stable-diffusion-v1-5")
```
```python
from ppdiffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4")
pipe.save_pretrained("stable-diffusion-v1-4")
```

**Comment by zcswdt** [comment]
> pip install ppdiffusers

我下载了，下载了报错，可以给脚本发给我邮箱吗？谢谢！jhsignal@126.com

**Comment by zcswdt** [comment]
> ```python
> pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
> ```

![image](https://user-images.githubusercontent.com/43515926/199007258-211a1cbd-99c2-44d6-aa63-4897a02da394.png)

**Comment by JunnYu** [comment]
同https://github.com/PaddlePaddle/PaddleNLP/issues/3588
