### ISSUE TITLE
[Question]: http访问ernie_matching服务

### ISSUE THREAD

**Issue by JaylonXiwei** [PaddlePaddle/PaddleNLP#3619]
### 请提出你的问题

我根据这个文档搭建了排序模型，[ernie_matching](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/ernie_matching)

rpc可以访问服务，但是http访问报错”not found“，请问是否有案例，如果使用http来调用改排序模型？
config文件中只写明了端口号，但是没有其他的具体说明了

**Comment by w5688414** [comment]
请把完整的报错信息发一下，可以参考faq-finance的文档，里面有http访问的示例。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/faq_finance

**Comment by JaylonXiwei** [comment]
解决了，谢谢
