### ISSUE TITLE
[Question]: UIE与ERNIE 3.0 轻量级模型有什么关系？

### ISSUE THREAD

**Issue by yuwochangzai** [PaddlePaddle/PaddleNLP#3623]
### 请提出你的问题

UIE是在ERNIE 3.0的基础上开发的吗？

**Comment by wawltor** [comment]
UIE是ERNIE 3.0系列模型进行微调的

**Comment by Alone749-i** [comment]
> UIE是ERNIE 3.0系列模型进行微调的

请问现在最新微调代码也是使用ERNIE3.0吗？
