### ISSUE TITLE
文档智能能否提供搜索功能

### ISSUE THREAD

**Issue by SOVLOOKUP** [PaddlePaddle/PaddleNLP#3625]
### Feature request

现在 [文档智能](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/document_intelligence) 可以提供对单个文件的信息问答。

但我有一堆资料，形式包括文档、文字、图片、音频、视频等等，如何达到以下效果：
 
```
问：张三的前科劣迹？ 
答：
张三2022年8月犯有盗窃罪  ——xxx判决书.pdf
张三2022年7月寻衅滋事     ——xxx扫描件.jpg
```

即提出一个问题，先对不确定的多个文档进行信息检索，定位到问题对应文档之后再使用 document_intelligence 进行文档理解回答。

### Motivation

文档智能的场景往往都是需要从一大堆资料中找出需要的内容，如何定位到问题对应的文档其实才是最难最耗时间的，如果能从成千上万的文档中快速地找到我想要的答案在哪个文档里面，就能解决这个痛点了

### Your contribution

先用 document_intelligence 将文档转换为向量化的中间产物，然后用 [jina](https://github.com/jina-ai/jina) 或是其他向量搜索引擎进行搜索，定位到问题关联的目标文档后再运行文档问答，是否可行？

**Comment by linjieccc** [comment]
你好，可以参考下这里汽车说明书视觉问答的解决方案：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/document_intelligence/doc_vqa
在VQA之前有个排序模块对文档以及问题根据相关性进行排序

**Comment by wawltor** [comment]
也可以看看这个目录 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering
