### ISSUE TITLE
[Question]: bert fintune时数据下载失败

### ISSUE THREAD

**Issue by rGitcy** [PaddlePaddle/PaddleNLP#3628]
### 请提出你的问题

您好，
我运行bert的fintune代码时，屏幕显示下载数据这个过程很慢，而且总是失败！请问找个有什么其他办法吗？
![image](https://user-images.githubusercontent.com/8943172/199129564-8defed98-416f-4d79-aaab-6a4c10f728d6.png)
RuntimeError: Download from https://bj.bcebos.com/dataset/glue/SST.zip failed. Retry limit reached
x谢谢！

**Comment by LemonNoel** [comment]
可以使用 wget https://bj.bcebos.com/dataset/glue/SST.zip 直接下载吗？

**Comment by rGitcy** [comment]
> 可以使用 wget https://bj.bcebos.com/dataset/glue/SST.zip 直接下载吗？

应该是可以的，请问下载后放到哪个目录？另一方面，经过测试，这个bug和网速有关，可能是官网限速！
