### ISSUE TITLE
[Question]: finetune relation model？遇到问题。

### ISSUE THREAD

**Issue by jxrjlxc02** [PaddlePaddle/PaddleNLP#3630]
### 请提出你的问题

目前已有的 finetune.py 模型 为 "class UIE(ErniePretrainedModel)", 该模型NER模型，目标是获取 start_prob, end_prob 概率，
请问目前是否有 关系模型的UIE finetune参考？ 还是需要自己定制化一个呢？

**Comment by wawltor** [comment]
可以支持关系抽取的微调

1. 按照关系抽取的方式来标注数据 
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/16698950/199155563-fe86844b-edbc-4190-8948-8bc325a5a8ff.png">

2. 生成训练数据 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/16698950/199155657-9365213c-5003-47e5-88cb-d5e24c8134f1.png">


3. 直接微调即可 

<img width="637" alt="image" src="https://user-images.githubusercontent.com/16698950/199155690-814141cb-f528-4b9d-ad39-ebd3c8771dec.png">
