### ISSUE TITLE
[Question]: UIE CPU部署后的model.onnx该如何使用？

### ISSUE THREAD

**Issue by yuwochangzai** [PaddlePaddle/PaddleNLP#3631]
### 请提出你的问题

使用命令python deploy/python/infer_cpu.py --model_path_prefix export/inference生成的model.onnx该如何使用？有demo吗？

**Comment by LemonNoel** [comment]
infer_cpu.py 就是使用 model.onnx 进行推理的。model.onnx 是在[这步](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py#L34-L38)由静态图模型转换得到的，使用它进行推理的代码可以看 [uie_predictor.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py) 文件。

**Comment by yuwochangzai** [comment]
可是我看这个文件只是写入了model.onnx文件，并没有用上它

**Comment by yuwochangzai** [comment]
> infer_cpu.py 就是使用 model.onnx 进行推理的。model.onnx 是在[这步](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py#L34-L38)由静态图模型转换得到的，使用它进行推理的代码可以看 [uie_predictor.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py) 文件。

可是我看这个代码只是写入了model.onnx文件，并没有用上它

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/bdd659d2660312c75bb62ca47382907378ecfaa5/model_zoo/uie/deploy/python/uie_predictor.py#L63

可以看这里，这里加载了onnx model

**Comment by yuwochangzai** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/bdd659d2660312c75bb62ca47382907378ecfaa5/model_zoo/uie/deploy/python/uie_predictor.py#L63
> 
> 可以看这里，这里加载了onnx model

这个onnx_model是用静态图转换得到的，我的意思是如何将生成了的model.onnx用起来？

**Comment by wawltor** [comment]
> > https://github.com/PaddlePaddle/PaddleNLP/blob/bdd659d2660312c75bb62ca47382907378ecfaa5/model_zoo/uie/deploy/python/uie_predictor.py#L63
> > 
> > 可以看这里，这里加载了onnx model
> 
> 这个onnx_model是用静态图转换得到的，我的意思是如何将生成了的model.onnx用起来？

<img width="615" alt="image" src="https://user-images.githubusercontent.com/16698950/199171864-047c8495-c806-4420-928e-9377ddb51352.png">
onnx_model 是使用paddle2onnx将静态图参数转成onnx格式，`ort.InferenceSession` 这个表示onnxruntime的backend来调用onnx模型

**Comment by yuwochangzai** [comment]
使用路径加载模型即可：
self.predictor = ort.InferenceSession(float_onnx_file,
                                              sess_options=sess_options,
                                              providers=providers)
