### ISSUE TITLE
[Question]: 请问什么时候能支持英文事件抽取捏？

### ISSUE THREAD

**Issue by xyliu-uir** [PaddlePaddle/PaddleNLP#3632]
### 请提出你的问题

请问什么时候能支持英文事件抽取捏？

**Comment by wawltor** [comment]
目前还不支持英文事件抽取，通常情况下我们是建议使用关系抽取来代替事件抽取，事件抽取在很多任务都有局限性，例如一个事件在一个句子没有办法对应两个出发词
