### ISSUE TITLE
[Question]: 关于模型加载Taskflow

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleNLP#3633]
### 请提出你的问题

您好，我把这个disco_diffusion_ernie_vil-2.0-base-zh模型下载到本地了，例如我存放在“F:\disco_diffusion_ernie_vil-2.0-base-zh”请问在使用Task加载模型的时候如何更改模型路径呢？谢谢。

![image](https://user-images.githubusercontent.com/43515926/199153957-222d7dff-e404-4eb5-8731-5b78599224e3.png)

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md

可以看上面的文档
具体可以设置home_path 
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/16698950/199156089-8e07c9dd-2ce9-4d08-85a0-cb9392587014.png">

**Comment by zcswdt** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md
> 
> 可以看上面的文档 具体可以设置home_path <img alt="image" width="1035" src="https://user-images.githubusercontent.com/16698950/199156089-8e07c9dd-2ce9-4d08-85a0-cb9392587014.png">

您好，我下载玩模型，讲模型路径按照上面文档改了，可是在运行代码还是报错，请问这个怎么解决呢？谢谢！

![image](https://user-images.githubusercontent.com/43515926/199165793-8ea07b74-ff09-4f61-9003-c8b2b19e8d71.png)

这是我的代码：
![image](https://user-images.githubusercontent.com/43515926/199165917-994540b7-f21c-45a1-ace0-36b400da58cc.png)

这是我下载的模型，路径为‘/root/PaddleNLP/text_image/disco_diffusion_ernie_vil-2.0-base-zh’

![image](https://user-images.githubusercontent.com/43515926/199165991-ca4d411d-489b-432c-8f87-8f7fb7a7b79b.png)

**Comment by wawltor** [comment]
你的任务名和模型路径不匹配？ 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/16698950/199172906-3654eb2f-746b-435b-ab22-44165ad13910.png">

**Comment by zcswdt** [comment]
> 你的任务名和模型路径不匹配？ <img alt="image" width="849" src="https://user-images.githubusercontent.com/16698950/199172906-3654eb2f-746b-435b-ab22-44165ad13910.png">

我现在将代码改了如下：
![image](https://user-images.githubusercontent.com/43515926/199173915-6b45fa42-0e10-4049-9bc1-b564a912ce9c.png)

运行这个代码还是会产生如下报错，一直叫我去下载东西，可是我模型已经保存在‘/root/PaddleNLP/text_image/disco_diffusion_ernie_vil-2.0-base-zh’这个文件夹下了，烦请帮忙看看，谢谢！

![image](https://user-images.githubusercontent.com/43515926/199173780-e6323edd-62c1-4471-ade3-5071b8fe8c40.png)

**Comment by LemonNoel** [comment]
默认模型是`pai-painter-painting-base-zh`，如果要加载`disco_diffusion`模型需要定义`model`参数，详情见[示例文档](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#disco-diffusion%E6%A8%A1%E5%9E%8B)，然后再结合`home_path`使用。
