### ISSUE TITLE
bert base fintune报错：AttributeError: 'paddle.fluid.core_avx.Tensor' object has no attribute 'astype'

### ISSUE THREAD

**Issue by rGitcy** [PaddlePaddle/PaddleNLP#3635]
### 请提出你的问题

使用bert static目录下代码使用官方例子进行fintune。报错：AttributeError: 'paddle.fluid.core_avx.Tensor' object has no attribute 'astype'
![image](https://user-images.githubusercontent.com/8943172/199164013-9a14316f-c59b-4d1b-baa0-7e2a57b2038c.png)

我的运行环境：
python==3.8
paadlepaddle-gpu==2.3.2
paddlenlp==2.4.2

**Comment by rGitcy** [comment]
i delete the astype in the line 428 of model_utils.py .Now it run successs.
![image](https://user-images.githubusercontent.com/8943172/199173265-dfbd6067-fbb4-446b-a677-b3a8ecda7f5e.png)

**Comment by wj-Mcat** [comment]
glad to see that you have found the trick to fix this issue. 

But, this is actually a bug when doing dynamic-to-static, we will try to fix it later.  Thanks for your posting.

**Comment by rGitcy** [comment]
> glad to see that you have found the trick to fix this issue.
> 
> But, this is actually a bug when doing dynamic-to-static, we will try to fix it later. Thanks for your posting.

ok. thx!

**Comment by rGitcy** [comment]
@wj-Mcat hi， do you have fix the bug？thx

**Comment by wj-Mcat** [comment]
yes, you can `pip install --upgrade pip` or `git clone https://github.com/PaddlePaddle/PaddleNLP` to use the latest feature.
