### ISSUE TITLE
[Question]: 如何提高UIE使用CPU部署的model.onnx模型的推理性能？

### ISSUE THREAD

**Issue by yuwochangzai** [PaddlePaddle/PaddleNLP#3636]
### 使用的uie_nano预训练模型，但是速度还是很慢
31个schema，80多条数据测试耗时190秒
模型是按照[文档](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)使用命令：
python deploy/python/infer_cpu.py --model_path_prefix export/inference
生成的，该如何提高推理性能？

**Comment by LemonNoel** [comment]
可以根据机器CPU配置，适当调大batch_size参数

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/3496  

这里有个LIte的INT8部署的工作，你可以看看自己的cpu是否支持INT8部署

**Comment by yuwochangzai** [comment]
> 

没用

**Comment by yuwochangzai** [comment]
> 可以根据机器CPU配置，适当调大batch_size参数

没用
