### ISSUE TITLE
“汽车说明书跨模态智能问答”的结果有问题

### ISSUE THREAD

**Issue by xdnjust** [PaddlePaddle/PaddleNLP#3638]
### 请提出你的问题

大佬们，我按照readme命令一行行执行训练和推理，最后发现和文档输出的结果有不同，请看看代码是否有bug？

**Comment by xdnjust** [comment]
![image](https://user-images.githubusercontent.com/38311101/199190337-f859c511-c5f2-4133-a240-635d0f7af580.png)

**Comment by LemonNoel** [comment]
是所有测试case都不正确吗？还是个别的case有问题，可以贴一下训练日志

**Comment by xdnjust** [comment]
我测了“钥匙怎么充电”，可以正确识别
所以应该是个别case不正确，如上面的“后备箱怎么开”
我看了下，对于“后备箱怎么开”，Rerank模块可以找到正确的图片，但是Extraction模块做阅读理解时出现问题，没法找到正确的答案，是不是代表Extraction模型训练的不充分？（我是按照readme.md来做的，没改动）

**Comment by LemonNoel** [comment]
有可能是训练不充分或者是相同参数配置下训练的随机性导致的，可以再调整下参数看看效果
