### ISSUE TITLE
[Question]: 能否将DocPrompt用于问答系统中？

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/PaddleNLP#3647]
### 请提出你的问题

输入为纯文本，不需要图像识别步骤的那种？

**Comment by wawltor** [comment]
纯文本的QA可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering  
<img width="504" alt="image" src="https://user-images.githubusercontent.com/16698950/199472744-ed9146dd-d0e1-4d9b-a201-6058f7896cc3.png">

**Comment by datalee** [comment]
> 纯文本的QA可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering <img alt="image" width="504" src="https://user-images.githubusercontent.com/16698950/199472744-ed9146dd-d0e1-4d9b-a201-6058f7896cc3.png">

你这个是基于生成的吧？我想要基于content的文本问答（ machine reading comprehension），类似dureader的形式

**Comment by wawltor** [comment]
不是基于生成的方式，使用的方式使用语义检索的方式来做的

**Comment by wjddd** [comment]
> 纯文本的QA可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering <img alt="image" width="504" src="https://user-images.githubusercontent.com/16698950/199472744-ed9146dd-d0e1-4d9b-a201-6058f7896cc3.png">

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/document_intelligence.py 这个例子可以改成文本输入而非图片输入吗？

**Comment by wawltor** [comment]
这个不可以的

**Comment by wjddd** [comment]
> 这个不可以的

了解，感谢答复。
