### ISSUE TITLE
[Question]: 支持novelai文生图吗?

### ISSUE THREAD

**Issue by omegaholysky** [PaddlePaddle/PaddleNLP#3649]
### 请提出你的问题

请问有novelai的文生图吗

**Comment by JunnYu** [comment]
您可以看一下这个aistudio项目，在这个项目中应该会有您所需要的模型
https://aistudio.baidu.com/aistudio/projectdetail/4905623?channelType=0&channel=0

**Comment by omegaholysky** [comment]
找到的实现都是ppdiffusers,novel模型都是分散的,有没有paddlenlp的taskflow能读取的整合模型?或者说有什么办法能把分散的模型合并为一个?
