### ISSUE TITLE
[Question]: ernie-health-chinese词典相关问题

### ISSUE THREAD

**Issue by johnsongwx** [PaddlePaddle/PaddleNLP#3654]
老师们好，关注到ernie-health-chinese这个非常优秀的工作。最近我们想基于咱们的模型，进一步做一些探索和尝试。
有如下疑问想请教老师们：
1. ernie-health-chinese的词典（类似于BERT的vocab）是否开源了呢？目前在项目中还没有找到这个文件；
2. 如果我们在您们的词典上进一步扩充（我们人工构造了一个补充进来的sub-word的词典），能否做continual pretrain？还想请教各位老师们，continual pretrain对于语料库的大小和来源是否也需要pretrain from scratch的160GB的体量呢？
新人提问，希望各位老师们百忙之中不吝赐教，谢谢！

**Comment by LemonNoel** [comment]
1. ernie-healht-chinese的词典开源了，可以从[这个地址](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/electra/tokenizer.py#L95)下载
2. 扩充词典可以调用 [resize_token_embeddings](https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.0/paddlenlp/transformers/model_utils.py#L521) 扩展模型字向量矩阵，调用[add_tokens](https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.0/paddlenlp/transformers/tokenizer_utils_base.py#L907)增加新的token。热启的话，对数据量要求应该相对小些。不过目前开源参数只有discriminator的部分，训练时也要考虑generator冷启的问题。

**Comment by johnsongwx** [comment]
感谢LemonNoel老师的耐心解答！
还想进一步请教下，目前tokenizer对于中文是进行单字切分，如果我们想进一步用subword（对中文来说就是多个字符的词语）来改进现在的tokenzier，是否可以进行混合切分呢？例如词表内单词按照整个subword切分，OOV单词按照单字切分这样。
以及，咱们的generator是否有计划开源呢？很多工作在BERT基础上在特定语料库continual pretrain，我们是想参考这样的思路，在咱们的eHealth模型上进一步预训练，冷启感觉可能是不是还是比较困难。倘若可以开源的话，可能也会进一步吸引更多的研究人员使用咱们的模型，能否麻烦各位老师们考虑下～
新人提问，可能有描述不当之处，还望老师海涵！
谢谢老师！

**Comment by LemonNoel** [comment]
- 分词：使用`add_tokens`添加`sub_word`即可实现混合切分，对于在词表中的`subword`，tokenizer 默认会按整体切分。
- generator：因为ERNIE-Health在下游只会用到Discriminator，Generator的作用只是用来辅助Discriminator的训练，所以只保留并开源了这部分参数。我们再找找还有没有当时Generator的参数。一种可能的替代方案是固定discriminator的参数先训练generator，收敛到一定程度之后再同时训练这两个模块。

**Comment by LemonNoel** [comment]
找到了Generator参数，晚些时间整理好放上来哈。

**Comment by LemonNoel** [comment]
预训练的完整参数（包括生成器和判别器）可以从[这里](https://bj.bcebos.com/paddlenlp/models/transformers/ernie-health-chinese/pretrained-ernie-health-chinese.tar.gz)下载。

**Comment by johnsongwx** [comment]
太感谢老师们了！！！收到收到，再次感谢！
祝老师们工作顺利，开心常伴！

**Comment by hitwangshuai** [comment]
您好，想问下ERNIE-Health预训练时有用其他通用语料上的预训练模型做热启吗，比如基于electra的模型做热启（中文的chinese-electra-base）
