### ISSUE TITLE
bert staric 运行预测脚本无结果输出

### ISSUE THREAD

**Issue by rGitcy** [PaddlePaddle/PaddleNLP#3658]
### 请提出你的问题

按照官方脚本对fintune后的模型进行测试，运行预测脚本：
![image](https://user-images.githubusercontent.com/8943172/199628897-75589623-785e-43c1-81b7-8bbd5a6f712e.png)

无输出结果。屏幕截图如下：
![image](https://user-images.githubusercontent.com/8943172/199628824-2bd81b5b-f809-41a0-b938-ec7295cd73bb.png)

**Comment by guoshengCS** [comment]
你好，看了下当前的这个代码确实是没有输出 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/static/predict_glue.py#L161 ，只算是个示例不是很完善，您可以先按照需要使用这里的返回值 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/static/predict_glue.py#L133
