### ISSUE TITLE
代码中有硬编码的开发者本人开发环境地址，是否有影响？

### ISSUE THREAD

**Issue by pfchai** [PaddlePaddle/PaddleNLP#3659]
### 问题描述

如题。

具体代码见：
https://github.com/PaddlePaddle/PaddleNLP/blob/1fc23a88887aab85b563bb3a9a8e844bc5dca497/applications/text_summarization/pegasus/export_model.py#L107

**Comment by gongel** [comment]
你好，这个不影响最终结果，如果本地没有该文件，会自动编译。也同时提了去除的PR：#3667，感谢反馈～
