### ISSUE TITLE
[Question]: 如何把预训练模型转换成inference_model保存下以供推理使用

### ISSUE THREAD

**Issue by Anditty** [PaddlePaddle/PaddleNLP#3660]
### 请提出你的问题

我正在尝试PaddleNLP/examples/code_generation/codegen/中的例子，但是我发现这个模型是通过paddle.save保存的训练模型，但是我想把该codegen模型转换成一个inference mode部署我的推理服务，我不知道如何将该模型转换成inference mode。

**Comment by gongel** [comment]
你好，推理暂时还没支持，可以先参考这个 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/pegasus/export_model.py， 也欢迎提PR共建。我们近期会安排上，尽情期待。
