### ISSUE TITLE
如何对下载到本地的ERNIE3.0预训练模型进行进一步的训练或者精调？

### ISSUE THREAD

**Issue by xiaocod** [PaddlePaddle/PaddleNLP#3661]
### 问题描述

你好，我将ERNIE3.0预训练模型下载到本地后，如何对其进行进一步的自定义调整呢？

**Comment by guoshengCS** [comment]
精调的话可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-3.0
