### ISSUE TITLE
paddlenlp怎么构建一个对话系统

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleNLP#3666]
### 请提出你的问题

刚开始接触paddlenlp,想快速搭建一个对话系统，可以加入自己的对话脚本进行对话，有没有大神指路

**Comment by guoshengCS** [comment]
因为对话系统相对庞大，可以先参考RASA这样一些对话系统的repo。PaddleNLP中目前还没有完整的对话系统的案例，有些对话系统子任务的[教程](https://aistudio.baidu.com/aistudio/projectdetail/2017202?channelType=0&channel=0) 可以先参考下，也欢迎持续关注，如果有相关内容更新我们也会及时发布出来

**Comment by oyb1125** [comment]
> 因为对话系统相对庞大，可以先参考RASA这样一些对话系统的repo。PaddleNLP中目前还没有完整的对话系统的案例，有些对话系统子任务的[教程](https://aistudio.baidu.com/aistudio/projectdetail/2017202?channelType=0&channel=0) 可以先参考下，也欢迎持续关注，如果有相关内容更新我们也会及时发布出来

好的谢谢

**Comment by sijunhe** [comment]
正如楼上所说，[Rasa](https://github.com/RasaHQ/rasa)是当前比较主流的对话系统开源框架。如果您想在Rasa内使用PaddleNLP的模型，可以尝试了解一下https://github.com/senses-chat/rasa-paddlenlp
