### ISSUE TITLE
Pipelines  内存不足

### ISSUE THREAD

**Issue by wujianqiangwjq** [PaddlePaddle/PaddleNLP#3669]
### 请提出你的问题

智能问答系统, 随着文档增加，当检索所有文档，Pipelines.run 存在内存不足的问题。

**Comment by w5688414** [comment]
Hi, @wujianqiangwjq , 请问您是怎么操作的？您的电脑内存是多少？

**Comment by wujianqiangwjq** [comment]
我电脑内存是8G, 我是按照智能问答系统中的 3.4 构建 Web 可视化问答系统操作的https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering

**Comment by wujianqiangwjq** [comment]
我改了ui/webapp_question_answering.py 中的,top_k_retriever改成1320,然后内存就报内存问题

**Comment by w5688414** [comment]
> 我改了ui/webapp_question_answering.py 中的,top_k_retriever改成1320,然后内存就报内存问题

为啥设置那么多，有什么需求吗？一般topk设置成50就可以

**Comment by wujianqiangwjq** [comment]
我使用updatefile 更新文档（希望能覆盖掉原来的答案），但是更新之后一直搜索不到正确答案，所以改了topk。

**Comment by w5688414** [comment]
Hi, @wujianqiangwjq ,如果nano版本效果不理想，可以选择更大的模型，请参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/API.md
