### ISSUE TITLE
[Question]: 文本生成任务模型推荐

### ISSUE THREAD

**Issue by YYGe01** [PaddlePaddle/PaddleNLP#3674]
### 请提出你的问题

你好：
        我正在类似机器翻译似的文本生成任务，问下有没有比较好的方案推荐，我看model_zoo中有这个方案：[ernie-gen](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-gen)，这个是不是PaddleNLP库里目前最好的方案呢，并且我看ernie-gen还是用的ernie1.0，问下除了ernie1.0，不知道是否可以选择效果更好的预训练模型嘛，比如ernie2.0，3.0，gpt，t5之类的。

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 你好： 我正在类似机器翻译似的文本生成任务，问下有没有比较好的方案推荐，我看model_zoo中有这个方案：[ernie-gen](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-gen)，这个是不是PaddleNLP库里目前最好的方案呢，并且我看ernie-gen还是用的ernie1.0，问下除了ernie1.0，不知道是否可以选择效果更好的预训练模型嘛，比如ernie2.0，3.0，gpt，t5之类的。

我们不太推荐ERNIE-GEN方法，我们比较推荐unimo-text，t5,  具体模型的使用方式可以参考  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation

**Comment by YYGe01** [comment]
@wawltor 谢谢回复，我看了下uinmo-text，发现主要是有答案的问题生成，也就是输入有两个，我目前的使用场景如下:


```python
输入：七层及以上住宅应设置电梯

输出：IF entity[住宅] attr[层数] >= num[7] unit[层]，THEN entity[住宅] SET entity[电梯]
```
是想通过一句话，生成一个指定规则格式的文本，如上IF THEN SET就是指定的格式，不知道这种场景uinmo-text是否合适，或者有没有其他的方案可以推荐呢，谢谢！

**Comment by wawltor** [comment]
> @wawltor 谢谢回复，我看了下uinmo-text，发现主要是有答案的问题生成，也就是输入有两个，我目前的使用场景如下:
> 
> ```python
> 输入：七层及以上住宅应设置电梯
> 
> 输出：IF entity[住宅] attr[层数] >= num[7] unit[层]，THEN entity[住宅] SET entity[电梯]
> ```
> 
> 是想通过一句话，生成一个指定规则格式的文本，如上IF THEN SET就是指定的格式，不知道这种场景uinmo-text是否合适，或者有没有其他的方案可以推荐呢，谢谢！

可以的，样本足够多的话，可以学习到该范式

**Comment by ucas010** [comment]
我的也是两个的，输入是一句话，输出是一句话，和ernie-gen比较像，但ernie-gen没有预测的代码（predict.py太费劲了）
