### ISSUE TITLE
[Question]: 在使用uie进行了finetune之后，按照文档参数再进行模型压缩时报错

### ISSUE THREAD

**Issue by starryzwh** [PaddlePaddle/PaddleNLP#3675]
### 请提出你的问题

在使用uie进行了finetune之后，按照文档参数再进行模型压缩时(仍然使用finetune.py)，报错信息ValueError: Some specified arguments are not used by the PdArgumentParser: ['--do_compress'] 没有使用此参数？

**Comment by yuwochangzai** [comment]
你这个除了更新UIE最新代码之后，还要更新paddlenlp源码的这三个文件
![image](https://user-images.githubusercontent.com/6983001/199932619-6096824d-6190-4d77-9605-3ee59aa512aa.png)

**Comment by starryzwh** [comment]
> 你这个除了更新UIE最新代码之后，还要更新paddlenlp源码的这三个文件 ![image](https://user-images.githubusercontent.com/6983001/199932619-6096824d-6190-4d77-9605-3ee59aa512aa.png)

谢谢，没看到之前的那个更新了，刚经过修改，运行正常
