### ISSUE TITLE
[Question]: gpu 跑chinese_bert 的 xnli, 报错

### ISSUE THREAD

**Issue by taixiurong** [PaddlePaddle/PaddleNLP#3680]
### 请提出你的问题

![1372219de945bee36b576379af2853fd](https://user-images.githubusercontent.com/6076976/199968511-1eee5921-e46a-4b80-9c1b-172d4819ebbc.png)
gpu上，跑直接报错。

**Comment by wj-Mcat** [comment]
你这个是由于paddlenlp的版本太低了，可使用以下命令来更新其版本：

```shell
pip install --upgrade paddlenlp
```
