### ISSUE TITLE
[Question]: 请问那么配置paddlenlp到aistudio中的沙盒？

### ISSUE THREAD

**Issue by joesong168** [PaddlePaddle/PaddleNLP#3682]
### 请提出你的问题

使用aistudion对paddlenlp进行了精调，但在部署时被告知，需要配置沙盒。

**Comment by 1649759610** [comment]
在AiStudio上部署需要配置沙盒环境，可以根据aistudio提示的步骤操作：

1. 选择模型文件
2. 设置模型输入输出
3. 制作输入输出转换器

**Comment by joesong168** [comment]
具体到如何制作uie_base模型的输入输出转换器，有没有可以参考的例子？
