### ISSUE TITLE
自定义词典中出现空格如何处理？

### ISSUE THREAD

**Issue by lx1054331851** [PaddlePaddle/PaddleNLP#3683]
### 请提出你的问题

自定义词典中有英文词汇，比如品牌名称，中间是有空格的，如何在自定义词典中进行设置？

**Comment by 1649759610** [comment]
可以详细解释下你的需求吗，背景是什么，是想对这些品牌词设置什么？

**Comment by wj-Mcat** [comment]
如果问题只是**自定义英文词汇中有空格**的话，其实这是一件非常简单的事情：把这个自定义词典添加到tokenizer当中去就行了。

我将以一段测试代码给出解决方案。

```python
from paddlenlp.transformers import BertTokenizer
sentence = "你ba la ba la好"
tokenizer: BertTokenizer = BertTokenizer.from_pretrained("bert-base-chinese")
tokenizer.add_tokens('ba la ba la')

features = tokenizer(sentence, add_special_tokens=False)
print(features)
assert len(features['input_ids']) == 3

product_id = features["input_ids"][1]
assert tokenizer.convert_ids_to_tokens(product_id) == 'ba la ba la'
```

期待你的回复。

**Comment by wj-Mcat** [comment]
抛一个问题：文本中本身就出现了空格，这个时候该怎么处理呢？例如：`"你好 啊"`。

通过tokenizer之后的空格会被删除掉的，这个时候该怎么获取到呢？

**Comment by lx1054331851** [comment]
@wj-Mcat 谢谢您的回复和解决问题的思路，刚发现您应该和微信里回复我消息的老师是同一个人。非常感谢。
paddlenlp给了普通人能够处理nlp领域的入场券，但是我确实是nlp新人，有很多概念不太了解。就像您上面给到的解决问题的方案，再往下走，我还是不懂，尴尬。更别提您提出的新的问题了。

如果您方便的话，那就再请您辛苦指点一下后续的实现，或者指点一下去哪里看看资料可以得到该方面的知识，从头学起nlp有点赶不上现在的业务需求。

**Comment by wj-Mcat** [comment]
@xl
 请问你后续的实现具体是指什么呢？你可以把你的问题描述清楚，我们也可以明确且快速的定位你的问题，从而帮你解决。

**Comment by lx1054331851** [comment]
@wj-Mcat 你好，非常感谢。
这几天看了下tokenizer、token、token_id等概念，终于理解了你上面的方法。

现在的问题是：
能找到的案例中使用user_dict的场景是使用TaskFlow高级API进行user dict的加载，如下：
from paddlenlp import Taskflow
seg = Taskflow("word_segmentation", user_dict="user_dict path")

按你上面的方法，还能用用户自定义词典吗？如何加载？搜索了一番，没找到案例。
还是说把所有的自定义词汇都加到tokenizer里面？
