### ISSUE TITLE
[Question]: 请问PaddleNLP能在arm平台上运行么？

### ISSUE THREAD

**Issue by joesong168** [PaddlePaddle/PaddleNLP#3684]
### 请提出你的问题

有没有相关的例子？谢谢

**Comment by wawltor** [comment]
只需要编译相应的arm版本的Paddle版本就可以使用PaddleNLP，与其他的芯片的版本使用没有差别

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html 

这里有一定预编译版本的arm版本，您看看是否可以使用，如果没有相应的Paddle版本，可以到Paddle的提个issue，看看线下编译arm版本

<img width="567" alt="image" src="https://user-images.githubusercontent.com/16698950/200171220-a6ca00a2-abb1-4418-9fbc-91eaef661c69.png">
