### ISSUE TITLE
[Question]: 使用word_interpret.ipynb试验出现ValueError: zero-dimensional arrays cannot be concatenated错误

### ISSUE THREAD

**Issue by w0r1dhe110** [PaddlePaddle/PaddleNLP#3686]
### 请提出你的问题

(https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label/analysis/word_interpret.ipynb

Start token level interpretion, it will take some time.
输入如下：
[Tensor(shape=[1, 128], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[1  , 103, 64 , 104, 236, 12043, 20 , 50 , 128, 305, 403, 252, 128, 90 ,
         290, 586, 59 , 12 , 111, 68 , 259, 12043, 403, 252, 59 , 290, 12079, 10235,
         12080, 1663, 500, 12043, 129, 37 , 71 , 7  , 439, 120, 251, 8141, 9497, 287,
         40 , 114, 38 , 5  , 124, 264, 12043, 20 , 305, 252, 560, 99 , 128, 90 ,
         53 , 230, 4  , 20 , 305, 125, 1274, 99 , 128, 90 , 53 , 230, 4  , 20 ,
         305, 2595, 252, 128, 90 , 9  , 577, 53 , 230, 4  , 20 , 305, 457, 252,
         244, 128, 90 , 9  , 577, 53 , 230, 4  , 20 , 305, 176, 213, 244, 128,
         90 , 53 , 230, 4  , 20 , 305, 176, 242, 244, 128, 90 , 53 , 230, 4  ,
         103, 1138, 422, 128, 90 , 12052, 271, 395, 12053, 9  , 577, 319, 162, 53 ,
         230, 2  ]]), Tensor(shape=[1, 128], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])]

错误如下：
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)/tmp/ipykernel_16501/349198651.py in <module>
     17 
     18     # print(tuple(batch))
---> 19     analysis_result += interpreter(tuple(batch)）
     20 
     21 # Add CLS and SEP tags to both original text and standard splited tokens
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/trustai/interpretation/token_level/method/base_interpret.py in __call__(self, *args, **kwargs)
     32 
     33     def __call__(self, *args, **kwargs):
---> 34         return self.interpret(*args, **kwargs)
     35 
     36     @abc.abstractmethod
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/trustai/interpretation/token_level/method/integrated_gradients.py in interpret(self, data, labels, steps)
     83                 instance = (data[i:i + 1], )
     84             label = None if labels is None else labels[i:i + 1]
---> 85             attributions, error_percent, pred_label, pred_proba = self._ig_interpret_instance(instance, label, steps)
     86             igresult = IGResult(attributions=attributions,
     87                                 pred_label=pred_label,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/trustai/interpretation/token_level/method/integrated_gradients.py in _ig_interpret_instance(self, instance, label, steps)
    185                 pred_proba = batch_probas[-1]
    186 
--> 187         total_gradients = np.concatenate(total_gradients, axis=0)
    188         trapezoidal_gradients = (total_gradients[1:] + total_gradients[:-1]) / 2
    189         integral = trapezoidal_gradients.mean(0)
<__array_function__ internals> in concatenate(*args, **kwargs)
ValueError: zero-dimensional arrays cannot be concatenated

**Comment by lugimzzz** [comment]
是否能提供使用的模型和样例，方便复现问题。

**Comment by w0r1dhe110** [comment]
@lugimzzz 

> 是否能提供使用的模型和样例，方便复现问题。

运行如下trustai文档中提供的demo，即可复现同样的错误

```
!pip install trustai==0.1.7
!pip install interpretdl==0.7.0

```

```
from trustai.demo import DEMO
from trustai.interpretation import IntGradInterpreter
from trustai.interpretation import visualize

demo = DEMO('chnsenticorp')
# init demo model
model = demo.get_model()
tokens, model_inputs = demo("这个宾馆比较陈旧了")
# tokens: List[List[str]], [['[CLS]', '这', '个', '宾', '馆', '比', '较', '陈', '旧', '了', '[SEP]']]
# model_inputs: List[Paddle.Tensor]，满足`logits = model(*model_inputs)`
# init interpreter
interpreter = IntGradInterpreter(model)
result = interpreter(model_inputs)
# result: List[IGResult], result[0].attribtions与tokens[0]一一对应，表示每一个token对预测结果的支持程度，即证据的支持度分数。
# result[0].attributions: [ 0.04054353,  0.12724458, -0.00042592,  0.01736268,  0.07130871, -0.00350687,
#                           0.01605285,  0.04392833,  0.04841821, -0.00514487,  0.13098583]

# 可视化结果
html = visualize(result, words=tokens)
# TrustAI提供可视化输出，即根据输入特征的支持度，以不同颜色深度展示结果。颜色越深表示支持度越大，越浅表示支持度越小。
```

**Comment by lugimzzz** [comment]
你好，感谢提供复现代码，我这边在paddlenlp 2.4.2环境下运行可以正常使用，是否方便提供你目前使用paddlenlp版本。
可以参考这个AI Studio复现结果：https://aistudio.baidu.com/aistudio/projectdetail/5053011

**Comment by w0r1dhe110** [comment]
你好，应该是开发版，AI Studio复现结果: https://aistudio.baidu.com/aistudio/projectdetail/5054406
paddlepaddle 2.4.0下会出现这个错误

**Comment by lugimzzz** [comment]
复现了一下发现和PaddleNLP的版本无关，确实在paddlepaddle 2.4.0环境下会出现这个问题，我们现在正在排查修复。请暂时使用paddlepaddle 2.3的版本

**Comment by lugimzzz** [comment]
trustai 0.1.12以上版本已对此问题进行兼容
