### ISSUE TITLE
[Question]: 文本分类，多分类提示学习，评估值过低

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3688]
### 请提出你的问题

1. 多分类的提示学习中，[效果展示](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot#%E6%95%88%E6%9E%9C%E5%B1%95%E7%A4%BA)里使用了240条样本作为训练集，得出评估值为0.5521。
感觉相比其他的场景来说有点过低了，请问可能是什么原因，因为原标签是英文？或标注数据的质量低？
2. 另外，我提高了训练集的样本量至每个分类50，100，150条数据，即共750，1500，2250条数据，训练30轮，得到的评估值如下：
<html>
<body>

数据量/每个分类 | 评估值（Accuracy）
-- | --
50 | 0.5958
100 | 0.6333
150 | 0.2792

</body>
</html>

还是没有达到较高的准确率。

3. 使用提示学习得到的checkpoint没有model_config.json文件，是否不能用analysis中的脚本进行详细评估与数据增强？

**Comment by LemonNoel** [comment]
1. 这个是因为示例数据集标注质量较低，所以评估指标的值比较低。
2. 这里如果还是 TNEWS 数据，按CLUE榜单的[结果](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/benchmark/clue#clue-%E8%AF%84%E6%B5%8B%E7%BB%93%E6%9E%9C)上万条数据的训练结果也在 Acc 也只在 60 左右。其他任务的话，则需要相应地修改 prompt 和标签映射。
3. 提示学习的模型为 PromptModelForSequenceClassification，所以暂时无法使用 analysis 中的脚本进行评估。但是数据增强脚本仍可以使用。
