### ISSUE TITLE
[Question]: 准备自搭paddle环境，目前主要用来做UIE，后续可能会做其他的，有推荐的显卡型号吗？

### ISSUE THREAD

**Issue by yuwochangzai** [PaddlePaddle/PaddleNLP#3703]
用于生产环境的。

**Comment by wawltor** [comment]
这个和预算、使用场景有关系

1）如果预算比较充裕，考虑训练的话可以看看A100，V100相关的机器，如果只是做预测部署，可以考虑一下T4，A10 

2）如果预算不是特别充裕，可以考虑一下 3080，3090系列的卡

**Comment by yuwochangzai** [comment]
> 

好的，多谢！

**Comment by yuwochangzai** [comment]
> 这个和预算、使用场景有关系
> 
> 1）如果预算比较充裕，考虑训练的话可以看看A100，V100相关的机器，如果只是做预测部署，可以考虑一下T4，A10
> 
> 2）如果预算不是特别充裕，可以考虑一下 3080，3090系列的卡

好的，多谢！

**Comment by yuwochangzai** [comment]
> 这个和预算、使用场景有关系
> 
> 1）如果预算比较充裕，考虑训练的话可以看看A100，V100相关的机器，如果只是做预测部署，可以考虑一下T4，A10
> 
> 2）如果预算不是特别充裕，可以考虑一下 3080，3090系列的卡

有没有搭配A10的完整服务器配置推荐？
