### ISSUE TITLE
在使用UIE-nano压缩后的模型int8类型，在进行cpu部署时，发生错误[Question]: 

### ISSUE THREAD

**Issue by starryzwh** [PaddlePaddle/PaddleNLP#3705]
### 请提出你的问题

您好，在使用压缩后的模型int8类型，在进行cpu部署时，发生错误，似乎时paddle2onnx有些算子不支持的原因，请问是否是版本原因导致的？
环境：paddlepaddle-gpu==2.4.0rc0 
onnx==1.12.0
onnxruntime==1.13.1
以下是错误信息：
`python .\app.py --model_path_prefix ../checkpoint/model_best/int8
[2022-11-08 17:07:09,400] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-11-08 17:07:09,400] [    INFO] - Already cached C:\Users\46383\.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt
[2022-11-08 17:07:09,427] [    INFO] - tokenizer config file saved in C:\Users\46383\.paddlenlp\models\ernie-3.0-base-zh\tokenizer_config.json
[2022-11-08 17:07:09,429] [    INFO] - Special tokens file saved in C:\Users\46383\.paddlenlp\models\ernie-3.0-base-zh\special_tokens_map.json
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ../checkpoint/model_best/int8.pdmodel
[Paddle2ONNX] Paramters file path: ../checkpoint/model_best/int8.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model. 
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max,
[ERROR] Due to the unsupported operators, the conversion is aborted.`

**Comment by wawltor** [comment]
能把报错信息提供更多一点吗？

**Comment by LiuChiachi** [comment]
您的paddle2onnx的版本是？建议更新到1.0.2
```
pip install paddle2onnx==1.0.2
```

**Comment by starryzwh** [comment]
> 您的paddle2onnx的版本是？建议更新到1.0.2
> 
> ```
> pip install paddle2onnx==1.0.2
> ```
您好，按照您的建议，之前版本时1.0.1，更新到1.0.2，还是报上面的错误，相关算子并没有支持

**Comment by LiuChiachi** [comment]
`fake_channel_wise_quantize_dequantize_abs_max`,`fake_quantize_dequantize_moving_average_abs_max`这些算子应该是旧版本的量化op，新版本量化op依赖paddlenlp的develop版本，压缩时onnx_format=True

再检查下`xxx/paddlenlp/trainer/trainer_compress.py`下onnx_format是否为True

https://github.com/PaddlePaddle/PaddleNLP/blob/e97f6704409567196c7542304c8cb36a51495be0/paddlenlp/trainer/trainer_compress.py#L660-L661

**Comment by starryzwh** [comment]
> `fake_channel_wise_quantize_dequantize_abs_max`,`fake_quantize_dequantize_moving_average_abs_max`这些算子应该是旧版本的量化op，新版本量化op依赖paddlenlp的develop版本，压缩时onnx_format=True
> 
> 再检查下`xxx/paddlenlp/trainer/trainer_compress.py`下onnx_format是否为True
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/e97f6704409567196c7542304c8cb36a51495be0/paddlenlp/trainer/trainer_compress.py#L660-L661

是使用的paddlenlp的develop版本，检查相关代码，onnx_format值是True
```659         args.moving_rate,
660         'onnx_format':
661         True

**Comment by LiuChiachi** [comment]
麻烦帮忙确认下Paddle环境里的这个文件`Paddle/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py`里`ImperativeQuantAware`类的`save_quantized_model`函数是否有`onnx_format`参数，


https://github.com/PaddlePaddle/Paddle/blob/ccb47076b73dbc12d3408ff786dc31b1769e3084/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L301-L304


https://github.com/PaddlePaddle/Paddle/blob/ccb47076b73dbc12d3408ff786dc31b1769e3084/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L301-L304


如果还有的话，再在paddlenlp的trainer_compress.py的`_quant_aware_training_dynamic`函数里的这个位置：
https://github.com/PaddlePaddle/PaddleNLP/blob/e97f6704409567196c7542304c8cb36a51495be0/paddlenlp/trainer/trainer_compress.py#L752-L755

补充上调用onnx_format=True，如下：
```python
 quanter.save_quantized_model(self.model, 
                              os.path.join(input_dir, 
                              args.output_filename_prefix), 
                              input_spec=input_spec,
                              onnx_format=True) 
```


您出现的这个问题是因为PaddlePaddle的最新包还没有发布出来，一些压缩和部署依赖的环境是旧版本中没有的功能，但是PaddleNLP先合入了UIE的压缩代码，等11.11之后版本稳定后只需要安装最新paddlepaddle、paddlenlp包就可以避免这些问题了。

**Comment by starryzwh** [comment]
> 麻烦帮忙确认下Paddle环境里的这个文件`Paddle/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py`里`ImperativeQuantAware`类的`save_quantized_model`函数是否有`onnx_format`参数，
> 
> https://github.com/PaddlePaddle/Paddle/blob/ccb47076b73dbc12d3408ff786dc31b1769e3084/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L301-L304
> 
> https://github.com/PaddlePaddle/Paddle/blob/ccb47076b73dbc12d3408ff786dc31b1769e3084/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py#L301-L304
> 
> 如果还有的话，再在paddlenlp的trainer_compress.py的`_quant_aware_training_dynamic`函数里的这个位置：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/e97f6704409567196c7542304c8cb36a51495be0/paddlenlp/trainer/trainer_compress.py#L752-L755
> 
> 补充上调用onnx_format=True，如下：
> 
> ```python
>  quanter.save_quantized_model(self.model, 
>                               os.path.join(input_dir, 
>                               args.output_filename_prefix), 
>                               input_spec=input_spec,
>                               onnx_format=True) 
> ```
> 
> 您出现的这个问题是因为PaddlePaddle的最新包还没有发布出来，一些压缩和部署依赖的环境是旧版本中没有的功能，但是PaddleNLP先合入了UIE的压缩代码，等11.11之后版本稳定后只需要安装最新paddlepaddle、paddlenlp包就可以避免这些问题了。

您好，首先谢谢解答，根据您以上提出，Paddle环境里的这个文件Paddle/python/paddle/fluid/contrib/slim/quantization/imperative/qat.py里ImperativeQuantAware类的save_quantized_model函数中没有onnx_format参数，但在ImperativeQuantizeOutputs类中，是有onnx_format参数：`def save_quantized_model(self,
                             model,
                             path,
                             input_spec=None,
                             onnx_format=False,
                             **config):`，前者的save_quantized_model函数调用的是后者的此函数。

如果最新paddlepaddle包可以在11.11后做最新发布，可以解决这些压缩和部署依赖问题，那我到时候再进行尝试，更新后能否通知一下我，我会随时关注这些信息，非常感谢！

**Comment by LiuChiachi** [comment]
有新版本发布我们会联系您~感谢您关注~

您也可以按照上面的建议
为paddlenlp的trainer_compress.py的_quant_aware_training_dynamic函数加上onnx_format=True，
<img width="436" alt="image" src="https://user-images.githubusercontent.com/26483581/201017798-80f5fa7c-5c44-4b79-b133-25859deb04ba.png">
重新压缩导，再执行推理即可
参考https://github.com/PaddlePaddle/PaddleNLP/issues/3706#issuecomment-1309646563
有朋友遇到相同的问题，已经成功了

**Comment by starryzwh** [comment]
> 有新版本发布我们会联系您~感谢您关注~
> 
> 您也可以按照上面的建议 为paddlenlp的trainer_compress.py的_quant_aware_training_dynamic函数加上onnx_format=True， <img alt="image" width="436" src="https://user-images.githubusercontent.com/26483581/201017798-80f5fa7c-5c44-4b79-b133-25859deb04ba.png"> 重新压缩导，再执行推理即可 参考[#3706 (comment)](https://github.com/PaddlePaddle/PaddleNLP/issues/3706#issuecomment-1309646563) 有朋友遇到相同的问题，已经成功了

非常感谢，按照上面的建议，重新压缩导出，并做推理，成功了！
此刻，还想问一个问题，模型压缩这一步目前是使用paddlepaddle-gpu2.4.0rc0才能进行压缩，后续可以用新发布的稳定版本代替是吧？还有上面推理补充代码paddlenlp的trainer_compress.py的_quant_aware_training_dynamic函数加上onnx_format=True也会在新版本中呈现是吗？

**Comment by LiuChiachi** [comment]
现在的这 改动是为了让paddlenlp适配现有的2.4.0rc版本的PaddlePaddle，等2.4.0正式版（新版本）发布之后，就不需要再做这个改动了。
等paddlepaddle新版本发布，您可以继续使用现在改过之后的环境，也可以升级paddlepaddle和paddlenlp至最新版本；

**Comment by starryzwh** [comment]
> 现在的这 改动是为了让paddlenlp适配现有的2.4.0rc版本的PaddlePaddle，等2.4.0正式版（新版本）发布之后，就不需要再做这个改动了。 等paddlepaddle新版本发布，您可以继续使用现在改过之后的环境，也可以升级paddlepaddle和paddlenlp至最新版本；

好的，了解了，非常感谢！
