### ISSUE TITLE
官方代码https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE 运行报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#3707]
### 问题描述

运行：
python process_data.py preprocess

报错：
`/home/aistudio/work/DuUIE
Building 灾害意外 dataset ...
Traceback (most recent call last):
  File "process_data.py", line 678, in <module>
    options.func(options)
  File "process_data.py", line 614, in preprocess
    data_folder=options.output_folder, schema_folder=options.schema_folder)
  File "process_data.py", line 496, in preprocess_event
    schema = load_definition_schema_file(schema_file)
  File "process_data.py", line 16, in load_definition_schema_file
    return yaml.load(open(filename, encoding='utf8'), Loader=yaml.FullLoader)
FileNotFoundError: [Errno 2] No such file or directory: 'data/seen_schema/灾害意外.yaml'
`

**Comment by linjieccc** [comment]
你好，

报名比赛后 https://aistudio.baidu.com/aistudio/competition/detail/436/0/introduction

可以在这里下载对应的数据集

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/40840292/200555842-02779b6c-22d6-4ffa-8182-1840255f0f20.png">
