### ISSUE TITLE
[Question]: ErnieTokenizer在做NER任务时会将换行符等去除

### ISSUE THREAD

**Issue by Macxy2018** [PaddlePaddle/PaddleNLP#3715]
### 请提出你的问题

1.环境：系统ubuntu18.04；python3.7；paddlepaddle-gpu 2.3稳定版；paddlenlp 2.4.1
2.模型：ernie-crf模型
3.需求：当前任务为NER任务，数据标注为单个字符标注的BIO类型，语句中包含换行符及特殊字符等
4.现象：使用tokenizer后会丢失换行符，导致crf输出无法与标签匹配，从而停止训练
5.问题：请问有什么办法能够保留换行符等特殊字符？目前使用add_tokens未能解决问题，还有特殊字符，是否需要将所有特殊字符添加进tokens？

**Comment by wj-Mcat** [comment]
关于NER任务当中的空格处理，你可以参考：[空格处理解决方案](https://github.com/PaddlePaddle/PaddleNLP/wiki/Best-Practice#%E7%A9%BA%E6%A0%BC%E5%A4%84%E7%90%86)

同时也已经有一个相似的PR  https://github.com/PaddlePaddle/PaddleNLP/issues/3683

相信上面的两个解决方案已经可以帮你解决问题。如果有任何问题，都可以在这里继续说明。
