### ISSUE TITLE
[Question]: LAC工具里面的rank能否提供具体的实现代码

### ISSUE THREAD

**Issue by vesper1012** [PaddlePaddle/PaddleNLP#3716]
### 请提出你的问题

即词重要性是如何计算的而不只是调用方法, 在baidu/lac那边提问没有回答 希望得到回复

**Comment by wawltor** [comment]
词重要性权重，是基于LAC的切词模型输出的 词序列 + 词性 => 打分模型完成计算，打分模型通过词语本身语义、词性 两种种特征进行排序打分。
可以理解在LAC模型之后有一个词语重要性模型来对词语的重要性进行打分，最终有4个等级
<img width="635" alt="482b6b9be0c9f405ac4d5dd355c50486" src="https://user-images.githubusercontent.com/16698950/201250902-a17863dc-fcdd-4ed0-9f82-d084046ebcc4.png">

**Comment by vesper1012** [comment]
您好:
感谢回复.
想请教一下, ernie-gram模型对文本中词语的词性、词重要程度有没有感知呢? &nbsp;如果我在Ernie- gram模型中再额外加入lac工具做的词性和词重要程度, 是不是在画蛇添足? 该如何知道模型是否已经学会这些信息了呢?




Vesper
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月11日(星期五) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: LAC工具里面的rank能否提供具体的实现代码 (Issue #3716)





 
词重要性权重，是基于LAC的切词模型输出的 词序列 + 词性 =&gt; 打分模型完成计算，打分模型通过词语本身语义、词性 两种种特征进行排序打分。
 可以理解在LAC模型之后有一个词语重要性模型来对词语的重要性进行打分，最终有4个等级

**Comment by wawltor** [comment]
> 您好: 感谢回复. 想请教一下, ernie-gram模型对文本中词语的词性、词重要程度有没有感知呢? &nbsp;如果我在Ernie- gram模型中再额外加入lac工具做的词性和词重要程度, 是不是在画蛇添足? 该如何知道模型是否已经学会这些信息了呢? Vesper ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleNLP" ***@***.***&gt;; 发送时间:&nbsp;2022年11月11日(星期五) 上午10:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: LAC工具里面的rank能否提供具体的实现代码 (Issue #3716) 词重要性权重，是基于LAC的切词模型输出的 词序列 + 词性 =&gt; 打分模型完成计算，打分模型通过词语本身语义、词性 两种种特征进行排序打分。 可以理解在LAC模型之后有一个词语重要性模型来对词语的重要性进行打分，最终有4个等级 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

从预训练模型的角度而言，本身在模型有self-attention 注意力机制，模型是可以学习到相关字、词相关的重要性的

**Comment by wawltor** [comment]
您好，我们将关闭ISSUE，如有问题可以再次打开ISSUE。
