### ISSUE TITLE
[Question]: PaddleNLP Pipelines的数据插入时，除了content和meta中的name字段可以被插入，其他字段内容是怎么被插入的呢

### ISSUE THREAD

**Issue by liruixue** [PaddlePaddle/PaddleNLP#3722]
### 请提出你的问题

在使用用PaddleNLP Pipelines产品时，官文介绍道据更新的方法有两种，第一种使用前面的 utils/offline_ann.py进行数据更新，第二种是使用前端界面的文件上传（在界面的左侧）进行数据更新。对于txt（需要按照空行划分段落），有些场景我不仅需要文本能把检索到，我还需要知道文本的引用出处或者作者或者生产时间等信息，是如何保存的呢？
期待老师的指导，感谢！

**Comment by w5688414** [comment]
Hi, @liruixue  Please refer to meta parameters, you can add the data into meta to statisfy your requests, 
 https://github.com/PaddlePaddle/PaddleNLP/blob/72cc9e12ad24f6e5dfa01de5f46669b7901d0356/pipelines/pipelines/schema.py#L95

**Comment by liruixue** [comment]
> Hi, @liruixue Please refer to meta parameters, you can add the data into meta to statisfy your requests,
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/72cc9e12ad24f6e5dfa01de5f46669b7901d0356/pipelines/pipelines/schema.py#L95

了解，感谢快速回复！
