### ISSUE TITLE
ernie-1.0-large-zh-cw 如何下载

### ISSUE THREAD

**Issue by haojiepan1** [PaddlePaddle/PaddleNLP#3726]
您好，请问ernie-1.0-large-zh-cw 从哪里下载，尝试了各种方式，下载不下来，是已经不开源了吗？

**Comment by Gavingx** [comment]
> 您好，请问ernie-1.0-large-zh-cw 从哪里下载，尝试了各种方式，下载不下来，是已经不开源了吗？

你好，你下载了吗？有链接吗？
