### ISSUE TITLE
[Question]: docprompt的抽取模型用的什么方法？

### ISSUE THREAD

**Issue by DamonYangyang** [PaddlePaddle/PaddleNLP#3729]
### 请提出你的问题

您好，请问一下docprompt用到的抽取方法是什么，MRC还是LinearCRF，又或是提到的mmlayout

**Comment by hehuang139** [comment]
很明显啊，从propmt中是qa问题，那肯定是阅读理解mrc，label是start,end。具体的话要确认可以通过DocPromptTask对eval结果start,end可以看出来，

**Comment by DamonYangyang** [comment]
> 很明显啊，从propmt中是qa问题，那肯定是阅读理解mrc，label是start,end。具体的话要确认可以通过DocPromptTask对eval结果start,end可以看出来，

**Comment by DamonYangyang** [comment]
> 很明显啊，从propmt中是qa问题，那肯定是阅读理解mrc，label是start,end。具体的话要确认可以通过DocPromptTask对eval结果start,end可以看出来，

不一定，paddlenlp中的docvqa给的就是linear crf，不是抽start和end才是阅读理解，很多场景抽start和end效果并不好。而且抽start和end也有很多种不同的方式，比如当做一个0到512的多分类任务或者指针网络span，也或者是片段排列。我就是想确认下这里用的是什么。

**Comment by LIUYANZHI88** [comment]
> 很明显啊，从propmt中是qa问题，那肯定是阅读理解mrc，label是start,end。具体的话要确认可以通过DocPromptTask对eval结果start,end可以看出来，

看源码了，不是MRC
