### ISSUE TITLE
做关键信息提取时，训练到RE的时候，精度一直为0

### ISSUE THREAD

**Issue by Nomia** [PaddlePaddle/PaddleNLP#3734]
你好，如题，做关键信息提取时，训练到RE的时候，精度一直为0
![image](https://user-images.githubusercontent.com/1707818/201300115-7d70e569-292e-4ffc-9126-dba2c0d5becb.png)

我用`xfund`数据没有任何问题，
但是用我自己的数据就有问题

我对比了`xfund`的数据结构和我的数据的数据结构，都是一样的
另外，`config`配置的`xml`文件也是一样的，除了train和val的数据路径不完全一致

训练语法也是一致的
`python tools/train.py -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xxxxxx_zh.yml`

这会是什么问题呢，如果还需要更多信息我可以提供，谢谢

**Comment by wawltor** [comment]
这个用PaddleOCR来训练的？ 麻烦可以转到PaddleOCR看看哈

**Comment by Nomia** [comment]
好
