### ISSUE TITLE
[Question]: The traning data format for finetuning ernie-layout

### ISSUE THREAD

**Issue by stefanqxb** [PaddlePaddle/PaddleNLP#3738]
### 请提出你的问题

Hi there,
   Im using the ernie-layout model to do some docVQA tasks, and I have tried with zero-shot one, and figure out need some finetuning, however, when I checked abt how to finetune, I have some uncertainty of the data-format, as in the example, u point to the docvqa_zh, but could someone also provide a skelton abt the dataset format, so I could take as a reference ? Thank you for the help

**Comment by stefanqxb** [comment]
Hi,
    Any updates on this one ??

**Comment by linjieccc** [comment]
Hi, 

sorry for the late response, you can view the data format by the following code

```python
import paddlenlp
from datasets import load_dataset

train_ds, dev_ds, test_ds = load_dataset(
        "docvqa_zh", split=["train", "validation", "test"])
print(train_ds[0])
```

**Comment by stefanqxb** [comment]
Hi lin,
     Thanks for the reply, now that I have got the data format, but I run into another issue when trying to fine-tune the model, with the run_mrc.py script,  I got the "Int" object is not iterable which coming from line 480 in the ernie-layout/utils.py when it trys to do the `for qid, question, answers in zip(qas[''question_id], xxxxx)` as the question_id is an int obj, can u help to do identify if there is a issue for the docvqa_zh data or is it in the code? Thanks for the help

**Comment by linjieccc** [comment]
@stefanqxb Hi, please check that qas['question_id'] is a list of `int`

**Comment by stefanqxb** [comment]
Hi @linjieccc ,  but in my case, my qas['question_id'] is something like 23432, and the qas part of one sample looks like this 
```
"qas": [ {"question_id": 23893, "question": "A dummy question", "answers":[{"text": xxxx, "answer_start":200, "answer_stop": 227}]}..... ]
```
 and this data is the docvqa_zh got from the code u shared with me, so wondering what is wrong here ?

**Comment by linjieccc** [comment]
Hi, 

here is an sample, please check whether you load the dataset correctly 

![image](https://user-images.githubusercontent.com/40840292/201644459-48b77ca5-b09f-41cf-adf7-d79854ec2f61.png)

**Comment by stefanqxb** [comment]
Hi @linjieccc ,
     Thanks for showing the sample, I think that is problem here, so could u share an correct url for downloading such data?, as my one downloads from https://bj.bcebos.com/paddlenlp/datasets/docvqa_zh.tar.gz which has the wrong format, thanks for the great help

**Comment by linjieccc** [comment]
Hi,

I would recommend to use the `load_dataset` api to download and convert the data.

If you download the dataset from  https://bj.bcebos.com/paddlenlp/datasets/docvqa_zh.tar.gz, I think you need to convert the data manually. You can refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py#L65 for the data format .

**Comment by stefanqxb** [comment]
hi,
  I see, thanks for the info, however, I have by now fixed the format issue, I took a subset abt 5 samples to try-out, but run into another error, saying 
```
There are no kenerls which are registered in the elementvwise_floordiv operator
[Hits: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter() == all_op_kernels.end()]
```
Do u recognize this error, or what could go wrong ? Thanks

**Comment by linjieccc** [comment]
You can run the following code to verify the installation of paddlepaddle
```python
import paddle
paddle.utils.run_check()
```

**Comment by stefanqxb** [comment]
Thanks @linjieccc , let me check abt it

**Comment by stefanqxb** [comment]
Hi @linjieccc ,
     I thnk the problem is solved by now, thanks so much for the help here! However, I have another question here, regrading the VQA dataset, seems now for each question, we only have one answer, for example: {"text": xxx, "answer_start": [2], "answer_end":[5]},  which the answer is a consective span from the text,  so Im wondering if we support questions with answers which is not consective ?? 

For example, given a OCR result is ["This", "is", "a", "dummy", "test", "with", "right", "answer", "A1", "and", "A1", "has"...,"another", "right", "answer", "A2",.....], so in this case, for the question: ` What are the right answers ?`, the answer should be `A1` and `A2`, however, A1 and A2 are not next to each other, then how should we specify these kinda answer for the training ? Thanks for the help

**Comment by XiaokangLei** [comment]
> ```python
> paddle.utils.run_check()
> ```

May I ask how you solved this problem?

**Comment by XiaokangLei** [comment]
> hi, I see, thanks for the info, however, I have by now fixed the format issue, I took a subset abt 5 samples to try-out, but run into another error, saying
> 
> ```
> There are no kenerls which are registered in the elementvwise_floordiv operator
> [Hits: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter() == all_op_kernels.end()]
> ```
> 
> Do u recognize this error, or what could go wrong ? Thanks

May I ask how you solved this problem?
