### ISSUE TITLE
[Bug]: PretrainedTokenizer的save_vocabulary方法是错误的

### ISSUE THREAD

**Issue by boxiaowave** [PaddlePaddle/PaddleNLP#3742]
### 软件环境

```Markdown
- paddlepaddle:2.3.1
- paddlepaddle-gpu: 2.3.1
- paddlenlp: 2.4.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
PretrainedTokenizer的save_vocabulary方法是错误的，源码中的方法：

if isinstance(vocab, Vocab):
            tokens = vocab.idx_to_token
        else:
            tokens = sorted(vocab.keys(), key=lambda token: vocab[token])
        with io.open(filepath, 'w', encoding='utf-8') as f:
            for token in tokens:
                f.write(token + '\n')

tokens这里取的是idx_to_token这个字典，key是id，在写入文件时会尝试把id写入，但是这个函数的目的是把对应的字写入文件，应该用token_to_idx这个成员变量
```

### 稳定复现步骤 & 代码

t = AutoTokenizer.from_pretrained('ernie-3.0-xbase-zh')
t.save_vocabulary(filepath='vocab.txt',vocab=t.vocab)

**Comment by wj-Mcat** [comment]
相信您最近在阅读`PaddleNLP`的代码，非常感谢您提出此问题，此函数确实存在问题，不过此函数目前属于废弃状态，不会被触发：通过`save_pretrained`和`save_resource`两个函数完成tokenizer 相关资源文件的保存。

所以如果你想保存 tokenizer 中相关资源文件，建议使用`save_pretrained`接口来实现。
