### ISSUE TITLE
想问下paddleNlp中的UIE模型可以用于不同垂直领域吗

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#3744]
### 请提出你的问题

1、想问下paddleNlp中的UIE模型可以用于不同垂直领域吗？
比如国防，金融，教育等，
2、要用于这些领域，每个领域通常需要的语料数量多少条【使用doccano】？
3、对语料有什么建议，UIE模型微调貌似有时精确率不升反降？

**Comment by wawltor** [comment]
1、 UIE模型 可以用于不同领域，建议不同领域各个训练一个模型出来 
2、主要要看任务难度，如果实体较多、关系较多，至少每个实体要有5条数据覆盖，建议少量数据先微调，然后再加数据继续提升效果
3、模型训练过程中有最好的best model，使用最好模型即可，因为验证集较少，指标有波动也很正常

**Comment by zchengzhong** [comment]
> 1、 UIE模型 可以用于不同领域，建议不同领域各个训练一个模型出来 2、主要要看任务难度，如果实体较多、关系较多，至少每个实体要有5条数据覆盖，建议少量数据先微调，然后再加数据继续提升效果 3、模型训练过程中有最好的best model，使用最好模型即可，因为验证集较少，指标有波动也很正常

感谢回复。
另：微调后的模型，能再拿去训练？还是只能用原来的base模型？ 可以用训练出来的模型继续训练的代码是？

**Comment by wawltor** [comment]
> > 1、 UIE模型 可以用于不同领域，建议不同领域各个训练一个模型出来 2、主要要看任务难度，如果实体较多、关系较多，至少每个实体要有5条数据覆盖，建议少量数据先微调，然后再加数据继续提升效果 3、模型训练过程中有最好的best model，使用最好模型即可，因为验证集较少，指标有波动也很正常
> 
> 感谢回复。 另：微调后的模型，能再拿去训练？还是只能用原来的base模型？ 可以用训练出来的模型继续训练的代码是？

如果是同一个任务，可以拿微调后的模型继续微调；如果不是同一个任务，建议重新拿base模型微调
