### ISSUE TITLE
paddleNlp中的UIE模型一些适用条件辛苦补充下，有些情况不可用

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#3745]
### 请提出你的问题

paddleNlp中的UIE模型一些适用条件辛苦补充下，有些情况不可用：
比如默认的模型（base）适配用于哪些领域， 通用一次推理适用多少文本（3000字还是1w字），内存（gpu模式显存多大，cpu下内存要多大），这些适用条件给一下，好让评估能不能上生产。谢谢

**Comment by linjieccc** [comment]
@zchengzhong 
你好，

1）uie-base模型对抽取场景和领域没有特殊限制，一般在领域数据上通过少量标注+微调即可进行适配。
2）Taskflow内置了对长文本的处理，因此对输入文本的长度没有限制
3）在V100下面base模型（batch_size=1）的显存占用是2.1G左右，CPU推理内存占用大概是1.7G左右

**Comment by zchengzhong** [comment]
感谢
