### ISSUE TITLE
[Question]: GPTTokenizer 未正常加载

### ISSUE THREAD

**Issue by zxcd** [PaddlePaddle/PaddleNLP#3749]
### 请提出你的问题

目前使用paddleNLP中的GPTTokenizer加载gpt2的tokenizer，加载后added_tokens.json的内容未成功加载。

> 环境：
paddlenlp版本为2.4.2
gpt2目录结构中包含added_tokens.json  merges.txt  special_tokens_map.json  tokenizer_config.json  vocab.json
其中，
1、added_tokens.json的内容为：{"<|endoftext|>": 50257}
2、special_tokens_map.json内容为：{"bos_token": "<|endoftext|>", "eos_token": "<|endoftext|>", "unk_token": "<|endoftext|>"}
3、tokenizer_config.json内容为：{"unk_token": {"content": "<|endoftext|>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "bos_token": {"content": "<|endoftext|>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "eos_token": {"content": "<|endoftext|>", "single_word": false, "lstrip": false, "rstrip": false, "normalized": true, "__type": "AddedToken"}, "add_prefix_space": false, "model_max_length": 1024, "special_tokens_map_file": null, "name_or_path": "multilingual", "errors": "replace", "tokenizer_class": "GPTTokenizer"}

> 代码：
from paddlenlp.transformers import GPTTokenizer
tokenizer = GPTTokenizer.from_pretrained(path)
print (tokenizer.bos_token, tokenizer.bos_token_id)

> 结果：
"<|endoftext|>"，NONE

**Comment by wj-Mcat** [comment]
此问题的原因在于：
* vocab当中没有`<|endoftext|>`这个special_token，且和其他special_token内容一致（核心原因）
* 可是在tokenizer当中这个依然成为一种special_token，故无法加入到vocab当中，而此类token是默认在vocab文件当中存在的

故判断此vocab文件配置错误。可通过以下方法进行调整：

*  直接在vocab 当中新增`<|endoftext|>`token,则可以解决`bos_token_id`为 None 的问题.可是会增加原始词表大小,不推荐.
* 将 vocab 当中 unused 的 其中一个 token 修改为`<|endoftext|>`,此时可无侵入性的调整完成词表的调整.
