### ISSUE TITLE
Ernie-Layout 在Xfund数据集预处理Text的一维序列化算法

### ISSUE THREAD

**Issue by bannima** [PaddlePaddle/PaddleNLP#3750]
### 请提出你的问题

**Ernie-Layout 在Xfund数据集预处理Text的一维序列化算法**

Ernie-Layout在做QA任务的时候，如何预处理Xfund数据集，得到text字段的一维序列化算法？这个预处理细节对于我们的推理服务很重要

**Comment by linjieccc** [comment]
你好，请问是指如何将xfund数据集转换为ERNIE-Layout QA任务推理需要的数据格式吗？

**Comment by bannima** [comment]
@linjieccc 
您好，更具体点，是在推理服务的时候，如何将二维OCR后的结果转为一维合理的输入Text序列。
举例来说，
如何将【“文务秘书“】【”工作承诺”】两个bounding boxes在转为一维度Text序列时合并为 【“文务秘书工作承诺”】
这样避免做NER任务时产生discontinuous ner问题。
![image](https://user-images.githubusercontent.com/12859455/201608320-52e56d2c-100b-4f23-9ead-3b85816675d0.png)

**Comment by hehuang139** [comment]
> text

建议看下layout的论文，基本的思路就是通过ocr按行（注意这个按行）解析文本text，以及坐标bbox，然后根据文本单字符还是双字符得到每行字符的bbox

**Comment by hehuang139** [comment]
> 务

就我了解是不支持阅读顺序的。从ocr解析的角度，文务秘书 -》 机要文件... -> 变更登记 ，会是这样的顺序
