### ISSUE TITLE
请问一下paddlenlp有dockerfile吗

### ISSUE THREAD

**Issue by dahu1** [PaddlePaddle/PaddleNLP#3751]
### 请提出你的问题

没找到paddlenlp的dockerfile，可以容器使用paddlenlp吗

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines
这里有些镜像可以拉取

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/16698950/201578003-0fd59fed-5094-4487-aed1-3ed6636632fb.png">

**Comment by dahu1** [comment]
如果想要自己编译镜像呢，有dockerfile吗？

**Comment by dahu1** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines 这里有些镜像可以拉取
> 
> <img alt="image" width="1001" src="https://user-images.githubusercontent.com/16698950/201578003-0fd59fed-5094-4487-aed1-3ed6636632fb.png">

如果想要自己编译镜像呢，有 dockerfile 吗？

**Comment by w5688414** [comment]
Hi, @dahu1 , 目前paddlenlp的镜像是拉取的官网的docker镜像编译而来，如果需要编译自己的镜像，请拉取官网的Paddle镜像做少许修改后，使用docker build打包，打包方法请参考链接https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker

另外，我搜了一下资料，您看看能否从镜像中获取dockerfile：
https://stackoverflow.com/questions/19104847/how-to-generate-a-dockerfile-from-an-image

**Comment by dahu1** [comment]
> Hi, @dahu1 , 目前 paddlenlp 的镜像是拉取的官网的 docker 镜像编译而来，如果需要编译自己的镜像，请拉取官网的 Paddle 镜像做少许修改后，使用 docker build 打包，打包方法请参考链接 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker
> 
> 另外，我搜了一下资料，您看看能否从镜像中获取 dockerfile： https://stackoverflow.com/questions/19104847/how-to-generate-a-dockerfile-from-an-image

感谢您的细致讲解，您的两个建议都很有用！

**Comment by dahu1** [comment]
> Hi, @dahu1 , 目前 paddlenlp 的镜像是拉取的官网的 docker 镜像编译而来，如果需要编译自己的镜像，请拉取官网的 Paddle 镜像做少许修改后，使用 docker build 打包，打包方法请参考链接 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker
> 
> 另外，我搜了一下资料，您看看能否从镜像中获取 dockerfile： https://stackoverflow.com/questions/19104847/how-to-generate-a-dockerfile-from-an-image

你好，我看了下这个 pipelines/docker/Dockerfile-GPU，里面还是有from 拉取镜像: 
 FROM paddlepaddle/paddlenlp:pipelines-1.0-gpu-cuda10.2-cudnn7

有那种原始的dockerfile 吗？因为1.拉取这个镜像特别慢， 2.可以根据dockerfile 自行安装相关的包。

**Comment by w5688414** [comment]
目前没有提供，paddle的国内镜像都很慢吗？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker#31-%E5%9F%BA%E7%A1%80%E9%95%9C%E5%83%8F

您需要gpu的docker吗？把这个镜像拉下来要多久？
```
nvidia-docker run --name pipelines --net host --shm-size 4g -it registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8 /bin/bash
```

**Comment by dahu1** [comment]
@w5688414  好的，我用的还是Dockerfile-GPU 里的paddlepaddle/paddlenlp:pipelines-1.0-gpu-cuda10.2-cudnn7 ，拉取大概花了40多分钟。
请问这个 镜像版本号以及里面对应的内容在哪看呢？
比如 paddlepaddle/paddlenlp:pipelines-1.0-gpu-cuda10.2-cudnn7  和 registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8 
该选哪个呢。

**Comment by w5688414** [comment]
pipelines的镜像是通过paddle镜像打tag得来的，只是加入了pipelines的依赖而已，具体内容参考paddle镜像即可，主要还是paddle官方镜像的一些内容，通过paddle镜像得到pipelines镜像的过程参考：

```
docker commit pipelines pipelines:1.0-gpu-cuda11.2-cudnn8
docker tag pipelines:1.0-gpu-cuda11.2-cudnn8  paddlepaddle/paddlenlp:pipelines-1.0-gpu-cuda11.2-cudnn8
```
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/docker#32-%E4%B8%80%E9%94%AE%E5%90%AF%E5%8A%A8%E9%95%9C%E5%83%8F
