### ISSUE TITLE
What is the recommended OCR model in paddle for english handwritting recognition

### ISSUE THREAD

**Issue by stefanqxb** [PaddlePaddle/PaddleNLP#3756]
### 请提出你的问题

Hi there,
     Wondering What is the recommended OCR model in paddle for english handwritting recognition, any suggestions ? :)

**Comment by MissPenguin** [comment]
[PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) provides a variety of text recognition models. You can try the English model first, as shown in the second row of the [model list](https://github.com/PaddlePaddle/PaddleOCR#%EF%B8%8F-pp-ocr-series-model-listupdate-on-september-8th), which shows a good performance for printed English text images. If you want to achieve a good effect in the handwriting scene, you may need to fine tune it with some handwriting data.

**Comment by stefanqxb** [comment]
Hi @MissPenguin,
     Thanks for the info, the en_PP-OCRv3_xx is the one we are having some issue at moment, so wondering if there is any other alternative or we need to finetune with our handwriting data? if fine-tune is a must, then could I get some guideline abt how to achieve in terms of data-format etc, thanks a lot for the help
