### ISSUE TITLE
[Question]: 超过vocab部分index未能成功转为unk_token或none

### ISSUE THREAD

**Issue by zxcd** [PaddlePaddle/PaddleNLP#3757]
### 请提出你的问题

> 问题描述：
在调用paddlenlp/transformers/tokenizer_utils_base.py中 _decode时，vocab大小为5027。目前paddlenlp版本为2.4.2。

> 资源文件：
同https://github.com/PaddlePaddle/PaddleNLP/issues/3749

> 调用：
self.tokenizer.decode(token_ids, **kwargs) #token_ids=50364

> 报错：
KeyError: 50364

> 期待输出：
unk_token_id或NONE

**Comment by wj-Mcat** [comment]
这个问题是预期范围之内的问题,我通过以下测试代码复现出你的问题:

```python
from paddlenlp.transformers import GPTTokenizer

tokenizer: GPTTokenizer = GPTTokenizer.from_pretrained("gpt2-en")
outof_token_id = tokenizer.vocab_size + 1
token = tokenizer.convert_ids_to_tokens(outof_token_id)
print(token)
```

原因是在于: 你手动调整了 input_ids, 可是这个ids 并不在词表当中. 建议不要手动调整input_ids.

建议先encode, 在不修改数据的前提下再来 decode.整体推荐代码如下所示:

```python
from paddlenlp.transformers import GPTTokenizer

tokenizer: GPTTokenizer = GPTTokenizer.from_pretrained("gpt2-en")
ids = tokenizer.encode(["<<<<<<unk_token>>>>>>"])['input_ids'][0]
tokens = tokenizer.decode(ids)
assert tokens == tokenizer.unk_token
```

**Comment by zxcd** [comment]
但我在做翻译任务的时候有类似需求，会新增语种标签，这种无法放入vocab里面，所以预期是加载成功但输出位空的。有没有办法能不报错？

**Comment by wj-Mcat** [comment]
Tokenizer本身是支持自定义添加 token 的，直接使用以下代码即可：

```python
from paddlenlp.transformers import GPTTokenizer

tokenizer: GPTTokenizer = GPTTokenizer.from_pretrained("gpt-cpm-small-cn-distill")
tokenizer.add_tokens("your-token")
```

上面报错还是因为：你添加的是理论上必须存在的`special_token`，可是并不在`vocab.json`当中。只要解决了这个问题，你上面的需求就可以得到解决。

**Comment by zxcd** [comment]
我在资源文件added_tokens.json中添加了special_token，按理说是否应该在from_pretrained的时候进行了tokenizer.add_tokens这一步呢？

**Comment by wj-Mcat** [comment]
确实是进行了，可是会在add_tokens函数中判断是否已存在，如果是将不会添加。

**Comment by zxcd** [comment]
目前尝试在vocab.json中添加对应的special_token，加载后可以读到对应special_token的id，但这个问题还是没有解决
