### ISSUE TITLE
[Question]: GPTTokenizer加载繁体中文时乱码

### ISSUE THREAD

**Issue by zxcd** [PaddlePaddle/PaddleNLP#3758]
### 请提出你的问题

> 环境及加载方式如：
https://github.com/PaddlePaddle/PaddleNLP/issues/3749

> 问题描述：
以上环境在加载GPTTokenizer后对繁体中文支持产生乱码。

> 实验结果：
我認為跑步最重要的就是給我帶來了身體健��

> 期待结果：
我認為跑步最重要的就是給我帶來了身體健康

**Comment by wj-Mcat** [comment]
这个问题的输入输出分别是什么呢? 你能通过一小段代码来描述你的问题吗? 就类似于这个[comment](https://github.com/PaddlePaddle/PaddleNLP/issues/3757#issuecomment-1314666246).

**Comment by zxcd** [comment]
这部分代码为

**Comment by zxcd** [comment]
这部分代码为self.tokenizer.decode(token_ids, **kwargs) 
token_ids :deocde [tensor(1654), tensor(39450), tensor(32585), tensor(31429), tensor(8661), tensor(24928), tensor(1546), tensor(5620), tensor(17798), tensor(1654), tensor(32379), tensor(25364), tensor(19847), tensor(23987), tensor(44201), tensor(6346), tensor(115)]

**Comment by wj-Mcat** [comment]
我看你 decode 函数的参数是`List[Tensor]`类型，必须将其转化成`List[int]`来使用，详细请看decode函数定义:

https://github.com/PaddlePaddle/PaddleNLP/blob/af9461a785f75499059e905214dd0ac73464422e/paddlenlp/transformers/tokenizer_utils.py#L1396-L1401

至于乱码的问题，这个通常与字符串编码有关。

我本地还是没能够复现出你的问题。

**Comment by zxcd** [comment]
如果是数据类型不对，或许应该是会直接报错而不会出现乱码问题？我vocab的编码是utf8，按理说不应该出现乱码问题。同样的资源使用transformers的tokenizer可以work

**Comment by zxcd** [comment]
复现代码为
from paddlenlp.transformers import GPTTokenizer
tokenizer = GPTTokenizer.from_pretrained(path) #path='assets/multilingual'
tokenizer.decode(115)

**Comment by zxcd** [comment]
自查问题已解决，词表中两个ids对应一个字，单个输出时会出现问题
应使用：
tokenizer.decode([6346,115])
