### ISSUE TITLE
[Question]: 基于ERNIE3.0微调得到的UIE，需要的数据量大概有多少？

### ISSUE THREAD

**Issue by WatsonWangZh** [PaddlePaddle/PaddleNLP#3766]
### 请提出你的问题

请问基于ERNIE3.0微调得到的UIE，需要的数据量大概有多少？

**Comment by LemonNoel** [comment]
不同任务微调需要的数据量不一样，简单点的任务每个标签几条或者十几条就够了，复杂点的就需要多些标注。用UIE做分类的话需要的数据量会更多些。

**Comment by WatsonWangZh** [comment]
意思是 UIE的参数 跟ERNIE3.0 差不多？直接在ERNIE3.0上预测效果也可以跟UIE相当么？

**Comment by wawltor** [comment]
> 意思是 UIE的参数 跟ERNIE3.0 差不多？直接在ERNIE3.0上预测效果也可以跟UIE相当么？

UIE是ERNIE 3.0的基础上使用了超过百万的数据(包括负样本)进行微调得到的

**Comment by WatsonWangZh** [comment]
感谢回复，请问相关微调数据集有开放的安排吗？

**Comment by WatsonWangZh** [comment]
微调得到的UIE模型支持预训练任务的微调吗？也就是在其权重的基础上继续进行预训练？
