### ISSUE TITLE
运行一个公开的bert-NER项目出错

### ISSUE THREAD

**Issue by Biggg888** [PaddlePaddle/PaddleNLP#377]
![image](https://user-images.githubusercontent.com/49727302/118019762-ee040900-b38b-11eb-92bc-c4fdd66dd793.png)

![image](https://user-images.githubusercontent.com/49727302/118019899-17bd3000-b38c-11eb-85c5-1277482844af.png)

项目地址：
https://aistudio.baidu.com/aistudio/projectdetail/1925434
from
https://aistudio.baidu.com/aistudio/projectdetail/1477098?channelType=0&channel=0

**Comment by Biggg888** [comment]
Thanks for paddle team.

**Comment by kinghuin** [comment]
Hi, 欢迎反馈问题。您参考的项目是1月份老版本的，现已不再推荐使用，请参考官方最新教程实现：https://aistudio.baidu.com/aistudio/projectdetail/1329361

**Comment by Biggg888** [comment]
> Hi, 欢迎反馈问题。您参考的项目是1月份老版本的，现已不再推荐使用，请参考官方最新教程实现：https://aistudio.baidu.com/aistudio/projectdetail/1329361

您好，我已看完并跑通该项目。
但是我想使用自己的数据集

trans_func = partial(convert_example, tokenizer=tokenizer, label_vocab=label_vocab)

在这里 我看不懂这些语句的作用trans_func  在utils.convert_example里面需要做什么修改之类的

**Comment by kinghuin** [comment]
convert_example的第一个参数会接收load_dataset传来的example（yield words, labels）
除此之外，您可以设置更多的参数用于控制convert_example过程中的max_seq_len等，这些参数的设置需要用partial函数来指定

**Comment by Biggg888** [comment]
> convert_example的第一个参数会接收load_dataset传来的example（yield words, labels）
> 除此之外，您可以设置更多的参数用于控制convert_example过程中的max_seq_len等，这些参数的设置需要用partial函数来指定

请问这个问题要去哪里改参数呢？
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
![image](https://user-images.githubusercontent.com/49727302/118092433-b08c9380-b3fe-11eb-8774-4fd7da81dc0b.png)

**Comment by Biggg888** [comment]
> > convert_example的第一个参数会接收load_dataset传来的example（yield words, labels）
> > 除此之外，您可以设置更多的参数用于控制convert_example过程中的max_seq_len等，这些参数的设置需要用partial函数来指定
> 
> 请问这个问题要去哪里改参数呢？
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
> ![image](https://user-images.githubusercontent.com/49727302/118092433-b08c9380-b3fe-11eb-8774-4fd7da81dc0b.png)

@ZeyuChen

**Comment by Biggg888** [comment]
@wawltor

**Comment by wawltor** [comment]
> @wawltor

看上面的代码已经做了一些改动导致的，因为DataLoader那块的数据是异步的，因此报错不是特别明显，可以设置export FLAGS_call_stack_level=2 ，看看是否有报错信息；如果方便的话，可以提供代码 我们来看看

**Comment by Biggg888** [comment]
> > @wawltor
> 
> 看上面的代码已经做了一些改动导致的，因为DataLoader那块的数据是异步的，因此报错不是特别明显，可以设置export FLAGS_call_stack_level=2 ，看看是否有报错信息；如果方便的话，可以提供代码 我们来看看

我看了历史issue 好像有类似的情况  也是您回复的  但是我不会处理    是我上面没有传入测试集  少了一个数据集  马上贴链接给您看看

**Comment by Biggg888** [comment]
> > @wawltor
> 
> 看上面的代码已经做了一些改动导致的，因为DataLoader那块的数据是异步的，因此报错不是特别明显，可以设置export FLAGS_call_stack_level=2 ，看看是否有报错信息；如果方便的话，可以提供代码 我们来看看

项目“CMeEE”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1922853/40b332ddfa8f4fa89d05c61980629632

**Comment by wawltor** [comment]
您好，您发给我的项目执行不了

**Comment by Biggg888** [comment]
> 您好，您发给我的项目执行不了

额 sorry  我调整一下

**Comment by Biggg888** [comment]
> 您好，您发给我的项目执行不了

劳烦您再试一下

**Comment by Biggg888** [comment]
> > 您好，您发给我的项目执行不了
> 
> 额 sorry 我调整一下

![image](https://user-images.githubusercontent.com/49727302/118140896-637ae280-b43b-11eb-800a-0d0fca8866b0.png)

**Comment by wawltor** [comment]
<img width="544" alt="图片" src="https://user-images.githubusercontent.com/16698950/118144807-7394c100-b43f-11eb-9668-e2fc8be5305b.png">

```python

train_ds1 = train_data_ds
dev_ds1 = dev_data_ds 

train_ds2 = MapDataset(train_ds1)
dev_ds2 = MapDataset(dev_ds1)
```
上面的代码改成这样试试

同时下面的代码写在一行
<img width="1070" alt="图片" src="https://user-images.githubusercontent.com/16698950/118145545-4a286500-b440-11eb-8d9a-1edaa741eba8.png">

**Comment by Biggg888** [comment]
@wawltor  GOD  这是现存不够用的意思吗？
![image](https://user-images.githubusercontent.com/49727302/118146630-61b41d80-b441-11eb-85b7-ad3e87bfa732.png)

显存不够，可以尝试把batch_size调小，batch_size 改成8之后可以跑起来，具体的batch_size可以根据来调一下

**Comment by Biggg888** [comment]
> @wawltor GOD 这是现存不够用的意思吗？
> ![image](https://user-images.githubusercontent.com/49727302/118146630-61b41d80-b441-11eb-85b7-ad3e87bfa732.png)
> 
> 显存不够，可以尝试把batch_size调小，batch_size 改成8之后可以跑起来，具体的batch_size可以根据来调一下

哭了 AI STUDIO 提供的高级版环境我试了batchsize=8 ，和 3 连一个epoch都跑不完就报错了

**Comment by Biggg888** [comment]
上面的模型我丢到colab 和另外一台3090的机子上都爆了= =
最低跳到batch_size=8
换了个模型 还没开始跑epoch就爆了

![image](https://user-images.githubusercontent.com/49727302/118172910-84552f00-b45f-11eb-9d3a-197108b9c003.png)


大佬们，这种问题有办法解决吗？ @wawltor @kinghuin @ZeyuChen 感谢

**Comment by wawltor** [comment]
您好，线下跑了一下你的代码，造成显存爆炸的原因是，您的代码中没有控制输入text文本的长度。需要注意下面两个的使用
1)  在ERNIE 1.0的模型中最大的序列长度是513，因此你需要对你输入的input_ids的长度要进行控制，不然模型的效果会有问题；
2) 显存爆炸的原因，你输入的文本中存在超长文本, 导致局部显存异常增长，最终导致显存不够
<img width="366" alt="图片" src="https://user-images.githubusercontent.com/16698950/118214409-3ca3c700-b4a2-11eb-9547-bda35b9d3abf.png">

因此你需要对输入的文本要做从长度控制
<img width="786" alt="图片" src="https://user-images.githubusercontent.com/16698950/118214463-547b4b00-b4a2-11eb-9b50-9484f4015783.png">
input_ids的长度需要 <= 513

**Comment by wawltor** [comment]
@Biggg888 想问一下 问题解决了吗？

**Comment by Biggg888** [comment]
工程师，您好。上述问题已经解决，正在陷入下一个问题当中。即我的测试集的答案是空的，所以不知道该如何下手就行。还有自动保存了模型之后，不知道如何进行预测。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 运行一个公开的bert-NER项目出错 (#377)





 
@Biggg888 想问一下 问题解决了吗？

**Comment by wawltor** [comment]
没有测试集是没有数据进行evaluation吗？预测的问题 可以参考这个  https://github.com/PaddlePaddle/PaddleNLP/pull/382/files
主要是参考文档，export_model.py  predict.py

**Comment by Biggg888** [comment]
你好，有测试集的，但是测试集里没有相应的标签，只有待预测的语句。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月14日(星期五) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 运行一个公开的bert-NER项目出错 (#377)





 
没有测试集是没有数据进行evaluation吗？预测的问题 可以参考这个  https://github.com/PaddlePaddle/PaddleNLP/pull/382/files
 主要是参考文档，export_model.py  predict.py

**Comment by kinghuin** [comment]
对于测试集，没有标签的，可以这么处理
读数据：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/data.py#L39
处理数据：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/data.py#L120
跑模型：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/model.py#L94
