### ISSUE TITLE
在使用uie slim数据蒸馏时，遇到的一些问题[Question]: 

### ISSUE THREAD

**Issue by starryzwh** [PaddlePaddle/PaddleNLP#3776]
### 请提出你的问题

您好，在使用uie slim数据蒸馏时，有一些问题：
使用版本如下：
paddlepaddle-gpu=2.4.0rc0
paddle2onnx=1.0.2
paddlenlp=develop

1.按照文档，生成了student_model的model_best文件夹，里面只有model_state.pdparams，没有相关的flask部署加载所需要的model.pdiparams和model.pdmodel文件，请问如果要用flask部署，不使用Taskflow方式一键部署的话，怎么生成该文件？
2.在用taskflow一键部署时，会在目录中生成推理的相关文件，static目录中的inference.pdiparams和inference.pdmodel，所以尝试使用该文件进行flask部署，借鉴uie deploy部署方法，发生paddle2onnx相关算子报错，具体输出如下：
```
python ./app.py --model_path_prefix ../data_distill/checkpoint/model_best/static/inference --device_id 2 --device gpu
[2022-11-16 15:17:54,495] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2022-11-16 15:17:54,496] [    INFO] - Already cached /home/zhangwenhao/.paddlenlp/models/ernie-3.0-base-zh/ernie_3.0_base_zh_vocab.txt
[2022-11-16 15:17:54,518] [    INFO] - tokenizer config file saved in /home/zhangwenhao/.paddlenlp/models/ernie-3.0-base-zh/tokenizer_config.json
[2022-11-16 15:17:54,519] [    INFO] - Special tokens file saved in /home/zhangwenhao/.paddlenlp/models/ernie-3.0-base-zh/special_tokens_map.json
>>> [InferBackend] Creating Engine ...
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ../data_distill/checkpoint/model_best/static/inference.pdmodel
[Paddle2ONNX] Paramters file path: ../data_distill/checkpoint/model_best/static/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including einsum,tril_triu,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted
```
是否是相关库的版本不匹配问题？如何解决

**Comment by linjieccc** [comment]
Hi，@starryzwh 

需要替换掉你的app.py里面加载onnx模型的相关代码

静态图模型文件inference.pdiparams和inference.pdmodel通过paddle inference预测库中的create_predictor来加载以及构建predictor，参考这里的例子：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/guides/hardware_support/rocm_docs/infer_example_cn.html#python

**Comment by starryzwh** [comment]
> Hi，@starryzwh
> 
> 需要替换掉你的app.py里面加载onnx模型的相关代码
> 
> 静态图模型文件inference.pdiparams和inference.pdmodel通过paddle inference预测库中的create_predictor来加载以及构建predictor，参考这里的例子：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/guides/hardware_support/rocm_docs/infer_example_cn.html#python

意思是不需要经过onnx部署方式是吗？

**Comment by linjieccc** [comment]
是的，通过paddle的预测库部署
