### ISSUE TITLE
[Question]运行applications里的text_classification案例，训练成功但生成的checkpoints文件夹里没有模型: 

### ISSUE THREAD

**Issue by lucky0604** [PaddlePaddle/PaddleNLP#3777]
### 请提出你的问题

运行此案例 [多标签分类指南](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label#readme)，按照文档要求配置的数据（包含`train.txt, dev.txt, label.txt`），训练是正常的，按文档描述
![image](https://user-images.githubusercontent.com/8739018/202116940-4c459144-bd38-4d6d-89d3-ce91a473944a.png)
但实际上跑完后`checkpoint`文件夹里只有一个`setting.txt`（内容是训练的一些配置）
![image](https://user-images.githubusercontent.com/8739018/202117269-ca75aff8-7faa-4cab-9a0f-ad9b6c2e62ec.png)
这是训练的输出，没有异常报错

**Comment by wawltor** [comment]
看起来是因为你的模型的F1值都是0，所以没有保存模型，可以看下面的代码逻辑
https://github.com/PaddlePaddle/PaddleNLP/blob/39c4f760b15ff40ba48dfb8803b17c71babb13d3/applications/text_classification/multi_class/train.py#L204

**Comment by lucky0604** [comment]
感谢，已解决
