### ISSUE TITLE
[Question]: 文本分类prompt，实际场景的评估值

### ISSUE THREAD

**Issue by FFinchR** [PaddlePaddle/PaddleNLP#3779]
### 请提出你的问题

我有一个疑问，关于文本分类的[prompt方法](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label/few-shot)：
prompt应用场景是【标注成本高的小样本】，那相应的，标注数据生成的测试集规模也很小。
用这个测试集做的评估值，相比用大规模数据做测试集的评估值来说，存在不够准确的问题。
那在实际场景中（没有大规模数据做测试集），应该怎么确定训练出来的模型实际上是否准确？
只能用 【在有大规模数据做测试集的场景评估值高】 做背书？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 我有一个疑问，关于文本分类的[prompt方法](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_label/few-shot)： prompt应用场景是【标注成本高的小样本】，那相应的，标注数据生成的测试集规模也很小。 用这个测试集做的评估值，相比用大规模数据做测试集的评估值来说，存在不够准确的问题。 那在实际场景中（没有大规模数据做测试集），应该怎么确定训练出来的模型实际上是否准确？ 只能用 【在有大规模数据做测试集的场景评估值高】 做背书？

在机器学习和深度学习场景，数据成本我理解是一个非常大的问题，所以在机器学习场景中大家尽快降低这个成本，在常规的微调场景中，大家都是对训练集合、验证集很多都是8:2的比例，但是prompt方法基本可以将训练集的大小降到很低，这里的数据将下降很低；同时在深度学习真实应用场景中，大家是希望快速验证模型效果，而不是大量制作数据来验证效果，prompt方法会大大提升模型验证效率；另外一个角度，Prompt方法不仅是小样本的优势，在模型统一上也具备优势，一套训练流程在建模上是可以搞定多种任务。
