### ISSUE TITLE
[Question]: autoprompt官方给的源码跑不通

### ISSUE THREAD

**Issue by Gavingx** [PaddlePaddle/PaddleNLP#3783]
### 请提出你的问题

paddlepaddle版本：2.4rc
paddlenlp版本：无，拉的源码

按照[autoprompt文档](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot)的流程，执行一样的参数：`python train.py --dataset_dir "./data/" --save_dir "./checkpoints" --max_seq_length 128 --model_name "ernie-3.0-base-zh" --batch_size 8 --learning_rate 3e-5 --epochs 100 --logging_steps 5 --early_stop`会抛出异常：`train.py: error: the following arguments are required: --output_dir`，在参数中加入--output_dir后，会抛出另一个异常：`ValueError: Some specified arguments are not used by the PdArgumentParser: ['--dataset_dir', 'root/t_news/', '--save_dir', './checkpoints', '--batch_size', '8', '--epochs', '100', '--early_stop']`.请问我该怎么处理才能跑通这个流程?

**Comment by LemonNoel** [comment]
这里执行的看起来是微调方式的脚本，需要到上级目录下执行，即`/applications/text_classification/multi_class`。few-shot目录下只能跑提示学习的脚本。

**Comment by Gavingx** [comment]
> 这里执行的看起来是微调方式的脚本，需要到上级目录下执行，即`/applications/text_classification/multi_class`。few-shot目录下只能跑提示学习的脚本。

然而提示学习也没跑通。日志如下：
![image](https://user-images.githubusercontent.com/43789460/202154138-08fde5d4-35f0-467c-89e5-4c4c2fd47798.png)
应该是版本的问题吧。

**Comment by LemonNoel** [comment]
看起来是版本的问题，develop的代码明天会发版。现在可以到 PaddleNLP 的目录下从源码安装。
```
pip install -r requirements.txt
pip install -e .
```

**Comment by Gavingx** [comment]
> pip install -e .

我按顺序执行了以下命令：
`pip install -e .`
`python setup.py build`
`python setup.py install`
'pip list | grep paddlenlp'显示
![image](https://user-images.githubusercontent.com/43789460/202340733-b6f4e4c8-74ae-4140-bc5e-842c724c06de.png)
但是当我执行autopromt的时候，依然报同样的错误：
![image](https://user-images.githubusercontent.com/43789460/202340839-7169981f-9885-44a7-bbd0-a62f2c105f5d.png)

**Comment by LemonNoel** [comment]
建议重新拉取develop代码，卸载原有 paddlenlp 后再安装。或者等晚上发版后安装 2.4.3 版本再试试。

```
git pull origin develop:develop
python -m pip uninstall paddlenlp
cd path_to_PaddleNLP
python -m pip install -r requirements.txt
python -m pip install -e .
```

**Comment by Gavingx** [comment]
> 建议重新拉取develop代码，卸载原有 paddlenlp 后再安装。或者等晚上发版后安装 2.4.3 版本再试试。
> 
> ```
> git pull origin develop:develop
> python -m pip uninstall paddlenlp
> cd path_to_PaddleNLP
> python -m pip install -r requirements.txt
> python -m pip install -e .
> ```
我重新clone了tag 2.4.3的代码，已经通了。但是又出现新的问题。执行脚本如下：
`python train.py \
--overwrite_output_dir True
--device gpu:1 \
--data_dir ./data \
--output_dir ./checkpoints/ \
--prompt "这条新闻标题的主题是" \
--max_seq_length 128  \
--learning_rate 3e-6 \
--ppt_learning_rate 3e-5 \
--do_train \
--do_eval \
--use_rdrop \
--max_steps 1000 \
--eval_steps 10 \
--logging_steps 5 \
--save_total_limit 1 \
--load_best_model_at_end True \
--per_device_eval_batch_size 32 \
--per_device_train_batch_size 8 \
--do_predict \
--do_export`
报错日志如下：
`[2022-11-18 18:09:12,139] [    INFO] - Exporting inference model to ./checkpoints/export/model
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 161, in main
    export_type=model_args.export_type)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/prompt_trainer.py", line 317, in export_model
    export_model(self.model, input_spec, export_path, export_type)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/export.py", line 61, in export_model
    paddle.jit.save(model, save_path)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
    func(layer, path, input_spec, **configs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 857, in save
    inner_input_spec, with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/prompt_trainer.py", line 373, in forward
        outputs, input_dict["masked_positions"])
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/verbalizer.py", line 389, in process_outputs
        self).process_outputs(outputs, masked_positions)
    File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/verbalizer.py", line 176, in process_outputs
        outputs = outputs.reshape([-1, num_pred])
        outputs = paddle.gather(outputs, masked_positions)
        outputs = outputs.reshape([batch_size, -1, num_pred])
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return outputs

    File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/manipulation.py", line 2139, in reshape
        return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 6435, in reshape
        attrs["shape"] = get_attr_shape(shape)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 6411, in get_attr_shape
        % dim_idx)

    AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1.

        # N = x.shape()[2]              # N is an int. (NOT recommend under @to_static)
        N = paddle.shape(x)[2]          # N is a Tensor. (Recommend)
        z = paddle.reshape([N, -1, 4])  # z.shape is [-1, -1, 4]

    If your target shape in Reshape represents dynamic shape, please turn it into a Tensor under @to_static. See above example for details.`

**Comment by bigcash** [comment]
> > 建议重新拉取develop代码，卸载原有 paddlenlp 后再安装。或者等晚上发版后安装 2.4.3 版本再试试。
> > ```
> > git pull origin develop:develop
> > python -m pip uninstall paddlenlp
> > cd path_to_PaddleNLP
> > python -m pip install -r requirements.txt
> > python -m pip install -e .
> > ```
> 
> 我重新clone了tag 2.4.3的代码，已经通了。但是又出现新的问题。执行脚本如下： `python train.py \ --overwrite_output_dir True --device gpu:1 \ --data_dir ./data \ --output_dir ./checkpoints/ \ --prompt "这条新闻标题的主题是" \ --max_seq_length 128 \ --learning_rate 3e-6 \ --ppt_learning_rate 3e-5 \ --do_train \ --do_eval \ --use_rdrop \ --max_steps 1000 \ --eval_steps 10 \ --logging_steps 5 \ --save_total_limit 1 \ --load_best_model_at_end True \ --per_device_eval_batch_size 32 \ --per_device_train_batch_size 8 \ --do_predict \ --do_export` 报错日志如下： `[2022-11-18 18:09:12,139] [ INFO] - Exporting inference model to ./checkpoints/export/model Traceback (most recent call last): File "train.py", line 165, in main() File "train.py", line 161, in main export_type=model_args.export_type) File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/prompt_trainer.py", line 317, in export_model export_model(self.model, input_spec, export_path, export_type) File "/usr/local/lib/python3.7/dist-packages/paddlenlp/transformers/export.py", line 61, in export_model paddle.jit.save(model, save_path) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper func(layer, path, input_spec, **configs) File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in **impl** return func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 857, in save inner_input_spec, with_hook=with_hook) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec *desired_input_spec, with_hook=with_hook) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program concrete_program, partial_program_layer = self._program_cache[cache_key] File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in **getitem** self._caches[item_id] = self._build_once(item) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once **cache_key.kwargs) File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in **impl** return func(*args, **kwargs) File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec error_data.raise_new_exception() File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception six.exec_("raise new_exception from None") File "", line 1, in AssertionError: In transformed code:
> 
> ```
> File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/prompt_trainer.py", line 373, in forward
>     outputs, input_dict["masked_positions"])
> File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/verbalizer.py", line 389, in process_outputs
>     self).process_outputs(outputs, masked_positions)
> File "/usr/local/lib/python3.7/dist-packages/paddlenlp/prompt/verbalizer.py", line 176, in process_outputs
>     outputs = outputs.reshape([-1, num_pred])
>     outputs = paddle.gather(outputs, masked_positions)
>     outputs = outputs.reshape([batch_size, -1, num_pred])
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>     return outputs
> 
> File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/manipulation.py", line 2139, in reshape
>     return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 6435, in reshape
>     attrs["shape"] = get_attr_shape(shape)
> File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 6411, in get_attr_shape
>     % dim_idx)
> 
> AssertionError: Only one dimension value of 'shape' in reshape can be -1. But received shape[1] is also -1.
> 
>     # N = x.shape()[2]              # N is an int. (NOT recommend under @to_static)
>     N = paddle.shape(x)[2]          # N is a Tensor. (Recommend)
>     z = paddle.reshape([N, -1, 4])  # z.shape is [-1, -1, 4]
> 
> If your target shape in Reshape represents dynamic shape, please turn it into a Tensor under @to_static. See above example for details.`
> ```

也是刚刚遇到同样的问题，新版本要求paddle版本是2.4.0以上，建议你更新安装2.4.0rc0版本。
另外，下载release中的源码吧，比如2.4.3，develop里代码因为更新比较快，可能有不太稳定的问题，更新多难免出点问题，(￣▽￣)"
感谢开源~
