### ISSUE TITLE
[Question]: 关于SER任务，value是分开的两行或多行时该怎么处理

### ISSUE THREAD

**Issue by pogevip** [PaddlePaddle/PaddleNLP#3784]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/27748841/202141200-4e1161ff-8c16-43b6-ab6f-6af7b96bc42e.png)

##### 如上图，【货物或应税劳务、服务名称】这一列，下面的【小米红米3时尚金色】和【移动联通电信4G手机双卡双待】这两个是分开的两行，
1. 如果是当做key-value抽取任务（SER+RE）的话，该如何处理？一个key link 到多个value吗？
2. 如果是当做SER任务，直接识别实体的话，又该怎么处理？

**Comment by pogevip** [comment]
我测试ernie-layout 现有的MRC的模型，似乎智能识别到一行。

**Comment by linjieccc** [comment]
Hi, @pogevip 

当前ERNIE-Layout中OCR的返回是从左上到右下排序的，所以可能会导致这种同列分行的情况识别有误，可以考虑增加一个版面分析模块来优化识别文本的排序

版面分析可以参考：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/quickstart.md#223-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90
