### ISSUE TITLE
[Question]: 使用 document_intelligence 估计出的答案在图片中没有那个字符串

### ISSUE THREAD

**Issue by svjack** [PaddlePaddle/PaddleNLP#3791]
### 请提出你的问题

您好 
```python
docprompt = Taskflow("document_intelligence", lang="ch")
docprompt(
[{"doc": "sample1.png", "prompt":
[
    "嵩山在哪？",
]}])
```
![sample1](https://user-images.githubusercontent.com/27874014/202361394-f9cd3a69-a898-4c79-afa1-03c2928a6ab3.jpg)

用这个图片 输出的结果是
```json 
[{'prompt': '嵩山在哪？',
  'result': [{'value': '中国河南省郊州市登封市', 'prob': 1.0, 'start': 968, 'end': 978}]}]
```
而且使用paddleocr识别后也没有这个字符串，请问这个结果是如何产生的？

**Comment by paulpaul91** [comment]
> ### 请提出你的问题
> 您好
> 
> ```python
> docprompt = Taskflow("document_intelligence", lang="ch")
> docprompt(
> [{"doc": "sample1.png", "prompt":
> [
>     "嵩山在哪？",
> ]}])
> ```
> 
> ![sample1](https://user-images.githubusercontent.com/27874014/202361394-f9cd3a69-a898-4c79-afa1-03c2928a6ab3.jpg)
> 
> 用这个图片 输出的结果是
> 
> ```json
> [{'prompt': '嵩山在哪？',
>   'result': [{'value': '中国河南省郊州市登封市', 'prob': 1.0, 'start': 968, 'end': 978}]}]
> ```
> 
> 而且使用paddleocr识别后也没有这个字符串，请问这个结果是如何产生的？



> ### 请提出你的问题
> 您好
> 
> ```python
> docprompt = Taskflow("document_intelligence", lang="ch")
> docprompt(
> [{"doc": "sample1.png", "prompt":
> [
>     "嵩山在哪？",
> ]}])
> ```
> 
> ![sample1](https://user-images.githubusercontent.com/27874014/202361394-f9cd3a69-a898-4c79-afa1-03c2928a6ab3.jpg)
> 
> 用这个图片 输出的结果是
> 
> ```json
> [{'prompt': '嵩山在哪？',
>   'result': [{'value': '中国河南省郊州市登封市', 'prob': 1.0, 'start': 968, 'end': 978}]}]
> ```
> 
> 而且使用paddleocr识别后也没有这个字符串，请问这个结果是如何产生的？

看着右侧是有的呀，郊是ocr识别错误了

**Comment by svjack** [comment]
> > ### 请提出你的问题
> > 您好
> > ```python
> > docprompt = Taskflow("document_intelligence", lang="ch")
> > docprompt(
> > [{"doc": "sample1.png", "prompt":
> > [
> >     "嵩山在哪？",
> > ]}])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![sample1](https://user-images.githubusercontent.com/27874014/202361394-f9cd3a69-a898-4c79-afa1-03c2928a6ab3.jpg)
> > 用这个图片 输出的结果是
> > ```json
> > [{'prompt': '嵩山在哪？',
> >   'result': [{'value': '中国河南省郊州市登封市', 'prob': 1.0, 'start': 968, 'end': 978}]}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而且使用paddleocr识别后也没有这个字符串，请问这个结果是如何产生的？
> 
> > ### 请提出你的问题
> > 您好
> > ```python
> > docprompt = Taskflow("document_intelligence", lang="ch")
> > docprompt(
> > [{"doc": "sample1.png", "prompt":
> > [
> >     "嵩山在哪？",
> > ]}])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![sample1](https://user-images.githubusercontent.com/27874014/202361394-f9cd3a69-a898-4c79-afa1-03c2928a6ab3.jpg)
> > 用这个图片 输出的结果是
> > ```json
> > [{'prompt': '嵩山在哪？',
> >   'result': [{'value': '中国河南省郊州市登封市', 'prob': 1.0, 'start': 968, 'end': 978}]}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而且使用paddleocr识别后也没有这个字符串，请问这个结果是如何产生的？
> 
> 看着右侧是有的呀，郊是ocr识别错误了

如果以PPstructure 的观点 这个问题答案既出现在text中也出现在类似table的结构中 当两个都有较高置信度时 有没有办法制定一个优先级 或者规则嵌入方法？
