### ISSUE TITLE
使用Taskflow时的参数问题[Question]: 

### ISSUE THREAD

**Issue by starryzwh** [PaddlePaddle/PaddleNLP#3797]
### 请提出你的问题

您好，在gpu环境下，使用paddlepaddle-gpu，在使用paddlenlp的Taskflow时，能否指定使用推理设备为CPU？我看源码是默认通过paddle.get_device来进行判定的，如何设置使用CPU

**Comment by starryzwh** [comment]
> ### 请提出你的问题
> 您好，在gpu环境下，使用paddlepaddle-gpu，在使用paddlenlp的Taskflow时，能否指定使用推理设备为CPU？我看源码是默认通过paddle.get_device来进行判定的，如何设置使用CPU

在后续尝试中，将参数device_id设置为-1，运行时没有用到gpu资源，是否认为，-1代表cpu设备？

**Comment by wawltor** [comment]
> > ### 请提出你的问题
> > 您好，在gpu环境下，使用paddlepaddle-gpu，在使用paddlenlp的Taskflow时，能否指定使用推理设备为CPU？我看源码是默认通过paddle.get_device来进行判定的，如何设置使用CPU
> 
> 在后续尝试中，将参数device_id设置为-1，运行时没有用到gpu资源，是否认为，-1代表cpu设备？

是的
