### ISSUE TITLE
[Question]: UIE预测报错

### ISSUE THREAD

**Issue by yuwochangzai** [PaddlePaddle/PaddleNLP#3798]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/6983001/202390841-02b1e6e4-ac9e-4a61-ba97-6ef9bd2fcd60.png)

**Comment by linjieccc** [comment]
@yuwochangzai 方便提供下复现代码以及paddlenlp版本信息么

**Comment by yuwochangzai** [comment]
> @yuwochangzai 方便提供下复现代码以及paddlenlp版本信息么
你好，调用UIE下的[deploy/python/uie_predictor.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py#L458)的[predict](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/uie_predictor.py#L458)方法报的错，版本信息如下：
![image](https://user-images.githubusercontent.com/6983001/202641988-37ca95d8-da58-4aaf-8741-25bac4130c70.png)

**Comment by yuwochangzai** [comment]
> @yuwochangzai 方便提供下复现代码以及paddlenlp版本信息么

是不是因为线程不安全的原因，今天跑那一批待预测的数据，又不报错了
