### ISSUE TITLE
docprompt发布过去已经20多天，希望paddlenlp人员能够抽空把docprompt的动态图模型及参数发布出来。

### ISSUE THREAD

**Issue by wn1652400018** [PaddlePaddle/PaddleNLP#3799]
### Feature request

document_intelligence任务需要提供动态图的模型参数和模型代码

### Motivation

目前paddlenlp中的docprompt的zero-shot性能非常的不错，但是仍然需要微调。
官方目前只提供了静态图的模型参数，但是对应动态图模型的参数和模型网络代码没有提供，导致不能进行微调。
虽然官方提供了在ErnieLayout模型上微调的脚本，但是该脚本训练的模型不能直接用在docprompt任务中（我通过调试发现，他们的输入明显不一样），而且ernielayout-xlm-base没有在文档问答的数据上预训练过。
docprompt发布过去已经20多天，希望paddlenlp人员能够抽空把docprompt的动态图模型及参数发布出来。

### Your contribution

。

**Comment by chenxiaozeng** [comment]
目前DocPrompt确实不支持微调，可以在开源的ERNIE-Layout基础上微调上游任务。 11月底我们将开放支持微调的UIE-x，用于多模态文档信息抽取，敬请关注repo动态，谢谢！

**Comment by Ch4osMy7h** [comment]
请问UIE-X相关文档信息抽取的模型啥时候发布，我看上周的时候已经发布了，今天看相关分支revert了。
