### ISSUE TITLE
[Question]: dreambooth keyword may have less weight than the normal ones? 通过dreambooth“塞”进模型里的东西权重不够怎么办

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#3804]
### 请提出你的问题

process: 
1. prepare tens of images include some item/object
2. run `ppdiffusers/example/dreambooth/...`
3. do generation by exported model and prompt, the prompt include not only the object 'sks' pinned, but also some other attributes with adjectives

the results generated by model may not include the object we pinned by 'sks', but have the attributes based on the other prompt

so, my question is, how can i keep/force the 'sks' keyword exists in the results?

**Comment by JunnYu** [comment]
个人感觉 从代码层面上看 **dreambooth训练**跟**模型微调**一样，因此的确会出现你说的这种情况。
如果想要加强里面部分单词的权重，这其实也没有什么太好的办法。
可能需要模型训练的时间更久，模型才能真正关注到这个 "sks"的意思。

**Comment by godlockin** [comment]
现在代码里在哪里可以把'sks'给改了，看推特上说sks是一种枪的型号，建议换掉…

现在有些困扰，似乎放更多的样本数据，增加更多的训练轮数，降低学习率…效果都不增反降，都没有直接default参数训练一轮的效果好

btw，我有个刷了100轮的模型确实sks丢啥进去都是奇形怪状的枪，可能就是这个原因

**Comment by godlockin** [comment]
close this question and raise a new one to trace, thx for answering
