### ISSUE TITLE
[Question]: PaddleNLP/examples/machine_reading_comprehension/DuReader-robust这个模型如何预测？

### ISSUE THREAD

**Issue by jyjy007** [PaddlePaddle/PaddleNLP#3807]
### 请提出你的问题

听说dureader的相关工作已经合并到paddlenlp了，但是在model_zoo没有看到有相关的模型，在example下看到有简单的dureader-robust的介绍，这里提供了封装好的模型训练脚本。但是模型预测似乎有点麻烦，不知道是否有封装更完善的dureader-robust抽取式阅读理解的模型应用代码？

**Comment by guoshengCS** [comment]
目前有的相关代码在这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/machine_reading_comprehension/DuReader-robust ，暂时还没有更多的例子，请问您那边是遇到什么问题了呢

**Comment by jyjy007** [comment]
> 目前有的相关代码在这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/machine_reading_comprehension/DuReader-robust ，暂时还没有更多的例子，请问您那边是遇到什么问题了呢

我是想对自己的数据进行模型预测，如果根据run_du.py进行预测，感觉代码有点复杂，这里有没有更多的示例代码？
另外就是有没有像paddlenlp其他模块比如uie之类的封装在taskflow里这样比较简洁的用法？
