### ISSUE TITLE
[Question]: 我是使用doccano标注数据的时候，按照文档中的指示步骤，生成的json数据中entities项都是空的，例如：{"id":90,"text":"厦门到深圳500块钱4月24号交通费","entities":[],"relations":[]}

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#3814]
### 请提出你的问题

我是使用doccano标注数据的时候，按照文档中的指示步骤，生成的json数据中entities项都是空的，例如：{"id":90,"text":"厦门到深圳500块钱4月24号交通费","entities":[],"relations":[]}

参考的文档有：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#%E5%AE%9E%E4%BD%93%E6%8A%BD%E5%8F%96  这个里面的训练定制部分
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md

**Comment by lichuantao6626** [comment]
使用的测试数据：
深大到双龙28块钱4月24号交通费
北大到清华30块钱6月24号交通费
汉威国际到双龙20块钱4月24号交通费
小红门到宋家庄30块钱4月24号交通费
北京到上海600块钱12月30号交通费
广东到沈阳700块钱4月24号交通费
新疆到合肥3000块钱4月24号交通费
宁夏到甘肃300块钱4月24号交通费
福州到合肥400块钱4月24号交通费
厦门到深圳500块钱4月24号交通费

**Comment by lichuantao6626** [comment]
测试的效果：
{"id":81,"text":"深大到双龙28块钱4月24号交通费","entities":[],"relations":[]}
{"id":82,"text":"北大到清华30块钱6月24号交通费","entities":[],"relations":[]}
{"id":83,"text":"汉威国际到双龙20块钱4月24号交通费","entities":[],"relations":[]}
{"id":84,"text":"小红门到宋家庄30块钱4月24号交通费","entities":[],"relations":[]}
{"id":85,"text":"北京到上海600块钱12月30号交通费","entities":[],"relations":[]}
{"id":86,"text":"广东到沈阳700块钱4月24号交通费","entities":[],"relations":[]}
{"id":87,"text":"新疆到合肥3000块钱4月24号交通费","entities":[],"relations":[]}
{"id":88,"text":"宁夏到甘肃300块钱4月24号交通费","entities":[],"relations":[]}
{"id":89,"text":"福州到合肥400块钱4月24号交通费","entities":[],"relations":[]}
{"id":90,"text":"厦门到深圳500块钱4月24号交通费","entities":[],"relations":[]}

总结：导出的数据中entities项都是空的，官网的使用指南里面给的测试数据这一项都是有值的

**Comment by linjieccc** [comment]
Hi, @lichuantao6626 

你的doccano版本是多少？

**Comment by lichuantao6626** [comment]
好像是1.8的版本



| |
lichuantao6626
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Linjie ***@***.***> |
| 日期 | 2022年11月18日 18:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: 我是使用doccano标注数据的时候，按照文档中的指示步骤，生成的json数据中entities项都是空的，例如：{"id":90,"text":"厦门到深圳500块钱4月24号交通费","entities":[],"relations":[]} (Issue #3814) |

Hi, @lichuantao6626

你的doccano版本是多少？

**Comment by linjieccc** [comment]
用1.6.2或者1.7.0版本试试呢，我们在1.6.2和1.7.0版本上验证过没问题

**Comment by lichuantao6626** [comment]
您好，我重新安装的1.6的版本，然后导出的数据还是：{"id": 2, "text": "张浩6月7日苏州街地铁站到海淀黄庄", "relations": [], "entities": []}
问题疑点：
1、抽取式任务标签的span和Relation两个标签都要配置吗，按照文档我两个配置了
![image](https://user-images.githubusercontent.com/102787771/202832101-ce1d71a9-c7e4-4e04-83e1-8b7c10553807.png)
![image](https://user-images.githubusercontent.com/102787771/202832106-6aaf8e64-58ae-4939-8500-9a3cb3a89343.png)
2、我在上传数据的时候报了一个错：
[2022-11-19 02:47:55,101: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[24aacdc5-3e40-4e86-8644-bbd65081ddf5] received
[2022-11-19 02:47:55,163: ERROR/ForkPoolWorker-1] Filename: /root/doccano/media/nEfi9GfM8A44LYkU8Dq5Nb/JmWBfH38aFMhkkDKHpC8Wf/test03.txt, Line: 1, Data: {}, Error: 'label'

test03.txt文本里面的内容为：张浩6月7日苏州街地铁站到海淀黄庄
这个是啥问题引起的，导致导出的数据的"relations": [], "entities": []这两项都是空的。
感谢！

**Comment by linjieccc** [comment]
Hi，@lichuantao6626

请参考标注示例并排查下文本中的实体、关系是否被正确标注

**Comment by lichuantao6626** [comment]
感谢啊，问题已经解决了 span实体标注上有问题，导致导出没有实体数据，在微信群里已经有人帮我指出来了。



| |
lichuantao6626
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Linjie ***@***.***> |
| 日期 | 2022年11月21日 10:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: 我是使用doccano标注数据的时候，按照文档中的指示步骤，生成的json数据中entities项都是空的，例如：{"id":90,"text":"厦门到深圳500块钱4月24号交通费","entities":[],"relations":[]} (Issue #3814) |

***@***.***

请参考标注示例并排查下文本中的实体、关系是否被正确标注
