### ISSUE TITLE
[Question]: 关于ppdiffuser使用到ema技术的问题

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#3815]
### 请提出你的问题

之前在下面这个链接看到了ppdiffuser里面用了ema技术：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/models/ema.py

在交流群里问到大佬，说是在预训练阶段会使用到。能否请问大佬给个具体使用到ema做训练的脚本文件链接。

还有就是，ema貌似会让模型的训练时间增加，如果在预训练阶段就用ema，这个预训练耗时会不会很长？

使用ema后，对模型的所带来的效果提升又有多少，是否有消融实习什么的？

谢谢大佬

**Comment by JunnYu** [comment]
- 预训练的过程中我们提供了ema的选项
https://github.com/PaddlePaddle/PaddleNLP/blob/6e73ee0019b1b3dae5e48b34a08f131ffda2efb9/ppdiffusers/examples/text_to_image_laion400m/ldm/model.py#L132-L144
- ema的确会增加训练时间，之前也测过数据但没记录下载。
- ema也会增加部分显存，因为又开辟一个空间存储模型的参数。
- ema对于模型效果的提升其实也不是太大的，目前我们这里并未有进行消融实验。

**Comment by ZeyuTeng96** [comment]
> 

我个人使用ema的时候感觉还是有一定提升的，但并没有使用过很多次，大佬是使用过很多次，觉得对模型效果提升不是太大？

还有就是我个人在使用时，发现ema会增加训练时间这一问题后，我一般会先训练一遍不使用ema的模型，根据之前模型不使用ema在各个epoch的收敛、精度等情况，再重新训练一个带有使用ema的模型，让模型在特定的epoch开启使用ema，这个思路大佬觉得是否合理呢？

**Comment by ZeyuTeng96** [comment]
请问大佬能再回复下我的问题？ @JunnYu

**Comment by JunnYu** [comment]
我之前其实也训练过带ema的模型，关于有没有提升其实不太清楚。
- ema会保存2个模型权重，1个是非ema的权重，1个是ema权重，ema的权重不会影响非ema权重的精度。
- ema增加训练时间很正常，因为他把每轮优化后的模型权重都相加（滑动平均操作）模型太大了，这个操作费时间的！
- 先不开启ema，然后再开启ema，其实相当于训练好一个模型，再热启来着了
