### ISSUE TITLE
neural_search ranking里cross encoder提供的预训练模型似乎有误 

### ISSUE THREAD

**Issue by MengZou0905** [PaddlePaddle/PaddleNLP#3818]
您好，neural_search ranking部分cross encoder提供的预训练模型似乎有误（和ernie match提供的预训练模型混淆了），请问能帮忙核查一下吗？非常感谢！
[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/cross_encoder](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/cross_encoder#5-%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83)

**Comment by w5688414** [comment]
感谢提醒，考虑到训练出来的模型不太通用（不过数据集已经开源，您可以训练出来），只是方法通用，所以cross encoder目前没有提供预训练模型。

**Comment by MengZou0905** [comment]
谢谢您的回复~
因为看到有性能对比：
![image](https://user-images.githubusercontent.com/20831637/202830223-884f9a34-9373-410d-bff1-978c2081440c.png)
并且pairwise方式的ERNIE-Gram模型提供了，自己训练不确定是否会因为设置误差导致复现不到对应效果，就非常期待平行对比的Cross encoder能放出预训练模型呀~

**Comment by w5688414** [comment]
> 

您可以先跑一下cross encoder，很容易复现，我记得当时都没有调参数，可能有更好的参数优化auc
