### ISSUE TITLE
[Question]: 'CompressionArguments' object has no attribute 'do_compress'

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#3825]
### 请提出你的问题

我在使用TaskFlow的定制训练模型中，加入自己的数据进行了模型的微调，但是在执行完下面这个命令后，
python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 16 \
    --per_device_train_batch_size  16 \
    --num_train_epochs 100 \
    --learning_rate 1e-5 \
    --label_names 'start_positions' 'end_positions' \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1 

在最后提示了一个错误：AttributeError: 'CompressionArguments' object has no attribute 'do_compress'
![image](https://user-images.githubusercontent.com/102787771/202841812-c4abd1dd-f889-4d5a-b2ae-b04efa67d761.png)

再请教一个问题：
![image](https://user-images.githubusercontent.com/102787771/202841899-543bb778-9196-4b05-a714-2ba6cd2467f8.png)
红框里面的f1指标代表啥意思，这些参数的含义在那个地方有详细的介绍吗。

**Comment by wawltor** [comment]
升级到最新PaddleNLP的版本，eval_f1 表示验证集的F1值，表示模型效果
