### ISSUE TITLE
"AssertionError: input_ids: 17, label: 18" in sentiment_analysis/extraction -> sh run_train.sh

### ISSUE THREAD

**Issue by xinaiwunai** [PaddlePaddle/PaddleNLP#3826]
aistudio@jupyter-114597-5085407:~/work/PaddleNLP-develop/applications/sentiment_analysis/extraction$ pip list|grep paddle
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.0
paddlefsl                      1.1.0
paddlehub                      2.3.0
paddlenlp                      2.3.0rc0
paddlepaddle-gpu               2.4.0rc0.post112
tb-paddle                      0.3.6

---------------------------------------------------------------------
aistudio@jupyter-114597-5085407:~/work/PaddleNLP-develop/applications/sentiment_analysis/extraction$ sh run_train.sh
[2022-11-20 22:39:08,217] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/skep_ernie_1.0_large_ch/skep_ernie_1.0_large_ch.vocab.txt
[2022-11-20 22:39:08,227] [ WARNING] - Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    train()
  File "train.py", line 57, in train
    train_ds = train_ds.map(trans_func, lazy=False)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 413, in map
    return self._map(fn, lazy=lazy, batched=batched)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 422, in _map
    fn(self.new_data[idx]) for idx in range(len(self.new_data))
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 422, in <listcomp>
    fn(self.new_data[idx]) for idx in range(len(self.new_data))
  File "/home/aistudio/work/PaddleNLP-develop/applications/sentiment_analysis/extraction/data.py", line 60, in convert_example_to_feature
    ), f"input_ids: {len(encoded_inputs['input_ids'])}, label: {len(label)}"
AssertionError: input_ids: 17, label: 18

**Comment by 1649759610** [comment]
训练配置或代码中有做过修改吗，另外方便提供下你的训练数据吗，或者能够复现该问题的最小数据集合。

**Comment by xinaiwunai** [comment]
> 训练配置或代码中有做过修改吗，另外方便提供下你的训练数据吗，或者能够复现该问题的最小数据集合。

@1649759610 

使用的是[README](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/extraction)中的脚本和[Demo数据](https://bj.bcebos.com/v1/paddlenlp/data/ext_data.tar.gz).

经过几次测试，怀疑是当text中包含空格时，token出的id位数会有缺失。
如，data/ext_data/train.txt 中的第12行
`我自己喜欢的炒饭味道 就是这样的	O O O B-Opinion I-Opinion O O O B-Aspect I-Aspect O O O O O O`
'味道'后面有一个空格' '，判断字符串长度的时候，前后一致。
但当转为token-id的时候，长度就缺少了一位。
同时，如果将文本中另外某字手工修改为空格，会发现token-id又更少了一位。

**Comment by xinaiwunai** [comment]
> 训练配置或代码中有做过修改吗，另外方便提供下你的训练数据吗，或者能够复现该问题的最小数据集合。

使用的是[README](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/extraction)中的脚本和[Demo数据](https://bj.bcebos.com/v1/paddlenlp/data/ext_data.tar.gz).

经过几次测试，怀疑是当text中包含空格时，token出的id位数会有缺失。
如，data/ext_data/train.txt 中的第12行
我自己喜欢的炒饭味道 就是这样的 O O O B-Opinion I-Opinion O O O B-Aspect I-Aspect O O O O O O
'味道后面又一个空格，判断字符串长度的时候，前后一致。
但当转为token-id的时候，长度就缺少了一位。
同时，如果将文本中另外某字手工修改为空格，会发现token-id又更少了一位。

**Comment by xinaiwunai** [comment]
升级 paddlenlp 到 2.4.3 后，问题依旧。
--------------------------------------------
aistudio@jupyter-114597-5085407:~/work/PaddleNLP-develop/applications/sentiment_analysis/extraction$ pip list|grep paddle
paddle-bfloat                  0.1.7
paddle2onnx                    1.0.0
paddlefsl                      1.1.0
paddlehub                      2.3.0
paddlenlp                      2.4.3
paddlepaddle-gpu               2.4.0rc0.post112
tb-paddle                      0.3.6

**Comment by xinaiwunai** [comment]
字符串长度一致。
{'text': ['我', '自', '己', '喜', '欢', '的', '炒', '饭', '味', '道', ' ', '就', '是', '这', '样', '的'], 'label': ['O', 'O', 'O', 'B-Opinion', 'I-Opinion', 'O', 'O', 'O', 'B-Aspect', 'I-Aspect', 'O', 'O', 'O', 'O', 'O', 'O']}
-----------------
encoded_inputs = tokenizer(list(example["text"]),
                               is_split_into_words=True,
                               max_seq_len=max_seq_len,
                               return_length=True)
------------------------------
encoded_inputs 中短了：
{'input_ids': [1, 75, 67, 324, 692, 811, 5, 2152, 1528, 775, 151, 113, 10, 47, 314, 5, 2], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'length': 17, 'seq_len': 17}

**Comment by 1649759610** [comment]
好的，感谢反馈，我们会尽快修复。

为方便使用，您当前可以在convert_example_to_feature函数中，将编码时的参数is_split_into_words设置为"token"，这样可以正常运行：

```python
def convert_example_to_feature(example,
                               tokenizer,
                               label2id,
                               max_seq_len=512,
                               is_test=False):
    encoded_inputs = tokenizer(list(example["text"]),
                               is_split_into_words="token",
                               max_seq_len=max_seq_len,
                               return_length=True)
```

**Comment by xinaiwunai** [comment]
thanks

**Comment by cyrusir-young** [comment]
我这几天也刚刚遇到这个问题，于是我直接改了一下read函数
def read(data_path):
    with open(data_path, "r", encoding="utf-8") as f:
        for line in f.readlines():
            text, label = line.split("\t")
            cleaned_text = []
            cleaned_label = []
            label = label[:-1] if label[-1] == "\n" else label
            label = label.split(" ")
            for char, label_char in zip(text, label):
                if char.isspace():
                    continue
                cleaned_text.append(char)
                cleaned_label.append(label_char)
            assert len(cleaned_text) == len(cleaned_label), f"{cleaned_text},  {cleaned_label}"
            example = {"text": cleaned_text, "label": cleaned_label}
            yield example
让他读取的时候自动删掉text中的空格就可以了
