### ISSUE TITLE
AutoPrompt 生成应用

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#3827]
### 请提出你的问题

AutoPrompt 可以做生成类应用吗？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> AutoPrompt 可以做生成类应用吗？

可以的，目前AutoPrompt template 的设计可以兼容生成模型，不过目前我们还没有开发相关示例出来

**Comment by ZTurboX** [comment]
> > ### 请提出你的问题
> > AutoPrompt 可以做生成类应用吗？
> 
> 可以的，目前AutoPrompt template 的设计可以兼容生成模型，不过目前我们还没有开发相关示例出来

文本生成一般是不定长度的，用prompt怎么来构造模板，有好的建议吗
