### ISSUE TITLE
[Question]: ernie-layout mrc 任务的数据格式问题

### ISSUE THREAD

**Issue by svjack** [PaddlePaddle/PaddleNLP#3828]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/cf478ba6ee3a0e76741bdb901b671ef3ff6d024f/model_zoo/ernie-layout/README.md

enire-layout 中 utils.py 中数据预处理模块好像跟docvqa_zh中的数据格式有些没有对齐。
比如下载后的docvqa_zh没有 pageno 这个域 answers 的解析也有细微差别 
如果是这样能修正一下吗？

**Comment by linjieccc** [comment]
Hi，@svjack

当前我们统一了ERNIE-Layout不同下游任务数据集的数据结构，因此在数据集加载的时候会针对不同原始数据集处理为统一的结构，这里是docvqa_zh数据集相关字段和对应数据结构定义，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py#L65

处理后的数据格式示例：

```python
import paddlenlp
from datasets import load_dataset

train_ds, dev_ds, test_ds = load_dataset(
        "docvqa_zh", split=["train", "validation", "test"])
print(train_ds[0])
```

**Comment by svjack** [comment]
> Hi，@svjack
> 
> 当前我们统一了ERNIE-Layout不同下游任务数据集的数据结构，因此在数据集加载的时候会针对不同原始数据集处理为统一的结构，这里是docvqa_zh数据集相关字段和对应数据结构定义，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py#L65
> 
> 处理后的数据格式示例：
> 
> ```python
> import paddlenlp
> from datasets import load_dataset
> 
> train_ds, dev_ds, test_ds = load_dataset(
>         "docvqa_zh", split=["train", "validation", "test"])
> print(train_ds[0])
> ```
从
_URL = "https://bj.bcebos.com/paddlenlp/datasets/docvqa_zh.tar.gz"
下载数据集之后 用dataset load 或者pandas 看列名时
<img width="776" alt="Screenshot 2022-11-21 at 13 19 45" src="https://user-images.githubusercontent.com/27874014/202971607-a08e6762-0e8b-42b8-bd51-36e680381393.png">

没有page_no 这个域

**Comment by svjack** [comment]
utils.py 中
```python
for qid, question, answers in zip(qas["question_id"],
                                              qas["question"], qas["answers"]):
```
改成
```python
for d in qas:
     qid = d["question_id"]
     question = d["question"]
     answers = d["answers"]
```
才能运行

**Comment by linjieccc** [comment]
> utils.py 中
> 
> ```python
> for qid, question, answers in zip(qas["question_id"],
>                                               qas["question"], qas["answers"]):
> ```
> 
> 改成
> 
> ```python
> for d in qas:
>      qid = d["question_id"]
>      question = d["question"]
>      answers = d["answers"]
> ```
> 
> 才能运行

Hi，这部分处理以及page_no字段的添加内置到load_dataset中了

如果不使用load_dataset来加载和处理数据的话确实原始数据集和preprocess_mrc会有break，可能需要预先手动处理一下数据集

**Comment by PancakeAwesome** [comment]
> > utils.py 中
> > ```python
> > for qid, question, answers in zip(qas["question_id"],
> >                                               qas["question"], qas["answers"]):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成
> > ```python
> > for d in qas:
> >      qid = d["question_id"]
> >      question = d["question"]
> >      answers = d["answers"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 才能运行
> 
> Hi，这部分处理以及page_no字段的添加内置到load_dataset中了
> 
> 如果不使用load_dataset来加载和处理数据的话确实原始数据集和preprocess_mrc会有break，可能需要预先手动处理一下数据集
我也遇到了同样的问题。如果使用官方数据集直接运行docvqa的微调命令。会出现
`feat["bbox"] = feat["bbox"] + [[0, 0, 0, 0] for _ in range(self.max_length - len(feat["bbox"]))] KeyError: 'bbox'`
的错误。这一块，是否是需要处理脚本处理一遍官方的数据集呢？ https://github.com/PaddlePaddle/PaddleNLP/issues/7145

**Comment by PancakeAwesome** [comment]
> > utils.py 中
> > ```python
> > for qid, question, answers in zip(qas["question_id"],
> >                                               qas["question"], qas["answers"]):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改成
> > ```python
> > for d in qas:
> >      qid = d["question_id"]
> >      question = d["question"]
> >      answers = d["answers"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 才能运行
> 
> Hi，这部分处理以及page_no字段的添加内置到load_dataset中了
> 
> 如果不使用load_dataset来加载和处理数据的话确实原始数据集和preprocess_mrc会有break，可能需要预先手动处理一下数据集

我也遇到了同样的问题。如果使用官方数据集直接运行docvqa的微调命令。会出现
feat["bbox"] = feat["bbox"] + [[0, 0, 0, 0] for _ in range(self.max_length - len(feat["bbox"]))] KeyError: 'bbox'
的错误。这一块，是否是需要处理脚本处理一遍官方的数据集呢？ https://github.com/PaddlePaddle/PaddleNLP/issues/7145
