### ISSUE TITLE
PaddleNLP/model_zoo/uie/deploy/python/infer_gpu.py 

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#3829]
### 问题描述

infer_gpu.py 里面能配置能有use_fast的参数实现加速吗？
use_fast: 使用C++实现的高性能分词算子FastTokenizer进行文本预处理加速。需要通过pip install fast_tokenizer安装FastTokenizer库后方可使用。默认为False。更多使用说明可参考[FastTokenizer文档](https://gitee.com/AI-Mart/PaddleNLP/blob/develop/fast_tokenizer)。

self._tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh"，  use_fast=True)是这样配置吗？

**Comment by AI-Mart** [comment]
我看官方infer_gpu.py代码没有这个参数配置？

**Comment by wawltor** [comment]
> 我看官方infer_gpu.py代码没有这个参数配置？

这里主要是相关配置在UIE上还不是特别稳定，也可以直接修改试试 
https://github.com/PaddlePaddle/PaddleNLP/blob/4f56bafdbf6848930700b7d4ae8619158d486bc4/model_zoo/uie/deploy/python/uie_predictor.py#L96

**Comment by AI-Mart** [comment]
> > 我看官方infer_gpu.py代码没有这个参数配置？
> 
> 这里主要是相关配置在UIE上还不是特别稳定，也可以直接修改试试
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/4f56bafdbf6848930700b7d4ae8619158d486bc4/model_zoo/uie/deploy/python/uie_predictor.py#L96

不稳定指的是？能不能产业上落地使用呢？
我看taskflow是有这个参数的哦
 ie = Taskflow('information_extraction',
                  schema="",
                  schema_lang="zh",
                  batch_size=1,
                  model='uie-base',
                  position_prob=0.5,
                  precision='fp32',
                  use_fast=False)

如果不稳定那就不敢产业化使用了哈，如果是漏掉参数了，官方的可以补上去。

**Comment by wawltor** [comment]
> > > 我看官方infer_gpu.py代码没有这个参数配置？
> > 
> > 
> > 这里主要是相关配置在UIE上还不是特别稳定，也可以直接修改试试
> > https://github.com/PaddlePaddle/PaddleNLP/blob/4f56bafdbf6848930700b7d4ae8619158d486bc4/model_zoo/uie/deploy/python/uie_predictor.py#L96
> 
> 不稳定指的是？能不能产业上落地使用呢？ 我看taskflow是有这个参数的哦 ie = Taskflow('information_extraction', schema="", schema_lang="zh", batch_size=1, model='uie-base', position_prob=0.5, precision='fp32', use_fast=False)
> 
> 如果不稳定那就不敢产业化使用了哈，如果是漏掉参数了，官方的可以补上去。

目前不是特别稳定，两边实现稍微有点区别，但是最终指标结果没有影响（有个别case有影响），你可以测试一下在自己的场景的影响

**Comment by AI-Mart** [comment]
那还是你们弄稳定再产业化使用了，毕竟这个参数是一键配置的，调用的底层代码，感谢回复

**Comment by wawltor** [comment]
好的
