### ISSUE TITLE
[Question]: faster tokenizer的使用方法

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/PaddleNLP#3830]
### 请提出你的问题

Hi，我看到faster tokenizer提供了不同的使用方式，我有一些疑惑：
README提供了一个ErnieFastTokenizer的示例。另外 `fast_tokenizer/perf/perf.py`这里也有一个对比huggingface性能的例子
前者用的是
```
import fast_tokenizer
from fast_tokenizer import ErnieFastTokenizer, models
```
后者用的是
```
from paddlenlp.experimental import FastTokenizer
```
这两个区别是什么呢。
前一种方法output包含了ids, type_ids, tokens, offsets, attention_mask
后一种方法只能输出input_ids, token_type_ids。

我自己测试用这两种方法处理同一个大文本，速度相差几倍。

请问这两种方法的实现有什么区别呢？ 后者能否也输出tokens (wordpieces)

**Comment by Wong4j** [comment]
补充一点，前者似乎只能输入一个string，后者可以传入包含多个string的tensor。

**Comment by joey12300** [comment]
@Wong4j 前者也能输入多个string，并且前者的功能齐全。前者是支持输出`offsets`，阅读理解任务是依赖`offsets`信息的。换句话说，fast_tokenizer库提供的`ErnieFastTokenizer`是几乎覆盖所有任务，而`paddlenlp.experimental. FastTokenizer `只支持文本分类任务、序列标注任务，并且输出只有`input_ids`, `token_type_ids`，无法输出`tokens`。

至于性能这一块，你是怎么测试具体的性能呢？

**Comment by Wong4j** [comment]
输入多个string是指的encode_batch吗？似乎可以输入一个list of string.

我的测试方法：
将一个wikipedia的文本按行读取，比如有100万行，`input`就是一个含有100万个string的list
```
vocab = models.WordPiece.read_file("bert-large-uncased-vocab.txt")
tokenizer = ErnieFasterTokenizer(vocab, max_sequence_len=128)
for s in input:
    output = tokenizer.encode(s)
```

```
from paddlenlp.experimental import FasterTokenizer, to_tensor
tokenizer = FasterTokenizer.from_pretrained("bert-large-uncased")
input_tensor = to_tensor(input)
output = tokenizer(input_tensor, max_seq_len=128)
```

后者比前者快3倍多。我猜是不是两种方法中`input_ids`和`token_type_ids`是调用的相同的c++实现来计算的，但是前者多了额外的tokens, mask等输出，使用python实现所以开销多了很多？

**Comment by joey12300** [comment]
> 输入多个string是指的encode_batch吗？似乎可以输入一个list of string.
> 
> 我的测试方法： 将一个wikipedia的文本按行读取，比如有100万行，`input`就是一个含有100万个string的list
> 
> ```
> vocab = models.WordPiece.read_file("bert-large-uncased-vocab.txt")
> tokenizer = ErnieFasterTokenizer(vocab, max_sequence_len=128)
> for s in input:
>     output = tokenizer.encode(s)
> ```
> 
> ```
> from paddlenlp.experimental import FasterTokenizer, to_tensor
> tokenizer = FasterTokenizer.from_pretrained("bert-large-uncased")
> input_tensor = to_tensor(input)
> output = tokenizer(input_tensor, max_seq_len=128)
> ```
> 
> 后者比前者快3倍多。我猜是不是两种方法中`input_ids`和`token_type_ids`是调用的相同的c++实现来计算的，但是前者多了额外的tokens, mask等输出，使用python实现所以开销多了很多？

你可以尝试使用 `tokenizer.encode_batch(input)` 替代`encode`方法，避免对每个string进行循环。

### 开销分析
前者主要多了offset计算。Tokenizer在切分前，会对原始文本进行一些文本预处理（如大小写转换，NFC转换等），在这个阶段，前者会记录原始offset的位置，每对一个字符做转换，都会记录一次offset位置，这带来了额外开销。所以在处理相同长度、批次的文本时，前者会有一定的额外开销。

### 优化建议
目前fast_tokenizer完成了一些升级，可以`pip install fast-tokenizer-python`安装最新版本的`fast_tokenizer`。针对批量的文本分词，可以通过多线程方式加速分词，可以调用`fast_tokenizer.set_thread_num(xxx)`方式设置线程数完成加速。可以参考以下代码：

```
import fast_tokenizer
from fast_tokenizer import ErnieFastTokenizer, models

# 设置8线程加速
fast_tokenizer.set_thread_num(8)
vocab = models.WordPiece.read_file("bert-large-uncased-vocab.txt")
tokenizer = ErnieFastTokenizer(vocab, max_sequence_len=128)

output = tokenizer.encode_batch(input)
```
