### ISSUE TITLE
paddle serving部署服务启动报错TypeError: can't pickle _thread.lock objects[Question]: 

### ISSUE THREAD

**Issue by wangtiehu** [PaddlePaddle/PaddleNLP#3832]
### 请提出你的问题

您好！我在使用D:\PaddleNLP-develop\applications\text_classification\multi_class\deploy\paddle_serving部署方案时，根据教程启动python service.py 一直报错TypeError: can't pickle _thread.lock objects和EOFError: Ran out of input
操作系统：windows10 
python 3.7
paddle-serving-app        0.9.0
paddle-serving-client     0.9.0
paddle-serving-server     0.9.0
paddle-serving-server-gpu 0.9.0.post1028
paddle2onnx               1.0.1
paddlefsl                 1.1.0
paddlenlp                 2.4.2
paddlepaddle-gpu          2.3.2.post111
尝试了很多次，都没成功启动服务，麻烦看一下问题出在哪里？

**Comment by wawltor** [comment]
PaddleServing目前在windows的不太好，我们新增了一个PaddleNLP Serving的功能，相对比较简易 

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/SimpleServing 

可以安装一下最新PaddleNLP的develop版本，可以尝试一下这个功能

**Comment by wangtiehu** [comment]
您好！最新的paddlenlp我只找到2.4.3，依旧有报错！请问2.4.4的在哪里下载呢

**Comment by lugimzzz** [comment]
安装一下paddlenlp的develop版本

**Comment by wangtiehu** [comment]
确实是下载的PaddleNLP-develop.zip，然后pip install paddlenlp==2.4.4,提示最新版本2.4.3，用了2.4.3报错ModuleNotFoundError: paddlenlp-cli tools is not installed correctly, you can use the following command to install paddlenlp cli tool: >>> pip install paddlenlp[cli]

**Comment by wawltor** [comment]
> 确实是下载的PaddleNLP-develop.zip，然后pip install paddlenlp==2.4.4,提示最新版本2.4.3，用了2.4.3报错ModuleNotFoundError: paddlenlp-cli tools is not installed correctly, you can use the following command to install paddlenlp cli tool: >>> pip install paddlenlp[cli]

是否可以加一些我们的微信群然后@ 泽阳，我们来指导如何来使用，这个还是一个非稳定问题，有些问题在里面

**Comment by wangtiehu** [comment]
好的，非常感谢！
