### ISSUE TITLE
[Question]:  Extracting Table from multiple pages in PDFs

### ISSUE THREAD

**Issue by stefanqxb** [PaddlePaddle/PaddleNLP#3842]
### 请提出你的问题

Hi there,
    As of now, in some of our cases, we need to extract some tables from PDF, and a table might actually be crossed two pages, so in this case, the origin Paddle doesnt support pdf as input as I known, so is there a way to take pdf as input?  thanks a lot for the help.

Brs
Bin

**Comment by w5688414** [comment]
Hi, @stefanqxb which PaddleNLP application are you using?

**Comment by stefanqxb** [comment]
Hi @w5688414 , 
     Im currently using paddleocr and ppstructure for table detection purpose

**Comment by stefanqxb** [comment]
Any updates on this ticket ??
