### ISSUE TITLE
[Question]: DocPrompt 中 OCR 结果的格式

### ISSUE THREAD

**Issue by minlik** [PaddlePaddle/PaddleNLP#3848]
### 请提出你的问题

在 DocPrompt 中，可以传入自定义的 OCR 结果：
> 默认使用PaddleOCR进行OCR识别，同时支持用户通过word_boxes传入自己的OCR结果，格式为List[str, List[float, float, float, float]]。

其中，四个坐标 List[float, float, float, float] 分别是代表什么含义？是左上右下的顺序(x_1, y_1, x_2, y_2)吗？是否进行了归一化处理？

**Comment by linjieccc** [comment]
Hi, @minlik 

word_boxes表示的是左下右上的坐标 x1, y1, x2, y2，不需要进行normalize，normalize的过程内置在Taskflow中了

**Comment by minlik** [comment]
> Hi, @minlik
> 
> word_boxes表示的是左下右上的坐标 x1, y1, x2, y2，不需要进行normalize，normalize的过程内置在Taskflow中了

感谢🙏
