### ISSUE TITLE
[Question]: Docprompt可以返回topk的answers吗

### ISSUE THREAD

**Issue by NaivePawn** [PaddlePaddle/PaddleNLP#3849]
### 请提出你的问题

Docprompt可以返回topk的answers吗

**Comment by lugimzzz** [comment]
可以通过配置topn返回topk answers，docprompt = Taskflow("document_intelligence",topn=3)
![image](https://user-images.githubusercontent.com/63761690/203062848-81508ebf-d2ab-4344-957b-db2fff0400d1.png)

**Comment by NaivePawn** [comment]
感谢！看到了，但是我设置topn=5，只返回2个answer，中间是有阈值卡了吗？

**Comment by lugimzzz** [comment]
是，设置的阈值是0.5

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有问题可以再次打开。

**Comment by tianchiguaixia** [comment]
在哪修改这个阈值0.5
