### ISSUE TITLE
[Question]: how to change the keyword 'sks' as it would pollute data

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#3852]
### 请提出你的问题

lab: ppdiffusers, dreambooth
The 'sks' is the fixed point in dreambooth, we may use the sentence "a photo of sks {keyword}" for models' fine tuning, but the 'sks' is also know of a kind of semi-automatic rifle ref: https://en.wikipedia.org/wiki/SKS, our results might be polluted by the images of gun, and with the increasing of epochs, the result would be more probable generated as some kinds of wired machine gun instead of what we pointed

So, how can I change the keyword 'sks' in ppdiffusers to avoid this pollution? ref: https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/blob/main/ldm/data/personalized.py#L10

**Comment by JunnYu** [comment]
或许我们可以跟`textual_inversion`一样。
- 先创建个独一无二的单词https://github.com/PaddlePaddle/PaddleNLP/blob/eeb5cfeed5a2adc91b41d90063b8b3efbe585b9f/ppdiffusers/examples/textual_inversion/train_textual_inversion.py#L475
- 再使用这个单词一起训练https://github.com/PaddlePaddle/PaddleNLP/blob/eeb5cfeed5a2adc91b41d90063b8b3efbe585b9f/ppdiffusers/examples/textual_inversion/train_textual_inversion.py#L505
当训练的越来越久，我反而感觉图片会忘记`sks`原来的含义（可以理解成过拟合）。

**Comment by godlockin** [comment]
用 placeholder_token 是可以，但是如果我需要指定多个（上千/上万）这种 token 就会很麻烦，不是个特别好的方案感觉

dreambooth原版里面是存在'sks'替换的能力的，不过不知道被封装到哪去了，是根据他的思路重写了整个逻辑吗？
