### ISSUE TITLE
[Question]: backbone模型从ernie2.0换为albert后，训练打印出所有层梯度为0，参数不更新，损失不下降

### ISSUE THREAD

**Issue by canghongjian** [PaddlePaddle/PaddleNLP#3854]
### 请提出你的问题

backbone模型从ernie2.0换为albert-xxlarge-v2后，训练打印出所有层梯度为0，参数不更新，损失不下降

**Comment by canghongjian** [comment]
backward后打印出子任务损失的梯度如下，全为1：
<img width="568" alt="image" src="https://user-images.githubusercontent.com/34473193/203231802-f4633215-9250-4eec-b13d-08ec45f4de03.png">
backward后打印出参与损失计算的中间量的梯度如下,看起来较为正常：
<img width="799" alt="image" src="https://user-images.githubusercontent.com/34473193/203232325-4a509e02-ff87-45d6-8257-5b85c7e5fa4c.png">
<img width="800" alt="image" src="https://user-images.githubusercontent.com/34473193/203232347-c9e7fa5b-80dd-48c1-ac74-84c33a5c0807.png">

**Comment by canghongjian** [comment]
换成electra-large也有同样的问题。目前看来只有ernie-2.0能够正常训练，但是效果也比我此前用pytorch和transformers的debert-v3-large低了六七个点。

**Comment by wawltor** [comment]
想问一下 具体用了哪个应用了？

**Comment by canghongjian** [comment]
> 想问一下 具体用了哪个应用了？

用的AlbertModel，取outputs[0]

**Comment by wawltor** [comment]
> > 想问一下 具体用了哪个应用了？
> 
> 用的AlbertModel，取outputs[0]

有具体的代码吗？

**Comment by canghongjian** [comment]
> > > 想问一下 具体用了哪个应用了？
> > 
> > 
> > 用的AlbertModel，取outputs[0]
> 
> 有具体的代码吗？

有，不过我的代码可能没法在这公开，再加上包括数据处理可能解释起来比较麻烦，能否私聊呢？如流zhangjiahao08或微信canghongjianzjh
