### ISSUE TITLE
怎么使用ERNIE-GEN模型进行对话任务

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleNLP#3862]
### 请提出你的问题

https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-gen 这个仓库里说ernie-gen能够用于多轮对话，但是没找到怎么使用的文档，请问这里有人知道吗

**Comment by gongel** [comment]
可以参考这里：https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie-gen/run_seq2seq.py#L59
另外也可以直接使用plato哈：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/

**Comment by oyb1125** [comment]
> 可以参考这里：https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie-gen/run_seq2seq.py#L59 另外也可以直接使用plato哈：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/dialogue/plato-2/

这两个模型那个更好呀

**Comment by gongel** [comment]
> 

第二个呢
