### ISSUE TITLE
[Bug]: fast_tokenizer遇到GLIBCXX_3.4.20 not found 问题

### ISSUE THREAD

**Issue by barrierye** [PaddlePaddle/PaddleNLP#3866]
### 软件环境

```Markdown
与Paddle环境无关，仅使用fast_tokenizer
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
跑fast_tokenizer README，遇到如下报错：
[root@bfd2b0147273 work]# python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import fast_tokenizer
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/fast_tokenizer/__init__.py", line 21, in <module>
    from . import core_tokenizers as C
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/fast_tokenizer/core_tokenizers.so)

本地gcc版本9.3.1，满足编译文档中gcc版本要求。
求问如何在不动环境的条件下解决？尝试基于repo安装whl包：pip install git+https://github.com/PaddlePaddle/PaddleNLP.git@v2.4.3#subdirectory=fast_tokenizer ，但貌似只跑了setup.py没有跑C++编译部分
```

### 稳定复现步骤 & 代码

pip install fast-tokenizer-python==1.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
执行README中的代码
```
import fast_tokenizer
from fast_tokenizer import ErnieFastTokenizer, models

# 0.（可选）设置线程数
fast_tokenizer.set_thread_num(1)
# 1. 加载词表
vocab = models.WordPiece.read_file("ernie_vocab.txt")
# 2. 实例化ErnieFastTokenizer对象
fast_tokenizer = ErnieFastTokenizer(vocab)
# 3. 切词
output = fast_tokenizer.encode("我爱中国")
# 4. 输出结果
print("ids: ", output.ids)
print("type_ids: ", output.type_ids)
print("tokens: ", output.tokens)
print("offsets: ", output.offsets)
print("attention_mask: ", output.attention_mask)
```

**Comment by barrierye** [comment]
本地libstdc++是4.8.5 ...

**Comment by barrierye** [comment]
core_tokenizers.so 可以做成静态编译吗：）

**Comment by joey12300** [comment]
> core_tokenizers.so 可以做成静态编译吗：）

你好，请问你的linux版本是多少呢？输入`ldd --version`看看glibc版本

**Comment by barrierye** [comment]
> > core_tokenizers.so 可以做成静态编译吗：）
> 
> 你好，请问你的linux版本是多少呢？输入`ldd --version`看看glibc版本

ldd (GNU libc) 2.17
用patchelf链接到高版本的libstdc++是可以使用的，但建议还是做成静态链接比较好...

**Comment by joey12300** [comment]
> > > core_tokenizers.so 可以做成静态编译吗：）
> > 
> > 
> > 你好，请问你的linux版本是多少呢？输入`ldd --version`看看glibc版本
> 
> ldd (GNU libc) 2.17 用patchelf链接到高版本的libstdc++是可以使用的，但建议还是做成静态链接比较好...

感谢建议哈。还想问一下你的Linux是Ubuntu 16吗？这个fast_tokenizer是在Centos 7上编译的，在Centos平台应该不会有问题。Ubuntu的话我们再进一步验证一下兼容性。

**Comment by barrierye** [comment]
> > > > core_tokenizers.so 可以做成静态编译吗：）
> > > 
> > > 
> > > 你好，请问你的linux版本是多少呢？输入`ldd --version`看看glibc版本
> > 
> > 
> > ldd (GNU libc) 2.17 用patchelf链接到高版本的libstdc++是可以使用的，但建议还是做成静态链接比较好...
> 
> 感谢建议哈。还想问一下你的Linux是Ubuntu 16吗？这个fast_tokenizer是在Centos 7上编译的，在Centos平台应该不会有问题。Ubuntu的话我们再进一步验证一下兼容性。

是Centos 7噢。
```
[root@bfd2b0147273 work]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
```
