### ISSUE TITLE
UIE模型蒸馏数据量问题

### ISSUE THREAD

**Issue by everzhou** [PaddlePaddle/PaddleNLP#3868]
### 请提出你的问题

关于UIE数据蒸馏， 示例的数据包里doccano_ext.json数据200条， unlabeled_data.txt是 1277 条。这个蒸馏用的数据量还是比较大的，需要很多时间整理数据，而UIE 微调时只需要几条几十条数据就可以了。 请问我们进行蒸馏时，最低的数据量要求是多少 ？

**Comment by linjieccc** [comment]
Hi，

主要看Teacher Model的效果是否满足要求，标注数据量没有特别要求，几条标注数据UIE微调后的模型只要效果符合预期同样也可以作为Teacher Model
