### ISSUE TITLE
[Question]: 4.8模型部署是做什么工作的？

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#3876]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/109952192/203542776-1d7291d7-84b6-453f-9c67-1593db49fa0d.png)

你好，咨询一个问题
对4.8模型部署是做什么的不清楚，感谢赐教

**Comment by JunnYu** [comment]
主要是为了生产部署用的。
生产实践过程中用户可能没有gpu，需要使用cpu进行推理预测，这里的教程主要是为了产业落地而添加的。

**Comment by MachineSheep** [comment]
> 主要是为了生产部署用的。 生产实践过程中用户可能没有gpu，需要使用cpu进行推理预测，这里的教程主要是为了产业落地而添加的。

你好，请问这和我自己写api服务使用Taskflow调用模型进行预测有什么区别呢？

**Comment by JunnYu** [comment]
部署推理的后端有多种形式，比如可以用onnx模型推理，使用paddle inference推理，使用tensorrt推理，使用openvino推理，使用原生的torch动态图推理，使用paddle动态图推理，使用paddle静态图图推理，不同的推理方式速度是不同的。

自己写api服务：可以用flask，fastapi封装一下Taskflow服务，当然也可以封装其他东西。
Taskflow服务：是一种封装，我们对内部的一些细节都进封装，屏蔽了底层调用的很多逻辑，用户只需要关心输入和输出就可以了。
