### ISSUE TITLE
[Question]: UIE如何提取出症状的否定词？

### ISSUE THREAD

**Issue by razor365** [PaddlePaddle/PaddleNLP#3880]
### 请提出你的问题

请教下：
UIE large提取症状，在给定句子 ”未出现发热”。
使用schema=["症状“]，UIE正确提取出了”发热“症状，
那么如何提取否定词“未”？

**Comment by LemonNoel** [comment]
可以将schema改为[阳性症状，阴性症状]来微调得到结果，阳性对应出现的症状，阴性对应未出现的症状。

**Comment by razor365** [comment]
@LemonNoel 感谢感谢

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有问题可以再次打开issue。
