### ISSUE TITLE
[Question]: 使用uie的doccano生成训练集时，部分实体无内容

### ISSUE THREAD

**Issue by lddcdut** [PaddlePaddle/PaddleNLP#3882]
### 请提出你的问题

如下，这些文本里面没有实体标签的内容，是不是应该去掉，不去掉会不会影响训练效率
`{"content": "上海到北京机票1320元", "result_list": [], "prompt": "时间"}

{"content": "昨天晚上十点加班打车回家58元", "result_list": [], "prompt": "出发地"}

{"content": "从合肥到北京高铁两百元", "result_list": [], "prompt": "时间"}`

**Comment by linjieccc** [comment]
Hi，

这些是标注数据到训练数据转换阶段自动构造的负例，UIE中负例的介绍可以参考下这篇文章 https://zhuanlan.zhihu.com/p/564033319
