### ISSUE TITLE
[Question]: 包含特殊字符时，在tokenize阶段就miss掉了，可不可以扩展一下

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/PaddleNLP#3893]
### 请提出你的问题

测试代码如下：
```
from paddlenlp.transformers import AutoTokenizer
model_name = "ernie-3.0-medium-zh"
tokenizer = AutoTokenizer.from_pretrained(model_name)
txt = "看𝗿𝟯𝟭𝟵.se"
result = tokenizer.tokenize(text=txt, max_seq_len=128)
print(result)
#['看', '[UNK]', '.', 'se']`
```

这个字符串在这个[网站编码：](http://www.mytju.com/classcode/tools/encode_utf8.asp)
![1669283238375](https://user-images.githubusercontent.com/8412025/203751902-a5ca04cd-6c8a-4046-9328-c24cb7b5e0a9.png)

**Comment by wj-Mcat** [comment]
上面是符合预期输出的，因为tokenizer 总是会遇到一些不认识[unk]的字符，不仅仅是全角半角，多语言中也会存在很多其它的特殊字符，它们在 vocab 当中都是不存在的，所以只能够识别为`unk`，如果要扩展的话，开发者可自行扩展：

```python
tokenizer.add_tokens(...)
```

你只需要自行扩展即可。 @thomaszheng

**Comment by thomaszheng** [comment]
在python端这样扩展导出后词典，java加载词表后转换发现这个字符串java看到的字符和python看到的字符不一致的情况（都是utf8编码），这个有问题解决吗？

**Comment by wj-Mcat** [comment]
你这里的 utf-8 编码应该只是文件编码，有可能还需要把内容给转码一遍才行。

如果你能够把词典导出前、导出后、java 加载后的字符都复制到这里来，对照着确切的字符串来聊，我相信问题会更清晰，不然很可能会造成无效沟通，你觉得呢？ @thomaszheng
