### ISSUE TITLE
[Question]: ernie-health spo抽取任务中，如何使用自定义finetune数据？

### ISSUE THREAD

**Issue by lichuanxiang** [PaddlePaddle/PaddleNLP#3895]
### ernie-health spo抽取任务中，目前看是直接调用函数获取的CMeIE的数据，想问下如何输入自定义的finetune数据呢？

![image](https://user-images.githubusercontent.com/10071850/203834683-e430850f-cfb4-48c4-9cd9-db5b625578e0.png)

**Comment by LemonNoel** [comment]
更换为自定义数据集包括两部分，一个是数据读取，一个是数据预处理

**数据读取**可以参考[自定义数据集文档](https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html)，主要是根据自己的数据文件格式写一个读取函数，然后调用 paddlenlp.datasets.load_dataset得到数据集。

**数据预处理**可以参考下 `utils.py` 文件里[这个函数和注释](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-health/cblue/utils.py#L214-L253)，仿照着用自定义数据生成`input_ids`, `token_type_ids`, `position_ids`, `attention_mask`, `ent_label` (optional), `spo_label` (optional)，替换掉这个函数；或者不想修改预处理代码，可以写脚本将自定义数据改成和`CMeIE`一样的格式，具体格式如下
```
{"text": "训练文本", "spo_list": [{"Combined": false, "predicate": "关系", "subject": "主语实体", "subject_type": "主语实体类别", "object": {"@value": "宾语实体"}, "object_type": {"@value": "宾语实体类别"}}]}

{"text": "胆囊炎@如果胆囊穿孔，死亡率为 30%。", "spo_list": [{"Combined": false, "predicate": "死亡率", "subject": "胆囊穿孔", "subject_type": "疾病", "object": {"@value": "30%"}, "object_type": {"@value": "流行病学"}}]}
```
