### ISSUE TITLE
序列生成任务？

### ISSUE THREAD

**Issue by yangbin-Neil** [PaddlePaddle/PaddleNLP#3903]
### Feature request

请问一下目前paddlenlp中序列生成任务领域除了可以用LSTM组件seq2seq，还有没有其他更好的选择。

### Motivation

准备利用序列生成任务做一些POI规范化方面的任务。

### Your contribution

.

**Comment by wawltor** [comment]
可以看看文本摘要的示例，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization 这个是用生成的模型来做文本生成

**Comment by yangbin-Neil** [comment]
但是但是，我的输出可能会比原始的输入要长。相比于输入，输出的结果会补充一些内容在里面。比如输入是“成都市青羊区”，我想让他输出“四川省成都市青羊区”，您说的这个文本生成可以完成类似的任务吗？

**Comment by wawltor** [comment]
> 但是但是，我的输出可能会比原始的输入要长。相比于输入，输出的结果会补充一些内容在里面。比如输入是“成都市青羊区”，我想让他输出“四川省成都市青羊区”，您说的这个文本生成可以完成类似的任务吗？

这个可以使用生成任务来试试，需要一定训练样本支持；不过这种任务更像是地域信息扩展，通过专业知识库扩展看起来更合适点

**Comment by yangbin-Neil** [comment]
好的，谢谢，那我先试试看吧。选择序列生成任务的原因就是没有专业的知识库（尴尬），才想试试其他的方法。
