### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#3905]
### 请提出你的问题

How to encode a "single word" as a single token after tokenizer's encoding? And even more, I need to inject some words linked by some symbol as a "single token"...

If not, the following issue would raise
```python
    # Convert the initializer_token, placeholder_token to ids
    token_ids = tokenizer.encode(args.initializer_token,
                                 add_special_tokens=False)["input_ids"]
    # Check if initializer_token is a single token or a sequence of tokens
    if len(token_ids) > 1:
        raise ValueError("The initializer token must be a single token.")
```
ref: [token_ids = tokenizer.encode(args.initializer_token,](https://github.com/PaddlePaddle/PaddleNLP/blob/14e6813c1e6aa8db170cf6932242230152471363/ppdiffusers/examples/textual_inversion/train_textual_inversion.py#L482)

The init token might be split into multiple tokens by mistake, e.g. [bookcase] -> [book, case] -> [2828, 2068], which we suppose to be a single token [bookcase] -> [ $some_id ].

I've tried: 
1. "bookcase" -> [book, case] -> [2828, 2068]
2. "book-case" -> [book, -, case] -> [1116, 268, 2068]
3. "[bookcase]" -> ['[', book, case, ']'] -> [314, 2828, 2068, 316]

**Comment by gongel** [comment]
你好，可以尝试增加special tokens来解决该问题，例如
```python
tokenizer = GPTTokenizer.from_pretrained('gpt2-en')
tokenizer.add_tokens(['godlockin'], True)
```

**Comment by godlockin** [comment]
it works, and also support Chinese terms, cheers
