### ISSUE TITLE
[Bug]: UIE文档有误

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/PaddleNLP#3907]
```Markdown
UIE 模型微调时，没有生成对应的inference模型
```

### 稳定复现步骤 & 代码

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/14270174/204002380-dc2701c7-8b62-4ce9-939f-653ddcbd2cca.png">

**Comment by gongel** [comment]
你好，也欢迎你这边提供PR修复哈，一起参与开源共现！

**Comment by wawltor** [comment]
已修复文档

**Comment by littletomatodonkey** [comment]
你好，我的意思是，按照文档操作，uie finetune的时候，并没有生成对应的inference模型哈，不知道是不是动转静要设置其他的参数？

**Comment by wawltor** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/16698950/204135561-22e9f91f-1758-464a-98f0-4b39f0626b51.png">
目前是会自动导出静态图inference模型
