### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by xinsheng44** [PaddlePaddle/PaddleNLP#3909]
### 请提出你的问题

您好，我在测试docprompt遇到以下问题：

测试代码：
`from paddlenlp import Taskflow
docprompt = Taskflow("document_intelligence", model='docprompt')
t = docprompt({"doc": "data/202111121508044287654.pdf", "prompts": ["甲方是谁"]})
print(1)
`

依赖包版本：
`paddle2onnx               1.0.3                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.4.3                    pypi_0    pypi
paddleocr                 2.5.0.3                  pypi_0    pypi
paddlepaddle-gpu          2.2.2                    pypi_0    pypi
paddleslim                2.2.1                    pypi_0    pypi
`

报错：
`  File "test.py", line 8, in <module>
    from paddlenlp import Taskflow
  File "/data/anaconda3/envs/wxs_paddle/lib/python3.7/site-packages/paddlenlp/__init__.py", line 36, in <module>
    from . import trainer
  File "/data/anaconda3/envs/wxs_paddle/lib/python3.7/site-packages/paddlenlp/trainer/__init__.py", line 18, in <module>
    from .trainer import *
  File "/data/anaconda3/envs/wxs_paddle/lib/python3.7/site-packages/paddlenlp/trainer/trainer.py", line 43, in <module>
    from paddle.distributed.sharding import group_sharded_parallel
ModuleNotFoundError: No module named 'paddle.distributed.sharding'`

**Comment by gongel** [comment]
你好，可以使用develop版本哈，我们已经修复该问题：https://github.com/PaddlePaddle/PaddleNLP/pull/3831
