### ISSUE TITLE
[Question]: 使用uie官方实例代码时报错，无结果返回

### ISSUE THREAD

**Issue by 61liuyi61** [PaddlePaddle/PaddleNLP#3910]
### 请提出你的问题

from pprint import pprint
from paddlenlp import Taskflow

schema = [{"歌曲名称": ["歌手", "所属专辑"]}, "人物"]
ie = Taskflow('information_extraction', schema=schema)
res = ie("告白气球是周杰伦在专辑周杰伦的床边故事里面的歌曲")
pprint(res)

![image](https://user-images.githubusercontent.com/46638017/204078423-826db544-e23d-4eb2-9902-cf0f7800d451.png)

其中：
python 3.7.4
paddlenlp 2.4.3

**Comment by wawltor** [comment]
看起来是windows机器，scipy的版本，需要满足 scipy<=1.3.1 & scipy>=1.7.3  
看看是否能解决你的问题
