### ISSUE TITLE
Pipelines能否提供通用的对用户调查问卷的自动QA对提取

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PaddleNLP#3913]
### Feature request

比如说你会收到从市场上不同调查公司发过来调查问卷，那不同公司，它肯定用他们自己的格式，但是总的来说，它还是会以一种问题答案的形式这样来展示对不对，但是，它很可能它的标号，标识，就是这种问题答案对，并不是完全用统一的方式，因为每个公司格式不一样，那么，怎么能够自动的在这个文档中把这些问题答案给切割出来

### Motivation

调查问卷中的QA对提取的通用方法

### Your contribution

User advice

**Comment by wj-Mcat** [comment]
如果是调查问卷的话，最终都会导出为一个 excel表格，此时thead 即为question，tbody即为answer，所以在抽取上而言可通过规则来。

此外，如果能够实现：识别那些是 question 描述，我相信调查问卷导出的表格数据可实现自动 QA 提取。
