### ISSUE TITLE
[Question]: InvalidArgumentError: input and filter data type should be consistent, but received input data type is int64_t and filter type is float       [Hint: Expected input_data_type == filter_data_type, but received input_data_type:3 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:209)       [operator < conv2d > error]

### ISSUE THREAD

**Issue by xinsheng44** [PaddlePaddle/PaddleNLP#3915]
### 请提出你的问题

我主要想测试
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout

具体操作如下：

我通过Taskflow下载了相应的docprompt的模型文件：
![image](https://user-images.githubusercontent.com/59272013/204123604-2d1cb8bb-1e02-4185-b10b-c3425b51be4d.png)

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/infer.py
然后我更改了infer.py里面的部分参数，将测试用例改成了自己的数据文件。
具体如下
`
   
    import argparse
    import collections
    import paddle
    
    from predictor import Predictor
    
    
    def parse_args():
        # yapf: disable
        parser = argparse.ArgumentParser()
        # Required parameters
        parser.add_argument("--model_path_prefix",  default="model/static/inference", type=str, help="The path prefix of inference model to be used.")
        parser.add_argument("--batch_size", default=4, type=int, help="Batch size per GPU for inference.")
        parser.add_argument("--max_seq_length", default=512, type=int, help="The maximum input sequence length. Sequences longer than this will be split automatically.")
        parser.add_argument("--task_type", default="ner", type=str, choices=["ner", "cls", "mrc"], help="Specify the task type.")
        parser.add_argument("--lang", default="ch", type=str, choices=["ch", "en"], help="Specify the task type.")
        parser.add_argument('--device', choices=['cpu', 'gpu'], default="gpu:2", help="Select which device to train model, defaults to gpu.")
        args = parser.parse_args()
        # yapf: enable
        return args
    
    
    def main():
        args = parse_args()
        docs_path = "data/202111121508044287654_1.jpg"
        if args.task_type == "mrc":
            args.questions = [
                [
                    "甲方是谁"
                ],
            ]
            docs = [docs_path]
        elif args.task_type == "cls":
            docs = [docs_path]
        elif args.task_type == "ner":
            docs = [docs_path]
        else:
            raise ValueError("Unspport task type: {}".format(args.task_type))
    
        predictor = Predictor(args)
    
        outputs = predictor.predict(docs)
        import pprint
        pprint.sorted = lambda x, key=None: x
        pprint.pprint(outputs)
    
    
    if __name__ == "__main__":
        main()
`

然后就报错
`

    Traceback (most recent call last):
      File "/data2/wangxinsheng/appstore/ernie-layout/infer.py", line 71, in <module>
        main()
      File "/data2/wangxinsheng/appstore/ernie-layout/infer.py", line 64, in main
        outputs = predictor.predict(docs)
      File "/data2/wangxinsheng/appstore/ernie-layout/predictor.py", line 878, in predict
        output = self.infer(input_dict)
      File "/data2/wangxinsheng/appstore/ernie-layout/predictor.py", line 854, in infer
        return self.inference_backend.infer(data)
      File "/data2/wangxinsheng/appstore/ernie-layout/predictor.py", line 65, in infer
        self.predictor.run()
    ValueError: In user code:
    
        File "models/save_infermodel.py", line 32, in <module>
          phase="infer")
        File "./src/multi_task_models/extract_model.py", line 154, in create_model
          body_feats_feature = model.net(image)
        File "./src/model/image_model/resnet.py", line 69, in net
          data_format=data_format)
        File "./src/model/image_model/resnet.py", line 145, in conv_bn_layer
          data_format=data_format)
        File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1714, in conv2d
          "data_format": data_format,
        File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
          return self.main_program.current_block().append_op(*args, **kwargs)
        File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3582, in append_op
          attrs=kwargs.get("attrs", None))
        File "/home/work/zhangdan20/opensource/DocPrompt/py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2596, in __init__
          for frame in traceback.extract_stack():
    
        InvalidArgumentError: input and filter data type should be consistent, but received input data type is int64_t and filter type is float
          [Hint: Expected input_data_type == filter_data_type, but received input_data_type:3 != filter_data_type:5.] (at /paddle/paddle/fluid/operators/conv_op.cc:209)
          [operator < conv2d > error]
`

上述问题在这个地方也有人提到过，我跟这个哥们的问题一模一样，有人解答是输入数据格式的问题https://github.com/PaddlePaddle/PaddleNLP/issues/3596

其实整体就是这样一个过程，我下载好docprompt的相关模型，然后想测试自己的图片文件，然而实际预测的时候却显示数据格式不一致的错误。我想问的是，我应该怎样做才能保证数据格式能符合已经下载模型文件的数据格式呢？毕竟，我输入的是一张图片，不是一个几维的矩阵，没有具体的数据格式，中间如何解析图片都是用库中自带的代码。

**Comment by linjieccc** [comment]
@wxs-newboy Hi，

docprompt不支持在如下脚本中替换静态图模型文件的形式进行预测，
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/infer.py

如果需要测试自己的图片建议使用``Taskflow("document_intelligence")``

**Comment by xinsheng44** [comment]
@linjieccc 

感谢回答，请问，如果我不使用Taskflow("document_intelligence")，我想使用基于infer.py进行预测的话，只能自己进行微调吗？不能直接使用百度大大训好的模型吗
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/infer.py
