### ISSUE TITLE
[Question]: 模型下载进度条不显示网速

### ISSUE THREAD

**Issue by gongel** [PaddlePaddle/PaddleNLP#3930]
### 请提出你的问题

最新代码走的是`get_path_from_url_with_filelock`, 缺少了之前显示网速的部分：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/downloader.py#L246-L252

Influenced by #3788

**Comment by wj-Mcat** [comment]
在目前 develop 分支中，底层的下载方法是使用 paddle.utils.download方法，并不是`paddlenlp.utils.downloader`中的方法。

不过网速应该还会显示，只不过是显示的bit/s（来自于 paddle.utils.download）的吧，具体可见：

<img width="956" alt="image" src="https://user-images.githubusercontent.com/10242208/205069103-6069f3da-73b4-4457-aa39-371ec7ce86ca.png">

在新的分支当中会切换到paddlenlp.utils.downloader的方法，此时会显示比较友好的网速：
<img width="934" alt="image" src="https://user-images.githubusercontent.com/10242208/205069433-32fde60c-d546-4c3d-b214-a85be7f76aab.png">

详细可见： https://github.com/PaddlePaddle/PaddleNLP/pull/3965

**Comment by gongel** [comment]
Nice job!
