### ISSUE TITLE
[Question]: ernie-3.0量化模型推理报错: segmentataion fault

### ISSUE THREAD

**Issue by tianjiahao** [PaddlePaddle/PaddleNLP#3931]
### 请提出你的问题

环境：
paddlenlp：2.4.3
paddleslim：1.0.0
paddlepaddle-gpu:2.3.0
问题：
进行ernie-3.0分类任务加速时，进行模型裁剪+量化，模型加速转换正常，进行infer推理时候，裁剪模型推理正常，量化模型推理报错：segmentation fault
执行命令： python3 infer.py --model_path ./out/width_mult_0.75/KL16_1/int8
mse模型也是同样的segmentation fault错误

**Comment by LemonNoel** [comment]
辛苦贴下具体的报错日志

**Comment by LiuChiachi** [comment]
请问你的机器的cuda版本是？使用的是paddle2onnx+onnx推理还是paddle inference+trt呢

**Comment by tianjiahao** [comment]
> 辛苦贴下具体的报错日志
![Rong_Image_1669686081606](https://user-images.githubusercontent.com/39933745/204417878-4c36f2e6-a5cc-4065-b609-65fff460616d.jpeg)
![Uploading Rong_Image_1669686078878.jpeg…]()

**Comment by tianjiahao** [comment]
> 请问你的机器的cuda版本是？使用的是paddle2onnx+onnx推理还是paddle inference+trt呢

cuda11.2,cudnn8.1,用的是paddle inference

**Comment by LiuChiachi** [comment]
你好，日志里你截图的部分没有报错呀。是不是在下面？

**Comment by tianjiahao** [comment]
> 
![2](https://user-images.githubusercontent.com/39933745/204516906-9741a46d-b3f1-43c8-8538-428f64ace53e.jpg)

**Comment by tianjiahao** [comment]
> 你好，日志里你截图的部分没有报错呀。是不是在下面？

更新一下日志，错误见上图
