### ISSUE TITLE
[Question]: 评估指标的优化等三个问题

### ISSUE THREAD

**Issue by yangbin-Neil** [PaddlePaddle/PaddleNLP#3932]
### 请提出你的问题

问题一：请问飞桨有没有提供实体级别的评估方法。我目前在做命名实体识别任务，我想将以字级别的评估改为以实体级别的评估，但是没有找到相应的案例，请问可以提供一下吗？

问题二：我对预训练模型进行了微调，但是使用该模型时为什么每次预测的结果不一样，预测一次变一次，之前是不变的，但有一段时间在使用java调用python程序之后，这个问题就出来了，也找不到问题出在哪里，我该从哪着手解决这个问题。

[问题三：请问以下这个报错是什么原因？实在使用模型进行预测的时候产生的。
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at C:\home\workspace\Paddle_release\paddle\phi\core\dense_tensor.cc:137)
  [operator < viterbi_decode > error]

**Comment by LemonNoel** [comment]
1. 实体级别的评估可以看看 [ChunkEvaluator](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/metrics/chunk.py)是否符合需求，可用于BIOS类型的实体识别效果评估
2. 模型评估阶段可以检查下 `dropout` 等带有随机性的函数是否已经固定，在`python`中的实现是`model.eval()`
3. 从报错信息看，应该是数据类型不匹配，可以先查看下模型需要的输入数据类型，和构造出来的数据类型是否一致。

**Comment by yangbin-Neil** [comment]
好的好的，我试试看，谢谢了

**Comment by yangbin-Neil** [comment]
您说的ChunkEvaluator是这个(https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/metrics/chunk.py)吗？，他自己带着一个超链接。我从飞桨官网上还看到一个paddle.fluid.metrics.ChunkEvaluator(name=None)，是前者还是后者？
