### ISSUE TITLE
[Question]: UIE：CCKS基线代码：解码细节请教

### ISSUE THREAD

**Issue by shihanmax** [PaddlePaddle/PaddleNLP#3934]
### 请提出你的问题

@luyaojie 你好👋，请问[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP)/[examples](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples)/[information_extraction](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction)/[DuUIE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)/inference.py 中实现的比赛基线方案中，是否实现了约束解码呢？看到代码用的是T5ForConditionalGeneration默认的generate方法，没有找到剪枝相关的操作，谢谢。

```Python
        }

        pred, _ = self.model.generate(
            input_ids=inputs['input_ids'],
            attention_mask=inputs['attention_mask'],
            max_length=self.max_target_length,
        )

        pred = self.tokenizer.batch_decode(pred.numpy())
```

**Comment by w5688414** [comment]
<img width="1005" alt="swagger_aip_demo" src="https://user-images.githubusercontent.com/12107462/204282574-4a468ba5-d32f-4ead-970b-87139b613521.png">
