### ISSUE TITLE
ernie-gen使用FasterGeneration

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#3939]
### 请提出你的问题

ernie-gen样例中数据为什么用\002分割，可以不分割吗？另外ernie-gen可以使用FasterGeneration吗？

**Comment by wawltor** [comment]
需要用\002分割，同时ernie-gen还不支持FasterGeneration；个人建议使用unimo-text 或者 T5模型来做生成，参考下面的代码
 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation

**Comment by ZTurboX** [comment]
> unimo-text

看到unimo-text 使用FasterGeneration时用动态图预测的，是否可以转成静态图再用FasterGeneration部署

**Comment by ZTurboX** [comment]
> 需要用\002分割，同时ernie-gen还不支持FasterGeneration；个人建议使用unimo-text 或者 T5模型来做生成，参考下面的代码 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation

unimo-text模型挺大的，有么有相关模型剪裁蒸馏量化方案

**Comment by wawltor** [comment]
> > 需要用\002分割，同时ernie-gen还不支持FasterGeneration；个人建议使用unimo-text 或者 T5模型来做生成，参考下面的代码 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation
> 
> unimo-text模型挺大的，有么有相关模型剪裁蒸馏量化方案

加速可以使用FasterTransformer来加速，可以FP16加速
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/16698950/204705121-03c74cc4-6f0c-4258-9b74-d5a54c612b8f.png">

**Comment by ZTurboX** [comment]
> > > 需要用\002分割，同时ernie-gen还不支持FasterGeneration；个人建议使用unimo-text 或者 T5模型来做生成，参考下面的代码 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation
> > 
> > 
> > unimo-text模型挺大的，有么有相关模型剪裁蒸馏量化方案
> 
> 加速可以使用FasterTransformer来加速，可以FP16加速 <img alt="image" width="1073" src="https://user-images.githubusercontent.com/16698950/204705121-03c74cc4-6f0c-4258-9b74-d5a54c612b8f.png">

unimo-text用于文本段落生成。输入是段落标题，输出是段落，参数num_return_sequences是指定生成的句子数吗？如果是指定生成的句子数，是否可以根据生成长度动态改变句子数？
