### ISSUE TITLE
[Question]: pddlenlp中是否有针对中文数据的t5模型？

### ISSUE THREAD

**Issue by BlueSkyBubble** [PaddlePaddle/PaddleNLP#3940]
### 请提出你的问题

pddlenlp中是否有针对中文数据的t5模型，即mt5？

**Comment by wawltor** [comment]
PaddleNLP里面集成了中文 mengzi T5模型和相关示例，可以参考以下代码 
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/t5/zero_shot_demo.py

**Comment by BlueSkyBubble** [comment]
> PaddleNLP里面集成了中文 mengzi T5模型和相关示例，可以参考以下代码 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/t5/zero_shot_demo.py

请问有在中文数据集上微调训练的代码吗?

**Comment by wawltor** [comment]
> > PaddleNLP里面集成了中文 mengzi T5模型和相关示例，可以参考以下代码 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/t5/zero_shot_demo.py
> 
> 请问有在中文数据集上微调训练的代码吗?

可以参考问题生成的微调方式： https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation/t5
