### ISSUE TITLE
[Question]: UIE微调后无法直接用于taskflow推理

### ISSUE THREAD

**Issue by guanghuixu** [PaddlePaddle/PaddleNLP#3943]
我基于UIE-base微调了模型，并重新指定了task_path，但无论输入什么返回结果都为空
```
schema = {'评价维度': ['观点词', '情感倾向[正向,中立,负向]']}
ie_model = Taskflow(task='information_extraction', task_path=checpoint_path,
                    schema=schema)
```

`checkpoint_path`目录下有pdparams文件
![image](https://user-images.githubusercontent.com/20624157/204469977-b435a631-34f2-4153-ad3d-f31a3d6bea13.png)

我没有真正训练完，训练时设置的epochs过大了。使用中间checkpoint也是可以用于taskflow推理的吧？
我的微调脚本如下：
```
export finetuned_model=./checkpoint/model_best

CUDA_VISIBLE_DEVICES=1 python finetune.py  \
    --device gpu \
    --logging_steps 100 \
    --save_steps 10000 \
    --eval_steps 10000 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 12 \
    --per_device_train_batch_size  12 \
    --num_train_epochs 100 \
    --learning_rate 1e-5 \
    --label_names 'start_positions' 'end_positions' \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1 \

```

**Comment by wawltor** [comment]
可以支持，把相关的文件夹路径写上去就行

**Comment by guanghuixu** [comment]
但我不指定task_path时可以出结果，一旦指定checkpoint路径就不行，
微调后的模型总会比没微调好一点？在开发集上的效果为 precision 0.81, recall 0.3, f1 0.44
我即使输入训练集的文本也没有结果

```
schema = {'评价维度': ['观点词', '情感倾向[正向,中立,负向]']}
checpoint_path = “checkpoint/model_best/checkpoint-10000”
ie_model = Taskflow(task='information_extraction', task_path=checpoint_path,
                    schema=schema)
```

**Comment by wawltor** [comment]
你把 checkpoint/model_best/checkpoint-10000 下的static目录删除试试

**Comment by guanghuixu** [comment]
删除了，paddle会重新自动生成
![image](https://user-images.githubusercontent.com/20624157/204479143-3411669b-d7d3-4ba3-bc62-7f6d5417c169.png)
但还是不能出结果

**Comment by wawltor** [comment]
> 删除了，paddle会重新自动生成 ![image](https://user-images.githubusercontent.com/20624157/204479143-3411669b-d7d3-4ba3-bc62-7f6d5417c169.png) 但还是不能出结果

确定这个checkpoints的效果是非常好的吗，有可能这个checkpoints效果不佳导致的

**Comment by guanghuixu** [comment]
F1 score确实一直维持在0.4左右
这是正常的吗？

**Comment by wawltor** [comment]
> F1 score确实一直维持在0.4左右 这是正常的吗？

不正常，0.4是比较低的score，可以尝试debug一下最佳模型的效果，一般情况下都是数据的问题 1) 标注数据小 2）标注质量不高，例如标注标准不统一

**Comment by guanghuixu** [comment]
```
schema = {'评价维度': ['观点词', '情感倾向[正向,中立,负向]']}
```
我重新定位了一下，是因为抽不出`评价维度`和`观点词`导致的结果为空
这个模型如果只做情感分类，是可以的
这可能跟我的微调数据有关，我用的是美团的ASAP，它本身只做方面级的情感分类，`评价维度是高度概括的字段(如food#Taste)`，不在原文text中出现
因此我想确认两个问题
1. UIE在训练中使用了多少数据？是否已经包括ASAP，包括的话，可以请教下你们的构造方式吗？我本意是想保留UIE的zero-shot抽实体能力，然后情感分类上用ASAP增强。我的构造方式如下，但微调效果很差
```
{"content": "和老公的朋友们聚餐，选择了这家烧肉屋，据说人气很旺，于是定座的，我们坐在楼上，阁楼感觉有点空气不流通，我这个孕妇貌似不适合油烟味大的地方，虽然已经过了孕吐期，
但一开始不太习惯，发现窗没有可以开的，都是固定的有点小失望，后来慢慢就习惯了，开始点了几个甜筒，很大一个，味道还凑合，后来大家点了很多肉，其中有一个肉味道很好，但是只顾着吃也忘记叫啥了，点了两份石锅饭也全干掉了，朋友的老婆点了冷面，第一次吃这样的，感觉不错啊！", "result_list": [{"text": "中立", "start": -10, "end": -8}], "prompt": "环境-嘈杂
情况的情感倾向[中立,负向,正向]"}
{"content": "和老公的朋友们聚餐，选择了这家烧肉屋，据说人气很旺，于是定座的，我们坐在楼上，阁楼感觉有点空气不流通，我这个孕妇貌似不适合油烟味大的地方，虽然已经过了孕吐期，
但一开始不太习惯，发现窗没有可以开的，都是固定的有点小失望，后来慢慢就习惯了，开始点了几个甜筒，很大一个，味道还凑合，后来大家点了很多肉，其中有一个肉味道很好，但是只顾着吃也忘记叫啥了，点了两份石锅饭也全干掉了，朋友的老婆点了冷面，第一次吃这样的，感觉不错啊！", "result_list": [], "prompt": "环境-就餐空间的情感倾向[中立,正向,负向]"}

```
2. 目前UIE是抽取范式，请问有实现生成范式的计划或打算吗？

**Comment by wawltor** [comment]
> ```
> schema = {'评价维度': ['观点词', '情感倾向[正向,中立,负向]']}
> ```
> 
> 我重新定位了一下，是因为抽不出`评价维度`和`观点词`导致的结果为空 这个模型如果只做情感分类，是可以的 这可能跟我的微调数据有关，我用的是美团的ASAP，它本身只做方面级的情感分类，`评价维度是高度概括的字段(如food#Taste)`，不在原文text中出现 因此我想确认两个问题
> 
> 1. UIE在训练中使用了多少数据？是否已经包括ASAP，包括的话，可以请教下你们的构造方式吗？我本意是想保留UIE的zero-shot抽实体能力，然后情感分类上用ASAP增强。我的构造方式如下，但微调效果很差
> 
> ```
> {"content": "和老公的朋友们聚餐，选择了这家烧肉屋，据说人气很旺，于是定座的，我们坐在楼上，阁楼感觉有点空气不流通，我这个孕妇貌似不适合油烟味大的地方，虽然已经过了孕吐期，
> 但一开始不太习惯，发现窗没有可以开的，都是固定的有点小失望，后来慢慢就习惯了，开始点了几个甜筒，很大一个，味道还凑合，后来大家点了很多肉，其中有一个肉味道很好，但是只顾着吃也忘记叫啥了，点了两份石锅饭也全干掉了，朋友的老婆点了冷面，第一次吃这样的，感觉不错啊！", "result_list": [{"text": "中立", "start": -10, "end": -8}], "prompt": "环境-嘈杂
> 情况的情感倾向[中立,负向,正向]"}
> {"content": "和老公的朋友们聚餐，选择了这家烧肉屋，据说人气很旺，于是定座的，我们坐在楼上，阁楼感觉有点空气不流通，我这个孕妇貌似不适合油烟味大的地方，虽然已经过了孕吐期，
> 但一开始不太习惯，发现窗没有可以开的，都是固定的有点小失望，后来慢慢就习惯了，开始点了几个甜筒，很大一个，味道还凑合，后来大家点了很多肉，其中有一个肉味道很好，但是只顾着吃也忘记叫啥了，点了两份石锅饭也全干掉了，朋友的老婆点了冷面，第一次吃这样的，感觉不错啊！", "result_list": [], "prompt": "环境-就餐空间的情感倾向[中立,正向,负向]"}
> ```
> 
> 2. 目前UIE是抽取范式，请问有实现生成范式的计划或打算吗？

1. UIE微调数据包括了ASAP相关数据，具体构建方式看
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md  

<img width="913" alt="image" src="https://user-images.githubusercontent.com/16698950/204705467-29de70ed-5259-42f5-ba38-5146e3884291.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/16698950/204705487-d657a8dc-01c2-4526-9888-3b49d096749a.png">

如果只加情感分类的数据微调，会有数据遗忘，建议对所有需要抽取的目标进行数据标注和微调

2. 生成的信息抽取在实验场景中有做过，UIE论文使用就是T5生成式，在产业落地方向还是建议抽取方法

**Comment by guanghuixu** [comment]
非常感谢回复！谢谢
