### ISSUE TITLE
[Question]: ernie-health spo 抽取任务，不会返回实体类型吗？

### ISSUE THREAD

**Issue by lichuanxiang** [PaddlePaddle/PaddleNLP#3949]
### 请提出你的问题

请教下，ernie-health 的 spo 抽取任务，不会返回实体类型吗？看输出，包括实体文本、span位置，spo实体文本+关系，想问下能拿到 subject、object 的实体类型吗？
![image](https://user-images.githubusercontent.com/10071850/204527604-69630b24-7a9c-46f6-b7fa-63ad82d0ddeb.png)

**Comment by LemonNoel** [comment]
ernie-health 抽取实体的方式是预测实体的起止位置，没有预测实体类型。

**Comment by lichuanxiang** [comment]
@LemonNoel 所以整体模型思路是参考 TPLinker 吗？

**Comment by LemonNoel** [comment]
有点区别，具体实现可以参考下  [ElectraForSPO 模型实现](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-health/cblue/train_spo.py#L134-L155)， 以及给出的 [样本标签示例](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-health/cblue/train_spo.py#L134-L155)
