### ISSUE TITLE
询问国产化环境下文本分类模型训练问题

### ISSUE THREAD

**Issue by 1205469665** [PaddlePaddle/PaddleNLP#395]
1. 系统:银河麒麟v10 
2. cpu:鲲鹏920 
3. 飞桨版本2.0
 执行文本分类训练异常缓慢, 设置多核
os.environ['CPU_NUM'] = str(32)
运行 感觉并没有产生作用，应该如何产生作用

**Comment by wawltor** [comment]
您好，
目前动态图版本还不支持CPU多核，目前动态图CPU多进程项目已经在开发计划中，有进展我们反馈给您！

**Comment by 1205469665** [comment]
以前不是可以吗？ 是升级2.0 不可以了吗？

**Comment by 1205469665** [comment]
就是以前不是 动态图版本开发的？ 然后现在是动态图开发的 ，动态图开发的现在还不支持 多核 是吗？ 我以前用的是1.7 版本的

**Comment by 1205469665** [comment]
用的是centos ,这个用2.0 版本的是因为要做国产化环境适配

**Comment by 1205469665** [comment]
@wawltor

**Comment by 1205469665** [comment]
那这个现在不能使用多核, 是不是训练完预测速度也会很慢啊

**Comment by wawltor** [comment]
> 那这个现在不能使用多核, 是不是训练完预测速度也会很慢啊
您好，PaddleNLP提供的版本均是动态图的版本，在 PaddlePdddle 2.0版本才正式提供了动态图，1.7和1.8版本均是静态图的，静态图的版本是可以对支持多核CPU加速训练的，动态图目前还不支持多核CPU加速。在预测方面的话，PaddleNLP的模型需要进行动转静，将动态图模型转化成可部署的静态图的模型，静态图的话在预测时是支持多核CPU加速的，具体的可以参考文本分类的https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models  预测部署这块
<img width="1258" alt="图片" src="https://user-images.githubusercontent.com/16698950/118440473-4b94ae80-b71a-11eb-9cef-242027c9942b.png">

**Comment by wawltor** [comment]
目前PddleNLP提供的文本分类训练是基于动态图的，动态图是PaddlePaddle 2.0才支持的属性，目前动态图还不支持多核CPU训练加速，在PaddlePaddle 1.7或者1.8版本是基于静态图的，因此是支持多核CPU加速。在预测方面，目前PaddleNLP支持将动态图训练得到的模型转成静态图，这样的话就可以支持预测多核CPU加速，具体的文本分类的静态图预测可以参考  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models  
<img width="1149" alt="图片" src="https://user-images.githubusercontent.com/16698950/118442349-0faf1880-b71d-11eb-8279-823463b26f3b.png">

**Comment by 1205469665** [comment]
您好，那个我咨询一个问题,就是 1.7 版本的不是可以 获取类型的分值每个类型的分值, 这个2.0 版本的为啥我看只有一个类型,有没有一个api 能获取到类型的分值

**Comment by wawltor** [comment]
您好，请教一下，您具体使用的代码是什么了，是否能提供一下链接地址了？@1205469665

**Comment by 1205469665** [comment]
https://github.com/PaddlePaddle/PaddleHub/blob/release/v2.1/demo/text_classification/predict.py 
![image](https://user-images.githubusercontent.com/16591941/118619698-6ab53e00-b7f7-11eb-8937-18590d5caee0.png)
 想获得分类类型的分值

**Comment by Steffy-zxf** [comment]
@1205469665 你好！由于PaddleHub的 ernie tiny module 预测接口predict接口已经对数据分类概率值封装好了，如果想要获取数据分类概率值需要改动module predict接口代码。不过你可以试试 PaddleNLP ERNIE完成文本分类任务，可以直接获取分类概率值，参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models

[此处](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/predict.py#L133)可以获取分类概率值。

**Comment by 1205469665** [comment]
您好,
请问这上面那块是可以获取到概率值的 我没太看出来怎么获取
![image](https://user-images.githubusercontent.com/16591941/118622373-d6000f80-b7f9-11eb-90a2-b6cd3fb04b73.png)

**Comment by Steffy-zxf** [comment]
> [此处](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/predict.py#L133)可以获取分类概率值。

这一行 代码： https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/predict.py#L133

**Comment by 1205469665** [comment]
您好，没看出来这个代码应该怎么取出概率值, 能说一下吗？

**Comment by 1205469665** [comment]
![image](https://user-images.githubusercontent.com/16591941/118628054-d18a2580-b7fe-11eb-8efe-d379e218d07d.png)
请问那个吗?

**Comment by 1205469665** [comment]
> 您好，
> 目前动态图版本还不支持CPU多核，目前动态图CPU多进程项目已经在开发计划中，有进展我们反馈给您！

您好,动态图版本的CPU 多进程有大概什么时间开发好吗？

**Comment by wawltor** [comment]
> > 您好，
> > 目前动态图版本还不支持CPU多核，目前动态图CPU多进程项目已经在开发计划中，有进展我们反馈给您！
> 
> 您好,动态图版本的CPU 多进程有大概什么时间开发好吗？

抱歉，因为动态图多核CPU的能力依赖于PaddlePaddle主框架，在最新的发版计划中目前还不会支持多核cpu。
