### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'paddle.distributed.sharding'

### ISSUE THREAD

**Issue by liuliuNLP** [PaddlePaddle/PaddleNLP#3958]
### 软件环境

```Markdown
- paddlepaddle:2.2.0
- paddlenlp: 2.4.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
任意执行一行代码就报这个错误
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow

# 默认模式————实体粒度分词，在精度和速度上的权衡，基于百度LAC
seg = Taskflow("word_segmentation")
seg("近日国家卫健委发布第九版新型冠状病毒肺炎诊疗方案")

**Comment by wawltor** [comment]
PaddlePaddle的版本过低，请升级到2.4rc版本

**Comment by ZHUI** [comment]
也可以将paddlenlp升级到`2.4.4`
