### ISSUE TITLE
[Bug]: TypeError: float() argument must be a string or a number, not 'tuple'

### ISSUE THREAD

**Issue by liuliuNLP** [PaddlePaddle/PaddleNLP#3966]
### 软件环境

```Markdown
- paddlepaddle:2.3.0
- paddlepaddle-gpu: 
- paddlenlp: 2.4.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
TypeError: float() argument must be a string or a number, not 'tuple'
```

### 稳定复现步骤 & 代码

  if args.params_path and os.path.isfile(args.params_path):
        state_dict = paddle.load(args.params_path)
        model.set_dict(state_dict)
        print("Loaded parameters from %s" % args.params_path)
    model.eval()

    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(shape=[None, None],
                                    dtype="int64"),  # input_ids
            paddle.static.InputSpec(shape=[None, None],
                                    dtype="int64"),  # segment_ids
            paddle.static.InputSpec(shape=[None], dtype="int64")  # lengths
        ])

    save_path = os.path.join(args.static_model_path, "inference")
    paddle.jit.save(model, save_path)

**Comment by wawltor** [comment]
能提供一下完整的复现的代码吗？

**Comment by zhouzhongmi** [comment]
@wawltor 

OS版本：Ubuntu 20.04.4 LTS \n \l
Python版本：Python 3.7.12
paddle版本：
```
paddle-bfloat                     0.1.7
paddle2onnx                       1.0.3
paddlefsl                         1.1.0
paddlenlp                         2.4.4
paddlepaddle                      2.3.2
```

完整复现代码：
```
from paddlenlp import Taskflow

senta = Taskflow("sentiment_analysis", model="skep_ernie_1.0_large_ch")
```

**Comment by liuliuNLP** [comment]
label_vocab = load_dict(os.path.join(args.data_dir, 'tag.dic'))
    ernie = ErnieGramForTokenClassification.from_pretrained(args.model_name, num_classes=len(label_vocab))
    model = ErnieGramCrfForTokenClassification(ernie)

    tokenizer = ErnieGramTokenizer.from_pretrained(args.model_name)
    if args.params_path and os.path.isfile(args.params_path):
        state_dict = paddle.load(args.params_path)
        model.set_dict(state_dict)
        print("Loaded parameters from %s" % args.params_path)
    model.eval()

    model = paddle.jit.to_static(
        model,
        input_spec=[
            paddle.static.InputSpec(shape=[None, None],
                                    dtype="int64"),  # input_ids
            paddle.static.InputSpec(shape=[None, None],
                                    dtype="int64"),  # segment_ids
            paddle.static.InputSpec(shape=[None], dtype="int64")  # lengths
        ])

    save_path = os.path.join(args.static_model_path, "inference")
    paddle.jit.save(model, save_path)

**Comment by liuliuNLP** [comment]
> 能提供一下完整的复现的代码吗？
paddlenlp==2.4.0下没问题，但是2.4.3不行，希望帮忙解答一下

**Comment by wawltor** [comment]
两种解决方法
1. 升级PaddlePaddle的版本到2.4版本 
2. 通过修复PR https://github.com/PaddlePaddle/PaddleNLP/pull/3970  来安装最新的PaddleNLP @liuliuNLP @zhouzhongmi

**Comment by zhouzhongmi** [comment]
> 两种解决方法
> 
> 1. 升级PaddlePaddle的版本到2.4版本
> 2. 通过修复PR [fix the taskflow skep & ErnieGram export model #3970](https://github.com/PaddlePaddle/PaddleNLP/pull/3970)  来安装最新的PaddleNLP @liuliuNLP @zhouzhongmi

按照您给的patch修正后，创建对象没问题了，但是在执行情感分析时又遇到了下面的报错：
```
from paddlenlp import Taskflow

senta = Taskflow("sentiment_analysis", model="skep_ernie_1.0_large_ch")

senta('歌都蛮好听的，很喜欢小偶像们的人设，立绘卡面都很精美，很高兴成为他们的普罗丢桑，但是运营就。想玩的姐妹们不要入脑吧放一张截到的好看的mv服装');
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/taskflow.py", line 611, in __call__
    results = self.task_instance(inputs)
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/task.py", line 388, in __call__
    outputs = self._run_model(inputs)
  File "/opt/conda/lib/python3.7/site-packages/paddlenlp/taskflow/sentiment_analysis.py", line 340, in _run_model
    self.predictor.run()
RuntimeError: could not create a descriptor for a matmul primitive
```

**Comment by wawltor** [comment]
> could not create a descriptor for a matmul primitive

你是什么机器设备了？ cpu？

**Comment by zhouzhongmi** [comment]
> > could not create a descriptor for a matmul primitive
> 
> 你是什么机器设备了？ cpu？

对，CPU机器，在一个Jupyter Notebook的容器里面执行遇到的问题

**Comment by wawltor** [comment]
> > > could not create a descriptor for a matmul primitive
> > 
> > 
> > 你是什么机器设备了？ cpu？
> 
> 对，CPU机器，在一个Jupyter Notebook的容器里面执行遇到的问题


两种方式 
1. 可以尝试把paddle版本降级到2.3.2版本 + 使用最新的develop版本的paddlenlp 
2. 可以尝试paddle版本降低2.4.0rc版本 

最新Paddle的2.4版本还不太稳定
