### ISSUE TITLE
[Question]: UIE结果不太稳定

### ISSUE THREAD

**Issue by xxllp** [PaddlePaddle/PaddleNLP#3974]
你好  我发现用官方的uie模型抽取数据 有存在不稳定的情况

比如我在抽取信息的文本（主干信息的文本）前面有其他文本就可能出不来或者出来部分。
这种是否是必须要单独训练才可以

**Comment by xxllp** [comment]
而且这个模型好像无法处理嵌套的这种信息？

**Comment by wawltor** [comment]
> 而且这个模型好像无法处理嵌套的这种信息？

产业应用建议微调；UIE目前还不能解决实体嵌套的问题

**Comment by xxllp** [comment]
好的  还想问下 这个是不是哪里有阀值 然后调整下阀值也能出来

**Comment by wawltor** [comment]
Taskflow任务可以通过下面的配置来改阈值
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/16698950/205037255-f77838d1-2972-44fa-860e-d303d537269d.png">
