### ISSUE TITLE
[Question]: 【快速上手ERNIE 3.0】对话意图识别实战代码

### ISSUE THREAD

**Issue by 1729789753** [PaddlePaddle/PaddleNLP#3976]
### 请提出你的问题

在前向传播的时候，使用交叉熵损失函数时，其中的logits和labels这两个张量的维度有时候不能对齐，导致模型跑不起来。到底哪里出了问题啊！！！大佬们帮帮我这个菜鸡

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 在前向传播的时候，使用交叉熵损失函数时，其中的logits和labels这两个张量的维度有时候不能对齐，导致模型跑不起来。到底哪里出了问题啊！！！大佬们帮帮我这个菜鸡

发一下链接？

**Comment by 1729789753** [comment]
原文档链接：https://aistudio.baidu.com/aistudio/projectdetail/2017202?contributionType=1

**Comment by 1729789753** [comment]
> 原文档链接：https://aistudio.baidu.com/aistudio/projectdetail/2017202?contributionType=1

**Comment by lugimzzz** [comment]
你好，这里的问题是数据处理的问题，你可以暂时添加下面两行代码，跳过长度不一致的数据使用，这块我们也将对项目错误进行修复
![image](https://user-images.githubusercontent.com/63761690/205588555-99918f8c-5a4e-4358-97df-2964f8ab2175.png)
