### ISSUE TITLE
[Feature request] 从文档中分析要求并给定类型

### ISSUE THREAD

**Issue by hehuang139** [PaddlePaddle/PaddleNLP#3994]
### Feature request

我现在面临的需求是，有一份给定说明文档，这些文档中有一些要求说明，需要分析出文档中的要求说明，并给出具体类型。以便可以根据要求去做对应的检查
举个例子，
要求一：要求类型为储蓄要求，要求内容为（必须提供储蓄证明，银行流水）
要求二：要求类型为犯罪证明，要求内容为（无刑事犯罪经历或已刑满出狱5年以上）
要求三：要求类型为健康证明，要求内容为（招工体检通过）
要求四：要求类型为国籍要求，要求内容为（中国大陆居民，港澳台除外）

问题是
1. 文档的内容可能比较多，需要从中找到要求的内容，并且可能有跨几个连续的自然段，并且要求内容可能只是文档的很小的一部分。
2. 不仅仅要找到要求，还需要给要求内容对应一个分类，并且分类后续可能增加。当然初期类型不会太多，大约10种以内

我想知道，目前是否有合适的nlp模型能做到以上说的需求，我考虑过文本分类也许可以做到，但是我当心的输入问题，我如何给模型输出，一段一段输入？但是存在跨多个连续自然段的情况。同时也担心，要求只是文档的很小一部分，如果用分类，是否有比较好的效果

### Motivation

见特性说明

### Your contribution

无

**Comment by hehuang139** [comment]
是否有比文本分类更好的模型，可以实现这个需求

**Comment by 1649759610** [comment]
1. 如果需要从大量文档或内容中找出答案的话，需要借助检索和排序的思路定位出潜在相关文档。
2. 如果文档比较长，建议文档按照固定长度进行分段，可以设置stride缓解跨多个连续自然段的情况
3. 除分类方法外，也可以尝试使用prompt learning的方式抽取内容信息，如：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by hehuang139** [comment]
> 1. 如果需要从大量文档或内容中找出答案的话，需要借助检索和排序的思路定位出潜在相关文档。
> 2. 如果文档比较长，建议文档按照固定长度进行分段，可以设置stride缓解跨多个连续自然段的情况
> 3. 除分类方法外，也可以尝试使用prompt learning的方式抽取内容信息，如：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

1. 检索排序要怎么做，是通过rocketqa进行定位吗？
2. 我的想法是每个自然段作为input，如果是固定长度512进行拆分在分类，这个分类是否会有问题，因为input里面有无关的内容
3. uie信息抽取，是将要求类型（国籍要求，健康要求）作为prompt进行抽取吗，uie抽取出一整个自然段感觉效果不是很好，感觉ner会比较好点，我现在只需要定位出段落即可，

**Comment by 1649759610** [comment]
如果只是定位段落，不抽取内容的话：
在数据量比较大的情况下，可以考虑基于rocketqa-zh-dureader-query-encoder进行检索召回部分，然后在排序阶段，可以通过rocketqa-zh-dureader-cross-encoder定位段落
在数据量不大的情况下，也可以直接通过rocketqa-zh-dureader-cross-encoder定位段落

**Comment by hehuang139** [comment]
@1649759610 如果文档不是固定的，是一类型的文档(每次都不一样的)，是否可以使用rocketqa进行检索。在看到“搭建自己的检索式问答系统“中有索引的概念，即文档是固定的。
并且关于rocketqa的模型微调方面，大致需要多少的训练集能达到比较好的效果，在rocketqa中也没有看到。

**Comment by hehuang139** [comment]
@1649759610 在rocketqa提了issue得到解答了，感谢
