### ISSUE TITLE
unimo-text

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4001]
### 请提出你的问题

unimo-text做文案生成时，同样的输入，如何让每次生成的结果不一样

**Comment by gongel** [comment]
你好，是否采用了sampling采样？如果想要固定结果，可以采取greedy search或者beam search

**Comment by ZTurboX** [comment]
> 你好，是否采用了sampling采样？如果想要固定结果，可以采取greedy search或者beam search

用了sampling采样，每次结果是一样的，希望每次结果不一样

**Comment by gongel** [comment]
可以贴下model.generate的参数

**Comment by ZTurboX** [comment]
> 可以贴下model.generate的参数

 parser.add_argument('--batch_size', type=int, default=2, help='Batch size per GPU/CPU for training.')
    parser.add_argument('--max_seq_len', type=int, default=512, help='The maximum sequence length of training.')
    parser.add_argument('--max_target_len', type=int, default=300, help='The maximum target sequence length of training.')
    parser.add_argument('--max_title_len', type=int, default=30, help='The maximum title sequence length of training.')
    parser.add_argument('--max_dec_len', type=int, default=300, help='The maximum sequence length of decoding.')
    parser.add_argument('--min_dec_len', type=int, default=3, help='The minimal sequence length of decoding.')
    parser.add_argument('--num_return_sequences', type=int, default=2, help='The numbers of returned sequences for one input in generation.')
    parser.add_argument('--decode_strategy', type=str, default='sampling', help='The decode strategy in generation.')
    parser.add_argument('--top_k', type=int, default=10, help='The number of highest probability vocabulary tokens to keep for top-k sampling.')
    parser.add_argument('--temperature', type=float, default=1.0, help='The value used to module the next token probabilities.')
    parser.add_argument('--top_p', type=float, default=1.0, help='The cumulative probability for top-p sampling.')
    parser.add_argument('--num_beams', type=int, default=3, help='The number of beams for beam search.')
    parser.add_argument('--length_penalty', type=float, default=1.2, help='The exponential penalty to the sequence length for beam search.')

**Comment by gongel** [comment]
Try set temperature=0.6
