### ISSUE TITLE
[Question]: text_summariztion中523M的pegasus模型无法下载

### ISSUE THREAD

**Issue by lily159** [PaddlePaddle/PaddleNLP#4006]
### 请提出你的问题

使用summarizer = Taskflow("text_summarization")语句，并不会开始下载模型，而是直接报错AttributeError: 'NoneType' object has no attribute 'eval'，并发出警告IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese\model_config.json  is not a valid path to a model config file 
但当我选择使用238M的pegasus模型或unimo-text-1.0-summary时，可以正常下载并使用，请问是什么原因？
当前环境 windows 无gpu  paddlenlp==2.4.4  paddlepaddle==2.4.0 python==3.7.0

**Comment by gongel** [comment]
你好，238M的pegasus模型如果可以，523M应该也可以的，再试一次？

**Comment by lily159** [comment]
> 你好，238M的pegasus模型如果可以，523M应该也可以的，再试一次？

你好，重新试了一次，已成功下载
