### ISSUE TITLE
[Question]: bertbase的实现

### ISSUE THREAD

**Issue by SoSoSaMa** [PaddlePaddle/PaddleNLP#4010]
### 请提出你的问题

请教下关于实现方案的问题，是基于Google research：https://github.com/google-research/bert 还是NVIDIA： https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT

**Comment by wawltor** [comment]
基于 NVIDIA  https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/LanguageModeling/BERT
