### ISSUE TITLE
[Question]: ERNIE-layout的训练和预测代码里没有serialization module？

### ISSUE THREAD

**Issue by LouisHeck** [PaddlePaddle/PaddleNLP#4015]
### 请提出你的问题

你好，在ernie-laytout的文档里，提到了serialization module来调整文本顺序，使得文本更符合阅读顺序，但是在ernie-layout训练和infer代码里均为看到serialization module，请问serializatin module是不是不开源？有计划开源吗？如果需要自己手动编写，请问有什么参考资料吗？感谢。

![1670225021122](https://user-images.githubusercontent.com/38588261/205578197-29de6537-8ac4-405c-9791-d6c58862eead.png)

**Comment by linjieccc** [comment]
@LouisHeck Hi,

Serialization module在ERNIE-Layout的预训练阶段有使用，公开数据集评测中没有使用，该模块为商用模块，暂时不会开源

**Comment by sisrfeng** [comment]
> 在ernie-layout训练和infer代码里均为看到serialization module

"为" 应是"未"

**Comment by sisrfeng** [comment]
论文里未给出Document Parser的链接, 我只搜到https://docparser.com/, 但似乎不是. Document Parser这一商用软件, 拥有者是谁呢? 如何下载使用? 如果无法使用Document Parser, 其他人如何完整复现论文的效果呢?
作为开源项目, 有没有违反https://github.com/Layout-Parser/layout-parser/blob/main/LICENSE ? (不熟悉开源协议, 真心求问求讨论)
