### ISSUE TITLE
[Question]: NLP模型文本分类的应用问题

### ISSUE THREAD

**Issue by tobias861222** [PaddlePaddle/PaddleNLP#4019]
### 请提出你的问题

目前想提升阅读测验的多选题的答题准确率，
目标题型为小学中文阅读测验，
因此在用ERNIE3.0解题前想先使用文本分类来分类题型，
判断多选题问题的答案 是否有在文章内，
有点像 判断 答案抽取/自由问答的题目，
判断完成后再将题目送至两种不同的解题模型，
一个针对答案在文章内的，一个针对答案在文章外的来做解题，
借此提高答题准确率。

我的问题是分类器的部分，担心文本分类大多应用在情感分析，新闻分类，会不会与我的应用相差过多?
或是有无其他的建议的模型可解决我的问题?

**Comment by lugimzzz** [comment]
预训练模型是在海量的数据预训练，不局限于情感分类、新闻分类等下游任务，如果是中文任务可以先使用ernie 3.0的模型使用一下。

文本分类使用可以参考，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification

**Comment by yaleimeng** [comment]
@tobias861222 
这种情况应该将文章与题目作为一对文本进行pairwise学习。类似于相关性打分。如果题目的答案在文章内可以为1，反之就标为0。最终模型结合具体的文章和题目会预测一个0~1之间的分值。
一篇文章可以跟很多问题无关，一个问题也可以跟很多文章无关。负样本非常多，正样本比较有限。有些担心题主数据集的数量是否充足。

**Comment by tobias861222** [comment]
@lugimzzz 
感谢回答
@yaleimeng 
感谢回答，目前也是打算将文章与题目作为一对文本来预测。
资料集的确是不太充足，需要自己标注，目前有一些国小阅读测验的题目和CLUE 的C3，之后可能會手动标注来做分类训练。
