### ISSUE TITLE
uie 信息抽取，只想做实体抽取，不想做关系抽取，必须要加入relation么

### ISSUE THREAD

**Issue by 694344851** [PaddlePaddle/PaddleNLP#4022]
### 请提出你的问题

想要训练一个单纯抽取地址的实体抽取模型，在准备数据的时候relation 怎么办

**Comment by linjieccc** [comment]
relation字段可以传入一个空的List

**Comment by 694344851** [comment]
我这边想要尝试抽取一句话中的地址信息。
比如：上城区四季青街道景昙路100号杭州大厦501城市广场F2巧虎kids早教机构学员，剩余2W多元费用，账号：1234556677，因所在班级的老师离职导致停课，来电要求退还剩余费用，望相关部门帮助核实处理。
目标是：上城区四季青街道景昙路100号杭州大厦501城市广场F2巧虎kids早教机构

直接提取，提取不出来地址，但是将“学员”两个字去掉以后就可以提取。
我这边根据不能提取的问题，做了标注进行训练，大概300条，但是训练完成以后，依旧提取不出来，甚至标注好的训练数据 依旧提取不出来地址，
请问这是什么原因，有什么好的办法么

**Comment by xxllp** [comment]
你是都出不来还是有badcase 部分出不来正常哈
