### ISSUE TITLE
[Question]: UIE-nano在cpu推理长文章时时间过长，以及占用memory过大

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#4023]
### 请提出你的问题

我这里2500字文章大概用时2分钟，占用memory占了8个G，是正常的么，如何优化

**Comment by linjieccc** [comment]
内存/显存占用过大的问题可以试试把batch_size调小一些
```python
Taskflow("information_extraction", model="uie-nano", schema=schema, batch_size=1)
```

**Comment by George-han** [comment]
是的，超级慢，千把字要二十来分钟，使用的cpu，请问有什么方法处理吗，还是哪里存在的问题，ie = Taskflow ('information_extraction', schema=schema,batch_size=1)

**Comment by LiuChiachi** [comment]
什么型号的CPU呢

**Comment by xiaoheiNLP** [comment]
感觉是Tokenizer的问题
