### ISSUE TITLE
[Question]: 如何基于ppdiffusers实现图片智能擦除

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#4025]
### 请提出你的问题

请问如何使用ppdiffusers移除图片中不想要的部分；谢谢！

**Comment by JunnYu** [comment]
目前应该没有直接移除的功能。
不过可以使用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers#%E5%9F%BA%E4%BA%8E%E6%96%87%E6%9C%AC%E5%BC%95%E5%AF%BC%E7%9A%84%E5%9B%BE%E5%83%8F%E7%BC%96%E8%BE%91text-guided-image-inpainting 
这里进行图像编辑。
![image](https://user-images.githubusercontent.com/50394665/205887194-b489590f-3dc1-4a37-bbc5-77171b418519.png)

**Comment by yanchaoguo** [comment]
> 目前应该没有直接移除的功能。 不过可以使用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers#%E5%9F%BA%E4%BA%8E%E6%96%87%E6%9C%AC%E5%BC%95%E5%AF%BC%E7%9A%84%E5%9B%BE%E5%83%8F%E7%BC%96%E8%BE%91text-guided-image-inpainting 这里进行图像编辑。 ![image](https://user-images.githubusercontent.com/50394665/205887194-b489590f-3dc1-4a37-bbc5-77171b418519.png)

图片编辑会新增元素 ；我希望把图片里不想要的部分擦除掉 而不新增

**Comment by JunnYu** [comment]
那目前是没有这个功能的，您是之前看到有使用扩散模型做这个的吗？

**Comment by yanchaoguo** [comment]
> 那目前是没有这个功能的，您是之前看到有使用扩散模型做这个的吗？

我看外网有人尝试做了 其中一个项目 lama cleaner;   我试了 如果mask区域不大 使用一个空的prompt  SD2.0可以做到擦除 但如果mask区域太大就会有新的物体生成

**Comment by JunnYu** [comment]
我看到他这个仓库 https://github.com/Sanster/lama-cleaner/blob/main/lama_cleaner/model/sd.py 代码使用的也是 runwayml/stable-diffusion-inpainting 的代码

**Comment by yanchaoguo** [comment]
看来diffusion是不能实现擦除功能了
