### ISSUE TITLE
[Question]: ERNIE3.0模型的微调

### ISSUE THREAD

**Issue by yangbin-Neil** [PaddlePaddle/PaddleNLP#4027]
### 请提出你的问题

在对ERNIE3.0模型进行微调时，发现可调的参数为epoch，batch_size，learn_rate。请问能否调节dropout率，暂时没找到在哪里调节，另外请问有没有什么好的办法来判断模型是否过拟合，谢谢

**Comment by yangbin-Neil** [comment]
dropout这个参数一般需要调吗？

**Comment by JunnYu** [comment]
一般来说没必要条件的，想要调整这个需要进入到代码里面进行修改。

**Comment by yangbin-Neil** [comment]
麻烦告知一下是从哪里进去修改呢，是加载模型的时候还是使用优化器的时候鸭？

**Comment by JunnYu** [comment]
如果你想要修改的是 ernie模型里面的dropout，可以直接修改配置文件 model_config.json。
![image](https://user-images.githubusercontent.com/50394665/206077264-f51e0bc8-ff22-440b-88e8-468e213439af.png)
如果是下游任务的dropout，你可以自己手动修改你自己所需的dropout。
https://github.com/PaddlePaddle/PaddleNLP/blob/b3b4fd0a9dffe81f810e13f408b9cb783f9fd927/paddlenlp/transformers/ernie/modeling.py#L151-L165

**Comment by yangbin-Neil** [comment]
我看到您给我截的图和代码框里的代码是一样的，您提供的这两个对应的是下游任务的dropout吗？我在做命名实体识别任务，目前主要对ERNIE3.0进行微调，然后使用以下代码加载ERNIE3.0模型。
 `ernie = AutoModelForTokenClassification.from_pretrained("ernie-3.0-medium-zh", num_classes=len(label_vocab))`
通过查询，我找到了以下代码，比您提供的多了一行定义model_config_file的代码，麻烦您再帮我看一下，代码如下：
```
class ErniePretrainedModel(PretrainedModel):
    An abstract class for pretrained ERNIE models. It provides ERNIE related
    `model_config_file`, `pretrained_init_configuration`, `resource_files_names`,
    `pretrained_resource_files_map`, `base_model_prefix` for downloading and
    loading pretrained models. 
    Refer to :class:`~paddlenlp.transformers.model_utils.PretrainedModel` for more details.
    """
    model_config_file = "model_config.json"
    pretrained_init_configuration = {
        # Deprecated, alias for ernie-1.0-base-zh
        "ernie-1.0": {
            "attention_probs_dropout_prob": 0.1,
            "hidden_act": "relu",
            "hidden_dropout_prob": 0.1,
            "hidden_size": 768,
            "initializer_range": 0.02,
            "max_position_embeddings": 513,
            "num_attention_heads": 12,
            "num_hidden_layers": 12,
            "type_vocab_size": 2,
            "vocab_size": 18000,
            "pad_token_id": 0,
        },
```
并且在里面找到我所使用的模型对应的参数：
`"ernie-3.0-base-zh": {
            "attention_probs_dropout_prob": 0.1,
            "hidden_act": "gelu",
            "hidden_dropout_prob": 0.1,
            "hidden_size": 768,
            "initializer_range": 0.02,
            "max_position_embeddings": 2048,
            "num_attention_heads": 12,
            "num_hidden_layers": 12,
            "task_type_vocab_size": 3,
            "type_vocab_size": 4,
            "use_task_id": True,
            "vocab_size": 40000
        },`

如果我想**针对下游任务**修改dropout的话，是修改这上面的参数吗？
另外还想咨询您如何查询model_config.json文件的路径，一般在哪个文件里？

**Comment by yangbin-Neil** [comment]
我的理解是：在必要的情况下，如果想要重新训练ERNIE3.0模型，是在model_config.json中修改dropout参数，如果仅仅想在下游任务中修改dropout参数，则仅需要修改modeling.py中的参数就好了，不需要修改配置文件中的。请问是这样吗？
