### ISSUE TITLE
[Question]: Taskflow 中的实体识别有误

### ISSUE THREAD

**Issue by shouxieai** [PaddlePaddle/PaddleNLP#4034]
### 请提出你的问题

 Taskflow 中的实体识别中，输入：XXX什么办？
最后的问号，识别出来竟然是 时间类_朝代

**Comment by wawltor** [comment]
> ### 请提出你的问题
> Taskflow 中的实体识别中，输入：XXX什么办？ 最后的问号，识别出来竟然是 时间类_朝代

是使用Taskflow('ner') 任务，如果是使用了这个任务的话因为模型精度是一定限度的，会有一些badcase的出现 ，这种情况下可以选择微调一下模型

**Comment by shouxieai** [comment]
感谢解答
