### ISSUE TITLE
[Question]: how to make the result more controllable 

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#4048]
### 请提出你的问题

Background: We'd like to do some generation based on the items we owned, which is seems like we draw some pictures base on our own items.

Process:
1. I did the "screenshot" for tens of photos of the items based on our 3D model in different distance and angle
2. I add the special token by tokenizer.add_tokens(['SPECIAL_TOKEN'], True) as symbol/pin for the item I added
3. After 1k~3k steps of fine tuning on ether dreambooth (sks SPECIAL_TOKEN) or textual_inversion (<textual_inversion>), i got 2 customized model
4. I input the prompt of '$SPECIAL_TOKEN' + other odds and ends to try to draw the pictures of my item
5. The result is only 50~60% similar with the item, e.g. input a table, white, half height, output a table in brown/only several hight .etc

I know i can force the result is 100% same with the original one as it would get influenced by the base model, but how can i raise the similar rate at least reach 80~90%? e.g. I input a white table, output a white table unless i high light the table should be brown one in my prompt?

**Comment by godlockin** [comment]
Is it able to ensure the result is quite similar with the original ones I injected? or it's totally a false proposition to do this attempt?
If yes, what I can do next in professional perspective?
1. to pick other model as base?
2. prepare much more feed images?
3. more steps/epoch with less learn rate?
Or no, try other technology e.g. face swap .etc ?

**Comment by JunnYu** [comment]
当前仓库的微调（与Hugginface一致）代码存在已知问题，训练效果没有原来仓库的那么好，首先需要排除代码的问题。
- 你可以先使用 https://github.com/victorchall/EveryDream-trainer 这里的dream代码进行微调，因为有微调这个 https://huggingface.co/ringhyacinth/nail-set-diffuser 权重的用户就反馈了使用原版代码比HF或PPDiffusers的代码要好。

我最近也要尝试修复一下这个问题。
