### ISSUE TITLE
目标词向量和上下文词向量有什么差别，分别用于什么场景

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleNLP#4050]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/16351823/206372252-5477df6a-6ad1-4fcd-b796-bd5d964ba459.png)
您好，文档中提供了2列词向量模型，目标词向量和上下文词向量，这里没理解，在训练emdding时，按道理词库中的所有词都有可能是目标词，也有可能会其他词的上下文，一个emdding权重矩阵，应该就可以达到这个目的了吧，为什么还会有一个上下文词向量表呢，这个是怎么训练出来的呢？这两个词向量表分别要在什么场景下用呢？

**Comment by joey12300** [comment]
@xdg2016 您好，在word2vec算法里，只需要目标词向量就可以了。但glove算法，会结合目标词向量和上下文词向量（求和或者求均值等）得到一个词向量，详细可以参考 https://nlp.stanford.edu/pubs/glove.pdf

**Comment by xdg2016** [comment]
好的，了解了，谢谢
