### ISSUE TITLE
你好，如何修改uie部署的http访问路径?

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#4052]
### 请提出你的问题

你好，如何修改uie部署的http访问路径,现在默认是 ip:端口/taskflow/uie，比如想修改为http://ip:端口/testInfo ,要怎么修改

**Comment by wawltor** [comment]
目前还不支持去除taskflow这个flag，这个工作我们排到下个paddlenlp版本，我们将这个issue通知开发进度；uie可以改变下面的方式来设定，
<img width="532" alt="image" src="https://user-images.githubusercontent.com/16698950/206456573-f94212c3-b5ca-48d3-acec-554bdbf8d124.png">

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md  相关功能已经支持，具体可以看文档，需要升级到最新的develop版本
