### ISSUE TITLE
UIE使用simpleServing部署，如何通过参数动态修改schema

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#4054]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie/deploy/serving/simple_serving/server.py  
这个代码实现中，若想动态修改schema，如何处理，麻烦指导一下，谢谢。

**Comment by wawltor** [comment]
我们预计下个paddlenlp版本支持该项工作，我们将在该issue通知相关修改PR

**Comment by zchengzhong** [comment]
> 

完善点能否加上：返回信息再处理，比如把返回内容再作转换等，然后再返回给请求客户端 ？

**Comment by wawltor** [comment]
这个已经支持了，可以重载下面的基类
<img width="970" alt="image" src="https://user-images.githubusercontent.com/16698950/206606881-bf879c57-04c0-4b58-94b0-23baa9cb4c18.png">

具体实现方式可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/383210a5b9e894aa4f7fb9dc13af22ca455901ff/paddlenlp/server/handlers/taskflow_handler.py#L18

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/4088  相关功能已经支持，可以看 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md
