### ISSUE TITLE
使用use_fast参数报错

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleNLP#4056]
### 请提出你的问题

Taskflow()参数use_fast报错，ModuleNotFoundError: No module named 'paddlenlp.transformers.ernie.faster_tokenizer'

目前已经按照文档安装了fast_tokenizer,pip install fast-tokenizer-python

paddlenlp我安装的是2.4.4最新版本，刚才我回退到2.4.0，后就可以使用这个use_fast参数没问题； 所以，你们是不是2.4.4版本和这个没适配

**Comment by joey12300** [comment]
@kevinuserdd 您好，感谢给PaddleNLP反馈问题。这个bug已经在 [PR4060](https://github.com/PaddlePaddle/PaddleNLP/pull/4060) 里修复了，如果着急的话可以先按照这个PR进行修改。今天下午将会发2.4.5版本，及时更新PaddleNLP即可正确运行。
