### ISSUE TITLE
unimo-text用FasterUNIMOText导出静态图

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4073]
### 请提出你的问题

paddlenlp不用pip安装，拉取后放在了自己项目里，unimo-text用FasterUNIMOText导出静态图后，libdecoding_op.so在自定义文件夹，在inference.py中如何加载libdecoding_op.so，即这边是怎么改写的
![image](https://user-images.githubusercontent.com/5669444/206841509-9af57e9f-0ce6-4190-a18a-07580f5ad72d.png)

**Comment by westfish** [comment]
这边还是推荐使用标准流程，按装最新版paddlenlp，然后load("FasterTransformer“)来体验FasterTransformer服务
