### ISSUE TITLE
有emlo预训练模型的参数吗？

### ISSUE THREAD

**Issue by zhangguozheng-1** [PaddlePaddle/PaddleNLP#4075]
### Feature request

https://github.com/PaddlePaddle/PaddleNLP/blob/4e56e4890c4caf09328bc1ea37ed0d135d90c15f/examples/language_model/elmo/run_pretrain.py

这个elmo预训练模型训练好的参数有吗？

### Motivation

在AI Studio上提供一个elmo和GloVe词向量表示的对比的项目。

### Your contribution

、

**Comment by wawltor** [comment]
目前 ELMO 没有提供预训练后的参数，只提供了预训练数据和流程；
想问一下 使用ELMO主要的用途是什么了？

**Comment by zhangguozheng-1** [comment]
想在AI Studio上做一个EMLO和GLOVE模型词向量表示的对比项目。
