### ISSUE TITLE
[Question]: 用UIE进行finetune的时候（评论词抽取任务），训练时模型一直不收敛的问题

### ISSUE THREAD

**Issue by xjDUAN184** [PaddlePaddle/PaddleNLP#4076]
### 请提出你的问题

我在使用UIE进行finetune的时候（评论词抽取），发现loss下降，但是f1值一直不收敛，使用的是paddlenlp2.4release版本的代码，100个epochs跑完f1才0.3几，最后模型在推理的时候，结果和0-shot的结果一样。不知道是什么问题，请各位大佬指点。最后一张是我推理的代码，会把评论词、评论主体、评论词的情感方向抽取出来。
训练日志
![image](https://user-images.githubusercontent.com/73686733/206914477-2436d920-411a-456d-b8a0-6d3507d91fb1.png)
推理代码
![image](https://user-images.githubusercontent.com/73686733/206914519-fce12074-c8e0-48a6-9aee-f89f97fd1928.png)
最后一个epochs的日志
![image](https://user-images.githubusercontent.com/73686733/206914567-5ff1a7de-a88c-49e6-8d54-016e0ec722e1.png)

**Comment by linjieccc** [comment]
@xjDUAN184 Hi,

请问你的标注数据量多大，方便提供几个你的标注例子看下吗

**Comment by xjDUAN184** [comment]
@linjieccc ，大佬您好。标注量20，下面是其中的四条，评价维度对应评价的主体词，观点词代表评价词，relations代表评价维度与观点词之间的关系
{"id":637,"text":"﻿这样座椅都不是很大，可用17号左右这个座椅加热也没有，","entities":[{"id":116,"label":"评价维度","start_offset":3,"end_offset":5},{"id":117,"label":"观点词","start_offset":6,"end_offset":10}],"relations":[{"id":21,"from_id":116,"to_id":117,"type":"观点词"}],"Comments":[]}

{"id":638,"text":"那差不多，差不多这个价格差不多那25万左右的话，","entities":[{"id":118,"label":"评价维度","start_offset":10,"end_offset":12},{"id":119,"label":"观点词","start_offset":12,"end_offset":15}],"relations":[{"id":22,"from_id":118,"to_id":119,"type":"观点词"}],"Comments":[]}

{"id":639,"text":"对于我来讲，我觉得七座对我来讲很重要，","entities":[{"id":120,"label":"评价维度","start_offset":9,"end_offset":11},{"id":121,"label":"观点词","start_offset":15,"end_offset":18}],"relations":[{"id":23,"from_id":120,"to_id":121,"type":"观点词"}],"Comments":[]}

{"id":640,"text":"啊颜色好的，颜色好的。","entities":[{"id":122,"label":"评价维度","start_offset":1,"end_offset":3},{"id":123,"label":"观点词","start_offset":3,"end_offset":4}],"relations":[{"id":24,"from_id":122,"to_id":123,"type":"观点词"}],"Comments":[]}

**Comment by linjieccc** [comment]
你可以尝试增加一些标注数据，如果按照0.8 0.2切分的话当前验证集只有四条数据。

另外标注阶段可以关注下实体边界的设定尽量统一，因为目前的评价方式需要实体的起始位置完全match才视为正确，例如标注的评论观点为『颜色好』，但其实『颜色好的』也可以视为一组结果

**Comment by xjDUAN184** [comment]
@linjieccc 
好的，我会尝试将标注数据增加到50条
关于您说的第二点，我的理解就是每条数据在标注的时候，尽量做到和句子的边界统一，就比如“啊颜色好的”，颜色作为“评价维度”，“好的”作为观点词。这样理解对吗？如果不对的话，能麻烦您帮忙指正一下吗？

**Comment by linjieccc** [comment]
> @linjieccc 好的，我会尝试将标注数据增加到50条 关于您说的第二点，我的理解就是每条数据在标注的时候，尽量做到和句子的边界统一，就比如“啊颜色好的”，颜色作为“评价维度”，“好的”作为观点词。这样理解对吗？如果不对的话，能麻烦您帮忙指正一下吗？

是的，你可以check下标注数据，尽量统一

**Comment by LimoLi-1** [comment]
我碰到了和你一样的问题，使用UIE做实体抽取，500条数据，F1初始是0。然后我下载了最新的UIE代码覆盖旧代码后就正常了，F1初始就很高了。

**Comment by xjDUAN184** [comment]
大佬您好，非常感谢您的回答，我想问一下你用的是哪个版本的UIE代码啊？




鑫鑫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月13日(星期二) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: 用UIE进行finetune的时候（评论词抽取任务），训练时模型一直不收敛的问题 (Issue #4076)





 
我碰到了和你一样的问题，使用UIE做实体抽取，500条数据，F1初始是0。然后我下载了最新的UIE代码覆盖旧代码后就正常了，F1初始就很高了。

**Comment by xjDUAN184** [comment]
@LimoLi-1  大佬您好，非常感谢您的回答，我想问一下您用的是那个版本的UIE代码啊？

**Comment by linjieccc** [comment]
@xjDUAN184 develop分支
