### ISSUE TITLE
[Question]: UIEM模型微調之後遭遇報錯

### ISSUE THREAD

**Issue by coolinstar** [PaddlePaddle/PaddleNLP#4077]
### 请提出你的问题

UIE模型微調
調整uie-m-base模型
Training Complete
Model Saved

之後進行導出以及部署
採用UIEM無法進行。

使用環境一
paddlepaddle-gpu  2.4.0
Paddlenlp                2.4.4   

使用環境二
paddlepaddle-gpu  2.4.0
Paddlenlp                develop   

請教如何導出部署UIEM模型，謝謝。

**Comment by linjieccc** [comment]
@coolinstar Hi,

麻烦提供一下错误信息

**Comment by linjieccc** [comment]
@coolinstar 可以参考下这里的修复代码看能否解决你的问题：https://github.com/PaddlePaddle/PaddleNLP/pull/4081
