### ISSUE TITLE
[Bug]: 模型微调finetune.py，from paddlenlp.transformers import UIE报错，请问如何解决？

### ISSUE THREAD

**Issue by RONG-SONG** [PaddlePaddle/PaddleNLP#4078]
### 软件环境

```Markdown
- paddlepaddle:2.4.0
- paddlepaddle-gpu: 
- paddlenlp:  2.4.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
模型微调finetune.py，from paddlenlp.transformers import UIE报错，请问如何解决？
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import UIE

**Comment by linjieccc** [comment]
@RONG-SONG Hi，

我们在2.4.5版本将UIE相关模型放入transformers中便于管理，你可以更新下develop分支的代码，同时升级到2.4.5版本试下

**Comment by RONG-SONG** [comment]
可以了，非常感谢
