### ISSUE TITLE
[Question]: 能否加入opendelta功能？

### ISSUE THREAD

**Issue by yinfupai** [PaddlePaddle/PaddleNLP#4082]
AutoPrompt很棒，不过能否加入像opendelta的功能？

**Comment by wawltor** [comment]
请教一下，想加入opendelta的主要是想进行什么样的工作了？

**Comment by yinfupai** [comment]
OpenDelta可以只更新模型极少参数（小于5%）可达到全参数微调的效果，可以用于高效的大模型微调，能有效节省训练资源

**Comment by wawltor** [comment]
> OpenDelta可以只更新模型极少参数（小于5%）可达到全参数微调的效果，可以用于高效的大模型微调，能有效节省训练资源

嗯嗯，了解 OpenDelta主要基于Adpater相关原理使用超大模型作为基础模型，通过一些Adpater来适配相关任务，目前我们开源的模型还没有超大模型，因此没有适配这个工作；这个工作我们先做一个需求评审看看，谢谢!
