### ISSUE TITLE
[Question]: ppdiffusers图像编辑功能，8G显存运行不足

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/PaddleNLP#4087]
### 请提出你的问题

Out of memory error on GPU 0. Cannot allocate 512.000000MB memory on GPU 0, 7.505859GB memory has been allocated and available memory is only 296.437500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)

请问是否可以通过减少计算精度解决这个问题，及如何改变计算精度

**Comment by JunnYu** [comment]
你好，正常在8g的显存上是跑不了sd模型的，可能fp16可以跑，不过需要尝试一下修改部分代码。如果想要在8g显存上跑这个模型建议之后可以使用fastdeploy进行跑。

**Comment by d2623587501** [comment]
你好，感谢答复，我看了fastdeploy中还没有对ppdiffusers图像编辑功能的模型支持，请问是不是只能去更改fp16的精度，这部分代码在那个文件中呢
