### ISSUE TITLE
[Question]: PaddleNLP/applications/question_answering/faq_system/ 缺失.py文件  "milvus.py"

### ISSUE THREAD

**Issue by jxrjlxc02** [PaddlePaddle/PaddleNLP#4092]
### 请提出你的问题

您好，在进行 python vector_insert.py 的时候，发现“milvus_util.py” 缺失了引用文件 "milvus.py" 其中定义了Milvus类相关的方法。目前已经自己搭建好 milvus的docker环境。

**Comment by w5688414** [comment]
please install pymilvus, for milvus 1.1.1

```
pip install pymilvus==1.1.1
```

**Comment by jxrjlxc02** [comment]
谢谢回复，建议文档后续可以添加相关的 docker地址，方便他们查找：
镜像地址： docker pull milvusdb/milvus:1.1.1-cpu-d061621-330cc6
安装文档：https://milvus.io/docs/v1.1.1/milvus_docker-cpu.md

**Comment by jxrjlxc02** [comment]
您好，部署的时候遇到问题 -> 步骤：Paddle Serving 部署：

报错步骤： 在 ”Paddle Serving 部署“ 中 运行 python web_service.py 报错
报错信息：
Traceback (most recent call last):
  File "web_service.py", line 70, in <module>
    ernie_service.prepare_pipeline_config("config_nlp.yml")
AttributeError: 'ErnieService' object has no attribute 'prepare_pipeline_config'

我的操作（没有 安装 serving:0.9.0-cuda11.2-cudnn8-devel，直接pip安装）：
1, pip install paddle-serving-client
发现可以正常完成 export_to_serving.py
# serving
python export_to_serving.py \
    --dirname "output_covid" \
    --model_filename "inference.get_pooled_embedding.pdmodel" \
    --params_filename "inference.get_pooled_embedding.pdiparams" \
    --server_path "./serving_server" \
    --client_path "./serving_client" \
    --fetch_alias_names "output_embedding"

2，pip install paddle-serving-server-gpu
cd deploy/python/
python web_service.py
报错了

教程中
”Paddle Serving 的安装可以参考[Paddle Serving 安装文档](https://github.com/PaddlePaddle/Serving#installation)。需要在服务端和客户端安装相关的依赖，安装完依赖后就可以执行下面的步骤。“
这句话我没有很理解，具体需要做什么，"需要在服务端和客户端安装相关的依赖"， 是安装 serving:0.9.0-cuda11.2-cudnn8-devel 环境后，把当前目录映射到docker环境中吗？

补充信息：
（自己通过[Paddle Serving 安装文档](https://github.com/PaddlePaddle/Serving#installation) 安装并启动了docker）
但是目前没有使用到docker 环境
λ be5a2eeac3db /home/Serving {v0.9.0} python3 -m paddle_serving_server.serve check
/usr/local/lib/python3.6/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Welcome to the check env shell.Type help to list commands.

(Cmd)

**Comment by jxrjlxc02** [comment]
我发现应该是 WebService  后端源码变化导致的，函数变了好像
ernie_service.prepare_pipeline_config("config_nlp.yml")   --> ernie_service.server_config_dir_paths(xx)
