### ISSUE TITLE
faq_financial环境问题

### ISSUE THREAD

**Issue by Gavingx** [PaddlePaddle/PaddleNLP#4095]
### 请提出你的问题

你好，想请问下https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/faq_finance这个项目下的包的版本具体是多少（或者有没有打包好的镜像）。按照requirements.txt安装包会报错：如下
![image](https://user-images.githubusercontent.com/43789460/207222188-ff5013f9-77ef-4232-8b03-84d0d9710be5.png)

我的环境对应的包如下（把paddlepaddle-gpu从2.2换到2.4都不行）：
pymilvus                      2.1.0
paddlenlp                     2.3.7
paddlepaddle-gpu              2.4.0
hnswlib                       0.5.2
numpy                         1.23.5
visualdl                      2.2.2
pybind11                      2.7.0

**Comment by w5688414** [comment]
> paddlepaddle

似乎是paddle的循环导入的问题，检查一下paddle的安装是否正常

安装完成后您可以使用 python3 进入 python 解释器，输入import paddle ，再输入 paddle.utils.run_check()

如果出现PaddlePaddle is installed successfully!，说明您已成功安装。
