### ISSUE TITLE
文档信息抽取

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4097]
### 请提出你的问题

文档信息抽取中增值税发票抽取，增值税存在购买方和销售方，标注是不是得用关系标注的方式

**Comment by linjieccc** [comment]
@ZTurboX Hi，

如果需要将购买方和销售方的对应属性就行关联，可以采用关系的标注方式

具体可以参考文档中的标注示例：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/label_studio_doc.md#2
