### ISSUE TITLE
[Question]: what if we open all config for internal model?

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#4101]
### 请提出你的问题

for images' generation, i always met the issue:The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['...'], which is controlled by the param: `max_position_embeddings` in CLIP's config ref [link](https://huggingface.co/transformers/v4.8.0/model_doc/clip.html)

so, can we add api/param .etc to customize the configurations for internal models then?

**Comment by JunnYu** [comment]
CLIP模型是进行图文匹配的模型，这最开始由openai提出，开始训练的，他们在训练的时候固定了文本最大长度为77.（我猜测这是因为他们统计数据集发现，文本长度基本不会超过77的，图文匹配数据集应该没有这么长的文本的。）
如果你想要修改，你也可以训练一个文本编码器，比如使用CLIP的文本编码器，Bert模型，或者Ernie模型。
这里有一个从零预训练的教程代码 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/text_to_image_laion400m
https://github.com/PaddlePaddle/PaddleNLP/blob/e8c8b6c70c519ad9c1a97750d1671dcbd1b673df/ppdiffusers/examples/text_to_image_laion400m/config/ldmbert.json#L3 可以参考一下
