### ISSUE TITLE
[Question]: UIE-X模型CPU环境部署性能问题

### ISSUE THREAD

**Issue by wxz5459** [PaddlePaddle/PaddleNLP#4111]
### 请提出你的问题

试用UIE-X发现模型效果很赞，感谢开源！
在将模型部署到CPU环境时，遇到模型预测耗时较长的问题，请问下有什么办法可以提高预测速度，如果需要做模型压缩，能否给出参考示例？谢谢！

**Comment by wawltor** [comment]
UIE-x目前的性能瓶颈在于ernie和Resnet的特征抽取的部分，在2.4.5版本目前在cpu的性能受限，建议是GPU版本；我们在2.5版本预计发布一个数据蒸馏的工具才进行加速。

**Comment by wxz5459** [comment]
感谢答复！
