### ISSUE TITLE
faiss or milvus增量更新后，服务是否需要重启？

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleNLP#4112]
### 请提出你的问题

语义问答中涉及到faiss、milvus的使用，如果后续有新数据需要新增进入，请问怎么保证实时更新？？

**Comment by w5688414** [comment]
可以看一下readme文档，elastic search和milvus是支持在线更新的，提供了相应的rest API来更新索引。 faiss目前只是方便演示，可以在终端进行一些数据的新增等操作，并没有提供res tapi来实时更新索引。
