### ISSUE TITLE
ValueError: substring not found [Question]: 

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleNLP#4113]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/28383188/207526088-333165ff-59d9-4161-b785-850a3282d6d6.png)

当我添加了特殊字符后，还是报错，因为它把  “49ˊ”  、 "18ˊ"都当成一个token了，那不是要把所有数字和“ˊ”添加进去么，请问一下这个问题怎么解决尼，
我很奇怪为什么它能将“113°”分为“113”和“°”尼，请大佬帮看一下

**Comment by wawltor** [comment]
这个在2.4.5版本已经修复，辛苦升级到该版本

**Comment by LeFuGang** [comment]
> 这个在2.4.5版本已经修复，辛苦升级到该版本

谢谢，已解决
