### ISSUE TITLE
[Question]: Uie模型数据标注问题

### ISSUE THREAD

**Issue by joesong168** [PaddlePaddle/PaddleNLP#4119]
### 请提出你的问题

请问数据标注的每一条，都必须有schema的每个字段么。如果用doccano.py生成的训练数据里有空字符串，会影响培训结果么？

doccano_ext.json
{"id": 1, "text": "戰國 人物龍鳳帛畫", "relations": [], "entities": [{"id": 0, "start_offset": 7, "end_offset": 9, "label": "材質"}]}
{"id": 2, "text": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "relations": [], "entities": [{"id": 1, "start_offset": 10, "end_offset": 14, "label": "高度"}, {"id": 2, "start_offset": 15, "end_offset": 17, "label": "寬度"}, {"id": 3, "start_offset": 17, "end_offset": 23, "label": "收藏者"}, {"id": 4, "start_offset": 7, "end_offset": 9, "label": "材質"}]}
{"id": 3, "text": " 金文拓本 10402226(1)", "relations": [], "entities": [{"id": 5, "start_offset": 1, "end_offset": 5, "label": "作品"}]}

train.txt
{"content": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "result_list": [{"text": "帛畫", "start": 7, "end": 9}], "prompt": "材質"}
{"content": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "result_list": [{"text": "28", "start": 15, "end": 17}], "prompt": "寬度"}
{"content": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "result_list": [{"text": "湖南省博物館", "start": 17, "end": 23}], "prompt": "收藏者"}
{"content": " 金文拓本 10402226(1)", "result_list": [], "prompt": "收藏者"}
{"content": " 金文拓本 10402226(1)", "result_list": [], "prompt": "材質"}
{"content": " 金文拓本 10402226(1)", "result_list": [], "prompt": "高度"}
{"content": " 金文拓本 10402226(1)", "result_list": [], "prompt": "寬度"}
{"content": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "result_list": [], "prompt": "作品"}
{"content": " 金文拓本 10402226(1)", "result_list": [{"text": "金文拓本", "start": 1, "end": 5}], "prompt": "作品"}
{"content": "戰國 人物禦龍帛畫 37.5x28湖南省博物館藏", "result_list": [{"text": "37.5", "start": 10, "end": 14}], "prompt": "高度"}

**Comment by wawltor** [comment]
不影响效果，空字符串的是属于负样本策略生成的。

**Comment by joesong168** [comment]
为什么用以上数据微调出来的模型，无法识别实体，而之前的可以。

![截屏2022-12-14 20 52 35](https://user-images.githubusercontent.com/10493864/207600282-648b7151-d090-4bd6-9ee5-864b0972e793.png)

![截屏2022-12-14 20 50 44](https://user-images.githubusercontent.com/10493864/207600122-146fcea2-c7af-4326-8a23-9367011e3c89.png)

**Comment by wawltor** [comment]
微调后的模型指标是什么情况？

**Comment by joesong168** [comment]
查了一下，的确是微调后的模型精度不行。我又简化了一下训练数据如下，训练了100个epoch，可是精度还是为零，请问是什么原因？

**Comment by joesong168** [comment]
{"id": 1, "text": "明 丁玉川 漁樂圖 絹布 38X77", "relations": [], "entities": [{"id": 0, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 1, "start_offset": 6, "end_offset": 9, "label": "作品"}, {"id": 2, "start_offset": 16, "end_offset": 18, "label": "高度"}, {"id": 3, "start_offset": 13, "end_offset": 15, "label": "寬度"}]}
{"id": 2, "text": "明 丘鑒 芙蓉蘆雁圖軸 絹本164.5x67.9安博", "relations": [], "entities": [{"id": 19, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 20, "start_offset": 5, "end_offset": 10, "label": "作品"}, {"id": 21, "start_offset": 14, "end_offset": 19, "label": "高度"}, {"id": 22, "start_offset": 20, "end_offset": 24, "label": "寬度"}]}
{"id": 3, "text": "Y佚名 中日韓三國畫家合作 傲雪迎春圖 中日韓三國畫家合作 傲雪迎春圖-整圖-119x238", "relations": [], "entities": [{"id": 23, "start_offset": 4, "end_offset": 13, "label": "作者"}, {"id": 24, "start_offset": 14, "end_offset": 19, "label": "作品"}, {"id": 25, "start_offset": 39, "end_offset": 42, "label": "高度"}, {"id": 26, "start_offset": 43, "end_offset": 46, "label": "寬度"}]}
{"id": 4, "text": "清 乾隆 綢繡蔬果掛屏芯34x43", "relations": [], "entities": [{"id": 29, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 30, "start_offset": 5, "end_offset": 12, "label": "作品"}, {"id": 31, "start_offset": 12, "end_offset": 14, "label": "高度"}, {"id": 32, "start_offset": 15, "end_offset": 17, "label": "寬度"}]}
{"id": 5, "text": " 9.清 10.晚晴民國 3 于右任 于右任 標準草書千字文 30X873", "relations": [], "entities": [{"id": 37, "start_offset": 15, "end_offset": 18, "label": "作者"}, {"id": 38, "start_offset": 23, "end_offset": 30, "label": "作品"}, {"id": 39, "start_offset": 31, "end_offset": 33, "label": "高度"}, {"id": 40, "start_offset": 34, "end_offset": 37, "label": "寬度"}]}
{"id": 6, "text": "于文江 小園香徑獨徘徊 79X79", "relations": [], "entities": [{"id": 42, "start_offset": 0, "end_offset": 3, "label": "作者"}, {"id": 43, "start_offset": 4, "end_offset": 11, "label": "作品"}, {"id": 44, "start_offset": 12, "end_offset": 14, "label": "高度"}, {"id": 45, "start_offset": 12, "end_offset": 14, "label": "寬度"}]}
{"id": 7, "text": "Y于照 于照 喜上眉梢圖-OK 49X128", "relations": [], "entities": [{"id": 46, "start_offset": 1, "end_offset": 3, "label": "作者"}, {"id": 47, "start_offset": 7, "end_offset": 12, "label": "作品"}, {"id": 48, "start_offset": 19, "end_offset": 22, "label": "高度"}, {"id": 49, "start_offset": 16, "end_offset": 18, "label": "寬度"}]}
{"id": 8, "text": "元 五家 合繪卷 五家合繪卷 王冕 朱澤民 張觀 方方壺 仲穆 故宮博物院紙本31.9x50.9", "relations": [], "entities": [{"id": 55, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 56, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 57, "start_offset": 39, "end_offset": 43, "label": "高度"}, {"id": 58, "start_offset": 44, "end_offset": 48, "label": "寬度"}]}
{"id": 9, "text": "J京新 小品羅漢 京新 小品羅漢-1-1 45X34", "relations": [], "entities": [{"id": 64, "start_offset": 1, "end_offset": 3, "label": "作者"}, {"id": 65, "start_offset": 6, "end_offset": 8, "label": "作品"}, {"id": 66, "start_offset": 24, "end_offset": 26, "label": "高度"}, {"id": 67, "start_offset": 21, "end_offset": 23, "label": "寬度"}]}
{"id": 10, "text": "C仇相吉 仇相吉 書法 同生共長-132x64.5", "relations": [], "entities": [{"id": 71, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 72, "start_offset": 12, "end_offset": 16, "label": "作品"}, {"id": 73, "start_offset": 17, "end_offset": 20, "label": "高度"}, {"id": 74, "start_offset": 21, "end_offset": 25, "label": "寬度"}]}
{"id": 11, "text": "明 仇英 赤壁圖卷 赤壁圖卷(全卷)絹本25.7x90.8臺北故宮", "relations": [], "entities": [{"id": 75, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 76, "start_offset": 5, "end_offset": 8, "label": "作品"}, {"id": 77, "start_offset": 20, "end_offset": 24, "label": "高度"}, {"id": 78, "start_offset": 25, "end_offset": 29, "label": "寬度"}]}
{"id": 12, "text": "元 任康民 山水圖 23.8X21", "relations": [], "entities": [{"id": 87, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 88, "start_offset": 6, "end_offset": 9, "label": "作品"}, {"id": 89, "start_offset": 10, "end_offset": 14, "label": "高度"}, {"id": 90, "start_offset": 15, "end_offset": 17, "label": "寬度"}]}
{"id": 13, "text": "清 任阜長 群仙圖 紙本 55x99", "relations": [], "entities": [{"id": 100, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 101, "start_offset": 6, "end_offset": 9, "label": "作品"}, {"id": 102, "start_offset": 16, "end_offset": 18, "label": "高度"}, {"id": 103, "start_offset": 13, "end_offset": 15, "label": "寬度"}]}
{"id": 14, "text": "H何家英 何家英 芭蕉麗人 165×74", "relations": [], "entities": [{"id": 110, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 111, "start_offset": 9, "end_offset": 13, "label": "作品"}, {"id": 112, "start_offset": 14, "end_offset": 17, "label": "高度"}, {"id": 113, "start_offset": 18, "end_offset": 20, "label": "寬度"}]}
{"id": 15, "text": "吳昌碩紀念館 何瀛 餉鳥圖53-114cm", "relations": [], "entities": [{"id": 119, "start_offset": 7, "end_offset": 9, "label": "作者"}, {"id": 120, "start_offset": 10, "end_offset": 13, "label": "作品"}, {"id": 121, "start_offset": 16, "end_offset": 19, "label": "高度"}, {"id": 122, "start_offset": 13, "end_offset": 15, "label": "寬度"}]}
{"id": 16, "text": "宋 團扇 何荃 草堂客話圖24xc23", "relations": [], "entities": [{"id": 125, "start_offset": 5, "end_offset": 7, "label": "作者"}, {"id": 126, "start_offset": 8, "end_offset": 13, "label": "作品"}, {"id": 127, "start_offset": 17, "end_offset": 19, "label": "高度"}, {"id": 128, "start_offset": 13, "end_offset": 15, "label": "寬度"}]}
{"id": 17, "text": "H何香凝 何香凝-牡丹梅花-okt 33×98", "relations": [], "entities": [{"id": 129, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 130, "start_offset": 9, "end_offset": 13, "label": "作品"}, {"id": 131, "start_offset": 21, "end_offset": 23, "label": "高度"}, {"id": 132, "start_offset": 18, "end_offset": 20, "label": "寬度"}]}
{"id": 18, "text": "H何香凝、柳亞子、馬公愚、鄭午昌 何香凝、柳亞子、馬公愚、鄭午昌-水墨梅竹圖軸132X32", "relations": [], "entities": [{"id": 133, "start_offset": 1, "end_offset": 16, "label": "作者"}, {"id": 134, "start_offset": 33, "end_offset": 38, "label": "作品"}, {"id": 135, "start_offset": 39, "end_offset": 42, "label": "高度"}, {"id": 136, "start_offset": 40, "end_offset": 42, "label": "寬度"}]}
{"id": 19, "text": "L來楚生 來楚生 枇杷粽子圖軸25X52", "relations": [], "entities": [{"id": 139, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 140, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 141, "start_offset": 15, "end_offset": 17, "label": "高度"}, {"id": 142, "start_offset": 18, "end_offset": 20, "label": "寬度"}]}
{"id": 20, "text": "清 俞樾手劄 二十四通(書法) 二十四通28x234", "relations": [], "entities": [{"id": 147, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 148, "start_offset": 7, "end_offset": 11, "label": "作品"}, {"id": 149, "start_offset": 20, "end_offset": 22, "label": "高度"}, {"id": 150, "start_offset": 23, "end_offset": 26, "label": "寬度"}]}
{"id": 21, "text": "N倪墨耕 倪墨耕-猴圖軸133X32", "relations": [], "entities": [{"id": 153, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 154, "start_offset": 9, "end_offset": 11, "label": "作品"}, {"id": 155, "start_offset": 12, "end_offset": 15, "label": "高度"}, {"id": 156, "start_offset": 16, "end_offset": 18, "label": "寬度"}]}
{"id": 22, "text": "F傅儒 傅儒 叢林遇雨圖 紙本55.2x132.8", "relations": [], "entities": [{"id": 168, "start_offset": 1, "end_offset": 3, "label": "作者"}, {"id": 169, "start_offset": 7, "end_offset": 12, "label": "作品"}, {"id": 170, "start_offset": 20, "end_offset": 25, "label": "高度"}, {"id": 171, "start_offset": 15, "end_offset": 19, "label": "寬度"}]}
{"id": 23, "text": "F傅小石 傅小石-人物圖軸 47×71", "relations": [], "entities": [{"id": 172, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 173, "start_offset": 9, "end_offset": 12, "label": "作品"}, {"id": 174, "start_offset": 17, "end_offset": 19, "label": "高度"}, {"id": 175, "start_offset": 14, "end_offset": 16, "label": "寬度"}]}
{"id": 24, "text": "F傅抱石 傅抱石 樹下獨飲 62×15", "relations": [], "entities": [{"id": 180, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 181, "start_offset": 9, "end_offset": 13, "label": "作品"}, {"id": 182, "start_offset": 17, "end_offset": 19, "label": "高度"}, {"id": 183, "start_offset": 14, "end_offset": 16, "label": "寬度"}]}
{"id": 25, "text": "F傅益瑤 傅益瑤-老翁聽松圖 94×48", "relations": [], "entities": [{"id": 184, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 185, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 186, "start_offset": 18, "end_offset": 20, "label": "高度"}, {"id": 187, "start_offset": 15, "end_offset": 17, "label": "寬度"}]}
{"id": 26, "text": "清 冷枚 百子圖 絹本40x200", "relations": [], "entities": [{"id": 189, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 190, "start_offset": 5, "end_offset": 8, "label": "作品"}, {"id": 191, "start_offset": 11, "end_offset": 13, "label": "高度"}, {"id": 192, "start_offset": 14, "end_offset": 17, "label": "寬度"}]}
{"id": 27, "text": "L劉中 劉中 斑馬ok 34X134", "relations": [], "entities": [{"id": 196, "start_offset": 1, "end_offset": 3, "label": "作者"}, {"id": 197, "start_offset": 7, "end_offset": 9, "label": "作品"}, {"id": 198, "start_offset": 15, "end_offset": 18, "label": "高度"}, {"id": 199, "start_offset": 12, "end_offset": 14, "label": "寬度"}]}
{"id": 28, "text": "L力踐61幅作品掃描 OKT 劉久亮 國色天香牡丹 137X68", "relations": [], "entities": [{"id": 201, "start_offset": 15, "end_offset": 18, "label": "作者"}, {"id": 202, "start_offset": 19, "end_offset": 25, "label": "作品"}, {"id": 203, "start_offset": 30, "end_offset": 32, "label": "高度"}, {"id": 204, "start_offset": 26, "end_offset": 29, "label": "寬度"}]}
{"id": 29, "text": "L劉伯年 劉伯年 柏樹圖軸 48X71", "relations": [], "entities": [{"id": 208, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 209, "start_offset": 9, "end_offset": 12, "label": "作品"}, {"id": 210, "start_offset": 17, "end_offset": 19, "label": "高度"}, {"id": 211, "start_offset": 14, "end_offset": 16, "label": "寬度"}]}
{"id": 30, "text": "劉俊_明 劉俊 漢殿論功圖 官網版 166.4x106cm 大都會博物館.jpg", "relations": [], "entities": [{"id": 212, "start_offset": 0, "end_offset": 2, "label": "作者"}, {"id": 213, "start_offset": 8, "end_offset": 13, "label": "作品"}, {"id": 214, "start_offset": 18, "end_offset": 23, "label": "高度"}, {"id": 215, "start_offset": 24, "end_offset": 27, "label": "寬度"}]}
{"id": 31, "text": "L劉國松 劉國松-正樹瀑布聲 72X23", "relations": [], "entities": [{"id": 224, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 225, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 226, "start_offset": 18, "end_offset": 20, "label": "高度"}, {"id": 227, "start_offset": 15, "end_offset": 17, "label": "寬度"}]}
{"id": 32, "text": "L劉奎齡 劉奎齡 關山春曉圖 紙137.4X66（天津博物館）", "relations": [], "entities": [{"id": 238, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 239, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 240, "start_offset": 16, "end_offset": 21, "label": "高度"}, {"id": 241, "start_offset": 22, "end_offset": 24, "label": "寬度"}]}
{"id": 33, "text": "宋 團扇 劉宗古 瑤臺步月圖絹本25.6x26.7故宮", "relations": [], "entities": [{"id": 242, "start_offset": 5, "end_offset": 8, "label": "作者"}, {"id": 243, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 244, "start_offset": 16, "end_offset": 20, "label": "高度"}, {"id": 245, "start_offset": 21, "end_offset": 25, "label": "寬度"}]}
{"id": 34, "text": "宋 劉寀 北宋 劉寀落花遊魚圖卷絹本26.4X252.2美國聖路易斯美術館", "relations": [], "entities": [{"id": 246, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 247, "start_offset": 10, "end_offset": 15, "label": "作品"}, {"id": 248, "start_offset": 18, "end_offset": 22, "label": "高度"}, {"id": 249, "start_offset": 23, "end_offset": 28, "label": "寬度"}]}
{"id": 35, "text": "L劉小敏 劉小敏 大悲觀音 80x154", "relations": [], "entities": [{"id": 250, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 251, "start_offset": 9, "end_offset": 13, "label": "作品"}, {"id": 252, "start_offset": 17, "end_offset": 20, "label": "高度"}, {"id": 253, "start_offset": 14, "end_offset": 16, "label": "寬度"}]}
{"id": 36, "text": "宋 劉履中 田畯醉歸圖 田畯醉歸圖(全卷)絹本28x188.4", "relations": [], "entities": [{"id": 254, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 255, "start_offset": 6, "end_offset": 11, "label": "作品"}, {"id": 256, "start_offset": 23, "end_offset": 25, "label": "高度"}, {"id": 257, "start_offset": 26, "end_offset": 31, "label": "寬度"}]}
{"id": 37, "text": "清 劉度 山水樓閣圖 紙本45X82.TIF", "relations": [], "entities": [{"id": 258, "start_offset": 2, "end_offset": 4, "label": "作者"}, {"id": 259, "start_offset": 5, "end_offset": 10, "label": "作品"}, {"id": 260, "start_offset": 16, "end_offset": 18, "label": "高度"}, {"id": 261, "start_offset": 13, "end_offset": 15, "label": "寬度"}]}
{"id": 38, "text": "清 劉彥沖 聽阮圖 聽阮圖紙本20.7x78.1 北京故宮", "relations": [], "entities": [{"id": 264, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 265, "start_offset": 6, "end_offset": 9, "label": "作品"}, {"id": 266, "start_offset": 15, "end_offset": 19, "label": "高度"}, {"id": 267, "start_offset": 20, "end_offset": 24, "label": "寬度"}]}
{"id": 39, "text": "劉松年_劉松年《博古圖》 絹本淡設色 縱128.3cm 橫56.6cm 藏臺北故宮.jpg", "relations": [], "entities": [{"id": 278, "start_offset": 0, "end_offset": 3, "label": "作者"}, {"id": 279, "start_offset": 8, "end_offset": 11, "label": "作品"}, {"id": 280, "start_offset": 20, "end_offset": 25, "label": "高度"}, {"id": 281, "start_offset": 29, "end_offset": 33, "label": "寬度"}]}
{"id": 40, "text": "L劉桂香 劉桂香 叢中笑（梅花）-138x69.5", "relations": [], "entities": [{"id": 282, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 283, "start_offset": 9, "end_offset": 12, "label": "作品"}, {"id": 284, "start_offset": 17, "end_offset": 20, "label": "高度"}, {"id": 285, "start_offset": 21, "end_offset": 25, "label": "寬度"}]}
{"id": 41, "text": "劉琰（明）_明 劉琰 騎馬遊山圖49x67.tif", "relations": [], "entities": [{"id": 302, "start_offset": 0, "end_offset": 2, "label": "作者"}, {"id": 303, "start_offset": 11, "end_offset": 16, "label": "作品"}, {"id": 304, "start_offset": 16, "end_offset": 18, "label": "高度"}, {"id": 305, "start_offset": 19, "end_offset": 21, "label": "寬度"}]}
{"id": 42, "text": "10 晚晴民國 1 劉石庵-書法軸126X57", "relations": [], "entities": [{"id": 308, "start_offset": 10, "end_offset": 13, "label": "作者"}, {"id": 309, "start_offset": 14, "end_offset": 16, "label": "作品"}, {"id": 310, "start_offset": 17, "end_offset": 20, "label": "高度"}, {"id": 311, "start_offset": 21, "end_offset": 23, "label": "寬度"}]}
{"id": 43, "text": "榮寶齋 近現代 劉繼卣 鍾馗圖軸紙本137x68", "relations": [], "entities": [{"id": 319, "start_offset": 8, "end_offset": 11, "label": "作者"}, {"id": 320, "start_offset": 12, "end_offset": 15, "label": "作品"}, {"id": 321, "start_offset": 18, "end_offset": 21, "label": "高度"}, {"id": 322, "start_offset": 22, "end_offset": 24, "label": "寬度"}]}
{"id": 44, "text": "L劉繼彪 劉繼彪 狗 29X29", "relations": [], "entities": [{"id": 323, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 324, "start_offset": 9, "end_offset": 10, "label": "作品"}, {"id": 325, "start_offset": 11, "end_offset": 13, "label": "高度"}, {"id": 326, "start_offset": 11, "end_offset": 13, "label": "寬度"}]}
{"id": 45, "text": "L劉繼鹵 劉繼鹵 少女26X51", "relations": [], "entities": [{"id": 327, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 328, "start_offset": 9, "end_offset": 11, "label": "作品"}, {"id": 329, "start_offset": 14, "end_offset": 16, "label": "高度"}, {"id": 330, "start_offset": 11, "end_offset": 13, "label": "寬度"}]}
{"id": 46, "text": "L劉茂善 劉茂善-江南水鄉圖軸 56X55", "relations": [], "entities": [{"id": 331, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 332, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 333, "start_offset": 19, "end_offset": 21, "label": "高度"}, {"id": 334, "start_offset": 16, "end_offset": 18, "label": "寬度"}]}
{"id": 47, "text": "L劉菊清 劉菊清 春眠不覺嘵 紙43X43", "relations": [], "entities": [{"id": 335, "start_offset": 1, "end_offset": 4, "label": "作者"}, {"id": 336, "start_offset": 9, "end_offset": 14, "label": "作品"}, {"id": 337, "start_offset": 16, "end_offset": 18, "label": "高度"}, {"id": 338, "start_offset": 16, "end_offset": 18, "label": "寬度"}]}
{"id": 48, "text": "清 勵宗萬 探雪圖卷27x249", "relations": [], "entities": [{"id": 344, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 345, "start_offset": 6, "end_offset": 9, "label": "作品"}, {"id": 346, "start_offset": 10, "end_offset": 12, "label": "高度"}, {"id": 347, "start_offset": 13, "end_offset": 16, "label": "寬度"}]}
{"id": 49, "text": "C成晋系列 NO.335-成晋系列6100-南海岩-母子 最終成品 南海岩-母子-125.5x69.5", "relations": [], "entities": [{"id": 351, "start_offset": 22, "end_offset": 25, "label": "作者"}, {"id": 352, "start_offset": 26, "end_offset": 28, "label": "作品"}, {"id": 353, "start_offset": 41, "end_offset": 46, "label": "高度"}, {"id": 354, "start_offset": 47, "end_offset": 51, "label": "寬度"}]}
{"id": 50, "text": "明 卞文瑜-秋窗讀易紙本26×108大都會", "relations": [], "entities": [{"id": 357, "start_offset": 2, "end_offset": 5, "label": "作者"}, {"id": 358, "start_offset": 6, "end_offset": 10, "label": "作品"}, {"id": 359, "start_offset": 12, "end_offset": 14, "label": "高度"}, {"id": 360, "start_offset": 15, "end_offset": 18, "label": "寬度"}]}
