### ISSUE TITLE
[Question]: map函数本地环境运行时报错

### ISSUE THREAD

**Issue by jackdong8588** [PaddlePaddle/PaddleNLP#4123]
### 请提出你的问题
![68d7585e2271a0d7e65f19f6c9644b3](https://user-images.githubusercontent.com/53993896/207776479-012fee69-a8fd-40c2-bd94-a7b24efe093a.png)

https://aistudio.baidu.com/aistudio/projectdetail/4944851项目中的源码在本地环境运行，运行到train_dataset = train_dataset_raw.map(convert_example_to_feature_train, batched=True, num_proc=4, remove_columns=column_names)代码时，出现不断重复无法打开错误，初步怀疑时map函数的本地环境配置问题。请解决。另，
![beaac177c13a94b6b7544b029f0bddf](https://user-images.githubusercontent.com/53993896/207775270-0a712b30-ba74-4433-897e-f35a21e572c5.png)
paddle是2.3.2，nlp是2.4.2。

**Comment by jackdong8588** [comment]
![68d7585e2271a0d7e65f19f6c9644b3](https://user-images.githubusercontent.com/53993896/207776370-29221288-f572-4549-9af5-3dcae56d5793.png)
运行时报错内容。

**Comment by lugimzzz** [comment]
> ![68d7585e2271a0d7e65f19f6c9644b3](https://user-images.githubusercontent.com/53993896/207776370-29221288-f572-4549-9af5-3dcae56d5793.png) 运行时报错内容。

贴一下完整的报错内容，包含所有报错内容

**Comment by jackdong8588** [comment]
一直重复相同的内容，不停止。

**Comment by lugimzzz** [comment]
看了一下是errno 22 错误，应该是你的路径中包含了特殊符号，建议文件名和路径不要包含下列任何字符：\ / : * ? " < > | 。我看你路径中包含<>的符号

**Comment by jackdong8588** [comment]
![image](https://user-images.githubusercontent.com/53993896/207779405-2935ced8-a60d-4ad7-91e3-46d146740737.png)

**Comment by lugimzzz** [comment]
你看看[这个链接](https://stackoverflow.com/questions/61916606/python-multiprocessing-pool-oserror-errno-22-invalid-argument)能不能解决你的问题，把代码放在下运行 if __name__ == '__main__':
![image](https://user-images.githubusercontent.com/63761690/207786548-e46309c5-0c7c-4dbd-b37d-63de11c2ad03.png)

**Comment by lugimzzz** [comment]
你搜索一下网上与报错`with io.open_code(decoded path) as f oserror errno 22 invalid argument`相关的解决方式都尝试一下，因为这是你运行环境有关，我们也不方便复现相关问题

**Comment by jackdong8588** [comment]
我感觉你们是不是在本机上也试跑跑，不可能所有项目都只在云上用呐

**Comment by lugimzzz** [comment]
这么使用，看是否还报错
![image](https://user-images.githubusercontent.com/63761690/207801151-a94cface-e261-4e8e-b9d4-e5a9a15fefca.png)

**Comment by jackdong8588** [comment]
按照lugim的解决方案，问题已解决。把执行代码，map的那行放在main里面执行。
