### ISSUE TITLE
请问simbert的原始tensorflow模型转成paddle有现成的工具吗？

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleNLP#4125]
### 请提出你的问题

（1）simbert中使用的模型是simber-base-chinese，请问这个模型是从https://github.com/ZhuiyiTechnology/simbert这边的模型直接转成paddle格式的吗？
（2）如果是转过来直接用的， 转完有重新finetune训练吗？
（3）如果是转过来直接用的，有现成的转换工具可以用吗？

**Comment by wawltor** [comment]
simbert-base-chinese 已经集成在PaddleNLP

```python
from paddlenlp.transformers import  AutoModel
model = AutoModel.from_pretrained("simbert-base-chinese", pool_act="linear")
```

**Comment by xdg2016** [comment]
谢谢，这个我已经用过了，我想问下，这个模型是怎么转成paddle模型的，我想转一下另外几个比较小的版本，请问有工具吗

**Comment by wawltor** [comment]
> 谢谢，这个我已经用过了，我想问下，这个模型是怎么转成paddle模型的，我想转一下另外几个比较小的版本，请问有工具吗

我们也工具可以进行转化，但是工具还没有完善，没有相关文档，不建议使用 ；或者你可以提供模型地址 我们判断一下转化成本

**Comment by xdg2016** [comment]
按道理simbert-base-chinese如果可以转换，那么对应的small版本和tiny版本应该也可以转，只是层数：
https://github.com/ZhuiyiTechnology/pretrained-models
![image](https://user-images.githubusercontent.com/16351823/207846258-c644fee0-b9d2-4942-9820-97168e96519b.png)

**Comment by wj-Mcat** [comment]
simbert 底座模型是属于 bert 模型，目前可使用 converter 对权重进行转化，示例代码如下所示：

```python
from transformers import BertModel, BertTokenizer

input_dir = "./pretrained_models/pytorch"
output_dir = "./pretrained_models/paddle"

BertModel.from_pretrained("peterchou/simbert-chinese-base").save_pretrained(input_dir)
BertTokenizer.from_pretrained("peterchou/simbert-chinese-base").save_pretrained(output_dir)

from paddlenlp.transformers import BertConverter, BertModel, BertTokenizer
# from paddlenlp.transformers import ElectraConverter, RobertaConverter, XLNetConverter, BertConverter

converter = BertConverter()
converter.convert(
    input_dir=input_dir,
    output_dir=output_dir
)

model = BertModel.from_pretrained(output_dir)
tokenizer = BertTokenizer.from_pretrained(output_dir)
```

当然上面的代码只是支持pytorch 的模型，tensorflow 的模型暂不支持：tensorflow 有的 pytorch 都有。

**Comment by w5688414** [comment]
您好，目前没有直接可用的工具，不过提供一下思路，您可以先把tf模型转换成pytorch，最后转换成paddle的模型

**Comment by wj-Mcat** [comment]
bert 转化的脚本网上一大堆，你可以自己搜索一下，很简单，就比如 huggingface 官方就提供了对应的脚本：https://github.com/huggingface/transformers/tree/main/src/transformers/models/bert。

我们把工具提供给你们，转化的工作肯定是你们自己来的。

**Comment by xdg2016** [comment]
谢谢@wj-Mcat @w5688414 我试试

**Comment by wj-Mcat** [comment]
有任何转化过程中的问题欢迎在这里讨论，同时也欢迎参与`Converter`的贡献。
