### ISSUE TITLE
请问Pegasus是否支持用在长文本摘要生成上？

### ISSUE THREAD

**Issue by SecretSsh** [PaddlePaddle/PaddleNLP#4136]
### Feature request

您好，请问Pegasus的输入文本字数是否由参数max_seq_len决定？

### Motivation

我想在2000字的长文本上做摘要生成测试。

### Your contribution

除了将长文本分段（这会影响内容的连续性），调整max_seq_len的值，请问还有什么能改进的方法吗？非常感谢。

**Comment by wawltor** [comment]
有max_seq_len决定，目前Pegasus发布出来的模型支持最大长度是1024

**Comment by SecretSsh** [comment]
感谢您的回复

**Comment by wawltor** [comment]
我们暂时关闭issue，如有疑问可以随时打开issue，谢谢！
