### ISSUE TITLE
[Bug]: codegen的python补全有时会缺少回车

### ISSUE THREAD

**Issue by allendred** [PaddlePaddle/PaddleNLP#4144]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.1.post112
- paddlenlp: 2.4.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
我在使用codegen mono-2b的模型,使用了fauxpilot的vscode的插件,我发现补全代码python代码的时候,有时候会缺少回车,我在使用huggingface 的模型仓库的 mono-2b模型时并没有出现相同的问题,为了解决这个问题我使用了正则表达式来解决


import re
regex = re.compile("     +")
output = regex.sub(lambda s: ('\n'+s.group(0)), output)
```
我不太确定这适用于所有场景,也不太清楚为什么会产生这种不同,请问这有可能是什么导致的？非常感谢。
```


### 稳定复现步骤 & 代码

类似的代码
```
class Net(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()

错误发生的图片
<img width="705" alt="image" src="https://user-images.githubusercontent.com/4343664/208098497-544106e1-431a-45c8-9c75-661cb5ab2e63.png">

**Comment by sijunhe** [comment]
感谢您的反馈！ 麻烦 @gongel 看下

**Comment by gongel** [comment]
和HF相比，二者的生成超参是一致的吗？比如解码方式，如果是sampling会存在随机性

**Comment by allendred** [comment]
> 和HF相比，二者的生成超参是一致的吗？比如解码方式，如果是sampling会存在随机性

这是paddle generate的设置
```
class DefaultConfig:
    model_name_or_path = "Salesforce/codegen-2B-mono"
    device = "gpu"
    temperature = 0.5
    top_k = 10
    top_p = 1.0
    repetition_penalty = 1.0
    min_length = 0
    max_length = 16
    decode_strategy = "greedy_search"
    load_state_as_np = True
    use_faster = True
    use_fp16_decoding = True
    default_dtype = "float16" if use_faster and use_fp16_decoding else "float32"
```
使用了 `greedy_search` 

以下是HF的代码,将sample设置为Fasle也是一样的
```
input_ids = tokenizer(text, return_tensors="pt").input_ids
generated_ids = model.generate(input_ids, do_sample=False, max_new_tokens=16)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True,
                       spaces_between_special_tokens=True))
```

**Comment by tutuxxx** [comment]
@allendred @gongel  请问这个问题解决了吗，我这边用几种语言尝试都有缺少换行的问题
