### ISSUE TITLE
阅读理解数据预处理，cpu版本正常，GPU出现 AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'

### ISSUE THREAD

**Issue by 0sxw0** [PaddlePaddle/PaddleNLP#4146]
阅读理解数据预处理，cpu2.3.2版本正常，paddle-GPU2.3.2出现 AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'
由于输入数据是dict类型，所以数据导入用的是datasets.Dataset.from_dict(res_dict)
    res_dict = {
        "id": ["0", "1", "2"],
        "question": ["崂山在哪", "崂山在哪", "崂山在哪"],
        "context": [
            "东、南濒黄海，西邻青岛市市南区、市北区，西北邻李沧区，北接青岛市城阳区和即墨区。辖区陆域面积395.8平方公里，海域面积3700平方公里，海岸线长103.7公里【摘要】崂山在青岛哪里【提问】您好！崂山区是山东省青岛市辖区...",
            "1994年2月，被列为全国15个副省级城市之一（其中省会十个，非省会五个）。2008年末全市户籍总人口为761.56万人，其中市区1159平方公里，人口276.25万人；五市（县级）485.3万人。 特产：崂山石、\"西施舌\"海贝、胶州湾...",
            "崂山景区为国家级风景名胜区、国家AAAAA级旅游景区、国家级森林公园、爱国主义教育基地。崂山古称牢山、劳山。坐落在山东半岛的东南，西靠青岛，东南两面濒临黄海。面积386平方公里，崂顶巨峰，海拔1，133米。既是中国道教名山，..."]
    }
请问我是否该修改数据加载的方法，用何种方法合适？

**Comment by Eason-zz** [comment]
你好请问你这个问题解决了吗
