### ISSUE TITLE
Are video diffusion models available?

### ISSUE THREAD

**Issue by zzwei1** [PaddlePaddle/PaddleNLP#4149]
### Feature request

https://arxiv.org/abs/2204.03458
https://arxiv.org/abs/2206.07696
https://openreview.net/forum?id=hX5Ia-ION8Y
https://arxiv.org/abs/2211.13221

### Motivation

Extend diffusion models to video, for video generation, video prediction, video infilling.

### Your contribution

Sorry, No.

**Comment by westfish** [comment]
It will come out soon
