### ISSUE TITLE
paddleNLP单机本地化部署

### ISSUE THREAD

**Issue by jackdong8588** [PaddlePaddle/PaddleNLP#4150]
### 请提出你的问题

我已经开发好了推理模型，在nlp说明文件里面只有服务器版本的部署，能不能提供pyinstaller打包成exe的方案？针对普通的cpu机器和有GPU的机器提供不同打包版本的exe打包说明，看看需要安装哪些基础包，总体积大小多少等等？

**Comment by w5688414** [comment]
这些指标目前没有，不过可以参考一下paddleOCR使用pyinstaller打包为本地离线可执行程序. https://blog.csdn.net/weixin_47764730/article/details/114042436

**Comment by yaleimeng** [comment]
在本机部署一个服务器和一个客户端就可以了。打包exe应该是吃力不讨好。
