### ISSUE TITLE
[Question]: 定向ft inpainting模型？

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#4158]
### 请提出你的问题

普通版本的sd模型可以通过dreambooth、textual 等工具进行定向fine-tuning，但是inpainting版和普通版的模型结构是不太一样的？如果直接套用上述工具是无法进行模型加载的。但是如果用原版模型进行文字引导绘制又无法将需要定制放置的东西融入模型里。

目前有可以用于inpainting版本模型的fine-tuning的工具存在吗？

**Comment by JunnYu** [comment]
目前我看HF有这个训练代码 https://github.com/huggingface/diffusers/tree/main/examples/research_projects/dreambooth_inpaint 
你可以仿照着这里的代码，改写成paddle代码，也欢迎你将paddle版的这里代码贡献到ppdiffusers（最近我可能没有时间改这个）。
