### ISSUE TITLE
[Bug]:PaddleNLP SimpleServing 的服务化多卡部署，查看显卡占用情况只调用了一张显卡

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleNLP#4169]
### 请提出你的问题

代码使用dev分支的最新代码
paddlenlp 引入的版本为2.4.5
![image](https://user-images.githubusercontent.com/36221128/208605272-f382b869-4fb0-4cc4-909b-f0cf46b13936.png)
设置多卡服务化代码如下：
![image](https://user-images.githubusercontent.com/36221128/208605533-ac7d6e20-963e-4d40-88b7-7b8807a60354.png)
服务化启动命令为：
paddlenlp server server:app --workers 1 --host 0.0.0.0 --port 8190
启动成功后，看调用日志的输出如下图，应该是分别调用在了不同的显卡上
![e1ea419fafc476f7a690527a9813985](https://user-images.githubusercontent.com/36221128/208605816-c325419e-b918-410d-a921-937f27cb9bba.png)
但是为何使用nvidia-smi查看显卡使用情况时，只使用了其中的一张显卡
![a5b7898a4302e0ff7ca887b3a391169](https://user-images.githubusercontent.com/36221128/208606048-eb085451-03ed-459e-a11d-5a08d9093218.png)

**Comment by JunnYu** [comment]
『但是为何使用nvidia-smi查看显卡使用情况时，只使用了其中的一张显卡』，关于这个问题，建议你可以每隔1s查看gpu的使用情况，命令 `watch -n 1 nvidia-smi`。

**Comment by LANSEYOUYUMOWANG** [comment]
启动时接收服务化的进程数workers设置为2
paddlenlp server server:app --workers 2 --host 0.0.0.0 --port 8190
服务启动后，拿 jmeter 持续压测，GPU 使用 watch -n 1 nvidia-smi 动态监控，仍然只有一个显卡被使用
![d1d43313cf0aab9e0c7ba7f48196db9](https://user-images.githubusercontent.com/36221128/209032097-bfc23580-1eab-406b-b19e-adc2d2e0173d.png)
![c448ce09985570b7ab075846bb768d2](https://user-images.githubusercontent.com/36221128/209032119-e060ee41-27bb-4caa-b589-3b1939d55bbd.png)
![ee2298db73caaf939a2d52b1afc8b16](https://user-images.githubusercontent.com/36221128/209032131-f5e2037b-9ef8-49bb-a0eb-418d87f40a79.png)
![image](https://user-images.githubusercontent.com/36221128/209032178-6cc1971e-f015-4cf0-b568-793e7ee57799.png)
![image](https://user-images.githubusercontent.com/36221128/209032193-02f3120d-d9fa-4365-9af8-49c8e0a90b77.png)

**Comment by wawltor** [comment]
经过测试，两种卡都是可以的，你把 watch -n 0.1 nvidia-smi  
<img width="572" alt="image" src="https://user-images.githubusercontent.com/16698950/209309250-0b5bb6b2-1bee-4a7f-b31f-d3815675ed9b.png">

**Comment by LANSEYOUYUMOWANG** [comment]
我使用 watch -n 0.1 nvidia-smi，还是不行，是不是因为我使用docker容易的原因
![image](https://user-images.githubusercontent.com/36221128/209765707-7b5333e6-aefc-4b9d-a24e-b3604f9a88c9.png)

**Comment by LANSEYOUYUMOWANG** [comment]
换了高算力的服务器，该问题解决
