### ISSUE TITLE
[Question]: 在使用UIE时报错“NameError: name 'Tensor' is not defined”

### ISSUE THREAD

**Issue by adureychloe** [PaddlePaddle/PaddleNLP#4171]
### 请提出你的问题

运行的是aistudio官网的UIE项目：《PaddleNLP信息抽取技术重磅升级！开放域信息抽取来了！三行代码用起来》，
已经更新paddlenlp至最新版并重启环境，
代码是：
```python
from paddlenlp import Taskflow 
schema = ['姓名', '毕业院校', '职位', '月收入', '身体状况']
ie = Taskflow('information_extraction', schema=schema)
```
报错图片：
<img width="910" alt="截屏2022-12-20 15 50 24" src="https://user-images.githubusercontent.com/31687386/208612559-0cede16d-97ef-4c6a-840b-78d84c01f71b.png">
<img width="1052" alt="截屏2022-12-20 15 50 41" src="https://user-images.githubusercontent.com/31687386/208612595-f4365465-f13b-4e95-a2dd-a9302520fbc7.png">

<img width="732" alt="截屏2022-12-20 15 50 47" src="https://user-images.githubusercontent.com/31687386/208612630-bbe9e51c-0e96-46d1-be27-327275d1dbde.png">

**Comment by jingsongliujing** [comment]
感觉是paddle版本不对

**Comment by adureychloe** [comment]
> 感觉是paddle版本不对

更新了paddle版本，问题解决。感谢🙏
