### ISSUE TITLE
[Question]: 文本分类模型输出模型判断关键词

### ISSUE THREAD

**Issue by hxyghostor** [PaddlePaddle/PaddleNLP#4172]
### 请提出你的问题

使用的是ERNIE3.0模型进行文本分类，我想知道这个模型是根据句子中的哪些字词进行分类判断的，要如何输出？谢谢！

**Comment by lugimzzz** [comment]
你好，可以参考单词级别的可解释性，应该是你要的功能 
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_class/analysis/word_interpret.ipynb
![image](https://user-images.githubusercontent.com/63761690/208638067-4273bbb6-8d14-4d4d-aade-b59c94c69a15.png)
