### ISSUE TITLE
uie的taskflow实例化时不指定schema而是在执行taskflow指定

### ISSUE THREAD

**Issue by hehuang139** [PaddlePaddle/PaddleNLP#4173]
### Feature request

目前的uie的taskflow需要提前指定schema，希望支持执行提取时在指定schema

### Motivation

举个例子，通过rocketqa在大文本中定位答案页，在uie提取，这时问题是不固定的

### Your contribution

这点在serving上也同样存在

**Comment by hehuang139** [comment]
看了下issues列表，发现有一个set_schema可以重置schema，我先试下

**Comment by hehuang139** [comment]
我发现这个方法不太可行，因为在并发请求的情况下，set_schema会有问题，是否能够吧schema作为参数和原始参数一起传入，支持并发访问的能力

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md 

安装develop版本的PaddleNLP
<img width="843" alt="image" src="https://user-images.githubusercontent.com/16698950/208638644-8fa53cbf-aa3e-4d50-b1e9-00f4de08b5ca.png">

**Comment by hehuang139** [comment]
@wawltor information_extraction的taskflow是否支持，因为我serving服务需要做一些数据处理，目前使用flask + taskflow来实现

**Comment by wawltor** [comment]
> @wawltor information_extraction的taskflow是否支持，因为我serving服务需要做一些数据处理，目前使用flask + taskflow来实现

Taskflow的set_schema接口是支持的，你可以通过把POST参数传递方式传过去即可实现，simple_serving也是同样的方式实现，建议使用SimpleServing，这个是FastAPI + Taskflow来实现的

**Comment by hehuang139** [comment]
@wawltor 并发访问是否有问题，

举个时序
time 1 A请求set_schema(schema_a) 
time 2 B 请求set_schema(schema_b)
time 3 A 执行提取
time 4 B执行提取
由于set_schema和提取不是原子的，这种情况是否A的schema会被重置为B请求的schema

**Comment by wawltor** [comment]
> @wawltor 并发访问是否有问题，
> 
> 举个时序 time 1 A请求set_schema(schema_a) time 2 B 请求set_schema(schema_b) time 3 A 执行提取 time 4 B执行提取 由于set_schema和提取不是原子的，这种情况是否A的schema会被重置为B请求的schema

不做并发并发访问有问题，可以去使用simple_serving，相关工作已经集成好

**Comment by hehuang139** [comment]
@wawltor 是指simple_serving 已经支持并发访问了吗？

**Comment by wawltor** [comment]
> @wawltor 是指simple_serving 已经支持并发访问了吗？

支持
