### ISSUE TITLE
 当data.txt中的 测试样本数目大于batch_size时， 会报错

### ISSUE THREAD

**Issue by PrayChen** [PaddlePaddle/PaddleNLP#4174]
https://github.com/PaddlePaddle/PaddleNLP/blob/f8d36ed274d3986e669feca03e5f07c4b896a72d/applications/text_classification/multi_label/few-shot/infer.py#L227

当data.txt中的 测试样本数目大于batch_size时， 会报错

infer.py", line 188, in infer_batch
    infer_data[i] = np.concatenate(infer_data[i], axis=0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 94 and the array at index 1 has size 112
(pp-nlp24) fyt@localhost: /home/storage/czq_bak/test/sentence_classification 17:52:09
$ ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 94 and the array at index 1 has size 112

**Comment by LemonNoel** [comment]
可以贴下 paddle 和 paddlenlp 版本、运行脚本和数据格式吗？我尝试复现一下
