### ISSUE TITLE
[Question]: UIE 使用finetune.py训练数据集时，报错forward() got an unexpected keyword argument 'pos_ids'

### ISSUE THREAD

**Issue by HysUnknown** [PaddlePaddle/PaddleNLP#4176]
### 请提出你的问题

我在使用UIE 的finetune.py 训练doccano的数据集时提示TypeError: forward() got an unexpected keyword argument 'pos_ids'
请问怎么解决呢？
运行脚本参数（使用的是官网数据以及实例代码）：
python finetune.py --device gpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 42 --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_length 512 --per_device_eval_batch_size 16 --per_device_train_batch_size 16 --num_train_epochs 20 --learning_rate 1e-5 --label_names 'start_positions' 'end_positions' --do_train --do_eval --do_export --export_model_dir ./checkpoint/model_best --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1
错误如下：
Traceback (most recent call last):
  File "F:\dev\project\py\PaddleNLP-2.4.5\model_zoo\uie\finetune.py", line 246, in <module>
    main()
  File "F:\dev\project\py\PaddleNLP-2.4.5\model_zoo\uie\finetune.py", line 185, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "D:\software\Anaconda3\lib\site-packages\paddlenlp\trainer\trainer.py", line 614, in train
    tr_loss_step = self.training_step(model, inputs)
  File "D:\software\Anaconda3\lib\site-packages\paddlenlp\trainer\trainer.py", line 1253, in training_step
    loss = self.compute_loss(model, inputs)
  File "D:\software\Anaconda3\lib\site-packages\paddlenlp\trainer\trainer.py", line 1215, in compute_loss
    outputs = model(**inputs)
  File "D:\software\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
TypeError: forward() got an unexpected keyword argument 'pos_ids'

**Comment by linjieccc** [comment]
@HysUnknown Hi，

可以拉一下最新的develop分支的代码再试下

**Comment by HysUnknown** [comment]
> @HysUnknown Hi，
> 
> 可以拉一下最新的develop分支的代码再试下

@linjieccc 我拉的已经是最新的了。还是报TypeError: forward() got an unexpected keyword argument 'pos_ids'

**Comment by linjieccc** [comment]
试下用develop的zip包，https://github.com/PaddlePaddle/PaddleNLP/archive/refs/heads/develop.zip

**Comment by HysUnknown** [comment]
> 试下用develop的zip包，https://github.com/PaddlePaddle/PaddleNLP/archive/refs/heads/develop.zip

@linjieccc 解决了，但是为什么训练完成后没有输出模型呢，只输出了部分日志文件？脚本是有do_export输出模型参数的。
脚本参数：
`python finetune.py --device gpu --logging_steps 10 --sa
ve_steps 100 --eval_steps 100 --seed 42 --model_name_or_path uie-base --output_dir ./checkpoint/model_best --tra
in_path data/train.txt --dev_path data/dev.txt --max_seq_length 512 --per_device_eval_batch_size 16 --per_device
_train_batch_size 16 --num_train_epochs 20 --learning_rate 1e-5  --do_train True --do_eval True --do_export True
  --export_model_dir ./checkpoint/model_best --overwrite_output_dir --disable_tqdm True --metric_for_best_model
eval_f1 --load_best_model_at_end True --save_total_limit 1
`
![微信截图_20221220215837](https://user-images.githubusercontent.com/39686680/208684632-17fc63fc-68f5-4638-8827-c096db4a62a4.png)
![image](https://user-images.githubusercontent.com/39686680/208684497-140c45ad-932e-44d0-b63e-fd5684916f8b.png)

**Comment by linjieccc** [comment]
执行下面的命令看下paddle是否安装成功

```python
import paddle 
paddle.utils.run_check()
```

**Comment by HysUnknown** [comment]
> 执行下面的命令看下paddle是否安装成功
> 
> ```python
> import paddle 
> paddle.utils.run_check()
> ```

@linjieccc 肯定是成功的。
![微信截图_20221220223050](https://user-images.githubusercontent.com/39686680/208691446-1d6ccfa1-3010-410d-a865-61daaed497a7.png)
paddle是2.4.1-gpu版本的
![image](https://user-images.githubusercontent.com/39686680/208691762-b77694b2-ce9c-475e-8249-59a4ea49cc34.png)
![image](https://user-images.githubusercontent.com/39686680/208692453-2ed6caf2-2544-4eb0-881b-e8460dad3e76.png)

**Comment by linjieccc** [comment]
你的scipy版本是多少？

**Comment by HysUnknown** [comment]
> 

@linjieccc numpy 是1.20.3 ，scipy是1.7.1

**Comment by linjieccc** [comment]
试下升级scipy到1.7.3版本看能否解决问题

**Comment by HysUnknown** [comment]
> 

@linjieccc scipy升级到1.7.3了，还是不行，只输出了日志文件

**Comment by linjieccc** [comment]
把batch_size调小试下 --per_device_train_batch_size这个参数

**Comment by HysUnknown** [comment]
> 把batch_size调小试下 --per_device_train_batch_size这个参数

可以训练了，谢谢！
