### ISSUE TITLE
[Question]: 使用UIE进行finetune.py时出现tokenizing是[UNK]的情况，导致异常

### ISSUE THREAD

**Issue by kevinva** [PaddlePaddle/PaddleNLP#4184]
### 请提出你的问题

原句是”你栓条链⼦你就能安静的多你这废物来送妈也不看看⾃⼰的⺠⼯爹挥汗如⾬的惨状还是得我⽤意念⼀巴掌扇进你妈的狗头扭转乾坤"，识别“挥汗如雨”的“雨”字时出现[UNK]，查了以下词表（uie-base/vocab.txt），“雨”字也是有的，不知为啥还会出现这种情况？
![截屏2022-12-21 上午10 00 29](https://user-images.githubusercontent.com/1279449/208808279-ae2865de-951a-4aa8-8e13-536a7a9bdce5.png)

使用版本：PaddleNLPv2.4.0
系统：Ubuntu
硬件：cuda 11.2，cudnn 8.1

**Comment by wj-Mcat** [comment]
我这边确实发现你例子当中的“雨”不是正常的雨，测试代码如下：

```python
from paddlenlp.transformers import AutoTokenizer, PretrainedTokenizer
tokenizer: PretrainedTokenizer = AutoTokenizer.from_pretrained("ernie-3.0-base-zh")
print(tokenizer.convert_ids_to_tokens(39979))
# 从上面例子中 copy 过来的字符
a = "⾬"

# 用键盘输入的字符
b = "雨"
assert a != b
print(tokenizer(a))
print(tokenizer(b))
```

这是以上问题的复现代码，具体解决方案还在 排查，你也可以尝试从中文字符编码的角度来解决此问题。

**Comment by wj-Mcat** [comment]
针对于这种长得一致的特殊字符问题，建议你在`convert_example_to_feature`这块特殊处理（替换）一下就行了，如果没有其他问题，稍后可关闭此 issue。

**Comment by kevinva** [comment]
好的，感谢
