### ISSUE TITLE
[Question]: `paddle.jit.to_static ` 在转静态模型时，对第一个非使用的变量怎么定义？

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#4185]
### 请提出你的问题

模型网络输入变量的定义 ：def forward(query=None, query_repr=None, title_repr=None, title=None)，
具体使用时是需要：
 1. 在训练时输入query和title输出两者相似度；
 2. 在离线时是输入query输出query向量；   
 3. 在线预测时输入query_repr和title_repr输出两者相似度； 
model = paddle.jit.to_static(
        model,
        input_spec=[
            None,  # query_id
            paddle.static.InputSpec(shape=[None, None], dtype="float32"),  # query_embedding
            paddle.static.InputSpec(shape=[None, None], dtype="float32"),  # title_embedding
        ],
    )

现在的问题是 在转换predict静态模型时，👆的转换代码哪里有问题？

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 模型网络输入变量的定义 ：def forward(query=None, query_repr=None, title_repr=None, title=None)， 具体使用时是需要：
> 
> 1. 在训练时输入query和title输出两者相似度；
> 2. 在离线时是输入query输出query向量；
> 3. 在线预测时输入query_repr和title_repr输出两者相似度；
>    model = paddle.jit.to_static(
>    model,
>    input_spec=[
>    None,  # query_id
>    paddle.static.InputSpec(shape=[None, None], dtype="float32"),  # query_embedding
>    paddle.static.InputSpec(shape=[None, None], dtype="float32"),  # title_embedding
>    ],
>    )
> 
> 现在的问题是 在转换predict静态模型时，👆的转换代码哪里有问题？

请问您使用的是哪个模型？
