### ISSUE TITLE
[Question]:  Is it possible to do coreference resolution for custom NER model entities?

### ISSUE THREAD

**Issue by Tanmay98** [PaddlePaddle/PaddleNLP#4188]
### 请提出你的问题

Thanks for making paddleOCR tool, it is really awesome.
I am interested in implementing coreference resolution for my NER model.

Presently, I have my custom NER model build in spacy. I want to implement coreference resolution for my custom NER entitites. I already have annotated my own dataset for it since I tried implementing Coreferee(by Explosion).

I just want to ask if finetuning coreference resolution model for custom NER model is possible in PaddleNLP?

Thanks in advance!

**Comment by linjieccc** [comment]
@Tanmay98 Hi，

I think you can finetune your coreference resolution model use [UIE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text) in a way similar to relation extraction.

We will provide English documents in recent days. I hope it will be helpful to you.
