### ISSUE TITLE
Question about fintune LayoutModel

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleNLP#4191]
[Question] about: "Fintune layoutml with other language"
Thank for great repo.
I want to fintune layoutml with ```vi-layoutxlm-base-uncased``` architecture portugal lang.
I am very thankfull if you can give step by step to fintune or give the documents fintune.
One more times, many thanks.

**Comment by linjieccc** [comment]
@phamkhactu Hi,

What is the downstream task?

**Comment by phamkhactu** [comment]
> @phamkhactu Hi,
> 
> What is the downstream task?

hi @linjieccc, I want to fintune [SER](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README.md#31-ser) task. After some research, I found out that: if I want to fintune ser, I need to fintune LayoutXLMModel, and if want to fintune  LayoutXLMModel I must fintue LayoutXLMTokenizer. So I my opinion, I need fintune LayoutXLMTokenizer before and after that LayoutXLMModel. I am sorry if I wrong.
At that time I want to fintune **vi-layoutxlm-base-uncased**. It combines from both(In my thought)
I very happy if you give me guide to solve it or help me can combine LayoutXLMTokenizer and LayoutXLMModel
Thank you.
