### ISSUE TITLE
[Question]: 请问finetune.py的文本最大切分长度max_seq_len是多少呢？因为训练文本长度最长是5602，我设置了5602就报错了

### ISSUE THREAD

**Issue by HysUnknown** [PaddlePaddle/PaddleNLP#4197]
### 请提出你的问题

请问finetune.py的文本最大切分长度max_seq_len是多少呢？因为训练文本长度最长是5602，我设置了5602就报错了
![image](https://user-images.githubusercontent.com/39686680/209047004-baa4d0bc-d9bc-4175-8422-0097f32157b2.png)

脚本内容：
`python finetune.py --device gpu --logging_steps 10 --save_steps 100 --eval_steps 100 --seed 42 --model_name_or_path uie-base --output_dir ./checkpoint/model_best --train_path data/train.txt --dev_path data/dev.txt --max_seq_length 5602 --per_device_eval_batch_size 8 --per_device_train_batch_size 8 --num_train_epochs 50 --learning_rate 1e-5  --do_train --do_eval --do_export --do_predict --export_model_dir ./checkpoint/model_best --overwrite_output_dir --disable_tqdm True --metric_for_best_model eval_f1 --load_best_model_at_end True --save_total_limit 1 --report_to visualdl`

报错内容：
`OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__
CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution an
d advice about CUDA Error.] (at ..\paddle\phi\backends\gpu\cuda\cuda_info.cc:259)

During handling of the above exception, another exception occurred:
`
`    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "D:\software\Anaconda3\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py", line 705, in co
nvert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True'
'truncation=True' to have batched tensors with the same length.
`
`OSError: (External) CUBLAS error(1).
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasst
atus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at ..\paddle\phi\backends\gpu\gpu_res
ources.cc:156)`

**Comment by wawltor** [comment]
max_seq_len最大的长度是2048，如果超过了max_seq_len会自动对样本进行切分
