### ISSUE TITLE
UIE-X中Doc.Parser功能建议添加推理结果文本在原图的Hover

### ISSUE THREAD

**Issue by TracyWang95** [PaddlePaddle/PaddleNLP#4198]
### Feature request

目前使用DocParser.write_image_with_results函数时，推理结果可视化仅被带颜色的方框图像框出，建议添加推理文字结果的hover悬浮于着色框之上。

### Motivation

如此一来，方便业务部门（基于PaddleNLP开发软件的使用者）快速进行推理结果的核验。

### Your contribution

可以提供数据样例。

**Comment by linjieccc** [comment]
@TracyWang95 Hi，

感谢建议，我们后续会考虑优化渲染相关的使用体验
