### ISSUE TITLE
PaddleNLP/applications/information_extraction/document/ uie-x 训练集拟合不充分

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#4204]
### 软件环境

```Markdown
- paddlepaddle:2.4
- paddlepaddle-gpu: 2.4
- paddlenlp: 2.4.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

官方原始数据和代码，用官方的训练集数据直接作为验证集数据，训练模型，发现验证集的结果p/c/f达不到100%，最好大概90%多，按理一般都是在训练集上要100%拟合才能说明模型或者数据预处理本身没问题，目前说明模型不能完全拟合自己训练的数据集，是不是数据集本身有问题或者模型的拟合度不够，能否验证下，找下原因，谢谢。

### 稳定复现步骤 & 代码

按照官方步骤，把原始生成的验证集dev删除了，把原始训练集train,复制粘贴一份，然后把名字改成dev即可验证

**Comment by lugimzzz** [comment]
没有模型一定能拟合训练集到100%的说法吧

**Comment by AI-Mart** [comment]
是没有这个说法，如果模型本身有问题，或者拟和能力有限，或者本身训练的数据集有问题，自然拟和不到100% 。
如果训练集都不能完全拟和，要么就是模型有问题，要么就是数据集有问题，这时应该针对不能拟和的数据做针对性分析，这是提升整个方案效果的一种思路。只有训练阶段已经非常好，部署预测效果才能有把握。

**Comment by AI-Mart** [comment]
大佬可以试验下，看看是哪里出问题了，是模型算法本身的缺陷，还是数据预处理的问题，然后给个解决方案建议

**Comment by lugimzzz** [comment]
如你所说，存在很多原因导致准确率不是100%，这在深度学习训练过程中是非常常见的现象，我们通常也更关注在开发集的表现而非训练集。提供数据集旨在提供一个使用UIE-X的范例，对于本数据集或其他自标注数据相似问题，你可以尝试打印bad case分析、分析ocr结果是否有错、或标注错误等方面去分析。

**Comment by AI-Mart** [comment]
会去分析的，不过对于开源一个优秀的产业化落地方案的角度来说，建议你们也尝试下哈。更关注开发集的表现的前提，个人认为应该是在训练集没问题的情况下，假如有问题，也要非常清楚是哪里出了问题。举个例子，假如手头只标注了10条数据，结果训练集的准确率只有90%，其中一条数据怎么也拟合不了，这时候肯定要分析这条不能拟合的数据，即使验证集能达到100%也是不能说明问题，可能验证集的数据刚好来自模型能拟合的那90%的那部分数据，所以那一条不能拟合的数据本身非常宝贵，值得分析的。
