### ISSUE TITLE
[Question]: 是否可以在ppdiffusers中支持Karlo的中文版模型

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#4210]
### 请提出你的问题

目前该模型对人物面部特征支持的比较好https://github.com/kakaobrain/karlo

**Comment by JunnYu** [comment]
目前正在更新最新的ppdiffusers，在新的ppdiffusers中可以体验unclip模型，也已经验证通过了，在使用上可以跟这个一样。
<img width="814" alt="image" src="https://user-images.githubusercontent.com/50394665/209262587-a5e457aa-cf5d-4f8d-abe5-cb74422b9097.png">

**Comment by yanchaoguo** [comment]
> 目前正在更新最新的ppdiffusers，在新的ppdiffusers中可以体验unclip模型，也已经验证通过了，在使用上可以跟这个一样。 <img alt="image" width="814" src="https://user-images.githubusercontent.com/50394665/209262587-a5e457aa-cf5d-4f8d-abe5-cb74422b9097.png">

速度！ 但是目前这个模型不支持中文，ppdiffusers是否打算支持呢

**Comment by JunnYu** [comment]
目前有开源的权重及使用方法吗？有的话，我可以看一下
