### ISSUE TITLE
[Question]: develop分支和2.4.5版本from .ernie.configuration import * 不同

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#4211]
### 请提出你的问题

在develop分支下 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/__init__.py
第68行有  from .ernie.configuration import *
在2.4.5版本下，以及之前的几个版本 https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.5/paddlenlp/transformers/__init__.py
并没有from .ernie.configuration import *
原因是什么？

**Comment by sijunhe** [comment]
@kg-nlp 你好，这是我们正在进行的对现有模型的PretrainedConfig升级工作。请问使用上有出现任何问题吗？

**Comment by kg-nlp** [comment]
我在进行Ernie预训练模型时
预训练代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/run_pretrain.py
第38行：需要导入ErnieConfig
from paddlenlp.transformers import (
    ErnieConfig,
paddleNLP-2.4.5版本会报错。
目前我离线下载develop版本，运行程序无报错

**Comment by sijunhe** [comment]
@kg-nlp 您好。抱歉干扰到了您的使用。我们今天发布了2.4.7, 应该和您在develop版本的使用体验一致。
