### ISSUE TITLE
[Question]: Ernie-layout finetuned model with "ResahpOps is invalid" error

### ISSUE THREAD

**Issue by stefanqxb** [PaddlePaddle/PaddleNLP#4212]
### 请提出你的问题

Hi there,
   Im using the ernie-layout model for some VQA tasks atm, and finetune with our custom data, following the steps mentioned
here [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout](url) So specifically, I did as follows:
1. specify our custom data in `custom_data/`
2. run the `run_mrc.py` to do the finetune, got the trained files ouput in `target_path`
3.  run the `export_model.py` with --model_path as `target_path` and output_path `output_path`, got the inference.pdiparams and inference.pdmodels and inference.info as output in `output_path`
4. tar those inferences file as docpromt.tar file and put it under `.paddlenlp/taskflow/document_inetelligence/doocpromt/static`
5.  copy those inferences files to the `.paddlenlp/taskflow/document_inetelligence/doocpromt/static/`
so the file structure looks like 
```
- docpromt
   - docpromt.tar
   - stastic
      - inference.pdiparams
      - xxxx
      - xxx
```
6. Initailize the docpromot obj and run the inference is 
```
docprompt = Taskflow("document_intelligence", lang="en", task_path=".paddlenlp/taskflow/document_inetelligence/doocpromt/")
docprompt(doc=[""], questions=[xxxx])
```
However, when doing the step 6, I got the following error

InvalidArgumentError: The 'shape' attribute in ReshapeOp is invalid. The input tensor X'size must be divisible by known capacity of 'shape'. But received X's shape = [7 , 7,  4], X's size = 196, 'shape' is [49, 1], known capacity of 'shape' is 49

The same image I use is working prefectly fine with the origin model without finetune, So wondering what is wrong here, thanks a lot for the help :)

**Comment by wawltor** [comment]
The DoPrompt model structure is not the same as the ERNIE-Layout, you can't use the tool of Taskflow to load the fine-tuned mode, you need to use the script  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout/deploy/python

**Comment by stefanqxb** [comment]
Oh!! I see! thanks for the info, yes, I tried to use the `infer.py` there and it works well, so the problem is solved

However Im having another issue now for the result mis-matching between evaluation and actual prediction

For example, during the finetune, in the end, it will output this `eval_predictions.json` which I assume containing the eval predictions results, in there I can see my question has been answered correctly,  but when I use the `infer.py` to load the finetuned model and do the prediction with the same question as what I have in the eval_predictions.json,  the output is quite wrong there, so wondering what is going wrong here?  Why the eval result is different from the actual predicted results. Thanks for the help

**Comment by wawltor** [comment]
Maybe you need to check 
1) The model was loaded successful ? you neee to check the model path 
2) The task type is correct? 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/16698950/209289295-32190fe8-7adc-4f2d-bd07-432b5e230252.png">

**Comment by stefanqxb** [comment]
Hi @wawltor ,
     Yes, Here is what I do for the finetuning and predict

0. create a fresh new dir /my/path/run_1
1. finetune with `run_mrc.py --ouput_dir /my/path/run_1/ --lang "en"` skipping the other args for now
2. convering to inference with `export_model.py --model_path /my/path/run_1 --output_path /my/path/run_1/mrc_export`
3. test with `python infer.py --model_path_prefix /my/path/run_1/mrc_export/inference --task_type mrc  --lang "en" --batch_size 8 `

So I assume the finetuned model is loaded correctly, but the results from the prediction is still different from the ones in the eval_predictions.json, so any other ideas ??

**Comment by wawltor** [comment]
> Hi @wawltor , Yes, Here is what I do for the finetuning and predict
> 
> 0. create a fresh new dir /my/path/run_1
> 1. finetune with `run_mrc.py --ouput_dir /my/path/run_1/ --lang "en"` skipping the other args for now
> 2. convering to inference with `export_model.py --model_path /my/path/run_1 --output_path /my/path/run_1/mrc_export`
> 3. test with `python infer.py --model_path_prefix /my/path/run_1/mrc_export/inference --task_type mrc  --lang "en" --batch_size 8 `
> 
> So I assume the finetuned model is loaded correctly, but the results from the prediction is still different from the ones in the eval_predictions.json, so any other ideas ??

When you run the script of `infer.py` twice,  the result is same or different ?

**Comment by stefanqxb** [comment]
> When you run the script of infer.py twice, the result is same or different ?
Yes, the results are teh same between the two runs 

Here is what is in the eval_predictions.json
![image](https://user-images.githubusercontent.com/10809030/209294567-80ecf9f1-6d01-4503-a8af-ca8f5f8ae55a.png)
Here is what is from the actual inference (1st run)
![image](https://user-images.githubusercontent.com/10809030/209294723-107f2a2f-a40f-497f-a6da-f9c072c38438.png)
Here is from the 2nd run
![image](https://user-images.githubusercontent.com/10809030/209294817-a8aaac8f-5e64-44ca-9093-ea70d2161e00.png)

**Comment by wawltor** [comment]
> > When you run the script of infer.py twice, the result is same or different ?
> > Yes, the results are teh same between the two runs
> 
> Here is what is in the eval_predictions.json ![image](https://user-images.githubusercontent.com/10809030/209294567-80ecf9f1-6d01-4503-a8af-ca8f5f8ae55a.png) Here is what is from the actual inference (1st run) ![image](https://user-images.githubusercontent.com/10809030/209294723-107f2a2f-a40f-497f-a6da-f9c072c38438.png) Here is from the 2nd run ![image](https://user-images.githubusercontent.com/10809030/209294817-a8aaac8f-5e64-44ca-9093-ea70d2161e00.png)

I guess it is a bug in the script of `infer.py`, I will find the code owner to fix it,  You could check the code diff, and i am happy to see you fix it.

**Comment by stefanqxb** [comment]
> I guess it is a bug in the script of infer.py, I will find the code owner to fix it, You could check the code diff, and i am happy to see you fix it.
Yep, Im happy to help,  but as I can see the `infer.py` is just a wrapper for calling the predictor, so Im not sure what code diff should I look for here, maybe start with the `predictor.py` or ?

**Comment by wawltor** [comment]
> > I guess it is a bug in the script of infer.py, I will find the code owner to fix it, You could check the code diff, and i am happy to see you fix it.
> > Yep, Im happy to help,  but as I can see the `infer.py` is just a wrapper for calling the predictor, so Im not sure what code diff should I look for here, maybe start with the `predictor.py` or ?

yep，start with the the `predictor.py `

**Comment by stefanqxb** [comment]
> yep，start with the the predictor.py 

Yep, surely, I can try my best but please @linjieccc  to help as well :)

**Comment by linjieccc** [comment]
@stefanqxb Hi, 

the postprocess is different between `eval_predictions.json` (output on the process of fine-tuning) and infer.py, `eval_prediction.json` is just for result comparison with the groud truth.

**Comment by linjieccc** [comment]
> Hi @wawltor , Yes, Here is what I do for the finetuning and predict
> 
> 0. create a fresh new dir /my/path/run_1
> 1. finetune with `run_mrc.py --ouput_dir /my/path/run_1/ --lang "en"` skipping the other args for now
> 2. convering to inference with `export_model.py --model_path /my/path/run_1 --output_path /my/path/run_1/mrc_export`
> 3. test with `python infer.py --model_path_prefix /my/path/run_1/mrc_export/inference --task_type mrc  --lang "en" --batch_size 8 `
> 
> So I assume the finetuned model is loaded correctly, but the results from the prediction is still different from the ones in the eval_predictions.json, so any other ideas ??

You can follow this process to predict with the fine-tuned model

**Comment by stefanqxb** [comment]
> @stefanqxb Hi,
> 
> the postprocess is different between `eval_predictions.json` (output on the process of fine-tuning) and infer.py, `eval_prediction.json` is just for result comparison with the groud truth.

Hi @linjieccc ,
     Thank you for the answer , So you mean the difference as I atteched in the above pics are only due to the postprocessing ??  Because as u see, for the same question, the output answer in the eval_predictions.json is what I want, but the answer produced from the infer.py is not what I want and they are quite different tbh.

so can u confirm that this difference is only due to the postprocess part ???  And if so,  I have two questions, 1st: how do I make the infer.py to produce the same output as in the `eval_prediction.json`?    2nd: why it looks so different and why dont we align them, as I see `eval` and `predict` should more or less be through the same process right?

**Comment by linjieccc** [comment]
@stefanqxb Hi,

is this example from the docvqa_zh dataset or from your own data? We should check that the model checkpoint and the OCR result used in these two process are the same.

**Comment by stefanqxb** [comment]
> @stefanqxb Hi,
> 
> is this example from the docvqa_zh dataset or from your own data? We should check that the model checkpoint and the OCR result used in these two process are the same.

Hi @linjieccc ,
     This is from our own data, not the docvqa_zh one. 
     As for the OCR result used in these two process  In `infer.py`, I assume we are using the PaddleOCR obj u speicfy in the `predictor.py`  and for the fine-tuning dataset ocr part, we are using also PaddleOCR,  to be speicifically, we are using en_PP_OCRv3_det_infer, en_PP_OCRv3_rec_infer, ch_ppocr_mobile_v2.0_cls_infer. So I assume they should output the same ?
    In addition, my question is what is cause of these eval and infer answer differences?  postporcessing? OCR differences? or what ??

**Comment by stefanqxb** [comment]
> > @stefanqxb Hi,
> > is this example from the docvqa_zh dataset or from your own data? We should check that the model checkpoint and the OCR result used in these two process are the same.
> 
> Hi @linjieccc , This is from our own data, not the docvqa_zh one. As for the OCR result used in these two process In `infer.py`, I assume we are using the PaddleOCR obj u speicfy in the `predictor.py` and for the fine-tuning dataset ocr part, we are using also PaddleOCR, to be speicifically, we are using en_PP_OCRv3_det_infer, en_PP_OCRv3_rec_infer, ch_ppocr_mobile_v2.0_cls_infer. So I assume they should output the same ? In addition, my question is what is cause of these eval and infer answer differences? postporcessing? OCR differences? or what ??



Any updates on this ?? @linjieccc @wawltor

**Comment by linjieccc** [comment]
@stefanqxb Hi,

If the OCR result used in these two process are the same, the prediction result should be the same using one model checkpoint. Or there may be a bug. Can you provide the model checkpoint and the inference sample, I will try to reproduce this issue, thanks!

**Comment by stefanqxb** [comment]
In addtion for the OCR result, I compare the OCR result used in our finetune data and the one generated by the PaddleOCR obj in `predictor.py`, its only minor differences between them for the same items.

For example for above one `-81.840.00` , the coordiations in our finetune data is [2010, 190, 2120, 215] and the one generated from `predictor.py` is [2006, 182, 2123, 220], both are in. [left, top, right, bottom] order. this applys to basically or other items

So does these differences leads to the eval_predict and infer.py differences or ? as far as I see, it shouldnt make such differences for answers ? Or maybe Im totally wrong ?

**Comment by linjieccc** [comment]
@stefanqxb Hi,

It may cause different model output if using different bbox input.  I think we should check the cause of the OCR differences if the same PaddleOCR model is used.

**Comment by stefanqxb** [comment]
> provide the model checkpoint and the inference sample, I will try to reproduce this issue, thanks!

Hi @linjieccc ,
     Im afraid it would be hard to provide u the inference sample, as the document is classified as restrcitd so Im not allow to share it externally at all.  
      However, if your guess is onto the PaddleOCR part, I have the same doubt why the OCR differs if Im using the same PaddleOCR model?  As far as I can tell, its just two parts in the code when it comes to OCR during inferencing 
 
```
self.ocr = PaddleOCR(xxx,xxx,xxx)
ocr_result = self.ocr.ocr(xx)
```
And I dont really see what cause the OCR differences here, or am I missing something ?

**Comment by linjieccc** [comment]
@stefanqxb Hi,

may be you can replace the OCR result here with the one used in training process to see whether the differences still exist. https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/predictor.py#L759

**Comment by stefanqxb** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/predictor.py#L759

Yep, surely, Im actually planning to do that to see if that is really the cause, will update u in the afternoon if I got the results

**Comment by stefanqxb** [comment]
> @stefanqxb Hi,
> 
> may be you can replace the OCR result here with the one used in training process to see whether the differences still exist. https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/predictor.py#L759

Hi @linjieccc ,
     I just tried with your suggestions, replacing the logic with the OCR used in training,  as I can see the result does different than the one I attached before, however, its still not the same as the`eval_prediction.json` . So now the ocr result is completely the same between training and infer, but the differences still exist . 

So my questions are 
1st maybe there is a bug in the code to cause this ? 
2nd is there any quick walkaround to get the `eval_prediction.json` output as output from `infer.py` ?

Below is the new outcome with the replacement, u can compare it with the previous attached ones ![image](https://user-images.githubusercontent.com/10809030/210052552-9c237103-15ce-46de-8a44-8ad02abd2e73.png)

**Comment by stefanqxb** [comment]
Hi @linjieccc @wawltor 
     Any thoughts or updates on this ?? :)

**Comment by linjieccc** [comment]
@stefanqxb Hi，

is it possible to provide some fake data you used in `run_mrc.py` and `infer.py`, so I can try to reproduce the issue

**Comment by stefanqxb** [comment]
> @stefanqxb Hi，
> 
> is it possible to provide some fake data you used in `run_mrc.py` and `infer.py`, so I can try to reproduce the issue

Hi @linjieccc ,
     Let me check with my boss to see if we could have some fake data for u to reproduce, I will try my best, but please also help to find what is the differences from a theoritical-point of view as of now, the ocr differences is also scoped-out, where else could cause such a differences. Will get back asap

**Comment by aashishpokharel** [comment]
> The DoPrompt model structure is not the same as the ERNIE-Layout, you can't use the tool of Taskflow to load the fine-tuned mode, you need to use the script https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout/deploy/python
Is there a way to obtain the answer confidence score similar to DocPrompt model?
