### ISSUE TITLE
[Question]: How to load  pretrained model from local 

### ISSUE THREAD

**Issue by phamkhactu** [PaddlePaddle/PaddleNLP#4222]
I want to load pretrained model from local disk
```
from paddlenlp.transformers import LayoutXLMModel, LayoutXLMTokenizer
outXLMTokenizer.from_pretrained("hugginface_model/phobert_paddle")
tokenizer = LayoutXLMTokenizer.from_pretrained("./model_state.pdparams",local_files_only=True)
print(tokenizer)

```
but I get error:
```
[2022-12-23 16:14:49,794] [ WARNING] - file<https://bj.bcebos.com/paddlenlp/models/community/model_state.pdparams/tokenizer_config.json> not exist
Traceback (most recent call last):
  File "train_layoutml.py", line 23, in <module>
    tokenizer = LayoutXLMTokenizer.from_pretrained("hugginface_model/layoutxml_paddle/model_state.pdparams",local_files_only=True)
  File "/home/tupk/tupk/ocr-digits/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1576, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/home/tupk/tupk/ocr-digits/PaddleNLP/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/tupk/tupk/ocr-digits/PaddleNLP/paddlenlp/transformers/layoutxlm/tokenizer.py", line 93, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/tupk/anaconda3/envs/ocr/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```
Thank you.

**Comment by sijunhe** [comment]
hi @phamkhactu. You can directly load from local disk with the `.from_pretrained()` method. The reason that your code didn't work is that you tried to load a model checkpoint file with the tokenizer class. Instead entering an actual filename, you can enter a folder path. The loader will look for the file in the folder automatically. 
```
tokenizer = LayoutXLMTokenizer.from_pretrained(<folder_file_path>, local_files_only=True)
model = LayoutXLMModel.from_pretrained(<folder_file_path>, local_files_only=True)
```

**Comment by phamkhactu** [comment]
> local_files_only=True

hi @sijunhe, thanks for your help. But I have some confuse.
The facts, I want to use **vi-layoutxlm-base-uncased**. I see that the pretrained model can download from **https://bj.bcebos.com/paddlenlp/models/transformers/vi-layoutxlm-base-uncased/model_state.pdparams**
Because my home storage limited, I download the ```model_state.pdparams``` to local disk.
I download sucessfully. Here in my local storage only has:
![image](https://user-images.githubusercontent.com/42369268/209496483-4c100339-1355-4c21-b773-c6ff318be994.png)

From code ```run_ner.py``` line 73-74
![image](https://user-images.githubusercontent.com/42369268/209495751-5ada6f23-ea06-4a22-984b-d933daec0122.png)

The pretrained model can load. Because I want load from local disk. So I had try 2 cases:
1. tokenizer = LayoutXLMTokenizer.from_pretrained("./layoutxml_paddle/model_state.pdparams")
I get the error, the error I had ask you before.
But from **.cache** not have error. I think that in .cache maybe have other configs, so not causes error.
2. tokenizer = LayoutXLMTokenizer.from_pretrained("./layoutxml_paddle/",local_files_only=True)
as you suggestion I get error:
```
    tokenizer = LayoutXLMTokenizer.from_pretrained("./layoutxml_paddle/",local_files_only=True)
  File "/home/tupk/tupk/ocr-digits/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py", line 1576, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/home/tupk/tupk/ocr-digits/PaddleNLP/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'vocab_file'
```
As you explain to me that: the model maybe as the checkpoint, so cause error.
So my questioin is: "if I want to load checkpoint, how to load it?" or now I have model at local, how to load it?
Many thanks.

**Comment by sijunhe** [comment]
```
/path/to/your/folder
| --  model_state.pdparams
| --  tokenizer.config
| --  vocab.txt
```
For example, your local folder would look like this. You have the `model_state.pdparams` in it and also the tokenizer files in it. To load the model, do `LayoutXLMModel.from_pretrained(/path/to/your/folder)`. To load the tokenizer, do `LayoutXLMTokenizer.from_pretrained(/path/to/your/folder)`. Does that make sense? @phamkhactu
