### ISSUE TITLE
[Question]: 是否有TTS中前端相关的功能模型

### ISSUE THREAD

**Issue by SG-XM** [PaddlePaddle/PaddleNLP#4231]
### 请提出你的问题

1. TTS中文本前端处理中有一个操作是韵律预测,我在 paddlespeech 中看到一个模型,不知道是否是咱们这边提供的
![image](https://user-images.githubusercontent.com/32589854/209361066-6756a02e-5894-4c3c-9f3a-802d197b903c.png)
韵律预测即生成对应的#1#2#3#4标签
![image](https://user-images.githubusercontent.com/32589854/209361192-058d0c60-eb1c-474e-9344-2599c09417d5.png)

2. paddleNLP 中是否有相关模型可以实现 TTS 的韵律预测功能?
3. paddleNLP 中是否有能实现其他前端功能的模型?
![image](https://user-images.githubusercontent.com/32589854/209361477-bb54d079-9012-4b5f-8501-80606440293d.png)
 
![image](https://user-images.githubusercontent.com/32589854/209361584-3368f2ef-c705-4ba2-b668-32971d087ffa.png)

**Comment by linjieccc** [comment]
@SG-XM Hi,

韵律预测功能目前应该是没有的，可以在 https://github.com/PaddlePaddle/PaddleSpeech 提个feature request的issue。

分词、词性标注等功能可以看下Taskflow能否满足你的需求：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md
