### ISSUE TITLE
[Question]: 预训练模型时内存溢出

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#4233]
### 请提出你的问题

在新的服务器上重新搭建paddle环境，复现仍然溢出，下面是保存依次模型后的warning信息，内存已经占了230G了，预训练的数据只有800多万条，使用pytorch训练不超过14G.
LAUNCH WARNING 2022-12-25 03:38:32,390 save gpu log failed
LAUNCH WARNING 2022-12-25 03:39:07,299 save gpu log failed
LAUNCH WARNING 2022-12-25 03:39:42,348 save gpu log failed
LAUNCH WARNING 2022-12-25 03:41:54,551 save gpu log failed
LAUNCH WARNING 2022-12-25 03:42:46,215 save gpu log failed
W1225 03:43:10.622591 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 03:45:38,110 save gpu log failed
W1225 03:45:51.152089 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 03:50:17.997763 92537 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 03:50:19.343796 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 03:50:35.905200 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 03:50:40.865072 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:21:28.570313 99867 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:21:29.524154 99835 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:21:29.628266 99861 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:31:19.437268 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:32:38.875106 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:33:08.067329 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 04:38:16,443 save gpu log failed
W1225 04:44:28.751844 92537 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 04:44:30.116302 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 04:44:55,336 save gpu log failed
W1225 04:52:18.196707 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 05:00:37,405 save gpu log failed
W1225 05:00:41.439925 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 05:01:23,044 save gpu log failed
W1225 05:01:51.126281 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 05:01:59,499 save gpu log failed
W1225 05:02:11.903935 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:03:04.696681 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:17:34.050822 99861 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:17:06.199263 99867 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:19:07.487483 92809 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:39:05.508414 99867 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W1225 05:39:13.059235 92537 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2022-12-25 05:39:17,741 save gpu log failed
![image](https://user-images.githubusercontent.com/58376804/209489115-464a02ed-a60d-48fc-942f-c8cff1ae78c1.png)

**Comment by sijunhe** [comment]
麻烦分享一下环境配置，以及训练使用的代码

**Comment by kg-nlp** [comment]
paddle-bfloat 0.1.7
paddle2onnx 1.0.5
paddlefsl 1.1.0
paddlenlp 2.4.5
paddlepaddle 2.4.1
paddlepaddle-gpu 2.4.

训练代码
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/run_pretrain.py

**Comment by sijunhe** [comment]
@ZHUI 麻烦看下有没有内存泄露的问题

**Comment by ZHUI** [comment]
确认一下，是内存问题还是显存，存在溢出问题？

数据是 mmap load的，大部分占用的应该都是空闲的cache内存，可以 free -g 看看

**Comment by kg-nlp** [comment]
四张T4卡，每张约占用5G显存，目前内存溢出，服务器已崩。。。

**Comment by ZHUI** [comment]
非常抱歉，给您带来了不好的体验

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/data_tools/dataset_utils.py#L166
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/data_tools/dataset_utils.py#L912

这边我们做的几处数据读取的地方，确实采用的是mmap load 的方式。
理论上内存不足的时候，会自动换页出去才对。
