### ISSUE TITLE
[Question]: DocPrompt 指定模型的路径

### ISSUE THREAD

**Issue by minlik** [PaddlePaddle/PaddleNLP#4244]
### 请提出你的问题

在使用 taskflow 的 intelligence_document 功能时，可以通过 task_path 指定模型的路径
docprompt  = Taskflow('intelligence_document', schema=schema, task_path=......)

但是，DocPrompt 使用时存在两个路径，一个是 taskflow 相关的，一个是模型 ernie-layoutx-base-uncased 相关的。task_path 好像是对 taskflow 路径生效的。请问下，这两个路径可以分别指定吗？

/root/.paddlenlp/taskflow/document_intelligence/docprompt/
/root/.paddlenlp/models/ernie-layoutx-base-uncased/special_tokens_map.json

**Comment by linjieccc** [comment]
@minlik Hi，

DocPrompt目前还不支持模型定制

**Comment by minlik** [comment]
@linjieccc 不是定制模型，而是想看下这两个路径能否分别指定？原因是如果部署到无网络的环境中的话，需要把这两个路径的模型相关文件提前下载好。那么下载好的文件路径，如何通过Taskflow指定呢？

感谢。

**Comment by linjieccc** [comment]
@minlik 明白了，目前还没有这样的参数可以直接指定文件位置。可以在有网环境执行一次后将`/root/.paddlenlp` 拷贝到无网环境

**Comment by minlik** [comment]
好的 谢谢
