### ISSUE TITLE
关于embedding的疑问

### ISSUE THREAD

**Issue by xdg2016** [PaddlePaddle/PaddleNLP#4252]
### 请提出你的问题

我看了paddlenlp中的这个样例
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/word_embedding
主要在对比是否使用TokenEmbedding加载预训练模型，对分类结果的影响。我按照教程训练出来一个模型，然后取出其中的embedder.weight作为词向量矩阵，用于后续直接查询，可是查询结果不太符合预期，像：
树叶 叶子 相似度才0.1939，而预训练的词向量矩阵查出来的向量相似度是0.6689。所以有几点疑惑：
（1）在文本情感分类任务下训练出来的词向量矩阵为什么没有预训练的效果好？
（2）预训练模型的训练，paddlenlp中有对应的例子吗？想弄清楚预训练模型是怎么训练出来的？
（3）预训练模型的npz是在哪个项目中保存出来的？

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 我看了paddlenlp中的这个样例 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/word_embedding 主要在对比是否使用TokenEmbedding加载预训练模型，对分类结果的影响。我按照教程训练出来一个模型，然后取出其中的embedder.weight作为词向量矩阵，用于后续直接查询，可是查询结果不太符合预期，像： 树叶 叶子 相似度才0.1939，而预训练的词向量矩阵查出来的向量相似度是0.6689。所以有几点疑惑： （1）在文本情感分类任务下训练出来的词向量矩阵为什么没有预训练的效果好？ （2）预训练模型的训练，paddlenlp中有对应的例子吗？想弄清楚预训练模型是怎么训练出来的？ （3）预训练模型的npz是在哪个项目中保存出来的？

https://github.com/PaddlePaddle/PaddleNLP/blob/699a2f07d424453dd52f3c42e64860b6428cdb92/examples/word_embedding/train.py#L73

您说的而是这个任务吗？BoWModel就是一个简单的分类模型，那些词向量预训练模型是来源于互联网，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/embeddings.md#%E4%B8%AD%E6%96%87%E8%AF%8D%E5%90%91%E9%87%8F
可以使用gensim工具进行训练，不过现在推荐使用bert模型

**Comment by xdg2016** [comment]
是的，是这个项目，我看paddle这边有介绍过词向量的原理和skip-gram算法训练
https://www.paddlepaddle.org.cn/tutorials/projectdetail/3578658
词向量用bert怎么做呢？我理解的bert是一个基础的语言模型，用于建模词和词之间的语义关系，那我输入一个词，输出一个向量，就是词向量吗？这样理解对吗？paddle中有没有基于bert的词向量呢？

**Comment by w5688414** [comment]
> 

bert是直接对句子进行建模的，你如果输入一个词，它还是会当成句子看待，当然这只是猜测，您可以做做实验，看行不行， 可以通过https://github.com/PaddlePaddle/PaddleNLP/blob/699a2f07d424453dd52f3c42e64860b6428cdb92/paddlenlp/transformers/bert/modeling.py#L383

来取出每个token的向量表示

**Comment by xdg2016** [comment]
好的，谢谢，我试试
