### ISSUE TITLE
文本分类预测出现的问题 

### ISSUE THREAD

**Issue by wanggei** [PaddlePaddle/PaddleNLP#4261]
### 请提出你的问题

进行文本分类预测时，安装官方的步骤生成了模板，但是进行预测时却出现了问题``
![image](https://user-images.githubusercontent.com/61741330/209765033-3f6470e2-680f-4106-b0ad-b8548e389875.png)
通过断点得知是modeling.py中的属性获取出现问题，但是模型训练出来的config.json并没有这个属性，导致下面代码程序出现错误
![image](https://user-images.githubusercontent.com/61741330/209765252-7cd51340-df2b-4ac6-8cb4-985e7b62cb53.png)

**Comment by lugimzzz** [comment]
你好，请问可以提供一下是在运行哪一份代码时遇到这个问题，方便我们复现定位问题

**Comment by wanggei** [comment]
@lugimzzz 运行的是predict.py中的代码

**Comment by lugimzzz** [comment]
方便提供一下paddlenlp和paddlepaddle版本

**Comment by wanggei** [comment]
@lugimzzz paddlelp: 2.4.5 paddlepaddle:2.3.2

**Comment by wawltor** [comment]
这个升级到2.4.6或者2.4.7版本试试

**Comment by wanggei** [comment]
paddlele吗

**Comment by lugimzzz** [comment]
> paddlele吗

你可以升级到paddlenlp最新版本试一下，我在2.4.8中验证了没问题。

**Comment by wanggei** [comment]
行，我试试

**Comment by wanggei** [comment]
@lugimzzz 还是不行，我训练出来的congfig.json是这样的
![image](https://user-images.githubusercontent.com/61741330/209780214-0aa16c2a-a354-4cf8-a4cd-7acc21edf508.png)
但一跑predict.py还是出现那个错误，训练步骤链接https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class#readme

**Comment by wanggei** [comment]
通过跑train.py生成的文件
![image](https://user-images.githubusercontent.com/61741330/209783196-4bf862d6-9a13-4af9-a2f7-0c1280b6753a.png)

**Comment by lugimzzz** [comment]
你训练的时候是在哪个版本训练的？2.4.8吗？

**Comment by wanggei** [comment]
@lugimzzz 对的

**Comment by lugimzzz** [comment]
paddlenlp 2.4.5应该保存的模型配置文件是model_config.json,2.4.8训练保存的模型文件名为config.json
![image](https://user-images.githubusercontent.com/63761690/209787507-83832ba4-92bc-40e5-9f65-50498c89769a.png)
![image](https://user-images.githubusercontent.com/63761690/209787573-1df342a6-eed0-49ca-9673-f49f808892b7.png)

**Comment by wanggei** [comment]
我这的版本是2.4.8的
![image](https://user-images.githubusercontent.com/61741330/209788742-3c2b8ef7-f885-4d33-b26a-e82e313ae2f3.png)
为啥我训练出来的文件和你那边的都不一样，而且训练结果文件保存路径都不会自动保存到checkpoint，是保存在其他的地方
![image](https://user-images.githubusercontent.com/61741330/209788986-f8f00170-b97c-4565-aab7-7f137ac91bb3.png)

**Comment by wanggei** [comment]
我是直接运行train.py，没有通过命令行的形式去运行，真正会影响吗

**Comment by wanggei** [comment]
我是直接运行train.py，没有通过命令行的形式去运行，这个会影响吗

**Comment by lugimzzz** [comment]
> 我是直接运行train.py，没有通过命令行的形式去运行，这个会影响吗

确实有点奇怪，你创建个test.py文件，运行下面代码看看
```
from paddlenlp.transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained("ernie-3.0-base-zh",num_classes=2)
model.save_pretrained("checkpoint-2")
```
![image](https://user-images.githubusercontent.com/63761690/209792447-fb492972-f50b-4dcb-a4f0-e9738a0364b8.png)

**Comment by wanggei** [comment]
还是和你生成的不一样
![image](https://user-images.githubusercontent.com/61741330/209793438-d73a8f86-b085-4ce9-81a1-28c6c0777ec0.png)

**Comment by wanggei** [comment]
奇怪是我设置了output_dir设置属性，但是生成的训练文件却保存正在其他的地方
![image](https://user-images.githubusercontent.com/61741330/209793763-243387bf-273b-47cc-8beb-c0385d4fb08e.png)

**Comment by wanggei** [comment]
用了上面的代码生成的config.json应该跟你是一样的
![image](https://user-images.githubusercontent.com/61741330/209793984-0323c435-2df9-4019-81a3-125c4f556095.png)

**Comment by wanggei** [comment]
生成的文件到这个下面了
![image](https://user-images.githubusercontent.com/61741330/209794327-d6cbbcc7-5fd4-45b7-a334-4d4d5e2b3234.png)

**Comment by lugimzzz** [comment]
因为你test.py文件就在analysis目录下，我看你保存文件没有问题，之前应该是哪里搞错了。**你删除原来的checkpoint**，重新按照最新版本application/text_classification/multi_class的代码 在paddlenlp 2.4.8版本下重新训练预测一遍，之前有可能是哪里搞混了，目前看来`save_pretrained`应该是没有问题的

**Comment by wanggei** [comment]
@lugimzzz 好的，我再试试，谢谢

**Comment by wanggei** [comment]
@lugimzzz 请问一下，同一个模型，每次预测出来的结果都不一样，这会有哪种情况会出现这个，还有昨天那个问题，我把原先的checkpoint给清除掉了，然后重新按照官方的步骤去训练，但还是生成的congfig文件不一样，我必须的手动调用才行
![image](https://user-images.githubusercontent.com/61741330/209895974-d38c0e4c-afc2-4b79-9325-dba3cb985db0.png)
但这样special_tokens_map.json、tokenizer_config.json以及vocab.txt都不会保存到我设定的checkpoint文件这种，得手动复制过来

**Comment by lugimzzz** [comment]
因为其他文件是tokenizer相关参数。你是使用代码传入--output_dir "checkpoint"不能保存吗，使用的是text_classification最新代码吗？你output_dir设置的是相对路径，还是完整的绝对路径

**Comment by wanggei** [comment]
用的是最新的2.4.8，output_dir用的是相对路径

**Comment by wanggei** [comment]
运行完train.py之后，会在运行文件的同级目录下创建一个checkpoint，但文件不会保存进去

**Comment by Monstercat-023** [comment]
> 运行完train.py之后，会在运行文件的同级目录下创建一个checkpoint，但文件不会保存进去

我也遇到了相同的路径和config的问题，您解决了么

**Comment by lugimzzz** [comment]
> > 运行完train.py之后，会在运行文件的同级目录下创建一个checkpoint，但文件不会保存进去
> 
> 我也遇到了相同的路径和config的问题，您解决了么

config是版本问题，你一开始训练应该使用了比较老的版本。目录保存可能你需要确定你运行的目录，建议用命令行运行，可以用pwd确定你运行目录 
![image](https://user-images.githubusercontent.com/63761690/225504333-bac944b0-ee84-4672-a728-f064a9be1311.png)
