### ISSUE TITLE
[Question]: UIE能从一篇文本中抽取工作任务时间线吗？

### ISSUE THREAD

**Issue by holmofy** [PaddlePaddle/PaddleNLP#4265]
### 请提出你的问题

我有很多的政府文件，里面有很多工作安排的deadline，但是文件的格式是不固定的，文件内容里的时间格式也不是固定的。举一个典型的例子：

```
1.XXX：自公告发布之日起至12月9日16时，逾期不再受理。

2.XXX。可于2022年11月10日0:00至11月15日24:00期间XXXX。逾期未完成网上报名确认并缴费的，视为自动放弃资格。

3.XXX。时间地点XXX。笔试时间为：

2022年12月4日上午  9:00—11:00  公共科目

2022年12月4日下午  14:00—17:00  专业科目

4.XXX。.......
```

paddleNLP的信息抽取能将这部分timeline信息结构化吗？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 我有很多的政府文件，里面有很多工作安排的deadline，但是文件的格式是不固定的，文件内容里的时间格式也不是固定的。举一个典型的例子：
> 
> ```
> 1.XXX：自公告发布之日起至12月9日16时，逾期不再受理。
> 
> 2.XXX。可于2022年11月10日0:00至11月15日24:00期间XXXX。逾期未完成网上报名确认并缴费的，视为自动放弃资格。
> 
> 3.XXX。时间地点XXX。笔试时间为：
> 
> 2022年12月4日上午  9:00—11:00  公共科目
> 
> 2022年12月4日下午  14:00—17:00  专业科目
> 
> 4.XXX。.......
> ```
> 
> paddleNLP的信息抽取能将这部分timeline信息结构化吗？

这里是希望抽取时间，还是希望抽取时间对应的关系，例如 专业科目 的 截止时间  2022年12月4日上午  9:00—11:00

**Comment by xxllp** [comment]
我觉得完全可以   设置实体类型叫工作名称  和时间  ，外加 对应一个关系叫 deadline 时间

**Comment by wawltor** [comment]
> 我觉得完全可以 设置实体类型叫工作名称 和时间 ，外加 对应一个关系叫 deadline 时间

这个先尝试一下微调效果吧，尽可能多覆盖需要抽取的case

**Comment by holmofy** [comment]
> > ### 请提出你的问题
> > 我有很多的政府文件，里面有很多工作安排的deadline，但是文件的格式是不固定的，文件内容里的时间格式也不是固定的。举一个典型的例子：
> > ```
> > 1.XXX：自公告发布之日起至12月9日16时，逾期不再受理。
> > 
> > 2.XXX。可于2022年11月10日0:00至11月15日24:00期间XXXX。逾期未完成网上报名确认并缴费的，视为自动放弃资格。
> > 
> > 3.XXX。时间地点XXX。笔试时间为：
> > 
> > 2022年12月4日上午  9:00—11:00  公共科目
> > 
> > 2022年12月4日下午  14:00—17:00  专业科目
> > 
> > 4.XXX。.......
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > paddleNLP的信息抽取能将这部分timeline信息结构化吗？
> 
> 这里是希望抽取时间，还是希望抽取时间对应的关系，例如 专业科目 的 截止时间 2022年12月4日上午 9:00—11:00

时间和对应的流程名都要，最后想要结构化成一张这种结构的表

|流程|时间|
|--|--|
|报名|yyyy-MM-dd~yyyy-MM-dd|
|缴费|yyyy-MM-dd~yyyy-MM-dd|
|笔试|yyyy-MM-dd~yyyy-MM-dd|
|笔试-公共科目|yyyy-MM-dd~yyyy-MM-dd|
|笔试-专业科目|yyyy-MM-dd~yyyy-MM-dd|
|查询成绩|yyyy-MM-dd~yyyy-MM-dd|

感觉原始文本太乱了，有的文本比我给的例子更乱，感觉UIE不太能弄不来。模型微调的话，直接把想要抽取的数据打标成`流程`和`时间`就ok了吗？抽取的时候schema怎么定义？

**Comment by datalee** [comment]
```
[{'prompt': '报名时间',
  'result': [{'end': 49,
              'prob': 0.88,
              'start': 33,
              'value': '2022年11月10日0:00至11月15日24：00'}]},
 {'prompt': '缴费时间',
  'result': [{'end': 52,
              'prob': 0.94,
              'start': 33,
              'value': '2022年11月10日0:00至11月15日24：00期间XXXX'}]},
 {'prompt': '公共科目笔试时间',
  'result': [{'end': 109,
              'prob': 1.0,
              'start': 95,
              'value': '2022年12月4日上午9:00-11:00'}]}]
```
try uie-x
