### ISSUE TITLE
[Question]: 训练过程动态监视

### ISSUE THREAD

**Issue by lddcdut** [PaddlePaddle/PaddleNLP#4285]
### 请提出你的问题

能否根据训练过程中的trainer_state.json生成dashboard图，动态监视训练过程

**Comment by wawltor** [comment]
目前Trainer已经集成了类似dashboard的VisualDL相关功能，日志产出在 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/16698950/209936361-d7a5f997-6d76-483d-87cc-f57df7b0a006.png">

可以用VDL打开日志，具体使用方法  https://github.com/PaddlePaddle/VisualDL
