### ISSUE TITLE
[Question]: 层次分类 vs 多标签分类

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleNLP#4294]
### 请提出你的问题

paddlenlp的这个层次分类与常规的多标签分类貌似是一个东西，没有利用标签间的层级关系？有对比HMCN等层次分类算法的效果吗？

**Comment by lugimzzz** [comment]
之前比较了这一两年的方法，现有针对层次分类的单模型效果并没有比直接利用"拍平"标签的多标签分类有优势。本身把多级标签拆开，也可以理解为利用了标签间的关系

**Comment by FrankWhh** [comment]
了解，感谢回复
