### ISSUE TITLE
[Question]: wordtag问题

### ISSUE THREAD

**Issue by zhuxiaoxiao-cn** [PaddlePaddle/PaddleNLP#4297]
### 请提出你的问题

为什么安装案例去做,结果如下:
[{'items': [{'item': '《孤', 'length': 2, 'offset': 0, 'wordtag_label': '介词'},
            {'item': '女', 'length': 1, 'offset': 2, 'wordtag_label': '物体类_兵器'},
            {'item': '》是201', 'length': 5, 'offset': 3, 'wordtag_label': '修饰词'},
            {'item': '0',
             'length': 1,
             'offset': 8,
             'wordtag_label': '组织机构类_教育组织机构_概念'},
            {'item': '年', 'length': 1, 'offset': 9, 'wordtag_label': '宇宙类'},
            {'item': '九州出版社出版的',
             'length': 8,
             'offset': 10,
             'wordtag_label': '组织机构类_体育组织机构'},
            {'item': '小',
             'length': 1,
             'offset': 18,
             'wordtag_label': '组织机构类_体育组织机构'},
            {'item': '说，作', 'length': 3, 'offset': 19, 'wordtag_label': '生物类'},
            {'item': '者是',
             'length': 2,
             'offset': 22,
             'wordtag_label': '疾病损伤类_植物病虫害'},
            {'item': '余兼',
             'length': 2,
             'offset': 24,
             'wordtag_label': '组织机构类_体育组织机构'},
            {'item': '羽',
             'length': 1,
             'offset': 26,
             'wordtag_label': '生物类_植物'}],
  'text': '《孤女》是2010年九州出版社出版的小说，作者是余兼羽'}]

**Comment by 1649759610** [comment]
这个运行哪个案例出的结果了？

**Comment by zhuxiaoxiao-cn** [comment]
from paddlenlp import Taskflow
wordtag = Taskflow("knowledge_mining", model="wordtag", linking=True)
# Support the input text directly
wordtag("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")

**Comment by 1649759610** [comment]
收到，我们会尽快排查解决。

**Comment by zhuxiaoxiao-cn** [comment]
已解决,paddle和paddlepaddle版本不一致造成
