### ISSUE TITLE
[Question]: SimpleServing 如何调试debug

### ISSUE THREAD

**Issue by hehuang139** [PaddlePaddle/PaddleNLP#4298]
### 请提出你的问题

taskflow 直接调用没有问题，通过simpleServing则返回空，我想知道是否有办法调试，
直接执行server.py脚本，无法启动服务，必须通过命令paddlenlp server server:app --host 0.0.0.0 --port 8189启动，但是这个命令就导致无法调试？

**Comment by hehuang139** [comment]
找到方法了，
path/to/paddlenlp/cli/main.py server \
server:app \
--app_dir \
path/to/applications/information_extraction/document/deploy/simple_serving \
--host \
0.0.0.0 \
--port \
8289 

建议文档中增加说明

**Comment by hehuang139** [comment]
这里有bug，simpleServing，假定了参数必须以text,这个不合理，同时document/deploy/client.py，用的也是doc，
class TaskflowHandler(BaseTaskflowHandler):
    def __init__(self):
        self._name = "taskflow_handler"

    @classmethod
    def process(cls, predictor, data, parameters):
        if data is None:
            return {}
        text = None
        if "text" in data:
            text = data["text"]
        else:
            return {}
        if "schema" in parameters:
            schema = parameters["schema"]
            predictor.set_schema(schema)
        return predictor(text)

**Comment by 1649759610** [comment]
感谢留言，我们后续尽快排查处理。

**Comment by wawltor** [comment]
> 这里有bug，simpleServing，假定了参数必须以text,这个不合理，同时document/deploy/client.py，用的也是doc， class TaskflowHandler(BaseTaskflowHandler): def **init**(self): self._name = "taskflow_handler"
> 
> ```
> @classmethod
> def process(cls, predictor, data, parameters):
>     if data is None:
>         return {}
>     text = None
>     if "text" in data:
>         text = data["text"]
>     else:
>         return {}
>     if "schema" in parameters:
>         schema = parameters["schema"]
>         predictor.set_schema(schema)
>     return predictor(text)
> ```

这里预留了接口，可以自定义不同的Handler，重载BaseTaskflowHandler即可

<img width="874" alt="image" src="https://user-images.githubusercontent.com/16698950/210293433-6ecfa1ce-fdbd-4c4c-9adb-0e65eeb641eb.png">
