### ISSUE TITLE
请问如何将UIE抽取出来的实体存储在结构化的表中呢？

### ISSUE THREAD

**Issue by xyliu-uir** [PaddlePaddle/PaddleNLP#4305]
### Feature request

请问如何将UIE抽取出来的实体存储在结构化的表中呢？
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/50279789/210085804-60cc645f-79ba-4bc5-880f-3051e68da4b2.png">

### Motivation

想把抽取出来的实体、关系、事件存储在结构化的数据库中，方便展示，也方便后续处理

### Your contribution

none

**Comment by SuFIND** [comment]
你已经获得了模型推理结果，设计你的数据库表，通过SQL命令写入即可。看起来你可能需要了解如何使用python对数据库进行增删改查
