### ISSUE TITLE
文本分类模型

### ISSUE THREAD

**Issue by wanggei** [PaddlePaddle/PaddleNLP#4307]
### 请提出你的问题

文本分类训练出来的模型是根据rain.txt和label.txt以及dev.txt这三个文本训练出来的吗，如果是，请问一下，我在data.txt文本中写上一条在train.txt中一模一样的文本，但是预测出来的结果和我在train.txt打的标签不一样，会是哪种情况造成的

**Comment by w5688414** [comment]
有没有开启 model.eval呢？

**Comment by wanggei** [comment]
@w5688414 这个是要在哪里开启
