### ISSUE TITLE
[Bug]: paddlenlp的精确分词效果奇差~

### ISSUE THREAD

**Issue by ScottishFold007** [PaddlePaddle/PaddleNLP#4308]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.4.9
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
如下图所示，多次测试，paddlenlp的精确分词效果奇差~
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/36957508/210198861-c55a4a7a-fb63-431d-8e3a-e4f55463348b.png)

**Comment by wj-Mcat** [comment]
目前 word_segmentation的底座模型正在升级: https://github.com/PaddlePaddle/PaddleNLP/pull/4292 ，请随时关注此 issue 从而获取最新进展。
