### ISSUE TITLE
[Question]: Ernie-layout large?

### ISSUE THREAD

**Issue by grantdelozier** [PaddlePaddle/PaddleNLP#4310]
### 请提出你的问题

I recently read the fantastic paper [ERNIE-Layout: Layout Knowledge Enhanced Pre-training
for Visually-rich Document Understanding](https://arxiv.org/abs/2210.06155) which lead me to this repository. I'm seeking information on the Ernie-layout-large model that was evaluated in the paper.

Under the ernie-layout instruction there is mention of a base version of the model which I can instantiate with ```AutoModelForTokenClassification.from_pretrained('ernie-layoutx-base-uncased')``` 

But this is a different model than the one evaluated in the paper. Is there a way to access the "large" pretrained version that is evaluated in the paper?

Thank you!

**Comment by sijunhe** [comment]
Hi @grantdelozier , thank you for your interest in Ernie-Layout! We have only open-sourced the **base** version of Ernie-Layout due to commercial considerations.
