### ISSUE TITLE
[Question]: 请问DUIE2.0的数据集是用什么工具进行标注的，我需要标注出一份跟DUIE2.0一样格式的数据集？

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/PaddleNLP#4317]
### 请提出你的问题

请问DUIE2.0的数据集是用什么工具进行标注的，我需要标注出一份跟DUIE2.0一样格式的数据集？

**Comment by linjieccc** [comment]
@lzh1998-jansen Hi，

可以尝试参考[doccano](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md)或者[label-studio](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/label_studio_text.md) 里面关系抽取的标注流程，导出标注数据后参考DUIE2.0的数据结构定义转一下数据格式

**Comment by lzh1998-jansen** [comment]
> @lzh1998-jansen Hi，
> 
> 可以尝试参考[doccano](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md)或者[label-studio](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/label_studio_text.md) 里面关系抽取的标注流程，导出标注数据后参考DUIE2.0的数据结构定义转一下数据格式

有提供转换脚本吗

**Comment by linjieccc** [comment]
目前只有doccano / label-studio 到UIE训练数据格式的转换脚本，DUIE的需要自己转下
