### ISSUE TITLE
[Bug]: autotokenizer的库就花了2.5秒而调transformer的autotokenizer才用了0.2秒

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PaddleNLP#4325]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp: 

用户群提到的问题
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
autotokenizer的库就花了2.5秒而调transformer的autotokenizer才用了0.2秒
```

### 稳定复现步骤 & 代码

![WechatIMG2007](https://user-images.githubusercontent.com/12107462/210471325-d2df7215-15a1-425e-aecc-914a533d6379.jpeg)
![WechatIMG2008](https://user-images.githubusercontent.com/12107462/210471330-45ad836f-da5a-4cc2-8c95-66bb6d7b7887.jpeg)

**Comment by wj-Mcat** [comment]
## 简要说明

在以上代码中，您可以先预热一下paddle 的环境：

```python
import paddle
t0 = time.time()
# ...
t1 = time.time()
```

相信环境预热之后的速度其实是差不多的。

## 深入分析

其实这个问题的来源是由于`import paddle`的时候需要花费一些时间，至于paddlenlp包的加载与常规包的加载逻辑一致，并无任何需要耗时的操作，所以理论上所有常规库的加载时间都是一致的。

**Comment by song4875343** [comment]
我是这么认为的，在torch中实现同样的功能，时间那么短，而我们的库要这么久，后续在模型调入等等方面的累计，同样功能torch全部运行下来1秒左右，而paddle框架却需要7.5秒左右。很多部署的运行环境不方便预热，不能用server的方式，7.5秒的等待，程序体验不好。这样就会导致paddle框架的影响力下降。其实我们的很多模型确实很不错。我在很多地方都看到开发者抱怨我们的框架落地有些不尽人意，希望我们在框架本身有所改进。
