### ISSUE TITLE
[Question]: 关于UIE微调模型的疑问

### ISSUE THREAD

**Issue by a1727236594** [PaddlePaddle/PaddleNLP#4326]
### 请提出你的问题

在使用UIE微调功能后，微调后模型进行实体抽取只能抽取标注的词，原模型能实体抽取的词，微调后的模型不能抽取，这是什么原因啊。谢谢

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 在使用UIE微调功能后，微调后模型进行实体抽取只能抽取标注的词，原模型能实体抽取的词，微调后的模型不能抽取，这是什么原因啊。谢谢

微调之后会有数据灾难性遗忘，对原本模型能抽取的东西会有相应的遗忘，因此微调的时候需要确定后续业务希望抽取的内容，然后针对相关内容进行数据准备、 模型训练

**Comment by lzh1998-jansen** [comment]
> > ### 请提出你的问题
> > 在使用UIE微调功能后，微调后模型进行实体抽取只能抽取标注的词，原模型能实体抽取的词，微调后的模型不能抽取，这是什么原因啊。谢谢
> 
> 微调之后会有数据灾难性遗忘，对原本模型能抽取的东西会有相应的遗忘，因此微调的时候需要确定后续业务希望抽取的内容，然后针对相关内容进行数据准备、 模型训练

还是没有回答，怎么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？

**Comment by datalee** [comment]
> 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？

加数据啊，不过百度是不会开源给你的

**Comment by lzh1998-jansen** [comment]
> > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> 
> 加数据啊，不过百度是不会开源给你的
加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地

**Comment by datalee** [comment]
> > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > 
> > 
> > 加数据啊，不过百度是不会开源给你的
> > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地

微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮

**Comment by lzh1998-jansen** [comment]
> > > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > > 
> > > 
> > > 加数据啊，不过百度是不会开源给你的
> > > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地
> 
> 微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮

下游任务中一个 关系，大约需要几条数据去训练，您有试过吗

**Comment by datalee** [comment]
> > > > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > > > 
> > > > 
> > > > 加数据啊，不过百度是不会开源给你的
> > > > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地
> > 
> > 
> > 微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮
> 
> 下游任务中一个 关系，大约需要几条数据去训练，您有试过吗

几条几十条都可以，关键看你的任务复杂度，准确率最高也就70%+

**Comment by lzh1998-jansen** [comment]
> > > > > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > > > > 
> > > > > 
> > > > > 加数据啊，不过百度是不会开源给你的
> > > > > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地
> > > 
> > > 
> > > 微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮
> > 
> > 
> > 下游任务中一个 关系，大约需要几条数据去训练，您有试过吗
> 
> 几条几十条都可以，关键看你的任务复杂度，准确率最高也就70%+

好的，感谢!

**Comment by lzh1998-jansen** [comment]
> > > > > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > > > > 
> > > > > 
> > > > > 加数据啊，不过百度是不会开源给你的
> > > > > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地
> > > 
> > > 
> > > 微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮
> > 
> > 
> > 下游任务中一个 关系，大约需要几条数据去训练，您有试过吗
> 
> 几条几十条都可以，关键看你的任务复杂度，准确率最高也就70%+

请问一下，UIE 的 shcema，可以把多个任务放到一个schema里面吗，比如scheam=【 实体抽取的schmea，关系抽取的schema】，这样直接检测出两个任务的结果

**Comment by datalee** [comment]
> > > > > > > 么保证在微调之前的数据不要遗忘，或者尽量遗忘的内容少一些 ？
> > > > > > 
> > > > > > 
> > > > > > 加数据啊，不过百度是不会开源给你的
> > > > > > 加这么多数据，那不就失去微调的意义了，==. ，用这个的目的就是为了尽量快速落地
> > > > 
> > > > 
> > > > 微调的意义是适用下游任务，你下游什么数据就学成什么呗，或者你在新数据上少训练几轮
> > > 
> > > 
> > > 下游任务中一个 关系，大约需要几条数据去训练，您有试过吗
> > 
> > 
> > 几条几十条都可以，关键看你的任务复杂度，准确率最高也就70%+
> 
> 请问一下，UIE 的 shcema，可以把多个任务放到一个schema里面吗，比如scheam=【 实体抽取的schmea，关系抽取的schema】，这样直接检测出两个任务的结果

可以，官方有示例：
需要明确下，你的关系是否依赖第一个任务的实体结果，如果依赖就是下面的写法：
```
schema =  {"评价维度":
                                     ["观点词", 
                                     "情感倾向[正向,负向,未提及]"]
                   }

schema =  {"实体1":
                                     ["关系1", 
                                     "关系2"]
                   }
```
