### ISSUE TITLE
[Bug]: T5 prepare_decoder_input_ids_from_labels return None

### ISSUE THREAD

**Issue by geasyheart** [PaddlePaddle/PaddleNLP#4328]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.1.post101
- paddlenlp: latest
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
[here](https://github.com/PaddlePaddle/PaddleNLP/blob/255360ffcfb9637a01667311e642a6e8d867694e/examples/information_extraction/DuUIE/uie/seq2struct/data_collator.py#L506)，self.model.prepare_decoder_input_ids_from_labels方法返回None。

type(self.model)
<class 'paddlenlp.transformers.t5.modeling.T5ForConditionalGeneration'>
getattr(self.model, "prepare_decoder_input_ids_from_labels")
getattr(self.model, "prepare_decoder_input_ids_from_labels") is None
True
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/11239531/210475997-67f09d9e-603b-4602-862c-ed02c0e43a10.png)

**Comment by FrostML** [comment]
T5 没有这个接口，可以封装或直接调用 `_shift_right` 实现

**Comment by geasyheart** [comment]
那我直接调用这个[_shift_right](https://github.com/PaddlePaddle/PaddleNLP/blob/640a84a942dc260892a0962da5c91d5e2c7ecbd1/paddlenlp/transformers/t5/modeling.py#L682)实现吗？

**Comment by JunnYu** [comment]
@geasyheart 我看了下HF的T5中这么写的，所以你可以直接调用 _shift_right 就可以了。
```python
def prepare_decoder_input_ids_from_labels(self, labels: torch.Tensor):
    return self._shift_right(labels)
```

**Comment by geasyheart** [comment]
哈哈，我也是看了下它的代码，多谢～。
希望你们后续可以补充下这个方法。

**Comment by JunnYu** [comment]
谢谢~已提PR https://github.com/PaddlePaddle/PaddleNLP/pull/4331

**Comment by geasyheart** [comment]
会在`_shift_right`这里遇到一个断言错误，即`bos_token_id is not None`。
报错信息：
```bash
AssertionError: bos_token_id has to be defined. In T5 it is usually set to the pad_token_id. See T5 docs for more information

```
[相关代码](https://github.com/PaddlePaddle/PaddleNLP/blob/bd2be0f97484776e4a8c03630b6dfe6932fdd5d6/paddlenlp/transformers/t5/modeling.py#L686)

**Comment by JunnYu** [comment]
你好，我这里查看t5config的bos token不是None呀，你可以确认一下？
![image](https://user-images.githubusercontent.com/50394665/210495410-b0457132-a471-4eda-8417-5c5ce529448e.png)

**Comment by geasyheart** [comment]
1. 我运行的是[DuUIE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)代码
2. 其中会走到![](https://user-images.githubusercontent.com/11239531/210475997-67f09d9e-603b-4602-862c-ed02c0e43a10.png)
3. 然后按照pr实现了prepare_decoder_input_ids_from_labels方法，其中[_shift_right](https://github.com/PaddlePaddle/PaddleNLP/blob/bd2be0f97484776e4a8c03630b6dfe6932fdd5d6/paddlenlp/transformers/t5/modeling.py#L686)会先进行断言，但是self.config.bos_token_id为None。
4. 会不会是因为用到的是uie-char-small呀，因为在[DuUIE多任务配置](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)那里，用的是uie-char-small，而不是t5-small。

**Comment by awhathell** [comment]
> 1. 我运行的是[DuUIE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)代码
> 2. 其中会走到![](https://user-images.githubusercontent.com/11239531/210475997-67f09d9e-603b-4602-862c-ed02c0e43a10.png)
> 3. 然后按照pr实现了prepare_decoder_input_ids_from_labels方法，其中[_shift_right](https://github.com/PaddlePaddle/PaddleNLP/blob/bd2be0f97484776e4a8c03630b6dfe6932fdd5d6/paddlenlp/transformers/t5/modeling.py#L686)会先进行断言，但是self.config.bos_token_id为None。
> 4. 会不会是因为用到的是uie-char-small呀，因为在[DuUIE多任务配置](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)那里，用的是uie-char-small，而不是t5-small。

我也遇到了这个问题，请问你怎么解决的啊？
