### ISSUE TITLE
[Question]: 请问如何修改Ernie/Bert模型的pooling层

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleNLP#4330]
### 请提出你的问题

使用PaddleHub加载Ernie模型，默认使用max_pooling的方式，如果我先改成attention_pooling，请问要怎么处理？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 使用PaddleHub加载Ernie模型，默认使用max_pooling的方式，如果我先改成attention_pooling，请问要怎么处理？

这个可以转到PaddleHub提个issue问问
