### ISSUE TITLE
[Question]: 更改模型时提示找不到config

### ISSUE THREAD

**Issue by ezekielqu** [PaddlePaddle/PaddleNLP#4335]
把uie的模型参数换成uie-m-large后，会自动下载模型，但是在使用的时候会提示找不到config。使用uie-base的模型就可以正常运行。但是在uie-base的文件夹下是有相关config的。也没有说明这个uie-m-larg需要的config是没有下载成功，还是需要手动添加

```
File "/disk/disk1/cuiyuan/NLP_RM_EntityExtract/new_NER/riskExtract.py", line 228, in uie_extract
    ie = Taskflow('information_extraction', schema=schema, model="uie-m-large")
  File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 579, in __init__
    self.task_instance = task_class(
  File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py", line 415, in __init__
    with open(os.path.join(self._task_path, CONFIG_NAME)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cuiyuan/.paddlenlp/taskflow/information_extraction/uie-m-large/config.json'
```

**Comment by wawltor** [comment]
> 把uie的模型参数换成uie-m-large后，会自动下载模型，但是在使用的时候会提示找不到config。使用uie-base的模型就可以正常运行。但是在uie-base的文件夹下是有相关config的。也没有说明这个uie-m-larg需要的config是没有下载成功，还是需要手动添加
> 
> ```
> File "/disk/disk1/cuiyuan/NLP_RM_EntityExtract/new_NER/riskExtract.py", line 228, in uie_extract
>     ie = Taskflow('information_extraction', schema=schema, model="uie-m-large")
>   File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 579, in __init__
>     self.task_instance = task_class(
>   File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py", line 415, in __init__
>     with open(os.path.join(self._task_path, CONFIG_NAME)) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/cuiyuan/.paddlenlp/taskflow/information_extraction/uie-m-large/config.json'
> ```

这个一般是模型参数没有完整下载导致的的，ui-m-large模型参数比较大，下载的时候网络会有中断情况

**Comment by sijunhe** [comment]
@linjieccc 看下是不是和IE Taskflow这边的config name修改相关？

**Comment by ezekielqu** [comment]
> > 把uie的模型参数换成uie-m-large后，会自动下载模型，但是在使用的时候会提示找不到config。使用uie-base的模型就可以正常运行。但是在uie-base的文件夹下是有相关config的。也没有说明这个uie-m-larg需要的config是没有下载成功，还是需要手动添加
> > ```
> > File "/disk/disk1/cuiyuan/NLP_RM_EntityExtract/new_NER/riskExtract.py", line 228, in uie_extract
> >     ie = Taskflow('information_extraction', schema=schema, model="uie-m-large")
> >   File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py", line 579, in __init__
> >     self.task_instance = task_class(
> >   File "/home/cuiyuan/anaconda3/envs/paddle24/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py", line 415, in __init__
> >     with open(os.path.join(self._task_path, CONFIG_NAME)) as f:
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/cuiyuan/.paddlenlp/taskflow/information_extraction/uie-m-large/config.json'
> > ```
> 
> 这个一般是模型参数没有完整下载导致的的，ui-m-large模型参数比较大，下载的时候网络会有中断情况

把下载的所有模型删掉，先使用uie-m-large，再使用uie-base，uie-m-large的目录下就有这个config.json了。感觉可能是名称或者路径的问题。
