### ISSUE TITLE
中文标题分类案例中，有一点小疑问

### ISSUE THREAD

**Issue by gzwzzu** [PaddlePaddle/PaddleNLP#434]
https://aistudio.baidu.com/aistudio/projectdetail/1709811?channelType=0&channel=0

在这个新闻标题分类案例中，没有报错。就是有一点没有太明白。
在用paddleNLP定义LSTM时，
class LSTM中的def forward(self, text, seq_len)：
我看前向传播中声明了seq_len参数。但是在使用的过程中始终没有看到这个参数是从哪里传入的
烦请老师帮忙解答一下。谢谢。

**Comment by Steffy-zxf** [comment]
@gzwzzu 你好！该项目下有一个utils.py脚本，这个脚本里面有一个`convert_example()`函数。这个函数会从Dataset中读取数据，进行数据处理，该函数返回值中有`seq_len`，具体实现可以看`convert_example()`函数。
