### ISSUE TITLE
希望增加将预训练模型或训练好的模型转换为推理模型的代码！

### ISSUE THREAD

**Issue by song4875343** [PaddlePaddle/PaddleNLP#4341]
### Feature request

希望增加将预训练模型或训练好的模型转换为推理模型的代码！

### Motivation

由于fastdeploy或者是paddle2onnx都是使用推理模型才能实现，目前仅有少量模型提供了推理模型，这严重阻碍了paddlenlp的企业应用

### Your contribution

目前paddleocr提供了转换代码，不过需要训练时的配置文件，nlp的预训练模型好像没有这个yml文件，paddleocr那个脚本是否也适用于paddlenlp

**Comment by yunguanglu501** [comment]
确实没有export.py的代码,官方冒个泡啊
