### ISSUE TITLE
[Question]: 关于uie模型用于句子的情感分析任务

### ISSUE THREAD

**Issue by yunshifengyu** [PaddlePaddle/PaddleNLP#4344]
### 请提出你的问题

关于uie模型的介绍中对于情感倾向分析的分类只有[正向，负向]，请问可以增加其分类吗？比如设置成[开心,生气,伤心,喜欢,厌恶,恐惧,惊讶]这种较细粒度的分类。
如果可以的话需要调整哪些部分的代码呢？还是只需要在构建数据集时增加options参数呢？
如果是的话，是否只需要运行
python doccano.py \
    --doccano_file ./data/doccano_cls.json \
    --task_type cls \
    --save_dir ./data \
    --splits 0.8 0.1 0.1 \
    --schema_lang ch \
    --options "伤心" "开心" "厌恶" "喜欢" "生气" "惊讶" "恐惧"
后续微调步骤不变？

**Comment by datalee** [comment]
不建议这么做，直接用分类就好了，哈哈哈哈哈

**Comment by yunshifengyu** [comment]
> 不建议这么做，直接用分类就好了，哈哈哈哈哈

这个微调任务不是就是一个分类任务嘛，直接用分类应该咋搞呢，小白不太懂

**Comment by datalee** [comment]
> > 不建议这么做，直接用分类就好了，哈哈哈哈哈
> 
> 这个微调任务不是就是一个分类任务嘛，直接用分类应该咋搞呢，小白不太懂

严格来说，这个是抽取任务，会抽空，或者抽出来多个
