### ISSUE TITLE
[Question]: mbart模型如何做蒸馏

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/PaddleNLP#4350]
### 请提出你的问题

![微信图片_20230105134604](https://user-images.githubusercontent.com/107381937/210711000-99be6807-495c-4440-96de-86327151339a.png)
![微信图片_20230105134554](https://user-images.githubusercontent.com/107381937/210711011-3da4aeab-3548-4cab-a6e6-5bd99a9c5fa3.png)

仿照bert的例子，只计算了学生和教师logits的均方误差，训练了一轮loss也不下降，是什么原因呢？帮忙看下我写的代码有什么问题吧。
学生模型是我改小了教师模型model_config中的层数后微调好的模型。

**Comment by LiuChiachi** [comment]
先说一个我发现的已知的问题吧，teacher模型不需要计算反向及更新参数，你可能需要参考这里处理下teacher模型：
加个`with paddle.no_grad()`
https://github.com/PaddlePaddle/PaddleNLP/blob/d218a25a4cefdf56cef72ecaf3886dd625668273/model_zoo/tinybert/task_distill.py#L371-L372

**Comment by Amy234543** [comment]
你好，我按照你说的改了，现在的loss是下降了，但是每轮刚开始的时候会上升在下降，感觉有问题，想问下你知道是什么原因导致的吗
![微信图片_20230106141127](https://user-images.githubusercontent.com/107381937/210941635-9ee7b1c5-08c3-4722-8a4f-40412bee8239.png)
@LiuChiachi

**Comment by LiuChiachi** [comment]
alpha=0不会使用数据集的hard标签，是不是可以调一下alpha值？
另外我看你好像没有evaluation阶段，除了loss是不是也可以看看评价指标

**Comment by Amy234543** [comment]
alpha我调成0.5了，我想问下蒸馏训练前，学生模型需不需要训练好，因为我是直接减少的教师模型的层数，不训练，蒸馏前学生模型是不能预测的，应该训练好学生模型再去做蒸馏训练吗 @LiuChiachi
