### ISSUE TITLE
[Question]: DuUIE和UIE对比

### ISSUE THREAD

**Issue by geasyheart** [PaddlePaddle/PaddleNLP#4352]
### 请提出你的问题

hello，请教各位大大个问题，[DuUIE](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/information_extraction/DuUIE)采用T5 generation方式来做信息提取，和[model_zoo/uie](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie)这种方式相对比，他俩的区别在什么地方。我看了[和model_zero/uie有什么不同](https://github.com/PaddlePaddle/PaddleNLP/issues/2960)历史描述，以及目前paddleNLP在宣传information extraction时都采用model_zoo/uie，是否可以将其总结为model_zoo/uie的效果相比DuUIE效果会更好，非常感谢各位大大解答～

**Comment by wawltor** [comment]
1. UIE和DuUIE是采样两种不同的建模方式来做信息抽取，UIE是片段抽取的方法来做信息抽取，DuUIE是使用T5的decoder方式来做信息抽取，相关抽取是通过生成方式来抽签出来的 
2. PaddleNLP目前开源的UIE的是抽取方法，主要是优势在零样本、抽取速度，因此我们推荐使用的是UIE方法

**Comment by geasyheart** [comment]
非常感谢～
