### ISSUE TITLE
[Question]: 如何解读uie-senta-base模型输出结果中的概率？

### ISSUE THREAD

**Issue by timsun001** [PaddlePaddle/PaddleNLP#4354]
### 请提出你的问题

请问uie-senta-base模型输出的结果中的probability应当如何理解？

举例：
from paddlenlp import Taskflow
schema = ["情感分析[正向,负向]"]
senta = Taskflow("sentiment_analysis",model="uie-senta-base",schema=schema)
senta(["测试","好","坏"]

输出的结果为：
[{'情感分析[正向,负向]':['text':'正向', 'probability':0.3516]},
{'情感分析[正向,负向]':['text':'正向', 'probability':0.9992]},
{'情感分析[正向,负向]':['text':'负向', 'probability':0.9966]}]

请问其中的probability是指以下哪种情况（或是有其他解读）？目前看起来用哪种方式都解释不通。
1. 正向概率。如果是这样的话，第3条结果（负向，0.9966）解释不通
2. 负向概率。如果是这样的话，第2条结果（正向，0.9992）解释不通
3. 对应结果“text”标签为真的概率，第1条结果（正向，0.3516）解释不通

感谢！

**Comment by 1649759610** [comment]
由于UIE是以抽取的方式生成信息，所以不能认为概率大于0.5就是积极，小于0.5就是消极。
这个概率代表的是抽取的text【正向，负向】是当前任务输出正确答案的概率。

**Comment by timsun001** [comment]
> 由于UIE是以抽取的方式生成信息，所以不能认为概率大于0.5就是积极，小于0.5就是消极。 这个概率代表的是抽取的text【正向，负向】是当前任务输出正确答案的概率。

理解了，感谢！
