### ISSUE TITLE
[Question]: Taskflow加载uie模型报错

### ISSUE THREAD

**Issue by jiangix-paper** [PaddlePaddle/PaddleNLP#4360]
### 请提出你的问题

我使用以下代码加载UIE模型报错：

from paddlenlp import Taskflow
schema  = ['时间']
ie = Taskflow('information_extraction', schema=schema, task_path='/workspace/uie-base')

其中，/workspace/uie-base存储下载后的模型，经过运行后，代码报错为segmentation fault。
各包的版本为：
paddlepaddle-gpu==2.3.0
paddlenlp==2.3.4
python=3.7.7
cuda=10.1
cudnn=7.6.5

nvidia卡为T4卡

请问是什么原因呢？

**Comment by linjieccc** [comment]
@jiangix-paper Hi，

不指定task_path的话是否会有问题？另外可以更新一下paddlenlp的版本试试

**Comment by jiangix-paper** [comment]
![image](https://user-images.githubusercontent.com/62198809/210920572-1b65ba9b-23b1-4815-9d91-76fa737743dc.png)
你好，不指定task_path，更新完paddlenlp版本为2.4.3之后，仍然会显示图中问题

**Comment by linjieccc** [comment]
可以验证下paddle的安装

```python
import paddle 
paddle.utils.run_check()
```

**Comment by jiangix-paper** [comment]
你好，报以下错误，是paddlepaddle-gpu安装失败导致的吗？
![image](https://user-images.githubusercontent.com/62198809/210921610-c41ca4e9-e5a7-4afd-b447-219ed667b591.png)

**Comment by linjieccc** [comment]
@jiangix-paper 应该是paddle安装问题，推荐用conda来安装 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/linux-conda.html

```shell
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
```

**Comment by jiangix-paper** [comment]
你好，由于我目前这个服务器是离线版本的。无法链接外部conda或者pip源安装。请问如果离线安装的话，有相关教程吗？可否帮忙提供一下需要安装的各包的链接？非常感谢

**Comment by wawltor** [comment]
> 你好，由于我目前这个服务器是离线版本的。无法链接外部conda或者pip源安装。请问如果离线安装的话，有相关教程吗？可否帮忙提供一下需要安装的各包的链接？非常感谢

如果服务器离线版本，建议使用docker镜像安装paddle，离线安装依赖的工作比较多，https://www.paddlepaddle.org.cn/
