### ISSUE TITLE
[Question]: UIE训练使用的schema是否方便提供一下？

### ISSUE THREAD

**Issue by IT-Xue** [PaddlePaddle/PaddleNLP#4361]
### 请提出你的问题

UIE训练使用的schema是否方便提供一下？为后续我们自己微调和schema定义提供知道。谢谢

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/2891  可以参考一下这个解答，目前我们提供schema原因是，在具体的下游任务都是需要自己重新设定schema，同时进行微调的工作，并且微调之后会有数据遗忘(之前的schema的抽取效果变差，对特定微调的schema效果会好很多)

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有疑问可以再次该issue。
