### ISSUE TITLE
[Question]: 在使用UIE-X遇到的问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#4363]
### 请提出你的问题

使用UIE-X选择Optical Character Recognition标注好后，使用label_studio.py报错
```
!python label_studio.py \
    --label_studio_file ./data/tax/label_studio.json \
    --save_dir ./data/tax \
    --splits 0.8 0.2 0\
    --task_type ext \
    --layout_analysis True

[2023-01-06 11:15:48,710] [    INFO] - Converting annotation data...
0it [00:00, ?it/s]
[2023-01-06 11:15:48,712] [    INFO] - Converting annotation data...
0it [00:00, ?it/s]
[2023-01-06 11:15:48,713] [    INFO] - Converting annotation data...
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "label_studio.py", line 138, in <module>
    do_convert()
  File "label_studio.py", line 99, in do_convert
    test_examples = data_converter.convert_cls_examples(raw_examples[p2:])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/tools.py", line 445, in convert_cls_examples
    items = self.process_text_tag(line, task_type="cls")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/utils/tools.py", line 281, in process_text_tag
    items["text"] = line["data"]["text"]
KeyError: 'text'
```

**Comment by 1061302569** [comment]
选择Object Detection with Bounding Boxes标注的会正常执行，这是label_studio.py不支持Optical Character Recognition标注吗

**Comment by linjieccc** [comment]
@1061302569 Hi，

请问是有微调OCR的需求么？如果是文档抽取的话标注任务类型需要选择 ``Object Detection with Bounding Boxes``

**Comment by 1061302569** [comment]
> @1061302569你好，
> 
> 请问是有微调OCR的需求吗？如果是文档抽取的话标注册类型需要选择`Object Detection with Bounding Boxes`

是文档抽取，我选择Object Detection with Bounding Boxes的文档抽取无法识别多行的表单，layout_analysis=True设置了也没用，如何让UIX识别多行
我看到Optical Character Recognition貌似是表单识别但是训练不了，直接报了上面的错误

**Comment by linjieccc** [comment]
可以通过下面的代码check下原始图片的文字识别情况

```python
from paddlenlp.utils.doc_parser import DocParser

doc_parser = DocParser(layout_analysis=True)
doc_path = "./cases/business_card.png"
parsed_doc = doc_parser.parse({"doc": doc_path})
doc_parser.write_image_with_results(
        doc_path,
        layout=parsed_doc['layout'],
        save_path="ocr_result.png")
```

**Comment by linjieccc** [comment]
另外方便的话可以提供下训练数据以及标注截图

**Comment by 1061302569** [comment]
> 另外方便的话可以提供下训练数据以及标注截图

![1672996699407](https://user-images.githubusercontent.com/44227598/210970580-8db13323-5219-439d-a51b-1b6a9567a810.jpg)
`[{'价税合计': [{'bbox': [[791, 453, 874, 471]],
            'end': 478,
            'probability': 0.8484589718075597,
            'start': 471,
            'text': '3456.04'}],
  '发票号码': [{'bbox': [[787, 45, 844, 59]],
            'end': 23,
            'probability': 0.9687713938143503,
            'start': 17,
            'text': '193305'}],
  '名称': [{'bbox': [[177, 486, 324, 500]],
          'end': 491,
          'probability': 0.8901710996199341,
          'start': 481,
          'text': '上海圆迈贸易有限公司'}],
  '地址、电话': [{'bbox': [[175, 534, 540, 548]],
             'end': 581,
             'probability': 0.9835612574322496,
             'start': 548,
             'text': '嘉定工业区叶城路1118号19层1901室021-39915587'}],
  '开票日期': [{'bbox': [[779, 71, 914, 88]],
            'end': 44,
            'probability': 0.9998079630539394,
            'start': 33,
            'text': '2019年10月18日'}],
  '纳税人识别号': [{'bbox': [[175, 505, 391, 526]],
              'end': 537,
              'probability': 0.5583727546217787,
              'start': 520,
              'text': '1310114666025597Y'}],
  '货物或应税劳务、服务名称': [{'bbox': [[40, 320, 260, 339]],
                    'end': 364,
                    'probability': 0.91663733613251,
                    'relations': {'单价': [{'bbox': [[601, 322, 647, 338]],
                                          'end': 378,
                                          'probability': 0.9927415114070257,
                                          'start': 371,
                                          'text': '2830.97'}],
                                  '单位': [{'bbox': [[384, 322, 398, 339]],
                                          'end': 370,
                                          'probability': 0.9896091164830167,
                                          'start': 369,
                                          'text': '台'}],
                                  '数量': [{'bbox': [[520, 324, 528, 335]],
                                          'end': 371,
                                          'probability': 0.9915928435684691,
                                          'start': 370,
                                          'text': '1'}],
                                  '税率': [{'bbox': [[804, 322, 832, 338]],
                                          'end': 389,
                                          'probability': 0.9934815927273917,
                                          'start': 385,
                                          'text': '13 %'}],
                                  '税额': [{'bbox': [[940, 322, 980, 338]],
                                          'end': 395,
                                          'probability': 0.8050369968795934,
                                          'start': 389,
                                          'text': '368.03'}],
                                  '规格型号': [{'bbox': [[291, 323, 334, 338]],
                                            'end': 369,
                                            'probability': 0.9994499747638912,
                                            'start': 364,
                                            'text': 'M433a'}],
                                  '金额': [{'bbox': [[746, 322, 794, 338]],
                                          'end': 385,
                                          'probability': 0.998912291687418,
                                          'start': 378,
                                          'text': '2830.97'}]},
                    'start': 343,
                    'text': '*计算机外部设备*惠普(HP)Laser)'},
                   {'bbox': [[42, 263, 273, 277]],
                    'end': 304,
                    'probability': 0.993878446048555,
                    'relations': {'单价': [{'bbox': [[606, 263, 647, 278]],
                                          'end': 317,
                                          'probability': 0.9997872225856668,
                                          'start': 311,
                                          'text': '227.47'}],
                                  '数量': [{'bbox': [[520, 264, 528, 277]],
                                          'end': 311,
                                          'probability': 0.9992939257807016,
                                          'start': 310,
                                          'text': '1'}],
                                  '税率': [{'bbox': [[803, 261, 834, 278]],
                                          'end': 327,
                                          'probability': 0.9991652172977261,
                                          'start': 323,
                                          'text': '13 %'}],
                                  '税额': [{'bbox': [[946, 263, 979, 278]],
                                          'end': 332,
                                          'probability': 0.9998089145696554,
                                          'start': 327,
                                          'text': '29.57'}],
                                  '规格型号': [{'bbox': [[292, 266, 347, 277]],
                                            'end': 310,
                                            'probability': 0.9995237981906939,
                                            'start': 304,
                                            'text': '政企延保1年'}],
                                  '金额': [{'bbox': [[753, 263, 795, 278]],
                                          'end': 323,
                                          'probability': 0.999902369973853,
                                          'start': 317,
                                          'text': '227.47'}]},
                    'start': 284,
                    'text': '*劳务*政企延保1年办公设备2000-3'}]}]`

**Comment by 1061302569** [comment]
> 货物或应税劳务、服务名称

票据中间的`货物或应税劳务、服务名称`比较长，只显示第一行的 换行后的无法识别，大神我该怎么办，对这个不太了解有什么办法能够一起识别到

**Comment by 1061302569** [comment]
> 可以通过下面的代码check下原始图片的文字识别情况
> 
> ```python
> from paddlenlp.utils.doc_parser import DocParser
> 
> doc_parser = DocParser(layout_analysis=True)
> doc_path = "./cases/business_card.png"
> parsed_doc = doc_parser.parse({"doc": doc_path})
> doc_parser.write_image_with_results(
>         doc_path,
>         layout=parsed_doc['layout'],
>         save_path="ocr_result.png")
> ```

![download](https://user-images.githubusercontent.com/44227598/210983418-620845b3-eeb9-41a2-88ae-e0afbf8206d9.png)
您好，用了您的代码识别是这样的

**Comment by linjieccc** [comment]
> ```python
> parsed_doc = doc_parser.parse({"doc": doc_path})
> ```

从识别结果来看，可能是默认版面分析模型对该场景的处理效果不是特别理想
![image](https://user-images.githubusercontent.com/40840292/211233106-7a78db98-80c0-47d3-9148-26969b109ab8.png)

建议可以参考pp-structure的[模型训练指南](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md)针对该场景进行训练，然后在这里替换成自己的版面分析模型

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/doc_parser.py#L254

**Comment by 1061302569** [comment]
> 

谢谢您

**Comment by 1061302569** [comment]
> > ```python
> > parsed_doc = doc_parser.parse({"doc": doc_path})
> > ```
> 
> 从识别结果来看，可能是默认版面分析模型对该场景的处理效果不是特别理想 ![image](https://user-images.githubusercontent.com/40840292/211233106-7a78db98-80c0-47d3-9148-26969b109ab8.png)
> 
> 建议可以参考pp-structure的[模型训练指南](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md)针对该场景进行训练，然后在这里替换成自己的版面分析模型
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/doc_parser.py#L254

谢谢您

**Comment by VignetteApril** [comment]
UIE-X的抽取效率问题i怎么解决。在CPU下抽取一张身份证要18S左右
