### ISSUE TITLE
unimo-text长度问题

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4364]
### 请提出你的问题

unimo-text最大长度是512吗？如果想生成文本的长度超过512有什么技巧吗？

**Comment by gongel** [comment]
你好，unimo-text模型支持的最大长度是512。生成(.generate)的时候，长度可以超过512，训练的时候可以尝试修改position_embedding的长度：https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.9/paddlenlp/transformers/unimo/modeling.py#L78

**Comment by ZTurboX** [comment]
> 你好，unimo-text模型支持的最大长度是512。生成(.generate)的时候，长度可以超过512，训练的时候可以尝试修改position_embedding的长度：https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.9/paddlenlp/transformers/unimo/modeling.py#L78

还有一个问题是，如果想生成的字数达到指定的字数，有什么技巧吗

**Comment by gongel** [comment]
> > 你好，unimo-text模型支持的最大长度是512。生成(.generate)的时候，长度可以超过512，训练的时候可以尝试修改position_embedding的长度：https://github.com/PaddlePaddle/PaddleNLP/blob/v2.4.9/paddlenlp/transformers/unimo/modeling.py#L78
> 
> 还有一个问题是，如果想生成的字数达到指定的字数，有什么技巧吗

最大和最小长度设置为指定长度
