### ISSUE TITLE
[Question]: 双语文本分类的预训练底座选择

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleNLP#4376]
### 请提出你的问题

需要同时对中文和英文文本做分类，预训练模型底座建议选一个多语言模型还是分别选中文和英文的？追求高精度

**Comment by lugimzzz** [comment]
可以尝试多语言模型（ernie-m-base,ernie-m-large）,如果是以中文为主，伴随一定量英文也可以考虑ernie 3.0系列模型。
