### ISSUE TITLE
[Question]: Ernie-layout: Add data preparation steps for funsd data

### ISSUE THREAD

**Issue by vishal-nayak1** [PaddlePaddle/PaddleNLP#4378]
### 请提出你的问题

Can you please share data preparation steps needed for model? like you have used for Funsd data.

**Comment by vishal-nayak1** [comment]
Also, how did you get segment bbox values from bbox value?

**Comment by linjieccc** [comment]
@vishal-nayak1 Hi,

The segment bbox can be get by the ocr model, for complete data preprocessing step (original docs to model inputs), you can refer to the code here https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/predictor.py#L756
