### ISSUE TITLE
ernie-layout如何进行领域预训练

### ISSUE THREAD

**Issue by yysirs** [PaddlePaddle/PaddleNLP#4379]
### 请提出你的问题

ernie-layout如何进行领域预训练，请问是否可以提供领域预训练代码

**Comment by linjieccc** [comment]
@yysirs Hi，

ernie-layout预训练代码目前没有开源，预训练具体思路可以参考论文 [ERNIE-Layout: Layout-Knowledge Enhanced Multi-modal Pre-training for Document Understanding](http://arxiv.org/abs/2210.06155)

**Comment by wawltor** [comment]
您好，我们将暂时该issue，如有疑问可以再次打开该issue。

**Comment by vanpersie32** [comment]
求ernie layout预训练代码
