### ISSUE TITLE
UIE相关功能NPU适配

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/PaddleNLP#4382]
### Feature request

NPU环境支持UIE微调、Taskflow一键预测等功能

### Motivation

UIE NPU环境验证，结合NPU特性优化相关代码，优化NPU环境的信息抽取体验

**Comment by wn1652400018** [comment]
啥叫NLU环境啊，自然语言理解环境吗？

**Comment by linjieccc** [comment]
> 啥叫NLU环境啊，自然语言理解环境吗？

@wn1652400018 这里NPU指华为昇腾系列硬件哈

**Comment by linjieccc** [comment]
closed as completed #4401
