### ISSUE TITLE
[Question]: UIE-X是否可以进行通用抽取

### ISSUE THREAD

**Issue by Originhhh** [PaddlePaddle/PaddleNLP#4386]
### 问题描述

您好，我看UIE-X的文档大多集中于如何微调某一类数据，如果我想讲几类数据混在一起进行抽取，不知UIE-X是否可以正常抽取，抽取的准确率会相较于只有一类数据时下降吗。

**Comment by wawltor** [comment]
可以通用抽取，准确率不会下降太多，但是这里可能需要考虑一个问题，就是抽取的内容比较多的时候，预测性能有所下降，所以建议抽取的内容范围要控制一下

**Comment by Originhhh** [comment]
好的谢谢
