### ISSUE TITLE
label_studio标注图片数据后生成训练样本的结果数据丢失空格

### ISSUE THREAD

**Issue by lddcdut** [PaddlePaddle/PaddleNLP#4387]
### 请提出你的问题

使用label_studio标注时，源数据是有空格的，如下图
![image](https://user-images.githubusercontent.com/43358822/211274060-dad8e078-564d-4f41-a970-4cfe91313c35.png)
生成训练样本后，空格丢失
![image](https://user-images.githubusercontent.com/43358822/211274155-953ced5f-2245-44e9-9877-c64026dbbc5e.png)
是不是ocr在识别时主动去掉了空格

**Comment by linjieccc** [comment]
@lddcdut Hi，

可以用下面的代码把OCR识别结果打印出来看下

```python
from paddlenlp.utils.doc_parser import DocParser

doc_parser = DocParser()
doc_path = "./cases/business_card.png" # 修改路径
parsed_doc = doc_parser.parse({"doc": doc_path})
print(parsed_doc['layout'])
```

**Comment by lddcdut** [comment]
打印出来确实丢掉了空格，可以选择ocr模型吗

**Comment by linjieccc** [comment]
目前默认用的是PP-OCRv3，可以考虑参考这里的微调文档进行[文本识别模型微调](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/finetune.md#3-%E6%96%87%E6%9C%AC%E8%AF%86%E5%88%AB%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83)

得到微调的模型后在这里指定一下OCR模型路径
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/doc_parser.py#L250
```python
self.ocr_infer_model = PaddleOCR(show_log=False, det_model_dir='{your_det_model_dir}')
```

模型加载方式可以参考[PaddleOCR自定义模型](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/whl.md#3-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)

**Comment by zhangxp12** [comment]
label-studio 导入txt后，在页面后端接口返回的 没有删除空格，是前端页面删除的空格， 咋解决啊？
