### ISSUE TITLE
[Question]: UIE微调模型过程中的性能评估

### ISSUE THREAD

**Issue by soultrans** [PaddlePaddle/PaddleNLP#4392]
### 请提出你的问题

您好，我尝试对关系抽取进行UIE模型微调，在doccano上少量标注数据后：
1.发现训练过程中的验证测试准确率一直很低（训练使用脚本，finetune.py）
2.使用单独的模型评估脚本，发现各类关系性能标准还可以（评估使用脚本，evaluate.py ）
请问，为什么会造成这样？训练过程中的验证指标统计与单独验证统计的标准有什么区别吗？

训练结果：
![image](https://user-images.githubusercontent.com/48265870/211440041-fbf4e697-d536-4433-bf75-ff626ffe7243.png)
评估结果:
![image](https://user-images.githubusercontent.com/48265870/211440128-ab78f6a4-9086-4f4c-b4e0-5bba6abd98cd.png)

**Comment by linjieccc** [comment]
@soultrans Hi，

从评估结果看部分关系类别的召回率偏低，建议针对性地增加一些标注数据。

另外关系抽取中，关系类型(P)的设置十分重要，需要遵循以下原则：

“{S}的{P}为{O}”需要能够构成语义合理的短语。比如对于三元组(S, 父子, O)，关系类别为父子是没有问题的。但按照UIE当前关系类型prompt的构造方式，“S的孩子为O”这个表达不是很通顺，因此P改成孩子更好，即“S的孩子为O”。

**Comment by soultrans** [comment]
> 

感谢指点，另外对您提供的关系设置原则有几点疑问：
1._“S的孩子为O”这个表达不是很通顺，因此P改成孩子更好，即“S的孩子为O”。_
为什么要这样呢？还是说(S, 父子, O)这个三元组调整为(S, 孩子, O)更合适？能再提供一些具体的说明吗？
2.此外有一些关系我想通过合并，将它们设置为一种关系在进行微调，是否可行？能否提供一些参考建议？如：“叔叔、伯伯、舅舅、姑妈”，统一标注设定为“亲戚”

**Comment by soultrans** [comment]
> @soultrans Hi，
> 
> 从评估结果看部分关系类别的召回率偏低，建议针对性地增加一些标注数据。
> 
> 另外关系抽取中，关系类型(P)的设置十分重要，需要遵循以下原则：
> 
> “{S}的{P}为{O}”需要能够构成语义合理的短语。比如对于三元组(S, 父子, O)，关系类别为父子是没有问题的。但按照UIE当前关系类型prompt的构造方式，“S的孩子为O”这个表达不是很通顺，因此P改成孩子更好，即“S的孩子为O”。

感谢指点，另外对您提供的关系设置原则有几点疑问：
1.“S的孩子为O”这个表达不是很通顺，因此P改成孩子更好，即“S的孩子为O”。
为什么要这样呢？还是说(S, 父子, O)这个三元组调整为(S, 孩子, O)更合适？能再提供一些具体的说明吗？
2.此外有一些关系我想通过合并，将它们设置为一种关系在进行微调，是否可行？能否提供一些参考建议？如：“叔叔、伯伯、舅舅、姑妈”，统一标注设定为“亲戚”

**Comment by linjieccc** [comment]
和关系抽取prompt构造有关系，例如三元组（赵弘殷，父子，赵匡胤） ``赵弘殷的父子是赵匡胤``就不是很通顺

**Comment by soultrans** [comment]
> 和关系抽取prompt构造有关系，例如三元组（赵弘殷，父子，赵匡胤） `赵弘殷的父子是赵匡胤`就不是很通顺

使用这样的构造关系（如：（赵弘殷，父子，赵匡胤），对模型微调产生的性能影响（主要是准确率）会很大吗？

**Comment by soultrans** [comment]
@linjieccc 您好，我想请问为什么训练过程中eval的结果评估测试会与单独使用模型评估脚本（evaluate.py）差的那么多？
训练过程中eval结果：
![image](https://user-images.githubusercontent.com/48265870/211710716-0f1fd6ad-2dab-4e1e-8586-5a400f700447.png)
单独模型评估：
![image](https://user-images.githubusercontent.com/48265870/211710796-702eeaf3-edae-41b2-a517-29e3d8a3ffb0.png)

如上图，单独看模型评估（evaluate.py）各类关系的训练识别结果准确率还是比较高的，但是进行微调训练时（finetune.py）的各项指标那么差？

**Comment by linjieccc** [comment]
debug模式下只针对验证集中的正样本进行评估，有可能是负样本（期望抽取结果为空的情况）被误识别出结果了，可以考虑在微调阶段适当增加一下负样本的比例

**Comment by soultrans** [comment]
> debug模式下只针对验证集中的正样本进行评估，有可能是负样本（期望抽取结果为空的情况）被误识别出结果了，可以考虑在微调阶段适当增加一下负样本的比例

@linjieccc 没太搞明白，请问：
1.微调过程（finetune.py）中evaluate数据与评估模型（evaluate.py）不都是使用的dev.txt吗？
2.为什么微调过程中的准确率(eval_precision)为40%左右，模型评估过程中的准确率（Precision）80%-90%，是因为微调过程会对验证集中所有数据进行验证，而模型评估只对验证集中正例数据进行评估验证？如果是这样的话，哪个更具有参考价值呢？

**Comment by chenchun0629** [comment]
提供一个思路，仅供参考。

比如：
第一步，可以将所有的关系合并为 “S的熟人为O”。
第二步，将“熟人”做多分类，推断具体分类（ “父亲“，”母亲“，”丈夫“， ”妻子“ ...）
