### ISSUE TITLE
文本分类训练

### ISSUE THREAD

**Issue by wanggei** [PaddlePaddle/PaddleNLP#4394]
### 请提出你的问题

使用cpu训练时，只会使用到一个cup的处理器，这是怎么回事，cup跑不满

**Comment by lugimzzz** [comment]
可以增大batch size和使用多线程训练方式增加使用率：`python -m paddle.distributed.launch --nproc_per_node=8 --backend='gloo' train.py `
文本分类训练可以考虑使用[aistudio](https://aistudio.baidu.com/aistudio/projectoverview/public)上免费训练gpu资源，提高训练效率。

**Comment by wanggei** [comment]
@ @lugimzzz 好的，谢谢

**Comment by wanggei** [comment]
还有就是想问一下，使用evaluate.py出现这样一种情况，在dev.txt中的文本如果超过了三行文本，就会出现这样的一个报错
ValueError: y should be a 1d array, got an array of shape (3, 2) instead. 但如果只有两行文本就不会，这个是我数据的问题吗？数据都是通过doccano生成的

**Comment by lugimzzz** [comment]
你检查一下你数据格式是否符合要求https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class：
![image](https://user-images.githubusercontent.com/63761690/211454613-93c7498d-c887-4809-8d01-6eaffc1e41ca.png)

**Comment by wanggei** [comment]
好的
