### ISSUE TITLE
[Question]: 英文文本可以调用Prompt API实现多标签分类吗？

### ISSUE THREAD

**Issue by CoderBinGe** [PaddlePaddle/PaddleNLP#4395]
### 请提出你的问题

您好！最近在学习Prompt learning用于多标签分类，发现PaddleNLP 的 Prompt API能够快速实现基于“ernie-3.0-base-zh”的中文多标签分类。请问一下，Prompt API能够实现基于“ernie-2.0-base-en”的英文多标签分类吗？（因为ernie-3.0-base-en还未支持）

**Comment by LemonNoel** [comment]
是可以的
