### ISSUE TITLE
[Question]: 使用Taskflow进行信息抽取时如何提升效率？

### ISSUE THREAD

**Issue by sysuls1** [PaddlePaddle/PaddleNLP#4396]
### 请提出你的问题

使用Taskflow进行信息抽取时，我的schema长度有500左右，每个文本抽取时间大概1分钟左右，怎样才能提升效率？

**Comment by wawltor** [comment]
具体是使用什么设备了？

**Comment by sysuls1** [comment]
> 具体是使用什么设备了？

Tesla T4

**Comment by wawltor** [comment]
> > 具体是使用什么设备了？
> 
> Tesla T4

使用了FP16加速了吗？

**Comment by sysuls1** [comment]
> > > 具体是使用什么设备了？
> > 
> > 
> > Tesla T4
> 
> 使用了FP16加速了吗？

Taskflow('information_extraction', schema=schema, batch_size=3,task_path=path,precision='fp16')，用了fp16加速

**Comment by wawltor** [comment]
首先确保 
1. FP16的环境是否设置正确

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/16698950/211457193-9dc1d914-9740-458c-993e-d09a1ea02de9.png">

2. 可以的话可以使用 uie-medium模型或者更小的模型来加速，默认使用的是uie-base模型

**Comment by sysuls1** [comment]
> 首先确保
> 
> 1. FP16的环境是否设置正确
> 
> <img alt="image" width="1025" src="https://user-images.githubusercontent.com/16698950/211457193-9dc1d914-9740-458c-993e-d09a1ea02de9.png">
> 
> 2. 可以的话可以使用 uie-medium模型或者更小的模型来加速，默认使用的是uie-base模型

小模型会影响finetune的效果吗？

**Comment by wawltor** [comment]
> > 首先确保
> > 
> > 1. FP16的环境是否设置正确
> > 
> > <img alt="image" width="1025" src="https://user-images.githubusercontent.com/16698950/211457193-9dc1d914-9740-458c-993e-d09a1ea02de9.png">
> > 
> > 2. 可以的话可以使用 uie-medium模型或者更小的模型来加速，默认使用的是uie-base模型
> 
> 小模型会影响finetune的效果吗？

medium模型之前的经验基本无损，具体需要微调后才知道结果

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有疑问，可以再次打开该issue。
