### ISSUE TITLE
[Question]: 使用doccano标注数据，对UIE模型进行微调

### ISSUE THREAD

**Issue by soultrans** [PaddlePaddle/PaddleNLP#4409]
### 请提出你的问题

请问，doccano标注的导出数据，经过官方数据处理脚本（doccano.py）处理后：
1.生成文件（sample_index.json）作用是什么？
2.数据处理脚本（doccano.py）中对标注数据的处理后，问什么会出现不在原标注语料中的prompt信息？
如：原始标注语料（”马静芬，女，褚时健夫人，褚橙庄园董事长“），其在train.txt的处理结果{"content": "马静芬，女，褚时健夫人，褚橙庄园董事长", "result_list": [], "prompt": "武修文的妻子"}，”武修文“并不在原始标注语料中，请问为什么出现这种情况？是作为负样本使用吗？如何避免或者减少这种情况？

**Comment by shtdbb** [comment]
1. 将数据集构造成阅读理解式的问题，以及负采样；
2. 这是负采样，随机替换了一个文中不存在的实体。可以再脚本中设置参数降低负采样频率
