### ISSUE TITLE
[Question]: NLP实体抽取图片关键信息，基于PaddleNLP SimpleServing 的服务化部署无法连接成功

### ISSUE THREAD

**Issue by Eddyzhangpan** [PaddlePaddle/PaddleNLP#4410]
### 请提出你的问题

Name: paddlenlp
Version: 2.4.4

NLP实体抽取图片关键信息，基于PaddleNLP SimpleServing 的服务化部署无法连接成功
显示404
INFO:     Uvicorn running on http://192.168.1.11:8189 (Press CTRL+C to quit)    
[2023-01-10 20:16:43,060] [    INFO] server.py:217 - Uvicorn running on http://1
92.168.1.11:8189 (Press CTRL+C to quit)                                         
INFO:     192.168.1.11:49997 - "POST /taskflow/uie HTTP/1.1" 404 Not Found  
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
client.py  代码
import requests
import json
from paddlenlp.utils.doc_parser import DocParser

# Define the docuemnt parser
doc_parser = DocParser()

image_paths = ['C:/Users/Administrator/Desktop/images/1.jpg']
image_base64_docs = []

# Get the image base64 to post
for image_path in image_paths:
    req_dict = {}
    doc = doc_parser.parse({"doc": image_path}, do_ocr=False)
    base64 = doc['image']
    req_dict['doc'] = base64
    image_base64_docs.append(req_dict)

url = "http://192.168.1.11:8189/taskflow/uie"
headers = {"Content-Type": "application/json"}
data = {'data': image_base64_docs}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.y代码
# Post the requests
r = requests.post(url=url, headers=headers, data=json.dumps(data))
datas = json.loads(r.text)
print(datas)

from paddlenlp import SimpleServer, Taskflow

# The schema changed to your defined schema
schema = ['货物名称', '销售方名称']
# The task path changed to your best model path
uie = Taskflow(
    "information_extraction",
    schema=schema,
    task_path="C:/NLPtest/document/checkpoint/model_best",
)
# If you want to define the finetuned uie service
app = SimpleServer()
#app.register_taskflow("uie", uie)
app.register_taskflow("taskflow/uie", uie)

**Comment by wawltor** [comment]
可以把PaddleNLP的版本提升到2.4.9试试

**Comment by Eddyzhangpan** [comment]
更新到2.5.0 还是不行哦
