### ISSUE TITLE
[Question]: ImportError: cannot import name 'DataConverter' from 'paddlenlp.utils.tools' (/root/miniconda3/lib/python3.7/site-packages/paddlenlp/utils/tools.py)paddlenlp2.3.2和2.4.1版本的文件里都没这个类了,哪个版本有,或者移到哪了

### ISSUE THREAD

**Issue by panliang5020** [PaddlePaddle/PaddleNLP#4424]
### 请提出你的问题

在准备文档关系抽取数据时,发现从label_studio平台导出的json数据运行label_studio.py出现报错,tools.py文件里缺少DataConverter类,所以这个类去哪了

**Comment by panliang5020** [comment]
问题已经解决了,更换了一下python版本,目前使用版本为3.9.15,可以正常调用这个类了,建议将至少需求的python版本加入readme

**Comment by sijunhe** [comment]
这个应该和python版本无关，我们支持python 3.7+
