### ISSUE TITLE
 text_summariztion中523M的pegasus tokenizer无法下载

### ISSUE THREAD

**Issue by stonebb** [PaddlePaddle/PaddleNLP#4430]
RuntimeError: Can't load tokenizer for 'IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese'.
Please make sure that 'IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese' is:
- a correct model-identifier of built-in pretrained models,
- or a correct model-identifier of community-contributed pretrained models,
- or the correct path to a directory containing relevant tokenizer files.

**Comment by gongel** [comment]
这边测试没问题哦
```python
from paddlenlp.transformers import PegasusChineseTokenizer
tokenzier =  PegasusChineseTokenizer.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")
```

**Comment by stonebb** [comment]
> 这边测试没问题哦
> 
> ```python
> from paddlenlp.transformers import PegasusChineseTokenizer
> tokenzier =  PegasusChineseTokenizer.from_pretrained("IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese")
> ```
测试还是不行，朋友，如果那里可以，可以不可以本地模型文件发一份给我，谢谢，460242157@qq.com

**Comment by gongel** [comment]
PaddleNLP版本是什么呢？建议安装最新的PaddleNLP

**Comment by stonebb** [comment]
paddle 2.4.2
paddlenlp 2.4.2









------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月12日(星期四) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP]  text_summariztion中523M的pegasus tokenizer无法下载 (Issue #4430)





 
paddlenlp版本是什么呢？

**Comment by gongel** [comment]
pip install -U paddlenlp

**Comment by stonebb** [comment]
谢谢，已成功，paddlenlp 2.4.9




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月12日(星期四) 中午11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP]  text_summariztion中523M的pegasus tokenizer无法下载 (Issue #4430)





 
pip install -U paddlenlp
