### ISSUE TITLE
[Question]: 关于文档关系抽取的疑问

### ISSUE THREAD

**Issue by panliang5020** [PaddlePaddle/PaddleNLP#4448]
### 请提出你的问题

目前文档关系抽取是否仅支持统一schema,如果schema中的关系名称不一致,但含义相同能否兼容,例如"项目名称"和"项目中文名","参考区间"和"参考范围"等,对同一类别票据如化验结果单,其中不同医院的化验单schema不同的情况,可否用同一种schema来定义关系.

**Comment by linjieccc** [comment]
@panliang5020 Hi，

针对文档中kv对，key值不太一样的情况，建议按照统一标签进行标注，这样标注出来的key有扩展性，来了新的说法也可以抽取
