### ISSUE TITLE
pegasus只能在GPU环境下进行推理吗，cpu可以跑吗

### ISSUE THREAD

**Issue by parkLGW** [PaddlePaddle/PaddleNLP#4454]
### 问题描述

pegasus进行文本摘要，在CPU上进行推理报错无法运行，必须是用GPU吗
FasterTransformer is not available because CUDA can not be found.

**Comment by gongel** [comment]
是的，高性能推理暂时只支持GPU哈。我们计划在2.6版本支持将生成式API做动转静，不走高性能推理。另外可以看看，不走推理，直接走predict是否可以满足需求呢?https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/pegasus/predict.py

**Comment by parkLGW** [comment]
用predict.py预测会报错：
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.  请问这可能是什么原因呢

**Comment by parkLGW** [comment]
> 是的，高性能推理暂时只支持GPU哈。我们计划在2.6版本支持将生成式API做动转静，不走高性能推理。另外可以看看，不走推理，直接走predict是否可以满足需求呢?https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_summarization/pegasus/predict.py

用predict.py预测会报错：
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. 请问这可能是什么原因呢
