### ISSUE TITLE
[Bug]: 加载ernie3-nano预训练权重的时候，报了警告，nano模型有4层，为什么警告第5层权重没用到？

### ISSUE THREAD

**Issue by NewToolAI** [PaddlePaddle/PaddleNLP#4458]
### 软件环境

```Markdown
paddlenlp                      2.4.9
paddlepaddle-gpu               2.4.0.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
model = ErnieForSequenceClassification.from_pretrained('ernie-3.0-nano-zh', num_classes=3)
```

在使用上面代码加载ernie3-nano权重的时候，报了如下警告，nano模型有4层，为什么警告第5层权重没用到？

<img width="935" alt="WechatIMG907" src="https://user-images.githubusercontent.com/17463933/212001940-e8497a54-244b-49c5-ace7-ea6b5eb299b9.png">

### 稳定复现步骤 & 代码

```Markdown
model = ErnieForSequenceClassification.from_pretrained('ernie-3.0-nano-zh', num_classes=3)
```

**Comment by wawltor** [comment]
> ### 软件环境
> ```gfm
> paddlenlp                      2.4.9
> paddlepaddle-gpu               2.4.0.post112
> ```
> 
> ### 重复问题
> * [x]  I have searched the existing issues
> 
> ### 错误描述
> ```gfm
> model = ErnieForSequenceClassification.from_pretrained('ernie-3.0-nano-zh', num_classes=3)
> ```
> 
> 在使用上面代码加载ernie3-nano权重的时候，报了如下警告，nano模型有4层，为什么警告第5层权重没用到？
> 
> <img alt="WechatIMG907" width="935" src="https://user-images.githubusercontent.com/17463933/212001940-e8497a54-244b-49c5-ace7-ea6b5eb299b9.png">
> 
> ### 稳定复现步骤 & 代码
> model = ErnieForSequenceClassification.from_pretrained('ernie-3.0-nano-zh', num_classes=3)

抱歉，这个warning是因为我们导出的模型多导出了一层模型参数，但是目前的使用方式对效果没有影响

**Comment by sijunhe** [comment]
Closing as duplicate of #4224
