### ISSUE TITLE
对semantic indexing进行场景定制训练的问题

### ISSUE THREAD

**Issue by justiceeem** [PaddlePaddle/PaddleNLP#446]
首先，谢谢paddlenlp团队推出的语义索引策略库和模型。这里有些问题想请教一下大佬们。
比如我想对一些特定场景下做语义相似的训练，我想采用的策略是使用paddlenlp团队提供好的训练数据对，然后添加一些自己收集的数据进去，然后采用最基本的方法进行训练。
请问这种做法有什么不妥之处吗，在数据量方面有没有什么限制或是要求呀。
还请各位大佬不吝赐教！

**Comment by tianxin1860** [comment]
> 首先，谢谢paddlenlp团队推出的语义索引策略库和模型。这里有些问题想请教一下大佬们。
> 比如我想对一些特定场景下做语义相似的训练，我想采用的策略是使用paddlenlp团队提供好的训练数据对，然后添加一些自己收集的数据进去，然后采用最基本的方法进行训练。
> 请问这种做法有什么不妥之处吗，在数据量方面有没有什么限制或是要求呀。
> 还请各位大佬不吝赐教！

1. 建议采用 2 阶段的训练策略: 基于我们 Release 的预训练模型进行热启，然后在自己的业务数据上进行 二阶段训练，这样可以在自己的业务场景下取得最优效果。
2. 数据量问题: 一般数据规模越大，效果越好，建议训练数据规模不要低于 10w 量级；

**Comment by justiceeem** [comment]
@tianxin1860 谢谢！
