### ISSUE TITLE
[Question]: cannot import name 'UIE' from 'paddlenlp.transformers'

### ISSUE THREAD

**Issue by wkunzhi** [PaddlePaddle/PaddleNLP#4463]
### 请提出你的问题

cannot import name 'UIE' from 'paddlenlp.transformers'

paddlenlp                2.4.4
paddlepaddle-gpu         2.4.0.post112

**Comment by sijunhe** [comment]
您好。2.4.4的时候，uie还没有加入`paddlenlp.transformers`. 您可以升级至2.4.5（推荐使用当前最新版本）以后即可使用。
