### ISSUE TITLE
[Bug]: TypeError: 'numpy.float64' object is not iterable

### ISSUE THREAD

**Issue by GoneWithTheCloud** [PaddlePaddle/PaddleNLP#4465]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.3.0
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Traceback (most recent call last):
  File "/home/james/PycharmProjects/paddle_nlp_learning/taskflow/uie_pipeline.py", line 16, in <module>
    result=text_cls('房间干净明亮，非常不错')
  File "/home/james/.conda/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/taskflow.py", line 603, in __call__
    results = self.task_instance(inputs)
  File "/home/james/.conda/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/task.py", line 440, in __call__
    results = self._postprocess(outputs)
  File "/home/james/.conda/envs/paddle/lib/python3.8/site-packages/paddlenlp/taskflow/zero_shot_text_classification.py", line 220, in _postprocess
    for i, class_score in enumerate(scores[0]):
TypeError: 'numpy.float64' object is not iterable
```

### 稳定复现步骤 & 代码

`
from paddlenlp import Taskflow

schema = ['这是一条差评', '这是一条好评']
text_cls = Taskflow("zero_shot_text_classification", schema=schema)
result=text_cls('房间干净明亮，非常不错')
print(result)
`

**Comment by LemonNoel** [comment]
paddlepaddle升级到2.4.1试试

**Comment by jiangliqin** [comment]
> paddlepaddle升级到2.4.1试试

试了，还是提示同样错误
paddlenlp                 2.5.0              
paddlepaddle-gpu          2.4.1.post112

**Comment by LemonNoel** [comment]
升级后删掉~/.paddlenlp/taskflow/zero_shot_text_classification目录后还会报错吗？

**Comment by GoneWithTheCloud** [comment]
升级后删掉~/.paddlenlp/taskflow/zero_shot_text_classification目录，能输出正常结果了

**Comment by jiangliqin** [comment]
@LemonNoel 你好，我升级后删掉~/.paddlenlp/taskflow/zero_shot_text_classification用test.py默认zero_shot_text_classification没问题，但task_path加载自己训练的模型还是会提示'numpy.float64' object is not iterable

**Comment by SakigamiYang** [comment]
for i, class_score in enumerate(scores[0])
我跑到以后scores就一定变成一维数组了，所以每次都报错

**Comment by LemonNoel** [comment]
可以安装 paddlepaddle develop 版本，或者将 scores[0] 改为 scores
