### ISSUE TITLE
[Question]: pipelines快速开发示例代码运行失败

### ISSUE THREAD

**Issue by ACbccc** [PaddlePaddle/PaddleNLP#4466]
### 请提出你的问题

CUDA10.2+cudnn7.6.5+python3.9

运行示例代码：
from pipelines.document_stores import FAISSDocumentStore
from pipelines.nodes import DensePassageRetriever, ErnieRanker

# Step1: Preparing the data
documents = [
  {'content': '金钱龟不分品种,只有生长地之分,在我国主要分布于广东、广西、福建、海南、香港、澳门等地,在国外主要分布于越南等亚热带国家和地区。',
  'meta': {'name': 'test1.txt'}},
  {'content': '衡量酒水的价格的因素很多的，酒水的血统(也就是那里产的，采用什么工艺等）；存储的时间等等，酒水是一件很难标准化得商品，只要你敢要价，有买的那就值那个钱。',
  'meta': {'name': 'test2.txt'}}
]

# Step2: Initialize a FaissDocumentStore to store texts of documents
document_store = FAISSDocumentStore(embedding_dim=768)
document_store.write_documents(documents)

# Step3: Initialize a DenseRetriever and build ANN index
retriever = DensePassageRetriever(document_store=document_store, query_embedding_model="rocketqa-zh-base-query-encoder",embed_title=False)
document_store.update_embeddings(retriever)

# Step4: Initialize a Ranker
ranker = ErnieRanker(model_name_or_path="rocketqa-base-cross-encoder")

# Step5: Initialize a SemanticSearchPipeline and ask questions
from pipelines import SemanticSearchPipeline
pipeline = SemanticSearchPipeline(retriever, ranker)
prediction = pipeline.run(query="衡量酒水的价格的因素有哪些?")

显示错误：
ValueError: The number of documents present in the SQL database does not match the number of embeddings in FAISS. Make sure your FAISS configuration file correctly points to the same database that was used when creating the original index.

**Comment by w5688414** [comment]
请问您锁在的目录是否有faiss的索引和sqlite的db文件，如果有请先删除，例如：

```
rm -rf faiss*
```

**Comment by ACbccc** [comment]
> 请问您锁在的目录是否有faiss的索引和sqlite的db文件，如果有请先删除，例如：
> 
> ```
> rm -rf faiss*
> ```

您好，在一个新空目录下运行，报出其他错误：
Loading Parameters from:rocketqa-base-cross-encoder

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 21
     18 document_store.update_embeddings(retriever)
     20 # Step4: Initialize a Ranker
---> 21 ranker = ErnieRanker(model_name_or_path="rocketqa-base-cross-encoder")
     23 # Step5: Initialize a SemanticSearchPipeline and ask questions
     24 from pipelines import SemanticSearchPipeline

File ~/anaconda3/envs/t2/lib/python3.9/site-packages/pipelines/nodes/ranker/ernie_ranker.py:74, in ErnieRanker.__init__(self, model_name_or_path, top_k, use_gpu, max_seq_len, progress_bar, batch_size, reinitialize, use_en)
     72 self.devices, _ = initialize_device_settings(use_cuda=use_gpu, multi_gpu=True)
     73 print("Loading Parameters from:{}".format(model_name_or_path))
---> 74 self.transformer_model = ErnieCrossEncoder(model_name_or_path, reinitialize=reinitialize)
     75 self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
     76 self.transformer_model.eval()

File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/semantic_search/modeling.py:254, in ErnieCrossEncoder.__init__(self, pretrain_model_name_or_path, num_classes, reinitialize, dropout)
    251 def __init__(self, pretrain_model_name_or_path, num_classes=2, reinitialize=False, dropout=None):
    252     super().__init__()
--> 254     self.ernie = ErnieEncoder.from_pretrained(pretrain_model_name_or_path, num_classes=num_classes)
    255     # Compatible to rocketv2 initialization for setting layer._epsilon to 1e-5
    256     if reinitialize:

File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:440, in PretrainedModel.from_pretrained(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs)
    391 """
    392 Creates an instance of `PretrainedModel`. Model weights are loaded
    393 by specifying name of a built-in pretrained model, or a community contributed model,
   (...)
    437         model = BertForSequenceClassification.from_pretrained('./my_bert/')
    438 """
    439 if cls.constructed_from_pretrained_config():
--> 440     return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs)
    442 resource_files = {}
    443 init_configuration = {}

File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:1261, in PretrainedModel.from_pretrained_v2(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs)
   1259 # 2. init the model
   1260 init_args = config["init_args"] or ()
-> 1261 model = cls(config, *init_args, **model_kwargs)
   1263 # 3. resolve model_weight file
   1264 model_weight_file = cls._resolve_model_file_path(
   1265     pretrained_model_name_or_path, cache_dir=cache_dir, from_hf_hub=from_hf_hub
   1266 )

File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/utils.py:170, in InitTrackerMeta.init_and_track_conf.<locals>.__impl__(self, *args, **kwargs)
    168     pre_init_func(self, init_func, *args, **kwargs)
    169 # keep full configuration
--> 170 init_func(self, *args, **kwargs)
    171 # registed helper by `post_init_func`
    172 if post_init_func:

TypeError: __init__() missing 1 required positional argument: 'output_emb_size'

**Comment by w5688414** [comment]
> > 请问您锁在的目录是否有faiss的索引和sqlite的db文件，如果有请先删除，例如：
> > ```
> > rm -rf faiss*
> > ```
> 
> 您好，在一个新空目录下运行，报出其他错误： Loading Parameters from:rocketqa-base-cross-encoder
> 
> TypeError Traceback (most recent call last) Cell In[1], line 21 18 document_store.update_embeddings(retriever) 20 # Step4: Initialize a Ranker ---> 21 ranker = ErnieRanker(model_name_or_path="rocketqa-base-cross-encoder") 23 # Step5: Initialize a SemanticSearchPipeline and ask questions 24 from pipelines import SemanticSearchPipeline
> 
> File ~/anaconda3/envs/t2/lib/python3.9/site-packages/pipelines/nodes/ranker/ernie_ranker.py:74, in ErnieRanker.**init**(self, model_name_or_path, top_k, use_gpu, max_seq_len, progress_bar, batch_size, reinitialize, use_en) 72 self.devices, _ = initialize_device_settings(use_cuda=use_gpu, multi_gpu=True) 73 print("Loading Parameters from:{}".format(model_name_or_path)) ---> 74 self.transformer_model = ErnieCrossEncoder(model_name_or_path, reinitialize=reinitialize) 75 self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path) 76 self.transformer_model.eval()
> 
> File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/semantic_search/modeling.py:254, in ErnieCrossEncoder.**init**(self, pretrain_model_name_or_path, num_classes, reinitialize, dropout) 251 def **init**(self, pretrain_model_name_or_path, num_classes=2, reinitialize=False, dropout=None): 252 super().**init**() --> 254 self.ernie = ErnieEncoder.from_pretrained(pretrain_model_name_or_path, num_classes=num_classes) 255 # Compatible to rocketv2 initialization for setting layer._epsilon to 1e-5 256 if reinitialize:
> 
> File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:440, in PretrainedModel.from_pretrained(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs) 391 """ 392 Creates an instance of `PretrainedModel`. Model weights are loaded 393 by specifying name of a built-in pretrained model, or a community contributed model, (...) 437 model = BertForSequenceClassification.from_pretrained('./my_bert/') 438 """ 439 if cls.constructed_from_pretrained_config(): --> 440 return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs) 442 resource_files = {} 443 init_configuration = {}
> 
> File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:1261, in PretrainedModel.from_pretrained_v2(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs) 1259 # 2. init the model 1260 init_args = config["init_args"] or () -> 1261 model = cls(config, *init_args, **model_kwargs) 1263 # 3. resolve model_weight file 1264 model_weight_file = cls._resolve_model_file_path( 1265 pretrained_model_name_or_path, cache_dir=cache_dir, from_hf_hub=from_hf_hub 1266 )
> 
> File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/utils.py:170, in InitTrackerMeta.init_and_track_conf..**impl**(self, *args, **kwargs) 168 pre_init_func(self, init_func, *args, **kwargs) 169 # keep full configuration --> 170 init_func(self, *args, **kwargs) 171 # registed helper by `post_init_func` 172 if post_init_func:
> 
> TypeError: **init**() missing 1 required positional argument: 'output_emb_size'

请问paddlenlp的版本是多少呢？升级到paddlenlp到2.5.0再试一下

**Comment by ACbccc** [comment]
> > > 请问您锁在的目录是否有faiss的索引和sqlite的db文件，如果有请先删除，例如：
> > > ```
> > > rm -rf faiss*
> > > ```
> > 
> > 
> > 您好，在一个新空目录下运行，报出其他错误： Loading Parameters from:rocketqa-base-cross-encoder
> > TypeError Traceback (most recent call last) Cell In[1], line 21 18 document_store.update_embeddings(retriever) 20 # Step4: Initialize a Ranker ---> 21 ranker = ErnieRanker(model_name_or_path="rocketqa-base-cross-encoder") 23 # Step5: Initialize a SemanticSearchPipeline and ask questions 24 from pipelines import SemanticSearchPipeline
> > File ~/anaconda3/envs/t2/lib/python3.9/site-packages/pipelines/nodes/ranker/ernie_ranker.py:74, in ErnieRanker.**init**(self, model_name_or_path, top_k, use_gpu, max_seq_len, progress_bar, batch_size, reinitialize, use_en) 72 self.devices, _ = initialize_device_settings(use_cuda=use_gpu, multi_gpu=True) 73 print("Loading Parameters from:{}".format(model_name_or_path)) ---> 74 self.transformer_model = ErnieCrossEncoder(model_name_or_path, reinitialize=reinitialize) 75 self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path) 76 self.transformer_model.eval()
> > File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/semantic_search/modeling.py:254, in ErnieCrossEncoder.**init**(self, pretrain_model_name_or_path, num_classes, reinitialize, dropout) 251 def **init**(self, pretrain_model_name_or_path, num_classes=2, reinitialize=False, dropout=None): 252 super().**init**() --> 254 self.ernie = ErnieEncoder.from_pretrained(pretrain_model_name_or_path, num_classes=num_classes) 255 # Compatible to rocketv2 initialization for setting layer._epsilon to 1e-5 256 if reinitialize:
> > File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:440, in PretrainedModel.from_pretrained(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs) 391 """ 392 Creates an instance of `PretrainedModel`. Model weights are loaded 393 by specifying name of a built-in pretrained model, or a community contributed model, (...) 437 model = BertForSequenceClassification.from_pretrained('./my_bert/') 438 """ 439 if cls.constructed_from_pretrained_config(): --> 440 return cls.from_pretrained_v2(pretrained_model_name_or_path, from_hf_hub=from_hf_hub, *args, **kwargs) 442 resource_files = {} 443 init_configuration = {}
> > File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py:1261, in PretrainedModel.from_pretrained_v2(cls, pretrained_model_name_or_path, from_hf_hub, *args, **kwargs) 1259 # 2. init the model 1260 init_args = config["init_args"] or () -> 1261 model = cls(config, *init_args, **model_kwargs) 1263 # 3. resolve model_weight file 1264 model_weight_file = cls._resolve_model_file_path( 1265 pretrained_model_name_or_path, cache_dir=cache_dir, from_hf_hub=from_hf_hub 1266 )
> > File ~/anaconda3/envs/t2/lib/python3.9/site-packages/paddlenlp/transformers/utils.py:170, in InitTrackerMeta.init_and_track_conf..**impl**(self, *args, **kwargs) 168 pre_init_func(self, init_func, *args, **kwargs) 169 # keep full configuration --> 170 init_func(self, *args, **kwargs) 171 # registed helper by `post_init_func` 172 if post_init_func:
> > TypeError: **init**() missing 1 required positional argument: 'output_emb_size'
> 
> 请问paddlenlp的版本是多少呢？升级到paddlenlp到2.5.0再试一下

升级2.5.0后已解决，感谢！
