### ISSUE TITLE
[Question]:  taskflow 文本相似度RocketQA 模型，输入同样的内容，结果都不是100%，而且比较低

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#4468]
### 请提出你的问题

taskflow，基于百万量级Dureader Retrieval数据集训练RocketQA并达到前沿文本相似效果，该模型预测的结果整体偏低，即使是完全相同的句子，结果也不是100%

**Comment by 1649759610** [comment]
你好，可以说明下你的测试数据情况（比如领域，文本长短，数据量等），以及列出一些case看看吗？

**Comment by w5688414** [comment]
rocketQA模型适合query passage这样的pair对，如果是query-query pair对，请使用simbert

**Comment by zhiyongLiu1114** [comment]
![Uploading image.png…]()


> rocketQA模型适合query passage这样的pair对，如果是query-query pair对，请使用simbert

了解了，谢谢
