### ISSUE TITLE
[Question]: nvidia-docker 快速部署显示connection error

### ISSUE THREAD

**Issue by ACbccc** [PaddlePaddle/PaddleNLP#4469]
### 请提出你的问题

环境：ubuntu16.04+cuda10.2+cudnn7.6.5+python3.9

docker镜像：registry.baidubce.com/paddlepaddle/paddlenlp:2.4.0-gpu-cuda10.2-cudnn7

错误问题：启动docker镜像后打开页面，显示connection error
                  docker logs paddlenlp_pipelines > test.txt 无结果
                  拖动文件至页面后显示：

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8891): Max retries exceeded with url: /file-upload (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe9859eda0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback:

File "/usr/local/python3.7.0/lib/python3.7/site-packages/streamlit/scriptrunner/script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
File "/root/PaddleNLP/pipelines/ui/webapp_semantic_search.py", line 206, in <module>
    main()
File "/root/PaddleNLP/pipelines/ui/webapp_semantic_search.py", line 107, in main
    raw_json = upload_doc(data_file)
File "ui/utils.py", line 189, in upload_doc
    response = requests.post(url, files=files).json()
File "/usr/local/python3.7.0/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/python3.7.0/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
File "/usr/local/python3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
File "/usr/local/python3.7.0/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
File "/usr/local/python3.7.0/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)

**Comment by w5688414** [comment]
请问elastic search容器有启动成功没？确保es是在容器内部正常访问

**Comment by ACbccc** [comment]
> 

您好，请问这样算是启动成功了吗？启动的时候也并未报错

sudo docker ps -a
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED              STATUS              PORTS                              NAMES
15ba92ad0b58   registry.baidubce.com/paddlepaddle/paddlenlp:2.4.0-gpu-cuda10.2-cudnn7   "/bin/sh -c '/root/s…"   About a minute ago   Up About a minute                                      paddlenlp_pipelines_gpu
81da84838e58   docker.elastic.co/elasticsearch/elasticsearch:8.3.3                      "/bin/tini -- /usr/l…"   3 minutes ago        Up 3 minutes        0.0.0.0:9200->9200/tcp, 9300/tcp   es02

**Comment by ACbccc** [comment]
> 请问elastic search容器有启动成功没？确保es是在容器内部正常访问

您好，请问这样算是启动成功了吗？
sudo docker ps -a
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED              STATUS              PORTS                              NAMES
15ba92ad0b58   registry.baidubce.com/paddlepaddle/paddlenlp:2.4.0-gpu-cuda10.2-cudnn7   "/bin/sh -c '/root/s…"   About a minute ago   Up About a minute                                      paddlenlp_pipelines_gpu
81da84838e58   docker.elastic.co/elasticsearch/elasticsearch:8.3.3                      "/bin/tini -- /usr/l…"   3 minutes ago        Up 3 minutes        0.0.0.0:9200->9200/tcp, 9300/tcp   es02

**Comment by w5688414** [comment]
> 
可以测一下es，用curl。

```
curl http://localhost:9200/_aliases?pretty=true
```

**Comment by ACbccc** [comment]
> > 
> 
> 可以测一下es，用curl。
> 
> ```
> curl http://localhost:9200/_aliases?pretty=true
> ```

在elasticsearch:8.3.3容器中执行，显示：
elasticsearch@81da84838e58:~$ curl http://localhost:9200/_aliases?pretty=true
{
  "dureader_robust_query_encoder" : {
    "aliases" : { }
  },
  "label" : {
    "aliases" : { }
  }
}


在paddlenlp:2.4.0-gpu-cuda10.2-cudnn7容器中执行，显示：
λ think-C246-WU4 ~ curl http://localhost:9200/_aliases?pretty=true
curl: (7) Failed to connect to localhost port 9200: Connection refused
