### ISSUE TITLE
是否能实现对长文本按照语义进行段落分割？

### ISSUE THREAD

**Issue by wenlincheng** [PaddlePaddle/PaddleNLP#4471]
### 请提出你的问题

请问PaddleNLP有没有提供训练好的长文本段落分割模型？效果如下

![企业微信截图_ce87f437-1061-4ae1-baf1-9dda5a370156](https://user-images.githubusercontent.com/35648826/212241872-01b856d1-4c8e-4094-81bf-a75f29a316e9.png)

**Comment by 1649759610** [comment]
当前repo中暂时没有这方面的工作，如果有注意到一些相关工作，欢迎提供相关信息。

**Comment by wenlincheng** [comment]
> 当前repo中暂时没有这方面的工作，如果有注意到一些相关工作，欢迎提供相关信息。

[长文本段落分割](https://developer.aliyun.com/article/1023307) 有相关的研究

**Comment by 1649759610** [comment]
收到，感谢。
