### ISSUE TITLE
[Question]:  taskflow 诗句生成输出为空

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#4472]
### 请提出你的问题

paddle-bfloat        0.1.7
paddle2onnx          0.9.8
paddlefsl            1.1.0
paddlenlp            2.5.0
paddlepaddle-gpu     2.4.1
paddleslim           2.3.4
paddlespeech         0.0.0
paddlespeech-feat    0.1.0

你好，以上是我使用的paddle相关python包，使用taskflow做诗句生成的任务时，设置device='cpu'，会出现模型输出为空的情况。这种情况在paddlenlp是2.3.2的时候也出现过，升级paddlenlp到2.4.2 的时候可以了，今天升级到了2.5又出现了

**Comment by 1649759610** [comment]
你好，可以提供一下可复现的代码吗？

**Comment by zhiyongLiu1114** [comment]
> 你好，可以提供一下可复现的代码吗？

![截屏2023-01-13 下午4 31 21](https://user-images.githubusercontent.com/47651345/212275161-9712e13e-4fb3-43ea-b8ef-37fcff594667.png)
