### ISSUE TITLE
[Question]: 请问标注工具 推荐Label Studio 还是 doccano？

### ISSUE THREAD

**Issue by Sun-Qiming** [PaddlePaddle/PaddleNLP#4473]
### 请提出你的问题

在model_zoo/uie章节以及applications/text_classification章节推荐的都是doccano，前者同时提供了Label Studio -》doccano转换工具
而applications/information_extraction/text推荐的则是Label Studio
请问
（1）二者推荐哪个，还是说都可以，因为只看到了labelstudio2doccano.py 不知道是不是支持互转
（2）paddle框架是否同时支持两种格式，还是需要统一转成doccano再操作？
谢谢

**Comment by 1649759610** [comment]
你好，推荐label-studio标注数据。

**Comment by Sun-Qiming** [comment]
> 你好，推荐label-studio标注数据。
@1649759610

请问
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/label_studio_text.md
中第二节 “文本分类、句子级情感倾向分类任务选择``Relation Extraction`。”、“命名实体识别、关系抽取、事件抽取、实体/评价维度分类任务选择``Relation Extraction`。”
是说这几种任务都是用Relation Extraction模式？不使用label-studio中提供的“named entity recognition”和“text classification”？

**Comment by 1649759610** [comment]
这里文档描述有误，文本分类、句子级情感倾向分类任务选择Text classification，命名实体识别、关系抽取、事件抽取、实体/评价维度分类任务选择Relation Extraction。

因为Relation Extraction模式能够覆盖到ner，考虑统一因素，所以这里推荐使用这个模式标注ner相关任务。

**Comment by linjieccc** [comment]
这里文档有误，已提交修复PR #4489，感谢反馈 @Sun-Qiming

**Comment by qbit-git** [comment]
纯文本标注，doccano 比 Label Studio 好用很多。
不过似乎 doccano 停更了
