### ISSUE TITLE
[Docs]: GPT文档中的数据无法获取

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#4475]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 详细描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/tree/be7d123409d54a1c82af93cab6a6707542003ddc/model_zoo/gpt#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87

这个链接下提供的OpenWebText2数据，无法下载（即：输入命令 “wget https://mystic.the-eye.eu/public/AI/pile_preliminary_components/openwebtext2.jsonl.zst.tar” 无法下载）。

进入OpenWebText2的网站也无法点击下载（https://openwebtext2.readthedocs.io/en/latest/index.html#download-plug-and-play-version）

是我个人访问网页的问题还是怎么？是否可以提供一个paddle的数据源以便于跑通整个数据获取与制作流程（类似于：wget https://bj.bcebos.com/paddlenlp/models/transformers/gpt/data/gpt_en_dataset_300m_ids.npy）
```

**Comment by ZHUI** [comment]
收到，我这边同步询问一下上游数据repo https://github.com/EleutherAI/openwebtext2/issues/7

**Comment by ZeyuTeng96** [comment]
> 

还请问下大佬GPT这类自回归模型做继续预训练和下游任务训练（类似于：诗歌、春联生成）是否没有区别？所以这个readme所提供的训练脚本也是用的run_pretrain?

其次，能否考虑提供一个中文数据集做训练的例子？因为create_pretrain_data设置的参数设置比较多，中英文数据做处理还不一样呢

**Comment by ZeyuTeng96** [comment]
> 收到，我这边同步询问一下上游数据repo [EleutherAI/openwebtext2#7](https://github.com/EleutherAI/openwebtext2/issues/7)

还请问下大佬GPT这类自回归模型做继续预训练和生成式下游任务训练（类似于：诗歌、春联生成）是否没有区别？所以这个readme（https://github.com/PaddlePaddle/PaddleNLP/tree/be7d123409d54a1c82af93cab6a6707542003ddc/model_zoo/gpt#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83 ）所提供的训练脚本也是用的run_pretrain?

其次，能否考虑提供一个中文数据集做训练的例子？因为create_pretrain_data设置的参数设置比较多，中英文数据做处理还不一样呢 @ZHUI

**Comment by ZeyuTeng96** [comment]
刚刚看数据集可以通过wget下载和网页手动点击下载了，能否麻烦大佬再回答一下我之前的问题 @ZHUI

**Comment by ZeyuTeng96** [comment]
同时，执行如下命令报错了：
tar -xvf openwebtext2.json.zst.tar -C  /path/to/openwebtext

报错如下：
tar: openwebtext2.json.zst.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

**Comment by ZHUI** [comment]
> > 收到，我这边同步询问一下上游数据repo [EleutherAI/openwebtext2#7](https://github.com/EleutherAI/openwebtext2/issues/7)
> 
> 还请问下大佬GPT这类自回归模型做继续预训练和生成式下游任务训练（类似于：诗歌、春联生成）是否没有区别？所以这个readme（https://github.com/PaddlePaddle/PaddleNLP/tree/be7d123409d54a1c82af93cab6a6707542003ddc/model_zoo/gpt#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83 ）所提供的训练脚本也是用的run_pretrain?
> 
> 其次，能否考虑提供一个中文数据集做训练的例子？因为create_pretrain_data设置的参数设置比较多，中英文数据做处理还不一样呢 @ZHUI


所提供的训练脚本也是用的run_pretrain?
- 是预训练。诗歌、春联之类的领域数据，在已有的模型基础上，把数据替换成领域数据即可
中文数据集做训练
- 其实是一样的，你可以用 gpt-cpm 这些中文模型的词表制作数据

**Comment by ZHUI** [comment]
> 同时，执行如下命令报错了： tar -xvf openwebtext2.json.zst.tar -C /path/to/openwebtext
> 
> 报错如下： tar: openwebtext2.json.zst.tar: Cannot open: No such file or directory tar: Error is not recoverable: exiting now

看是不是文件坏的

**Comment by ZeyuTeng96** [comment]
> > 同时，执行如下命令报错了： tar -xvf openwebtext2.json.zst.tar -C /path/to/openwebtext
> > 报错如下： tar: openwebtext2.json.zst.tar: Cannot open: No such file or directory tar: Error is not recoverable: exiting now
> 
> 看是不是文件坏的

排查了一下发现问题了，这里下载下来的文件是openwebtext2.jsonl.zst.tar （jsonl格式），命令输入的是openwebtext2.json.zst.tar（json格式）。其次，就是后面跟着的-C /path/to/openwebtext，整个命令很容易让用户直接想当然的复制黏贴无法运行，可能麻烦大佬考虑下怎么修改比较好 @ZHUI

**Comment by ZeyuTeng96** [comment]
> > > 收到，我这边同步询问一下上游数据repo [EleutherAI/openwebtext2#7](https://github.com/EleutherAI/openwebtext2/issues/7)
> > 
> > 
> > 还请问下大佬GPT这类自回归模型做继续预训练和生成式下游任务训练（类似于：诗歌、春联生成）是否没有区别？所以这个readme（https://github.com/PaddlePaddle/PaddleNLP/tree/be7d123409d54a1c82af93cab6a6707542003ddc/model_zoo/gpt#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83 ）所提供的训练脚本也是用的run_pretrain?
> > 其次，能否考虑提供一个中文数据集做训练的例子？因为create_pretrain_data设置的参数设置比较多，中英文数据做处理还不一样呢 @ZHUI
> 
> 所提供的训练脚本也是用的run_pretrain?
> 
> * 是预训练。诗歌、春联之类的领域数据，在已有的模型基础上，把数据替换成领域数据即可
>   中文数据集做训练
> * 其实是一样的，你可以用 gpt-cpm 这些中文模型的词表制作数据

所以，还想请问大佬一下GPT的预训练和下游生成式任务的训练，这两个概念对于GPT这种自回归模型而言，有区别嘛？因为我对这块不是很了解，能否麻烦大佬详细解释一下

**Comment by ZeyuTeng96** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/gpt#%E5%8D%95%E5%8D%A1%E8%AE%AD%E7%BB%83

同时，这个单卡训练的命令，我运行也报错了。paddlenlp版本为2.4.7。执行命令为：
python run_pretrain.py \
  --model_name_or_path gpt2-en \
  --input_dir ./data \
  --output_dir ./output_dir/pretrain \
  --weight_decay 0.01 \
  --max_steps 500000 \
  --save_steps 100000 \
  --device gpu:1 \
  --warmup_steps 320000 \
  --warmup_ratio 0.01 \
  --mirco_batch_size 4 \
  --eval_steps 100 \
  --do_train true \
  --do_predict true
（上述命令的“\”不显示，但是shell脚本里有加）

报错信息为：
Traceback (most recent call last):
  File "run_pretrain.py", line 473, in <module>
    do_train()
  File "run_pretrain.py", line 344, in do_train
    [ModelArguments, TrainingArguments, DataArguments]
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/argparser.py", line 230, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the PdArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the PdArgumentParser: ['--mirco_batch_size', '4']

如果删去执行命令中的 “--mirco_batch_size 4 \”则可以成功运行，这块是什么原因嘞大佬 @ZHUI

**Comment by ZHUI** [comment]
> 所以，还想请问大佬一下GPT的预训练和下游生成式任务的训练，这两个概念对于GPT这种自回归模型而言，有区别嘛？因为我对这块不是很了解，能否麻烦大佬详细解释一下

没有区别，可以看做是领域数据上继续训练了一会儿。

**Comment by ZHUI** [comment]
> 报错信息为： Traceback (most recent call last): File "run_pretrain.py", line 473, in do_train() File "run_pretrain.py", line 344, in do_train [ModelArguments, TrainingArguments, DataArguments] File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/argparser.py", line 230, in parse_args_into_dataclasses raise ValueError(f"Some specified arguments are not used by the PdArgumentParser: {remaining_args}") ValueError: Some specified arguments are not used by the PdArgumentParser: ['--mirco_batch_size', '4']
> 
> 如果删去执行命令中的 “--mirco_batch_size 4 \”则可以成功运行，这块是什么原因嘞大佬 @ZHUI

抱歉，这个是因为 前段时间对脚本进行了升级，readme 暂时还未修改的缘故。可以将 mirco_batch_size -> per_device_train_batch_size 试试。


@wj-Mcat 修改脚本后，注意同步修改一下 readme

**Comment by ZeyuTeng96** [comment]
> > 报错信息为： Traceback (most recent call last): File "run_pretrain.py", line 473, in do_train() File "run_pretrain.py", line 344, in do_train [ModelArguments, TrainingArguments, DataArguments] File "/usr/local/lib/python3.7/dist-packages/paddlenlp/trainer/argparser.py", line 230, in parse_args_into_dataclasses raise ValueError(f"Some specified arguments are not used by the PdArgumentParser: {remaining_args}") ValueError: Some specified arguments are not used by the PdArgumentParser: ['--mirco_batch_size', '4']
> > 如果删去执行命令中的 “--mirco_batch_size 4 \”则可以成功运行，这块是什么原因嘞大佬 @ZHUI
> 
> 抱歉，这个是因为 前段时间对脚本进行了升级，readme 暂时还未修改的缘故。可以将 mirco_batch_size -> per_device_train_batch_size 试试。
> 
> @wj-Mcat 修改脚本后，注意同步修改一下 readme

嗯嗯，辛苦大佬了

**Comment by ZeyuTeng96** [comment]
> > 所以，还想请问大佬一下GPT的预训练和下游生成式任务的训练，这两个概念对于GPT这种自回归模型而言，有区别嘛？因为我对这块不是很了解，能否麻烦大佬详细解释一下
> 
> 没有区别，可以看做是领域数据上继续训练了一会儿。

谢谢大佬
