### ISSUE TITLE
AttributeError: module 'paddlenlp.datasets' has no attribute 'GlueCoLA'

### ISSUE THREAD

**Issue by Darshcg** [PaddlePaddle/PaddleNLP#448]
Hi,

I have installed paddlenlp and while running https://github.com/PaddlePaddle/PaddleSlim/blob/develop/demo/ofa/bert/run_glue_ofa.py this script, I am getting below error,

Please help me to resolve this issue:

```
Traceback (most recent call last):
  File "run_glue_ofa.py", line 37, in <module>
    "cola": (datasets.GlueCoLA, Mcc),
AttributeError: module 'paddlenlp.datasets' has no attribute 'GlueCoLA'
```

Thanks,
Darshan

**Comment by ZeyuChen** [comment]
@Darshcg We are checking this issue, will reply you soon.

**Comment by LiuChiachi** [comment]
Hi,

We recommend you to refer to the demo in [PaddleNLP ofa example](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa), and it's same as the demo you ran before and uses paddlenlp2.0.0.

And we recommend you to  install newest paddleslim following the command below because develop branch fixed a bug just now, and we will release a new version soon:)
```
git clone https://github.com/PaddlePaddle/PaddleSlim
python setup.py build && python setup.py install
```

Thanks,
LiuChiachi

**Comment by Darshcg** [comment]
Hi @LiuChiachi,

Thanks for the reply.
I had followed the same but still did not worked.

**Comment by LiuChiachi** [comment]
Hello @Darshcg , is the result wrong or the program hangs?  Could you please provide a screenshot of your error report ? Thanks!

**Comment by Darshcg** [comment]
Hi @LiuChiachi,

Thanks for your support.

I am getting the same error after installing the latest version of paddleslim and changing paddlenlp to 2.0.0:

```
Traceback (most recent call last):
  File "run_glue_ofa.py", line 37, in <module>
    "cola": (datasets.GlueCoLA, Mcc),
AttributeError: module 'paddlenlp.datasets' has no attribute 'GlueCoLA'

```

Regards,
Darshan

**Comment by ZeyuChen** [comment]
@Darshcg Please also try PaddleNLP ofa exmaple, and run the code as the link below.
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression/ofa/run_glue_ofa.py#L294
We use `load_dataset` API the access dataset. the  `datasets.GlueCoLA`  API has deprecated.
You need to clone PaddleNLP repo and try the latest code.

**Comment by Darshcg** [comment]
Hi @ZeyuChen and @LiuChiachi,

I was able to overcome that issue when I used this: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa 

Thank you for your help.

Regards,
Darshan
