### ISSUE TITLE
[Question]: UIE 用 evaluate.py 和 taskflow 识别结果不同

### ISSUE THREAD

**Issue by zhengbiqing** [PaddlePaddle/PaddleNLP#4481]
### 请提出你的问题

fineturn训练了1个信息抽取模型，发现evaluate.py 和 taskflow输出的结果不同：

1、待识别内容：1.txt：
    {"content": "A further study revealed that miR-124 directly targeted FZD4 and LRP6, which encode a receptor and co-receptor of the Wnt/β-catenin signaling pathway, respectively, thus reducing the activity of this signaling.", "result_list": [{"text": "FZD4", "start": 56, "end": 60}, {"text": "LRP6", "start": 65, "end": 69}], "prompt": "miR-124's target genes is"}

2、evaluate.py输出识别出了1个关系：
python .\evaluate_zbq.py --model_path D:\projects\NLP\paddlenlp\uie_en\checkpoint-gene-0110\model_best  --test_path ./gene-0110/ext/1.txt --batch_size 8  --max_seq_len 512 --debug
输出：
[2023-01-14 21:05:53,353] [    INFO] - -----------------------------
[2023-01-14 21:05:53,354] [    INFO] - 关系：'s target genes is
[2023-01-14 21:05:53,355] [    INFO] - Evaluation Precision: 1.00000 | Recall: 0.50000 | F1: 0.66667 | acc: 0.00000 | Sample Num: 1

3、但是taskflow则未识别出任何东西：
schema = ["'s target genes is"]
ie_en = Taskflow('information_extraction', schema=schema, task_path=r'D:\projects\NLP\paddlenlp\uie_en\checkpoint-gene-0110\model_best')

with open(r'D:\projects\NLP\paddlenlp\uie_en\gene-0110\ext\1.txt',"r", encoding='utf-8') as f:
    lines = f.readlines()

for line in lines:
    d = eval(line)
    c = d['content']
    pred = ie_en(c)
    print(pred)

输出：
[2023-01-14 21:06:26,770] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'D:\projects\NLP\paddlenlp\uie_en\checkpoint-gene-0110\model_best'.
[{}]

我看前面有人提到了这个问题：https://github.com/PaddlePaddle/PaddleNLP/issues/2428
有大神能说一下为什么吗？

**Comment by linjieccc** [comment]
@zhengbiqing Hi，可能是model_best下面的模型权重有更新但静态图模型没有更新，我们在新版本优化了这部分体验 #3506 可以升级一下paddlenlp的版本再试试

**Comment by zhaoqf-cq** [comment]
> @zhengbiqing Hi，可能是model_best下面的模型权重有更新但静态图模型没有更新，我们在新版本优化了这部分体验 #3506 可以升级一下paddlenlp的版本再试试

大佬， 请问一下 没有 模型微调后 finetune.py 后的结果详解啊... 文件有点多，完全不知道那些是什么，哪些不需要，跟着产业级微调出来的模型，自己想使用直接用checkpoint吗？ 文档里面说的什么蒸馏压缩不需要的吗？
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/27794583/eb3b2d24-be50-4d43-9dfc-b75a597a4b70)
