### ISSUE TITLE
[Question]:Taskflow("question_generation") 执行过程异常，似乎卡住了。请问这么解决?

### ISSUE THREAD

**Issue by BuryMe** [PaddlePaddle/PaddleNLP#4482]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/25027988/212481614-c3cf0c90-49d4-4b1c-92ef-6723c74d02c7.png)

version:2.4.1

code:

     import paddle
     from paddlenlp import Taskflow

     if __name__ == '__main__':
            seg = Taskflow("word_segmentation")  
            print(seg("近日国家卫健委发布第九版新型冠状病毒肺炎诊疗方案"))
            question_generator = Taskflow("question_generation")
            r = question_generator([
                {
                    "context": "奇峰黄山千米以上的山峰有77座，整座黄山就是一座花岗岩的峰林，自古有36大峰，36小峰，最高峰莲花峰、最险峰天都峰和观日出的最佳点光明顶构成黄山的三大主峰。",
                    "answer": "莲花峰"}
            ])
            print("---------------")
            print(r)

run log pic:
![image](https://user-images.githubusercontent.com/25027988/212481753-35c2bb65-dcd6-4623-b64e-55b4569c7bfd.png)

程序似乎卡住，不往下执行了，请问这是为这么？我该这么处理？

**Comment by westfish** [comment]
![image](https://user-images.githubusercontent.com/20476674/212644245-ee8bccb4-cebd-4f0f-8da7-7811e3ddcd5a.png)
你好我测试了一下，应该是可以正常运行的，请确保paddlenlp升级到最新版本。
