### ISSUE TITLE
uie实体识别文本长度过长会导致内存爆掉

### ISSUE THREAD

**Issue by MachineSheep** [PaddlePaddle/PaddleNLP#4484]
### 请提出你的问题

在使用uie微调之后的模型时，使用Taskflow进行推理，当输入文本长度2万左右时，会导致32G内存爆掉，同时系统检测显示，会从硬盘中加载大量的数据进入内存中。请问文本分割之后，是怎么进行推理的呢？

包版本：
paddlepaddle==2.3.0
paddlenlp==2.4.0

**Comment by linjieccc** [comment]
@MachineSheep Hi，在调用Taskflow的时候适当减小batch_size并打开lazy_load试下呢

```python
uie = Taskflow("information_extraction", schema=schema, lazy_load=True, batch_size=2)
```

**Comment by MachineSheep** [comment]
> 

有Taskflow参数讲解的链接吗

**Comment by linjieccc** [comment]
是指具体参数释义么，uie可以参考这里：[Taskflow UIE可配置参数说明](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E5%8F%AF%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E-3)
