### ISSUE TITLE
希望UIEX能够支持checkpointing技术

### ISSUE THREAD

**Issue by wn1652400018** [PaddlePaddle/PaddleNLP#4486]
### Feature request

尽量减少显存消耗

### Motivation

在训练uiex时，发现batch=1，len=512，1660卡6g的显存不够用。需要checkpointing来支持训练。

### Your contribution

.

**Comment by linjieccc** [comment]
@wn1652400018 Hi，recompute功能目前正在开发中，可以关注下这个PR: #4490
