### ISSUE TITLE
[Question]: 信息提取不同位置但相同位置触发词处理

### ISSUE THREAD

**Issue by geasyheart** [PaddlePaddle/PaddleNLP#4496]
### 请提出你的问题

作者大大好，比如“张三打算吃饭，李四打算喝水”，对于同样的触发词“打算”但是位置索引不同的这种情况，如何构造prompt呢，以及你们认为怎样处理会更好呢？非常感谢！

**Comment by geasyheart** [comment]
比如：
索引为(2,4)的打算的主语，索引为(2,4)的打算的宾语
索引为(9,11)的打算的主语，索引为(9,11)的打算的宾语

**Comment by linjieccc** [comment]
UIE目前还不支持单个句子内触发词字面相同的情况，这个case可以看下能否改成关系抽取的形式。比如将人物作为第一阶段的抽取目标，对应的schema可以是：

```python
schema = {"人物": "意图"}
```
