### ISSUE TITLE
[Question]: 文本分类应用端到端问题

### ISSUE THREAD

**Issue by ningpengtao-coder** [PaddlePaddle/PaddleNLP#4497]
### 请提出你的问题

我使用文本分类应用时，阅读了一下预测代码发现预测分类两步，第一步是分词，第二步是推理。

我不太会使用python，希望通过其他语言调用，例如java。这样我需要通过onnx运行时去推理，
但是需要分词，分词又没有可以直接分词的onnx 模型，就卡住了。

有没有一个完整的端到端模型既可以分词又可以推理？

**Comment by joey12300** [comment]
您好，请问您是开发安卓代码开发文本分类应用吗？ PaddleNLP ERNIE 3.0 Tiny 模型基于 FastDeploy 提供安卓端部署示例，使用C++对整个端到端流程进行封装，并用JNI导出了Java接口，可以在Java端进行调用，看看下面这个示例能否解决你的问题？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-tiny/deploy/android

**Comment by ningpengtao-coder** [comment]
@joey12300 谢谢，文本分类应用的文档上没有提到，我以为不支持呢。

**Comment by GJYWorld** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-tiny/deploy/android 文档的链接找不到了，可否再提供一下呢
