### ISSUE TITLE
您好，PaddleNLP/examples/text_classification/rnn/deploy/   能否提供serving部署示例

### ISSUE THREAD

**Issue by alei76** [PaddlePaddle/PaddleNLP#451]
您好，PaddleNLP/examples/text_classification/rnn/deploy/   能否提供serving部署示例,折腾一天的就是不行。
环境：
    win10+Docker Desktop
    PaddleNLP用的 PaddleNLP v2.0.0，Serving 用的是0.6.0版本
    推理模型已经导出成功，服务能正常启动 ,rpc和http都没调用成功
    rpc: python3 -m paddle_serving_server.serve --model Intention_detection_model --thread 2 --port 9292 --use_multilang
    http:python3 -m paddle_serving_server.serve --model Intention_detection_model --thread 2 --port 9292 --use_multilang --name uci

**Comment by Steffy-zxf** [comment]
@alei76 感谢反馈！Server端部署脚本正在开发，预计下周提供。开发完成后，第一时间通知您！同时想了解下 您的具体应用场景是什么样的？

**Comment by alei76** [comment]
> @alei76 感谢反馈！Server端部署脚本正在开发，预计下周提供。开发完成后，第一时间通知您！同时想了解下 您的具体应用场景是什么样的？

@Steffy-zxf ，非常感谢，智能客服相关的：客户意图识别、来电原因分类、工单信息提取、升级投诉预测等等，我们是你们合作伙伴，用你们的asr/tts/edp/ngd等,但是客户有些场景需要定制化，需要自己开发一些模型。
examples\text_classification\rnn\train.py  
121 行    attention = SelfInteractiveAttention(hidden_size=2 * stm_hidden_size)     stm_hidden_size  少了个字母lstm_hidden_size
