### ISSUE TITLE
[Question]:UIE能否处理多个触发词的事件抽取

### ISSUE THREAD

**Issue by prtj** [PaddlePaddle/PaddleNLP#4515]
### 请提出你的问题

有多个触发词的事件类型，UIE能否进行抽取或者基于标注的数据进行针对性训练

**Comment by linjieccc** [comment]
UIE支持处理多个触发词的情况，除了触发词字面相同的特殊case(参考#4496)，可能需要尝试替换一下第一阶段的抽取目标
