### ISSUE TITLE
[Question]: neural search 排序模型cross_encoder web_service.py 使用tensorRT出错

### ISSUE THREAD

**Issue by lin1490188** [PaddlePaddle/PaddleNLP#4521]
### 请提出你的问题

config use_encryption model here None
[DAG] Succ init
[PipelineServicer] succ init
2023/01/19 15:57:35 start proxy service
W0119 15:57:38.186408 16534 analysis_predictor.cc:1118] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0119 15:57:38.246953 16534 analysis_predictor.cc:881] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [delete_weight_dequant_linear_op_pass]
--- Running IR pass [delete_quant_dequant_linear_op_pass]
--- Running IR pass [add_support_int8_pass]
I0119 15:57:39.121083 16534 fuse_pass_base.cc:57] ---  detected 425 subgraphs
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [preln_embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
I0119 15:57:39.446327 16534 fuse_pass_base.cc:57] ---  detected 25 subgraphs
--- Running IR pass [preln_skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [trt_squeeze2_matmul_fuse_pass]
--- Running IR pass [trt_reshape2_matmul_fuse_pass]
--- Running IR pass [trt_flatten2_matmul_fuse_pass]
--- Running IR pass [trt_map_matmul_v2_to_mul_pass]
I0119 15:57:39.483711 16534 fuse_pass_base.cc:57] ---  detected 74 subgraphs
--- Running IR pass [trt_map_matmul_v2_to_matmul_pass]
I0119 15:57:39.491195 16534 fuse_pass_base.cc:57] ---  detected 24 subgraphs
--- Running IR pass [trt_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0119 15:57:39.572584 16534 fuse_pass_base.cc:57] ---  detected 74 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I0119 15:57:39.604351 16534 tensorrt_subgraph_pass.cc:145] ---  detect a sub-graph with 17 nodes
I0119 15:57:39.609318 16534 tensorrt_subgraph_pass.cc:433] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
failed to create predictor: Log_id: 0  Raise_msg: (InvalidArgument) The input [layer_norm_37.tmp_2] shape of trt subgraph is [-1,-1,768], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at /paddle/paddle/fluid/inference/tensorrt/engine.h:118)
  ClassName: LocalPredictor.load_model_config.<locals>.create_predictor_check  FunctionName: create_predictor_check

**Comment by w5688414** [comment]
装的是tensort的paddlepaddle版本吗？请问环境是啥？

**Comment by lin1490188** [comment]
> 装的是tensort的paddlepaddle版本吗？请问环境是啥？

装的是paddle的tensort版本：paddlepaddle_gpu-2.3.2.post101-cp36-cp36m-linux_x86_64.whl
tensort版本：TensorRT-6.0.1.5.CentOS-7.6.x86_64-gnu.cuda-10.1.cudnn7.6.tar.gz
