### ISSUE TITLE
Ernie-Layout: Fine tuning with SROIE and CORD daatsets

### ISSUE THREAD

**Issue by chinnaGuggilla** [PaddlePaddle/PaddleNLP#4528]
### Feature request

Could you please add fine tuning scripts for SROIE and CORD datasets. We could see only for FUNSD.
Thanks.

### Motivation

Could you please add fine tuning scripts for SROIE and CORD datasets. We could see only for FUNSD.

### Your contribution

Could you please add fine tuning scripts for SROIE and CORD datasets. We could see only for FUNSD.

**Comment by linjieccc** [comment]
@chinnaGuggilla Hi, 

SROIE and CORD are similar to FUNSD, you can convert the original dataset to our data format and follow the process of [FUNSD Train](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout#41-key-information-extraction) directly.
