### ISSUE TITLE
[Question]: Why loading a finetuned model on ernie layout gives different results every time?

### ISSUE THREAD

**Issue by sujit420** [PaddlePaddle/PaddleNLP#4529]
### 请提出你的问题

I am doing below:

MODEL_CHKPOINT = "ernie-layoutx-base-uncased/models/checkpoint-xxxx"
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHKPOINT)
model = AutoModelForQuestionAnswering.from_pretrained(MODEL_CHKPOINT)
model.config['has_visual_segment_embedding'] = False

tmp_data = eval_dataset[0]

input_ids = paddle.to_tensor([tmp_data['input_ids']], dtype="int64")
attention_mask = paddle.to_tensor([tmp_data['attention_mask']], dtype="int64")
token_type_ids = paddle.to_tensor([tmp_data['token_type_ids']], dtype="int64")
position_ids = paddle.to_tensor([tmp_data['position_ids']], dtype="int64")
bbox = paddle.to_tensor([tmp_data['bbox']], dtype="int64")
image = paddle.to_tensor([tmp_data['image']], dtype="int64")
print(input_ids.shape, attention_mask.shape, token_type_ids.shape, position_ids.shape, bbox.shape, image.shape) 
#[1, 512] [1, 512] [1, 512] [1, 512] [1, 512, 4] [1, 3, 224, 224]

#predict
output = model(input_ids=input_ids, attention_mask=attention_mask,token_type_ids=token_type_ids, position_ids=position_ids, bbox=bbox, image=image)
###

import numpy as np
start = np.argmax(output[0])
end = np.argmax(output[1])
print(start, end, output[0][0][start], output[1][0][end])

The above code gives different results every time I execute #predict block.
**run1:**
(215,
 216,
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [3.67313457]),
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [3.77244473]))
     
**run2:**
(0,
 0,
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [2.51358175]),
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [2.90562463]))
        
**run3:**
(215,
 216,
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [4.49431562]),
 Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
        [4.77424192]))
@stefanqxb did you get your expected result? I saw you were also facing a similar issue.
@linjieccc @wawltor please help.

**Comment by lugimzzz** [comment]
you should add the following line before inference.
`model.eval()`

**Comment by sujit420** [comment]
> you should add the following line before inference. `model.eval()`

Thanks!! it worked.
