### ISSUE TITLE
[Question]: How critical is the "segment_bbox" to the performance of ERNIE-Layout? Is there an expected F1 difference between bbox and segment_bbox?

### ISSUE THREAD

**Issue by waynemystir** [PaddlePaddle/PaddleNLP#4532]

**Comment by linjieccc** [comment]
@waynemystir Hi, in our experiments, using segment boxes increase the F1 on NER task, but has no obvious improvement on MRC and Classification tasks.

You can try to use word boxes instead by set `use_segement_box` to False in model fine-tuning.
