### ISSUE TITLE
[Question]: For ERNIE-Layout, how should we get the segment bboxes? For inference purposes, should we do some form of image segmentation or clustering during preprocessing?

### ISSUE THREAD

**Issue by waynemystir** [PaddlePaddle/PaddleNLP#4533]

**Comment by linjieccc** [comment]
@waynemystir Hi, Thanks for your interest on ERNIE-Layout! 

Segment boxes can be obtained through OCR Inference, you can refer to [the example of PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/quickstart_en.md#22-use-by-code)
