### ISSUE TITLE
自启动服务

### ISSUE THREAD

**Issue by wanggei** [PaddlePaddle/PaddleNLP#4563]
### 问题描述

进行文本分类预测能不能把predict.py做成一个服务，进行预测时直接给一段文本就能进行预测，而不是每次有新的文本要进行预测就得运行一遍predict.py

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/simple_serving

提供SimpleServing服务化的方式，可以看看

**Comment by wanggei** [comment]
@wawltor 这个启动完会自动加载我训练好的模型吗，那如果我下次用新的模型去替换掉旧的模型，这个服务会自动加载新的模型进行预测吗

**Comment by wanggei** [comment]
还有就是我启动server出现这样一个错误，麻烦看一下，谢谢。
![image](https://user-images.githubusercontent.com/61741330/215409739-4a436b17-21f3-4355-9318-11eb1dd98fc2.png)

**Comment by wawltor** [comment]
> @wawltor 这个启动完会自动加载我训练好的模型吗，那如果我下次用新的模型去替换掉旧的模型，这个服务会自动加载新的模型进行预测吗

启动的时候 可以加上 --reload 来打开自动加载模型的选项

**Comment by wawltor** [comment]
> 还有就是我启动server出现这样一个错误，麻烦看一下，谢谢。 ![image](https://user-images.githubusercontent.com/61741330/215409739-4a436b17-21f3-4355-9318-11eb1dd98fc2.png)

是否进入了正确了目录了，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/simple_serving  ，看看启动命令的目录下是否有server.py文件

**Comment by wanggei** [comment]
![image](https://user-images.githubusercontent.com/61741330/215412594-48d94896-4549-4f59-98c6-86dd9a2dd03d.png)
这个路径是要配置成我模型存放的路径吗

**Comment by wawltor** [comment]
> ![image](https://user-images.githubusercontent.com/61741330/215412594-48d94896-4549-4f59-98c6-86dd9a2dd03d.png) 这个路径是要配置成我模型存放的路径吗

是的，需要是静态图模型导出的路径

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有疑问可以再次打开该issue。
