### ISSUE TITLE
[Question]:PaddleNLP Pipelines问答系统继续使用有监督数据训练

### ISSUE THREAD

**Issue by Graduo** [PaddlePaddle/PaddleNLP#4569]
您好，请问PaddleNLP Pipelines问答系统可以继续向有监督问答一样对检索与排序模型进行训练嘛

**Comment by w5688414** [comment]
> 您好，请问PaddleNLP Pipelines问答系统可以继续向有监督问答一样对检索与排序模型进行训练嘛

请问是FAQ智能问答还是阅读理解智能问答呢？FAQ智能问答的训练可以参考Neural Search的inbatch-negatives，如果是阅读理解的问答，请参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_reading_comprehension/DuReader-robust

**Comment by Graduo** [comment]
> > 您好，请问PaddleNLP Pipelines问答系统可以继续向有监督问答一样对检索与排序模型进行训练嘛
> 
> 请问是FAQ智能问答还是阅读理解智能问答呢？FAQ智能问答的训练可以参考Neural Search的inbatch-negatives，如果是阅读理解的问答，请参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_reading_comprehension/DuReader-robust

您好，这边想问的是FAQ问答，目前注意到FAQ问答可以通过流水线PiPeline（https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa） 实现，也可以通过 （https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/supervised_qa） 实现，前者好处在于有检索以及排序模块可以使效果更准确同时包含前端页面模型部署展示更加方便、但是不直接附带模型优化模块，后者可以用SimCSE使用有监督以及对模型进行优化，请问后面有计划将两者优势进行集成嘛，比如在pipline里加入模型优化训练模块

**Comment by w5688414** [comment]
目前applications训练的模型都可以用pipelines加载，pipelines剥离了训练的任务，这部分由applications承接，您训练的模型，可以直接用pipelines加载

> > > 您好，请问PaddleNLP Pipelines问答系统可以继续向有监督问答一样对检索与排序模型进行训练嘛
> > 
> > 
> > 请问是FAQ智能问答还是阅读理解智能问答呢？FAQ智能问答的训练可以参考Neural Search的inbatch-negatives，如果是阅读理解的问答，请参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_reading_comprehension/DuReader-robust
> 
> 您好，这边想问的是FAQ问答，目前注意到FAQ问答可以通过流水线PiPeline（[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa）](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa%EF%BC%89) 实现，也可以通过 （[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/supervised_qa）](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/supervised_qa%EF%BC%89) 实现，前者好处在于有检索以及排序模块可以使效果更准确同时包含前端页面模型部署展示更加方便、但是不直接附带模型优化模块，后者可以用SimCSE使用有监督以及对模型进行优化，请问后面有计划将两者优势进行集成嘛，比如在pipline里加入模型优化训练模块

**Comment by Graduo** [comment]
> 目前applications训练的模型都可以用pipelines加载，pipelines剥离了训练的任务，这部分由applications承接，您训练的模型，可以直接用pipelines加载
> 
> > > > 您好，请问PaddleNLP Pipelines问答系统可以继续向有监督问答一样对检索与排序模型进行训练嘛
> > > 
> > > 
> > > 请问是FAQ智能问答还是阅读理解智能问答呢？FAQ智能问答的训练可以参考Neural Search的inbatch-negatives，如果是阅读理解的问答，请参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_reading_comprehension/DuReader-robust
> > 
> > 
> > 您好，这边想问的是FAQ问答，目前注意到FAQ问答可以通过流水线PiPeline（[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa）](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa%EF%BC%89) 实现，也可以通过 （[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/supervised_qa）](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/question_answering/supervised_qa%EF%BC%89) 实现，前者好处在于有检索以及排序模块可以使效果更准确同时包含前端页面模型部署展示更加方便、但是不直接附带模型优化模块，后者可以用SimCSE使用有监督以及对模型进行优化，请问后面有计划将两者优势进行集成嘛，比如在pipline里加入模型优化训练模块

好的了解，感谢您这边的工作与耐心回复

**Comment by gg22mm** [comment]
> ons训练的模型都可以用pipelines加载，pipelines剥离了训练的任务，这部分由applications承接，您训练的模型，可以直接用pipelines加载

这个在applications中训练不能在pipelines中用的吧，我上次试了，报错。...   
![图片](https://user-images.githubusercontent.com/6648329/233301264-7b0f2a94-3ed0-49cc-ab44-dbb802ea9f70.png)
你们加载试试，直接会报错的
