### ISSUE TITLE
analysis中的数据优化是不是不能用在小样本层次分类中[Question]: 

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleNLP#4591]
### 请提出你的问题

analysis中的数据优化是不是不能用在小样本层次分类中, 比如analysis中的evaluate的各个类别的指标评估?在小样本提示学习中, 是不是不能使用, 或是底层的模型不一样, 小样本层次分类其实是掩码预测即生成预测, 和多分类模型直接预测本质上是不一样的, 这样理解是否合理, 希望指点一二, 谢谢

**Comment by lugimzzz** [comment]
微调的evaluate.py各个评估指标也适用于评估小样本的层次分类，不过目前尚未提供相应的脚本，需要自己写。其他可解释性相关的方法暂无在小样本上试验
