### ISSUE TITLE
[Question]: 运行pipelines智能问答时，较长段落末尾的文本内容无法搜索

### ISSUE THREAD

**Issue by ACbccc** [PaddlePaddle/PaddleNLP#4594]
### 请提出你的问题

一段文字大概长度在500字左右时，末尾的文字内容会丢失，是预定义了段落长度吗？请问这个参数在哪里修改

**Comment by w5688414** [comment]
目前语义检索和问答还不支持长文本，query和passage的总长度不要超过512，越长反而效果不好，可以进行分段后进行检索和问答哈。
