### ISSUE TITLE
window系统运行出现普遍性的报错The current variable type is (int64_t), but the previous variable type is (int). 

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#460]
InvalidArgumentError: The DataType of greater_than Op's duplicable Variable Y must be consistent. The current variable type is (int64_t), but the previous variable type is (int). (at C:\home\workspace\Paddle_release\paddle\fluid\framework\operator.cc:1574)
  [operator < greater_than > error] 运行PaddleNLP\examples\information_extraction\waybill_ie里面的run_bigru_crf.py出现报错

应该是windows系统运行的原因，这些代码应该要linux和window都验证过就好了,能省开发者很多时间，你们维护起来估计也会轻松很多

**Comment by AI-Mart** [comment]
希望解决下

**Comment by joey12300** [comment]
@AI-Mart 您好，感谢您反馈的bug，目前修复的PR已合入，欢迎继续使用 :)
