### ISSUE TITLE
[Question]: UIE中预训练模型代替

### ISSUE THREAD

**Issue by geasyheart** [PaddlePaddle/PaddleNLP#4602]
### 请提出你的问题

Hi，各位作者大大们好！我有一个问题，就是UIE的预训练模型是否可以用其他预训练模型同等效果替代，比如Roberta、T5等等。

我参考了[3368](https://github.com/PaddlePaddle/PaddleNLP/issues/3368)解答，知道uie预训练模型训练时就让模型适配固定prompt，那是否有其他预训练模型也能在同样prompt模板+微调的情况下达到uie预训练模型的效果。

非常感谢！

**Comment by linjieccc** [comment]
@geasyheart 你好，

模型底座没有限制，其他的TransformerEncoder在大规模信息抽取数据上进行过二阶段预训练也可以具备通用信息抽取能力

**Comment by geasyheart** [comment]
感谢回复，关键是没有大规模信息抽取数据拿来训练😂😂，也不清楚你们是[在多大数据集上训练的以及对应的schema有哪些](https://github.com/PaddlePaddle/PaddleNLP/issues/2891)，看样子要是想体验，只能转战paddle了😂。
