### ISSUE TITLE
[Question]: simbert_base_chinese相似度运行效率问题

### ISSUE THREAD

**Issue by Alexander-jazz** [PaddlePaddle/PaddleNLP#4606]
### 请提出你的问题

我的环境是14核CPU 160G内存 参数方面，batch_size=512 计算两个不是很长的短文本（不超过30个字符），需要5到6秒。本人新手，不是很了解需要调整taskflow的参数，还是需要怎么操作。

**Comment by w5688414** [comment]
batch_size 设置那么大，你比较的是两个短文本吗？batch_size表示的是样本的数量，如果只是两个文本的相似度，设置成1就行。

**Comment by Alexander-jazz** [comment]
>好的，我试试将batch_size改为1，谢谢

**Comment by Alexander-jazz** [comment]
您好，我将batch_size改为1后，速度上没有太大的提升。因为我在做一个计算两两短文本相似度的工作，如果每条数据处理需要5秒，那两两计算一次，就会耗时很长。查了一些资料，说是要用多线程进行这个任务。您是否有好的方案和建议。

**Comment by Alexander-jazz** [comment]
> batch_size 设置那么大，你比较的是两个短文本吗？batch_size表示的是样本的数量，如果只是两个文本的相似度，设置成1就行。
您好，我将batch_size改为1后，速度上没有太大的提升。因为我在做一个计算两两短文本相似度的工作，如果每条数据处理需要5秒，那两两计算一次，就会耗时很长。查了一些资料，说是要用多线程进行这个任务。您是否有好的方案和建议。

**Comment by w5688414** [comment]
> > batch_size 设置那么大，你比较的是两个短文本吗？batch_size表示的是样本的数量，如果只是两个文本的相似度，设置成1就行。
> > 您好，我将batch_size改为1后，速度上没有太大的提升。因为我在做一个计算两两短文本相似度的工作，如果每条数据处理需要5秒，那两两计算一次，就会耗时很长。查了一些资料，说是要用多线程进行这个任务。您是否有好的方案和建议。

可以把max_seq_len设小，默认384，有点大，比如设置成64或者32这样。

https://github.com/PaddlePaddle/PaddleNLP/blob/19f76239215bf36f491149cbde00ff20f91803c7/paddlenlp/taskflow/text_similarity.py#L126

**Comment by Alexander-jazz** [comment]
> > > batch_size 设置那么大，你比较的是两个短文本吗？batch_size表示的是样本的数量，如果只是两个文本的相似度，设置成1就行。
> > > 您好，我将batch_size改为1后，速度上没有太大的提升。因为我在做一个计算两两短文本相似度的工作，如果每条数据处理需要5秒，那两两计算一次，就会耗时很长。查了一些资料，说是要用多线程进行这个任务。您是否有好的方案和建议。
> 
> 可以把max_seq_len设小，默认384，有点大，比如设置成64或者32这样。
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/19f76239215bf36f491149cbde00ff20f91803c7/paddlenlp/taskflow/text_similarity.py#L126

感谢您的意见，运行大概减少一秒左右。想请教一下您，如果用Taskflow()方法获取相似度，是调用的模型的API，还是在本地跑这个模型呢，如果是在本地跑，我打算尝试用一下多线程的方法，看能否提高效率。

**Comment by w5688414** [comment]
> > > > batch_size 设置那么大，你比较的是两个短文本吗？batch_size表示的是样本的数量，如果只是两个文本的相似度，设置成1就行。
> > > > 您好，我将batch_size改为1后，速度上没有太大的提升。因为我在做一个计算两两短文本相似度的工作，如果每条数据处理需要5秒，那两两计算一次，就会耗时很长。查了一些资料，说是要用多线程进行这个任务。您是否有好的方案和建议。
> > 
> > 
> > 可以把max_seq_len设小，默认384，有点大，比如设置成64或者32这样。
> > https://github.com/PaddlePaddle/PaddleNLP/blob/19f76239215bf36f491149cbde00ff20f91803c7/paddlenlp/taskflow/text_similarity.py#L126
> 
> 感谢您的意见，运行大概减少一秒左右。想请教一下您，如果用Taskflow()方法获取相似度，是调用的模型的API，还是在本地跑这个模型呢，如果是在本地跑，我打算尝试用一下多线程的方法，看能否提高效率。

Taskflow已经帮您做了优化了，如果想进一步优化，可以看看能不能用C++的方式
