### ISSUE TITLE
[Question]: 关于uie-senta-base模型定制训练的问题

### ISSUE THREAD

**Issue by foxblade77** [PaddlePaddle/PaddleNLP#4611]
### 请提出你的问题

我这边有个疑问想找各位大神确认一下：就是目前我这边需要使用标注数据对uie-senta-base模型进行定制化训练，是不是只能使用PaddleNLP情感应用文档中提及的unified_sentiment_extraction目录下的脚本进行训练？因为我发现如果使用model_zoo/uie下面的训练脚本就无法完成训练，会找不到model，强制指定model绝对路径完成训练在实际使用时会出现各种奇怪问题，比如预测后的json文件过于庞大等情况。

**Comment by 1649759610** [comment]
建议使用unified_sentiment_extraction下的训练脚本完成训练，unified_sentiment_extraction已对uie-senta系列模型进行了完备适配。同时该脚本默认即以uie-senta系列模型为底座进行情感分析。

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction

微调脚本在这个目录下

**Comment by wfs420100** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction
> 
> 微调脚本在这个目录下

您好，请问该微调流程是否兼容使用英文uie进行英文文本定制化情感分析？

**Comment by wawltor** [comment]
> > https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction
> > 微调脚本在这个目录下
> 
> 您好，请问该微调流程是否兼容使用英文uie进行英文文本定制化情感分析？

目前这个目录下的内容还不能进行英文的senta模型的定制化，如果想进行UIE的英文情感分析的定制化，可以到 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by foxblade77** [comment]
非常感谢大家的答复~
