### ISSUE TITLE
[Question]: UIE评论观点抽取，官方案例结果为空[{}]

### ISSUE THREAD

**Issue by wfs420100** [PaddlePaddle/PaddleNLP#4615]
### 请提出你的问题

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/64070362/215998852-c8f72ccc-110a-4d77-b809-ade79107e686.png">
<img width="945" alt="image" src="https://user-images.githubusercontent.com/64070362/215998959-343c4ef0-0ab2-4f51-9b2c-5173a2162234.png">

**Comment by linjieccc** [comment]
@wfs420100 你好，感谢反馈，我们会对模型权重进行更新

**Comment by wfs420100** [comment]
您好，请问一下uie的评论观点抽取中，情感分类是只有正负两个类别吗，是否具有[sentiment_analysis](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis)中的“未提及”标签

问题：[sentiment_analysis](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis)是否有计划推出英文版

**Comment by linjieccc** [comment]
通用模型uie-base零样本只有正向、负向两类标签，如果只针对情感分析任务推荐使用uie-senta，详见[情感分析应用](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis)。

另外uie-senta暂时没有计划出英文版本

**Comment by EleniWang** [comment]
请问有解决吗，同样的问题
