### ISSUE TITLE
[Docs]: uie的 simpleservering服务，server端启动之后，通过java往server端端口发送 预测的文本数据，就可以实现预测了吗？

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/PaddleNLP#4628]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 详细描述

```Markdown
[Docs]: uie的 simpleservering服务，server端启动之后，通过java往server端端口发送 预测的文本数据，就可以实现预测了吗？
```

**Comment by wawltor** [comment]
我理解是可以的，SimpleServing走的是HTTP协议，Java走这个协议发送请求即可

**Comment by lzh1998-jansen** [comment]
> 我理解是可以的，SimpleServing走的是HTTP协议，Java走这个协议发送请求即可

from paddlenlp import SimpleServer, Taskflow

# The schema changed to your defined schema
schema = ["出发地", "目的地", "费用", "时间"]
# The task path changed to your best model path
uie = Taskflow("information_extraction", schema=schema, task_path="../../checkpoint/model_best/")
# If you want to define the finetuned uie service
app = SimpleServer()
app.register_taskflow("taskflow/uie", uie)

这是uie simpleserver server端的代码，有接口字段说明吗，client端怎么发送数据到server

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/serving/simple_serving/client.py  参考这个

**Comment by lzh1998-jansen** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/serving/simple_serving/client.py 参考这个

![image](https://user-images.githubusercontent.com/61367424/216502760-45186549-6337-4d36-a834-9d3d637aec4e.png)
您好，启动server端报错了，paddlenlp版本 为2.4.9符合simpleserver的要求

**Comment by lzh1998-jansen** [comment]
跑通了，感谢paddlenlp

**Comment by wawltor** [comment]
好的，我们将暂时关闭issue，如有问题可以再次打开。

**Comment by lzh1998-jansen** [comment]
请问，有没有simpleserver更多的文档介绍，比如在server.py，我如何实现提供多个接口，比如一个预测实体抽取，一个预测关系抽取
