### ISSUE TITLE
[Question]: UTC微调问题

### ISSUE THREAD

**Issue by DT-lyx** [PaddlePaddle/PaddleNLP#4631]
### 请提出你的问题

UTC分类，taskflow使用微调过的模型，预测结果相比0shot不会变化，类似于问题https://github.com/PaddlePaddle/PaddleNLP/issues/4481#issue-1533249811

**Comment by LemonNoel** [comment]
该问题已在develop版本修复，辛苦运行以下命令安装develop版本，同时删除checkpoint下生成的static目录
```
pip install paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by imempty** [comment]
> 该问题已在develop版本修复，辛苦运行以下命令安装develop版本，同时删除checkpoint下生成的static目录
> 
> ```
> pip install paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
> ```

通过升级paddlenlp版本就能解决此问题？和taskflow加载代码无关？  @LemonNoel 
问题解决了么？ @DT-lyx
