### ISSUE TITLE
[Question]: 小样本层次分类中: 遇到维度不一致, 报错

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleNLP#4632]
### 请提出你的问题

在使用小样本层次分类中, 模型导出后, 使用infer.py文件进行推理的时候, 报:
```python
Traceback (most recent call last):
  File "infer.py", line 227, in <module>
    predictor.predict(text_list)
  File "infer.py", line 152, in predict
    infer_result = self.infer_batch(encoded_inputs)
  File "infer.py", line 188, in infer_batch
    infer_data[i] = np.concatenate(infer_data[i], axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 31 and the array at index 1 has size 29
```
 这个问题, 请解答一下, 谢谢

**Comment by chinesejunzai12** [comment]
此处验证在一个batch内是可以正常预测的, 当预测数据的量大于一个batch的时候就会发生以上的错误形状不一致的错误, 是否可以解答一下, 具体的问题方案, 谢谢

**Comment by LemonNoel** [comment]
请问 paddle 和 paddlenlp 的版本分别是多少呢？

**Comment by chinesejunzai12** [comment]
@各个版本:
paddlenlp                         2.4.9
paddlepaddle                      2.4.1
paddlepaddle-gpu                  2.4.1.post112
paddle2onnx                       1.0.5
以上错误是在动态图转化为静态图之后模型推理阶段出现的问题.

**Comment by chinesejunzai12** [comment]
这个是调试过程中发现的问题, 更加底层的代码看不到了
<img width="751" alt="image" src="https://user-images.githubusercontent.com/103180175/216541698-c6debbf2-56ed-455c-b75b-963e88b5ffb7.png">
这个部分照成了np.concatenate合并的时候出现错误, 涉及到的文件是infer.py文件188行:infer_data[i] = np.concatenate(infer_data[i], axis=0)这行代码

**Comment by LemonNoel** [comment]
辛苦升级到 develop 版本看看是否还有这个问题，命令如下
```
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by chinesejunzai12** [comment]
> pip install paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
你好, 问题还是存在, 没有解决

**Comment by LemonNoel** [comment]
升级之后模型有重新export吗？
