### ISSUE TITLE
[Question]: 关于启动simple_serving出现错误

### ISSUE THREAD

**Issue by wanggei** [PaddlePaddle/PaddleNLP#4643]
### 请提出你的问题

启动sipmle_serving出现找不到server module ,

工程已经定位到deploy下进行运行

![image](https://user-images.githubusercontent.com/61741330/216743898-443ec427-e2db-4e38-8817-d4a1e1caa118.png)

**Comment by wanggei** [comment]
paddlenlp 版本2.5.0

**Comment by wawltor** [comment]
要进入相应的目录下，找到server.py文件，例如 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/deploy/simple_serving

**Comment by wanggei** [comment]
哦哦，好的好的，谢谢

**Comment by wawltor** [comment]
您好，我们将暂时关闭该issue，如有问题可以再次打开该issue。
