### ISSUE TITLE
[Docs]: 请问，有没有simpleserver更多的文档介绍，比如在server.py，我如何实现提供多个接口，比如一个预测实体抽取，一个预测关系抽取

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/PaddleNLP#4649]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 目前最新的
```

### 详细描述

```Markdown
请问，有没有simpleserver更多的文档介绍，比如在server.py，我如何实现提供多个接口，比如一个预测实体抽取，一个预测关系抽取
```

**Comment by lzh1998-jansen** [comment]
![image](https://user-images.githubusercontent.com/61367424/216884479-450e1f66-5099-40dc-ab63-47deedbe093d.png)
我猜可以用类似这样的方式，但结果是，找不到第二个接口

**Comment by wawltor** [comment]
> ![image](https://user-images.githubusercontent.com/61367424/216884479-450e1f66-5099-40dc-ab63-47deedbe093d.png) 我猜可以用类似这样的方式，但结果是，找不到第二个接口

一次只能启动一个app，因为文档启动示例 `server:app` 启动是 `app` 这个server，如果需要启动 `app1` 需要启动server:app1

**Comment by lzh1998-jansen** [comment]
> > ![image](https://user-images.githubusercontent.com/61367424/216884479-450e1f66-5099-40dc-ab63-47deedbe093d.png) 我猜可以用类似这样的方式，但结果是，找不到第二个接口
> 
> 一次只能启动一个app，因为文档启动示例 `server:app` 启动是 `app` 这个server，如果需要启动 `app1` 需要启动server:app1

以后会实现吗?

**Comment by wawltor** [comment]
> > > ![image](https://user-images.githubusercontent.com/61367424/216884479-450e1f66-5099-40dc-ab63-47deedbe093d.png) 我猜可以用类似这样的方式，但结果是，找不到第二个接口
> > 
> > 
> > 一次只能启动一个app，因为文档启动示例 `server:app` 启动是 `app` 这个server，如果需要启动 `app1` 需要启动server:app1
> 
> 以后会实现吗?

这个预计这个季度没有排期，因为这个SimpleServer是基于FastAPI来做的，FastAPI不支持该项工作

**Comment by wawltor** [comment]
您好，我们先关闭该issue，如有问题可以及时再次打开issue，谢谢！
