### ISSUE TITLE
unimo-text如何在垂直领域上预训练

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4650]
### 请提出你的问题

unimo-text如何在垂直领域上预训练

**Comment by westfish** [comment]
unimo-text是一类比较通用的文本生成模型，在垂直领域上预训练可以参考我们已有一些例子，如https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/question_generation/unimo-text 和 
 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/unimo-text
