### ISSUE TITLE
[Bug]: uie-senta-base模型处理酒店场景的部分测试数据时返回结果为空[{}] 

### ISSUE THREAD

**Issue by ccc008** [PaddlePaddle/PaddleNLP#4657]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1.post112
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
test_hotel.txt 内的部分测试文本在uie-senta-base模型测试，发现返回结果为空。如下：

房间挺大的，还算干净，但服务态度有点冷淡，
酒店味道大，隔音差
酒店设施略显陈旧，灯光还需要再亮点，有些暗
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow
schema = ['情感倾向[正向，负向]']
senta = Taskflow("sentiment_analysis", model="uie-senta-base", schema=schema)
print(senta('酒店设施略显陈旧，灯光还需要再亮点，有些暗'))

**Comment by wawltor** [comment]
这个是因为Taskflow直接对这句话进行预测，结果为空，是因为零样本的模型的泛化和精度是有限的，需要经过微调效果才能出来，你可以的尝试教程微调的流程进行微调

**Comment by wawltor** [comment]
您好，我们将关闭该issue，如有问题可以再次打开该issue。
