### ISSUE TITLE
[Question]: 篇章级事件相关

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#4664]
### 请提出你的问题

1.篇章级事件会出现多个同类的事件，例如下文出现多次销售额事件。此时，我的触发词“销售额”需要每次事件在数据里指定不同id和位置么，还是说共用？
```
9月22日消息，据国外媒体报道，数据显示，DRAM市场销售额6月份急剧下滑36%，7月份又下降了21%。市场销售而急剧下跌，以至于7月的DRAM市场规模约为5月的一半！
对通胀飙升和经济衰退的担忧削弱了消费者在新智能手机、电脑、电视和其他电子产品上的支出。反过来，系统制造商也缩减了新的DRAM 订单，理由是需要消耗他们积累的现有库存。
此前，研究机构公布的数据显示，今年第一季度，全球DRAM的销售额为242.5亿美元，自2021年第三季度创下262.4亿美元的新高之后连续第二个季度下滑。今年第二季度，全球DRAM的销售额为255.9亿美元，环比增长5.53%。
```
2.在同一句里发生两个同类的事件，uie能否区分开？
3.在同一事件下分布在不同句里的论元uie能否合并？如果在长文章里过长文字会截断，在截断位置两边的同一事件下论元是否可以合并？
4.不同事件都会出现“公司实体”，为避免实体分配错误，例如抽取建厂、销售额事件时，实体label都给定为“公司”，关系label给定为“建厂_公司”,"销售额_公司"是否有必要？如有必要，schema的prompt是{"建厂触发词",["公司"]}还是{"建厂触发词",["建厂_公司"]}?

**Comment by linjieccc** [comment]
1、2，UIE目前还不能区分触发词字面相同的情况，有两种方法避免，一个是按照句子级别标注、训练和预测，把这种冲突情况降低到最小；二是不要用容易字面相同的触发词，比如可以把季度时间作为第一阶段的抽取目标。
3，目前还不支持合并，对长文本的处理是切分成sub_text分别预测，因此句子级关系、事件抽取可能更合适些
4，直接标注公司即可，第一阶段的触发词即可区分不同类型的事件进行

**Comment by BEILOP** [comment]
也就是说，事件抽取时，schema就变成了{'专利时间': ['公司', '触发词', '专利'],'建厂时间': ['公司', '触发词', '产品', '地点', '国家']}么？然后数据标注时，relations是可以是从时间链接到其他实体包括触发词么？
这种情况下时间就成了必要元素，触发词成了非必要元素。

**Comment by Huangswust182** [comment]
@linjieccc 请问，怎么进行按照句子级别标注呀？
