### ISSUE TITLE
文本分类案例，是否支持 多层级单标签场景？

### ISSUE THREAD

**Issue by zbmain** [PaddlePaddle/PaddleNLP#4670]
### 问题描述

您好，此问题为功能咨询。
请问按截图文档描述，表示[层次分类场景]其实是个多层级多标签分类任务？（不同层级 有且有一个或多个标签）
若想修改为多层级单标签（不同层级有且只有一个标签）的话，是否支持？
![image](https://user-images.githubusercontent.com/52638096/217124114-7cce1391-c16e-408b-bb1a-52b508032a1f.png)

**Comment by lugimzzz** [comment]
也是支持，这种情况你即可以视为单标签，用多分类方案，也可以选择层次分类来做

**Comment by zbmain** [comment]
您好，我的场景是：多层单标签。
我想使用层次分类方案解决。但在使用PaddleNLP案例[层次分类]中，发现它的输出是 多层多标签。如果不修改源码的话，可能我需要训练多个[多分类方案]模型来实现多层单标签 任务。
![image](https://user-images.githubusercontent.com/52638096/217139301-d1a239e6-76a6-4384-95ba-770c337a10ff.png)

请教一下，如何设置[层次分类方案]输出为 多层单标签？

**Comment by lugimzzz** [comment]
这种情况建议你直接使用多分类来解决，把多层标签视为单个标签"一级标签##二级标签##三级标签"
