### ISSUE TITLE
[Question]: 在使用 基于检索的文本分类方法(applications/text_classification/multi_class/retrieval_based)进行训练时遇到一些问题

### ISSUE THREAD

**Issue by Isfate** [PaddlePaddle/PaddleNLP#4671]
### 请提出你的问题

这是我使用的训练参数
root_path=inbatch
data_path=../data/bingF
python -u -m paddle.distributed.launch --gpus "5" \
    train.py \
    --device gpu \
    --save_dir ./checkpoints/${root_path} \
    --batch_size 16 \
    --learning_rate 5E-5 \
    --epochs 100 \
    --output_emb_size 0 \
    --save_steps 50 \
    --max_seq_length 512 \
    --warmup_proportion 0.0 \
    --margin 0.2 \
    --recall_result_dir "recall_result_dir" \
    --recall_result_file "recall_result.txt" \
    --train_set_file ${data_path}/train.txt \
    --corpus_file ${data_path}/label.txt   \
    --similar_text_pair_file ${data_path}/dev.txt \
    --evaluate True
我使用的环境如下:
python 3.8.15
paddlenlp 2.5.0
cuda 10.2
paddlepaddle_gpu 2.4.1

报错信息如下:
global step 1990, epoch: 1, batch: 1990, loss: 5.08325, speed: 1.06 step/s
global step 2000, epoch: 1, batch: 2000, loss: 5.10051, speed: 1.09 step/s
global step 2010, epoch: 1, batch: 2010, loss: 5.68769, speed: 1.05 step/s
global step 2020, epoch: 1, batch: 2020, loss: 4.25817, speed: 1.11 step/s
evaluating
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    do_train()
  File "train.py", line 274, in do_train
    recall_5 = evaluate(model, corpus_data_loader, query_data_loader, recall_result_file, text_list, id2corpus)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/zhb/sunxiaorui/software/anaconda3/envs/cjdbi3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "train.py", line 132, in evaluate
    recalled_idx, cosine_sims = final_index.knn_query(batch_query_embedding.numpy(), args.recall_num)
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small

在第一个epoch训练完毕后, 进行evaluating时报错

**Comment by Isfate** [comment]
我在进行调试时, 将args.recall_num 更改为我的标签数后, 这个错误就消失了
但是这个参数的含义在文档中的表述为 "对 1 个文本召回的相似文本数量"

**Comment by Isfate** [comment]
还是没有定位到这个错误的出现原因

**Comment by w5688414** [comment]
> 我在进行调试时, 将args.recall_num 更改为我的标签数后, 这个错误就消失了 但是这个参数的含义在文档中的表述为 "对 1 个文本召回的相似文本数量"

评估的方式是：利用文本召回标签，请问您的标签数量是多少？另外这种方法比较特殊，会利用标签的文本信息，如果标签中融入一些描述等信息，效果会更好。

**Comment by Isfate** [comment]
我的标签数是43, args.recall_num在43以下时, 这行代码就可以正常运行

**Comment by w5688414** [comment]
> 我的标签数是43, args.recall_num在43以下时, 这行代码就可以正常运行

您的标签数量比较少，可以不设置那么大，设置成20或者10比较合适，然后batch_size设置小一点。
