### ISSUE TITLE
[Question]: 使用UIE-X训练模型后发现Answer为空时会去找别的值代替，如何让他显示为空

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#4672]
### 请提出你的问题

教程上是有值的情况是正常的，出现为空的时候会出现下图的问题，找下一行的Answer作为自己的值，如何才能避免这种情况，为空Answer就显示空而不去找下一行的
![1675735302193](https://user-images.githubusercontent.com/44227598/217128889-f08d98be-e466-4e83-81a6-0b5eb4da736e.png)

**Comment by linjieccc** [comment]
@1061302569 Hi，目前的标注数据规模是多少？可以尝试在数据转换阶段适当增大negative_ratio来生成更多的负样本

**Comment by 1061302569** [comment]
> @1061302569 Hi，目前的标注数据规模是多少？可以尝试在数据转换阶段适当增大negative_ratio来生成更多的负样本

谢谢你，目前数据规模只有60，增大negative_ratio会自动生成负样本吗

**Comment by linjieccc** [comment]
会增加负样本即抽取为空的数据的占比，另外方便的话可以贴一下目前的标注例子和schema设置哈

**Comment by 1061302569** [comment]
> 会增加负样本即抽取为空的数据的占比，另外方便的话可以贴一下目前的标注例子和schema设置哈

schema = [
    '发票代码',
    '发票号码',
    '开票日期',
    {
        '货物或应税劳务、服务名称': [
            '数量','单价','税率','税额','金额','规格型号','单位'
        ]
    },
    '名称','开户行及账号','纳税人识别号','地址、电话','价税合计'
]
![1675741389834](https://user-images.githubusercontent.com/44227598/217142995-51206862-dcd5-4d42-9978-551f0b7c6c50.png)
![1675741480733](https://user-images.githubusercontent.com/44227598/217143142-f7244b1b-cd1a-4ca1-b7f0-0a470caa885b.png)

**Comment by linjieccc** [comment]
schema和标注看起来没有问题，增加一下负样本的比例试试呢

**Comment by 1061302569** [comment]
> schema和标注看起来没有问题，增加一下负样本的比例试试呢

好的，谢谢老师
