### ISSUE TITLE
pipelines qa任务调用uie模型报错Segmentation fault

### ISSUE THREAD

**Issue by Karenlyw** [PaddlePaddle/PaddleNLP#4677]
环境配置：
paddlepaddle==2.4.1
paddlenlp==2.4.3
python=3.8

跑pipelines底下的examples/unsupervised-question-answering/unsupervised_question_answering_example.py 
报错日志如下：
 We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/home/gpu_user/.paddlenlp/pipelines/unsupervised_question_answering/uie-base-qa-filter'.
createing synthetic answers...
  0%|                                                      | 0/2 [00:00<?, ?it/s]
Segmentation fault

**Comment by Karenlyw** [comment]
用gpu也是一样的问题

**Comment by hmz0629** [comment]
考虑更新一下cudnn版本，我是用uie-x模型出现Segmentation fault，我粗大10.2，cudnn8，在降级到cudnn7.6.5后解决问题。

**Comment by Karenlyw** [comment]
> 考虑更新一下cudnn版本，我是用uie-x模型出现Segmentation fault，我粗大10.2，cudnn8，在降级到cudnn7.6.5后解决问题。

感谢~，试了下更新cudnn，现在已经跑通了

**Comment by sisrfeng** [comment]
cuda cudnn这些版本 要自己慢慢试验吗
