### ISSUE TITLE
[Question]: 文本纠错中有个参数传递错误

### ISSUE THREAD

**Issue by Alone749-i** [PaddlePaddle/PaddleNLP#4682]
### 请提出你的问题

parser.add_argument("--model_name_or_path", type=str, default="ernie-1.0", choices=["ernie-1.0"], help="Pretraining model name or path")
train.py文件中对预训练模型做了限制

python train.py --batch_size 32 --logging_steps 100 --epochs 10 --learning_rate 5e-5 --model_name_or_path ernie-1.0-base-zh --output_dir ./checkpoints/ --extra_train_ds_dir ./extra_train_ds/ --max_seq_length 192
在文档中训练时，两者有冲突。

**Comment by ZHUI** [comment]
你好，请给一下代码的地址？

**Comment by Alone749-i** [comment]
> 

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc

**Comment by ZHUI** [comment]
好的，这里应该统一修改为 `ernie-1.0-base-zh`

**Comment by ZHUI** [comment]
修复pr： https://github.com/PaddlePaddle/PaddleNLP/pull/4690

**Comment by wawltor** [comment]
您好，我们将关闭该issue，如有疑问您可以再次打开该issue，谢谢！
