### ISSUE TITLE
[Question]: 我想问下TaskFlow的近义词接口部署成服务端后如何传参呢？

### ISSUE THREAD

**Issue by foxblade77** [PaddlePaddle/PaddleNLP#4685]
我想把TaskFlow接口中的text_similarity近义词判断接口部署成一个server服务，目前写好了python脚本也正常部署好了服务端，但是不太清楚如何进行传参，看近义词文档中的描述貌似是传一个二维数组进去：
similarity([["春天适合种什么花？", "春天适合种什么菜？"]])
不过我传如下的json进去总是报错（传一维数组也是报错）：
{
    "data": {
        "text": [[
            "春天适合种什么花？",
            "春天适合种什么菜？"
        ]]
    }      
}
TypeError: Invalid input format.
请问这种接口部署成服务端应该如何传参呢

**Comment by LemonNoel** [comment]
server服务代码什么样呢？理论上部署后的输入数据格式和taskflow是相同的。

**Comment by wawltor** [comment]
1. 安装develop版本的PaddleNLP
2. 使用下面的client代码
   
 ```python
import json

import requests

url = "http://0.0.0.0:8981/taskflow/similarity"
headers = {"Content-Type": "application/json"}
texts = [["春天适合种什么花？", "春天适合种什么菜？"]]
data = {
    "data": {
        "text": texts,
    }
}
r = requests.post(url=url, headers=headers, data=json.dumps(data))
print(r)
datas = json.loads(r.text)
print(datas)
  ```

**Comment by foxblade77** [comment]
> server服务代码什么样呢？理论上部署后的输入数据格式和taskflow是相同的。

就是很简单的一段代码
from paddlenlp import SimpleServer, Taskflow

similarity = Taskflow("text_similarity")

app = SimpleServer()
app.register_taskflow("similarity", similarity)

我又拿别的TaskFlow接口试了下，比如分词接口word_segmentation，同样的代码部署上就可以使用，
传参是：
{
    "data": "近日国家卫健委发布第九版新型冠状病毒肺炎诊疗方案"
}
但这个近义词的就不行呢？

**Comment by foxblade77** [comment]
> 1. 安装develop版本的PaddleNLP
> 2. 使用下面的client代码
> 
> ```python
> import json
> 
> import requests
> 
> url = "http://0.0.0.0:8981/taskflow/similarity"
> headers = {"Content-Type": "application/json"}
> texts = [["春天适合种什么花？", "春天适合种什么菜？"]]
> data = {
>    "data": {
>        "text": texts,
>    }
> }
> r = requests.post(url=url, headers=headers, data=json.dumps(data))
> print(r)
> datas = json.loads(r.text)
> print(datas)
> ```

我试了下，拿不到数据，提示服务器错误

**Comment by wawltor** [comment]
> > 1. 安装develop版本的PaddleNLP
> > 2. 使用下面的client代码
> > 
> > ```python
> > import json
> > 
> > import requests
> > 
> > url = "http://0.0.0.0:8981/taskflow/similarity"
> > headers = {"Content-Type": "application/json"}
> > texts = [["春天适合种什么花？", "春天适合种什么菜？"]]
> > data = {
> >    "data": {
> >        "text": texts,
> >    }
> > }
> > r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > print(r)
> > datas = json.loads(r.text)
> > print(datas)
> > ```
> 
> 我试了下，拿不到数据，提示服务器错误

具体报什么错误了？ 我们本地测试可以的，是否有安装develop版本的paddlenlp？

**Comment by foxblade77** [comment]
> > > 1. 安装develop版本的PaddleNLP
> > > 2. 使用下面的client代码
> > > 
> > > ```python
> > > import json
> > > 
> > > import requests
> > > 
> > > url = "http://0.0.0.0:8981/taskflow/similarity"
> > > headers = {"Content-Type": "application/json"}
> > > texts = [["春天适合种什么花？", "春天适合种什么菜？"]]
> > > data = {
> > >    "data": {
> > >        "text": texts,
> > >    }
> > > }
> > > r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > > print(r)
> > > datas = json.loads(r.text)
> > > print(datas)
> > > ```
> > 
> > 
> > 我试了下，拿不到数据，提示服务器错误
> 
> 具体报什么错误了？ 我们本地测试可以的，是否有安装develop版本的paddlenlp？

我本地安装的是PaddleNLP 2.5.0 develop版本，使用您的脚本后，报错内容为：
ValueError: [TypeError("'numpy.float32' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
如果传参的json调整为：
{
    "data": [["春天适合种什么花？", "春天适合种什么菜？"]]
}
则不会产生报错，但也没有预测结果，返回如下：
{
    "result": {}
}
此时服务器端的信息为：The predictor id: 0 is selected by running the taskflow. 没有报错内容
麻烦您再给看下，谢谢

**Comment by wawltor** [comment]
> > > > 1. 安装develop版本的PaddleNLP
> > > > 2. 使用下面的client代码
> > > > 
> > > > ```python
> > > > import json
> > > > 
> > > > import requests
> > > > 
> > > > url = "http://0.0.0.0:8981/taskflow/similarity"
> > > > headers = {"Content-Type": "application/json"}
> > > > texts = [["春天适合种什么花？", "春天适合种什么菜？"]]
> > > > data = {
> > > >    "data": {
> > > >        "text": texts,
> > > >    }
> > > > }
> > > > r = requests.post(url=url, headers=headers, data=json.dumps(data))
> > > > print(r)
> > > > datas = json.loads(r.text)
> > > > print(datas)
> > > > ```
> > > 
> > > 
> > > 我试了下，拿不到数据，提示服务器错误
> > 
> > 
> > 具体报什么错误了？ 我们本地测试可以的，是否有安装develop版本的paddlenlp？
> 
> 我本地安装的是PaddleNLP 2.5.0 develop版本，使用您的脚本后，报错内容为： ValueError: [TypeError("'numpy.float32' object is not iterable"), TypeError('vars() argument must have **dict** attribute')] 如果传参的json调整为： { "data": [["春天适合种什么花？", "春天适合种什么菜？"]] } 则不会产生报错，但也没有预测结果，返回如下： { "result": {} } 此时服务器端的信息为：The predictor id: 0 is selected by running the taskflow. 没有报错内容 麻烦您再给看下，谢谢

这不是develop版本，你可以确认一下 https://github.com/PaddlePaddle/PaddleNLP/blob/f1c395005b4aca6639aa7826e8ffba4a5638fe38/paddlenlp/taskflow/text_similarity.py#L268  这里的代码是否和你线下安装的代码一致
