### ISSUE TITLE
[Question]: vscode插件fauxpilot +paddlenlp codegen，无反应。

### ISSUE THREAD

**Issue by GUSHUMING** [PaddlePaddle/PaddleNLP#4692]
### 请提出你的问题

操作系统win11
GPU 3090
paddlenlp 2.5

使用openai demo测试是可行的能够运行
```

```
但使用vscode插件fauxpilot 无代码补全提示，fauxpilot设置如下
![13e0ed7aecaa379d79f7e36264b9cf9](https://user-images.githubusercontent.com/73211918/217248932-7a0bc098-4d09-45d0-959a-6432e7ec7b16.png)

**Comment by gongel** [comment]
你好，vscode控制台的日志能否截图看下？

**Comment by GUSHUMING** [comment]
> 你好，vscode控制台的日志能否截图看下？

```
import openai
openai.api_key = 'dummy'
openai.api_base = 'http://124.223.32.99:8979'
result = openai.Completion.create(
    engine='codegen', prompt='def chect_odd', max_tokens=16, temperature=0.1)
print(result)
```

这个是我用测试文件调用的。
![image](https://user-images.githubusercontent.com/73211918/217449259-648e51e6-e4ba-4029-a6f5-f9fab84925e8.png)
顺便问下，github copilot插件使用本地codegen服务也是要登录吗？github copilot貌似要付费。

**Comment by gongel** [comment]
OK，这个服务器的日志，需要提供下vs-code控制台的日志，看是否插件配置成功了。Copilot需要登录激活，然后也可以用我们的CodeGen去hack掉。

**Comment by sherluck314** [comment]
我也是这个情况。。。

**Comment by sherluck314** [comment]
在vscode安装插件之后，完全看不到它有启用的迹象

**Comment by garychian** [comment]
> 
请问一下，如何hack呢？我也是起了服务器，用测试用例可以跑，但是GitHub copolit插件的json文件也修改了，但是用的时候完全没有补齐或者啥的提示。
