### ISSUE TITLE
[Question]: 文本摘要抽取，貌似限制在164个汉字，超过就报错，怎么设置不限制输入字数呢

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleNLP#4694]
### 请提出你的问题

代码：

from paddlenlp import Taskflow
summarizer = Taskflow("text_summarization")
# 单条输入
print(summarizer('正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正正'
                 ))

**Comment by gongel** [comment]
你好，我这边测试没有问题哦，辛苦截图看下，同时告知PaddleNLP的版本

**Comment by sweetboxwwy** [comment]
> 你好，我这边测试没有问题哦，辛苦截图看下，同时告知PaddleNLP的版本

paddlenlp版本是2.4.9

报错如下：
  File "D:/PycharmProjects/Projects/text_summarization/test/main.py", line 5
SyntaxError: Non-UTF-8 code starting with '\xe5' in file D:/PycharmProjects/Projects/text_summarization/test/main.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by gongel** [comment]
> > 你好，我这边测试没有问题哦，辛苦截图看下，同时告知PaddleNLP的版本
> 
> paddlenlp版本是2.4.9
> 
> 报错如下： File "D:/PycharmProjects/Projects/text_summarization/test/main.py", line 5 SyntaxError: Non-UTF-8 code starting with '\xe5' in file D:/PycharmProjects/Projects/text_summarization/test/main.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

你写的代码是不是有bug呢？

**Comment by sweetboxwwy** [comment]
> > > 你好，我这边测试没有问题哦，辛苦截图看下，同时告知PaddleNLP的版本
> > 
> > 
> > paddlenlp版本是2.4.9
> > 报错如下： File "D:/PycharmProjects/Projects/text_summarization/test/main.py", line 5 SyntaxError: Non-UTF-8 code starting with '\xe5' in file D:/PycharmProjects/Projects/text_summarization/test/main.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> 
> 你写的代码是不是有bug呢？

没有bug，代码就是上面那一点点，我在164个字的基础上加一个字代码就报错，不加就可以输出结果

**Comment by gongel** [comment]
“SyntaxError: Non-UTF-8 code starting with '\xe5' in ... but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details” 
这个报错跟文本摘要的代码没有关系，是main.py的代码问题，代码最开始加 `# coding:utf-8`这个试下。

**Comment by sweetboxwwy** [comment]
> “SyntaxError: Non-UTF-8 code starting with '\xe5' in ... but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details” 这个报错跟文本摘要的代码没有关系，是main.py的代码问题，代码最开始加 `# coding:utf-8`这个试下。

解决了，谢谢大佬~

**Comment by wawltor** [comment]
您好，我们将关闭该issue，如有问题可以再次打开该issue，谢谢！
