### ISSUE TITLE
text_classification下few_shot的pet，使用infer.py推理错误

### ISSUE THREAD

**Issue by bobok65** [PaddlePaddle/PaddleNLP#4696]
### 请提出你的问题

环境python3.8.16
paddlepaddle=2.4.0
paddlenlp=2.4.3
windows10-64
![use](https://user-images.githubusercontent.com/97508337/217467890-b5375052-aa18-42cc-b795-a6425ce95b26.PNG)

![error](https://user-images.githubusercontent.com/97508337/217467954-a87feaa7-8952-45fa-abe5-c48ec82e5129.PNG)

**Comment by LemonNoel** [comment]
1. paddlenlp版本辛苦升级到最新版本，以保证执行代码与安装代码一致。命令如下
```
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

2. 执行 infer.py 推理前请按照[文档说明](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)导出模型，然后在 infer 时将 `model_path_prefix` 参数设置为导出模型路径前缀 `checkpoints/export/model`

3. 小样本文本分类任务推荐使用 UTC 模型，零样本和小样本能力更好。链接：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/zero_shot_text_classification

**Comment by bobok65** [comment]
我的硬件条件不支持训练，可以通过直接引用ernie_3.0_base_zh.pdparams来进行推理么？，不走导出模型的那一步

**Comment by wawltor** [comment]
> 我的硬件条件不支持训练，可以通过直接引用ernie_3.0_base_zh.pdparams来进行推理么？，不走导出模型的那一步

不可以的，ernie_3.0_base_zh.pdparams 不可以直接来做预测，https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/zero_shot_text_classification  这里的零样本分类可以直接预测，可以不做训练

**Comment by bobok65** [comment]
可以提供一下导出好能用的模型文件么，我的硬件条件不支持训练

**Comment by LemonNoel** [comment]
不支持训练是指什么呀？使用Taskflow只会导出模型，不会训练，执行下边代码的时候是有报错吗？
```
from paddlenlp import Taskflow
cls = Taskflow("zero_shot_text_classification", schema=["这是一条好评", "这是一条差评"])
cls("房间干净明亮，非常不错")
# [{'predictions': [{'label': '这是一条好评', 'score': 0.9695149765679986}], 'text_a': '房间干净明亮，非常不错'}]
```

**Comment by bobok65** [comment]
是否可以将zero_shot_text_classification改为text_classification 使用taskflow拿到few shot -pet 的模型呢？

**Comment by LemonNoel** [comment]
当前 develop 版本已经支持了，可以升级后试用，具体 PR 可参考 [这里](https://github.com/PaddlePaddle/PaddleNLP/pull/4723)，不过暂时还没有文档
```
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by bobok65** [comment]
text-classification如何使用taskflow，有示例么
![te](https://user-images.githubusercontent.com/97508337/218032072-3155587e-6e5a-4bd1-8c1d-68eeb72c0165.PNG)

**Comment by LemonNoel** [comment]
今天晚点会提个示例文档的 PR，提交后会在这里更新进展 @lugimzzz

**Comment by lugimzzz** [comment]
请参考文档，详见 https://github.com/PaddlePaddle/PaddleNLP/pull/4747
![image](https://user-images.githubusercontent.com/63761690/218041847-6438d643-cf48-49ab-b4a4-4af3a6bf6629.png)

**Comment by bobok65** [comment]
可以把你截图的网页地址放一下么，没找到相关的位置。
![error](https://user-images.githubusercontent.com/97508337/218384544-4a06ef0f-deed-4f10-8138-b1e08c442206.PNG)

**Comment by lugimzzz** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/06dbd35a93caec2a46e08a56a1450497b279f2a0/docs/model_zoo/taskflow.md

model 应该写成model = "prompt"

**Comment by bobok65** [comment]
错误，您的环境是什么
[list](https://user-images.githubusercontent.com/97508337/218395092-0b721351-54a8-45b0-bcb3-5ccb3447ac53.PNG)
![error](https://user-images.githubusercontent.com/97508337/218395141-0ea8fae4-86b3-481b-9e64-fa557b358917.PNG)

**Comment by bobok65** [comment]
仍然报错，您的环境是什么
![list](https://user-images.githubusercontent.com/97508337/218395246-6080aad4-a32c-4383-af00-ed3608d96737.PNG)
![error](https://user-images.githubusercontent.com/97508337/218395281-74c32dfa-f775-4fbd-b687-f6ceeae56eb5.PNG)

python3.8.16

**Comment by lugimzzz** [comment]
task_path要改成你自己的模型静态图路径
from paddlenlp import Taskflow
cls = Taskflow("text_classification", model="prompt", task_path="checkpoint/plm", is_static_model=True, problem_type="multi_label", id2label={ 0: "体育", 1: "经济", 2: "娱乐"})

**Comment by bobok65** [comment]
不支持开箱即用，不支持像其他案例的taskflow直接拉取下载模型是么，因为无法训练得到模型，所以想通过taskflow直接拉取模型

**Comment by lugimzzz** [comment]
对，暂时没有零样本能力

**Comment by bobok65** [comment]
不是zero_shot_classification ,是txt_classification，也没有？

**Comment by bobok65** [comment]
先按readme中的微调步骤进行训练，错误，
![trainerror](https://user-images.githubusercontent.com/97508337/218406855-1384e33d-c3c3-4427-8f11-f8c0d6f663e5.PNG)
![dir](https://user-images.githubusercontent.com/97508337/218406891-144a6fcc-1c61-4bff-9cd6-88e4ea740a48.PNG)
命令和数据结构是否有问题，此环境为PC，无gpu，cuda，cudnn
