### ISSUE TITLE
[Question]: 文本匹配任务中的sentence_transformers模型，是否可以用paddleserving进行部署？是否有相关文档？

### ISSUE THREAD

**Issue by MooTong123** [PaddlePaddle/PaddleNLP#4697]
### 请提出你的问题

1. 请问下 文本匹配的sentence_transformers模型，怎么没有export_model.py脚本进行模型导出功能，把动态图转换成静态图？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/sentence_transformers
2. 请问下这个sentence_transformers，有部署方面的文档吗？是否可以用paddleserving进行快速部署？

**Comment by w5688414** [comment]
目前不建议用paddle serving服务化部署了，可以看看 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md 

如果需要高性能部署，可以参考：https://github.com/PaddlePaddle/FastDeploy

**Comment by MooTong123** [comment]
> 目前不建议用paddle serving服务化部署了，可以看看 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md
> 
> 如果需要高性能部署，可以参考：https://github.com/PaddlePaddle/FastDeploy

您好，有个问题，用SimpleSevring的预训练模型部署中的post_handler，有没有针对文本匹配任务的post_handler?https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/sentence_transformers
