### ISSUE TITLE
[Question]: paddle在使用UIE的时候报错

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleNLP#4701]
### 请提出你的问题

在进行模型评估的时候, 使用evaluate.py文件的时候, 报如下bug
/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "evaluate.py", line 30, in <module>
    from paddlenlp.transformers import UIE, UIEM, AutoTokenizer
ImportError: cannot import name 'UIE' from 'paddlenlp.transformers' (/data/disk-2T/houxiaojun/anaconda3/envs/ner_pytorch_py37/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)
问题: paddlenlp不能导入UIE而报错

**Comment by linjieccc** [comment]
@chinesejunzai12 你好，请尝试下更新paddlenlp的版本 ``pip install -U paddlenlp``

**Comment by chinesejunzai12** [comment]
可以了, 谢谢 需要升级的paddlenlp==2.5.0
------------------------------------------------------------------
发件人：Linjie Chen ***@***.***>
发送时间：2023年2月8日(星期三) 19:56
收件人：PaddlePaddle/PaddleNLP ***@***.***>
抄　送：侯晓君 ***@***.***>; Mention ***@***.***>
主　题：Re: [PaddlePaddle/PaddleNLP] [Question]: paddle在使用UIE的时候报错 (Issue #4701)
@chinesejunzai12 <https://github.com/chinesejunzai12 > 你好，请尝试下更新paddlenlp的版本 pip install -U paddlenlp

**Comment by chinesejunzai12** [comment]
在使用evaluate.py文件进行debug评估的时候报以下问题:
[2023-02-09 11:02:09,335] [    INFO] - -----------------------------
[2023-02-09 11:02:09,336] [    INFO] - Class Name: 时间
[2023-02-09 11:02:09,336] [    INFO] - Evaluation Precision: 1.00000 | Recall: 1.00000 | F1: 1.00000
[2023-02-09 11:02:09,425] [    INFO] - -----------------------------
[2023-02-09 11:02:09,425] [    INFO] - Class Name: 费用
[2023-02-09 11:02:09,425] [    INFO] - Evaluation Precision: 1.00000 | Recall: 0.90000 | F1: 0.94737
[2023-02-09 11:02:09,477] [    INFO] - -----------------------------
[2023-02-09 11:02:09,477] [    INFO] - Class Name: 出发地
[2023-02-09 11:02:09,477] [    INFO] - Evaluation Precision: 1.00000 | Recall: 1.00000 | F1: 1.00000
Traceback (most recent call last):
  File "../evaluate.py", line 142, in <module>
    do_eval()
  File "../evaluate.py", line 118, in do_eval
    precision, recall, f1 = evaluate(model, metric, test_data_loader)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/uie_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data/disk-2T/houxiaojun/anaconda3/envs/uie_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "../evaluate.py", line 51, in evaluate
    batch["input_ids"], batch["token_type_ids"], batch["position_ids"], batch["attention_mask"]
KeyError: 'token_type_ids'
目前包的版本是:
paddle-bfloat        0.1.7
paddle2onnx          1.0.5
paddlefsl            1.1.0
paddlenlp            2.5.0
paddlepaddle         2.4.1
paddlepaddle-gpu     2.4.1.post112
x2paddle             1.4.0

**Comment by szz1211** [comment]
> 在使用evaluate.py文件进行debug评估的时候报以下问题: [2023-02-09 11:02:09,335] [ INFO] - ----------------------------- [2023-02-09 11:02:09,336] [ INFO] - Class Name: 时间 [2023-02-09 11:02:09,336] [ INFO] - Evaluation Precision: 1.00000 | Recall: 1.00000 | F1: 1.00000 [2023-02-09 11:02:09,425] [ INFO] - ----------------------------- [2023-02-09 11:02:09,425] [ INFO] - Class Name: 费用 [2023-02-09 11:02:09,425] [ INFO] - Evaluation Precision: 1.00000 | Recall: 0.90000 | F1: 0.94737 [2023-02-09 11:02:09,477] [ INFO] - ----------------------------- [2023-02-09 11:02:09,477] [ INFO] - Class Name: 出发地 [2023-02-09 11:02:09,477] [ INFO] - Evaluation Precision: 1.00000 | Recall: 1.00000 | F1: 1.00000 Traceback (most recent call last): File "../evaluate.py", line 142, in do_eval() File "../evaluate.py", line 118, in do_eval precision, recall, f1 = evaluate(model, metric, test_data_loader) File "/data/disk-2T/houxiaojun/anaconda3/envs/uie_env/lib/python3.7/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/data/disk-2T/houxiaojun/anaconda3/envs/uie_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function return func(*args, **kwargs) File "../evaluate.py", line 51, in evaluate batch["input_ids"], batch["token_type_ids"], batch["position_ids"], batch["attention_mask"] KeyError: 'token_type_ids' 目前包的版本是: paddle-bfloat 0.1.7 paddle2onnx 1.0.5 paddlefsl 1.1.0 paddlenlp 2.5.0 paddlepaddle 2.4.1 paddlepaddle-gpu 2.4.1.post112 x2paddle 1.4.0

你好请问解决了吗  我也遇到了这个问题
