### ISSUE TITLE
[Question]: 使用utc的零样本文本分类，在预测时模型转换onnx报不支持算子错误

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#4709]
### 请提出你的问题

paddlepaddle-gpu  2.3.0.post1112
paddlenlp: 2.5.0
paddle2onnx: 1.0.5

使用零样本文本分类，使用领域小样本对utc进行微调后，参照https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/zero_shot_text_classification中“2.5定制模型一键预测”进行文本分类预测，模型加载后，在转onnx时报不支持conditional_block,select_input 这些算子，从而转换onnx失败。

模型加载代码： Taskflow("zero_shot_text_classification", schema=schema, task_path=model_path, precision=precision), 其中precision设置为fp16

![image](https://user-images.githubusercontent.com/5744496/217711009-58893664-7930-44f0-a489-7c6e8f29050d.png)

**Comment by LemonNoel** [comment]
paddlepaddle-gpu 2.4.1 后支持了这些算子，更新 paddlepaddle-gpu 即可

**Comment by leon-cas** [comment]
@LemonNoel 谢谢，我稍后更新下paddlepaddle-gpu版本后再试试。  此外，zero_shot_text_classification如果是二分类的话，预测结果两个类目的score之和不等于1， 可能两个类目预测出来的score都小于指定的阈值，比如0.5。 从而导致预测没有任何结果，对于二分类任务，怎么保证每次总有一个预测类目呢？

**Comment by leon-cas** [comment]
> paddlepaddle-gpu 2.4.1 后支持了这些算子，更新 paddlepaddle-gpu 即可

@LemonNoel 更新到paddlepaddle-gpu 2.4.1后，预测时报错如下：

```
from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

在/usr/local/cuda-11.2/lib64和/usr/local/cuda/lib64/libcuda目录下只有libcudart.so.11.0

**Comment by LemonNoel** [comment]
1. 预测结果：如果执行的 run_eval.py 文件，最简单的可以将[109行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/zero_shot_text_classification/run_eval.py#L109)替换，阈值设为0.5即可
```
preds = paddle.nn.functional.softmax(paddle.to_tensor(test_ret.predictions), axis=-1)
```

2. 环境问题：这个是paddle安装问题，CUDA环境文件缺失，可以使用conda安装，自动会补齐缺失的依赖。

**Comment by leon-cas** [comment]
> 1. 预测结果：如果执行的 run_eval.py 文件，最简单的可以将[109行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/zero_shot_text_classification/run_eval.py#L109)替换，阈值设为0.5即可
> 
> ```
> preds = paddle.nn.functional.softmax(paddle.to_tensor(test_ret.predictions), axis=-1)
> ```
> 
> 2. 环境问题：这个是paddle安装问题，CUDA环境文件缺失，可以使用conda安装，自动会补齐缺失的依赖。

@LemonNoel  是通过如下方式进行预测的：

```
query='测试样本'
utc = Taskflow("zero_shot_text_classification", schema=schema, task_path=model_path, kwargs = args)
res=utc(query)
```

**Comment by LemonNoel** [comment]
那可以修改 [paddlenlp/taskflow/zero_shot_text_classification.py 第239行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/zero_shot_text_classification.py#L239) ，替换为
```
from scipy.special import softmax
scores = softmax(np.array(logits), axis=1)
```
然后 cd 到 PaddleNLP 的根目录，从本地安装一下
```
pip install -e .
```

**Comment by leon-cas** [comment]
> 那可以修改 [paddlenlp/taskflow/zero_shot_text_classification.py 第239行](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/zero_shot_text_classification.py#L239) ，替换为
> 
> ```
> from scipy.special import softmax
> scores = softmax(np.array(logits), axis=1)
> ```
> 
> 然后 cd 到 PaddleNLP 的根目录，从本地安装一下
> 
> ```
> pip install -e .
> ```

@LemonNoel  谢谢，问题解决了
