### ISSUE TITLE
请问类似BertForSequenceClassification的预训练模型，只能用于处理文本二分类问题么

### ISSUE THREAD

**Issue by ybc-ybc** [PaddlePaddle/PaddleNLP#471]
训练文本多分类的数据，在train.py中修改num_classes，还是报错
    model = ppnlp.transformers.BertForSequenceClassification.from_pretrained('bert-wwm-ext-chinese', num_class=9)
    tokenizer = ppnlp.transformers.BertTokenizer.from_pretrained('bert-wwm-ext-chinese')

**Comment by Steffy-zxf** [comment]
你好！具体报错信息是什么？ 代码是什么样的？

**Comment by ybc-ybc** [comment]
> 你好！具体报错信息是什么？ 代码是什么样的？

SystemError: (Fatal) Operator equal raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 2, or == -100,but got 7. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 2, or == -100,but got 7. Please check input value.

**Comment by ZeyuChen** [comment]
检查下数据是否存在越界的情况。
