### ISSUE TITLE
[Question]: 文档信息抽取 UIE-X，同一实体只能抽取一个

### ISSUE THREAD

**Issue by BugOMan** [PaddlePaddle/PaddleNLP#4711]
### 请提出你的问题

文档信息抽取 UIE-X，同一实体只能抽取一个。
例如：图片中有多个联系电话，但是抽取出来只有一个联系电话。
<img width="275" alt="5" src="https://user-images.githubusercontent.com/26920237/217714934-286ca2d1-0b04-4cc5-a8d5-9853673d1548.png">

from paddlenlp import Taskflow
docprompt = Taskflow("document_intelligence")
print(docprompt({"doc": "./images/5.png", "prompt": ["电话"]}))
模型只输出一个电话号码：
[{'prompt': '电话', 'result': [{'value': '15911144234', 'prob': 0.99, 'start': 94, 'end': 94}]}]

**Comment by linjieccc** [comment]
@BugOMan 你好，试试设置topn参数来返回top n个结果，默认值是1

```python
docprompt = Taskflow("document_intelligence", topn=5)
```
