### ISSUE TITLE
ChatGPT 这样的能弄不？

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleNLP#4725]
### 问题描述

ChatGPT 这样的能弄不？

对话起码要实现上下文

**Comment by lugimzzz** [comment]
开放域对话可以参考一下这个taskflow，看是否可以满足要求：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md#%E5%BC%80%E6%94%BE%E5%9F%9F%E5%AF%B9%E8%AF%9D
