### ISSUE TITLE
[Question]: UTC微调，分类标签过多问题

### ISSUE THREAD

**Issue by liuyubiao** [PaddlePaddle/PaddleNLP#4730]
### 请提出你的问题

本地环境CentOS7
TITAN XP 16G 单卡
CUDA 10.2
cuDNN 7.6.5

Conda环境：
Python 3.7.13
Paddle-GPU 2.4.1
PaddleNLP 2.5.0

官方提供的医疗数据集已测试通过，
使用自定义数据集125分类微调，每类约3000条数据，
按照医疗数据集格式化了训练数据，数据格式为：
{"choices": [..(125类的标签名称)], "labels": ..(标签索引), "question": "", "text_a": ..(内容), "text_b": ""}
训练启动失败，
一处警告为：
[ WARNING] - Token indices sequence length is longer than the specified maximum sequence length for this model (704 > 512). Running this sequence through the model will result in indexing errors
报错为：
Actual length has exceeded the maximum length. Check the implementation.

debug代码发现：
paddlenlp包中
(anaconda本机路径)/paddlenlp/prompt/prompt_tokenizer.py 
_create_max_lengths_from_do_truncate 函数也会对提供的choices中标签文本进行长度判断，因为默认的max_length为512，分类标签长度超过了512，导致报错，目前将max_length改成了1024，其他参数没有变动 
还会提示
[ WARNING] - Token indices sequence length is longer than the specified maximum sequence length for this model (704 > 512). Running this sequence through the model will result in indexing errors

不过可以正常训练，请问这样训练是否影响最终结果？

另外，训练2-3轮之后（2-3轮的训练和评估都正常，loss正常下降），训练会卡在Running Evaluation，训练日志没有其他异常，训练进程会直接退出，并没有生成best_model，checkpoint停留在checkpoint-200，重新启动训练不会加载已训练的checkpoint，会从头开始训练，训练2-3轮后依然出现上述问题，目前训练陷入瓶颈

问题点：
1. 请问将max_length改成1024之后，是否对最终结果有影响
2. 目前我该如何操作可以正常的完成训练

希望各位大佬们有时间可以给我一些提示，非常感激

**Comment by feng-1985** [comment]
预训练模型只支持512，文本过长，应该会截断的。

可以把文本长度截断一下（比如100之类），跑一下。太长了，占显存，可能就卡住了

**Comment by LemonNoel** [comment]
1. max_length 改为 1024 对最终结果没有影响，text 与 label 编码是分开的
2. 训练的脚本是多卡还是单卡呢？

**Comment by liuyubiao** [comment]
> 预训练模型只支持512，文本过长，应该会截断的。
> 
> 可以把文本长度截断一下（比如100之类），跑一下。太长了，占显存，可能就卡住了

谢谢回答
目前数据集中每条数据的格式为：
{"choices": [..(125类的标签名称)], "labels": ..(标签索引), "question": "", "text_a": ..(内容), "text_b": ""}
文本内容（text_a）没有超过512的，最长的就是200，主要是标签（choices）问题，参照医疗数据集，choices中的内容（125分类名称）每条数据都要带上，所以choices长度一超过了，就会提示 Actual length has exceeded the maximum length. Check the implementation. 错误了，请问choices也可以截断处理吗? 如果可以的话，那单条数据的形式是什么样子的呢？ 

附官方提供的医疗数据集
python label_studio.py 执行完成之后的医疗数据集单条的示例为：
{"text_a": "汗蒸对人体有什么好处？", "text_b": "", "question": "", "choices": ["病情诊断", "治疗方案", "病因分析", "指标解读", "就医建议", "疾病表述", "后果表述", "注意事项", "功效作用", "医疗费用", "其他"], "labels": 8}

每条数据的choices中将所有分类标签都带上了，我目前就是这个choices中放了125分类的名称，导致超出了max_length

期待回复

**Comment by liuyubiao** [comment]
> 1. max_length 改为 1024 对最终结果没有影响，text 与 label 编码是分开的
> 2. 训练的脚本是多卡还是单卡呢？

好的，明白，感谢回复
训练的脚本我用的是单卡的，很奇怪，每次正常训练及评估运行2-3轮，在第三轮的Running Evaluation 时就卡住了，然后整个进程就被kill掉了，日志中也没发现异常，如果是显存的问题，我准备换V100的设备再测试一下

**Comment by LemonNoel** [comment]
1. choices 是没办法截断的，目前 max_length 计算的时候这部分长度需要手动加上去，也就是text需要的长度 + len(choices) + sum([len(x) for x in choices])。

2. 评估问题可能是bug导致的，对于部分数据处理不兼容，目前[修复 PR](https://github.com/PaddlePaddle/PaddleNLP/pull/4716) 暂未合入。可以在 ~/.paddlenlp/models/utc-large/vocab.txt 文件最后一行加上 `[O-MASK]` 再尝试

**Comment by liuyubiao** [comment]
> 1. max_length

好的，非常感谢，我尝试操作一下

**Comment by liuyubiao** [comment]
> 1. choices 是没办法截断的，目前 max_length 计算的时候这部分长度需要手动加上去，也就是text需要的长度 + len(choices) + sum([len(x) for x in choices])。
> 2. 评估问题可能是bug导致的，对于部分数据处理不兼容，目前[修复 PR](https://github.com/PaddlePaddle/PaddleNLP/pull/4716) 暂未合入。可以在 ~/.paddlenlp/models/utc-large/vocab.txt 文件最后一行加上 `[O-MASK]` 再尝试

修改完成后可以正常训练和评估，多谢解答，
另外请问，如果我训练时中断了，怎么加载中间模型继续进行训练呢？我看UTC说明里面有断点重启的功能

**Comment by LemonNoel** [comment]
可以使用 resume_from_checkpoint 参数指定路径加载中间模型

**Comment by liuyubiao** [comment]
> 可以使用 resume_from_checkpoint 参数指定路径加载中间模型
问题已解决，非常感谢
