### ISSUE TITLE
[Bug]: zero shot text classification的taskflow离线加载模型失败

### ISSUE THREAD

**Issue by feng-1985** [PaddlePaddle/PaddleNLP#4731]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.3.1
- paddlenlp: 2.5.0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
mkvirtualenv 创建虚拟环境
将utc-large的模型文件迁移到缓存目录:~/.paddlenlp/models/utc-large
```

### 稳定复现步骤 & 代码

schema = ["好评", "差评"]
my_cls = Taskflow("zero_shot_text_classification", 
                  schema=schema)

没有加载缓存的模型，依然在调用接口下载

**Comment by LemonNoel** [comment]
需求是离线预测是吗？taskflow 的缓存目录和微调的有所区别，需要将下载文件移到目录`~/.paddlenlp/taskflow/zero_shot_text_classification/utc-large/` 

下载的文件地址在 [这个链接](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/zero_shot_text_classification.py#L58-L78)

**Comment by feng-1985** [comment]
离线预测，模型文件迁移到这个目录里
~/.paddlenlp/taskflow/zero_shot_text_classification/utc-large/

找到原因了。
之前是命名为utc_large.pdparams，改成model_state.pdparams就行了

**Comment by feng-1985** [comment]
加载已经训练好的模型：
指定目录为'./checkpoint/model_best/plm' - 这个目录存的是微调后的模型吗？

**Comment by LemonNoel** [comment]
是微调后的模型。另外加载微调模型需要安装 paddlenlp develop 版本
```
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by feng-1985** [comment]
解决了：
加载已经训练好的模型，指定目录为'./checkpoint/model_best/plm' 

还需要把tokenizer相关文件迁移到这个目录下才行

**Comment by feng-1985** [comment]
预测完之后，会生成static目录，请问这里面的inference.pdmodel怎么用？

**Comment by wawltor** [comment]
> 预测完之后，会生成static目录，请问这里面的inference.pdmodel怎么用？

生成static目录后，后自动选择static的inference.pdmodel进行加速预测

**Comment by wawltor** [comment]
您好，我们将暂时关闭该issue，如有问题，可以再次打开该issue。

**Comment by feng-1985** [comment]
@wawltor   加载训练好的模型，设置好目录后，会先加载预训练模型，怎么避免加载预训练模型？（可以把预训练模型放入默认缓存目录，但是增加了需要加载的模型）
