### ISSUE TITLE
层次分类的few-shot learning 中出现verbalizer Nonetype报错

### ISSUE THREAD

**Issue by felixstander** [PaddlePaddle/PaddleNLP#4736]
### 请提出你的问题

1）版本、环境信息

PaddleNLP 2.4.3
PaddlePaddle 2.4.1
2）系统环境
windows10， Python3.8
3）复现信息
您好，在复现[applications/text_classification/hierarchical/few-shot](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical/few-shot)的代码过程，根据README.md要求在Terminal中成功运行了训练&评估代码，如下：
python train.py \
--data_dir D:/PaddleNLP/data \
--output_dir ./checkpoints/ \
--prompt "这句话描述的事件是" \
--model_name_or_path C:/Users/43855/.paddlenlp/models/ernie-3.0-base-zh \
--max_seq_length 128  \
--device 'cpu' \
--learning_rate 3e-5 \
--ppt_learning_rate 3e-4 \
--do_train \
--do_eval \
--do_export \
--num_train_epochs 100 \
--logging_steps 5 \
--save_total_limit 1 \
--per_device_eval_batch_size 32 \
--per_device_train_batch_size 8 \
--metric_for_best_model macro_f1_score \
--load_best_model_at_end \
--eval_steps 100

<img width="596" alt="image" src="https://user-images.githubusercontent.com/92704549/218005767-b7036be0-4453-4406-856d-9a4546faaace.png">

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/92704549/218005641-654056a1-2c1a-4a56-9b32-38728ff68d1f.png">

却出现verbalizer Nonetype报错，请问这有可能是什么造成的，如何解决呢？

**Comment by felixstander** [comment]
应该是 AutoModelForMaskedLM 加载ernie 3.0 预训练模型的时候出现 model.___class__.__name__出现 Nonetype

**Comment by felixstander** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/92704549/218016599-1101fa8e-7349-49ea-9cd9-b650cd6df246.png">

请问是模型文件起名或者config出现问题吗

**Comment by LemonNoel** [comment]
辛苦安装 paddlenlp 最新版本看看是否还有这个问题，近期框架升级存在版本迭代。
```
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by felixstander** [comment]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/92704549/218019364-8a1bd139-a601-4080-83db-e889250561ca.png">
这边更新了最新版本，但也存在这样的情况

**Comment by LemonNoel** [comment]
这里是 from_pretrained 时候就报错了，请问 model_args.model_name_or_path 参数设置的是哪个呢

**Comment by felixstander** [comment]
model_name_or_path 是我把模型下载下来的本地文件路径呢，路径没有问题，都已经包括该有的文件了。
<img width="742" alt="image" src="https://user-images.githubusercontent.com/92704549/218022463-41c25f5b-ff2f-438d-b38d-d356e96c6aa4.png">

**Comment by LemonNoel** [comment]
从本地建议先使用 `ErnieForMaskedLM` 加载

**Comment by felixstander** [comment]
嗯嗯，用paddlenlp.transformers.ernie.modeling import ErnieForMaskedLM 可成功载入，已解决，谢谢。
