### ISSUE TITLE
预测结果问题

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#4753]
### 请提出你的问题

请问，这个层次分类代码我看bad case里每一层级的预测结果有多个，比如体育下一层级有篮球和足球，我运行后bad case里的预测结果篮球和足球都会显示，可以改为每一层级只能预测一种结果吗？另外，比如上一层级是体育和文化，结果会出现文化和足球，可以修改为如果结果为文化，就不再进行下一层级的判断吗？就是结果输出为文化就结束了，输出为体育，再进行下一层级的判断，篮球还是足球。谢谢。

**Comment by lugimzzz** [comment]
目前这个层次分类是被转化为多标签任务，这个建议你对模型预测结果进行一些后处理，加上这些逻辑判断

**Comment by QChen0409** [comment]
您好，请问具体需要是对哪个文件进行修改呢？是修改写模型的文件吗？没有找到模型文件，只看到train.py,evaluate.py和predict.py这些。另外，还有几个问题想向您请教下。
①macroF1是怎么算的，我的样本极度不平衡，想看一下Macro F1值是怎么算的？或者您能告诉我一下Macro F1值计算方法是哪个文件吗？
②这个分词依据是什么？我的样本是标注好的数据，每个词以空格分开，模型可以按照空格来分割每个词来学习各自的embedding吗？可以print出来看下吗？
③想输出attention的值看看每个词对应的attention权重，应该在哪个文件上如何修改呢？
④trustai那部分我看支持lm,IG，grad，我想用attentioninterpret，根据教程修改后报错list index out of range,请问应该如何修改呢？
非常感谢！




1624140190
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 预测结果问题 (Issue #4753)





 
目前这个层次分类是被转化为多标签任务，这个建议你对模型预测结果进行一些后处理，加上这些逻辑判断

**Comment by lugimzzz** [comment]
训练不需要改变，也不用改模型代码，修改 predict.py文件即可https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/hierarchical/predict.py#L90
1. macro f1请查看utils.py
2. 分词的依据是根据ernie-3.0分词方法，可以用tokenizer.tokenize()
```
from paddlenlp.transformers import  AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-medium-zh")
tokenizer.tokenize("查看分词方法")
```
3.在另一个issue有人回答你了
4.目前analysis模块暂时没支持attentioninterpret，不清楚你是怎么修改的，可以到trustai repo下提issue https://github.com/PaddlePaddle/TrustAI

**Comment by QChen0409** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/4431334
您好，在这里面看到的attentioninterpret,按照这个来修改的

from trustai.interpretation.token_level.common import attention_predict_fn_on_paddlenlp
from trustai.interpretation.token_level import AttentionInterpreter

att_interpreter = AttentionInterpreter(model, device="gpu:0", predict_fn=attention_predict_fn_on_paddlenlp)

**Comment by lugimzzz** [comment]
这块可以在trustai repo提一个issue，提供你修改后完整可复现代码、具体报错以及运行环境（paddlepaddle、paddlenlp、trustai版本）。
