### ISSUE TITLE
important visualization显示的文本是每一个数据的全部文本吗？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#4754]
important visualization显示的文本是每一个数据的全部文本吗？

请问word_interpret.ipynb文件中important visualization显示的文本是每一个数据的全部文本吗？我的每一个数据大概1800个字，但是结果里面important visualization一栏并没有显示全部的文本，只显示了100多个字。谢谢

**Comment by 1649759610** [comment]
你好，可以提供多一点的信息吗，是在做什么应用时出现的问题？
