### ISSUE TITLE
请问可以输出每个词对应的attention重要性分数吗？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#4755]
### 请提出你的问题

请问可以将每个词及其对应的attention重要性分数以字典形式输出出来吗？就是可以看到文本中所有词及其对应的attention分数，有相关的代码吗？谢谢

**Comment by 1649759610** [comment]
在调用forward函数时可以设置output_attentions=True, 即可返回attention权重。

**Comment by QChen0409** [comment]
请问是哪个文件的forward函数呢？没有找到，可以将每个词及其对应的attention权重以字典形式输出出来吗？

**Comment by sijunhe** [comment]
> 请问是哪个文件的forward函数呢？没有找到，可以将每个词及其对应的attention权重以字典形式输出出来吗？

paddlenlp里的主要的模型都支持`output_attentions`这个参数，请参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/modeling.py#L290
