### ISSUE TITLE
[Bug]: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#4760]
### 软件环境

```Markdown
- paddlepaddle:无
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
之前都能用GPU训练UIE，使用新版本后突然报错cudnn的错误，尝试重新配cudnn无效，执行paddle.utils.run_check()如下：
```

### 稳定复现步骤 & 代码

![issue_1](https://user-images.githubusercontent.com/88191580/218355163-154138e9-051a-4537-ba50-3bcc1dd6274c.png)
![issue_2](https://user-images.githubusercontent.com/88191580/218355165-966ee3c3-c2d6-4593-ada0-875cadc34d18.png)

**Comment by wawltor** [comment]
使用这个方法可以解决 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/16698950/218385446-f5a45833-afc9-4901-9746-c4a44b23c73f.png">
https://github.com/PaddlePaddle/Paddle/issues/49106

**Comment by jiweizhangxu** [comment]
> 

还是不行，这个好像不是我是liunx系统，将其写入.bashrc文件，重新加载后还是报相同错误
![3](https://user-images.githubusercontent.com/88191580/218388848-1177071a-e684-4418-b328-bbeb0079fa98.png)

**Comment by jiweizhangxu** [comment]
> 
不管用，我将其写入.bashrc文件，执行source ~/.bashrc后还是报相同错误
![1 5](https://user-images.githubusercontent.com/88191580/218389746-22207166-9d70-43ce-95b0-fdd81a413515.png)

**Comment by jiweizhangxu** [comment]
> 使用这个方法可以解决 <img alt="image" width="866" src="https://user-images.githubusercontent.com/16698950/218385446-f5a45833-afc9-4901-9746-c4a44b23c73f.png"> [PaddlePaddle/Paddle#49106](https://github.com/PaddlePaddle/Paddle/issues/49106)

没有解决，您看一下我下面的回复

**Comment by wawltor** [comment]
export 第一个LD_LIBRARY_PATH即可，你用了python 环境就export 
<img width="821" alt="image" src="https://user-images.githubusercontent.com/16698950/218395837-d05e6d7e-2f0c-4b8a-b269-f82b0a585ce4.png">

**Comment by jiweizhangxu** [comment]
> export 第一个LD_LIBRARY_PATH即可，你用了python 环境就export <img alt="image" width="821" src="https://user-images.githubusercontent.com/16698950/218395837-d05e6d7e-2f0c-4b8a-b269-f82b0a585ce4.png">

把下面的paddle_fei_new_1删除了，再次重新source ~/.bashrc还是报错，还有别的解决方法吗？

**Comment by jiweizhangxu** [comment]
> 

我刚才直接在pycharm中运行报同样错误，但是命令行运行可以检测到GPU了，算是解决了吧

**Comment by wawltor** [comment]
> > 
> 
> 我刚才直接在pycharm中运行报同样错误，但是命令行运行可以检测到GPU了，算是解决了吧

那看起来是pycharm环境的设置和命令行的环境配置有区别。我们先关闭该issue，如有问题可以再次打开该issue!
