### ISSUE TITLE
关于迁移学习的问题

### ISSUE THREAD

**Issue by justiceeem** [PaddlePaddle/PaddleNLP#477]
例子提供的训练脚本里都是给的AdamW以及LinearDecayWithWarmup。
想要请问一下，如果对于数量极少的场景下做迁移学习是否需要修改优化器。
还有就是想要请教下对于这种数据少的情况，有没有什么好的办法呢？

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot
Few-shot Leanring可以了解下。
方便介绍下你的应用场景吗？数据极少是多少？@justiceeem

**Comment by justiceeem** [comment]
场景是做Q-A匹配，将场景常见的语句与一个标准的语句（答案）做匹配，这样做主要是想要实现一个意图的分析来判断某一条语句属于哪一个标准，再进行下一步处理。
数据只有几千条。
训练策略则是加载预训练权重后直接训练这几千条数据。 @ZeyuChen

**Comment by tianxin1860** [comment]
> 场景是做Q-A匹配，将场景常见的语句与一个标准的语句（答案）做匹配，这样做主要是想要实现一个意图的分析来判断某一条语句属于哪一个标准，再进行下一步处理。
> 数据只有几千条。
> 训练策略则是加载预训练权重后直接训练这几千条数据。 @ZeyuChen

提供 2 个解决思路:
1.  几千条训练数据可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot 解决方案，针对小样本场景下训练1个 QA 匹配模型
2. 基于我们开源的语义匹配模型热启，在此基础上继续训练 1 个 QA 匹配模型, 参考示例: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/ernie_matching

**Comment by justiceeem** [comment]
@tianxin1860 谢谢！
