### ISSUE TITLE
[Question]: [Bug]ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.

### ISSUE THREAD

**Issue by zhangsone** [PaddlePaddle/PaddleNLP#4770]
### 请提出你的问题

我在运行 paddleNLP/exsamples/imformation_extraction/DuEE 篇章级事件抽取时，在最后枚举分类模型训练时报错
```
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.[Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:300 != labels_dims[i]:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:164)
```

没有改过代码，其他都可以正常运行，请问各位这个应该怎么解决？

**Comment by LiuChiachi** [comment]
看起来是报错的维度不对。可以根据代码定位到具体报错的行，打印下shape看看呢

**Comment by zhangsone** [comment]
> 
            logits = model(input_ids, token_type_ids)
            print(logits.shape)               #[16,300,4]
            print(labels.reshape)             #[16,1]
            loss = criterion(logits, labels)
虽然我知道是维度不对，但我尝试过修改维度，目前还没有找到好的解决办法

**Comment by LemonNoel** [comment]
paddlepaddle 版本是多少呢，我尝试复现下

**Comment by zhangsone** [comment]
> paddlepaddle 版本是多少呢，我尝试复现下

paddlenlp               2.2.2
paddlepaddle-gpu        2.3.2
这是我的版本号，前面运行都没有问题，只有最后做枚举属性训练的时候遇到这个维度错误

**Comment by zhangsone** [comment]
> paddlepaddle 版本是多少呢，我尝试复现下

请问您复现出来了吗？

**Comment by LemonNoel** [comment]
辛苦paddlenlp更新到2.5.1版本看下

**Comment by zhangsone** [comment]
> 辛苦paddlenlp更新到2.5.1版本看下

更新了也还是一样的报错，不知道为什么
