### ISSUE TITLE
[Question]: 关于docprompt/uie-x 从图片中长文本抽取

### ISSUE THREAD

**Issue by zirui** [PaddlePaddle/PaddleNLP#4772]
### 请提出你的问题

场景:
输入图片中要抽取的内容，既包含带layout(schema)的信息, 也有长的自由文本里信息, 用什么模型合适(同时支持layout信息抽取和VQA)?

搜了下相关的issue [3799](https://github.com/PaddlePaddle/PaddleNLP/issues/3799) [3579](https://github.com/PaddlePaddle/PaddleNLP/issues/3517)
 似乎Docprompt(document_intelligence)目前还不支持自定义数据集微调,  uie-x可以

那么关于uie-x 模型做抽取:

1. 是否支持从不带layout结构的长文本里抽取(VQA, 类似docprompt)？
2. 输入同时有带layout的以及长文本的，是否可以用一个uie-x模型来做抽取？

**Comment by linjieccc** [comment]
@zirui 你好，

UIE-X是面向纯文本及文档场景的通用抽取式模型，常见的报关单、表格、年报等都可以使用UIE-X，同时有布局例如表格加大段文本的情况一般需要在实际场景进行标注微调，可以参考这里的示例流程：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document

**Comment by zirui** [comment]
> @zirui 你好，
> 
> UIE-X是面向纯文本及文档场景的通用抽取式模型，常见的报关单、表格、年报等都可以使用UIE-X，同时有布局例如表格加大段文本的情况一般需要在实际场景进行标注微调，可以参考这里的示例流程：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document

多谢回复，目前我尝了做自由文本抽取(未标注实际场景数据),效果上uie-x-base不如docprompt好(uie-x基本召不回)
可能是因为docprompt在更多相关任务上云训练得得更好么, 或者说是uie-x-base缺乏在长文本任务如VQA上的训练么?

**Comment by linjieccc** [comment]
DocPrompt预训练数据规模更多，任务类型也更全面些，因此零样本效果更好
