### ISSUE TITLE
【PaddlePaddle Hackathon 第四期】No.105：基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型

### ISSUE THREAD

**Issue by chenxiaozeng** [PaddlePaddle/PaddleNLP#4775]
### No.105：基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型 <a name='task105'></a>

- **技术标签：** Python、NLP、扩散模型
- **奖励设置：**
   * 创意奖：一等奖奖金3k（1名），二等奖奖金1k（5名）；三等奖 面值 200 元京东卡（10名）。创意奖获奖队伍还可获得 50 美元 HuggingFace store 代金券一张
  * 参与奖：证书荣誉、飞桨周边礼品

- **详细描述：** 结合 [PPDiffusers](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers) 最新版本，基于自己的数据集，训练并开源趣味模型。可参考 **[模型训练  QuickStart](https://aistudio.baidu.com/aistudio/projectdetail/5513258)**
  - 基于 [DreamBooth + LoRA](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/dreambooth) 、[Text-to-Image+LoRA](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/text_to_image) 等技术，  使用自己的图片 Fine-tune 模型；当然你也可以使用 PPDiffusers 中  [Textual Inversion](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/textual_inversion) 等更多玩法，等你探索！
  - 主题推荐：
    - 流浪地球
    - 三体
    - 表情包
    - 家乡景观
    - 动物萌宠
    - 家居设计
    - 无限想象（主题不限）
- **提交内容：**
  - 【必需】提交1个AI studio项目，遵从 **[模板](https://aistudio.baidu.com/aistudio/projectdetail/5519383)** 规范
  - 【必需】将模型文件上传到Hugging Face，在模型卡片中介绍模型，并上传由模型生成的图片（以及相应Prompt，至少3组）
  - 【必需】在AI Studio 搭建应用中心，可参考 **[ QuickStart](https://aistudio.baidu.com/aistudio/projectdetail/5513258)**
- **提交流程：**
  - 在 **本条Issue** 下按如下模板回复，提交自己的趣味创意

```plain
【队名】：一个让人印象深刻的名字
【模型简介】：一句话描述自己模型的特色
【模型链接】：Hugging Face 地址
【AI Studio 项目地址】：xxx 
【可选】【Hugging Face 应用中心】：xxx
```

- **评奖：**
  - AI Studio 项目like数 + Fork数/10 + Hugging Face like数，结合AI Studio项目质量（实现思路、创意、项目作为教程的易读易用性）综合评选
  - 每支队伍可以提交多个模型，选择最好成绩作为队伍最终成绩
  - 只要提交，即可获得参与奖；每支队伍仅可获得一项创意奖
- **技术要求：**
  - 会用Python

**Comment by livingbody** [comment]
【队名】：大江向东我向西画画队
【模型简介】：美食、中国美食、顶尖美食
【模型链接】：[Hugging Face 地址](https://huggingface.co/livingbody/Chinese_Food)
【AI Studio 项目地址】：[【飞桨黑客松】AIGC - DreamBooth LoRA 文生图【美食】模型](https://aistudio.baidu.com/aistudio/projectdetail/5695460)

**Comment by livingbody** [comment]
【队名】：大江向东我向西画画队
【模型简介】：美食、中国美食、顶尖美食
【模型链接】：  https://huggingface.co/livingbody/Chinese_Food
【AI Studio 项目地址】：[https://aistudio.baidu.com/aistudio/projectdetail/5695460](https://aistudio.baidu.com/aistudio/projectdetail/5695460)

**Comment by livingbody** [comment]
【队名】：大江向东我向西画画队  
【模型简介】：美食、中国美食、顶尖美食  
【模型链接】： [https://huggingface.co/livingbody/Chinese\_Food](https://huggingface.co/livingbody/Chinese_Food)  
【AI Studio 项目地址】：[https://aistudio.baidu.com/aistudio/projectdetail/5695749](https://aistudio.baidu.com/aistudio/projectdetail/5695749)

**Comment by fanyhchn** [comment]
【队名】：AI爱画画
【模型简介】：流浪地球中的巨型行星发动机
【模型链接】： https://huggingface.co/fanfanchn/WonderingEarth
【AI Studio 项目地址】：https://aistudio.baidu.com/aistudio/projectdetail/5696904
【AI Studio 应用中心】：【PaddlePaddle Hackathon 4】AIGC作品 【行星发动机】

**Comment by greasebig** [comment]
【队名】：活宝
【模型简介】：隔空将你的狗狗放进桶里
【模型链接】： https://huggingface.co/greasebig/lora_sks_dogs
【AI Studio 项目地址】：https://aistudio.baidu.com/aistudio/projectdetail/5704542?contributionType=1

**Comment by livingbody** [comment]
【队名】：大江向东我向西画画队  
【模型简介】：美食、中国美食、顶尖美食  
【模型链接】： [https://huggingface.co/livingbody/Chinese\_Food](https://huggingface.co/livingbody/Chinese_Food)  
【AI Studio 项目地址】：[https://aistudio.baidu.com/aistudio/projectdetail/5695749](https://aistudio.baidu.com/aistudio/projectdetail/5695749)
【AI Studio 应用中心】：AIGC中国美食

**Comment by livingbody** [comment]
加了应用部署

**Comment by peteli25** [comment]
【队名】：together
【模型简介】：This is my hometown
【模型链接】： https://huggingface.co/peteli/hometown
【AI Studio 项目地址】：https://aistudio.baidu.com/aistudio/projectdetail/5682527
【AI Studio 应用中心】：AIGC-HomeTown

**Comment by zzk0** [comment]
【队名】：LPC
【模型简介】：Jedi Teddy: Rebuilding the Order of the Jedi, Fallen But Not Forgotten.
【模型链接】：https://huggingface.co/zzk0/jedi_teddy
【AI Studio 项目地址】：https://aistudio.baidu.com/aistudio/projectdetail/5797270
【AI Studio 应用中心】：【PaddlePaddle Hackathon 4】Jedi Teddy

**Comment by YangWulve** [comment]
【队名】：炼丹师
【模型简介】：饿了？整点薯条
【模型链接】：https://huggingface.co/LianDanShi/lora_fried_food
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5817401
【AI Studio 应用中心】：AIGC油炸美食

**Comment by yuchen202** [comment]
【队名】：不想画图
【模型简介】：生成独一无二的玫瑰花
【模型链接】：https://huggingface.co/yuchen1/lora_rose_flowers
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5876560

**Comment by Niki173** [comment]
【队名】：I_B_M
【模型简介】：钢铁侠与蝙蝠侠的复合体
【模型链接】：https://huggingface.co/Niki-173/lora_IR_BM
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5823506

**Comment by jjyaoao** [comment]
【队名】：花开富贵
【模型简介】：史前巨兽将以高达形态出击！！！机甲风炫酷恐龙一枚~~
【模型链接】： https://huggingface.co/jjyaoao/Gundam_Dinosaur/tree/main/
【AI Studio 项目地址】：https://aistudio.baidu.com/aistudio/projectdetail/5932453
【AI Studio 应用中心】：AIGC高达恐龙

**Comment by Liyulingyue** [comment]
【队名】：一根外向的腿毛
【模型简介】：通过'Neolle with xxxx'的语句生成原神角色诺艾尔的图片，主要集中在面部，例如'Neolle with blue flower'会返回一张带有蓝色花朵的诺艾尔面部图片。
【模型链接】：https://huggingface.co/Liyulingyue/Neolle_Face_Generator
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5912535

**Comment by zhl1bug** [comment]
【队名】：易八鸽铁匠铺

【模型简介】：剑，出自易八鸽铁匠铺。

【模型链接】：https://huggingface.co/zhl1bug/sword_1bug

【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5906465

【AI Studio 应用中心】：https://aistudio.baidu.com/aistudio/projectdetail/5906465

**Comment by megemini** [comment]
【队名】：megemini
【模型简介】：当中国水墨山水遇上AIGC
【模型链接】：Hugging Face 地址:
  - 模型 👉 [megemini/shanshui_style](https://huggingface.co/megemini/shanshui_style) 可以生成水墨山水画。
  - 模型 👉 [megemini/shanshui_gen_style](https://huggingface.co/megemini/shanshui_gen_style) 可以生成水墨山水画的具像图片。

【AI Studio 项目】：👉 [【Hackathon 4th AIGC】当中国水墨山水遇上AIGC](https://aistudio.baidu.com/aistudio/projectdetail/6103948)
【AI Studio 应用中心】：👉 [☯ 当中国水墨山水遇上AIGC ☯](https://aistudio.baidu.com/aistudio/projectdetail/6103948)
【Hugging Face 应用中心】：👉 [megemini/shanshui](https://huggingface.co/spaces/megemini/shanshui)

**Comment by yuchen202** [comment]
收到了，谢谢

**Comment by lizechng** [comment]
【队名】：Mortal
【模型简介】：万物皆可coding: 让模型认识到coding，从而实现生成任何[target]进行coding的图像
【模型链接】：https://huggingface.co/mortal99/everything_can_coding
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/6065063
【AI Studio 应用中心】：万物皆可coding

**Comment by enkilee** [comment]
【队名】：摸鱼
【模型简介】：利用皮卡丘生成动漫皮卡新造型
【模型链接】：[huggingface.co/enkilee/pika_comic](https://huggingface.co/enkilee/pika_comic)
【AI Studio 项目】：[aistudio.baidu.com/aistudio/projectdetail/5680388](https://aistudio.baidu.com/aistudio/projectdetail/5680388)

**Comment by thunder95** [comment]
【队名】：thunder95
【模型简介】：用 LoRA 和 DreamBooth 创作出奥特曼的舞姿
【模型链接】：https://huggingface.co/demut/lora_ultraman
【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/6176091
【AI Studio 应用中心】：https://aistudio.baidu.com/aistudio/projectdetail/6176091

**Comment by yanguicheng** [comment]
【队名】：1234567

【模型简介】：心海表情包生成

【模型链接】：https://huggingface.co/ygc/expression

【AI Studio 项目】：https://aistudio.baidu.com/aistudio/projectdetail/5906612

【AI Studio 应用中心】：https://aistudio.baidu.com/ibdgpua100/user/3666773/5906612/lab/tree/index.py

**Comment by FerryHuang** [comment]
【队名】：easy revenge

【模型简介】：使用了多种LoRA训练技巧训练了星野爱的人物LoRA

【模型链接】：Hugging Face 地址:

模型  [f3rry/hoshino_ai](https://huggingface.co/f3rry/hoshino_ai)
【AI Studio 项目】：[【Hackathon 4th AIGC】复活吧，我的爱人！《我推的孩子》人气主角星野爱角色LoRA训练](https://aistudio.baidu.com/aistudio/projectdetail/6180712)

【AI Studio 应用中心】： [✨ 复活吧，我的爱人！《我推的孩子》人气主角星野爱角色LoRA训练 ✨](https://aistudio.baidu.com/aistudio/projectdetail/6180712)

**Comment by sijunhe** [comment]
## 一等奖：
- megemini-当中国水墨山水遇上AIGC[【Hackathon 4th AIGC】当中国水墨山水遇上AIGC - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/6103948)



## 二等奖：
- 一根外向的腿毛-原神角色诺艾尔生成器[【PaddlePaddle Hackathon 4】AIGC 诺艾尔生成器 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5912535)
- AI爱画画-流浪地球中的巨型行星发动机[【PaddlePaddle Hackathon 4】AIGC作品 【行星发动机】 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5696904)
- 花开富贵-机甲风炫酷高达恐龙[【PaddlePaddle Hackathon 4】AIGC【高达恐龙】 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5932453)
- 易八鸽铁匠铺-剑 - 铁匠铺计划[【飞桨黑客松】AIGC - 剑 - 铁匠铺计划 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5906465)
- together-This is my hometown[【飞桨黑客松-AIGC - DreamBooth LoRA】HomeTown - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5682527)

## 三等奖：
- LPC-Jedi Teddy: Rebuilding the Order of the Jedi, Fallen But Not Forgotten.[【PaddlePaddle Hackathon 4】Jedi Teddy - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5797270)
- I_B_M-钢铁侠与蝙蝠侠的复合体[【PaddlePaddle Hackathon 4】AIGC【钢铁侠与蝙蝠侠】 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5823506)
- 炼丹师-饿了？整点薯条[【PaddlePaddle Hackathon 4】AIGC 【饿了？生成薯条】 - 飞桨AI Studio](https://aistudio.baidu.com/aistudio/projectdetail/5817401)
- 大江向东我向西画画队-美食、中国美食、顶尖美食([【PaddlePaddle Hackathon 4】AIGC【中国美食与花】](https://aistudio.baidu.com/aistudio/projectdetail/5695749))
- 不想画图-生成独一无二的玫瑰花([【飞桨黑客松】AIGC - DreamBooth LoRA 生成你的月季花](https://aistudio.baidu.com/aistudio/projectdetail/5876560))
- Mortal-万物皆可coding（[【PaddlePaddle Hackathon 第四期】No.105 作品提交：万物皆可coding](https://aistudio.baidu.com/aistudio/projectdetail/6065063)）
- thunder95-用 LoRA 和 DreamBooth 创作出奥特曼的舞姿（[【PaddlePaddle Hackathon 4】AIGC舞动的奥特曼](https://aistudio.baidu.com/aistudio/projectdetail/6176091)）
- easy revenge [✨ 复活吧，我的爱人！《我推的孩子》人气主角星野爱角色LoRA训练 ✨](https://aistudio.baidu.com/aistudio/projectdetail/6180712)

如果有问题，请发邮件至 paddle-hack@baidu.com 沟通

**Comment by yuchen202** [comment]
收到了，谢谢

**Comment by dddlli** [comment]
后续的事宜会在群里通知，还是发邮件呢
