### ISSUE TITLE
[Question]: UTC模型代码，获取第二个[CLS]token隐向量时，tensor.gather没有考虑文本sequence_length

### ISSUE THREAD

**Issue by LouisHeck** [PaddlePaddle/PaddleNLP#4784]
### 请提出你的问题

在UTC模型源码文件(paddlenlp/transformers/ernie/modeling) 第1331行，获取第二个[CLS]token隐向量时，tensor.gather()方法时，cls_position是不是应该加上每个文本的长度？否则获取到的cls_output仅为第一个文本cls处的向量表示

即：将原文1331行代码 `cls_output = paddle.tensor.gather(flat_sequence_output, cls_positions)` 改为如下：
`cls_output = paddle.tensor.gather(flat_sequence_output, cls_positions + flat_length)`

请帮忙看下，我理解的对不对？

附件：
![e652f8d8d31a16141c8dcc92461ffad](https://user-images.githubusercontent.com/38588261/218625609-39c1acf2-2563-4bfc-adc9-d154c9464eec.png)
![c265b73968597a9ed644698dbd8abd4](https://user-images.githubusercontent.com/38588261/218625624-cc4ba628-4063-4113-a9a2-d86b896c5083.png)

**Comment by LemonNoel** [comment]
非常感谢！修复 PR 已提交 https://github.com/PaddlePaddle/PaddleNLP/pull/4785
