### ISSUE TITLE
sentiment analysis 载入训练好的模型权重时无法识别自定义schema

### ISSUE THREAD

**Issue by felixstander** [PaddlePaddle/PaddleNLP#4787]
### 请提出你的问题

请提出你的问题
1）版本、环境信息

PaddleNLP 2.5.0
PaddlePaddle-gpu 2.3.1
2）系统环境
windows10， Python3.8
3）复现信息
您好，在复现[applications/sentiment_analysis/unified_sentiment_extraction](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction)的代码过程，根据README.md要求在Terminal中成功运行了训练&评估代码，如下：
python batch_predict.py
--file_path D:/voice_factory/data/sentiment/test_sentiment_0213.txt 
--save_path D:/voice_factory/data/sentiment/test_sentiment_0213_result.json
--load_from_dir  D:/voice_factory/checkpoint/model_best 
--schema "[ '情感倾向[中性,正面,负面-重度,负面-轻度吐槽]']"
--batch_size 4
--max_seq_len 256 

senta = Taskflow("sentiment_analysis",schema=args.schema, batch_size=args.batch_size,max_seq_len=args.max_seq_len,task_path=args.load_from_dir)

使用task flow载入训练好的权重进行预测时，schema无法识别，预测出来的类目也是只有一个negative类目，score也相近。
![4e516c2cbf6e4f41933f8c9ab636df8](https://user-images.githubusercontent.com/92704549/218632963-4c2ef796-3a74-41c5-9101-2ed5b85778a6.jpg)
想问问这是什么原因引起的？

**Comment by felixstander** [comment]
安装了develop版本，也无法识别出schema

**Comment by 1649759610** [comment]
有重新训练模型吗，如果重新训练了的话，可以放几条train.json文件中的训练样本看一下。

**Comment by felixstander** [comment]
训练数据长这样，并且训练过程中dev数据集的metric指标也有随之提升。
![f62c74d547deb9c4ef307a3e2fd2f69](https://user-images.githubusercontent.com/92704549/218675996-d2cfe7a3-9a31-48e5-b423-aef546829737.jpg)

**Comment by felixstander** [comment]
很奇怪，直接使用载入预训练模型uie-senta-base,也没办法识别到自定义的schema

**Comment by 1649759610** [comment]
可以按如下方法，先排查下问题：
1. 对训练集中的数据进行预测，验证是否预测正确
2. 删除load_from_dir目录下static子目录
3. 最后的结果文件比较奇怪，不像是batch_predict.py输出的文件信息

**Comment by felixstander** [comment]
![4772ac8f11ade98932f640abd6bb6e1](https://user-images.githubusercontent.com/92704549/218680831-b4c71f63-20a4-4938-b280-3900dda7411b.jpg)
输出答案为:[{text:'这个车险不错‘,'label':'negative','score':0.526676}]

**Comment by 1649759610** [comment]
需要手动指定下模型类型model="uie-senta-base"，比如：
senta = Taskflow("sentiment_analysis", schema=schema, model="uie-senta-base")

**Comment by felixstander** [comment]
但是他会去自动去联网去下载模型，这边我是内网，无法连外网下载模型，只能下载到本地。

**Comment by felixstander** [comment]
找到问题了，训练完的model best文件夹里没有model_config.json文件，这里就会去联网下载model_config.json。
