### ISSUE TITLE
[Question]: 关于语义检索系统的一些问题

### ISSUE THREAD

**Issue by ZeyuTeng96** [PaddlePaddle/PaddleNLP#4793]
### 请提出你的问题

做语义检索系统的大佬好，想问您一些关于语义检索系统的问题。
1.Milvus库中存的数据到底该是什么样式的数据？demo中给出的数据样例是 title+keywords的拼接和一句话（https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/recall/milvus#4-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87 ）。那么要做成像主界面展示的动图里回答的形式的话（https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search#1-%E5%9C%BA%E6%99%AF%E6%A6%82%E8%BF%B0 ），库里的数据还是按照“title+keywords的拼接和一句话”的形式来（而后通过相应的标题给用户提供具体内容），还是像动图里的“不同问题的各种答案”的形式？
2.如果milvus库中存的数据是“不同问题的各种答案”，是否在训练召回模型（SimCSE和In-batch-neg）和排序模型时（ernie-matching或者rocketQA），数据也将变成query + 不同问题的各种答案的形式。
3.如果milvus库中存的数据是“不同问题的各种答案”，如果出现issue里提到的长文本该怎么办？（[教学的问答系统使用什么技术是比较好的选择? · Issue #4651 · PaddlePaddle/PaddleNLP (github.com)](https://github.com/PaddlePaddle/PaddleNLP/issues/4651)）是不是考虑就不在库里存答案了，而是存一些答案的标题，对标题进行召回+排序。然后根据标题，去存储答案的地方，把答案返回用户？
4.能否在vx上和您私聊下这些问题。因为Issue沟通有时比较慢

**Comment by w5688414** [comment]
Hi, @ZeyuTeng96   title+keywords不是必须的，如果有当然更好，正常情况下title就行。如果要像pipelines那样的话，则需要用户的query和passage的对，库里的数据要跟您的训练集保持一致，这个根据训练集而定。

2. Milvus里面存放的是title/passage,然后用query进行检索对应的title/passage，Neural Search的数据需要query title的pair对的形式。
3.如果出现长文本，建议分段处理。标题是一篇文章的高度概括，长文本是不太好处理，可以先从标题召回下手。

4.您有加PaddleNLP用户群吗？里面有各个技术方向的工程师，可以随时沟通交流。
![image](https://user-images.githubusercontent.com/12107462/218704993-c8db785c-8910-4caf-8ff8-5b196a737566.png)

**Comment by ZeyuTeng96** [comment]
> 

1. 大佬好，也就是说milvus里面存放的是title/passage。具体存放的是什么类型的数据，是根据你训练召回和排序模型的训练集而定的？
2. 如果是学术检索这种场景，如果库里存放的是title，而我想返回整篇文章的话，是不是则需要按我的说法，就是根据title，从其他数据库拿整篇文章返回？
3. 我在群里，但是能否和您私聊一下这些问题
谢谢大佬 @w5688414

**Comment by w5688414** [comment]
> > 
> 
> 1. 大佬好，也就是说milvus里面存放的是title/passage。具体存放的是什么类型的数据，是根据你训练召回和排序模型的训练集而定的？
> 2. 如果是学术检索这种场景，如果库里存放的是title，而我想返回整篇文章的话，是不是则需要按我的说法，就是根据title，从其他数据库拿整篇文章返回？
> 3. 我在群里，但是能否和您私聊一下这些问题
>    谢谢大佬 @w5688414

您的微信号是多少，我加您，拉您进群

**Comment by ZeyuTeng96** [comment]
> > > 
> > 
> > 
> > 
> > 1. 大佬好，也就是说milvus里面存放的是title/passage。具体存放的是什么类型的数据，是根据你训练召回和排序模型的训练集而定的？
> > 2. 如果是学术检索这种场景，如果库里存放的是title，而我想返回整篇文章的话，是不是则需要按我的说法，就是根据title，从其他数据库拿整篇文章返回？
> > 3. 我在群里，但是能否和您私聊一下这些问题
> >    谢谢大佬 @w5688414
> 
> 您的微信号是多少，我加您，拉您进群

微信号是： zeyuteng
