### ISSUE TITLE
有关GPTMODEL中MultiHeadAttention的问题

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#4796]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/gpt/modeling.py#L345
在这里是TransformerDecoderLayer，为什么只创建一个MultiHeadAttention（self_attn），而decoderlayer应该是2个呀？（一个是self_attn，一个是cross_attn）

**Comment by liuzhipengchd** [comment]
@ZHUI @w5688414  大佬有空解答一下吗

**Comment by ZHUI** [comment]
找一了下 huggingface 那边的代码看看。这里的  `add_cross_attention `一般也是不开启的。这个PR为了其他目的才支持的。

https://github.com/huggingface/transformers/blob/9d1116e9951686f937d17697820117636bfc05a5/src/transformers/models/gpt2/modeling_gpt2.py#L366-L372
