### ISSUE TITLE
[Question]: uie是否可以进行多模型的联合训练最后集成

### ISSUE THREAD

**Issue by yangzhenyu6** [PaddlePaddle/PaddleNLP#4802]
### 请提出你的问题

之前听百度的一个大牛讲课是关于句子匹配的，他说如果最后还想提高效果，可以再ernie模型之后加一个bert和其他模型来提高单个模型的效果，我想问uie可以加入其他模型提高效果吗？如果有的话，有可以参考的demo吗，谢谢！！

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 之前听百度的一个大牛讲课是关于句子匹配的，他说如果最后还想提高效果，可以再ernie模型之后加一个bert和其他模型来提高单个模型的效果，我想问uie可以加入其他模型提高效果吗？如果有的话，有可以参考的demo吗，谢谢！！

UIE目前主要是聚集在信息抽取相关领域，目前我们进行没有增加模型来提升UIE效果的工作，如果单独提升UIE的效果可以使用更大模型、使用高质量的数据来提升模型效果。
