### ISSUE TITLE
[Question]: 端到端开放文档抽取问答系统运行提取时报错

### ISSUE THREAD

**Issue by behappyto-cn** [PaddlePaddle/PaddleNLP#4805]
### 请提出你的问题

您好，请问下 curl --request POST --url 'http://0.0.0.0:8891/query_documents' -H "Content-Type: application/json"  --data '{"meta": {"doc": "https://bj.bcebos.com/paddlenlp/taskflow/document_intelligence/images/invoice.jpg", "prompt": ["发票号码是多少?", "校验码是多少?"]}}' 出现如下的错误，应该怎么解决呢？
examples/document-intelligence/run_docprompt_server.sh: 行 20: 299528 段错误               (核心已转储)python rest_api/application.py 8891

![image](https://user-images.githubusercontent.com/98333528/218943449-e00b66fa-25e6-469e-8dcf-c629b3e072c1.png)

**Comment by w5688414** [comment]
请确认一下您的paddle版本是否装好。

```
安装完成后您可以使用 python3 进入 python 解释器，输入import paddle ，再输入 paddle.utils.run_check()

如果出现PaddlePaddle is installed successfully!，说明您已成功安装。
```
显存是否足够
