### ISSUE TITLE
[Question]: T5ForConditionalGeneration.from_pretrained("Langboat/mengzi-t5-base-mt") 这样是下载模型时 没有model_state.pdparams模型

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#4811]
### 请提出你的问题

paddlenlp          2.4.9
paddlepaddle-gpu   2.4.1.post112

T5ForConditionalGeneration.from_pretrained("Langboat/mengzi-t5-base-mt") 自动下载模型时 显示没有model_state.pdparams 和model_config.json.

请问 如何下载mengzi-t5-base paddle版本模型？？

**Comment by wj-Mcat** [comment]
你需要更新一paddlenlp 的版本就行了，这个权重也是最近才加进去的:

```shell
pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by RileyShe** [comment]
> 你需要更新一paddlenlp 的版本就行了，这个权重也是最近才加进去的:
> 
> ```shell
> pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
> ```

**Comment by xieyu0214** [comment]
> 你需要更新一paddlenlp 的版本就行了，这个权重也是最近才加进去的:
> 
> ```shell
> pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
> ```
我升级到 paddlenlp==2.5.0了  ，还是下载不下来：FileNotFoundError: configuration file<config.json> or <model_config.json> not found。 是不是模型源里就没有呢？

**Comment by gongel** [comment]
> > 你需要更新一paddlenlp 的版本就行了，这个权重也是最近才加进去的:
> > ```shell
> > pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
> > ```
> 
> 我升级到 paddlenlp==2.5.0了 ，还是下载不下来：FileNotFoundError: configuration file<config.json> or <model_config.json> not found。 是不是模型源里就没有呢？

2.5.1可以试下哈

**Comment by xieyu0214** [comment]
> > > 你需要更新一paddlenlp 的版本就行了，这个权重也是最近才加进去的:
> > > ```shell
> > > pip install --pre paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
> > > ```
> > 
> > 
> > 我升级到 paddlenlp==2.5.0了 ，还是下载不下来：FileNotFoundError: configuration file<config.json> or <model_config.json> not found。 是不是模型源里就没有呢？
> 
> 2.5.1可以试下哈

试了可以下载了 ，谢谢~ 
另外，gpt-cpm-small-cn-distill 这个模型是不是没有，不提供下载呀？

**Comment by gongel** [comment]
> gpt-cpm-small-cn-distill

应该有的：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/gpt/configuration.py#L168

**Comment by xieyu0214** [comment]
> > gpt-cpm-small-cn-distill
> 
> 应该有的：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/gpt/configuration.py#L168

下载了！非常感谢~
