### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by xiabingbao-ok** [PaddlePaddle/PaddleNLP#4814]
### 请提出你的问题

使用UIE进行推理的时候，可以输入一段文字在不指定schema情况下输出所有种类吗？？？
类似下面这种，不指定schema
schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
 ie = Taskflow('information_extraction', schema=schema)
 print(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
输出里面的人名、地名、品牌名等等所涉及的所有实体种类

**Comment by wawltor** [comment]
抱歉，UIE目前必须提供相关shema来提取相关信息，如果是封闭域的模型可以使用Taskflow WordTag模型，

```python
>>> from paddlenlp import Taskflow
>>> ner = Taskflow("ner")
>>> ner("《孤女》是2010年九州出版社出版的小说，作者是余兼羽")
[('《', 'w'), ('孤女', '作品类_实体'), ('》', 'w'), ('是', '肯定词'), ('2010年', '时间类'), ('九州出版社', '组织机构类'), ('出版', '场景事件'), ('的', '助词'), ('小说', '作品类_概念'), ('，', 'w'), ('作者', '人物类_概念'), ('是', '肯定词'), ('余兼羽', '人物类_实体')]
```
