### ISSUE TITLE
[Bug]: TypeError: __init__() got an unexpected keyword argument 'vocab_size'

### ISSUE THREAD

**Issue by michelleqyhqyh** [PaddlePaddle/PaddleNLP#4819]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1.post112
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
But there is a bug:
/home/qyh/anaconda3/envs/py39/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/resources/qyh/big-model/PaddleNLP/model_zoo/gpt/run_eval.py", line 291, in <module>
    run()
  File "/resources/qyh/big-model/PaddleNLP/model_zoo/gpt/run_eval.py", line 287, in run
    do_eval(args)
  File "/resources/qyh/big-model/PaddleNLP/model_zoo/gpt/run_eval.py", line 231, in do_eval
    model = GPTForPretraining(GPTModel(**model_class.pretrained_init_configuration[args.model_name]))
  File "/home/qyh/.local/lib/python3.9/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'vocab_size'


How can I fix the issure?
```

### 稳定复现步骤 & 代码

I train with the following code:

CUDA_VISIBLE_DEVICES=7 python run_pretrain.py \
    --model_type gpt \
    --model_name_or_path gpt2-en \
    --input_dir "./data"\
    --output_dir "output"\
    --weight_decay 0.01\
    --grad_clip 1.0\
    --max_steps 500000\
    --save_steps 100000\
    --decay_steps 320000\
    --warmup_rate 0.01\
    --micro_batch_size 4\
    --device gpu

And eval with the following code:

CUDA_VISIBLE_DEVICES=6 python run_eval.py --model_name gpt2-en \
     --eval_path ./wikitext-103/wiki.valid.tokens \
     --overlapping_eval 32 \
     --init_checkpoint_path ./output/model_100000/model_state.pdparams \
     --batch_size 4 \
     --device gpu

**Comment by wj-Mcat** [comment]
这个已经在 https://github.com/PaddlePaddle/PaddleNLP/pull/4614  中解决了因 GPTConfig 升级导致的相关问题。

**Comment by wyqnumber** [comment]
降低版本，2.5版本的Config有问题
