### ISSUE TITLE
请问现在paddlenlp有能文本润色或文本风格转化的模型吗？

### ISSUE THREAD

**Issue by jiweizhangxu** [PaddlePaddle/PaddleNLP#4820]
### Feature request

如题，并且问一下taskflow的文本纠错功能是首次下载模型之后，完全可以离线运行对吗？如果文本风格转化有相关模型希望也能尽量首次下载模型后，之后能完全离线

### Motivation

希望能将一些模板化的报告，加些润色词或改变一些叙述风格来产生些变化

### Your contribution

无

**Comment by JunnYu** [comment]
对于问题1：回答是肯定的，完全可以离线运行，首次下载会将模型权重文件缓存到 `~/.paddlenlp` 的文件夹下面。
对于问题2：目前 PaddleNLP 不支持文本润色和文本风格转化的功能。
