### ISSUE TITLE
paddlenlp标注工具

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#4821]
### 请提出你的问题

目前paddlenlp能做到端到端，已经几乎90%。但是目前针对标注工具，paddlenlp还有一定不完善的地方。
目前主流的文本标注工具：labelstudio，doccano虽然已经较完备。但是缺少灵活的预标注，导出格式也多种多样。如果下面paddlenlp可以中心花一点在NLP标注工具上，增加一些模型预标注功能。这样就是不依赖外界，100%端到端了。

**Comment by guiniao** [comment]
你好，请问下labelstudio怎么标注整篇文章，类似doccano的textfile模式；还有doccano跨行标注可以吗，我一个实体，在doccano页面占据了两行，选择两行，但是标注不了，感谢

**Comment by JunnYu** [comment]
@tianchiguaixia 目前的话PaddleNLP是没有标注提升的工作计划的，您可以在主流的 labelstudio，doccano 标注工具上进行二次开发，增加您所需的功能
