### ISSUE TITLE
[Question]: ErnieFastTokenizer解码时中文之间额外的空格？

### ISSUE THREAD

**Issue by Chan-0312** [PaddlePaddle/PaddleNLP#4822]
### 请提出你的问题

ErnieFastTokenizer解码时中文之间额外的空格？

**Comment by JunnYu** [comment]
对于中文，您可以直接删除掉里面的空格。
因为最开始这些tokenizer是为了英文单词考虑的，比如："a dog is sleeping. "，如果不加空格，那就会连在一起了。
