### ISSUE TITLE
[Question]: UnifiedTransformer finetune使用自定义数据集训练报错

### ISSUE THREAD

**Issue by xu-peng-7** [PaddlePaddle/PaddleNLP#4833]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/21714c3797149f5283c9229313cb93fcb2c2d51a/examples/dialogue/unified_transformer/README.md

按照如教程所示训练自定义数据集时，报错：
![image](https://user-images.githubusercontent.com/49851465/219288581-12118b24-6a14-4dca-ada2-492c5e85a6c8.png)

其中自定义数据集主要函数如下：
返回关键字与示例数据集关键字相同
```
def read_data(data_path):
    data = pd.read_table(data_path, encoding = "utf-8",header=None )
    for i in range(data.shape[0]):
        info = data.iloc[i,0]
        info_dict = json.loads(info)
        sex = info_dict['title'][0]
        labels = info_dict['label']
        knows = knows_process(labels,sex)
        chats = chats_process(info_dict['chats'])
        goals = [['START', '目的' ,'心理咨询'], ['心理咨询', '主题', info_dict['title']]]

        yield {'goal': goals, 'knowledge': knows,'conversation': chats}
```

**Comment by FrostML** [comment]
UnifiedTransformer 的数据处理是根据 DuConv 来做的，如果自定义数据集可能需要将数据集的格式和 DuConv 调整成一致，或是需要自定义一个 Dataset 来载入。

**Comment by xu-peng-7** [comment]
您好，非常感谢您的回复，我尝试了这两种方法，第一种您指的格式除了K-V的形式外还有其他的内容吗，我已经和duconv的输出的三个关键字对齐了，但是报错内容如上。第二种，我定义了Dataset并使用MapDataset进行包装，报错内容如下：
```
    train_ds = MyDataset(path = 'train.txt')  # paddle.io.Dataset
    train_ds = MapDataset(train_ds)    # paddlenlp.datasets.MapDataset
```
![image](https://user-images.githubusercontent.com/49851465/219317085-3c0b25d0-2c40-4c36-9e05-42181750041c.png)
查了很多资料，该模型使用自定义数据集微调的好像没找到，希望您能针对报错解答疑惑。

**Comment by xu-peng-7** [comment]
我注意到，deconv的数据type为 <class 'datasets.arrow_dataset.Dataset'> ，但是paddlenlp的自定义数据教程中，定义Dataset都要求使用MapDataset进行包装，此时格式为 <class 'paddlenlp.datasets.dataset.MapDataset'>，请问该如何将数据type生成arrow_dataset.Dataset类型？

**Comment by JunnYu** [comment]
现在paddlenlp基本上全面使用hf的datasets了，想要了解如何使用，建议先参考datasets的文档。
你可以查看这里的代码，https://huggingface.co/datasets/PaddlePaddle/duconv/blob/main/duconv.py
```python
from datasets import load_dataset
data = load_dataset("duconv.py")
```

**Comment by xu-peng-7** [comment]
您好，我已经成功加载了自己的数据并实现了模型的训练，但在终端运行 **人机交互** 时，总会卡死。即使按照示例代码运行也会报错。
