### ISSUE TITLE
[Bug]: fast-tokenizer 1.0.1 在 windows上导入报错

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleNLP#4834]
### 软件环境

```Markdown
- paddlepaddle:2.4.1
- paddlenlp: 2.5.0
- fast-tokenizer-python-1.0.1
- windows11
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
报错如下图所示，但在fast-tokenizer-python-1.0.0中不会出现这个问题。
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/96160062/219296825-5f8416ea-e157-46e8-9181-7c0f2a2f7756.png)

![image](https://user-images.githubusercontent.com/96160062/219296931-93310da2-9531-4984-9896-0a963a5f40e7.png)

**Comment by joey12300** [comment]
@sanbuphy 您好，请试试 `pip install fast_tokenizer_python --upgrade`将 fast_tokenizer 更新到最新版本，然后再试试是否可以导入？

**Comment by sanbuphy** [comment]
> @sanbuphy 您好，请试试 `pip install fast_tokenizer_python --upgrade`将 fast_tokenizer 更新到最新版本，然后再试试是否可以导入？

你好，现在可以导入了，就是还是没有明显的性能差异或加速，甚至不开会快一点（linux上是有明显变快的，相同的代码
