### ISSUE TITLE
utc中提到的zero-shot-classification如何进行多阶段微调

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#4835]
### 请提出你的问题

请问如何实现zero-shot-classification多阶段微调？
比如有2份领域相似，但不同的训练集D1, D2;  先基于D1训练一个模型M1;   然后想在模型M1基础上，用数据集D2进行进一步微调得到最终的模型M2. 

根据https://github.com/PaddlePaddle/PaddleNLP/tree/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/applications/zero_shot_text_classification的说明，可以通过设置overwrite_output_dir参数和output_dir参数来实现： 如果 True，覆盖输出目录的内容。如果 output_dir 指向检查点目录，则使用它继续训练。  

不知是我理解错误了，还是训练参数设置正确。通过上述设置， 当用数据集D2来继续微调M1得到M2时，模型训练时没有看到代码中有加载M1的模型进行继续训练。

**Comment by LemonNoel** [comment]
这种情况需要使用 `resume_from_checkpoint` 参数指定上次保存的 checkpoint 目录并加载参数。`output_dir` 只决定当次训练的存储路径，`overwrite_output_dir`设置与否并不会影响模型参数的初始化，只决定是否在训练开始前删除已有的 `output_dir` 目录。

**Comment by leon-cas** [comment]
> 

谢谢，可以了
