### ISSUE TITLE
[Question]: 端到端检索式问答系统在访问paddle serving时总报错

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#4847]
### 请提出你的问题

我使用docker安装的paddle serving，并且根据文档https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system，逐步的搭建了问答系统，在最后访问paddle serving时总是报错：
执行命令：
curl -X POST -k http://localhost:9292/ernie/prediction -d '{"key": ["0"], "value": ["宁夏针对哪些人员开通工伤保障绿色通道?"]}
报错信息：
{"err_no":10000,"err_msg":"Log_id: 0  Raise_msg: future feature annotations is not defined (model_utils.py, line 14)  ClassName: Op._run_preprocess.\u003clocals\u003e.preprocess_help  FunctionName: preprocess_help","key":[],"value":[],"tensors":[]}
请问这个问题是啥原因引起的？着急中
说明：
1、python web_service.py，这个脚本启动是成功的：
![image](https://user-images.githubusercontent.com/102787771/219521772-abeabd2d-7d03-489d-9688-ff9f1e3fa37a.png)
2、paddlepaddle安装验证是安装成功的。
3、paddle serving采用docker的推荐方式安装，安装成功的：
![image](https://user-images.githubusercontent.com/102787771/219522072-fae29422-0168-467b-af3e-33e14c66d2a4.png)

**Comment by w5688414** [comment]
> 

具体的运行环境是啥，把环境发一下

**Comment by lichuantao6626** [comment]
paddle serving通过docker安装的，安装命令：
# 启动 CPU Docker
docker pull registry.baidubce.com/paddlepaddle/serving:0.9.0-devel
docker run -p 9292:9292 --name test_cpu -dit registry.baidubce.com/paddlepaddle/serving:0.9.0-devel bash
docker exec -it test_cpu bash
git clone https://github.com/PaddlePaddle/Serving

cd Serving
pip3 install -r python/requirements.txt

pip3 install paddle-serving-client==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip3 install paddle-serving-app==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

# CPU Server
pip3 install paddle-serving-server==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

# CPU环境请执行
pip3 install paddlepaddle==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

运行环境检查（检查结果正常，没报错）
python3 -m paddle_serving_server.serve check
参考文档：
paddle serving部署参考文档：
https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md
问答系统搭建参考的文档：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system
说明：目前跟问答系统搭建文档，一步步执行，前面的步骤都已经正常执行，现在卡在了paddle serving部署，成功启动完python web_service.py后，使用curl -X POST -k http://localhost:8090/ernie/prediction -d '{"key": ["0"], "value": ["宁夏针对哪些人员开通工伤保障绿色通道?"]}'发送请求报错。

**Comment by w5688414** [comment]
> paddle serving通过docker安装的，安装命令：
> 
> # 启动 CPU Docker
> docker pull registry.baidubce.com/paddlepaddle/serving:0.9.0-devel docker run -p 9292:9292 --name test_cpu -dit registry.baidubce.com/paddlepaddle/serving:0.9.0-devel bash docker exec -it test_cpu bash git clone https://github.com/PaddlePaddle/Serving
> 
> cd Serving pip3 install -r python/requirements.txt
> 
> pip3 install paddle-serving-client==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple pip3 install paddle-serving-app==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> # CPU Server
> pip3 install paddle-serving-server==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> # CPU环境请执行
> pip3 install paddlepaddle==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> 运行环境检查（检查结果正常，没报错） python3 -m paddle_serving_server.serve check 参考文档： paddle serving部署参考文档： https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md 问答系统搭建参考的文档： https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system 说明：目前跟问答系统搭建文档，一步步执行，前面的步骤都已经正常执行，现在卡在了paddle serving部署，成功启动完python web_service.py后，使用curl -X POST -k http://localhost:8090/ernie/prediction -d '{"key": ["0"], "value": ["宁夏针对哪些人员开通工伤保障绿色通道?"]}'发送请求报错。

paddle-serving 0.8或者0.7版本可以试一下，另外Paddle Serving后续不会支持了，可以尝试使用simple Serving或者fastDeploy。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md
https://github.com/PaddlePaddle/FastDeploy

**Comment by lichuantao6626** [comment]
paddle serving后期不更新了吗，以后模型部署工具使用那个比较好



| |
lichuantao6626
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月18日 14:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: 端到端检索式问答系统在访问paddle serving时总报错 (Issue #4847) |

paddle serving通过docker安装的，安装命令：

启动 CPU Docker

docker pull registry.baidubce.com/paddlepaddle/serving:0.9.0-devel docker run -p 9292:9292 --name test_cpu -dit registry.baidubce.com/paddlepaddle/serving:0.9.0-devel bash docker exec -it test_cpu bash git clone https://github.com/PaddlePaddle/Serving

cd Serving pip3 install -r python/requirements.txt

pip3 install paddle-serving-client==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple pip3 install paddle-serving-app==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

CPU Server

pip3 install paddle-serving-server==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

CPU环境请执行

pip3 install paddlepaddle==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple

运行环境检查（检查结果正常，没报错） python3 -m paddle_serving_server.serve check 参考文档： paddle serving部署参考文档： https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md 问答系统搭建参考的文档： https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system 说明：目前跟问答系统搭建文档，一步步执行，前面的步骤都已经正常执行，现在卡在了paddle serving部署，成功启动完python web_service.py后，使用curl -X POST -k http://localhost:8090/ernie/prediction -d '{"key": ["0"], "value": ["宁夏针对哪些人员开通工伤保障绿色通道?"]}'发送请求报错。

paddle-serving 0.8或者0.7版本可以试一下，另外Paddle Serving后续不会支持了，可以尝试使用simple Serving或者fastDeploy。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md
https://github.com/PaddlePaddle/FastDeploy

**Comment by w5688414** [comment]
> paddle serving后期不更新了吗，以后模型部署工具使用那个比较好 | | lichuantao6626 | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年02月18日 14:13 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: 端到端检索式问答系统在访问paddle serving时总报错 (Issue #4847) | paddle serving通过docker安装的，安装命令： 启动 CPU Docker docker pull registry.baidubce.com/paddlepaddle/serving:0.9.0-devel docker run -p 9292:9292 --name test_cpu -dit registry.baidubce.com/paddlepaddle/serving:0.9.0-devel bash docker exec -it test_cpu bash git clone https://github.com/PaddlePaddle/Serving cd Serving pip3 install -r python/requirements.txt pip3 install paddle-serving-client==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple pip3 install paddle-serving-app==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple CPU Server pip3 install paddle-serving-server==0.9.0 -i https://pypi.tuna.tsinghua.edu.cn/simple CPU环境请执行 pip3 install paddlepaddle==2.3.0 -i https://pypi.tuna.tsinghua.edu.cn/simple 运行环境检查（检查结果正常，没报错） python3 -m paddle_serving_server.serve check 参考文档： paddle serving部署参考文档： https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Install_CN.md 问答系统搭建参考的文档： https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system 说明：目前跟问答系统搭建文档，一步步执行，前面的步骤都已经正常执行，现在卡在了paddle serving部署，成功启动完python web_service.py后，使用curl -X POST -k http://localhost:8090/ernie/prediction -d '{"key": ["0"], "value": ["宁夏针对哪些人员开通工伤保障绿色通道?"]}'发送请求报错。 paddle-serving 0.8或者0.7版本可以试一下，另外Paddle Serving后续不会支持了，可以尝试使用simple Serving或者fastDeploy。 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md https://github.com/PaddlePaddle/FastDeploy — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

后面FastDeploy是重点支持的
