### ISSUE TITLE
[Question]: 使用SimpleServing部署UIE-X识别一张发票需要11-15秒，CPU推理有办法优化速度吗

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#4848]
### 请提出你的问题

paddle2.4.1
paddlenlp2.5.1
cpu内核14
只使用OCR几秒钟就能全部识别，在SimpleServing对UIE-X如何才能优化识别速度

**Comment by linjieccc** [comment]
@1061302569 有个封闭域文档抽取的工作正在进行中，可以缓解一部分性能问题，欢迎持续关注

**Comment by 1061302569** [comment]
> @1061302569 有个封闭域文档抽取的工作正在进行中，可以缓解一部分性能问题，欢迎持续关注

嗯嗯，谢谢老师百忙中回复我的问题，UIE-X的FastDeploy是不是要出来了

**Comment by linjieccc** [comment]
> > @1061302569 有个封闭域文档抽取的工作正在进行中，可以缓解一部分性能问题，欢迎持续关注
> 
> 嗯嗯，谢谢老师百忙中回复我的问题，UIE-X的FastDeploy是不是要出来了

是的，这部分工作也在计划中哈

**Comment by 1061302569** [comment]
> 有个封闭域文档抽取的工作正在进行中，可以缓解一部分性能问题

哈哈哈，期待中，听说很好用

**Comment by 1061302569** [comment]
> > > @1061302569 有个封闭域文档抽取的工作正在进行中，可以缓解一部分性能问题，欢迎持续关注
> > 
> > 
> > 嗯嗯，谢谢老师百忙中回复我的问题，UIE-X的FastDeploy是不是要出来了
> 
> 是的，这部分工作也在计划中哈

哈哈哈，期待中，听说很好用

**Comment by sijunhe** [comment]
UIE-X的抽取速度和schema长度直接相关，如果需要显著加速，可以尝试减少schema里的抽取类型数目
