### ISSUE TITLE
[Question]: 文本信息抽取功能，使用多块cpu训练报错问题。

### ISSUE THREAD

**Issue by fuqiang-benz** [PaddlePaddle/PaddleNLP#4853]
### 请提出你的问题

我使用的是 develop分支下：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text 文本信息抽取这个功能，paddlenlp=2.5.0 paddlepaddle= 2.4.1 ，使用分布式命令训练python -m paddle.distributed.launch --nproc_per_node=3 --backend=gloo ./finetune.py 在训练两批次后 然后报错
![ce4aeeb77256bb31e017b84214eebb5](https://user-images.githubusercontent.com/64388539/219557750-d1989baa-24ac-4e22-82cb-49f286b88e3b.png)
以下是我的训练数据
[dev.txt](https://github.com/PaddlePaddle/PaddleNLP/files/10763514/dev.txt)
[test.txt](https://github.com/PaddlePaddle/PaddleNLP/files/10763515/test.txt)
[train.txt](https://github.com/PaddlePaddle/PaddleNLP/files/10763516/train.txt)

**Comment by fuqiang-benz** [comment]
麻烦大佬帮忙看一下

**Comment by linjieccc** [comment]
增加一下dev.txt中的样本数量再试下呢
