### ISSUE TITLE
[Question]: 如何修改模型的默认下载路径？

### ISSUE THREAD

**Issue by Lix1993** [PaddlePaddle/PaddleNLP#4857]
### 请提出你的问题

在文档中，修改环境变量可以改：

![image](https://user-images.githubusercontent.com/12579295/219577491-6e9097f3-5fb4-4efe-b5e4-f4c0476b0002.png)

但是按照如下命令设置了之后，仍然在之前的默认位置

![image](https://user-images.githubusercontent.com/12579295/219578046-4f04417d-6cd6-4245-bdb2-30c06ba15a52.png)

请问应该怎么修改呢？

**Comment by sijunhe** [comment]
您好，当前develop版本（以及马上发的v2.5.1版本及以后）有了统一的cache_dir参数，可以直接在from_pretrained中使用，例子见https://github.com/PaddlePaddle/PaddleNLP/blob/e6a5a9f0541e6f038cb9329d0b4d85b081c92c0e/tests/transformers/test_modeling_utils.py#L44

**Comment by Lix1993** [comment]
hello,

[image: image.png]

那请问Taskflow需要怎么修改呢， 直接加cache_dir没有用

Best Regards,
Li Xing

**Comment by sijunhe** [comment]
> hello, [image: image.png] 那请问Taskflow需要怎么修改呢， 直接加cache_dir没有用 Best Regards, Li Xing

@linjieccc

**Comment by linjieccc** [comment]
@Lix1993 Taskflow中可以通过`home_path`自定义任务文件的保存路径

```python
from paddlenlp import Taskflow

ner = Taskflow("ner", home_path="/workspace")
```

**Comment by Lix1993** [comment]
thx
