### ISSUE TITLE
请问UIE-X是大模型吗？是基于ERNIE 3.0-Mini的大模型？

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#4858]
### 请提出你的问题

请问UIE-X是大模型吗？是基于ERNIE 3.0-Mini的大模型？

**Comment by linjieccc** [comment]
@zchengzhong 你好，UIE-X基于ERNIE-Layout跨模态模型，ERNIE-Layout的介绍可以参考[这里](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout)，对应的论文地址：https://arxiv.org/abs/2210.06155
