### ISSUE TITLE
[Bug]: doccano.py在导入utils.py中的str2bool报错

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/PaddleNLP#4859]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1.post112
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
ImportError: cannot import name 'str2bool' from 'utils' (/home/aistudio/uie/utils.py)
utils.py文件中不存在'str2bool'函数
```

### 稳定复现步骤 & 代码

python doccano.py \
    --doccano_file ./data/doccano_ext.json \
    --task_type ext \
    --save_dir ./data \
    --splits 0.8 0.2 0 \
    --schema_lang ch

**Comment by sijunhe** [comment]
您好 这个bug应该已经在 #4240 修复了，develop版本或者v2.5.1(即将发版）已经修复了
