### ISSUE TITLE
[Question]: UIE结果出现问题

### ISSUE THREAD

**Issue by yangzhenyu6** [PaddlePaddle/PaddleNLP#4860]
### 请提出你的问题

为啥会单个字得抽取，结果如下：
[{'仿生产品': [{'end': 79,
            'probability': 0.5842643820039086,
            'start': 78,
            'text': '有'},
           {'end': 2,
            'probability': 0.3209942311613645,
            'start': 1,
            'text': '着'},
           {'end': 11,
            'probability': 0.5061413888120398,
            'start': 10,
            'text': '叶'},
           {'end': 20,
            'probability': 0.6196562510040451,
            'start': 19,
            'text': '对'},
           {'end': 14,
            'probability': 0.603985967500531,
            'start': 13,
            'text': '用'},
           {'end': 21,
            'probability': 0.6422457955109167,
            'start': 20,
            'text': '其'},
           {'end': 37,
            'probability': 0.5217626457277618,
            'start': 36,
            'text': '竹'},
           {'end': 63,
            'probability': 0.5372188464861871,
            'start': 62,
            'text': '模'},
           {'end': 100,
            'probability': 0.5411281340592353,
            'start': 99,
            'text': '能'},
           {'end': 27,
            'probability': 0.4698596032226554,
            'start': 26,
            'text': '要'},
           {'end': 132,
            'probability': 0.48058674584902406,
            'start': 131,
            'text': '设'},
           {'end': 31,
            'probability': 0.4533180498063416,
            'start': 30,
            'text': '益'},
           {'end': 64,
            'probability': 0.5260664897370475,
            'start': 63,
            'text': '型'},
           {'end': 74,
            'probability': 0.4868258436701467,
            'start': 73,
            'text': '软'},
           {'end': 112,
            'probability': 0.6065022461451122,
            'start': 111,
            'text': '叶'},
           {'end': 45,
            'probability': 0.6027836973210867,
            'start': 44,
            'text': '出'},
           {'end': 4,
            'probability': 0.5211965976935389,
            'start': 3,
            'text': '用'}],
  '仿生模本': [{'end': 132,
            'probability': 0.4766075891903654,
            'start': 131,
            'text': '设'},
           {'end': 31,
            'probability': 0.44949586002537245,
            'start': 30,
            'text': '益'},
           {'end': 63,
            'probability': 0.5333878828426108,
            'start': 62,
            'text': '模'},
           {'end': 100,
            'probability': 0.5391079141082002,
            'start': 99,
            'text': '能'},
           {'end': 45,
            'probability': 0.6009696818520496,
            'start': 44,
            'text': '出'},
           {'end': 2,
            'probability': 0.3195237210128319,
            'start': 1,
            'text': '着'},
           {'end': 11,
            'probability': 0.5009840661685416,
            'start': 10,
            'text': '叶'},
           {'end': 79,
            'probability': 0.5812286468301409,
            'start': 78,
            'text': '有'},
           {'end': 4,
            'probability': 0.5184505597713951,
            'start': 3,
            'text': '用'},
           {'end': 64,
            'probability': 0.5227796006682439,
            'start': 63,
            'text': '型'},
           {'end': 74,
            'probability': 0.48175613316548294,
            'start': 73,
            'text': '软'},
           {'end': 21,
            'probability': 0.6389312979819763,
            'start': 20,
            'text': '其'},
           {'end': 112,
            'probability': 0.6039862041789945,
            'start': 111,
            'text': '叶'},
           {'end': 37,
            'probability': 0.5169679408346326,
            'start': 36,
            'text': '竹'},
           {'end': 20,
            'probability': 0.6155931859816519,
            'start': 19,
            'text': '对'},
           {'end': 14,
            'probability': 0.5997010382843797,
            'start': 13,
            'text': '用'}],
  '仿生特征': [{'end': 11,
            'probability': 0.5022521174844243,
            'start': 10,
            'text': '叶'},
           {'end': 132,
            'probability': 0.47799178289169575,
            'start': 131,
            'text': '设'},
           {'end': 100,
            'probability': 0.539542309734145,
            'start': 99,
            'text': '能'},
           {'end': 14,
            'probability': 0.6004968201910259,
            'start': 13,
            'text': '用'},
           {'end': 74,
            'probability': 0.4828131200641437,
            'start': 73,
            'text': '软'},
           {'end': 64,
            'probability': 0.5239655610305931,
            'start': 63,
            'text': '型'},
           {'end': 79,
            'probability': 0.5814616632074987,
            'start': 78,
            'text': '有'},
           {'end': 2,
            'probability': 0.3191238031558541,
            'start': 1,
            'text': '着'},
           {'end': 112,
            'probability': 0.6044316090747799,
            'start': 111,
            'text': '叶'},
           {'end': 4,
            'probability': 0.5190605297969171,
            'start': 3,
            'text': '用'},
           {'end': 45,
            'probability': 0.6011207362625086,
            'start': 44,
            'text': '出'},
           {'end': 20,
            'probability': 0.6173114368155019,
            'start': 19,
            'text': '对'},
           {'end': 37,
            'probability': 0.5182847385694416,
            'start': 36,
            'text': '竹'},
           {'end': 63,
            'probability': 0.5334719703554214,
            'start': 62,
            'text': '模'},
           {'end': 31,
            'probability': 0.45101384791819754,
            'start': 30,
            'text': '益'},
           {'end': 21,
            'probability': 0.6398721223380193,
            'start': 20,
            'text': '其'}],
  '研究方法': [{'end': 11,
            'probability': 0.5038058117976902,
            'start': 10,
            'text': '叶'},
           {'end': 37,
            'probability': 0.52090134059668,
            'start': 36,
            'text': '竹'},
           {'end': 14,
            'probability': 0.6027150908387355,
            'start': 13,
            'text': '用'},
           {'end': 4,
            'probability': 0.5199508994308673,
            'start': 3,
            'text': '用'},
           {'end': 31,
            'probability': 0.45401333836107227,
            'start': 30,
            'text': '益'},
           {'end': 20,
            'probability': 0.6190453836096879,
            'start': 19,
            'text': '对'},
           {'end': 74,
            'probability': 0.4865673478596051,
            'start': 73,
            'text': '软'},
           {'end': 100,
            'probability': 0.5410662841437954,
            'start': 99,
            'text': '能'},
           {'end': 63,
            'probability': 0.53700393865617,
            'start': 62,
            'text': '模'},
           {'end': 64,
            'probability': 0.5256918688764642,
            'start': 63,
            'text': '型'},
           {'end': 2,
            'probability': 0.3192984212841594,
            'start': 1,
            'text': '着'},
           {'end': 132,
            'probability': 0.48010620678675764,
            'start': 131,
            'text': '设'},
           {'end': 45,
            'probability': 0.602049563100131,
            'start': 44,
            'text': '出'},
           {'end': 79,
            'probability': 0.5833557684627095,
            'start': 78,
            'text': '有'},
           {'end': 21,
            'probability': 0.6412387469914904,
            'start': 20,
            'text': '其'},
           {'end': 112,
            'probability': 0.6064566615326115,
            'start': 111,
            'text': '叶'}]}]

**Comment by yangzhenyu6** [comment]
代码如下：uie模型是自己微调过的模型
`from pprint import pprint
from paddlenlp import Taskflow

schema = ['仿生产品', '仿生模本', '研究方法', '仿生特征']
few_ie = Taskflow('information_extraction', schema=schema, batch_size=1, task_path=r'C:\Users\Administrator\model')
pprint(few_ie("随着矿用轴流式风机长叶片使用日趋广泛,对其减振性能的要求也日益提高。模拟竹壁微观结构,提出了一种多孔阻尼结构,"
              "并建立了其数学模型。利用ABAQUS软件对某带有多孔阻尼结构的矿用轴流式风机叶片的阻尼性能进行了研究。结果表明,叶片的减振性能显著提高。可为高效阻尼结构设计及矿用轴流式风机叶片抑颤研究提供参考."))`

**Comment by linjieccc** [comment]
@yangzhenyu6 升级一下paddlenlp的版本，如果还有问题的话可以拉最新develop的代码重新微调试试

**Comment by jenfung** [comment]
请问一下你们微调要多久啊？我的checkpoint都到了9700还不停下来！
