### ISSUE TITLE
[Bug]: 特殊字符引起的分词报错

### ISSUE THREAD

**Issue by Agirljustsayhello** [PaddlePaddle/PaddleNLP#4863]
### 软件环境

```Markdown
paddlenlp                2.5.0
paddlepaddle             2.3.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
from paddlenlp import Taskflow
schema = ['情感倾向[正向，负向]']
senta = Taskflow("sentiment_analysis", model="uie-senta-mini", schema=schema)
print(senta('˃ʍ˂'))
tokenizer_utils.py报错：
token_mapping.append((char_mapping[start], char_mapping[end - 1] + 1))
   1340 return token_mapping
IndexError: list index out of range
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow
schema = ['情感倾向[正向，负向]']
senta = Taskflow("sentiment_analysis", model="uie-senta-mini", schema=schema)
print(senta('˃ʍ˂'))

**Comment by wj-Mcat** [comment]
tokenizer在遇到连续unk时目前确实没办法很好的解决offset mapping，因为这个信息应该在切词的时候完成的，hf就是这样做的。

不过为了支持这个功能，也可以写一套逻辑来解决，只是大概率offset mapping的结果与真实值有diff，也会引来新的问题。

@sijunhe 你怎么看呢
