### ISSUE TITLE
提高UIE-X对文档型图片的抽取

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#4866]
### Feature request

目前的UIE-X针对表格的图片抽取的效果很好。但是针对文档型的图片抽取的效果不是很好。例如：我想抽取既往史，现病史等大段文本时候，发现总是抽取的不是很完整。后期针对文档型图片，UIE-X会做相关算法和文本逻辑处理的优化？

现实中，这样的场景还是很多的，比如：病历实体提取，基金公告提取，投标书提取，合同提取等等
![image](https://user-images.githubusercontent.com/29837553/219608231-f509df5d-accb-4558-bac5-6083961a7621.png)

### Motivation

目的就是为了让UIE-X适用的领域更广，目前UIE-X还是主流在表格，表单等相对结构的图片。现实中长文本的图片也很多，如果新增这些领域，UIE-X将光芒万丈。

### Your contribution

目前我的模型使用UIE-X的，后期是否团队可以在代码逻辑优化一下，来处理长文本。

**Comment by xxllp** [comment]
这个是因为uie 模型抽取长文本(段落)的会效果不佳。

**Comment by tianchiguaixia** [comment]
而且我也测试了，抽取图片里面疾病的实体，发现效果也不是很高。这一块是否后期会优化一下
