### ISSUE TITLE
[Bug]:  Taskflow 开启版面分析(layout_analysis)总联网下载layout模型

### ISSUE THREAD

**Issue by zirui** [PaddlePaddle/PaddleNLP#4870]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.0.post111
- paddlenlp: 2.5.0
- npaddleocr   2.6.1.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Taskflow 开启layout分析时(layout_analysis=True)
paddle总会从互联网上下载picodet_lcnet_x1_0_fgd_layout_cdla_infer模型，即使默认模型目录已经存在
https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
```

### 稳定复现步骤 & 代码

```
uie = Taskflow(
        "information_extraction",
        model="uie-x-base",
        task_path="/xx/uie-x-base",
        schema=schema,
        from_hf_hb=False,
        layout_analysis=True
)
```

跟踪了下代码，发现paddleocr会check默认模型目录下是否存在`inference.pdiparams` 和`inference.pdmodel`
而实际上官网模型picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar中根本就没有这两个文件:
picodet_lcnet_x1_0_fgd_layout_cdla_infer:
```
infer_cfg.yml
model.pdmodel
model.pdiparams
model.pdiparams.info
```

**Comment by linjieccc** [comment]
@zirui 你好，如果是手动下载的话可以尝试下手动修改文件名为`inference.xxx`，关于文件名不一致的问题也可以在PaddleOCR提个issue https://github.com/PaddlePaddle/PaddleOCR/issues

**Comment by zirui** [comment]
> @zirui 你好，如果是手动下载的话可以尝试下手动修改文件名为`inference.xxx`，关于文件名不一致的问题也可以在PaddleOCR提个issue https://github.com/PaddlePaddle/PaddleOCR/issues

我的机器是离线的环境，下载模型后手动copy到paddleocr默认目录，发现总出这个问题。 然后通过修改paddleocr入口代码(paddleocr.py)，不让下载layout模型就可以跑起来了。 你说的修改模型文件也是一种方法. 
因此问题已经临时解决，提这个issue是为了反馈bug。


为了方便使用, 我建议:
1.  允许用户传参指定模型路径(OCR我看代码中部分模型可以， 如det、rec、cls等模型有入口参数)

**Comment by linjieccc** [comment]
非常感谢你的建议~我们计划下个版本在DocParser中增加更多关于OCR、版面分析定制模型的接口，来支持定制模型的加载
