### ISSUE TITLE
[Question]: How to train Ernie-Layout on multi-page documents?

### ISSUE THREAD

**Issue by JP-Leite** [PaddlePaddle/PaddleNLP#4872]
### 请提出你的问题

This is related to [4662](https://github.com/PaddlePaddle/PaddleNLP/issues/4662).

What would be the most optimal way to train multi-page documents on the MRC task? Within the [dataset_hf](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py) script there is some mention of page_no but can you provide guidance on what the dataset should look like to leverage that? Is it possible to train Ernie-Layout with multipage documents or is it best to split the documents into individual pages and provide question and answers only associated to that page?

Then for inference, there does not seem to be any mention of page_no, so are we to run each page of the multi-page image thru individually? If that is the case, any guidance on outputing confidence % for answers coming from the MRC inference so we can consolidate and present the best scored answer for a question across multiple pages?

**Comment by linjieccc** [comment]
@JP-Leite Hi,

Thanks for your interest on ERNIE-Layout!

In both fine-tuning and inference, ``page_no`` is not used. Each page is treated as an individual one, you can refer code here
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py#L124

**Comment by JP-Leite** [comment]
> @JP-Leite Hi,
> 
> Thanks for your interest on ERNIE-Layout!
> 
> In both fine-tuning and inference, `page_no` is not used. Each page is treated as an individual one, you can refer code here https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/datasets/hf_datasets/docvqa_zh.py#L124

Thank you for the reply! So if a question is answered on multiple pages, is there a confidence % that we can access to determine which result is best across multiple pages?

**Comment by JP-Leite** [comment]
Following up on this, it seems like we can pass in multiple pages and questions associated with each page into the infer.py script for Ernie-Layout while not effect running times by much:

``` if args.task_type == "mrc":
        args.questions = [
            [
                "What is the Name",
                "What is the Member ID Number?",
            ],
            [
                "What is the Name",
                "What is the Member ID Number?",
            ],
        ]
        docs = ["./images/InsuranceCard2.png","./images/InsuranceCard1.png"]
```

I would like to do something similar for the DocPrompt pipeline since DocPrompt provides confidence % associated with answers out of the box, while the infer.py does not for question answering.

Seems like within the document_intelligence.py, we are building a list of predicitions and passing in a list of examples which is similar to the infer.py:

```
    def run(self, example: dict):
        results = self._run_model([example])
        output = {"results": results}
        return output, "output_1"

  def _run_model(self, inputs: List[dict]):
        """
        Run docprompt model.
        """
        all_predictions_list = []
        for example in inputs:
            ocr_result = example["ocr_result"]
            doc_path = example["doc"]
            prompt = example["prompt"]
            ocr_type = example["ocr_type"]
```

Would we just need to modify standard_pipeline.py to accept a list of meta instead of just a single meta:

```
class DocPipeline(BaseStandardPipeline):
    def run(self, meta: dict, params: Optional[dict] = None, debug: Optional[bool] = None):
        output = self.pipeline.run(meta=meta, params=params, debug=debug)
        return output
```

This would be useful for processing multi-page tiffs or converted PDFs
