### ISSUE TITLE
[Question]: How can I train ERNIE Layout on multiple GPU's?

### ISSUE THREAD

**Issue by waynemystir** [PaddlePaddle/PaddleNLP#4873]
### 请提出你的问题

I tried various approaches after looking around and wasn't successful. The property training_args.world_size is always 1.

**Comment by sijunhe** [comment]
What multi-GPU strategy are you using? If you are just thinking of plain data parallel(DP), it should work out of the box by using our [Trainer](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/trainer.py#L139) and launching with a command like this `unset CUDA_VISIBLE_DEVICES python -m paddle.distributed.launch --gpus 0,1 train.py \`

**Comment by waynemystir** [comment]
Thanks @sijunhe . I want to use DDP.

**Comment by waynemystir** [comment]
Please review when you have time @sijunhe and @ZHUI 
Thank you

**Comment by sijunhe** [comment]
@waynemystir If you using our `paddlenlp.trainer.Trainer`, the only thing you need to do is to start the training script with `unset CUDA_VISIBLE_DEVICES python -m paddle.distributed.launch --gpus 0,1 train.py`. If you are not using our `Trainer`, you can wrap the model instance with `model = paddle.DataParallel(model)` (see [example](https://github.com/PaddlePaddle/PaddleNLP/blob/3ae3ea533584d0135813fb95410216495faf9d98/examples/question_generation/t5/train.py#L147)) and then launch it with `distributed.launch`
