### ISSUE TITLE
`tests/taskflow/test_feature_extraction` is too slow for unit tests

### ISSUE THREAD

**Issue by sijunhe** [PaddlePaddle/PaddleNLP#4874]
### 问题描述

`PaddlePaddle/ernie_vil-2.0-base-zh` is too large of a model to be used in unit tests, as the model download takes too long and is prone to failure. Consider creating and uploading a tiny random ernie-vil model under 5MB (e.g. `__internal_testing__/tiny-random-ernie`) with very small num_layers, num_attention_heads and hidden_size and use that for unit tests.

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/4881
