### ISSUE TITLE
[Question]: uie-base 和 uie-nano 的使用问题

### ISSUE THREAD

**Issue by Isfate** [PaddlePaddle/PaddleNLP#4876]
### 请提出你的问题

我的环境是 paddlenlp2.5.0
GPU是3090
我在分别对两种不同模型进行压力测试的时候, 他们的并发量相差过大
但是在之前我进行测试的时候并没有这么大的差距, 我的nano模型及base模型都是使用paddlenlp2.3.4版本训练的, 在之前的测试中两种模型的并发差距大概是10%-20%, 但是这次的差距就达到了600% (base-51tps; nano-310tps)
我想问这个正常么

**Comment by wawltor** [comment]
我理解正常情况nano模型及base模型的性能差异是非常大的，不应该是10%~20%的性能差别，现在差距就达到了600%反而是正常的情况。

**Comment by Isfate** [comment]
好的, 感谢你的解答
