### ISSUE TITLE
[Question]: faq_system政务问答系统的train.csv无监督训练集与test_pair.csv、corpus.csv、qa_pair.csv三个数据集之间存在什么关系

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/PaddleNLP#4885]
### 请提出你的问题

根据https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_system官方指导文档，基本已经搭建完成问答系统，现在想造一点自己的数据，然后用自己的数据训练模型，经过分析，不知道train.csv无监督训练集的生成规则，对train.csv于另外三个数据集（test_pair.csv、corpus.csv、qa_pair.csv）之间的关系还是不太清楚。

请问，哪位大神能说明一下这几个文件的构造规则吗？

**Comment by w5688414** [comment]
test_pair.csv是测试集合
corpus.csv 是模拟的整个召回库
qa_pair.csv是原始的问答对。

FAQ问答的测试就是用test_pair.csv的句子1，在corpus.csv里面去检索，看能否把test_pair.csv的句子2检索出来。

**Comment by lichuantao6626** [comment]
疑问一：
train.csv这个训练集合一般依据那些规则进行构造的数据，我发现train.csv里面的问题再其他三个文件里面都没有。
疑问二：
使用train.csv训练模型的主要作用是什么？（有没有相关的资料详细介绍的推荐一下）
