### ISSUE TITLE
请问ppdiffusers下个版本会支持ControlNet 

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#4888]
### 简要描述

生成内容可控

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

https://huggingface.co/lllyasviel/ControlNet

**Comment by JunnYu** [comment]
@yanchaoguo 你好，预计0.12.0的版本会增加`ControlNet`的，请耐心等待！

**Comment by yanchaoguo** [comment]
> @yanchaoguo 你好，预计0.12.0的版本会增加`ControlNet`的，请耐心等待！

目前哪里可以看到ppdiffusers支持的所有模型列表

**Comment by yanchaoguo** [comment]
> @yanchaoguo 你好，预计0.12.0的版本会增加`ControlNet`的，请耐心等待！

都3月了 请问这个版本啥时候发布 @JunnYu

**Comment by JunnYu** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/5009 您可以先关注使用一下这个PR
