### ISSUE TITLE
[Question]: 加载预训练模型作为参数传递失败

### ISSUE THREAD

**Issue by ZhaoyingAC** [PaddlePaddle/PaddleNLP#4889]
### 请提出你的问题

1. 根据config加载预训练self.ernie = ErnieModel(config)
2. 将步骤1中的ernie作为参数传递赋值 self.ernie = ernie
报错 "Some weights of ** were not initialized from the model checkpoint at **"
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
然后卡住了，这种情况应该怎么处理

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 1. 根据config加载预训练self.ernie = ErnieModel(config)
> 2. 将步骤1中的ernie作为参数传递赋值 self.ernie = ernie
>    报错 "Some weights of ** were not initialized from the model checkpoint at **"
>    You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
>    然后卡住了，这种情况应该怎么处理

能提供一下复现的PaddleNLP的版本和具体的代码吗？
