### ISSUE TITLE
[Question]: 文本摘要使用默认模型，摘要结果过短怎么解决

### ISSUE THREAD

**Issue by Guolbj** [PaddlePaddle/PaddleNLP#4899]
### 请提出你的问题

您好，使用默认模型 IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese 摘要结果过短有什么入参可以改善摘要结果过短的问题，代码如下：

**Comment by Guolbj** [comment]
from paddlenlp import Taskflow
from paddlenlp import SimpleServer


uie = Taskflow("text_summarization",min_length=30)
app = SimpleServer()
app.register_taskflow('taskflow/uie', uie)

**Comment by gongel** [comment]
你好，设置min_length=30，生成的最短长度应该就在30

**Comment by Guolbj** [comment]
因为不设置这个长度，默认配置的结果比这个30还短，有什么办法可以调长这个结果。

示例：
文本内容：据微信公众号“界面”报道，4日上午10点左右，中国发改委反垄断调查小组突击查访奔驰上海办事处，调取数据材料，并对多名奔驰高管进行了约谈。截止昨日晚9点，包括北京梅赛德斯-奔驰销售服务有限公司东区总经理在内的多名管理人员仍留在上海办公室内
默认配置摘要结果：北上广深奔驰高管集体被约谈
设置最短长度为30的结果：北上广深奔驰高管集体被约谈，多名管理人员仍在上海办公室内（附名单）| 视频光明网(组图)

然后配置了最短长度的话，摘要结果会硬凑几个词来补充

**Comment by gongel** [comment]
可以尝试更换解码策略看看：decode_strategy="sampling"，temperature、top_k、top_p可以做相应的调整

**Comment by Guolbj** [comment]
您好，这个默认模型的摘要结果应该是标题，有没有推荐模型做文本摘要，类似于新闻摘要

**Comment by gongel** [comment]
可以参考这里训练一个新闻的：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/finetune

**Comment by liuwei92** [comment]
增加了min_lenth

> 因为不设置这个长度，默认配置的结果比这个30还短，有什么办法可以调长这个结果。
> 
> 示例： 文本内容：据微信公众号“界面”报道，4日上午10点左右，中国发改委反垄断调查小组突击查访奔驰上海办事处，调取数据材料，并对多名奔驰高管进行了约谈。截止昨日晚9点，包括北京梅赛德斯-奔驰销售服务有限公司东区总经理在内的多名管理人员仍留在上海办公室内 默认配置摘要结果：北上广深奔驰高管集体被约谈 设置最短长度为30的结果：北上广深奔驰高管集体被约谈，多名管理人员仍在上海办公室内（附名单）| 视频光明网(组图)
> 
> 然后配置了最短长度的话，摘要结果会硬凑几个词来补充

这个有什么好的解决办法吗，硬凑补充词语
