### ISSUE TITLE
Taskflow文图生成加载模型失败

### ISSUE THREAD

**Issue by Gaia-Wu** [PaddlePaddle/PaddleNLP#4901]
### 请提出你的问题

三行代码体验 Stable Diffusion时报错，nlp新手，不知该如何解决

报错提示如下：
![图片](https://user-images.githubusercontent.com/94101986/220234542-2026d57e-e71d-4835-a89b-9445af6cfa26.png)

**Comment by JunnYu** [comment]
哈喽，主readme里面的文图生成教程将要废弃，
- 如果您有本地机器的话，您可以使用这里代码体验StableDiffusion模型
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers#%E6%96%87%E5%9B%BE%E7%94%9F%E6%88%90-text-to-image-generation
- 当然也可以体验这里的Aistudio项目 https://aistudio.baidu.com/aistudio/projectdetail/4905623?channelType=0&channel=0

**Comment by Gaia-Wu** [comment]
> 

好的我明白了，非常感谢
