### ISSUE TITLE
`model_zoo/bert`预训练问题

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/PaddleNLP#4904]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/create_pretraining_data.py
246行的max_num_tokens是否应该改成target_seq_length，毕竟183行有一定几率缩短最大长度
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/bert/create_pretraining_data.py

**Comment by sijunhe** [comment]
@doubleguy 看一下

**Comment by doubleguy** [comment]
已在该PR中修复：https://github.com/PaddlePaddle/PaddleNLP/pull/4851/files

**Comment by doubleguy** [comment]
> 

已在该PR中修复：https://github.com/PaddlePaddle/PaddleNLP/pull/4851/files
