### ISSUE TITLE
[Question]: 对于摘要的这个预训练大模型更改配置来替换模型时，会报出错误

### ISSUE THREAD

**Issue by liruixue** [PaddlePaddle/PaddleNLP#4907]
### 请提出你的问题

对于摘要的这个预训练大模型 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/pretrain

文档说这里的默认model是可替换，但并没有指出如何替换。如果我需要将IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese这个模型替换为另一个Randeng-Pegasus的模型（比如：PaddlePaddle/Randeng-Pegasus-523M-Summary-Chinese-SSTIA），更改配置后并不能正确加载模型，错误显示为：
```
AssertionError: The models name: PaddlePaddle/Randeng-Pegasus-523M-Summary-Chinese-SSTIA is not in task:[text_summarization]
```
当前的运行环境为：
pip list|grep  paddle
```
paddle-bfloat        0.1.2
paddle2onnx          1.0.0
paddlefsl            1.1.0
paddlehub            1.5.0
paddlenlp            2.5.1
paddlepaddle-gpu     2.3.0.post101
tb-paddle            0.3.6
```
请帮忙解决下，如何才能正确使用百度官方支持的其他模型来替换IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese这个模型？谢谢

**Comment by gongel** [comment]
你好，taskflow加载生态模型可以先这么使用
```python
summarizer = Taskflow("text_summarization", task_path='PaddlePaddle/Randeng-Pegasus-523M-Summary-Chinese-SSTIA')
```

**Comment by liruixue** [comment]
嗯，试了下PaddlePaddle/Randeng-Pegasus-523M-Summary-Chinese-SSTIA模型可以加载运行成功，不过根据结果看Randeng-Pegasus-523M-Summary-Chinese-SSTIA和Randeng-Pegasus-523M-Summary-Chinese模型的运行结果看起来是一致的，比如：下面这句
···
'这里也不能不提到程心，她的选择是整个三体3黑暗森林的骨架，而大刘也一再强调程心的母性，她的责任感等等，可是读者仍然没办法读懂程心的价值观。不像章北海，他虽然在隐藏自己的真实价值观，可读者仍然有蛛丝马迹可循，会感觉到他的真实。而程心则像是一个被主角光环包围的任性公主，整个世界最重要的事情不断围绕她发生，她也不断地搞砸事情然后让全太阳系买单，这样的情节持续一遍又一遍后，我不仅要怀疑大刘是为了推动剧情不得不加入程心这样一个角色，而不是因为有了这样的角色所以将剧情像这样推动。'
···
出来的summary是'《三体》:29集'，很奇怪的一个摘要，而huggingface上IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1这个模型效果要比这俩模型的结果好出一头来，请官方大大能考虑下能够支持到IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1这个新模型，期待~

**Comment by gongel** [comment]
好的，感谢反馈哈，我们近期支持下。
