### ISSUE TITLE
[Question]: 在cpu上使用taskflow进行ner运行时间过长，有没有办法加速？

### ISSUE THREAD

**Issue by lzjjeff** [PaddlePaddle/PaddleNLP#4908]
我在cpu上用taskflow做ner，长度1000的文本耗时约2分钟，请问目前有在cpu上加速的方法吗？

**Comment by wawltor** [comment]
目前在Taskflow的NER任务已经做了MKLDNN和多核加速，如果速度还是不够用的话，可以尝试使用GPU加速或者更多核的机器

**Comment by lzjjeff** [comment]
> 目前在Taskflow的NER任务已经做了MKLDNN和多核加速，如果速度还是不够用的话，可以尝试使用GPU加速或者更多核的机器

好的，感谢～
