### ISSUE TITLE
[Question]: AltDiffusionPipeline模型报错

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#4909]
### 请提出你的问题

pipe = AltDiffusionPipeline.from_pretrained("BAAI/AltDiffusion", paddle_dtype=paddle.float16 )
设置了dtype=paddle.float16后运行text to image 会报下面的错误
![image](https://user-images.githubusercontent.com/11827802/220277416-be6218ed-2d3d-423a-a89f-4970c34feb32.png)

**Comment by JunnYu** [comment]
@yanchaoguo 您好，当前需要配合下面的代码使用，未来paddlepaddle下个版本就无需这样了
```python
pipe = AltDiffusionPipeline.from_pretrained("BAAI/AltDiffusion", paddle_dtype=paddle.float16 )
with paddle.amp.auto_cast(True, level='O2'):
    image = pipe(xxxxxxxx)
```
