### ISSUE TITLE
[Question]: 使用UIE进行调整后发现速度过慢

### ISSUE THREAD

**Issue by yutong12** [PaddlePaddle/PaddleNLP#4911]
### 请提出你的问题

使用uie-base做识别时发现速度很慢，我有一个大的字符串(约在两千字到四千字左右)，使用GPU调用时耗时在一秒到三秒左右，由于客户现场限制，我们尝试使用CPU进行推理，推理耗时普遍在十秒以上，请问有何种方式能够帮助我们优化推理耗时？
ps:换用其他的小模型试验后发现效果不佳，没有base的效果好

**Comment by wawltor** [comment]
可以提供一下你的GPU型号，或者你是否打开了float16加速的选项？

**Comment by yutong12** [comment]
GPU为Tesla T4 没有打开float16选项

**Comment by yutong12** [comment]
GPU型号为Tesla T4 没有打开float16
我想确认的是有没有能在CPU环境下进行推理加速的？现在实测大概只使用了一半的CPU资源(TOP命令显示CPU使用量百分之五十)，2G的内存资源，我感觉资源没有被充分吃掉

**Comment by yutong12** [comment]
增加batch-size后内存占用上升，时间消耗减小一秒左右，但仍不能满足需求

**Comment by linjieccc** [comment]
@yutong12 你好，你用的是默认模型还是微调后的呢？

**Comment by wawltor** [comment]
> 增加batch-size后内存占用上升，时间消耗减小一秒左右，但仍不能满足需求

我们测试过，50% cpu利用率的时候是预测速度最佳的状态，能有的办法还是推荐使用medium模型，之前的经验medium的模型的效果只要多增加点数据，效果是和base模型一致

**Comment by yutong12** [comment]
@linjieccc 微调后的

**Comment by yutong12** [comment]
也就是使用medium模型，在这个基础上多增加数据是吧 了解了

**Comment by xxllp** [comment]
我觉得你可以尝试下onnx模型

**Comment by wawltor** [comment]
> 也就是使用medium模型，在这个基础上多增加数据是吧 了解了

是的

**Comment by yutong12** [comment]
感谢大家，paddle的静态图做部署应用后，准确率和速度都上去了，现在的速度和精确度都达到了一个满意的状态，后续可能会利用部署侧将静态图模型转成onnx在边缘侧部署了，这样可能会更加快(不过没有试验过，而且这个项目应该到现在这一步就完结了)，非常感谢！

**Comment by xxllp** [comment]
> 感谢大家，paddle的静态图做部署应用后，准确率和速度都上去了，现在的速度和精确度都达到了一个满意的状态，后续可能会利用部署侧将静态图模型转成onnx在边缘侧部署了，这样可能会更加快(不过没有试验过，而且这个项目应该到现在这一步就完结了)，非常感谢！

静态图下速度如何

**Comment by yutong12** [comment]
tag为四个至五个时，一篇两千五百字的内容，处理时间在三秒至四秒左右，但有点奇怪的是，部署flaskapi后，一句话从调用到返回整理时间都在0.9s左右，这里还不太懂
