### ISSUE TITLE
fast_generation问题

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#4926]
### 请提出你的问题

fast_generation中libdecoding_op.so每种模型是不同的还是相同的

**Comment by gongel** [comment]
是同一个so，编译的时候可以选择模型去打开加速开关：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/CMakeLists.txt#L29-L47

**Comment by ZTurboX** [comment]
unimo-text示例中的run_gen.py和infer_utils.py适用于gpt吗

**Comment by gongel** [comment]
需要改动，直接支持不行

**Comment by ZTurboX** [comment]
> 需要改动，直接支持不行

对于文本续写任务，unimo和gpt2哪个效果好点

**Comment by gongel** [comment]
> > 需要改动，直接支持不行
> 
> 对于文本续写任务，unimo和gpt2哪个效果好点

这个暂无结论，可以自己多尝试看看。
