### ISSUE TITLE
【PaddlePaddle Hackathon 第四期】NLP、AIGC 赛题合集，欢迎报名！

### ISSUE THREAD

**Issue by chenxiaozeng** [PaddlePaddle/PaddleNLP#4931]
### 问题描述

大家好，非常高兴地告诉大家，第四期 [PaddlePaddle Hackathon](https://www.paddlepaddle.org.cn/PaddlePaddleHackathon-2023-2) 开始了。PaddlePaddle Hackathon 是面向全球开发者的深度学习领域编程活动，鼓励开发者了解与参与 PaddlePaddle 开源社区。本次共有四个赛道：核心框架开源贡献、模型套件开源贡献、生态伙伴开源贡献、产业合作开源贡献。欢迎大家前往 [任务总览页](https://github.com/PaddlePaddle/Paddle/issues/50629) 了解活动详情，报名参赛。

对于熟悉 PaddleNLP 的小伙伴，推荐大家重点关注如下赛题，快来选择自己感兴趣的题目吧。可在本issue下讨论相关赛题。

**自然语言处理模型库 PaddleNLP**<a name='nlp'></a>

| 序号 | 难度 | 任务 ISSUE                                                   | 
| ---- | ---- | ------------------------------------------------------------ | 
| 98   | ⭐️    | [升级paddlenlp.transformers内的模型结构并且增加基础单测](https://github.com/PaddlePaddle/Paddle/issues/50631#task98) |  等等天黑(报名)([PaddleNLP](http://github.com/ZwhElliott/PaddleNLP)) </br>自动AC机(报名)([PaddleNLP](http://github.com/robinbg/PaddleNLP))               |          |
| 99   | ⭐️    | [升级paddlenlp.transformers内的模型结构并且增加基础单测](https://github.com/PaddlePaddle/Paddle/issues/50631#task99) |   自动AC机(报名)([PaddleNLP](http://github.com/robinbg/PaddleNLP))         |          |
| 100  | ⭐️    | [升级paddlenlp.transformers内的模型结构并且增加基础单测](https://github.com/PaddlePaddle/Paddle/issues/50631#task100) |  自动AC机(报名)([PaddleNLP](http://github.com/robinbg/PaddleNLP))                 |          |
| 101  | ⭐️    | [升级paddlenlp.transformers内的模型结构并且增加基础单测](https://github.com/PaddlePaddle/Paddle/issues/50631#task101) |   自动AC机(报名)([PaddleNLP](http://github.com/robinbg/PaddleNLP))                |          |
| 102  | ⭐️    | [给AutoConverter增加新的模型组网的支持](https://github.com/PaddlePaddle/Paddle/issues/50631#task102) |                  |          |
| 103  | ⭐️    | [新增tie_weights能力](https://github.com/PaddlePaddle/Paddle/issues/50631#task103) |                  |          |
| 104  | ⭐️    | [生成式API对齐HF，包括sample和contrastive_search](https://github.com/PaddlePaddle/Paddle/issues/50631#task104) |                  |          |
| 105  | ⭐    | [基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型](https://github.com/PaddlePaddle/Paddle/issues/50631#task105) |                  |          |
| 106  | ⭐️⭐️   | [论文名称：Attend-and-Excite: Attention-Based Semantic Guidance for Text-to-Image Diffusion](https://github.com/PaddlePaddle/Paddle/issues/50631#task106) |                  |          |
| 107  | ⭐️⭐️   | [论文名称：Plug-and-Play Diffusion Features for Text-Driven Image-to-Image Translation](https://github.com/PaddlePaddle/Paddle/issues/50631#task107) |                  |          |
| 108  | ⭐️⭐️   | [论文名称：AudioLDM: Text-to-Audio Generation with Latent Diffusion Models](https://github.com/PaddlePaddle/Paddle/issues/50631#task108) |                  |          |
| 109  | ⭐️⭐️   | [论文名称：Zero-shot Image-to-Image Translation](https://github.com/PaddlePaddle/Paddle/issues/50631#task109) |                  |          |
| 110  | ⭐️    | [论文名称：Multi-Concept Customization of Text-to-Image Diffusion](https://github.com/PaddlePaddle/Paddle/issues/50631#task110) |                  |          |
| 111  | ⭐️⭐️   | [论文名称：DeBERTa: Decoding-enhanced BERT with Disentangled Attention](https://github.com/PaddlePaddle/Paddle/issues/50631#task111) |                  |          |
| 237  | ⭐️    | [基于PaddleNLP的跨模态文档信息抽取](https://github.com/PaddlePaddle/Paddle/issues/50633#task237) |  可爱修狗(报名)([Cross-modal-Document-Information-Extraction](http://github.com/Yu-xm/Cross-modal-Document-Information-Extraction))                |          |

**Comment by fuqianya** [comment]
hello @chenxiaozeng, 好像这期的论文复现题目需要发送简历到指定邮箱，通过筛选后锁定题目，在飞桨导师的指导下完成复现。我昨天发送了邮件，目前还未收到反馈～

**Comment by crwsr124** [comment]
@chenxiaozeng 请问下，"基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型"这个不需要报名，提交作品就行，对吧？

**Comment by chenxiaozeng** [comment]
> @chenxiaozeng 请问下，"基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型"这个不需要报名，提交作品就行，对吧？

是的，不需要报名，直接提交即可，因为这道题目是创意赛，大家的作品互相pk。提交规范和地址请查看105题目详情，欢迎参与！

**Comment by chenxiaozeng** [comment]
> hello @chenxiaozeng, 好像这期的论文复现题目需要发送简历到指定邮箱，通过筛选后锁定题目，在飞桨导师的指导下完成复现。我昨天发送了邮件，目前还未收到反馈～

论文复现类题目确实是需要发送简历的，本周相关工作人员会回复邮件，还请耐心等待一下，欢迎参与！
