### ISSUE TITLE
[Question]: 请问UIE标注一个实体可以被标记为多个标签吗

### ISSUE THREAD

**Issue by SuFIND** [PaddlePaddle/PaddleNLP#4932]
### 请提出你的问题

如题比如：
我有一段语料
```
...
0：请问地址在哪里？

1：奥帆公园这边，有两个人被困在电梯里。
^ ------------ 主题：地点----------^
^----------主题：人员被困 ---------^
...
```
如果我把一段对话作为实体进行抽取，UIE支持把“奥帆...”那段对话作为同时两个类别实体抽取出来吗

**Comment by LemonNoel** [comment]
标注微调后可以实现。

**Comment by SuFIND** [comment]
> 标注微调后可以实现。

感谢回复，我发现问题中错别字太多了不好意思，我想表达的意思是：推理时是支持同时将“1：奥帆公园这边，有两个人被困在电梯里。”同时推理为“主题：地点”和"主题：人员被困“两类的实体的对吗？因为我大概尝试了300条左右的数据基于uie-medium进行微调但是看到的都是单一标签的情况

**Comment by linjieccc** [comment]
请问是想对 『奥帆公园这边，有两个人被困在电梯里』这句话进行主题分类吗？同时属于 『主题：地点』和『主题：人员被困』两个类别？

**Comment by SuFIND** [comment]
> 

分类任务我搜索了下issue可以支持多标签，但是我觉得我的任务应该是序列标注，因为例子中我只是截取了对话中的一小部分对话，实际上前后还有很多对话，原先我希望一长段中的对话中的部分对话进行序列标注，给予他们一些主题标签，比如同时具备两个主题——地点与人员被困

**Comment by SuFIND** [comment]
> 请问是想对 『奥帆公园这边，有两个人被困在电梯里』这句话进行主题分类吗？同时属于 『主题：地点』和『主题：人员被困』两个类别？

分类任务我搜索了下issue可以支持多标签，但是我觉得我的任务应该是序列标注，因为例子中我只是截取了对话中的一小部分对话，实际上前后还有很多对话，原先我希望一长段中的对话中的部分对话进行序列标注，给予他们一些主题标签，比如同时具备两个主题——地点与人员被困

**Comment by SuFIND** [comment]
很感谢两位的回复，但在实验中未能发现产出同一段文字标记为多类实体的样例，关闭问题。如果有朋友发现可行的话，请踢踢我3Q
