### ISSUE TITLE
[Bug]: uie-m系列模型不能使用 

### ISSUE THREAD

**Issue by wn1652400018** [PaddlePaddle/PaddleNLP#4935]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
uie-m系列模型不能使用 
uie = Taskflow('information_extraction', 'uie-m-base', device_id=-1, schema=['店名', '品牌名'])


FileNotFoundError: [Errno 2] No such file or directory: '.paddlenlp\\taskflow\\information_extraction\\uie-m-large\\config.json'
```

### 稳定复现步骤 & 代码

uie = Taskflow('information_extraction', 'uie-m-base', device_id=-1, schema=['店名', '品牌名'])

**Comment by LemonNoel** [comment]
请将 paddlenlp 升级到最新版本 2.5.1，删除 ~\\.paddlenlp\taskflow\information_extraction 目录下的缓存后再尝试，我这边测试可以正常使用。
