### ISSUE TITLE
paddlenlp.prompt里面的InputExample类怎么没有？

### ISSUE THREAD

**Issue by kevinuserdd** [PaddlePaddle/PaddleNLP#4942]
### 请提出你的问题

paddlenlp.prompt里面的InputExample类怎么没有？

**Comment by kevinuserdd** [comment]
检查了下，现在项目里面的prompt_utils.py里面的确没有这个类

**Comment by LemonNoel** [comment]
请问是运行代码时有报错吗？还是希望支持这个类？

**Comment by kevinuserdd** [comment]
> 请问是运行代码时有报错吗？还是希望支持这个类？

你们之前是有InputExample这个类的啊，肯定要需要这个类，我搜索了下没找到哪个文件下有。 这个类不是prompt模板构造前的数据格式吗？ 麻烦检查下

**Comment by LemonNoel** [comment]
当前版本已经删除了这个类别限制，直接构造为dict即可。如果运行的是之前的代码，可以将分支切换到相应版本查看代码。
