### ISSUE TITLE
[Question]: document_intelligence模型通过simplesever部署，client端的请求方式

### ISSUE THREAD

**Issue by zirui** [PaddlePaddle/PaddleNLP#4944]
### 请提出你的问题

如题:

server.py:
```python
di = Taskflow(
        "document_intelligence",
        device_id=3,
        from_hf_hb=False,
)
app = SimpleServer()
app.register_taskflow('taskflow/di', di)
```
```bash
paddlenlp server server:app --workers 1 --host 0.0.0.0 --port 8188
```
client.py:

```python
import requests
url = "http://0.0.0.0:8188/taskflow/di"
headers = {"Content-Type": "application/json"}
r = requests.post(url=url, headers=headers, data=json.dumps(data))
```

尝试了如下3种请求方式, 均失败

1.
```json
 [{"doc": "base64_str", "prompt": ["q1", "q2"]}]
```

2.
```json
{"data":  [{"doc": "base64_str", "prompt": ["q1", "q2"]}]}
```
3.
```json
{"data": {"text": [{"doc": "base64_str", "prompt": ["q1", "q2"]}]}}
```

1. 出错：`{"detail":[{"loc":["body","data"],"msg":"field required","type":"value_error.missing"},{"loc":["body","doc"],"msg":"extra fields not permitted","type":"value_error.extra"}]}`
3. 返回 {"result":{}}
2. 出错： `服务Internal Server Error`

输入图片在本机加载模型测试有数据结果的
请问正确的传参方式是怎样的， 在文档中只找到了uie/uie-x的client示例代码

**Comment by linjieccc** [comment]
@zirui 你好，docprompt目前还不支持base64的输入格式，可以尝试本地路径或http link

```python
doc_path = "./data/b1.jpg"

{"data": {"text": [{"doc": doc_path, "prompt": ["q1", "q2"]}]}}
```

**Comment by zirui** [comment]
> @zirui 你好，docprompt目前还不支持base64的输入格式，可以尝试本地路径或http link
> 
> ```python
> doc_path = "./data/b1.jpg"
> 
> {"data": {"text": [{"doc": doc_path, "prompt": ["q1", "q2"]}]}}
> ```
改成本地路径好使！ 多谢！
 建议文档里加个使用说明
