### ISSUE TITLE
[Question]: [AAAI2023]usm的统一信息抽取方法，啥时候放出来？

### ISSUE THREAD

**Issue by feng-1985** [PaddlePaddle/PaddleNLP#4950]
### 请提出你的问题

如题

**Comment by wawltor** [comment]
目前基于USM的UIE_v2目前还没有计划开源，我们基于USM方法实现的文本分类UTC，您可以参考实现一下  https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/zero_shot_text_classification
