### ISSUE TITLE
我在一台笔记本上训练的模型 checkpoint目录移动到另一台电脑上用Taskflow调用的预测结果。label 中文是乱码的

### ISSUE THREAD

**Issue by szy833** [PaddlePaddle/PaddleNLP#4951]
### 请提出你的问题

我在一台笔记本上训练的模型 checkpoint目录移动到另一台电脑上用Taskflow调用的预测结果。label 中文是乱码的

**Comment by wawltor** [comment]
建议检查一下两个电脑下的系统编码是否一致

**Comment by szy833** [comment]
> 建议检查一下两个电脑下的系统编码是否一致
<img width="292" alt="企业微信截图_16771201112427" src="https://user-images.githubusercontent.com/31844882/220810211-53680999-c185-4410-9c69-05f92e1468a3.png">
两个电脑的编码都是936 GBK编码。

**Comment by wawltor** [comment]
可以尝试把label字段转码成utf-8试试

**Comment by szy833** [comment]
> 可以尝试把label字段转码成utf-8试试
对返回结果的label转程utf-8确实可以，但是为什么会出现这种情况？因为在训练的本地电脑上是正常的。应在在训练结果保存之前做什么操作吗？

**Comment by szy833** [comment]
> 可以尝试把label字段转码成utf-8试试

对返回结果的label转程utf-8确实可以，但是为什么会出现这种情况？因为在训练的本地电脑上是正常的。应在在训练结果保存之前做什么操作吗？

**Comment by wawltor** [comment]
> > 可以尝试把label字段转码成utf-8试试
> 
> 对返回结果的label转程utf-8确实可以，但是为什么会出现这种情况？因为在训练的本地电脑上是正常的。应在在训练结果保存之前做什么操作吗？

这个可能是你的terminal的编码有关系
