### ISSUE TITLE
请问uie的观点评论抽取可以针对已知的实体抽取吗

### ISSUE THREAD

**Issue by songsa1** [PaddlePaddle/PaddleNLP#4964]
### Feature request

![image](https://user-images.githubusercontent.com/42863413/220870263-86895aa9-48c0-438e-bdee-41bf77a5cd2c.png)
比如这个例子，抽出了性价比高，店面干净，但是我的前一个任务已知了我这句话中所需要的实体，请问可以根据我提供的实体来抽取观点词和极性判断吗

### Motivation

如上所述

### Your contribution

如上所述

**Comment by songsa1** [comment]
请解答，不胜感激

**Comment by linjieccc** [comment]
@songsa1 Hi，这个可能需要结合实际场景对UIE进行标注及模型定制。有一种方案，可以尝试下对评价维度这类标签进一步细化，例如商品类评价维度、人物类评价维度等，再与对应的实体标签例如商品实体、人物实体进行绑定

**Comment by linjieccc** [comment]
@songsa1 你好，

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis/unified_sentiment_extraction#412-%E5%B1%9E%E6%80%A7%E7%BA%A7%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90
可以看下这里属性级情感分析中固定属性的功能

<img width="979" alt="image" src="https://user-images.githubusercontent.com/40840292/220920997-e70b7832-6bfb-46a9-8d4a-691ae94719d0.png">

**Comment by songsa1** [comment]
好的 谢谢您的及时解答
