### ISSUE TITLE
[Question]: 运行 applications\question_answering\supervised_qa\faq_finance\deploy\python\web_service.py报错

### ISSUE THREAD

**Issue by evanweiguohua** [PaddlePaddle/PaddleNLP#4965]
### 请提出你的问题

环境如下：
CentOS Linux release 8.2.2004 (Core)
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
---------------------------------------------------------------
Name: paddle-serving-server
Version: 0.3.0
Summary: Paddle Serving Package for saved model with PaddlePaddle
Home-page: https://github.com/PaddlePaddle/Serving
Author: PaddlePaddle Autho
----------------------------------------------------------------
错误：File "web_service.py", line 17, in <module>
    from paddle_serving_server.web_service import Op, WebService
ImportError: cannot import name 'Op' from 'paddle_serving_server.web_service' (/usr/local/src/paddlenlpS/.env/lib/python3.8/site-packages/paddle_serving_server/web_service.py)

**Comment by w5688414** [comment]
请试试重新安装paddle serving。

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/supervised_qa/faq_finance#paddle-serving-%E9%83%A8%E7%BD%B2

**Comment by evanweiguohua** [comment]
感谢，问题已经解决了。
