### ISSUE TITLE
UTC任务引入外部知识

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PaddleNLP#4966]
### Feature request

如何引入一些外部的已知知识来帮助分类，比如让其能先训练一些专业领域的文章啥的。或者我还看了你们提示学习的例子，但例子给了一个二分类情感分类的例子，不是很适合多分类，能否提供个多分类的提示学习的例子供参考。

### Motivation

我们之前使用zero_shot_text_classification效果很好，我们的样本集体量只有400多条，分6类，准确率能达到80%左右。通过对错误分类的观察，我们发现其多我们所使用的专业场景中的一些特定的关系没有学习到，比如出现特定词大概率都会分到某一类，但这种关系并不通用语言中出现，而是在比较专业的领域中才会有相关关系。

### Your contribution

我刚接触NLP，之前并没有太多了解，只了解过大概原理和浏览过相关文章，比如某些文章中提出可以融入知识图谱，但对具体如何实现不是很了解。https://zhuanlan.zhihu.com/p/156898885

**Comment by wawltor** [comment]
整体上样本量是够的，可以针对分类错误的case进行分析，主要是有一下两种方法
1）脏数据，例如本来是科技类新闻被标注成娱乐类的样本，可以做一些重新标注的工作
2）稀疏数据，『比如出现特定词大概率都会分到某一类』 可以增加跟这类词相关的样本应该就能提升效果
