### ISSUE TITLE
[Question]: paddlenlp+pipelines语义检索系统，使用图片更新索引的时候报错

### ISSUE THREAD

**Issue by huangbo-bo** [PaddlePaddle/PaddleNLP#4968]
### 请提出你的问题

使用图片更新索引的时候报错了

**执行脚本**
python3 utils/offline_ann.py --index_name dureader_robust_query_encoder --doc_dir data/dureader_dev/jpg --port 9200 --search_engine elastic --delete_index

**报错**
INFO - pipelines.utils.preprocessing -  Converting data/dureader_dev/jpg/images_0.png
[2023/02/23 21:29:23] ppocr DEBUG: dt_boxes num : 5, elapse : 0.5434155464172363
[2023/02/23 21:29:23] ppocr DEBUG: cls num  : 5, elapse : 0.056862592697143555
[2023/02/23 21:29:24] ppocr DEBUG: rec_res num  : 5, elapse : 1.634822130203247
Traceback (most recent call last):
  File "utils/offline_ann.py", line 125, in <module>
    offline_ann(args.index_name, args.doc_dir)
  File "utils/offline_ann.py", line 69, in offline_ann
    dicts = convert_files_to_dicts(
  File "/usr/local/lib/python3.8/dist-packages/pipelines/utils/preprocessing.py", line 75, in convert_files_to_dicts
    list_documents = suffix2converter[suffix].convert(
  File "/usr/local/lib/python3.8/dist-packages/pipelines/nodes/file_converter/image.py", line 94, in convert
    pages = self._image_to_text(file_path)
  File "/usr/local/lib/python3.8/dist-packages/pipelines/nodes/file_converter/image.py", line 142, in _image_to_text
    texts = [''.join(texts)]
TypeError: sequence item 0: expected str instance, list found

**环境**
系统：Linux version 5.4.0-100-generic (buildd@lcy02-amd64-002) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
python：3.8.10

Package                        Version
------------------------------ --------------------
aiofiles                       23.1.0
aiohttp                        3.8.4
aiosignal                      1.3.1
altair                         4.2.2
anyio                          3.6.2
astor                          0.8.1
async-timeout                  4.0.2
attrdict                       2.0.1
attrs                          19.3.0
Automat                        0.8.0
Babel                          2.11.0
backports.zoneinfo             0.2.1
bce-python-sdk                 0.8.79
beautifulsoup4                 4.11.2
blinker                        1.4
Brotli                         1.0.9
cachetools                     5.3.0
certifi                        2019.11.28
cffi                           1.15.1
chardet                        3.0.4
charset-normalizer             3.0.1
click                          8.0.0
cloud-init                     19.1
colorama                       0.4.3
colorlog                       6.7.0
command-not-found              0.3
configobj                      5.0.6
constantly                     15.1.0
contourpy                      1.0.7
cryptography                   39.0.1
cssselect                      1.2.0
cssutils                       2.6.0
cycler                         0.11.0
Cython                         0.29.33
datasets                       2.10.0
dbus-python                    1.2.16
decorator                      5.1.1
dill                           0.3.4
distro                         1.4.0
distro-info                    0.23ubuntu1
elasticsearch                  7.10.0
entrypoints                    0.3
et-xmlfile                     1.1.0
faiss-cpu                      1.7.3
fastapi                        0.92.0
ffmpy                          0.3.0
filelock                       3.9.0
fire                           0.5.0
Flask                          2.2.3
Flask-Babel                    2.0.0
fonttools                      4.38.0
frozenlist                     1.3.3
fsspec                         2023.1.0
future                         0.18.3
gevent                         22.10.2
geventhttpclient               2.0.2
gitdb                          4.0.10
GitPython                      3.1.31
gradio                         3.19.1
greenlet                       2.0.2
grpcio                         1.47.2
grpcio-tools                   1.47.2
h11                            0.14.0
htbuilder                      0.6.1
httpcore                       0.16.3
httplib2                       0.14.0
httpx                          0.23.3
huggingface-hub                0.12.1
hyperlink                      19.0.0
idna                           2.8
imageio                        2.25.1
imgaug                         0.4.0
importlib-metadata             6.0.0
importlib-resources            5.4.0
incremental                    16.10.1
itsdangerous                   2.1.2
jieba                          0.42.1
Jinja2                         3.1.2
joblib                         1.2.0
jsonpatch                      1.32
jsonpointer                    2.2
jsonschema                     4.4.0
keyring                        18.0.1
kiwisolver                     1.4.4
langdetect                     1.0.9
language-selector              0.1
launchpadlib                   1.10.13
lazr.restfulclient             0.14.2
lazr.uri                       1.0.3
llvmlite                       0.39.1
lmdb                           1.4.0
lxml                           4.9.2
Markdown                       3.4.1
markdown-it-py                 2.2.0
MarkupSafe                     2.1.2
matplotlib                     3.7.0
mdit-py-plugins                0.3.3
mdurl                          0.1.2
mmh3                           3.0.0
more-itertools                 9.0.0
mpmath                         1.2.1
multidict                      6.0.4
multiprocess                   0.70.12.2
netifaces                      0.10.4
networkx                       3.0
nltk                           3.8.1
numba                          0.56.4
numpy                          1.23.5
oauthlib                       3.1.0
onnx                           1.13.1
opencv-contrib-python          4.6.0.66
opencv-contrib-python-headless 4.7.0.72
opencv-python                  4.6.0.66
openpyxl                       3.1.1
opt-einsum                     3.3.0
orjson                         3.8.6
packaging                      23.0
paddle-bfloat                  0.1.7
paddle-pipelines               0.4.0
paddle2onnx                    1.0.5
paddlefsl                      1.1.0
paddlenlp                      2.5.1
paddleocr                      2.6.1.3
paddlepaddle                   2.4.1
pandas                         1.5.3
pdf2docx                       0.5.6
pdfminer.six                   20221105
pdfplumber                     0.8.0
pexpect                        4.6.0
Pillow                         9.4.0
pip                            23.0.1
premailer                      3.10.0
protobuf                       3.20.2
psutil                         5.9.4
pyarrow                        11.0.0
pyasn1                         0.4.2
pyasn1-modules                 0.2.1
pyclipper                      1.3.0.post4
pycparser                      2.21
pycryptodome                   3.17
pydantic                       1.10.5
pydeck                         0.8.0
pydub                          0.25.1
Pygments                       2.14.0
PyGObject                      3.36.0
PyHamcrest                     1.9.0
PyJWT                          1.7.1
pymacaroons                    0.13.0
pymilvus                       2.2.2
Pympler                        1.0.1
PyMuPDF                        1.19.0
PyNaCl                         1.3.0
pyOpenSSL                      23.0.0
pyparsing                      3.0.9
pyrsistent                     0.18.1
python-apt                     2.0.0+ubuntu0.20.4.7
python-dateutil                2.8.2
python-debian                  0.1.36ubuntu1
python-docx                    0.8.11
python-multipart               0.0.5
python-rapidjson               1.9
pytz                           2022.7.1
pytz-deprecation-shim          0.1.0.post0
PyWavelets                     1.4.1
PyYAML                         5.3.1
rapidfuzz                      2.13.7
rarfile                        4.0
regex                          2022.10.31
requests                       2.22.0
requests-unixsocket            0.2.0
responses                      0.18.0
rfc3986                        1.5.0
rich                           13.3.1
scikit-image                   0.19.3
scikit-learn                   1.2.1
scipy                          1.10.1
SecretStorage                  2.3.1
semver                         2.13.0
sentencepiece                  0.1.97
seqeval                        1.2.2
service-identity               18.1.0
setuptools                     45.2.0
shapely                        2.0.1
simplejson                     3.16.0
six                            1.14.0
smmap                          5.0.0
sniffio                        1.3.0
sos                            4.2
soupsieve                      2.4
SQLAlchemy                     1.4.46
SQLAlchemy-Utils               0.40.0
ssh-import-id                  5.10
st-annotated-text              3.0.0
starlette                      0.25.0
streamlit                      1.9.0
sympy                          1.11.1
systemd-python                 234
termcolor                      2.2.0
threadpoolctl                  3.1.0
tifffile                       2023.2.3
toml                           0.10.2
toolz                          0.12.0
tornado                        6.2
tqdm                           4.64.1
tritonclient                   2.30.0
Twisted                        18.9.0
typer                          0.7.0
typing_extensions              4.5.0
tzdata                         2022.7
tzlocal                        4.2
ubuntu-advantage-tools         27.6
ufw                            0.36
ujson                          5.4.0
unattended-upgrades            0.1
urllib3                        1.26.14
uvicorn                        0.20.0
validators                     0.20.0
visualdl                       2.4.2
wadllib                        1.3.3
Wand                           0.6.11
watchdog                       2.2.1
websockets                     10.4
Werkzeug                       2.2.3
wheel                          0.34.2
wordcloud                      1.8.2.2
x2paddle                       1.4.0
xxhash                         3.2.0
yarl                           1.8.2
zipp                           3.7.0
zope.event                     4.6
zope.interface                 4.7.1

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 使用图片更新索引的时候报错了
> 
> **执行脚本** python3 utils/offline_ann.py --index_name dureader_robust_query_encoder --doc_dir data/dureader_dev/jpg --port 9200 --search_engine elastic --delete_index
> 
> **报错** INFO - pipelines.utils.preprocessing - Converting data/dureader_dev/jpg/images_0.png [2023/02/23 21:29:23] ppocr DEBUG: dt_boxes num : 5, elapse : 0.5434155464172363 [2023/02/23 21:29:23] ppocr DEBUG: cls num : 5, elapse : 0.056862592697143555 [2023/02/23 21:29:24] ppocr DEBUG: rec_res num : 5, elapse : 1.634822130203247 Traceback (most recent call last): File "utils/offline_ann.py", line 125, in offline_ann(args.index_name, args.doc_dir) File "utils/offline_ann.py", line 69, in offline_ann dicts = convert_files_to_dicts( File "/usr/local/lib/python3.8/dist-packages/pipelines/utils/preprocessing.py", line 75, in convert_files_to_dicts list_documents = suffix2converter[suffix].convert( File "/usr/local/lib/python3.8/dist-packages/pipelines/nodes/file_converter/image.py", line 94, in convert pages = self._image_to_text(file_path) File "/usr/local/lib/python3.8/dist-packages/pipelines/nodes/file_converter/image.py", line 142, in _image_to_text texts = [''.join(texts)] TypeError: sequence item 0: expected str instance, list found
> 
> **环境** 系统：Linux version 5.4.0-100-generic (buildd@lcy02-amd64-002) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 python：3.8.10
> 
> Package Version
> 
> aiofiles 23.1.0 aiohttp 3.8.4 aiosignal 1.3.1 altair 4.2.2 anyio 3.6.2 astor 0.8.1 async-timeout 4.0.2 attrdict 2.0.1 attrs 19.3.0 Automat 0.8.0 Babel 2.11.0 backports.zoneinfo 0.2.1 bce-python-sdk 0.8.79 beautifulsoup4 4.11.2 blinker 1.4 Brotli 1.0.9 cachetools 5.3.0 certifi 2019.11.28 cffi 1.15.1 chardet 3.0.4 charset-normalizer 3.0.1 click 8.0.0 cloud-init 19.1 colorama 0.4.3 colorlog 6.7.0 command-not-found 0.3 configobj 5.0.6 constantly 15.1.0 contourpy 1.0.7 cryptography 39.0.1 cssselect 1.2.0 cssutils 2.6.0 cycler 0.11.0 Cython 0.29.33 datasets 2.10.0 dbus-python 1.2.16 decorator 5.1.1 dill 0.3.4 distro 1.4.0 distro-info 0.23ubuntu1 elasticsearch 7.10.0 entrypoints 0.3 et-xmlfile 1.1.0 faiss-cpu 1.7.3 fastapi 0.92.0 ffmpy 0.3.0 filelock 3.9.0 fire 0.5.0 Flask 2.2.3 Flask-Babel 2.0.0 fonttools 4.38.0 frozenlist 1.3.3 fsspec 2023.1.0 future 0.18.3 gevent 22.10.2 geventhttpclient 2.0.2 gitdb 4.0.10 GitPython 3.1.31 gradio 3.19.1 greenlet 2.0.2 grpcio 1.47.2 grpcio-tools 1.47.2 h11 0.14.0 htbuilder 0.6.1 httpcore 0.16.3 httplib2 0.14.0 httpx 0.23.3 huggingface-hub 0.12.1 hyperlink 19.0.0 idna 2.8 imageio 2.25.1 imgaug 0.4.0 importlib-metadata 6.0.0 importlib-resources 5.4.0 incremental 16.10.1 itsdangerous 2.1.2 jieba 0.42.1 Jinja2 3.1.2 joblib 1.2.0 jsonpatch 1.32 jsonpointer 2.2 jsonschema 4.4.0 keyring 18.0.1 kiwisolver 1.4.4 langdetect 1.0.9 language-selector 0.1 launchpadlib 1.10.13 lazr.restfulclient 0.14.2 lazr.uri 1.0.3 llvmlite 0.39.1 lmdb 1.4.0 lxml 4.9.2 Markdown 3.4.1 markdown-it-py 2.2.0 MarkupSafe 2.1.2 matplotlib 3.7.0 mdit-py-plugins 0.3.3 mdurl 0.1.2 mmh3 3.0.0 more-itertools 9.0.0 mpmath 1.2.1 multidict 6.0.4 multiprocess 0.70.12.2 netifaces 0.10.4 networkx 3.0 nltk 3.8.1 numba 0.56.4 numpy 1.23.5 oauthlib 3.1.0 onnx 1.13.1 opencv-contrib-python 4.6.0.66 opencv-contrib-python-headless 4.7.0.72 opencv-python 4.6.0.66 openpyxl 3.1.1 opt-einsum 3.3.0 orjson 3.8.6 packaging 23.0 paddle-bfloat 0.1.7 paddle-pipelines 0.4.0 paddle2onnx 1.0.5 paddlefsl 1.1.0 paddlenlp 2.5.1 paddleocr 2.6.1.3 paddlepaddle 2.4.1 pandas 1.5.3 pdf2docx 0.5.6 pdfminer.six 20221105 pdfplumber 0.8.0 pexpect 4.6.0 Pillow 9.4.0 pip 23.0.1 premailer 3.10.0 protobuf 3.20.2 psutil 5.9.4 pyarrow 11.0.0 pyasn1 0.4.2 pyasn1-modules 0.2.1 pyclipper 1.3.0.post4 pycparser 2.21 pycryptodome 3.17 pydantic 1.10.5 pydeck 0.8.0 pydub 0.25.1 Pygments 2.14.0 PyGObject 3.36.0 PyHamcrest 1.9.0 PyJWT 1.7.1 pymacaroons 0.13.0 pymilvus 2.2.2 Pympler 1.0.1 PyMuPDF 1.19.0 PyNaCl 1.3.0 pyOpenSSL 23.0.0 pyparsing 3.0.9 pyrsistent 0.18.1 python-apt 2.0.0+ubuntu0.20.4.7 python-dateutil 2.8.2 python-debian 0.1.36ubuntu1 python-docx 0.8.11 python-multipart 0.0.5 python-rapidjson 1.9 pytz 2022.7.1 pytz-deprecation-shim 0.1.0.post0 PyWavelets 1.4.1 PyYAML 5.3.1 rapidfuzz 2.13.7 rarfile 4.0 regex 2022.10.31 requests 2.22.0 requests-unixsocket 0.2.0 responses 0.18.0 rfc3986 1.5.0 rich 13.3.1 scikit-image 0.19.3 scikit-learn 1.2.1 scipy 1.10.1 SecretStorage 2.3.1 semver 2.13.0 sentencepiece 0.1.97 seqeval 1.2.2 service-identity 18.1.0 setuptools 45.2.0 shapely 2.0.1 simplejson 3.16.0 six 1.14.0 smmap 5.0.0 sniffio 1.3.0 sos 4.2 soupsieve 2.4 SQLAlchemy 1.4.46 SQLAlchemy-Utils 0.40.0 ssh-import-id 5.10 st-annotated-text 3.0.0 starlette 0.25.0 streamlit 1.9.0 sympy 1.11.1 systemd-python 234 termcolor 2.2.0 threadpoolctl 3.1.0 tifffile 2023.2.3 toml 0.10.2 toolz 0.12.0 tornado 6.2 tqdm 4.64.1 tritonclient 2.30.0 Twisted 18.9.0 typer 0.7.0 typing_extensions 4.5.0 tzdata 2022.7 tzlocal 4.2 ubuntu-advantage-tools 27.6 ufw 0.36 ujson 5.4.0 unattended-upgrades 0.1 urllib3 1.26.14 uvicorn 0.20.0 validators 0.20.0 visualdl 2.4.2 wadllib 1.3.3 Wand 0.6.11 watchdog 2.2.1 websockets 10.4 Werkzeug 2.2.3 wheel 0.34.2 wordcloud 1.8.2.2 x2paddle 1.4.0 xxhash 3.2.0 yarl 1.8.2 zipp 3.7.0 zope.event 4.6 zope.interface 4.7.1

请问您有示例图片吗？我测试一下
