### ISSUE TITLE
text_classification/multi_class/few-shot的label.txt支持类目多别名吗？

### ISSUE THREAD

**Issue by zbmain** [PaddlePaddle/PaddleNLP#4969]
### 请提出你的问题

applications/text_classification/multi_class/few-shot
![image](https://user-images.githubusercontent.com/52638096/221070395-3a8d2bcd-4ad5-48fd-a167-01a4bac1a98a.png)

请问下，这里是否支持多个类目标签映射词？
比如：beverage==饮料==酒水

**Comment by LemonNoel** [comment]
可以的，直接分开映射即可，读取的时候会合并
```
beverage==饮料
beverage==酒水
```
