### ISSUE TITLE
[Question]:  运行 applications\question_answering\supervised_qa\faq_finance 出现问题

### ISSUE THREAD

**Issue by evanweiguohua** [PaddlePaddle/PaddleNLP#4978]
### 请提出你的问题

你好！
按照部署模式，已经安装 pip install paddle-serving-server==0.8.3 pip install paddle-serving-client==0.8.3 pip install paddle-serving-app==0.8.3

到了pymilvus 这边，就会出现grpcio, grpcio-tools，在 paddle-serving-server里要求的版本<=1.33.2,但是 pymilvus==2.0.0RC这边，版本会要求grpcio, grpcio-tools >= 1.37.2

这种循环版本冲突请问怎么解决，我查了下清华源paddle-serving-server最高也就是0.9.0，grpcio, grpcio-tools依然是<= 1.33.2的

**Comment by evanweiguohua** [comment]
补充一下，pymilvus版本再往下降到1.1.x，倒是可以解决这个冲突，但是milvus_ann_search.py已经是无法运行了。

**Comment by w5688414** [comment]
冲突那个可以忽略，faq-finance的milvus用的是2.1，所以milvus的版本必须是2.1才可以
