### ISSUE TITLE
[Question]: 层次分类的底层实现是转换成多标签来实现的么？

### ISSUE THREAD

**Issue by AHNU** [PaddlePaddle/PaddleNLP#4983]
### 请提出你的问题

层次分类模型里有采用标签的层级特征么，是将层次分类任务退化成多标签任务然后加了个后处理将层级关系映射上面的么？还是最底层的模型结构有区别？
![image](https://user-images.githubusercontent.com/27804219/221111886-86e73ce4-42c4-46f4-97ee-fb12e42969f7.png)

**Comment by lugimzzz** [comment]
就是多标签

**Comment by AHNU** [comment]
您发送的邮件已经收到，我会尽快给您答复！
