### ISSUE TITLE
[Question]: In_batch_negative策略问题

### ISSUE THREAD

**Issue by kg-nlp** [PaddlePaddle/PaddleNLP#4993]
### 请提出你的问题

(https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class)/retrieval_based/
在用语义索引解决分类问题时,在一个batch内如果有多条样本的label相同,那使用in_batch_negative策略是错误的吧(分类标签数量相对少很多,一个batch内很容易出现相同标签的数据)

**Comment by w5688414** [comment]
> 

对的，这种适合标签数量多的情况，标签数量比较少的情况，不建议用这种方法，另一种改进的方法就是使用检索的方法构造负样本，特别构造强负样本。
