### ISSUE TITLE
[Question]: 文本层次分类（小样本）跑源码的时候报错

### ISSUE THREAD

**Issue by teensilenc** [PaddlePaddle/PaddleNLP#5000]
### 请提出你的问题

在AI STUDIO中，并且下载了最新版本的PaddleNLP-develop\applications\text_classification\hierarchical\few-shot\infer.py
读取JSON文件抛出异常JSONDecodeError
![image](https://user-images.githubusercontent.com/120088435/221364874-181eed7f-17d7-43ef-9eea-fdb0958961ae.png)

**Comment by LemonNoel** [comment]
辛苦打开 checkpoint/export_model 路径下的 template.json 文件，删除第二行内容。这个是版本不兼容问题，后续修复一下。
