### ISSUE TITLE
[Question]: 使用对话生成模型，sample模式，内存就会不断变大，最后崩溃，用的aistudio，代码是nlp,example里的2021那个比赛基线

### ISSUE THREAD

**Issue by freeman1980** [PaddlePaddle/PaddleNLP#5001]
### 请提出你的问题

[Question]: 使用对话生成模型，sample模式，内存就会不断变大，最后崩溃，用的aistudio，代码是nlp,example里的2021那个比赛基线

**Comment by FrostML** [comment]
能否详细描述下你所使用的模型，具体的链接以及具体的使用方式？

**Comment by gongel** [comment]
你好，可以这样试试看哈，另外可以减少生成的长度以及batch size。
![image](https://user-images.githubusercontent.com/24390500/221796934-eb02b6e0-46ca-4024-b5cc-0db6c36b99ad.png)
