### ISSUE TITLE
[Question]:下载token配置文件失败 

### ISSUE THREAD

**Issue by Juelianqvq** [PaddlePaddle/PaddleNLP#5002]
### 请提出你的问题

执行uie的 infer_cpu/gpu时遇到 Downloading from https://bj.bcebos.com/paddlenlp/models/community//tokenizer_config.json failed with code 404!

**Comment by linjieccc** [comment]
@Juelianqvq 你好，可以检查一下infer脚本指定的模型路径是否设置正确
