### ISSUE TITLE
请问在官网看到的的ERNIE-Search：围绕检索场景的多种任务，有开源地址嘛

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#5007]
### 问题描述

请问在官网看到的的ERNIE-Search：围绕检索场景的多种任务，有开源地址嘛

https://wenxin.baidu.com/wenxin/modelbasedetail/ernie_search

模型概述
为了提升 ERNIE 在检索领域的效果，ERNIE-Search 提出了使用预训练阶段细粒度交互向粗粒度交互蒸馏的策略。通过在训练过程中进行自蒸馏，在节省了传统方法中训练教师模型的开销之外，提高了 ERNIE-Search 的模型效果。

**Comment by w5688414** [comment]
@您好，@dingidng ERNIE-Search的开源在计划中了，目前会提供英文版本的代码和微调流程，敬请关注
