### ISSUE TITLE
使用ERNIE文心模型时报错

### ISSUE THREAD

**Issue by jiyuwangbupt** [PaddlePaddle/PaddleNLP#5008]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 暂未安装paddlenlp，直接使用git命令安装的ERNIE。
Tesla p40 (Compute Capability: 6.1), cuda10.2，cudnn7.6.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用ERNIE保存模型时报错
```

### 稳定复现步骤 & 代码

![c0a6f8e6e33a041fcfdd34e62371b24](https://user-images.githubusercontent.com/37127150/221461153-b4f6888a-22d4-4ca8-bce3-e77e8688df73.png)
运行命令是官方的文本分类:  python run_trainer.py --param_path ./examples/cls_ernie_fc_ch.json

**Comment by lugimzzz** [comment]
建议使用paddlenlp套件的ERNIE模型来做分类 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class  。ernie repo中相关问题建议直接在相关repo提issue https://github.com/PaddlePaddle/ERNIE/issues

**Comment by jiyuwangbupt** [comment]
> 建议使用paddlenlp套件的ERNIE模型来做分类 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class 。ernie repo中相关问题建议直接在相关repo提issue https://github.com/PaddlePaddle/ERNIE/issues

好的，非常感谢。
