### ISSUE TITLE
使用最新版本的uie，微调过程中eval_f1始终为0

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#5018]
### 请提出你的问题

最近为了使用蒸馏，更新了最新版本的uie，但更新后进行小样本微调时，eval_f1始终为0.0; （备注：更新uie之前，小样本微调是work的）

其中发现一个很奇怪的现象：从头开始用小样本进行微调模型，发现在初期看起来并为加载uie-model:
![image](https://user-images.githubusercontent.com/5744496/221786383-0d026f2f-fed4-4994-a348-6c434da1b96a.png)

模型训练：eval_f1始终为0.0
![image](https://user-images.githubusercontent.com/5744496/221786217-54d6a0b5-10eb-4aad-9a81-ef76c34bbac7.png)

**Comment by 1202010685** [comment]
我可以在这里问个问题嘛？

我也是新的uie微调，PaddleNLP/develop/model_zoo/uie/finetune.py , 只更改了train_path 和 dev_path，为什么我的运行不报错也不训练？

**Comment by 1202010685** [comment]
我也遇到了这个问题；第一次输出f1为0.2；第二次为0.0；

**Comment by adureychloe** [comment]
请问解决方案是什么呢？

**Comment by Qi0716** [comment]
请问是如何解决的？我这边除了loss有指标，其他指标全为0

**Comment by mynameisSiri** [comment]
请问有解决办法吗，是什么原因导致的

**Comment by zhangqiqi1228** [comment]
> ### 请提出你的问题
> 最近为了使用蒸馏，更新了最新版本的uie，但更新后进行小样本微调时，eval_f1始终为0.0; （备注：更新uie之前，小样本微调是work的）
> 
> 其中发现一个很奇怪的现象：从头开始用小样本进行微调模型，发现在初期看起来并为加载uie-model: ![image](https://user-images.githubusercontent.com/5744496/221786383-0d026f2f-fed4-4994-a348-6c434da1b96a.png)
> 
> 模型训练：eval_f1始终为0.0 ![image](https://user-images.githubusercontent.com/5744496/221786217-54d6a0b5-10eb-4aad-9a81-ef76c34bbac7.png)

看了下finetune.py的源碼，貌似是用dev_path中的數據集做的eval。
你用label_studio.py轉換數據集的時候，是不是將dev設置成了0呀？
如果dev數據集是空的，應該eval指標都是0。
