### ISSUE TITLE
[Question]: uie-m-large模型在GPU环境下执行demo结果不正常

### ISSUE THREAD

**Issue by LyleLiu666** [PaddlePaddle/PaddleNLP#5027]
### 请提出你的问题

**预期是，可以得到probability高于0.9的结果，实际上，都低于0.1**
环境如下：
```bash
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
```

![image](https://user-images.githubusercontent.com/31182860/222032263-37f0b12f-7618-43f0-8f9b-1cd6fb1ce764.png)
![image](https://user-images.githubusercontent.com/31182860/222032349-f605c48c-bfb5-4d3e-bff8-1661e841e095.png)
![image](https://user-images.githubusercontent.com/31182860/222032406-d14a1621-83d5-4040-b6a0-649ff00b7409.png)
![image](https://user-images.githubusercontent.com/31182860/222033553-028b369b-11e7-46bd-a2ee-72b70b80fb05.png)

执行结果：
![image](https://user-images.githubusercontent.com/31182860/222032916-5072bf19-db20-4efc-8231-e71776161045.png)

**Comment by LyleLiu666** [comment]
补充一下操作系统信息：
Linux version 4.15.0-180-generic (buildd@lcy02-amd64-097) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))

**Comment by linjieccc** [comment]
@GavinLiu666 感谢反馈！经排查是#4494 attention_mask改动导致，我们修复下这个问题
