### ISSUE TITLE
[Question]: 使用information_extraction训练实体抽取。训练完成后GPU缓存不清除

### ISSUE THREAD

**Issue by new-cainiao** [PaddlePaddle/PaddleNLP#5028]
### 请提出你的问题

使用uie模型进行微调训练，完成后GPU缓存不清除，重复训练会导致内存累积直至强制kill。
显卡为3090.驱动信息如下
![image](https://user-images.githubusercontent.com/39564677/222037362-861ddf68-9599-4c3d-8429-f68065d57656.png)
使用推荐参数训练，每次训练会增加2G左右到缓存，并且训练结束不会被清理
![image](https://user-images.githubusercontent.com/39564677/222037261-eab1982b-de39-4568-981d-da2ec9e248e4.png)

**Comment by new-cainiao** [comment]
使用的flask搭建的服务，调用学习使用，其中有关information_extraction/text内的脚本都在接口函数中import，结束后依然不会清理

**Comment by linjieccc** [comment]
@new-cainiao 你好，请问是在执行微调finetune.py的时候程序无法正常结束么

**Comment by new-cainiao** [comment]
正常结束了，训练也完成了，模型也都正常。就是主程序不结束GPU缓存就无法清理。重复运行finetune.py会导致GPU内存积累

**Comment by new-cainiao** [comment]
@linjieccc 我是import导入finetune相关包后去使用，会出现这样的问题。我目前的解决方法是使用subprocess在脚本内构造运行命令去训练评估，这种方式运行完是会清理GPU缓存的。

**Comment by new-cainiao** [comment]
![image](https://user-images.githubusercontent.com/39564677/222108152-f48d0652-ead9-4e09-8489-43a8ed071891.png)
这种方式导入使用是有问题的。主进程不结束是无法释放GPU内存。这个问题应该挺好复现。我可以粘贴一点我的处理代码
![image](https://user-images.githubusercontent.com/39564677/222108454-46473089-17d0-4e7c-8200-4f6a0bf19ea7.png)
![image](https://user-images.githubusercontent.com/39564677/222110930-ec1e88a6-0b6e-4095-9fd7-693a18f7c982.png)
将输入参数处理成训练方法需要的参数，finetune不用做修改可以被调用执行。

**Comment by iwhyshop** [comment]
> 使用的flask搭建的服务，调用学习使用，其中有关information_extraction/text内的脚本都在接口函数中import，结束后依然不会清理

你好方便贴一下【我目前的解决方法是使用subprocess在脚本内构造运行命令去训练评估】相关代码吗？我也碰到了，
flask+uwsgi,GPU MEMORY一直加，不释放
