### ISSUE TITLE
[Question]: onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : No graph was found in the protobuf.

### ISSUE THREAD

**Issue by weiiWill** [PaddlePaddle/PaddleNLP#5029]
### 请提出你的问题

paddle few-shot代码进行文本分类训练的模型，在infer的时候报错。
代码路径为： paddleNLP-develop/applications/text_classification/multi_class/few-shot/

**Comment by LemonNoel** [comment]
静态图路径配置正确吗？

**Comment by weiiWill** [comment]
> 

配置正确，训练代码没有改动，直接按照给的训练命令训练的，然后在cheackpoint保存的位置再重新加载模型进行infer,就一直报错，还有一个template.json 文件读取一直报错的问题

**Comment by LemonNoel** [comment]
template.json 读取不兼容问题已知待修复，辛苦先将文件第二行删除即可执行。加载模型的目录是 export 后的静态图吗？要同时带有去掉后缀的文件名，看报错是没有读取到静态图。

**Comment by weiiWill** [comment]
<img width="286" alt="image" src="https://user-images.githubusercontent.com/46260207/222374146-49e1ded6-9ad4-4342-b69d-da2ce77afd35.png">
上图为我保存的模型的位置。
下面为我infer时候给的命令：
<img width="776" alt="image" src="https://user-images.githubusercontent.com/46260207/222375173-a6e0810c-9e35-4714-9678-84725904fdde.png">

**Comment by LemonNoel** [comment]
1. 执行[模型导出](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/few-shot#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)这步得到静态图
2. 执行 infer.py 文件，--model_path_prefix 设置为 ./export_checkpoint/export/model
