### ISSUE TITLE
[Question]: 我使用django来封装uie的模型，实现预测功能，性能上有些问题

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/PaddleNLP#5037]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/61367424/222078129-6f071b4d-a883-4ce5-8dde-259c6e4daea7.png)
我把taskflow 实例化放到接口里，每次访问接口，都会执行一遍taskflow对象的实例化。我如果把taskflow实例化放到全局，就必须得把 batchsize，model等参数给写死。请问是否有接口，在taskflow实例化之后，再修改参数的接口；或是有别的方法，能避免每次访问接口，都执行taskflow的初始化

**Comment by wawltor** [comment]
目前我们提供了一个simple serving的能力可以实现出上述的效果 
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/server.md
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/16698950/222118206-5c16d2e6-633a-4280-8d8a-05cc0aa0b94d.png">

**Comment by lzh1998-jansen** [comment]
我看过这个，你这个clint端每次请求，server端的 模型都得加载一次把， Taskflow("information_extraction",schema=["公司","人名","地名"],batch_size=8,model="uie-base")。我想请教的是，如何能避免每次都加载这个模型

**Comment by lzh1998-jansen** [comment]
我看过这个，你这个clint端每次请求，server端的 模型都得加载一次把， Taskflow("information_extraction",schema=["公司","人名","地名"],batch_size=8,model="uie-base")。我想请教的是，如何能避免每次都加载这个模型

**Comment by wawltor** [comment]
> 我看过这个，你这个clint端每次请求，server端的 模型都得加载一次把， Taskflow("information_extraction",schema=["公司","人名","地名"],batch_size=8,model="uie-base")。我想请教的是，如何能避免每次都加载这个模型

不会重新加载

**Comment by lzh1998-jansen** [comment]
simple servering 中的 server端，不会重新加载模型的原理，也是把模型放到全局的原理吧
![image](https://user-images.githubusercontent.com/61367424/222311180-3749ed8e-945f-461d-8045-7183d3eb8861.png)

**Comment by wawltor** [comment]
> simple servering 中的 server端，不会重新加载模型的原理，也是把模型放到全局的原理吧 ![image](https://user-images.githubusercontent.com/61367424/222311180-3749ed8e-945f-461d-8045-7183d3eb8861.png)

server服务化只会启动一次

**Comment by lzh1998-jansen** [comment]
还是有个疑问，server端初始化了一个taskflow，你client端发送了 batchsize等参数，这个taskflow对象是怎么接收的？

**Comment by wawltor** [comment]
> 还是有个疑问，server端初始化了一个taskflow，你client端发送了 batchsize等参数，这个taskflow对象是怎么接收的？

Taskflow目前支持schema的传入，暂时不支持其他的参数的传入，batch_size等参数传入应该在离线测试需要确定好
<img width="852" alt="image" src="https://user-images.githubusercontent.com/16698950/222381963-51a5a16f-750b-4623-9463-d99cba4ed58b.png">

预训练模型的serving可以支持batch size的参数

**Comment by wawltor** [comment]
您好，我们将关闭该issue，如有问题可以再打开该issue。
