### ISSUE TITLE
[Question]: paddleserving 部署时多进程配置

### ISSUE THREAD

**Issue by wpxhaha** [PaddlePaddle/PaddleNLP#5039]
### 请提出你的问题

paddlenlp用paddleserving 部署，这两个地方配置多进程有什么不同，实际尝试都能配置多进程：
<img width="706" alt="image" src="https://user-images.githubusercontent.com/90829300/222081489-15cb4d7f-4c33-4745-bfcf-9f846d473cbe.png">

**Comment by HexToString** [comment]
上面的worker_num是grpc的网络请求的并发数。
而下面的是请求内部处理函数，比如你这里的是seq_cls的并发数。
举例：例如flask服务，入口函数为def seq_cls()
那么，worker_num对应flask的并发数量，而下面的concurrecy对应每个flask进程中，seq_cls的并发数量
