### ISSUE TITLE
[Question]: Taskflow每次都会重新下载词表

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PaddleNLP#5041]
### 请提出你的问题

在使用自己微调过的Taskflow("zero_shot_text_classification", model="utc-base", schema=schema, task_path='./checkpoint/model_best/plm')是会自动下载词表（ Downloading vocab.txt from https://paddlenlp.bj.bcebos.com/taskflow/zero_shot_text_classification/utc-base/vocab.txt），但是因为数据要求，我的服务器在内网环境。我已经从能上互联网的机器上拷贝$HOME/.paddlenlp/models/utc-base文件夹到内网服务器后还不行。

**Comment by wawltor** [comment]
建议更新PaddleNLP的版本到2.5.1版本

**Comment by LemonNoel** [comment]
将 `./checkpoint/model_best/` 目录下的 vocab.txt, tokenizer_config.json 文件拷贝到 `./checkpoint/model_best/plm` 目录下

**Comment by wjj001-dl** [comment]
> 建议更新PaddleNLP的版本到2.5.1版本

更新后，离线环境下文本摘要任务中使用IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1时，仍然需要下载，该怎么解决？
