### ISSUE TITLE
[Question]: AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/PaddleNLP#5047]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/50578167/222120467-19356eb2-376c-4b5a-8ad2-e528b0d62746.png)

按网上说的做法都不行，python版本 3.8.10

**Comment by wawltor** [comment]
你的pandas的版本是什么了？

**Comment by zongzijiayou** [comment]
> 
你好，是1.5.3

**Comment by wawltor** [comment]
可以降低一下pandas的版本，可以降低到 pandas 1.4.3 版本

**Comment by zongzijiayou** [comment]
> 可以降低一下pandas的版本，可以降低到 pandas 1.4.3 版本

你好，我尝试降低到1.4.3版本后，依然是一样的错误
![捕获](https://user-images.githubusercontent.com/50578167/222149725-bdc928da-bc7c-46d7-b96d-bc35fe5c78b9.PNG)
![捕获11](https://user-images.githubusercontent.com/50578167/222149753-d8410f99-ee81-48e4-abdc-94a84d5f7f85.PNG)
![捕获333](https://user-images.githubusercontent.com/50578167/222149772-a5f515d4-7e24-4981-9e6d-e7b5f31da9ed.PNG)

**Comment by zongzijiayou** [comment]
> 可以降低一下pandas的版本，可以降低到 pandas 1.4.3 版本

我同样也试了 1.5.0  1.4.2   1.4.4

**Comment by zongzijiayou** [comment]
> 可以降低一下pandas的版本，可以降低到 pandas 1.4.3 版本

我同样也试了 1.5.0  1.4.2   1.4.4

**Comment by wawltor** [comment]
那就尝试换一个Python的版本 😅

**Comment by zongzijiayou** [comment]
> 

暂时换成3.9.0不报那个错误了，谢谢

**Comment by wawltor** [comment]
好的 那我们暂时关闭该issue，如有问题可以再次打开打开issue。
