### ISSUE TITLE
[Question]: Ernie-Layout - getting IndexError: list index out of range error in Inference script for custom dataset.

### ISSUE THREAD

**Issue by vishal-nayak1** [PaddlePaddle/PaddleNLP#5051]
### 请提出你的问题

Hi, I am trying to infer model using fine-tuned model on custom dataset but getting IndexError: list index out of range error in predictor.py file.I think few [lines](https://github.com/PaddlePaddle/PaddleNLP/blob/afa34599c24159f29a9dbfd95ea553e40c3d52ca/model_zoo/ernie-layout/deploy/python/predictor.py#L80) need to be updated.

**Comment by linjieccc** [comment]
@vishal-nayak1 Hi,

I think you should modify `label_dict` according to the label defined in your custom dataset
