### ISSUE TITLE
[Question]:  同时安装paddlepaddle & paddlepaddle-gpu 无法调用gpu

### ISSUE THREAD

**Issue by 1202010685** [PaddlePaddle/PaddleNLP#5055]
### 请提出你的问题

pycharm无法调用gpu,请教！

相关配置：
py3.7
paddlepaddle-gpu 2.4.2
CUDA 11.7
cuDNN 8.7
Driver API 12.1
Auntime API 11.7
pycharm 2022.3
电脑显卡： RTX 4000

我在anaconda-prompt-我的环境-python中可以调用gpu 
(import paddle  /  paddle.utlis.run_check()   返回了works well on 1 gpu)

但在运行uie/finetune的时候 仍然返回ValueError: The device should not be "gpu"...

请问为什么？

**Comment by linjieccc** [comment]
@1202010685 你好，建议只安装一个gpu版本的paddle。如果有需要在CPU上执行的场景，在代码起始位置加入`paddle.device.set_device("cpu")`即可

**Comment by 1202010685** [comment]
> @1202010685 你好，建议只安装一个gpu版本的paddle。如果有需要在CPU上执行的场景，在代码起始位置加入`paddle.device.set_device("cpu")`即可

谢谢！我先安装了CPU版本，且正在运行，因为运行很慢，60条长文本数据（千字长度）；所以想再安装GPU运行，看看GPU会不会快；目前的CPU正常运行，GPU报错说配置不对(错误代码126)，但我不清楚哪里不对？

**Comment by wawltor** [comment]
> > @1202010685 你好，建议只安装一个gpu版本的paddle。如果有需要在CPU上执行的场景，在代码起始位置加入`paddle.device.set_device("cpu")`即可
> 
> 谢谢！我先安装了CPU版本，且正在运行，因为运行很慢，60条长文本数据（千字长度）；所以想再安装GPU运行，看看GPU会不会快；目前的CPU正常运行，GPU报错说配置不对(错误代码126)，但我不清楚哪里不对？

先执行一下 paddle.utils.run_check()，看看是不是GPU版本安装的不对
