### ISSUE TITLE
[Question]: 使用NLP ocr 功能时，报错 Killed

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/PaddleNLP#5057]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/50578167/222313536-a2aa5968-8a05-42f7-b69c-0759ca5893f8.png)

**Comment by zongzijiayou** [comment]
经过排查是内存不够用了，运行的时候，7个G的内存都不够用。。。。

**Comment by wj-Mcat** [comment]
ernie-layout 基座模型的大小确实是比较大，建议在内存较大的服务器上面测试开发。

**Comment by zongzijiayou** [comment]
> ernie-layout 基座模型的大小确实是比较大，建议在内存较大的服务器上面测试开发。

谢谢，只能这样了，加了内存好了
