### ISSUE TITLE
请问UIE有长篇文本级别信息抽取【实体抽取、关系抽取】没有512限制的开源模型吗

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#5060]
### Feature request

请问UIE有长篇文本级别信息抽取【实体抽取、关系抽取】没有512限制的开源模型吗？
之前有看到ERNIE-DOC但没有开源的长篇级信息抽取

https://github.com/PaddlePaddle/ERNIE/blob/repro/ernie-doc/README_zh.md#%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96

### Motivation

请问UIE有长篇文本级别信息抽取【实体抽取、关系抽取】没有512限制的开源模型吗？

### Your contribution

暂无

**Comment by wawltor** [comment]
UIE本身底座模型最大的长度是2048，但是2048的文档长度会限制模型的效果，以及容易内显存溢出；
Taskflow对UIE的功能封装功能的时候，已经做了文档切片处理，可以接受较长长度的文档

**Comment by tingaicompass** [comment]
> UIE本身底座模型最大的长度是2048，但是2048的文档长度会限制模型的效果，以及容易内显存溢出； Taskflow对UIE的功能封装功能的时候，已经做了文档切片处理，可以接受较长长度的文档

![image](https://user-images.githubusercontent.com/34392683/222344343-bc5a9a88-ba6e-4a35-9037-a76528034f39.png)

对于实体抽取影响是不大的，但对于关系抽取，尤其是跨句子会导致关系遗漏。同时也好奇现在UIE是否支持关系抽取里部分关系推理，语义消歧，共指关联。
Entity Structure Within and Throughout: Modeling Mention Dependencies for Document-Level Relation Extraction AAAI2021
https://github.com/PaddlePaddle/Research/tree/master/KG/AAAI2021_SSAN
 这篇论文里是你们之前做的SSAN篇章级关系推理模型，这块会和UIE结合嘛

**Comment by wawltor** [comment]
> > UIE本身底座模型最大的长度是2048，但是2048的文档长度会限制模型的效果，以及容易内显存溢出； Taskflow对UIE的功能封装功能的时候，已经做了文档切片处理，可以接受较长长度的文档
> 
> ![image](https://user-images.githubusercontent.com/34392683/222344343-bc5a9a88-ba6e-4a35-9037-a76528034f39.png)
> 
> 对于实体抽取影响是不大的，但对于关系抽取，尤其是跨句子会导致关系遗漏。同时也好奇现在UIE是否支持关系抽取里部分关系推理，语义消歧，共指关联。 Entity Structure Within and Throughout: Modeling Mention Dependencies for Document-Level Relation Extraction AAAI2021 https://github.com/PaddlePaddle/Research/tree/master/KG/AAAI2021_SSAN 这篇论文里是你们之前做的SSAN篇章级关系推理模型，这块会和UIE结合嘛

长文本的关系抽取相对比较难，目前没有计划和SSAN进行结合

**Comment by Walker-DJ1** [comment]
> UIE本身底座模型最大的长度是2048，但是2048的文档长度会限制模型的效果，以及容易内显存溢出； Taskflow对UIE的功能封装功能的时候，已经做了文档切片处理，可以接受较长长度的文档

请问。uie-large模型训练支持的max_seq_length是多少？我在训练的时候512是正常训练，设置1024便出现报错的情况。
