### ISSUE TITLE
[Question]: 执行ernie-health中的 train_classification.py 提示OSError: Invalid enum backend type `64`.

### ISSUE THREAD

**Issue by elvis324** [PaddlePaddle/PaddleNLP#5065]
### 请提出你的问题

python 版本 3.7  
pip 版本20.1.1
paddlepaddle  版本2.4.1
paddlenlp 版本 2.5.1 
windows系统  windows server 2012 64位

执行命令 ：
D:\smart\app\ernie-health\cblue>python train_clas
sification.py --device cpu --dataset CHIP-CDN-2C --batch_size 256 --max_seq_leng
th 32 --learning_rate 3e-5 --epochs 16

错误输出：
`
[2023-03-02 13:37:45,297] [    INFO] - Already cached C:\Users\Administrator\.pa
ddlenlp\models\ernie-health-chinese\ernie-health-chinese\ernie-health-chinese.pd
params
Traceback (most recent call last):
  File "train_classification.py", line 239, in <module>
    do_train()
  File "train_classification.py", line 121, in do_train
    "ernie-health-chinese", num_classes=len(train_ds.label_list), activation="ta
nh"
  File "D:\smart\app\python3\lib\site-packages\paddlenlp\transformers\model_util
s.py", line 712, in from_pretrained
    state_to_load[k] = paddle.cast(state_to_load[k], dtype)
  File "D:\smart\app\python3\lib\site-packages\paddle\tensor\manipulation.py", l
ine 77, in cast
    return _C_ops.cast(x, dtype)
**OSError: Invalid enum backend type `64`.**
  [C:\home\workspace\Paddle\paddle/phi/common/backend.h:140]

`
是系统版本的问题还是别的原因，无法正常执行？

**Comment by wj-Mcat** [comment]
从错误可以初步看出是 paddle 版本的问题，你可以先尝试一下[升级paddle](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)。

如果还无法解决你的问题的话，你可以给出：

1. 你的环境：`pip list | grep paddle`
2. 你本地代码路径：你是执行的那部分代码，从上面没办法定位到具体代码位置
3. 如果你能够使用一小段代码稳定复现时，这当然是最好的，也请粘贴到这里来。

**Comment by elvis324** [comment]
1.环境：pip list | grep paddle

```
paddle-bfloat      0.1.7
paddle2onnx        0.6
paddlefsl          1.0.0
paddlehub          2.1.0
paddlenlp          2.5.1
paddlepaddle       2.4.2
```
2.本地代码路径 

2.1  执行命令：
```
D:\smart\app\paddleNLP\git-code-ernie-heath\ernie-health\cblue>python train_clas
sification.py --device cpu --dataset CHIP-CDN-2C --batch_size 256 --max_seq_leng
th 32 --learning_rate 3e-5 --epochs 16

```
2.2 执行代码文件：  
D:\smart\app\paddleNLP\git-code-ernie-heath\ernie-health\cblue\train_classification.py  
  [github连接 train_classification.py](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-health/cblue/train_classification.py)

2.3 错误文件跟踪
```
** 文件1：train_classification.py ** 
def do_train():
    paddle.set_device(args.device)
    rank = paddle.distributed.get_rank()
    if paddle.distributed.get_world_size() > 1:
        paddle.distributed.init_parallel_env()

    set_seed(args.seed)

    train_ds, dev_ds = load_dataset("cblue", args.dataset, splits=["train", "dev"])
   // 执行这句报错
    **model = ElectraForSequenceClassification.from_pretrained(
        "ernie-health-chinese", num_classes=len(train_ds.label_list), activation="tanh"**
    )

**文件2：D:\smart\app\python3\lib\site-packages\paddlenlp\transformers\model_util.py** 

# TODO(guosheng): add warnings for unmatched dtypes
            if k in state_to_load: 
                if paddle.in_dynamic_mode():
                    if isinstance(state_to_load[k], np.ndarray):
                        state_to_load[k] = state_to_load[k].astype(dtype)
                    else: 
                        **state_to_load[k] = paddle.cast(state_to_load[k], dtype)**

**文件3 D:\smart\app\python3\Lib\site-packages\paddle\tensor\manipulation.py**

   if in_dygraph_mode():
        if not isinstance(dtype, core.VarDesc.VarType):
            dtype = convert_np_dtype_to_dtype_(dtype)
        **return _C_ops.cast(x, dtype)**

```

目前在linux系统上可以运行， 在windows server 2012 R2 64位 报这个错误，可能跟操作系统有关了

**Comment by gg22mm** [comment]
？ 我也遇到这样的问题，什么情况，也没有个解决说明？？？
