### ISSUE TITLE
PaddleNLP/applications/text_summarization/finetune/

### ISSUE THREAD

**Issue by liuliuNLP** [PaddlePaddle/PaddleNLP#5072]
### 请提出你的问题

[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP)/[applications](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications)/[text_summarization](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization)/finetune/

微调的文本摘要模型，但是没有gpu无法使用fast_generation，我怎么保存静态图模型呢

**Comment by wawltor** [comment]
没有GPU的话目前是无法导出静态图，预计我们在稍微时间点会打通动转静逻辑；同时生成模型相对较大，同时解码过程相对比较复杂耗时，建议还是使用GPU来做生成相关的工作
