### ISSUE TITLE
[Question]: utc模型训练完启动simpleServer进行预测，为什么不能用gpu只能cpu预测

### ISSUE THREAD

**Issue by Jaydon996** [PaddlePaddle/PaddleNLP#5087]
### 请提出你的问题

utc模型训练完启动simpleServer进行预测，服务启动后调用就只用cpu进行预测，看源码is_compiled_with_cuda()这个返回值就是false，是环境有问题么？

**Comment by JunnYu** [comment]
是的，is_compiled_with_cuda() 这个为false就表明你的环境没配置正确。
您可以参考这里重新安装一下paddle，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Jaydon996** [comment]
好的，谢谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月03日 16:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: utc模型训练完启动simpleServer进行预测，为什么不能用gpu只能cpu预测 (Issue #5087) |

是的，is_compiled_with_cuda() 这个为false就表明你的环境没配置正确。
您可以参考这里重新安装一下paddle，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Jaydon996** [comment]
好的，我试试，谢谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月03日 16:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: utc模型训练完启动simpleServer进行预测，为什么不能用gpu只能cpu预测 (Issue #5087) |

是的，is_compiled_with_cuda() 这个为false就表明你的环境没配置正确。
您可以参考这里重新安装一下paddle，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Jaydon996** [comment]
> 是的，is_compiled_with_cuda() 这个为false就表明你的环境没配置正确。 您可以参考这里重新安装一下paddle，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

好的，我试试，谢谢
