### ISSUE TITLE
[Question]: 我可以用的paddle加载别人社区训练好的lora模型么，safetensor格式的

### ISSUE THREAD

**Issue by liusseu** [PaddlePaddle/PaddleNLP#5092]
### 请提出你的问题

我可以用的paddle加载别人社区训练好的lora模型么，safetensor格式的

**Comment by JunnYu** [comment]
当前ppdiffusers里面使用的lora与[civi](https://civitai.com/)上的lora不太一样，您可以看一下这个 PR 里面的LORA https://github.com/PaddlePaddle/PaddleNLP/pull/5015 这里的可以直接加载 https://github.com/bmaltais/kohya_ss 这个人的lora权重

**Comment by liusseu** [comment]
> 当前ppdiffusers里面使用的lora与[civi](https://civitai.com/)上的lora不太一样，您可以看一下这个 PR 里面的LORA #5015 这里的可以直接加载 https://github.com/bmaltais/kohya_ss 这个人的lora权重

好的，谢谢，后续有考虑支持civi上的lora么

**Comment by liuguicen** [comment]
> > 当前ppdiffusers里面使用的lora与[civi](https://civitai.com/)上的lora不太一样，您可以看一下这个 PR 里面的LORA #5015 这里的可以直接加载 https://github.com/bmaltais/kohya_ss 这个人的lora权重
> 
> 好的，谢谢，后续有考虑支持civi上的lora么

赞呀，考虑支持civi吗，目前用stable diffusion的人大都会用这个civitai上的lora吧
