### ISSUE TITLE
[Question]: 信息抽取的uie-x的转静态图的疑问

### ISSUE THREAD

**Issue by zyc751201** [PaddlePaddle/PaddleNLP#5099]
### 请提出你的问题

我能直接调用static或者onnex模型么？动态图参数删除就会重新从网上下载。有什么办法直接加载静态图模型？

**Comment by linjieccc** [comment]
@zyc751201 你好，可以参考文本这里的实现方案修改下，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/deploy/python/infer_gpu.py
