### ISSUE TITLE
ERNIE3.0文本分类原理

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5100]
请问ERNIE3.0文本分类的原理是什么？是用[CLS]的信息输入到分类器里来判断类别吗？

**Comment by wawltor** [comment]
是的，就是通过CLS来进行分类的，微调的时候就学习这个分类器

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有问题可以再次打开该issue。
