### ISSUE TITLE
请问模型文件在哪里？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5101]
### 请提出你的问题

请问分类模型文件在呢？层次文本分类中没看到模型文件，只有train、evaluate、predict这些。

**Comment by wawltor** [comment]
预训练模型保存的地址 ~/.paddlenlp/models/，需要通过微调之后再将模型参数保存  https://github.com/PaddlePaddle/PaddleNLP/blob/f6cf94de48731dbccaab1bfe14b8af6789469c27/applications/text_classification/hierarchical/train.py#L191
