### ISSUE TITLE
[Bug]: BertForMaskedLM参数缺失

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/PaddleNLP#5102]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py
BertForMaskedLM的forward函数中，少了masked_positions参数，导致无法进行MLM任务
第1399行也未将masked_positions赋值
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py
BertForMaskedLM的forward函数中，少了masked_positions参数，导致无法进行MLM任务
第1399行也未将masked_positions赋值

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/5104/files

感谢反馈
