### ISSUE TITLE
K折交叉验证

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5103]
### 请提出你的问题

请问数据集较小，想加一个K折交叉验证的方法，请问有什么简便的方式来做吗？谢谢

**Comment by sijunhe** [comment]
您好，您可以写一个大的for loop, 用上[sklearn的kfold](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html), for loop里面根据KFold提供的train_idx和val_idx创造train_dataset和eval_dataset，创建model和trainer, 然后训练，评估。大概就是这么个流程

**Comment by QChen0409** [comment]
您好，请问平时我用的一般都是训练集、测试集、验证集6:2:2这种方式，k折交叉验证用到的是训练集和测试集还是训练集和验证集呢？我看网上说法大多数都说训练集和测试集，这个方法不需要用到验证集是吗？




1624140190
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] K折交叉验证 (Issue #5103)





 
您好，您可以写一个大的for loop, 用上sklearn的kfold, for loop里面根据KFold提供的train_idx和val_idx创造train_dataset和eval_dataset，创建model和trainer, 然后训练，评估。大概就是这么个流程

**Comment by sijunhe** [comment]
> 您好，请问平时我用的一般都是训练集、测试集、验证集6:2:2这种方式，k折交叉验证用到的是训练集和测试集还是训练集和验证集呢？我看网上说法大多数都说训练集和测试集，这个方法不需要用到验证集是吗？ 1624140190 ***@***.*** &nbsp;
 
看个人习惯了，一般是KFold用训练和验证集，最后再用测试集跑一次测试指标
