### ISSUE TITLE
[Question]: UIE情感分析CPU和GPU预测结果不一致

### ISSUE THREAD

**Issue by YizhuLiu** [PaddlePaddle/PaddleNLP#5105]
### 请提出你的问题

在使用UIE情感分析时，安装paddlepaddle==2.3.0且使用CPU时返回结果正常，安装paddlepaddle-gpu==2.3.0且使用GPU时无报错，但返回结果是空的，请问是什么原因呢？

**Comment by wawltor** [comment]
首先建议升级一下Paddle的版本，同时在安装GPU的时候检查一下是否安装成功

```python
import paddle 
paddle.utils.run_check()
```

**Comment by YizhuLiu** [comment]
升级paddlepaddle-gpu==2.4.1，在执行python batch_predict.py的时候现实paddle安装成功，但是报的cuda的错，请问是因为什么呢？
`Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.`

`OSError: (External) CUDA error(209), no kernel image is available for execution on the device. 
  [Hint: Please search for the error code(209) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:148)
`

**Comment by wawltor** [comment]
能提供一下你的GPU设备型号、本地的cuda和cudnn版本，以及PaddlePaddle-gpu的cuda版本吗？

**Comment by YizhuLiu** [comment]
GPU：a100
cuda：10.2
cudnn：7.6.5

**Comment by YizhuLiu** [comment]
PaddlePaddle-gpu的cuda版本是什么意思？

**Comment by YizhuLiu** [comment]
PaddlePaddle-gpu的cuda版本是什么意思？没单独给PaddlePaddle-gpu安装cuda

**Comment by YizhuLiu** [comment]
我后边又试了
GPU：a100
cuda：11.3
cudnn：8.2
paddlepaddle-gpu==2.4.1，
报这个错
`Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/workdir/batch_predict.py", line 19, in <module>
    from utils import load_txt, write_json_file
  File "/workdir/utils.py", line 21, in <module>
    import paddle
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/usr/local/python3/lib/python3.9/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory`

**Comment by wawltor** [comment]
设置一下 根据python的路径限制一下LD_LIBRARY_PATH，  类似 export LD_LIBRARY_PATH= /opt/conda/envs/nlp/lib/python3.7/lib:$LD_LIBRARY_PATH

**Comment by wawltor** [comment]
您好，我们将暂时关闭该issue，如有问题可以再次打开该issue。

**Comment by Molly-Xia** [comment]
你好，请问在运行python -u -m paddle.distributed.launch --gpus "0" finetune.py \
  --train_path ./data/train.json \
  --dev_path ./data/dev.json \
  --save_dir ./checkpoint \
  --learning_rate 1e-5 \
  --batch_size 16 \
  --max_seq_len 512 \
  --num_epochs 3 \
  --model uie-senta-base \
  --seed 1000 \
  --logging_steps 10 \
  --valid_steps 100 \
  --device gpu
要怎么修改关于cpu的信息？我是在服务器上运行的，服务器装了4个处理器。我在当初下载paddlepaddle时是下载的是cpu版本
