### ISSUE TITLE
UIE-X预测加速

### ISSUE THREAD

**Issue by xurning** [PaddlePaddle/PaddleNLP#5106]
### 请提出你的问题

uie-x使用task_path参数以后识别很慢，每次都要在static文件夹生成预测模型，请问有解决办法吗？

**Comment by linjieccc** [comment]
@xurning 你好，

当前如果硬件环境满足要求的话可以使用半精度推理(precision="fp16")来提速，

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/taskflow_doc.md#27-%E6%9B%B4%E5%A4%9A%E9%85%8D%E7%BD%AE

另外我们有个封闭域文档抽取的工作正在进行中：https://github.com/PaddlePaddle/PaddleNLP/pull/4900

欢迎持续关注~
