### ISSUE TITLE
[Question]: paddle 跑ernie3.0 zeus模型，分布式预估，报这个错误，连不上master？

### ISSUE THREAD

**Issue by dongwenxin2046** [PaddlePaddle/PaddleNLP#5110]
### 请提出你的问题

paddle 跑ernie3.0 zeus模型，分布式预估，报这个错误，求看

![image](https://user-images.githubusercontent.com/107353780/223014972-6ecd139c-11ad-4133-8073-cfacca2434a8.png)

**Comment by gongel** [comment]
已转向文心团队。
