### ISSUE TITLE
利用UIE slim数据蒸馏后，通过taskflow模型推理速度反而变慢

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#5112]
### 请提出你的问题

问题1：按照UIE slim中的方案https://github.com/PaddlePaddle/PaddleNLP/tree/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/applications/information_extraction/text/data_distill进行数据蒸馏后， student模型的推理速度相比teacher反而更慢。 期望的效果应该是student模型的推理速度相比teacher提速x倍。

问题2： 此外使用student模型推理，不管是否设置use_fast是否为true， 模型的平均推理性能基本没变化。 

paddlenlp              2.5.1.post0    
paddlepaddle-gpu       2.3.0 

具体细节：
teacher 模型： 使用uie-base
student 模型： 使用ernie-3.0-mini-zh

模型预测：case by case预测， 2000个sample， 平均长度512

1.teacher模型： teacher模型推理平均时长：39ms
task_path ='../checkpoint/photo/20230208/base/model_best' 
ie = Taskflow("information_extraction",use_fast = True,precision='fp32',task_path=task_path, schema=schema)

2.student模型： student模型推理平均时长：47ms
task_path="checkpoint/model_best/"  # student
ie = Taskflow("information_extraction", model="uie-data-distill-gp", use_fast = True,precision='fp32',task_path=task_path)

**Comment by linjieccc** [comment]
@leon-cas 你好，

能否贴一下你的schema设置，封闭域抽取的速度提升和schema的数量/复杂度有关系，封闭域模型和UIE的差别主要在于封闭域模型需要跑一次前向

封闭域模型目前还不支持fast_tokenizer，我们会在近期进行适配 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/information_extraction.py#L1393

**Comment by leon-cas** [comment]
> 

@linjieccc teacher模型(uie)， 和封闭域模型中使用的schema都是一样的： schema=['图书名']。  

做了个简单的耗时测试, 具体如下：  从下面的结果看来uie模型支持use_fast和precision设置； 而蒸馏后的student模型貌似不支持设置precision，同时若支持use_fast应该对于student模型的推理性能会有较大影响，不知是否是这样？
teacher模型(uie) 
   use_fast=True, precision=fp16   17.5ms 
  use_fast=True,  precision=fp32   38.4ms
  use_fast=False,  precision=fp16   57.2ms
  use_fast=False,  precision=fp32   75.4ms

student模型(封闭)
precision=fp16    46.8ms
precision=fp32    44.8ms

**Comment by feng-1985** [comment]
mark - 同问...
