### ISSUE TITLE
[Question]: Taskflow API 【zero_shot_text_classification执行样例时报错：'numpy.float64' object is not iterable】

### ISSUE THREAD

**Issue by maodandanqiu** [PaddlePaddle/PaddleNLP#5114]
### 请提出你的问题

<img width="782" alt="image" src="https://user-images.githubusercontent.com/43943978/223028548-1129239f-83e1-4eb1-b463-08e74d301596.png">
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/43943978/223028620-abdcedec-570d-428d-a2e5-d7fc1f572e30.png">

**Comment by wawltor** [comment]
可以参考一下这个issue  https://github.com/PaddlePaddle/PaddleNLP/issues/4635

**Comment by wawltor** [comment]
您好，我们暂时关闭该issue，如有问题可以再次打开该issue。
