### ISSUE TITLE
[Question]: 我想在语义检索中显示出我上传的png图片，请高手指点一下，如何增加？

### ISSUE THREAD

**Issue by WangShunzhiDQ** [PaddlePaddle/PaddleNLP#5126]
### 请提出你的问题

image[] 显示为空，应该赋值什么？ webapp_semantic_search.py 页面代码如何增加图片显示？请高手指点！！！

**Comment by w5688414** [comment]
Hi, @WangShunzhiDQ， 上传的文件在file_upload目录下，您可以读取该目录下的图片进行可视化，可视化可以参考语义检索前端本身的Image控件。https://github.com/PaddlePaddle/PaddleNLP/blob/18287d3a8543b73c8bed8cbfb4db13f0cf01bcbd/pipelines/ui/webapp_semantic_search.py#L198
