### ISSUE TITLE
[Question]: 关于  ERNIE 3.0  multi_class 文本训练及预测问题咨询

### ISSUE THREAD

**Issue by done520** [PaddlePaddle/PaddleNLP#5137]
### 请提出你的问题

你好，在使用paddlenlp   ERNIE 3.0  multi_class 训练及预测遇到几个问题想咨询：
1. 训练文本长度不一，多大多个超过2048。我目前对超过 512的文本强制进行滑动窗口截断（按照字符串长度切割，截断后每段最长512，并保留于上一段有128的重叠），但这样处理可能会将某些词或完整句子拆散，请问你们什么建议吗？
2. 训练文本主要文中文，但也有相当一部分会出现中英文混杂的情况，即一段中文 紧接着为中文翻译后的英文，目前是通过正则去除掉整段英文，对整篇为英语语种的文档不适应，是不是需要训练两种语言的分类模型，你们有什么好的建议？
3. 由于训练时的长文采用了截断处理，那推理预测时遇到长文该怎么处理？如果长文截断后预测，可能多个截断部分预测分类不一致

**Comment by lugimzzz** [comment]
1.ernie 3.0目前最高是接收2048，不过设置太长确实会有显存问题。对文本进行有效预处理是目前常用推荐方法
2.ernie其实分词中也是支持英文的，以中文为主只有部分英文这块直接使用ernie 3.0模型就好。另外的选择就是使用ernie-m
3.那确实需要对多个预测结果进行一些后处理，投票，取交集或并集，或加入其他策略
