### ISSUE TITLE
[Question]: 请问这个模型是默认继续之前最好结果继续训练吗？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5141]
### 请提出你的问题

请问这个模型是默认继续之前最好结果继续训练吗？如果是的话如何重新开始训练呢？

**Comment by wawltor** [comment]
> ### 请提出你的问题
> 请问这个模型是默认继续之前最好结果继续训练吗？如果是的话如何重新开始训练呢？

具体是什么模型了?

**Comment by QChen0409** [comment]
您好，层次文本分类hierarchical的ERNIE3.0模型，想多跑几次选择超参数，发现会按照之前保存的模型继续训练，请问save_dir和init_from_ckpt去掉是不是每次可以重新训练了，另外想输出attention的值，设置output_attetntion = true在哪个文件下操作呢？


1624140190
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: 请问这个模型是默认继续之前最好结果继续训练吗？ (Issue #5141)





  
请提出你的问题
 
请问这个模型是默认继续之前最好结果继续训练吗？如果是的话如何重新开始训练呢？
  
具体是什么模型了?

**Comment by lugimzzz** [comment]
只要init_from_ckpt为None，每次都是重新训练。在train文件操作，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/hierarchical/train.py#L163
