### ISSUE TITLE
[Question]: UIE 关系抽取、事件抽取如何进行标签构建、任务标注、使用schema？

### ISSUE THREAD

**Issue by huzing2524** [PaddlePaddle/PaddleNLP#5144]
### 请提出你的问题

你好：

- 我是NLP新手，有一批文档，需要从文字描述中把 “同一种命名实体：人物类、组织机构类” 区分开【抵押人】、【保证人】，抽取出“**人物类的名称**”、“**组织机构类的名称**”。
- 文字描述可能非常灵活，保证关系有这些很固定的描述：最高额保证、连带责任保证、保证责任、保证人。
- 数据集举例如下：
  1. 以**张三**及配偶**李四**房地产**抵押**，同时追加借款人股东**王五**及其配偶**赵六**、**孙七**及配偶**周八** **连带责任保证**。
  2. 由**虾稻醇酒业有限公司**提供工业用地**抵押**，并由**中辉建设集团有限公司**、**李四**及配偶**王五**承担**最高额保证**。
  3. **张三**提供票据**抵押**，全部敞口由**李四**及配偶**王五**承担**保证责任**。
  4. 最高额抵押金额为： 3,330,000.00元，**抵押人**：**张三**、**李四**；最高额保证金额为：3,330,000.00元，**保证人**：**王五**、**赵六**。

问题：
- 这个任务适合“**关系抽取**”还是“**事件抽取**”呢？应该如何“**标签构建**”、“**任务标注**”、"**Taskflow使用什么schema**"呢？我参考了一下其它的issues，下面是我的一些想法，不知道是否正确。
- 如果使用关系抽取，使用哪种方法更好，或者有更好的方法吗？
  - 方法1：
    - 定义多种Span类型标签：抵押、最高额保证、连带责任保证、保证责任、保证人。
    - Relation标签：抵押关系、保证关系。
    - schema1= {"人物类": ["抵押关系", "保证关系"]}
    - schema2= {"组织机构类": ["抵押关系", "保证关系"]}
    ![image](https://user-images.githubusercontent.com/39394831/223603878-9de180ce-9e51-4cbb-b8a5-351648a00d2b.png)
  - 方法2：
    - 定义一种Span类型标签：抵押维度、保证维度。
    - Relation标签：抵押关系、保证关系。
    - schema1 = {"人物类": ["抵押关系", "保证关系"]}
    - schema2= {"组织机构类": ["抵押关系", "保证关系"]}
    ![image](https://user-images.githubusercontent.com/39394831/223605993-ab64875d-16e5-4315-ad5d-2cd88d6db0e5.png)
- 如果使用事件抽取：
  - 定义多种Span类型标签：抵押触发词、最高额保证触发词、连带责任保证触发词、保证责任触发词、保证人触发词、人物类、组织机构类。
  - Relation标签：人物、组织机构。
  - schema1 = {"抵押触发词": ["人物类", "组织机构类"]}]
  - schema2 = {"最高额保证触发词": ["人物类", "组织机构类"]}]
  - schema3 = {"连带责任保证触发词": ["人物类", "组织机构类"]}
  - schema4 = {"保证责任触发词": ["人物类", "组织机构类"]}
  - schema5 = {"保证人触发词": ["人物类", "组织机构类"]}
  ![image](https://user-images.githubusercontent.com/39394831/223607499-590b4baa-70c2-4d10-81e1-489907f045e1.png)

恳请给出一些专业意见，不胜感激。

**Comment by linjieccc** [comment]
@huzing2524 你好，建议采用关系抽取的形式，UIE关系抽取中prompt的构造主要由主体和关系类别决定，可以不用过多关注客体的标签类别，即标注为抵押维度、保证维度即可。事件抽取触发词字面相同的情况目前UIE还不支持（例如例子里存在两个抵押触发词）

**Comment by huzing2524** [comment]
> @huzing2524 你好，建议采用关系抽取的形式，UIE关系抽取中prompt的构造主要由主体和关系类别决定，可以不用过多关注客体的标签类别，即标注为抵押维度、保证维度即可。事件抽取触发词字面相同的情况目前UIE还不支持（例如例子里存在两个抵押触发词）

非常感谢！
