### ISSUE TITLE
部署UIE时，通过Infer_GPU方式推理如何设置fast_tokenizer

### ISSUE THREAD

**Issue by leon-cas** [PaddlePaddle/PaddleNLP#5154]
### 请提出你的问题

根据https://github.com/PaddlePaddle/PaddleNLP/tree/a13e8776d2032f8e1fbac0958a7d2109fe61b10c/model_zoo/uie  中的说明，通过taskflow的方式可以设置use_fast使用fast_tokenizer。由于部署服务的机器是只读的，不能生成.cache_info，从而不能使用该方式。

但通过infer_GPU方式进行服务推理，只需要vocab.txt和onnx model。  但通过这种方式推理如何设置使用fast_tokenizer?

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/6e20322d05860542948c0e5b7cae22acf968c592/model_zoo/uie/deploy/python/uie_predictor.py#L86 

在这个地方修改相关代码
```python
self._tokenizer = AutoTokenizer.from_pretrained(model_path，use_fast=True)
```

**Comment by leon-cas** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/6e20322d05860542948c0e5b7cae22acf968c592/model_zoo/uie/deploy/python/uie_predictor.py#L86
> 
> 在这个地方修改相关代码
> 
> ```python
> self._tokenizer = AutoTokenizer.from_pretrained(model_path，use_fast=True)
> ```

@wawltor 谢谢，问题已解决
