### ISSUE TITLE
[Question]: 使用信息抽取和文档智能时响应慢，占内存

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/PaddleNLP#5155]
### 请提出你的问题

使用文档智能和信息抽取功能时，发现存在等待时间长和占内存的问题。我的需求是打算批量执行，请问针对上述两个问题有没有优化的方案？

**Comment by zongzijiayou** [comment]
如果放在循环当中，每次调用执行，都会有一个加载到内存的过程，有没有可以缓存的方法？

**Comment by linjieccc** [comment]
@zongzijiayou 你好，可以通过服务化部署的方式将模型常驻在内存中 

参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/deploy/simple_serving

**Comment by zongzijiayou** [comment]
> @zongzijiayou 你好，可以通过服务化部署的方式将模型常驻在内存中
> 
> 参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/deploy/simple_serving

好的，看到了，谢谢，但是这个链接是针对信息抽取的，文档智能该应用的目录下没有看到是否可以服务化的说明，请问文档只能支持服务化吗

**Comment by zongzijiayou** [comment]
> @zongzijiayou 你好，可以通过服务化部署的方式将模型常驻在内存中
> 
> 参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/deploy/simple_serving

不好意思，认真看了文档后理解了

**Comment by Jaydon996** [comment]
> > @zongzijiayou 你好，可以通过服务化部署的方式将模型常驻在内存中
> > 参考：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/deploy/simple_serving
> 
> 不好意思，认真看了文档后理解了

你好，文档智能服务化部署了么，求求帮忙解答一下怎么部署的呗
