### ISSUE TITLE
[Question]: 没有找到gradio_seg2image_segmenter

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#5165]
### 请提出你的问题

请问目前controlnet支持的模型有哪些，分别在哪里下载
mlsd支持吗

**Comment by westfish** [comment]
gradio_seg2image_segmenter请关注最新的PR，
https://github.com/PaddlePaddle/PaddleNLP/pull/5156

目前controlnet支持的模型请参考，
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/controlnet
