### ISSUE TITLE
[Question]: uie微调训练，是否支持更换预训练模型？

### ISSUE THREAD

**Issue by jiaxintan123** [PaddlePaddle/PaddleNLP#5169]
### 请提出你的问题

在利用finetune进行微调训练时，将模型的model_name改为本地的预训练模型或者hg上的模型，发现训练时，eval的值都是0，想请问是否不支持更换除finetune.py中标注以外的模型？

**Comment by linjieccc** [comment]
@jiaxintan123 你好，建议基于UIE系列模型进行微调，基于其他预训练模型微调的话相当于重头开始训练UIE这套解码方式，可能不具备小样本迁移的能力

**Comment by jiaxintan123** [comment]
好的，谢谢您的回复。
