### ISSUE TITLE
[Question]: 单机双卡训练Erine-layout时卡住

### ISSUE THREAD

**Issue by charlesHsuGG** [PaddlePaddle/PaddleNLP#5174]
这边使用两张Tesla P100微调erine-layout run_mrc任务, 已经把batch size调小过依旧没有, 检查log也没抱任何错误就在储存checkpoint上系统卡了一个小时完全没动, 尝试过仅用单张卡就可以正常运行, 快疯了希望能得到协助。

代码完全按照官方[范例](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout) , 仅有修改输入数据。

运行单机多卡指令, `python -u paddle.distributed.launch run_mrc.py --example_json_path ./data/examples.json --prompt_path ./data/prompt.json --test_data_list_path ./data/test_dataset.json --model_name_or_path "./models/ernie-layoutx-base-uncased" --det_model_name_or_path "./models/ch_PP-OCRv3_det_infer" --cls_model_name_or_path "./models/ch_ppocr_mobile_v2.0_cls_infer" --ret_model_name_or_path "./models/ch_PP-OCRv3_rec_infer" --output_dir "./models/docvqa_zh/" --do_train --do_eval --do_pred --lang "ch" --num_train_epochs 6 --lr_scheduler_type linear --warmup_ratio 0.05 --weight_decay 0 --eval_steps 1000 --save_steps 1000 --save_total_limit 1 --load_best_model_at_end --pattern "mrc" --overwrite_cache false --doc_stride 128 --target_size 1000 --per_device_train_batch_size 4 --per_device_eval_batch_size 1 --learning_rate 2e-5 --preprocessing_num_workers 32 --save_total_limit 1 --train_nshard 16 --seed 1000 --metric_for_best_model anls --greater_is_better true --overwrite_output_dir`

日誌打印结果:

`loss: 1.56923511, learning_rate: 1.651e-05, global_step: 1000, interval_runtime: 425.8203, interval_samples_per_second: 9.394, interval_steps_per_second: 1.174, epoch: 1.2953

 22%|██▏       | 1000/4632 [14:12<51:00,  1.19it/s][32m[2023-03-09 10:48:32,595] [    INFO][0m - The following columns in the evaluation set  don't have a corresponding argument in `ErnieLayoutForQuestionAnswering.forward` and have been ignored: questions, question_id, token_to_orig_map, id, start_labels, token_is_max_context, end_labels, tokens. If questions, question_id, token_to_orig_map, id, start_labels, token_is_max_context, end_labels, tokens are not expected by `ErnieLayoutForQuestionAnswering.forward`,  you can safely ignore this message.[0m
[32m[2023-03-09 10:48:32,628] [    INFO][0m - ***** Running Evaluation *****[0m
[32m[2023-03-09 10:48:32,629] [    INFO][0m -   Num examples = 722[0m
[32m[2023-03-09 10:48:32,629] [    INFO][0m -   Total prediction steps = 361[0m
[32m[2023-03-09 10:48:32,629] [    INFO][0m -   Pre device batch size = 1[0m
[32m[2023-03-09 10:48:32,629] [    INFO][0m -   Total Batch size = 2[0m

  0%|          | 0/361 [00:00<?, ?it/s][A

  1%|          | 2/361 [00:00<00:19, 18.82it/s][A

  1%|          | 4/361 [00:00<00:30, 11.71it/s][A

  2%|▏         | 6/361 [00:00<00:33, 10.46it/s][A

  2%|▏         | 8/361 [00:00<00:35,  9.86it/s][A

  3%|▎         | 10/361 [00:00<00:36,  9.63it/s][A

  3%|▎         | 12/361 [00:01<00:37,  9.25it/s][A

  4%|▎         | 13/361 [00:01<00:37,  9.27it/s][A

  4%|▍         | 14/361 [00:01<00:37,  9.28it/s][A

  4%|▍         | 15/361 [00:01<00:37,  9.24it/s][A

  4%|▍         | 16/361 [00:01<00:37,  9.24it/s][A

  5%|▍         | 17/361 [00:01<00:37,  9.17it/s][A

  5%|▍         | 18/361 [00:01<00:37,  9.21it/s][A

  5%|▌         | 19/361 [00:01<00:36,  9.25it/s][A

  6%|▌         | 20/361 [00:02<00:37,  9.17it/s][A

  6%|▌         | 21/361 [00:02<00:36,  9.22it/s][A

  6%|▌         | 22/361 [00:02<00:37,  9.15it/s][A

  6%|▋         | 23/361 [00:02<00:36,  9.21it/s][A

  7%|▋         | 24/361 [00:02<00:36,  9.26it/s][A

  7%|▋         | 25/361 [00:02<00:36,  9.22it/s][A

  7%|▋         | 26/361 [00:02<00:36,  9.26it/s][A

  7%|▋         | 27/361 [00:02<00:35,  9.31it/s][A

  8%|▊         | 28/361 [00:02<00:36,  9.13it/s][A

  8%|▊         | 29/361 [00:03<00:36,  9.10it/s][A

  8%|▊         | 30/361 [00:03<00:36,  9.12it/s][A

  9%|▊         | 31/361 [00:03<00:35,  9.20it/s][A

  9%|▉         | 32/361 [00:03<00:35,  9.25it/s][A

  9%|▉         | 33/361 [00:03<00:35,  9.20it/s][A

  9%|▉         | 34/361 [00:03<00:36,  9.07it/s][A

 10%|▉         | 35/361 [00:03<00:35,  9.12it/s][A

 10%|▉         | 36/361 [00:03<00:35,  9.20it/s][A

 10%|█         | 37/361 [00:03<00:35,  9.17it/s][A

 11%|█         | 38/361 [00:04<00:35,  9.21it/s][A

 11%|█         | 39/361 [00:04<00:35,  9.20it/s][A

 11%|█         | 40/361 [00:04<00:35,  9.16it/s][A

 11%|█▏        | 41/361 [00:04<00:34,  9.20it/s][A

 12%|█▏        | 42/361 [00:04<00:34,  9.21it/s][A

 12%|█▏        | 43/361 [00:04<00:34,  9.20it/s][A

 12%|█▏        | 44/361 [00:04<00:34,  9.17it/s][A

 12%|█▏        | 45/361 [00:04<00:34,  9.19it/s][A

 13%|█▎        | 46/361 [00:04<00:34,  9.25it/s][A

 13%|█▎        | 47/361 [00:05<00:33,  9.30it/s][A

 13%|█▎        | 48/361 [00:05<00:33,  9.28it/s][A

 14%|█▎        | 49/361 [00:05<00:33,  9.28it/s][A

 14%|█▍        | 50/361 [00:05<00:33,  9.27it/s][A

 14%|█▍        | 51/361 [00:05<00:33,  9.28it/s][A

 14%|█▍        | 52/361 [00:05<00:33,  9.30it/s][A

 15%|█▍        | 53/361 [00:05<00:33,  9.33it/s][A

 15%|█▍        | 54/361 [00:05<00:33,  9.28it/s][A

 15%|█▌        | 55/361 [00:05<00:33,  9.18it/s][A

 16%|█▌        | 56/361 [00:05<00:33,  9.21it/s][A

 16%|█▌        | 57/361 [00:06<00:32,  9.24it/s][A

 16%|█▌        | 58/361 [00:06<00:33,  9.17it/s][A

 16%|█▋        | 59/361 [00:06<00:32,  9.20it/s][A

 17%|█▋        | 60/361 [00:06<00:32,  9.18it/s][A

 17%|█▋        | 61/361 [00:06<00:32,  9.22it/s][A

 17%|█▋        | 62/361 [00:06<00:32,  9.28it/s][A

 17%|█▋        | 63/361 [00:06<00:32,  9.30it/s][A

 18%|█▊        | 64/361 [00:06<00:31,  9.34it/s][A

 18%|█▊        | 65/361 [00:06<00:31,  9.34it/s][A

 18%|█▊        | 66/361 [00:07<00:31,  9.30it/s][A

 19%|█▊        | 67/361 [00:07<00:31,  9.29it/s][A

 19%|█▉        | 68/361 [00:07<00:31,  9.27it/s][A

 19%|█▉        | 69/361 [00:07<00:31,  9.25it/s][A

 19%|█▉        | 70/361 [00:07<00:31,  9.24it/s][A

 20%|█▉        | 71/361 [00:07<00:31,  9.22it/s][A

 20%|█▉        | 72/361 [00:07<00:31,  9.27it/s][A

 20%|██        | 73/361 [00:07<00:30,  9.31it/s][A

 20%|██        | 74/361 [00:07<00:30,  9.36it/s][A

 21%|██        | 75/361 [00:08<00:30,  9.35it/s][A

 21%|██        | 76/361 [00:08<00:30,  9.29it/s][A

 21%|██▏       | 77/361 [00:08<00:30,  9.31it/s][A

 22%|██▏       | 78/361 [00:08<00:30,  9.35it/s][A

 22%|██▏       | 79/361 [00:08<00:30,  9.38it/s][A

 22%|██▏       | 80/361 [00:08<00:29,  9.37it/s][A

 22%|██▏       | 81/361 [00:08<00:29,  9.34it/s][A

 23%|██▎       | 82/361 [00:08<00:30,  9.26it/s][A

 23%|██▎       | 83/361 [00:08<00:29,  9.30it/s][A

 23%|██▎       | 84/361 [00:08<00:30,  9.18it/s][A

 24%|██▎       | 85/361 [00:09<00:30,  9.17it/s][A

 24%|██▍       | 86/361 [00:09<00:38,  7.19it/s][A

 24%|██▍       | 87/361 [00:09<00:36,  7.55it/s][A

 24%|██▍       | 88/361 [00:09<00:34,  7.99it/s][A

 25%|██▍       | 89/361 [00:09<00:32,  8.37it/s][A

 25%|██▍       | 90/361 [00:09<00:31,  8.61it/s][A

 25%|██▌       | 91/361 [00:09<00:30,  8.79it/s][A

 25%|██▌       | 92/361 [00:09<00:30,  8.88it/s][A

 26%|██▌       | 93/361 [00:10<00:29,  8.99it/s][A

 26%|██▌       | 94/361 [00:10<00:29,  9.07it/s][A

 26%|██▋       | 95/361 [00:10<00:29,  9.09it/s][A

 27%|██▋       | 96/361 [00:10<00:28,  9.15it/s][A

 27%|██▋       | 97/361 [00:10<00:28,  9.22it/s][A

 27%|██▋       | 98/361 [00:10<00:28,  9.22it/s][A

 27%|██▋       | 99/361 [00:10<00:28,  9.28it/s][A

 28%|██▊       | 100/361 [00:10<00:28,  9.27it/s][A

 28%|██▊       | 101/361 [00:10<00:28,  9.17it/s][A

 28%|██▊       | 102/361 [00:11<00:28,  9.16it/s][A

 29%|██▊       | 103/361 [00:11<00:28,  9.11it/s][A

 29%|██▉       | 104/361 [00:11<00:27,  9.18it/s][A

 29%|██▉       | 105/361 [00:11<00:27,  9.21it/s][A

 29%|██▉       | 106/361 [00:11<00:27,  9.22it/s][A

 30%|██▉       | 107/361 [00:11<00:27,  9.19it/s][A

 30%|██▉       | 108/361 [00:11<00:27,  9.21it/s][A

 30%|███       | 109/361 [00:11<00:27,  9.25it/s][A

 30%|███       | 110/361 [00:11<00:27,  9.23it/s][A

 31%|███       | 111/361 [00:12<00:27,  9.20it/s][A

 31%|███       | 112/361 [00:12<00:26,  9.24it/s][A

 31%|███▏      | 113/361 [00:12<00:26,  9.28it/s][A

 32%|███▏      | 114/361 [00:12<00:26,  9.23it/s][A

 32%|███▏      | 115/361 [00:12<00:26,  9.12it/s][A

 32%|███▏      | 116/361 [00:12<00:27,  9.03it/s][A

 32%|███▏      | 117/361 [00:12<00:27,  9.02it/s][A

 33%|███▎      | 118/361 [00:12<00:26,  9.13it/s][A

 33%|███▎      | 119/361 [00:12<00:26,  9.21it/s][A

 33%|███▎      | 120/361 [00:13<00:26,  9.26it/s][A

 34%|███▎      | 121/361 [00:13<00:25,  9.27it/s][A

 34%|███▍      | 122/361 [00:13<00:25,  9.23it/s][A

 34%|███▍      | 123/361 [00:13<00:26,  9.03it/s][A

 34%|███▍      | 124/361 [00:13<00:26,  8.80it/s][A

 35%|███▍      | 125/361 [00:13<00:26,  8.83it/s][A

 35%|███▍      | 126/361 [00:13<00:26,  8.85it/s][A

 35%|███▌      | 127/361 [00:13<00:26,  8.99it/s][A

 35%|███▌      | 128/361 [00:13<00:25,  9.09it/s][A

 36%|███▌      | 129/361 [00:14<00:25,  9.14it/s][A

 36%|███▌      | 130/361 [00:14<00:25,  9.20it/s][A

 36%|███▋      | 131/361 [00:14<00:25,  9.15it/s][A

 37%|███▋      | 132/361 [00:14<00:24,  9.19it/s][A

 37%|███▋      | 133/361 [00:14<00:24,  9.22it/s][A

 37%|███▋      | 134/361 [00:14<00:24,  9.19it/s][A

 37%|███▋      | 135/361 [00:14<00:24,  9.23it/s][A

 38%|███▊      | 136/361 [00:14<00:24,  9.24it/s][A

 38%|███▊      | 137/361 [00:14<00:24,  9.26it/s][A

 38%|███▊      | 138/361 [00:14<00:23,  9.31it/s][A

 39%|███▊      | 139/361 [00:15<00:23,  9.35it/s][A

 39%|███▉      | 140/361 [00:15<00:23,  9.38it/s][A

 39%|███▉      | 141/361 [00:15<00:23,  9.31it/s][A

 39%|███▉      | 142/361 [00:15<00:23,  9.29it/s][A

 40%|███▉      | 143/361 [00:15<00:23,  9.16it/s][A

 40%|███▉      | 144/361 [00:15<00:24,  8.88it/s][A

 40%|████      | 145/361 [00:15<00:23,  9.02it/s][A

 40%|████      | 146/361 [00:15<00:23,  9.08it/s][A

 41%|████      | 147/361 [00:15<00:23,  9.15it/s][A

 41%|████      | 148/361 [00:16<00:23,  9.13it/s][A

 41%|████▏     | 149/361 [00:16<00:23,  9.17it/s][A

 42%|████▏     | 150/361 [00:16<00:22,  9.23it/s][A

 42%|████▏     | 151/361 [00:16<00:22,  9.23it/s][A

 42%|████▏     | 152/361 [00:16<00:23,  9.08it/s][A

 42%|████▏     | 153/361 [00:16<00:22,  9.16it/s][A

 43%|████▎     | 154/361 [00:16<00:22,  9.17it/s][A

 43%|████▎     | 155/361 [00:16<00:29,  7.08it/s][A

 43%|████▎     | 156/361 [00:17<00:27,  7.58it/s][A

 43%|████▎     | 157/361 [00:17<00:25,  8.04it/s][A

 44%|████▍     | 158/361 [00:17<00:24,  8.39it/s][A

 44%|████▍     | 159/361 [00:17<00:23,  8.67it/s][A

 44%|████▍     | 160/361 [00:17<00:22,  8.84it/s][A

 45%|████▍     | 161/361 [00:17<00:22,  8.97it/s][A

 45%|████▍     | 162/361 [00:17<00:22,  8.74it/s][A

 45%|████▌     | 163/361 [00:17<00:22,  8.91it/s][A

 45%|████▌     | 164/361 [00:17<00:21,  9.04it/s][A

 46%|████▌     | 165/361 [00:18<00:21,  9.03it/s][A

 46%|████▌     | 166/361 [00:18<00:21,  9.00it/s][A

 46%|████▋     | 167/361 [00:18<00:21,  8.93it/s][A

 47%|████▋     | 168/361 [00:18<00:22,  8.70it/s][A

 47%|████▋     | 169/361 [00:18<00:21,  8.87it/s][A

 47%|████▋     | 170/361 [00:18<00:21,  8.96it/s][A

 47%|████▋     | 171/361 [00:18<00:21,  9.04it/s][A

 48%|████▊     | 172/361 [00:18<00:20,  9.13it/s][A

 48%|████▊     | 173/361 [00:18<00:20,  9.17it/s][A

 48%|████▊     | 174/361 [00:19<00:20,  9.20it/s][A

 48%|████▊     | 175/361 [00:19<00:20,  9.20it/s][A

 49%|████▉     | 176/361 [00:19<00:20,  9.23it/s][A

 49%|████▉     | 177/361 [00:19<00:19,  9.22it/s][A

 49%|████▉     | 178/361 [00:19<00:19,  9.17it/s][A

 50%|████▉     | 179/361 [00:19<00:19,  9.20it/s][A

 50%|████▉     | 180/361 [00:19<00:19,  9.17it/s][A

 50%|█████     | 181/361 [00:19<00:19,  9.20it/s][A

 50%|█████     | 182/361 [00:19<00:19,  9.26it/s][A

 51%|█████     | 183/361 [00:20<00:19,  9.25it/s][A

 51%|█████     | 184/361 [00:20<00:19,  9.19it/s][A

 51%|█████     | 185/361 [00:20<00:19,  9.21it/s][A

 52%|█████▏    | 186/361 [00:20<00:18,  9.24it/s][A

 52%|█████▏    | 187/361 [00:20<00:18,  9.30it/s][A

 52%|█████▏    | 188/361 [00:20<00:18,  9.33it/s][A

 52%|█████▏    | 189/361 [00:20<00:18,  9.25it/s][A

 53%|█████▎    | 190/361 [00:20<00:18,  9.23it/s][A

 53%|█████▎    | 191/361 [00:20<00:18,  9.24it/s][A

 53%|█████▎    | 192/361 [00:20<00:18,  9.28it/s][A

 53%|█████▎    | 193/361 [00:21<00:18,  9.31it/s][A

 54%|█████▎    | 194/361 [00:21<00:18,  8.99it/s][A

 54%|█████▍    | 195/361 [00:21<00:18,  8.99it/s][A

 54%|█████▍    | 196/361 [00:21<00:18,  9.08it/s][A

 55%|█████▍    | 197/361 [00:21<00:17,  9.14it/s][A

 55%|█████▍    | 198/361 [00:21<00:17,  9.14it/s][A

 55%|█████▌    | 199/361 [00:21<00:17,  9.19it/s][A

 55%|█████▌    | 200/361 [00:21<00:17,  9.24it/s][A

 56%|█████▌    | 201/361 [00:21<00:17,  9.23it/s][A

 56%|█████▌    | 202/361 [00:22<00:17,  9.22it/s][A

 56%|█████▌    | 203/361 [00:22<00:17,  9.04it/s][A

 57%|█████▋    | 204/361 [00:22<00:17,  9.11it/s][A

 57%|█████▋    | 205/361 [00:22<00:17,  9.13it/s][A

 57%|█████▋    | 206/361 [00:22<00:16,  9.13it/s][A

 57%|█████▋    | 207/361 [00:22<00:16,  9.19it/s][A

 58%|█████▊    | 208/361 [00:22<00:16,  9.23it/s][A

 58%|█████▊    | 209/361 [00:22<00:16,  9.26it/s][A

 58%|█████▊    | 210/361 [00:22<00:16,  9.30it/s][A

 58%|█████▊    | 211/361 [00:23<00:16,  8.98it/s][A

 59%|█████▊    | 212/361 [00:23<00:16,  9.09it/s][A

 59%|█████▉    | 213/361 [00:23<00:16,  9.01it/s][A

 59%|█████▉    | 214/361 [00:23<00:16,  9.00it/s][A

 60%|█████▉    | 215/361 [00:23<00:16,  9.09it/s][A

 60%|█████▉    | 216/361 [00:23<00:16,  9.05it/s][A

 60%|██████    | 217/361 [00:23<00:15,  9.11it/s][A

 60%|██████    | 218/361 [00:23<00:15,  9.17it/s][A

 61%|██████    | 219/361 [00:23<00:15,  9.22it/s][A

 61%|██████    | 220/361 [00:24<00:15,  9.23it/s][A

 61%|██████    | 221/361 [00:24<00:15,  9.22it/s][A

 61%|██████▏   | 222/361 [00:24<00:15,  9.08it/s][A

 62%|██████▏   | 223/361 [00:24<00:15,  9.14it/s][A

 62%|██████▏   | 224/361 [00:24<00:14,  9.22it/s][A

 62%|██████▏   | 225/361 [00:24<00:14,  9.26it/s][A

 63%|██████▎   | 226/361 [00:24<00:14,  9.24it/s][A

 63%|██████▎   | 227/361 [00:24<00:14,  9.25it/s][A

 63%|██████▎   | 228/361 [00:24<00:14,  9.28it/s][A

 63%|██████▎   | 229/361 [00:25<00:14,  9.30it/s][A

 64%|██████▎   | 230/361 [00:25<00:14,  9.30it/s][A

 64%|██████▍   | 231/361 [00:25<00:13,  9.29it/s][A

 64%|██████▍   | 232/361 [00:25<00:13,  9.29it/s][A

 65%|██████▍   | 233/361 [00:25<00:13,  9.26it/s][A

 65%|██████▍   | 234/361 [00:25<00:13,  9.26it/s][A

 65%|██████▌   | 235/361 [00:25<00:13,  9.28it/s][A

 65%|██████▌   | 236/361 [00:25<00:13,  9.28it/s][A

 66%|██████▌   | 237/361 [00:25<00:13,  9.28it/s][A

 66%|██████▌   | 238/361 [00:25<00:13,  9.30it/s][A

 66%|██████▌   | 239/361 [00:26<00:13,  9.32it/s][A

 66%|██████▋   | 240/361 [00:26<00:12,  9.33it/s][A

 67%|██████▋   | 241/361 [00:26<00:12,  9.26it/s][A

 67%|██████▋   | 242/361 [00:26<00:13,  9.14it/s][A

 67%|██████▋   | 243/361 [00:26<00:12,  9.19it/s][A

 68%|██████▊   | 244/361 [00:26<00:12,  9.23it/s][A

 68%|██████▊   | 245/361 [00:26<00:12,  9.26it/s][A

 68%|██████▊   | 246/361 [00:26<00:12,  9.23it/s][A

 68%|██████▊   | 247/361 [00:26<00:12,  8.87it/s][A

 69%|██████▊   | 248/361 [00:27<00:12,  8.99it/s][A

 69%|██████▉   | 249/361 [00:27<00:12,  9.00it/s][A

 69%|██████▉   | 250/361 [00:27<00:12,  9.10it/s][A

 70%|██████▉   | 251/361 [00:27<00:12,  9.08it/s][A

 70%|██████▉   | 252/361 [00:27<00:11,  9.14it/s][A

 70%|███████   | 253/361 [00:27<00:11,  9.19it/s][A

 70%|███████   | 254/361 [00:27<00:11,  9.25it/s][A

 71%|███████   | 255/361 [00:27<00:11,  9.26it/s][A

 71%|███████   | 256/361 [00:27<00:11,  9.26it/s][A

 71%|███████   | 257/361 [00:28<00:11,  9.15it/s][A

 71%|███████▏  | 258/361 [00:28<00:11,  9.10it/s][A

 72%|███████▏  | 259/361 [00:28<00:11,  9.17it/s][A

 72%|███████▏  | 260/361 [00:28<00:11,  9.13it/s][A

 72%|███████▏  | 261/361 [00:28<00:10,  9.15it/s][A

 73%|███████▎  | 262/361 [00:28<00:10,  9.18it/s][A

 73%|███████▎  | 263/361 [00:28<00:10,  9.21it/s][A

 73%|███████▎  | 264/361 [00:28<00:10,  9.24it/s][A

 73%|███████▎  | 265/361 [00:28<00:10,  8.91it/s][A

 74%|███████▎  | 266/361 [00:29<00:10,  9.02it/s][A

 74%|███████▍  | 267/361 [00:29<00:10,  9.00it/s][A

 74%|███████▍  | 268/361 [00:29<00:10,  9.01it/s][A

 75%|███████▍  | 269/361 [00:29<00:10,  9.04it/s][A

 75%|███████▍  | 270/361 [00:29<00:10,  9.06it/s][A

 75%|███████▌  | 271/361 [00:29<00:09,  9.08it/s][A

 75%|███████▌  | 272/361 [00:29<00:09,  9.08it/s][A

 76%|███████▌  | 273/361 [00:29<00:09,  9.12it/s][A

 76%|███████▌  | 274/361 [00:29<00:09,  9.12it/s][A

 76%|███████▌  | 275/361 [00:30<00:09,  9.05it/s][A

 76%|███████▋  | 276/361 [00:30<00:09,  8.93it/s][A

 77%|███████▋  | 277/361 [00:30<00:09,  8.96it/s][A

 77%|███████▋  | 278/361 [00:30<00:09,  9.02it/s][A

 77%|███████▋  | 279/361 [00:30<00:09,  9.09it/s][A

 78%|███████▊  | 280/361 [00:30<00:08,  9.07it/s][A

 78%|███████▊  | 281/361 [00:30<00:09,  8.64it/s][A

 78%|███████▊  | 282/361 [00:30<00:08,  8.79it/s][A

 78%|███████▊  | 283/361 [00:30<00:09,  8.64it/s][A

 79%|███████▊  | 284/361 [00:31<00:08,  8.77it/s][A

 79%|███████▉  | 285/361 [00:31<00:08,  8.84it/s][A

 79%|███████▉  | 286/361 [00:31<00:08,  8.95it/s][A

 80%|███████▉  | 287/361 [00:31<00:08,  9.01it/s][A

 80%|███████▉  | 288/361 [00:31<00:08,  8.82it/s][A

 80%|████████  | 289/361 [00:31<00:08,  8.83it/s][A

 80%|████████  | 290/361 [00:31<00:07,  8.91it/s][A

 81%|████████  | 291/361 [00:31<00:07,  9.02it/s][A

 81%|████████  | 292/361 [00:31<00:07,  8.96it/s][A

 81%|████████  | 293/361 [00:32<00:07,  9.01it/s][A

 81%|████████▏ | 294/361 [00:32<00:07,  9.09it/s][A

 82%|████████▏ | 295/361 [00:32<00:07,  9.15it/s][A

 82%|████████▏ | 296/361 [00:32<00:07,  9.17it/s][A

 82%|████████▏ | 297/361 [00:32<00:07,  9.06it/s][A

 83%|████████▎ | 298/361 [00:32<00:06,  9.09it/s][A

 83%|████████▎ | 299/361 [00:32<00:06,  9.15it/s][A

 83%|████████▎ | 300/361 [00:32<00:06,  9.13it/s][A

 83%|████████▎ | 301/361 [00:32<00:06,  9.08it/s][A

 84%|████████▎ | 302/361 [00:33<00:06,  9.06it/s][A

 84%|████████▍ | 303/361 [00:33<00:06,  9.11it/s][A

 84%|████████▍ | 304/361 [00:33<00:06,  9.13it/s][A

 84%|████████▍ | 305/361 [00:33<00:06,  9.12it/s][A

 85%|████████▍ | 306/361 [00:33<00:05,  9.17it/s][A

 85%|████████▌ | 307/361 [00:33<00:05,  9.13it/s][A

 85%|████████▌ | 308/361 [00:33<00:05,  9.13it/s][A

 86%|████████▌ | 309/361 [00:33<00:05,  9.15it/s][A

 86%|████████▌ | 310/361 [00:33<00:05,  9.14it/s][A

 86%|████████▌ | 311/361 [00:34<00:05,  8.97it/s][A

 86%|████████▋ | 312/361 [00:34<00:05,  9.01it/s][A

 87%|████████▋ | 313/361 [00:34<00:05,  9.01it/s][A

 87%|████████▋ | 314/361 [00:34<00:05,  9.04it/s][A

 87%|████████▋ | 315/361 [00:34<00:05,  9.12it/s][A

 88%|████████▊ | 316/361 [00:34<00:04,  9.16it/s][A

 88%|████████▊ | 317/361 [00:34<00:04,  9.16it/s][A

 88%|████████▊ | 318/361 [00:34<00:04,  9.22it/s][A

 88%|████████▊ | 319/361 [00:34<00:04,  9.24it/s][A

 89%|████████▊ | 320/361 [00:35<00:04,  9.23it/s][A

 89%|████████▉ | 321/361 [00:35<00:04,  9.09it/s][A

 89%|████████▉ | 322/361 [00:35<00:04,  9.10it/s][A

 89%|████████▉ | 323/361 [00:35<00:04,  9.19it/s][A

 90%|████████▉ | 324/361 [00:35<00:04,  9.10it/s][A

 90%|█████████ | 325/361 [00:35<00:03,  9.16it/s][A

 90%|█████████ | 326/361 [00:35<00:03,  9.19it/s][A

 91%|█████████ | 327/361 [00:35<00:03,  9.17it/s][A

 91%|█████████ | 328/361 [00:35<00:03,  9.16it/s][A

 91%|█████████ | 329/361 [00:36<00:03,  9.22it/s][A

 91%|█████████▏| 330/361 [00:36<00:03,  9.27it/s][A

 92%|█████████▏| 331/361 [00:36<00:03,  9.31it/s][A

 92%|█████████▏| 332/361 [00:36<00:03,  9.07it/s][A

 92%|█████████▏| 333/361 [00:36<00:03,  9.17it/s][A

 93%|█████████▎| 334/361 [00:36<00:02,  9.22it/s][A

 93%|█████████▎| 335/361 [00:36<00:02,  9.01it/s][A

 93%|█████████▎| 336/361 [00:36<00:02,  8.90it/s][A

 93%|█████████▎| 337/361 [00:36<00:02,  8.99it/s][A

 94%|█████████▎| 338/361 [00:37<00:02,  9.00it/s][A

 94%|█████████▍| 339/361 [00:37<00:02,  9.12it/s][A

 94%|█████████▍| 340/361 [00:37<00:02,  9.14it/s][A

 94%|█████████▍| 341/361 [00:37<00:02,  9.21it/s][A

 95%|█████████▍| 342/361 [00:37<00:02,  9.21it/s][A

 95%|█████████▌| 343/361 [00:37<00:01,  9.20it/s][A

 95%|█████████▌| 344/361 [00:37<00:01,  9.21it/s][A

 96%|█████████▌| 345/361 [00:37<00:01,  9.25it/s][A

 96%|█████████▌| 346/361 [00:37<00:01,  9.11it/s][A

 96%|█████████▌| 347/361 [00:37<00:01,  9.17it/s][A

 96%|█████████▋| 348/361 [00:38<00:01,  9.16it/s][A

 97%|█████████▋| 349/361 [00:38<00:01,  9.12it/s][A

 97%|█████████▋| 350/361 [00:38<00:01,  8.90it/s][A

 97%|█████████▋| 351/361 [00:38<00:01,  8.87it/s][A

 98%|█████████▊| 352/361 [00:38<00:01,  8.95it/s][A

 98%|█████████▊| 353/361 [00:38<00:00,  9.05it/s][A

 98%|█████████▊| 354/361 [00:38<00:00,  8.88it/s][A

 98%|█████████▊| 355/361 [00:38<00:00,  9.03it/s][A

 99%|█████████▊| 356/361 [00:38<00:00,  9.09it/s][A

 99%|█████████▉| 357/361 [00:39<00:00,  9.12it/s][A

 99%|█████████▉| 358/361 [00:39<00:00,  9.18it/s][A

 99%|█████████▉| 359/361 [00:39<00:00,  9.23it/s][A

100%|█████████▉| 360/361 [00:39<00:00,  9.29it/s][A

100%|██████████| 361/361 [00:39<00:00,  9.32it/s][A
                                                   

                                                 
[Aeval_anls: 37.61981976698725, epoch: 1.2953

 22%|██▏       | 1000/4632 [14:55<51:00,  1.19it/s]

100%|██████████| 361/361 [00:43<00:00,  9.32it/s][A

[2023-03-09 10:49:16,312] [    INFO][0m - Saving model checkpoint to ./models/docvqa_zh/checkpoint-1000[0m
[32m[2023-03-09 10:49:16,314] [    INFO][0m - Configuration saved in ./models/docvqa_zh/checkpoint-1000/config.json[0m
[32m[2023-03-09 10:49:17,882] [    INFO][0m - tokenizer config file saved in ./models/docvqa_zh/checkpoint-1000/tokenizer_config.json[0m
[32m[2023-03-09 10:49:17,883] [    INFO][0m - Special tokens file saved in ./models/docvqa_zh/checkpoint-1000/special_tokens_map.json[0m`

硬体配置:

`Thu Mar  9 12:43:36 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000001:00:00.0 Off |                    0 |
| N/A   33C    P0    31W / 250W |   11364MiB / 16384MiB |      100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000002:00:00.0 Off |                    0 |
| N/A   30C    P0    25W / 250W |      11364MiB / 16384MiB |      100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|`

已经把batch size 调至 4 CUDA momory也没有占满, 唯一发现仅有GPU-Util都冲到100%就卡住了, 完全没有任何错误信息。

**Comment by linjieccc** [comment]
@charlesHsuGG 从训练日志来看，任务可以完整跑完一个epoch + 一轮评估流程？

**Comment by charlesHsuGG** [comment]
@linjieccc 对的, 但是跑完一轮就自己卡死了, 我这边是用paddlepaddle-gpu==2.4.2.post117这个版本, 不确定是否是多序卡GPU或是paddlenlp的trainer有做什麽设置, 但是我这边仅用一张P100是可以跑完完整的训练加评估的, 这边有尝试过测试nccl也是正常可以双卡可以互相通讯, 在麻烦看看是哪一部分有问题了

**Comment by linjieccc** [comment]
我这边没能复现出这个问题，有尝试过在其他任务上进行多卡训练么
