### ISSUE TITLE
[Question]: NLP服务化，官方给的例子是信息抽取的，请问文档智能服务化，客户端传参json结构是什么？

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/PaddleNLP#5178]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/50578167/224213842-2275b61b-8f28-49df-a7bf-602374517f6c.png)
这是信息抽取的传参例子，

文档智能服务化时，我不知道怎么传参，我想把以下区域当作参数动态传递
![image](https://user-images.githubusercontent.com/50578167/224214311-a65b34c9-bd65-4b9d-b7c3-cd5f18c786ed.png)

**Comment by zongzijiayou** [comment]
![image](https://user-images.githubusercontent.com/50578167/224214662-28da6724-0730-48c9-920f-18a3baade8bf.png)

这是我目前尝试的结果

**Comment by zongzijiayou** [comment]
![image](https://user-images.githubusercontent.com/50578167/224217760-bee99b06-273d-4f15-a245-2a999e244628.png)

还有这个workers 该参数如何去使用？它的含义是什么？

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/4944  可以参考一下这个

workers是接收请求的进程数

**Comment by zongzijiayou** [comment]
> #4944 可以参考一下这个
> 
> workers是接收请求的进程数

谢谢
