### ISSUE TITLE
您好，需要增加基于attentiond的解释

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5181]
### Feature request

层次文本分类任务需要输出attention权重分数，赋予结果基于attention的可解释性

### Motivation

有关，赋予结果基于attention的可解释性

### Your contribution

no,thanks

**Comment by lugimzzz** [comment]
你是需要attention分数，还是只是要一个可解释性分析？可解释性分析可以直接参考这个链接https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical/analysis#%E5%8D%95%E8%AF%8D%E7%BA%A7%E5%88%AB%E5%8F%AF%E8%A7%A3%E9%87%8A%E6%80%A7%E5%88%86%E6%9E%90
![image](https://user-images.githubusercontent.com/63761690/224271763-adfae999-eb1c-42b0-8e02-bb9968e1b00d.png)

**Comment by QChen0409** [comment]
请问这个解释的原理是什么？想要基于attention的解释&nbsp;


1624140190
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月10日(星期五) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] 您好，需要增加基于attentiond的解释 (Issue #5181)





 
你是需要attention分数，还是只是要一个可解释性分析？可解释性分析可以直接参考这个链接https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/hierarchical/analysis#%E5%8D%95%E8%AF%8D%E7%BA%A7%E5%88%AB%E5%8F%AF%E8%A7%A3%E9%87%8A%E6%80%A7%E5%88%86%E6%9E%90
