### ISSUE TITLE
[Question]: ernie-3.0-xbase模型下载

### ISSUE THREAD

**Issue by bill4689** [PaddlePaddle/PaddleNLP#5192]
### 请提出你的问题

Downloading from https://paddlenlp.bj.bcebos.com/models/transformers/community/ernie-3.0-xbase-zh/model_state.pdparams failed with code 404!

**Comment by bill4689** [comment]
这个网址下载不下来模型参数

**Comment by wawltor** [comment]
更新一下PaddleNLP的版本，同时执行下面的代码
```
from paddlenlp.transformers import AutoModel
ernie = AutoModel.from_pretrained('ernie-3.0-xbase-zh')
```

具体的下载地址 ： https://bj.bcebos.com/paddlenlp/models/transformers/ernie_3.0/ernie_3.0_xbase_zh.pdparams
