### ISSUE TITLE
请问ERNIE有最大长度限制吗？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5195]
### 请提出你的问题

请问ERNIE有最大文本长度限制吗？max_length指的是文本有多少个字符还是分词后有多少个词呢？

**Comment by wawltor** [comment]
ERNIE 3.0系列的模型最大长度限制是2048；max_length是指tokenizer处理后的字符长度

**Comment by wawltor** [comment]
您好，我们将关闭该issue，如有因为可以再次打开该issue。
