### ISSUE TITLE
[Question]: 请问加载自有数据集微调uie的时候，卡在数据读取，无限增加内存消耗

### ISSUE THREAD

**Issue by ykallan** [PaddlePaddle/PaddleNLP#5196]
### 请提出你的问题

你好，这是我的程序denmo：
`链接：https://pan.baidu.com/s/18Sx0FydPxoBy86d0c7b8nw?pwd=a5c6 
提取码：a5c6 
--来自百度网盘超级会员V5的分享`

我在训练的时候，使用这个原本附带的数据样例（data文件夹），可以进行微调，前几天也可以使用我自己的数据进行训练（data2文件夹），但是昨天开始，使用我自己的数据集进行训练的时候，会一直加载训练集，并且内存会持续走高，几十兆的训练集，会吃满32g内存，这是我训练的时候的日志：

`C:\Users\k\.conda\envs\paddle\python.exe D:/nlp_about/UIE-Finance-org-Finetune_old/UIE-Finance-org-Finetune/finetune.py
C:\Users\k\.conda\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\k\.conda\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023-03-12 11:14:45,590] [    INFO] - prepair parser finished, start load datas
[2023-03-12 11:14:45,591] [    INFO] - Downloading resource files...
100%|██████████| 69980/69980 [00:03<00:00, 21460.60it/s]
100%|██████████| 1/1 [00:00<00:00, 1014.83it/s]
100%|██████████| 183/183 [00:00<00:00, 761.14it/s]
100%|██████████| 1/1 [00:00<00:00, 974.74it/s]
100%|██████████| 1/1 [00:00<00:00, 995.80it/s]
[2023-03-12 11:14:51,051] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'uie-nano'.
W0312 11:14:51.071393  6088 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0312 11:14:51.074384  6088 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
[2023-03-12 11:14:52,095] [    INFO] - loading datas...
Traceback (most recent call last):
  File "D:\nlp_about\UIE-Finance-org-Finetune_old\UIE-Finance-org-Finetune\finetune.py", line 193, in <module>
    do_train()
  File "D:\nlp_about\UIE-Finance-org-Finetune_old\UIE-Finance-org-Finetune\finetune.py", line 51, in do_train
    train_ds = load_dataset(reader,
  File "C:\Users\k\.conda\envs\paddle\lib\site-packages\paddlenlp\datasets\dataset.py", line 196, in load_dataset
    return reader_instance.read(**custom_kwargs)
  File "C:\Users\k\.conda\envs\paddle\lib\site-packages\paddlenlp\datasets\dataset.py", line 833, in read
    return MapDataset(list(examples))
  File "D:\nlp_about\UIE-Finance-org-Finetune_old\UIE-Finance-org-Finetune\utils.py", line 213, in reader
    if len(result_list) == 0:
KeyboardInterrupt`

后面的error，是我自己停止了训练。

全量数据集使用check_data.py脚本检查过，不清楚是什么问题，导致卡在加载训练集一直不能训练。

**Comment by linjieccc** [comment]
@ykallan 你好，你的paddlenlp版本是多少呢？可以先试试更新下微调代码以及paddlenlp版本

**Comment by ykallan** [comment]
@linjieccc 你好，paddle版本与paddlenlp版本均为2.4.2，环境中其他包版本，保存在pip_list.txt问价中

**Comment by ykallan** [comment]
@linjieccc 以下是我环境中的包版本：
(paddle) D:\nlp_about\UIE-Finance-org-Finetune_old\UIE-Finance-org-Finetune>pip list
Package            Version
------------------ -------------
aiohttp            3.8.4
aiosignal          1.3.1
anyio              3.6.2
astor              0.8.1
async-timeout      4.0.2
attrs              22.2.0
Babel              2.12.1
bce-python-sdk     0.8.79
brotlipy           0.7.0
certifi            2022.12.7
cffi               1.15.1
charset-normalizer 2.1.1
click              8.1.3
colorama           0.4.6
colorlog           6.7.0
contourpy          1.0.7
cryptography       39.0.2
cycler             0.11.0
datasets           2.10.1
decorator          5.1.1
dill               0.3.4
fastapi            0.92.0
filelock           3.9.0
Flask              2.2.3
Flask-Babel        2.0.0
fonttools          4.38.0
frozenlist         1.3.3
fsspec             2023.3.0
future             0.18.3
h11                0.14.0
huggingface-hub    0.12.1
idna               3.4
itsdangerous       2.1.2
jieba              0.42.1
Jinja2             3.1.2
joblib             1.2.0
kiwisolver         1.4.4
markdown-it-py     2.2.0
MarkupSafe         2.1.2
matplotlib         3.7.1
mdurl              0.1.2
multidict          6.0.4
multiprocess       0.70.12.2
numpy              1.24.2
opencv-python      4.7.0.72
opt-einsum         3.3.0
packaging          23.0
paddle-bfloat      0.1.7
paddle2onnx        1.0.5
paddlefsl          1.1.0
paddlenlp          2.4.2
paddlepaddle-gpu   2.4.2.post117
pandas             1.5.3
Pillow             9.4.0
pip                23.0.1
protobuf           3.20.0
pyarrow            11.0.0
pycparser          2.21
pycryptodome       3.17
pydantic           1.10.5
Pygments           2.14.0
pyOpenSSL          23.0.0
pyparsing          3.0.9
PySocks            1.7.1
python-dateutil    2.8.2
pytz               2022.7.1
PyYAML             6.0
requests           2.28.2
responses          0.18.0
rich               13.3.2
scikit-learn       1.2.1
scipy              1.10.1
sentencepiece      0.1.97
seqeval            1.2.2
setuptools         67.4.0
six                1.16.0
sniffio            1.3.0
starlette          0.25.0
threadpoolctl      3.1.0
tqdm               4.65.0
typer              0.7.0
typing_extensions  4.5.0
urllib3            1.26.14
uvicorn            0.20.0
visualdl           2.4.2
Werkzeug           2.2.3
wheel              0.38.4
win-inet-pton      1.1.0
xxhash             3.2.0
yarl               1.8.2

**Comment by linjieccc** [comment]
请尝试升级paddlenlp到2.5.2版本，另外同步拉一下最新的微调代码 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie

**Comment by ykallan** [comment]
@linjieccc 请问paddlenlp 2.5.2版本是否适配paddle-gpu==2.4.2版本，目前多个环境都在使用paddle-gpu==2.4.2，更换paddle-gpu版本成本较大。。

**Comment by linjieccc** [comment]
可以适配，paddlepaddle 2.4.2版本可以保持不变
