### ISSUE TITLE
如何载入保存训练好的模型？

### ISSUE THREAD

**Issue by Ryan906k9** [PaddlePaddle/PaddleNLP#52]
使用了预训练模型进行 finetune：
```
import paddlenlp as ppnlp

# 设置想要使用模型的名称
MODEL_NAME = "ernie-1.0"

ernie_model = ppnlp.transformers.ErnieModel.from_pretrained(MODEL_NAME)
model = ppnlp.transformers.ErnieForTokenClassification.from_pretrained(MODEL_NAME, num_classes=train_ds.num_label)
tokenizer = ppnlp.transformers.ErnieTokenizer.from_pretrained(MODEL_NAME)

```

训练完成后：

```
model.save_pretrained('./checkpoint')
tokenizer.save_pretrained('./checkpoint')
```

请问训练完成后应该如何加载保存的模型？

**Comment by guoshengCS** [comment]
和`model.save_pretrained('./checkpoint')`及`tokenizer.save_pretrained('./checkpoint')`对应，使用`model.from_pretrained('./checkpoint')`及`tokenizer.from_pretrained('./checkpoint')`就可以了

**Comment by guoshengCS** [comment]
`model.from_pretrained`和`tokenizer.from_pretrained`是支持按照`bert-base-uncased`这种模型名称或者本地训练模型的路径来导入模型的

**Comment by guoshengCS** [comment]
另外通过
```python
model.save_pretrained('./checkpoint')
tokenizer.save_pretrained('./checkpoint')
```
保存下来的内容（如下）中的`model_state.pdparams`是通过Paddle原生的[save接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/framework/io/save_cn.html#save)保存的，也可以使用Paddle原生的[load接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/framework/io/load_cn.html#load)来加载
```
-rw-r--r-- 1 root root  416 Mar  2 07:56 model_config.json
-rw-r--r-- 1 root root 632M Mar  2 07:56 model_state.pdparams
-rw-r--r-- 1 root root  141 Mar  2 07:56 tokenizer_config.json
-rw-r--r-- 1 root root 227K Mar  2 07:56 vocab.txt
```

**Comment by Ryan906k9** [comment]
> 另外通过
> 
> ```python
> model.save_pretrained('./checkpoint')
> tokenizer.save_pretrained('./checkpoint')
> ```
> 
> 保存下来的内容（如下）中的`model_state.pdparams`是通过Paddle原生的[save接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/framework/io/save_cn.html#save)保存的，也可以使用Paddle原生的[load接口](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/framework/io/load_cn.html#load)来加载
> 
> ```
> -rw-r--r-- 1 root root  416 Mar  2 07:56 model_config.json
> -rw-r--r-- 1 root root 632M Mar  2 07:56 model_state.pdparams
> -rw-r--r-- 1 root root  141 Mar  2 07:56 tokenizer_config.json
> -rw-r--r-- 1 root root 227K Mar  2 07:56 vocab.txt
> ```

谢谢！
