### ISSUE TITLE
对 crf （paddlenlp.layers.LinearChainCrf） 的文档疑问

### ISSUE THREAD

**Issue by 15814** [PaddlePaddle/PaddleNLP#520]
[crf文档链接](https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.layers.crf.html) 

LinearChainCrf(num_labels, crf_lr=0.1, with_start_stop_tag=True) 中的 crf_lr 的含义究竟是什么？比如说 我将这里的 crf层 组成 bilstm-crf 后，optimizer 那里会设置一个全局学习率lr，这里也有一个 crf_lr, 那么 crf layer 参数更新时的学习率是 crf_lr， 还是 lr*crf_lr ?  

我看了一下源码，好似更倾向于后者。希望得到开发者的确认，谢谢。建议在文档里对这一参数增加说明以使文档描述更清晰准确。

**Comment by joey12300** [comment]
@15814 您好，crf层的学习率是lr*crf_lr。感谢您提供的建议:)

**Comment by yingyibiao** [comment]
感谢您的提问和建议，我们的文档还在持续迭代完善中，欢迎提出更多的意见和建议！
