### ISSUE TITLE
[Question]: multi_class/ inference时，想输出每个标签及其对应的confidence

### ISSUE THREAD

**Issue by White2White** [PaddlePaddle/PaddleNLP#5201]
### 请提出你的问题

cls = Taskflow("text_classification", task_path='checkpoint/export', is_static_model=True)
cls(["黑苦荞茶的功效与作用及食用方法","幼儿挑食的生理原因是"])
# [{'predictions': [{'label': '功效作用', 'score': 0.9683999621710758}], 'text': '黑苦荞茶的功效与作用及食用方法'}, {'predictions': [{'label': '病因分析', 'score': 0.5204789523701855}], 'text': '幼儿挑食的生理原因是'}]

以示例为例，希望predictions里面有topN的label及其confidence或者全部label及confidence，有什么方法吗

**Comment by lugimzzz** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/text_classification.py#L339
![image](https://user-images.githubusercontent.com/63761690/224883477-c4021f92-9604-4391-b8db-c2684eaf63f2.png)

建议你自己修改一下预测的源码，这块我们可以考虑后续添加相关功能
```
for score, label in zip(scores, labels):
    postprocessed_output = {}
    if self.id2label is None:
        postprocessed_output["predictions"] = [{"label": label, "score": score[label],"all_score":score}]
    else:
        postprocessed_output["predictions"] = [{"label": self.id2label[label], "score": score[label],"all_score":score}]
```
