### ISSUE TITLE
[Question]: 数据增强模块的反义词表为空，无法进行反义词改写 ？

### ISSUE THREAD

**Issue by Tellyang7** [PaddlePaddle/PaddleNLP#5204]
### 请提出你的问题

按照[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/dataaug.md](url)给出的词替换api，同义词可以正常执行，但是反义词返回为空，结果如图：
![antonym空](https://user-images.githubusercontent.com/24445133/224632541-3f175536-83c7-423a-96d5-1deb0737f68b.PNG)

paddlenlp 2.4.1
paddlepaddle 2.3.2

**Comment by lugimzzz** [comment]
建议你更新一下paddlenlp的版本到最新版本pip install paddlenlp==2.5.2。版本paddlenlp 2.4.1 应该还不支持反义词
![image](https://user-images.githubusercontent.com/63761690/224648151-7a5300c0-09be-4aaf-8442-85aa1d540dd9.png)

**Comment by Tellyang7** [comment]
> pip install paddlenlp==2.5.2

确实是这样，更新后问题解决了：
`if aug_type in ["antonym", "embedding", "synonym", "homonym", "custom"]:`
之前是：
`if aug_type in ["synonym", "homonym", "custom"]:`

感谢。
