### ISSUE TITLE
[Question]: 使用自定义数据集报错

### ISSUE THREAD

**Issue by Hadesong** [PaddlePaddle/PaddleNLP#5207]
### 请提出你的问题

报错信息
![屏幕截图 2023-03-13 181255.png](https://img1.imgtp.com/2023/03/13/3VuQ0Gcj.png)

finetune模型：unified_transformer-12L-cn-luge
数据集：使用的duconv，保留小部分数据用以测试

按照 [从本地文件创建数据集](https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html#id2) 方法，在finetune.py 中添加read方法

![屏幕截图 2023-03-13 181114.png](https://img1.imgtp.com/2023/03/13/zuctfUzL.png)

![屏幕截图 2023-03-13 181130.png](https://img1.imgtp.com/2023/03/13/fMdsavYU.png)

**Comment by FrostML** [comment]
这份文档比较早期了，可以先试试换成 `from paddlenlp.datasets import load_dataset` 试试看
