### ISSUE TITLE
BERT glue任务在windows系统执行错误

### ISSUE THREAD

**Issue by GetUsernametsy** [PaddlePaddle/PaddleNLP#521]
Windows 环境 预训练模型训练后 首先把用export_model.py转换模型 

![QQ图片20210608172018](https://user-images.githubusercontent.com/24663912/121159570-df6f1b80-c87d-11eb-8707-3a0c44ea9e76.png)
然后用predict.py 加载模型  报错
![QQ图片20210608171758](https://user-images.githubusercontent.com/24663912/121159759-0cbbc980-c87e-11eb-8b06-cd763e76342b.png)

**Comment by wawltor** [comment]
这是修复PR https://github.com/PaddlePaddle/PaddleNLP/pull/525， 辛苦验证一下效果

**Comment by ZeyuChen** [comment]
Solved by #525
