### ISSUE TITLE
diffusion支持dreamlike-art

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleNLP#5211]
### 简要描述

模型地址
https://huggingface.co/dreamlike-art/dreamlike-diffusion-1.0

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

该模型生成图像细腻 人物处理较好

**Comment by JunnYu** [comment]
如果您需要这个权重的话
- 可以参考这里 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/scripts/convert_diffusers_model 的教程尝试进行转换。
- 也可以等晚些时候，我这里会将这部分权重上传上来
