### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by Monstercat-023** [PaddlePaddle/PaddleNLP#5223]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/116543487/224926505-ee412a4c-018d-4090-9d3b-4c8517636fd7.png)

**Comment by Monstercat-023** [comment]
运行的文本分类应用

**Comment by Monstercat-023** [comment]
运行的是多标签分类

**Comment by Monstercat-023** [comment]
还有一个小问题
![image](https://user-images.githubusercontent.com/116543487/224931581-0e9da1ea-0970-499e-9af6-66731f3260fd.png)
我训练模型后他只会在指定文件夹生成一个setting.txt文件，训练模型不知道为什么跑到
C:\Users\xxx\.paddlenlp\models\ernie-3.0-base-zh里面去了，运行模型评估的模型文件是手动粘到checkpoint文件夹的

**Comment by Monstercat-023** [comment]
尝试更新了一下模块之后还是抱错AttributeError: Unable to parse 'architectures' or 'init_class' from ./checkpoint/config.json. Also unable to infer model class from 'pretrained_model_name_or_path'

**Comment by lugimzzz** [comment]
请提供一下paddlenlp和paddlepaddle，建议使用最新paddlenlp版本

**Comment by Monstercat-023** [comment]
paddlehub | 2.3.1 |  
paddlenlp | 2.5.2 |  
paddlepaddle-gpu | 2.4.2.post117 |

**Comment by Monstercat-023** [comment]
> 请提供下paddlenlp和paddlepaddle，建议使用最新paddlenlp版本

桨毂 | 2.3.1 |  
桨叶 | 2.5.2 |  
paddlepaddle-gpu | 2.4.2.post117 |

**Comment by Monstercat-023** [comment]
> 请提供一下paddlenlp和paddlepaddle，建议使用最新paddlenlp版本
paddlehub | 2.3.1 | 2.3.1
paddlenlp | 2.5.2 | 2.5.2
paddlepaddle-gpu | 2.4.2.post117 | 2.4.2

**Comment by Monstercat-023** [comment]
> 请提供一下paddlenlp和paddlepaddle，建议使用最新paddlenlp版本

我觉的不是版本的问题

**Comment by Monstercat-023** [comment]
> 请提供一下paddlenlp和paddlepaddle，建议使用最新paddlenlp版本

paddlehub | 2.3.1 | 2.3.1
paddlenlp | 2.5.2 | 2.5.2
paddlepaddle-gpu | 2.4.2.post117 | 2.4.

**Comment by kg-nlp** [comment]
这个问题有解决了吗,我增量训练完 ernie-3.0-medium-zh ,在使用AutoModelForSequenceClassification.from_pretrained(model_args.model_name_or_path, num_classes=num_classes)的时候同样报这个错误

**Comment by Adherer** [comment]
> 尝试更新了一下模块之后还是抱错AttributeError: Unable to parse 'architectures' or 'init_class' from ./checkpoint/config.json. Also unable to infer model class from 'pretrained_model_name_or_path'

这个问题解决了吗？我在尝试合并lora权重的时候，报的这个错误

**Comment by Adherer** [comment]
> 这个问题有解决了吗,我增量训练完 ernie-3.0-medium-zh ,在使用AutoModelForSequenceClassification.from_pretrained(model_args.model_name_or_path, num_classes=num_classes)的时候同样报这个错误

这个问题解决了吗？我在尝试合并lora权重的时候，报的这个错误
