### ISSUE TITLE
[Question]: 强烈建议开源一个pipelines导入数据自动化脚本

### ISSUE THREAD

**Issue by WangShunzhiDQ** [PaddlePaddle/PaddleNLP#5224]
### 请提出你的问题

文档报告格式正常就是一个段落一个段落挨着，中间不会有空行。而目前pipelines需要处理报告每段后面加空行，很麻烦啊！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by 1649759610** [comment]
请说明下用的是哪个Pipeline功能呢？

**Comment by WangShunzhiDQ** [comment]
用的语义检索功能，左侧上传docx和pdf报告的时候，解析的不好，谢谢


 
发件人： Milen
发送时间： 2023-03-14 20:16
收件人： PaddlePaddle/PaddleNLP
抄送： WangShunzhiDQ; Author
主题： Re: [PaddlePaddle/PaddleNLP] [Question]: 强烈建议开源一个pipelines导入数据自动化脚本 (Issue #5224)
请说明下用的是哪个Pipeline功能呢？

**Comment by 1649759610** [comment]
好的，很赞的提议，感谢反馈。
