### ISSUE TITLE
[Question]: text_correction不训练

### ISSUE THREAD

**Issue by wuyuziAb** [PaddlePaddle/PaddleNLP#5227]
### 请提出你的问题

运行python train.py --batch_size 32 --logging_steps 100 --epochs 10 --learning_rate 5e-5 --model_name_or_path ernie-1.0-base-zh --output_dir ./checkpoints/ --extra_train_ds_dir ./extra_train_ds/ --max_seq_length 192后报  [ WARNING] - Some weights of the model checkpoint at ernie-1.0-base-zh were not used when initializing ErnieModel: ['cls.pre
dictions.transform.weight', 'cls.predictions.layer_norm.weight', 'cls.predictions.transform.bias', 'cls.predictions.decoder_bias', 'cls.predictions.la
yer_norm.bias']
- This IS expected if you are initializing ErnieModel from the checkpoint of a model trained on another task or with another architecture (e.g. initia
lizing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ErnieModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertF
orSequenceClassification model from a BertForSequenceClassification model).
[2023-03-14 15:26:24,703] [ WARNING] - Some weights of ErnieModel were not initialized from the model checkpoint at ernie-1.0-base-zh and are newly in
itialized: ['ernie.embeddings.task_type_embeddings.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
然后不训练。

**Comment by 1649759610** [comment]
你好，看起来权重和加载的模型有些diff，当前在执行什么任务，用的什么脚本，模型是什么，可以多描述一些背景，最好提供下可复现的代码，帮助定位问题。

**Comment by wuyuziAb** [comment]
你好，首先感谢回复，当前执行的是text_correction任务，模型是ernie1.0，按照readme教程进行的，执行到单卡训练那一步就报上面的warning，然后不训练。具体的页面在https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_correction/ernie-csc。

**Comment by 1649759610** [comment]
你好，上边的报的warning是不影响训练的，不会阻塞训练进程的；另外本地启动了下任务，是可以正常训练的。

上边提到的不训练是指？会不会出现类似下面的信息？使用的paddlenlp版本是什么呢？

```
global step 100, epoch: 0, batch: 100, loss: 7.568213, speed: 2.78 step/s
```

**Comment by wuyuziAb** [comment]
你好，不会出现你说出现的信息，只有一条[2023-03-15 19:28:55,634] [    INFO] - Total training step: 87940
然后我看任务管理器GPU内存动了几十秒然后就结束了，没有你给的信息。
