### ISSUE TITLE
[Question]: It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled

### ISSUE THREAD

**Issue by ChinaGPT** [PaddlePaddle/PaddleNLP#5228]
转换模型：fd_pipe = FastDeployStableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5@fastdeploy")

出现报错：It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled

**Comment by JunnYu** [comment]
你好，这不是报错，建议你参考这里的部署流程，重新导出一下模型https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/deploy
