### ISSUE TITLE
[Bug]: 小样本场景下的多标签分类

### ISSUE THREAD

**Issue by Monstercat-023** [PaddlePaddle/PaddleNLP#5240]
### 软件环境

```Markdown
- paddlepaddle: 无
- paddlepaddle-gpu:  2.4.2.post117
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
File "train.py", line 133, in <module>
    main()
  File "train.py", line 114, in main
    train_result = trainer.train(resume_from_checkpoint=None)
  File "C:\Users\fym2004\IdeaProjects\text\venv\lib\site-packages\paddlenlp\trainer\trainer.py", line 669, in train
    tr_loss_step = self.training_step(model, inputs)
  File "C:\Users\fym2004\IdeaProjects\text\venv\lib\site-packages\paddlenlp\trainer\trainer.py", line 1350, in training_step
    loss = self.compute_loss(model, inputs)
  File "C:\Users\fym2004\IdeaProjects\text\venv\lib\site-packages\paddlenlp\prompt\prompt_trainer.py", line 239, in compute_loss
    raise ValueError("Fail to compute loss as `labels` not in {}.".format(inputs))
ValueError: Fail to compute loss as `labels` not in {'input_ids': Tensor(shape=[16, 18], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[1  , 1  , 835, 114, 249, 3  , 2  , 0  , 0  , 0  , 0  , 0  , 0  , 0  ,
```

### 稳定复现步骤 & 代码

python -u -m paddle.distributed.launch --gpus 0 train.py --data_dir ./data/ --output_dir ./checkpoints/ --model_name_or_path ernie-3.0-base-zh --max_seq_length 512  --learning_rate 3e-5 --ppt_learning_rate 3e-4 --do_train --do_eval --do_predict --do_export --num_train_epochs 100 --logging_steps 5 --save_total_limit 1 --per_device_eval_batch_size 64 --per_device_train_batch_size 16 --metric_for_best_model macro_f1_score --load_best_model_at_end --evaluation_strategy epoch --save_strategy epoch
![image](https://user-images.githubusercontent.com/116543487/225195796-4548ab4f-5613-4d21-a825-e6176e67218e.png)

**Comment by LemonNoel** [comment]
训练数据中有标签吗
