### ISSUE TITLE
[Question]: 已经训练完成的模型如何压缩？

### ISSUE THREAD

**Issue by adatwfx** [PaddlePaddle/PaddleNLP#5243]
已经使用UIE小样本训练完成了模型训练，且可以正常预测，现在想压缩模型，有没有单独的压缩办法，我看在训练时加上 --do_compress可以压缩，但是我不想重复一遍训练过程。还有压缩后在CPU上能提升多大的推理速度？

**Comment by LiuChiachi** [comment]
可以参考，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-3.0/README.md，
使用PTQ的量化策略，可以避免训练过程
