### ISSUE TITLE
[Question]:想请问下，faster_generation加速库能支持像vit、Ernie模型或Ernie-vil2等模型的性能加速吗？

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleNLP#5248]
### 请提出你的问题

或者厂里有没有其他的可加速此类模型的项目，如果有的话可以麻烦指点一下～

**Comment by FrostML** [comment]
目前没有 VIT，ERNIE-VIL2 模型加速，仅涉及文本到文本的生成加速。具体支持模型可以参考 [fast_generation/sample](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/fast_generation/samples) [fast_transformer/sample](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/ops/fast_transformer/sample) 这两个路径下的文件
