### ISSUE TITLE
[Question]: 使用paddlenlp.metrics中的AccuracyAndF1时update报错

### ISSUE THREAD

**Issue by zcg-joker** [PaddlePaddle/PaddleNLP#5256]
### 请提出你的问题

使用paddlenlp.metrics中的AccuracyAndF1时update报错，终端提示如下：
Traceback (most recent call last)
/tmp/ipykernel_2909/537038920.py in <module>
     42                 "%Y-%m-%d %H:%M:%S", time.localtime(time.time())))
     43     acc, precision, recall, f1, average_of_acc_and_f1 =  evaluate(model, criterion, metric,
---> 44                                                 dev_data_loader)
     45     save_best_path = args.save_dir
     46     if not os.path.exists(save_best_path):

<decorator-gen-706> in evaluate(model, criterion, metric, data_loader)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in _decorate_function(func, *args, **kwargs)
    373         def _decorate_function(func, *args, **kwargs):
    374             with self:
--> 375                 return func(*args, **kwargs)
    376 
    377         @decorator.decorator

/tmp/ipykernel_2909/865202917.py in evaluate(model, criterion, metric, data_loader)
     22 
     23         print(correct)
---> 24         metric.update(correct.squeeze())
     25 
     26     (acc, precision, recall, f1, average_of_acc_and_f1) = metric.accumulate()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/metrics/glue.py in update(self, correct, *args)
    115         self.acc.update(correct)
    116         self.precision.update(self.preds_pos, self.label)
--> 117         self.recall.update(self.preds_pos, self.label)
    118 
    119     def accumulate(self):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/metric/metrics.py in update(self, preds, labels)
    565             pred = preds[i]
    566             label = labels[i]
--> 567             if label == 1:
    568                 if pred == label:
    569                     self.tp += 1

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

我也已打印了metric.update(correct)中的correct，显示如下：
![image](https://user-images.githubusercontent.com/77949815/225464665-a0d924f1-84c8-4d58-819b-d8440e2c964a.png)
跟文档提供的示例输出是一致的
请问如何解决~

**Comment by w5688414** [comment]
您好，我的环境是：
```
paddlenlp              2.5.2
paddlepaddle-gpu       2.4.2.post112
```
代码为：
```
import paddle
from paddlenlp.metrics import AccuracyAndF1


x = paddle.to_tensor([[0.1, 0.9], [0.5, 0.5], [0.6, 0.4], [0.7, 0.3]])
y = paddle.to_tensor([[1], [0], [1], [1]])
m = AccuracyAndF1()
correct = m.compute(x, y)
m.update(correct)
res = m.accumulate()
print(res) # (0.5, 0.5, 0.3333333333333333, 0.4, 0.45)
```
输出结果为：
```
(0.5, 0.5, 0.3333333333333333, 0.4, 0.45)
```
