### ISSUE TITLE
google_news word embedding can not be loaded in ai studio

### ISSUE THREAD

**Issue by meteorjim** [PaddlePaddle/PaddleNLP#527]
w2v.google_news.target.word-word.dim300.en
在加载过程中 notebook会崩溃并强制重启
![FGSGCKFX{SOP0BG}3N3VI%7](https://user-images.githubusercontent.com/10251260/121275224-c5295200-c8fe-11eb-8b20-c19eba8ce06d.png)
![`7)6_%%2KJQ6{FUPN%MHG@3](https://user-images.githubusercontent.com/10251260/121275229-c78bac00-c8fe-11eb-8a73-32298510199d.png)

**Comment by joey12300** [comment]
您好，这个模型比较大，占用显存较多，可参考[Embedding预训练模型](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/embeddings.md#%E6%A8%A1%E5%9E%8B%E4%BF%A1%E6%81%AF)选择较小模型，如`w2v.wiki.target.bigram-char.dim300`。
