### ISSUE TITLE
在实体抽取任务中，进行微调时出现报错：paddle.load` can not parse the file

### ISSUE THREAD

**Issue by dsuanya** [PaddlePaddle/PaddleNLP#5276]
### 请提出你的问题

ValueError: `paddle.load` can not parse the file:C:\Users\.paddlenlp\models\uie-base\model_state.pdparams.[Question]: 
你好，请问在实体抽取任务中出现以上报错该怎么解决？希望有人能解答一下，真的非常感谢！！！！！

**Comment by linjieccc** [comment]
@dsuanya 你好，可能是模型文件损坏了，可以尝试下删除后重新下载

**Comment by dsuanya** [comment]
> @dsuanya 你好，可能是模型文件损坏了，可以尝试下删除后重新下载

谢谢您的回复！
