### ISSUE TITLE
[Bug]: UIE加载uie-m-large模型报model file is damaged. 请问是内存不足还是显存不足导致？至少需要多少内存或显存才能加载uie-m-larege

### ISSUE THREAD

**Issue by xiahexiang2** [PaddlePaddle/PaddleNLP#5278]
### 软件环境

```Markdown
- paddlepaddle-gpu:  2.3.2.post112
- paddlenlp: 2.4.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
RuntimeError: (Unavailable) An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:86)
  [operator < load_combine > error]
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow
schema = ['出发地', '目的地', '费用', '时间']
ie = Taskflow("information_extraction", schema=schema, model='uie-m-large')

**Comment by linjieccc** [comment]
@xiahexiang2 看报错应该是模型不完整没完全下载下来

**Comment by xiahexiang2** [comment]
> @xiahexiang2 看报错应该是模型不完整没完全下载下来

文件没问题，model_state.pdparams的MD5值 75f3989c515f05f6842e314d3f75ee27

**Comment by 526872163** [comment]
我使用uie-m-large也遇到完全一样的错误 ，请问该如何解决

**Comment by godshen** [comment]
+1

**Comment by linjieccc** [comment]
请问是windows环境 我在linux下面似乎没能复现出这个问题

**Comment by 526872163** [comment]
我是3090的显卡，更换了很多个版本的paddlepaddle和paddlenlp ，不管是win10还是ubuntu18，依旧出现这个问题，两个不同机器，但是显卡相同依旧报以上错误

**Comment by xiahexiang2** [comment]
已解决，内存、显存都得足够大

**Comment by lddcdut** [comment]
> 已解决，内存、显存都得足够大

和操作系统有关吗？

**Comment by 526872163** [comment]
请问要多大的内存和显存呢，我目前还没解决这个问题

**Comment by Spider4U** [comment]
> 已解决，内存、显存都得足够大

大概需要多大内存呢

**Comment by 46319943** [comment]
和显存和内存无关

**Comment by masknugget** [comment]
可以透露下怎么解决的嘛
