### ISSUE TITLE
是否能够支持使用ChatGLM-6B?

### ISSUE THREAD

**Issue by xikakera** [PaddlePaddle/PaddleNLP#5293]
### Feature request

能否支持 ChatGLM-6B的推理和微调的代码？
[官方地址](https://github.com/PaddlePaddle/PaddleNLP/blob/5f9019452072963a58e86d359c42a9d208731bbf/paddlenlp/transformers/glm/configuration.py)transformers 里还没有支持ChatGLM-6B

相关地址：
[huggingface](https://huggingface.co/THUDM/chatglm-6b)
[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B)

### Motivation

transformers 里还没有支持，但是有GLM的支持代码

### Your contribution

无

**Comment by jiweizhangxu** [comment]
同样请求集成在Paddle里
