### ISSUE TITLE
[Bug]: zero shot text classification taskflow报错

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#5297]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
微信15群的用户，提出如图所示报错
```

### 稳定复现步骤 & 代码

![470a3ef03b68fe9adf66adf573bccf81](https://user-images.githubusercontent.com/50394665/226115814-d7a60431-d414-4530-b618-13a79a85e2ae.png)

**Comment by LemonNoel** [comment]
paddlepaddle-gpu版本是多少呢？

**Comment by LemonNoel** [comment]
遇到这一问题可以尝试将 `paddlepaddle-gpu` 升级即可解决，如果必须使用较低版本的 `paddlepaddle`，可将 418 行的 scores[0] 改为 scores.
