### ISSUE TITLE
[Question]:  调用服务报错 UnimplementedError: emebdding input only support int32 and int64

### ISSUE THREAD

**Issue by clSpider** [PaddlePaddle/PaddleNLP#5298]
### 请提出你的问题

我在调用部署的服务时报错：
1. paddlenlp server server_token_cls:app --host 0.0.0.0 --port 8189 --workers 1
2. texts = [
        # '审理(2018)川1802民初666号雅安诚易达物流有限公司与陈取强挂靠经营合同纠纷一案',
        '刘敏与朗信银龙律师事务所案',
    ]
data = {
        'data': {
            'text': texts,
        },
        'parameters': {
            'max_seq_len': 128,
            'batch_size': 2
        }
    }
r = requests.post(url="http://localhost:8189/person",  data=json.dumps(data))
3. server_token_cls.py 代码如下：
import numpy as np

from paddlenlp import SimpleServer
from paddlenlp.server import BasePostHandler, TokenClsModelHandler, ERNIEMHandler, CustomModelHandler

class NERPostHandler(BasePostHandler):
    def __init__(self):
        super().__init__()

    @classmethod
    def process(cls, data, parameters):
        label_list = ["ORG-B", "ORG-I", "PER-B", "PER-I", "O"]
        input_datas = data["data"]["text"]
        predictions = np.array(data["logits"])
        tokens_label = predictions.argmax(axis=-1)
        tokens_label = tokens_label.tolist()
        value = []
        print(tokens_label)
        for batch, token_label in enumerate(tokens_label):
            start = -1
            label_name = ""
            items = []
            input_data = input_datas[batch]

            sent_out = []
            outputs = []
            tags_out = []

            words = ""
            # print(input_data, tokens_label)
            input = [text for text in input_data]
            tags = [label_list[t] for t in token_label]
            for s, t in zip(input, tags):
                # print(s, t)
                if t.endswith('-B') or t == 'O':
                    if len(words):
                        sent_out.append(words)
                    tags_out.append(t.split('-')[0])
                    words = s
                else:
                    words += s
            if len(sent_out) < len(tags_out):
                sent_out.append(words)
            # outputs.append(''.join(
            #     [str((s, t)) for s, t in zip(sent_out, tags_out)]))
            for s, t in zip(sent_out, tags_out):
                outputs.append((s, t))

            for result in outputs:
                if result[1] in ['ORG', 'PER']:
                    items.append(result[0])
            value.append(items)

        out_dict = {"value": value }
        return out_dict

app = SimpleServer()
app.register(
    "person",
    model_path="output/person",
    # model_path="ernie_ckpt",
    tokenizer_name="ernie-3.0-medium-zh",
    model_handler=ERNIEMHandler,
    post_handler=NERPostHandler,
)
![image](https://user-images.githubusercontent.com/14866283/226116371-c34d4e60-bce7-4b5e-93cd-6cd0064e35ff.png)

![image](https://user-images.githubusercontent.com/14866283/226116273-ddb04ecc-47b0-4a0c-b618-285926557417.png)

**Comment by hsu1943** [comment]
同样的问题
