### ISSUE TITLE
[Question]: 使用text_to_image_laion400m例子时，疑似陷入死循环

### ISSUE THREAD

**Issue by sanshanya** [PaddlePaddle/PaddleNLP#5299]
### 请提出你的问题

使用飞桨v100环境启动例子，数据集使用的个人整理的，停留在此处
CPU占用率100%，GPU占用率0%
![image](https://user-images.githubusercontent.com/62289203/226149947-4b238a06-2bc5-403c-b9e4-0af1e56b2415.png)

**Comment by JunnYu** [comment]
你好，当前配置下，32GV100是训练不了分辨率为256的模型的，还有建议把num_workers设置成1.

**Comment by JunnYu** [comment]
出现死循环，最有可能的原因是https://github.com/PaddlePaddle/PaddleNLP/blob/f8604c450b4b9bc34b34c99d27470305ed4c0292/ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py#L159-L161 这里continue了
