### ISSUE TITLE
DatasetBuilder 对 splits 和 data_files 加个  assert 限制不能同时出现是否会更好？

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/PaddleNLP#530]
https://github.com/PaddlePaddle/PaddleNLP/blob/311bbfb7637c023fd627af2a47ff59db6f238140/paddlenlp/datasets/dataset.py#L474
e.g.
```python
assert splits is None or data_files is None , "Only one of `data_files` and `splits` can be set."
```

**Comment by guoshengCS** [comment]
Resolved by #531. Thanks for your contribution.

**Comment by smallv0221** [comment]
Why these two arguements should be exclusive? User may be needing PaddleNLP datasets and local file datasets at the same time. @jiaqianjing

**Comment by jiaqianjing** [comment]
> Why these two arguements should be exclusive? User may be needing PaddleNLP datasets and local file datasets at the same time. @jiaqianjing

Yep, but it's kind of weird and not straight forward.  e.g.`train_ds, dev_ds, local_train_ds =   load_dataset("lcqmc", splits=["train", "dev"], data_files="/to/path/xxx.tsv")`. Generally, we use `data_files` for load our dataset. Another reason may be that there is no Internet.

**Comment by jiaqianjing** [comment]
More importantly, I feel that if I support these two parameters at the same time, users will be confused.  Like me.

**Comment by smallv0221** [comment]
> More importantly, I feel that if I support these two parameters at the same time, users will be confused. Like me.

I'm not what you were confussing about. Did you think that the splits arguement is for data_files to specific splits?

I think that the situation that someone wants PaddleNLP dataset to train a model then predicts his local dataset is fairly common.

**Comment by jiaqianjing** [comment]
> Did you think that the splits arguement is for data_files to specific splits?

yes, before I read source code.

**Comment by smallv0221** [comment]
I see... Maybe we should have done more work on documentation. Thanks for bring it. Also thank you for contribution.

**Comment by jiaqianjing** [comment]
You're welcome. Good luck.
