### ISSUE TITLE
[Question]: 导入paddlenlp出现fast_tokenizer错误

### ISSUE THREAD

**Issue by lai-serena** [PaddlePaddle/PaddleNLP#5312]
### 请提出你的问题

linux paddlenlp=2.5.2 paddlepaddle-gpu=2.4.2-post112

from paddlenlp import Taskflow

# 模型预测
cls = Taskflow("text_classification", task_path='checkpoint_labels2/export', is_static_model=True)
result=cls(["黑苦荞茶的功效与作用及食用方法","幼儿挑食的生理原因是"])
print(result)

出现错误：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "test_text_classification.py", line 1, in <module>
    from paddlenlp import Taskflow
  File "/home/PaddleNLP/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/PaddleNLP/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/PaddleNLP/paddlenlp/data/data_collator.py", line 25, in <module>
    from ..transformers import BertTokenizer
  File "/home/PaddleNLP/paddlenlp/transformers/__init__.py", line 28, in <module>
    from .tokenizer_utils_fast import PretrainedFastTokenizer
  File "/home/PaddleNLP/paddlenlp/transformers/tokenizer_utils_fast.py", line 22, in <module>
    from fast_tokenizer import Encoding as FastEncoding
ImportError: cannot import name 'Encoding' from 'fast_tokenizer' (unknown location)

尝试安装fasttokenizer，但是不能解决

**Comment by joey12300** [comment]
@lai-serena 您好，您paddlenlp应该是develop版本的，可以尝试git pull最新代码解决这个问题，或者安装fast_tokenizer解决 `pip install fast_tokenizer_python`
