### ISSUE TITLE
[Question]: 使用pipelines构建语义检索系统时报 assert d == self.d 错误

### ISSUE THREAD

**Issue by halenfly** [PaddlePaddle/PaddleNLP#5331]
### 请提出你的问题

在执行以下脚本时报 assert d == self.d 错误
examples/semantic-search/semantic_search_example.py \
                                              --device cpu \
                                              --query_embedding_model rocketqa-zh-base-query-encoder \
                                              --params_path checkpoints/model_40/model_state.pdparams \
                                              --embedding_dim 256
按照ＦＡＱ文档，把faiss_document_store.db　删除掉再运行脚本，反复试多次依然报这个错误。

**Comment by w5688414** [comment]
您是想加载neural search训练的模型吗？如果是的话，需要改一下model_type为neural_search，详情请参考代码。
https://github.com/PaddlePaddle/PaddleNLP/blob/bcd96cb29e0b1160122462a34b7e3420b7219992/pipelines/examples/semantic-search/semantic_search_example.py#L41

**Comment by halenfly** [comment]
您好，邮件已收到，我查看到会尽快给您回复。

**Comment by halenfly** [comment]
examples/semantic-search/semantic_search_example.py
--device cpu
--query_embedding_model rocketqa-zh-base-query-encoder
--params_path checkpoints/model_40/model_state.pdparams
--embedding_dim 256

DEMO脚本容易弄错，query_embedding_model 、passage_embedding_model这两个参数需要保持一致，demo中只指定了一个。embedding_dim　这个需要根据指定的模型来设定，具体参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/API.md
