### ISSUE TITLE
Taskflow 预测

### ISSUE THREAD

**Issue by Isfate** [PaddlePaddle/PaddleNLP#5348]
### 问题描述

Taskflow现在可以多线程并发预测了么

**Comment by Isfate** [comment]
Taskflow的预测速度跟schema数量有很大的关系, 能否优化这部分的逻辑呢

**Comment by linjieccc** [comment]
场景相对固定且数据量足够的话，可以尝试下封闭域建模的方案，只需要一次前向即可获得所有抽取结果

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/data_distill
