### ISSUE TITLE
[Bug]: 多分类模型传参问题

### ISSUE THREAD

**Issue by tendrillion** [PaddlePaddle/PaddleNLP#5351]
### 软件环境

```Markdown
- paddlepaddle:--
- paddlepaddle-gpu: 2.4.0.post116 
- paddlenlp: 2.5.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class
运行代码参数报错。
```

### 稳定复现步骤 & 代码

配置好环境后，在vscode中运行train.py代码，报错。
train.py: error: the following arguments are required: --output_dir

在train.py中添加：
@dataclass
class TrainingArguments:
    output_dir: str = field(default="./output",metadata={
        "help":"The output directory where the model predictions and checkpoints will be written."})

仍然报错，提示参数冲突：
发生异常: ArgumentError
argument --output_dir: conflicting option string: --output_dir

问题：
我应该怎么添加argument，才能在vscode中运行train.py代码？

**Comment by lugimzzz** [comment]
你直接在命令行运行的时候加python train.py --output_dir "checkpoint"是最推荐的方式，如果一定要在代码里修改请参考下图
![image](https://user-images.githubusercontent.com/63761690/226819350-054b8c91-4407-4a1f-af17-d93e526d774a.png)

**Comment by tendrillion** [comment]
> 你直接在命令行运行的时候加python train.py --output_dir "checkpoint"是最推荐的方式，如果一定要在代码里修改请参考下图 ![image](https://user-images.githubusercontent.com/63761690/226819350-054b8c91-4407-4a1f-af17-d93e526d774a.png)

首先，根据上面的提示修改后，代码能跑起来。多说一句，因为需要集成到业务逻辑中，所以python train.py --output_dir "checkpoint"这个启动方法不是很方便，希望后续考虑优化下示例代码。

**Comment by lugimzzz** [comment]
> > 你直接在命令行运行的时候加python train.py --output_dir "checkpoint"是最推荐的方式，如果一定要在代码里修改请参考下图 ![image](https://user-images.githubusercontent.com/63761690/226819350-054b8c91-4407-4a1f-af17-d93e526d774a.png)
> 
> 首先，根据上面的提示修改后，代码能跑起来。多说一句，因为需要集成到业务逻辑中，所以python train.py --output_dir "checkpoint"这个启动方法不是很方便，希望后续考虑优化下示例代码。

@ZHUI
