### ISSUE TITLE
请教一下，paddle怎么开箱既用法？给的演示代码，还需要下载模型，这个模型用代理还下载不了！下载后的模型要保存那个位置？可以用其他攻击下载？

### ISSUE THREAD

**Issue by ahong007007** [PaddlePaddle/PaddleNLP#5352]
### 问题描述
请教一下，paddle怎么开箱既用法？给的演示代码，还需要下载模型，这个模型用代理还下载不了！下载后的模型要保存那个位置？可以用其他攻击下载？
![image](https://user-images.githubusercontent.com/22077027/226802915-655ff0dc-fb77-456a-8b77-6af7b887ec42.png)

![image](https://user-images.githubusercontent.com/22077027/226802949-829a6523-d0f6-4c6d-90dc-4de362357ab2.png)

**Comment by linjieccc** [comment]
你好，你是在离线环境执行吗？可以先在联网的设备上执行一次，然后将~/.paddlenlp这个目录拷贝到离线环境对应路径下

**Comment by ahong007007** [comment]
> 就是因为不方便联网，不知道下载那个模型，模型存放那个位置，

如果有离线下载包或者脚本就好了。

**Comment by wjj001-dl** [comment]
> 你好，你是在离线环境执行吗？可以先在联网的设备上执行一次，然后将~/.paddlenlp这个目录拷贝到离线环境对应路径下

你好，是只能放在c盘吗？如何放到其他盘并可以运行？

**Comment by wjj001-dl** [comment]
> 你好，你是在离线环境执行吗？可以先在联网的设备上执行一次，然后将~/.paddlenlp这个目录拷贝到离线环境对应路径下

IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1 这个模型复制到离线环境怎么还需要联网
