### ISSUE TITLE
[Question]: GPU-A100 模型：T5-base，使用fast generation直接Aborted

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/PaddleNLP#5355]
### 请提出你的问题

机器环境：A100
模型：T5-base
paddle版本：2.4
使用代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/fast_generation/samples/t5_sample.py

现象：执行后开始下载fasttransformer并编译，编译过程正常，生成libboost.a  和 libdecoding_op.so， 然后执行代码aborted。

<img width="948" alt="image" src="https://user-images.githubusercontent.com/13117136/226813290-7e66202e-a3a0-432c-973e-2375e1e7c5ce.png">

**Comment by FrostML** [comment]
贴一下执行命令。

**Comment by zzcgithub** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/fast_generation/samples/t5_sample.py

**Comment by zzcgithub** [comment]
python t5_sample.py

**Comment by FrostML** [comment]
`legacy/fast.py` 是什么？

**Comment by zzcgithub** [comment]
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

**Comment by zzcgithub** [comment]
已解决。
定位的问题是：paddle是2.4.1.post112（对应cuda11.2）， a100默认cuda环境11.0， 更换cuda环境到11.2，重新编译相关so 可以正常运行。
