### ISSUE TITLE
[Question]: UIE-X 

### ISSUE THREAD

**Issue by Originhhh** [PaddlePaddle/PaddleNLP#5357]
### 请提出你的问题

用Taskflow基于UIE-X模型进行预测的过程中，可以不用PaddleOCR使用第三方OCR吗

**Comment by linjieccc** [comment]
@Originhhh 你好，可以参考这里使用自己的OCR输入

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/taskflow_doc.md#24-%E8%BE%93%E5%85%A5%E8%AF%B4%E6%98%8E

**Comment by Originhhh** [comment]
> @Originhhh 你好，可以参考这里使用自己的OCR输入
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/taskflow_doc.md#24-%E8%BE%93%E5%85%A5%E8%AF%B4%E6%98%8E

感谢
