### ISSUE TITLE
KeyError: 'uie-base-answer-extractor-v1'

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5362]
### 请提出你的问题

运行：python examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py --device gpu --source_file data/source_file.txt --doc_dir data/my_data

报以下错：
(paddleGpu) D:\dzkj\PaddleNLP\pipelines>python examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py --device gpu --source_file data/source_file.txt --doc_dir data/my_data
Traceback (most recent call last):
  File "examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py", line 71, in <module>
    offline_qa_generation()
  File "examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py", line 36, in offline_qa_generation
    position_prob=0.01,
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\pipelines\nodes\answer_extractor\answer_extractor.py", line 94, in __init__
    self._check_task_files()
  File "C:\ProgramData\Anaconda3\envs\paddleGpu\lib\site-packages\pipelines\nodes\answer_extractor\answer_extractor.py", line 114, in _check_task_files
    url = self.resource_files_urls[self.model][file_id][0]
KeyError: 'uie-base-answer-extractor-v1'

打印出来数据是这样的：
![图片](https://user-images.githubusercontent.com/6648329/226856107-82090b2a-c43b-4d87-82f7-75abab6aefdb.png)

---------------------------
print(path):

C:\Users\Administrator\.paddlenlp\pipelines\unsupervised_question_answering\uie-base-answer-extractor-v1\model_state.pdparams

---------------------------
print(self.resource_files_urls):
{'uie-base-answer-extractor': {'model_state': ['https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/model_state.pdparams', 'c8619f631a0c20434199840d34bb8b8c'], 'model_config': ['https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/model_config.json', '74f033ab874a1acddb3aec9b9c4d9cde'], 'vocab_file': ['https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/vocab.txt', '1c1c1f4fd93c5bed3b4eebec4de976a8'], 'special_tokens_map': ['https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/special_tokens_map.json', '8b3fb1023167bb4ab9d70708eb05f6ec'], 'tokenizer_config': ['https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/tokenizer_config.json', '3e623b57084882fd73e17f544bdda47d']}}

---------------------------
数组key完全对不上，应该是版本还是什么问题，  差别也太大了

环境：
paddlenlp                            2.5.2
paddlepaddle-gpu               2.3.1

paddle-pipelines               0.5.1
paddle2onnx                    0.9.8
paddlefsl                      1.1.0
paddlehub                      2.2.0
paddlenlp                      2.5.2
paddleocr                      2.6.1.3
paddlepaddle-gpu               2.3.1
paddleseg                      2.6.0
paddlespeech                   1.2.0
paddlespeech-feat              0.1.0
paddlex                        1.3.0

**Comment by westfish** [comment]
paddlepaddle-gpu的版本太低了，建议更新到最新的版本2.4.2

**Comment by ruolunhui** [comment]
更新到最新的版本2.4.2版本后 
在aistudio中又报错 :  libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by ruolunhui** [comment]
> paddlepaddle-gpu的版本太低了，建议更新到最新的版本2.4.2

更新到最新的版本2.4.2版本后
在aistudio中又报错 : libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by ruolunhui** [comment]
> > paddlepaddle-gpu的版本太低了，建议更新到最新的版本2.4.2
> 
> 更新到最新的版本2.4.2版本后 在aistudio中又报错 : libcudart.so.10.2: cannot open shared object file: No such file or directory

使用 python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 
升级之后 还是找不到 uie-base-answer-extractor-v1


Traceback (most recent call last):
  File "examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py", line 71, in <module>
    offline_qa_generation()
  File "examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py", line 36, in offline_qa_generation
    position_prob=0.01,
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/pipelines/nodes/answer_extractor/answer_extractor.py", line 94, in __init__
    self._check_task_files()
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/pipelines/nodes/answer_extractor/answer_extractor.py", line 114, in _check_task_files
    url = self.resource_files_urls[self.model][file_id][0]
KeyError: 'uie-base-answer-extractor-v1'

看了下源码 
    resource_files_urls = {
        "uie-base-answer-extractor": {
            "model_state": [
                "https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/model_state.pdparams",
                "c8619f631a0c20434199840d34bb8b8c",
            ],
            "model_config": [
                "https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/model_config.json",
                "74f033ab874a1acddb3aec9b9c4d9cde",
            ],
            "vocab_file": [
                "https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/vocab.txt",
                "1c1c1f4fd93c5bed3b4eebec4de976a8",
            ],
            "special_tokens_map": [
                "https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/special_tokens_map.json",
                "8b3fb1023167bb4ab9d70708eb05f6ec",
            ],
            "tokenizer_config": [
                "https://bj.bcebos.com/paddlenlp/pipelines/answer_generator/uie-base-answer-extractor/uie-base-answer-extractor-v1/tokenizer_config.json",
                "3e623b57084882fd73e17f544bdda47d",
            ],
        },
    }
里面没有v1模型

**Comment by ruolunhui** [comment]
这个报错和paddlepaddle-gpu没有关系，是paddlenlp代码里面的错误，具体内容为下面这行
```
# 文件地址 : pipelines/pipelines/nodes/answer_extractor/answer_extractor.py
 url = self.resource_files_urls[self.model][file_id][0]
md5 = self.resource_files_urls[self.model][file_id][1]
```
dict字典没有uie-base-answer-extractor-v1这个key直接报错了

查找了下提交记录 
010fcd87e7510b1f1987ba9c3aff604d88d489c5
Add unsupervised-qa pipelines (https://github.com/PaddlePaddle/PaddleNLP/pull/3605)

在初次提交时这个错误就存在 
推测可能是 offline_question_answer_pairs_generation.py 在本地测试是是使用本地模型路径uie-base-answer-extractor-v1，之后提交的时候没有改或者设置为task_path

**Comment by westfish** [comment]
把offline_question_answer_pairs_generation.py中的uie-base-answer-extractor-v1、unimo-text-1.0-question-generator-v1、uie-base-qa-filter-v1分别改为uie-base-answer-extractor、unimo-text-1.0-question-generator、uie-base-qa-filter

**Comment by ruolunhui** [comment]
> 把offline_question_answer_pairs_generation.py中的uie-base-answer-extractor-v1、unimo-text-1.0-question-generator-v1、uie-base-qa-filter-v1分别改为uie-base-answer-extractor、unimo-text-1.0-question-generator、uie-base-qa-filter

好的 谢谢 可以了
