### ISSUE TITLE
[Question]: 现在用uie微调的模型，遇到在CPU上实体提取速度太慢，而且并发的话更慢，有没有好的优化方式

### ISSUE THREAD

**Issue by szy833** [PaddlePaddle/PaddleNLP#5363]
### 请提出你的问题

现在用uie微调的模型，遇到在CPU上实体提取速度太慢，而且并发的话更慢，有没有好的优化方式

**Comment by szy833** [comment]
用的paddlenlp 2.5.1

**Comment by linjieccc** [comment]
@szy833 你好，

1.选择小尺寸的模型，例如uie-nano、uie-micro
2.尝试下global pointer封闭域建模方案：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/data_distill
