### ISSUE TITLE
uie-x 与 ernie-layout

### ISSUE THREAD

**Issue by Originhhh** [PaddlePaddle/PaddleNLP#5366]
### 问题描述

您好，请问ernie-layout与uie-x有什么区别吗，我看docprompt使用的是ernie-layout， information_extraction则用的是uie-x？

**Comment by linjieccc** [comment]
你好，docprompt和uie-x都是针对下游任务的模型，两者都基于ernie-layout在大量数据上进行了多任务训练，docprompt适合问答抽取场景，uie-x更专注在信息抽取上。

ernie-layout和layoutlm系列一样都是跨模态预训练模型，除了docpromt还可以用于文档分类、序列标注等其他下游任务。
