### ISSUE TITLE
[Question]: uie微调

### ISSUE THREAD

**Issue by szy833** [PaddlePaddle/PaddleNLP#5367]
### 请提出你的问题

怎么再之前微调基础上，调优？多次标注感觉越调效果越差....

**Comment by linjieccc** [comment]
类别标签有更新的话，建议重新基于uie进行微调

**Comment by szy833** [comment]
> 类别标签有更新的话，建议重新基于uie进行微调

标签不变的情况下，如何基于已经训练好的模型进行优化？
