### ISSUE TITLE
PaddleNLP是否有保存best model的api？

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#537]
无敌的陈老师，能不能开发个保存best model的api？

**Comment by jiaqianjing** [comment]
呃呃呃，这个完全可以自己在 train loop 实现吧。。。每一轮 epoch 查一下 metric , 如果比历史的效果好，就覆盖 save_model

**Comment by livingbody** [comment]
嗯嗯，太漂亮了。其实当初想能做成高层Api那种，一句话启动训练，日志啥的，那就太牛了
