### ISSUE TITLE
[Question]: 我想了解uie中finetune.py中的具体函数功能，但是没有注释。我该去哪里查看文档呢

### ISSUE THREAD

**Issue by yangzhenyu6** [PaddlePaddle/PaddleNLP#5373]
### 请提出你的问题

我想了解uie中finetune.py中的具体函数功能，但是没有注释。我该去哪里查看文档呢，可以了解其中每个函数的具体功能。

**Comment by sijunhe** [comment]
你好，请问你想了解哪个py文件的函数功能呢？

**Comment by yangzhenyu6** [comment]
> 你好，请问你想了解哪个py文件的函数功能呢？

uie中finetune.py文件，就是微调的那个文件

**Comment by sijunhe** [comment]
> > 你好，请问你想了解哪个py文件的函数功能呢？
> 
> uie中finetune.py文件，就是微调的那个文件

能链接一下代码文件吗？如果关于代码有具体的问题，也可以一并提出

**Comment by yangzhenyu6** [comment]
> > > 你好，请问你想了解哪个py文件的函数功能呢？
> > 
> > 
> > uie中finetune.py文件，就是微调的那个文件
> 
> 能链接一下代码文件吗？如果关于代码有具体的问题，也可以一并提出

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/finetune.py
我就想了解一下微调实现的过程，各个函数的作用什么的然后试试能不能自己写微调的代码

**Comment by sijunhe** [comment]
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/finetune.py 我就想了解一下微调实现的过程，各个函数的作用什么的然后试试能不能自己写微调的代码

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie#43-%E6%A8%A1%E5%9E%8B%E5%BE%AE%E8%B0%83 应该有参数注释了，直接看代码应该也可以

**Comment by yangzhenyu6** [comment]
> 
好的，谢谢
