### ISSUE TITLE
报错：TypeError: retrieve_batch() got an unexpected keyword argument 'query_type'

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5380]
### 请提出你的问题

 一键体验语义检索系统 ：python examples/semantic-search/semantic_search_example.py --device cpu
报错：

Traceback (most recent call last):
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 565, in run_batch
    node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run_batch(**node_input)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 127, in _dispatch_run_batch
    return self._dispatch_run_general(self.run_batch, **kwargs)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 164, in _dispatch_run_general
    output, stream = run_method(**run_inputs, **run_params)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 154, in run_batch
    queries=queries, filters=filters, top_k=top_k, index=index, headers=headers
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 107, in wrapper
    ret = fn(*args, **kwargs)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 199, in run_query_batch
    batch_size=batch_size,
TypeError: retrieve_batch() got an unexpected keyword argument 'query_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/semantic-search/semantic_search_example.py", line 191, in <module>
    semantic_search_tutorial()
  File "examples/semantic-search/semantic_search_example.py", line 180, in semantic_search_tutorial
    predictions = pipe.run_batch(queries=["亚马逊河流的介绍", "期货交易手续费指的是什么?"], params={"Retriever": {"top_k": 10}})
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\standard_pipelines.py", line 181, in run_batch
    output = self.pipeline.run_batch(queries=queries, params=params, debug=debug)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 572, in run_batch
    ) from e
Exception: Exception while running node 'Retriever': retrieve_batch() got an unexpected keyword argument 'query_type'
Enable debug logging to see the data that was passed when the pipeline failed.

![图片](https://user-images.githubusercontent.com/6648329/227117196-6d1c951c-8103-4d4c-ac4f-bdd4e1cb411e.png)

---环境---
windos:

paddle-pipelines               0.5.1
paddle2onnx                    1.0.1
paddlefsl                      1.1.0
paddlenlp                      2.5.2
paddleocr                      2.6
paddlepaddle                   2.3.2

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 一键体验语义检索系统 ：python examples/semantic-search/semantic_search_example.py --device cpu 报错：
> 
> Traceback (most recent call last): File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 565, in run_batch node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run_batch(**node_input) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 127, in _dispatch_run_batch return self._dispatch_run_general(self.run_batch, **kwargs) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 164, in _dispatch_run_general output, stream = run_method(**run_inputs, **run_params) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 154, in run_batch queries=queries, filters=filters, top_k=top_k, index=index, headers=headers File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 107, in wrapper ret = fn(*args, **kwargs) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 199, in run_query_batch batch_size=batch_size, TypeError: retrieve_batch() got an unexpected keyword argument 'query_type'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "examples/semantic-search/semantic_search_example.py", line 191, in semantic_search_tutorial() File "examples/semantic-search/semantic_search_example.py", line 180, in semantic_search_tutorial predictions = pipe.run_batch(queries=["亚马逊河流的介绍", "期货交易手续费指的是什么?"], params={"Retriever": {"top_k": 10}}) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\standard_pipelines.py", line 181, in run_batch output = self.pipeline.run_batch(queries=queries, params=params, debug=debug) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 572, in run_batch ) from e Exception: Exception while running node 'Retriever': retrieve_batch() got an unexpected keyword argument 'query_type' Enable debug logging to see the data that was passed when the pipeline failed.
> 
> ![图片](https://user-images.githubusercontent.com/6648329/227117196-6d1c951c-8103-4d4c-ac4f-bdd4e1cb411e.png)
> 
> ---环境--- windos:
> 
> paddle-pipelines 0.5.1 paddle2onnx 1.0.1 paddlefsl 1.1.0 paddlenlp 2.5.2 paddleocr 2.6 paddlepaddle 2.3.2

您好，这是pipelines最近升级跨模态检索引起的，请参考pr。https://github.com/PaddlePaddle/PaddleNLP/pull/5385

**Comment by gg22mm** [comment]
> > ### 请提出你的问题
> > 一键体验语义检索系统 ：python examples/semantic-search/semantic_search_example.py --device cpu 报错：
> > Traceback (most recent call last): File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 565, in run_batch node_output, stream_id = self.graph.nodes[node_id]["component"]._dispatch_run_batch(**node_input) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 127, in _dispatch_run_batch return self._dispatch_run_general(self.run_batch, **kwargs) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\base.py", line 164, in _dispatch_run_general output, stream = run_method(**run_inputs, **run_params) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 154, in run_batch queries=queries, filters=filters, top_k=top_k, index=index, headers=headers File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 107, in wrapper ret = fn(*args, **kwargs) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\nodes\retriever\base.py", line 199, in run_query_batch batch_size=batch_size, TypeError: retrieve_batch() got an unexpected keyword argument 'query_type'
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "examples/semantic-search/semantic_search_example.py", line 191, in semantic_search_tutorial() File "examples/semantic-search/semantic_search_example.py", line 180, in semantic_search_tutorial predictions = pipe.run_batch(queries=["亚马逊河流的介绍", "期货交易手续费指的是什么?"], params={"Retriever": {"top_k": 10}}) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\standard_pipelines.py", line 181, in run_batch output = self.pipeline.run_batch(queries=queries, params=params, debug=debug) File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddle_pipelines-0.5.1-py3.7.egg\pipelines\pipelines\base.py", line 572, in run_batch ) from e Exception: Exception while running node 'Retriever': retrieve_batch() got an unexpected keyword argument 'query_type' Enable debug logging to see the data that was passed when the pipeline failed.
> > ![图片](https://user-images.githubusercontent.com/6648329/227117196-6d1c951c-8103-4d4c-ac4f-bdd4e1cb411e.png)
> > ---环境--- windos:
> > paddle-pipelines 0.5.1 paddle2onnx 1.0.1 paddlefsl 1.1.0 paddlenlp 2.5.2 paddleocr 2.6 paddlepaddle 2.3.2
> 
> 您好，这是pipelines最近升级跨模态检索引起的，请参考pr。#5385

多谢大老，牛啊~！~~~~  非常感谢~~！！！！！！
