### ISSUE TITLE
[Question]: PaddleNLP中的ernie-layout模型document_intelligence问题

### ISSUE THREAD

**Issue by Fly-betterme** [PaddlePaddle/PaddleNLP#5383]
### 请提出你的问题

from paddlenlp import Taskflow
docprompt = Taskflow("document_intelligence", device_id=-1, topn=3)
智能表格抽取问答有什么参数可以识别换行数据吗？
具体场景如下：
![image](https://user-images.githubusercontent.com/46836430/227127126-7372d3b9-d61d-4ada-92d5-5501256fb399.png)

目前识别结果{'prompt': '收款人名称', 'result': [{'value': '华宝基金管理有', 'prob': 0.99, 'start': 50, 'end': 56}]}]

想要结果应该是：华宝基金管理有限公司

**Comment by linjieccc** [comment]
@draling 你好，表格类型文档可以结合PPStructure增强抽取效果，用法可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/taskflow_doc.md#25-%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7

**Comment by Fly-betterme** [comment]
试了下，效果并不好，可能需要自己标注训练
![image](https://user-images.githubusercontent.com/46836430/227149001-861a81c4-2085-4685-bf86-d60c92a465fa.png)

**Comment by linjieccc** [comment]
```python
schema = "收款人名称"
ie = Taskflow("information_extraction", schema=schema, model="uie-x-base", layout_analysis=True)
```

场景定制可以参考这里的例子：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document

**Comment by Fly-betterme** [comment]
![image](https://user-images.githubusercontent.com/46836430/227149632-d33a1052-524f-4289-bda9-9a7264007363.png)
顺便问下开箱即用工具中的v2底层是哪个版本哪个模型
