### ISSUE TITLE
[Question]: 请教一下taskflow--information_extraction算法使用的schema都有那些，有没有列表？

### ISSUE THREAD

**Issue by ahong007007** [PaddlePaddle/PaddleNLP#5384]
### 请提出你的问题

           官方给的例子如下。我希望能查询到 information_extraction在哪里，有什么内容可以用于自己的数据抽取。感谢。
           # Entity Extraction
            schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
            ie = Taskflow('information_extraction', schema=schema)
            ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！")

**Comment by linjieccc** [comment]
schema没有特别限制，可以根据实际抽取需要自由定义，比如这里 『赛事名称』 也可以换成『赛事名』、『比赛名称』等其他说法

**Comment by ahong007007** [comment]
> schema没有特别限制，可以根据实际抽取需要自由定义，比如这里 『赛事名称』 也可以换成『赛事名』、『比赛名称』等其他说法

百度给的这个例子是明确了定义实体的类别，比如
“变压器、静止式变流器（例如，整流器)及电感器：-液体介质变压器：--额定容量不超过650千伏安：-----额定容量≤650KVA液体介质变压器”
这句话，我不需要指定schema，Taskflow("ner")就成抽取出实体“液体介质变压器”，而使用Taskflow('information_extraction', schema=schema)，我不知道schema是什么，抽取不出来任何实体。
