### ISSUE TITLE
[Question]: fast generation导出模型时，cmake编译时需要下载boost_1_41_0.tar.gz

### ISSUE THREAD

**Issue by TangXinOfChina** [PaddlePaddle/PaddleNLP#5386]
### 请提出你的问题

我可能无法联网下载，如果离线下载好boost_1_41_0.tar.gz，我应该放到哪个位置

**Comment by FrostML** [comment]
`build/third-party/source/` 可以放在这个路径下，解压之后按照如下路径结构组织：
<img width="299" alt="image" src="https://user-images.githubusercontent.com/7160927/228454777-f0068551-11c1-4420-8bfd-454f8711f814.png">

**Comment by FrostML** [comment]
或者你放在当前机器随便哪个位置，修改下这里[下载链接](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/cmake/external/boost.cmake#L26)的代码让它自动从你提供的新的本机的服务链接下”下载“

**Comment by TangXinOfChina** [comment]
> 

我之前试过把tar包放到这个目录下，但它貌似还是根据下载链接去下载了，我放的是这个位置：
~/.paddlenlp/extensions/d24xxxxxxxxxxxxxxxxx/FasterTransformer/build/temp.linux-x86_64-3.7/third-party/source/boost/src/
这是对的吗？
我先试下您说的改成本机的链接吧，非常感谢！

**Comment by mymynew** [comment]
@TangXinOfChina 离线部署的情况下，除了boost，FasterGeneration需要原本是git的，离线编译过么？

**Comment by TangXinOfChina** [comment]
> @TangXinOfChina 离线部署的情况下，除了boost，FasterGeneration需要原本是git的，离线编译过么？
没有，我直接下载了FastTransformer，只是checkout到相应分支上去了
可以看https://github.com/PaddlePaddle/PaddleNLP/issues/3433
