### ISSUE TITLE
[Question]: uie 命名实体提取。怎样在已经微调后的模型上进行补充优化？标签不变。

### ISSUE THREAD

**Issue by szy833** [PaddlePaddle/PaddleNLP#5399]
### 请提出你的问题

微调后，还是有一些提取错误的。应该怎么继续优化？是把--model_name_or_path 换成微调后的模型，继续根据标注的数据训练吗？还是别的方法？（纯小白...）

**Comment by LemonNoel** [comment]
可以针对提取错误的case再标注一些数据。推荐将新标注的数据和原有数据混合后重新训练。
