### ISSUE TITLE
[Question]: 无监督智能检索问答系统的CPU环境下运行示例运行不起来

### ISSUE THREAD

**Issue by chanlong** [PaddlePaddle/PaddleNLP#5401]
### 请提出你的问题

参考样例中的命令执行
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/11283440/227407401-4ab60cb3-0967-4a2f-86eb-52ff591620d1.png">

执行后提示“The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA”
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/11283440/227407325-da13cc6f-1aa7-4ee3-b5ca-d27cbf18b4fb.png">

运行环境：
python = 3.8.6
pip = 20.3.1
Paddle = 2.4.2
PaddleNLP = 2.5.2
pipelines = 0.5.1

**Comment by lixianli1987** [comment]
我运行起来了，但是生成的问答对不精准，下一步不知道咋个调整了

**Comment by westfish** [comment]
有数据的话可以参考这个训练自定义模型https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B

**Comment by lixianli1987** [comment]
ok 尝试一把，你的问答系统应用起来了吗

**Comment by gg22mm** [comment]
> 有数据的话可以参考这个训练自定义模型https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/unsupervised_qa#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B

您发的连接能训练：

rocketqa-zh-base-query-encoder 与  rocketqa-base-cross-encoder 吗？

如图是调用代码：
![图片](https://user-images.githubusercontent.com/6648329/233297674-68f30e7c-4279-4f3e-be46-524197f526e4.png)

那问问题来了：
1、训练好后怎么放在这里去？
2、我看您发的连接没有训练这两个的，只看到下面的
![图片](https://user-images.githubusercontent.com/6648329/233298773-f942348c-d39c-4ad8-8c8f-d740c9b9a952.png)
![图片](https://user-images.githubusercontent.com/6648329/233298806-e1c06e3d-b615-46cb-a2c0-1fa1e9a7eb02.png)
![图片](https://user-images.githubusercontent.com/6648329/233298981-76d63c07-d38f-48dc-a36e-42c3e6c37fc7.png)

**Comment by XingMingYue** [comment]
看上面报错信息提示打开 question_generation.py 文件47行，写死了device gpu
手动更改为cpu就可以了
