### ISSUE TITLE
[Question]: 为什么example中的codegen模型占用显存比网上的参考大很多

### ISSUE THREAD

**Issue by airob0t** [PaddlePaddle/PaddleNLP#5402]
### 请提出你的问题

按照网上预估codegen
- 2B模型需要至少7G
- 6B模型需要至少12G

我使用Tesla T4 16G运行example中的code_server.py, 只能运行起来2B的模型.
6B模型,即使开了cuda管理内存,仍然OOM.

这是什么原因导致的?

**Comment by gongel** [comment]
网上预估不正确，6B模型FP32在24G左右

**Comment by airob0t** [comment]
> 

差这么多吗?16B模型预估需要多少?

**Comment by gongel** [comment]
16 / 6 * 24
