### ISSUE TITLE
[Question]: 对Codegen进行finetune时，如何实现模型并行？

### ISSUE THREAD

**Issue by Anditty** [PaddlePaddle/PaddleNLP#5405]
### 请提出你的问题

我在尝试对Codegen模型进行finetune，但是由于显卡显存不够，我需要将模型load到多张卡上进行训练。 paddlenlp/exsample/codegen中的finetune脚本似乎只能进行数据并行。想请教一下paddle是否支持codegen这样的大模型进行模型并行的finetune呢？

**Comment by sijunhe** [comment]
您好，paddlenlp下一次发布将会发布打磨好的分布式训练能力。如果您想提前尝试，可以参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/glm/modeling.py 的分布式模型定义
