### ISSUE TITLE
[Question]: 张量模型并行的方法？

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5407]
### 请提出你的问题

在对GLM-6B 模型做Finetune时，如何做模型并行？ 有4张3090卡

**Comment by sijunhe** [comment]
您好，paddlenlp的张量并行正在开发中，将在近期上线

**Comment by xieyu0214** [comment]
> 您好，paddlenlp的张量并行正在开发中，将在近期上线

请问，GLM模型并行的方法可以用了吗？ 看modeling.py中已有相关的代码，请问怎么使用？

**Comment by sijunhe** [comment]
> 请问，GLM模型并行的方法可以用了吗？ 看modeling.py中已有相关的代码，请问怎么使用？

目前代码已经可以跑通，但是使用体验尚未打磨好，如果您想提前尝试，可以参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/glm/README.md#large-%E6%A8%A1%E5%9E%8B%E5%A4%9A%E5%8D%A1%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC%E6%A8%A1%E5%9E%8B%E5%B9%B6%E8%A1%8C%E7%AD%96%E7%95%A5

**Comment by xieyu0214** [comment]
> > 请问，GLM模型并行的方法可以用了吗？ 看modeling.py中已有相关的代码，请问怎么使用？
> 
> 目前代码已经可以跑通，但是使用体验尚未打磨好，如果您想提前尝试，可以参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/glm/README.md#large-%E6%A8%A1%E5%9E%8B%E5%A4%9A%E5%8D%A1%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC%E6%A8%A1%E5%9E%8B%E5%B9%B6%E8%A1%8C%E7%AD%96%E7%95%A5

我昨天就是按照这个运行finetune_generation.py ，发现很奇怪的想象：一张卡24G 3090就能跑GLM-10b-chinese模型，而且batch_size=8/ src_len=1024/tgt_len=100。  finetune后的模型 预测时结果完全不能看，猜测哪里有bug？？
