### ISSUE TITLE
[Question]: 导入paddlenlp后，运行代码报非法指令

### ISSUE THREAD

**Issue by yanghanxx** [PaddlePaddle/PaddleNLP#5427]
### 请提出你的问题

环境python3.8.16
paddlepaddle=2.5.2
paddlenlp=2.4.3
centos7

代码如下：
print("111")
from paddlenlp import Taskflow
print("222")
t = Taskflow("text_similarity")
print(t([["label1", "label2"]]))

报错如下：
![N (11NO1}7 {YLCMMQ0HI3I](https://user-images.githubusercontent.com/127913987/227837110-38136d65-432f-43fa-b80f-288b8982d4e8.png)

**Comment by yanghanxx** [comment]
环境写错了，不好意思
自己编译的python3.8.16
paddlepaddle=2.4.2
paddlenlp=2.5.2
centos7系统

**Comment by guoshengCS** [comment]
这个还不太好定位，您那边可否尝试看下import https://github.com/PaddlePaddle/PaddleNLP/blob/develop/requirements.txt 这里的包看看是否依赖的哪个会报错。另外您那边可否先参考官网 https://www.paddlepaddle.org.cn/ 使用docker环境，也避免后续其他一些环境问题
