### ISSUE TITLE
使用标注工具生成的数据进行uie模型微调训练报错

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#5432]
### 软件环境

```Markdown
1、用 python doccano.py --doccano_file ./data/doccano_ext.json  --task_type "ext" --save_dir ./data --negative_ratio 5  生成数据。
2、生成的数据见附件（实体关系抽取）
3、然后使用下面命令训练微调，直接报错：
export finetuned_model=./checkpoint/model_best

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 16 \
    --per_device_train_batch_size  16 \
    --num_train_epochs 20 \
    --learning_rate 1e-5 \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1



报错：ValueError: num_samples should be a positive integer, but got num_samples=0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
1、用 python doccano.py --doccano_file ./data/doccano_ext.json  --task_type "ext" --save_dir ./data --negative_ratio 5  生成数据。
2、生成的数据见附件（实体关系抽取）
3、然后使用下面命令训练微调，直接报错：
export finetuned_model=./checkpoint/model_best

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 16 \
    --per_device_train_batch_size  16 \
    --num_train_epochs 20 \
    --learning_rate 1e-5 \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1



报错：ValueError: num_samples should be a positive integer, but got num_samples=0
```

### 稳定复现步骤 & 代码

1、用 python doccano.py --doccano_file ./data/doccano_ext.json  --task_type "ext" --save_dir ./data --negative_ratio 5  生成数据。
2、生成的数据见附件（实体关系抽取）
3、然后使用下面命令训练微调，直接报错：
export finetuned_model=./checkpoint/model_best

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 16 \
    --per_device_train_batch_size  16 \
    --num_train_epochs 20 \
    --learning_rate 1e-5 \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1

报错：ValueError: num_samples should be a positive integer, but got num_samples=0[](url)

**Comment by zchengzhong** [comment]
附件数据在这里 @[
[data.zip](https://github.com/PaddlePaddle/PaddleNLP/files/11079344/data.zip)
](url)

**Comment by linjieccc** [comment]
@zchengzhong Hi, 可以适当增加一些标注数据，附件数据里只包含了一条标注数据，导致数据转换后训练集和验证集样本量为零
