### ISSUE TITLE
[Question]: bloom 和 llama 的7b模型多会儿可以使用呢

### ISSUE THREAD

**Issue by loujie0822** [PaddlePaddle/PaddleNLP#5453]
### 请提出你的问题

bloom 和 llama 的7b模型多会儿可以使用呢

**Comment by 1649759610** [comment]
llama可以参考这里：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/llama

**Comment by sijunhe** [comment]
您好，paddlenlp下一次发版会发布大模型训练以及推理能力，同时包含市面上主流的大模型。请耐心等待~

**Comment by loujie0822** [comment]
bloom 和 llama 现在有稳定版本吗？现在都跑不起来，代码本身的问题还有很多。

**Comment by loujie0822** [comment]
@sijunhe 
bloom 和 llama 现在有稳定版本吗？现在都跑不起来，代码本身的问题还有很多。
此外，效果上有对齐吗？特别是在7b模型。

**Comment by sijunhe** [comment]
> @sijunhe bloom 和 llama 现在有稳定版本吗？现在都跑不起来，代码本身的问题还有很多。 此外，效果上有对齐吗？特别是在7b模型。

预计4月底有稳定版本~
