### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fxb392** [PaddlePaddle/PaddleNLP#5457]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp: 
paddle-bfloat      0.1.7
paddlepaddle-gpu   2.4.2.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用ernie-health 提供的微调ner代码train_ner.py加载模型报错
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/40045460/228420118-e72085ec-01f2-4b9f-82bc-88c257da98ce.png)

![image](https://user-images.githubusercontent.com/40045460/228419936-473530e7-4008-4268-bd78-d5bf7e800a6f.png)

**Comment by LemonNoel** [comment]
您好，可以贴下详细的报错信息吗？

**Comment by fxb392** [comment]
&nbsp;


冯晓斌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 下午2:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Bug]:  (Issue #5457)





 
您好，可以贴下详细的报错信息吗？

**Comment by fxb392** [comment]
加载预训练模型传的类编参数是个num_classes=[33,5]的列表,

range(num_labels)报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月29日(星期三) 下午2:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Bug]:  (Issue #5457)





 
您好，可以贴下详细的报错信息吗？
