### ISSUE TITLE
想问下ernie-vil2.0可以用trt导出静态图么，可否通过paddle静态图部署使用trt的fp16推理实现进一步的模型推理加速？

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleNLP#5458]
### 请提出你的问题

想问下ernie-vil2.0可以用trt导出静态图么

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 想问下ernie-vil2.0可以用trt导出静态图么

可以使用fastdeploy,然后fastdeploy支持trt。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-vil2.0#%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E9%A2%84%E6%B5%8B
