### ISSUE TITLE
[Question]: 文档信息抽取UIEX未来会支持data_distill吗

### ISSUE THREAD

**Issue by JunzheLin** [PaddlePaddle/PaddleNLP#5467]
### 请提出你的问题

如题，目前文本信息抽取UIE有模型蒸馏：[PaddleNLP-develop\applications\information_extraction\text\data_distill](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text/data_distill)
但文档信息抽取没有，经过测试，文本信息抽取的data_distill无法在document的模型中直接使用。因为很多参数不一样：
![image](https://user-images.githubusercontent.com/61039043/228536735-4359b31b-9f5b-4d18-b9da-9f0f87e3d2d3.png)
请问后期UIEX会有数据蒸馏工具吗？大概何时公布？

**Comment by linjieccc** [comment]
@z5z56 HI 这块的工作目前还没有合入develop，你可以用这个分支的代码尝试下：https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain
