### ISSUE TITLE
语义索引任务如何评估自己的模型？

### ISSUE THREAD

**Issue by justiceeem** [PaddlePaddle/PaddleNLP#547]
semantic indexing里提供的评估方法——构造一个评估集，然后使用R@10与R@50来评估模型。
请问这个方法适合自己场景下训练的模型吗？是直接使用开源的数据集（比如例子里提供的数据集）还是需要自己收集数据构建此场景下的相似对？
那如果是自己收集不了太多数据的情况下，怎么才能更好的评估自己的模型呢？
我当前的情况是凭感觉，随机写几条语句测试。还望大佬们多多指教！

**Comment by tianxin1860** [comment]
> semantic indexing里提供的评估方法——构造一个评估集，然后使用R@10与R@50来评估模型。
> 请问这个方法适合自己场景下训练的模型吗？是直接使用开源的数据集（比如例子里提供的数据集）还是需要自己收集数据构建此场景下的相似对？
> 那如果是自己收集不了太多数据的情况下，怎么才能更好的评估自己的模型呢？
> 我当前的情况是凭感觉，随机写几条语句测试。还望大佬们多多指教！

因为每个细分场景下的数据分布有很大不同，建议按照 semantic indexing 里的评估方式构造自己场景的评估数据来评估模型效果，如果自己场景的数据量太少，可以考虑先基于我们开源的评估集进行评估，作为一个参考结果。

**Comment by justiceeem** [comment]
谢谢 @tianxin1860
