### ISSUE TITLE
[Question]: 索引库中的内容可以指定删除么

### ISSUE THREAD

**Issue by lixianli1987** [PaddlePaddle/PaddleNLP#5473]
### 请提出你的问题

例如：问答对源文件source_file.txt，生成的索引文件test_index。
需求：因某些原因，需要删除或新增source_file.txt文件中的某个问答对，请问在索引中怎么找得到这个问答进行删除或新增。

**Comment by w5688414** [comment]
可以在elastic search里面进行删除，或者使用document store的API进行删除。
https://github.com/PaddlePaddle/PaddleNLP/blob/0df89760936039a7199dac530881d471df04d566/pipelines/pipelines/document_stores/elasticsearch.py#L1548

**Comment by lastrei** [comment]
milvus，Elasticsearch 都可在cli里使用命令行删除。
