### ISSUE TITLE
[Question]: ERNIE-Layout 可以转成onnx模型格式吗？

### ISSUE THREAD

**Issue by liyandongpy** [PaddlePaddle/PaddleNLP#5477]
### 请提出你的问题

ERNIE-Layout 做版面分析，文档分类时，能转化成onnx格式的模型进行infer 吗？

**Comment by linjieccc** [comment]
可以，这块的工作在进行中[ERNIE-Layout FastDeploy部署](https://github.com/PaddlePaddle/PaddleNLP/pull/5153)，欢迎持续关注~
