### ISSUE TITLE
[Question]: 无监督检索式问答系统样例提取的问答对个数不够

### ISSUE THREAD

**Issue by lixianli1987** [PaddlePaddle/PaddleNLP#5478]
### 请提出你的问题

我给的源文件内容：
“张三来自于湖北，本科就读于江汉大学，电子信息工程专业，2011年考研来到成都信息工程大学，电子与通信工程专业，2014年研究生毕业。第一份工作就职于成都lqd科技有限公司，从事java后端开发工作；第二份工作就职于成都hqy科技有限公司，从事软件设计工作。第三份工作就职于tqls group，从事系统架构工作。毕业快10年了，掌握后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等技术栈。”
一、无监督提取出来的问答对：
张三是哪里人	湖北
张三的家乡到底是哪里？	湖北
张三是成都哪个大学毕业的？	成都信息工程大学
二、总结：提取的问题准确度还是可以，但是问答对的个数不够多，我希望提取的问答对内容是
张三是哪里人  湖北
张三本科是哪个学校  江汉大学
张三本科是什么专业  电子信息工程
张三研究生是什么专业  电子与通信工程
张三考研是哪一年  2011年
张三哪一年研究生毕业  2014年
张三第一份工作是哪个公司  成都lqd科技有限公司
张三第一份工作从事  java后端开发
张三第二份工作是哪个公司  成都hqy科技有限公司
张三第二份工作从事  软件设计
张三第三份工作是哪个公司  tqls group
张三第三份工作从事  系统架构
张三掌握哪些技能  后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等。
三、请问怎样可以增加提取问答对的个数

**Comment by zouchl** [comment]
> ### 请提出你的问题
> 我给的源文件内容： “张三来自于湖北，本科就读于江汉大学，电子信息工程专业，2011年考研来到成都信息工程大学，电子与通信工程专业，2014年研究生毕业。第一份工作就职于成都lqd科技有限公司，从事java后端开发工作；第二份工作就职于成都hqy科技有限公司，从事软件设计工作。第三份工作就职于tqls group，从事系统架构工作。毕业快10年了，掌握后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等技术栈。” 一、无监督提取出来的问答对： 张三是哪里人 湖北 张三的家乡到底是哪里？ 湖北 张三是成都哪个大学毕业的？ 成都信息工程大学 二、总结：提取的问题准确度还是可以，但是问答对的个数不够多，我希望提取的问答对内容是 张三是哪里人 湖北 张三本科是哪个学校 江汉大学 张三本科是什么专业 电子信息工程 张三研究生是什么专业 电子与通信工程 张三考研是哪一年 2011年 张三哪一年研究生毕业 2014年 张三第一份工作是哪个公司 成都lqd科技有限公司 张三第一份工作从事 java后端开发 张三第二份工作是哪个公司 成都hqy科技有限公司 张三第二份工作从事 软件设计 张三第三份工作是哪个公司 tqls group 张三第三份工作从事 系统架构 张三掌握哪些技能 后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等。 三、请问怎样可以增加提取问答对的个数

**Comment by zouchl** [comment]
> ### 请提出你的问题
> 我给的源文件内容： “张三来自于湖北，本科就读于江汉大学，电子信息工程专业，2011年考研来到成都信息工程大学，电子与通信工程专业，2014年研究生毕业。第一份工作就职于成都lqd科技有限公司，从事java后端开发工作；第二份工作就职于成都hqy科技有限公司，从事软件设计工作。第三份工作就职于tqls group，从事系统架构工作。毕业快10年了，掌握后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等技术栈。” 一、无监督提取出来的问答对： 张三是哪里人 湖北 张三的家乡到底是哪里？ 湖北 张三是成都哪个大学毕业的？ 成都信息工程大学 二、总结：提取的问题准确度还是可以，但是问答对的个数不够多，我希望提取的问答对内容是 张三是哪里人 湖北 张三本科是哪个学校 江汉大学 张三本科是什么专业 电子信息工程 张三研究生是什么专业 电子与通信工程 张三考研是哪一年 2011年 张三哪一年研究生毕业 2014年 张三第一份工作是哪个公司 成都lqd科技有限公司 张三第一份工作从事 java后端开发 张三第二份工作是哪个公司 成都hqy科技有限公司 张三第二份工作从事 软件设计 张三第三份工作是哪个公司 tqls group 张三第三份工作从事 系统架构 张三掌握哪些技能 后端底层框架、对象映射框架、数据库、缓存、消息队列、大数据等。 三、请问怎样可以增加提取问答对的个数

我用你这个 生成的答案 都只有一个字。 是哪里配置不对吗
问题：张三是什么专业

答案：列
