### ISSUE TITLE
[Question]: UIE-X 继续训练

### ISSUE THREAD

**Issue by Originhhh** [PaddlePaddle/PaddleNLP#5484]
### 请提出你的问题

您好，我想问一下我之前通过对一类数据微调得到了一个模型。现在我会增加一类数据，想在之前模型的基础上继续训练，应该如何操作呢，这样做会影响我之前那类数据的抽取效果吗

**Comment by linjieccc** [comment]
@Originhhh 建议和原先的标注数据合并重新基于UIE-X微调

**Comment by 471417367** [comment]
请问，训练的finetune.py是在哪儿的呢
