### ISSUE TITLE
[Question]: CodeGen基于2B模型训练时内存飚满导致训练失败

### ISSUE THREAD

**Issue by tutuxxx** [PaddlePaddle/PaddleNLP#5486]
### 请提出你的问题

# 环境信息
* 机器内存信息：
![image](https://user-images.githubusercontent.com/14323022/229012197-214daa30-7389-4ac9-8964-ee9af668f3ae.png)
* 显卡信息：
![image](https://user-images.githubusercontent.com/14323022/229012284-1f4ce99e-94cc-447a-9790-af75522ea807.png)
* python版本：3.7.4
* paddlenlp版本：2.4.5

# 训练参数
* 训练参数：
![image](https://user-images.githubusercontent.com/14323022/229012698-63919f47-678c-4573-b45a-5c3145a00ecb.png)
* 数据集：两个js文件，大概1000多字符

# 问题表现
训练时机器内存会上升到100%，导致机器卡死，ssh无法连接。
![image](https://user-images.githubusercontent.com/14323022/229012504-f86bcb1b-fb2f-4f01-b27c-7b23ca49700e.png)

请问这个问题有解决方案吗

**Comment by sijunhe** [comment]
是内存满还是显存满呢？内存满的话，一般是是data loader没做好

**Comment by tutuxxx** [comment]
> 是内存满还是显存满呢？内存满的话，一般是是data loader没做好

内存满，请问data loader需要怎么做呢，没在readme中看到相关信息。目前我这边是只补充了train.json，格式如下
![image](https://user-images.githubusercontent.com/14323022/229475084-c46f1825-8607-4fff-a939-97bc4c143b90.png)

**Comment by gongel** [comment]
> > 是内存满还是显存满呢？内存满的话，一般是是data loader没做好
> 
> 内存满，请问data loader需要怎么做呢，没在readme中看到相关信息。目前我这边是只补充了train.json，格式如下 ![image](https://user-images.githubusercontent.com/14323022/229475084-c46f1825-8607-4fff-a939-97bc4c143b90.png)

请问数据量多大呢？

**Comment by tutuxxx** [comment]
@gongel  只有上图所示的两个js文件，大概1000多字符
