### ISSUE TITLE
paddlenlp paddlepaddle cuda版本 有没有一个对应的兼容性表？

### ISSUE THREAD

**Issue by White2White** [PaddlePaddle/PaddleNLP#5489]
### 请提出你的问题

paddlenlp paddlepaddle cuda版本 有没有一个对应的兼容性表？

**Comment by w5688414** [comment]
官方有对应cuda的paddle安装方法，其他cuda版本的paddle需要自己编译。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
