### ISSUE TITLE
[Question]: 走ernie_layout的官方demo做docvqa训练后，无法infer

### ISSUE THREAD

**Issue by Nomia** [PaddlePaddle/PaddleNLP#5493]
### 请提出你的问题

我看的是这个文档：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#42-%E6%96%87%E6%A1%A3%E8%A7%86%E8%A7%89%E9%97%AE%E7%AD%94%E4%BB%BB%E5%8A%A1

做的是docvqa训练：
<img width="602" alt="image" src="https://user-images.githubusercontent.com/1707818/229061008-53c1da14-d18f-47aa-9f89-ae34226ae4cf.png">

训练完后导出了模型：
<img width="339" alt="image" src="https://user-images.githubusercontent.com/1707818/229061081-1ca648ac-e8b5-4dd3-b92d-b645b768d45f.png">

然后继续按官方教程做inference：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/README_ch.md

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1707818/229061300-e71acfe1-05c3-45f6-a9c2-a020b993c619.png">

下面是我执行inference的代码，没有报错，但是得到的是空数组：
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/1707818/229061480-41d5ddb6-e8da-4dc5-8660-a02a05708e9e.png">

**Comment by linjieccc** [comment]
@Nomia 你好，训练后的模型精度可以到多少呢

**Comment by Nomia** [comment]
ernie_layout不是本身就可以taskflow做pipeline吗，我看官方的示例都是可以直接用的，所以我以为稍微微调一下就可以了，下面是官方README.md的示例

![image](https://user-images.githubusercontent.com/1707818/229174970-b18b3228-ff97-422d-b6fc-e129ad1ee778.png)

官方的这个是经过经过非常高的精度的finetune之后的吗？
我怎么可以直接拿到官方这个模型(.pdmodel文件)呢 @linjieccc

**Comment by linjieccc** [comment]
docprompt在大量QA数据上基于ernie-layout做了二次预训练，目前预训练流程没有开源

这里推理例子是完整跑完mrc微调流程后的best model，数据集是[DocVQA-ZH](http://ailab.aiwin.org.cn/competitions/49)

**Comment by Randy1009** [comment]
您好，原始的DocVQA-ZH数据集百度网盘下载链接失效了，请问可以分享一下您下载的数据吗，谢谢！
