### ISSUE TITLE
请问层次文本分类模型对于判断是否患有某种疾病，输入什么句子都会预测患病，这个怎么解决呢？

### ISSUE THREAD

**Issue by QChen0409** [PaddlePaddle/PaddleNLP#5497]
### 请提出你的问题

请问层次文本分类模型对于判断是否患有某种疾病，输入什么句子都会预测患病，这个怎么解决呢？是否患病两个类的概率差值特别大，0.998和0.002这种？可以调整吗？

**Comment by lastrei** [comment]
试试增加neg label

**Comment by lugimzzz** [comment]
没太明白具体的场景？
