### ISSUE TITLE
[Question]: codegen demo 要达到毫秒级的性能需要如何优化？

### ISSUE THREAD

**Issue by SilentTiger** [PaddlePaddle/PaddleNLP#5503]
### 请提出你的问题

我跑了 16B-multi 模型的 codegen server，每次生成代码时间都要 1 秒以上。
硬件配置：
GPU A100-SXM4-80GB(80GB) * 1
CPU 14 vCPU Intel(R) Xeon(R) Platinum 8352M CPU @ 2.30GHz
内存 228GB
<img width="958" alt="image" src="https://user-images.githubusercontent.com/764862/229402778-5e3830f1-1d12-426f-94f3-b69cc3000bb6.png">

想请教一下如何优化才能使得每次生成代码的时间在 300ms 以下？
另外还想请教一下，如果想让这个模型能真正为一个 100 人左右的开发团队服务，大概需要怎样的硬件配置？

**Comment by gongel** [comment]
你好，可考虑走多卡预测，这个优化需要点成本。16B模型fp16下单卡40G可以load。

**Comment by leojames** [comment]
哥们问一下 你的A100 load 16B 模型需要多久  我的load了N久 貌似没反应不知道为啥
