### ISSUE TITLE
[Question]: gradient_accumulation_steps 这个参数的使用方法？

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5505]
### 请提出你的问题

在使用过程中，没理解 gradient_accumulation_steps这个参数的正确使用方法。

比如`args.batch_size = 1, args. gradient_accumulation_steps=16 ` ：是表示 在16个batch后才进行一次梯度计算和参数更新吗？？ 

gradient_accumulation_steps 这个参数的目的，是用来降低机器资源不足的情况吗

**Comment by sijunhe** [comment]
> gradient_accumulation_steps 这个参数的目的，是用来降低机器资源不足的情况吗

是的。gradient_accumulation的使用场景是需要大batch size但是没有足够大的显存。如果gradient_accumulation=16, 那么会做16次forward，算好梯度，最后做一次参数update. 相当于增大batch size 16倍
