### ISSUE TITLE
请问ERNIE ViL2在finetune的时候，可以冻结视觉模型或者语言模型的某些层吗

### ISSUE THREAD

**Issue by wangpx0906** [PaddlePaddle/PaddleNLP#5522]
### 请提出你的问题

请问ERNIE ViL2在finetune的时候，可以冻结视觉模型或者语言模型的某些层吗

**Comment by w5688414** [comment]
可以设置stop_gradient为True即可。具体请参考文档：

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#tensor-stop-gradient
