### ISSUE TITLE
[Question]: 运行train文件时，出现属性错误，有那位大神指点一下

### ISSUE THREAD

**Issue by zxcvbnm29** [PaddlePaddle/PaddleNLP#5533]
### 请提出你的问题

数据是官方的数据，代码也是，但是在运行train文件时，出现属性错误，'NoneType' object has no attribute 'backward'
报错如下
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    do_train()
  File "train.py", line 216, in do_train
    loss.backward()
AttributeError: 'NoneType' object has no attribute 'backward'

**Comment by linjieccc** [comment]
重新提问 #5534 已进行解答，这个issue先关闭了哈
