### ISSUE TITLE
[Bug]: 只要一运行train文件，就会出现属性错误，'NoneType' object has no attribute 'backward'

### ISSUE THREAD

**Issue by zxcvbnm29** [PaddlePaddle/PaddleNLP#5534]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.3.2
- paddlenlp:  2.0.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
数据是官方的数据，代码也是，但是在运行train文件时，出现属性错误，'NoneType' object has no attribute 'backward'
报错如下
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    do_train()
  File "train.py", line 216, in do_train
    loss.backward()
AttributeError: 'NoneType' object has no attribute 'backward'
```

### 稳定复现步骤 & 代码

root_path=inbatch
data_path=data
python -u -m paddle.distributed.launch --gpus "0,1" \
    train.py \
    --device gpu \
    --save_dir ./checkpoints/${root_path} \
    --batch_size 24 \
    --learning_rate 5E-5 \
    --epochs 100 \
    --output_emb_size 0 \
    --save_steps 50 \
    --max_seq_length 384 \
    --warmup_proportion 0.0 \
    --margin 0.2 \
    --recall_result_dir "recall_result_dir" \
    --recall_result_file "recall_result.txt" \
    --train_set_file ${data_path}/train.txt \
    --corpus_file ${data_path}/label.txt   \
    --similar_text_pair_file ${data_path}/dev.txt \
    --evaluate True

Traceback (most recent call last):
  File "train.py", line 244, in <module>
    do_train()
  File "train.py", line 216, in do_train
    loss.backward()
AttributeError: 'NoneType' object has no attribute 'backward'

**Comment by w5688414** [comment]
请升级一下paddlenlp至 2.5.2， paddle版本升级到2.4.2

**Comment by zxcvbnm29** [comment]
还是不行啊

**Comment by zhuyuhao2333** [comment]
请问问题解决了吗？
