### ISSUE TITLE
msra_ner数据集（文档问题）

### ISSUE THREAD

**Issue by 1084667371** [PaddlePaddle/PaddleNLP#554]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/data_prepare/dataset_load.rst

![image](https://user-images.githubusercontent.com/50902619/121651896-b04ee900-cacd-11eb-90b5-b7b5c684c863.png)

问题：msra_ner数据集没有dev  只有 train test  这里写错了

![image](https://user-images.githubusercontent.com/50902619/121652322-1c315180-cace-11eb-95ef-dd601ef31b10.png)

**Comment by smallv0221** [comment]
已修改，感谢提醒！

**Comment by 1084667371** [comment]
okok
