### ISSUE TITLE
[Question]: Diffusion模型导出报错（FastDeploy Stable Diffusion 模型高性能部署）

### ISSUE THREAD

**Issue by XiaoqingWang** [PaddlePaddle/PaddleNLP#5540]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/deploy/export.md
FastDeploy布署diffusion模型，目前是不是只支持linux系统？
在win10系统下，导出sd模型时报错，方便的话，烦请帮忙看一下，感谢

python export_model.py --pretrained_model_name_or_path runwayml/stable-diffusion-v1-5 --output_path stable-diffusion-v1-5 --height=512 --width=512
e:\ProgramData\Anaconda3\envs\psd\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[FastDeploy][INFO]:  Successfully found CUDA ToolKit from system PATH env -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin
W0406 10:34:19.950145 21524 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0406 10:34:20.081827 21524 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Fetching 18 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 1388.71it/s]
[2023-04-06 10:34:51,590] [    INFO] - loading configuration file C:\Users\Administrator/.cache\paddlenlp\ppdiffusers\runwayml/stable-diffusion-v1-5\text_encoder\config.json
[2023-04-06 10:34:51,593] [    INFO] - Model config CLIPTextConfig {
  "_name_or_path": "openai/clip-vit-large-patch14",
  "architectures": [
    "CLIPTextModel"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "dropout": 0.0,
  "eos_token_id": 2,
  "hidden_act": "quick_gelu",
  "hidden_size": 768,
  "initializer_factor": 1.0,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 77,
  "model_type": "clip_text_model",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "paddlenlp_version": null,
  "projection_dim": 512,
  "return_dict": true,
  "torch_dtype": "float32",
  "transformers_version": "4.21.0.dev0",
  "vocab_size": 49408
}

You have disabled the safety checker for <class 'ppdiffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. PaddleNLP team, diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
cross_attention_dim: 768
 unet_in_channels: 4
 vae_encoder_in_channels: 3
 vae_decoder_latent_channels: 4
Save text_encoder model in stable-diffusion-v1-5\text_encoder\inference successfully.
Save unet model in stable-diffusion-v1-5\unet\inference successfully.
Save vae_encoder model in stable-diffusion-v1-5\vae_encoder\inference successfully.
Save vae_decoder model in stable-diffusion-v1-5\vae_decoder\inference successfully.
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0406 10:37:18.641384 21524 analysis_config.cc:958] It is detected that mkldnn and memory_optimize_pass are enabled at the same time, but they are not supported yet. Currently, memory_optimize_pass is explicitly disabled
[INFO] fastdeploy/runtime/runtime.cc(266)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(266)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(266)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
UnavailableError: An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:93)

Traceback (most recent call last):
  File "F:\ai\paddle\PaddleNLP-develop\ppdiffusers\deploy\export_model.py", line 168, in <module>
    convert_ppdiffusers_pipeline_to_fastdeploy_pipeline(
  File "F:\ai\paddle\PaddleNLP-develop\ppdiffusers\deploy\export_model.py", line 140, in convert_ppdiffusers_pipeline_to_fastdeploy_pipeline
    unet=FastDeployRuntimeModel.from_pretrained(output_path / "unet"),
  File "e:\ProgramData\Anaconda3\envs\psd\lib\site-packages\ppdiffusers\pipelines\fastdeploy_utils.py", line 317, in from_pretrained
    return cls._from_pretrained(
  File "e:\ProgramData\Anaconda3\envs\psd\lib\site-packages\ppdiffusers\pipelines\fastdeploy_utils.py", line 244, in _from_pretrained
    model = FastDeployRuntimeModel.load_model(
  File "e:\ProgramData\Anaconda3\envs\psd\lib\site-packages\ppdiffusers\pipelines\fastdeploy_utils.py", line 129, in load_model
    return fd.Runtime(option)
  File "e:\ProgramData\Anaconda3\envs\psd\lib\site-packages\fastdeploy\runtime.py", line 33, in __init__
    assert self._runtime.init(
RuntimeError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
UnavailableError: An error occurred while loading model parameters. Please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(*buffer) == true, but received static_cast<bool>(*buffer):0 != true:1.] (at ..\paddle/fluid/operators/load_combine_op.h:93)
  [operator < load_combine > error]

**Comment by JunnYu** [comment]
当前fastdeploy+ppdiffusers sd可能不太支持windows系统，但是你可以试一下更新最新的 paddlepaddle和fastdeploy，然后尝试继续导出一下
```sh
# 我这里用cuda117为例，安装paddlepaddle
python -m pip install paddlepaddle-gpu==0.0.0.post117 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
pip install fastdeploy-gpu-python==0.0.0 -f https://www.paddlepaddle.org.cn/whl/fastdeploy_nightly_build.html
```
