### ISSUE TITLE
[Question]: 无监督智能检索问答通过UI的问答对生成生成问答以及上传文件生成问答对报错

### ISSUE THREAD

**Issue by chanlong** [PaddlePaddle/PaddleNLP#5546]
### 请提出你的问题

问题一
<img width="867" alt="image" src="https://user-images.githubusercontent.com/11283440/230279220-04883486-58cb-47c7-a65a-3d3fab3847fa.png">
如图：输入文本后点击“开始生成”，提示“An error occurred during the request.”

问题二
<img width="313" alt="image" src="https://user-images.githubusercontent.com/11283440/230279564-75554be0-6d9f-45ba-9ca5-54d09d4203e8.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/11283440/230280271-c0765e51-da6a-4c64-b2f0-e9db3df7ffb9.png">
如图：选择文件后点击“文件上传并自动生成载入问答对”，提示json解析错误

**Comment by longhail2008** [comment]
请问这个问题解决了吗？ 除了这个问题我也遇到过；在上传文本语料自动生成问答对并且保存数据库之后，截图显示OK，但是下面问答检索报错了，没有输出结果，能帮看下么
