### ISSUE TITLE
[Question]: 自己可以把PPDiffuser内置到stable diffusion webui中使用吗

### ISSUE THREAD

**Issue by liuguicen** [PaddlePaddle/PaddleNLP#5561]
### 请提出你的问题

自己可以把PPDiffuser内置到stable diffusion webui中使用吗，就是说结合使用PPDiffuser的加速能力和stable diffusion webui的各种操作特性

**Comment by w5688414** [comment]
> stable diffusion webui

目前是不支持的，需要做一点paddle的适配，欢迎贡献一下。或者参考一下开发者的贡献。
https://github.com/tensorfly-gpu/PPdiffusers-webui
