### ISSUE TITLE
[Question]: pipelines中的语义检索的功能感觉已经覆盖了非监督式问答的功能？

### ISSUE THREAD

**Issue by jooze** [PaddlePaddle/PaddleNLP#5570]
### 请提出你的问题

 pipelines中的语义检索的功能感觉已经覆盖了非监督式问答的功能？
我仅是一名初学者，觉得两个的功能很类似，不知道对不对

**Comment by w5688414** [comment]
可以这么理解，直接用语义检索搭建FAQ智能问答，如果想提升准确率，那就需要进一步训练调优
