### ISSUE TITLE
[Question]:  在A机器上编译了fast generation ，在B机器上使用时如何避免再重新编译？

### ISSUE THREAD

**Issue by zzcgithub** [PaddlePaddle/PaddleNLP#5572]
### 请提出你的问题

将A机器上编译得到的库（libboost.a. libdecoding_op.so拷贝到B机器，在运行前将其添加到LD_LIBRARY_PATH，没有解决问题。

**Comment by gongel** [comment]
请问怎么使用的？

**Comment by zzcgithub** [comment]
希望部署服务使用。
在A机器上使用fast模式处理数据,  然后触发编译libboost.a. libdecoding_op.so， 编译完成后可以正常使用。

在B机器上想使用fast模式处理数据，为了避免重新编译， 将A上编译好的libboost.a. libdecoding_op.so拷贝到so目录中，并在运行前将其添加到LD_LIBRARY_PATH。 但是运行时，程序仍然重新进行编译了。

是否是我使用方法错误？

**Comment by zzcgithub** [comment]
参考：BART修改函数的输入decoding_lib = kwargs.get("decoding_lib", None) 和FastT5 forward的输入即可。

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bart/modeling.py#L955-L982
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/t5/modeling.py#L1645-L1662

**Comment by benyang0506** [comment]
请问解决了吗

**Comment by gongel** [comment]
> 请问解决了吗

参考上面的方案 https://github.com/PaddlePaddle/PaddleNLP/issues/5572#issuecomment-1502834769
