### ISSUE TITLE
[Question]: UIE-X可以在版面分析的table里面做关系抽取吗

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#5599]
### 请提出你的问题

# 版面分析识别为table以后，生成的正负例会少一大半,同时关系抽取也出现抽取不到关系混乱
![DK5%0QB)ZQ0CKAG39HGR%QK](https://user-images.githubusercontent.com/44227598/231029071-8143014c-689a-478c-9a0f-7cf61fb91a7b.png)

**Comment by linjieccc** [comment]
@1061302569 使用版面分析功能时将返回完整table cell区域的bbox，``layout_analysis=True``时当前还不支持对表格内部进行关系抽取
