### ISSUE TITLE
预训练模型下载地址修改

### ISSUE THREAD

**Issue by turkeymz** [PaddlePaddle/PaddleNLP#560]
建议在readme里面添加预训练模型环境变量地址修改的提示。
我之前遇到过磁盘空间不够，原因就是这个问题
但不是所有人都会debug源码去查看框架读的是哪个系统变量

**Comment by ZeyuChen** [comment]
很好的建议！ 
@chenxiaozeng 请将更改数据和模型环境变量作为FAQ文档的一部分。
```
export PPNLP_HOME=xxxx
```

**Comment by yingyibiao** [comment]
参见：https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#q1-2-paddlenlp
