### ISSUE TITLE
[Question]: PaddleNLP 文本摘要例子结果异常

### ISSUE THREAD

**Issue by icylord** [PaddlePaddle/PaddleNLP#5602]
### 请提出你的问题

这个链接的例子：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/taskflow.md 
示例代码：
from paddlenlp import Taskflow
summarizer = Taskflow("text_summarization")

summarizer(
        '据悉，2022年教育部将围绕“巩固提高、深化落实、创新突破”三个关键词展开工作。要进一步强化学校教育主阵地作用，继续把落实“双减”作为学校工作的重中之重，重点从提高作业设计水平、提高课后服务水平、提高课堂教学水平、提高均衡发展水平四个方面持续巩固提高学校“双减”工作水平。'
    )

示例给出的结果是：
'教育部：将从四个方面持续巩固提高学校“双减”工作水平'

实际运行输出结果是：
['校车']

这偏差也太离谱了吧，是不是哪里有问题导致？

**Comment by wawltor** [comment]
文本摘要提供的模型不是一个通用模型，依赖自己的数据来自己微调https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_summarization/finetune

**Comment by icylord** [comment]
不是一个通用模型这个我可以理解；
在这里只是想问下，为什么按照示例跑出来的结果跟官方给出来的不一致，且结果偏差有点大

**Comment by gongel** [comment]
可以考虑换下模型，
```python
summarizer = Taskflow("text_summarization", model="IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1")
```
这是模型列表：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/taskflow.py#L258-L287

**Comment by icylord** [comment]
> 可以考虑换下模型，
> 
> ```python
> summarizer = Taskflow("text_summarization", model="IDEA-CCNL/Randeng-Pegasus-523M-Summary-Chinese-V1")
> ```
> 
> 这是模型列表：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/taskflow.py#L258-L287

谢谢，哈。 估计是默认的模型变化了导致。
