### ISSUE TITLE
[Bug]: 使用fastdeploy的高性能部署stablediffusion出现分词器错误

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleNLP#5616]
### 软件环境

```Markdown
- paddlepaddle:dev最新
- paddlenlp: dev最新
- fast-deploy：dev最新
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/deploy
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行任意如：
python text_to_img_infer.py --model_dir stable-diffusion-v1-4/ --scheduler "pndm" --backend paddle
```

### 稳定复现步骤 & 代码

![image](https://user-images.githubusercontent.com/96160062/231153750-bed734af-7c53-4b6f-bcd1-2454be7ea03e.png)

**Comment by JunnYu** [comment]
你好，这里的话你需要是首先自己导出对应的模型，然后才可以使用本地的`stable-diffusion-v1-4/`这个文件夹里面的模型
