### ISSUE TITLE
[Question]:  开箱即用的 信息抽取-命名实体识别任务中，实体名称如何定义？

### ISSUE THREAD

**Issue by xiabingbao-ok** [PaddlePaddle/PaddleNLP#5632]
### 请提出你的问题

 schema = ['时间', '选手', '赛事名称'] 中的”时间“、”选手“等是怎么确定的？如果我想识别文本中：电视节目，请问”电视节目“在模型的训练数据集中吗？还是使用了什么方法？

>>> from pprint import pprint
>>> from paddlenlp import Taskflow

>>> schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
>>> ie = Taskflow('information_extraction', schema=schema)
>>> pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
[{'时间': [{'end': 6,
          'probability': 0.9857378532924486,
          'start': 0,
          'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,
            'probability': 0.8503089953268272,
            'start': 6,
            'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,
          'probability': 0.8981548639781138,
          'start': 28,
          'text': '谷爱凌'}]}]

**Comment by cuyoo** [comment]
据我所知开箱即用就是直接改“schema ”实体名称。
你要自己训练数据才需要标注实名名称和关系。
