### ISSUE TITLE
卡死： python milvus_ann_search.py --data_path data/qa_pair.csv --embedding_path corpus_embedding.npy --batch_size 100000  --insert

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5633]
### 软件环境

```Markdown
(paddle38) [root@localhost faq_finance]# pip list | grep paddle
paddle-bfloat                  0.1.7
paddle-pipelines               0.5.2
paddle2onnx                    1.0.6
paddlefsl                      1.1.0
paddlenlp                      2.5.2
paddleocr                      2.6.1.3
paddlepaddle-gpu               2.4.2
x2paddle                       1.4.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
#尝试修复，不知对不对
vi \paddleNLP\applications\question_answering\supervised_qa\faq_finance\milvus_util.py

def create_index(self, index_name):
        try:
            print(fmt.format("Start Creating index"))
            
            #官方到这里直接卡死
            self.collection.create_index(index_name, index_config) 
            print(fmt.format("Start loading")) 
            self.collection.load()

            # 自己修改 collection 替换成 connections 解决官方到这里直接卡死
            # self.connections.create_index(index_name, index_config)
            # print(fmt.format("Start loading")) 
            # self.connections.load()    
                       

        except Exception as e:
            print("Milvus create index error:", e)
```

### 稳定复现步骤 & 代码

卡死在这里： python milvus_ann_search.py --data_path data/qa_pair.csv --embedding_path corpus_embedding.npy --batch_size 100000  --insert
![图片](https://user-images.githubusercontent.com/6648329/231430507-97de2989-e295-4537-afc7-9720b7f51855.png)

#尝试修复，不知对不对 vi \paddleNLP\applications\question_answering\supervised_qa\faq_finance\milvus_util.py
def create_index(self, index_name):
        try:
            print(fmt.format("Start Creating index"))
            
            #官方到这里直接卡死
            self.collection.create_index(index_name, index_config) 
            print(fmt.format("Start loading")) 
            self.collection.load()

            # 自己修改 collection 替换成 connections 解决官方到这里直接卡死
            # self.connections.create_index(index_name, index_config)
            # print(fmt.format("Start loading")) 
            # self.connections.load()    
                       

        except Exception as e:
            print("Milvus create index error:", e)

![图片](https://user-images.githubusercontent.com/6648329/231430850-08e6041e-7821-4ea7-a599-500e22219da9.png)

**Comment by w5688414** [comment]
请问一下您的milvus版本是多少？milvus_ann_search对应的pymilvus版本是2.1

**Comment by gg22mm** [comment]
版本是：v2.1.4
![图片](https://user-images.githubusercontent.com/6648329/231653722-1344bb39-95e7-4ec3-97bf-eb676dcd4ac5.png)

![图片](https://user-images.githubusercontent.com/6648329/231652250-3b4f011a-2ad7-4084-bdf7-1bb8c0d06cb5.png)

配置milvus：
	vi \paddle\PaddleNLP\applications\question_answering\supervised_qa\faq_finance\config.py
	MILVUS_HOST = "10.10.10.123" #milvus连接ip
	MILVUS_PORT = 19530			 #milvus连接端口


然后就是上面的先用官方代码运行卡死：
![图片](https://user-images.githubusercontent.com/6648329/231652682-b1357cf3-965f-4a50-8d50-e786755263d6.png)

然后改成自己的：
![图片](https://user-images.githubusercontent.com/6648329/231652870-37f1ec10-3f65-4f2c-a26f-e1e910348fad.png)


运行后怎么都是些数字？不是中文
![图片](https://user-images.githubusercontent.com/6648329/231661424-99e0010c-ee76-4800-b813-92ea52729cde.png)

**Comment by gg22mm** [comment]
算了，反正我也不用  “部署” 这一块代码  ，  也不会用到 “ Document Store ”
我只用到：模型推理， 我只想： 召回+排序自己拼接
