### ISSUE TITLE
使用unimo-text-1.0-large时摘要结果为好多句号“。”

### ISSUE THREAD

**Issue by wjj001-dl** [PaddlePaddle/PaddleNLP#5642]
### 请提出你的问题

`summarizer = Taskflow("text_summarization", task_path='unimo-text-1.0-large')`
使用unimo-text-1.0-large时摘要结果为好多句号“。”，有大佬知道这是怎么回事吗？

**Comment by 1649759610** [comment]
感谢反馈，我们尽快排查修复。

**Comment by gongel** [comment]
`unimo-text-1.0-large` 是个基础模型，没有针对摘要做过微调，可以考虑用`unimo-text-1.0-summary`
