### ISSUE TITLE
[Question]: How can I utilize Ernie-Layout for Entity linking task?

### ISSUE THREAD

**Issue by vishal-nayak1** [PaddlePaddle/PaddleNLP#5649]
### 请提出你的问题

Hi,

Can Ernie-Layout be utilised for entity linking task?

Regards,
Vishal

**Comment by vishal-nayak1** [comment]
Hey, Any update on this?

**Comment by linjieccc** [comment]
Hi @vishal-nayak1 , sorry for not replying here.

I think UIE-X with Ernie-Layout as the backbone model might be suitable for this. You can refer to [the example here](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/document/README_en.md) to label the data and fine-tune the model in your scene.
