### ISSUE TITLE
[Question]: AssertionError: The task name:text_summarization is not in Taskflow list

### ISSUE THREAD

**Issue by ReinhartLee** [PaddlePaddle/PaddleNLP#5670]
### 请提出你的问题

我通过docker安装了paddlenlp，按照示例执行以下命令时，报错：
![image](https://user-images.githubusercontent.com/24267561/231977776-cd115c00-f4c8-4213-b58d-818a64014e3d.png)

之后我升级了paddlenlp
![image](https://user-images.githubusercontent.com/24267561/231977996-89c9659b-d1f9-455d-a5d5-2948263f715e.png)

还是报一样的错误，请问要怎么解决?

**Comment by JunnYu** [comment]
明显你用的是
![image](https://user-images.githubusercontent.com/50394665/232025370-70ebe4b5-6f62-4dc1-9965-4b602a0d6637.png)
当前目录的paddlenlp，而不是刚刚装的
![image](https://user-images.githubusercontent.com/50394665/232025457-705f7cf5-0fc6-4a4b-80e1-828e9626bb9c.png)

**Comment by ReinhartLee** [comment]
已解决，谢谢！
