### ISSUE TITLE
doccano转换为labelstudio格式

### ISSUE THREAD

**Issue by shenhu365** [PaddlePaddle/PaddleNLP#5678]
### Feature request

官方提供了Label Studio导出数据转换为doccano数据格式的代码：model_zoo/uie/labelstudio2doccano.py
可以再提供一下doccano导出数据转换为Label Studio格式的代码

### Motivation

文本分类一直推荐使用的标注平台是doccano，当我需要做NER或者其他任务时，有的要求是Label Studio标注平台，因此请求提供官方标准的转换工具

### Your contribution

无

**Comment by linjieccc** [comment]
@HuShenS Hi，之前有开发者写了一个版本，可以参考下 #4681
