### ISSUE TITLE
英文detokenizer

### ISSUE THREAD

**Issue by lxsyz** [PaddlePaddle/PaddleNLP#568]
使用mosestokenizer中的detokenizer效果不是很好，请问paddlenlp中有对英文做detokenizer的工具代码吗？

**Comment by wawltor** [comment]
您好，目前PaddleNLP还不支持detokenizer的功能，想问一下，能不能提供有一个具体的需求了，我们会根据需求来评估一下解决方案。

**Comment by ZeyuChen** [comment]
@lxsyz 是针对翻译场景的解码需求吗？
