### ISSUE TITLE
问答模型 能否像文心一言或ChatGPT那样，有前后呼应，而不是一问一答，如果不行有什么好的方案？

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5680]
### 请提出你的问题

问答模型现在做得还不错，但是有一点 问答模型 能否像文心一言或ChatGPT那样，有前后呼应，而不是一问一答，如果不行有什么好的方案？或是后期往这方面发展？感谢！！

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 问答模型现在做得还不错，但是有一点 问答模型 能否像文心一言或ChatGPT那样，有前后呼应，而不是一问一答，如果不行有什么好的方案？或是后期往这方面发展？感谢！！

这个功能会在后续的更新中体现，敬请期待。

**Comment by gg22mm** [comment]
感谢回复 ！！！， 非常期待 ...  完美。

我看了一些列子不过最近没见更新~~：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer

**Comment by gg22mm** [comment]
感谢回复 ！！！， 非常期待 ...  完美。

我看了一些列子不过最近没见更新~~，不知道对于理解上下文 多轮对话效果怎么样：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer
