### ISSUE TITLE
[Question]: lora训练的问题

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#5684]
### 请提出你的问题

1、使用lora微调参数之后，在训练的时候，看官方给出的应该是流程应该是pretrained的部分与lora部分（A和B）计算求和，但是只训练A和B部分。但是，我看paddle中实现，只是将LoRAMergedLinear 把 (query_key_value): Linear 进行了替换，然后进行训练。没有2部分求和？请问是什么原因呀
![v2-d86c9a771dec0643f5a75c0a785169f7_1440w](https://user-images.githubusercontent.com/18607037/232371943-27948bae-5cd4-43b1-b3cd-ae62de95f1ac.png)

**Comment by sijunhe** [comment]
LoRA不一定需要求和。训练的时候可以两个branch都走，但是只训练A或者B. 我们也有求和的逻辑，见.eval()和.train()

**Comment by liuzhipengchd** [comment]
> LoRA不一定需要求和。训练的时候可以两个branch都走，但是只训练A或者B. 我们也有求和的逻辑，见.eval()和.train()

大佬，在看构建lora的时候，有一个参数enable_lora_list，设置的参数是[[True, False, True]]，为什么这么设定？如果设置 [[True, True,False]] 这种，有什么区别，我看构建的之后参数量都一样

**Comment by sijunhe** [comment]
> [[True, False, True]]，为什么这么设定？如果设置 [[True, True,False]] 这种，有什么区别，我看构建的之后参数量都一样

`[[True, False, True]]`的意思是打开q和v的lora, 关闭k的lora. 原因是qkv_projection被融合在了一起，所有有一个单独的开关控制

**Comment by liuzhipengchd** [comment]
> > [[True, False, True]]，为什么这么设定？如果设置 [[True, True,False]] 这种，有什么区别，我看构建的之后参数量都一样
> 
> `[[True, False, True]]`的意思是打开q和v的lora, 关闭k的lora. 原因是qkv_projection被融合在了一起，所有有一个单独的开关控制

大佬，使用lora微调之后，是不是只需要把lora层替换qkv层就行了吧，然后参数进行model.set_state_dict就可以了吧？ 
我用自己的数据微调之后遇到一个问题，效果很差，不如全量训练的效果。但是，微调的loss 要比全量调的loss要小。（微调用的glm2b，全量的是glm-large） 这种情况是什么原因？可以怎么提升效果呢

**Comment by sijunhe** [comment]
> 大佬，使用lora微调之后，是不是只需要把lora层替换qkv层就行了吧，然后参数进行model.set_state_dict就可以了吧？ 我用自己的数据微调之后遇到一个问题，效果很差，不如全量训练的效果。但是，微调的loss 要比全量调的loss要小。（微调用的glm2b，全量的是glm-large） 这种情况是什么原因？可以怎么提升效果呢

lora使用请直接参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/glm/finetune_generation.py#L113 ，API已经完全封装好了，不需要你手动替换。效果差也许可能是使用的方式的问题，我们用lora结果都不错，先使用正确的api先吧

**Comment by liuzhipengchd** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/glm/finetune_generation.py#L113

这个我看到了，finetune_generation 是封装好了，但是predict_generation 里面不支持lora 加载

**Comment by sijunhe** [comment]
> 这个我看到了，finetune_generation 是封装好了，但是predict_generation 里面不支持lora 加载

后续会加入

**Comment by liuzhipengchd** [comment]
> > 这个我看到了，finetune_generation 是封装好了，但是predict_generation 里面不支持lora 加载
> 
> 后续会加入
大佬，我现在需要用lora的进行predict_generation。只需要按照finetune_generation里面方式构建loramodel，然后将训练好的lora_model_state.pdparams参数，把lora_a和lora_b进行替换，其他的参数都不用变动。然后就可以推理了？

**Comment by liuzhipengchd** [comment]
> > 这个我看到了，finetune_generation 是封装好了，但是predict_generation 里面不支持lora 加载
> 
> 后续会加入

在采用lora分布式训练的时候，训练结束存储lora参数的时候有bug，没有对参数进行merge。

**Comment by sijunhe** [comment]
> 
> 在采用lora分布式训练的时候，训练结束存储lora参数的时候有bug，没有对参数进行merge。

如果没有merge weights, 那么推理的时候需要再LoRAModel from_pretrained一次。
