### ISSUE TITLE
我是用uie-x做增值税专用发票实体信息提取。如果还有几十张其他类型的单据。能一起训练吗，还是一种单据一个taskflow

### ISSUE THREAD

**Issue by rexzhengzhihong** [PaddlePaddle/PaddleNLP#5690]
### 请提出你的问题

我是用uie-x做增值税专用发票实体信息提取。如果还有几十张其他类型的单据。能一起训练吗，还是一种单据一个taskflow

**Comment by linjieccc** [comment]
@rexzhengzhihong Hi，可以合并基于uie-x微调。

**Comment by rexzhengzhihong** [comment]
> Hi，可以合并基于uie-x微调。

好的。那每一种单据的schema不一样。一种单据需要启动一个Taskflow吧？

**Comment by linjieccc** [comment]
如果对推理速度要求不高的场景，也可以将schema合并，load一个Taskflow任务

**Comment by rexzhengzhihong** [comment]
> 如果对推理速度要求不高的场景，也可以将schema合并，load一个Taskflow任务
如果单据有100种。合并之后也太大了吧

**Comment by wn1652400018** [comment]
@rexzhengzhihong 你可以用uiex训练一个分类模型，然后使用对应的类型的schema。不过推理脚本可能要修改一下。

**Comment by Panda891027** [comment]
> @rexzhengzhihong 你可以用uiex训练一个分类模型，然后使用对应的类型的schema。不过推理脚本可能要修改一下。

这个分类模型怎么训练呀，我好像没看到示例

**Comment by dingidng** [comment]
> 

楼主，相关问题有好的解决方案吗

**Comment by tingaicompass** [comment]
> > @rexzhengzhihong 你可以用uiex训练一个分类模型，然后使用对应的类型的schema。不过推理脚本可能要修改一下。
> 
> 这个分类模型怎么训练呀，我好像没看到示例

楼主，相关问题最后有较好的解决方案嘛
