### ISSUE TITLE
document_intelligence的推理模型转ONNX报错

### ISSUE THREAD

**Issue by 471417367** [PaddlePaddle/PaddleNLP#5691]
paddlenlp                          2.5.2
paddleocr                          2.6.0.1
paddlepaddle                       2.4.2
onnx                               1.13.1
paddle2onnx                        1.0.6

文件结构：docprompt/inference.pdmodel    docprompt/inference.pdiparams
使用命令：
paddle2onnx --model_dir docprompt --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file docprompt.onnx --enable_onnx_checker True
报错：
[Paddle2ONNX] Oops, there are some operators not supported yet, including one_hot,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
请问这个是模型中有onnx不支持的算子吗？如何解决呢？

**Comment by linjieccc** [comment]
@471417367 Hi，docprompt目前还没有验证过paddle转onnx的流程，从报错看应该是one_hot算子不支持转换，可以在paddle2onnx的repo提个issue反馈下这个问题：https://github.com/PaddlePaddle/Paddle2ONNX/issues

**Comment by 471417367** [comment]
好的，谢谢

Linjie Chen ***@***.***> 于2023年4月18日周二 14:10写道：
