### ISSUE TITLE
[Question]: ppdiffusers使用ddim调度器出图质量极低

### ISSUE THREAD

**Issue by zhangvia** [PaddlePaddle/PaddleNLP#5692]
### 请提出你的问题

按照md中的教程导出模型后，我测试了controlnet_infer和img2img两个文件，使用pndm和euler采样器效果正常，但使用ddim采样器效果极差，甚至可以说出图是完全随机的。

**Comment by JunnYu** [comment]
你好能提供一下样例代码吗？

**Comment by zhangvia** [comment]
> 你好能提供一下样例代码吗？

我就是在get_scheduler函数中加了一句scheduler = DDIMScheduler(),难道是默认的参数不行吗。另外我想问一下有没有stablediffusion在各类显卡上的推理时间benchmark？我这边在a100 40g上controlnet在1.22s，img2img在750ms左右。但我的同事在4090上测试，img2img达到了2.3s左右，我正在重新测试，这是正常的吗

**Comment by JunnYu** [comment]
你好，默认参数是不可以的，需要下面的
```python
DDIMScheduler(
            beta_start=0.00085,
            beta_end=0.012,
            beta_schedule="scaled_linear",
            clip_sample=False,
            set_alpha_to_one=False,
            steps_offset=1,
        )
```
目前没有stablediffusion在各类显卡上的推理时间benchmark，只有A100的部分数据，text2img 0.77s左右，controlnet1.11s左右，img2img不清楚

**Comment by zhangvia** [comment]
> 你好，默认参数是不可以的，需要下面的
> 
> ```python
> DDIMScheduler(
>             beta_start=0.00085,
>             beta_end=0.012,
>             beta_schedule="scaled_linear",
>             clip_sample=False,
>             set_alpha_to_one=False,
>             steps_offset=1,
>         )
> ```
> 
> 目前没有stablediffusion在各类显卡上的推理时间benchmark，只有A100的部分数据，text2img 0.77s左右，controlnet1.11s左右，img2img不清楚

刚试了一下，效果正常，想问下类似的各种调度器参数该如何设置有文档吗

**Comment by JunnYu** [comment]
基本上都可以通过
```python
original_sc = DDIMScheduler(
            beta_start=0.00085,
            beta_end=0.012,
            beta_schedule="scaled_linear",
            clip_sample=False,
            set_alpha_to_one=False,
            steps_offset=1,
        )

new_scheduler = xxxScheduler.from_config(original_sc.config)
```

**Comment by zhangvia** [comment]
> 基本上都可以通过
> 
> ```python
> original_sc = DDIMScheduler(
>             beta_start=0.00085,
>             beta_end=0.012,
>             beta_schedule="scaled_linear",
>             clip_sample=False,
>             set_alpha_to_one=False,
>             steps_offset=1,
>         )
> 
> new_scheduler = xxxScheduler.from_config(original_sc.config)
> ```

了解，那如果要一次性生成多张图该怎么办呢，应该如何修改dynamic_shape？推理时修改max_shape就可以了吗，opt_shape需要修改吗

**Comment by joey12300** [comment]
> > 基本上都可以通过
> > ```python
> > original_sc = DDIMScheduler(
> >             beta_start=0.00085,
> >             beta_end=0.012,
> >             beta_schedule="scaled_linear",
> >             clip_sample=False,
> >             set_alpha_to_one=False,
> >             steps_offset=1,
> >         )
> > 
> > new_scheduler = xxxScheduler.from_config(original_sc.config)
> > ```
> 
> 了解，那如果要一次性生成多张图该怎么办呢，应该如何修改dynamic_shape？推理时修改max_shape就可以了吗，opt_shape需要修改吗

你好，推理时修改max_shape就可以了，注意修改所有变量的第一维度（batch维度）。如图所示：
<img width="541" alt="image" src="https://user-images.githubusercontent.com/10826371/233057744-8b456b28-03f3-47a7-ab09-ebb71310ba3e.png">
代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/deploy/img_to_img_infer.py#L247

注意：shape范围增大，加载trt的时间就会大大增加
