### ISSUE TITLE
[Question]: 请问AUTOMATIC1111 WebUI Stable Diffusion 的pipeline是否会支持fast deploy部署？

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleNLP#5693]
### 请提出你的问题

普通的pipeline无法在结果上与webui的版本对齐，对于WebUIStableDiffusionPipeline版本 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/community#automatic1111-webui-stable-diffusion 的请问是否有fastdeploy的部署版本呢？谢谢。

**Comment by JunnYu** [comment]
你好，当前这个WebUIStableDiffusionPipeline是没有部署版本的，你可以自己仿照这里的实现 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_stable_diffusion.py ，将webui中最费时的unet使用fd推理，其他都使用动态图推理即可。

**Comment by sanbuphy** [comment]
> 你好，当前这个WebUIStableDiffusionPipeline是没有部署版本的，你可以自己仿照这里的实现 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_stable_diffusion.py ，将webui中最费时的unet使用fd推理，其他都使用动态图推理即可。

感谢建议！ 让我学习一下。

**Comment by sanbuphy** [comment]
> 你好，当前这个WebUIStableDiffusionPipeline是没有部署版本的，你可以自己仿照这里的实现 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_stable_diffusion.py ，将webui中最费时的unet使用fd推理，其他都使用动态图推理即可。

不过我还发现个问题呢，这个其实结果也是和其他的diffuser对齐的，也就是说它并不是和webui的结果对其（只是管道参数对齐）请问这个原因是什么呢？

**Comment by JunnYu** [comment]
这个 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_stable_diffusion.py 就是对齐diffusers中的onnx的pipeline的，你需要webui的话，就需要自己仿照这里添加对应的新的pipeline
