### ISSUE TITLE
[Bug]: paddlenlp兼容性问题

### ISSUE THREAD

**Issue by ZOUG** [PaddlePaddle/PaddleNLP#5697]
### 软件环境

```Markdown
- paddlenlp: 2.5.2
```

### 重复问题

- [x] I have searched the existing issues

### 错误描述

paddlenlp2.5.2与visualdl 2.5.0版本不兼容。paddlenlp 2.5.2版本的[requirements.txt](https://github.com/PaddlePaddle/PaddleNLP/blob/v2.5.2/requirements.txt)要求visualdl和Flask-Babel < 3.0.0。而visualdl 2.5.0以上版本的[requirements.txt](https://github.com/PaddlePaddle/VisualDL/blob/v2.5.0/requirements.txt) 要求Flask-Babel >= 3.0.0。因此二者存在兼容性冲突。

直接解决方法是修改Flask-Babel限制或设置visualdl < 2.5.0。更深层次的问题是飞桨发布各个工具包时缺乏兼容性检验。希望能将paddlenlp等常用飞桨工具包都编译放到conda上进行管理，这样在发布工具包时就可以及时发现类似问题。

**Comment by sijunhe** [comment]
你好，之前paddlenlp限制Flask-Babel的原因是和readthedocs之间的依赖有问题，导致docs无法编译。后续我们会重新看一下

**Comment by sijunhe** [comment]
This is resolved by #5791
