### ISSUE TITLE
UIE模型中的finetune.py如何实现早停法[Question]: 

### ISSUE THREAD

**Issue by yangzhenyu6** [PaddlePaddle/PaddleNLP#5700]
### 请提出你的问题

想在微调时使用100轮次，如何实现早停法

**Comment by linjieccc** [comment]
@yangzhenyu6 Hi，uie finetune脚本中当前还没有加入早停策略，可以参考这里的写法加下相关逻辑https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/text_classification/multi_label/train.py#L155 欢迎给我们贡献PR
