### ISSUE TITLE
[Question]: 请问GPT-3模型是否已经支持

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/PaddleNLP#5704]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/gpt-3
您好，请问此模型是否已支持？如已支持，能否给出详细依赖，如paddlepaddle版本，谢谢！

**Comment by engineer1109** [comment]
这个是仿制品吧，GPT3没开源，看起来和GPT2差不多

**Comment by jinyouzhi** [comment]
> 这个是仿制品吧，GPT3没开源，看起来和GPT2差不多

这个是paddlefleetx迁移过来的，应该是飞桨复现的GPT-3模型吧，按文档我本地跑不起来，求助一下官方RD

**Comment by engineer1109** [comment]
@jinyouzhi 没几个能跑得起来，他这个有自定义算子，太麻烦。
看起来和另一个GPT没啥区别

**Comment by jinyouzhi** [comment]
@sijunhe 方便确认一下吗？

**Comment by jinyouzhi** [comment]
@sijunhe 方便确认一下吗？

**Comment by sijunhe** [comment]
> @sijunhe 方便确认一下吗？

您好！
楼上说的没错，GPT-3的模型结构和参数确实都没有开源，所以我们这边的GPT其实是GPT-2，如果需要一个能跑起来的版本，可以先使用https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/gpt-3

从paddlefleetx迁移过来的gpt确实是我们这边的最新工作，比我们这边已有的gpt实现多了很多工程加速。但是这个版本目前因为底层算子的原因依赖nightly的paddle框架，也仍然在积极开发中，使用体验不会太好。
我们这边计划在5月中发下一个大版本，会全面支持各种开源大模型的分布式训练

**Comment by gg22mm** [comment]
看了市面上的那么多，还是百度的靠谱..   等得起 ~~  期待....   学习边角料等待~!~

**Comment by jinyouzhi** [comment]
@sijunhe @engineer1109 感谢解答
