### ISSUE TITLE
document_intelligence中word_boxes类型数据是什么格式的

### ISSUE THREAD

**Issue by qiu-pinggaizi** [PaddlePaddle/PaddleNLP#5711]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/52409244/232951786-4cbaea22-3414-4e8e-8b84-0a40121c3bc5.png)
document_intelligence任务中，ocr内容支持通过”word_boxes“字段传入，”word_boxes“内容具体是什么格式，有示例吗？ @tonyanhq @felixhao28 @kztao @

**Comment by qiu-pinggaizi** [comment]
![image](https://user-images.githubusercontent.com/52409244/232952797-9b658fc2-2475-4e16-8325-cdc017a5599e.png)
假如是多个字段，结构是什么呢？

**Comment by zhangqiqi1228** [comment]
多个字段也是一样的，自己重新定义一个batch_input就好。
![image](https://github.com/user-attachments/assets/a5ebba2b-153b-4c68-a329-2cc5cf6af8c5)
