### ISSUE TITLE
[Question]: feature_extraction 文本embedding该怎么选择模型

### ISSUE THREAD

**Issue by yuanjie-ai** [PaddlePaddle/PaddleNLP#5712]
### 请提出你的问题

![image](https://user-images.githubusercontent.com/20265321/232959131-a7d6f1ce-0171-404b-9bc0-a8eb784748b2.png)
- 哪些适合无监督？
- 哪些适合句向量
- 哪些适合篇章向量
- 长文本咋处理

**Comment by yuanjie-ai** [comment]
哪些适合无监督？
哪些适合句向量
哪些适合篇章向量
长文本咋处理

**Comment by w5688414** [comment]
> 哪些适合无监督？ 哪些适合句向量 哪些适合篇章向量 长文本咋处理

这个没有细分，需要自己实验，长文本需要进行分段
