### ISSUE TITLE
如何进行多gpu推理

### ISSUE THREAD

**Issue by zhiyongLiu1114** [PaddlePaddle/PaddleNLP#5719]
### Feature request

模型加载时，将模型拆分到多个gpu上

### Motivation

gpu显存不够

### Your contribution

tranformers的做法如下：

```python
max_memory_mapping = {0: "1GB", 1: "2GB"}
model_name = "bigscience/bloom-3b"
model_8bit = AutoModelForCausalLM.from_pretrained(
    model_name, device_map="auto", load_in_8bit=True, max_memory=max_memory_mapping
)
```

**Comment by wj-Mcat** [comment]
根据你的描述，基本上可以确定：

1. 模型大概率是基于流水线并行的方式执行，这部分的功能目前正在支持，请关注PaddleNLP 的最新发版信息。
2. 动态控制每张卡的现存占用大小：这个也是后续重点关注的特性，预计下个月可以完成。

接下来 PaddlenLP 将重点关注大模型训练、部署的能力，而你所描述的也是最基础的一些功能，肯定是需要实现好的，所以，敬请期待吧 ~~~ 也非常欢迎关注 PaddleNLP 的发版信息。🔥 🔥 🔥

**Comment by zhiyongLiu1114** [comment]
> 根据你的描述，基本上可以确定：
> 
> 1. 模型大概率是基于流水线并行的方式执行，这部分的功能目前正在支持，请关注PaddleNLP 的最新发版信息。
> 2. 动态控制每张卡的现存占用大小：这个也是后续重点关注的特性，预计下个月可以完成。
> 
> 接下来 PaddlenLP 将重点关注大模型训练、部署的能力，而你所描述的也是最基础的一些功能，肯定是需要实现好的，所以，敬请期待吧 ~~~ 也非常欢迎关注 PaddleNLP 的发版信息。🔥 🔥 🔥

非常感谢，拭目以待
