### ISSUE TITLE
[Question]: llama-7b finetune时 [ WARNING] - Some weights of LlamaForCausalLM were not initialized from the model checkpoint 

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5720]
### 请提出你的问题

./examples/llama/ finetune_generation.py 加载模型时，有warning。
"""
[ WARNING] - Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /root/nlp/xieyu/pretrained_models/llama_7b and are newly initialized: ['llama.layers.0.self_attn.rotary_emb.inv_freq', 'llama.layers.27.self_attn.rotary_emb.inv_freq', 'llama.layers.9.self_attn.rotary_emb.inv_freq'，....
"""

请问有没有问题？

**Comment by wawltor** [comment]
这个没有问题，inv_freq 这个并不是可学习参数，所以不需要加载
