### ISSUE TITLE
[Question]: llama  finetune_generation.py 报错

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5721]
### 请提出你的问题

报错信息如下：

Error: /paddle/paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu:56 Assertion `(real_label < D * nranks) && (real_label >= 0)` failed. The index is out of bounds, please check whether the value of label and input meet the class number. It should be less than [32000], but received [0]

paddlepaddle、paddlenlp 都是develop分支最新版

**Comment by wawltor** [comment]
这个问题的解决需要最新的paddle的版本，可能你下载的paddle版本并不是最新的版本

**Comment by xieyu0214** [comment]
> 这个问题的解决需要最新的paddle的版本，可能你下载的paddle版本并不是最新的版本

`python -m pip install paddlepaddle-gpu==0.0.0.post117 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html` 
用的这个重新装的

单卡是没问题的，只是多卡时就会报错：

Error: /paddle/paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu:56 Assertion `(real_label < D * nranks) && (real_label >= 0)` failed. The index is out of bounds, please check whether the value of label and input meet the class number. It should be less than [32000], but received [0]
Error: /paddle/paddle/fluid/operators/collective/c_softmax_with_cross_entropy_op.cu:56 Assertion `(real_label < D * nranks) && (real_label >= 0)` failed. The index is out of bounds, please check whether the value of label and input meet the class number. It should be less than [32000], but received [0]

OSError: (External) OSError: (External) CUDA error(719), unspecified launch failure.

参数设置：
"""
python -m paddle.distributed.launch \
    --gpus "2,3" finetune_generation.py \
    --model_name_or_path ../pretrained_models/llama_7b \
    --cps_dir ../corpus/poi_mining \
    --src_length 1024 \
    --tgt_length 100 \
    --task_name mining \
    --do_train \
    --do_eval \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --tensor_parallel_degree 2 \
    --overwrite_output_dir \
    --output_dir ./checkpoints/mining-llama-7b-3e-5 \
    --logging_steps 10 \
    --fp16 \
    --fp16_opt_level O2 \
    --gradient_accumulation_steps 4 \
    --recompute \
    --learning_rate 3e-5 \
    --lr_scheduler_type linear \
    --max_grad_norm 1.0 \
    --warmup_steps 20 \
    --lora true
"""

是不是bug呢？

**Comment by wawltor** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/16698950/233261973-34735309-bfe6-4bea-80c7-6d5b09fa7c4a.png">
在多卡走的是parallel_crosss_entroy分支，这个问题在最新develop版本修复了，有可能安装的版本不是最新的版本
