### ISSUE TITLE
[Question]: 使用【FinRE】公开金融关系数据集进行关系抽取，训练出的模型会对每一句预测出全部（44）条关系

### ISSUE THREAD

**Issue by new-cainiao** [PaddlePaddle/PaddleNLP#5729]
### 请提出你的问题

使用【FinRE】公开金融关系数据集进行关系抽取测试。训练评估看着很正常（我打印了评估的每条结果），但是在具体使用模型预测的时候会把schema里的所有关系全部预测出来，并且probability都很高。
- 整理前的原数据格式为：
![1](https://user-images.githubusercontent.com/39564677/233276673-996cae0a-8dab-417c-8633-e2a80beecdd0.jpg)
- 整理后的数据格式为：
![image](https://user-images.githubusercontent.com/39564677/233276771-582942b9-7138-4e70-ae36-43f4dc96aec4.png)
- 评估的结果：
![image](https://user-images.githubusercontent.com/39564677/233277308-8222896f-6603-4ee8-80ca-554c7abd449c.png)
- shema：
{"机构": ["拥有","被拥有","unknown","被分析","合作","拟收购","被增持","合资","竞争","被持股","入股","被收购","重组","被成立","减持","被减持","成立","商讨","被拟收购","注资","自己","持股","被发行","被注资","签约","收购","订单","分析","被买资","纠纷","被帮助","交易","合并","买资","增持","被转让","帮助","欠款","被欠款","被入股","被借壳","转让","发行","借壳"]}
- 预测结果
![image](https://user-images.githubusercontent.com/39564677/233277729-526334fc-d37b-463f-8eb1-b077aebea89e.png)

是我对schema的定义出现问题了吗，还是对关系抽取的训练数据整理方面。
求解答。。我不是太理解关系抽取的标注与数据集的格式

**Comment by new-cainiao** [comment]
另外我还有一个疑问，关于关系标注中的实体名称问题。
对于上述数据我是给两个实体同一个标签，这样会有影响吗？还是关系标注对实体的标签不敏感

**Comment by new-cainiao** [comment]
FinRE数据链接：https://github.com/thunlp/Chinese_NRE

**Comment by new-cainiao** [comment]
今日更新：
"schema":{
    "head":["自己","发行","unknown","增持","被分析","拥有","竞争","被帮助","被转让","被拥有","订单","合作","分析","被增持","商讨","持股","被发行","注资","被收购","被持股","收购","减持","签约","拟收购","帮助","被注资","交易","成立","合并","买资","转让","重组","被成立","纠纷","被入股","合资","被减持","入股","借壳","被欠款","被拟收购","被买资","欠款","被借壳"],
    "tail":["自己","纠纷","unknown","分析","被转让","收购","合作","增持","注资","竞争","被分析","被拟收购","被拥有","被持股","签约","交易","被减持","拥有","被收购","持股","重组","欠款","减持","帮助","成立","拟收购","入股","被增持","被注资","发行","合资","订单","借壳","被成立","被借壳","商讨","被发行","转让","被入股","被买资","被帮助","合并","买资","被欠款"]
}
出现同样的问题，而且会在head里提出tail的内容
![image](https://user-images.githubusercontent.com/39564677/233515254-3d15a0f2-0aac-4246-a52d-803eccab8070.png)

**Comment by linjieccc** [comment]
@new-cainiao 你好，请问在微调的数据集中有加入负例进行训练么，如果数据集只有正例容易造成错误召回，就是上例中全部预测的情况。关于UIE 关系抽取负例的构造方式可以参考这篇文章：https://zhuanlan.zhihu.com/p/564033319

**Comment by new-cainiao** [comment]
@linjieccc 好的好的，我看到了，之前没考虑负例的情况，刚做完负例的数据集，尝试一下。
另外我想问一下对于关系抽取中的实体标签敏感吗？例如：
冠生园于<N>年创立的冠生园互联网金融园区已布局互联网金融、智慧社区等板块。
实体为：冠生园	冠生园互联网金融园区
我构造单独的实体标签（eg：机构）与两个实体标签（eg：机构1、机构2）对于训练会有什么不同的影响吗？
关系为：机构成立机构｜机构1成立机构2
