### ISSUE TITLE
[Question]: 在使用uie 做分类任务的finetune时，程序报错，无法进行fintune

### ISSUE THREAD

**Issue by lzh1998-jansen** [PaddlePaddle/PaddleNLP#5731]
### 请提出你的问题

paddle-bfloat        0.1.7
paddle2onnx          1.0.5
paddlefsl            1.1.0
paddlenlp            2.5.1.post0
paddlepaddle-gpu     2.4.2
执行下面代码的是报错
![image](https://user-images.githubusercontent.com/61367424/233296114-8e8681fe-0466-4df7-8541-7977f6c504d7.png)
报错截图为
![image](https://user-images.githubusercontent.com/61367424/233296242-0d542dae-c2c0-4669-9ff0-1a4961ca5f54.png)
![image](https://user-images.githubusercontent.com/61367424/233296382-d55ddbb1-5b49-490c-ac40-4339a896a327.png)

**Comment by linjieccc** [comment]
@lzh1998-jansen 你好，可以删除`/root/.paddlenlp/models/uie-base/model_state.pdparams`重新执行微调试下
