### ISSUE TITLE
[Question]: import paddlenlp报错

### ISSUE THREAD

**Issue by MutianWang** [PaddlePaddle/PaddleNLP#5735]
### 请提出你的问题

paddlepaddle=2.4.2
paddlenlp=2.5.2
scikit-learn=1.2.2
python=3.8.16

import paddlenlp，会报错提示scikit-learn安装有问题；但如果直接import scikit-learn就没报错

直接import paddlenlp，报错在sklearn
![image](https://user-images.githubusercontent.com/43964394/233323469-4df8448a-f7fa-4ec5-9460-b1b47f389ddd.png)

直接import sklearn，无报错；再import paddlenlp，报错
![image](https://user-images.githubusercontent.com/43964394/233323800-903bc994-ee57-4497-931a-846a1c6f29d5.png)

**Comment by w5688414** [comment]
试试conda命令：

```
conda install numpy  scikit-learn 
```
