### ISSUE TITLE
[Question]: 在使用的时候报错，导致系统直接崩溃了，帮忙看下

### ISSUE THREAD

**Issue by yspyhp** [PaddlePaddle/PaddleNLP#5739]
### 请提出你的问题

现象如下：

1. 首先我开起了一个任务A，目的是把文字转成向量索引
2. 任务A在不断的执行过程中都是正常的，但是如果调用了simbert_similarity = Taskflow("text_similarity", model='simbert-base-chinese') 计算相似度的话，就会报下边这个错
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/23613386/233358802-3b490887-3448-48a6-b50a-9fec8ea74305.png">
3. 如果simbert_similarity = Taskflow("text_similarity", model='simbert-base-chinese')调用多了，系统就会崩溃，报下边这个错
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/23613386/233359068-8277c996-2218-4036-a09b-c7a3b465e740.png">
4. 一开始我以为是模型冲突，所以我又测试了，我们同一个服务当中另一个部署的uie模型，在任务A执行的过程中大量调用，不报错，系统一切正常

求助，是在找不出原因了

**Comment by yspyhp** [comment]
为什么会报JRE的错，很是奇怪

**Comment by BrightXiaoHan** [comment]
> 为什么会报JRE的错，很是奇怪

感觉JRE的错误应该是你 Pycharm的问题。

**Comment by yspyhp** [comment]
> > 为什么会报JRE的错，很奇怪
> 
> 感觉 JRE 的错误应该是你 Pycharm 的问题。

不是的，在其他物理机上有同样的问题

**Comment by w5688414** [comment]
> > > 为什么会报JRE的错，很奇怪
> > 
> > 
> > 感觉 JRE 的错误应该是你 Pycharm 的问题。


请问怎么复现呢？有最小可复现代码没？
