### ISSUE TITLE
请问如何训练UIE-X的图片抽取能力，如果标注的如何准备数据，用什么工具，输出什么格式内容给到uie-x模型 

### ISSUE THREAD

**Issue by zchengzhong** [PaddlePaddle/PaddleNLP#5745]
### 请提出你的问题

请问如何训练UIE-X的图片抽取能力，如果标注的如何准备数据，用什么工具，输出什么格式内容给到uie-x模型

**Comment by linjieccc** [comment]
@zchengzhong 你好，可以参考下这里发票抽取的例子 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/document
