### ISSUE TITLE
[Question]: 文档智能 可以使用paddleserver部署吗 

### ISSUE THREAD

**Issue by qiu-pinggaizi** [PaddlePaddle/PaddleNLP#5750]
### 请提出你的问题

文档智能或信息抽取部署方法咨询，模型用PaddleServing部署，自己写前后处理逻辑，然后通过grpc调用推理，这种方式可以吗？

**Comment by qiu-pinggaizi** [comment]
@solrex @tonyanhq @ZeyuChen @kztao

**Comment by LemonNoel** [comment]
服务端部署QPS要求不高可以用simple serving，如果要求高可以用triton部署。PaddleServing之后将不持续维护了

**Comment by qiu-pinggaizi** [comment]
你的意思是使用triton部署，使用tensorRT进行模型推理还是paddle推理？假如是转trt，是否有坑呀？如何把前后处理代码给单独拿出来呀，有拿出代码的示例吗？ @LemonNoel

**Comment by LemonNoel** [comment]
推荐使用工具 FastDeploy，当前在零样本文本分类下有示例，链接如下。文档智能还没来得及适配，可以参照着实现一下，主要修改的是infer.py文件中的模型初始化和前后处理代码，详细的参数配置可以看下README。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/zero_shot_text_classification/deploy/python

**Comment by qiu-pinggaizi** [comment]
图1是document_intelligence默认模型的输入输出节点大小，但使用taskflow进行推理的时候，数据的大小和输入节点的大小不一致，图2是输入数据中image的维度，但还能推理成功，这是为什么呢？当我把模型部署到triton里面，自己写推理脚步通过grpc调用triton，会报错数据维度不一致的问题；这是为什么呢？难道是使用taskflow里面的paddle inference，输入数据维度大小不需要和模型输入节点大小一致？
![image](https://user-images.githubusercontent.com/52409244/233837880-23669bfe-8916-489a-850f-e27bdeca1ee6.png)
![image](https://user-images.githubusercontent.com/52409244/233838247-be7d6087-a0ce-4811-8f0e-831c83c1d2eb.png)
![image](https://user-images.githubusercontent.com/52409244/233838347-ad469451-78a4-4ad4-b827-3301f1bf4a90.png)
@LemonNoel

**Comment by qiu-pinggaizi** [comment]
`成功使用triton完成了部署推理，有个疑惑点想咨询一下，模型的一些输入节点维度是固定的（图1），但因为推理前处理得到的数据维度和节点需要的维度对不上，我将triton中config.pbtxt的输入维度设置成了动态，成功完成了推理。这表明虽然模型结构中输入节点的数据是固定的，但模型本身是支持动态输入的？`
![image](https://user-images.githubusercontent.com/52409244/233951494-d887a35d-e732-4929-a71a-f3f320859c5a.png)
config.pbtxt信息
`input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [3, -1, -1],
  },
  {
    name: "unique_id"
    data_type: TYPE_INT64
    dims: [-1],
  },
  {
    name: "super_rel_pos"
    data_type: TYPE_INT64
    dims: [-1, -1],
  },
  {
    name: "input_mask_mat"
    data_type: TYPE_FP32
    dims: [-1, -1],
  },
  {
    name: "task_ids"
    data_type: TYPE_INT64
    dims: [-1, 1],
  },
  {
    name: "segment_ids"
    data_type: TYPE_INT64
    dims: [-1, 1],
  },
  {
    name: "2d_pos_ids"
    data_type: TYPE_INT64
    dims: [-1, 4],
  },
  {
    name: "pos_ids"
    data_type: TYPE_INT64
    dims: [-1, 1],
  },
  {
    name: "sent_ids"
    data_type: TYPE_INT64
    dims: [-1, 1],
  },
  {
    name: "src_ids"
    data_type: TYPE_INT64
    dims: [-1, 1],
  }
]`

**Comment by Panda891027** [comment]
这个是怎么部署的呀
