### ISSUE TITLE
[Bug]: llama - lora 方式训练后，模型加载问题

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5751]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu: 0.0.0.post117
- paddlenlp: 2.5.2.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
llama-lora 在训练时，设置了 tensor_parallel_degree=2， 用两张卡训练的。lora_config中没有设置merge_weights。以至于lora模型的保存是分开的。
保存的lora_config=
{
  "enable_lora_list": null,
  "lora_alpha": 8,
  "lora_dropout": 0.0,
  "merge_weights": false,
  "r": 4,
  "target_modules": [
    ".*q_proj.*",
    ".*v_proj.*"
  ],
  "tensor_parallel_degree": 2,
  "trainable_bias": null,
  "trainable_modules": null
}


加载lora模型（self.model = LoRAModel.from_pretrained(self.model, args.lora_model_dir)）预测时，发现是否设置 `--tensor_parallel_degree 2`  都是没用的，都报错 ` File ".../PaddleNLP/paddlenlp/layers/lora.py", line 620, in from_pretrained
    raise ValueError(
ValueError: 2 is not equal to 1. Please save LoRA parameters as onepiece model.`

所以应该怎么使用lora的训练方法，对现在的模型该怎么使用？
```

### 稳定复现步骤 & 代码

==

**Comment by lugimzzz** [comment]
你用分片训练，trainer在保存checkpoint的时候为了节省卡之间通信时间，所有没有将两卡的权重进行合并，每个卡权重存了一份参数。

现在建议是用两卡方式加载进行推理或者你可以先用两卡加载一次lora模型，然后运行
lora_model.save_pretrained('checkpoint', merge_tensor_parallel=True)
得到可以用于单卡推理的合并权重

**Comment by xieyu0214** [comment]
> 你用分片训练，trainer在保存checkpoint的时候为了节省卡之间通信时间，所有没有将两卡的权重进行合并，每个卡权重存了一份参数。
> 
> 现在建议是用两卡方式加载进行推理或者你可以先用两卡加载一次lora模型，然后运行 lora_model.save_pretrained('checkpoint', merge_tensor_parallel=True) 得到可以用于单卡推理的合并权重


训练的时候 `trainer.save_model(merge_tensor_parallel=training_args.tensor_parallel_degree > 1)`  理论上保存合并后的模型对吧？ 用lora微调时，只保存lora部分，那是不是应该就是保存合并后的模型。 但现在看起是要lora_config中再设置一次 才合并？

**Comment by lugimzzz** [comment]
trainer.save_model(merge_tensor_parallel=training_args.tensor_parallel_degree > 1) 这块如果使用lora只保存lora相关以及可训练参数的权重，权重已合并，保存的lora_config中tensor_parallel_degree会为1。

**Comment by xieyu0214** [comment]
> trainer.save_model(merge_tensor_parallel=training_args.tensor_parallel_degree > 1) 这块如果使用lora只保存lora相关以及可训练参数的权重，权重已合并，保存的lora_config中tensor_parallel_degree会为1。

根据我测试的结果，trainer.save_model(merge_tensor_parallel=training_args.tensor_parallel_degree > 1) 这种方式 并不会合并lora模型。现在同时设置了 lora_config中merge_weights=True， 在训练试试。

**Comment by lugimzzz** [comment]
你确定一下否使用最新代码，因为最近paddlenlp开发迭代节奏比较快。我本地用最新代码运行了，没有发现lora_model.save_pretrained('checkpoint', merge_tensor_parallel=True)保存得到的lora_config.tensor_parallel_degree不为1

```
tensor_parallel_degree = paddle.distributed.get_world_size()
tensor_parallel_rank = 0
if tensor_parallel_degree > 1:
    strategy = fleet.DistributedStrategy()
    strategy.hybrid_configs = {
        "dp_degree": 1,
        "mp_degree": tensor_parallel_degree,
        "pp_degree": 1,
        "sharding_degree": 1,
    }
    fleet.init(is_collective=True, strategy=strategy)
    hcg = fleet.get_hybrid_communicate_group()
    tensor_parallel_rank = hcg.get_model_parallel_rank()

config = LlamaConfig.from_pretrained(args.model_name_or_path)
dtype = "float16" if config.dtype is None else config.dtype
paddle.set_default_dtype(dtype)
model = AutoModelForCausalLM.from_pretrained(
    args.model_name_or_path,
    tensor_parallel_degree=tensor_parallel_degree,
    tensor_parallel_rank=tensor_parallel_rank,
    load_state_as_np=True,
    dtype=dtype,
)
lora_model = LoRAModel.from_pretrained(self.model, self.args.lora_path)
lora_model.save_pretrained('checkpoint', merge_tensor_parallel=True)
```

**Comment by xieyu0214** [comment]
> 

我是问 设置了 trainer.save_model(merge_tensor_parallel=True) 为什么模型没有合并。 不过，我明白你的意思了。感谢~

**Comment by xieyu0214** [comment]
# Load the pretrained language model.
    model = AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        load_state_as_np=True,
        low_cpu_mem_usage=True,
        dtype=dtype,  # todo enable set dtype to avoid additional mem usage
        tensor_parallel_degree=training_args.tensor_parallel_degree,
        tensor_parallel_rank=training_args.tensor_parallel_rank,
        fp16_opt_level=training_args.fp16_opt_level,
        use_flash_attention=model_args.use_flash_attention,
        use_recompute=training_args.recompute,
    )
    if model_args.lora:
        # TODO: hardcode parameters for now. Change after MergedLoRA is introduced
        lora_config = LoRAConfig(
            target_modules=[".*q_proj.*", ".*v_proj.*"],
            r=8,
            lora_alpha=32,
            merge_weights=True,
            tensor_parallel_degree=training_args.tensor_parallel_degree,
        )
        model = LoRAModel(model, lora_config)
        model.mark_only_lora_as_trainable()
        model.print_trainable_parameters()

**Comment by xieyu0214** [comment]
# Load the pretrained language model.
    model = AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        load_state_as_np=True,
        low_cpu_mem_usage=True,
        dtype=dtype,  # todo enable set dtype to avoid additional mem usage
        tensor_parallel_degree=training_args.tensor_parallel_degree,
        tensor_parallel_rank=training_args.tensor_parallel_rank,
        fp16_opt_level=training_args.fp16_opt_level,
        use_flash_attention=model_args.use_flash_attention,
        use_recompute=training_args.recompute,
    )
    if model_args.lora:
        # TODO: hardcode parameters for now. Change after MergedLoRA is introduced
        lora_config = LoRAConfig(
            target_modules=[".*q_proj.*", ".*v_proj.*"],
            r=8,
            lora_alpha=32,
            **merge_weights=True,**
            tensor_parallel_degree=training_args.tensor_parallel_degree,
        )
        model = LoRAModel(model, lora_config)
        model.mark_only_lora_as_trainable()
        model.print_trainable_parameters()

...

    trainer = LlamaTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=dev_ds,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics_func,
        do_generation=True,
        data_collator=collate_fn,
    )

    if training_args.do_train:
        train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
        trainer.save_model(**merge_tensor_parallel=training_args.tensor_parallel_degree > 1**)
        trainer.log_metrics("train", train_result.metrics)
        trainer.save_metrics("train", train_result.metrics)
        trainer.save_state()
        
       
更新了paddlenlp最新版本，用上面的代码训练的模型 ，保存的依然是未被合并
merge_weights=True
merge_tensor_parallel=True

**Comment by lugimzzz** [comment]
checkpoint的话是不合并的，只有训练完成才会合并

**Comment by xieyu0214** [comment]
> checkpoint的话是不合并的，只有训练完成才会合并

没说checkpoint合并啊

lora_config.json                optimizer.tp00.pdopt  rng_state_1.pth     sentencepiece.bpe.model  trainer_state.json
lora_model_state.tp00.pdparams  optimizer.tp01.pdopt  scaler.pdparams     special_tokens_map.json  training_args.bin
lora_model_state.tp01.pdparams  rng_state_0.pth       scheduler.pdparams  tokenizer_config.json

这是保存的模型，模型没有合并

**Comment by lugimzzz** [comment]
你要不到源码打印一下merge_tensor_parallel 和 self.model.config.tensor_parallel_degree 的值，确定有走入这个分支。因为我这边训练都是正常的，复现不出这个问题
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/layers/lora.py#L687
![image](https://user-images.githubusercontent.com/63761690/233885145-e160a0db-349c-48e2-941a-b510fe284df0.png)

**Comment by xieyu0214** [comment]
if training_args.do_train:
    train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
    trainer.save_model(**merge_tensor_parallel=training_args.tensor_parallel_degree > 1**)
    trainer.log_metrics("train", train_result.metrics)
    trainer.save_metrics("train", train_result.metrics)
    trainer.save_state()

> 你要不到源码打印一下merge_tensor_parallel 和 self.model.config.tensor_parallel_degree 的值，确定有走入这个分支。因为我这边训练都是正常的，复现不出这个问题 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/layers/lora.py#L687 ![image](https://user-images.githubusercontent.com/63761690/233885145-e160a0db-349c-48e2-941a-b510fe284df0.png)

if training_args.do_train:
    train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
    trainer.save_model(**merge_tensor_parallel=training_args.tensor_parallel_degree > 1**)
    trainer.log_metrics("train", train_result.metrics)
    trainer.save_metrics("train", train_result.metrics)
    trainer.save_state()

这是保存模型部分的代码，  trainer.save_model(**merge_tensor_parallel=training_args.tensor_parallel_degree > 1**) 这个动作会执行 lora_model.save_pretrained(...) 接口吗

**Comment by lugimzzz** [comment]
会，具体可以看trainer源码实现
