### ISSUE TITLE
[Question]: 使用Taskflow API进行推理时，如何使用全部的核心？

### ISSUE THREAD

**Issue by BrightXiaoHan** [PaddlePaddle/PaddleNLP#5756]
### 请提出你的问题

我自己在ARM服务器上编译了paddle，并使用taskflow api进行预测，但是观察到cpu核心数只用到了机器的一半，有没有什么方法让paddle模型计算时把机器的核心数吃满。
![image](https://user-images.githubusercontent.com/25839309/233826387-7c040329-9034-4fee-b698-e116d9407556.png)
可以看到上图，我的机器是8核心，只用到了其中的四个。

**Comment by wawltor** [comment]
我们测试过占用一半的核心是性能最优的情况，因此不需要使用全部的CPU

**Comment by BrightXiaoHan** [comment]
那我机器扩大核心数比如扩大到16，模型会用到8核，然后这时8核是最优解可以这么理解么

**Comment by wawltor** [comment]
> 那我机器扩大核心数比如扩大到16，模型会用到8核，然后这时8核是最优解可以这么理解么

可以这么理解

**Comment by BrightXiaoHan** [comment]
感谢解答
