### ISSUE TITLE
[Question]: glm模型tokenizer的size与word_embeddings的size长度不一致的问题

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#5759]
### 请提出你的问题

tokenizer的词表默认是50000个，增加了一些字符之后是50010，但是word_embeddings的维度是[50048, 1024]，为什么embeddings多出来了几个？
![WeChatadf205392de443097b8f330c071408b6](https://user-images.githubusercontent.com/18607037/233833280-4249ac5a-91ea-4024-bf4f-4580cc0d65de.png)

**Comment by liuzhipengchd** [comment]
多出来的这些token主要是哪些？

**Comment by LemonNoel** [comment]
这里实现是与[原代码](https://huggingface.co/THUDM/glm-10b-chinese/tree/main)保持一致，但实际测试多出来的 token 并没有用到。
