### ISSUE TITLE
[Bug]:在ai studio 平台使用图片信息提取一键预测报错 

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleNLP#5763]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.4.2.post117
- paddlenlp: 2.4.5
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在ai studio 平台上使用V100 32GB启动项目，运行图片信息提取一键预测报错
执行代码如下:
from pprint import pprint
from paddlenlp import Taskflow
from paddlenlp.utils.doc_parser import DocParser

schema = ['姓名', '项目', '缩写', '结果', '参考值', '单位', '送检日期', '审核日期', '检验者','核对者', '打印时间']
_ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')
doc_path = "./data/images/a4.jpg"
results = my_ie({"doc": doc_path})
pprint(results)


报错信息如下：
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_509/952308238.py in <cell line: 6>()
      4 
      5 schema = ['姓名', '项目', '缩写', '结果', '参考值', '单位', '送检日期', '审核日期', '检验者','核对者', '打印时间']
----> 6 _ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')
      7 doc_path = "./data/images/a4.jpg"
      8 results = my_ie({"doc": doc_path})

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py in __init__(self, task, model, mode, device_id, from_hf_hub, **kwargs)
    537         self.kwargs = kwargs
    538         task_class = TASKS[self.task][tag][self.model]["task_class"]
--> 539         self.task_instance = task_class(
    540             model=self.model, task=self.task, priority_path=self.priority_path, from_hf_hub=from_hf_hub, **self.kwargs
    541         )

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py in __init__(self, task, model, schema, **kwargs)
    411         self.set_schema(schema)
    412         self._check_predictor_type()
--> 413         self._get_inference_model()
    414         self._usage = usage
    415         self._construct_tokenizer()

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/task.py in _get_inference_model(self)
    291             self._prepare_static_mode()
    292         else:
--> 293             self._prepare_onnx_mode()
    294 
    295     def _convert_dygraph_to_static(self):

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/task.py in _prepare_onnx_mode(self)
    209         float_onnx_file = os.path.join(onnx_dir, "model.onnx")
    210         if not os.path.exists(float_onnx_file) or self._param_updated:
--> 211             onnx_model = paddle2onnx.command.c_paddle_to_onnx(
    212                 model_file=self._static_model_file,
    213                 params_file=self._static_params_file,

UnboundLocalError: local variable 'paddle2onnx' referenced before assignment
```

### 稳定复现步骤 & 代码

from pprint import pprint
from paddlenlp import Taskflow
from paddlenlp.utils.doc_parser import DocParser

schema = ['姓名', '项目', '缩写', '结果', '参考值', '单位', '送检日期', '审核日期', '检验者','核对者', '打印时间']
_ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')
doc_path = "./data/images/a4.jpg"
results = my_ie({"doc": doc_path})
pprint(results)

**Comment by LANSEYOUYUMOWANG** [comment]
将paddlenlp 尝试更新到2.5.2
![image](https://user-images.githubusercontent.com/36221128/233880606-3b894760-db44-4bce-8322-1163d45e27d5.png)
报如下错误：
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_3439/952308238.py in <cell line: 6>()
      4 
      5 schema = ['姓名', '项目', '缩写', '结果', '参考值', '单位', '送检日期', '审核日期', '检验者','核对者', '打印时间']
----> 6 _ie = Taskflow("information_extraction", model="uie-x-base", schema=schema, task_path='./checkpoint/model_best', precision='fp16')
      7 doc_path = "./data/images/a4.jpg"
      8 results = my_ie({"doc": doc_path})

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py in __init__(self, task, model, mode, device_id, from_hf_hub, **kwargs)

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py in __init__(self, task, model, schema, **kwargs)

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/task.py in _get_inference_model(self)

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/task.py in _convert_dygraph_to_static(self)

<decorator-gen-239> in save(layer, path, input_spec, **configs)

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     24     def __impl__(func, *args, **kwargs):
     25         wrapped_func = decorator_func(func)
---> 26         return wrapped_func(*args, **kwargs)
     27 
     28     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py in wrapper(layer, path, input_spec, **configs)
    647         for hook in _save_pre_hooks:
    648             hook(layer, input_spec, configs)
--> 649         func(layer, path, input_spec, **configs)
    650 
    651     return wrapper

<decorator-gen-238> in save(layer, path, input_spec, **configs)

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     24     def __impl__(func, *args, **kwargs):
     25         wrapped_func = decorator_func(func)
---> 26         return wrapped_func(*args, **kwargs)
     27 
     28     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py in __impl__(*args, **kwargs)
     65     def __impl__(*args, **kwargs):
     66         with framework._dygraph_guard(None):
---> 67             return func(*args, **kwargs)
     68 
     69     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py in save(layer, path, input_spec, **configs)
    925                     continue
    926 
--> 927                 concrete_program = static_func.concrete_program_specify_input_spec(
    928                     inner_input_spec, with_hook=with_hook)
    929             elif 'forward' == attr_func:

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in concrete_program_specify_input_spec(self, input_spec, with_hook)
    575             has_input_spec = (desired_input_spec is not None)
    576             if has_input_spec:
--> 577                 concrete_program, _ = self.get_concrete_program(
    578                     *desired_input_spec,
    579                     with_hook=with_hook,

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in get_concrete_program(self, *args, **kwargs)
    483 
    484         # 3. check whether hit the cache or build a new program for the input arguments
--> 485         concrete_program, partial_program_layer = self._program_cache[cache_key]
    486         return concrete_program, partial_program_layer
    487 

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in __getitem__(self, item)
    953         self._recent_key = item_id
    954         if item_id not in self._caches:
--> 955             self._caches[item_id] = self._build_once(item)
    956             # Note: raise warnings if number of traced program is more than `max_tracing_count`
    957             current_tracing_count = len(self._caches)

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in _build_once(self, cache_key)
    937 
    938     def _build_once(self, cache_key):
--> 939         concrete_program = ConcreteProgram.from_func_spec(
    940             func_spec=cache_key.function_spec,
    941             input_spec=cache_key.input_args_with_spec,

<decorator-gen-235> in from_func_spec(func_spec, input_spec, input_kwargs_spec, class_instance, **kwargs)

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     24     def __impl__(func, *args, **kwargs):
     25         wrapped_func = decorator_func(func)
---> 26         return wrapped_func(*args, **kwargs)
     27 
     28     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py in __impl__(*args, **kwargs)
     65     def __impl__(*args, **kwargs):
     66         with framework._dygraph_guard(None):
---> 67             return func(*args, **kwargs)
     68 
     69     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in from_func_spec(func_spec, input_spec, input_kwargs_spec, class_instance, **kwargs)
    846         # Transforms dygraph function into static function and caches it.
    847         dygraph_function = func_spec.dygraph_function
--> 848         static_func = convert_to_static(dygraph_function)
    849         # apply pre\post hook for outermost layer
    850         hook_helper = HookHelper(dygraph_function, class_instance,

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in convert_to_static(function)
    140         return function
    141     with _CACHE_LOCK:
--> 142         static_func = _FUNCTION_CACHE.convert_with_cache(function)
    143         setattr(static_func, ALREADY_D2S, True)
    144         return static_func

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in convert_with_cache(self, func)
     75 
     76         if static_func is None:
---> 77             static_func = self._convert(func)
     78             self._converted_static_func_caches[func] = static_func
     79 

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in _convert(self, func)
    102         # with decorator directly and function.__wrapped__ holds the actual function.
    103         func = unwrap(func)
--> 104         source_code = func_to_source_code(func)
    105 
    106         # TODO(liym27):

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py in func_to_source_code(function, dedent)
    701             )
    702         )
--> 703     source_code_list, _ = inspect.getsourcelines(function)
    704     # Replace comments with blank lines so that error messages are not misplaced
    705     source_code_list = [

/opt/conda/envs/python35-paddle120-env/lib/python3.9/inspect.py in getsourcelines(object)
   1004     raised if the source code cannot be retrieved."""
   1005     object = unwrap(object)
-> 1006     lines, lnum = findsource(object)
   1007 
   1008     if istraceback(object):

/opt/conda/envs/python35-paddle120-env/lib/python3.9/inspect.py in findsource(object)
    833         lines = linecache.getlines(file)
    834     if not lines:
--> 835         raise OSError('could not get source code')
    836 
    837     if ismodule(object):

OSError: could not get source code

**Comment by linjieccc** [comment]
@LANSEYOUYUMOWANG 方便的话可以分享下项目地址

**Comment by LANSEYOUYUMOWANG** [comment]
https://aistudio.baidu.com/bj-gpu-02/user/2621467/6015406/lab/workspaces/auto-F/tree/PaddleNLP-develop/applications/information_extraction/document/main.ipynb

**Comment by linjieccc** [comment]
可以公开一下项目，然后分享项目链接

**Comment by LANSEYOUYUMOWANG** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/6015406?contributionType=1

**Comment by linjieccc** [comment]
设置一下项目公开

![image](https://user-images.githubusercontent.com/40840292/233923765-d90c5ffc-75f8-46a7-b73b-05a10a0e756e.png)

**Comment by LANSEYOUYUMOWANG** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/6015406?contributionType=1&sUid=2621467&shared=1&ts=1682320951533
设置了，麻烦您在看下

**Comment by linjieccc** [comment]
> https://aistudio.baidu.com/aistudio/projectdetail/6015406?contributionType=1&sUid=2621467&shared=1&ts=1682320951533 设置了，麻烦您在看下

看起来项目是空的呢
