### ISSUE TITLE
[Question]: 文档信息抽取可以抽取PDF数据，但是label-studio不能标注PDF数据呀

### ISSUE THREAD

**Issue by Jaydon996** [PaddlePaddle/PaddleNLP#5770]
### 请提出你的问题

如题所示
<img width="1842" alt="b3cf2d20550294f42d5be11a3073dd5" src="https://user-images.githubusercontent.com/116625543/233941341-65ea793a-0721-4e88-b460-521b14eb1ebc.png">

那PDF数据怎么标注呀

**Comment by linjieccc** [comment]
当前可以考虑将PDF转为图片格式来标注
