### ISSUE TITLE
为什么Milvus会连接不上？pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5772]
### 请提出你的问题

为什么Milvus会连接不上？
报错：pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on
#
![图片](https://user-images.githubusercontent.com/6648329/233967258-6a409f33-b948-49f8-ab7c-ea0ed4c28f76.png)
#
![图片](https://user-images.githubusercontent.com/6648329/233967377-b93c1657-08ed-4747-880f-229839e2bd4b.png)
#
![图片](https://user-images.githubusercontent.com/6648329/233967546-e2213be1-376f-44d9-a368-0a35a3758218.png)
#attu都可以登陆进来
![图片](https://user-images.githubusercontent.com/6648329/233968470-c1bc8df2-ea73-44fe-9d53-438c29fe1f05.png)

![图片](https://user-images.githubusercontent.com/6648329/233971391-19bb7110-7b2c-47b1-b166-4dae89a763c6.png)

测试地址点击这里进行 aistudio 在线测试： https://aistudio.baidu.com/aistudio/projectdetail/6009399?contributionType=1

**Comment by w5688414** [comment]
1. 使用localhost直接在milvus机器上测试呢？
2. 另外，请确保您的端口是对外开放着的。

**Comment by gg22mm** [comment]
> 1. 使用localhost直接在milvus机器上测试呢？
> 
>     2. 另外，请确保您的端口是对外开放着的。

那肯定是对外的，您可以在线运行一下测试一下。  attu都可以跑起来并登陆,为什么在paddle中不行？这个肯定是问题了吧，这么明显了。
![图片](https://user-images.githubusercontent.com/6648329/234150956-c068d854-6799-45ae-981c-ac119c4bf629.png)

![图片](https://user-images.githubusercontent.com/6648329/234150673-0d52c29d-535c-42f8-99e8-e5d3000263d4.png)

http://159.27.13.175:16814/
你的默认用户是root，密码是Milvus


如果不能解决建议这里换成faiss, Milvus有更种兼容问题：
![图片](https://user-images.githubusercontent.com/6648329/234165634-5a797956-a963-4787-bc9a-1a3a80ce8dec.png)

**Comment by w5688414** [comment]
您有微信没？可以留个联系方式，我们单独解决一下

**Comment by JackLCL** [comment]
@gg22mm 
你在本地能跑通hello_milvus.py（https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py）吗？先确认一下milvus是没有问题的。然后如果能跑通，再去检查一下是不是网络的问题。

**Comment by gg22mm** [comment]
> 您有微信没？可以留个联系方式，我们单独解决一下



> @gg22mm 你在本地能跑通hello_milvus.py（[https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py）吗？先确认一下milvus是没有问题的。然后如果能跑通，再去检查一下是不是网络的问题。](https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py%EF%BC%89%E5%90%97%EF%BC%9F%E5%85%88%E7%A1%AE%E8%AE%A4%E4%B8%80%E4%B8%8Bmilvus%E6%98%AF%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%E7%9A%84%E3%80%82%E7%84%B6%E5%90%8E%E5%A6%82%E6%9E%9C%E8%83%BD%E8%B7%91%E9%80%9A%EF%BC%8C%E5%86%8D%E5%8E%BB%E6%A3%80%E6%9F%A5%E4%B8%80%E4%B8%8B%E6%98%AF%E4%B8%8D%E6%98%AF%E7%BD%91%E7%BB%9C%E7%9A%84%E9%97%AE%E9%A2%98%E3%80%82)

微信： weililong123456
但是我觉得是 milvus 的问题。 已经给milvus 提交了问题，到目前没有实际解决 https://github.com/milvus-io/milvus/issues/23673

**Comment by gg22mm** [comment]
> 您有微信没？可以留个联系方式，我们单独解决一下

知道问题了，我是在aistudio中运行，不知道为什么 aistudio 中不能访问外网还是怎么回事导致的。。 我在我本地就可以很好的运行

**Comment by LLLiHaotian** [comment]
> ### 请提出你的问题
> 为什么Milvus会连接不上？ 报错：pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on
> 
> ![图片](https://user-images.githubusercontent.com/6648329/233967258-6a409f33-b948-49f8-ab7c-ea0ed4c28f76.png)
> 
> ![图片](https://user-images.githubusercontent.com/6648329/233967377-b93c1657-08ed-4747-880f-229839e2bd4b.png)
> 
> ![图片](https://user-images.githubusercontent.com/6648329/233967546-e2213be1-376f-44d9-a368-0a35a3758218.png) #attu都可以登陆进来 ![图片](https://user-images.githubusercontent.com/6648329/233968470-c1bc8df2-ea73-44fe-9d53-438c29fe1f05.png)
> 
> ![图片](https://user-images.githubusercontent.com/6648329/233971391-19bb7110-7b2c-47b1-b166-4dae89a763c6.png)
> 
> 测试地址点击这里进行 aistudio 在线测试： https://aistudio.baidu.com/aistudio/projectdetail/6009399?contributionType=1

您好，我和您同样的报错，您最后解决了吗？我是在linux系统中运行python程序。
Milvus2.3.10
pymilvus2.3.6

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/150894804/149aa72c-039d-491d-b970-767bcb59b458)

**Comment by mashaonian** [comment]
是不是milvus不能通过其他电脑连接，只能通过connections.connect(alias="default",host='localhost', port='19530')才能建立连接
