### ISSUE TITLE
[Bug]: AI studio 【NLP经典项目】样例报错

### ISSUE THREAD

**Issue by ybqand187** [PaddlePaddle/PaddleNLP#5787]
### 软件环境

```Markdown
AI studio环境
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
『NLP经典项目集』09 ：基于Bi-GRU+CRF的快递单信息抽取：https://aistudio.baidu.com/aistudio/projectdetail/1317771
样例代码中有一步切片传入的是tensor，出现报错，无法确定是paddle的bug还是样例代码写的有问题

还有给个建议可否针对样例项目定期做维护呢？不只这一个项目，其它还有一些样例项目在AI Studio中直接跑也会报错，如果无法保证样例项目能跑通，初学者可能会怀疑是paddle的bug，转而采用其它的框架
```

### 稳定复现步骤 & 代码

运行https://aistudio.baidu.com/aistudio/projectdetail/1317771该AI Studio项目，在B.4模型训练报错
执行
model.fit(train_data=train_loader,
              eval_data=dev_loader,
              epochs=1,
              save_dir='./results'
              #log_freq=1
              )
后报错：/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    939               print(loss)
    940         """
--> 941         loss = self._adapter.train_batch(inputs, labels)
    942         if fluid.in_dygraph_mode() and self._input_info is None:
    943             self._update_inputs()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in train_batch(self, inputs, labels)
    654         else:
    655             outputs = self.model.network.forward(
--> 656                 * [to_variable(x) for x in inputs])
    657 
    658         losses = self.model._loss(*(to_list(outputs) + labels))
/tmp/ipykernel_197/1782869612.py in forward(self, x, lens)
     24         output, _ = self.gru(embs)
     25         output = self.fc(output)
---> 26         _, pred = self.decoder(output, lens)
     27         return output, lens, pred
     28 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    900                 self._built = True
    901 
--> 902             outputs = self.forward(*inputs, **kwargs)
    903 
    904             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/layers/crf.py in forward(self, inputs, lengths)
    396         zeros = paddle.zeros([1], dtype='int64')
    397         ones = paddle.ones([1], dtype='int64')
--> 398         for i, logit in enumerate(inputs_t[:max_seq_len]):
    399             # if not with_start_stop_tag, the first label has not antecedent tag.
    400             if i == 0 and not self.with_start_stop_tag:
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows None or integers in slice item, but received Tensor. (at /paddle/paddle/fluid/pybind/imperative.cc:337)

**Comment by linjieccc** [comment]
@ybqand187 你好，感谢反馈~看起来可能是版本兼容问题，我们升级维护下

**Comment by ybqand187** [comment]
@linjieccc 你好，非常感谢回复~AI Studio上的【NLP经典项目】真的很好，如果都定期维护就完美了！

**Comment by ybqand187** [comment]
刚刚重试了一下，已经顺利跑通了，效率很快！
