### ISSUE TITLE
[Question]: diffusers如何设置seed

### ISSUE THREAD

**Issue by zhangvia** [PaddlePaddle/PaddleNLP#5793]
### 请提出你的问题

我看了FastDeployStableDiffusionControlNetPipeline中的源码，generator是一个np.random.RandomState,但却没有设置seed的地方。那在推理代码的地方用generator=np.random.RandomState(seed)可以设置种子吗，可是为什么感觉好像没什么用，没有办法复现效果

**Comment by JunnYu** [comment]
如果scheduler内部没有随机因素的话，你只要设置 generator=np.random.RandomState(seed) 就好了。
当前的 euler_ancestral 的scheduler内部存在随机因素，因此你需要设置一下 paddle.seed(seed)
