### ISSUE TITLE
[Question]: ERNIE Health二次预训练如何新增自定义任务

### ISSUE THREAD

**Issue by johnsongwx** [PaddlePaddle/PaddleNLP#5798]
### 请提出你的问题

您好！一直有在关注ERNIE Health模型，非常棒的一篇工作！
想请教下，我们计划扩展预训练任务，在当前模型训练的基础上继续预训练，在查看代码的过程中发现，model的几个loss已经封装好了，我们如果想进一步添加loss的计算方式应该在哪里添加呢？还是没必要管封装的loss，直接重写模型训练过程代码呢？
谢谢！

**Comment by wawltor** [comment]
理论上最好不要改变Loss的计算方式，loss的改变了模型的收敛目标，如果需要改动的话可以看 
https://github.com/PaddlePaddle/PaddleNLP/blob/a9fec1f4608259b5d886d9cc43923cac3d532a6a/paddlenlp/transformers/electra/modeling.py#L1273
