### ISSUE TITLE
[Question]: codegen 16B 6B模型运行过程中直接卡住不动了不知道为什么？

### ISSUE THREAD

**Issue by leojames** [PaddlePaddle/PaddleNLP#5799]
### 请提出你的问题

在运行codegen的模型6B 直接卡主不动了 环境 A800 80G单卡

loading configuration file /home/user01/.paddlenlp/models/Salesforce/codegen-6B-multi/model_config.json
[2023-04-26 15:47:18,054] [    INFO] - Model config CodeGenConfig {
  "activation_function": "gelu_new",
  "architectures": [
    "CodeGenForCausalLM"
  ],
  "attn_pdrop": 0.0,
  "bos_token_id": 1,
  "embd_pdrop": 0.0,
  "eos_token_id": 2,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "codegen",
  "n_ctx": 2048,
  "n_embd": 4096,
  "n_head": 16,
  "n_inner": null,
  "n_layer": 33,
  "n_positions": 2048,
  "pad_token_id": 50256,
  "paddlenlp_version": null,
  "resid_pdrop": 0.0,
  "rotary_dim": 64,
  "vocab_size": 51200
}

直接就卡到这里了 Python 进程还在 很奇怪

**Comment by liuzhipengchd** [comment]
加载数据集 lazy模式吧，应该是在处理数据

**Comment by leojames** [comment]
> 加载数据集 lazy模式吧，应该是在处理数据

这个应该是下载的问题，下载的模型参数后边有个_tmp 把这个去掉就好了 的确有点坑啊  希望官方修复下
