### ISSUE TITLE
[Question]: Label Studio 表格标注

### ISSUE THREAD

**Issue by LANSEYOUYUMOWANG** [PaddlePaddle/PaddleNLP#5806]
### 请提出你的问题

在使用uie-x-base 对检查检验报告进行训练时，需要在Label Studio 上进行标注，看到git上描述检查检验报告按照下图的方式标注，麻烦问下下图这种实体怎样定义，如何进行标注，是否有相关操作文档？
![image](https://user-images.githubusercontent.com/36221128/234828899-6aa53dc8-f048-4ad0-8304-efa332289dc2.png)

**Comment by linjieccc** [comment]
标注方式和纯文本任务基本一致，这个例子里面实体类别用的是表头名称，文档任务标注可以参考这篇文档：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/label_studio_doc.md
