### ISSUE TITLE
taskflow做信息抽取的时候，同样的信息只能抽到一个

### ISSUE THREAD

**Issue by 123109** [PaddlePaddle/PaddleNLP#5807]
### 请提出你的问题

>>> from paddlenlp import Taskflow
>>> ext = Taskflow('information_extraction')
>>> ext.set_schema(['地址','电话'])
>>> ext('我在软件园A区一号楼上班，我的个人电话是13809232344，工作电话是13809888888')
[{'地址': [{'text': '软件园A区一号楼', 'start': 2, 'end': 10, 'probability': 0.7718060350683764}], '电话': [{'text': '13809232344', 'start': 20, 'end': 31, 'probability': 0.8240228923603432}]}]

如上面的例子，一句里有两个电话号码，但是只能取到第一个。所以要怎么样可以把所有相关的信息都抽取出来呢？

**Comment by wawltor** [comment]
这个需要自己的需求来标注数据微调 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction

**Comment by Vibion** [comment]
> 这个需要自己的需求来标注数据微调 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction

请问微调的数据集大小大概多少呢

**Comment by 123109** [comment]
> 这个需要自己的需求来标注数据微调 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction

这个很不AI吧？比如我一句话里有三个地址，我要都找出来，我要怎么微调呢？是不是我得准备一些数据，这些数据里带了三个地址，我把这三个地址都标注出来，然后去做finetune。那么如果一句话里有四个地址呢？我要不要准备四个地址的数据？再比如有三个人名，我是不是得准备三个人名的标注去训练？同理，凡是有多个同类型的信息，我要抽取都要微调？

**Comment by 123109** [comment]
再补充一下，一句话里有多个姓名，可以都提取出来……这要怎么解释呢？我现在是一脸懵逼

**Comment by linjieccc** [comment]
零样本抽取比较适合早期的调研阶段，可能一些prompt抽取效果不太理想。UIE主要优势在于少样本定制的能力，这种情况少量标注几条数据在你的场景上适配下即可
