### ISSUE TITLE
[Question]: Ernie-layout Performance

### ISSUE THREAD

**Issue by htcml** [PaddlePaddle/PaddleNLP#5810]
### 请提出你的问题

The performance scores reported in the Ernie-layout repo don't match the ones shown in the paper. For example, 89.31 is reported for Key Information Extraction on FUNSD here: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout#3-model-performance But in the paper, 93.12 is reported. Could you explain this discrepency?

**Comment by LiuChiachi** [comment]
The result 93.12 shown in paper is the result of model ERNIE-Layout-**Large**, not the ERNIE-LayoutX-**Base**.

**Comment by htcml** [comment]
Thank you!
