### ISSUE TITLE
LLaMA模型训练

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/PaddleNLP#5811]
### 问题描述

请问[paddlenlp中这个LLaMA](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/llama)模型可以训练自己的的数据吗？

**Comment by wawltor** [comment]
可以构造自己的数据来训练，可以自定义一个dataset https://github.com/PaddlePaddle/PaddleNLP/blob/93e78c2f3fd3d33054da49c78551a148810caaf3/examples/language_model/llama/finetune_generation.py#L156
https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html

**Comment by d2623587501** [comment]
感谢大佬的解答
