### ISSUE TITLE
[Bug]: 使用ernie-3.0做事件抽取时，执行PaddleNLP/examples/information_extraction/DuEE/下的脚本./run_duee_fin.sh trigger_train 报错

### ISSUE THREAD

**Issue by 996-icu-FuJian** [PaddlePaddle/PaddleNLP#5812]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.3.2
- paddlenlp: 2.5.1.post
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
报错信息：
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:3648 != labels_dims[i]:3664.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:164)
  [operator < softmax_with_cross_entropy > error]
```

### 稳定复现步骤 & 代码

    # cd PaddleNLP/examples/information_extraction/DuEE/
    # ./run_duee_fin.sh data_prepare
    # ...
    # ./run_duee_fin.sh trigger_train
![image](https://user-images.githubusercontent.com/36201952/235122155-ed9f3a68-a8b4-4625-b25d-b482b8a1fe42.png)

**Comment by LiuChiachi** [comment]
您好，收到您的反馈，您可以先尝试打印logits和label的shape，看是否是数据处理存在问题，我们后面会安排同学进行排查

**Comment by awhathell** [comment]
您好，我也遇到了这个问题，请问您怎么解决的

**Comment by zlyir** [comment]
hi 我也遇到了同样的问题，请问你这边解决了吗

**Comment by awhathell** [comment]
没有&nbsp;


王梦影
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月14日(星期三) 晚上8:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Bug]: 使用ernie-3.0做事件抽取时，执行PaddleNLP/examples/information_extraction/DuEE/下的脚本./run_duee_fin.sh trigger_train 报错 (Issue #5812)





 
hi 我也遇到了同样的问题，请问你这边解决了吗

**Comment by 1605wzf** [comment]
您好！我也遇到了同样的问题，请问有解决吗
