### ISSUE TITLE
[Question]: ChatGLM  finetune-lora 过程中，发现显存使用量 一直在逐步增加 

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#5822]
### 请提出你的问题

finetune.sh

python -m paddle.distributed.launch --gpus "0,2" finetune_generation.py \
    --model_name_or_path THUDM/chatglm-6b \
    --task_path ../assistant/gen_dialogues/train \
    --max_steps 50000 \
    --learning_rate 3e-5 \
    --warmup_steps 20 \
    --eval_steps 1000 \
    --logging_steps 500 \
    --save_steps 1000 \
    --save_total_limit 100 \
    --output_dir ./checkpoints/chatglm-6b \
    --src_length 2048 \
    --tgt_length 50 \
    --per_device_eval_batch_size 4 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --fp16 \
    --fp16_opt_level O2 \
    --recompute True \
    --do_train \
    --tensor_parallel_degree 2 \
    --lora True

上面是配置，在微调过程中 显存占用逐步在增加，训练半个小时的时间内 由17G 涨到了24G，直至Out of memory error。

paddlenlp 用的是最新的dev分支

**Comment by lugimzzz** [comment]
你用的是什么版本的paddlepaddle，建议用最新develop版本，之前有一个版本有内存泄露问题，现在已修复
