### ISSUE TITLE
[Question]: Optimize english model 

### ISSUE THREAD

**Issue by grinay** [PaddlePaddle/PaddleNLP#5824]
### 请提出你的问题

Hello.Thanks for your beautiful product and effort on making it publicly available. 
I just finetuned uie-base-en model , to extract PII information in my data. 
Currently I'm trying to find the way to simplify model and make it works faster. 
I've tried the way like data_distill , and it works fine, however output model lost ability to work with promts. Which was working on uie-base-en without training. 

I'm looking for a way to user smaller model such as uie-tiny, but there are not pre-trained model for English. 
Would you suggest the steps to optimize the inference time. 
Currently I'm processing page of text and average inference time is around 1 sec per page. My goal is to reduce it up to 0.3 sec per page.  Any help would be appreciated.

**Comment by linjieccc** [comment]
@grinay Hi, Thank you for your interest on UIE. During the inference stage, you can use the fast tokenizer and half-precision inference to speed up the process. The specific configuration method is as follows:

```python
Taskflow('information_extraction', 
                model='uie-base-en', 
                task_path=/path/to/your/model,
                precision='fp16',
                use_fast=True)
```

**Comment by grinay** [comment]
@linjieccc thank you very much, yes that really works great. Reduced inference time almost 10x times. 
The only one thing appear, when using fast tokenizer it output many empty recognitions result
```
           {'end': 1515,
            'probability': 0.9960973262786865,
            'start': 1515,
            'text': ''},
           {'end': 1515,
            'probability': 0.9960975646972656,
            'start': 1515,
            'text': ''}],
```

I may filter out them for sure, but maybe there is something incorrect. Do you have any advice ? May this affect recognition quality? And shouldn't network be finetuned with fast tokenizer too ?
