### ISSUE TITLE
[Question]:  uie抽关系或者实体的时候能设置自动过滤么？比如probability低于0.5就不作为结果这样的？还是说全部抽出来后再另外处理？

### ISSUE THREAD

**Issue by DeqianBai** [PaddlePaddle/PaddleNLP#5827]
### 请提出你的问题

uie抽关系或者实体的时候能设置自动过滤么？比如probability低于0.5就不作为结果这样的？还是说全部抽出来后再另外处理？

我之前在百度的答疑群里看到有人回复说;
Taskflow里面通过probability已经过滤了一波，你可以设置自己的需求设置probability，例如你要求准确率高就设置大一点；

然后我就在加了这个参数，如下：

`ent_re_extract = Taskflow("information_extraction", schema=ent_relation_schema,
                                           task_path='checkpoint/ent_relation/checkpoint-8000',
                                           max_seq_len=512, batch_size=1, probability=0.5)`

但是依然会将低于0.5的结果输出出来，版本信息：
Name: paddlenlp
Version: 2.5.0
Windows 11系统

请问正确的设置方式是什么呢，谢谢解答

**Comment by linjieccc** [comment]
@DeqianBai Hi，可以尝试设置下这个参数`position_prob`，关于这个参数的解释是：模型对于span的起始位置/终止位置的结果概率在0~1之间，返回结果去掉小于这个阈值的结果，默认为0.5，span的最终概率输出为起始位置概率和终止位置概率的乘积
