### ISSUE TITLE
[Bug]: taskflow分词官方教程出错

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleNLP#5828]
### 软件环境

```Markdown
- paddlepaddle:2.4
- paddlepaddle-gpu: 
- paddlenlp: 最新
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
安装完paddlenlp环境后，执行
from paddlenlp import Taskflow
seg_accurate = Taskflow("word_segmentation", mode="accurate")
报错
```

### 稳定复现步骤 & 代码

from paddlenlp import Taskflow
seg_accurate = Taskflow("word_segmentation", mode="accurate")
![图片](https://user-images.githubusercontent.com/26616061/236373523-503f3b3d-9725-4161-8a63-47dc60609361.png)

**Comment by linjieccc** [comment]
paddlenlp的版本是多少呢，我这边没能复现出这个问题，可以尝试做下升级

```shell
pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```

**Comment by truthsun22** [comment]
我是windows系统，直接从conda窗口命令执行的，就报这个错，但是我从Pycharm里面运行就没事，您可以忽略这个错误
