### ISSUE TITLE
有多张 GPU，但是每张 GPU 的显存大小都不足以容纳完整的模型,怎么将模型部署到多张 GPU 上进行推理

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#5832]
### 请提出你的问题

ChatGLM 提供了这种方法
首先安装 accelerate: pip install accelerate，然后通过如下方法加载模型：
from utils import load_model_on_gpus
model = load_model_on_gpus("THUDM/chatglm-6b", num_gpus=2)
即可将模型部署到两张 GPU 上进行推理。你可以将 num_gpus 改为你希望使用的 GPU 数。默认是均匀切分的，你也可以传入 device_map 参数来自己指定。

---------------------------------------------------------------------------

现在paddle有没有这种功能？

**Comment by sijunhe** [comment]
您好，我们月中会正式推出v2.6的paddlenlp，会包含你这里提到的分布式推理功能. 
如果您想提前尝试，可以看看https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/chatglm/predict_generation.py 注意安装最新的nightly的paddle框架

**Comment by felix-fei-fei** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/chatglm/predict_generation.py 
确认了上面的代码，装载模型还是使用一个gpu，没办法使用多卡来装载。
