### ISSUE TITLE
[Question]: 智能语音指令解析基于Web的部署Demo方案在哪？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/PaddleNLP#5835]
### 请提出你的问题

文档实例中的智能语音指令解析，最后面部署有一个基于Web的部署Demo方案，但没找到代码，链接页面https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/speech_cmd_analysis
![图片](https://user-images.githubusercontent.com/26616061/236412780-dd1da9df-eb22-4c7e-9ff9-71442146cdcb.png)

**Comment by truthsun22** [comment]
找到了，在产业范例里面，找到了ai studio项目，里面有详细说明

**Comment by Jaydon996** [comment]
> 找到了，在产业范例里面，找到了ai studio项目，里面有详细说明

没找到啊兄弟，能给个链接么，谢谢

**Comment by truthsun22** [comment]
> > 找到了，在产业范例里面，找到了ai studio项目，里面有详细说明
> 
> 没找到啊兄弟，能给个链接么，谢谢

在paddlespeech里面，\PaddleSpeech\demos\speech_web

**Comment by Jaydon996** [comment]
> > > 找到了，在产业范例里面，找到了ai studio项目，里面有详细说明
> > 
> > 
> > 没找到啊兄弟，能给个链接么，谢谢
> 
> 在paddlespeech里面，\PaddleSpeech\demos\speech_web

好的，谢谢
