### ISSUE TITLE
关于ppdiffusers/examples/dreambooth中的代码更新申请

### ISSUE THREAD

**Issue by A-cunminF** [PaddlePaddle/PaddleNLP#5847]
### 希望官方的训练代码可以更新对hf_hub、diffusers模型的支持。

按照目前训练代码（ https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/dreambooth ）中README的信息， “--pretrained_model_name_or_path: 所使用的 Stable Diffusion 模型权重名称或者本地下载的模型路径，目前支持了上表中的8种模型权重，我们可直接替换使用。”

然而实际替换成hf_hub的模型名称，是没有办法直接替换使用的。训练脚本没有提供传入from_hf_hub、from_diffusers和to_diffusers三个参数，因此目前的脚本实际上无法读取、下载、训练、保存比较主流的pytorch模型。

#### 半成品脚本
我做了一个更新的版本，增加了to_diffusers（保存成pytorch diffusers）、from_diffusers（读取hf_diffusers模型）和from_hf_hub（从huggingface下载模型）三个参数以传入，action为store_true，调用即激活。

#### from_hf_hub遇到的问题
然而，训练中的AutoTokenizer类即使调用了subfolder=“tokenizer”似乎也不能正确定位vocab.json文件。

我尝试使用hf_hub_download直接下载，在AI Studio中HTTP报错443（链接正确，本地可以打开）。

因此我放弃了from_hf_hub，只测试了在work目录下放diffusers模型的情况。

#### 目前进度
使用本地模型时，在AI Studio中可以成功读取并训练基于pytorch anything-v5的LoRA模型。

以下是链接：

https://github.com/A-cunminF/ppdiffusers_train_dreambooth_and_lora/tree/main

希望官方能够尽快跟进训练脚本的更新！

**Comment by JunnYu** [comment]
你好，当前其实可以通过设置环境变量即可达到你上面的那种效果。
https://github.com/PaddlePaddle/PaddleNLP/blob/19ac480600fbb59839753b1a88e76475b5e24b1f/ppdiffusers/ppdiffusers/utils/constants.py#L49-L51
```sh
export FROM_HF_HUB=True
export FROM_DIFFUSERS=True
export TO_DIFFUSERS=False
```

**Comment by A-cunminF** [comment]
> 你好，当前其实可以通过设置环境变量即可达到你上面的那种效果。
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/19ac480600fbb59839753b1a88e76475b5e24b1f/ppdiffusers/ppdiffusers/utils/constants.py#L49-L51
> 
> ```shell
> export FROM_HF_HUB=True
> export FROM_DIFFUSERS=True
> export TO_DIFFUSERS=False
> ```

感谢您的回复，您说的这种方法我尝试过了，但还是遇到了一些问题。我的做法是vim一个sh文件如下并在AI Studio的终端中运行：

```shell
export FROM_HF_HUB=True
export FROM_DIFFUSERS=True
export TO_DIFFUSERS=True
python train_dreambooth_lora.py \
  --pretrained_model_name_or_path="stablediffusionapi/anything-v5"  \
  --instance_data_dir="./train_data" \
  --output_dir="lora_outputs" \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=100 \
  --learning_rate=1e-4 \
  --report_to="visualdl" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=50 \
  --lora_rank=4 \
  --seed=0 
```

但是目前我在AI Studio当中遇到了这样的问题：

#### 1、当打开FROM_HF_HUB=True时，脚本并不能正确识别repo_id来自hf_hub，报错如下：

```
RuntimeError: Downloading from https://bj.bcebos.com/paddlenlp/models/community/stablediffusionapi/anything-v5/tokenizer/tokenizer_config.json failed with code 404!
...
RuntimeError: Can't load tokenizer for 'stablediffusionapi/anything-v5/tokenizer'.
```

从链接可以看到，即使设置了环境变量，脚本依旧按照repo_id来自paddlenlp来下载文件，因此会报错404。另一方面，脚本目前获取tokenizer的方式在hf_hub上似乎是不可行的，hf_hub上获取subfolder看起来是要指定repo_id再传入一个subfolder参数，而不是直接写path。

#### 2、使用本地模型时（修改pretrained_model_name_or_path为本地目录，设置FROM_HF_HUB=False），能正确识别各config的json文件，但FROM_DIFFUSERS环境变量似乎并不生效，报错如下：

```
File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/ppdiffusers/patches/ppnlp_patch_utils.py", line 742, in from_pretrained_v3
    from_hf_hub=from_hf_hub,
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/ppdiffusers/utils/download_utils.py", line 87, in _get_model_file
    f"Error no file named {weights_name} found in directory {pretrained_model_name_or_path}."
OSError: Error no file named model_state.pdparams found in directory ./work/anything-v5/text_encoder.
```

可以看到脚本依然是在寻找model_state.pdparams，这意味着FROM_DIFFUSERS似乎并没有生效。

#### 我想知道这是否是我的操作出现了什么问题，希望您有空的时候予以答复，谢谢！

**Comment by JunnYu** [comment]
1. 当前paddlenlp的tokenizer还不受 FROM_HF_HUB 这个环境变量的控制，因此tokenizer是无法这样下载的。
2. 我发现我在设置默认变量的时候，没有这样写，from_diffusers = kwargs.pop("from_diffusers", FROM_DIFFUSERS)，因此环境变量不生效，之后我会修复这个的。
最后，我会尽快提个PR，新增 to_diffusers、from_diffusers和from_hf_hub这三个选项的

**Comment by A-cunminF** [comment]
> 1. 当前paddlenlp的tokenizer还不受 FROM_HF_HUB 这个环境变量的控制，因此tokenizer是无法这样下载的。
> 2. 我发现我在设置默认变量的时候，没有这样写，from_diffusers = kwargs.pop("from_diffusers", FROM_DIFFUSERS)，因此环境变量不生效，之后我会修复这个的。
>    最后，我会尽快提个PR，新增 to_diffusers、from_diffusers和from_hf_hub这三个选项的

### 感谢您的工作！我自己试图修复过tokenizer的下载问题，希望下面这些内容对您有用：

paddlenlp的autotokenizer类的from_pretrained方法其实提供了from_hf_hub这个参数，但并不适配diffusers的目录结构，即使指定subfolder='tokenizer'也依然会在main分支下找vocab.json文件，例如运行如下代码：

```python
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('stablediffusionapi/anything-v5', from_hf_hub = True, subfolder='tokenizer')
```

得到的结果是

```
We are using <class 'paddlenlp.transformers.clip.tokenizer.CLIPTokenizer'> to load 'stablediffusionapi/anything-v5'.
...
EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64588f91-3dc5990327a380d44e507167)
Entry Not Found for url: https://huggingface.co/stablediffusionapi/anything-v5/resolve/main/vocab.json.
```

可以看到在寻找从vocab.json文件时，subfolder参数并未生效，但寻找tokenizer_config.json时是生效了的。关于vocab.json文件，正确的链接应该是：https://huggingface.co/stablediffusionapi/anything-v5/resolve/main/tokenizer/vocab.json

**Comment by JunnYu** [comment]
```python
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('stablediffusionapi/anything-v5', from_hf_hub = True, subfolder='tokenizer')
```
这里需要改成，使用 CLIPTokenizer。
```python
from paddlenlp.transformers import CLIPTokenizer
tokenizer = CLIPTokenizer.from_pretrained('stablediffusionapi/anything-v5', from_hf_hub = True, subfolder='tokenizer')
```
当前 AutoTokenizer存在bug，需要等待修复

**Comment by A-cunminF** [comment]
原来如此，了解了，感谢您抽空回答我的问题，期待新版本能够修复这些问题！

**Comment by JunnYu** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/5868 等待这部分修复

**Comment by A-cunminF** [comment]
> #5868 等待这部分修复

原来subfolder是都不行么，难怪那个训练脚本在Tokenizer那块写的那么别扭……

不过，只是想加载BOS的话倒是可以不用subfolder，像这样可以正常读取：

```python
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5/tokenizer', from_hf_hub = False)
```

但HF不接受这种方式，要求必须是'repo_name' or 'namespace/repo_name'，如果运行：

```python
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5/tokenizer', from_hf_hub = True)
```

则会报错：

```
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'runwayml/stable-diffusion-v1-5/tokenizer'. Use `repo_type` argument if needed.
```
