### ISSUE TITLE
schema 随便怎么设置都可以，要参考与训练的一些实体？[Question]: 

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#5848]
### 请提出你的问题

schema 随便怎么设置都可以，要参考与训练的一些实体？需要根据什么设置？我设置schema=【‘金额’】的时候提取不到金额

如果我要提取甲方公司名 和乙方公司名 要区分甲方和乙方，实体标注的时候需要把甲方标注在内？：
text：
甲方  ：XXXXX有限公司 
已方  ：XXXXX有限公司

**Comment by LemonNoel** [comment]
在特定场景建议先定制化微调后再使用，具体使用可参考[相关文档](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/text#2)
