### ISSUE TITLE
please help! can not fine dataset DuReader

### ISSUE THREAD

**Issue by Chambers1994** [PaddlePaddle/PaddleNLP#585]
python -m paddle.distributed.launch --gpus "1" run_du.py     --model_type bert     --model_name_or_path bert-base-chinese     --max_seq_length 512     --batch_size 16     --learning_rate 5e-5     --num_train_epochs 4     --logging_steps 1000     --save_steps 1000     --warmup_proportion 0.1     --weight_decay 0.01     --output_dir ./tmp/dureader/     --n_gpu 1 \
> 
-----------  Configuration Arguments -----------
gpus: 1
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers: 
training_script: run_du.py
training_script_args: ['--model_type', 'bert', '--model_name_or_path', 'bert-base-chinese', '--max_seq_length', '512', '--batch_size', '16', '--learning_rate', '5e-5', '--num_train_epochs', '4', '--logging_steps', '1000', '--save_steps', '1000', '--warmup_proportion', '0.1', '--weight_decay', '0.01', '--output_dir', './tmp/dureader/', '--n_gpu', '1']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-06-17 21:26:56,740 launch.py:316] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-06-17 21:26:56,741 launch_utils.py:472] Local start 1 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:39091               |
    |                     PADDLE_TRAINERS_NUM                        1                      |
    |                PADDLE_TRAINER_ENDPOINTS                 127.0.0.1:39091               |
    |                     FLAGS_selected_gpus                        1                      |
    +=======================================================================================+

INFO 2021-06-17 21:26:56,741 launch_utils.py:475] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
[2021-06-17 21:26:57,817] [    INFO] - Found /root/.paddlenlp/models/bert-base-chinese/bert-base-chinese-vocab.txt
Traceback (most recent call last):
  File "run_du.py", line 236, in <module>
    do_train(args)
  File "run_du.py", line 119, in do_train
    train_dataset = ppnlp.datasets.DuReader(
AttributeError: module 'paddlenlp.datasets' has no attribute 'DuReader'

**Comment by smallv0221** [comment]
I'm sorry that DuReader dataset is still under progress. You are welcome to use DuReader-Robust, DuReader-Checklist or DuReader-YesNo dataset instead.

**Comment by chenxiaozeng** [comment]
You can also define DuReader dataset according to the doc: https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html
