### ISSUE TITLE
关于关键信息提取task的问题

### ISSUE THREAD

**Issue by Fly-betterme** [PaddlePaddle/PaddleNLP#5856]
### 请提出你的问题

task_instance = Taskflow(
    "information_extraction",
    model="uie-x-base",
    device_id=-1)
调用该模型时以下报错：
could not create a primitive descriptor for a reorder primitive
不知道是哪里出了问题，可能出问题的点在哪

**Comment by linjieccc** [comment]
你好 @draling ，请尝试更新下paddlepaddle到最新版本
