### ISSUE TITLE
请问一下paddlenlp中simbert模型的准确率和召回率指标是多少？

### ISSUE THREAD

**Issue by danxuan2022** [PaddlePaddle/PaddleNLP#5859]
### 请提出你的问题

请问一下paddlenlp中simbert模型的准确率和召回率指标是多少？（注：在PaddleNlp Repo里只看到了用法，目前业务中想直接接入paddlenlp的simbert能力，但需要先参考一下该模型top1、top5准确率和召回率指标）
paddlenlp示例：
>>> from paddlenlp import Taskflow
>>> similarity = Taskflow("text_similarity")
>>> similarity([["春天适合种什么花？", "春天适合种什么菜？"]])
[{'text1': '春天适合种什么花？', 'text2': '春天适合种什么菜？', 'similarity': 0.83402544}]

**Comment by w5688414** [comment]
这个没有测试过,simbert是在公开的2000万QQpair对训练过，可以自己找数据集测试一下.
