### ISSUE TITLE
[Question]: 搭建两路召回语义检索启动报错

### ISSUE THREAD

**Issue by longhail2008** [PaddlePaddle/PaddleNLP#5861]
搭建两路召回语义检索启动报错

按照说明搭建两路召回语义检索系统，在启动API服务进行curl验证的时候出现报错：ValueError: No node(s) or global parameter(s) named BMRetriever, DenseRetriever found in pipeline.
请问要如何解决呢

**Comment by w5688414** [comment]
请问您用的是哪个pipelines版本，请升级最新版本的pipelines试一下

**Comment by longhail2008** [comment]
好的谢谢，我试试，目前用的0.5.2版本

**Comment by longhail2008** [comment]
@w5688414 谢谢，问题解决了，原来是API端口号冲突的问题，改个端口号就行了。
