### ISSUE TITLE
[Question]: UIE-X关系抽取混乱

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#5862]
### 请提出你的问题

paddlepaddle-gpu==2.4.2
paddlenlp==2.5.2
<h1>使用五倍负例和八倍负例发现惨不忍睹关系抽取很乱</h1>

![ocr_result2 (6)](https://user-images.githubusercontent.com/44227598/236727831-ca5bb99c-fc77-4d49-870b-79bf932a0d7b.png)

<h1>于是乎我使用了16倍负例和20倍负例看看能不能解决发现成了下面的样子</h1>

![ocr_result2 (7)](https://user-images.githubusercontent.com/44227598/236728159-28b1390f-588d-4973-bce7-e1fc5fe786c6.png)
![ocr_result2 (8)](https://user-images.githubusercontent.com/44227598/236728174-26ef4d8c-8ef3-438c-9a9c-cc6337c99ee4.png)

<h1>我目前使用的版面分析是这样子的</h1>

![LPVXQ01EVN~62W}%YBOTH28](https://user-images.githubusercontent.com/44227598/236728720-33c209e2-fcc2-423a-a1c3-1b44a3cd7dfd.png)

<h1>当我使用这种版面分析的时候，使用八倍负例非常完美,可惜不能多行识别，求助帮帮我</h1>

![YJ8(~XFQEBQ{E15TU5N~}S8](https://user-images.githubusercontent.com/44227598/236729077-a7740b61-d476-4924-9215-c78b01927bb9.png)

![ocr_result2 (3)](https://user-images.githubusercontent.com/44227598/236729167-01b2184f-63cc-426b-94ec-40a21b4accb2.png)

**Comment by linjieccc** [comment]
@1061302569 你好，版面分析多行无法识别的原因可能是默认的PPStructure模型在当前发票场景下的识别效果不太理想，可以通过定制PPStructure模型来提升表格识别的效果，以下优化方案供参考：[UIE 文档表格关键信息抽取专项优化方案](https://aistudio.baidu.com/aistudio/projectdetail/5704766?sUid=2900009&shared=1&ts=1679480566567)

**Comment by 1061302569** [comment]
> @1061302569 你好，版面分析多行无法识别的原因可能是默认的PPStructure模型在当前发票场景下的识别效果不太理想，可以通过定制PPStructure模型来提升表格识别的效果，以下优化方案供参考：[UIE 文档表格关键信息抽取专项优化方案](https://aistudio.baidu.com/aistudio/projectdetail/5704766?sUid=2900009&shared=1&ts=1679480566567)

谢谢老师能在百忙中回复我，我尝试过将表格识别为table，可以进行多行识别，副作用是无法产生负例，这是上次训练表格识别提的Issues https://github.com/PaddlePaddle/PaddleNLP/issues/5599 不知道怎么办了尝试很多办法都无法正常关系抽取

**Comment by 1061302569** [comment]
> @1061302569你好，版面分析多行无规律的原因可能是默认的PPStructure模型在当场场景下的密码效果不太理想，可以通过自定义PPStructure模型模型来提升级表格知识的效果，以下优化方案提供参考： UIE 文档[表格关键信息抽取专项优化方案](https://aistudio.baidu.com/aistudio/projectdetail/5704766?sUid=2900009&shared=1&ts=1679480566567)

<h1>这是我的表格标注</h1>

![2bbf6efd4d060674a2c51159c51baa2](https://user-images.githubusercontent.com/44227598/237042592-9295916a-cb2f-4a15-bec9-8591ee8d537f.png)

<h1>使用的命令</h1>

!python label_studio.py \
    --label_studio_file ./datasets/label.json \
    --save_dir ./datasets \
    --splits 0.8 0.2 0\
    --task_type ext \
    --layout_analysis True \
    --negative_ratio 8

**Comment by datuizhuang** [comment]
你好，请问你抽取      项目名称-单位-单价-金额          这种关系的时候怎么设置的prompt呢？如果prompt设置为项目名称，那么每一个名称后面的一串信息如何抽取出来呢？
