### ISSUE TITLE
[Bug]: Auto及非Auto的Tokenizer、Model、Config 的from_pretrained+subfolder加载HF和BOS出错

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#5868]
### 软件环境

```Markdown
paddle-bfloat                     0.1.7
paddle2onnx                       1.0.5
paddlefsl                         1.1.0
paddlehub                         2.3.1
paddlenlp                         2.5.2.post0
paddleocr                         2.6.1.3
paddlepaddle-gpu                  0.0.0.post117
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

1. AutoTokenizer + subfolder + hf 出错
2. AutoTokenizer + subfolder + bos 出错
3. 非Auto的CLIPTokenizer + subfolder + bos 出错
4. AutoConfig + subfolder + bos 出错
5. 非Auto的CLIPTextConfig + subfolder + bos 出错
6. CLIPTextModel  + subfolder + bos 出错 （暂不考虑automodel）
7. CLIPTextModel  + subfolder + hf 出错 （暂不考虑automodel）
8. ImageProcessor + subfolder + bos 出错 

### 加载HF出错
```python

from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer
tokenizer = AutoTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='tokenizer', 
                                  from_hf_hub=True)
```
![image](https://user-images.githubusercontent.com/50394665/236753033-b01437bc-05e8-4f29-bea7-170bda16acec.png)

### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer
tokenizer = AutoTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='tokenizer', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236753241-f3491cf6-dae3-45c4-8185-a8b580c52bd7.png)

### 加载HF正确
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer
tokenizer = CLIPTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='tokenizer', 
                                  from_hf_hub=True)

```
### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer
tokenizer = CLIPTokenizer.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='tokenizer', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236754067-11331b86-2028-4294-bacf-fedd07a5598d.png)

### 加载HF正确
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig
config = AutoConfig.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=True)
```
### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig
config = AutoConfig.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236755230-ffa0d57d-0d13-4323-9f17-7c6be0844e65.png)

### 加载HF正确
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig
config = CLIPTextConfig.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=True)
```
### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig, CLIPTextConfig
config = CLIPTextConfig.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236755524-e694c718-7d01-4c06-84fb-214caf497650.png)

### 加载HF错误，因为config都加载不上。。。。
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig, CLIPTextConfig, CLIPTextModel
model = CLIPTextModel.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=True)

```
![image](https://user-images.githubusercontent.com/50394665/236756402-6284792a-75c2-4f24-b029-7536b9ac5ad1.png)

### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig, CLIPTextConfig, CLIPTextModel
model = CLIPTextModel.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='text_encoder', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236756714-7114fec5-af78-4556-8e10-4a8ea3e4815e.png)

### 加载BOS出错
```python
from paddlenlp.transformers import AutoTokenizer, CLIPTokenizer, AutoConfig, CLIPTextConfig, CLIPTextModel, CLIPImageProcessor
processor = CLIPImageProcessor.from_pretrained('runwayml/stable-diffusion-v1-5', 
                                  subfolder='feature_extractor', 
                                  from_hf_hub=False)
```
![image](https://user-images.githubusercontent.com/50394665/236757514-da279e6b-0e2d-45ac-a922-5fe54f8d8e09.png)

**Comment by macanv** [comment]
我这边也遇到无法加载HF模型的问题
paddlenlp                         2.5.2
paddlepaddle-gpu            2.4.2


稳定复现
替换 examples/information_extraction/waybill_ie/run_ernie.py 中的模型ernie-3.0-medium-zh为：
hfl/chinese-electra-180g-small-ex-discriminator
后无法训练，CUBLAS 报错：
core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUBLAS error(14). 
  [Hint: Please search for the error code(14) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)

**Comment by JunnYu** [comment]
已经修复
