### ISSUE TITLE
Milvus 只有一个字匹配，召唤率达0.6这么高， 如何设置只匹配一个字的直接不召唤算了

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleNLP#5869]
### 请提出你的问题

Milvus 只有一个字匹配，召唤率0.6这么高， 按道理只有一个字匹配的都可以过滤掉了~~
![图片](https://user-images.githubusercontent.com/6648329/236748486-0e3bc817-b892-4a76-afd9-2fe2f1883893.png)

如何设置只匹配一个字的直接不召回，或如何设置根据匹配度来召回。 比如当匹配两个字的情况比一个字靠前。

**Comment by w5688414** [comment]
> ### 请提出你的问题
> Milvus 只有一个字匹配，召唤率0.6这么高， 按道理只有一个字匹配的都可以过滤掉了~~ ![图片](https://user-images.githubusercontent.com/6648329/236748486-0e3bc817-b892-4a76-afd9-2fe2f1883893.png)
> 
> 如何设置只匹配一个字的直接不召回，或如何设置根据匹配度来召回。 比如当匹配两个字的情况比一个字靠前。

您好，匹配跟Milvus无关，Milvus只起到加速的效果，这个跟模型相关，并且关键字匹配不推荐使用语义检索，如果是句子级别的匹配，使用语义检索更合适

**Comment by w5688414** [comment]
请问您使用的是neural search 还是pipelines呢？

**Comment by gg22mm** [comment]
> neural search

使用的是： neural search

在线测试：http://159.27.13.78:16883/ask/index.html 
aistudio: https://aistudio.baidu.com/aistudio/projectdetail/6009399?contributionType=1

**Comment by w5688414** [comment]
> > neural search
> 
> 使用的是： neural search
> 
> 在线测试：http://159.27.13.78:16883/ask/index.html aistudio: https://aistudio.baidu.com/aistudio/projectdetail/6009399?contributionType=1

这个需要在得到检索结果之后，写规则进行过滤。模型如果在训练的时候没遇到过这种情况，不太可能cover住。
