### ISSUE TITLE
some error at the api reference  of paddlenlp

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/PaddleNLP#587]
![991CFED9A5776BF1AD1B37A9CFAE2137](https://user-images.githubusercontent.com/16071449/122518526-e5b28400-d043-11eb-967c-1179721e3d59.jpg)
Mybe that `pooling_type is not None xxxx`

**Comment by Steffy-zxf** [comment]
Thanks for your attention! This docs error will be fix by pr : https://github.com/PaddlePaddle/PaddleNLP/pull/595 .
