### ISSUE TITLE
[Question]: aistudio平台克隆develop分支，调用LLaMa模型训练

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/PaddleNLP#5877]
### 请提出你的问题

aistudio平台克隆develop分支，调用LLaMa模型训练，如下（修改了路径）
`!python -u  -m paddle.distributed.fleet.launch \
    --gpus "0" PaddleNLP/examples/language_model/llama/finetune_generation.py \  
    --model_name_or_path facebook/llama-7b \
    --do_train \
    --do_eval \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --tensor_parallel_degree 4 \
    --overwrite_output_dir \
    --output_dir ./checkpoints/ \
    --logging_steps 10 \
    --fp16 \
    --fp16_opt_level O2 \
    --gradient_accumulation_steps 32 \
    --recompute \
    --learning_rate 3e-5 \
    --lr_scheduler_type linear \
    --max_grad_norm 1.0 \
    --warmup_steps 20`
报错结果如下
`Traceback (most recent call last):
  File "PaddleNLP/examples/language_model/llama/finetune_generation.py", line 21, in <module>
    from modeling_pp import LlamaForCausalLMPipe
  File "/home/aistudio/PaddleNLP/examples/language_model/llama/modeling_pp.py", line 22, in <module>
    from paddlenlp.transformers.llama.modeling import (
ModuleNotFoundError: No module named 'paddlenlp.transformers.llama'`
训练走的是aistudio本身环境中的paddlenlp，而不是开发分支中的PaddleNLP/paddlenlp，请问这种情况应该怎么处理。

**Comment by linjieccc** [comment]
可以通过下面的方式来安装develop版本：

```shell
pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
```
