### ISSUE TITLE
[Bug]: examples/text_classification/ernie_doc/train.py  参数错误

### ISSUE THREAD

**Issue by now-101** [PaddlePaddle/PaddleNLP#5878]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
examples/text_classification/ernie_doc/train.py
line 340：

    predict(model, test_dataloader, args.file_path, memories, test_ds.label_list)

args中不存在参数“args.file_path”，根据代码逻辑，应该是参数“args.test_results_file”
```

### 稳定复现步骤 & 代码

python train.py --batch_size 4                 --model_name_or_path ernie-doc-base-zh                 --epoch 5                 --output_dir ./checkpoints/

报错如图：
![image](https://user-images.githubusercontent.com/34698600/237020653-80bdaa3e-87d1-4914-b90e-678ee38d796f.png)

**Comment by w5688414** [comment]
感谢反馈
