### ISSUE TITLE
使用UTC做多分类发现一个问题，基于fastploy部署预测结果欠佳和正常taskflow以及sever方式结果差距很大，很神奇？

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#5879]
### 请提出你的问题

使用UTC做多分类发现一个问题，基于fastploy部署预测结果欠佳和正常taskflow以及sever方式结果差距很大，很神奇？

背景描述：之前做了一个8分类的小样本训练，不存在上述问题。

后续增加分类种类到30+，正常训练完预测正常，本地进行sever调用结果也正常，但是经过fastploy部署方式分类结果就会错很多。想请问为什么会造成上述情况呀，用的mini 模型测试的。

用训练集来测，fastploy方式得到结果依旧错误较多

**Comment by tingaicompass** [comment]
补充：发现问题源头：是model下面放置了static 静态图模型导致的，删除就好了，具体缘由不详。还请解答

**Comment by WethatVivy** [comment]
遇到了类似的问题，模型run_train时eval和run_eval时eval都正常。使用Taskflow设置task_path参数指定训练出来的模型时会出现参数加载不全的warning，且最终预测结果异常，结果如下。
[{'text_a': '连翘的功效与作用', 'predictions': [{'label': '病情诊断', 'score': 0.6040157635199932}, {'label': '治疗方案', 'score': 0.6033586895256761}, {'label': '病因分析', 'score': 0.6056000139163521}, {'label': '指标解读', 'score': 0.6029113714061555}, {'label': '就医建议', 'score': 0.6091699045680704}, {'label': '疾病表述', 'score': 0.6071043242013696}, {'label': '后果表述', 'score': 0.6036845139203233}, {'label': '注意事项', 'score': 0.6071798303385197}, {'label': '功效作用', 'score': 0.6014871598547071}, {'label': '医疗费用', 'score': 0.6000158113506858}, {'label': '其他', 'score': 0.6136537486740526}]}]
有看到题主之前发过一个情况非常类似的issue然后关闭了，如果能告知一下解决方法的话会非常感谢。
也希望官方人员能解答一下，谢谢。

**Comment by 315445896** [comment]
遇到同样问题，paddlenlp2.5.2，模型run_train时eval和run_eval时eval都正常。使用Taskflow设置task_path参数指定训练出来的模型时会出现参数加载不全的warning，且最终预测结果异常。希望有人解决过的话，告知一下谢谢。

**Comment by JoshonSmith** [comment]
> 遇到了类似的问题，模型run_train时eval和run_eval时eval都正常。使用Taskflow设置task_path参数指定训练出来的模型时会出现参数加载不全的warning，且最终预测结果异常，结果如下。 [{'text_a': '连翘的功效与作用', 'predictions': [{'label': '病情诊断', 'score': 0.6040157635199932}, {'label': '治疗方案', 'score': 0.6033586895256761}, {'label': '病因分析', 'score': 0.6056000139163521}, {'label': '指标解读', 'score': 0.6029113714061555}, {'label': '就医建议', 'score': 0.6091699045680704}, {'label': '疾病表述', 'score': 0.6071043242013696}, {'label': '后果表述', 'score': 0.6036845139203233}, {'label': '注意事项', 'score': 0.6071798303385197}, {'label': '功效作用', 'score': 0.6014871598547071}, {'label': '医疗费用', 'score': 0.6000158113506858}, {'label': '其他', 'score': 0.6136537486740526}]}] 有看到题主之前发过一个情况非常类似的issue然后关闭了，如果能告知一下解决方法的话会非常感谢。 也希望官方人员能解答一下，谢谢。

我是用checkpionts下面的plm子文件作为Taskflow的路径，就可以正常出结果

**Comment by JoshonSmith** [comment]
> 遇到同样问题，paddlenlp2.5.2，模型run_train时eval和run_eval时eval都正常。使用Taskflow设置task_path参数指定训练出来的模型时会出现参数加载不全的warning，且最终预测结果异常。希望有人解决过的话，告知一下谢谢。

我是用checkpionts下面的plm子文件作为Taskflow的路径，就可以正常出结果

**Comment by imempty** [comment]
> 遇到了类似的问题，模型run_train时eval和run_eval时eval都正常。使用Taskflow设置task_path参数指定训练出来的模型时会出现参数加载不全的warning，且最终预测结果异常，结果如下。 [{'text_a': '连翘的功效与作用', 'predictions': [{'label': '病情诊断', 'score': 0.6040157635199932}, {'label': '治疗方案', 'score': 0.6033586895256761}, {'label': '病因分析', 'score': 0.6056000139163521}, {'label': '指标解读', 'score': 0.6029113714061555}, {'label': '就医建议', 'score': 0.6091699045680704}, {'label': '疾病表述', 'score': 0.6071043242013696}, {'label': '后果表述', 'score': 0.6036845139203233}, {'label': '注意事项', 'score': 0.6071798303385197}, {'label': '功效作用', 'score': 0.6014871598547071}, {'label': '医疗费用', 'score': 0.6000158113506858}, {'label': '其他', 'score': 0.6136537486740526}]}] 有看到题主之前发过一个情况非常类似的issue然后关闭了，如果能告知一下解决方法的话会非常感谢。 也希望官方人员能解答一下，谢谢。

问题解决了么，我遇到同样问题，预测结果概率值都很接近。整体准确率很低。 @315445896 @WethatVivy
