### ISSUE TITLE
AI Studio notebook Memory burst

### ISSUE THREAD

**Issue by ITerydh** [PaddlePaddle/PaddleNLP#589]
When there are more than one training task in a notebook project, the memory occupied by the last task will not be released in time. It needs to be restarted the actuator.I think this needs to be optimized

**Comment by ZeyuChen** [comment]
You mean run paddlenlp in AIStudio? @ITerydh

**Comment by ITerydh** [comment]
不是，就是跑完一个数据集之后，再跑下一个数据集的时候，就会提示内存超过范围，需要重启一下才可以跑，每次跑一个数据集都需要这样操作一次，我的感觉是跑完一个模型之后他不会及时释放内存。

**Comment by chenxiaozeng** [comment]
您好，感谢您的建议！我们已反馈AI Studio同学，暂时建议您重启环境后运行。相关讨论 #578
