### ISSUE TITLE
[Question]: 无监督文档问答demo时，生成的答案都是一个字

### ISSUE THREAD

**Issue by zouchl** [PaddlePaddle/PaddleNLP#5891]
### 请提出你的问题

问题：张三是什么专业

答案：列

问题：张三专攻什么专业

答案：列

日志里warning提示
pipelines.pipelines.base -  YAML version (1.1.0) does not match with pipelines version (0.5.2). Issues may occur during loading. To fix this warning, save again this pipeline with the current pipelines version using Pipeline.save_to_yaml(), or downgrade to pipelines version 0.5.2.
请教是什么原因，与yaml文件是否有关

**Comment by w5688414** [comment]
日志的warning跟这个没关系，请问使用的pipelines的什么应用呢？

**Comment by Stupid-Ai** [comment]
无监督检索式问答系统
这个还有我想试试案例里的source_file.txt文件也是编码后的，压根用不了。根本看不出什么格式
