### ISSUE TITLE
[Question]: UIE 小样本微调，是否需要负样本？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#5899]
### 请提出你的问题

小样本微调，是否需要负样本？

**Comment by linjieccc** [comment]
在UIE训练定制中，正负样本的比例十分重要，如果数据集只有正样本容易造成错误召回，而如果负样本所占比例过多也可能造成模型不召回，因此数据集构造过程中需要控制好正负样本的比例。

**Comment by cqray1990** [comment]
> 正负样本是再doccano.py自动生成的，还是要自己手动去标呢


> 在UIE训练定制中，正负样本的比例十分重要，如果数据集只有正样本容易造成错误召回，而如果负样本所占比例过多也可能造成模型不召回，因此数据集构造过程中需要控制好正负样本的比例。

> 正负样本是再doccano.py自动生成的，还是要自己手动去标呢
@linjieccc
