### ISSUE TITLE
[Question]:  定制的实体的标注

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#5905]
### 请提出你的问题

买方（以下简称甲方）：XX有限公司
卖方（以下简称乙方）：XX有限公司

甲方：XX有限公司
乙方：XX有限公司

定制的抽取分出甲方和乙方，上面两种情况相同，请问编注的时候  “买方（以下简称甲方）：XX有限公司” 和“甲方：XX有限公司”全都标为甲方公司名？

**Comment by linjieccc** [comment]
可以尝试通过细粒度的实体标签进行区分或者关系抽取的方式来标注微调
