### ISSUE TITLE
[Bug]: 训练脚本中datasets模块import顺序问题

### ISSUE THREAD

**Issue by USTCKAY** [PaddlePaddle/PaddleNLP#5916]
### 软件环境

```Markdown
- paddlepaddle:开发版0.0.0
- paddlepaddle-gpu: 
- paddlenlp: 最新的develop版
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在运行bert多卡微调训练任务时hang在数据集下载部分，单卡运行该任务时没出现这种情况
```

### 稳定复现步骤 & 代码

运行如下训练指令，就会在数据集下载部分hang住：
`python -m paddle.distributed.launch --npus "0,1" run_glue_trainer.py \
    --model_name_or_path bert-base-uncased \
    --task_name SST2 \
    --max_seq_length 128 \
    --per_device_train_batch_size 32   \
    --per_device_eval_batch_size 32   \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --logging_steps 1 \
    --eval_steps 500 \
    --save_steps 500 \
    --output_dir ./tmp/ \
    --device npu \
    --fp16 False\
    --do_train \
    --do_eva`
训练日志中有抛出如下WARNING：
![0db3af233e2580e135a678b371f9cb2c](https://github.com/PaddlePaddle/PaddleNLP/assets/50285351/f0969ad4-9b40-4727-b1e1-e9943647e2e0)
似乎run_glue_trainer.py中导入datasets模块的顺序有点问题。我将其中的`from datasets import load_dataset`放到导入paddlenlp模块后面训练能够正常进行。
另外我搜索了一下paddlenlp的代码，似乎是因为代码格式化工具的作用，几乎所有的训练脚本中datasets模块都在paddlenlp之前导入。烦请套件同学评估一下是否需要调整datasets和paddlenlp的导入顺序，多谢了！

**Comment by JunnYu** [comment]
收到该问题，我们这里先本地复现一下该问题，之后再给你反馈信息。

**Comment by JunnYu** [comment]
你好，我这里本地是能正常跑起来，没有卡住
```sh
python -m paddle.distributed.launch --gpus "4,5" run_glue_trainer.py --model_name_or_path bert-base-uncased --task_name SST2 --max_seq_length 128 --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --learning_rate 2e-5 --num_train_epochs 3 --logging_steps 1 --eval_steps 500 --save_steps 500 --output_dir ./tmp/ --device gpu --do_train --do_eval
```
<img width="965" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/2942b6ea-6833-49ab-97a1-515d2e1bd4c8">

**Comment by USTCKAY** [comment]
> 你好，我这里本地是能正常跑起来，没有卡住
> 
> ```shell
> python -m paddle.distributed.launch --gpus "4,5" run_glue_trainer.py --model_name_or_path bert-base-uncased --task_name SST2 --max_seq_length 128 --per_device_train_batch_size 32 --per_device_eval_batch_size 32 --learning_rate 2e-5 --num_train_epochs 3 --logging_steps 1 --eval_steps 500 --save_steps 500 --output_dir ./tmp/ --device gpu --do_train --do_eval
> ```
> 
> <img alt="image" width="965" src="https://user-images.githubusercontent.com/50394665/238357752-2942b6ea-6833-49ab-97a1-515d2e1bd4c8.png">

请问一下是在厂内环境测的吗？如果是的话那么这个问题可能是偶发性的了，并且我单卡运行时也没出现这个问题。那么就没有必要调整datasets和paddlenlp的导入顺序了是吧？

**Comment by JunnYu** [comment]
是的，在开发机的环境下运行的；感觉你出现hang的原因可能是网络或者啥卡住、本地缓存存在但没下载完成之类的。

**Comment by USTCKAY** [comment]
> 是的，在开发机的环境下运行的；感觉你出现hang的原因可能是网络或者啥卡住、本地缓存存在但没下载完成之类的。

好的，多谢解答，那我关闭issue了
