### ISSUE TITLE
[Question]: model_zoo/gpt-3/external_ops 中算子导入报错

### ISSUE THREAD

**Issue by Zhao-Yian** [PaddlePaddle/PaddleNLP#5917]
### 请提出你的问题

执行 python setup.py build 之后，算子编译失败：
<img width="1118" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/77494834/a6389ead-120e-4a13-bc77-9a535080c75d">

此时导入显示找不到module：
<img width="827" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/77494834/d287fa6c-636a-45cc-ab87-a344cbb57083">

再次执行  python setup.py build develop 之后，fused_ln编译成功：
<img width="1115" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/77494834/87b8c5f6-f838-4c80-84ff-8fbcde5d87d9">

但是此时导入fused_ln仍然报错，并且不再显示找不到module：
<img width="1113" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/77494834/3011a0ee-54d7-4be4-8d05-445ba985ad8b">

对于fast_ln编译始终报错，提示找不到<cuda_bf16.h>文件

**Comment by JunnYu** [comment]
你好，请问你的 环境是什么呢？CUDA版本、GPU、Paddle版本

**Comment by Zhao-Yian** [comment]
CUDA：11.0
GPU：Tesla V100
paddle2.4.1

**Comment by JunnYu** [comment]
你好，bf16需要在3090、4090、A100这些系列的显卡上才能正常运行

**Comment by Zhao-Yian** [comment]
好的，我在A100上编译一下试试

**Comment by Zhao-Yian** [comment]
fused_ln 编译成功无法导入的问题能看出来是什么原因吗？

**Comment by JunnYu** [comment]
感觉可能是环境问题，我这里V100编译成功。
你可以更新一下CUDA版本吗，我这里用的CUDA 11.7
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/da27c096-77d6-4178-b750-a4f261e0766b)
