### ISSUE TITLE
[Bug]: label_studio 标注数据，参数负样本比例10，发现相同prompt的result_list结果不一样

### ISSUE THREAD

**Issue by houhailun** [PaddlePaddle/PaddleNLP#5920]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu:2.4.2 
- paddlenlp: 2.4.9
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
对uie模型进行few-shot,使用label_studio.py脚本进行数据格式转换，设置参数负样本比例10，转换后的数据中，发现相同prompt的result_list结果不一样。

问题：
prompt表现是：商品的观点词

{"content": "消威士75%酒精消毒液2.5l家医用75度乙醇皮 消威士75%酒精消毒液2.5l家医用75度乙醇皮肤物品杀菌清洁大桶装,现货.都是新鲜日期,有效期两年,消威士皮肤物品消毒的保障,话
不多说您觉得合适,咱就交易,疫情当下做消毒是对家庭最基本的保护措施.由于羊人增多,使用比较多,库存没多少了,转给应急的朋友们可随时自取.", "result_list": [], "prompt": "消威士75
%酒精消毒液2.5l家医用75度乙醇皮的观点词"}

{"content": "消威士75%酒精消毒液2.5l家医用75度乙醇皮 消威士75%酒精消毒液2.5l家医用75度乙醇皮肤物品杀菌清洁大桶装,现货.都是新鲜日期,有效期两年,消威士皮肤物品消毒的保障,话
不多说您觉得合适,咱就交易,疫情当下做消毒是对家庭最基本的保护措施.由于羊人增多,使用比较多,库存没多少了,转给应急的朋友们可随时自取.", "result_list": [{"text": "有效期两年",
 "start": 70, "end": 75}, {"text": "消威士皮肤物品消毒的保障", "start": 76, "end": 88}, {"text": "疫情当下做消毒是对家庭最基本的保护措施", "start": 104, "end": 123}], "pr
ompt": "消威士75%酒精消毒液2.5l家医用75度乙醇皮的观点词"}
```

### 稳定复现步骤 & 代码

执行命令：
python label_studio.py     --label_studio_file  tmp     --task_type "ext"     --save_dir ./data     --splits 1 0.0 0.0     --prompt_prefix "情感倾向"     --options "正 向" "负向" "中"    --separator "##" --negative_ratio 10

tmp文件数据：
[{"id": 936, "cancelled_annotations": 0, "comment_count": 0, "inner_id": 1, "total_annotations": 1, "data": {"text": "消威士75%酒精消毒液2.5l家医用75度乙醇皮 消威士75%酒
精消毒液2.5l家医用75度乙醇皮肤物品杀菌清洁大桶装,现货.都是新鲜日期,有效期两年,消威士皮肤物品消毒的保障,话不多说您觉得合适,咱就交易,疫情当下做消毒是对家庭最基本的保护措施.
由于羊人增多,使用比较多,库存没多少了,转给应急的朋友们可随时自取."}, "annotations": [{"id": 1, "completed_by": 1, "ground_truth": false, "parent_annotation": null, "parent
_prediction": null, "prediction": {}, "project": 2, "result_count": 0, "task": 2, "was_cancelled": false, "result": [{"value": {"start": 0, "end": 3, "text": "消威士", "l
abels": ["品牌"]}, "id": "V8QxsKh6Wn", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}, {"value": {"start": 0, "end": 24, "text": "消威士75
%酒精消毒液2.5l家医用75度乙醇皮", "labels": ["商品名"]}, "id": "WiXUVp8V4D", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}, {"value": {"s
tart": 70, "end": 75, "text": "有效期两年", "labels": ["观点词"]}, "id": "7TW9BibGqT", "from_name": "label", "to_name": "text", "type": "labels", "origin":"manual"}, {"di
rection": "right", "from_id": "WiXUVp8V4D", "labels": ["品牌"], "to_id": "V8QxsKh6Wn", "type": "relation"}, {"direction": "right", "from_id": "WiXUVp8V4D", "labels": ["观
点词"], "to_id": "7TW9BibGqT", "type": "relation"}, {"value": {"start": 0, "end": 3, "text": "消威士", "labels": ["品牌"]}, "id": "SHCAHn76H7", "from_name": "label", "to_
name": "text", "type": "labels", "origin": "manual"}, {"value": {"start": 0, "end": 24, "text": "消威士75%酒精消毒液2.5l家医用75度乙醇皮", "labels": ["商品名"]}, "id": "R
hCWDG9YeJ", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}, {"value": {"start": 76, "end": 88, "text": "消威士皮肤物品消毒的保障", "labels
": ["观点词"]}, "id": "wMtr77bJyH", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}, {"direction": "right", "from_id": "RhCWDG9YeJ", "label
s": ["品牌"], "to_id": "SHCAHn76H7", "type": "relation"}, {"direction": "right", "from_id": "RhCWDG9YeJ", "labels": ["观点词"], "to_id": "wMtr77bJyH", "type": "relation"}
, {"value": {"start": 0, "end": 3, "text": "消威士", "labels": ["品牌"]}, "id": "gVWsWD3CtY", "from_name": "label", "to_name": "text", "type": "labels","origin": "manual"
}, {"value": {"start": 0, "end": 24, "text": "消威士75%酒精消毒液2.5l家医用75度乙醇皮", "labels": ["商品名"]}, "id": "2hIi1Q4rqT", "from_name": "label", "to_name": "text"
, "type": "labels", "origin": "manual"}, {"value": {"start": 104, "end": 123, "text": "疫情当下做消毒是对家庭最基本的保护措施", "labels": ["观点词"]},"id": "h9i1zccguI",
"from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}, {"direction": "right", "from_id": "2hIi1Q4rqT", "labels": ["品牌"], "to_id": "gVWsWD3CtY",
 "type": "relation"}, {"direction": "right", "from_id": "2hIi1Q4rqT", "labels": ["观点词"], "to_id": "h9i1zccguI", "type": "relation"}]}]}]

**Comment by JunnYu** [comment]
你好，这个参数负样本比例10应该是有随机因素的，然后会导致输出的result list结果不同的
