### ISSUE TITLE
[Question]: 使用ERINE-3模型意图识别杂乱文字也能识别出一条

### ISSUE THREAD

**Issue by TherChenYang** [PaddlePaddle/PaddleNLP#5931]
### 请提出你的问题

使用ernie-3.0-medium-zh进行训练，共有15个分类，使用了将近15000数据量进行训练，训练完成后，发现正常拟合还可以，但是输入杂乱无章的文字也能预测出意图，大佬们能帮忙分析下，是训练的时候出现了问题还是哪里的操作不对？
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/124348939/9360f72c-7977-4776-8669-c1cbfed40ae2)

**Comment by w5688414** [comment]
这是bad case，建议标注一部分数据优化一下
