### ISSUE TITLE
采用uie-x进行关键信息抽取时，通过set_schema方法重置抽取目标报错

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleNLP#5935]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/67177370/e5e3cf2a-d9bf-49ca-bc16-61e0f87c9940)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/67177370/0fb4e31d-0419-4ec9-b26f-b5c2a806e1b4)

**Comment by linjieccc** [comment]
set_schema方法用来动态修改实例my_ie的schema设置，可以尝试修改下代码：

```python
my_ie.set_schema(schema)

doc_path = r"8.jpg"
results = my_ie({"doc": doc_path})
```
