### ISSUE TITLE
[Question]: UIE-X使用表格识别后遇到的问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#5940]
### 请提出你的问题

paddlepaddle-gpu==2.4.2
paddlenlp==2.5.2

<h1>使用表格识别发现自己怎么也调不好我的数据集有476张</h1>

- <h1>这是使用默认的5倍负例训练的，发现不理想有些没有抽取到</h1>
![ocr_result2 (9)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/8f293859-78b9-4205-a700-9fb1b7d84b8f)
- <h1>于是我采取降低负例到0，1，2，3，4倍负例，虽然抽取到更多了，可还是有遗漏的，求教是不是用了表格识别容易过拟合</h1>
![ocr_result2 (12)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/4d9350a0-e5c5-42d0-a4f4-99b3f35280b1)
![ocr_result2 (13)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/db3e10cd-04f4-47f2-8f56-19975b0b17f9)
![ocr_result2 (11)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/228e191b-f6a8-4ba7-bd6e-c433bcbfacf7)
- <h1>这是我的版面分析所检测到区域</h1>
![ocr_result (10)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/85941e7e-462a-441f-bc09-28b96667fe05)

**Comment by linjieccc** [comment]
@1061302569 看起来坐标位置不是特别准确，可能会影响到uie-x训练数据构造，这个是定制训练后的表格识别模型吗

**Comment by 1061302569** [comment]
> @1061302569 看起来坐标位置不是特别准确，可能会影响到uie-x训练数据构造，这个是定制训练后的表格识别模型吗

<h1>是的，定制训练后表格识别模型，坐标不是很准可以检测到文字就没有很在意</h1>
- <h1>这是我标注的表格数据集，坐标偏移不知道怎么导致的</h1>

![WI2YM}VK45_)91)0(HJI1LW](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/a3d0dfaa-5170-479e-bb0b-006f06e133f1)
![}%73CQE3EZ67TWMP`P PN~T](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/9579f06b-0867-4520-a3d3-53884aa129ef)

**Comment by 1061302569** [comment]
@linjieccc  老师您好，我对版面分析做了重新调整现在坐标基本准确了
![ocr_result (11)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/caf3a7fd-4a54-454a-835a-ac863ecdf1f3)

现在还有一些漏检，训练的结果混乱 负例0到40倍多次测试，结果还是这样，不知道是什么原因导致的
![ocr_result2-Copy1 (1)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/1e2d1bcd-41bb-42a7-aa73-ba714940f934)
![ocr_result2 (31)](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/bda27dd6-7d76-44b1-ae76-e438277b5dfe)

**Comment by whisky-12** [comment]
您好 请问您的问题解决了嘛， 我这边使用实体抽取 文字都能检查的到， 但会出现前边几个字被过滤掉的问题， 
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/957c6ac8-13bb-4f4f-9484-2aafff54fcbc)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/2633c864-36f6-4879-9ba3-d4b971a4eea3)
