### ISSUE TITLE
[Question]: ernie-3.0-base-zh 预训练基于wudao数据

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/PaddleNLP#5942]
请问 ernie-3.0-base-zh 预训练基于 wudao 数据训练中
1.数据处理脚本和这里ernie-1.0的一致吗？
https://github.com/PaddlePaddle/PaddleNLP/blob/e6a9cee8e7445542be8463d01db90d0c1c873b89/model_zoo/ernie-1.0/preprocess/docs/WuDaoCorpusBase.md
2.请问有wudao 200G数据训练时长和精度可以参考吗？

```
python -u -m paddle.distributed.launch \
    --log_dir "output/trainer_log" \
    run_pretrain_trainer.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-3.0-base-zh" \
    --tokenizer_name_or_path "ernie-3.0-base-zh" \
    --input_dir "./data_ernie_3.0" \
    --output_dir "output/trainer_log" \
    --split 949,50,1 \
    --max_seq_length 512 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 32 \
    --fp16  \
    --fp16_opt_level "O2"  \
    --learning_rate 0.0001 \
    --min_learning_rate 0.00001 \
    --max_steps 2 \
    --save_steps 2\
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 1\
    --dataloader_num_workers 4 \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --do_train \
    --device "gpu"
```

**Comment by ZHUI** [comment]
1.数据处理脚本和这里ernie-1.0的一致吗？
对，注意切换tokenizer

2.请问有wudao 200G数据训练时长和精度可以参考吗？
两台A100 40G，两周左右，可以看 ernie-1.0-base-cw  ernie-1.0-large-cw的效果。

**Comment by tiandou-tangdou** [comment]
> 1.数据处理脚本和这里ernie-1.0的一致吗？ 对，注意切换tokenizer
> 
> 2.请问有wudao 200G数据训练时长和精度可以参考吗？ 两台A100 40G，两周左右，可以看 ernie-1.0-base-cw ernie-1.0-large-cw的效果。

tokenizer => ernie-3.0-base-zh
两台A100 40G => 两台机器 2 * 8 = 16张卡是吗？

**Comment by ZHUI** [comment]
对的

**Comment by BeingGod** [comment]
请问有ernie-3.0-base-zh 的在wudao 2G下数据训练时长的数据吗？
