### ISSUE TITLE
[Question]: ImportError: cannot import name 'ElectraConfig' from 'paddlenlp.transformers' 报错怎么办啊 paddlenlp版本是2.4.1

### ISSUE THREAD

**Issue by csd088** [PaddlePaddle/PaddleNLP#5944]
### 请提出你的问题

ImportError: cannot import name 'ElectraConfig' from 'paddlenlp.transformers' 报错怎么办啊 paddlenlp版本是2.4.1

**Comment by gongel** [comment]
升级版本看下哈

**Comment by csd088** [comment]
通过开发分支升级到最新版本，问题已解决，谢谢
















在 2023-05-18 17:45:49，"gongenlei" ***@***.***> 写道：

升级版本看下哈
