### ISSUE TITLE
[Question]: ernie-layout如何做的bbox归一化到0-1000？

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/PaddleNLP#5949]
### 请提出你的问题

基于ernie-layout想自定义训练模型，但是不知道标注原始图片的某个字的bbox如何做的preprocess，查看[代码](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/document/utils.py ) 没有发现有对bbox缩放,请问论文中提到的**all the coordinate values are normalized in the range [0, 1000].**这个功能在哪里实现的，只看到处理xfun数据里有，如果我的bbox超过了1000是如何处理的？

**Comment by guobayang** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/d3e67b98d43a63cdfdcf8deb49ada4c5f4058a3e/applications/document_intelligence/doc_vqa/Extraction/docvqa.py#L266

**Comment by aixuedegege** [comment]
感谢楼上回答
