### ISSUE TITLE
[PPDiffusers] 新增control_v11的ip2p和mlsd代码及权重

### ISSUE THREAD

**Issue by GoooHi** [PaddlePaddle/PaddleNLP#5950]
### 简要描述

1. 新增权重 control_v11e_sd15_ip2p 和 对应文件 gradio_ip2p2image.py
2. 新增权重 control_v11p_sd15_mlsd 和 对应文件 gradio_mlsd2image.py

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

https://github.com/PaddlePaddle/PaddleNLP/tree/36591ab297dfa45d89255aa6e14988940ccea299/ppdiffusers/examples/controlnet

**Comment by JunnYu** [comment]
感谢你的贡献。这是该issue的相关PR，https://github.com/PaddlePaddle/PaddleNLP/pull/5951
