### ISSUE TITLE
[Question]: 在分布式训练的时候，单机多卡加载模型，有点太费物理内存了。

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#5958]
### 请提出你的问题

启动几个显卡，一个文件就加载几次，后续可以优化么

**Comment by linjieccc** [comment]
@liuzhipengchd 请问具体跑的是哪个任务呢？可以尝试下例如模型并行、流水线并行等分布式策略来优化显存占用

可以看看这个例子：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/llama#llama-inplementation
