### ISSUE TITLE
bert 静态图训练， finetune 运行pretrained模型

### ISSUE THREAD

**Issue by ykkk2333** [PaddlePaddle/PaddleNLP#596]
这边在执行bert静态图训练时，在run_glue.py脚本中使用model.from_pretrained接口来载入pretrained模型时，精度无法像动态图相同操作时那样收敛，使用100globle steps的pretrain模型跑finetune的精度是0.8左右，但是用10000 global steps及更多iter的pretrain模型跑finetune的话精度会掉到0.5，想问下glue的脚本如何正确的载入pretrain 模型，或者有没有别的用pretrained可以跑收敛的办法。

paddlegpu版本 = 2.1.0.post112
paddlenlp 2.0.1

机器：Nvidia A100-PCIE-40GB
Driver：460.71.01
CUDA version: 11.2

系统：Linux 18.04.1-Ubuntu 
x86_64

**Comment by ZeyuChen** [comment]
可否提供更多的脚本信息？ @ykkk2333

**Comment by ykkk2333** [comment]
@ZeyuChen 
下面是运行finetune的脚本
model_1000是pretrained后保存的模型

export CUDA_VISIBLE_DEVICES=0
  3 export TASK_NAME=SST-2
  4
  5 python3.7 -u ./run_glue.py \
  6     --model_type bert \
  7     --task_name $TASK_NAME \
  8     --max_seq_length 128 \
  9     --batch_size 64   \
 10     --learning_rate 2e-5 \
 11     --num_train_epochs 3 \
 12     --logging_steps 100 \
 13     --save_steps 500 \
 14     --use_amp True \
 15     --use_pure_fp16 True \
 16     --output_dir ./tmp/$TASK_NAME/ \
 17     --model_name_or_path fp16_out/model_1000 \

**Comment by guoshengCS** [comment]
您那边试下静态图下的[run_glue.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/static/run_glue.py#L403)这里按照下面改下：

```python
# paddle.static.set_program_state(main_program, reset_state_dict)

# 将model_path设置为本地保存的模型文件名
paddle.static.load(main_program, model_path="tmp/model_500/model_state.pdparams")

```

原始的静态图代码加载本地的模型好像确实会有些问题，这个我们尽快确认修复下。

**Comment by guoshengCS** [comment]
> 您那边试下静态图下的run_glue.py这里按照下面改下

您上面那个启动命令中的 `--model_name_or_path`还要使用原先的内置模型的名字，直接在上面`paddle.static.load`这里使用您本地保存的模型文件。当前静态图脚本中也不是使用的和`from_pretrained`对应的`save_pretrained`来保存的，直接`from_pretrained`传本地模型可能有些问题。也请 @wawltor  帮忙确认下这里
