### ISSUE TITLE
[Question]: chatglm微调遇到的问题

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#5965]
### 请提出你的问题

使用chatglm 里面默认的脚本，采用lora微调
1、日志打印，learning_rate 一直是0 ，这个是什么问题，怎么处理
![WeChatd873e18fb0630b5e09c9ab5a2515b9e5](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/c6f44027-cef1-4b08-9613-02d1411a79a1)

2、[2023-05-19 11:24:57,508] [ WARNING] - optimizer not run, scale_before: 16384.0, scale_after: 16384.0
这个是什么意思？

希望有大佬可以解释

**Comment by lugimzzz** [comment]
看着不太正常，你用的develop最新代码吗，运行命令是什么

**Comment by liuzhipengchd** [comment]
> 看着不太正常，你用的develop最新代码吗，运行命令是什么

用的是最新的代码

python -m paddle.distributed.launch --gpus "0,1,2,3" finetune_generation.py \
--model_name_or_path /root/chatglm \
--task_name_or_path /root/data \
--max_steps 3000 \
--learning_rate 3e-4 \
--warmup_steps 20 \
--eval_steps 100 \
--logging_steps 1 \
--save_steps 1000 \
--save_total_limit 1 \
--output_dir ./checkpoints/chatglm-6b \
--src_length 106 \
--tgt_length 608 \
--per_device_eval_batch_size 2 \
--per_device_train_batch_size 2 \
--gradient_accumulation_steps 12 \
--lr_scheduler_type linear \
--fp16 \
--fp16_opt_level O2 \
--recompute True \
--do_train \
--do_eval \
--lora True \
--tensor_parallel_degree 4 \
--do_generation True


data的格式是{"content" : '' , "summary"}

**Comment by lugimzzz** [comment]
你先看一下单卡跑会不会出现这个问题，我这块也复现一下多卡lora是否有相似的问题

**Comment by liuzhipengchd** [comment]
> 你先看一下单卡跑会不会出现这个问题，我这块也复现一下多卡lora是否有相似的问题

单卡配置不够呀，所以只能多卡lora 微调

**Comment by liuzhipengchd** [comment]
单卡 训练，依然出现 lr为0，loss是nan
![WeChat94b4723610fc3d54d875127b2109467a](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/640ab311-a151-43e5-a5cb-9ccd646782cf)

**Comment by liuzhipengchd** [comment]
> 你先看一下单卡跑会不会出现这个问题，我这块也复现一下多卡lora是否有相似的问题

大佬，单卡依然有问题，使用的是最新代码

**Comment by lugimzzz** [comment]
我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本

**Comment by liuzhipengchd** [comment]
> 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本

我的cuda版本是11.3，paddlepaddle-gpu nightly 是用11.2吗

**Comment by liuzhipengchd** [comment]
> 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本

还有一个问题，使用的是paddlepaddle-gpu nightly

在微调的时候，显存会不断增加，最后到oom，（使用的是A100，80g的卡）

**Comment by liuzhipengchd** [comment]
> 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本

还有一个问题，就是全参数调的话，需要多大的显存。我这是一个A100-80g全参训练，就直接oom了

**Comment by lugimzzz** [comment]
> > 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本
> 
> 我的cuda版本是11.3，paddlepaddle-gpu nightly 是用11.2吗

嗯

**Comment by lugimzzz** [comment]
> > 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本
> 
> 还有一个问题，就是全参数调的话，需要多大的显存。我这是一个A100-80g全参训练，就直接oom了

我们一般使用4卡进行sft，lora用单卡足够了。

**Comment by xieyu0214** [comment]
@lugimzzz 
[2023-05-24 10:08:42,855] [ WARNING] - optimizer not run, scale_before: 32768.0, scale_after: 32768.0
Found inf or nan, current scale is: 32768.0, decrease to: 32768.0*0.5
[2023-05-24 10:08:43,182] [ WARNING] - optimizer not run, scale_before: 32768.0, scale_after: 16384.0
[2023-05-24 10:08:43,506] [ WARNING] - optimizer not run, scale_before: 16384.0, scale_after: 16384.0
Found inf or nan, current scale is: 16384.0, decrease to:

训练过程中，一致报这个 warning，请问是有什么问题？怎么解决呢

**Comment by liuzhipengchd** [comment]
> > > 我这边复现不出这个问题，你用的paddle版本是什么，建议用paddlepaddle-gpu nightly版本
> > 
> > 
> > 还有一个问题，就是全参数调的话，需要多大的显存。我这是一个A100-80g全参训练，就直接oom了
> 
> 我们一般使用4卡进行sft，lora用单卡足够了。

@lugimzzz 

遇到一个问题，分布式训练好lora参数，进行predict ，与合并之后的推理的结果不一致。

合并参数，输出的结果
python -m paddle.distributed.launch --gpus 0,1 predict_generation.py \
    --model_name_or_path /mnt/afs/chatglm --lora_path  ./checkpoints/chatglm-6b/checkpoint-3500/  --src_length 106 --tgt_length 608 --merge_tensor_parallel_path  ./checkpoints/chatglm-merged

![WeChat8afe492f951cd6e5a3b3aadeec008091](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/fb3da06a-caa9-4bc9-96aa-22235dcb97da)



使用合并的模型
python  predict_generation.py \
    --model_name_or_path /mnt/afs/chatglm --lora_path  ./checkpoints/chatglm-merged  --src_length 106 --tgt_length 608 

![WeChat0a1a5eecea4d780b4d98a73758410180](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/ce9bf64b-2b36-4bb9-9016-1332a78f47fb)



然后发现 lora_A的参数不一样，但是合并的时候，只选择了tp0的参数


![WeChat6acf45e9108fbe2d8c8b44d102e9fa1c](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/dbb8e9cc-f139-4aac-b78d-ee188fc22279)


合并之后的lora_A参数


![WeChate14ca9d1ccbcf59449a697cba6e7fe8a](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/d309ab17-56c0-49bc-bcec-86095f0ca6df)

**Comment by xieyu0214** [comment]
@liuzhipengchd 上面这个问题我会

python predict_generation.py
--model_name_or_path /mnt/afs/chatglm --lora_path ./checkpoints/chatglm-merged --src_length 106 --tgt_length 608

这个使用方法是错的，正确的是：python predict_generation.py
--model_name_or_path ./checkpoints/chatglm-merged --src_length 106 --tgt_length 608

合并之后的模型 是合并了lora参数和原chatglm参数，你看下合并后的模型的大小

**Comment by liuzhipengchd** [comment]
> python predict_generation.py
> --model_name_or_path ./checkpoints/chatglm-merged --src_length 106 --tgt_length 608

你这样不对呀。。这里合并是把lora和原chatglm参数合成了一个文件，但是加载时候还是要分开加载的。（他这里全合并有些不太友好，应该只把lora合并就可以了）

**Comment by xieyu0214** [comment]
> > python predict_generation.py
> > --model_name_or_path ./checkpoints/chatglm-merged --src_length 106 --tgt_length 608
> 
> 你这样不对呀。。这里合并是把lora和原chatglm参数合成了一个文件，但是加载时候还是要分开加载的。（他这里全合并有些不太友好，应该只把lora合并就可

在使用过程中，感觉这种合并到chatglm模型的方式更友好，因为多卡训练后，在推断时只需要单卡就行了。若是还是要分开加载，那就加载未合并的模型就行啊

**Comment by lugimzzz** [comment]
这块lora设计确实有问题导致多卡情况下lora_A在不同卡上权重不共享，这块问题我们正在修复，目前这种情况只能几卡训练几卡推理。

**Comment by liuzhipengchd** [comment]
> 这块lora设计确实有问题导致多卡情况下lora_A在不同卡上权重不共享，这块问题我们正在修复，目前这种情况只能几卡训练几卡推理。

大佬，有什么解决方案吗？是训练策略的时候，数据共享问题？？
或者提供点思路，我也看看，能不能解决

**Comment by sijunhe** [comment]
@liuzhipengchd 您好，非常感谢您帮我们排查出这个分布式不一致的问题，这个对我们帮助很大！这个问题的根本原因是我们在初始化lora_A矩阵的时候没有对齐，导致后续的lora_A会一直不一样，这个问题已经在 #6016 中被fix了
