### ISSUE TITLE
[Question]: label-studio标注，跨行标注

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleNLP#5968]
### 请提出你的问题

对于这种跨行实体如何标注
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/67177370/dec31719-960e-4346-8854-863a34516eca)

**Comment by linjieccc** [comment]
@LJY6356 你好，UIE-X当前还不支持这种形式的跨行标注
