### ISSUE TITLE
UIE 模型版本请教

### ISSUE THREAD

**Issue by DeqianBai** [PaddlePaddle/PaddleNLP#5969]
### 问题描述

Yaojie Lu等人在ACL-2022 的论文中提出了通用信息抽取统一框架UIE，在这篇论文中，UIE的训练是先用 T5-v1.1-base 和T5-v1.1-large 初始化模型，然后用论文中提到的三种类型的数据集进行进一步的预训练，最后在下游特定任务上进行微调使用；

而在`PaddleNLP/model_zoo/uie` 里，则是这样描述的：
PaddleNLP借鉴该论文的方法，基于ERNIE 3.0知识增强预训练模型，训练并开源了首个中文通用信息抽取模型UIE。
但是PaddleNLP具体是怎么借鉴的，怎么训练的等等细节并没有提到，关于训练相关的细节能不能详细解释一下；
我能不能这样理解：只是把初始化模型更换成了ERNIE 3.0知识增强预训练模型，其他的都和原论文里一样？

**Comment by shtdbb** [comment]
UIE的图是一个抽取式模型，一个做实体开始索引的预测，一个做结束索引的预测，差别还蛮大的，一个生成式一个抽取式
