### ISSUE TITLE
[Question]: chatglm如何使用流式输出回答问题

### ISSUE THREAD

**Issue by Chinesenovels** [PaddlePaddle/PaddleNLP#5977]
### 请提出你的问题

chatglm如何使用流式输出回答问题，而不是全部回答完输出
prompt = tokenizer.prepare_query_for_chat(
    query="晚上睡不着应该怎么办", history=[("你好", "你好👋!我是人工智能助手 ChatGLM-6B,很高兴见到你,欢迎问我任何问题。")]
)
print(prompt)
inputs = tokenizer(prompt, return_tensors="pd")
outputs = model.generate(**inputs, max_length=2048)

**Comment by gongel** [comment]
你好，我们内部也正在开发相关逻辑。

**Comment by w5688414** [comment]
在解码的时候，编解码边输出即可。以greedy search，只需要在https://github.com/PaddlePaddle/PaddleNLP/blob/3a62bf0abab95c38df7d2a8757013289fff9a176/paddlenlp/transformers/generation_utils.py#LL1064C46-L1064C46

加入yield 把每次解码的token输出即可。
