### ISSUE TITLE
uie实体抽取支持自定义词表嘛

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/PaddleNLP#5978]
### Feature request

uie实体抽取支持自定义词表嘛

### Motivation

uie实体抽取支持自定义词表嘛

### Your contribution

uie实体抽取支持自定义词表嘛

**Comment by linjieccc** [comment]
方便描述下具体的需求么

**Comment by hitzhu** [comment]
在实体抽取任务中，是否可以自定义词表，词表中的内容是一些确定的实体和实体类型，相当于告诉模型一些命名实体的先验知识，对于词表中的实体，当在文本中出现时，一定能够抽取出来

**Comment by linjieccc** [comment]
这个目前还不支持哈

**Comment by invokerbyxv** [comment]
可以用label studio自己标注点数据finetune，亲测效果还可以。
