### ISSUE TITLE
ErnieGramTokenizer tokenizer词表不对应问题 [UNK]对应的id无法转为[UNK]

### ISSUE THREAD

**Issue by BFJL** [PaddlePaddle/PaddleNLP#599]
![image](https://user-images.githubusercontent.com/46952203/122730693-16492680-d2ad-11eb-94b7-a459567b044d.png)
[UNK]对应的id 18017 无法转为[UNK]

**Comment by BFJL** [comment]
今天看了一下，发现问题出在ernie-gram-zh的vocab.txt上，该vocab.txt文件存在两个 美元$符号。索引从1开始，分别在12085行，18006行。 由于两个相同的字符，构建token_to_idx字典时，token的最大idx，便会比idx_to_token列表的长度大1位，于是抛出错误。

**Comment by BFJL** [comment]
该vocab.txt两个字符的重复，导致第二个字符后的的idx_to_token与token_to_idx全部错位，考虑提升代码的鲁棒性，根据token_to_idx建立idx_to_token字典是否更好?

**Comment by Steffy-zxf** [comment]
@BFJL 您好，感谢反馈！您是否方便提PR修复该问题呢？

**Comment by BFJL** [comment]
> @BFJL 您好，感谢反馈！您是否方便提PR修复该问题呢？

ok 已经提交PR [https://github.com/PaddlePaddle/PaddleNLP/pull/617](url)
