### ISSUE TITLE
[Bug]: 调用 llama.LlamaDecoderLayer 显存溢出

### ISSUE THREAD

**Issue by wjm202** [PaddlePaddle/PaddleNLP#5990]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu:  2.4.2.post117
- paddlenlp: 2.5.2.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
调用 llama.LlamaDecoderLayer
在load llm 阶段会有25g的显存增长导致显存溢出，同等情况 调用huggingface transformer llama 不会有显存增长
```

### 稳定复现步骤 & 代码

config={
  "_name_or_path": "./pyllama_data/output/7B",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "lm_shift_labels": True,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "paddlenlp_version": None,
  "rms_norm_eps": 1e-06,
  "tensor_parallel_output": True,
  "tie_word_embeddings": False,
  "transformers_version": "4.28.0.dev0",
  "use_flash_attention": False,
  "use_recompute": False,
  "vocab_size": 32001
}
import paddle
from paddlenlp.transformers.llama.modeling import LlamaDecoderLayer
from paddlenlp.transformers.llama.configuration import LlamaConfig
config=LlamaConfig(config)
layers=paddle.nn.LayerList(sublayers=[LlamaDecoderLayer(config) for _ in range(32)])

![e791eb4f8531421c01c27460d80ad0a8](https://github.com/PaddlePaddle/PaddleNLP/assets/97875990/407f5eb5-909b-4b8d-b898-d92778b48baa)

**Comment by linjieccc** [comment]
@wjm202 可以试试加一个``paddle.LazyGuard()``的context manager，这样可以延迟对layer权重进行延迟初始化，在实例模型后再通过`set_state_dict`将layer权重以numpy array的形式传入。

如果是通过from_pretrained接口来调用，则直接可以通过`load_state_as_np=True`来控制加载方式

示例：

```python
model = LlamaModel.from_pretrained("facebook/llama-7b", load_state_as_np=True)
```
