### ISSUE TITLE
[Question]: 智能问答和FAQ的区别

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#5996]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50852027/f972d3f5-e80a-4572-a719-454a038bd082)
请问这两个有什么区别呢？详细的模型介绍在哪里呀？

**Comment by w5688414** [comment]
FAQ问答属于QQ匹配，本质上是一个检索问题，只需要匹配库里面的问题，返回答案即可；而抽取式智能问答本质上是阅读理解+检索问题，抽取式智能问答难度更大一点。

**Comment by seetimee** [comment]
> FAQ问答属于QQ匹配，本质上是一个检索问题，只需要匹配库里面的问题，返回答案即可；而抽取式智能问答本质上是阅读理解+检索问题，抽取式智能问答难度更大一点。

感谢
