### ISSUE TITLE
[Bug]: 训练时使用EMA造成内存泄露

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/PaddleNLP#6003]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.4.0
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
1、训练过程使用EMA，内存会不断增加，直到溢出。
2、如果在EMA的过程中将参数转化成numpy，则不会有内存泄露，但速度慢了无数倍，这显然不正常
3、我想应该需要pytorch中类似param.data的操作
```

### 稳定复现步骤 & 代码

一、正常使用EMA，内存泄露
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51204375/c8fd56ff-4d2c-4e8c-9398-d177345a7d12)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51204375/a4975728-e462-4038-8d4c-c708d2da96ea)

二、使用EMA时将参数转化为numpy，内存不会一直增加，但速度慢无数倍
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51204375/0fcb2cbb-4df0-4a17-ab89-55e19d8c14c3)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51204375/45dc67b5-a3c8-4138-a60a-827d8446d3d9)

三、复现代码
https://aistudio.baidu.com/aistudio/projectdetail/6232319?contributionType=1&sUid=581675&shared=1&ts=1684826633129
版本：EMA bug

**Comment by JunnYu** [comment]
update的时候缺少Paddle.no_grad

**Comment by xiaotingyun** [comment]
@JunnYu 有效！
