### ISSUE TITLE
[Question]: rocketqa-zh-dureader-query-encoder和rocketqa-zh-base-query-encoder模型有什么区别

### ISSUE THREAD

**Issue by gyl1993** [PaddlePaddle/PaddleNLP#6015]
### 请提出你的问题

rocketqa-zh-dureader-query-encoder和rocketqa-zh-base-query-encoder模型有什么区别，哪里有文档介绍这两个模型？

**Comment by w5688414** [comment]
rocketqa-zh-base-query-encoder是基于ERNIE 3.0训练的
rocketqa-zh-dureader-query-encoder 是基于ERNIE 1.0训练的

**Comment by gyl1993** [comment]
> rocketqa-zh-base-query-encoder是基于ERNIE 3.0训练的 rocketqa-zh-dureader-query-encoder 是基于ERNIE 1.0训练的

谢谢，有说明文档吗

**Comment by w5688414** [comment]
> > rocketqa-zh-base-query-encoder是基于ERNIE 3.0训练的 rocketqa-zh-dureader-query-encoder 是基于ERNIE 1.0训练的
> 
> 谢谢，有说明文档吗

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/benchmarks/README.md

**Comment by gyl1993** [comment]
> rocketqa-zh-base-query-encoder是基于ERNIE 3.0训练的 rocketqa-zh-dureader-query-encoder 是基于ERNIE 1.0训练的

判断两句话语义是否相同预训练模型用rocketqa-zh-base-query-encoder效果更好吧，有更好的预训练模型推荐吗？

**Comment by gyl1993** [comment]
rocketqa-zh-base-query-encoder训练用的RocketQA，还是RocketQAv2呢

**Comment by w5688414** [comment]
> 

RocketQA， 判断两句话是否语义相同可以用simBERT，RocketQA主要是用在搜索场景
