### ISSUE TITLE
dead code should be removed

### ISSUE THREAD

**Issue by jiaqianjing** [PaddlePaddle/PaddleNLP#602]
https://github.com/PaddlePaddle/PaddleNLP/blob/7048bf9dd8ce689bed803cfe6c1dd58ed56aa29d/paddlenlp/datasets/dataset.py#L129

This is the reason.
https://github.com/PaddlePaddle/PaddleNLP/blob/7048bf9dd8ce689bed803cfe6c1dd58ed56aa29d/paddlenlp/datasets/dataset.py#L534

**Comment by ZeyuChen** [comment]
It's hard to understand through this issues, is it possible to submit a PR? @jiaqianjing

**Comment by smallv0221** [comment]
Dead code removed, Thank you!
