### ISSUE TITLE
chatglm 采用lora 多卡微调，lora_A参数不一致问题未修复

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#6024]
### 请提出你的问题

采用2个卡微调，记录100轮之后的模型参数
![WeChat901eddbd7b307f851ac0cfcef0c3ddaa](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/0d1c9d1b-bedf-4987-a111-efe932917f39)

发现参数还是不一致

**Comment by liuzhipengchd** [comment]
@sijunhe 可以看下吗

**Comment by sijunhe** [comment]
> @sijunhe 可以看下吗

确实还是有点问题，我这两天看一下

**Comment by liuzhipengchd** [comment]
> > @sijunhe 可以看下吗
> 
> 确实还是有点问题，我这两天看一下

大佬，你昨天改的方式，还是在每个进程里面创建lora_A，并没有多节点共享。

**Comment by liuzhipengchd** [comment]
@sijunhe 大佬，可以再问一个问题吗。。chatglm提供的分布式推理的脚本，并不能在python的web框架里面使用。。如果我想提供服务，比如像transformer的
kwargs["max_memory"] = {i: max_gpu_memory for i in range(num_gpus)}
model = AutoModelForCausalLM.from_pretrained(
        model_path, low_cpu_mem_usage=True, **kwargs
    )，
这样我就可以把这个model提供web服务了。目前paddlenlp 有这种功能吗

**Comment by sijunhe** [comment]
@liuzhipengchd 您好，#6048 已修复多卡权重不一致问题，欢迎本地确认一下

**Comment by sijunhe** [comment]
> @sijunhe 大佬，可以再问一个问题吗。。chatglm提供的分布式推理的脚本，并不能在python的web框架里面使用。。如果我想提供服务，比如像transformer的 kwargs["max_memory"] = {i: max_gpu_memory for i in range(num_gpus)} model = AutoModelForCausalLM.from_pretrained( model_path, low_cpu_mem_usage=True, **kwargs )， 这样我就可以把这个model提供web服务了。目前paddlenlp 有这种功能吗

可以尝试通过`paddle.distributed.launch`来启动web服务

**Comment by liuzhipengchd** [comment]
@sijunhe 大佬，我采用 
python -m paddle.distributed.launch --gpus "0,1" predict_generation.py \
    --model_name_or_path  /mnt/afs/winning/oro/lzp/chatglm  这个方式启用了web 服务
![WeChat938387a311addc6f8e80a520c4af5047](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/cfafaa8e-05ef-47b9-a62b-ff56f900bd34)
正确的应该怎么启动？
