### ISSUE TITLE
[Question]: 如果是一整页的文档输入UIE进行实体抽取

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6029]
### 请提出你的问题

如果是一整页的文档输入UIE进行实体抽取，如何分割句子比较好呢，代码中推理使用了cut_chinese_sent，但是有的是没有标点符号，这样切分又会导致有的数据很长，又被切分为max_len=128,这在切分过程中又可能恰好把某个实体切分开，这怎么处理呢？

**Comment by aixuedegege** [comment]
学习一下，留个座位。个人觉得用滑窗方式比较好，重复的部分使用策略选择，比如概率最大的，投票最多的。

**Comment by cqray1990** [comment]
> 学习一下，留个座位。个人觉得用滑窗方式比较好，重复的部分使用策略选择，比如概率最大的，投票最多的。

用滑窗，效率咋办，这得滑几次？

**Comment by linjieccc** [comment]
长文档可以考虑滑窗的方式来提升抽取效果，ernie-layout提供了滑窗处理的例子可以参考下

**Comment by xxllp** [comment]
能具体说说吗，这块的策略
