### ISSUE TITLE
[Question]: 运行文档智能doc_vqa案例时，出现异常`TypeError: __init__() missing 1 required positional argument: 'num_classes'`

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleNLP#6034]
### 请提出你的问题

[Question]: 运行文档智能doc_vqa案例时，出现异常`TypeError: __init__() missing 1 required positional argument: 'num_classes'`

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34825635/501b423f-512c-434b-bbc5-4a206aecc660)

## 问题说明
按照[教程](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/document_intelligence/doc_vqa)，运行到**6. 跨模态阅读理解模块**时，按说明下载了预训练模型，然后运行脚本`bash run_train.sh`时出错。

* 检查了下载下来的base模型，发现config.json文件中缺少`num_classes`这个参数，手动添加了`num_classes:4`，然后尝试运行脚本依然报错，查看日志，打印的LayoutXLMConfig中，依然没有num_classes
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34825635/ce24e705-e740-4b7a-b4d9-83822d60f4e9)

* 考虑到应该是实例化模型时传参出错，尝试直接设置默认值

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34825635/5d2874a9-9616-4b1d-af88-f2d5282a0961)

然后出现了新的异常

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34825635/f9cc0caf-5f30-4734-b9ff-41c8587524ad)

**Comment by ZzyChris97** [comment]
环境忘记说了：
python.                             3.9.12
paddlenlp                         2.5.2.post0
paddleocr                         2.6
paddlepaddle-gpu          2.4.1.post112

**Comment by JunnYu** [comment]
@linjieccc https://github.com/PaddlePaddle/PaddleNLP/blob/dda4c60ef0bd774df040f963ef31d17c11982b1f/applications/document_intelligence/doc_vqa/Extraction/model.py#L144 这里没有升级pretrained config
