### ISSUE TITLE
Paddle ernie layout

### ISSUE THREAD

**Issue by ocrifydotnet** [PaddlePaddle/PaddleNLP#6038]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Why the paddle ernie layout base model work badly than the service in huggingface.co/paddlepaddle/ernie-layout
```

### 稳定复现步骤 & 代码

Why the paddle ernie layout base model work badly than the service in huggingface.co/paddlepaddle/ernie-layout

**Comment by linjieccc** [comment]
Hi @ocrifydotnet 

The model DocPrompt provided in HuggingFace has undergone secondary pre-training on a large-scale extraction &  question-answering dataset, building upon the ernie-layout pre-trained model.
