### ISSUE TITLE
[Bug]: UIE Slim 数据蒸馏下的SimpleServing 的服务化部署bug，无法预测结果，全为空。

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#6047]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp: pip install paddlenlp >= 2.4.4
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
不使用serving下：
from pprint import pprint
from paddlenlp import Taskflow
ie = Taskflow("information_extraction",model="uie-data-distill-gp", task_path="/home/aistudio/data_distill/checkpoint-mini/model_best") # Schema is fixed in closed-domain information extraction
pprint(ie("格鲁曼FF/SF战斗机，是美国海军装备的第一种可以收放起落架的舰载战斗机，也是格鲁曼战斗机同美国海军结缘70年的开始。"))
[{'武器名称': [{'end': 11,
            'probability': 0.99916863,
            'relations': {'产国': [{'end': 15,
                                  'probability': 0.99942076,
                                  'relations': {},
                                  'start': 13,
                                  'text': '美国'}],
                          '类型': [{'end': 11,
                                  'probability': 0.9989723,
                                  'relations': {},
                                  'start': 8,
                                  'text': '战斗机'}]},
            'start': 0,
            'text': '格鲁曼FF/SF战斗机'}]}]
结果正常：

```

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34392683/16c063a0-c3fb-4996-ba43-a236b9ebddcd)

使用后就无法预测结果。
为了避免是模型问题测试了，全部未标注文档抽取，serving方式一个都无法抽取，用时0.03s  正常情况为7s左右

### 稳定复现步骤 & 代码

官方给出链接稳定复现：

[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill)

[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/deploy/simple_serving](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/deploy/simple_serving)

也可以在AIStudio中稳定复现：
[https://aistudio.baidu.com/aistudio/projectdetail/6280910?contributionType=1&sUid=691158&shared=1&ts=1685436426932](https://aistudio.baidu.com/aistudio/projectdetail/6280910?contributionType=1&sUid=691158&shared=1&ts=1685436426932)

对了，提醒一下使用非数据蒸馏模型使用serving没有任何问题，码源中client.py有区别分别为：

```
data = {"data": {"text": texts}}

data = {'data': texts}
```

**Comment by linjieccc** [comment]
@dingidng 你好 我们尝试复现下这个问题

**Comment by tingaicompass** [comment]
> @dingidng 你好 我们尝试复现下这个问题

这个问题修复的情况如何呀

**Comment by linjieccc** [comment]
@dingidng 经排查是返回的数据类型问题，已PR修复~感谢反馈问题
