### ISSUE TITLE
此处不支持bfloat16

### ISSUE THREAD

**Issue by hwchen1** [PaddlePaddle/PaddleNLP#6052]
https://github.com/PaddlePaddle/PaddleNLP/blob/c8b47a699b5c2b538b7ab49bcb63e6ea2a844418/paddlenlp/transformers/generation_utils.py#L1118

**Comment by gongel** [comment]
能定位到是哪个算子吗？

**Comment by sijunhe** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/c8b47a699b5c2b538b7ab49bcb63e6ea2a844418/paddlenlp/transformers/generation_utils.py#L1118

麻烦发一下具体的报错信息，感谢
