### ISSUE TITLE
[Question]: ernie-3.0-base-zh 基于wudao 2G数据预训练

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleNLP#6054]
### 请提出你的问题

1. 请问有ernie-3.0-base-zh的wudao 2G预训练硬件配置信息吗？
2. 请问有ernie-3.0-base-zh的wudao 2G预训练训练时长的数据可以参考吗？

**Comment by w5688414** [comment]
您好，暂时没有相关的开源计划，欢迎开发者贡献。
