### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by sifuhr** [PaddlePaddle/PaddleNLP#6057]
### 请提出你的问题

paddle.distributed.launch  
python -m paddle.distributed.launch --log_dir log   ./src/train_ce.py    --use_cuda false --verbose true --do_train true --do_val false --do_test false --use_mix_precision false --train_data_size 40000  --batch_size 32 --init_pretraining_params checkpoints/base_model --train_set data/train.tsv --save_steps 1250 --validation_steps 1250 --checkpoints output --weight_decay  0.01 --warmup_proportion 0.0 --epoch 50 --max_seq_len 384 --for_cn true --vocab_path config/ernie_base_1.0_CN/vocab.txt --ernie_config_path config/ernie_base_1.0_CN/ernie_config.json --learning_rate 1e-5 --skip_steps 10 --num_iteration_per_drop_scope 1 --num_labels 2 --random_seed 1   
不采用paddle.distributed.launch  行吗？使用单节点怎么运行

**Comment by gongel** [comment]
same as #6058
