### ISSUE TITLE
PaddleNLP标签设置问题

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#606]
PaddleNLP标签设置，只能是从0依次开始。
窃以为，本身都是从文本读取，然后再排列的，没必要卡死文本读取从0开始，可以再Dataset里作转换，而不是直接读取label标签，然后来回映射。

**Comment by ZeyuChen** [comment]
什么任务呢？是否可以提供更多细节信息？@livingbody

**Comment by livingbody** [comment]
比如 有的分类，5 分类，1，2，3，4，5标签，我需要设置label的集合来映射，能不能自动映射，或者如同paddlex一样，生成label映射文件。

**Comment by livingbody** [comment]
比如： https://aistudio.baidu.com/aistudio/projectdetail/2109882
