### ISSUE TITLE
arm环境下推理速度巨慢[Question]: 

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/PaddleNLP#6065]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/55450821/3f60fb44-36cc-4b69-92e4-80b7d7c12bb4)
如图，在arm环境下运行demo需要二三十分钟才能出来结果，这正常嘛（cpu)

**Comment by linjieccc** [comment]
你好，请尝试下安装ARM架构对应的paddle版本 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/arm-compile.html
