### ISSUE TITLE
[Question]: 关于uie-senta数据格式问题

### ISSUE THREAD

**Issue by Bigwhitepear** [PaddlePaddle/PaddleNLP#6075]
### 请提出你的问题

请问在语句级情感分析uie-senta中的数据格式中，"result_list"中的“start”和“end”键代表什么

**Comment by linjieccc** [comment]
start end表示实体在文本中的起始及终止位置

**Comment by Bigwhitepear** [comment]
> 请问在语句级情感分析uie-senta中的数据格式中，"result_list"中的“start”和“end”键代表什么



> start end表示实体在文本中的起始及终止位置
你好，语句级情感分析应该没有实体，我看start，end都是负数是什么意思，了解吗？
