### ISSUE TITLE
[Question]: 多样本归类

### ISSUE THREAD

**Issue by yuxiaotongshenzhen** [PaddlePaddle/PaddleNLP#6078]
### 请提出你的问题

我有一百多个类别，想让短语或者信息准确的归类到正确的类别中，这些类别跨度差异很大；例如药品和疾病等等，大家认为这个任务是使用信息抽取UIX做会好一些，还是使用统一文本分类做会好一些？任务目标是将医疗数据库中的数据归类到正确的类别

**Comment by lugimzzz** [comment]
可以先做文本分类

**Comment by LemonNoel** [comment]
可以分析下数据。如果数据中有明确的代表实体可以用于分类，可以采用 UIE 提取后处理输出类别；如果没有明确实体指向，建议使用 UTC 进行分类。
