### ISSUE TITLE
[Question]: from paddlenlp import Taskflow 报错

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#6083]
### 请提出你的问题

我在aistudio gpu版直接用
> from paddlenlp import Taskflow 
报错,这是为啥啊
cannot import name 'Taskflow' from 'paddlenlp' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/__init__.py)

**Comment by lugimzzz** [comment]
更新一下最新paddlenlp版本，然后重启kernel

**Comment by seetimee** [comment]
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50852027/5161f2c2-21db-4962-b1e6-338840989ec1)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50852027/a6e026be-36f4-40e0-8932-33c0b08a76f2)

**Comment by seetimee** [comment]
> 更新一下最新paddlenlp版本，然后重启kernel

更新重启内核后报错如上
