### ISSUE TITLE
[Question]: 一个论文角色存在多个替换论元

### ISSUE THREAD

**Issue by prtj** [PaddlePaddle/PaddleNLP#6093]
### 请提出你的问题

请问下，一个论元角色只有一个论元，但这个论元在句子中有多个同义词，请问这种问题该怎么构造数据格式

**Comment by lugimzzz** [comment]
可以再展开详细说吗？举一个例子

**Comment by prtj** [comment]
> 可以再展开详细说吗？举一个例子

例如，"据美国国防官员1月3日透露，美国五角大楼将向海湾地区派出第二支航母打击群，....，五角大楼同意打断约翰•C•斯坦尼斯号航母战斗群的计划，"。这里有一个“部署”事件，”部署“事件的论元角色”主体“，既可以是前面的”美国五角大楼“，也可以是后面的“五角大楼”，请问这种该怎么构造prompt呢

**Comment by lugimzzz** [comment]
你的数据集任务是什么？是要用uie做信息抽取任务吗？

**Comment by prtj** [comment]
> 你的数据集任务是什么？是要用uie做信息抽取任务吗？

是用来做事件抽取任务的

**Comment by linjieccc** [comment]
如果是大段长文本可以选择短句中与事件距离最近，或者语义关联性最高的实体进行标注，

uie小样本学习的能力以及定制成本都不会很高，可以根据你的需求多尝试一些标注方案，在具体场景中取最优
