### ISSUE TITLE
[Question]: 使用uie-x-base抽取文档时出现错误。

### ISSUE THREAD

**Issue by estuday** [PaddlePaddle/PaddleNLP#6094]
### 请提出你的问题

项目包版本：
paddlenlp 2.5.2
paddleocr 2.6.13
`UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_3180/2016929010.py in <cell line: 1>()
----> 1 res=my_ie({"doc":"/home/aistudio/NLP.docx"})

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/taskflow.py in __call__(self, *inputs)
    848         The main work function in the taskflow.
    849         """
--> 850         results = self.task_instance(inputs)
    851         return results
    852 

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/task.py in __call__(self, *args)
    513 
    514     def __call__(self, *args):
--> 515         inputs = self._preprocess(*args)
    516         outputs = self._run_model(inputs)
    517         results = self._postprocess(outputs)

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py in _preprocess(self, inputs)
    601            2) Generate the other model inputs from the raw text and token ids.
    602         """
--> 603         inputs = self._check_input_text(inputs)
    604         outputs = {}
    605         outputs["text"] = inputs

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/taskflow/information_extraction.py in _check_input_text(self, inputs)
    630                             data["layout"] = example["layout"]
    631                         else:
--> 632                             data = self._parser_map[self._ocr_lang_choice].parse(
    633                                 {"doc": example["doc"]}, expand_to_a4_size=self._expand_to_a4_size
    634                             )

~/.data/webide/pip/lib/python3.9/site-packages/paddlenlp/utils/doc_parser.py in parse(self, doc, expand_to_a4_size, do_ocr)
     54         offset_x, offset_y = 0, 0
     55         if expand_to_a4_size:
---> 56             image, offset_x, offset_y = self.expand_image_to_a4_size(image, center=True)
     57         img_h, img_w = image.shape[:2]
     58         doc["image"] = np2base64(image)

UnboundLocalError: local variable 'image' referenced before assignment`

**Comment by linjieccc** [comment]
你好，目前uie-x支持图片及pdf格式输入，docx文档格式暂时还不支持
