### ISSUE TITLE
[Question]: 发现UIE-X的一个问题

### ISSUE THREAD

**Issue by 1061302569** [PaddlePaddle/PaddleNLP#6096]
### 请提出你的问题

paddlepaddle-gpu==2.4.2
paddlenlp==2.5.2
<h1>同一个模型推理下面两张图片出现两种情况，一个有空值，一个值是完整的，有空值的是混乱的，值都完整关系抽取正常，这是什么情况导致的</h1>

![NH4)8BX93(ZI(3 PZFE7H)T](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/c8bff07e-6377-4006-9db0-10cf090a4e37)
![Y{(NEZE_`S%2CU$NX$4VL1](https://github.com/PaddlePaddle/PaddleNLP/assets/44227598/35d3ac35-1eca-4120-bd6e-e6e5c83f8d5b)

**Comment by linjieccc** [comment]
你好，看起来模型对空值处理的鲁棒性还有待提升，建议可以检查标注质量以及转换后的训练、验证数据正确性，另外可以尝试下数据增强等方式提升特殊case的处理效果
