### ISSUE TITLE
[Question]: uie推理结果与官方demo不一致

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/PaddleNLP#6099]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/67177370/e1e4fd39-860a-4c4c-bb8c-eb22e43f830a)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/67177370/4c56722d-45a9-4db9-979e-f1648224647c)

**Comment by linjieccc** [comment]
请尝试下更新paddlenlp到最新版本，如果还有问题，可以再试试删除`~/.paddlenlp`目录重新下载模型

**Comment by schneiderlin** [comment]
已经是最新的 paddlenlp 2.5.2 版本, paddlepaddle 是 2.5.0, 模型也是新下载的, 不管哪个模型的输出都和 demo 差很远, 感觉就是随机输出.

**Comment by Ol1verZZZ** [comment]
> 已经是最新的 paddlenlp 2.5.2 版本, paddlepaddle 是 2.5.0, 模型也是新下载的, 不管哪个模型的输出都和 demo 差很远, 感觉就是随机输出.

遇到了同样的问题，请问你最终解决了吗？

**Comment by schneiderlin** [comment]
@Ol1verZZZ 解决了, 版本不兼容的问题. 具体版本号用的什么忘记了, 你找一下文档里面的兼容版本说明
