### ISSUE TITLE
训练ernie-1.0 和 ernie-tiny 出现 accu 忽高忽低，epoch 乱序

### ISSUE THREAD

**Issue by ZhangQuentin** [PaddlePaddle/PaddleNLP#611]
eval loss: 0.66868, accu: 0.93750
global step 44110, epoch: 295, batch: 10, loss: 0.00000, accu: 0.99687, speed: 3.07 step/s
global step 44120, epoch: 295, batch: 20, loss: 0.01429, accu: 0.99609, speed: 5.78 step/s
global step 44130, epoch: 295, batch: 30, loss: 0.00000, accu: 0.99635, speed: 5.42 step/s
global step 44140, epoch: 295, batch: 40, loss: 0.00855, accu: 0.99687, speed: 5.91 step/s
eval loss: 0.69317, accu: 0.50583
global step 50010, epoch: 42, batch: 810, loss: 0.72628, accu: 0.37500, speed: 1.17 step/s
global step 44150, epoch: 295, batch: 50, loss: 0.01203, accu: 0.99656, speed: 6.57 step/s
global step 50020, epoch: 42, batch: 820, loss: 0.74670, accu: 0.44375, speed: 9.35 step/s
global step 44160, epoch: 295, batch: 60, loss: 0.00000, accu: 0.99661, speed: 6.15 step/s
global step 50030, epoch: 42, batch: 830, loss: 0.68618, accu: 0.47083, speed: 11.14 step/s
global step 50040, epoch: 42, batch: 840, loss: 0.70661, accu: 0.48438, speed: 9.03 step/s
global step 44170, epoch: 295, batch: 70, loss: 0.00000, accu: 0.99687, speed: 5.79 step/s
global step 50050, epoch: 42, batch: 850, loss: 0.70259, accu: 0.49500, speed: 11.60 step/s
global step 50060, epoch: 42, batch: 860, loss: 0.67246, accu: 0.49167, speed: 8.86 step/s
global step 44180, epoch: 295, batch: 80, loss: 0.02238, accu: 0.99687, speed: 5.41 step/s
global step 50070, epoch: 42, batch: 870, loss: 0.70629, accu: 0.48571, speed: 10.84 step/s
global step 50080, epoch: 42, batch: 880, loss: 0.68906, accu: 0.48281, speed: 8.75 step/s
global step 44190, epoch: 295, batch: 90, loss: 0.00000, accu: 0.99722, speed: 5.42 step/s
global step 50090, epoch: 42, batch: 890, loss: 0.69488, accu: 0.49583, speed: 10.94 step/s
global step 44200, epoch: 295, batch: 100, loss: 0.00000, accu: 0.99719, speed: 6.40 step/s
global step 50100, epoch: 42, batch: 900, loss: 0.71366, accu: 0.49250, speed: 8.73 step/s
eval loss: 0.66964, accu: 0.93667
global step 44210, epoch: 295, batch: 110, loss: 0.00000, accu: 1.00000, speed: 3.17 step/s
global step 44220, epoch: 295, batch: 120, loss: 0.00000, accu: 0.99844, speed: 8.58 step/s
global step 44230, epoch: 295, batch: 130, loss: 0.02268, accu: 0.99740, speed: 8.58 step/s
global step 44240, epoch: 295, batch: 140, loss: 0.00000, accu: 0.99766, speed: 8.97 step/s
eval loss: 0.69378, accu: 0.50583
global step 44250, epoch: 295, batch: 150, loss: 0.01143, accu: 0.99781, speed: 8.25 step/s
global step 50110, epoch: 42, batch: 910, loss: 0.68101, accu: 0.43750, speed: 1.24 step/s
global step 44260, epoch: 296, batch: 10, loss: 0.00000, accu: 0.99818, speed: 7.78 step/s

**Comment by ZeyuChen** [comment]
@yingmuying 是否有完整的启动命令？

**Comment by ZhangQuentin** [comment]
>" @yingmuying 是否有完整的启动命令？"
>@ZeyuChen
分别修改了 train.py model tokenizer 使用 ernie-tiny ernie-1.0, 其他设置数据集都一样
$ python -m paddle.distributed.launch --gpus "0" train.py --device gpu --save_dir ./checkpoints_ernie-tiny
$ python -m paddle.distributed.launch --gpus "1" train.py --device gpu --save_dir ./checkpoints_ernie-1.0

**Comment by Steffy-zxf** [comment]
@yingmuying 你好！
日志输出乱序，应该是使用分布式同时启动训练，但没有区分日志输出路径导致的。
在同一机器使用`paddle.distributed.launch`分布式训练时，不同进程请使用不同的`log_dir` 设置不同的日志输出路径，如 
`python -m paddle.distributed.launch --gpus "0"  --log_dir "test_1" train.py --device gpu --save_dir ./checkpoints_ernie-tiny`
`python -m paddle.distributed.launch --gpus "1"  --log_dir "test_2" train.py --device gpu --save_dir ./checkpoints_ernie-1.0`

关于分布式训练可以参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/Overview_cn.html
