### ISSUE TITLE
[Question]: 搭建语义系统 使用端口号 8891 启动rest_api模型服务是报错

### ISSUE THREAD

**Issue by ANemo-yj** [PaddlePaddle/PaddleNLP#6111]
### 请提出你的问题

Exception: Failed loading pipeline component 'Retriever': Failed loading pipeline component 'DocumentStore': RequestError(400, 'illegal_argument_exception', 'Mapper for [embedding] con
flicts with existing mapper:\n\tCannot update parameter [dims] from [312] to [768]')

已将将pipelines/rest_api/pipeline/semantic_search.yaml中的DocumentStore的embedding_dim从312改为了768，且重新构建过索引，还是相同的错误，这个怎么解决？

**Comment by ANemo-yj** [comment]
elastic search中的文本的向量的维度怎么查询

**Comment by w5688414** [comment]
> ### 请提出你的问题
> Exception: Failed loading pipeline component 'Retriever': Failed loading pipeline component 'DocumentStore': RequestError(400, 'illegal_argument_exception', 'Mapper for [embedding] con flicts with existing mapper:\n\tCannot update parameter [dims] from [312] to [768]')
> 
> 已将将pipelines/rest_api/pipeline/semantic_search.yaml中的DocumentStore的embedding_dim从312改为了768，且重新构建过索引，还是相同的错误，这个怎么解决？
把原来的索引删除，重建即可。https://github.com/PaddlePaddle/PaddleNLP/blob/5540c0cfbe43a5db10e8c085f03b702470a21c66/pipelines/utils/offline_ann.py#L120

也可以命令删除：

```
curl -XDELETE http://localhost:9200/dureader_robust_query_encoder
```
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/semantic-search

**Comment by ANemo-yj** [comment]
谢谢，报错解决了 我以为构建索引时--delete_index参数就能删除原来的索引
