### ISSUE TITLE
[Bug]: paddle.fluid.dataloader api在最新的develop中已经移出

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#6113]
### 软件环境

```Markdown
- paddlepaddle: develop
- paddlepaddle-gpu: develop
- paddlenlp: 2.5.0.post
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
该PR https://github.com/PaddlePaddle/Paddle/pull/48699 移出了paddle.fluid.dataloader。
```

### 稳定复现步骤 & 代码

当前仓库代码中有3处使用
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/52e6129a-6ab1-4cc8-ae6c-df53f382094b)

**Comment by ZHUI** [comment]
fix in https://github.com/PaddlePaddle/PaddleNLP/pull/6116
