### ISSUE TITLE
[Question]: 做chatglm的LoRa微调的时候，报错：ModuleNotFoundError: No module named 'paddlenlp.peft'

### ISSUE THREAD

**Issue by yohohohoho** [PaddlePaddle/PaddleNLP#6114]
### 请提出你的问题

做chatglm的LoRa微调的时候，报错：ModuleNotFoundError: No module named 'paddlenlp.peft'，请问这个是什么原因呢？

**Comment by 1649759610** [comment]
升级paddleNLP到最新版本或用develop版试下呢？
