### ISSUE TITLE
[Question]: ModuleNotFoundError: No module named 'paddle.dataset'

### ISSUE THREAD

**Issue by zlht812** [PaddlePaddle/PaddleNLP#6118]
### 请提出你的问题

按照安装步骤，安装了paddlenlp 和 pipelines 后，运行：python run_pipelines_example.py --device gpu --source_file data/source_file.txt --doc_dir data/my_data --index_name faiss_index --retriever_batch_size 16
报错：ModuleNotFoundError: No module named 'paddle.dataset'

**Comment by w5688414** [comment]
> 

请问您使用的是pipelines哪个应用？另外，请确保paddlepaddle安装。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
