### ISSUE TITLE
load_dataset()内部格式加载本地数据出错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#612]
load_dataset()内部格式加载本地数据出错
test_ds = load_dataset("cote", "dp", data_files='./data/COTE-BD/test.tsv')

**Comment by smallv0221** [comment]
Different splits in cote dataset has different format, and the split of loacl dataset will be set to train if you dont specify.
So the script should be `test_ds = load_dataset("cote", "dp", splits='test', data_files='./data/COTE-BD/test.tsv')` in this case.

**Comment by AI-Mart** [comment]
以内置数据集格式读取本地数据集

有的时候，我们希望使用数据格式与内置数据集相同的本地数据替换某些内置数据集的数据（例如参加SQuAD竞赛，对训练数据进行了数据增强）。&nbsp;load_dataset()&nbsp;方法提供的&nbsp;data_files&nbsp;参数可以实现这个功能。以&nbsp;SQuAD&nbsp;为例。
&gt;&gt;&gt; from paddlenlp.datasets import load_dataset &gt;&gt;&gt; train_ds, dev_ds = load_dataset("squad", data_files=("my_train_file.json", "my_dev_file.json")) &gt;&gt;&gt; test_ds = load_dataset("squad", data_files="my_test_file.json")


谢谢，我刚试了下这样确实可以，但是官方手册没有这样操作，也没有说明这点，希望你们能把手册弄得越详细越规范越好，支持国产！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月24日(星期四) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] load_dataset()内部格式加载本地数据出错 (#612)





 
Different splits in cote dataset has different format, and the split of loacl dataset will be set to train if you dont specify.
 So the script should be test_ds = load_dataset("cote", "dp", splits='test', data_files='./data/COTE-BD/test.tsv') in this case.

**Comment by ZeyuChen** [comment]
@smallv0221 We can upgrade our documents later. Issues solved.
