### ISSUE TITLE
[Question]: uie-x 在单据信息提取场景下同一字段内容换行问题

### ISSUE THREAD

**Issue by shenchenfei** [PaddlePaddle/PaddleNLP#6121]
### 请提出你的问题

感谢paddle开源！
uie-x 应用于单据识别场景下，当字段出现换行的情况，如下：

| 物品名称 | ...
|  六味       | ...
| 地黄丸    | ...

使用label studio标注的时候应该如何标注呢？
1、是分“六味”、“地黄丸”两个框吗，都归类为“名称”？可是这样的话又会引入一些后处理成本。
2、把“六味地黄丸”框在一起，这种方案我在运行python label_studio.py的时候，发现_find_segment_in_box这个函数会把标注框覆盖的检测框都通过offset这个变量将文本信息搜集起来，但是在append到items["entities"]时，却只取了offset的0维，也就是会把“地黄丸”这三个文本信息丢弃。看起来在2的标注方案下，不支持换行的字段信息？
![图片](https://github.com/PaddlePaddle/PaddleNLP/assets/50792800/f99a6d5d-6b1d-408c-935c-1c025c21ad96)

**Comment by linjieccc** [comment]
你好，感谢对UIE的关注~ @shenchenfei 

默认PPOCR的文字是按照左上至右下排序的，因此上例中当六味右侧有其他文字时，『六味』和『地黄丸』会作为两部分散落在文本中（非连续），这样不太适合当前UIE-X起始、终止位置双指针解码的策略。

当前UIE-X提供的换行处理的解决方案是基于PPStructure+UIE-X进行标注和抽取，即在数据转换、预测阶段都打开`layout_analysis`这个开关，通过版面分析将一个单元格内的文字聚拢在一起。
