### ISSUE TITLE
[Question]: 关于cannot import name 'LlamaForCausalLM' from 'paddlenlp.transformers'的问题

### ISSUE THREAD

**Issue by geoxlt** [PaddlePaddle/PaddleNLP#6123]
### 请提出你的问题

在运行Aistudio上一个大模型项目：PaddleNLP：基于 LLaMA 和 Vicuna 的对话机器人（https://aistudio.baidu.com/aistudio/projectdetail/6112290?channelType=0&channel=0）

按照项目要求安装了开发板的nlp
（!pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html --user
!pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html --user）
但在导入包时（from paddlenlp.transformers import LlamaForCausalLM, LlamaConfig, LlamaTokenizer）
提示报错
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_195/1393435076.py in <cell line: 6>()
      4 
      5 from tqdm import tqdm
----> 6 from paddlenlp.transformers import LlamaForCausalLM, LlamaConfig, LlamaTokenizer
      7 
      8 pattern = 'paddle-model-?????-of-?????.pdparams'

ImportError: cannot import name 'LlamaForCausalLM' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlenlp/transformers/__init__.py)
```

**Comment by ZHUI** [comment]
应该有的
https://github.com/PaddlePaddle/PaddleNLP/blob/8ddd9a82e486b3871c4ed161b21fdc664b20d0d1/paddlenlp/transformers/llama/modeling.py#L60

!pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html 

再次安装试试？可能是AiStudio问题、

**Comment by crash-zwt** [comment]
我也碰到了这个问题！！！！
