### ISSUE TITLE
[Question]:chatglm 微调 FileNotFoundError: can not find paddle weight file<model_state.pdparams> and pytorch pytorch weight file<pytorch_model.bin> under <model>

### ISSUE THREAD

**Issue by liwei0826** [PaddlePaddle/PaddleNLP#6130]
### 请提出你的问题

指定模型路径后这样报错
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/48194881/8e995fc3-238c-4cda-b2b5-d5f10455099e)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/48194881/de3a8ed6-9773-4858-969a-f5207e86dc59)

**Comment by sunnysky29** [comment]
请问，解决了嘛？？
