### ISSUE TITLE
[Bug]: ValueError: array split does not result in an equal division

### ISSUE THREAD

**Issue by liwei0826** [PaddlePaddle/PaddleNLP#6133]
### 软件环境

```Markdown
paddle-bfloat       0.1.7
paddle2onnx         1.0.6
paddlefsl           1.1.0
paddlenlp           2.5.2.post0
paddlepaddle-gpu    0.0.0.post112
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
完全按照readme,一样的命令出现 ValueError: array split does not result in an equal division
```

### 稳定复现步骤 & 代码

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/48194881/fea263e5-4218-404c-9871-8423d241e3b3)

**Comment by ZHUI** [comment]
你好，你可以看一下你的 `tensor_parallel_dergee` 吗？可能shape不能整除，导致无法切分。
