### ISSUE TITLE
使用UIE-X or ERNIE-Layout 现在是否支持 word excel csv的信息抽取，非图片类。

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#6134]
### 请提出你的问题

目前看到案例UIE-X or ERNIE-Layout 支持 text 、图片、PDF的信息抽取

关于 word excel csv的信息抽取，非图片类，是否支持以及应该如何操作，感谢答疑

补充一下：关于类似word这样文件，如果直接用doc库处理再用UIE效果不是很好，没有版面分析，想问问UIE-x或其他模型是否有支持的。

**Comment by linjieccc** [comment]
@dingidng 你好，uie-x文档当前只支持图片和pdf输入，docx格式可以考虑转成图片来抽取

**Comment by tingaicompass** [comment]
> @dingidng 你好，uie-x文档当前只支持图片和pdf输入，docx格式可以考虑转成图片来抽取

好的，谢谢。

**Comment by zengzhixian1995** [comment]
> @dingidng 你好，uie-x文档当前只支持图片和pdf输入，docx格式可以考虑转成图片来抽取

pdf输入报错

AttributeError: 'Pixmap' object has no attribute 'pil_tobytes'
