### ISSUE TITLE
[Bug]: chatglm 多卡训练finetune的时候，lm_head.weight 层合并有问题

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#6136]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
finetune之后，合并的模型参数
chatglm.transformer.word_embeddings.weight [130528, 4096]
............
lm_head.weight [65264, 4096]
******************************************
预训练模型的参数
transformer.layers.14.attention.query_key_value.weight [4096, 12288]
...........
lm_head.weight [4096, 130528]
.........
```

### 稳定复现步骤 & 代码

model=paddle.load('./checkpoints/chatglm-6b/model_state.pdparams') ## finetune的

model=paddle.load('预训练模型的/model_state.pdparams')

lm_head的维度不一样

**Comment by liuzhipengchd** [comment]
![WeChat270e655edbc73716d2c499eda0ff3175](https://github.com/PaddlePaddle/PaddleNLP/assets/18607037/a0be1ef4-3947-4e5a-9508-bec3e833cb27)


多卡训练中，lm_head 引用的是word_embedding，但是这里做切分的时候，没有处理lm_head，所以在最后合并的时候，没有合并

**Comment by LemonNoel** [comment]
当前模型实现是 `tie_weights` 的方式，在使用 from_pretrained 加载 checkpoint 的时候，`lm_head` 的参数并不会用于初始化。

**Comment by liuzhipengchd** [comment]
> 当前模型实现是 `tie_weights` 的方式，在使用 from_pretrained 加载 checkpoint 的时候，`lm_head` 的参数并不会用于初始化。

所以训练好之后的lm_head和 word_embedding 参数是一样的，最后合并的时候就不用merge lm_head的参数？因为load的时候这个权重参数和 word_embedding 就已经绑定了
