### ISSUE TITLE
[Bug]: chatglm 双卡训练的LoRA模型，进行合并后预测效果和 用双卡进行预测效果 有差异

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#6137]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 0.0.0.post117
- paddlenlp: 2.5.2.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
模型合并的方法，使用的是finetune_predict.py脚本：
 
 if args.merge_tensor_parallel_path is not None:
        predictor.model.save_pretrained(
            save_directory=args.merge_tensor_parallel_path,
            merge_tensor_parallel=True,
        )
        predictor.tokenizer.save_pretrained(args.merge_tensor_parallel_path)

合并后的模型大小是13G

现在测试时发现：同样的输入，双卡加载模型后推断结果 和 单卡加载合并的模型推断结果 会出现不一致的情况
```

### 稳定复现步骤 & 代码

该问题 可以稳定复现

发现合并后的模型大小12888594204， 而原来THUDM/chatgpt-6b模型为13416835550。猜测是合并的代码有问题？?

**Comment by lugimzzz** [comment]
理论上，如果你传入了--lora_path 'checlpoint' --merge_tensor_parallel_path True 应该只merge了lora相关权重，为什么这里看上去是保存了chatglm主干模型的权重。

**Comment by xieyu0214** [comment]
> 理论上，如果你传入了--lora_path 'checlpoint' --merge_tensor_parallel_path True 应该只merge了lora相关权重，为什么这里看上去是保存了chatglm主干模型的权重。

![r8DJhOD4yO](https://github.com/PaddlePaddle/PaddleNLP/assets/13896613/b288a346-4fe5-4db8-b4be-40105447afe4)

模型训练完，出了checkpoint 下的保存的模型，还会在上级目录保存一份，即图中的显示的模型，这个是什么？不是最终checkpoint的模型吗？

**Comment by xieyu0214** [comment]
> 理论上，如果你传入了--lora_path 'checlpoint' --merge_tensor_parallel_path True 应该只merge了lora相关权重，为什么这里看上去是保存了chatglm主干模型的权重。

python -m paddle.distributed.launch --gpus "2,3" predict.py \
    --model_name_or_path /root/nlp/pretrained_models/THUDM_glm/chatglm-6b \
    --lora_path /root/nlp/tasks/chatglm/checkpoints/chatglm-6b-8-32/checkpoint-21960 \
    --src_length 2048 \
    --tgt_length 160 \
    --batch_size 10 \
    --data_fp /root/nlp/corpus/task_bot/assistant/gen_dialogues/loose_constraint_train/cases.txt \
    --merge_tensor_parallel_path /root/nlp/tasks/chatglm/checkpoints/chatglm-6b-8-32/finetuned_model/

上面这样的配置，得到的合并模型是13G。想要只 保存合并LoRA模型，该怎么设置？

**Comment by lugimzzz** [comment]
你好，验证后发现是我们这边lora merged linear实现有问题，这边我们已经在提pr修复了https://github.com/PaddlePaddle/PaddleNLP/pull/6141
- 在修复pr合并之前，建议如果需要使用lora 训练，可以修改finetune_generation.py `enable_lora_list = None`
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/chatglm/finetune_generation.py#L126
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/63761690/d18308e2-3cff-4af9-9901-a7abe4569e06)

- 如果使用predict_generation.py合并参数只合并lora参数，请在104行后添加一行代码`model.mark_only_lora_as_trainable()` 。https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/chatglm/predict_generation.py#L104
