### ISSUE TITLE
[Question]: 使用uie模型预训练走GPU报错

### ISSUE THREAD

**Issue by Jiyongjie0903** [PaddlePaddle/PaddleNLP#6138]
### 请提出你的问题

我运行paddle.fluid.install_check.run_check()，返回Your Paddle Fluid works well on MUTIPLE GPU or CPU. 是不是说明GPU正常运行。但是用UIE微调模型时，使用GPU报错，说不能识别GPU DEVICE,是什么问题呢？

**Comment by linjieccc** [comment]
麻烦提供下paddle、cuda版本信息
