### ISSUE TITLE
[Question]: TrainingArguments 吐槽

### ISSUE THREAD

**Issue by JianhuanZhuo** [PaddlePaddle/PaddleNLP#6139]
### 请提出你的问题

Trainer API 这么好的一个东西，为什么多了一个 TrainingArguments 这种败笔，这种设计就无法单独使用 Trainer

**Comment by ZHUI** [comment]
嗯嗯，你好，可以说一下你这边的需求？

TrainingArguments 这个东西的话，主要是训练的很多参数需要传入，所以做了一些内置。

不通过命令行，直接代码里面初始化 TrainingArguments 也是可以的。

**Comment by rio5050** [comment]
> 嗯嗯，你好，可以说一下你这边的需求？
> 
> TrainingArguments 这个东西的话，主要是训练的很多参数需要传入，所以做了一些内置。
> 
> 不通过命令行，直接代码里面初始化 TrainingArguments 也是可以的。

请问如何在代码里初始化呢 @ZHUI

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/llama/run_pretrain.py#L369-L371

参考这里，可以用dict初始化。
