### ISSUE TITLE
强烈建议出一个动态batch_size的数据读取工具

### ISSUE THREAD

**Issue by fiyen** [PaddlePaddle/PaddleNLP#614]
目前训练一般是针对固定batch_size进行的。而通过paddlenlp中的Pad等工具可以动态适应序列的最长长度，使每批数据的长度是动不一样的。而在批长度很小的情况下，固定的batch_size其实很大程度上浪费了GPU的资源，batch_size的设定其实是多次尝试中调节出来的，但是也不可能最大程度利用GPU。能否将批长度和batch_size的乘积作为一个可调的量来做一个动态batch_size的数据读取器。最大化利用GPU资源，加快训练速度，提高训练效果。

**Comment by ZeyuChen** [comment]
Thanks for your feature request! 我们评估后答复您！ :)

**Comment by ZeyuChen** [comment]
@fiyen 你是否有在其他框架中看到这种功能？是否可以提供更多参考示例？
因为动态的大小会导致不同卡之间计算进度差距较大，不利于多卡的同步和梯度的稳定性，需要权衡下如何设计更妥当。

**Comment by fiyen** [comment]
> @fiyen 你是否有在其他框架中看到这种功能？是否可以提供更多参考示例？
> 因为动态的大小会导致不同卡之间计算进度差距较大，不利于多卡的同步和梯度的稳定性，需要权衡下如何设计更妥当。

还没有在其他框架看到类似功能，只是一个初步的想法，未来会验证一下这样的做法的可行性。

**Comment by fiyen** [comment]
> @fiyen 你是否有在其他框架中看到这种功能？是否可以提供更多参考示例？
> 因为动态的大小会导致不同卡之间计算进度差距较大，不利于多卡的同步和梯度的稳定性，需要权衡下如何设计更妥当。

我简单实现了这个设想，并做了一些验证。动态batch_size在单卡上可以完成训练，并且可以提高训练速度同时不影响收敛。但是也遇到了训练不稳定的问题。相关实验结果我更新了一个项目，链接：https://aistudio.baidu.com/aistudio/projectdetail/2159272 。以后会跟进相关的进站，如果可能请宇哥进行一些技术指导。
