### ISSUE TITLE
[Question]: llama预训练脚本报错

### ISSUE THREAD

**Issue by cifar10** [PaddlePaddle/PaddleNLP#6165]
### 请提出你的问题

在路径PaddleNLP/tree/develop/examples/language_model/llama下，运行llama预训练脚本（--fp16_opt_level "O2" ），报错Gaussian 算子无fp16实现。该预训练脚本是否未经过验证。
运行环境：
1、GPU-A100
2、python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by ZHUI** [comment]
你好，请使用最新的 paddle nightly develop 版本。

https://www.paddlepaddle.org.cn/

<img width="1029" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/16911935/8a1a2279-80e6-4cc2-af49-ae43b0b22ab7">

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/6167/files 添加了一些 readme 注意事项。

**Comment by cifar10** [comment]
多谢回复，另外请问llama的预训练脚本是否在PaddleCustomDevice仓库下实验过，我在PaddleCustomDevice套件下，将启动脚本中的‘device’设置成cpu后，出现了类似index越界的问题，具体log如下图：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/41565156/bcf45d0a-f0ca-498c-9c12-537d8336077a)

**Comment by ZHUI** [comment]
没有尝试过，不过建议 cpu 训练，请使用单卡训。

**Comment by cifar10** [comment]
是指开启cpu设备时，用单卡启动命令训练是吗

**Comment by cifar10** [comment]
再请问下，llama预训练脚本中的--max_seq_length 参数，默认是2048，这个参数对最终收敛精度影响大吗？可以修改成较小的数值，比如256，512吗？

**Comment by ZHUI** [comment]
可以调小。不过肯定影响模型效果的。

**Comment by cifar10** [comment]
请问下，使用llama预训练脚本中默认的--max_seq_length 参数2048，在训练时遇到embedding_backward的其中一个输入indice[i]中的值等于4000，此时的输出shape是output[4000, 5120]，导致访问output越界，这个问题你们之前有遇到过吗？另外这个会是最开始数据处理时tokenizer的问题吗

**Comment by ZHUI** [comment]
贴一下报错？有点奇怪，4000 这个值有点特殊，也跟2048没有啥关系？

**Comment by cifar10** [comment]
嗯嗯，跟max_seq_length 的2048关系不大。将embedding_backward算子放在cpu上执行时，能够定位到是输入到kernel的input(indice)越界了，即进入embedding_backward时，input中就已经存在索引值是4000的错误了。这个input也是embedding前项的输入之一，所以猜测会不会是tokenizer的问题
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/41565156/39436cef-b402-4cb7-953a-b020ef21bfd5)

**Comment by cifar10** [comment]
暂时解决了，谢谢帮助

**Comment by cifar10** [comment]
暂时解决了，谢谢回复
