### ISSUE TITLE
[Question]: 根据教程搭建的语义检索系统效果很拉跨

### ISSUE THREAD

**Issue by ANemo-yj** [PaddlePaddle/PaddleNLP#6171]
### 请提出你的问题

我照着文档把paddlenlp 的语义检索系统搭建起来了，完全没有视频中的丝滑流畅 自己前端上传的文章基本检索出来都不准，这是为什么呢？有没有一种稍微准确些的部署方式？我使用的不是他内置的nano模型 用的是rocketqa-zh-medium-query-encoder 上传的文章是正常的论文格式，搜索的问题是论文中的小标题。效果如下 无论问这篇文章的什么内容 检索出来的只有摘要，图片也无法展示。

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/58975405/a95a13f6-e88d-49a0-83f8-945553bf4763)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/58975405/aa091f93-3195-42b2-9234-dd4b196baf41)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/58975405/eafc1a2c-d2c2-43e7-88de-992d54be4154)

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 我照着文档把paddlenlp 的语义检索系统搭建起来了，完全没有视频中的丝滑流畅 自己前端上传的文章基本检索出来都不准，这是为什么呢？有没有一种稍微准确些的部署方式？我使用的不是他内置的nano模型 用的是rocketqa-zh-medium-query-encoder 上传的文章是正常的论文格式，搜索的问题是论文中的小标题。效果如下 无论问这篇文章的什么内容 检索出来的只有摘要，图片也无法展示。
> 
> ![image](https://user-images.githubusercontent.com/58975405/245694870-a95a13f6-e88d-49a0-83f8-945553bf4763.png)
> 
> ![image](https://user-images.githubusercontent.com/58975405/245694915-aa091f93-3195-42b2-9234-dd4b196baf41.png)
> 
> ![image](https://user-images.githubusercontent.com/58975405/245694948-eafc1a2c-d2c2-43e7-88de-992d54be4154.png)

请问您是用的pdf导入的吗？还是word，目前word需要按照行分段，或者使用text_splitter来进行聚合一下

**Comment by w5688414** [comment]
语义检索给了txt的示例，请先按照txt的方式添加语料，先调出效果来

**Comment by ANemo-yj** [comment]
我是使用word添加的  pdf我试了也是一样的效果，难道我在上传之前要先按行来分一下段吗？所有格式都是这样？

**Comment by w5688414** [comment]
> 我是使用word添加的 pdf我试了也是一样的效果，难道我在上传之前要先按行来分一下段吗？所有格式都是这样？

可以看看ES里面的文本是否分得太细了，对于小的段落需要进行合并

**Comment by ANemo-yj** [comment]
> 看看ES里面的文本是否分得太细了，对于小的段落需要进行合并

请教一下 怎么看ES，是上传之前就要按行分段或者小段落合并还是上传后在进行操作呢？

**Comment by ANemo-yj** [comment]
> > 我是使用word添加的 pdf我试了也是一样的效果，难道我在上传之前要先按行来分一下段吗？所有格式都是这样？
> 
> 可以看看ES里面的文本是否分得太细了，对于小的段落需要进行合并



还要请问一下 为啥检索出来的文档中图显示不出来呢

**Comment by oyehko** [comment]
ernie模型的语义相似度匹配效果极差，而且默认的text_matching代码匹配两个句子相似度时，相同的句子，每次结果都不一样，如果你是以此为基础搭建的检索系统其结果肯定就是个笑话
