### ISSUE TITLE
[Question]:一句话 抽取的实体同时被预测出来多种schema，这种如何处理？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6173]
### 请提出你的问题

比如：
项目编号：09080-0800
同时schema中定义了项目编号和甲方项目编号，乙方项目编号
这时项目编号就会被抽取成甲方或者乙方项目编号，同时项目编号也会抽取成了甲方项目编号，乙方项目编号，抽取错误，但是实际是没有甲方和乙方的

**Comment by linjieccc** [comment]
@cqray1990 可以尝试通过关系抽取的方式来处理

**Comment by cqray1990** [comment]
> @cqray1990 可以尝试通过关系抽取的方式来处理
 因为任务就是实体抽取，又重新搞关系抽取，就有两个任务，实际任务不是单独分开的，这个想做成实体抽取,还有这个项目编号:6666669怎么去标注关系抽取三元组，项目编号会被错误抽取成甲方或乙方，可能有公共的项目编号四个字，导致出错，这种继续搞数据训练可否？
@linjieccc

**Comment by linjieccc** [comment]
从你举的这个例子没办法区分甲乙方吧，需要有一个甲乙方的背景信息输入

**Comment by cqray1990** [comment]
> 从你举的这个例子没办法区分甲乙方吧，需要有一个甲乙方的背景信息输入

@linjieccc 
甲方项目编号:0908023
乙方项目编号:0901348
项目编号:080800

这种的话是可以区分的吧？但是实际预测好容易把甲方，乙方项目编号分成项目编号，标注这三种实体，应该可以区分吧？
