### ISSUE TITLE
[Question]: 文本抽取任务与通用信息抽取uie的区别是什么呢

### ISSUE THREAD

**Issue by zhaicc** [PaddlePaddle/PaddleNLP#6182]
### 请提出你的问题

[Question]: 文本抽取任务与通用信息抽取uie的区别是什么呢

**Comment by linjieccc** [comment]
模型解码方式不同，传统文本抽取通常基于BIO序列标注的方式，需要的标注数据量更大，且不同场景复用、迁移能力较弱。UIE是基于prompt范式的双指针解码方式，并且在大规模各类信息抽取数据上进行了多任务训练，零样本及小样本能力更强。

**Comment by zhaicc** [comment]
明白了，感谢
