### ISSUE TITLE
[Question]: doccano 不支持长文本跨行标注？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6183]
### 请提出你的问题

比如：
5.2.1合同签订付款：双方合同签订后，甲方收到相应金额的、符合国家规定的增值税专用发票后[7]个工作日内，甲方向乙方支付合同总价款的30%款项，即大写人民币贰拾万柒仟元整，小写：￥207,000
.00元
 我想要标注207，000.00元，但是他跨行，doccno跨行选不行，labelstudio也不行，长文本标注比较麻烦

**Comment by linjieccc** [comment]
@cqray1990 doccano支持跨行标注，可以排查下是不是浏览器显示问题

**Comment by 1ZhangMR** [comment]
我标注的时候也是支持的

**Comment by cqray1990** [comment]
> 我标注的时候也是支持的
你是什么版本的？，如果标签很长，文本不能一行显示，我试着滚动鼠标，让字变小，还是显示了多行，我想标注全部作为标签，可就是不行，奇怪，你滚动了缩小了浏览器？
@1ZhangMR
