### ISSUE TITLE
[Question]: uie-base无法微调，If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.

### ISSUE THREAD

**Issue by hahashayebuhui** [PaddlePaddle/PaddleNLP#6184]
### 请提出你的问题

在微调的时候，不报错，但也无法训练
[2023-06-15 11:08:56,540] [    INFO] - All the weights of UIE were initialized from the model checkpoint at uie-senta-mini.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
这样就结束了

**Comment by linjieccc** [comment]
请尝试下根据CUDA环境安装对应的paddle版本，另外可以通过`paddle.utils.run_check()`验证安装 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by gitaidea** [comment]
@linjieccc 我也碰到了类似问题，请问后续解决了吗？
