### ISSUE TITLE
[Question]: llama训练使用的GPU设备

### ISSUE THREAD

**Issue by cifar10** [PaddlePaddle/PaddleNLP#6189]
### 请提出你的问题

请问，在PaddleNLP/tree/develop/examples/language_model/llama下，预训练或者微调 llama-7B/13B 的GPU设备是A100吗，设备的显存是多少呢？

**Comment by linjieccc** [comment]
@cifar10 llama微调推荐使用4卡/8卡 A100，显存>=40G，另外也可以关注下低参数微调LoRA等方案来降低训练的显存占用

**Comment by cifar10** [comment]
好的，谢谢回复
