### ISSUE TITLE
[Question]: 评估uie报错

### ISSUE THREAD

**Issue by gggdroa** [PaddlePaddle/PaddleNLP#6194]
### 请提出你的问题

是版本的问题吗？怎么解决呢  希望回复一下  感谢

当前版本
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/bb9b28f4-40d1-4734-9cba-8dc106699866)

报错：
KeyError: 'token_type_ids'
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/6c44397d-ea9f-46c9-bacc-806b2a4b1de2)

**Comment by linjieccc** [comment]
@gggdroa 请尝试下更新微调及评估的脚本，用最新develop代码

**Comment by gggdroa** [comment]
> @gggdroa 请尝试下更新微调及评估的脚本，用最新develop代码

用的就是最新版的
我又重新拉了一下代码，没有得到解决 还是报错

**Comment by linjieccc** [comment]
可以贴下你的执行方式吗

**Comment by gggdroa** [comment]
> 可以贴下你的执行方式吗

python evaluate.py \
    --model_path ./checkpoint/model_best \
    --test_path ./data/dev.txt \
    --batch_size 16 \
    --max_seq_len 512 \       按照说明文档里操作的  感谢回复

**Comment by linjieccc** [comment]
删除``./checkpoint/model_best``，用最新的代码重新跑下微调流程试试

**Comment by gggdroa** [comment]
> 删除`./checkpoint/model_best`，用最新的代码重新跑下微调流程试试
好 
再来确定下 没有选择错误代码吧
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/82b58a36-afea-4842-b01c-d9e318228a38)

**Comment by gggdroa** [comment]
> 删除`./checkpoint/model_best`，用最新的代码重新跑下微调流程试试

另外想问下，如果数据量足够大，用uie训练会起反作用吗，必须精度不高什么的

**Comment by gggdroa** [comment]
> 删除`./checkpoint/model_best`，用最新的代码重新跑下微调流程试试

跑完了  评估文件是同样的错误

**Comment by linjieccc** [comment]
我这边没有复现出你的问题哈，你试试新建一个的conda环境

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/40840292/6ded959f-89b9-406c-9377-9e3e5f4d0f28)

**Comment by gggdroa** [comment]
> 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> 
> ![image](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)

是这套代码吗 我新建了一个还是同样的错误  哎
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/09b3cb83-de43-49a8-89da-3cdc63e71521)

**Comment by gggdroa** [comment]
> 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> 
> ![image](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)

你的paddlen版本是多少呢 感谢

**Comment by gggdroa** [comment]
> 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> 
> ![image](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)

搞定了   感谢感谢

**Comment by gggdroa** [comment]
> > 删除`./checkpoint/model_best`，用最新的代码重新跑下微调流程试试
> 
> 另外想问下，如果数据量足够大，用uie训练会起反作用吗，必须精度不高什么的


另外想问下，如果数据量足够大，用uie训练会起反作用吗，必须精度不高什么的？
会出现这个问题吗

**Comment by gggdroa** [comment]
另外想问下，如果数据量足够大，用uie训练会起反作用吗？比如指标不高

**Comment by Walker-DJ1** [comment]
> > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> 
> 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo)
你是咋搞定的我遇见了相同的"token_type_ids": encoded_inputs["token_type_ids"]报错信息

**Comment by gggdroa** [comment]
> > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > 
> > 
> > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo)
> > 你是咋搞定的我遇见了相同的"token_type_ids": encoded_inputs["token_type_ids"]报错信息

你用的什么版本的paddlenlp？

**Comment by gggdroa** [comment]
> > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > 
> > 
> > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo)
> > 你是咋搞定的我遇见了相同的"token_type_ids": encoded_inputs["token_type_ids"]报错信息

有点遗忘  因为我的记录文件误删了 
是不是评估参数的问题？

**Comment by Walker-DJ1** [comment]
> > > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > > 
> > > 
> > > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo) 你是咋搞定的我遇见了相同的“token_type_ids”： encoded_inputs[“token_type_ids”]报错信息
> 
> 你用的什么版本的paddlenlp？

跟你一样：
paddlenlp                     2.5.2
paddlepaddle-gpu              2.4.2.post117

**Comment by gggdroa** [comment]
> > > > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > > > 
> > > > 
> > > > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo) 你是咋搞定的我遇见了相同的“token_type_ids”： encoded_inputs[“token_type_ids”]报错信息
> > 
> > 
> > 你用的什么版本的paddlenlp？
> 
> 跟你一样： paddlenlp 2.5.2 paddlepaddle-gpu 2.4.2.post117

运行参数也一样吗？
我的是：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/cd228d20-f5fc-4c13-98a4-0b1fa304932a)
均可执行
重新搭环境试过不？

**Comment by Walker-DJ1** [comment]
> > > > > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > > > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > > > > 
> > > > > 
> > > > > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo) 你是咋搞定的我遇见了相同的“token_type_ids”： encoded_inputs[“token_type_ids”]报错信息
> > > 
> > > 
> > > 你用的什么版本的paddlenlp？
> > 
> > 
> > 跟你一样： paddlenlp 2.5.2 paddlepaddle-gpu 2.4.2.post117
> 
> 运行参数也一样吗？ 我的是： ![image](https://private-user-images.githubusercontent.com/106646583/320714511-cd228d20-f5fc-4c13-98a4-0b1fa304932a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzQ2NjIsIm5iZiI6MTcxMjYzNDM2MiwicGF0aCI6Ii8xMDY2NDY1ODMvMzIwNzE0NTExLWNkMjI4ZDIwLWY1ZmMtNGMxMy05OGE0LTBiMWZhMzA0OTMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2Q2OWNjYTllYmJkNjA0ZTQ1NjI4YTg3NzZkNjA1NGJhMGRlMDIwMGUxNzM5MTMxOTIwNmIxNzBiOGEwYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.99Y19wjjYjROxoHRKekbqVCfuD9NbDzsiZTlheBB1yA) 均可执行 重新搭环境试过不？

基本一致，多传了几个参数。没有试过重装环境
```
python evaluate.py \
    --model_path ./checkpoint-6680 \
    --test_path ./data/dev.txt \
    --batch_size 4 \
    --max_seq_len 512\
    --debug
```

**Comment by chinesejunzai12** [comment]
> > > > > > > 我这边没有复现出你的问题哈，你试试新建一个的conda环境
> > > > > > > ![图像](https://user-images.githubusercontent.com/40840292/246331367-6ded959f-89b9-406c-9377-9e3e5f4d0f28.png)
> > > > > > 
> > > > > > 
> > > > > > 是这套代码吗 我新建了一个还是同样的错误 哎 ![图像](https://private-user-images.githubusercontent.com/106646583/246333416-09b3cb83-de43-49a8-89da-3cdc63e71521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzM0NTcsIm5iZiI6MTcxMjYzMzE1NywicGF0aCI6Ii8xMDY2NDY1ODMvMjQ2MzMzNDE2LTA5YjNjYjgzLWRlNDMtNDlhOC04OWRhLTNjZGM2M2U3MTUyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDRmZDA2NDcwMGNmMTJjNTM0ODY4NmMzZmRkMTJjMjZjYTQzY2U5MTI4MzQ5YWZhMTk3ZTViMGU5MzIyYjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGJOTC9UQ_OQkWOBnf-OfqbejYJqmPeWsDljzUKUqdo) 你是咋搞定的我遇见了相同的“token_type_ids”： encoded_inputs[“token_type_ids”]报错信息
> > > > 
> > > > 
> > > > 你用的什么版本的paddlenlp？
> > > 
> > > 
> > > 跟你一样： paddlenlp 2.5.2 paddlepaddle-gpu 2.4.2.post117
> > 
> > 
> > 运行参数也一样吗？ 我的是： ![image](https://private-user-images.githubusercontent.com/106646583/320714511-cd228d20-f5fc-4c13-98a4-0b1fa304932a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MzQ2NjIsIm5iZiI6MTcxMjYzNDM2MiwicGF0aCI6Ii8xMDY2NDY1ODMvMzIwNzE0NTExLWNkMjI4ZDIwLWY1ZmMtNGMxMy05OGE0LTBiMWZhMzA0OTMyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwMzQ2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2Q2OWNjYTllYmJkNjA0ZTQ1NjI4YTg3NzZkNjA1NGJhMGRlMDIwMGUxNzM5MTMxOTIwNmIxNzBiOGEwYjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.99Y19wjjYjROxoHRKekbqVCfuD9NbDzsiZTlheBB1yA) 均可执行 重新搭环境试过不？
> 
> 基本一致，多传了几个参数。没有试过重装环境
> 
> ```
> python evaluate.py \
>     --model_path ./checkpoint-6680 \
>     --test_path ./data/dev.txt \
>     --batch_size 4 \
>     --max_seq_len 512\
>     --debug
> ```
你好, 你的这个问题解决了么, 是我在taskflow的时候报的同样的错误, paddlenlp=2.5.2

**Comment by Walker-DJ1** [comment]
你好这个应该是paddle的常见Bug,这个环境应该是可以的。还是paddle版本的问题或者建议新建环境paddlepaddle==2.5 paddlenlp==2.5
注意这个bug: libstdc++.so.6:version 'GLIBCXX_3.4.30‘ not found · Issue #56047 · PaddlePaddle/Paddle (github.com)
conda install -c conda-forge gcc=12.2.0
| |
Walker.DJ
|
|
北京交通大学
18810724099
***@***.***
北京市海淀区
100044
|
在2024年5月28日 ***@***.***> 写道：

我这边没有复现出你的问题哈，你试试新建一个的conda环境


是这套代码吗 我新建了一个还是同样的错误 哎 你是咋搞定的我遇见了相同的“token_type_ids”： encoded_inputs[“token_type_ids”]报错信息

你用的什么版本的paddlenlp？

跟你一样： paddlenlp 2.5.2 paddlepaddle-gpu 2.4.2.post117

运行参数也一样吗？ 我的是： 均可执行 重新搭环境试过不？

基本一致，多传了几个参数。没有试过重装环境

python evaluate.py \
    --model_path ./checkpoint-6680 \
    --test_path ./data/dev.txt \
    --batch_size 4 \
    --max_seq_len 512\
    --debug


你好, 你的这个问题解决了么, 是我在taskflow的时候报的同样的错误, paddlenlp=2.5.2

**Comment by szz1211** [comment]
我用uie-base是好的，改成uie-m-base评估就会有这个错误，请问怎么解决呢

**Comment by pengpoo** [comment]
> 我用uie-base是好的，改成uie-m-base评估就会有这个错误，请问怎么解决呢

python evaluate.py --model_path ./checkpoint/model_best --test_path ./data/test.txt --batch_size 16 --max_seq_len 512 --multilingual --debug
我也是这个问题，后来看文档里面，多语言模型要加 `--multilingual` 参数
