### ISSUE TITLE
[Question]: CLUE数据集处理方式？

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/PaddleNLP#6197]
### 请提出你的问题

下载的CLUE数据集解压后包括两个部分：
```
1、clue_pretrain_oscar_corpus  均分三部分
├── dev  19639 个文件
├── test 19642 个文件
└── train 19644 个文件
2、train：
   clue_pretrain_0000000.txt - clue_pretrain_0028599.txt
```
尝试复现 [大规模语料预训练: 400GB - CLUE & WuDao](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/README.md#22-%E5%A4%A7%E8%A7%84%E6%A8%A1%E8%AF%AD%E6%96%99%E9%A2%84%E8%AE%AD%E7%BB%83-400gb---clue--wudao) 

1.请问 [这里](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/pretraining_introduction.md)是将所有数据放到一起预处理使用吗？如果将所有数据放到一起，按照 CLUECorpusSmall 处理方式会生成相应的 jsonl 和 npy、npz文件，假如命名为：
clue_pretrain .npy
clue_pretrain .npz

2.结合处理的 wudao数据生成 npy npz文件：
wudao_corpus_200g_0623_ids.npy
wudao_corpus_200g_0623_idx.npz

请问是将这两份npy、npz直接文件分别放到data里凑400G文件一起使用吗？是否需要合并？如果需要合并应该怎么合并？如果不需要合并，--input_dir中形式为这样启动预训练吗？
clue_pretrain .npy
clue_pretrain .npz
wudao_corpus_200g_0623_ids.npy
wudao_corpus_200g_0623_idx.npz

**Comment by gongel** [comment]
不需要合并的，放一个文件夹里面就可以 https://github.com/PaddlePaddle/PaddleNLP/blob/v2.6.0rc/model_zoo/ernie-1.0/run_pretrain.py#L174-L179

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/README.md#%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87-1

<img width="1202" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/16911935/22a7b32c-73e7-454a-8504-61e2d95f5335">
 
参考这里，数据比例 + 数据名前缀 组合一起就行。
