### ISSUE TITLE
[Question]:离线蒸馏

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6199]
### 请提出你的问题

UIE离线蒸馏每有看到训练老师模型和学生模型同时训练，离线蒸馏是不是换了轻量的模型，比如uie-nano，uie-mini等，data_distill.py 生成student_data   数据后，用--encoder ernie-3.0-micro-zh 底座模型区训练sdudent_data 和直接用uie-mini fintune.py 进行训练的区别是什么呢， 并且这两种情况得到模型区别：

**Comment by sunfan1997** [comment]
所以答案是什么。
