### ISSUE TITLE
[Question]: 如何导出uie的静态模型，没有找到export_model.py

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6200]
### 请提出你的问题

如何导出uie的静态模型，没有找到export_model.py

**Comment by gongel** [comment]
你好，可以先走动态图部署哈

**Comment by cqray1990** [comment]
> 你好，可以先走动态图部署哈

静态图部署不了？
@gongel ,我好像看到有静态图的推理，但是没有看到导出静态图的，训练不是保存了？

**Comment by gongel** [comment]
参考这里哈：https://github.com/PaddlePaddle/PaddleNLP/blob/9c484e60592be6a27c6ad588fc22ff3e1d7fe93e/model_zoo/uie/finetune.py#L206
