### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Rruown** [PaddlePaddle/PaddleNLP#6202]
### 请提出你的问题

[信息抽取应用 README](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction/#readme)里面有关于中文文本数据集实验效果的表格，表格内容如下：

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/34084211/9e67a735-d9fe-4b20-8024-37ea18fbfabd)

我想提的问题如下：
1. 实验的指标是什么，这些数字代表什么意思？Accuracy？F1-Score？
2. Ernie-Layout 的文档中有明确说明具体的评测方法和超参数。如果可以的话上述图片的数据能否提供超参数以方便复现？

**Comment by gongel** [comment]
1. F1-Score
2. 参考这里 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/evaluate.py
