### ISSUE TITLE
[Question]: UIE 标注

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6211]
### 请提出你的问题

买方：xxxx公司
甲方：xxx公司

标注为甲方，这样的prompts会有影响？标注的内容是否需要跟prompt字相近？

**Comment by 1ZhangMR** [comment]
没有影响

**Comment by linjieccc** [comment]
uie对标注方式没有特别限制，prompt符合自然语言语义更佳
