### ISSUE TITLE
[Question]: hierarchical\retrieval_based  中评估指标的recall计算

### ISSUE THREAD

**Issue by Typooner** [PaddlePaddle/PaddleNLP#6213]
### 请提出你的问题

在hierarchical\retrieval_based下的模型训练和评估中，代码使用recall作为评估指标，但是我跑出来的结果recall一直都是0

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/55538775/dc531731-500a-4811-9aa5-01892f6e2fb0)

**Comment by w5688414** [comment]
用的是示例数据集吗？如果是的话，请把复现的步骤提供一下，如果使用自己的数据，检查一下数据的格式是否正确，基于检索的文本分类适合类别不均衡和较多的情况

**Comment by Typooner** [comment]
我使用了自己的数据集，刚试了下示例数据集确实没有问题，感谢~
