### ISSUE TITLE
[Question]: 文档智能传入PDF数据问题

### ISSUE THREAD

**Issue by Jaydon996** [PaddlePaddle/PaddleNLP#6218]
### 请提出你的问题

第一次传入PDF时报错：AttributeError: 'Document' object has no attribute 'pageCount'
解决办法：更换PyMuPDF版本为1.19.0
再次启动服务并调用时报错：IndexError: list index out of range

报错内容详见截图，小白，还望大神指点
<img width="725" alt="2c6b808a858153cef54981442ac44c1" src="https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/0ecb8a65-779c-47ff-b470-40c3526de313">
<img width="709" alt="c153a1460e3e080c5d593d904cf484a" src="https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/a900b631-d832-44d4-b5cc-7443539b8c37">

**Comment by Jaydon996** [comment]
这个是输出的ocr_res数据
<img width="1733" alt="87839429a1cf16cd4b4b7acf540c425" src="https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/6572a21e-3db0-4992-9e00-d4ab963e78c3">

**Comment by Jaydon996** [comment]
报错行附近代码
<img width="618" alt="d7ee01d9b8d31f376a2da029adaf8db" src="https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/3a972ed1-5580-4dab-80d6-c1560b0ce4dd">

**Comment by Jaydon996** [comment]
为什么会报错呀，jpg格式就没事问题

**Comment by zhangqiqi1228** [comment]
> 为什么会报错呀，jpg格式就没事问题

這個問題你解決了麽，我跟你有相同情況的報錯。

**Comment by Jaydon996** [comment]
解决方案就是先转成jpg再调接口…



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Keyla ***@***.***> |
| 日期 | 2023年07月18日 14:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: 文档智能传入PDF数据问题 (Issue #6218) |

为什么会报错呀，jpg格式就没事问题

這個問題你解決了麽，我跟你有相同情況的報錯。
