### ISSUE TITLE
手把手搭建一个语义检索系统无监督预训练 - 看到有SimCSE支持，关于DiffCSE会添加进来吗？

### ISSUE THREAD

**Issue by tingaicompass** [PaddlePaddle/PaddleNLP#6224]
### 请提出你的问题

手把手搭建一个语义检索系统无监督预训练 - 看到有SimCSE支持，关于DiffCSE会添加进来吗？
[SimCSE无监督语义索引链接](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/neural_search/recall/simcse/README.md)，

看到了[无监督语义匹配模型 DiffCSE链接](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/diffcse)有相关实现，后续会把DiffCSE添加进来嘛。

或者提供一下需要修改SimCSE文件内容情况，谢谢。

**Comment by w5688414** [comment]
目前没有这个计划，不过实现不难，欢迎开发者贡献

**Comment by tingaicompass** [comment]
> 目前没有这个计划，不过实现不难，欢迎开发者贡献

好的，我把后面流程搞完后，到时提个pr
