### ISSUE TITLE
[Question]: 目前 develop 分支依赖的 Paddle 版本

### ISSUE THREAD

**Issue by sBobHuang** [PaddlePaddle/PaddleNLP#6227]
### 请提出你的问题

我想用Nvidia GPU跑下 Paddle 支持的LLM，我看到 develop 分支支持的模型已经很多了，请问目前 develop 分支依赖哪个 Paddle 版本，我用 Paddle 的稳定版 和 develop 都有报错。

**Comment by ZHUI** [comment]
使用最新dev 或者 2.5版本（稍晚些会发） https://www.paddlepaddle.org.cn/
