### ISSUE TITLE
[Question]: 有没有关于指令训练的技术方案 呀

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleNLP#6228]
### 请提出你的问题

我在看代码里面，以chatglm为例，我看指令训练就是在data里面把instruct 和 input 进行了拼接，生成prompt。然后放到模型训练。还有没有其他的技巧？ 或者 在构建指令和input的时候，应该怎么生成高质量的数据？

**Comment by sijunhe** [comment]
你好，我们chatglm examples里面的[指令prompt](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/chatglm/data.py#L41)是直接参考的[ChatGLM官方Repo](https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/main.py#L159)提供的范例。指令微调的prompt也没有什么特别的诀窍，主要是取决于模型本身的SFT的时候使用的prompt。也可以自己随意尝试不同的prompt
