### ISSUE TITLE
[Question]: UIE 实体抽取和关系抽取两个任务是否可以同时进行？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#6229]
### 请提出你的问题

根据输入的格式，UIE 实体抽取和关系抽取两个任务是否可以同时进行？然后根据结果组合自己想要的结果
这样输入多个任务，
schema = ["时间",{ '作品名': [
        '歌手',
        '发行时间',
        '所属专辑'
    ]}]

如果可以的话，那训练怎么训练呢，数据合一起？

**Comment by linjieccc** [comment]
标注阶段根据需求同时标注即可
