### ISSUE TITLE
[Question]UIE文档实体抽取对应信息不支持换行嘛？: 

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleNLP#6231]
### 请提出你的问题

比如 下图的开户银行信息 ，模型预测的结果只有上边的一行 ，下边 门支行 三字没有识别
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/0042a503-1aa0-4cc2-9e83-fe33e06f3154)

**Comment by linjieccc** [comment]
换行抽取可以考虑PPStructure版面分析 + UIE-X的解决方案，默认版面分析可能在一些场景识别效果不是很好需要重新训练，这里有个例子可以参考下 https://aistudio.baidu.com/aistudio/projectdetail/5704766?sUid=2900009&shared=1&ts=1679480566567

**Comment by whisky-12** [comment]
好的 感谢，还是 想请问下 是否可以有办法提升ocr识别的精度，排除多行影响

**Comment by tianchiguaixia** [comment]
传入付费的ocr result。可以提高
