### ISSUE TITLE
[Question]: UIE pretraining and schema setting

### ISSUE THREAD

**Issue by songtaoWang1** [PaddlePaddle/PaddleNLP#6241]
### 请提出你的问题

How do I use UIE to unsupervisedly pre-train my own dataset? How schema is set？What are the mechanisms of schema？

**Comment by linjieccc** [comment]
UIE is trained based on ernie 3.0 using a large amount of information extraction data which we called the multi-task training step. The training data format is the same as the fine-tuning step.
