### ISSUE TITLE
[Question]: 使用Taskflow进行分词时，出现E0626：Please compile with MKLDNN first to use MKLDNN

### ISSUE THREAD

**Issue by new-cainiao** [PaddlePaddle/PaddleNLP#6249]
### 请提出你的问题

本地环境：
Python 3.8.10 (v3.8.10:3d8993a744, May  3 2021, 08:55:58)
paddlenlp==2.5.1
paddlepaddle==2.4.2
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/39564677/f6c5cb6b-f998-4404-bcb0-510b6a9938a1)

使用过程：
from paddlenlp import Taskflow
 seg_accurate = Taskflow("word_segmentation", mode="accurate", task_path='./wordtag/', device_id=-1)
出现问题：
E0626 16:43:02.376854 347514368 analysis_config.cc:579] Please compile with MKLDNN first to use MKLDNN

Mac应该是无法使用MKLDNN进行推理加速的，但是本地加载分词模型（所有模型）时出现了这个问题，其中task_path就是word_segmentation模型，没有改动。
Taskflow使用MKLDNN加速的功能是不是可以手动开关

**Comment by linjieccc** [comment]
@new-cainiao Hi，这个是warning可以忽略，确认正确安装了对应mac的paddle版本即可

**Comment by new-cainiao** [comment]
@linjieccc 好的谢谢

**Comment by Lowpower** [comment]
/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
E1024 19:28:38.475243 4034977280 analysis_config.cc:630] Please compile with MKLDNN first to use MKLDNN
[2023-10-24 19:28:38,963] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/Users/shengzhiqiang/.paddlenlp/taskflow/information_extraction/uie-base'.
zsh: segmentation fault
