### ISSUE TITLE
请问一下这里的use segment_box是什么意思？xfund有相应的实现么？

### ISSUE THREAD

**Issue by aixuedegege** [PaddlePaddle/PaddleNLP#6262]
https://github.com/PaddlePaddle/PaddleNLP/blob/fda38e4e5274866cfe06e0e0d5aa18b677fb04a6/model_zoo/ernie-layout/README_ch.md?plain=1#L249

**Comment by linjieccc** [comment]
数据集中包含两种bbox，一种是字符粒度的bbox，另外一种是片段粒度的bbox（segment_box）。segment粒度对NER效果提升大

**Comment by aixuedegege** [comment]
谢谢您的回答，我可视化后看segment_box画出来的值对应不上相应的文字区域的segment，好像是硬用1000规范化后的box，但是我没有找到对应的代码能完整的将segment_box恢复到原有图片对应的文字块box，如图下面红色的bbox是一个segment_box的框，对应不到任何字块：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/19356707/9dd34449-5e5b-424d-a115-f63444dd84e5)

**Comment by aixuedegege** [comment]
@linjieccc 可以帮我再看看是什么问题么

**Comment by linjieccc** [comment]
ernie-layout输入会按照1000，1000对原始bbox进行normalization，可以根据原始图片的宽高进行还原，参考这里https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/doc_parser.py#L272

**Comment by aixuedegege** [comment]
那个是application中uie-x的数据处理逻辑，我看到了，您看一下这段ernielayout ner的处理代码[248-257行](https://github.com/PaddlePaddle/PaddleNLP/blob/e5023f7c77d6995220c0ffea9de5a08deb7f48c3/model_zoo/ernie-layout/utils.py#L248)， 我的疑问是

1、[redame](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#41-%E6%96%87%E6%A1%A3%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96%E4%BB%BB%E5%8A%A1) 中的XFUND-ZH训练下面use_segment_box是打开的，segment_box这里打开了，那取出来的应该是normalization后的segment bbox，为何下面又调用了_scale_same_as_image，这样不是做了两遍normalization了么？ 

2、你们处理xfund的segment bbox是有什么方法，是已经normalization的了吧，因为对应不上文字，如上面我提到的，这个处理过程可以开源么？ 

3、uie-x和ernielayout有什么具体区别啊，我的理解是uiex是再ernielayout上加了两个start end指针，ernielayout的问答也是这个原理么？

再次感谢您的抽空回答

**Comment by aixuedegege** [comment]
@linjieccc 可以帮我解答一下么

**Comment by linjieccc** [comment]
@aixuedegege 

1. 主要是确保用户使用自己的数据（未进行normalization的）也可以兼容，如果数据集本身已经做了normalization，可以不用重复执行_scale_same_as_image
2. 处理片段粒度的方法和_scale_same_as_image一致，可以参考下面的代码对bbox进行还原:

```python
def _normalize_box(box, old_size, new_size):
    """normalize box"""
    return [
        int(box[0] * new_size[0] / old_size[0]),
        int(box[1] * new_size[1] / old_size[1]),
        int(box[2] * new_size[0] / old_size[0]),
        int(box[3] * new_size[1] / old_size[1]),
    ]

new_box = _normalize_box(old_box, [1000, 1000], [img_w, img_h])
```
3. uie-x采用双指针解码的方式进行抽取，和ernie-layout在问答任务上的解码方式是相同的

**Comment by aixuedegege** [comment]
thanks a lot!
