### ISSUE TITLE
[Question]: UIE-X模型是否支持蒸馏和FastTokenizer？或者有没有支持其他模型压缩的方式？

### ISSUE THREAD

**Issue by Sijia-NR** [PaddlePaddle/PaddleNLP#6266]
### 请提出你的问题

https://zhuanlan.zhihu.com/p/592422623
这篇介绍文章说，UIE-X即将支持封闭域蒸馏和FastTokenizer，文章是去年发布的，现在已经支持了么，我试着用UIE的数据蒸馏去处理UIE-X,但是感觉不成功(https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/README.md)😭
1、如果现在支持封闭域蒸馏和FastTokenizer了话，哪里有参考的资料呀？
2、有没有其他模型裁剪，模型压缩的方式？有没有参考资料呀？
3、目前在CPU服务器上推理需要时间很长，一个schema中一个实体抽取需要1秒的样子，如果schema中有10个 抽一次就要10秒，比较慢。有没有一个schema中的多个实例抽取可以并行抽取的方式？
上面三个，有一个能有解决方案就好了，跪求大佬解答。。

**Comment by linjieccc** [comment]
uie-x数据蒸馏可以参考这里，可以实现所有schema并行抽取 https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain

**Comment by Sijia-NR** [comment]
> uie-x数据蒸馏可以参考这里，可以实现所有schema并行抽取 https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain

感谢，感谢，我等会试试，麻烦再问一下，uie-x的模型压缩和裁剪有能够参考的资料么？我希望加快微调后模型的推理速度，希望能够在cpu的服务器上也能够快速给出结果

**Comment by linjieccc** [comment]
当前还没有专门针对uie-x的模型压缩工作示例，你可以先尝试下数据蒸馏的方式能否满足需求，schema越多速度提升约明显
