### ISSUE TITLE
AttributeError: module 'paddlenlp.transformers' has no attribute 'ErnieGramTokenizer'

### ISSUE THREAD

**Issue by caigao** [PaddlePaddle/PaddleNLP#627]
运行：
import paddlenlp
tokenizer = paddlenlp.transformers.ErnieGramTokenizer.from_pretrained('ernie-gram-zh')

报错：
---------------------------------------------------------------------------AttributeError                            Traceback (most recent call last)<ipython-input-3-d653147d4caa> in <module>
      2 # 后续样本转换函数基于 tokenizer 对文本进行切分
      3 
----> 4 tokenizer = paddlenlp.transformers.ErnieGramTokenizer.from_pretrained('ernie-gram-zh')
AttributeError: module 'paddlenlp.transformers' has no attribute 'ErnieGramTokenizer'

**Comment by ZeyuChen** [comment]
请升级至最新版本2.0.3
pip install --upgrade paddlenlp
