### ISSUE TITLE
关于一些具体建议

### ISSUE THREAD

**Issue by myboyliu** [PaddlePaddle/PaddleNLP#628]
1.希望可以把底层的api文档再完善一些，比如encoder,decoder，以便于复现一些论文
2.希望可以维护一个pytorch和paddle的api对照一览表，尽量全一些
3.错误日志能否准确一些，有时候datalaoder出的一些错误信息不好定位
4.能否增加使用梯度累加特性，进一步提高batch size

**Comment by LiuChiachi** [comment]
您好，我先回答其中两个问题吧，2.https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/08_api_mapping/pytorch_api_mapping_cn.html#pytorch-paddlepaddle-api
4.这个据我所知是已经有的功能，您可以多个batch之后更新参数、清空梯度实现提高batch_size。如果使用的是高层API的`hapi.Model.fit`来训练的话，下个版本也会新增梯度累加的特性。

**Comment by myboyliu** [comment]
nice,paddle越来越强大了

**Comment by ZHUI** [comment]
> 1.希望可以把底层的api文档再完善一些，比如encoder,decoder，以便于复现一些论文
> 2.希望可以维护一个pytorch和paddle的api对照一览表，尽量全一些
> 3.错误日志能否准确一些，有时候datalaoder出的一些错误信息不好定位
> 4.能否增加使用梯度累加特性，进一步提高batch size

1. 文档目前的话，确实不太完善。我们也在按计划，持续完善文档中。 @yingyibiao 同学会持续跟进文档问题，可以反馈下哪些文档是比较急需的，我们可以调整优先级，完善文档。
2. 见上面回复
3. DataLoader报错的话，可以尝试打开export FLAGS_call_stack_level=2 ，查看更多报错信息。具体的case，可以单独提issue询问。
4. 同上回复。我下面给出一个简单的例子。 out.backward()产生梯度，如果不运行 optimizer.clear_grad()，梯度会默认累加之前的梯度值，实现梯度累计的效果。
```python
import paddle
import numpy as np

paddle.seed(0)
value = np.arange(26).reshape(2, 13).astype("float32")
a = paddle.to_tensor(value)
linear = paddle.nn.Linear(13, 5)
optimizer = paddle.optimizer.SGD(learning_rate=0.02,
                                 parameters=linear.parameters())
batch_acc=5
for i in range(batch_acc):
    out = paddle.mean(linear(a))
    out.backward() # 多次backward产生的梯度默认累加
optimizer.step() #参数更新
optimizer.clear_grad() #清空参数
print(paddle.mean(linear(a)))
```
