### ISSUE TITLE
paddlepaddle和paddlenlp的版本兼容性问题。

### ISSUE THREAD

**Issue by ZYD-TECH** [PaddlePaddle/PaddleNLP#6280]
### 请提出你的问题

from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！")) # Better print results using pprint
**以上是我在官方文档中找到的UIE框架示例程序，但是在我本地运行时输出结果明显不正确且每次结果均不同，我的版本信息：
paddlepaddle==2.5.0，paddlenlp==2.5.2，paddlehub==2.3.1，python==3.8
例如，在某次运行我的结果为：**
[{'选手': [{'end': 0, 'probability': 0.39528031532912067, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.40785024333310815, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.40740392789255964, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3904063453889428, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.39121997576148715, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3715034211640358, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.39082529381335007, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3825354569752335, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.41748026762970625, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.4198387829958534, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.36629768103983906, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.41318269079695824, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.34856962951070614, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.37119464334374186, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.40006078464809747, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3884037056143086, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3936295188744623, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.37776151304663586, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.35721655263342456, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.37445443352007146, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.38047034555278714, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.3527655530816389, 'start': 0, 'text': ''},
         {'end': 0, 'probability': 0.39844150842962733, 'start': 0, 'text': ''},
         {'end': 0,
          'probability': 0.3567521921089778,
          'start': 0,
          'text': ''}]}]
再次运行结果为：
[{'选手': [{'end': 29,
          'probability': 0.2737457337928433,
          'start': 27,
          'text': '手谷'},
         {'end': 24,
          'probability': 0.2872463952964779,
          'start': 23,
          'text': '中'}]}]
**不知道是版本问题还是环境原因，以往可以得到专业人员的解答，谢谢！**

**Comment by nikkyyang** [comment]
我昨天、前天也是你这样的问题 

刚刚用的   paddlenlp==2.5.2 paddlepaddle==2.4.2 python==3.8 这个已经可以正常运行

**Comment by ZYD-TECH** [comment]
@nikkyyang 非常感谢，这个版本组合是正常的，
刚换完版本后还遇到了：Process finished with exit code -1073741819 (0xC0000005)这个问题，该问题是因为依赖包版本不兼容或有损坏，建议新建一个环境install paddlenlp==2.5.2， paddlepaddle==2.4.2，最终可以复现正确输出。
