### ISSUE TITLE
参照上面官方文档，加载本地数据，出现错误

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#629]
**以内置数据集格式读取本地数据集
有的时候，我们希望使用数据格式与内置数据集相同的本地数据替换某些内置数据集的数据（例如参加SQuAD竞赛，对训练数据进行了数据增强）。 load_dataset() 方法提供的 data_files 参数可以实现这个功能。以 SQuAD 为例。
from paddlenlp.datasets import load_dataset
train_ds, dev_ds = load_dataset("squad", data_files=("my_train_file.json", "my_dev_file.json"))
test_ds = load_dataset("squad", data_files="my_test_file.json")**

参照上面官方文档，加载本地数据，出现错误
dataset_name = "chnsenticorp"
train_ds = load_dataset(dataset_name, splits="train",
                                data_files='./data/NLPCC14-SC/train.tsv')

报错
convert_example
    text=example["text"], max_seq_len=max_seq_length)
TypeError: tuple indices must be integers or slices, not str

**Comment by smallv0221** [comment]
I used the format of `chnsenticorp` to load NLPCC14-SC dataset as you did. The `load_dataset` func works well. It seems you got this exception from other part of your code.
![image](https://user-images.githubusercontent.com/33639025/123371543-8ceb6a00-d5b4-11eb-802c-e489664bdf31.png)

**Comment by AI-Mart** [comment]
是可以加载，但是启动训练直接报错，我想表达的是数据正确加载后，一键启动训练，不要出现其他的错误



PaddleNLP/examples/sentiment_analysis/skep/train_sentence.p
报错
convert_example
text=example["text"], max_seq_len=max_seq_length)
TypeError: tuple indices must be integers or slices, not str

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 参照上面官方文档，加载本地数据，出现错误 (#629)





 
I used the format of chnsenticorp to load NLPCC14-SC dataset as you did. The load_dataset func works well. It seems you got this exception from other part of your code.

**Comment by smallv0221** [comment]
I changed train dataset as you did and blocked all the dev code. Didn't see your exception in `convert_example`. 
![image](https://user-images.githubusercontent.com/33639025/123395681-0eea8b80-d5d3-11eb-94e3-00cf3f5023d7.png)
![image](https://user-images.githubusercontent.com/33639025/123395706-190c8a00-d5d3-11eb-906a-eb4796c92ad2.png)
![image](https://user-images.githubusercontent.com/33639025/123395729-1e69d480-d5d3-11eb-9c02-d74552d80813.png)
![image](https://user-images.githubusercontent.com/33639025/123395770-275aa600-d5d3-11eb-8d43-a28a6b771e52.png)

**Comment by AI-Mart** [comment]
我，没有屏蔽dev code，而是把 train_ds 直接赋值给dev_ds了，测试下能否跑通




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 参照上面官方文档，加载本地数据，出现错误 (#629)





 
I changed train dataset as you did and blocked all the dev code. Didn't see your exception in convert_example.

**Comment by smallv0221** [comment]
My guess is that you used code like `dev_ds=train_ds`, which is a copy instead of deepcopy. So there is only one dataset in memory with two names `train_ds` and `dev_ds`. When the program start to process `dev_ds`, it is actually processing `train_ds` again. That is why `convert_example` raise a exception since the data inside has already changed. The code below works fine.

![image](https://user-images.githubusercontent.com/33639025/123397734-52de9000-d5d5-11eb-8e52-8a0312f4840c.png)
![image](https://user-images.githubusercontent.com/33639025/123397757-5bcf6180-d5d5-11eb-9e59-55beaf37905b.png)

**Comment by AI-Mart** [comment]
好吧，确实是这样的，应该要深拷贝不能直接赋值，疏忽了，那就是支持的，paddle干得漂亮，希望越来越火越来越完善！
开发手册一定要越详细越好啊，多举一些例子。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] 参照上面官方文档，加载本地数据，出现错误 (#629)





 
My guess is that you used code like dev_ds=train_ds, which is a copy instead of deepcopy. So there is only one dataset in memory with two names train_ds and dev_ds. When the program start to process dev_ds, it is actually processing train_ds again. That is why convert_example raise a exception since the data inside has already changed. The code below works fine.

**Comment by smallv0221** [comment]
Thanks! We will do our best.
