### ISSUE TITLE
[Question]: 支持chatglm2 模型吗

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#6295]
### 请提出你的问题

有paddle版的 chatglm2 模型吗

**Comment by BrightXiaoHan** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/6290
好像这个功能已经merge了，不知道能不能用

**Comment by xieyu0214** [comment]
> #6290 好像这个功能已经merge了，不知道能不能用

谢谢，看到了。看起来还不支持基于微调，只是推理。

**Comment by sijunhe** [comment]
已支持，见https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/chatglm
