### ISSUE TITLE
[Question]: 事件抽取如何定义label_map.json,我没有在uie和uie_slim找到示例

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#6297]
### 请提出你的问题

事件抽取如何定义label_map.json,我没有在uie和uie_slim找到示例

**Comment by linjieccc** [comment]
你好~label_maps.json会根据你定义的schema自动生成，参考https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/data_distill/data_distill.py#L35
