### ISSUE TITLE
[Question]: 文档实体抽取中 det检测区文本区域没有问题， 但ocr会漏检识别区域前几个文字

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleNLP#6304]
### 请提出你的问题

文档实体抽取中 det检测区文本区域没有问题， 但ocr会漏检识别区域前几个文字 ：如下所以 开户核准号 前几个字符遗漏
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/679a271f-f7e0-43d3-a22d-251f4e24e7c9)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/d0f0f3f9-4034-4c58-9fba-1c4a2762daa7)

**Comment by linjieccc** [comment]
@whisky-12 可以检查下标注产生的训练数据集的正确性，当前的训练数据集是通过label-studio与ocr的bbox取交集生成的，标注给的bbox位置或者文本片段存在中英文混合的情况都有可能引入误差，当前建议根据自定场景微调这部分计算逻辑 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/utils/tools.py#L321

**Comment by tianchiguaixia** [comment]
传入付费的ocr结果可以很好解决这个问题
