### ISSUE TITLE
[ppdiffuser]支持controlnet与lora的图生图的pipeline类

### ISSUE THREAD

**Issue by aceyw** [PaddlePaddle/PaddleNLP#6319]
### Feature request

有没有class或者demo代码，使同时支持lora+control+文本提示+图片引导的生图的推理方法。谢谢

### Motivation

最大最全组合的AIGC功能

### Your contribution

stable-diffusion-webui支持这样的组合功能

**Comment by JunnYu** [comment]
你可以试一下这个，
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/examples/community/stable_diffusion_mega.py，
更多可以参考这个https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/deploy/controlnet/infer_dygraph.py的推理调用
```python
from ppdiffusers import DiffusionPipeline
controlnet = xxxx
pipe = DiffusionPipeline.from_pretrained(
        "xxxxx",
        controlnet=controlnet,
        safety_checker=None,
        feature_extractor=None,
        requires_safety_checker=False,
        paddle_dtype=paddle_dtype,
        custom_pipeline="stable_diffusion_mega",
    )
pipe.change_scheduler("ddim")
# 这个lora加载是临时的，之后会更新一下用prompt加载lora的方法
pipe.apply_lora("xxxx.safetensors")
# 调用
pipe.text2img(xxxxxx)
pipe.img2img(xxxxxx)
pipe.inpaint_legacy(xxxxxx)
```

**Comment by ViewWholeWorld** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/ppdiffusers/deploy/controlnet/infer_dygraph.py的推理调用

请问有加载多个 LoRA 和在 prompt 中动态切换的示例代码么？
