### ISSUE TITLE
paddle数据加载的一些建议

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#632]
paddle的案例已经足够丰富，要在业界落地最快的方式，就是把现有的数据集弄成和案列的数据集格式一致，然后本地加载，其他什么都不动直接开始训练，调参就好。尽量不要陷入内部底层的数据预处理中去，各种自定义数据读取，那样的话这些高阶的API集没意义了，大家还是没从数据中解放出来，花更多的时间去调参，模型比对，优化。
比如官方默认加载内置数据集
train_ds, dev_ds = load_dataset('chnsenticorp', splits=["train", "dev"])
换成本地的数据，按内置的格式加载应该如下所示只要添加一行data_files='./data/NLPCC14-SC/train.tsv就可以了，其他什么都不用动，可以完全兼容内置的方式训练，出结果，这样是最便捷的了，能把大家从繁琐的数据预处理中解放出来，花更多的时间去调参，模型比对，优化。目前情况是换成本地的文件，训练过程会出现各种报错和不匹配。
train_ds, dev_ds = load_dataset('chnsenticorp', splits=["train", "dev"]， data_files='./data/NLPCC14-SC/train.tsv )
希望能采纳，谢谢

**Comment by smallv0221** [comment]
`train_ds, dev_ds = load_dataset('chnsenticorp', splits=["train", "dev"]， data_files='./data/NLPCC14-SC/train.tsv )`

Sorry the code above didn‘t work. Because that `splits` and 'data_flies' should one-to-one correspondence so that you can specify the format of each file. You can also use default format which is train by not setting `splits`. 
The correct code should be `train_ds = load_dataset('chnsenticorp', splits="train"， data_files='./data/NLPCC14-SC/train.tsv )`

**Comment by AI-Mart** [comment]
The correct code should be&nbsp;train_ds = load_dataset('chnsenticorp', splits="train"， data_files='./data/NLPCC14-SC/train.tsv )

我可能没描述清楚，这样是可以加载，但是启动训练报错了，我想要表达的是，数据一键加载，直接训练，后面不会报错。



报错
convert_example
text=example["text"], max_seq_len=max_seq_length)
TypeError: tuple indices must be integers or slices, not str
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] paddle数据加载的一些建议 (#632)





 
train_ds, dev_ds = load_dataset('chnsenticorp', splits=["train", "dev"]， data_files='./data/NLPCC14-SC/train.tsv )
 
Sorry the code above didn‘t work. Because that splits and 'data_flies' should one-to-one correspondence so that you can specify the format of each file. You can also use default format which is train by not setting splits.
 The correct code should be train_ds = load_dataset('chnsenticorp', splits="train"， data_files='./data/NLPCC14-SC/train.tsv )
