### ISSUE TITLE
AI Studio易用性建议

### ISSUE THREAD

**Issue by shoran-stone** [PaddlePaddle/PaddleNLP#633]
1.关于操作:
①对notebook界面放大进入编辑模式，光标指向位置错误，实际输入位置和当前光标所在位置不一。
②建议出一个类似pycharm的编辑工具集成在AI Studio平台。
2.关于代码：
①对于执行后更新参数再执行过程，会丢失执行结果重新执行；只能手动添加断点续训，没有连接上一次执行后参数自动执行操作，建议可以将其添加到代码上更便捷。
②对于分布式训练，建议设置一些代码的参数窗口，对于多卡并行操作更便捷。
希望paddle生态越来越大，代码封装越做越好。

**Comment by wawltor** [comment]
您好，谢谢您对PaddlePaddle的支持！
1. 操作问题主要看起来是在AI Studio， 我们来反馈给AI Studio进行优化。
2. 断点续跑这块确实是个强需求，我们内部讨论一下断点续跑的方案，等有方案后我们反馈给您。
3. 您说的 "建议设置一些代码的参数窗"，没有太明白其中的含义，麻烦详细说明一下了。

@ shoran-stone
