### ISSUE TITLE
[Question]: import PaddleNLP 2.6.0rc0.post0之后报错

### ISSUE THREAD

**Issue by VBPython** [PaddlePaddle/PaddleNLP#6341]
### 请提出你的问题

在ai studio上，以PaddlePaddle-GPU 2.5.0和PaddleNLP 2.6.0rc0.post0为环境，
运行：
import paddlenlp
print(paddlenlp.__version__)

报错如下：
No module named 'custom_setup_ops'
感觉是不兼容的问题。

**Comment by w5688414** [comment]
安装最新的源代码：

```
pip install git+https://github.com/PaddlePaddle/PaddleNLP.git 
```
