### ISSUE TITLE
在用ai studio平台跑程序时，一直报错

### ISSUE THREAD

**Issue by rela0426** [PaddlePaddle/PaddleNLP#635]
Ai studio：https://aistudio.baidu.com/studio/project/partial/verify/2122019/68278d531767461786dff5cf2dd64413

我的代码在ai studio平台运行时，执行到bash run_duee_1.sh trigger_train语句时一直报错。之前训练集为中文时没问题，我换了其他语言的数据集进行训练，就出错了。报错信息如下：
```
<class 'paddle.fluid.reader.DataLoader'>
2021-06-25 14:48:46,173 - WARNING - DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "sequence_labeling.py", line 312, in <module>
    do_train()
  File "sequence_labeling.py", line 219, in do_train
    for idx, (input_ids, token_type_ids, seq_lens, labels) in enumerate(train_loader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

INFO 2021-06-25 14:48:53,114 launch_utils.py:307] terminate all the procs
ERROR 2021-06-25 14:48:53,134 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-06-25 14:48:56,138 launch_utils.py:307] terminate all the procs
end DuEE1.0 trigger train
```
求帮忙～多谢～

**Comment by Steffy-zxf** [comment]
@rela0426 你好！经过调试，发现是label在转id的时候出错，原因是，在读入tag_path文件的时候，没有去掉末尾的空格符号。可以去掉tag_path文件每行末尾的空格符。BTW，可以通过设置export FLAGS_call_stack_level=2打开出错信息堆栈显示。

另外发现目前crf的用法不是最新的用法，最新用法参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/run_ernie_crf.py
使用CRF时，对label进行padding处理的时候，不要用负值进行padding，用label中的’O‘ tag padding，参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/waybill_ie/run_ernie_crf.py#L87
