### ISSUE TITLE
机器同传平台测试结果

### ISSUE THREAD

**Issue by chenyu-2020** [PaddlePaddle/PaddleNLP#640]
按照磊子老师的指导本地实现了机器同传的demo：

[https://github.com/chenyu-2020/PaddleNLP/blob/develop/%E5%90%8C%E4%BC%A01.png](url)

[https://github.com/chenyu-2020/PaddleNLP/blob/develop/%E5%90%8C%E4%BC%A02.png](url)

请老师看看是否有用。

**Comment by chenxiaozeng** [comment]
非常好！可以把搭建demo的心得在论坛上分享出来哦~https://aistudio.baidu.com/paddle/forum/topic/list?boardId=222

**Comment by chenyu-2020** [comment]
已分享。谢谢老师鼓励！
https://aistudio.baidu.com/paddle/forum/topic/show/989124
