### ISSUE TITLE
[Bug]: doccano.py脚本划分数据集有bug

### ISSUE THREAD

**Issue by zzwtop1** [PaddlePaddle/PaddleNLP#6416]
### 软件环境

```Markdown
- paddlepaddle:2.4.1
- paddlepaddle-gpu: 
- paddlenlp: 2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
做uie模型微调，使用doccano.py脚本划分数据集，生成的prompt压根与这条数据没有一点关系，不知道什么原因
```

### 稳定复现步骤 & 代码

操作文档：[https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie](url)

**Comment by tingaicompass** [comment]
看一下有没有标注，有些是负样本策略生成的，有些是真实样本含标注信息

**Comment by zzwtop1** [comment]
那应该就是负样本了，没有标注位置
