### ISSUE TITLE
paddlenlp 2.0.4最新版本bug,升级版本记得测试没问题在发布哈

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#649]
运行 PaddleNLP/ examples / text_matching / ernie_matching / train_pointwise.py 
报错
![image](https://user-images.githubusercontent.com/63343847/123537294-42f3b700-d761-11eb-906e-6affbd12e83b.png)

paddlenlp降级为2.0.3运行正常

**Comment by libertatis** [comment]
我也遇到了这种情况，该异常官方已经提交 `PR` 修复了。暂时先使用 `paddlenlp 2.0.3` 吧。如果你是在 `AIStudio` 运行，那行更新 `paddlenlp` 的代码可替换成 `pip install paddlenlp==2.0.3` 执行~

**Comment by libertatis** [comment]
现在 `paddlenlp` 已经升级到 `2.0.5` 版本啦！这个 `bug` 官方已经修复啦！可以放心升级使用啦~

**Comment by ZeyuChen** [comment]
可以通过`pip install --upgrade paddlenlp`升级到2.0.5版本解决2.0.4引入的问题。感谢反馈！@AI-Mart @libertatis
