### ISSUE TITLE
AI Studio中Fork的项目如何挂载自定义数据集

### ISSUE THREAD

**Issue by Shuai-GAO** [PaddlePaddle/PaddleNLP#650]
我想基于中英文本自动翻译系统这个公开的项目，挂载自己的数据集，做其他语言的翻译系统。但是发现Fork后无法设置数据集挂载。

于是我重新建立项目，挂载数据集后，又发现无法单独clone Transformer的目录。必须整个将PaddleNLP的repo clone下来，未免有点过于不方便。

希望之后能实现Fork的项目可以自定义设置数据集。

感谢。

**Comment by livingbody** [comment]
觉得可以自己本地clone，然后单独压缩包上传所需部分

**Comment by chenxiaozeng** [comment]
您好，AI Studio上可以在项目中，启动环境前，点修改，挂数据集
