### ISSUE TITLE
aistudio checkpoints文件夹打不开问题

### ISSUE THREAD

**Issue by ITerydh** [PaddlePaddle/PaddleNLP#651]
在进行情感分析的任务的时候，生成的checkpoints文件夹点击之后打不开，会弹窗（con`t read property 'length' of undefined），但是在终端使用命令ls是可以看到东西的,并且不影响后续使用，项目见https://aistudio.baidu.com/aistudio/projectdetail/2104045

**Comment by ITerydh** [comment]
悟了，GT大佬说是，这个checkpoints单词被底层占用了，不过还是希望，声明一下，不然真的不知道是为啥出现这个情况。

**Comment by ZeyuChen** [comment]
@ITerydh 是否可以升级到最新的2.0.5版本后重新运行下试试，然后可否发更详细的错误日志出来？具体到哪行代码？

**Comment by ITerydh** [comment]
没有，不是代码问题，就是这个词被占用了吧，运行项目后，生成checkpoints这个文件夹之后，点击checkpoints这个文件夹，就会弹窗（con`t read property 'length' of undefined），然后我用的是AIstudio的paddle环境的2.0.2

**Comment by ITerydh** [comment]
这个问题不影响代码的流程，就是单纯的点击之后无法打开文件夹了，只能去终端用linux命令查看这个文件夹的详情。

**Comment by ITerydh** [comment]
![错误图片](https://github.com/ITerydh/PaddleNLP-emotion-analysis/blob/main/QQ%E5%9B%BE%E7%89%8720210628125210.png)
