### ISSUE TITLE
[Question]: SimpleServing 的服务化部署后，服务端报 Unable to serialize unknown type

### ISSUE THREAD

**Issue by zailushang1** [PaddlePaddle/PaddleNLP#6517]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/9928369/09bf8b02-4ade-4e0a-9ffa-3f93e42198fc)

**Comment by xpfo-go** [comment]
我也是！

**Comment by xpfo-go** [comment]
> 我也是！



> 
paddlenlp==2.5.2
paddlepaddle==2.4.2

**Comment by yizhixiaoxiaogou** [comment]
我也是paddlenlp 升级到了2.6.0rc0，还是这样，求指导哇

**Comment by tingaicompass** [comment]
这个问题我之前也遇到了，解决方案是降级里面一个依赖库。你比对一下老版本和新版本区别，具体依赖库名称不记得了

**Comment by xpfo-go** [comment]
我得解决方案是把predict.py改造一下，改成web了.....麻烦一些

**Comment by zailushang1** [comment]
> 这个问题我之前也遇到了，解决方案是降级里面一个依赖库。你比对一下老版本和新版本区别，具体依赖库名称不记得了

非常感谢！ 将fastapi 版本从 0.100.1 改 0.97.0 问题解决
