### ISSUE TITLE
快递单信息抽取本质是一个序列标注任务求解

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#652]
快递单信息抽取本质是一个序列标注任务，训练数据是按字标注的，为啥预测结果不按字标注？

**Comment by livingbody** [comment]
比如说训练集：
text_a	label
16620200077宣荣嗣甘肃省白银市会宁县河畔镇十字街金海超市西行50米	T-BT-IT-IT-IT-IT-IT-IT-IT-IT-IT-IP-BP-IP-IA1-BA1-IA1-IA2-BA2-IA2-IA3-BA3-IA3-IA4-BA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-IA4-I
13552664307姜骏炜云南省德宏傣族景颇族自治州盈江县平原镇蜜回路下段	T-BT-IT-IT-IT-IT-IT-IT-IT-IT-IT-IP-BP-IP-IA1-BA1-IA1-IA2-BA2-IA2-IA2-IA2-IA2-IA2-IA2-IA2-IA2-IA3-BA3-IA3-IA4-BA4-IA4-IA4-IA4-IA4-IA4-IA4-I
内蒙古自治区赤峰市阿鲁科尔沁旗汉林西街路南13701085390那峥	A1-BA1-IA1-IA1-IA1-IA1-IA2-BA2-IA2-IA3-BA3-IA3-IA3-IA3-IA3-IA4-BA4-IA4-IA4-IA4-IA4-IT-BT-IT-IT-IT-IT-IT-IT-IT-IT-IT-IP-BP-I
广东省梅州市大埔县茶阳镇胜利路13601328173张铱	A1-BA1-IA1-IA2-BA2-IA2-IA3-BA3-IA3-IA4-BA4-IA4-IA4-IA4-IA4-IT-BT-IT-IT-IT-IT-IT-IT-IT-IT-IT-IP-BP-I

我想预测结果也是这样

**Comment by libertatis** [comment]
预测完以后，后面不是得需要解码吗？比如你对‘广东省’进行标注，我们知道它是一个地名，对它进行标注，它的标签应该是'LOC'，你总不能标注'LOC-B LOC-I LOC-I' 或者'LOC-B LOC-I LOC-E'吧。如果我不事先知道你的编码方案，我怎么知道你这是啥呀。你在模型评估的时候，可以用这个计算它的准确率，召回率和F值，但是，预测完以后，你得告诉我哪个名词的命名实体类型是啥吧。就像你做抽取式阅读理解任务，预测完以后你不能只返回答案在文中的开始和结束位置，你得告诉用户答案是啥！预测阶段不光是计算模型在测试集上的评价指标如何，后续还有一个解码过程~

**Comment by livingbody** [comment]
明白
