### ISSUE TITLE
[Question]: 请问一下现在PaddleNLP支持Ernie大模型嘛

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/PaddleNLP#6522]
### 请提出你的问题

请问一下现在PaddleNLP支持12B的Ernie模型嘛，想要看看能不能把12B的模型放到PaddleNLP的框架下。

**Comment by wawltor** [comment]
您好，目前ERNIE 12B模型暂无开源计划，暂且不会放到PaddleNLP上

**Comment by Fordacre** [comment]
@wawltor 厂内用户如果已有12B模型的话有办法直接复用PaddleNLP的框架嘛。

**Comment by wawltor** [comment]
> @wawltor 厂内用户如果已有12B模型的话有办法直接复用PaddleNLP的框架嘛。

公司内部12B ERNIE模型是静态模型并且进行了加密，PaddleNLP对加密后的模型进行支持的成本高

**Comment by Fordacre** [comment]
> > @wawltor 厂内用户如果已有12B模型的话有办法直接复用PaddleNLP的框架嘛。
> 
> 公司内部12B ERNIE模型是静态模型并且进行了加密，PaddleNLP对加密后的模型进行支持的成本高

okay，了解，多谢啦。
