### ISSUE TITLE
停词表stopwords是不是也可以合并进来？

### ISSUE THREAD

**Issue by livingbody** [PaddlePaddle/PaddleNLP#653]
如题：停词表stopwords是不是也可以合并进来？

**Comment by wawltor** [comment]
> 如题：停词表stopwords是不是也可以合并进来？

您好，能不能提供一下具体的使用场景或者任务了？

**Comment by livingbody** [comment]
比如我要做词频统计，画画词云啥的。

**Comment by wawltor** [comment]
> 比如我要做词频统计，画画词云啥的。

您好，意思是说能提供一份通用的停用词表到paddlenlp？

**Comment by livingbody** [comment]
嗯嗯，合适不，这个放进来，

**Comment by wawltor** [comment]
> 嗯嗯，合适不，这个放进来，

嗯嗯 我们内部讨论一下，有信息后续我们反馈给您 如果需要放进去的话，个人觉得通过一些全局变量方式呈现出来更好，而不是一个文件词表。
