### ISSUE TITLE
【论文复现】Tree of Thoughts

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/PaddleNLP#6543]
## 背景
ToT允许LMs通过考虑多个不同的推理路径和自我评估选择来进行深思熟虑的决策，以决定下一步行动，并在必要时前瞻或回溯以做出全局选择。我们的实验表明，ToT显著提高了语言模型在三项需要非琐碎计划或搜索的新任务上的解决问题能力：24小时游戏、创意写作和迷你交叉词。例如，在《24小时游戏》中，具有思维链提示的GPT-4只解决了4%的任务，而我们的方法的成功率为74%。
Tree of Thoughts: Deliberate Problem Solving with Large Language Models

## 解决步骤：
1.仿照ReAct的方式集成到pipelines里面，并评估跟论文精度一致。论文链接：https://github.com/princeton-nlp/tree-of-thought-llm
2.接入开源模型例如chatglm v2或者llama v2，并给出TOT的使用示例和文档。提交至https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/agents

**Comment by ErnestinaQiu** [comment]
报名
