### ISSUE TITLE
[Question]: partiapartially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

### ISSUE THREAD

**Issue by balcony021** [PaddlePaddle/PaddleNLP#6557]
### 请提出你的问题

paddlepaddle 2.5.0版本，
conda 安装 paddlenlp 2.5.2版本，
上周五运行似乎还正常，
今天开始，
from paddlenlp import Taskflow  时，
报错：
partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by sijunhe** [comment]
您好，我在当前develop版本没有遇到这个问题，建议您尝试升级到当前develop版本试试

**Comment by jerryandjune** [comment]
我更新了charset-normalizer就解决了这个问题
pip install --upgrade charset-normalizer --user
