### ISSUE TITLE
LAC模型，增量训练自定义标签LABEL

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#657]
模型中只有，PER ORG LOC TIME四种实体类别，我希望在此基础上增加新的自定义标签，比如训练医疗数据集，存在疾病DISEASE，治疗TREATMENT，药物MEDICINE等实体标签，这种可以实现吗？

**Comment by ZeyuChen** [comment]
可以的，只需要修改下CRF的标签数即可训练。

**Comment by ZeyuChen** [comment]
更新一下tag.dict文件即可。
https://github.com/PaddlePaddle/PaddleNLP/blob/e9b3ac67c00cff028965a49a8042c89a0c64a281/examples/lexical_analysis/train.py#L77

**Comment by tom-tangqs** [comment]
> 可以的，只需要修改下CRF的标签数即可训练。
就是这个CRF的标签修改，在哪个位置呀，我没有找到呢

**Comment by tom-tangqs** [comment]
谢谢解答，修改CRF的标签是在哪个文件？我没有找到呢
