### ISSUE TITLE
[Bug]: 单卡微调gpt-3模型，出现GPTTrainer获取不到dp_group

### ISSUE THREAD

**Issue by sxl1993** [PaddlePaddle/PaddleNLP#6575]
### 软件环境

```Markdown
- paddlepaddle:2.5.0
- paddlepaddle-xpu: 2.5.0
- paddlenlp: 2.6.0rc0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
单卡微调时，通过paddle.distributed.get_world_size()获取world_size的值为1，
无法对dp_group属性进行赋值。只有当world_size大于1时，才会赋值。
导致保存模型参数时，会找不到属性报错。
[图片]
```

### 稳定复现步骤 & 代码

export PYTHONPATH="../../PaddleNLP/"

log_dir="log"
rm -rf $log_dir

python3 -m paddle.distributed.launch \
    --xpus "0" \
    --log_dir ${log_dir} \
    finetune_generation.py \
    --model_type "gpt" \
    --model_name_or_path gpt2-medium-en \
    --output_dir "output/$task_name" \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --tensor_parallel_degree 1 \
    --pipeline_parallel_degree 1 \
    --scale_loss 1024 \
    --learning_rate 0.00001 \
    --max_steps 10000 \
    --save_steps 5000 \
    --weight_decay 0.01 \
    --warmup_ratio 0.01 \
    --max_grad_norm 1.0 \
    --logging_steps 1\
    --dataloader_num_workers 1 \
    --sharding "stage2" \
    --max_evaluate_steps 1000 \
    --eval_steps 1000 \
    --report_to "visualdl" \
    --disable_tqdm true \
    --recompute 1 \
    --gradient_accumulation_steps 2 \
    --do_train \
    --do_eval \
    --device "xpu"
执行以上代码，问题必现。
解决方案：可以在获取属性之前，通过hasattr判断属性是否存在。

**Comment by ZHUI** [comment]
你贴一下 报错吧。
