### ISSUE TITLE
LAC增量训练

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#658]
你好，我刚才询问关于LAC模型，增量训练自定义标签，修改CRF标签数这个操作是在哪个文件呢，我没有找到呢

**Comment by wawltor** [comment]
<img width="470" alt="图片" src="https://user-images.githubusercontent.com/16698950/123604627-98959580-d82d-11eb-908f-1a61c4def2c7.png">
https://github.com/PaddlePaddle/PaddleNLP/blob/ccd3557f572bc8150e5f8c13392455a0b2889530/examples/lexical_analysis/train.py#L121  

在训练代码中会根据label_vocab的大小自动设置标签数

**Comment by chenxiaozeng** [comment]
#662
