### ISSUE TITLE
[Question]: AttributeError: type object 'DataLoader' has no attribute 'from_generator'

### ISSUE THREAD

**Issue by yz8654773** [PaddlePaddle/PaddleNLP#6595]
### 请提出你的问题

版本信息
paddlenlp                    2.5.2
paddlepaddle-gpu             2.5.1.post120
错误：AttributeError: type object 'DataLoader' has no attribute 'from_generator'

感觉 2.5 的paddlepaddle，bug挺多的！gpu版的 paddlehub 也用不了

**Comment by sijunhe** [comment]
您好。这个bug我们应该在当前develop修过了，可以安装develop版本，或者2.6.0rc

**Comment by iamxinxin** [comment]
您好,安装最新版还是有这个问题哎
版本信息：
paddlenlp          2.6.0.post0
paddlepaddle-gpu   0.0.0.post116
paddlepaddle 2.5.1也试了，一样报错

    self.dataloader = paddle.io.DataLoader.from_generator(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DataLoader' has no attribute 'from_generator'

**Comment by sijunhe** [comment]
> 您好,安装最新版还是有这个问题哎 版本信息： paddlenlp 2.6.0.post0 paddlepaddle-gpu 0.0.0.post116 paddlepaddle 2.5.1也试了，一样报错
> 
> ```
> self.dataloader = paddle.io.DataLoader.from_generator(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> AttributeError: type object 'DataLoader' has no attribute 'from_generator'

您好，很抱歉paddle框架的升级给您造成了困扰！
PaddleNLP库内应该是没有再使用 `paddle.io.DataLoader.from_generator` 这个 api了，一些老的代码使用的是`paddle.fluid.reader.DataLoader.from_generator`, 这个在paddle 2.5.1是ok的

**Comment by iamxinxin** [comment]
> > 您好,安装最新版还是有这个问题哎 版本信息： paddlenlp 2.6.0.post0 paddlepaddle-gpu 0.0.0.post116 paddlepaddle 2.5.1也试了，一样报错
> > ```
> > self.dataloader = paddle.io.DataLoader.from_generator(
> >                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > AttributeError: type object 'DataLoader' has no attribute 'from_generator'
> 
> 您好，很抱歉paddle框架的升级给您造成了困扰！ PaddleNLP库内应该是没有再使用 `paddle.io.DataLoader.from_generator` 这个 api了，一些老的代码使用的是`paddle.fluid.reader.DataLoader.from_generator`, 这个在paddle 2.5.1是ok的

问题解决了，感谢回复~
