### ISSUE TITLE
变量名错误

### ISSUE THREAD

**Issue by l99500** [PaddlePaddle/PaddleNLP#66]
发现一个小错误
PaddleNLP/examples/text_matching/sentence_transformers/train.py /
上面的line40 parser.add_argument里面是warmup_proption，下面line237是args.warmup_proportion。

**Comment by Steffy-zxf** [comment]
你好！感谢反馈！该问题将在 pr：https://github.com/PaddlePaddle/PaddleNLP/pull/54/commits/56ade3bb8808ae94974bc6cb7f9d483b6e484e9d 修复

**Comment by ZeyuChen** [comment]
Latest code solve this issues. @l99500
