### ISSUE TITLE
[Question]: llm/ernie-3.5-se 模型支持问题

### ISSUE THREAD

**Issue by woshildh** [PaddlePaddle/PaddleNLP#6605]
### 请提出你的问题

Hi,
我在https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/ernie-3.5-se 看到了ernie-3.5 的文档，请问现在 ernie-3.5 的预训练模型在 paddlenlp 上对外开放了吗? 我通过如下代码调用的时候发现会报错
```
import paddlenlp 

# 加载ERNIE预训练模型
MODEL_NAME = "baidu/ernie-3.5-se-3b"
ernie_model = paddlenlp.transformers.ErnieModel.from_pretrained(MODEL_NAME)
```

**Comment by ZHUI** [comment]
目前还没有放出模型权重，抱歉。
