### ISSUE TITLE
LAC自定义标签训练

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#662]
LAC模型识别实体，增加一些新的标签LABEL，更新tag.dic，从重新开始训练了吗，不能使用预训练模型接着训练吗？
重新训练的数据集格式是PER-B  PER-I
增量训练的数据集格式是 姚明/PER
所以新增标签的训练方式要使用哪一种呢？

**Comment by joey12300** [comment]
你好，可以提供部分的新增样例数据吗？并且您所指的重新训练是指在现有的lac数据集上训练后，再加数据以及数据标签，再开始训练吗？

**Comment by tom-tangqs** [comment]
lac模型现有PER  LOC  ORG  TIME，我们希望增加一些实体的数据标签，比如新增加医疗数据，就会包含疾病DISEASE   药品MEDICINE等标签，这时候我们要更新tag.dic文件的标签，增加一些新标签，然后怎么训练呢，如果使用LAC的预训练模型，那输出的维度就不一样了

**Comment by joey12300** [comment]
@tom-tangqs 
您的问题主要有两个：
1. 如何添加标签、数据样本。
2. 如何使用预训练模型对新增数据集继续训练。

### 添加标签、数据样本

首先，新增数据集标签必须要使用PER-B这样的格式。比如说你提供的新样本是`肝癌 DISEASE`，要处理成`肝\002癌 DISEASE-B\002DISEASE-I`。


### 训练方法
![image](https://user-images.githubusercontent.com/10826371/123897741-85520980-d996-11eb-989b-40d181d7b8b2.png)

上图为LAC任务中所用的BiGruCrf模型。对于lac任务，实际上是通过BiGRU模型抽取序列特征，再接入FC层和CRF层进行Token分类。与标签数相关的仅仅是FC层和CRF层，而Embedding层和BiGRU层**与标签数无关**。所以新增标签再训练，FC层和CRF层的参数不可以加载预训练的参数，而Embedding参数和BiGRU参数可以基于预训练模型的参数继续训练。

**Comment by tom-tangqs** [comment]
这样我训练是通过examples\lexical_analysis\train.py进行训练吗？我加入新的数据标签后，运行train.py进行训练，这种就不是基于预训练模型进行的训练了。

基于预训练模型的流程介绍里，是加载的lac模型，进行的增量训练
![image](https://user-images.githubusercontent.com/51399899/123913195-81cb7c00-d9b0-11eb-9f52-e3de15944ab7.png)
它是加载预训练模型的fc_0.b_0等文件后继续训练

**Comment by bigvine2** [comment]
> 
> 
> @tom-tangqs
> 您的问题主要有两个：
> 
>     1. 如何添加标签、数据样本。
> 
>     2. 如何使用预训练模型对新增数据集继续训练。
> 
> 
> ### 添加标签、数据样本
> 
> 首先，新增数据集标签必须要使用PER-B这样的格式。比如说你提供的新样本是`肝癌 DISEASE`，要处理成`肝\002癌 DISEASE-B\002DISEASE-I`。
> ### 训练方法
> 
> ![image](https://user-images.githubusercontent.com/10826371/123897741-85520980-d996-11eb-989b-40d181d7b8b2.png)
> 
> 上图为LAC任务中所用的BiGruCrf模型。对于lac任务，实际上是通过BiGRU模型抽取序列特征，再接入FC层和CRF层进行Token分类。与标签数相关的仅仅是FC层和CRF层，而Embedding层和BiGRU层**与标签数无关**。所以新增标签再训练，FC层和CRF层的参数不可以加载预训练的参数，而Embedding参数和BiGRU参数可以基于预训练模型的参数继续训练。

我们看工程里面的训练都是直接加载全部预训练模型的参数，paddle可以有选择地加载预训练模型的指定层的参数吗？

**Comment by tom-tangqs** [comment]
> > @tom-tangqs
> > 您的问题主要有两个：
> > ```
> > 1. 如何添加标签、数据样本。
> > 
> > 2. 如何使用预训练模型对新增数据集继续训练。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 添加标签、数据样本
> > 首先，新增数据集标签必须要使用PER-B这样的格式。比如说你提供的新样本是`肝癌 DISEASE`，要处理成`肝\002癌 DISEASE-B\002DISEASE-I`。
> > ### 训练方法
> > ![image](https://user-images.githubusercontent.com/10826371/123897741-85520980-d996-11eb-989b-40d181d7b8b2.png)
> > 上图为LAC任务中所用的BiGruCrf模型。对于lac任务，实际上是通过BiGRU模型抽取序列特征，再接入FC层和CRF层进行Token分类。与标签数相关的仅仅是FC层和CRF层，而Embedding层和BiGRU层**与标签数无关**。所以新增标签再训练，FC层和CRF层的参数不可以加载预训练的参数，而Embedding参数和BiGRU参数可以基于预训练模型的参数继续训练。
> 
> 我们看工程里面的训练都是直接加载全部预训练模型的参数，paddle可以有选择地加载预训练模型的指定层的参数吗？

是啊，纠结的就是这个，如果不能选择性的加载指定层，我现在新增数据标签就用不了预训练模型了，只能修改标签然后从头训练了

**Comment by joey12300** [comment]
@tom-tangqs @bigvine2 理解两位意思了。如果是静态图的话，你的参数目录my_lac_model下，应该会有以crf和fc命名的对应的参数文件，删除后加载参数就不会把这两层加载进来了。如果是动态图的话，在使用paddle.load加载参数的state_dict后，把dict对应的crf和fc的items给删掉，就不会加载这两层的参数了。

**Comment by tom-tangqs** [comment]
![image](https://user-images.githubusercontent.com/51399899/124058321-bcd6b980-da5b-11eb-90e2-d21e896eb111.png)
这样删掉crf和fc的文件吗？这样会报错
![image](https://user-images.githubusercontent.com/51399899/124058359-d1b34d00-da5b-11eb-84a4-8ce7424de09b.png)

**Comment by wawltor** [comment]
> ![image](https://user-images.githubusercontent.com/51399899/124058321-bcd6b980-da5b-11eb-90e2-d21e896eb111.png)
> 这样删掉crf和fc的文件吗？这样会报错
> ![image](https://user-images.githubusercontent.com/51399899/124058359-d1b34d00-da5b-11eb-84a4-8ce7424de09b.png)

您好，看起来你这个使用方式是用了百度开源LAC repo，和PaddleNLP有点差别。
上面使用的方式有点问题，在于load 模型那块，如果你想自定义标签训练的话，有两种方式
1）使用PaddleNLP的lac目录，直接重新利用自己的数据进行训练，这块是没有瓶颈。效果的好坏 在于你的训练数据是否足够
2）使用LAC，这块你可能需要去改一下LAC加载模型那块的逻辑，使用下面的warmup方式
```python
import paddle.fluid as F 
def warmstart(self, program, path='./checkpoints'):
        def _existed_persitables(var):
            #if not isinstance(var, F.framework.Parameter):
            #    return False
            if not F.io.is_persistable(var):
                return False
            param_path = os.path.join(path, var.name)
            log.info("Loading parameter: {} persistable: {} exists: {}".format(
                param_path,
                F.io.is_persistable(var),
                os.path.exists(param_path),
            ))
            return os.path.exists(param_path)
        F.io.load_vars(
            self.exe,
            path,
            main_program=program,
            predicate=_existed_persitables
        )
```

**Comment by bigvine2** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/51399899/124058321-bcd6b980-da5b-11eb-90e2-d21e896eb111.png)
> > 这样删掉crf和fc的文件吗？这样会报错
> > ![image](https://user-images.githubusercontent.com/51399899/124058359-d1b34d00-da5b-11eb-84a4-8ce7424de09b.png)
> 
> 您好，看起来你这个使用方式是用了百度开源LAC repo，和PaddleNLP有点差别。
> 上面使用的方式有点问题，在于load 模型那块，如果你想自定义标签训练的话，有两种方式
> 1）使用PaddleNLP的lac目录，直接重新利用自己的数据进行训练，这块是没有瓶颈。效果的好坏 在于你的训练数据是否足够
> 2）使用LAC，这块你可能需要去改一下LAC加载模型那块的逻辑，使用下面的warmup方式
> 
> ```python
> import paddle.fluid as F 
> def warmstart(self, program, path='./checkpoints'):
>         def _existed_persitables(var):
>             #if not isinstance(var, F.framework.Parameter):
>             #    return False
>             if not F.io.is_persistable(var):
>                 return False
>             param_path = os.path.join(path, var.name)
>             log.info("Loading parameter: {} persistable: {} exists: {}".format(
>                 param_path,
>                 F.io.is_persistable(var),
>                 os.path.exists(param_path),
>             ))
>             return os.path.exists(param_path)
>         F.io.load_vars(
>             self.exe,
>             path,
>             main_program=program,
>             predicate=_existed_persitables
>         )
> ```

您给出的加载方式和LAC repo里面的加载方式几乎一样，这样加载还是报一样的错啊

**Comment by bigvine2** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/51399899/124058321-bcd6b980-da5b-11eb-90e2-d21e896eb111.png)
> > > 这样删掉crf和fc的文件吗？这样会报错
> > > ![image](https://user-images.githubusercontent.com/51399899/124058359-d1b34d00-da5b-11eb-84a4-8ce7424de09b.png)
> > 
> > 
> > 您好，看起来你这个使用方式是用了百度开源LAC repo，和PaddleNLP有点差别。
> > 上面使用的方式有点问题，在于load 模型那块，如果你想自定义标签训练的话，有两种方式
> > 1）使用PaddleNLP的lac目录，直接重新利用自己的数据进行训练，这块是没有瓶颈。效果的好坏 在于你的训练数据是否足够
> > 2）使用LAC，这块你可能需要去改一下LAC加载模型那块的逻辑，使用下面的warmup方式
> > ```python
> > import paddle.fluid as F 
> > def warmstart(self, program, path='./checkpoints'):
> >         def _existed_persitables(var):
> >             #if not isinstance(var, F.framework.Parameter):
> >             #    return False
> >             if not F.io.is_persistable(var):
> >                 return False
> >             param_path = os.path.join(path, var.name)
> >             log.info("Loading parameter: {} persistable: {} exists: {}".format(
> >                 param_path,
> >                 F.io.is_persistable(var),
> >                 os.path.exists(param_path),
> >             ))
> >             return os.path.exists(param_path)
> >         F.io.load_vars(
> >             self.exe,
> >             path,
> >             main_program=program,
> >             predicate=_existed_persitables
> >         )
> > ```
> 
> 您给出的加载方式和LAC repo里面的加载方式几乎一样，这样加载还是报一样的错啊



> 
> 
> > ![image](https://user-images.githubusercontent.com/51399899/124058321-bcd6b980-da5b-11eb-90e2-d21e896eb111.png)
> > 这样删掉crf和fc的文件吗？这样会报错
> > ![image](https://user-images.githubusercontent.com/51399899/124058359-d1b34d00-da5b-11eb-84a4-8ce7424de09b.png)
> 
> 您好，看起来你这个使用方式是用了百度开源LAC repo，和PaddleNLP有点差别。
> 上面使用的方式有点问题，在于load 模型那块，如果你想自定义标签训练的话，有两种方式
> 1）使用PaddleNLP的lac目录，直接重新利用自己的数据进行训练，这块是没有瓶颈。效果的好坏 在于你的训练数据是否足够
> 2）使用LAC，这块你可能需要去改一下LAC加载模型那块的逻辑，使用下面的warmup方式
> 
> ```python
> import paddle.fluid as F 
> def warmstart(self, program, path='./checkpoints'):
>         def _existed_persitables(var):
>             #if not isinstance(var, F.framework.Parameter):
>             #    return False
>             if not F.io.is_persistable(var):
>                 return False
>             param_path = os.path.join(path, var.name)
>             log.info("Loading parameter: {} persistable: {} exists: {}".format(
>                 param_path,
>                 F.io.is_persistable(var),
>                 os.path.exists(param_path),
>             ))
>             return os.path.exists(param_path)
>         F.io.load_vars(
>             self.exe,
>             path,
>             main_program=program,
>             predicate=_existed_persitables
>         )
> ```

我看了一下代码，模型加载的函数是这样的：
![图片](https://user-images.githubusercontent.com/44392161/124230239-5035ea80-db41-11eb-8bc5-8401fa8c9832.png)
真正从模型路径读取预训练模型参数的地方是用的create_paddle_predictor这个函数，这个函数来自from paddle.fluid.core import create_paddle_predictor，fluid.core的部分看不到create_paddle_predictor函数的代码，应该是来自dll，因此我们无法控制预训练模型的加载，是这样吗？

**Comment by wawltor** [comment]
create_paddle_predictor 一般都是在预测的场景才会使用，前面您提到的是要做一个增量训练，感觉前后场景有点不太match了

**Comment by bigvine2** [comment]
> 
> 
> create_paddle_predictor 一般都是在预测的场景才会使用，前面您提到的是要做一个增量训练，感觉前后场景有点不太match了

感谢耐心答复，确实不需要预测部分的代码，将预测部分代码注释掉之后可以顺利训练了

**Comment by wawltor** [comment]
> > create_paddle_predictor 一般都是在预测的场景才会使用，前面您提到的是要做一个增量训练，感觉前后场景有点不太match了
> 
> 感谢耐心答复，确实不需要预测部分的代码，将预测部分代码注释掉之后可以顺利训练了

没事 应该的 后续对于这种长时间issue没有回复的话，可以新建一个issue 有时候确实可能遗漏了
