### ISSUE TITLE
复现 FewCLUE 测试集结果

### ISSUE THREAD

**Issue by zhouxiao-coder** [PaddlePaddle/PaddleNLP#664]
首先，感谢开发者提供方便的 few shot [实验代码](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot)。

为了方便研究，能否提供下 FewCLUE  [benchmark](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot#benchmark) 复现的超参数？

**Comment by tianxin1860** [comment]
> 首先，感谢开发者提供方便的 few shot [实验代码](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot)。
> 
> 为了方便研究，能否提供下 FewCLUE [benchmark](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot#benchmark) 复现的超参数？

小样本场景下的指标波动比较大，建议按照和我们一样的实验方式进行效果复现,  实验主要调整的超参为:
lr: (2E-5 5E-5 1E-4 5E-4),  bs:(8 16 32),  P-tuning 策略的 p-embedding-num:(1 8 16 32),  EFL 策略的 negative_num,  
实验方式为: 对上述超参数进行组合实验，在多组 test_public 结果上取最高作为最终的评估指标. 建议按照这种方式进行复现，这样指标会相对稳定.

**Comment by zhouxiao-coder** [comment]
> > 首先，感谢开发者提供方便的 few shot [实验代码](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot)。
> > 为了方便研究，能否提供下 FewCLUE [benchmark](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/few_shot#benchmark) 复现的超参数？
> 
> 小样本场景下的指标波动比较大，建议按照和我们一样的实验方式进行效果复现, 实验主要调整的超参为:
> lr: (2E-5 5E-5 1E-4 5E-4), bs:(8 16 32), P-tuning 策略的 p-embedding-num:(1 8 16 32), EFL 策略的 negative_num,
> 实验方式为: 对上述超参数进行组合实验，在多组 test_public 结果上取最高作为最终的评估指标. 建议按照这种方式进行复现，这样指标会相对稳定.

谢谢回复，我尝试一下这批参数组合。
