### ISSUE TITLE
torch模型转paddle时，paddle中没有对应方法

### ISSUE THREAD

**Issue by crazydust** [PaddlePaddle/PaddleNLP#665]
总：torch.nn.Parameter()和torch.nn.ModuleDict()两个方法在paddle中无对应的。
1. torch中有Parameter()、ParameterList()、ParameterDict()三个方法，paddle中只有ParameterList()一个，现在想转第一个，不知道怎么转。
2. ModuleDict()在paddle中完全没对应的。

**Comment by wawltor** [comment]
1. 如果想设置parameter的话，可以通过下面的方式来设置，通过set_value来设置，set_value的参数可以是numpy或者tensor
```python
   layer.weight.set_value(
                    paddle.tensor.normal(
                        mean=0.0,
                        std=self.initializer_range
                        if hasattr(self, "initializer_range") else
                        self.ernie.config["initializer_range"],
                        shape=layer.weight.shape))
````

2. ModuleDict() 目前确实没有这个API，这个我们反馈给框架同学

**Comment by wennyHou** [comment]
https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/utils/torch.nn.parameter.Parameter.md
