### ISSUE TITLE
aistudio终端运行.sh文件  PaddleNLP/ examples / information_extraction / DuIE /报错,官方源码什么动没改 

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#669]
![image](https://user-images.githubusercontent.com/63343847/123910410-fac8d480-d9ac-11eb-9e41-a74bab5daf1b.png)
![image](https://user-images.githubusercontent.com/63343847/123910473-0fa56800-d9ad-11eb-8c18-cf6ddd37ca39.png)
![image](https://user-images.githubusercontent.com/63343847/123910521-2350ce80-d9ad-11eb-8429-e358427f2a96.png)
![image](https://user-images.githubusercontent.com/63343847/123910555-3368ae00-d9ad-11eb-8e9d-eb552bb27c07.png)

**Comment by Steffy-zxf** [comment]
你好！根据以上报错信息，看起来像是，命令当中的空格间距的问题，建议在aistudio平台上可以直接参考PaddleNLP官方关系抽项目：https://aistudio.baidu.com/aistudio/projectdetail/1639963

**Comment by AI-Mart** [comment]
不是命令行的问题，是.sh文件的格式有问题不能是doc格式，github上的文件格式要调整下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上8:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] aistudio终端运行.sh文件  PaddleNLP/ examples / information_extraction / DuIE /报错,官方源码什么动没改  (#669)





 
你好！根据以上报错信息，看起来像是，命令当中的空格间距的问题，建议在aistudio平台上可以直接参考PaddleNLP官方关系抽项目：https://aistudio.baidu.com/aistudio/projectdetail/1639963

**Comment by Steffy-zxf** [comment]
> 是.sh文件的格式有问题不能是doc格式 

不明白doc格式是啥意思？

我在linux上执行没有问题。

**Comment by AI-Mart** [comment]
https://blog.csdn.net/weixin_42903419/article/details/102842521




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] aistudio终端运行.sh文件  PaddleNLP/ examples / information_extraction / DuIE /报错,官方源码什么动没改  (#669)





  
是.sh文件的格式有问题不能是doc格式
 不明白doc格式是啥意思？
  
我在linux上执行没有问题。

**Comment by Steffy-zxf** [comment]
你是指的dos文件格式吧。我这边看了train.sh文件是unix格式。

应该是你在windows下clone 的repo 文件，导致文件编码格式错误。

**Comment by AI-Mart** [comment]
是的，最好规避下哦，windows很多人都使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] aistudio终端运行.sh文件  PaddleNLP/ examples / information_extraction / DuIE /报错,官方源码什么动没改  (#669)





 
你是指的dos文件格式吧。我这边看了train.sh文件是unix格式。
 
应该是你在windows下clone 的repo 文件，导致文件编码格式错误。
