### ISSUE TITLE
ERNIE-GEN自动写诗教程出现 AssertionError: only one element variable can be converted to float.

### ISSUE THREAD

**Issue by libertatis** [PaddlePaddle/PaddleNLP#672]
在运行项目[『NLP经典项目集』06： 使用预训练模型ERNIE-GEN自动写诗](https://aistudio.baidu.com/aistudio/projectdetail/1339888) 时，出现如下 `AssertionError` 断言错误：
```
---------------------------------------------------------------------------AssertionError                            Traceback (most recent call last)<ipython-input-9-b624e10c45e4> in <module>
     50                 "global step %d, epoch: %d, batch: %d, loss: %f, speed: %.2f step/s, lr: %.3e"
     51                 % (global_step, epoch, step, loss, logging_steps /
---> 52                     (time.time() - tic_train), lr_scheduler.get_lr()))
     53             tic_train = time.time()
     54 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py in _float_(var)
    113     def _float_(var):
    114         numel = np.prod(var.shape)
--> 115         assert numel == 1, "only one element variable can be converted to float."
    116         tensor = var.value().get_tensor()
    117         assert tensor._is_initialized(), "variable's tensor is not initialized"
AssertionError: only one element variable can be converted to float.
```
经过一番 `bug` 排查，发现应该是 `paddle` 版本和 `paddlenlp` 版本不兼容所导致的字符串格式化问题。
该项目使用的 `paddle` 版本为 `2.0.2`，在 `AIStudio` 中执行更新 `paddlenlp` 得到的版本为 `2.0.5`。
经过测试，在 `paddle 2.0.2` 下，使用 `paddlenlp` `2.0.0` 和 `2.0.1` 两个版本，程序正常运行，而当 `paddlenlp` 的版本号 `>= 2.0.2` 时，则会出现上述 `AssertionError` 断言错误。
目前我的解决办法是，将 `AIStudio` 中那句更新 `paddlenlp` 的命令:
```
!pip install --upgrade paddlenlp -i https://pypi.org/simple
```
改为：
```
!pip install paddlenlp==2.0.0
```
或
```
!pip install paddlenlp==2.0.1
```
即，将 `paddlenlp` 的版本退回到 `2.0.0` 或 `2.0.1` 版本。
鉴于 `AIStudio` 社区还有很多基于 `paddle 2.0.2` 版本的项目，盼望官方能够早日修复这个bug~
开发和维护框架的老师们，你们辛苦啦~

**Comment by wawltor** [comment]
好的 我们尽快来修复这个问题

**Comment by libertatis** [comment]
> 好的 我们尽快来修复这个问题

我还不知道这个bug产生的真正原因，官方查明原因，修复bug后，还望不吝告知~

**Comment by wawltor** [comment]
> > 好的 我们尽快来修复这个问题
> 
> 我还不知道这个bug产生的真正原因，官方查明原因，修复bug后，还望不吝告知~

您好，我们已经在最新的教程中做了修复，辛苦使用最新的版本!

上面的问题，在于打印loss tensor的时候，需要对loss tensor进行单个元素float化，在paddle 2.0.2之前版本没有对tensor的元素个数进行判断，在2.0.2进行一个强制判断，判断tensor的元素个数是否为1，防止一些空tensor的情况。
在我们版本迭代过程中，没有对loss进行mean操作，导致loss的元素个数超过1，因此出现了上述的问题，修复的方式见下面的代码
```python
loss = loss.mean()
```

感谢给我们反馈问题！欢迎给PaddleNLP贡献代码！

**Comment by libertatis** [comment]
原来如此呀！非常感谢您的赐教！昨天晚上有一瞬间我有想过里面有个值是批量的，注意力光集中到下面的 `lr_scheduler` 去了，发现它不是一个批量值，就错误的转向字符串格式化上去了，从而忽略了那个 `loss`。嗯，真是受教啦，再次表示感谢~
