### ISSUE TITLE
ERNIE-GEN finetune报错(InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.

### ISSUE THREAD

**Issue by yanshuai19941224** [PaddlePaddle/PaddleNLP#673]
![image](https://user-images.githubusercontent.com/48637582/124043105-4cbd3900-da45-11eb-8f1c-7432f0d015f4.png)
这该怎么解决啊

**Comment by ZHUI** [comment]
您好，刚刚在windows上调试了一下。应该是 windows 和 linux 上默认数据类型不一致导致的问题。可以修改下面一行，把输入显式转为int64类型。
https://github.com/PaddlePaddle/PaddleNLP/blob。/develop/examples/text_generation/ernie-gen/encode.py#L43
```python
tgt_ids = np.array(tgt_ids)
# 替换为
tgt_ids = np.array(tgt_ids).astype("int64")
```

**Comment by yanshuai19941224** [comment]
非常感谢解答!终于跑起来了!

**Comment by yanshuai19941224** [comment]
非常感谢!终于跑起来了
