### ISSUE TITLE
[Question]: TaskFlow做文本相似度匹配，根本无法使用

### ISSUE THREAD

**Issue by SIGNCHECK** [PaddlePaddle/PaddleNLP#6762]
### 请提出你的问题

就单纯的使用默认模型完成文本相似度匹配的任务，根本无法使用，一会高，一会底，甚至还有负数。
```python
from paddlenlp import Taskflow
similarity = Taskflow("text_similarity")
similarity([["百度真厉害", "百度真厉害"]])
```

输入结果如下，很离谱的结果，换不同模型也没用

```shell
>>> similarity([["百度真厉害", "百度真厉害"]])
/home/signcheck/miniconda3/envs/paddlenlp/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1865: UserWarning: Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
  warnings.warn(
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.8073881268501282}]
>>> 
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.46116241812705994}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5011074542999268}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.4119800627231598}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.2658393383026123}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5620529651641846}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': -0.4480578303337097}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.6538177728652954}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': -0.06106607988476753}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.39216071367263794}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.35281193256378174}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.1794922798871994}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.19759981334209442}]
>>> similarity([["百度真厉害", "百度真厉害"]])
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5641244649887085}]

```

**Comment by w5688414** [comment]
> ### 请提出你的问题
> 就单纯的使用默认模型完成文本相似度匹配的任务，根本无法使用，一会高，一会底，甚至还有负数。
> 
> ```python
> from paddlenlp import Taskflow
> similarity = Taskflow("text_similarity")
> similarity([["百度真厉害", "百度真厉害"]])
> ```
> 
> 输入结果如下，很离谱的结果，换不同模型也没用
> 
> ```shell
> >>> similarity([["百度真厉害", "百度真厉害"]])
> /home/signcheck/miniconda3/envs/paddlenlp/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1865: UserWarning: Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
>   warnings.warn(
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.8073881268501282}]
> >>> 
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.46116241812705994}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5011074542999268}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.4119800627231598}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.2658393383026123}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5620529651641846}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': -0.4480578303337097}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.6538177728652954}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': -0.06106607988476753}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.39216071367263794}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.35281193256378174}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.1794922798871994}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.19759981334209442}]
> >>> similarity([["百度真厉害", "百度真厉害"]])
> [{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 0.5641244649887085}]
> ```

请问您的环境是什么？

**Comment by SIGNCHECK** [comment]
@w5688414 您好，系统为Ubuntu 20.04.6 LTS，python版本为3.8
```shell
paddlenlp                 2.6.0
paddlepaddle              2.5.1
```

**Comment by w5688414** [comment]
cpu版本？这是我的结果：

```
[{'text1': '百度真厉害', 'text2': '百度真厉害', 'similarity': 1.0}]
```
请参考一下我的环境：
```
paddlenlp                      2.6.0
paddleocr                      2.6.1.3
paddlepaddle-gpu               0.0.0.post112
```

**Comment by SIGNCHECK** [comment]
@w5688414 您好，谢谢！以下是我的cpu信息，暂未使用gpu版本的paddlepaddle，换了几个模型的推理结果都不是很对，不知道是否为paddle paddle的原因？

```shell
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           33
Model name:                      AMD Ryzen 7 5700X 8-Core Processor
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6800.24
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disable
                                 d via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __u
                                 ser pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IB
                                 RS_FW, STIBP always-on, RSB filling, PBRSB-e
                                 IBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep 
                                 mtrr pge mca cmov pat pse36 clflush mmx fxsr
                                  sse sse2 ht syscall nx mmxext fxsr_opt pdpe
                                 1gb rdtscp lm constant_tsc rep_good nopl non
                                 stop_tsc cpuid extd_apicid aperfmperf rapl p
                                 ni pclmulqdq monitor ssse3 fma cx16 sse4_1 s
                                 se4_2 x2apic movbe popcnt aes xsave avx f16c
                                  rdrand lahf_lm cmp_legacy svm extapic cr8_l
                                 egacy abm sse4a misalignsse 3dnowprefetch os
                                 vw ibs skinit wdt tce topoext perfctr_core p
                                 erfctr_nb bpext perfctr_llc mwaitx cpb cat_l
                                 3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp 
                                 vmmcall fsgsbase bmi1 avx2 smep bmi2 erms in
                                 vpcid cqm rdt_a rdseed adx smap clflushopt c
                                 lwb sha_ni xsaveopt xsavec xgetbv1 xsaves cq
                                 m_llc cqm_occup_llc cqm_mbm_total cqm_mbm_lo
                                 cal clzero irperf xsaveerptr rdpru wbnoinvd 
                                 arat npt lbrv svm_lock nrip_save tsc_scale v
                                 mcb_clean flushbyasid decodeassists pausefil
                                 ter pfthreshold avic v_vmsave_vmload vgif v_
                                 spec_ctrl umip pku ospke vaes vpclmulqdq rdp
                                 id overflow_recov succor smca fsrm
```

**Comment by w5688414** [comment]
> @w5688414 您好，谢谢！以下是我的cpu信息，暂未使用gpu版本的paddlepaddle，换了几个模型的推理结果都不是很对，不知道是否为paddle paddle的原因？
> 
> ```shell
> Architecture:                    x86_64
> CPU op-mode(s):                  32-bit, 64-bit
> Byte Order:                      Little Endian
> Address sizes:                   48 bits physical, 48 bits virtual
> CPU(s):                          16
> On-line CPU(s) list:             0-15
> Thread(s) per core:              2
> Core(s) per socket:              8
> Socket(s):                       1
> NUMA node(s):                    1
> Vendor ID:                       AuthenticAMD
> CPU family:                      25
> Model:                           33
> Model name:                      AMD Ryzen 7 5700X 8-Core Processor
> Stepping:                        2
> Frequency boost:                 enabled
> CPU MHz:                         2200.000
> CPU max MHz:                     3400.0000
> CPU min MHz:                     2200.0000
> BogoMIPS:                        6800.24
> Virtualization:                  AMD-V
> L1d cache:                       256 KiB
> L1i cache:                       256 KiB
> L2 cache:                        4 MiB
> L3 cache:                        32 MiB
> NUMA node0 CPU(s):               0-15
> Vulnerability Itlb multihit:     Not affected
> Vulnerability L1tf:              Not affected
> Vulnerability Mds:               Not affected
> Vulnerability Meltdown:          Not affected
> Vulnerability Mmio stale data:   Not affected
> Vulnerability Retbleed:          Not affected
> Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disable
>                                  d via prctl and seccomp
> Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __u
>                                  ser pointer sanitization
> Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IB
>                                  RS_FW, STIBP always-on, RSB filling, PBRSB-e
>                                  IBRS Not affected
> Vulnerability Srbds:             Not affected
> Vulnerability Tsx async abort:   Not affected
> Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep 
>                                  mtrr pge mca cmov pat pse36 clflush mmx fxsr
>                                   sse sse2 ht syscall nx mmxext fxsr_opt pdpe
>                                  1gb rdtscp lm constant_tsc rep_good nopl non
>                                  stop_tsc cpuid extd_apicid aperfmperf rapl p
>                                  ni pclmulqdq monitor ssse3 fma cx16 sse4_1 s
>                                  se4_2 x2apic movbe popcnt aes xsave avx f16c
>                                   rdrand lahf_lm cmp_legacy svm extapic cr8_l
>                                  egacy abm sse4a misalignsse 3dnowprefetch os
>                                  vw ibs skinit wdt tce topoext perfctr_core p
>                                  erfctr_nb bpext perfctr_llc mwaitx cpb cat_l
>                                  3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp 
>                                  vmmcall fsgsbase bmi1 avx2 smep bmi2 erms in
>                                  vpcid cqm rdt_a rdseed adx smap clflushopt c
>                                  lwb sha_ni xsaveopt xsavec xgetbv1 xsaves cq
>                                  m_llc cqm_occup_llc cqm_mbm_total cqm_mbm_lo
>                                  cal clzero irperf xsaveerptr rdpru wbnoinvd 
>                                  arat npt lbrv svm_lock nrip_save tsc_scale v
>                                  mcb_clean flushbyasid decodeassists pausefil
>                                  ter pfthreshold avic v_vmsave_vmload vgif v_
>                                  spec_ctrl umip pku ospke vaes vpclmulqdq rdp
>                                  id overflow_recov succor smca fsrm
> ```

换一台机器试试呢？我没有您的机器配置，不太方便，按理说是支持的

**Comment by ninnyyan1993** [comment]
同样用paddle cpu版本，也遇到了和楼主一样的问题。楼主解决了吗

**Comment by re0phimes** [comment]
遇到同样问题了
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               799.932
CPU max MHz:           3900.0000
CPU min MHz:           800.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-19,40-59
NUMA node1 CPU(s):     20-39,60-79
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
```

`paddlenlp: 2.6.1`

有解决了的么

**Comment by aduil** [comment]
同样的情况 CPU 完全没法用
```
paddlenlp                      2.6.1
paddlepaddle                   2.5.1
```

**Comment by 18772247265** [comment]
cpu版本使用情感分析也是类似情况，官方案例第一次跑完全部为正面，没有一个负面，第二次跑完绝大部分为负面，少数正面，这误差也太大了

**Comment by xiaojuantian** [comment]
cpu版本UIE也是一样的情况，和官方案例都不一致，抽取不出任何结果。
