### ISSUE TITLE
[Bug]: WINDOWS环境下搭建端到端智能问答系统出现TypeError: __init__() got an unexpected keyword argument 'pooling_mode'

### ISSUE THREAD

**Issue by 1042312930** [PaddlePaddle/PaddleNLP#6766]
### 软件环境

```Markdown
- paddlepaddle:2.5.1
- paddlepaddle-gpu: cpu版
- paddlenlp: 2.5.2
- paddle-bfloat                  0.1.7
- paddle-pipelines               0.5.3
- paddle2onnx                    1.0.6
- paddlefsl                      1.1.0
- paddleocr                      2.7.0.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行
python examples/question-answering/dense_qa_example.py --device cpu
出现
Traceback (most recent call last):
  File "D:\lzx\myprojects\ppadleproject\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 202, in <module>
    semantic_search_tutorial()
  File "D:\lzx\myprojects\ppadleproject\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 174, in semantic_search_tutorial
    retriever = get_faiss_retriever(use_gpu)
  File "D:\lzx\myprojects\ppadleproject\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 81, in get_faiss_retriever
    retriever = DensePassageRetriever(
TypeError: __init__() got an unexpected keyword argument 'pooling_mode'
```

### 稳定复现步骤 & 代码

按照步骤文档:
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/question-answering/Install_windows.md
执行到其中的1.3出现了上述问题
在其他的issue中看到解决方法是
pip install git+https://github.com/PaddlePaddle/PaddleNLP.git
但是我的问题还是没变化

**Comment by w5688414** [comment]
这个问题已经修复了，请参考：https://github.com/PaddlePaddle/PaddleNLP/blob/928c59e23c719f04610f25f6bbe447c9349ec2a8/pipelines/pipelines/nodes/retriever/dense.py#L65

请升级pipelines到最新develop版本。

**Comment by 1042312930** [comment]
> 这个问题已经修复了，请参考：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/928c59e23c719f04610f25f6bbe447c9349ec2a8/pipelines/pipelines/nodes/retriever/dense.py#L65
> 
> 请升级pipelines到最新develop版本。

通过git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP/pipelines
python setup.py install
吗

**Comment by 1042312930** [comment]
我出错的时候试过使用
通过git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP/pipelines
python setup.py install
了但是还是报错

**Comment by w5688414** [comment]
升级一下paddlenlp到2.6.0

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/pull/6790 我尝试移除pooling_mode来避免这个问题，看看能否解决您的问题
