### ISSUE TITLE
[急]本地加载chnsenticorp数据集， dev.tsv出现异常

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#677]
![image](https://user-images.githubusercontent.com/83859417/124118804-53c76400-daa4-11eb-93a0-c96da9b6a94f.png)

问题发生原因是qid在dev.tsv不存在，解析错误。请看一下

D:\Python\Python39\python.exe D:/VOC评估/PVoc/dataset_test.py
Traceback (most recent call last):
  File "D:\VOC评估\PVoc\dataset_test.py", line 7, in <module>
    dev_ds = load_dataset('chnsenticorp', splits="dev", data_files='./chnsenticorp/dev.tsv')
  File "D:\Python\Python39\lib\site-packages\paddlenlp\datasets\dataset.py", line 139, in load_dataset
    datasets = reader_instance.read_datasets(
  File "D:\Python\Python39\lib\site-packages\paddlenlp\datasets\dataset.py", line 543, in read_datasets
    datasets += [
  File "D:\Python\Python39\lib\site-packages\paddlenlp\datasets\dataset.py", line 544, in <listcomp>
    self.read(
  File "D:\Python\Python39\lib\site-packages\paddlenlp\datasets\dataset.py", line 628, in read
    examples = list(examples)
  File "D:\Python\Python39\lib\site-packages\paddlenlp\datasets\chnsenticorp.py", line 73, in _read
    qid, label, text = data
ValueError: not enough values to unpack (expected 3, got 2)

Process finished with exit code 1

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/124119156-bc164580-daa4-11eb-8d20-d9682aadf94c.png)
请看一下

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/124119680-62fae180-daa5-11eb-8041-5b83dbcb7f83.png)
临时把split做处理，换成train， 想问一下qid是啥？

**Comment by Steffy-zxf** [comment]
你好！你是否更换了chnsenticorp原始数据呢？PaddleNLP内置的chnsenticorp数据有qid字段。qid表示这个数据样本编号。

**Comment by LangDaoAI** [comment]
我明天上午再确认一下数据集的来源，谢谢

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LangDaoAI** [comment]
> 你好！你是否更换了chnsenticorp原始数据呢？PaddleNLP内置的chnsenticorp数据有qid字段。qid表示这个数据样本编号。

早上好！ 我是从下图红框地址手动下载的
![image](https://user-images.githubusercontent.com/83859417/124205270-7e9cd100-db13-11eb-901b-a64224449ef1.png)

然后，dev.tsv的内容格式如下图，
![image](https://user-images.githubusercontent.com/83859417/124205355-adb34280-db13-11eb-86ec-cf8fc39dff06.png)

也就是说只有两列，而chnsenticorp.py中的split  'dev' 返回三个结果
![image](https://user-images.githubusercontent.com/83859417/124205421-c3c10300-db13-11eb-90d7-7b533a60d209.png)

所以，我判断：

1 数据集是否有不一致，那么请告知一下最新的数据集
2 chnsenticorp.py代码有回退

请确认一下，谢谢！

**Comment by LangDaoAI** [comment]
做了进一步确认， 代码里面URL是 "https://dataset-bj.cdn.bcebos.com/qianyan/ChnSentiCorp.zip"， 来自千言的， 而https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/sentiment_analysis/skep  readme里面的地址是https://ernie.bj.bcebos.com/task_data_zh.tgz，  问题就是数据集来源不一致，请更新readme， 谢谢！

**Comment by Steffy-zxf** [comment]
@LangDaoAI 感谢反馈！你可以通过以下代码加载chnsenticorp数据集

```python
from paddlenlp import load_dataset

train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=["train", "dev", "test"])
```

**Comment by LangDaoAI** [comment]
> @LangDaoAI 感谢反馈！你可以通过以下代码加载chnsenticorp数据集
> 
> ```python
> from paddlenlp import load_dataset
> 
> train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=["train", "dev", "test"])
> ```

是的，这个我知道，我是离线下载数据集，再本地加载， 所以才遇到这个问题了

**Comment by wawltor** [comment]
> > @LangDaoAI 感谢反馈！你可以通过以下代码加载chnsenticorp数据集
> > ```python
> > from paddlenlp import load_dataset
> > 
> > train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=["train", "dev", "test"])
> > ```
> 
> 是的，这个我知道，我是离线下载数据集，再本地加载， 所以才遇到这个问题了

这个问题我们提个PR修复了一下，谢谢反馈问题！

**Comment by LangDaoAI** [comment]
> > > @LangDaoAI 感谢反馈！你可以通过以下代码加载chnsenticorp数据集
> > > ```python
> > > from paddlenlp import load_dataset
> > > 
> > > train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=["train", "dev", "test"])
> > > ```
> > 
> > 
> > 是的，这个我知道，我是离线下载数据集，再本地加载， 所以才遇到这个问题了
> 
> 这个问题我们提个PR修复了一下，谢谢反馈问题！

Great!

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/677 已合入

**Comment by LangDaoAI** [comment]
感谢！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
