### ISSUE TITLE
[Question]:  基于chatglm 训练的lora-model, 在同时加载多个lora模型时，会出现后者覆盖前者

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/PaddleNLP#6780]
### 请提出你的问题

base_model = load_base_model(lora_config.dtype, args.model_name_or_path)
predictor_1 = Predictor(args, tokenizer, base_model, lora_path_1)
predictor_2 = Predictor(args, tokenizer, base_model, lora_path_2)

debug时发现 predictor_1.model.parameters() 是等于predictor_2.model.parameters()的。是我使用的方式不对吗？？

期望是只加载一次chatglm-6b模型，同时加载lora_model_1 和lora_model_2两个模型，分别得到predictor_1 和predictor_2 。正确加载模型的方式是什么呢？

@lugimzzz
@sijunhe

**Comment by lugimzzz** [comment]
正确的方式是两个predictor传入的base_model应该是两个独立的模型，因为lora_model是对base_model替换linear层为lora_linear，然后加载lora参数。上面的行为是对同个模型先加载参数1，再加载参数2，所以参数会一致

**Comment by xieyu0214** [comment]
> 正确的方式是两个predictor传入的base_model应该是两个独立的模型，因为lora_model是对base_model替换linear层为lora_linear，然后加载lora参数。上面的行为是对同个模型先加载参数1，再加载参数2，所以参数会一致

理解了，谢谢~  
那我想节省显存，只加载一次base_model，如何才能得到两个独立的predictor呢？

**Comment by lugimzzz** [comment]
目前无法支持，你可以通过使用的时候切换loramodel中lora参数完成这个功能
```
lora_model1= LoRAModel.from_pretrained(base_model, lora_path1)
base_model = lora_model1.restore_original_model()
lora_model2= LoRAModel.from_pretrained(base_model, lora_path2)
```

**Comment by xieyu0214** [comment]
> 目前无法支持，你可以通过使用的时候切换loramodel中lora参数完成这个功能
> 
> ```
> lora_model1= LoRAModel.from_pretrained(base_model, lora_path1)
> base_model = lora_model1.restore_original_model()
> lora_model2= LoRAModel.from_pretrained(base_model, lora_path2)
> ```

    lora_model_1 = LoRAModel.from_pretrained(base_model,  lora_path_1)
    restored_model = lora_model_1.restore_original_model()
    restored_model.eval()
    lora_model_2 = LoRAModel.from_pretrained(restored_model,  lora_path_2)
    assert lora_model_1.parameters() != lora_model_2.parameters()

这么测试了， 发现lora_model_1参数和lora_model_2还是一样的呢。lora_model1 是合并了base_model和lora参数的。若是要 在使用时切换lora参数，需要单独保存各个lora 参数吗？

**Comment by lugimzzz** [comment]
> 目前无法支持，你可以通过使用的时候切换loramodel中lora参数完成这个功能
> 
> ```
> lora_model1= LoRAModel.from_pretrained(base_model, lora_path1)
> base_model = lora_model1.restore_original_model()
> lora_model2= LoRAModel.from_pretrained(base_model, lora_path2)
> ```

目前是无法支持你想要的情况，就是两个独立的predictor，但只有一个base_model。你只能在要使用某一个lora权重的时候进行切换加载

**Comment by xieyu0214** [comment]
> > 目前无法支持，你可以通过使用的时候切换loramodel中lora参数完成这个功能
> > ```
> > lora_model1= LoRAModel.from_pretrained(base_model, lora_path1)
> > base_model = lora_model1.restore_original_model()
> > lora_model2= LoRAModel.from_pretrained(base_model, lora_path2)
> > ```
> 
> 目前是无法支持你想要的情况，就是两个独立的predictor，但只有一个base_model。你只能在要使用某一个lora权重的时候进行切换加载

嗯嗯 明白了 谢谢
