### ISSUE TITLE
ernie-gen finetune后的模型安装报错

### ISSUE THREAD

**Issue by yanshuai19941224** [PaddlePaddle/PaddleNLP#680]
明明我已经打包好了呀，模型也在本地保存好了但是没办法hub install，求帮助
![image](https://user-images.githubusercontent.com/48637582/124231457-40bb9f00-db4b-11eb-8d6f-3e190b37aab3.png)

**Comment by yanshuai19941224** [comment]
![image](https://user-images.githubusercontent.com/48637582/124237682-bd9e4700-db52-11eb-8c7a-57b55854d963.png)
补一张打包的程序，之前finetune有成功显示 exported

**Comment by KPatr1ck** [comment]
![image](https://user-images.githubusercontent.com/22954146/124243417-72833480-db50-11eb-8739-442227b28eb0.png)

你好，你的路径信息应该是不对的，当前目录下没有`ernie_gen_iro_notrio_creater`这个目录。
对应你截图的路径信息，你还需要`cd .paddlehub`再执行install的命令。

**Comment by yanshuai19941224** [comment]
感谢感谢。。。是我疏忽了
