### ISSUE TITLE
关于from_pretrained方法加载模型的问题

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#682]
当通过以下方法加载模型时候，模型加载耗时有点慢， 
model = SkepForSequenceClassification.from_pretrained(pretrained_model_name_or_path="skep_ernie_1.0_large_ch", num_classes=len(train_ds.label_list))

我在分析的时候发现主要是paddlenlp\transformers\model_utils.py中两个地方加载慢，1）和2）都会加载

1）base_model = cls.base_model_class(*base_args, **base_kwargs)
2）model = cls(*derived_args, **derived_kwargs)

![image](https://user-images.githubusercontent.com/83859417/124240587-75305a80-db4d-11eb-8f87-fb3ee655384b.png)

首先，模型加载逻辑是没有任何问题的， 但是，我想知道什么样的推荐的机器性能能够急剧提升性能， 毕竟我现在是在开发机器上做分析。

其次， 除了机器性能推荐，那么是不是还有其他程序上改进的best practice。

以上希望能够得到提示和反馈，非常感谢！

**Comment by LangDaoAI** [comment]
想问一下team这个是问题吗

**Comment by LangDaoAI** [comment]
从训练角度看from_pretrained是能够忍受的， 刚刚看了一下服务端部署，推理的模型加载应该不会使用这个API， 不知道认识是否正确，所以线上部署的话应该不会遇到这个问题吧

**Comment by wawltor** [comment]
> 从训练角度看from_pretrained是能够忍受的， 刚刚看了一下服务端部署，推理的模型加载应该不会使用这个API， 不知道认识是否正确，所以线上部署的话应该不会遇到这个问题吧

您好，我简单回答一下这个问题。您的想法基本是没有错的，前面from_pretrained相对来说比较耗时，因此需要把较大模型参数load，同时分配给各个参数，但是这种load操作在线上只会有一次，之后预测服务不需要再次load模型了。

**Comment by LangDaoAI** [comment]
是的，感谢回复！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
