### ISSUE TITLE
无法从paddlenlp.transformers导入ErnieGramForQuestionAnswering

### ISSUE THREAD

**Issue by zifeiYv** [PaddlePaddle/PaddleNLP#683]
我在aistudio中按照说明运行`examples/machine_reading_comprehension/DuReader-robust/run_du.py`，报以下错误：
```
Traceback (most recent call last):
  File "run_du.py", line 34, in <module>
    from paddlenlp.transformers import ErnieGramForQuestionAnswering, ErnieGramTokenizer
ImportError: cannot import name 'ErnieGramForQuestionAnswering' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)
Traceback (most recent call last):
  File "run_du.py", line 34, in <module>
    from paddlenlp.transformers import ErnieGramForQuestionAnswering, ErnieGramTokenizer
ImportError: cannot import name 'ErnieGramForQuestionAnswering' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)
```
请问这是怎么回事。

**Comment by wawltor** [comment]
麻烦提供一下aistudio中的paddlenlp 版本

**Comment by libertatis** [comment]
`ernie-gram` 是 `PaddleNLP 2.0.2` 之后才支持的预训练模型。你先检查一下环境中的 `PaddleNLP` 的版本号是否高于 `2.0.2`。如果版本低于 `2.0.2`，请将 `PaddleNLP` 升级到最新版本。嗯，目前最新版的版本号是 `2.0.5`~ 。升级 `PaddleNLP` 的命令为:
```
pip install --upgrade paddlenlp -i https://pypi.org/simple
```

**Comment by zifeiYv** [comment]
> 麻烦提供一下aistudio中的paddlenlp 版本

我的paddlenlp版本是2.0.1，升级后问题已解决。

**Comment by zifeiYv** [comment]
> `ernie-gram` 是 `PaddleNLP 2.0.2` 之后才支持的预训练模型。你先检查一下环境中的 `PaddleNLP` 的版本号是否高于 `2.0.2`。如果版本低于 `2.0.2`，请将 `PaddleNLP` 升级到最新版本。嗯，目前最新版的版本号是 `2.0.5`~ 。升级 `PaddleNLP` 的命令为:
> 
> ```
> pip install --upgrade paddlenlp -i https://pypi.org/simple
> ```

已解决，感谢
