### ISSUE TITLE
[Question]: 社区模型在哪里可以找到列表和描述？

### ISSUE THREAD

**Issue by fymaplefish** [PaddlePaddle/PaddleNLP#6831]
### 请提出你的问题

社区模型（community models）在哪里可以找到列表和描述？

**Comment by lugimzzz** [comment]
大模型可以在llm目录下，对应的模型结构找到 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm。其他模型可以使用cli，比如`paddlenlp search ernie`搜索。之后会推出一个模型中心，更加方便了解模型，请期待

**Comment by fymaplefish** [comment]
> 大模型可以在llm目录下，对应的模型结构找到 [https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm。其他模型可以使用cli，比如`paddlenlp](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm%E3%80%82%E5%85%B6%E4%BB%96%E6%A8%A1%E5%9E%8B%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8cli%EF%BC%8C%E6%AF%94%E5%A6%82%60paddlenlp) search ernie`搜索。之后会推出一个模型中心，更加方便了解模型，请期待

谢谢，期待以后的模型中心
