### ISSUE TITLE
[Question]: ernie_vil-2.0-base-zh/model_config.json下载失败

### ISSUE THREAD

**Issue by aircov** [PaddlePaddle/PaddleNLP#6874]
### 请提出你的问题

https://bj.bcebos.com/paddlenlp/models/community/PaddlePaddle/ernie_vil-2.0-base-zh/model_config.json
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/43372380/eddf80d7-90cc-4e58-8b33-509582b587e0)

**Comment by aircov** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/43372380/a8af9231-7cce-411d-b5b1-8c0cf3a4f2a2)

**Comment by qingzhong1** [comment]
<img width="1277" alt="截屏2023-08-30 19 41 29" src="https://github.com/PaddlePaddle/PaddleNLP/assets/137043369/d8fe1d8c-8b03-4cf5-9a84-c476fd50f292">
```precessor=ErnieViLProcessor.from_pretrained('PaddlePaddle/ernie_vil-2.0-base-zh')
model=ErnieViLModel.from_pretrained('PaddlePaddle/ernie_vil-2.0-base-zh')```
我这边运行正常，paddlenlp版本是2.6.0
你这边paddlenlp的版本是什么
