### ISSUE TITLE
[Question]: 训练ChatGLM6B模型时报错

### ISSUE THREAD

**Issue by Jaydon996** [PaddlePaddle/PaddleNLP#6881]
### 请提出你的问题

<img width="1347" alt="d78025106deb3ceca607e35cd3e4802" src="https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/dd96a83c-2ae1-4ded-9997-13075822e8c2">

环境：
paddlepaddle==2.5.1
paddlenlp==2.6.0
python==3.10

除了配置数据集路径外无改动
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/116625543/2a1c391d-f97e-4087-8d7c-3d671e0cf704)

运行命令：
python -u  -m paddle.distributed.launch --gpus "0,1,2,3" finetune_generation.py ./chatglm2/sft_argument.json

**Comment by lastrei** [comment]
存疑是否与pipeline_parallel有关.watch

**Comment by Jaydon996** [comment]
已解决，paddlenlp必须更新到develop版本，2.6.0不可以...

**Comment by lugimzzz** [comment]
这个pr修复兼容了paddlenlp 2.6 可以参考修复 https://github.com/PaddlePaddle/PaddleNLP/pull/6891
