### ISSUE TITLE
[Bug]: paddlenlp在2.5.0rc1CPU下有结果，2.5.1结果为空。安装GPU后2.5.0rc1和2.5.1结果都为空

### ISSUE THREAD

**Issue by iwhyshop** [PaddlePaddle/PaddleNLP#6884]
### 软件环境

```Markdown
- paddlepaddle:2.5.0-rc1/2.5.1
- paddlepaddle-gpu: 2.5.1.post120
- paddlenlp: 2.6.0.post
NVIDIA Tesla P4 CUDA 12.0
详细信息如下
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:12:58_PDT_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
paddlenlp的ie = Taskflow('information_extraction', schema=schema, model='uie-base')
在
paddlepaddle=2.5.0rc1CPU下有结果，
paddlepaddle=2.5.1没有有结果。
安装GPU后2.5.0rc1和2.5.1都不出结果
```

### 稳定复现步骤 & 代码

1、CPU版本paddle:2.5.0-rc1下正常出结果

`
from pprint import pprint

from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称']

ie = Taskflow('information_extraction', schema=schema, model='uie-base')

pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
`

`

[{'时间': [{'end': 6,
          'probability': 0.9857378532473966,
          'start': 0,
          'text': '2月8日上午'}],
  '赛事名称': [{'end': 23,
            'probability': 0.850308274507654,
            'start': 6,
            'text': '北京冬奥会自由式滑雪女子大跳台决赛'}],
  '选手': [{'end': 31,
          'probability': 0.8981546917607339,
          'start': 28,
          'text': '谷爱凌'}]}]`

2、CPU版本paddle:2.5.1下不出结果
[{}]

3、安装GPU情况下，无论使用paddle:2.5.0-rc1还是paddle:2.5.1，都不出结果
[{}]

**Comment by RoacherM** [comment]
我也遇到这个问题了，用的默认例子
❯ pip list | grep paddle
paddle-bfloat         0.1.7
paddle2onnx           1.0.9
paddlefsl             1.1.0
paddlenlp             2.6.0
paddleocr             2.7.0.2
paddlepaddle          2.5.1

**Comment by iwhyshop** [comment]
搞定了用develop那个版本就可以



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Houpus ***@***.***&gt;
发送时间: 2023年9月1日 15:39
收件人: PaddlePaddle/PaddleNLP ***@***.***&gt;
抄送: Showker ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [PaddlePaddle/PaddleNLP] [Bug]: paddlenlp在2.5.0rc1CPU下有结果，2.5.1结果为空。安装GPU后2.5.0rc1和2.5.1结果都为空 (Issue #6884)





 
我也遇到这个问题了，用的默认例子
 ❯ pip list | grep paddle
 paddle-bfloat         0.1.7
 paddle2onnx           1.0.9
 paddlefsl             1.1.0
 paddlenlp             2.6.0
 paddleocr             2.7.0.2
 paddlepaddle          2.5.1

**Comment by iwhyshop** [comment]
搞定了用develop那个版本就可以

python -m pip install paddlepaddle-gpu==0.0.0.post120 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/5828223/0ab45527-13cd-4c35-8e67-51fb3585433c)

**Comment by sijunhe** [comment]
确实 paddle 2.5.1的cpu inference是有点问题的，希望用cpu使用UIE taskflow的话，可以稍微回退一下paddle版本 到2.5.0-rc1或者更早

**Comment by sijunhe** [comment]
> 搞定了用develop那个版本就可以
> 
是的，当前这个问题develop已经修复了，稳定版需要等到下一次paddle发版。先用develop也可以的

**Comment by yxk9810** [comment]
paddle2onnx           1.0.9
paddlefsl             1.1.0
paddlenlp             2.6.0
paddleocr             2.7.0.2
paddlepaddle-gpu      0.0.0.post112


document intelligent 使用cpu有结果，gpu也是无结果，替换使用develop安装包也不行呀

**Comment by tangtangv** [comment]
paddle2onnx           1.0.6
paddlefsl             1.1.0
paddlenlp             2.6.0
paddleocr             2.7.0.0
paddlepaddle          2.5.0
python 3.9.17

cpu 跑的结果跟示例不一样啊
from pprint import pprint
from paddlenlp import Taskflow
schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction')
ie.set_schema(schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

 FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal 
input size of the model (e.g. 512 for Bert).
  warnings.warn(
[{'时间': [{'end': 0, 'probability': 0.2681570091207419, 'start': 27, 'text': ''},
         {'end': 14,
          'probability': 0.260949134562793,
          'start': 11,
          'text': '自由式'}],
  '赛事名称': [{'end': 0,
            'probability': 0.3742573899303352,
            'start': 0,
            'text': ''},
           {'end': 0,
            'probability': 0.3255384454863872,
            'start': 0,
            'text': ''},
           {'end': 12,
            'probability': 0.4159634075219998,
            'start': 9,
            'text': '奥会自'},
           {'end': 0,
            'probability': 0.35813834356179086,
            'start': 0,
            'text': ''}]}]

请问这个是什么原因啊？ 而且每次的结果都不一样
