### ISSUE TITLE
[Question]: paddlenlp上的项目能否应部署到arm架构上？有什么可能的风险？

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#6887]
### 请提出你的问题

关于应用paddlenlp的项目部署到arm架构的问题，问题如标题。

**Comment by sijunhe** [comment]
您好，arm架构在PaddleNLP的层面没什么风险，风险来自与Paddle框架。目前Paddle框架是官方支持arm架构的，但是暂时还不提供直接下载，需要您从源代码进行编译，可以参考以下这个[https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html](安装指南)
