### ISSUE TITLE
[Question]: 加载paddlelnp时报错：module 'paddle' has no attribute 'io'

### ISSUE THREAD

**Issue by wzstang1994** [PaddlePaddle/PaddleNLP#6888]
### 请提出你的问题

环境：
python 3.8.15
paddle 1.0.2
paddlepaddle  2.3.2
paddlelnp 2.6.0

**Comment by wzstang1994** [comment]
在linux上安装的环境，用pip3 install 安装模块
from paddlenlp import Taskflow引入报错
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/40292145/c080cd81-3b25-47a3-9ec9-ab5ef32d809d)

import paddle.fluid as fluid
fluid.install_check.run_check() 
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/40292145/0ddb2d10-7b56-4e26-8a1a-bc4de96a4565)

**Comment by sijunhe** [comment]
您好，这个问题是您使用的两个库版本不匹配。paddlepaddle 2.3.2  paddlelnp 2.6.0

如果您希望使用最新的paddlenlp 2.6.0, 那么需要paddlepaddle >= 2.5.1
如果您希望继续使用原有的paddlepaddle 2.3.2, 那么可以使用paddlenlp 2.5.0 就可以了, 这个版本可以满足您使用taskflow
