### ISSUE TITLE
LAC训练词重要性

### ISSUE THREAD

**Issue by justiceeem** [PaddlePaddle/PaddleNLP#689]
请问一下LAC如何增量训练词重要性呢？

**Comment by wawltor** [comment]
> 请问一下LAC如何增量训练词重要性呢？

不太理解您说的增量训练词重要性，辛苦解释一下了

**Comment by justiceeem** [comment]
@wawltor 开源的[lac](https://github.com/baidu/lac)工具，里面提供了词法分析训练和分词训练但是没有词重要性训练的相关内容。所以想请教一下。

**Comment by wawltor** [comment]
> @wawltor 开源的[lac](https://github.com/baidu/lac)工具，里面提供了词法分析训练和分词训练但是没有词重要性训练的相关内容。所以想请教一下。

目前PaddleNLP这块确实没有设置词的重要性训练这块，您可以去LAC repo来问一下相关的开发者如何进行训练，我们也跟踪一下这个LAC 词重要性训练这个需求，有相关的调研结论我们会在这个issue回复您

**Comment by wawltor** [comment]
@joey12300  辛苦调研一下 LAC有关词重要性的相关信息

**Comment by justiceeem** [comment]
谢谢！！

**Comment by chenxiaozeng** [comment]
@justiceeem 您好，不知道您是否找到了合适的方案，方便的话可以留下您的联系方式，或者邮件联系我们Paddle-better@baidu.com，我们可以 1 对 1 沟通下，以便更好得解答您的问题。谢谢！
