### ISSUE TITLE
关于classifier.weight和classifier.bias warning

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#690]
在做skep情感分析时候，使用模型加载API ：
model = SkepForSequenceClassification.from_pretrained(pretrained_model_name_or_path="skep_ernie_1.0_large_ch", num_classes=len(train_ds.label_list))

 加载完skep_ernie_1.0_large_ch.pdparams后，出现了以下的两个警告，

![image](https://user-images.githubusercontent.com/83859417/124453585-19b6d480-ddba-11eb-9046-b9d2c375c941.png)

看了一下from_pretrained方法的参数， 可变参数中似乎可以指定weight和bias， 想问一下，

1 这两个警告的side effect有没有？
2 classifier.weight和classifier.bias 指定后有什么更好效果吗？目前也没有发现这样的sample

希望能够给与提示，谢谢！

**Comment by wawltor** [comment]
1. 这两个警告对模型的效果没有影响 
2. 不需要指定 这个finetune需要训练的参数 

在SKEP模型底层依赖于的模型是ERNIE-Gram模型, 保存下来的ERNIE-Gram主要是预训练相关的参数，不会涉及下游finetune参数；classifier.weight和classifier.bias是finetune模型最后的分类器的参数，这个需要通过finetune后才能学习到，因此这两个参数不需要导入。

**Comment by LangDaoAI** [comment]
感谢回复！

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
