### ISSUE TITLE
[Question]: information_extraction使用uie-x-base模型时，报错The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'

### ISSUE THREAD

**Issue by iwhyshop** [PaddlePaddle/PaddleNLP#6912]
### 请提出你的问题

ie = Taskflow('information_extraction', schema=schema,model='uie-x-base',layout_analysis=False)
path='aaa.pdf';
    a = ie({"doc":path})
在分析pdf或图片时，使用uie-x-base时报如下错误,  uie-base模型没有问题。
```
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [7, 7, 4], X's size = 196, 'shape' is [49, 512], the capacity of 'shape' is 25088.
  [Hint: Expected capacity == in_size, but received capacity:25088 != in_size:196.] (at ../paddle/phi/infermeta/unary.cc:1889)

```
paddle用的devlep版本
```
paddle:0.0.0
paddlenlp:2.6.0.post
Running verify PaddlePaddle program ... 
I0904 17:53:48.566730 2465398 program_interpreter.cc:175] New Executor is Running.
W0904 17:53:48.567200 2465398 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.0, Runtime API Version: 12.0
W0904 17:53:48.568287 2465398 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
I0904 17:53:50.642114 2465398 interpreter_util.cc:602] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

paddleocr版本2.7.0.2如下
```
>>> print(paddleocr.__version__)
2.7.0.2
```

**Comment by rcx986635** [comment]
I have the same problem.

File "/home/xxx/PaddleNLP/paddlenlp/taskflow/information_extraction.py", line 981, in _single_stage_predict
    self.predictor.run()
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 561, 768], X's size = 430848, 'shape' is [561, 561, 12, 64], the capacity of 'shape' is 241705728.
  [Hint: Expected capacity == in_size, but received capacity:241705728 != in_size:430848.] (at /paddle/paddle/phi/infermeta/unary.cc:1781)
  [operator < reshape2 > error]

**Comment by rcx986635** [comment]
@yingyibiao
