### ISSUE TITLE
[Question]: uie-x-base，按照官方教程中的文档信息提取给的流程来进行微调时会报错

### ISSUE THREAD

**Issue by YesterdayisTuesday** [PaddlePaddle/PaddleNLP#6918]
### 请提出你的问题

会报以下的错 KeyError:'token_type_ids'
官方说明文档路径如下：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/document/README.md

**Comment by chinesejunzai12** [comment]
你好, 这个问题你解决了吗, 我也遇到了同样的问题, 请教一下
