### ISSUE TITLE
plato-2 运行报错

### ISSUE THREAD

**Issue by jaiminZhang** [PaddlePaddle/PaddleNLP#692]
![image](https://user-images.githubusercontent.com/24643210/124464508-dadb4b80-ddc6-11eb-971c-d03d1ac3b2f1.png)
python3.6

**Comment by smallv0221** [comment]
PLATO-2 needs python3.7+ to work. Sorry we didn't specify in the readme.

**Comment by jaiminZhang** [comment]
换成 python3.7 正常。多谢
