### ISSUE TITLE
[Question]: 基于pipelines的question-answering提示Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>.

### ISSUE THREAD

**Issue by xavieryang007** [PaddlePaddle/PaddleNLP#6933]
### 请提出你的问题

Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>.

测试安装了多个版本都无法正常，包括docker模式。

最终安装的是paddlepaddle 2.4.2
paddlenlp2.4.9
pipelines所有版本都测试了，都是一样的错误信息。

**Comment by w5688414** [comment]
> ### 请提出你的问题
> Unable to generate pydantic-core schema for <class 'pandas.core.frame.DataFrame'>.
> 
> 测试安装了多个版本都无法正常，包括docker模式。
> 
> 最终安装的是paddlepaddle 2.4.2 paddlenlp2.4.9 pipelines所有版本都测试了，都是一样的错误信息。

cpu版本？请问环境是什么呢？

**Comment by xavieryang007** [comment]
cpu版本 ，windows11下
