### ISSUE TITLE
[Question]: 文档错误多不完善，许多实例无法复现

### ISSUE THREAD

**Issue by anomousA** [PaddlePaddle/PaddleNLP#6936]
### 请提出你的问题

这段时间用了下paddlenlp，辗转多个文档，被飞桨主页和github页面的各种不统一的文档搞得晕头转向：
1. docker的paddleserver部署存在恶性bug无法正常运行，环境检测失败，之前有人提交issue没有答复
2.“推荐使用 Trainer API 对模型进行微调”，trainer api一个详细的文档都没有，随便丢个示例糊弄谁啊，paddle的开发团队真抽象，浪费用户时间。
建议管理层别干了

**Comment by zzwtop1** [comment]
文档确实很拉跨
