### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#695]
想问一下skep_ernie_2.0_large_ch还会加入到预训练模型库中吗， 还是说skep_ernie_2.0_large_ch相比skep_ernie_1.0_large_ch效果提升并不是很明显， 另外， 情感分析模型今天看到ernie 3.0直接可以做垂直任务，是不是后面要把ernie 3.0也加入进来， 希望得到team的回复， 感谢！

**Comment by Steffy-zxf** [comment]
你好！目前ernie 2.0/3.0中文模型还未开源。如果后期开源，将会第一时间告知您，也请同时多多关注PaddleNLP更多中文模型开源信息！

**Comment by LangDaoAI** [comment]
> 你好！目前ernie 2.0/3.0中文模型还未开源。如果后期开源，将会第一时间告知您，也请同时多多关注PaddleNLP更多中文模型开源信息！

感谢您的回复！
