### ISSUE TITLE
关于Skep模型压缩

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#696]
想确认一下Skep模型压缩有示例吗，还是说参考https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/model_compression/ofa 进行修改？谢谢！

**Comment by LiuChiachi** [comment]
您好，基于Skep模型的压缩示例目前没有直接提供，但是您可以对model_compression目录下现有的几个示例（包括ofa）进行修改，把bert改成skep进行实验~

**Comment by LangDaoAI** [comment]
嗯好的，我暂时先开着这个问题

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
