### ISSUE TITLE
[Question]: 使用conda环境得到的结果错误，每次都不一样

### ISSUE THREAD

**Issue by hanhing** [PaddlePaddle/PaddleNLP#6960]
### 请提出你的问题

使用conda环境的得到的结果明显错误，还每次都不一样，使用系统环境则正常，使用的paddlenlp版本为2.5.2，conda环境从3.8到3.10都试过了，结果都一样，在同事的电脑上也试过了，在Linux下也试过了，都不行，截图如下：

这是conda环境下的官方示例：
![py38](https://github.com/PaddlePaddle/PaddleNLP/assets/50894846/24e8ce52-559b-492e-8407-b41b5f80e4fe)

**Comment by RobinDNA** [comment]
我也遇到一样的问题，[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP) 已经好久没更新了， NLP的官方示例都跑不通， 垃圾

**Comment by tangtangv** [comment]
遇到了一样的问题！！！有没有哪位是可以跑通官方示例的？

**Comment by hanhing** [comment]
@RobinDNA @tangtangv 解决问题了，在前面issues中看了个回答，在安装paddlepaddle的时候安装开发版即可，已经安装的卸载重装，亲测可用，如下图：我用的是CPU，GPU没测。这好像是一个bug，不过这开发版比稳定版好用我也是没见过
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50894846/c71548f7-51b7-476e-8a41-2e5a98b961d9)
