### ISSUE TITLE
关于plato2 添加特征值多用户聊天

### ISSUE THREAD

**Issue by jaiminZhang** [PaddlePaddle/PaddleNLP#697]
Dear all.
现在想使用服务对外提供算力，每个用户在和机器人聊天的时候。机器人根据用户id记录用户属性。在之后的聊天中也能记住这些特征值。
我司在此方面有很强烈的需求，希望能达成一定的合作。
静候佳音。

**Comment by portia1026** [comment]
从描述看，PLATO 应该是可以支持这个需求。如果方便的话，请把联系方式发到我邮箱（baosiqi@baidu.com），后续我们相关同学会联系你。

**Comment by jaiminZhang** [comment]
多谢。
