### ISSUE TITLE
[Question]: 使用最新版本的paddle和paddlenlp，在使用Taskflow中的feature_extraction任务中的官方示例代码时，遇到值异常的问题

### ISSUE THREAD

**Issue by wqainlpdl** [PaddlePaddle/PaddleNLP#6977]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/44708429/9ac2e7bd-e515-474a-9f5f-a2ad413d463c)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/44708429/4df11077-ceb2-478e-bd5b-e428f0438c6c)

**Comment by wqainlpdl** [comment]
这是官方代码
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/44708429/8ee615ce-d4cd-46e0-b8ba-64e517213836)

**Comment by w5688414** [comment]
what's your environment setup?

**Comment by wqainlpdl** [comment]
Paddlepaddle与paddlenlp最新版本，我是按照paddlenlp的官方文档安装的。
***@***.***
Paddlepaddle
***@***.***
然后，再运行我贴的问题中的示例代码，就出现了那个问题，可以试试，应该可以复现的

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年9月11日 10:43
收件人: ***@***.***>
抄送: Yoshua ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/PaddleNLP] [Question]: 使用最新版本的paddle和paddlenlp，在使用Taskflow中的feature_extraction任务中的官方示例代码时，遇到值异常的问题 (Issue #6977)


what's your environment setup?

―

**Comment by wqainlpdl** [comment]
大佬，这个问题有结论了吗？

**Comment by neilzhang-strong** [comment]
遇到同样的问题，解决了吗？
