### ISSUE TITLE
PaddleNLP训练好的模型如何部署到服务器

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#698]
类似问题https://aistudio.baidu.com/forum/topic/show/983531

推荐的做法请告知一下，谢谢！

**Comment by LangDaoAI** [comment]
看到https://github.com/PaddlePaddle/PaddleNLP/issues/115 提到了3月份出高性能部署教程， 请告知一下教程地址

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/electra 您好，这里有个示例包含了动转静，以及最终部署的过程 可以参考这个看看

**Comment by LangDaoAI** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/electra 您好，这里有个示例包含了动转静，以及最终部署的过程 可以参考这个看看

感谢感谢！

**Comment by LangDaoAI** [comment]
这个问题我先open一下， 一旦确认没有问题我将关闭。
