### ISSUE TITLE
【文本匹配】与【语义索引中文档匹配】是否可以合并？

### ISSUE THREAD

**Issue by Junshuai-Song** [PaddlePaddle/PaddleNLP#699]
文本匹配：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_matching/simnet
语义索引匹配：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing

感觉语义索引任务中，核心也是文本匹配?

**Comment by tianxin1860** [comment]
语义索引要解决的核心问题是如何从海量 doc 中通过 ANN 索引的方式快速、准确地找出跟 query 的相关 doc，语义匹配要解决的核心问题是对 query、doc 更精细的语义匹配信息建模.

**Comment by Junshuai-Song** [comment]
先感谢这么高效的回复！

上述语义索引示例中提供了（1）前沿语义索引策略的训练、（2）语义索引模型的效果评估方案，两大部分内容。
我理解其中第（1）部分的核心是在考虑如何训练一个更好的语义文本匹配模型；第（2）部分则可以基于ANN构建索引进行快速检索。

这里第（1）部分介绍的语义文本匹配模型，和另一个链接给出的文本匹配模型有什么重点上的区别吗？换句话说另一个文本匹配链接中介绍的内容是不是也可以融入到语义索引的索引策略训练部分？

**Comment by Junshuai-Song** [comment]
@tianxin1860

**Comment by tianxin1860** [comment]
> 先感谢这么高效的回复！
> 
> 上述语义索引示例中提供了（1）前沿语义索引策略的训练、（2）语义索引模型的效果评估方案，两大部分内容。
> 我理解其中第（1）部分的核心是在考虑如何训练一个更好的语义文本匹配模型；第（2）部分则可以基于ANN构建索引进行快速检索。
> 
> 这里第（1）部分介绍的语义文本匹配模型，和另一个链接给出的文本匹配模型有什么重点上的区别吗？换句话说另一个文本匹配链接中介绍的内容是不是也可以融入到语义索引的索引策略训练部分？
这部分换个角度理解更容易一些: [语义索引](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing)是要解决搜索、推荐场景下的召回问题、而语义匹配是要解决排序问题，两者要解决的问题不同，所采用的方案会有很大不同，但也存在一些共通的技术点，可以互相借鉴.

**Comment by tianxin1860** [comment]
这部分换个角度理解更容易一些: [语义索引](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/semantic_indexing)是要解决搜索、推荐场景下的召回问题、而语义匹配是要解决排序问题，两者要解决的问题不同，所采用的方案会有很大不同，但也存在一些共通的技术点，可以互相借鉴.

**Comment by Junshuai-Song** [comment]
thx!
