### ISSUE TITLE
调用Taskflow 得到的结果和官方给的实例不一样

### ISSUE THREAD

**Issue by tangtangv** [PaddlePaddle/PaddleNLP#6997]
### 请提出你的问题

python 3.9.17
paddle-bfloat         0.1.7
paddle2onnx           1.0.6
paddlefsl             1.1.0
paddlenlp             2.6.0
paddleocr             2.7.0.0
paddlepaddle          2.5.0

cpu调用Taskflow 得到的结果和官方给的实例不一样：

from pprint import pprint
from paddlenlp import Taskflow
schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

结果：
tokenizer_utils_base.py:1878: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal 
input size of the model (e.g. 512 for Bert).
  warnings.warn(
[{'时间': [{'end': 4,
          'probability': 0.29468374504864414,
          'start': 3,
          'text': '日'}],
  '赛事名称': [{'end': 12,
            'probability': 0.39339868023475333,
            'start': 9,
            'text': '奥会自'},
           {'end': 6,
            'probability': 0.30246450581736894,
            'start': 5,
            'text': '午'},
           {'probability': 0.29940597926696455, 'text': '事'},
           {'probability': 0.32003069242905724, 'text': '赛'}]}]

并且每次调用得到的结果都不一样！请问这个是什么原因呢？

**Comment by whuter** [comment]
+1 我也遇到了

**Comment by tangtangv** [comment]
收到！唐明榕

**Comment by RobinDNA** [comment]
+1 一样的问题，这跟广告效果天差地别

**Comment by yhl666mail** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/85988803/8d64cac3-1ea7-4ab8-be46-9c33a5317a5b)
一样遇到错别纠正根本没法使用

**Comment by tangtangv** [comment]
我现在已经解决了，好像是现在的版本会有问题。目前在cpu使用版本：paddlenlp： 2.3.4；paddlepaddle：2.3.0

**Comment by Chanwb** [comment]
> ![image](https://user-images.githubusercontent.com/85988803/267512240-8d64cac3-1ea7-4ab8-be46-9c33a5317a5b.png) 一样遇到错别纠正根本没法使用

我也是得到和你类似的结果

**Comment by Chanwb** [comment]
> 我现在已经解决了，好像是现在的版本会有问题。目前在cpu使用版本：paddlenlp： 2.3.4；paddlepaddle：2.3.0

我也是改成了这个版本，效果和demo样例一致

**Comment by Lowpower** [comment]
这问题还能解吗?
