### ISSUE TITLE
是否有基于paddlenlp的 aspect-level sentiment analysis

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#700]
目前能够看到的使用paddlenlp都是面向极性判断的sentiment analysis，以及顶会中公开的aspect-level sentiment analysis很多基于pytorch， 是否有基于paddlenlp的 aspect-level sentiment analysis供参考， 或者说有这样的plan来基于paddlenlp来做三元组的情感分析，希望给与一些提示，谢谢！

**Comment by Steffy-zxf** [comment]
你好！aspect-level sentiment analysis 可以参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/skep/train_aspect.py

**Comment by LangDaoAI** [comment]
> 你好！aspect-level sentiment analysis 可以参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/sentiment_analysis/skep/train_aspect.py

是的，几个任务都在https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/sentiment_analysis/skep， 感谢回复！
