### ISSUE TITLE
[Bug]: Taskflow文本纠错text_correction 调用输出结果和官方示例结果不一样错别字只有"既"字

### ISSUE THREAD

**Issue by yhl666mail** [PaddlePaddle/PaddleNLP#7000]
### 软件环境

```Markdown
- paddlepaddle:2.5.1
- paddlepaddle-cpu 
- paddlenlp: 2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
代码
from paddlenlp import Taskflow
corrector = Taskflow("text_correction")
result =  corrector("遇到逆竟时，我们必须勇于面对，而且要愈挫愈勇。")
print(result)
结果：
[{'source': '遇到逆竟时，我们必须勇于面对，而且要愈挫愈勇。', 'target': '遇到逆竟时，我既必须既既面既，而既既愈挫既勇。', 'errors': [{'position': 7, 'correction': {'们': '既'}}, {'position': 10, 'correction': {'勇': '既'}}, {'position': 11, 'correction': {'于': '既'}}, {'position': 13, 'correction': {'对': '既'}}, {'position': 16, 'correction': {'且': '既'}}, {'position': 17, 'correction': {'要': '既'}}, {'position': 20, 'correction': {'愈': '既'}}]}]
```

### 稳定复现步骤 & 代码

每次调用结果一样

**Comment by yhl666mail** [comment]
这个是官方示例输出结果
[{'source': '遇到逆竟时，我们必须勇于面对，而且要愈挫愈勇。', 'target': '遇到逆境时，我们必须勇于面对，而且要愈挫愈勇。', 'errors': [{'position': 3, 'correction': {'竟': '境'}}]}]

**Comment by yhl666mail** [comment]
corrector('遇到逆竟时，我们必须勇于面对，而且要愈挫愈勇。')
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/85988803/4d161029-abef-4e6b-b6fb-0690a0a67179)

**Comment by Chanwb** [comment]
应该是paddlepaddle和paddlenlp的问题，我原本的结果和你的一样，然后把paddlepaddle降到2.3.0 paddlenlp版本降到2.3.4 就能得到demo的展示效果

**Comment by ichigo-xin** [comment]
我用的paddlepaddle是2.5.0，paddlenlp是2.6.0，也有这样的问题。不降版本的话有什么解决方法吗？

**Comment by moqiaaa** [comment]
pip install paddlepaddle==2.5.0rc1 用这个版本没问题
