### ISSUE TITLE
[Question]: 无法抽取数据

### ISSUE THREAD

**Issue by jimmytanj** [PaddlePaddle/PaddleNLP#7001]
### 请提出你的问题

环境：
paddle-bfloat       0.1.7
paddle2onnx         1.0.6
paddlefsl           1.1.0
paddlenlp           2.6.0
paddlepaddle        2.5.1

代码：
from pprint import pprint
from paddlenlp import Taskflow
schema = ['时间', '选手', '赛事名称']
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

得到结果：
[{}]

问题：
为啥官方示例上的代码运行起来都无法正确抽取，换了几个环境都是一样的效果，UIE是不能用了么

**Comment by kerry-weic** [comment]
我本机环境正常，相关依赖包版本如下:
```
(paddle_env) C:\Users\aoc>pip3 list | findstr paddle
paddle-bfloat         0.1.7
paddle2onnx           1.0.6
paddleclas            2.5.1
paddlefsl             1.1.0
paddlenlp             2.5.2
paddleocr             2.6.1.3
paddlepaddle          2.4.2
x2paddle              1.4.1
```

**Comment by flycocopig** [comment]
> 

我也是出现同样的问题。试过了，必须跟@kerry-weic提供的版本一致才能提取到信息
