### ISSUE TITLE
[Question]: 同一个文本分类模型在GPU和CPU环境上表现不一致

### ISSUE THREAD

**Issue by jiaolongxue** [PaddlePaddle/PaddleNLP#7004]
### 请提出你的问题

在一台有显卡windows机器上，用paddlenlp训练了一个三分类的模型，代码路径PaddleNLP/applications/text_classification/multi_class，并且windows机器上用paddlenlp里面的simple_serving部署，预测结果比较符合预期，然后把这个模型在另外一台linux服务器上部署，这个服务器是没有显卡的，安装的是paddle的cpu版本，同样用simple_serving部署，然后预测的结果就很奇怪了。
训练参数
```
python train.py ^
    --do_train ^
    --do_export ^
    --do_eval ^
    --debug True ^
    --model_name_or_path ernie-3.0-base-zh ^
    --output_dir checkpoint_20230912_2 ^
    --device gpu ^
    --num_train_epochs 100 ^
    --early_stopping True ^
    --early_stopping_patience 5 ^
    --learning_rate 3e-5 ^
    --max_length 128 ^
    --per_device_eval_batch_size 32 ^
    --per_device_train_batch_size 32 ^
    --metric_for_best_model accuracy ^
    --load_best_model_at_end ^
    --logging_steps 5 ^
    --evaluation_strategy epoch ^
    --save_strategy epoch ^
    --save_total_limit 1

```
CPU环境上的预测表现
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/21324579/5ffe3f01-1703-41d9-8cc6-5fa807c32fd3)

在GPU上的表现
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/21324579/9bbb2749-4bfd-4e25-903e-300e391d8b87)

模型未做裁剪，simple_serving启动参数
```python
Taskflow("text_classification", task_path="../../checkpoint_20230912_2/export", is_static_model=True)
```

**Comment by rchong3** [comment]
Disabling mkldnn might help. I was able to accomplish this by moving `self._config.enable_mkldnn()` from line 197 of https://github.com/PaddlePaddle/PaddleNLP/blob/10ff94a752f45b7990a01c074e9b5e4dac561aad/paddlenlp/taskflow/task.py into the following if statement (right before line 200).
