### ISSUE TITLE
Ernie训练自定义数据集时加入字典信息

### ISSUE THREAD

**Issue by wangcn99** [PaddlePaddle/PaddleNLP#702]
在利用Ernie训练自定义模型的时候
有额外的字典信息怎么加入vocab.txt

**Comment by guoshengCS** [comment]
这里是希望使用额外的字典信息做什么呢，ERNIE这些预训练模型通常使用和预训练阶段一样的字典就可以了，另外直接使用ERNIE的tokenizer会按照字粒度来切分无法产生词。也有另一种方式可以使用这些字典信息，可以将数据中在词典信息中的词进行整体mask进行一个mask language model的二次预训练。

**Comment by wangcn99** [comment]
主要是针对医学方面有一些定义好的固定词语 我直觉上认为vocab通过添加这些固定词语作为额外的信息能够引入模型，提高模型的性能：）关于第二种方式有相关的例子或者API文档吗 指（另一种方式可以使用这些字典信息，可以将数据中在词典信息中的词进行整体mask进行一个mask language model的二次预训练。）

**Comment by guoshengCS** [comment]
> 关于第二种方式有相关的例子或者API文档吗 

可以参考下这里 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/pretraining_data_prepare
