### ISSUE TITLE
[Question]: UIE模型转为ONNX后如何使用ONNX进行推理

### ISSUE THREAD

**Issue by gabrielpondc** [PaddlePaddle/PaddleNLP#7020]
### 请提出你的问题

是否有示例,ONNX模型的输入和输出分别是什么,是否中间需要再编写函数进行数据处理,因为我看有的实例中还有vocab.txt的引入,官网的ONNX模型的使用例子也不适用于UIE模型,schema我该如何设置也不明白

**Comment by DrJacksons** [comment]
其实在PaddleNLP代码仓库的taskflow模块代码里有UIE加载onnxruntime引擎推理的部分，可以看一下paddlenlp/taskflow/task.py和paddlenlp/taskflow/taskflow.py里面的代码逻辑。onnxruntime 调用run方法要传的input参数为input_dict = {
                        "input_ids": input_ids.numpy(),
                        "token_type_ids": token_type_ids.numpy(),
                        "position_ids": pos_ids.numpy(),
                        "attention_mask": att_mask.numpy(),
                    }

**Comment by gabrielpondc** [comment]
了解，感谢

**Comment by gabrielpondc** [comment]
了解，感谢

**Comment by zhangzef** [comment]
哈喽！ @gabrielpondc  请问你转换onnx成功了嘛，如果成功的话方便发一下转换和部署的代码嘛，我在本地转换onnx后发现uie的测试结果为0，一直没明白原因是什么，感谢！
