### ISSUE TITLE
API 怎么调用 ChatGLM-6B、ChatGLM2-6B、Bloom、OPT、Qwen

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleNLP#7023]
### 问题描述

```python
 from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("linly-ai/chinese-llama-2-7b")
model = AutoModelForCausalLM.from_pretrained("linly-ai/chinese-llama-2-7b", dtype="float16")
input_features = tokenizer("你好！请自我介绍一下。", return_tensors="pd")
outputs = model.generate(**input_features, max_length=128)
tokenizer.batch_decode(outputs[0])
```

官方只有 chinese-llama-2-7b 的

如果改为 ChatGLM-6B、ChatGLM2-6B、Bloom、OPT、Qwen
就会报错

API 怎么调用 ChatGLM-6B、ChatGLM2-6B、Bloom、OPT、Qwen

**Comment by DrownFish19** [comment]
1. 在`PaddleNLP/llm`目录下包含多个模型文件目录，相应目录下有对应的**支持模型权重**，可以参考**支持模型权重**名称进行填写。
2. 针对OPT给出以下样例
```python
    from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
    tokenizer = AutoTokenizer.from_pretrained("facebook/opt-125m")
    model = AutoModelForCausalLM.from_pretrained("facebook/opt-125m", dtype="float16")
    input_features = tokenizer("你好！请自我介绍一下。", return_tensors="pd")
    outputs = model.generate(**input_features, max_length=128)
    print(tokenizer.batch_decode(outputs[0]))
```

**Comment by whisky-12** [comment]
> 1. 在`PaddleNLP/llm`目录下包含多个模型文件目录，相应目录下有对应的**支持模型权重**，可以参考**支持模型权重**名称进行填写。
> 2. 针对OPT给出以下样例
> 
> ```python
>     from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
>     tokenizer = AutoTokenizer.from_pretrained("facebook/opt-125m")
>     model = AutoModelForCausalLM.from_pretrained("facebook/opt-125m", dtype="float16")
>     input_features = tokenizer("你好！请自我介绍一下。", return_tensors="pd")
>     outputs = model.generate(**input_features, max_length=128)
>     print(tokenizer.batch_decode(outputs[0]))
> ```

您好 ，请问是否可以适用这个接口 ，加载从[huageface](https://huggingface.co/)中下载的模型，比如我下载了 codellama-7b的模型，文件结构如下：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/79358023/9828ed19-b5b2-4bfb-a501-4a598b119f2b)
请问如果我AutoTokenizer.from_pretrained(“本地模型路径”) 这样的格式接口是否支持使用？
