### ISSUE TITLE
关于max_seq_length

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#703]
Skep模型中max_seq_length默认设置512， 如果训练集中的句子的长度超过512, 目前是做截断处理的， transformer模型的一个问题就是序列长度对时间复杂度的影响，所以做截断是能够理解的，我想问一下的是，有没有其他模型（例如处理超长句子）可以使用，昨天看到了ernie-doc（https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-doc）可以处理超长文本，例如如下的一个超长句子：

荣耀手机在经过了差不多半年的休整，现在已开始陆续“出招”了！这次的新品是款非常非常轻薄的机型---荣耀Play5。这款机型很有些特点，有幸我提前体验了段时间，下面边看图赏边来聊聊这款荣耀的新机型。    轻薄直角质感｜  荣耀Play5我上手第一感觉就是轻，很轻很薄。采用的是玻璃材质背部直角边框，整体的质感还是挺可以的。我手上这台是幻夜黑配色，低调简约纯粹。还有两款冰岛幻境和钛空银的配色就要相对更炫些。    66W超级快充｜  对于现在选智能手机，充电速度怎么样？已是很重要的一项标准。这次荣耀Play5搭载的是单电芯双回路66W超级快充技术。这个技术拥有更节约机身空间、不存在老化差异、安全系数更高的优点。再加上高导热石墨烯自动控温、电芯循环寿命提升加持，这点很可以。    我的实际体验感受，荣耀Play5的充电，在电量只有5%的时候充电15分钟左右，电量即可充至60%，继续充至差不多半小时就可以充满，这样的话利用碎片时间给手机充个电，不经意间，电量就满了的感觉真是不错。对了还有一点，荣耀Play5标配的充电头体积要小巧很多，并且支持100V～240V宽电压。这对经常出差的朋友来说非常友好，充电头轻了速度却快了。荣耀Play5可以说是同档位最佳快充体验手机。    OLED屏幕｜  这次荣耀Play5采用的是6.53英寸的OLED屏幕，支持DCI-P3广色域，支持AOD灭屏显示，显示效果还是可以的。    后置超清四摄｜  荣耀Play5的后置四摄包括： 6400万超清主镜头、800万超广角镜头、4cm微距镜头和专业人像景深镜头。这个四摄的布局方式可以是很“稳妥”今年很多机型所采用的都是这种左上角摄像模组的ID设计，不过荣耀Play5的摄像模组凸起度很低，加上保护壳基本上整个机身应该都是平齐的。后面有些实拍的样张，大家看看怎样？    还有更多｜  荣耀Play5主副卡槽同时支持5G，同时也拥有5G省电技术，更快更省电。搭载的是Magic UI 4.0智慧系统，还有多功能NFC。相对这个价位，整体来说这款机子还是很有“战斗力”的，大家觉得呢？

想听一下建议，谢谢！

**Comment by guoshengCS** [comment]
ERNIE-DOC模型目前还在开发中 https://github.com/PaddlePaddle/PaddleNLP/pull/613 ，合入后我们在这里更新通知。当前已经集成的模型中XLNet和BigBird也可以试下

**Comment by LangDaoAI** [comment]
> ERNIE-DOC模型目前还在开发中 #613 ，合入后我们在这里更新通知。当前已经集成的模型中XLNet和BigBird也可以试下

Great News! 感谢回复！ 这个问题请保留一下， #613 merge后我将关闭这个issue。
