### ISSUE TITLE
[Question]:使用命名实体模型处理文本返回为空 

### ISSUE THREAD

**Issue by qingfengcss** [PaddlePaddle/PaddleNLP#7033]
### 请提出你的问题

环境：
paddlenlp           2.6.1.post0
paddlepaddle-gpu    2.5.1

测试代码：
from paddlenlp import Taskflow

def run(sentences):
    ner = Taskflow('ner')
    res_ner = ner(sentences)

if __name__ == '__main__':
    sentences = "电影《信条》杀青之后，演员罗伯特·帕丁森送给导演诺兰一本由凯·伯德和马丁·舍温共同撰写的《奥本海默传》。"
    # sentences = '《长津湖》收尾，北美是最大海外票仓'
    res = run(sentences)
    print（res)

测试结果：
/root/anaconda3/envs/test_paddlenlp/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/home/css/projects/knowledge_extract/ner_test/PaddleNLP/paddlenlp/transformers/tokenizer_utils_base.py:1865: UserWarning: Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
  warnings.warn(
None

**Comment by duhuan35** [comment]
你解决了吗
