### ISSUE TITLE
【急】【需要确认】visualDL使用无效

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#705]
visualDL已经安装，命令行我启动visualDL，结果看不到.\vdl_dir\scalar， 我是在CPU环境训练，训练正常结束。

d:\VOC评估\PVoc>python skep_sentiment_classification.py --use_vdl=true --vdl_log_dir=.\vdl_dir\scalar

![image](https://user-images.githubusercontent.com/83859417/124768931-a654c480-df6b-11eb-95cf-d9de1845bebc.png)

![image](https://user-images.githubusercontent.com/83859417/124769094-c84e4700-df6b-11eb-8182-ed74aa972998.png)

确认一下是不支持CPU？还是启动命令有问题？

**Comment by LangDaoAI** [comment]
这个能确认是否有问题吗

**Comment by ZeyuChen** [comment]
@LangDaoAI 麻烦提供下错误信息？没看出来使用无效的地方在哪？

**Comment by LangDaoAI** [comment]
就是没有看到错误信息，然后vdl目录也没有产生

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LangDaoAI** [comment]
我想确认一下发起的命令是否正确，python skep_sentiment_classification.py --use_vdl=true --vdl_log_dir=.\vdl_dir\scalar

**Comment by Steffy-zxf** [comment]
@LangDaoAI 你的训练代码脚本是否方便贴出来呢？参考的是哪里的实现呢？

**Comment by Steffy-zxf** [comment]
经线下沟通发现，`skep_sentiment_classification.py`训练脚本未使用vdl接口记录日志数据，导致vdl使用无效。
