### ISSUE TITLE
[Question]: 使用UIE微调之后，在cpu上的结果和gpu的结果不一致

### ISSUE THREAD

**Issue by chengtingting980903** [PaddlePaddle/PaddleNLP#7052]
### 请提出你的问题

GPU环境：Python3.7.13
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio==3.7.1
astor==0.8.1
async-timeout==4.0.3
asynctest==0.13.0
attrs==23.1.0
Babel==2.12.1
bce-python-sdk==0.8.90
beautifulsoup4==4.12.2
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
colorlog==6.7.0
concurrent-log-handler==0.9.24
cssselect==1.2.0
cycler==0.11.0
datasets==2.13.1
decorator==5.1.1
dill==0.3.4
dnspython==2.3.0
et-xmlfile==1.1.0
exceptiongroup==1.1.3
fastapi==0.103.0
filelock==3.12.2
Flask==2.2.5
flask-babel==3.1.0
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.1.0
future==0.18.3
h11==0.14.0
html2text==2020.1.16
html5lib==1.1
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.7.0
itsdangerous==2.1.2
jieba==0.42.1
Jinja2==3.1.2
joblib==1.3.2
kiwisolver==1.4.5
lxml==4.9.3
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.5.3
mdurl==0.1.2
multidict==6.0.4
multiprocess==0.70.12.2
numpy==1.21.6
onnx==1.14.1
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.1
paddle-bfloat==0.1.7
paddle2onnx==1.0.9
paddlefsl==1.1.0
paddlenlp==2.6.0
paddlepaddle==2.5.0
paddlepaddle-gpu==2.5.0
pandas==1.3.5
Pillow==9.5.0
portalocker==2.7.0
protobuf==3.20.2
psutil==5.9.5
py==1.11.0
pyarrow==12.0.1
pycryptodome==3.18.0
pydantic==2.3.0
pydantic_core==2.6.3
Pygments==2.16.1
pymongo==4.5.0
pyparsing==3.1.1
pyquery==2.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
rarfile==4.0
requests==2.31.0
retry==0.9.2
rich==13.5.2
safetensors==0.3.3
scikit-learn==1.0.2
scipy==1.7.3
sentencepiece==0.1.99
seqeval==1.2.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
starlette==0.27.0
threadpoolctl==3.1.0
tqdm==4.66.1
typer==0.9.0
typing_extensions==4.7.1
urllib3==2.0.4
uvicorn==0.22.0
visualdl==2.5.3
webencodings==0.5.1
Werkzeug==2.2.3
xxhash==3.3.0
yarl==1.9.2
zipp==3.15.0
CPU环境：
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio==3.7.1
astor==0.8.1
async-timeout==4.0.3
asynctest==0.13.0
attrs==23.1.0
Babel==2.12.1
bce-python-sdk==0.8.90
beautifulsoup4==4.12.2
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
colorlog==6.7.0
concurrent-log-handler==0.9.24
cssselect==1.2.0
cycler==0.11.0
datasets==2.13.1
decorator==5.1.1
dill==0.3.4
dnspython==2.3.0
et-xmlfile==1.1.0
exceptiongroup==1.1.3
fastapi==0.103.0
filelock==3.12.2
Flask==2.2.5
flask-babel==3.1.0
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.1.0
future==0.18.3
h11==0.14.0
html2text==2020.1.16
html5lib==1.1
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.7.0
itsdangerous==2.1.2
jieba==0.42.1
Jinja2==3.1.2
joblib==1.3.2
kiwisolver==1.4.5
lxml==4.9.3
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.5.3
mdurl==0.1.2
multidict==6.0.4
multiprocess==0.70.12.2
numpy==1.21.6
onnx==1.14.1
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.1
paddle-bfloat==0.1.7
paddle2onnx==1.0.9
paddlefsl==1.1.0
paddlenlp==2.6.0
paddlepaddle==2.5.0
pandas==1.3.5
Pillow==9.5.0
portalocker==2.7.0
protobuf==3.20.2
psutil==5.9.5
py==1.11.0
pyarrow==12.0.1
pycryptodome==3.18.0
pydantic==2.3.0
pydantic_core==2.6.3
Pygments==2.16.1
pymongo==4.5.0
pyparsing==3.1.1
pyquery==2.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
rarfile==4.0
requests==2.31.0
retry==0.9.2
rich==13.5.2
safetensors==0.3.3
scikit-learn==1.0.2
scipy==1.7.3
sentencepiece==0.1.99
seqeval==1.2.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
starlette==0.27.0
threadpoolctl==3.1.0
tqdm==4.66.1
typer==0.9.0
typing_extensions==4.7.1
urllib3==2.0.4
uvicorn==0.22.0
visualdl==2.5.3
webencodings==0.5.1
Werkzeug==2.2.3
xxhash==3.3.0
yarl==1.9.2
zipp==3.15.0
调用模型的代码：
my_ie = Taskflow("information_extraction", schema=self.schema, task_path='./checkpoint/model_best')
my_ie(text)
cpu上返回的结果是[{}]
但实际上GPU环境下返回的结果是非空的

**Comment by Mona59** [comment]
我也遇到了这个问题，本来抽取不出来的东西，gpu微调后能返回结果，cpu仍然返回空。

**Comment by NextGuido** [comment]
+1
