### ISSUE TITLE
llm目录下ernie-3.5-se此模型使用默认model_name_or_path无法从社区hub下载模型[Question]: 

### ISSUE THREAD

**Issue by tangleintel** [PaddlePaddle/PaddleNLP#7055]
### 问题描述

我在尝试按照llm/ernie-3.5-se目录下的README中描述的使用[动态图预测](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/ernie-3.5-se#4-%E5%8A%A8%E6%80%81%E5%9B%BE%E9%A2%84%E6%B5%8B)的命令时给model_name_or_path参数指定为"baidu/ernie-3.5-se-3b"（即默认参数）。随后在运行过程中发下模型无法从相应url（https://bj.bcebos.com/paddlenlp/models/community/baidu/ernie-3.5-se-3b/model.safetensors）加载。请问该地址是否为一个有效地址？如果不是，用户该如何指定正确的model_name_or_path参数从而获取到模型？
下图为在运行上述命令时的log与错误信息：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/83808509/c9e4f98a-9e98-4f17-8f3d-f43e4bdbf483)

**Comment by ZHUI** [comment]
没有训练好的模型，地址是你自己训练出来的 中间 ckpt 即可。
