### ISSUE TITLE
[Question]: 我在实现PaddleNLP官网的古爱凌的示例的时候，所抽取出来的信息并无意义

### ISSUE THREAD

**Issue by CHESE0801** [PaddlePaddle/PaddleNLP#7064]
### 请提出你的问题

我在实现PaddleNLP官网的古爱凌的示例的时候，所抽取出来的信息并无意义，与官方给出的并不相同，是什么原因呢
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/88099148/c36336af-1b03-4c06-a45a-34bcf7b1f0f1)

**Comment by CHESE0801** [comment]
我解决了，是现在的cpu版本会有问题。正确的cpu使用版本：paddlenlp： 2.3.4；paddlepaddle：2.3.0

**Comment by redemption-star** [comment]
我在使用谷爱凌例子的时候抽取出来的结果为空：[{}]

**Comment by 18772247265** [comment]
> 我解决了，是现在的cpu版本会有问题。正确的cpu使用版本：paddlenlp： 2.3.4；paddlepaddle：2.3.0

感谢，我试试看，我也是用的这个样例，paddlenlp 2.5.2，结果乱七八糟

**Comment by liuyi-193** [comment]
> 我在使用谷爱凌例子的时候抽取出来的结果为空：[{}]

请问解决了吗，我也是空，代码都一样呀，不知道怎么回事

**Comment by liuyi-193** [comment]
解决了就是版本问题

**Comment by 18772247265** [comment]
低版本确实可以了，但是好像还存在一个问题，同一个类型出现多次，识别效果不太好，比如“手机号”，如果句子中出现了多次，只能识别出来一次
