### ISSUE TITLE
[Question]: 信息提取任务如何直接输入图像数据？

### ISSUE THREAD

**Issue by msnoshain** [PaddlePaddle/PaddleNLP#7112]
### 请提出你的问题

使用uie-x-base对文档进行抽取任务时，需要输入图像路径。有没有办法直接输入Image对象或者ndarray等

**Comment by zhaoqf-cq** [comment]
以这个地址为例 `https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction#23` , 里面的文档信息抽取好像就能做

**Comment by msnoshain** [comment]
> 以这个地址为例 `https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/information_extraction#23` , 里面的文档信息抽取好像就能做

谢谢，已经解决了。输入base64即可
