### ISSUE TITLE
[Question]: uie-x 在进行微调后，发现部分case返回为空

### ISSUE THREAD

**Issue by zr-icu** [PaddlePaddle/PaddleNLP#7124]
### 请提出你的问题

使用uie-x 在1000左右训练量级的内容提取数据上进行训练，发现在标准的测试集上，F1 Score大概可以达到92%，大部分提取符合预期，但是有一些例子，明明是很简单的内容，但是最终提取为[]，这种可能是什么情况导致的呢？ 我这边调整了负样本的比例，但是收益不大，在个别例子上还是无法做到准确提取。 【是指非常规范的数据上，但是却提取不到内容的情况，不是hardcase的数据】

**Comment by zhaoqf-cq** [comment]
大哥, 你的 config 文件怎么解决的啊? 我微调的时候要去加载一个 config.json文件,提示找不到

**Comment by zr-icu** [comment]
您好 程铖已经收到您的邮件

**Comment by zr-icu** [comment]
> 大哥, 你的 config 文件怎么解决的啊? 我微调的时候要去加载一个 config.json文件,提示找不到

这个都是自动检测，然后如果没有的话会自动下载的呀？ 你是不是模型选错了？

**Comment by zhaoqf-cq** [comment]
> > 大哥, 你的 config 文件怎么解决的啊? 我微调的时候要去加载一个 config.json文件,提示找不到
> 
> 这个都是自动检测，然后如果没有的话会自动下载的呀？ 你是不是模型选错了？

应该没有选错吧，报错信息是
```
FileNotFoundError: configuration file<config.json> or <model_config.json> not found
```
我用的uie-x-base 根据文档`https://github.com/PaddlePaddle/PaddleNLP/blob/develop/applications/information_extraction/text/README.md`一步步来的
我看代码是从网络上下载 config.json 文件， 但是那个地址 没有哪个文件了
