### ISSUE TITLE
请fix model_compression/tinybert/imgs/tinybert.png

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#713]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/model_compression/tinybert/imgs/tinybert.png 已经丢失，请修补一下

**Comment by FrostML** [comment]
麻烦 @LiuChiachi 看看

**Comment by ZeyuChen** [comment]
Solve by #714 .
Thanks for your feedback @LangDaoAI
