### ISSUE TITLE
[Question]: AttributeError: module 'paddle' has no attribute 'io'

### ISSUE THREAD

**Issue by jaydenlau014** [PaddlePaddle/PaddleNLP#7158]
### 请提出你的问题

Traceback (most recent call last):

  File C:\ProgramData\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\alpha\spyder\telegram copilot\untitled1.py:8
    import paddlenlp

  File ~\AppData\Roaming\Python\Python310\site-packages\paddlenlp\__init__.py:35
    from . import (

  File ~\AppData\Roaming\Python\Python310\site-packages\paddlenlp\data\__init__.py:15
    from .blendable_dataset import *

  File ~\AppData\Roaming\Python\Python310\site-packages\paddlenlp\data\blendable_dataset.py:30
    class BlendableDataset(paddle.io.Dataset):

AttributeError: module 'paddle' has no attribute 'io'

Do anyone know how to solve this?

**Comment by thetaaaaa** [comment]
Hi, I occured the same problem, would you mind tell me how to solve the problem ? Much thanks.

**Comment by vivisidea** [comment]
> Hi, I occured the same problem, would you mind tell me how to solve the problem ? Much thanks.

install or upgrade paddlepaddle to latest version may resolve your problem.

```
pip install --upgrade paddlepaddle
```
