### ISSUE TITLE
想问下这个self-attention这个多头注意力最后这个out_reshape后形状不应该是 [batch_size,词语数量，多头*词向量]那么为什么这个out_obj输入的是embedding 而不是embedding*多头数呢

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#716]
https://github.com/PaddlePaddle/PaddleNLP/blob/7c76b2f61191b8706802430b2fabf5a8a84c475b/paddlenlp/transformers/gpt/modeling.py#L251
https://github.com/PaddlePaddle/PaddleNLP/blob/7c76b2f61191b8706802430b2fabf5a8a84c475b/paddlenlp/transformers/gpt/modeling.py#L254
            self.out_proj = nn.Linear(
                embed_dim, embed_dim, weight_attr, bias_attr=bias_attr)

**Comment by FrostML** [comment]
理论上，out 的 shape 应该是 `[batch size, sequence length, num_head * size_per_head]`，然后这里的 `num_head * size_per_head == hidden_dim` 这里应该可以视作是 `embed_dim`。

**Comment by hl123-123** [comment]
self.head_dim = embed_dim // num_heads
i know .thank you very much
