### ISSUE TITLE
想问下这个dropout相加是什么思想，我们一般dropout不是用来增加神经网络各个部分能力的吗

### ISSUE THREAD

**Issue by hl123-123** [PaddlePaddle/PaddleNLP#717]
https://github.com/PaddlePaddle/PaddleNLP/blob/7c76b2f61191b8706802430b2fabf5a8a84c475b/paddlenlp/transformers/gpt/modeling.py#L426        
        residual = tgt

        if self.normalize_before:
            tgt = self.norm1(tgt)

        if use_cache is False:
            tgt = self.self_attn(tgt, tgt, tgt, tgt_mask, use_cache, cache)
        else:
            tgt, incremental_cache = self.self_attn(tgt, tgt, tgt, tgt_mask,
                                                    use_cache, cache)
        tgt = residual + self.dropout1(tgt)

**Comment by FrostML** [comment]
`self_attn` 计算完成之后，过一层 dropout，然后加上的是一个 residual 残差单元。

**Comment by hl123-123** [comment]
thank you
