### ISSUE TITLE
PaddleNLP/ examples / dialogue / unified_transformer / infer.py  在win10,py3.7，paddle相关包都是最新版本，运行报错，原始官方代码

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#719]
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/framework/tensor_impl.h:33)
  [operator < concat > error]

**Comment by LiuChiachi** [comment]
已在 #721 中解决，您可以拉取最新的代码再次尝试。十分感谢提出建议~

**Comment by smallv0221** [comment]
Sorry for the inconvenience. This bug is caused by `np.asarray()`. This func generates int32 by default in win32.
We fixed this in #721

**Comment by AI-Mart** [comment]
还是不行，最好验证下再发布哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月9日(星期五) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/ examples / dialogue / unified_transformer / infer.py  在win10,py3.7，paddle相关包都是最新版本，运行报错，原始官方代码 (#719)





 
Sorry for the inconvenience. This bug is caused by np.asarray(). This func generates int32 by default in win32.
 We fixed this in #721

**Comment by smallv0221** [comment]
I have tested this on a win32. Did you fetch the newest code in `example/`? And still the same exception?

**Comment by timohaha** [comment]
你好，我也在复现这个代码，遇到相同的问题，你的问题解决了么？

**Comment by AI-Mart** [comment]
还没有解决呢，我后面直接把代码放在linux上去运行了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/ examples / dialogue / unified_transformer / infer.py  在win10,py3.7，paddle相关包都是最新版本，运行报错，原始官方代码 (#719)





 
你好，我也在复现这个代码，遇到相同的问题，你的问题解决了么？
