### ISSUE TITLE
[Question]: GPT/llama模型初始化RowParallelLinear层scale

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleNLP#7190]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/dc32055c98a8f750906912a72416c6004f62c3a6/paddlenlp/transformers/llama/modeling.py#L1063

为什么llama和gpt需要对RowParallelLinear层的初始化参数进行scale操作？

**Comment by iosmers** [comment]
@ZHUI 帮忙看下

**Comment by ZHUI** [comment]
https://github.com/NVIDIA/Megatron-LM/blob/f7727433293427bef04858f67b2889fe9b177d88/megatron/core/utils.py#L176-L183 

应该是参考来自这里。

**Comment by BeingGod** [comment]
好的，谢谢~
