### ISSUE TITLE
[Bug]: 官方示例跑不通，是版本问题吗

### ISSUE THREAD

**Issue by Steven-Luo** [PaddlePaddle/PaddleNLP#7211]
### 软件环境

```Markdown
paddle-bfloat              0.1.7
paddle2onnx                1.0.6
paddlefsl                  1.1.0
paddlehub                  2.3.1
paddlenlp                  2.6.1
paddlepaddle               2.5.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用官方示例代码：

from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

输出结果空的：
[2023-10-12 19:31:14,405] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load '/home/aistudio/.paddlenlp/taskflow/information_extraction/uie-base'.
[{}]
```

### 稳定复现步骤 & 代码

from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

**Comment by Julyssn** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/46492039/37e5fb73-9e25-4653-b009-9a97b4a9b3cb)
俺也一样

**Comment by HysysRobert** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/133632562/a763b5fd-9c9b-447e-b645-75200010b67e)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/133632562/f7b1d339-0a1f-480a-8498-33a043b9797d)
运行环境：linux cpu
不知道哪里有问题我也跑不通

**Comment by YoannCheung** [comment]
不仅是跑出来的结果有问题，连续几次跑的结果还不一样，非常夸张。

**Comment by reslmd** [comment]
到底怎么回事啊，跑出来的结果很离谱

**Comment by zhangwanyu2020** [comment]
我也是这样，不报错，但结果是空的

**Comment by hotpeppeper** [comment]
这个问题时间挺长了，还没解决吗

**Comment by reslmd** [comment]
请问解决了吗

**Comment by hanfeng11** [comment]
cpu 实测paddlepaddle 2.5.0rc1 + paddlenlp 2.6.1可以正常输出。
