### ISSUE TITLE
【ernie-3.5-se】use_fused_ln的性能收益？

### ISSUE THREAD

**Issue by zhurou603** [PaddlePaddle/PaddleNLP#7216]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/32234672/6f2cea33-7c88-4a34-9106-e39c0b88d4b5)
在ernie-3.5-se 预训练模型中如果开启use_fused_ln后似乎性能无任何差异？请问理论上fused layernorm和nn.layernorm的提升在哪里，或者在A100上预期有什么收益？

**Comment by ZHUI** [comment]
paddle 的layernorm已经经过性能优化了，所以提升不大
