### ISSUE TITLE
[Question]: 报错ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by fxb392** [PaddlePaddle/PaddleNLP#7228]
### 请提出你的问题

from paddlenlp import Taskflow报错ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
WSL环境中openssl版本OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)

**Comment by wencan** [comment]
我系统fedora 38
通过安装openssl1.1解决了问题

**Comment by fxb392** [comment]
感谢帮助，我出现这个错感觉是因为paddle的这个paddlepaddle-gpu==2.5.1.post117版本和我的系统有冲突，换成paddlepaddle-gpu==2.5.1就没这个问题了，又遇到了其他问题，我用conda装好了，简单记录了一下：https://blog.csdn.net/qq_37356556/article/details/133850214
