### ISSUE TITLE
paddle对抗训练-FGM

### ISSUE THREAD

**Issue by ZeqiangWangAI** [PaddlePaddle/PaddleNLP#723]
版本
paddlehub              2.0.4          
paddlenlp              2.0.1          
paddlepaddle-gpu       2.1.0.post101  
FGM代码：
import paddle
class FGM():
    """针对embedding层梯度上升干扰的对抗训练方法,Fast Gradient Method（FGM）"""

    def __init__(self, model):
        self.model = model
        self.backup = {}

    def attack(self, epsilon=1., emb_name='emb'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:  # 检验参数是否可训练及范围
                self.backup[name] = param.numpy()  # 备份原有参数值
                grad_tensor = paddle.to_tensor(param.grad)  # param.grad是个numpy对象
                norm = paddle.norm(grad_tensor)  # norm化
                if norm != 0:
                    r_at = epsilon * grad_tensor / norm
                    param.add(r_at)  # 在原有embed值上添加向上梯度干扰

    def restore(self, emb_name='emb'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:
                assert name in self.backup
                param.set_value(self.backup[name])  # 将原有embed参数还原
        self.backup = {}
训练代码
    #pgd = PGD(model)
    fgm = FGM(model)
    #K = 3
    for epoch in range(args.num_train_epochs):
        step = 0
        for input_ids, token_type_ids, length, labels in train_data_loader:
            global_step += 1
            logits = model(input_ids, token_type_ids)
            loss = loss_fct(logits, labels)
            avg_loss = paddle.mean(loss)
            if global_step % args.logging_steps == 0:
                print(
                    "global step %d, epoch: %d, batch: %d, loss: %f, speed: %.2f step/s"
                    % (global_step, epoch, step, avg_loss,
                       args.logging_steps / (time.time() - tic_train)))
                tic_train = time.time()
            avg_loss.backward( retain_graph = True)
            fgm.attack()
            #loss_adv = model(batch_input, batch_label)
            #loss_adv.backward() # 反向传播，并在正常的grad基础上，累加对抗训练的梯度
            adv_logits = model(input_ids, token_type_ids)
            adv_loss = loss_fct(logits, labels)
            adv_avg_loss = paddle.mean(loss)
            adv_avg_loss.backward()
            fgm.restore() # 恢复embedding参数
            #pgd.backup_grad()

            # 对抗训练
            #for t in range(K):
            #    pgd.attack(is_first_attack=(t==0)) # 在embedding上添加对抗扰动, first attack时备份param.data
            #  if t != K-1:
            #        optimizer.clear_grad()
            #    else:
            #        pgd.restore_grad()
            #    loss_adv = loss_fct(logits, labels)
            #    loss_adv.backward() # 反向传播，并在正常的grad基础上，累加对抗训练的梯度
            #pgd.restore() # 恢复embedding参数
            optimizer.step()
            lr_scheduler.step()
            optimizer.clear_grad()
            step = step+1
训练命令
python -u ./train.py  --model_name_or_path bert-wwm-chinese --max_seq_length 128  --batch_size 32  --learning_rate 2e-5  --num_train_epochs 30 --logging_steps 1  --save_steps 500  --output_dir ./tmp/bert_ner/ --device gpu
报错信息
global step 1, epoch: 0, batch: 0, loss: 2.467751, speed: 3.54 step/s
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py:373: UserWarning: 
Warning:
tensor.grad will return the tensor value of the gradient. 
  warnings.warn(warning_msg)
global step 2, epoch: 0, batch: 1, loss: 1.908787, speed: 1.00 step/s
Traceback (most recent call last):
  File "./train.py", line 248, in <module>
    do_train(args)
  File "./train.py", line 208, in do_train
    avg_loss.backward( retain_graph = True)
  File "<decorator-gen-123>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 236, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) No grad node corresponding to grad Tensor (dygraph_tmp_1691@GRAD) was found.
  [Hint: Expected find_grad_node_of_var == true, but received find_grad_node_of_var:0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:229)

**Comment by wawltor** [comment]
您好，请问一下上述的代码是否是完整的代码，如果是完整的代码，麻烦也提供一下相应的数据给我们，我们来复现一下问题

**Comment by libertatis** [comment]
我参考了你的部分代码和知乎上这篇文章[【炼丹技巧】功守道：NLP中的对抗训练 + PyTorch实现](https://zhuanlan.zhihu.com/p/91269728)的 `PyTorch` 实现，我在抽取式机器阅读理解数据集 `DuReader-robust` 的 `baseline` 上实现了 `PaddlePaddle` 的 `PGD`。中间我也出现了你的这种情况。经过一番 `bug` 排查后，我发现，是因为预训练模型中有两个参数的梯度为 `None` 造成的。这个可以在备份参数的梯度时，打印参数名和参数的梯度类型查看：
```
    print('in backup_grad: ', name, type(param.grad))
```
我做的是抽取式机器阅读理解任务，使用的是 `ErnieGramForQuestionAnswering` 这个模型，它里面有个属性 `ernie_gram`, 是 `ErnieGramModel` 的一个实例，它有两个输出，分别是 `sequence_output` 和 `pooled_output`。而对于抽取式阅读理解任务， `ErnieGramForQuestionAnswering` 模型只用了 `sequence_output` 这一个输出，而没有用到 `pooled_output` 这个输出，这个输出是由 `[CLS]` 的表征经过一层线性变换，即一个 `dense layer` 得到的，它有两个参数，即 `ernie_gram.pooler.dense.weight` 和 `ernie_gram.pooler.dense.bias`。由于模型的输出没有用到 `pooled_output`，也就是说我们计算 `loss` 时，没有经过它这个结点，即和它没有关系（不在图中），所以 `loss.backward()` 计算梯度时，就不会计算 `ernie_gram.pooler.dense.weight` 和 `ernie_gram.pooler.dense.bias` 这两个参数的梯度，于是它们的梯度就为 `None` 了。从而导致了你的那个 `bug`。解决的办法是很简单，只需要在梯度备份和恢复的时候，将这两个参数剔除掉，即判断一下参数的梯度是否为空即可:
```
    def backup_grad(self):
        for name, param in self.model.named_parameters():
            # 不需要备份梯度为 None 的参数
            # param.grad is not None 或者 ‘pooler’ not in name
            if not param.stop_gradient and param.grad is not None:
                # print('in backup_grad: ', name, type(param.grad))
                self.grad_backup[name] = param.grad

    def restore_grad(self):
        for name, param in self.model.named_parameters():
            # 不需要备份梯度为 None 的参数
            # param.grad is not None 或者 ‘pooler’ not in name
            if not param.stop_gradient and param.grad is not None:
                param.grad.set_value(self.grad_backup[name])
```

修改后完整的 `PGD` 实现如下：
```
class PGD:
    def __init__(self, model):
        self.model = model
        self.emb_backup = {}
        self.grad_backup = {} 

    def attack(self, epsilon=1., alpha=0.3, emb_name='word_embeddings', is_first_attack=False):
        # emb_name 这个参数要换成你模型中 embedding 的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:
                if is_first_attack:
                    self.emb_backup[name] = param
                param_grad = param.grad
                norm = paddle.norm(param_grad)
                if norm != 0 and not paddle.isnan(norm):
                    r_at = alpha * param_grad / norm
                    param.add(r_at)
                    param = self.project(name, param, epsilon)

    def restore(self, emb_name='word_embeddings'):
        # emb_name 这个参数要换成你模型中 embedding 的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:
                assert name in self.emb_backup
                param.set_value(self.emb_backup[name])
        self.emb_backup = {}

    def project(self, param_name, param, epsilon):
        r = param - self.emb_backup[param_name]
        if paddle.norm(r) > epsilon:
            r = epsilon * r / paddle.norm(r)
        return self.emb_backup[param_name] + r

    def backup_grad(self):
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and param.grad is not None:
                # print('in backup_grad: ', name, type(param.grad))
                self.grad_backup[name] = param.grad

    def restore_grad(self):
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and param.grad is not None:
                param.grad.set_value(self.grad_backup[name])
```
以上是我的情况，我想你的也差不多是这个情况吧。最后希望能够帮到你~

**Comment by libertatis** [comment]
我在你的模型训练命令里看到了你似乎做的是 `NER` 任务，如果是 `NER` 的话，它是一个 `token` 级的分类任务，用的模型应该是 `XXXForTokenClassification` ，它和抽取式机器阅读理解模型 `XXXForQuestionAnswering` 一样，只用到了 `sequence_output`, 没有用到 `pooled_output`~

**Comment by libertatis** [comment]
哎呀！我才反应过来，你是 `FGM` 出现的问题，不是 `PGD`！刚才的 `PGD` 还没跑完(跑得贼慢)，跑完我再试一下 `FGM`~

**Comment by ZeqiangWangAI** [comment]
> 哎呀！我才反应过来，你是 `FGM` 出现的问题，不是 `PGD`！刚才的 `PGD` 还没跑完(跑得贼慢)，跑完我再试一下 `FGM`~

感谢您的帮助，我昨天晚上后面又弄好了，和您的想法类似。FGM和PGD都有尝试，不过性能提升没有想象中显著：）

**Comment by ZeqiangWangAI** [comment]
> 您好，请问一下上述的代码是否是完整的代码，如果是完整的代码，麻烦也提供一下相应的数据给我们，我们来复现一下问题

更多是我的代码问题，我这边已经弄好了，谢谢您

**Comment by Lanme** [comment]
你好，方便提供下FGM修改后的代码么

**Comment by shishijier** [comment]
> 

class FGM():
    def __init__(self, model):
        self.model = model
        self.backup = {}

    def attack(self, epsilon=1., emb_name='word_embeddings'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:
                self.backup[name] = param
                norm = paddle.norm(param.grad)
                if norm != 0 and not paddle.isnan(norm):
                    r_at = epsilon * param.grad / norm
                    param.add(r_at)

    def restore(self, emb_name='word_embeddings'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name: 
                assert name in self.backup
                param.set_value(self.backup[name])
        self.backup = {}

FGM修改后可以用，希望能帮助到你

**Comment by shishijier** [comment]
> 你好，方便提供下FGM修改后的代码么

class FGM():
    def __init__(self, model):
        self.model = model
        self.backup = {}

    def attack(self, epsilon=1., emb_name='word_embeddings'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name:
                self.backup[name] = param
                norm = paddle.norm(param.grad)
                if norm != 0 and not paddle.isnan(norm):
                    r_at = epsilon * param.grad / norm
                    param.add(r_at)

    def restore(self, emb_name='word_embeddings'):
        # emb_name这个参数要换成你模型中embedding的参数名
        for name, param in self.model.named_parameters():
            if not param.stop_gradient and emb_name in name: 
                assert name in self.backup
                param.set_value(self.backup[name])
        self.backup = {}

FGM的，可以使用
