### ISSUE TITLE
develop分支报错ModuleNotFoundError: No module named 'paddlenlp.taskflow.model'

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/PaddleNLP#725]
需要用到最新的datasets， 但是无论是setup还是直接用，都会报这个错ModuleNotFoundError: No module named 'paddlenlp.taskflow.model'

**Comment by wawltor** [comment]
> 需要用到最新的datasets， 但是无论是setup还是直接用，都会报这个错ModuleNotFoundError: No module named 'paddlenlp.taskflow.model'

紧急修复了一个版本 https://github.com/PaddlePaddle/PaddleNLP/pull/727

**Comment by thunder95** [comment]
嗯 注释掉taskflow也解决了
