### ISSUE TITLE
ERNIE模型能否返回中间层的输出？

### ISSUE THREAD

**Issue by KinvenW** [PaddlePaddle/PaddleNLP#728]
ERNIE模型只返回最后一层的输出，那要获取中间层的输出呢？

**Comment by libertatis** [comment]
`PaddleNLP` 的 `API` 似乎没有提供这样的接口。有一种办法是直接修改 `ERNIE` 的源码，想返回啥，自己看着返回就行了。不过我一直没试过~
[https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/modeling_ernie.py](https://github.com/PaddlePaddle/ERNIE/blob/develop/ernie/modeling_ernie.py)

**Comment by yingyibiao** [comment]
对的，我们目前的API设计是不保留中间层输出的。
除了修改源码外，我们也可以通过加一个register_forward_post_hook来进行中间层的输出；
参考（https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#register_forward_post_hook ） 在hook里把每一层encoder layer的输入存到一个全局的list里。
