### ISSUE TITLE
运行Research/NLP/Text2SQL-BASELINE/ 报错，/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL可以

### ISSUE THREAD

**Issue by liu100286** [PaddlePaddle/PaddleNLP#729]
我在aistudio 上运行了这个项目，报错了。
https://github.com/PaddlePaddle/Research/tree/master/NLP/Text2SQL-BASELINE

在执行 bash data/download_trained_model.sh  这个脚本时，提示 

aistudio@jupyter-282755-2175973:~/Text2SQL-BASELINE$ bash data/download_trained_model.sh
--2021-07-11 23:05:11--  https://dataset-bj.cdn.bcebos.com/text2sql/text2sql_trained_model_v1.0.0.tar.gz
Resolving dataset-bj.cdn.bcebos.com (dataset-bj.cdn.bcebos.com)... 182.61.128.166
Connecting to dataset-bj.cdn.bcebos.com (dataset-bj.cdn.bcebos.com)|182.61.128.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-07-11 23:05:11 ERROR 404: Not Found.

tar (child): text2sql_trained_model_v1.0.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

![}BN{4WV5JDX{Q$GO3@QXKYK](https://user-images.githubusercontent.com/39895015/125199936-141a2c80-e29b-11eb-8e45-3ccce8a93e88.png)

![V{FYX% }IUMP)66$YO3K227](https://user-images.githubusercontent.com/39895015/125199911-fd73d580-e29a-11eb-827e-d1d1440b4320.png)

**Comment by ZeyuChen** [comment]
@liu100286 Please try this one https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_sql/RAT-SQL

**Comment by liu100286** [comment]
感谢，可以了
