### ISSUE TITLE
LAC模型识别实体能支撑的量级？

### ISSUE THREAD

**Issue by tom-tangqs** [PaddlePaddle/PaddleNLP#731]
官方的LAC模型做实体预测，除了一些词性以外，实体有人名，地名，组织机构名，时间这四种，想问一下模型能够识别大约多少种实体，几十种，上百种能行吗？

**Comment by joey12300** [comment]
实体类别数取决于训练时提供的label列表的大小。label列表越大，实体类别数越多，就能识别更多的实体。

可参考[词法分析](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis)示例。示例中提供的[数据集](https://paddlenlp.bj.bcebos.com/datasets/lexical_analysis_dataset_tiny.tar.gz)中的`tag.dic`描述了该数据集的实体类别。

**Comment by tom-tangqs** [comment]
嗯嗯，这个tag.dic文件列出了所有的label，那这个label的数量有上限要求吗，或者label超过一定的数量，会存在模型识别准确率下降的情况吗？

**Comment by joey12300** [comment]
@tom-tangqs 理论上对label是没有上限要求的。但是label数越多，为了维持准确率，就需要更大量的样本进行训练。并且label数增多也会加大模型占用的显存，对训练的机器资源有更高的要求。

**Comment by tom-tangqs** [comment]
好的，了解了，感谢
