### ISSUE TITLE
[Question]: PaddleNLP Text_to_sql RAT-SQL 在训练完成时，进行推理测试，出现错误got an unexpected keyword argument 'attention_probs_dropout_prob'

### ISSUE THREAD

**Issue by baiclamp** [PaddlePaddle/PaddleNLP#7310]
### 请提出你的问题

如标题所示：
bash ./run.sh ./script/text2sql_main.py --mode infer \
>          --config conf/text2sql_dusql.jsonnet \
>          --data-root data/DuSQL/preproc \
>          --test-set data/DuSQL/preproc/dev.pkl \
>          --init-model-param output/dusql_baseline/epoch030_acc30.0000/model.pdparams \
>          --output output/dusql_dev_infer_result.sql
------------------------------------------------------------
CUDA_VISIBLE_DEVICES=0
running command: (/usr/local/bin/python3 ./script/text2sql_main.py --mode infer --config conf/text2sql_dusql.jsonnet --data-root data/DuSQL/preproc --test-set data/DuSQL/preproc/dev.pkl --init-model-param output/dusql_baseline/epoch030_acc30.0000/model.pdparams --output output/dusql_dev_infer_result.sql)
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W1025 08:28:25.489967  4761 analysis_predictor.cc:1736] Deprecated. Please use CreatePredictor instead.
/usr/local/python3.7.0/lib/python3.7/site-packages/pandas/util/testing.py:27: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import pandas._libs.testing as _testing
[2023-10-25 08:28:28,818] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0/vocab.txt
[2023-10-25 08:28:28,832] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/ernie-1.0/tokenizer_config.json
[2023-10-25 08:28:28,833] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/ernie-1.0/special_tokens_map.json
Traceback (most recent call last):
  File "./script/text2sql_main.py", line 213, in <module>
    inference(config)
  File "./script/text2sql_main.py", line 113, in inference
    model = ModelClass(config.model, g_label_encoder)
  File "./script/text2sql_main.py", line 182, in <lambda>
    ModelClass = lambda x1, x2: text2sql.models.EncDecModel(x1, x2, "v2")
  File "/paddle/resource/git/PaddleNLP/examples/text_to_sql/RAT-SQL/text2sql/models/enc_dec.py", line 31, in __init__
    self.encoder = encoder_v2.Text2SQLEncoderV2(config)
  File "/paddle/resource/git/PaddleNLP/examples/text_to_sql/RAT-SQL/text2sql/models/encoder_v2.py", line 83, in __init__
    self.base_encoder = PretrainModel(**args["cfg"])
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddlenlp/transformers/utils.py", line 170, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'attention_probs_dropout_prob'

-------------------------------
λ gputnode1 /paddle/resource/git/PaddleNLP/examples/text_to_sql/RAT-SQL pip list | grep paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
paddle-bfloat                  0.1.7
paddle-serving-app             0.7.0
paddle-serving-client          0.7.0
paddle-serving-server-gpu      0.7.0.post102
paddle2onnx                    0.9.8
paddlefsl                      1.1.0
paddlehub                      2.1.0
paddlenlp                      2.5.2
paddleocr                      2.5.0.3
paddlepaddle-gpu               2.3.1

**Comment by ByeByeChen** [comment]
请问你这个问题解决了吗？我今天也遇到这个情况了

**Comment by baiclamp** [comment]
你好，这边应该是代码过旧的问题。这边我同事改了代码过去了。但是我并不知道修改了什么内容。发自我的 iPhone在 2023年11月13日，10:16，Chen Yuming ***@***.***> 写道：﻿
请问你这个问题解决了吗？我今天也遇到这个情况了

**Comment by ByeByeChen** [comment]
是库的版本问题吗

**Comment by baiclamp** [comment]
你可以比对一下。发自我的 iPhone在 2023年11月13日，10:30，Chen Yuming ***@***.***> 写道：﻿
是库的版本问题吗
