### ISSUE TITLE
[Question]: 内存报错信息是否正确？

### ISSUE THREAD

**Issue by LuYuPromax** [PaddlePaddle/PaddleNLP#7312]
### 请提出你的问题

想要使用4090训练llama，但是出现了如下的错误信息，想要问下为什么报错信息是需要172M显存？这里可以看到显卡内存并没有使用，报错显示23.48G，但只有167.06G能用
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 172.000000MB memory on GPU 0, 23.486572GB memory has been allocated and available memory is only 167.062500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
 (at ../paddle/fluid/memory/allocation/cuda_allocator.cc:86)

I1026 09:51:11.657310 597454 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-10-26 09:51:12,809 Exit code 1
[2023-10-26 09:51:12,809] [    INFO] controller.py:149 - Exit code 1

显卡信息：
(paddleenv) ubuntu@ubuntu-7003-r8424-g12:~/smyin/llama$ nvidia-smi
Thu Oct 26 09:52:27 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:4B:00.0 Off |                  Off |
| 33%   31C    P8              19W / 450W |     13MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off | 00000000:CA:00.0 Off |                  Off |
| 33%   32C    P8              19W / 450W |     13MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1859      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      1859      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

**Comment by luo-geng** [comment]
我也是，debian12

**Comment by LuYuPromax** [comment]
> 我也是，debian12
想问一下你解决了没有？我现在还是没有解决这个问题，按道理说双卡4090应该是可以跑通的才对

**Comment by luo-geng** [comment]
> 道理说双卡4090应该是可以跑通的

没有，等官方更新下个版本看，测试nlp要求的2.5.1以上版本，一样无结果

**Comment by LuYuPromax** [comment]
> 没有，等官方更新下个版本看，测试nlp要求的2.5.1以上版本，一样无结果

好的好的，我打算一会试一下四卡能不能行
