### ISSUE TITLE
[Bug]: 使用uie预测时不出结果

### ISSUE THREAD

**Issue by yicentian02** [PaddlePaddle/PaddleNLP#7318]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5.1
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
运行示例代码
from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema)
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
出现错误：
```

### 稳定复现步骤 & 代码

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/109857514/85620fee-f33e-4a7a-9b7f-006838f65988)

**Comment by BigTailMonkey** [comment]
我也出现了这种问题。我用的是cpu版本，系统是ubuntu 22.04.6版本。

paddlepaddle 2.5.1
paddlenlp 2.6.1

**Comment by BigTailMonkey** [comment]
paddlepaddle 降级到2.5.0rc1试试。我的问题解决了。

**Comment by bobo-168** [comment]
解决了。
建议按以下步骤进行安装：
1.conda install paddlepaddle==2.5.0rc1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
2.pip install paddlenlp -i https://pypi.tuna.tsinghua.edu.cn/simple

安装后的PADDLE相关的版本号：
(my_paddlenlp_test) [root@OracleLinux data]# conda list | grep paddle
# packages in environment at /data/miniconda3/envs/my_paddlenlp_test:
paddle2onnx               1.1.0                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.6.1                    pypi_0    pypi
paddlepaddle              2.5.0rc1                 pypi_0    pypi

**Comment by bobo-168** [comment]
解决了。
建议按以下步骤进行安装：
1.conda install paddlepaddle==2.5.0rc1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
2.pip install paddlenlp -i https://pypi.tuna.tsinghua.edu.cn/simple

安装后的PADDLE相关的版本号：
(my_paddlenlp_test) [root@OracleLinux data]# conda list | grep paddle
# packages in environment at /data/miniconda3/envs/my_paddlenlp_test:
paddle2onnx               1.1.0                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.6.1                    pypi_0    pypi
paddlepaddle              2.5.0rc1                 pypi_0    pypi

**Comment by bobo-168** [comment]
> 我也出现了这种问题。我用的是cpu版本，系统是ubuntu 22.04.6版本。
> 
> paddlepaddle 2.5.1 paddlenlp 2.6.1

这两个版本组合有问题。PADDLE2.5.2也存在类似问题。
