### ISSUE TITLE
[Question]: batch_size等于1，内存报错

### ISSUE THREAD

**Issue by LuYuPromax** [PaddlePaddle/PaddleNLP#7321]
### 请提出你的问题

报错信息：
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 32.000000MB memory on GPU 0, 23.623291GB memory has been allocated and available memory is only 27.062500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
 (at ../paddle/fluid/memory/allocation/cuda_allocator.cc:86)
. (at ../paddle/fluid/imperative/tracer.cc:322)

LAUNCH INFO 2023-10-27 08:22:04,158 Exit code 1
[2023-10-27 08:22:04,158] [    INFO] controller.py:149 - Exit code 1

显卡信息：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/115551266/f867ce09-15a5-4e6f-959d-ddd3da0af4ea)

运行信息：
{
    "model_name_or_path": "facebook/llama-7b",
    "dataset_name_or_path": "./data",
    "output_dir": "./checkpoints/llama_sft_ckpts",
    "per_device_train_batch_size": 1,
    "gradient_accumulation_steps": 4,
    "per_device_eval_batch_size": 8,
    "eval_accumulation_steps":16,
    "num_train_epochs": 3,
    "learning_rate": 3e-05,
    "warmup_steps": 30,
    "logging_steps": 1,
    "evaluation_strategy": "epoch",
    "save_strategy": "epoch",
    "src_length": 1024,
    "max_length": 2048,
    "fp16": true,
    "fp16_opt_level": "O2",
    "do_train": true,
    "do_eval": true,
    "disable_tqdm": true,
    "load_best_model_at_end": true,
    "eval_with_do_generation": false,
    "metric_for_best_model": "accuracy",
    "recompute": true,
    "save_total_limit": 1,
    "tensor_parallel_degree": 2,
    "pipeline_parallel_degree": 1
  }

**Comment by DrownFish19** [comment]
你设置的per_device_eval_batch_size太大了，先尝试设置为1

**Comment by LuYuPromax** [comment]
已经是1了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月01日 12:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleNLP] [Question]: batch_size等于1，内存报错 (Issue #7321) |

你设置的per_device_eval_batch_size太大了，先尝试设置为1

**Comment by DrownFish19** [comment]
我看你脚本里的`"per_device_eval_batch_size": 8`,你把这个参数也设置成1试试，7b的模型是能在v100 32G运行的，应该通过tp之后也能在4090*2运行
