### ISSUE TITLE
[Question]: 发现将windows训练效果良好的uie模型移植到linux系统后，似乎模型失效了

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#7328]
### 请提出你的问题

如题，将Windows系统下训练好的模型移植到了centos7和ubuntu18后，均发现执行
` my_ie = Taskflow("information_extraction", schema=schema, task_path='./checkpoint/model_best')`
`result =my_ie(input_str)`
得到的result内容为空，使用paddlepaddle              2.5.1           py39_cpu_many_linux。
但是之前在windows使用使用训练好的模型（'./checkpoint/model_best'）能得到良好的抽取效果，例如`input_str=一架侦察机从冲绳出发前往南海。`，能够抽取到“侦察机”、“冲绳”、“南海”，使用paddlepaddle-gpu   .4.2.post117。
请问导致这种结果的原因有些？
ps1：不同操作系统下训练的模型应该是跨平台的吧，仅仅python项目的依赖包环境需要进行相应的替换吧？
ps2：应该能够使用paddle_linux_cpu版本来运行在windows下使用paddle_gpu训练的模型？

**Comment by BigTailMonkey** [comment]
paddlepaddle 降级到2.5.0rc1试试。我的问题解决了。
