### ISSUE TITLE
[Question]:PaddleNLP-2.6.1\examples\text_classification中的ERNIE-DOC在执行train.py的时候提示“'NoneType' object has no attribute 'from_pretrained'”

### ISSUE THREAD

**Issue by AaronSunXuBao** [PaddlePaddle/PaddleNLP#7334]
### 请提出你的问题

如下图所示，使用RNIE-DOC在执行train.py的时候提示“'NoneType' object has no attribute 'from_pretrained'”，请大神帮看看问题，非常感谢！
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/6190723/d38ae67e-c56a-4b94-8231-575526fd2c50)

**Comment by cuisws** [comment]
我也是paddlenlp-2.6.1，同样的错误

**Comment by cuisws** [comment]
> ### 请提出你的问题
> 如下图所示，使用RNIE-DOC在执行train.py的时候提示“'NoneType' object has no attribute 'from_pretrained'”，请大神帮看看问题，非常感谢！ ![image](https://user-images.githubusercontent.com/6190723/278987866-d38ae67e-c56a-4b94-8231-575526fd2c50.png)

我也是同样的问题，降一下版本就可以了
