### ISSUE TITLE
[Question]: ernie-doc预测结果每次都不相同，完全不一样

### ISSUE THREAD

**Issue by cuisws** [PaddlePaddle/PaddleNLP#7335]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/ernie_doc
我按着这个例子训练后，进行预测，每次结果都完全不一样。
用例子的官方数据预测，也是同样的结果，不知道问题在哪里。

**Comment by gggdroa** [comment]
甚至跑起来有问题，你那边的指标没出问题吗  我的直接出现了无限大···官方人员也无人回复 感觉不太能用啊

**Comment by cuisws** [comment]
> 甚至跑起来有问题，你那边的指标没出问题吗 我的直接出现了无限大···官方人员也无人回复 感觉不太能用啊

论文最后有不同数据集应该用的超参数，你可以对应试一下
