### ISSUE TITLE
[Question]: libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by chestnut111** [PaddlePaddle/PaddleNLP#7336]
### 请提出你的问题

安装paddlenlp之后，运行；
`from paddlenlp import Taskflow`
报错；
`/mnt/wanglixin/anaconda3/envs/nlpx/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: User
。。。
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /mnt/wanglixin/anaconda3/envs/nlpx/lib/python3.11/site-packages/scipy/spatial/_ckdtree.cpython-31-x86_64-linux-gnu.so)`

**Comment by chestnut111** [comment]
fix

**Comment by natureLanguageQing** [comment]
有两种可能一种是codna 安装 我在 ubuntu系统 nvidia-smi NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2 使用conda安装 conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=12.3 -c paddle -c nvidia的时候遇到了你说的这个问题 在完全卸载paddlepaddle后使用conda安装conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=11.8 -c paddle -c nvidia解决掉了这个问题
