### ISSUE TITLE
不理解fetch的含义

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#734]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_classification/pretrained_models/deploy/serving/client.py中有如下关于fetch的执行语句，
...
fetch_map = client.predict(
            feed={"input_ids": input_ids,
                  "token_type_ids": token_type_ids},
            fetch=["save_infer_model/scale_0.tmp_1"],
            batch=True)
        output_data = np.array(fetch_map["save_infer_model/scale_0.tmp_1"])
...

相比之下，https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/fit_a_line/test_client.py中predict函数中的fetch如下：
...
 fetch_map = client.predict(
        feed={"x": new_data}, fetch=["price"], batch=True)
...

不理解其含义，希望能够给与解释，谢谢！

**Comment by ZHUI** [comment]
这个应该都是 tensor 的name。fetch 的对象是tensor，这个是  tensor 的name。

**Comment by LangDaoAI** [comment]
> 这个应该都是 tensor 的name。fetch 的对象是tensor，这个是 tensor 的name。

price怎么会是tensor的name呢，而且fit_a_line代码也没有看到定义tensor的name为price

**Comment by ZHUI** [comment]
> > 这个应该都是 tensor 的name。fetch 的对象是tensor，这个是 tensor 的name。
> 
> price怎么会是tensor的name呢，而且fit_a_line代码也没有看到定义tensor的name为price

看起来，这里save的时候做了映射
https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/fit_a_line/local_train.py#L52

**Comment by LangDaoAI** [comment]
> > > 这个应该都是 tensor 的name。fetch 的对象是tensor，这个是 tensor 的name。
> > 
> > 
> > price怎么会是tensor的name呢，而且fit_a_line代码也没有看到定义tensor的name为price
> 
> 看起来，这里save的时候做了映射
> https://github.com/PaddlePaddle/Serving/blob/v0.6.0/python/examples/fit_a_line/local_train.py#L52

好像是的

**Comment by LangDaoAI** [comment]
调查了一下， 当做Serving的模型和配置导出，也就是python -u deploy/serving/export_servable_model.py \
    --inference_model_dir ./ \
    --model_file static_graph_params.pdmodel \
    --params_file static_graph_params.pdiparams

后，serving_client_conf.prototxt中的配置发现了这些name， 当然，price在save的时候做了映射后可能name做了改变（有时间我会做一下进一步确认的）

feed_var {
  name: "input_ids"
  alias_name: "input_ids"
  is_lod_tensor: false
  feed_type: 0
}
feed_var {
  name: "token_type_ids"
  alias_name: "token_type_ids"
  is_lod_tensor: false
  feed_type: 0
}
fetch_var {
  name: "save_infer_model/scale_0.tmp_1"
  alias_name: "save_infer_model/scale_0.tmp_1"
  is_lod_tensor: true
  fetch_type: 1
  shape: -1
}

**Comment by LangDaoAI** [comment]
先关闭这个问题
