### ISSUE TITLE
关于paddle-serving-app

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#735]
想确认一下部署的时候paddle-serving-app需不需要安装， 我安装paddle-serving-client就应该可以了吧， 没有看到paddle-serving-app使用的地方， 所以想请Team确认一下认识是否正确，谢谢！

**Comment by Steffy-zxf** [comment]
你好！需要安装paddle-serving-app。

**Comment by LangDaoAI** [comment]
OK
