### ISSUE TITLE
[Question]: llama中如果开启pipelineparallel后，想要配合sharding的tensor fusion使用该如何配置

### ISSUE THREAD

**Issue by zhurou603** [PaddlePaddle/PaddleNLP#7356]
### 请提出你的问题

使用现状：
pipeline degree = 4
sharding degree = 2
看到目前套件中支持的sharding stage1的优化器是
distributed/fleet/meta_optimizers/dygraph_optimizer/dygraph_sharding_optimizer.py
中的DygraphShardingOptimizer，其中有一个参数是通过sharding_config配置tensor_fusion
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/32234672/a5f49e07-05fd-4068-8009-456d249af26b)

困惑点1:
PaddleNLP套件中没有显式地提供用户配置tensor_fusion的位置

困惑点2:
似乎如果想要自己添加配置，pipeline config似乎做了一个拦截
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/32234672/bc6afc4e-d6c7-491d-8335-92ccd2ec7906)

希望回答的问题：
如何在用户侧快速地在配置pipeline + sharding的情况下开启sharding的tensor fusion

**Comment by zhurou603** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/32234672/4daab318-257d-4530-ab9f-5effef32d79b)
并且在pipeline_parallel_config中也没有fusion相关的配置，只有overlap的相关配置

**Comment by zhurou603** [comment]
<img width="723" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/32234672/ae089e85-faac-4a57-98aa-a36cde84a648">
develop最新代码也没有说明tensor fusion如何在pipeline_parallel_config中配置，并且DygraphShardingOptimizer中只会确认sharding_configs是否配置了tensor_fusion，那为啥要在pipeline_parallel_config配置？

**Comment by ZHUI** [comment]
@FeixLiu

**Comment by FeixLiu** [comment]
pipeline的tensor fusion需要结合调度进行。所以需要再pipeline中配置。
`--pipeline_parallel_config "enable_sharding_comm_overlap"` 即可。pp没有单独的tensor fusion开关，只在通讯overlap时候进行tensor fusion。
