### ISSUE TITLE
【问题】http接口访问服务端模型失败

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#736]
当我部署完模型后，启动客户端程序（flask)，然后用curl访问客户端，出现以下错误：

paddle-jupyter-677f4cfd57-j6zr7 /home/data/pvoc python sentiment_client.py 
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
 * Serving Flask app 'sentiment_client' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.16.0.236:8018/ (Press CTRL+C to quit)
handle_request_failed   Traceback (most recent call last):
  File "sentiment_client.py", line 31, in SensitiveWordsServer
    text = args['text']
TypeError: 'NoneType' object is not subscriptable
        'NoneType' object is not subscriptable
127.0.0.1 - - [12/Jul/2021 12:36:58] "POST /cn/sentiment HTTP/1.1" 200 -
handle_request_failed   Traceback (most recent call last):
  File "sentiment_client.py", line 34, in SensitiveWordsServer
    predictor = Predictor(128,client_config_file='./serving_client/serving_client_conf.prototxt')
  File "sentiment_client.py", line 110, in __init__
    self.client = Client()
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_client/client.py", line 146, in __init__
    from .serving_client import PredictorRes
ImportError: libcrypto.so.10: cannot open shared object file: No such file or directory
        libcrypto.so.10: cannot open shared object file: No such file or directory
127.0.0.1 - - [12/Jul/2021 12:38:41] "GET /cn/sentiment?text=è¿ä¸ªå®¾é¦æ¯è¾éæ§äºï¼ç¹ä»·ç
                                                                                        æ¿é´ä¹¾ä¸è¬ãæ»ä½æè¬ HTTP/1.1" 200 -

**Comment by LangDaoAI** [comment]
这个现在阻塞了客户端正常工作，还请帮忙看一下，谢谢！

**Comment by LangDaoAI** [comment]
paddle-serving-app 我先装一下看看

**Comment by Steffy-zxf** [comment]
建议使用docker进行安装部署，详细参考文档
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85

**Comment by LangDaoAI** [comment]
> 建议使用docker进行安装部署，详细参考文档
> https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/pretrained_models#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85

好的，暂时不关闭，明天上午确认后没有问题我就关闭这个issue

**Comment by LangDaoAI** [comment]
已经确定没有问题了
