### ISSUE TITLE
[Question]: ERNIE-layout的微调数据集FUNSD格式处理脚本有吗，或者有处理好的链接？

### ISSUE THREAD

**Issue by zhangquanwei962** [PaddlePaddle/PaddleNLP#7362]
### 请提出你的问题

如题，发现直接使用https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/README_ch.md#41-%E6%96%87%E6%A1%A3%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96%E4%BB%BB%E5%8A%A1 链接里面的脚本，通过直接下载原始的FUNSD并无法使用，不知道数据集预处理的步骤。

**Comment by PancakeAwesome** [comment]
请问你找到解决方法了么
