### ISSUE TITLE
[Question]: 运行uie示例时程序突然中断

### ISSUE THREAD

**Issue by A-man-and-a-girl** [PaddlePaddle/PaddleNLP#7372]
### 请提出你的问题

使用cpu运行uie
中断前的日志如下：
 pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))
E:\ruanjian\python\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py:2478: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
  warnings.warn(
E:\ruanjian\python\lib\site-packages\paddlenlp\transformers\tokenizer_utils_base.py:1878: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(

**Comment by DigYang** [comment]
遇到同样的问题

**Comment by A-man-and-a-girl** [comment]
> 遇到同样的问题

有GPU的话还是用GPU运行，感觉CPU运行模型会出一些奇怪的bug。安装好cuda和cudnn，还有对应版本的paddle，我这边跑起来没有其他的问题了

**Comment by sisrfeng** [comment]
> > 遇到同样的问题
> 
> 有GPU的话还是用GPU运行，感觉CPU运行模型会出一些奇怪的bug。安装好cuda和cudnn，还有对应版本的paddle，我这边跑起来没有其他的问题了

@A-man-and-a-girl  请问可以贴出你的安装命令吗? 想看下具体版本. (Paddle安装相关的issue太多了, 感觉有点坑)
我想跑的是:
```python
import paddle
# paddle.set_device("cpu")
from pprint import pprint
from paddlenlp import Taskflow
schema = ["收发货人", "进口口岸", "进口日期", "运输方式", "征免性质", "境内目的地", "运输工具名称", "包装种类", "件数", "合同协议号"]
ie = Taskflow("information_extraction", schema=schema, model="uie-x-base")
print(ie({"doc": "/home/wf/d/coolS/PaddleNLP/applications/information_extraction/document/data/images/b1.jpg"}))

```
在python3.10 cuda11.7 cudnn8.5上, `ie =Taskflow`那行报错 `segment fault`

**Comment by A-man-and-a-girl** [comment]
@sisrfeng 我在我的机子上跑你的代码没在Taskflow那行报错，但我是windows环境。
我是在python3.9， cuda11.2 cudnn 8.9，paddle安装的话即使按照官网的pip命令
python -m pip install paddlepaddle-gpu==2.5.2.post120 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
我建议你再检查一下cuda，cudnn还有paddle是否安装正确，paddle是否正确使用了gpu

**Comment by hjing100** [comment]
Windows+paddlepaddle==2.5.1 （CPU）
遇到同样的问题，电脑没有GPU...

**Comment by hjing100** [comment]
paddlepadle2.4.1 ，paddlenlp 2.4.0 window10+CPU版的paddlepaddle可以

**Comment by A-man-and-a-girl** [comment]
> paddlepadle2.4.1 ，paddlenlp 2.4.0 window10+CPU版的paddlepaddle可以

那可以的，感觉部分比较大的uie在cpu上跑的效果也不好，我之前测试只是nano效果还可以。
最开始的程序中断可能是环境的问题，我用anaconda创建可一个新的环境后也没有出现中断的问题。

**Comment by sisrfeng** [comment]
> 报错 segment fault
我应该是k8s集群里的docker容器里跑的. 申请了一张整卡就没这个问题了. 其他人也有类似情况
