### ISSUE TITLE
[Bug]: [NVIDIA] Sharding parallel stage2 overlap + async allreduce has convergence issue

### ISSUE THREAD

**Issue by Tom-Zheng** [PaddlePaddle/PaddleNLP#7375]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.5.2
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
We found that use of asynchronous allreduce with sharding parallel stage2 overlap may cause convergence issue -- loss became NaN randomly. 

In https://github.com/PaddlePaddle/PaddleNLP/pull/7092 , it is mentioned that "no other sync could be called during the training for broadcast overlap". Is this a known issue?
```

### 稳定复现步骤 & 代码

-

**Comment by Tom-Zheng** [comment]
@FeixLiu  for vis.

**Comment by FeixLiu** [comment]
We didn't meet the same problem during previous tests, could you provide some cases that can result the problem?  In the mentioned PR, two kinds of overlap has been enabled: reduce overlap backward and broadcast overlap forward. Do you know which kind of overlap causes the problem?
