### ISSUE TITLE
[Question]:官方案例实体抽取结果为空 

### ISSUE THREAD

**Issue by wsh2836741** [PaddlePaddle/PaddleNLP#7384]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/21173914/e7094367-b1bc-4abc-ba9c-1f1d0627bb9a)

**Comment by watermonth** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/137641777/be9b5a88-80e7-4b5a-a92f-1e1b846e2fa7)
我也是用官方的例子，返回了个鬼

**Comment by watermonth** [comment]
一群水论文的程序员搞的，我也试了。提取的结果太烂了。

**Comment by bobo-168** [comment]
我也遇到同样问题。。。。

**Comment by bobo-168** [comment]
解决了。
建议按以下步骤进行安装：
1.conda install paddlepaddle==2.5.0rc1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
2.pip install paddlenlp -i https://pypi.tuna.tsinghua.edu.cn/simple

安装后的PADDLE相关的版本号：
(my_paddlenlp_test) [root@OracleLinux data]# conda list | grep paddle
# packages in environment at /data/miniconda3/envs/my_paddlenlp_test:
paddle2onnx               1.1.0                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.6.1                    pypi_0    pypi
paddlepaddle              2.5.0rc1                 pypi_0    pypi

**Comment by wsh2836741** [comment]
@bobo-168 强👍🏻，可以了

**Comment by littlewwwhite** [comment]
> 解决了。 建议按以下步骤进行安装： 1.conda install paddlepaddle==2.5.0rc1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ 2.pip install paddlenlp -i https://pypi.tuna.tsinghua.edu.cn/simple
> 
> 安装后的 PADDLE 相关的版本号： (my_paddlenlp_test) [root@OracleLinux data]# conda list | grep paddle
> 
> # packages in environment at /data/miniconda3/envs/my_paddlenlp_test:
> paddle2onnx 1.1.0 pypi_0 pypi paddlefsl 1.1.0 pypi_0 pypi paddlenlp 2.6.1 pypi_0 pypi paddlepaddle 2.5.0rc1 pypi_0 pypi

牛的，是什么原因导致的问题？
