### ISSUE TITLE
[Question]: pp下是否可以开启flash atten

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleNLP#7387]
### 请提出你的问题

当前paddle flash atten不支持attention mask
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/31957460/9f175a6b-e9f5-4851-aee6-6962c8860646)

根据`paddlenlp/transformers/llama/modeling.py`的注释pp下需要`atten mask`
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/31957460/a9d82bfe-f46b-43cc-9f78-5ebccf010569)

请问当前flash atten + pp是否支持？

**Comment by ZHUI** [comment]
> 请问当前flash atten + pp是否支持？

支持的。这里是不是用flash attn 的时候，需要自己构造mask
