### ISSUE TITLE
[Question]: 针对UIE模型能不能更新一下

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#7390]
### 请提出你的问题

UIE预训练模型好久没更新了。能否更新更新模型，使得模型效果更好。

**Comment by ZHUI** [comment]
抱歉，由于人力原因。UIE 可能暂时不会更新

**Comment by tianchiguaixia** [comment]
1.支持所有图片类型  2.支持交互，所答即所见
3.针对换行的文本，解决换行问题   4.返回坐标信息     5.自定义化的功能，本地的定义，fewshot学习，各种大模型切换等等。
