### ISSUE TITLE
[Question]: 同一个模型在不同服务上推理的结果不同

### ISSUE THREAD

**Issue by chenfuckthesky** [PaddlePaddle/PaddleNLP#7406]
### 请提出你的问题

我基于uie-base训练taskflow模型（信息抽取、文本分类都有这个问题），得到的模型数据，在不同的服务器上面跑，得到的结果是完全不一样的。在训练模型的这台设备上，用它进行推理，得到的结果全是错的，但是放到另一台服务器上则是对的。这是什么原因导致的？这两台服务器所装的cuda/paddlepaddle-gpu/paddlenlp等的版本是完全一样的，只是python的版本不同。

**Comment by tianchiguaixia** [comment]
路径

**Comment by zhangqiqi1228** [comment]
> 路径

@tianchiguaixia 你好，我也遇到了同样的问题。

请问能具体解释一下么，为什么路径会影响uie-base的推理结果呀？
