### ISSUE TITLE
paddlepaddle-gpu 2.1.1.post112在有gpu的容器中未能正确开启

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#742]
现象：paddlepaddle-gpu 2.1.1.post112在有gpu的容器中未能正确开启，这台容器的gpu信息如下：

![image](https://user-images.githubusercontent.com/83859417/125467773-2da3ff18-9f04-4efb-a572-f5e933b7eea4.png)

![image](https://user-images.githubusercontent.com/83859417/125467184-8142ea95-b447-49b6-acf1-2987b526a51a.png)

从两边的版本看都是具合的，这台容器是从我的GPU训练机器上克隆出来的， python版本都是3.7.10， 我的训练环境能够正常开启GPU训练。 以下是我训练环境的GPU信息， 

![image](https://user-images.githubusercontent.com/83859417/125468393-736a33d3-aeb9-4012-a69f-e1cb06b2e9a8.png)

所以感觉非常奇怪。

**Comment by wawltor** [comment]
import paddle
paddle.utils.run_check()

试一下gpu版本是否正确安装

**Comment by LangDaoAI** [comment]
> import paddle
> paddle.utils.run_check()
> 
> 试一下gpu版本是否正确安装

嗯， 训练机器上正确安装了， 请看一下，推理机器我明早测试一下

![image](https://user-images.githubusercontent.com/83859417/125477774-e9adfcba-e3f5-46de-87d7-e545d08c1afe.png)

**Comment by LangDaoAI** [comment]
已经确认还是容器环境问题，关闭
