### ISSUE TITLE
Bert+BiLSTM+CRF报错

### ISSUE THREAD

**Issue by ZeqiangWangAI** [PaddlePaddle/PaddleNLP#743]
版本：
paddlehub              2.0.4          
paddlenlp              2.0.1          
paddlepaddle-gpu       2.1.0.post101  
环境：
ai studio V100 32G环境
代码

模型代码：
import paddle.nn as nn
from paddlenlp.transformers import BertPretrainedModel
from paddlenlp.layers.crf import LinearChainCrf, ViterbiDecoder, LinearChainCrfLoss

```
class BertLSTMCRF(nn.Layer):
    def __init__(self, bert, hidden_dropout_prob = 0.1, lstm_embedding_size = 1024, 
                hidden_size = 1024, lstm_dropout_prob = 0.5, crf_lr=100):
        super().__init__()
        self.num_classes = bert.num_classes
        self.bert = bert  # allow bert to be config
        self.dropout = nn.Dropout(hidden_dropout_prob)
        self.bilstm = nn.LSTM(
            input_size=lstm_embedding_size,  # 1024
            hidden_size=hidden_size // 2,  # 1024
            num_layers=2,
            time_major=False, 
            dropout=lstm_dropout_prob,  # 0.5
            direction='bidirect' 
        )
        self.classifier = nn.Linear(hidden_size, bert.num_classes)
        self.crf = LinearChainCrf(
            self.num_classes, crf_lr=crf_lr, with_start_stop_tag=False)
        self.crf_loss = LinearChainCrfLoss(self.crf)
        self.viterbi_decoder = ViterbiDecoder(
            self.crf.transitions, with_start_stop_tag=False)

    def forward(self,
                input_ids,
                token_type_ids=None,
                position_ids=None,
                attention_mask=None,
                lengths=None,
                labels=None):
        sequence_output = self.bert(
                input_ids,
                token_type_ids=token_type_ids,
                position_ids=position_ids,
                attention_mask=attention_mask)
        sequence_output = self.dropout(sequence_output)
        lstm_output , _ = self.bilstm(sequence_output)
        logits = self.classifier(lstm_output)
        if labels is not None:
            loss = self.crf_loss(logits, lengths, labels)
            return loss
        else:
            _, prediction = self.viterbi_decoder(logits, lengths)
            return prediction
```
训练代码：
    
    tokenizer = BertTokenizer.from_pretrained(args.model_name_or_path)
    #tokenizer = ErnieCtmTokenizer.from_pretrained("ernie-ctm")

    # Define the model netword and its loss
    bert = BertForTokenClassification.from_pretrained(
        args.model_name_or_path, num_classes=label_num)
    model = BertLSTMCRF(bert)
    #model = ErnieCtmForTokenClassification.from_pretrained(
    #    args.model_name_or_path, num_classes=label_num)

报错信息：
[2021-07-13 23:56:58,977] [    INFO] - Found /home/aistudio/.paddlenlp/models/bert-wwm-ext-chinese/bert-wwm-ext-chinese-vocab.txt
[2021-07-13 23:56:58,993] [    INFO] - Already cached /home/aistudio/.paddlenlp/models/bert-wwm-ext-chinese/bert-wwm-ext-chinese.pdparams
W0713 23:56:58.995085  6645 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0713 23:56:59.000708  6645 device_context.cc:422] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1297: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1297: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
Traceback (most recent call last):
  File "./train_crf.py", line 220, in <module>
    do_train(args)
  File "./train_crf.py", line 196, in do_train
    loss = model(input_ids, token_type_ids, lengths=lengths, labels=labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/bert-ner/bert_bilstm_crf.py", line 41, in forward
    lstm_output , _ = self.bilstm(sequence_output)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1049, in forward
    return self._cudnn_impl(inputs, initial_states, sequence_length)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 990, in _cudnn_impl
    not self.training)
ValueError: (InvalidArgument) The cudnn rnn and setting weight size should be same.
  [Hint: Expected weights_size_ == sizeof(T) * weight_numel_, but received weights_size_:33832960 != sizeof(T) * weight_numel_:50397184.] (at /paddle/paddle/fluid/operators/rnn_op.cu.cc:158)
  [operator < rnn > error]

**Comment by libertatis** [comment]
```
ValueError: (InvalidArgument) The cudnn rnn and setting weight size should be same.
```
这个问题出在 `LSTM` 的预期的输入维度和接收的输入维度不匹配。
看了一下你的 `BertLSTMCRF` 模型的实现和训练部分的代码，有两点错误：
其一：
```
self.bilstm = nn.LSTM(
  input_size=lstm_embedding_size, # 1024
  hidden_size=hidden_size // 2, # 1024
  num_layers=2,
  time_major=False,
  dropout=lstm_dropout_prob, # 0.5
  direction='bidirect'
)
```
`LSTM` 的 `input_size` 应该是 `bert` 的 `hidden_size`，不是随便设的。`bert-base` 的 `hidden_size` 是 `768`，`bert-large` 的 `hidden_size` 是 `1024`，正确的写法是：`input_size=self.bert.config['hidden_size']`。
其二：
```
  bert = BertForTokenClassification.from_pretrained(
      args.model_name_or_path, num_classes=label_num)
  model = BertLSTMCRF(bert)
```
嗯，这里不应该用 `BertForTokenClassification`，你不妨看一下它的输出是啥。它的输出是一个分类的 `logits`，不是特征。这里应该用 `BertModel` 才对。即：
```
  bert = BertModel.from_pretrained(
      args.model_name_or_path, num_classes=label_num)
  model = BertLSTMCRF(bert)
```
改完这里，`BertLSTMCRF` 的 `forward` 方法再改一点儿，将：
```
    sequence_output = self.bert(
            input_ids,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            attention_mask=attention_mask)
```
改为：
```
    sequence_output, _ = self.bert(
            input_ids,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            attention_mask=attention_mask)
```
`bert` 的输出有两个，分别是 `sequence_output` 和 `pooled_output`，对于 `token` 级的分类任务，我们只需要 `sequence_output`即可。
目前，改完这些应该就没啥问题了。有问题再提~

**Comment by ZeqiangWangAI** [comment]
版本：
paddlehub              2.0.4          
paddlenlp              2.0.5          
paddlepaddle-gpu       2.1.1.post101  （在paddle上提了这个问题让我更新版本 现在已经是最新版本）
报错：
Traceback (most recent call last):
  File "./train.py", line 261, in <module>
    do_train(args)
  File "./train.py", line 216, in do_train
    attack(att_fun, model,input_ids, token_type_ids,labels, lengths, True, optimizer)
  File "/home/aistudio/work/bert-ner/Attack_Train.py", line 114, in attack
    loss_adv.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:40) #

**Comment by libertatis** [comment]
这个是环境问题，一般重启一下 `AIStudio` 就好了。不行的话，你把你的项目号给我，我看一下~

**Comment by ZeqiangWangAI** [comment]
> 这个是环境问题，一般重启一下 `AIStudio` 就好了。不行的话，你把你的项目号给我，我看一下~

我先重启一下试试 谢谢您啦 非常感谢

**Comment by ZeqiangWangAI** [comment]
主要是后面想跑多卡的脚本任务，不知道在脚本机器上会不会有这样的问题
AI studio默认环境：
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
安装：
paddlehub 2.0.4
paddlenlp 2.0.1
paddlepaddle-gpu 2.1.0.post101
报错：
Traceback (most recent call last):
  File "./train_crf.py", line 218, in <module>
    do_train(args)
  File "./train_crf.py", line 202, in do_train
    avg_loss.backward()
  File "<decorator-gen-123>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 236, in backward
    framework._dygraph_tracer())
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/operators/rnn_op.cu.cc:723)

**Comment by libertatis** [comment]
问题没解决吗？

**Comment by wawltor** [comment]
可以把PaddleNLP更新到最新的版本

**Comment by ZeqiangWangAI** [comment]
> 可以把PaddleNLP更新到最新的版本

刚刚更新到2.0.5还是出现类似问题

**Comment by libertatis** [comment]
你把你的项目地址给我，我来看一下~

**Comment by ZeqiangWangAI** [comment]
> 你把你的项目地址给我，我来看一下~

https://aistudio.baidu.com/aistudio/projectdetail/2183659

**Comment by libertatis** [comment]
> > 你把你的项目地址给我，我来看一下~
> 
> https://aistudio.baidu.com/aistudio/projectdetail/2183659

你的项目没有公开，看不了~

**Comment by ZeqiangWangAI** [comment]
> > > 你把你的项目地址给我，我来看一下~
> > 
> > 
> > https://aistudio.baidu.com/aistudio/projectdetail/2183659
> 
> 你的项目没有公开，看不了~

稍等哈

**Comment by wzq-hunau** [comment]
https://aistudio.baidu.com/studio/project/partial/verify/2183659/c3aeb7ef5adc4111beb69d619ceb4128

**Comment by ZeqiangWangAI** [comment]
> > > 你把你的项目地址给我，我来看一下~
> > 
> > 
> > https://aistudio.baidu.com/aistudio/projectdetail/2183659
> 
> 你的项目没有公开，看不了~
https://aistudio.baidu.com/studio/project/partial/verify/2183659/c3aeb7ef5adc4111beb69d619ceb4128

**Comment by libertatis** [comment]
项目运行的命令是啥呀？

**Comment by ZeqiangWangAI** [comment]
> 项目运行的命令是啥呀？

python -u ./train_crf.py  --model_name_or_path bert-wwm-ext-chinese  --max_seq_length 128  --learning_rate 2e-5  --num_train_epochs 30 --device gpu

**Comment by libertatis** [comment]
有意思，它不是程序不能运行，一开始就报错，而是在第 `6` 个 `step` 的 `loss.backward()` 报的错~

**Comment by ZeqiangWangAI** [comment]
> 有意思，它不是程序不能运行，一开始就报错，而是在第 `6` 个 `step` 的 `loss.backward()` 报的错~

是的 调小了batch之后会在第六个step出问题 batch大的话 会在大概第二个step出问题

**Comment by wawltor** [comment]
@joey12300 辛苦关注一下这个问题

**Comment by libertatis** [comment]
这个问题搞不定！很诡异！我写了个 `notebook` 项目，一开始正常使用 `token` 分类器 `BertForTokenClassification`，项目正常运行，没有任何问题。后来使用 `SkepCrfForTokenClassification`，还没跑多少 `step` 呢，就出现下面这个 `CUBLAS_STATUS_EXECUTION_FAILED` 的问题：
```
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
global_step: 10, epoch: 1, batch: 10/5963, loss: 12.69030, speed: 2.21 step/s, lr=1.9969813852e-05
global_step: 20, epoch: 1, batch: 20/5963, loss: 26.07231, speed: 3.04 step/s, lr=1.9936273688e-05
global_step: 30, epoch: 1, batch: 30/5963, loss: 21.10577, speed: 2.45 step/s, lr=1.9902733523e-05
---------------------------------------------------------------------------OSError                                   Traceback (most recent call last)<ipython-input-19-680e898ebdc7> in <module>
     44             tic_train = time.time()
     45 
---> 46         loss.backward()
     47         optimizer.step()
     48         lr_scheduler.step()
<decorator-gen-247> in backward(self, grad_tensor, retain_graph)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in backward(self, grad_tensor, retain_graph)
    234             else:
    235                 core.dygraph_run_backward([self], [grad_tensor], retain_graph,
--> 236                                           framework._dygraph_tracer())
    237         else:
    238             raise ValueError(
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:40)
```
问题出在 `loss.backward()` 上，不能理解。
如果 `batch_size` 设小一点儿，能跑久一点儿，但还是会出现这个问题。
开始我怀疑是不是 `crf` 的问题，但是官方 `examples` 里信息抽取下的那个 `waybill_ie` 项目，运行 `python run_ernie_crf.py`，并没有任何问题。我直接把示例代码实现的 `ErnieCrfForTokenClassification` 拿过来用还是不行~
这是我的 `AIStudio` 项目地址~
https://aistudio.baidu.com/aistudio/projectdetail/2187480
请求官方支援！官方支援！！支援！！！

PS：老师复现 `bug` 直接运行我的项目就可以~

**Comment by joey12300** [comment]
@libertatis @wzq-hunau 感谢两位支持使用PaddleNLP。目前定位到的错误如下：

![image](https://user-images.githubusercontent.com/10826371/125721715-1f725bee-477e-4792-82cf-0f0b167a3757.png)

## 原因
由于计算CRF Loss的时候会根据label值使用paddle.gather取出发射概率。而目前paddle.gather不支持负数index，并且不检查index值，导致假如使用-1去pad label batch时，在gather时候就会出错。

## 结论
目前关于gather的index合法值检查已经在开发中，预计下个版本会修复该问题。两位可先用非负数值去pad label，如
```
pad_label_id = label_vocab['O']
```
看看是否能解决目前无法训练的bug。

**Comment by ZeqiangWangAI** [comment]
> @libertatis @wzq-hunau 感谢两位支持使用PaddleNLP。目前定位到的错误如下：
> 
> ![image](https://user-images.githubusercontent.com/10826371/125721715-1f725bee-477e-4792-82cf-0f0b167a3757.png)
> 
> ## 原因
> 由于计算CRF Loss的时候会根据label值使用paddle.gather取出发射概率。而目前paddle.gather不支持负数index，并且不检查index值，导致假如使用-1去pad label batch时，在gather时候就会出错。
> 
> ## 结论
> 目前关于gather的index合法值检查已经在开发中，预计下个版本会修复该问题。两位可先用非负数值去pad label，如
> ```
> pad_label_id = label_vocab['O']
> ```
这么说我有印象了 在官方的ernie+crf中ignore_label貌似是100 当时还有点好奇怎么不同的版本ignore值不同 谢谢大家的帮助 @libertatis @wawltor @joey12300

**Comment by libertatis** [comment]
> @libertatis @wzq-hunau 感谢两位支持使用PaddleNLP。目前定位到的错误如下：
> 
> ![image](https://user-images.githubusercontent.com/10826371/125721715-1f725bee-477e-4792-82cf-0f0b167a3757.png)
> 
> ## 原因
> 由于计算CRF Loss的时候会根据label值使用paddle.gather取出发射概率。而目前paddle.gather不支持负数index，并且不检查index值，导致假如使用-1去pad label batch时，在gather时候就会出错。
> 
> ## 结论
> 目前关于gather的index合法值检查已经在开发中，预计下个版本会修复该问题。两位可先用非负数值去pad label，如
> 
> ```
> pad_label_id = label_vocab['O']
> ```
> 
> 看看是否能解决目前无法训练的bug。

我这个代码是参考【NLP 打卡营 命名实体识别】的教程写的，那个 `label_pad_id` 或者 `ignore_id` 是参照教程设的，当时没考虑那么多。这样困扰了我一晚上的问题终于解决了！看来如果对源码不熟悉，有些 `bug` 连定位都很难做到呀！我还需要多学习，源码还需要多看！今天我再看看源码，重新定位一下 `bug`。今天又学到了一个 `debug` 的思路，非常感谢老师的指教~ @joey12300
