### ISSUE TITLE
win10复现复现对话系统UnifiedTransforme遇到的问题

### ISSUE THREAD

**Issue by timohaha** [PaddlePaddle/PaddleNLP#744]
我的环境为win10+python3.6+paddlenlp2.0.5+paddlepaddle-gpu2.1.1.post101
在复现对话系统UnifiedTransformer中finetune.py，代码报错。
`
Epoch 1/3
WARNING: Detect dataset only contains single fileds, return format changed since Paddle 2.1. In Paddle <= 2.0, DataLoader add a list surround output data(e.g. return [data]), and in Paddle >= 2.1, DataLoader return the single filed directly (e.g. return data). For example, in following code: 

import numpy as np
from paddle.io import DataLoader, Dataset

class RandomDataset(Dataset):
    def __getitem__(self, idx):
        data = np.random.random((2, 3)).astype('float32')

        return data

    def __len__(self):
        return 10

dataset = RandomDataset()
loader = DataLoader(dataset, batch_size=1)
data = next(loader())

In Paddle <= 2.0, data is in format '[Tensor(shape=(1, 2, 3), dtype=float32)]', and in Paddle >= 2.1, data is in format 'Tensor(shape=(1, 2, 3), dtype=float32)'

Traceback (most recent call last):
  File "F:/zyz/PaddleNLP-develop/PaddleNLP-develop/examples/dialogue/unified_transformer/finetune.py", line 155, in <module>
    train(args)
  File "F:/zyz/PaddleNLP-develop/PaddleNLP-develop/examples/dialogue/unified_transformer/finetune.py", line 101, in train
    loss = F.cross_entropy(logits, labels)
  File "H:\anaconda\envs\pei\lib\site-packages\paddle\nn\functional\loss.py", line 1392, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at C:\home\workspace\Paddle_release2\paddle/fluid/framework/tensor_impl.h:33)
  [operator < softmax_with_cross_entropy > error]
`
我应该怎么做才能解决这个问题，感谢。 @ZeyuChen @LiuChiachi @zhxfl

**Comment by smallv0221** [comment]
Sorry for the inconvenience. This bug is caused by np.array(). This func generates int32 by default in win32.
We just fixed this in #747 . You can try again now.

**Comment by ZeyuChen** [comment]
@timohaha Please clone the latest code and try again, issues solved by #747

**Comment by AI-Mart** [comment]
还是一样报错哦
