### ISSUE TITLE
[Question]: 零样本文本分类预测值为空：'predictions': []

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/PaddleNLP#7448]
### 请提出你的问题

如何设置predictions至少为schema提供的类别中的一个呢，即使schema里面有"其它"这个类别的时候，predictions还是空的

**Comment by sunfan1997** [comment]
参数single_label设置为True，没有预测为空。
如：my_cls = Taskflow("zero_shot_text_classification", model="utc-base", schema=schema, task_path='./checkpoint/model_best/plm', precision="fp32", single_label=True)

**Comment by Mushano** [comment]
试一下将阈值从0.5调到0
