### ISSUE TITLE
[Question]: uie模型做文本信息抽取时，文本有最大字数限制吗？

### ISSUE THREAD

**Issue by tammy-na** [PaddlePaddle/PaddleNLP#7454]
### 请提出你的问题

uie模型做文本信息抽取时，文本有最大字数限制吗？微调后的模型怎么知道text的最大字数限制？是text有最大字数限制还是schema有最大字数限制？

**Comment by xxllp** [comment]
预测文本没有最大字数限制，因为是分段预测的~~

**Comment by tammy-na** [comment]
> 预测文本没有最大字数限制，因为是分段预测的~~

如果是分段预测是多少字分为一段呢？

**Comment by xxllp** [comment]
这个是根据模型的maxlen，可以是128、256、512。
