### ISSUE TITLE
[Bug]: 在ai_studio上运行uie的实例，返回空数据，但是切换成GPU又没问题

### ISSUE THREAD

**Issue by moqiaaa** [PaddlePaddle/PaddleNLP#7465]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
![微信图片_20231117130434](https://github.com/PaddlePaddle/PaddleNLP/assets/129827905/f01235c9-9bf7-4492-9e6e-f3f51f30efc0)


同样的弄到linux服务器也是这个情况，
linux环境配置如下，到底啥原因
![0FAB2MW0R)83@0IZT$XO}1D](https://github.com/PaddlePaddle/PaddleNLP/assets/129827905/3824bf60-2208-4210-b9aa-d74b0f5052b2)
```

### 稳定复现步骤 & 代码

![微信图片_20231117130434](https://github.com/PaddlePaddle/PaddleNLP/assets/129827905/f01235c9-9bf7-4492-9e6e-f3f51f30efc0)

同样的弄到linux服务器也是这个情况，
linux环境配置如下，到底啥原因
![0FAB2MW0R)83@0IZT$XO}1D](https://github.com/PaddlePaddle/PaddleNLP/assets/129827905/3824bf60-2208-4210-b9aa-d74b0f5052b2)

**Comment by memoryleilei** [comment]
同样的问题。。。而且每次的结果还可能随机出现些其他结果
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/42407587/460f2b3c-7e0b-4a87-bb27-66b07ae20d7a)

**Comment by fedral** [comment]
碰到过类似的问题：
CPU 版本 paddlepaddle 2.5.2 + paddlenlp 2.6.1 每次run，文本特征向量数值随机。
切换成GPU 版本 paddlepaddle-gpu 2.5.2 + paddlenlp 2.6.1  结果才正确。

**Comment by tianbuwei** [comment]
我也是这样的问题

**Comment by Godfish-Li** [comment]
同问

**Comment by jiaohuix** [comment]
同问，我也出现cpu为空，gpu正常
