### ISSUE TITLE
[Question]: 请问LLM如何加载HF下载的模型以及Tokenizer

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/PaddleNLP#7506]
### 请提出你的问题

想要请教一下如何加载或者转化HF上下载的模型文件。
1. 针对模型文件，使用`AutoModelForCausalLM.from_pretrained("/path/to/pytorch/model", convert_from_torch=True, dtype="float16")`命令进行了转化。
2. 但是对于Tokenizer并没有找到相关的转化文档。直接加载显示vocab文件缺失错误。麻烦帮忙看一下。

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/12699033/9ee70c9d-be51-4a7d-8d05-f0c7f58ac504)

**Comment by wj-Mcat** [comment]
这块已经在计划中了，后续有 PR 我们会 link 这个 issue。

此外，针对于你这个场景下，你只需要rename 一下sentencepiece 的文件就行了：tokenizer.model -> sentencepiece.bpe.model

**Comment by Fordacre** [comment]
> tokenizer.model -> sentencepiece.bpe.model

按照上述方式已经成功解决，多谢。
