### ISSUE TITLE
[Question]: How to predownload sentencepiece bpe model?

### ISSUE THREAD

**Issue by danteblink** [PaddlePaddle/PaddleNLP#7512]
### 请提出你的问题

Hi, 

I have the following problem. I have a docker container that implements the SER Model from Paddle. The SER inference script uses PaddleNLP. Every time when the container is restarted, if I run the inference script, it downloads the sentencepiece.bpe.model to /root/.paddlenlp/models/layoutxlm-base-uncased.

Is there a way to download this file and point to it from the code to avoid this?

**Comment by wj-Mcat** [comment]
You can cache the related files and mount it to docker contaienr.
