### ISSUE TITLE
为什么有时候本地跑微调uie报错需要联网 ？

### ISSUE THREAD

**Issue by ws441572091** [PaddlePaddle/PaddleNLP#7527]
本地离线循环跑模型，用uie-base
第一次跑的时候正常，没有保存模型
第二次跑的时候就报错，log显示开始从网站上下载uie-base-1.0版本
然后由于没有联网报错connection error

**Comment by sijunhe** [comment]
如果model_name_or_path是本地路径，或者cache里面已经有下好的模型，就不会联网

**Comment by ws441572091** [comment]
> 如果model_name_or_path是本地路径，或者cache里面已经有下好的模型，就不会联网

是本地路径，我是循环对不同数据跑对比实验，第一次能正常使用本地路径，第二次就会报错联网
