### ISSUE TITLE
[Question]: ALBERT文档API中会返回hidden_states, attentions，我这里却是hidden_states=None, attentions=None

### ISSUE THREAD

**Issue by wangbofan** [PaddlePaddle/PaddleNLP#7533]
### 请提出你的问题

import paddle
from paddlenlp.transformers import AlbertModel, AlbertTokenizer

tokenizer = AlbertTokenizer.from_pretrained('albert-base-v1')
model = AlbertModel.from_pretrained('albert-base-v1')

inputs = tokenizer("Welcome to use PaddlePaddle and PaddleNLP!i like ball")
inputs = {k:paddle.to_tensor([v]) for (k, v) in inputs.items()}
output = model(**inputs,return_dict=True)
output
....................29857466, -0.08089331]]), hidden_states=None, attentions=None)
hidden_states和hidden_states一直显示为None

**Comment by JasonCZH4** [comment]
你好，请问你的问题解决了吗，我也遇到这个问题了
