### ISSUE TITLE
[Question]: 训练好的UTC模型做量化

### ISSUE THREAD

**Issue by luoruijie** [PaddlePaddle/PaddleNLP#7535]
### 请提出你的问题

我想把我训练好的模型做一下量化操作，请问是否这方面的说明文档啊。看了一下paddleslim那边也没找到对UTC模型做量化的说明。

**Comment by JoshonSmith** [comment]
训练好的UTC模型如何做量化？

**Comment by zwjwhxz** [comment]
同问

**Comment by zwjwhxz** [comment]
请问训练好的UTC模型做量化解决了吗 @luoruijie
