### ISSUE TITLE
[Question]: uie模型能否部署在麒麟系统（ARM架构）

### ISSUE THREAD

**Issue by Mnanazi** [PaddlePaddle/PaddleNLP#7564]
### 请提出你的问题

按照[该文章](https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/download_prebuilt_libraries.md)所述，在uie的gpu部署中没有提到arm架构（麒麟系统是aarch64的），请问是否说明训练的gpu版本的uie模型不能部署在麒麟系统，只能部署cpu版本的uie模型？

**Comment by xxllp** [comment]
模型不太好支持吧

**Comment by Juruobudong** [comment]
请问UIE在fastdeploy-python是能支持鲲鹏cpu推理的吗，我看FastDeploy支持Linux下AArch64 CPU
我环境是型号名称： Kunpeng-920
系统：Kylin V10
架构： aarch64
