### ISSUE TITLE
[Question]: 蒸馏训练的问题

### ISSUE THREAD

**Issue by Shadow-Pirates** [PaddlePaddle/PaddleNLP#7567]
### 请提出你的问题

在根据https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain进行的过程中，当进行到模型训练的步骤时，出现了这个问题：
$ python train.py \
    --train_path data/train_data.json \
    --dev_path data/dev_data.json \
    --label_maps_path data/label_maps.json \
    --num_epochs 50 \
    --model_name_or_path ernie-3.0-base-zh
D:\CondaEnv\envs\paddle2\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-12-01 17:00:38,902] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'.
[2023-12-01 17:00:38,902] [    INFO] - Already cached C:\Users\zh\.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt
[2023-12-01 17:00:38,919] [    INFO] - tokenizer config file saved in C:\Users\zh\.paddlenlp\models\ernie-3.0-base-zh\tokenizer_config.json
[2023-12-01 17:00:38,919] [    INFO] - Special tokens file saved in C:\Users\zh\.paddlenlp\models\ernie-3.0-base-zh\special_tokens_map.json
Traceback (most recent call last):
  File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 189, in <module>
    do_train()
  File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 44, in do_train
    model = ErnieLayoutForClosedDomainIE.from_pretrained(
  File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 671, in from_pretrained
    return cls.from_pretrained_v2(
  File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1522, in from_pretrained_v2
    config, model_kwargs = cls.config_class.from_pretrained(
  File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 742, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 768, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(
  File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 843, in _get_config_dict
    raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found")
FileNotFoundError: configuration file<config.json> or <model_config.json> not found
类似的问题没有找到解决办法。

**Comment by ahahaha-zxp** [comment]
> ### 请提出你的问题
> 在根据[https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain进行的过程中，当进行到模型训练的步骤时，出现了这个问题：](https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain%E8%BF%9B%E8%A1%8C%E7%9A%84%E8%BF%87%E7%A8%8B%E4%B8%AD%EF%BC%8C%E5%BD%93%E8%BF%9B%E8%A1%8C%E5%88%B0%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%AD%A5%E9%AA%A4%E6%97%B6%EF%BC%8C%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%9A) $ python train.py --train_path data/train_data.json --dev_path data/dev_data.json --label_maps_path data/label_maps.json --num_epochs 50 --model_name_or_path ernie-3.0-base-zh D:\CondaEnv\envs\paddle2\lib\site-packages_distutils_hack__init__.py:33: UserWarning: Setuptools is replacing distutils. warnings.warn("Setuptools is replacing distutils.") [2023-12-01 17:00:38,902] [ INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'. [2023-12-01 17:00:38,902] [ INFO] - Already cached C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt [2023-12-01 17:00:38,919] [ INFO] - tokenizer config file saved in C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\tokenizer_config.json [2023-12-01 17:00:38,919] [ INFO] - Special tokens file saved in C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\special_tokens_map.json Traceback (most recent call last): File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 189, in do_train() File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 44, in do_train model = ErnieLayoutForClosedDomainIE.from_pretrained( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 671, in from_pretrained return cls.from_pretrained_v2( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1522, in from_pretrained_v2 config, model_kwargs = cls.config_class.from_pretrained( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 742, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 768, in get_config_dict config_dict, kwargs = cls._get_config_dict( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 843, in _get_config_dict raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found") FileNotFoundError: configuration file<config.json> or <model_config.json> not found 类似的问题没有找到解决办法。

我也遇到这个问题了

**Comment by ahahaha-zxp** [comment]
> > ### 请提出你的问题
> > 在根据[https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain进行的过程中，当进行到模型训练的步骤时，出现了这个问题：](https://github.com/linjieccc/PaddleNLP/tree/add-doc-ie/applications/information_extraction/document/closed_domain%E8%BF%9B%E8%A1%8C%E7%9A%84%E8%BF%87%E7%A8%8B%E4%B8%AD%EF%BC%8C%E5%BD%93%E8%BF%9B%E8%A1%8C%E5%88%B0%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83%E7%9A%84%E6%AD%A5%E9%AA%A4%E6%97%B6%EF%BC%8C%E5%87%BA%E7%8E%B0%E4%BA%86%E8%BF%99%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%9A) $ python train.py --train_path data/train_data.json --dev_path data/dev_data.json --label_maps_path data/label_maps.json --num_epochs 50 --model_name_or_path ernie-3.0-base-zh D:\CondaEnv\envs\paddle2\lib\site-packages_distutils_hack__init__.py:33: UserWarning: Setuptools is replacing distutils. warnings.warn("Setuptools is replacing distutils.") [2023-12-01 17:00:38,902] [ INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load 'ernie-3.0-base-zh'. [2023-12-01 17:00:38,902] [ INFO] - Already cached C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\ernie_3.0_base_zh_vocab.txt [2023-12-01 17:00:38,919] [ INFO] - tokenizer config file saved in C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\tokenizer_config.json [2023-12-01 17:00:38,919] [ INFO] - Special tokens file saved in C:\Users\zh.paddlenlp\models\ernie-3.0-base-zh\special_tokens_map.json Traceback (most recent call last): File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 189, in do_train() File "D:\Paddle\PaddleNLP-add-doc-ie\applications\information_extraction\document\closed_domain\train.py", line 44, in do_train model = ErnieLayoutForClosedDomainIE.from_pretrained( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 671, in from_pretrained return cls.from_pretrained_v2( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\model_utils.py", line 1522, in from_pretrained_v2 config, model_kwargs = cls.config_class.from_pretrained( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 742, in from_pretrained config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs) File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 768, in get_config_dict config_dict, kwargs = cls._get_config_dict( File "D:\CondaEnv\envs\paddle2\lib\site-packages\paddlenlp\transformers\configuration_utils.py", line 843, in _get_config_dict raise FileNotFoundError(f"configuration file<{CONFIG_NAME}> or <{LEGACY_CONFIG_NAME}> not found") FileNotFoundError: configuration file<config.json> or <model_config.json> not found 类似的问题没有找到解决办法。
> 
> 我也遇到这个问题了

debug后发现， 是 https://bj.bcebos.com/paddlenlp/models/community/ernie-3.0-base-zh/config.json 不存在

![企业微信截图_17157524411583](https://github.com/PaddlePaddle/PaddleNLP/assets/66762398/ba1985bb-96a8-42f7-a300-467f58fda09a)
