### ISSUE TITLE
[Question]: 如何制作自己的数据集

### ISSUE THREAD

**Issue by stardustzh** [PaddlePaddle/PaddleNLP#7599]
### 请提出你的问题

想要使用自己的图片文档制作类似于 xfund_zh 格式的数据集用于 ernie-layout 模型的文档信息抽取任务微调，请问有什么方法可以快速地制作数据集？

**Comment by dc6273632** [comment]
同问

**Comment by w5688414** [comment]
可以参考源数据集制作一份：

https://github.com/doc-analysis/XFUND/releases
