### ISSUE TITLE
rocketqa-base-cross-encoder中模型训练完后，利用deploy.sh导出模型，运行web_service.py启动服务，python rpc_client.py请求，发现预测单个样本和多个样本(预测batch不同)打分不一样。请问这是符合预期的吗？

### ISSUE THREAD

**Issue by liulj0507** [PaddlePaddle/PaddleNLP#7605]
### 请提出你的问题

rocketqa-base-cross-encoder中模型训练完后，利用deploy.sh导出模型，运行web_service.py启动服务，python rpc_client.py请求，发现预测单个样本和多个样本(预测batch不同)打分不一样。请问这是符合预期的吗？
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/neural_search/ranking/cross_encoder

**Comment by w5688414** [comment]
有问题，怎么复现呢？环境是什么？
