### ISSUE TITLE
CRF-前向计算错误

### ISSUE THREAD

**Issue by ZeqiangWangAI** [PaddlePaddle/PaddleNLP#762]
环境：
paddlehub              2.0.4          
paddlenlp              2.0.5          
paddlepaddle-gpu       2.0.2.post101  
代码：

训练代码    
for epoch in range(10):
        for token_ids, lengths, label_ids in train_loader:
            loss = model(token_ids, lengths, label_ids)
            loss = loss.mean()
            loss.backward()
            optimizer.step()
            optimizer.clear_grad()
            step += 1
            print("[TRAIN] Epoch:%d - Step:%d - Loss: %f" % (epoch, step, loss))
        evaluate(model, metric, dev_loader)
        paddle.save(model.state_dict(), './ernie_ckpt/model_%d.pdparams' % step)
CRF：
class BiGRUWithCRF(nn.Layer):
    def __init__(self,
                 emb_size,
                 hidden_size,
                 word_num,
                 label_num,
                 use_w2v_emb=False):
        super(BiGRUWithCRF, self).__init__()
        if use_w2v_emb:
            self.word_emb = TokenEmbedding(
                extended_vocab_path='./data/word.dic', unknown_token='OOV')
        else:
            self.word_emb = nn.Embedding(word_num, emb_size)
        self.gru = nn.GRU(emb_size,
                          hidden_size,
                          num_layers=4,
                          direction='bidirect')
        # We need `label_num + 2` for appending BOS and EOS tag 
        self.fc = nn.Linear(hidden_size * 2, label_num + 2)
        self.crf = LinearChainCrf(label_num)
        self.crf_loss = LinearChainCrfLoss(self.crf)
        self.viterbi_decoder = ViterbiDecoder(self.crf.transitions)

    def forward(self, inputs, lengths, labels=None):
        embs = self.word_emb(inputs)
        output, _ = self.gru(embs)
        emission = self.fc(output)
        if labels is not None:
            loss = self.crf_loss(emission, lengths, labels)
            return loss
        else:
            _, prediction = self.viterbi_decoder(emission, lengths)
            return prediction
备注：完全是example/information_extraction/ 下面的官方GRU-CRF代码
错误信息：
能够正常训练50个step:
Traceback (most recent call last):
  File "run_bigru_crf.py", line 134, in <module>
    evaluate(model, metric, dev_loader)
  File "<decorator-gen-233>", line 2, in evaluate
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 315, in _decorate_function
    return func(*args, **kwargs)
  File "run_bigru_crf.py", line 51, in evaluate
    preds = model(token_ids, lengths)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/model.py", line 51, in forward
    _, prediction = self.viterbi_decoder(emission, lengths)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/layers/crf.py", line 398, in forward
    for i, logit in enumerate(inputs_t[:max_seq_len]):
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows None or integers in slice item, but received Tensor. (at /paddle/paddle/fluid/pybind/imperative.cc:337)

我只更换了数据集
但是数据集文本比较长 平均sequence_length大约是500

**Comment by wawltor** [comment]
辛苦升级一下PaddlePaddle的版本

**Comment by ZeqiangWangAI** [comment]
> 辛苦升级一下PaddlePaddle的版本
更新到最新的paddle版本之后可以了 谢谢
