### ISSUE TITLE
示例一键UIE预测返回值为空

### ISSUE THREAD

**Issue by YinSonglin1997** [PaddlePaddle/PaddleNLP#7628]
### 请提出你的问题

根据README中的一键UIE预测进行测试，返回结果为空值。
![1702360297946](https://github.com/PaddlePaddle/PaddleNLP/assets/90330685/3f3de9a3-f35e-4017-94fb-d6358f086913)

**Comment by DigYang** [comment]
遇到同样问题

**Comment by evan-qianjh** [comment]
示例就没一个能跑的。。

**Comment by ehehe066** [comment]
> 示例就没一个能跑的。。

安装paddlepaddle==2.5.0rc1 就可以用了

**Comment by ireader2008** [comment]
就没一个能用，全返回空

**Comment by w5688414** [comment]
可以降低PaddleNLP和Paddle的版本试一下

**Comment by ireader2008** [comment]
谢谢，降低版本解决了

w5688414 ***@***.***> 于2024年4月25日周四 18:10写道：
