### ISSUE TITLE
层次分类检索方式需要更新线上模型时如何操作

### ISSUE THREAD

**Issue by BEILOP** [PaddlePaddle/PaddleNLP#7638]
### 请提出你的问题

小批量更新标签，是直接覆盖label.txt然后导出label——embedding后，直接运行milvus插入向量的代码么。还是说要先清空milvus。
大批量更新标签，重新训练完又如何更新呢

**Comment by w5688414** [comment]
直接把标签插入到Milvus向量数据库中，即可更新。推荐和原来的分类模型一起使用，检索方案作为补充，效果更佳。
