### ISSUE TITLE
unified_transformer中文输入退格导致UnicodeDecodeError

### ISSUE THREAD

**Issue by yulangz** [PaddlePaddle/PaddleNLP#764]
在使用PaddleNLP/examples/dialogue/unified_transformer/interaction.py人机交互模式时，输入中文后使用退格键删除会导致UnicodeDecodeError，目前可以确定是因为utf-8下一个汉字占3个字节，退格键一次只会删除1个字节，解决方法是按3次退格，但是会导致屏幕中显示异常。不知道能不能从代码层面修改，或许也可以在Readme中提示一下。

**Comment by smallv0221** [comment]
Interaction,py is just a demo, not a qualified application. Thanks for reporting this constraint. We have added this to our README. #774
