### ISSUE TITLE
[Question]: 请问是否有与关键词挖掘、新词挖掘相关的能力，最近业务从长文本中提取重要关键词

### ISSUE THREAD

**Issue by yspyhp** [PaddlePaddle/PaddleNLP#7659]
### 请提出你的问题

请问是否有与关键词挖掘、新词挖掘相关的能力，最近业务从长文本中提取重要关键词

**Comment by w5688414** [comment]
推荐使用大模型解决您的问题：
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm
