### ISSUE TITLE
[Question]: text_summarization默认模型部署后，效果不尽人意，完全没有文档中的效果好

### ISSUE THREAD

**Issue by zhaziqwe** [PaddlePaddle/PaddleNLP#7682]
### 请提出你的问题

```
from paddlenlp import Taskflow
summarizer = Taskflow("text_summarization")
```
下面是两个测试效果
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/95856679/9aa8cf83-c686-40ea-a0ff-f1667c6c85ea)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/95856679/1517365a-bb9a-46a1-9c95-18d2a913b55e)
可以看到，明明是关于牙刷的信息，却生成了完全不相关的摘要

**Comment by bamboolaile** [comment]
麻烦问下兄弟这个问题解决了吗，我也遇到类似问题

**Comment by w5688414** [comment]
您好，文本摘要任务现在推荐使用大模型。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm
