### ISSUE TITLE
[Bug]: fast_generation/samples/opt_sample.py 运行错误

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleNLP#7689]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: develop
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
_C_ops.matmul 错误
```

### 稳定复现步骤 & 代码

cd fast_generation/samples/
python opt_sample.py

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/4617245/9ff2d535-2be4-41e1-8cc9-739c5df2280b)

**Comment by w5688414** [comment]
fast_generation 由于人力有限，停止维护了，可以降低paddle和paddlenlp的版本试试
