### ISSUE TITLE
[Question]: 加载自定数据集时，使用load_dataset方法无法传入label_list

### ISSUE THREAD

**Issue by lcneyc** [PaddlePaddle/PaddleNLP#7710]
### 请提出你的问题

<img width="1205" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/90854867/2b332648-6123-48db-ac1f-4979c9ba61bc">
<img width="687" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/90854867/2d6aacb7-7e69-4615-afc9-99076d32b50e">

**Comment by w5688414** [comment]
上面提示你的train_ds为空，请检查一下你的数据
