### ISSUE TITLE
[Question]: ernie_matching能否给出一个可以直接判断的函数

### ISSUE THREAD

**Issue by SamZhou-2019** [PaddlePaddle/PaddleNLP#7719]
### 请提出你的问题

examples/text_matching/ernie_matching
这个模型感觉很不错，但是实际用起来不方便。具体体现在：
训练好模型之后，如果要判断自己的数据，必须要将数据**以“word1\tword2”的格式，存储为tsv文件后进行**。而在实际处理数据时，反复存储数据会增加时间成本和外部存储器损耗。是否可以写一个函数，输入两个词即可判断。也就是相当于：
`def matching(word1:str, word2:str)->bool`
个人能力有限写不出来，希望官方或者大神可以解答，万分感谢！

**Comment by w5688414** [comment]
欢迎开发者贡献哈
