### ISSUE TITLE
text_classification\pretrained_models\train.py训练出现异常

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#772]
请Team看一下，当使用train.py训练时候出现如下异常， 使用的数据集是chnsenticorp

![image](https://user-images.githubusercontent.com/83859417/126256038-3eb93c78-31e3-4199-8286-320ace807bc4.png)

**Comment by LangDaoAI** [comment]
我是修改了源码，变更为ernie-gram-zh预训练模型

![image](https://user-images.githubusercontent.com/83859417/126256248-c1dd527b-a2cd-4600-bc58-06028d385e6b.png)

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/126257489-916be018-dec3-4ebf-8797-7eba53e57b69.png)

![image](https://user-images.githubusercontent.com/83859417/126257511-f4aee796-222a-4ae4-b603-24d81a53f0f0.png)

**Comment by LangDaoAI** [comment]
我设置了batch是16，max length是256

**Comment by linjieccc** [comment]
您好，可以换成ppnlp.transformers.ErnieGramForSequenceClassification再试下

**Comment by LangDaoAI** [comment]
![image](https://user-images.githubusercontent.com/83859417/126267183-4e97eea6-93cd-4aa6-9a9d-830c9f86238e.png)

换了之后，出现上面错误

**Comment by LangDaoAI** [comment]
我是从以下地址下载了新的ernie_gram_zh模型，放到了$HOME/paddlenlp/models/ernie_gram_zh目录下面，

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie_gram/modeling.py#L106

**Comment by LangDaoAI** [comment]
已经解决了，关闭问题
