### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Lobaer-D** [PaddlePaddle/PaddleNLP#7723]
### 请提出你的问题

pipelines搭建了语义检索系统，启动了rest_api服务，上传文档应该怎么切割，需要传入什么参数，为什么一直整篇文档向量化

**Comment by w5688414** [comment]
请升级到最新的pipelines版本，然后试试这个。https://github.com/PaddlePaddle/PaddleNLP/tree/a33ab3781ff2dd2fe3a5bfb3d9f906b8406e8c92/pipelines/examples/chatbot
