### ISSUE TITLE
[Question]: EFL微调后的模型如何进行推理

### ISSUE THREAD

**Issue by dhh-chyc** [PaddlePaddle/PaddleNLP#7726]
### 请提出你的问题

examples/few_shot/efl 微调后的模型如何进行推理，官方文档中没有给出调用示例，加载微调后的模型，提示缺少配置文件

**Comment by w5688414** [comment]
请参考代码：

https://github.com/PaddlePaddle/PaddleNLP/blob/de149078f883a2e278047c5c06f77b76d5a52431/examples/few_shot/pet/utils.py#L213
