### ISSUE TITLE
[Question]: improved_aesthetics_6plus

### ISSUE THREAD

**Issue by kopyl** [PaddlePaddle/PaddleNLP#7751]
### 请提出你的问题

Hey. Is there any chance you have this dataset cached locally and can send it to me?

https://huggingface.co/datasets/ChristophSchuhmann/improved_aesthetics_6plus

I'm going to train miniSDXL (like lambdalabs/miniSD-diffusers, but for SDXL) and need the exact same dataset which was used here...

**Comment by w5688414** [comment]
Sorry, we don't provide the dataset, you can download the dataset through huggingface or some other available downloads
