### ISSUE TITLE
[Question]: 中文文本纠错, 启示 判定为错别字, 误判.请问如何纠正?

### ISSUE THREAD

**Issue by cloudAndMonkey** [PaddlePaddle/PaddleNLP#7769]
### 

<img width="752" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/12228225/f59e56d4-ce88-44b3-9dfa-292497b25e78">

**Comment by w5688414** [comment]
target就是纠正后的文本，另外，text_correction已经停止更新了，推荐使用大模型。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm
