### ISSUE TITLE
请问目前有支持基于ernie-2.0版本的静态图转动态图的工具吗

### ISSUE THREAD

**Issue by cucumberpieces** [PaddlePaddle/PaddleNLP#777]

**Comment by cucumberpieces** [comment]
请问目前有支持基于ernie-2.0版本的静态图转动态图的工具吗

**Comment by Steffy-zxf** [comment]
你好！可以参考这里的参数转换脚本：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/transformers/ernie/static_to_dygraph_params

首先，需要将静态图参数保存成ndarray数据，之后将静态图参数名和对应动态图参数名对应上，之后保存成动态图参数即可。
