### ISSUE TITLE
[Question]: 按照流程使用SimpleServer部署uie抽取后，显存随着推理调用一直增加，直至爆掉

### ISSUE THREAD

**Issue by gaojuntian** [PaddlePaddle/PaddleNLP#7773]
### 请提出你的问题

按照流程使用SimpleServer部署uie抽取后，显存随着推理调用一直增加，直至爆掉

**Comment by w5688414** [comment]
推荐使用fastdeploy的服务化部署。

https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/text/uie

**Comment by Huangswust182** [comment]
@w5688414 使用fastdeploy也有这个问题，uie的显存占用跟样本大小有关吗？
