### ISSUE TITLE
[Question]: uie自动标注doccano问题

### ISSUE THREAD

**Issue by lznext** [PaddlePaddle/PaddleNLP#7783]
### 请提出你的问题

目前我实现了uie对doccano的自动标注实体，训练的UIE是关系实体都能抽取，但是网上给出的自动标注代码只能自动标实体，不能标关系。而且因为标注了关系，UIE返回的抽取信息存在嵌套，如｛实体1｛关系｛实体2｛关系｛实体3｝｝｝｝｝，因此不像实体标注那样简单就能标完。
我参考的自动标注代码来源：https://zhuanlan.zhihu.com/p/623996244 。请各位大佬指点如何标注关系。

**Comment by w5688414** [comment]
您好，UIE停止维护了，推荐使用文心大模型+prompt engineering来抽取实体
