### ISSUE TITLE
[Bug]: Paddle-pipelines 跨模态文图检索搜索不出结果

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/PaddleNLP#7784]
### 软件环境

```Markdown
- paddlepaddle: None
- paddlepaddle-gpu: develop 
- paddlenlp: 2.7.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
demo示例搜索不出结果
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/image_text_retrieval/text_to_image_retrieval_example.py

pipelines 2.5.2 正常
pipelines 2.6.2 搜索不出结果

**Comment by xiuxiuxius** [comment]
bug解决了吗，我是源码安装的0.6.2，但是还是没有结果
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/89114157/315b20ca-d691-47b9-9193-119a13270434)
