### ISSUE TITLE
[Question]: 关于离线蒸馏

### ISSUE THREAD

**Issue by pengcheng-yan** [PaddlePaddle/PaddleNLP#7789]
### 请提出你的问题

FileNotFoundError: [Errno 2] No such file or directory: '/data/datamili/military/sample_index.json'
请问一下  在运行蒸馏代码的时候 一直提示这个  但是军事数据集下面没有做这个sample_index.json，请问一下这个json文件去哪里获取？

**Comment by cap1215** [comment]
同问同问！楼主你解决了吗

**Comment by cap1215** [comment]
解决了，方案如下：
data_distill.py文件中，注释掉44到50行，内容如图
![00ee50de9a6ad84dd27c8eab2d1290e](https://github.com/PaddlePaddle/PaddleNLP/assets/90299019/d01ea6a8-40c8-4031-8a3a-fcf1fcb0750e)
在62行开始加入下述代码：
    indexes = np.random.permutation(len(json_lines))
    index_list = indexes.tolist()

    i1, i2, _ = args.splits
    p1 = int(len(json_lines) * i1)
    p2 = int(len(json_lines) * (i1 + i2))

    train_ids = index_list[:p1]
    dev_ids = index_list[p1:p2]
    test_ids = index_list[p2:]
结果如下图所示：
![8bff9e52d0f9637dc293e162e9e3a54](https://github.com/PaddlePaddle/PaddleNLP/assets/90299019/5d047dd6-4375-4ad7-a55c-396351742547)

原理应该是手动增加个id or 索引，目前我的学生模型训练数据已正常生成
