### ISSUE TITLE
请问如何使用ERNIE进行自然语言推理任务[Question]: 

### ISSUE THREAD

**Issue by dhh-chyc** [PaddlePaddle/PaddleNLP#7792]
### 请提出你的问题

请问如何使用ERNIE进行自然语言推理任务，efl文件夹下的模型调用缺少配置文件

**Comment by w5688414** [comment]
请问您使用的是哪份代码？有链接没

或者复现代码是什么？

**Comment by dhh-chyc** [comment]
我是对下面这个模型微调的，没有找到ERNIE自然语言推理任务怎么使用
https://huggingface.co/MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7

**Comment by w5688414** [comment]
deberta在develop分支已经支持了，可以把模型转换成paddle后进行微调。

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/paddlenlp/transformers/deberta_v2
