### ISSUE TITLE
[Question]: generate API 的 max_new_tokens 和 min_new_token 参数名不统一

### ISSUE THREAD

**Issue by sserdoubleh** [PaddlePaddle/PaddleNLP#7805]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/blob/37b4fe0285dbfd098fc29efcf3eef25984970cc0/paddlenlp/generation/configuration_utils.py#L149-L150
这里的 GenerationConfig 中，max_new_tokens 带 s，而 min_new_token 不带 s，参数名格式不统一，最好还是统一成带 s 的？

**Comment by w5688414** [comment]
感谢反馈，已经做了兼容了。

https://github.com/PaddlePaddle/PaddleNLP/blob/a37f53d6e04cfa89a7aa765c8a36cded57f8182b/paddlenlp/generation/configuration_utils.py#L147
