### ISSUE TITLE
[Bug]: 搭建语义搜索系统Demo，执行dense_faq_example.py时，无法返回任何结果

### ISSUE THREAD

**Issue by qukeji** [PaddlePaddle/PaddleNLP#7814]
### 软件环境

```Markdown
paddle-pipelines               0.6.2
paddle2onnx                    1.1.0
paddlefsl                      1.1.0
paddlenlp                      2.6.1
paddleocr                      2.6.1.3
paddlepaddle                   2.5.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
体验Demo使用faiss作为检索库，在初次执行dense_faq_example.py 根据数据生成faiss正常，但是下面示例的检索内容“企业如何办理社会保险”，无任何结果输出
```

### 稳定复现步骤 & 代码

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/38743841/8bcbcbe5-48ff-46f0-9292-6b6bb226bbee)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/38743841/736bc4d7-55a4-4c41-aba1-903bcaf17b23)
不知道遇到了何种问题，还烦请各位大神帮瞧瞧

**Comment by magicianCoder** [comment]
跟你一样的现象。代码断点后就是没匹配到数据。无语了。

**Comment by qukeji** [comment]
> 跟你一样的现象。代码断点后就是没匹配到数据。无语了。

后来我发现了原因，要在所有操作开始前，将系统的编码设置一下（编码改为utf-8 Linux子系统或Docker内部有可能是中文乱码状态）；否则会导致读取csv数据后是乱码，继而转成的向量异常

**Comment by w5688414** [comment]
bug修复了，请升级到最新的develop版本的pipelines
