### ISSUE TITLE
[Docs]: https://paddlenlp.readthedocs.io/zh/latest/pretraining/dataset.html链接挂了

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/PaddleNLP#7816]
### 软件环境

```Markdown
https://paddlenlp.readthedocs.io/zh/latest/pretraining/dataset.html  
链接挂了

位置
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/README.md
```

### 详细描述

https://paddlenlp.readthedocs.io/zh/latest/pretraining/dataset.html  
链接挂了

位置
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/README.md

**Comment by w5688414** [comment]
感谢反馈，已提pr。

https://github.com/PaddlePaddle/PaddleNLP/pull/8336

也欢迎开发者主动提交PR进行完善。
