### ISSUE TITLE
[Bug]: paddlepaddle print warning message ( Llama-13b pretrain )

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleNLP#7819]
### 软件环境

```Markdown
- paddlepaddle: N/A
- paddlepaddle-gpu: 2.6.0.post120
- paddlenlp: v2.7.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
主框架在 PaddlePaddle/Paddle#59518 中对于multiply输入类型不一致会输出warning日志。
https://github.com/PaddlePaddle/PaddleNLP/blob/b893463f84913d62b278bb76dee2e5efcfae2c2a/paddlenlp/transformers/llama/modeling.py#L371C17-L371C17
存在fp16/bf16和fp32 multiply的场景，导致主框架输出警告日志。
```

### 稳定复现步骤 & 代码
复现代码：
<img width="617" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/31957460/2b1d2419-755d-44b4-8caf-9c1b2892b49d">

错误日志：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/31957460/2d32a9ce-80e0-4d22-a2ff-7af80f87782f)

复现代码/修复PR：
https://github.com/PaddlePaddle/PaddleNLP/pull/7818

**Comment by ZHUI** [comment]
感谢修复
