### ISSUE TITLE
[Question]: 使用DDParser可以自定义词典进行分词吗

### ISSUE THREAD

**Issue by 1042312930** [PaddlePaddle/PaddleNLP#7837]
### 请提出你的问题

使用DDParser可以自定义词典进行分词吗?

from paddlenlp import Taskflow
ddp = Taskflow("dependency_parsing")
ddp("百度是一家高科技公司")
通过加载词典分割出   高科技公司

**Comment by wawltor** [comment]
暂且不支持自定义词表，目前大模型在依存关系上一个比较大的提升方式，可以尝试用大模型应用来解决。
