### ISSUE TITLE
pip下载安装paddlenlp出现问题

### ISSUE THREAD

**Issue by EricDing618** [PaddlePaddle/PaddleNLP#7845]
### 请提出你的问题

在pip install paddlenlp的过程中，下载依赖库pandas时出现报错，Python版本为3.11.0

**Comment by EricDing618** [comment]
有人能提供一个稳定版本吗，谢谢

**Comment by wawltor** [comment]
这个和pandas的安装有关系，可以直接 pip install pandas，同时关注下pandas的稳定版本

**Comment by EricDing618** [comment]
> 这个和pandas的安装有关系，可以直接 pip install pandas，同时关注下pandas的稳定版本

直接`pip install pandas`也会报错
![Image_1705571108698](https://github.com/PaddlePaddle/PaddleNLP/assets/135501423/9e192e0b-ddb0-487b-abac-1d0935debaac)
![Image_1705571107015](https://github.com/PaddlePaddle/PaddleNLP/assets/135501423/325a4c77-3a48-4474-a9b3-d38f16baec64)

**Comment by ZHUI** [comment]
试试
```shell
python -m pip install --upgrade pip
python -m pip install --upgrade --force-reinstall paddlenlp
```

**Comment by EricDing618** [comment]
> 试试
> 
> ```shell
> python -m pip install --upgrade pip
> python -m pip install --upgrade --force-reinstall paddlenlp
> ```


和之前截图里的报错一模一样，就是在pandas那个地方出错

**Comment by EricDing618** [comment]
> 试试
> 
> ```shell
> python -m pip install --upgrade pip
> python -m pip install --upgrade --force-reinstall paddlenlp
> ```

报错如下：
```shell
Collecting pandas (from datasets>=2.0.0->paddlenlp)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6f/41/eb562668eaf93790762f600536b28c97b45803cba9253cd8e436cda96aef/pandas-2.1.4.tar.gz (4.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0 C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.1
      Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0
      Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build
      Build type: native build
      Project name: pandas
      Project version: 2.1.4

      ..\..\meson.build:2:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      A full log can be found at C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

是不是因为我的电脑上没有装什么东西

**Comment by EricDing618** [comment]
> > 试试
> > ```shell
> > python -m pip install --upgrade pip
> > python -m pip install --upgrade --force-reinstall paddlenlp
> > ```
> 
> 报错如下：
> 
> ```shell
> Collecting pandas (from datasets>=2.0.0->paddlenlp)
>   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6f/41/eb562668eaf93790762f600536b28c97b45803cba9253cd8e436cda96aef/pandas-2.1.4.tar.gz (4.3 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>   Preparing metadata (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Preparing metadata (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [12 lines of output]
>       + meson setup C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0 C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build\meson-python-native-file.ini
>       The Meson build system
>       Version: 1.2.1
>       Source dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0
>       Build dir: C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build
>       Build type: native build
>       Project name: pandas
>       Project version: 2.1.4
> 
>       ..\..\meson.build:2:0: ERROR: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> 
>       A full log can be found at C:\Users\Administrator\AppData\Local\Temp\pip-install-kc2pso4y\pandas_ebe49c18eb374e4eae3a409b8f054dd0\.mesonpy-kb06jrlk\build\meson-logs\meson-log.txt
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.
> ```
> 
> 是不是因为我的电脑上没有装什么东西


好了，安装完Visual Studio 2019后vswhere.exe有了，我又把Python3.11的32位版本换成64位的就成功了
