### ISSUE TITLE
做信息抽取，根据官方提示 预训练模型由"ernie-1.0"更换为"roberta-wwm-ext-large"， 开始训练还是正常的，然后f1 recall 一直都是0

### ISSUE THREAD

**Issue by chenxi00a1** [PaddlePaddle/PaddleNLP#785]
模型训练情况：
![M@UI2T UOTFOG{WV@{T3~GT](https://user-images.githubusercontent.com/49149464/126583532-6ec5663f-8cb9-44f9-adb5-af19c7349d1f.png)
模型改变代码：
![NFBAUB7`OQYQP53(737EZGK](https://user-images.githubusercontent.com/49149464/126583666-5695653d-0424-4f70-aeb9-83f61b59a9d2.png)
同时，还有一个线程问题。这个报错在启动训练过程中，时有时无：
![36e4b29e98d577a43248bfd31afddc8](https://user-images.githubusercontent.com/49149464/126583725-0ecede75-1bb2-43c0-becf-7ebcd147a3ee.png)

**Comment by Steffy-zxf** [comment]
你好！使用的是什么数据？代码参考的哪里的代码？建议参考：https://aistudio.baidu.com/aistudio/projectdetail/1639963?channelType=0&channel=0

**Comment by robertoding** [comment]
我也遇到了同样的问题，请问是如何解决的？同样的代码，使用ernie-1.0没问题
