### ISSUE TITLE
[Question]: UIE模型得更新了

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#7858]
### 请提出你的问题

UIE模型好几年没更新了，这个更新一下，适应复杂场景啊

**Comment by wawltor** [comment]
目前暂且没有更新计划，从技术角度而言大模型相关技术是信息抽取方向后续重点应用方向，可以尝试用大模型方式来解决信息抽取的问题。

**Comment by tianchiguaixia** [comment]
可是大模型解决信息抽取，我已经全部打通了。还是喜欢UIE的可靠性。

https://github.com/PaddlePaddle/PaddleNLP/assets/29837553/d922f369-3634-4b67-98a4-4b060a70952a

**Comment by tianchiguaixia** [comment]
https://github.com/PaddlePaddle/PaddleNLP/assets/29837553/fabda300-f10f-48f6-80f5-5be185cdfa80

**Comment by tianchiguaixia** [comment]
https://github.com/PaddlePaddle/PaddleNLP/assets/29837553/03a6451e-8b14-4628-b978-84a5d1fcc190

**Comment by kuntali** [comment]
@tianchiguaixia 大哥，请教下你的技术实现路径，你这个实现方式是先做OCR，再用将识别结果的文字灌入到大模型么？

**Comment by tianchiguaixia** [comment]
> @tianchiguaixia 大哥，请教下你的技术实现路径，你这个实现方式是先做OCR，再用将识别结果的文字灌入到大模型么？

对的

**Comment by tran601** [comment]
> > @tianchiguaixia 大哥，请教下你的技术实现路径，你这个实现方式是先做OCR，再用将识别结果的文字灌入到大模型么？
> 
> 对的

佬，请问ocr识别结果怎么送入大模型的，ocr的识别结果应该是从左上到右下的顺序，按照顺序拼接直接送入大模型可以吗。比如说那个血常规校验报告单，我想要拿到”白细胞数目“的”结果“值，我把ocr识别的结果按顺序拼接，然后送入大模型，可以拿到想要的结果吗

**Comment by tianchiguaixia** [comment]
可以的。
