### ISSUE TITLE
[Bug]: 无法加载huggingface的TinyLlama的模型，特别是Tokenizer不工作

### ISSUE THREAD

**Issue by chen-zhiyu** [PaddlePaddle/PaddleNLP#7861]
### 软件环境

```Markdown
paddle2onnx         1.1.0
paddlefsl           1.1.0
paddlenlp           2.7.1
paddlepaddle-gpu    2.6.0.post117
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
home/work/venv/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2024-01-18 15:44:41,136] [    INFO] - Loading configuration file /home/work/.paddlenlp/models/models--TinyLlama--TinyLlama-1.1B-Chat-v0.5/snapshots/5c9e70dd07f5234bf6bf6a2425fffeecd5a6020b/config.json
Traceback (most recent call last):
  File "tiny_token.py", line 13, in <module>
    tokenizer = LlamaTokenizer.from_pretrained(
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils.py", line 686, in from_pretrained
    tokenizer = super().from_pretrained(pretrained_model_name_or_path, *args, **kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py", line 1605, in from_pretrained
    tokenizer = cls(*init_args, **init_kwargs)
  File "/home/work/venv/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 255, in __impl__
    init_func(self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'vocab_file'
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import *

model_name="TinyLlama/TinyLlama-1.1B-Chat-v0.5"
#model_name="TinyLlama/TinyLlama-1.1B-Chat-v1.0"

#config = LlamaConfig.from_pretrained("./config.json")
config = LlamaConfig.from_pretrained(model_name, from_hf_hub=True)

#model_name="/home/work/github.com/TinyLlama-1.1B-Chat-v0.4"

if True:
    tokenizer = LlamaTokenizer.from_pretrained(
        model_name,
        config=config,
        convert_from_torch=True,
        #from_hf_hub=True
        )

print(tokenizer)

**Comment by chen-zhiyu** [comment]
tokenizer.model 改名为sentencepiece.bpe.model 就ok

**Comment by chen-zhiyu** [comment]
现在需要手动改名才ok，需要程序自动识别，请管理员reopen此卡片

**Comment by 1826133674** [comment]
@chen-zhiyu 您好，完成tiny-llama的convert后，我修改了tokenizer.model的名字后，可以成功加载但是，推理不出正确的结果。请问您有遇到类似的情况吗？
我的环境：
paddle-bfloat             0.1.7
paddle2onnx              1.1.0
paddlefsl                    1.1.0
paddlenlp                   2.7.0.post0
paddlepaddle-gpu     2.6.0.post112
转换代码
from paddlenlp.transformers import AutoModelForCausalLM

AutoModelForCausalLM.from_pretrained("./TinyLlama-1.1B-Chat-v1.0", convert_from_torch=True, dtype="float16")

推理代码
from paddlenlp.transformers import AutoModelForCausalLM, AutoTokenizer
paddle.set_device("gpu:3")
print("paddle.device",paddle.get_device())
model = AutoModelForCausalLM.from_pretrained("./TinyLlama-1.1B-Chat-v1.0")
tokenizer = AutoTokenizer.from_pretrained("./TinyLlama-1.1B-Chat-v1.0")
input_features = tokenizer("introduce your self!", return_tensors="pd")
outputs = model.generate(**input_features, max_new_tokens=128)
print(outputs)
ans = tokenizer.batch_decode(outputs[0])
print("ans",ans)

推理结果

W0130 10:45:50.950965 55792 dygraph_functions.cc:52641] got different data type, run type protmotion automatically, this may cause data type been changed.
(Tensor(shape=[1, 1], dtype=int64, place=Place(gpu:3), stop_gradient=True,
       [[2]]), Tensor(shape=[1, 1], dtype=float32, place=Place(gpu:3), stop_gradient=True,
       [[12.16406250]]))
ans ['</s>']
