### ISSUE TITLE
[Question]: 用paddlenlp的llama2的apply_chat_template的时候一开始能正常得到预测结果，但是到若干次后，就报Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:67 和OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED的错误

### ISSUE THREAD

**Issue by ErnestinaQiu** [PaddlePaddle/PaddleNLP#7866]
### 请提出你的问题

报错代码是
outputs = self.generator.generate(**input_features, decode_strategy="greedy_search", temperature=temperature, top_p=top_p, max_new_tokens=max_gen_len)

完整报错是重复了以下这句报错很多次
Error: /paddle/paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [4096] and greater than or equal to 0, but received [0]

以及以下这段
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED. 
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at /paddle/paddle/phi/kernels/gpudnn/softmax_gpudnn.h:1068)

在网上找到了类似的bug，但是都没有解决
https://aistudio.baidu.com/paddle/forum/topic/show/2297492
https://github.com/PaddlePaddle/PaddleDetection/issues/8426

**Comment by wj-Mcat** [comment]
这种错误一般是模型配置加载错误，你要确保 self.generator 模型 from_pretrained 的路径是对的。

此外，再检查一下你的 input_features 的输入是否符合预期，如果你不知道的话可以把这些信息都贴出来，我们来帮你一起分析下。
