### ISSUE TITLE
[Bug]: 修复随机数生成器调用参数错误导致加载ckpt失败

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/PaddleNLP#7889]
### 软件环境

```Markdown
- paddlepaddle: 2.6.0
- paddlepaddle-gpu: N/A
- paddlenlp: c1ccafaca8a5ef3e167dbb9c1ead8406429d5cb1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
fix generator argument incompatible
```

### 稳定复现步骤 & 代码

报错截图：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/31957460/1920a459-8af1-4398-8e35-bc2b23925d03)

修复PR：https://github.com/PaddlePaddle/PaddleNLP/pull/7888

**Comment by BeingGod** [comment]
PTAL @ZHUI

**Comment by ZHUI** [comment]
还有问题吗？应该没问题了吧

**Comment by BeingGod** [comment]
已经修复~
