### ISSUE TITLE
PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#789]
Epoch 1/3
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "D:/captura_record/paddle_基于深度学习的自然语言处理/84_dialogue_competition/dialogue/Chatbot/paddlenlp_wechaty/train_chat.py", line 155, in <module>
    train(args)
  File "D:/captura_record/paddle_基于深度学习的自然语言处理/84_dialogue_competition/dialogue/Chatbot/paddlenlp_wechaty/train_chat.py", line 96, in train
    for inputs in train_data_loader:
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 204, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-3:
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 199, in _thread_loop
    six.reraise(*sys.exc_info())
  File "D:\Program Files\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 99, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\Program Files\Python37\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 99, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "D:\Program Files\Python37\lib\site-packages\paddlenlp\datasets\dataset.py", line 179, in __getitem__
    idx]) if self._transform_pipline else self.new_data[idx]
  File "D:\Program Files\Python37\lib\site-packages\paddlenlp\datasets\dataset.py", line 170, in _transform
    data = fn(data)
  File "D:\captura_record\paddle_基于深度学习的自然语言处理\84_dialogue_competition\dialogue\Chatbot\paddlenlp_wechaty\utils.py", line 83, in convert_example
    return_length=True)
  File "D:\Program Files\Python37\lib\site-packages\paddlenlp\transformers\unified_transformer\tokenizer.py", line 628, in dialogue_encode
    "to the task: {}.".format(task_type))
AssertionError: The vocab file should contain the special token corresponding to the task: knowledge.

**Comment by smallv0221** [comment]
请问运行的是finetune.py么

**Comment by AI-Mart** [comment]
是的 训练模型的时候报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
请问运行的是finetune.py么

**Comment by smallv0221** [comment]
不好意思我们的readme写的不太准确。plato-mini是不能用于任务型对话任务的。

**Comment by AI-Mart** [comment]
那你们的文档要更新下，另外我要怎么微调plato-mini呢，我想融入自己的数据集


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
不好意思我们的readme写的不太准确。plato-mini是不能用于任务型对话任务的。

**Comment by smallv0221** [comment]
您可以把utils.py中第66行的task_type改为None试试

**Comment by AI-Mart** [comment]
谢谢，改了确实运行没有报错，但是不知道这样更改会不会对训练效果有影响呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 中午12:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
您可以把utils.py中第66行的task_type改为None试试

**Comment by smallv0221** [comment]
我觉得应该没有影响，但我们确实不太推荐对plato-mini继续训练

**Comment by AI-Mart** [comment]
我想引入自己的数据集呢，就是日常对话的数据偏我的数据集那样的回复，在这上面增量训练，你们不推荐的原因是什么呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
我觉得应该没有影响，但我们确实不太推荐对plato-mini继续训练

**Comment by smallv0221** [comment]
我们不推荐的原因是这个模型已经在大规模语料上finetune好了，继续finetune可能会有模型退化这种不可知的影响。当然也可能不会。

**Comment by AI-Mart** [comment]
那如果我要定制闲聊的机器人应该如何操作呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
我们不推荐的原因是这个模型已经在大规模语料上finetune好了，继续finetune可能会有模型退化这种不可知的影响。当然也可能不会。

**Comment by smallv0221** [comment]
您可以训练plato-mini试试，也可以尝试把模型换成`unified_transformer-12L-cn`，然后把task_type设成“chitchat”

**Comment by AI-Mart** [comment]
好的，不过unified_transformer-12L-cn是千万级数据集训练得出来的，词的语义表示会不会plato更准确呢，毕竟plato训练的数据集是过亿的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
您可以训练plato-mini试试，也可以尝试把模型换成unified_transformer-12L-cn，然后把task_type设成“chitchat”

**Comment by smallv0221** [comment]
这就看您自己数据集的质量了，如果不大的话可能效果会不如直接使用plato-mini

**Comment by AI-Mart** [comment]
了解了 谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789)





 
这就看您自己数据集的质量了，如果不大的话可能效果会不如直接使用plato-mini

**Comment by smallv0221** [comment]
不客气

**Comment by zhanghaoie** [comment]
> 了解了 谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleNLP" ***@***.***&gt;; 发送时间:&nbsp;2021年7月27日(星期二) 下午4:30 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/dialogue/unified_transformer/ 预训练模型改成plato-mini后报错 (#789) 这就看您自己数据集的质量了，如果不大的话可能效果会不如直接使用plato-mini — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗨，请问下你这边用plato-mini微调后效果怎么样啊？数据集大概是什么量级的啊
