### ISSUE TITLE
[Question]: 在Ernie-layout模型中，如何载入我自己的xfund_zh格式的数据集？

### ISSUE THREAD

**Issue by bohui-lv** [PaddlePaddle/PaddleNLP#7891]
### 请提出你的问题

如题，我正在使用model_zoo/ernie-layout/run_ner.py
我想要使用我自己的数据集来训练模型，我的数据集是xfund格式的中文数据，我在load_dataset部分要怎么处理这些数据？

**Comment by w5688414** [comment]
数据处理参考这个进行处理：

https://github.com/PaddlePaddle/PaddleNLP/blob/79cb8b6acda42c054e82c1623b3cfff260ae60e5/docs/FAQ.md?plain=1#L67

数据的格式可以查看：

https://github.com/PaddlePaddle/PaddleNLP/blob/79cb8b6acda42c054e82c1623b3cfff260ae60e5/paddlenlp/datasets/hf_datasets/xfund_zh.py#L54

**Comment by bohui-lv** [comment]
> 数据处理参考这个进行处理：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/79cb8b6acda42c054e82c1623b3cfff260ae60e5/docs/FAQ.md?plain=1#L67
> 
> 数据的格式可以查看：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/79cb8b6acda42c054e82c1623b3cfff260ae60e5/paddlenlp/datasets/hf_datasets/xfund_zh.py#L54

谢谢， 我把我的数据处理成和xfund_zh的格式一样就可以了
