### ISSUE TITLE
关于多任务学习

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#790]
Team,

有没有多任务学习的案例可以参考一下，比如，既分类，又输出情感，希望一个模型同时两个或多个任务，重用中间学习能力，避免多个模型节省线上GPU资源和维护成本。

**Comment by LangDaoAI** [comment]
有一个疑惑： 看到 https://github.com/PaddlePaddle/PALM/tree/master/examples/classification  也就是paddle palm是做多任务学习， 该repository是否已经out of date， 后面要全部移植到paddlenlp中， 还是说以后多任务的case也要集成在paddlenlp repo中并且使用paddle palm做多任务学习呢？

**Comment by ZeyuChen** [comment]
@LangDaoAI PALM当前尚未升级到paddle 2.0.
我门后续评估新增多任务学习的example，但多任务学习并不是太通用，根据实际情况调参技巧会比较高，打比赛比较使用。工业实践不一定有单业务单模型实用。

**Comment by LangDaoAI** [comment]
> @LangDaoAI PALM当前尚未升级到paddle 2.0.
> 我门后续评估新增多任务学习的example，但多任务学习并不是太通用，根据实际情况调参技巧会比较高，打比赛比较使用。工业实践不一定有单业务单模型实用。

噢， 感谢回复，后面期待example出来。
