### ISSUE TITLE
关于few shot模型中的样本不均衡性

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#791]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/few_shot/efl/data.py 中有一个ToDo，关于样本不均衡性处理， 想知道应该如何去做这样处理， 目前代码并没有这样去考虑，可以提供一些建议吗，谢谢！

![image](https://user-images.githubusercontent.com/83859417/126886987-5964b48f-82f5-4319-992e-8f6093da7370.png)

**Comment by Steffy-zxf** [comment]
你好！关于数据类别分布不均衡的问题，可以采用以下方法解决：
1）欠采样，即去除一些多数类中的样本使得正例、反例数目接近，然后再进行学习。
2）过采样，即增加一些少数类样本使得正、反例数目接近，然后再进行学习。
3）修改分类阈值，因为数据集存在类别不均衡的情况，所以直接训练分类器会使得模型在预测时更偏向于多数类，所以不再以0.5为分类阈值，而是针对少数类在模型仅有较小把握时就将样本归为少数类。
4）使用Focal loss计算损失函数值。Focal loss是一个能较好适应类别不均衡的损失函数。

以上方法仅供参考，需要结合具体数据和任务解决问题。

**Comment by LangDaoAI** [comment]
好的感谢！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tianxin1860** [comment]
此处的样本不均衡是指 `EFL` 策略2分类任务中: 正、负样本的不均衡，经实验验证: 负样本的采样数量在类别数较大的条件下对模型效果影响较大，您使用过程中仅需要对负样本采样数量 `neg_num` 这个超参数多跑几组实验，挑选最合适的 `neg_num` 即可。

**Comment by LangDaoAI** [comment]
> 此处的样本不均衡是指 `EFL` 策略2分类任务中: 正、负样本的不均衡，经实验验证: 负样本的采样数量在类别数较大的条件下对模型效果影响较大，您使用过程中仅需要对负样本采样数量 `neg_num` 这个超参数多跑几组实验，挑选最合适的 `neg_num` 即可。

是的，你说的很正确， 我的场景是14类， 然后有一半近7个类别的样本是很少的，那么在这种情况下， neg_num增大的策略是随机增大吗， 或者说这种情况下EFL依然针对这7个类别有识别能力吗， 我一方面会调整采样的策略，尽可能针对性地包含这7个类别，同时，再想想办法弥补稀疏地负样本。

**Comment by tianxin1860** [comment]
> > 此处的样本不均衡是指 `EFL` 策略2分类任务中: 正、负样本的不均衡，经实验验证: 负样本的采样数量在类别数较大的条件下对模型效果影响较大，您使用过程中仅需要对负样本采样数量 `neg_num` 这个超参数多跑几组实验，挑选最合适的 `neg_num` 即可。
> 
> 是的，你说的很正确， 我的场景是14类， 然后有一半近7个类别的样本是很少的，那么在这种情况下， neg_num增大的策略是随机增大吗， 或者说这种情况下EFL依然针对这7个类别有识别能力吗， 我一方面会调整采样的策略，尽可能针对性地包含这7个类别，同时，再想想办法弥补稀疏地负样本。

14 个类别的话，建议 `neg_num` 超参数分别选取 1, 7, 13 跑 3 组实验先明确在你的场景下 `neg_num` 对实验效果的影响以及实验效果如何，EFL 策略对所有 14 个类都具有识别能力；如果想进一步验证调整类别间样本平衡对模型性能的影响: 建议可以把样本数很少的 7 个类别训练数据多 copy 几份即可。

**Comment by LangDaoAI** [comment]
好的感谢！

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LangDaoAI** [comment]
我修改了EFL的模型代码， 在命令行加入指定的负采样类别， 显式对这些极少类做采样， 比如以下命令：

python train.py --task_name "honorcrisis" --save_dir ./checkpoints --sample_negative_classes "1|2|3|4"，

然后代码中对data.py做负采样增强如下：

![image](https://user-images.githubusercontent.com/83859417/127288075-f6c1c893-415b-432a-8bb8-1e8d4620af3e.png)

这样的话，保证每次蕴涵模板可以采样到这些少类的样本，做语言训练的增强。
