### ISSUE TITLE
什么时候考虑支持Mixtral8*7B呢？

### ISSUE THREAD

**Issue by onewaymyway** [PaddlePaddle/PaddleNLP#7926]
### 简要描述

Mixtral8*7B系列模型是当前开源的效果最好的模型，Mixtral8*7B instruct几乎可以打过chatgpt3.5，什么时候paddlenlp才能把Mixtral8*7系列的模型也支持了呢

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

huggingface:
https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
https://huggingface.co/mistralai/Mixtral-8x7B-v0.1

介绍：
https://mistral.ai/news/mixtral-of-experts/

**Comment by DesmonDay** [comment]
相关PR已经提了 https://github.com/PaddlePaddle/PaddleNLP/pull/7803/files ，但由于有其他事情暂时没有更新，后续会继续支持的。

**Comment by onewaymyway** [comment]
> 相关PR已经提了 https://github.com/PaddlePaddle/PaddleNLP/pull/7803/files ，但由于有其他事情暂时没有更新，后续会继续支持的。

赞
