### ISSUE TITLE
训练mbart模型报错 ，Logits和Label维度不匹配

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/PaddleNLP#7929]
paddlepaddle-gpu    2.5.2.post112
paddlenlp           2.7.1

报错信息：
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.   [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:288 != labels_dims[i]:256.] (at ../paddle/phi/infermeta/binary.cc:909)
 请问下怎么解决

**Comment by wawltor** [comment]
请问下，是使用自己的数据来训练的吗？
