### ISSUE TITLE
[Question]: rocketqa-para-encoder和rocketqa-query-encoder区别

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#7933]
### 请提出你的问题

rocketqa-para-encoder和rocketqa-query-encoder区别是什么？这两个分别适合在什么场景使用？

**Comment by w5688414** [comment]
一个是对query进行编码，另一个是对段落进行编码

**Comment by ZTurboX** [comment]
> 一个是对query进行编码，另一个是对段落进行编码

场景是query去匹配段落，建议用哪个呢

**Comment by w5688414** [comment]
query用：rocketqa-query-encoder
段落用：rocketqa-para-encoder
