### ISSUE TITLE
[Question]: Taskflow("document_intelligence")出现错误

### ISSUE THREAD

**Issue by lai-serena** [PaddlePaddle/PaddleNLP#7940]
### 请提出你的问题

```from pprint import pprint
from paddlenlp import Taskflow

if __name__ == '__main__':
    docprompt = Taskflow("document_intelligence")
    pprint(docprompt([{"doc": "images_1.png", "prompt": ["给文档按标号分段"]}]))
```
运行以上代码出现如下错误：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/44218061/a3f12de1-7bab-46f7-ac4b-29da86afe994)

环境：
ubuntu
cuda 11.2
paddlepaddle-gpu       2.6.0.post112
paddleocr              2.7.0.3
paddlenlp              2.7.2

**Comment by wawltor** [comment]
看报错信息可能是paddle版本安装有问题，可以按照下面的命令执行后并截图给我们了解下信息 

```python
import paddle 
paddle.utils.run_check()
```

**Comment by Lem0nTe4** [comment]
同样的问题，之前能跑通的，现在跑不通了
![微信截图_20240222161241](https://github.com/PaddlePaddle/PaddleNLP/assets/96911311/f14599a9-92a5-44af-8bd3-dac78dbdc3ed)

**Comment by jidechao** [comment]
@lai-serena 问题解决了吗？我也遇到了类似的问题

**Comment by Lem0nTe4** [comment]
> @lai-serena 问题解决了吗？我也遇到了类似的问题

退回Paddle2.5.0就行，参考
https://github.com/PaddlePaddle/PaddleNLP/issues/8008

**Comment by lai-serena** [comment]
paddle 2.6版本应该是不支持的，退回paddle 2.5版本
