### ISSUE TITLE
[Question]: 训练中途报错中断后，重新训练如何在已训练的checkpoint上继续训练而不是重新开始训练

### ISSUE THREAD

**Issue by Matter-Charles** [PaddlePaddle/PaddleNLP#7952]
### 请提出你的问题

训练中途报错中断后，重新跑finetune.py代码发现模型重新训练，从checkpiont-100开始，是否有参数可以选择从之前训练过的某个checkpoint开始继续训练？

**Comment by gongel** [comment]
重跑就可以了哈，自动继续训练。

**Comment by Matter-Charles** [comment]
我在使用的过程中，中断后重新跑finetune.py代码是没有出现继续训练的情况，每一次都是重新训练，请问是环境的原因吗？能否提供一下能继续训练的环境版本？--load_best_model_at_end  True这个参数也有写上的

**Comment by w5688414** [comment]
可以类似这样，指定自己的checkpoint。

https://github.com/PaddlePaddle/PaddleNLP/blob/ac117a108de2d777fe77d542c732dc5a83889b5d/applications/information_extraction/document/finetune.py#L141
