### ISSUE TITLE
[Question]: text_summarization测试官方提供样例结果很差

### ISSUE THREAD

**Issue by bamboolaile** [PaddlePaddle/PaddleNLP#7954]
### 请提出你的问题

同样的配置环境，在别人电脑就可以，但是在自己的电脑的效果就很差
python=3.8.18
paddle=2.5.0rc1
paddlenlp=2.6.1

**Comment by wawltor** [comment]
电脑的配置硬件有区别吗？

**Comment by bamboolaile** [comment]
电脑配置应该是有区别的，不过后来修改了其他版本后可以使用了，谢谢呀发自我的手机-------- 原始邮件 --------发件人： wawltor ***@***.***>日期： 2024年2月5日周一 晚上9:42收件人： PaddlePaddle/PaddleNLP ***@***.***>抄送： bamboolaile ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/PaddleNLP] [Question]: text_summarization测试官方提供样例结果很差 (Issue #7954)
电脑的配置硬件有区别吗？
