### ISSUE TITLE
新功能需求：nlp能否实现提取整篇文档中序号项目的文字

### ISSUE THREAD

**Issue by tammy-na** [PaddlePaddle/PaddleNLP#7956]
### Feature request

nlp能否实现在整篇文档中提取诸如以序号开头的段落1、***********。2、**************。一、**************。二、***************。（1）*******************。（2）*****************。1）************。2）****************。等等

### Motivation

在信息提取的过程中，uie对距离较远的关系实体的提取准确度不高，想要先对整篇文档做分割，并且我想要做信息提取的部分就是文档中序号项的部分，序号项的格式不局限于一种格式1）1、（1）并且序号的大小也不限制，可能为（三十一）（五十一）等。有没有更好的办法提取出整篇文本中序号项的部分呢？

### Your contribution

未找出能够实现这项需求的相关方法

**Comment by wawltor** [comment]
UIE本身模型的特性对较远的关系实体的抽取会存在较多的问题，这个是UIE本身模型的特性有关系；对于这类模型可以尝试下使用PaddleNLP 大模型相关的问题来进行解决，现有的大模型对长文本的能力相对较强，zero-shot或者few-shot后看起来是一个更好的解决方案。

**Comment by tammy-na** [comment]
> UIE本身模型的特性对较远的关系实体的抽取会存在较多的问题，这个是UIE本身模型的特性有关系；对于这类模型可以尝试下使用PaddleNLP 大模型相关的问题来进行解决，现有的大模型对长文本的能力相对较强，zero-shot或者few-shot后看起来是一个更好的解决方案。

现有的大模型对tokens的字数也是有限制的，不适用我的应用场景。

**Comment by tammy-na** [comment]
> > UIE本身模型的特性对较远的关系实体的抽取会存在较多的问题，这个是UIE本身模型的特性有关系；对于这类模型可以尝试下使用PaddleNLP 大模型相关的问题来进行解决，现有的大模型对长文本的能力相对较强，zero-shot或者few-shot后看起来是一个更好的解决方案。
> 
> 现有的大模型对tokens的字数也是有限制的，不适用我的应用场景。
对于PaddleNLP 大模型的微调方面，数据集的制作这部分很遗憾我没有找到对应的方案教程，官方文档中是直接提供了网上通用的数据集样例，我无法制作适合我的应用场景的数据集。

**Comment by w5688414** [comment]
把您的场景的数据构造成src，tgt这种pair对即可
