### ISSUE TITLE
[Question]: 标注问题

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#7959]
### 请提出你的问题
UIE 做实体识别标注问题
标注甲方的公司需要把甲方：标进去？同理乙方也需要？
甲方 ：XXXXX有限公司
已方 ：XXXXX有限公司

**Comment by wawltor** [comment]
请具体描述下是哪个模型的标注问题以及具体的使用场景。

**Comment by cqray1990** [comment]
> 请具体描述下是哪个模型的标注问题以及具体的使用场景。

@wawltor UIE的实体标注

**Comment by w5688414** [comment]
只需要标注需要识别的实体即可
