### ISSUE TITLE
[Question]: 使用QA问答时，无法查询es向量库。search_phase_execution_exception

### ISSUE THREAD

**Issue by morego123** [PaddlePaddle/PaddleNLP#7964]
### 请提出你的问题

使用问答时，无法查询es向量库。
教程：【https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/question-answering】
报错： elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'runtime error')

**Comment by w5688414** [comment]
看看后台的日志是什么错误信息呢？

**Comment by w5688414** [comment]
看是不是这个问题： https://github.com/PaddlePaddle/PaddleNLP/issues/8247
