### ISSUE TITLE
[Bug]: sentence transformers推理结果不一致

### ISSUE THREAD

**Issue by guishilike** [PaddlePaddle/PaddleNLP#7970]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.6
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用sentence_transformers每次推理的结果不一致
```

### 稳定复现步骤 & 代码

![1707182116564](https://github.com/PaddlePaddle/PaddleNLP/assets/51023060/82219d89-0aa9-410b-9876-3e30314345db)
![1707182239832](https://github.com/PaddlePaddle/PaddleNLP/assets/51023060/d5694b75-9cb4-4cba-b972-e54597e8e29f)

**Comment by w5688414** [comment]
加一个model.eval()

 示例如下：

```
pretrained_model = AutoModel.from_pretrained("ernie-3.0-medium-zh")
model = SentenceTransformer(pretrained_model)
model.eval()

```

**Comment by w5688414** [comment]
请问怎么复现呢？

**Comment by w5688414** [comment]
请确认一 下这个lineear层是否初始化。 https://github.com/PaddlePaddle/PaddleNLP/blob/b312959a77880acdcd3adb7e4ff636738f4e19d3/examples/text_matching/sentence_transformers/model.py#L25C14-L25C24

**Comment by guishilike** [comment]
![1707201012593](https://github.com/PaddlePaddle/PaddleNLP/assets/51023060/414377ec-c36d-4eb1-b61a-642fd1c6f6e7)是这个吗  代码和仓库的一样

**Comment by guishilike** [comment]
这个必须得自己训练一个是吗 并不能直接使用吗

**Comment by guishilike** [comment]
我能再问一下，这个训练和推理需要是一致的吗@w5688414 
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51023060/7db63bd9-a39e-44af-8f56-539d881b7e7c)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/51023060/ef5fd3f8-e7c5-4e0c-82eb-838c35852a50)

**Comment by w5688414** [comment]
这个没有明确的规定，都行。

**Comment by guishilike** [comment]
如果直接用余弦相似度的话 似乎就不需要那个classifier
