### ISSUE TITLE
【快速上手ERNIE 3.0】对话意图识别实战中环境包版本问题

### ISSUE THREAD

**Issue by huluhulu595** [PaddlePaddle/PaddleNLP#7979]
### 请提出你的问题

官方文档中没有说明跑通这个项目的PaddlePaddle、paddlenlp、protobuf等环境包的具体版本，按顺序跑代码的时候总是报错比如AttributeError: 'Parameter' object has no attribute '_bump_inplace_version'
AttributeError: 'DataLoader' object has no attribute 'prefetch_factor'
TypeError: Descriptors cannot not be created directly. If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. If you cannot immediately regenerate your protos, some other possible work
目前实验的版本为!pip install --upgrade paddlenlp==2.3.3
!pip install protobuf==3.19.0
在【使用PaddleNLP一键加载预训练模型】这一模块报错AttributeError: 'Parameter' object has no attribute '_bump_inplace_version'
希望能告知该项目具体运行环境包的版本号

**Comment by huluhulu595** [comment]
AttributeError: 'Parameter' object has no attribute '_bump_inplace_version'

**Comment by huluhulu595** [comment]
!pip install --upgrade paddlenlp==2.4.4
!pip install pyzmq==18.1.1

**Comment by huluhulu595** [comment]
AttributeError: 'Parameter' object has no attribute '_bump_inplace_version'

**Comment by huluhulu595** [comment]
使用以上版本在【使用PaddleNLP一键加载预训练模型】报错AttributeError: 'Parameter' object has no attribute '_bump_inplace_version'

**Comment by gongel** [comment]
你好，可以参考星河社区的教程来运行：https://aistudio.baidu.com/projectdetail/2017189
或者查看当时发布该功能的时间点，找到PaddlePaddle和PaddleNLP对应的版本。
