### ISSUE TITLE
I need ideas from your side

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [PaddlePaddle/PaddleNLP#7981]
### 请提出你的问题

Hi Sir,
I am using paddlenlp document intelligence model for image vqa. Please give ideas for these below 3 queries?

1. Model getting two much of memory usage. How to use optimize this? 
2. How to send multiple question or how to process multiple question at a time?, [Ex, I will send 5 questions for a image, i need process parallel and get output with less memory consumption] Its there any way to solve this?
3. How to load paddlenlp models from my local folder?

**Comment by gongel** [comment]
Thank you for using it. We no longer maintain this feature.
