### ISSUE TITLE
[Bug]: generation sample_d2s 没有正确实现 temperature 功能

### ISSUE THREAD

**Issue by sserdoubleh** [PaddlePaddle/PaddleNLP#7984]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.6.0
- paddlenlp: 2.7.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
需要对 logits 除以 temperature，再进行 top k / top p sampling
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/generation/utils.py#L1395-L1406

**Comment by gongel** [comment]
收到，我们尽快修改。
