### ISSUE TITLE
[Question]: 为什么在使用开箱即用的情感分析时，提示没有uie-senta-base模型

### ISSUE THREAD

**Issue by peiqijiayou** [PaddlePaddle/PaddleNLP#7995]
### 请提出你的问题

 为什么在使用开箱即用的情感分析时，提示没有uie-senta-base模型
 AssertionError: The models name: uie-senta-base is not in task:[sentiment_analysis]
 然后在/.paddlenlp/taskflow目录下也没有发现这个模型
 就是下面这个代码调用时
`# 使用UIE模型进行情感分析，具有较强的样本迁移能力
# 1. 语句级情感分析
>>> schema = ['情感倾向[正向，负向]']
>>> senta = Taskflow("sentiment_analysis", model="uie-senta-base", schema=schema)
>>> senta('蛋糕味道不错，店家服务也很好')
#[{'情感倾向[正向,负向]': [{'text': '正向', 'probability': 0.996646058824652}]}]`

**Comment by wawltor** [comment]
paddlenlp是什么版本？

**Comment by peiqijiayou** [comment]
已经解决了，paddlepaddle版本改为2.6.0，然后paddlenlp最新版本就可以了
