### ISSUE TITLE
检索pipeline 增加BAAI/bge-m3,ranker模型增加 bge-reranker模型

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#7998]
### Feature request

检索pipeline 增加BAAI/bge-m3,ranker模型增加 bge-reranker模型

### Motivation

paddlenlp的检索好久没更新了,m3支持8000token的长度,且reranker模型效果应该会有所提升

### Your contribution

None

**Comment by gongel** [comment]
你好，欢迎提PR共建哈。

**Comment by seetimee** [comment]
请问torch转换paddle权重的方法有哪些呀

**Comment by michaelowenliu** [comment]
> 请问torch转换paddle权重的方法有哪些呀

可以参考https://github.com/PaddlePaddle/PaConvert

**Comment by w5688414** [comment]
#### PyTorch向量检索模型权重转换
PaddleNLP-Pipelines 提供了可自动将 PyTorch 相关的权重转化为 Paddle 权重的接口，以BAAI/bge-m3为例，代码如下：

```python
from paddlenlp.transformers import AutoModel, AutoTokenizer
model = AutoModel.from_pretrained("BAAI/bge-m3", from_hf_hub=True, convert_from_torch=True)
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-m3')

model.save_pretrained("BAAI/bge-m3-pd")
tokenizer.save_pretrained("BAAI/bge-m3-pd")
```

然后在这里像这样注册一下即可使用。

https://github.com/PaddlePaddle/PaddleNLP/blob/b6dcb4e19efd85911b13a0fc587fef33578cfebf/paddlenlp/taskflow/taskflow.py#L680

**Comment by seetimee** [comment]
哇,感谢感谢

**Comment by MaxHouxu** [comment]
ranker如何添加模型

**Comment by w5688414** [comment]
ranker模型的思路是一样的，前提是有对应的base模型的结构
