### ISSUE TITLE
什么时候增加deberta意图识别模型呢

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#7999]
### 简要描述

主要是用于分类任务

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

https://github.com/microsoft/DeBERTa

**Comment by wawltor** [comment]
暂且没有计划增加deberta识别模型，可以尝试一些其他模型。

**Comment by seetimee** [comment]
好的

**Comment by seetimee** [comment]
谢谢
