### ISSUE TITLE
Bert分词无法识别特殊标记[MASK]等字符。

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#801]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.6，PaddlePaddle2.1.1
2）系统环境：Windows，python3.7
- 复现信息：如为报错，请给出复现环境、复现步骤

```python
In [1]: from paddlenlp.transformers.bert.tokenizer import BertTokenizer
In [2]: tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")
[2021-07-27 06:09:39,448] [    INFO] - Found \.paddlenlp\models\bert-base-chinese\bert-base-chinese-vocab.txt
In [3]: text = "今天[MASK]非常好!"
In [4]: tokenizer(text)
Out[4]:
{'input_ids': [101, 791, 1921, 138, 100, 140, 7478, 2382, 1962, 106, 102],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
In [5]: tokenizer.tokenize(text)
Out[5]: ['今', '天', '[', '[UNK]', ']', '非', '常', '好', '!']

```
其中[MASK]特殊标记被拆成了 '[', '[UNK]', ']'，我想要的结果是['今', '天', '[MASK]', '非', '常', '好', '!']。
Huggingface仓库中的tokenizer分词正常。

**Comment by libertatis** [comment]
刚才试了一下，`PaddleNLP` 的 `tokenizer` 在对一个字符串分词的时候，并没有把字符串中的特殊标记 `['[UNK]', '[PAD]', '[SEP]', '[MASK]', '[CLS]']` 当作一个整体看待，而是都分成了 `'[', '[UNK]', ']'`。感觉这样做不太合理~

**Comment by JunnYu** [comment]
我看huggingface实现的时候，他们好像是用句子中的特殊标记分割句子。
举个例子：
（1）`"今天[MASK]非常好!"` -> chunk_list = ["今天","非常好！"]
（2）然后分别对chunk_list中每个句子再进行tokenizer：
`“今天”->[“今”，“天”]`
`"非常好！"->["非"，“常”，“好”，“！”]`
（3）最后组合：
`[“今”，“天”] + ["[MASK]"] + ["非"，“常”，“好”，“！”]`

**Comment by smallv0221** [comment]
Our tokenizer design is different from HF. It is more like google's Bert tokenizer. You can add special tokens like `[MASK]` after using `tokenizer.tokenize()`.
