### ISSUE TITLE
FAQ给出的官方例子跑出来有问题

### ISSUE THREAD

**Issue by senyousanmu** [PaddlePaddle/PaddleNLP#8010]
### 请提出你的问题

我在跑FAQ中的dense_faq_example.py，在创建模型阶段（第一次跑为创建模型），没有问题，但是在第二次跑（使用模型阶段）就出现问题。
![c6c24fca2f0c31f0ef0c20097a0d765](https://github.com/PaddlePaddle/PaddleNLP/assets/33517019/ce383949-8a54-4495-a81a-e3a73a38ad1b)

**Comment by senyousanmu** [comment]
在已经生成faiss相关文件后，使用加载就一直报这个错误。希望得到帮助。
document_store = FAISSDocumentStore.load(args.index_name)

**Comment by gongel** [comment]
你好，我们排查看看哈。

**Comment by marshalcn** [comment]
> 你好，我们排查看看哈。

你好，排查的怎么样了，我也遇到这个问题了，第二次运行的时候报一样的错

**Comment by marshalcn** [comment]
你好，排查的怎么样了

**Comment by marshalcn** [comment]
> 你好，我们排查看看哈。

你好，排查的怎么样了

**Comment by w5688414** [comment]
请问您用的是pipelines哪个版本？

**Comment by marshalcn** [comment]
> 请问您用的是pipelines哪个版本？
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/17228475/f216604e-ee12-41f1-b069-9c33f177300c)

**Comment by marshalcn** [comment]
> 请问您用的是pipelines哪个版本？

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/17228475/56282da5-1038-4550-9e3f-a2a1366d6921)

**Comment by w5688414** [comment]
安装最新的pipelines试一下：

```
cd PaddleNLP/pipelines
pip install -e .
export CUDA_VISIBLE_DEVICES=0
python examples/FAQ/dense_faq_example.py --device gpu
```

<img width="1108" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/12107462/8b511542-5534-4957-aed0-d3d879bbcc4e">

或者删除faiss db重新进行代码：

```
rm -rf faiss_document_store.db
export CUDA_VISIBLE_DEVICES=0
python examples/FAQ/dense_faq_example.py --device gpu
```

**Comment by marshalcn** [comment]
> 安装最新的pipelines试一下：
> 
> ```
> cd PaddleNLP/pipelines
> pip install -e .
> export CUDA_VISIBLE_DEVICES=0
> python examples/FAQ/dense_faq_example.py --device gpu
> ```
> 
> <img alt="image" width="1108" src="https://private-user-images.githubusercontent.com/12107462/313052497-8b511542-5534-4957-aed0-d3d879bbcc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzE2NjksIm5iZiI6MTcxMDQ3MTM2OSwicGF0aCI6Ii8xMjEwNzQ2Mi8zMTMwNTI0OTctOGI1MTE1NDItNTUzNC00OTU3LWFlZDAtZDNkODc5YmJjYzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAyNTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYTQwOWU2MTc1ODI2M2Q5OWRlNWRjMmMyN2VmZjQxMzc4YzhhNDhjNGM1MzM3YzlhMjNiMWQ3NjYwNWQ0YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ALBQDGfsEqIkqgBUmuRjPG6bl1HlPOfZV3XpDaSX1mQ">
> 或者删除faiss db重新进行代码：
> 
> ```
> rm -rf faiss_document_store.db
> export CUDA_VISIBLE_DEVICES=0
> python examples/FAQ/dense_faq_example.py --device gpu
> ```

你可能没太明白，问题是创建模型的时候可以运行成功，这时候自动构建的faiss_document_store.db 第二次运行的时候这个文件存在的情况下运行就报上面的错

**Comment by marshalcn** [comment]
> 安装最新的pipelines试一下：
> 
> ```
> cd PaddleNLP/pipelines
> pip install -e .
> export CUDA_VISIBLE_DEVICES=0
> python examples/FAQ/dense_faq_example.py --device gpu
> ```
> 
> <img alt="image" width="1108" src="https://private-user-images.githubusercontent.com/12107462/313052497-8b511542-5534-4957-aed0-d3d879bbcc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzI2NTcsIm5iZiI6MTcxMDQ3MjM1NywicGF0aCI6Ii8xMjEwNzQ2Mi8zMTMwNTI0OTctOGI1MTE1NDItNTUzNC00OTU3LWFlZDAtZDNkODc5YmJjYzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAzMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDc2NDc1NDNhNTIzZmM3M2VmZjhlOTE5MjM0ZWVmMTljNWI2NGQ4OGI2ZDgzZmRhNzFhZDE3MGRiNmNmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbOxKbqxq79wRqdQMldGuzjuFW8x9R6zeHuDqQvCpts">
> 或者删除faiss db重新进行代码：
> 
> ```
> rm -rf faiss_document_store.db
> export CUDA_VISIBLE_DEVICES=0
> python examples/FAQ/dense_faq_example.py --device gpu
> ```

你尝试第二次跑一下，进入到登录模型阶段再看下有问题没

**Comment by songjunming13** [comment]
<img width="1080" alt="问题" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/1fb2bee6-f1ac-4647-ac3d-4903a15db754">
我也出现这个问题，这个问题是 1、首先再创建模型的时候会生成一个.db文件（如图片画线1处）这是没有问题的2、报错是  再已经产生这个.db
文件以后才出现的，也就是再调用加载模型的时候出现的  ，这个地方出现了问题。

**Comment by w5688414** [comment]
> > 安装最新的pipelines试一下：
> > ```
> > cd PaddleNLP/pipelines
> > pip install -e .
> > export CUDA_VISIBLE_DEVICES=0
> > python examples/FAQ/dense_faq_example.py --device gpu
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1108" src="https://private-user-images.githubusercontent.com/12107462/313052497-8b511542-5534-4957-aed0-d3d879bbcc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzI2NTcsIm5iZiI6MTcxMDQ3MjM1NywicGF0aCI6Ii8xMjEwNzQ2Mi8zMTMwNTI0OTctOGI1MTE1NDItNTUzNC00OTU3LWFlZDAtZDNkODc5YmJjYzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAzMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMDc2NDc1NDNhNTIzZmM3M2VmZjhlOTE5MjM0ZWVmMTljNWI2NGQ4OGI2ZDgzZmRhNzFhZDE3MGRiNmNmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbOxKbqxq79wRqdQMldGuzjuFW8x9R6zeHuDqQvCpts">
> > 或者删除faiss db重新进行代码：
> > ```
> > rm -rf faiss_document_store.db
> > export CUDA_VISIBLE_DEVICES=0
> > python examples/FAQ/dense_faq_example.py --device gpu
> > ```
> 
> 你尝试第二次跑一下，进入到登录模型阶段再看下有问题没

没问题，我跑了好多次（建议拉一下最新的代码）
