### ISSUE TITLE
[Question]: 使用PaddleNLP Taskflow 时不断出现 kernel crashes

### ISSUE THREAD

**Issue by chentitus** [PaddlePaddle/PaddleNLP#8012]
### 请提出你的问题

我使用PaddleNLP Taskflow（例如 word_segmentation 或是 sentiment_analysis）的时候，一直出现 Kernel crashed 的问题，请问有解决方法吗？

我是在Visual Studio Code 上使用Jupyter。
电脑作业系统是 Apple M3 Pro Sonoma 14.3.1。 
Python 版本是3.9.6。
VS Code 版本是1.86.2。
paddlepaddle 2.6.0。
paddlelp 2.5.2。
paddlefsl 1.1.0。
paddle2onnx 1.0.9。

Selected Jupyter core packages:
IPython          : 8.18.1
ipykernel        : 6.29.2
ipywidgets       : 8.1.2
jupyter_client   : 8.6.0
jupyter_core     : 5.7.1
jupyter_server   : 2.12.5
jupyterlab       : 4.1.2
nbclient         : 0.9.0
nbconvert        : 7.16.1
nbformat         : 5.9.2
notebook         : 7.1.0
qtconsole        : 5.5.1
traitlets        : 5.14.1

我的 Python code:
import paddlenlp
from paddlenlp import Taskow
schema = ['[正向，负向]']
senta = Taskflow("sentiment_analysis", model="uie-senta-base", schema=schema)
texts = ["美众院议长佩洛西访台"]
a = senta(texts)

Jupyter log:
13:17:41.542 [info] Handle Execution of Cells 7 for ~/HiTitus/paddleNLP.ipynb
13:17:41.548 [info] Kernel acknowledged execution of cell 7 @ 1708665461548
13:17:46.878 [info] End cell 7 execution after 5.33s, completed @ 1708665466878, started @ 1708665461548
13:17:49.236 [info] Handle Execution of Cells 8 for ~/HiTitus/paddleNLP.ipynb
13:17:49.242 [info] Kernel acknowledged execution of cell 8 @ 1708665469242
13:17:49.244 [info] End cell 8 execution after 0.002s, completed @ 1708665469244, started @ 1708665469242
13:18:06.028 [info] Handle Execution of Cells 9 for ~/HiTitus/paddleNLP.ipynb
13:18:06.034 [info] Kernel acknowledged execution of cell 9 @ 1708665486034
13:18:08.122 [warn] StdErr from Kernel Process E0223 13:18:07.647910 3801553984 analysis_config.cc:653] Please compile with MKLDNN first to use MKLDNN
13:18:08.250 [error] Disposing session as kernel process died ExitCode: undefined, Reason: E0223 13:18:07.647910 3801553984 analysis_config.cc:653] Please compile with MKLDNN first to use MKLDNN

13:18:08.250 [info] Dispose Kernel process 5405.
13:18:08.265 [info] End cell 9 execution after -1708665486.034s, completed @ undefined, started @ 1708665486034

**Comment by gongel** [comment]
建议切换Linux机器，或者在星河社区运行：https://aistudio.baidu.com/index

**Comment by chentitus** [comment]
> 建议切换Linux机器，或者在星河社区运行：https://aistudio.baidu.com/index

但是我沒有中國的手機號碼，不能註冊百度
