### ISSUE TITLE
[Question]: UIE标注问题

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#8015]
### 请提出你的问题
UIE 做实体识别标注问题，需要标注甲方和乙方两个实体
标注甲方的公司需要把甲方：标进去？同理乙方也需要？
甲方 ：XXXXX有限公司
乙方 ：XXXXX有限公司

**Comment by gongel** [comment]
你好，只要把甲方对应的公司标注进去就可以了，与甲方这实体标签对应即可。

**Comment by cqray1990** [comment]
> 你好，只要把甲方对应的公司标注进去就可以了，与甲方这实体标签对应即可。
前面的“甲方：”字符不需要对吧
