### ISSUE TITLE
将label studio导出的 JSON 数据文件格式转换成doccano导出的数据文件过程中报错IndexError: list index out of range

### ISSUE THREAD

**Issue by Vivi529** [PaddlePaddle/PaddleNLP#8016]
按照官方文档的代码转换数据文件过程中出现以下报错：
Traceback (most recent call last):
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 111, in <module>
    do_convert(args)
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 80, in do_convert
    raise ValueError("Please input the correct path of label studio file.")
ValueError: Please input the correct path of label studio file.

(paddle) D:\AAApaper\online review\uie>python labelstudio2doccano.py --labelstudio_file label-studio.json
Traceback (most recent call last):
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 111, in <module>
    do_convert(args)
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 85, in do_convert
    results = convert(dataset, args.task_type)
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 61, in convert
    item, label_id, relation_id = append_attrs(data, item, label_id, relation_id)
  File "D:\AAApaper\online review\uie\labelstudio2doccano.py", line 45, in append_attrs
    "type": anno["labels"][0],
IndexError: list index out of range
 line 45："type": anno["labels"][0],
【来自 for anno in data["annotations"][0]["result"]:
        if anno["type"] == "relation":
            relation_id += 1
            item["relations"].append(
                {
                    "id": relation_id,
                    "from_id": mapp[anno["from_id"]],
                    "to_id": mapp[anno["to_id"]],
                    "type": anno["labels"][0],
                }
            )】
检查labelstudio.json文件，格式如{"id":1762,"annotations":[{"id":1144,"completed_by":1,"result":[{"value":{"start":8,"end":15,"text":"service","labels":["评价维度##正向"]},"id":"5Jo38I_i7z","from_name":"label","to_name":"text","type":"labels","origin":"manual"},{"value":{"start":0,"end":7,"text":"awesome","labels":["观点词"]},"id":"fTwA1Ck1_a","from_name":"label","to_name":"text","type":"labels","origin":"manual"},{"from_id":"5Jo38I_i7z","to_id":"fTwA1Ck1_a","type":"relation","direction":"right","labels":[]}],"was_cancelled":false,"ground_truth":false,"created_at":"2024-02-20T13:27:33.969374Z","updated_at":"2024-02-20T13:27:33.969374Z","lead_time":11.765,"prediction":{},"result_count":0,"task":1762,"parent_prediction":null,"parent_annotation":null}],"file_upload":"44821eb2-label3_cleaned.txt","drafts":[],"predictions":[],"data":{"text":"awesome service all round made our stay very enjoyable."},"meta":{},"created_at":"2024-02-20T12:04:10.045326Z","updated_at":"2024-02-20T13:27:34.052100Z","inner_id":685,"total_annotations":1,"cancelled_annotations":0,"total_predictions":0,"comment_count":0,"unresolved_comment_count":0,"last_comment_updated_at":null,"project":3,"updated_by":1,"comment_authors":[]}

**Comment by youngsasa2021** [comment]
看一下在标注的时候每个句子是不是都有label，查看数据集中是否有"labels":[]的情况
