### ISSUE TITLE
[Question]: simcse in batch negative

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#8019]
### 请提出你的问题

用simcse in batch negative，通过问题，召回问题相关文本块时，数据中存在一个文本块对应多个问题，造成一个batch内出现多个问题对应相同文本块，从而不同问题的相同文本块会认为是负例，但是虽然问题不同，但相同文本块还是正例。那么如何保证一个batch这种数据不出现呢

**Comment by w5688414** [comment]
这是概率问题，如果数据量比较小，建议使用hard negatives训练，因为这个问题会很明显。
