### ISSUE TITLE
[Bug]: 无法支持带有variant的torch模型自动转换

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/PaddleNLP#8026]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.6.0
- paddlenlp: develop
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
下面都判断了 "model-", 如果是 model.fp16-00001-00005.safetensors 就不支持转换了
```

### 稳定复现步骤 & 代码

![eab5131c5333f106d9cbdb3172199d5e](https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/5da3fb59-03e6-4b53-9a55-a3d821bd0105)
![cc6bc327a42ec45019e7469c1ddc330c](https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/da3deae5-b55d-4415-a99f-cb682984c70b)
<img width="403" alt="a735cc653fdd298fe5af6cbc5aa00ddb" src="https://github.com/PaddlePaddle/PaddleNLP/assets/50394665/fb76e048-c702-4376-a7a6-390e678b2b83">

**Comment by w5688414** [comment]
目前没有开发的计划，欢迎开发者贡献
