### ISSUE TITLE
[Bug]: paddlenlp 版本不兼容，api没修改

### ISSUE THREAD

**Issue by godlockin** [PaddlePaddle/PaddleNLP#8029]
### 软件环境

```Markdown
paddle2onnx              1.1.0
paddlefsl                1.1.0
paddlenlp                2.3.1
paddlepaddle             2.6.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
pip install paddlepaddle paddlenlp

运行python环境 `from paddlenlp import Taskflow` 即刻复现

有pr把 'paddle.fluid' 改成了 'paddle.base'，但是调用的地方没改
```

### 稳定复现步骤 & 代码

>>> from paddlenlp import Taskflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/__init__.py", line 24, in <module>
    from . import data
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/data/data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/transformers/__init__.py", line 15, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/transformers/model_utils.py", line 31, in <module>
    from .generation_utils import GenerationMixin
  File "/home/algo/.conda/envs/research/lib/python3.10/site-packages/paddlenlp/transformers/generation_utils.py", line 23, in <module>
    from paddle.fluid.data_feeder import convert_dtype
ModuleNotFoundError: No module named 'paddle.fluid'

**Comment by ZHUI** [comment]
是的，需要升级paddlenlp，可以安装 paddlenlp 2.7.2 版本

**Comment by godlockin** [comment]
直接pip源里安装的版本有点老，是否考虑更新一下

**Comment by ZHUI** [comment]
https://pypi.org/project/paddlenlp/#history 

最新的是 2.7.2，你用的是什么源呢？

**Comment by godlockin** [comment]
我直接这样装的，应该是ubuntu的默认源
```bash
pip install --upgrade pip
pip install paddlepaddle paddlenlp
```

**Comment by YanzhenMa** [comment]
使用了下边两命令都没有讲paddlenlp的版本升级到2.7.2
pip install --upgrade paddlenlp
或者
pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html

如果使用pip install paddlenlp==2.7.2安装的话会报错：
ERROR: Could not find a version that satisfies the requirement tool-helpers (from paddlenlp) (from versions: none)
ERROR: No matching distribution found for tool-helpers

**Comment by ZHUI** [comment]
你是什么 python 版本，什么机器平台？
这个包的话，不跑预训练是不需要的。需要安装的话，可以考虑自己编译安装，clone这个 https://github.com/ZHUI/helpers

使用下面命令编译包，然后自己安装。

pip wheel ./ --no-deps -w wheelhouse/

**Comment by YanzhenMa** [comment]
感谢您的答复
我Python版本是3.10.11，win11 ，3080Ti
使用ddp =TaskfLow("dependencyparsing"）时报错了
报错有两种：第一种是
from paddle.fluid.data_feeder import convert_dtype
ModuleNotFoundError: No module named 'paddle.fluid'
第二种是提示更新LAC（即时在我已经执行了更新命令，还是一样的报错）


可口
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 中午11:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Bug]: paddlenlp 版本不兼容，api没修改 (Issue #8029)





 
你是什么 python 版本，什么机器平台？
 这个包的话，不跑预训练是不需要的。需要安装的话，可以考虑自己编译安装，clone这个 https://github.com/ZHUI/helpers
 
使用下面命令编译包，然后自己安装。
 
pip wheel ./ --no-deps -w wheelhouse/

**Comment by YanzhenMa** [comment]
我Python版本是3.10.11，win11 ，3080Ti
使用ddp =TaskfLow("dependencyparsing"）时报错了
报错有两种：第一种是
from paddle.fluid.data_feeder import convert_dtype
ModuleNotFoundError: No module named 'paddle.fluid'
第二种是提示更新LAC（即时在我已经执行了更新命令，还是一样的报错）

**Comment by ZHUI** [comment]
嗷，这个包没有win的版本，可以不装。这个的话，你看看paddle的包，需要2.6.0
```python
from paddle.fluid.data_feeder import convert_dtype
ModuleNotFoundError: No module named 'paddle.fluid'
```

**Comment by YanzhenMa** [comment]
pip show paddlepaddle-gpu
Name: paddlepaddle-gpu
Version: 2.6.0
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/37795185/7ff3334c-b293-451e-ad7a-f50e8463268e)

**Comment by w5688414** [comment]
fluid的API在2.6.0版本移除了，可以降低到2.5.2版本试试
