### ISSUE TITLE
[Question]: 使用ernie-layout训练中文模型，没有用--use_segment_box，训练出来的模型预测结果总是少最后一个字

### ISSUE THREAD

**Issue by bohui-lv** [PaddlePaddle/PaddleNLP#8032]
### 请提出你的问题

如题，比如预测的结果中有一个QUESTION，应该是“姓名”，但是实际的结果只有“姓”这一个字

另外，由于使用PPOCR没有办法控制颗粒度，没有办法满足标注，我使用的是另一个OCR工具，而且是每个字都有一个box

**Comment by w5688414** [comment]
您好，我不确定是哪里的问题，您可以先debug一下，或者试试文档里面推荐的参数和配置训练一下。
