### ISSUE TITLE
[Question]: 基于检索的文本分类方法如何实现C++ 推理

### ISSUE THREAD

**Issue by huangtao2999** [PaddlePaddle/PaddleNLP#8039]
### 请提出你的问题

我根据https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.7/applications/text_classification/multi_class/retrieval_based这个地址实现了python版本的推理，但是c++版本如何实现推理，文档中没有相关示例demo

**Comment by w5688414** [comment]
可以使用Fastdeploy，参考文档：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/text/ernie-3.0/cpp
