### ISSUE TITLE
[Question]: AutoTokenizer.from_pretrained()方法中use_fast参数True和False影响tokenizer编码结果

### ISSUE THREAD

**Issue by rjhuang09** [PaddlePaddle/PaddleNLP#8041]
### 请提出你的问题

AutoTokenizer.from_pretrained("ernie-2.0-base-en", use_fast=True)中，使用fasttokenizer与不使用fasttokenizer产生的结果具有一些差异，这种差异在推理过程中会被放大，导致分类任务出现不同的结果

**Comment by w5688414** [comment]
您好，因为人力有限，fasttokenizer暂停维护了，欢迎开发者积极贡献
