### ISSUE TITLE
[Question]: 为什么Milvus会连接不上？pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on

### ISSUE THREAD

**Issue by LLLiHaotian** [PaddlePaddle/PaddleNLP#8046]
### 请提出你的问题

您好，我注意到上一位朋友在aistudio中运行连接不上，在本地可以运行。
我的运行环境是在vscode上的linux服务器的python环境，请问为什么会产生报错，应该如何连接呢？
（我的工作目标是导入向量到Milvus进行向量相似度的快速计算）

![微信图片_20240303101443](https://github.com/PaddlePaddle/PaddleNLP/assets/150894804/7ebec42f-7271-4468-9be3-44f37360c06e)

![微信图片_20240303101438](https://github.com/PaddlePaddle/PaddleNLP/assets/150894804/640892bb-9cd3-4a3c-b557-0fd9066d72e9)

**Comment by LLLiHaotian** [comment]
已解决 
pymilvus版本问题
更换到pymilvus==2.2.3即可

**Comment by LLLiHaotian** [comment]
您好，更换到pymilvus==2.2.3后无法使用COSINE这个度量类型。
目前我的版本为Milvus: v2.3.10  pymilvus: v2.3.6
但在linux系统下利用python连接数据库超时，请问这是什么问题呢？该如何解决？

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/150894804/d3178f3e-1ec0-45cf-bbfc-36941bcec039)

**Comment by w5688414** [comment]
超时的问题，可以看看是否是端口没有打开。

另外关于Milvus的API问题，可以参考milvus的官方文档：

https://milvus.io/docs/quickstart.md
