### ISSUE TITLE
调用WordTag报错：No module named 'paddle.io'

### ISSUE THREAD

**Issue by leerumor** [PaddlePaddle/PaddleNLP#805]
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：
```
paddlenlp                 2.0.6                    pypi_0    pypi
paddlepaddle              1.8.3                    pypi_0    pypi
```

2）系统环境：
```
python==3.7.6
MacOS
```

- 复现信息：
安装paddlenlp
```
pip install paddlenlp
```
运行官方代码：
```
from paddlenlp.taskflow import TaskFlow
task = TaskFlow("text2knowledge", model="wordtag")
task(["热梅茶是一道以梅子为主要原料制作的茶饮",
      "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
# Support the input text directly
task("热梅茶是一道以梅子为主要原料制作的茶饮")
```
报错：
```
Traceback (most recent call last):
  File "process.py", line 357, in <module>
    main()
  File "process.py", line 27, in main
    from paddlenlp.taskflow import TaskFlow
  File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/__init__.py", line 18, in <module>
    from . import datasets
  File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/datasets/__init__.py", line 15, in <module>
    from .dataset import *
  File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 27, in <module>
    from paddle.io import Dataset, IterableDataset
ModuleNotFoundError: No module named 'paddle.io'
```

**Comment by wawltor** [comment]
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：
> 
> ```
> paddlenlp                 2.0.6                    pypi_0    pypi
> paddlepaddle              1.8.3                    pypi_0    pypi
> ```
> 
> 2）系统环境：
> 
> ```
> python==3.7.6
> MacOS
> ```
> 
> * 复现信息：
>   安装paddlenlp
> 
> ```
> pip install paddlenlp
> ```
> 
> 运行官方代码：
> 
> ```
> from paddlenlp.taskflow import TaskFlow
> task = TaskFlow("text2knowledge", model="wordtag")
> task(["热梅茶是一道以梅子为主要原料制作的茶饮",
>       "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
> # Support the input text directly
> task("热梅茶是一道以梅子为主要原料制作的茶饮")
> ```
> 
> 报错：
> 
> ```
> Traceback (most recent call last):
>   File "process.py", line 357, in <module>
>     main()
>   File "process.py", line 27, in main
>     from paddlenlp.taskflow import TaskFlow
>   File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/__init__.py", line 18, in <module>
>     from . import datasets
>   File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/datasets/__init__.py", line 15, in <module>
>     from .dataset import *
>   File "/Users/miniconda3/lib/python3.7/site-packages/paddlenlp/datasets/dataset.py", line 27, in <module>
>     from paddle.io import Dataset, IterableDataset
> ModuleNotFoundError: No module named 'paddle.io'
> ```

辛苦升级PaddlePaddle到最新的版本

**Comment by leerumor** [comment]
解决了！谢谢
