### ISSUE TITLE
关于few-shot learning的EFL模型中的max_seq_length

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#806]
由于EFL是用蕴涵语句拼接原来的输入sentence， 因此，如果我的原来的输入sentence的语句长度已经超过了max_seq_length（512）,那么，该模型是从拼接后的语句（sentence1+sentence2)截断 还是 先截断sentence1然后拼接sentence2？ 如果是从拼接后的语句（sentence1+sentence2)截断，我就要在做数据的时候考虑样本的长度了，否则，把蕴涵语句截了那就出问题了。

希望能够得到回复，谢谢！

**Comment by tianxin1860** [comment]
> 由于EFL是用蕴涵语句拼接原来的输入sentence， 因此，如果我的原来的输入sentence的语句长度已经超过了max_seq_length（512）,那么，该模型是从拼接后的语句（sentence1+sentence2)截断 还是 先截断sentence1然后拼接sentence2？ 如果是从拼接后的语句（sentence1+sentence2)截断，我就要在做数据的时候考虑样本的长度了，否则，把蕴涵语句截了那就出问题了。
> 
> 希望能够得到回复，谢谢！

先截断 sentence1 然后拼接 sentence2，不存在你担心的问题.

**Comment by LangDaoAI** [comment]
> > 由于EFL是用蕴涵语句拼接原来的输入sentence， 因此，如果我的原来的输入sentence的语句长度已经超过了max_seq_length（512）,那么，该模型是从拼接后的语句（sentence1+sentence2)截断 还是 先截断sentence1然后拼接sentence2？ 如果是从拼接后的语句（sentence1+sentence2)截断，我就要在做数据的时候考虑样本的长度了，否则，把蕴涵语句截了那就出问题了。
> > 希望能够得到回复，谢谢！
> 
> 先截断 sentence1 然后拼接 sentence2，不存在你担心的问题.

感谢！
