### ISSUE TITLE
请问PaddleNLP的SimpleSevring支持同一个接口里面多个模型的调用吗

### ISSUE THREAD

**Issue by liulj0507** [PaddlePaddle/PaddleNLP#8064]
### 请提出你的问题

请问PaddleNLP的SimpleSevring支持同一个接口里面多个模型的调用吗，可以自己写if根据来的请求判断走哪个模型，现在server:app默认只能调用一个模型吧

**Comment by wawltor** [comment]
如果是多张卡启动一个模型是可以支持的，device_id 可以传入多个gpus来支持多卡预测；如果需要支持不同的卡来加载不同的模型需要需要修改模型且逻辑比较复杂 https://github.com/PaddlePaddle/PaddleNLP/blob/dd8a46c81dab74ed138c5e1a24987feb82434c3c/paddlenlp/server/model_manager.py#L61 ；建议根据需求来构建dispatcher，通过需求判断来分发不用的请求到不同的模型上
