### ISSUE TITLE
AutoModelForCausalLM.from_pretrained 如何加载本地模型？

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8067]
### 请提出你的问题

https://paddlenlp.bj.bcebos.com/taskflow/ 和 https://bj.bcebos.com/paddlenlp/models/community/ 这些网站为什么不能访问，主要想知道这些网站的模型配置参数，比如需要多大显卡，现在是一无所知

**Comment by ZHUI** [comment]
我们考虑一下看看要不 出一个网页版的地址目录。

aistudio 上有一些模型库，可以直接下载观看。
https://aistudio.baidu.com/modelsdetail/696?modelId=696
