### ISSUE TITLE
[Question]: UIE信息抽取做 关系抽取任务，出现幻想，文本中没有出现的信息，会出现幻觉

### ISSUE THREAD

**Issue by 827648313** [PaddlePaddle/PaddleNLP#8068]
### 请提出你的问题

调用的是paddlepaddle uie-base 模型进行推理，配置关系如下，及其结果如下，有好的解决方案吗？
![uie](https://github.com/PaddlePaddle/PaddleNLP/assets/66358885/5a184180-f0bf-4f31-b577-250b5b445ae5)

**Comment by wawltor** [comment]
这个是模型效果的问题，需要通过UIE微调方式来提升效果。

**Comment by 827648313** [comment]
微调 通过增加负样例 依然还是有这样的问题，不觉得是负样例的问题，猜测可能和uie本身预测的结构有关系

**Comment by w5688414** [comment]
您好，UIE相关的技术已经停止更新了，欢迎使用LLM来解决您的业务问题
