### ISSUE TITLE
[Question]: 在使用2.7.2版本跑llama2-7b的lora遇到关于dataset的问题（报错：An error occurred while generating the dataset）

### ISSUE THREAD

**Issue by xiaoluomi** [PaddlePaddle/PaddleNLP#8069]
### 请提出你的问题

使用的数据集是paddlenlp已经支持的TriviaQA数据集。
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49263480/9ffd7ea1-4b93-4e59-81b5-e135f86226e9)
但是跑起来的时候报错如下：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49263480/71c144a7-a14b-4c2b-8af5-bbff33e8dbc2)
![Uploading image.png…]()

**Comment by xiaoluomi** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/49263480/35e68ef5-b5a5-43c2-a96b-2dd0eb822186)

**Comment by xiaoluomi** [comment]
请问 这个错误应该怎么解决？

**Comment by w5688414** [comment]
错误显示0 examples，请看一下这个数据集是否被成功加载
