### ISSUE TITLE
UIE-X模型蒸馏时间计划

### ISSUE THREAD

**Issue by VignetteApril** [PaddlePaddle/PaddleNLP#8074]
### Feature request

目前使用uie-x在CPU上推理速度较慢，请问什么时候会出知识蒸馏后的uie-x模型？

### Motivation

-

### Your contribution

-

**Comment by wawltor** [comment]
您好，UIE-X暂且没有升级蒸馏版本的时间，UIE-X在CPU开启了多线程cpu加速能力，目前的版本在CPU基本上没有性能提升得空间；如有条件可以试试GPU预测。

**Comment by VignetteApril** [comment]
ok
