### ISSUE TITLE
[Question]: 给予一段话，判断该文章是否提及过类似这段话的内容？文章很长，而话很短，考虑到用Transformer好像不太靠谱。请问有什么方法可以建议一下？

### ISSUE THREAD

**Issue by yangnianen** [PaddlePaddle/PaddleNLP#8080]
### 请提出你的问题

文章：你对这边熟悉吗？还熟悉啊，你知道中环怎么走吧。啊，那知道就行，不知道我就导个航。全是OPPO挂了是吗？呃对这个这个旁边亮了就是。你在中环上试一下玩一玩吧，嗯。啊，舒舒适模式下那个方向盘太轻了,啊，那个是吧？太轻了是吧？你老家哪里的？湖南是吧？嗯那就在我们隔壁。你江西人？对，江西江西老表哈哈哈你们那边是？我们不都是江西老表吗？对。那你也很难吃了啊！湖南的湖南跟我们江西都很能吃啊！亮的,亮的！呵，我跟你说，比之前那个老款P7亮多了。呃也不能过去不能过去,我知道对,嗯我喜欢啊,贴着线贴着线呢。一般如果靠近哪边或者干嘛的它哪边的话，它会主动的去打开哦啊因为左边那边可能靠东西，它可能会左边打开，如果右边如果靠的更近的话，它右边那个多少啊多少的我没研究过，但是。很清楚的。这是因为我打左转了还是因为我空转？呃左边这个东西靠近它车子哪边靠近的，就算你不打转向灯，它自己也会出来。然后就算这如果前面你看到这种都能看得到，如果前面有个人，哪怕它是交警，它会单独识别出来它是一个交警。对，这还是非常牛的，就它智能化这一块，非常非常牛。好像有一点点延迟，延迟的一一秒的样子，就那个看那个电动座椅啊，到那边去啊，稍微有点点延迟，那样只会越来越好了，哈哈哈。这是他自己画的吗？这线还是线？线还是用高进去的是吧？对，靠近这线。但Max版本它肯定能不依赖高清基础，但但只是现在还没有完全的开放出来这个功能。电车跟油车近一点确实，哈哈。告诉你一个问题。现在是运动模式是吧？对。是会很轻松啊,哈哈哈好，没事，我有准备的，哈哈我习惯了有准备。呃，也就是只有四驱才会有这个效果对吧？那后续的话大概是6秒,4也很猛。后续的话，跟这个比，这个舒适模式还是要强一点是吗？那肯定比这个舒适模式强的。你给我看看舒适模式。这标准左右啊，差不多啊，你调一下这个模式,我看下价格。比这个快啊，一个体感。体感要强一点是吧？不是强一点，强很多哈，基本上跟这个标准模式差不多，你感受一下啊。标准模式差不多的,已主在打开了哦，但是比比老款的要更猛很多啊，跟这个差不多吗？呃我觉得差不多啊,这么猛啊，猛,猛啊！你说6秒4它能到100码呀好的。我现在不太敢踩，踩到底了，哈哈。嗯，这是高架吗？对，这是高架。高架的话你要试一下，它就能辅助驾驶吧？嗯，就是呢，要先找个位置先设置个位置是吧？对我们是哪？稍微近一点，这样子吧，你往前看，然后再。往回倒啊啊对，往回倒吧好吧,然后前面过两个你觉得差不多了然后下去就行了然后再倒回去。他现在他就是啊，他会跟那个什么你们前面一公里又转出去啊，你们说。啊，你刚想问的是,就是它从那个市里开，那个城市道路就是也不是城市道路，就是地下，然后就可以开直接倒了是吧？呃，那个是X3GP,呃，那你的CNGP是什么呢？CNGP是城市路面。城市路面是对,这些是高路面啊不是城市路面也可以对,我的意思就下面,下面啊你等一下试一下是吧但它看要看它是不是高精度地图覆盖,哦哦，要对对对，要看上海应该基本上都,呃不一定也不一定是吧？嗯，不一定。哦对对，上海都没有全市有覆盖，它肯定有路转的。对，有路转的，刚刚是报警的，是压线了是吧？对呃，你看这要么右边下去,再往前面开一段啊？可以唉，请问这下去是哪来的？漳浦路下一出口，中环路,对吧？中环路是另外另外一个高架吧，对吧？你看吧，前面如果能有出去的，有出口就下就好。中环路应该是去中环高架了。对，是是中央保险公司，再找个地方。带你那边去方向那边也是方向啊，那行。想再往前开一点。好像4.5公里了啊。呃，最近的好像4.5公里了。4.5公里啊对，往前开吧，那没办法了。
一段话：CNGP是城市路面，他采用高精地图，自动辅助起来非常牛逼，你可以试试。
现在该文章是否讲过这段话这种算法，用相似度模型很难起作用，请问还有什么办法搞，可以给点建议吗？谢谢。

**Comment by zouhan6806504** [comment]
长文章拆分成短文类似的长度，拆分的部分可以有一定的重叠，然后计算相似度，达到一定程度就认为出现过

**Comment by w5688414** [comment]
可以使用大模型+prompt engineering的方式，可以先用API版本的文心一言试一下效果，然后再使用开源的llm微调一个
