### ISSUE TITLE
使用PaddleNLP语义预训练模型ERNIE优化情感分析報錯：ImportError: cannot import name 'convert_example' from 'utils'

### ISSUE THREAD

**Issue by chentitus** [PaddlePaddle/PaddleNLP#8084]
### 请提出你的问题

Macbook M3 Pro
OS: Sonoma 14.4
Python version: 3.12.2
PaddleNLP version: 2.6.1.post
Paddlepaddle version: 2.6.0

您好：我是PaddleNLP的新手，我在學習這個網頁上的代碼進行情感分類：https://aistudio.baidu.com/projectdetail/1294333

發現以下報錯：**ImportError: cannot import name 'convert_example' from 'utils'**
同樣錯誤也出現在 create_dataloader 以及 predict。

請求協助，謝謝！

**Comment by wawltor** [comment]
在aistudio教程里面有个utils.py文件，需要进行拷贝到相应的环境

**Comment by chentitus** [comment]
> 在aistudio教程里面有个utils.py文件，需要进行拷贝到相应的环境

@wawltor 

請問可以提供utils.py文件的網址嗎？謝謝您！

**Comment by wawltor** [comment]
点击aistudio项目的运行一下，进入项目中才有utils.py脚本

**Comment by Hughhuh** [comment]
> 点击aistudio项目的运行一下，进入项目中共有utils.py脚本

请问一下utils.py应该放在哪里
