### ISSUE TITLE
安装过程中提示hll模块无法正常安装

### ISSUE THREAD

**Issue by ixiami1314** [PaddlePaddle/PaddleNLP#8102]
### 请提出你的问题

设备运行环境为：c86 + kylinv10 sp2 + 寒武纪加速卡
在安装过程中一直提示 hll 模块不存在。

**Comment by DesmonDay** [comment]
收到，这边将问题转交 @qili93 帮忙查看一下。

**Comment by qili93** [comment]
这个可能是寒武纪设备安装相关的问题？还是Paddle安装的问题呢？能请您这里提供下详细的复现步骤和具体的报错日志，方便我们定位一下不？谢谢！
