### ISSUE TITLE
[Question]: milvus document_store 如何多字段查询和检索

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#8103]
### 请提出你的问题

默认是有一个name字段标记文件名,假如我想加一个user_id字段,请问怎么做可以当检索的时候既可以根据user_id或name字段单独检索,也可以user_id+name字段检索呢?

**Comment by w5688414** [comment]
请问您用的代码是什么呢？milvus现在支持条件检索了。

**Comment by w5688414** [comment]
https://milvus.io/docs/search.md#Conduct-a-vector-search
可以参考milvus官方文档，search的时候也支持传入表达式做过滤

**Comment by seetimee** [comment]
from pipelines.document_stores import MilvusDocumentStore
使用的是MilvusDocumentStore这个类

**Comment by seetimee** [comment]
本地数据库使用的是sqlite,文档转成字典后如果传多余的字段好像是放在了meta的二级字典里,但是后面update_embeding的时候传到milvus的又没有将自定义字段传到milvus,所以需要修改下insert这个函数和查询函数应该就可以了对吧
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50852027/26bade47-a1d6-41ca-8005-e766a415497d)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/50852027/b7c3bb66-6dd6-45a5-8ec9-3f07e759a45a)

**Comment by w5688414** [comment]
欢迎提PR升级pipelines里面的milvus
