### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by nehashinde-canopy** [PaddlePaddle/PaddleNLP#8105]
### 请提出你的问题

I want to load a custom dataset to train earnie-layout on. Instead of using load_dataset from "datasets" library, how can I load files from my custom dataset folder and split it into train test val? My custom dataset would have same format as funsd dataset so that it will have image files and annotation files.

**Comment by DesmonDay** [comment]
Hi, you can refer to this document. https://paddlenlp.readthedocs.io/zh/latest/data_prepare/dataset_self_defined.html

**Comment by nehashinde-canopy** [comment]
Thanks for your response @DesmonDay . I need help in converting a custom dataset (which is in funsd format) to the actual format that earnie-layout uses. A lot of questions like [https://github.com/PaddlePaddle/PaddleNLP/issues/4599] here talk about converting the custom datasets to your own format but the method to convert it is not available. Another place where @linjieccc talks about converting SROIE and CORD to your format is [https://github.com/PaddlePaddle/PaddleNLP/issues/4528]
Your format of funsd dataset used for ernie uses segment ids. I need help in creating data to convert my custom dataset to the format which will contain segment ids and other details.
