### ISSUE TITLE
[Bug]: ValueError: Couldn't find cache for glue for config 'sst2' Available configs in the cache: ['cola'] LAUNCH INFO 2024-03-13 06:22:13,223 Exit code 1

### ISSUE THREAD

**Issue by lizexu123** [PaddlePaddle/PaddleNLP#8109]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.6.0
- paddlenlp: 2.7.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/bert
执行这里的以GLUE中的SST-2任务为例，启动Fine-tuning的方式如下：

unset CUDA_VISIBLE_DEVICES
python -m paddle.distributed.launch --gpus "0" run_glue_trainer.py \
    --model_name_or_path bert-base-uncased \
    --task_name SST2 \
    --max_seq_length 128 \
    --per_device_train_batch_size 32   \
    --per_device_eval_batch_size 32   \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --logging_steps 1 \
    --save_steps 500 \
    --output_dir ./tmp/ \
    --device gpu \
    --fp16 False\
    --do_train \
    --do_eval
稳定报错
```

### 稳定复现步骤 & 代码

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/bert
执行这里的以GLUE中的SST-2任务为例，启动Fine-tuning的方式如下：

unset CUDA_VISIBLE_DEVICES
python -m paddle.distributed.launch --gpus "0" run_glue_trainer.py \
    --model_name_or_path bert-base-uncased \
    --task_name SST2 \
    --max_seq_length 128 \
    --per_device_train_batch_size 32   \
    --per_device_eval_batch_size 32   \
    --learning_rate 2e-5 \
    --num_train_epochs 3 \
    --logging_steps 1 \
    --save_steps 500 \
    --output_dir ./tmp/ \
    --device gpu \
    --fp16 False\
    --do_train \
    --do_eval
稳定报错

**Comment by w5688414** [comment]
您好，这个是由于huggingface在国内访问受限导致的，您可以使用一些中国的镜像或者代理，例如：

```
export HF_ENDPOINT=https://hf-mirror.com
```
