### ISSUE TITLE
[Question]: paddle提供的uie-base-answer-extractor-v1预训练模型在哪里可以找到呀

### ISSUE THREAD

**Issue by yysturdy** [PaddlePaddle/PaddleNLP#8115]
### 请提出你的问题

 run_qa_pairs_generation.py \
    --source_file_path=data/source_file.txt \
    --target_file_path=data/target_file.json \
    --answer_generation_model_path=uie-base-answer-extractor-v1 \
    --question_generation_model_path=unimo-text-1.0-question-generation \
请问一下paddle提供的uie-base-answer-extractor-v1预训练模型在哪里可以找到呀

**Comment by w5688414** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/79cb8b6acda42c054e82c1623b3cfff260ae60e5/pipelines/pipelines/nodes/answer_extractor/answer_extractor.py#L42

您好，问题生成相关的模型停止维护了，推荐直接使用大模型做这个任务
