### ISSUE TITLE
[Question]: Embedding-V1是基于百度文心大模型技术的文本表示模型,请问这个具体是哪个模型啊?是ernie-embedding-v1吗?

### ISSUE THREAD

**Issue by seetimee** [PaddlePaddle/PaddleNLP#8126]
### 请提出你的问题

[Question]: Embedding-V1是基于百度文心大模型技术的文本表示模型,请问这个具体是哪个模型啊?是ernie-embedding-v1吗?

**Comment by w5688414** [comment]
您好，您是说的pipeliens里面的ernie-embedding-v1吗？这个模型也是一个基于ERNIE训练的向量检索模型，用的跟ERNIE SDK同样的接口，但没有开源

**Comment by seetimee** [comment]
哦哦,是这样呀,谢谢了
