### ISSUE TITLE
[Question]: simcse in batch negative数据问题

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#8129]
### 请提出你的问题

用simcse in batch negative，通过问题，召回问题相关文本块时，数据中存在一个文本块对应多个问题，造成一个batch内出现多个问题对应相同文本块，从而不同问题的相同文本块会认为是负例，虽然问题不同，但相同文本块还是正例。那么如何保证一个batch这种数据不出现呢

**Comment by w5688414** [comment]
您好，一般in batch negative会使用超大batch size，建议您使用超大batch size来缓解这个问题，另外in batch negative微调过的模型，建议继续使用hard negatives进行调优。

**Comment by ZTurboX** [comment]
> 您好，一般in batch negative会使用超大batch size，建议您使用超大batch size来缓解这个问题，另外in batch negative微调过的模型，建议继续使用hard negatives进行调优。

in batch negative中
cosine_sim = paddle.matmul(query_cls_embedding, title_cls_embedding, transpose_y=True)
margin_diag = paddle.full(
            shape=[query_cls_embedding.shape[0]], fill_value=self.margin, dtype=paddle.get_default_dtype()
        )
cosine_sim = cosine_sim - paddle.diag(margin_diag)
cosine_sim *= self.scale

后续用hard negatives进行调优要分别计算query和pos_sample的cosin_sim,query和neg_sample的cosin_sim;
那么这两种cosin_sim要怎么结合呢

**Comment by w5688414** [comment]
需要自己实现哈，就是把batch的负样本，变成传入负样本即可，可以参考：

https://github.com/w5688414/generative-search/blob/f50f8d4e1828b592538945499ec50bcf54846296/models/modeling.py#L451

**Comment by w5688414** [comment]
搜到一篇改进的论文，里面的方法也可以参考一下： https://arxiv.org/html/2402.16829v1

**Comment by ZTurboX** [comment]
> 搜到一篇改进的论文，里面的方法也可以参考一下： https://arxiv.org/html/2402.16829v1

好的 谢谢
