### ISSUE TITLE
paddlenlp.taskflow.Taskflow("text2knowledge", "wordtag")模型数据推断线程爆炸

### ISSUE THREAD

**Issue by Desperado-Jia** [PaddlePaddle/PaddleNLP#813]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.6，PaddlePaddle2.1.0
2）系统环境：MacOS，python3.7

model = Taskflow("text2knowledge", "wordtag")
for sample in samples_list:
    result = model(sample)

进行全量数据推断时，执行到约1000条样本时出现线程爆炸的问题，报错：can't start new thread

**Comment by wawltor** [comment]
> 欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
> 在留下您的问题时，辛苦您同步提供如下信息：
> 
> * 版本、环境信息
>   1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.6，PaddlePaddle2.1.0
>   2）系统环境：MacOS，python3.7
> 
> model = Taskflow("text2knowledge", "wordtag")
> for sample in samples_list:
> result = model(sample)
> 
> 进行全量数据推断时，执行到约1000条样本时出现线程爆炸的问题，报错：can't start new thread

1. 修复PaddlePaddle的版本的问题，如果是PaddlePaddle 2.1.1或者PaddlePaddle 2.1.2的版本，通过https://github.com/PaddlePaddle/Paddle/pull/34301/files 来修复DataLoader的问题
2. 拉取最特定PaddleNLP分支(未合入)，https://github.com/PaddlePaddle/PaddleNLP/pull/817，或者PR的修改加入自己的paddlenlp包中

**Comment by Desperado-Jia** [comment]
done
