### ISSUE TITLE
[Question]: 我们这个库里有没有分布式加载模型的示例，比如 llama 13b的

### ISSUE THREAD

**Issue by deepindeed2022** [PaddlePaddle/PaddleNLP#8136]
### 请提出你的问题

我们这个库里有没有分布式加载模型的示例，比如 llama 13b的。

**Comment by wawltor** [comment]
python -u  -m paddle.distributed.launch --gpus "0,1,2,3,4,5,6,7" run_pretrain.py ./llama/pretrain-llama2_7b-tp2sd4_stage2.json  

可以参照这个示例，这里就是8卡分布式训练的方式
