### ISSUE TITLE
做快递单提取时，采用高级api modle.fit 训练 与 ChunkEvaluator  时报错

### ISSUE THREAD

**Issue by tim20112017** [PaddlePaddle/PaddleNLP#815]
paddlepaddle 2.1.0
paddlenlp 2.0.2

代码：
metric = ChunkEvaluator(label_list=label_vocab.keys(), suffix=True)
input_ids = InputSpec((-1, -1), dtype="int64", name="input_ids")
input_token_type = InputSpec((-1, -1), dtype="int64", name="input_token_type")
# seq_len = InputSpec((-1, -1), dtype="int64", name="seq_len")
labels = InputSpec((-1, -1), dtype="int64", name="labels")
model = paddle.Model(pre_model, [input_ids, input_token_type], [labels])
model.prepare(optimizer=optimizer, loss=criterion, metrics=metric)
model.fit(train_data=train_loader, eval_data=dev_loader, save_dir=save_dir)

报错：
...
File "/Users/timmike/me/pythonwork/pyproject1/venv/lib/python3.7/site-packages/paddle/hapi/model.py", line 1058, in train_batch
loss = self._adapter.train_batch(inputs, labels)
File "/Users/timmike/me/pythonwork/pyproject1/venv/lib/python3.7/site-packages/paddle/hapi/model.py", line 734, in train_batch
metric_outs = metric.compute(*(to_list(outputs) + labels))
TypeError: compute() missing 1 required positional argument: 'labels'

跟踪：
源码位置
metric_outs = metric.compute(*(to_list(outputs) + labels)) 是一个有两个item的list，

但是ChunkEvaluator.compute()方法是三个参数，具体如下：

compute(self, lengths, predictions, labels, dummy=None):

结论：
要不是我的数据的的输入有问题，要不就是paddle 处理 metric （ChunkEvaluator）的时候，有问题

**Comment by tim20112017** [comment]
paddlepaddle 2.1.0
paddlenlp 2.0.2

**Comment by wawltor** [comment]
这个主要是因为目前paddle的高阶API的要求Loss和Metric的输入是一致的，这个依赖于框架的修复。目前的状态，是不太建议在快递单抽取上使用高阶API了。

**Comment by tim20112017** [comment]
> 这个主要是因为目前paddle的高阶API的要求Loss和Metric的输入是一致的，这个依赖于框架的修复。目前的状态，是不太建议在快递单抽取上使用高阶API了。

了解了，谢谢。
