### ISSUE TITLE
[Bug]: Win下建立索引后再次运行索引与文档数不匹配报错

### ISSUE THREAD

**Issue by justforyou2017** [PaddlePaddle/PaddleNLP#8153]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp: 
所有默认
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
pipelines\document_stores\faiss.py 该文件中_load_init_params_from_config方法中初始化索引名时有问题，Win下路径是abc\\wahaha 不应该用/这个符号切分
```

### 稳定复现步骤 & 代码

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/30369560/8cf62a53-5ddf-4c46-b8b4-1ce55d59285b)

**Comment by w5688414** [comment]
感谢，已经提了PR。https://github.com/PaddlePaddle/PaddleNLP/pull/8159
