### ISSUE TITLE
[Question]: text_correct模型什么时候升级到ernie3.0？等了好久了.....

### ISSUE THREAD

**Issue by danxuan2022** [PaddlePaddle/PaddleNLP#8169]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/107532297/7d4f7754-38a0-4c83-809f-18b869d6f676)
zeyu说是Q2升级模型，但是都一年过去了，我等的花都谢了，求升级效果好的text_correct模型
https://github.com/PaddlePaddle/PaddleNLP/issues/1720

**Comment by ZeyuChen** [comment]
能详细介绍下您的使用场景吗？我们评估下用生成式大模型来解决会不会更好，现在有大模型后，这些传统的任务有新的解法。@danxuan2022

**Comment by cnpioneer** [comment]
> 能详细介绍下您的使用场景吗？我们评估下用生成式大模型来解决会不会更好，现在有大模型后，这些传统的任务有新的解法。@danxuan2022

目前在用PaddleNLP在做文本分类，最大优势就是快，准确度微调后可以接受。但是文本来源错别字很多，影响了分类效果，所以需要前置纠错，数据量每天千万条级别，使用大模型完全带不动，速度太慢，但是现有的Ernie-CSC效果比较拉胯，可否更新一版？
