### ISSUE TITLE
[Question]: UIEX可以直接抽取大段连续内容吗？

### ISSUE THREAD

**Issue by tianwenzhe** [PaddlePaddle/PaddleNLP#8173]
### 请提出你的问题

UIEX是否可以像DocPrompt的阅读理解那样，将连续的几个句子（看着长实体）抽取出来呢？
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/109948251/049a460e-602f-426e-bab2-6d32a7c91719)

**Comment by wawltor** [comment]
可以的，主要是看标注样本数和标注质量

**Comment by cloudfame** [comment]
要标注多少样本呢？UIE是小样本，是不是标注几十条就可以呢？

**Comment by wawltor** [comment]
> 要标注多少样本呢？UIE是小样本，是不是标注几十条就可以呢？

标注样本数和任务难度有关系，可以先尝试标注几十条样本试试
