### ISSUE TITLE
[Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。

### ISSUE THREAD

**Issue by songjunming13** [PaddlePaddle/PaddleNLP#8175]
### 请提出你的问题

在使用FAQ模型的时候，做好异常处理以后，返回一个正确结果，出现一次异常，然后再返回正确结果，再出现异常  请问这个怎么了？应该怎么处理呢?

**Comment by songjunming13** [comment]
请问现在有结果吗？

**Comment by songjunming13** [comment]
在使用FAQ模型的时候，做好异常处理以后，向模型提问一个问题返回一个正确结果，再次提问问题出现一次异常，然后再返回正确结果，再出现异常 请问这个怎么了？应该怎么处理呢?

**Comment by michaelowenliu** [comment]
@songjunming13 你好，收到你的问题和邮件。能否把这个issue里遇到的问题完善下，包括issue的title，这样方便相关研发同学快速定位和解决，谢谢。

**Comment by songjunming13** [comment]
![Uploading 第二次问答结果返回.
<img width="800" alt="模型加载界面" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/d6648a1b-75f0-49ce-be2b-62ea55055c76">
<img width="1077" alt="首次问答结果返回" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/33f43774-75f5-4a1a-aa72-a116b2d51edf">
<img width="800" alt="两次使用模型返回界面" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/2e3175a8-092e-4458-bf37-6bd575b87314">…]()

**Comment by songjunming13** [comment]
![Uploading 两次使用模型返回界面.png…]()

**Comment by songjunming13** [comment]
__
<img width="1077" alt="首次问答结果返回" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/20b6a11d-307e-4a75-8d6e-c68d73ab0650">
<img width="1077" alt="第二次问答结果返回" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/f04f0706-4729-4034-8857-a8426bfd4bd2">

**Comment by songjunming13** [comment]
<img width="870" alt="Snipaste_2024-03-29_09-43-14" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/674c0c2d-6f5c-45e6-af12-cc5c1d1466a0">
红线上面内容对应返回结果正确的那张图片，红线下方对应反馈结果错误的那张照片

**Comment by songjunming13** [comment]
已经收到您的邮件，并按照您所给出的指示做出了相应的操作。新的地址为:[Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 · Issue #8175 · PaddlePaddle/PaddleNLP (github.com)&nbsp;望能够帮助到您~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月29日(星期五) 上午9:21
收件人: ***@***.***&gt;; 
抄送: "Sadness  and  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Question]:  (Issue #8175)





 
@songjunming13 你好，收到你的问题和邮件。能否把这个issue里遇到的问题完善下，包括issue的title，这样方便相关研发同学快速定位和解决，谢谢。

**Comment by ZHUI** [comment]
嗯嗯，你好，请问您使用的代码是哪一个目录的？方便发一下链接吗？

**Comment by songjunming13** [comment]
这个demo13.py是我们的源码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 中午11:11
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
嗯嗯，你好，请问您使用的代码是哪一个目录的？方便发一下链接吗？

**Comment by songjunming13** [comment]
您好，谢谢您的关注，已经向您发送了邮箱，阐述了问题了，以及您所需要的文件，如有不足之处望您在详细说明   谢谢

**Comment by ZHUI** [comment]
请问您的邮件发到哪个地址了？

**Comment by songjunming13** [comment]
非常抱歉，不知道什么原因导致您没有收到邮件，现在我再给您发送一个新的邮件。
demo13.py为我们的源码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 下午3:26
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
请问您的邮件发到哪个地址了？

**Comment by songjunming13** [comment]
<img width="834" alt="发送的邮箱地址" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/82e90aa5-62cb-4565-8062-193759e61050">
这个邮件发送再这个邮箱了？里面有一个问题文档说明，还有源码文件，以及一个遇到问题的演示视频，希望能够减少您的麻烦

**Comment by ZHUI** [comment]
嗯嗯，收到了👌

**Comment by w5688414** [comment]
@您好， 已提交修复的PR：https://github.com/PaddlePaddle/PaddleNLP/pull/8214 ， 然后按照这样设置一下：
```
retriever11 = DensePassageRetriever(
    document_store=document_store11,
    query_embedding_model="rocketqa-zh-dureader-query-encoder",
    passage_embedding_model="rocketqa-zh-dureader-query-encoder",
    max_seq_len_query=64,
    max_seq_len_passage=256,
    batch_size=16,
    use_gpu=False,
    embed_title=False,
    _static_mode=False
)
```
类似错误issue：https://github.com/PaddlePaddle/Paddle/issues/33831

**Comment by w5688414** [comment]
我测试了几次，没什么问题了。

<img width="855" alt="image" src="https://github.com/PaddlePaddle/PaddleNLP/assets/12107462/d03e1f5c-e218-465d-b3b8-2056dcbdf0e0">

**Comment by songjunming13** [comment]
非常感谢，您愿意帮我们解决问题！！！超级激动！！！但是，按照您的要求改变了以后，我这边是出现了这个情况。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 下午5:38
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
@您好， 按照这样设置一下：
 retriever11 = DensePassageRetriever(     document_store=document_store11,     query_embedding_model="rocketqa-zh-dureader-query-encoder",     passage_embedding_model="rocketqa-zh-dureader-query-encoder",     max_seq_len_query=64,     max_seq_len_passage=256,     batch_size=16,     use_gpu=False,     embed_title=False,     _static_mode=False )  
类似错误issue：PaddlePaddle/Paddle#33831
 已提交修复的PR：#8214

**Comment by w5688414** [comment]
把我最新合入的pr拉一下，重新安装一下pipelines

**Comment by songjunming13** [comment]
您说的最新合入的pr拉一下有点没太理解。我应该做的是:&nbsp; 1、将您给我的代码把源文件的进行替换 2、将pipelines给卸载了，重新装。这个理解正确吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 晚上6:08
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
把我最新合入的pr拉一下，重新安装一下pipelines

**Comment by w5688414** [comment]
对的，源码安装最新版本

**Comment by songjunming13** [comment]
您好，很抱歉再次打扰您，按照您的指定操作以后，环境好像出现了问题，然后就在配置环境，但是到最后出现了这个情况[&nbsp; &nbsp;document_store11 = FAISSDocumentStore.load('faiss_index15')
AttributeError: type object 'MissingDependency' has no attribute 'load'
]
为了让您看的更加清楚，发送了一张照片，来说明这个错误。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 晚上6:46
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
对的，源码安装最新版本

**Comment by songjunming13** [comment]
<img width="813" alt="2" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/bbab2761-0636-4181-9b07-7360da9b5d63">

**Comment by w5688414** [comment]
贴一下你的环境，可以使用如下的命令把你的python包输出到requirements.txt里面
```
pip freeze > requirements.txt
```

**Comment by songjunming13** [comment]
您好，附件里面放的文件是您所需要的环境。如果有问题，可随时对我进行询问，最后对您表示万分感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 中午1:08
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
贴一下你的环境，可以使用如下的命令把你的python包输出到requirements.txt里面
 pip freeze &gt; requirements.txt

**Comment by songjunming13** [comment]
您好，在我当初搭建环境成功的时候录制了一个视频，今天看着那个视频，按照相同的步骤搭建，仍然出现了[document_store = FAISSDocumentStore.load(args.index_name)
AttributeError: type object 'MissingDependency' has no attribute 'load'
]这个问题，然后又生成了一个requirements.text文件&nbsp; 冒昧的发给您，希望可以帮到您尽快解决问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 中午1:08
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
贴一下你的环境，可以使用如下的命令把你的python包输出到requirements.txt里面
 pip freeze &gt; requirements.txt

**Comment by songjunming13** [comment]
[Uploading requirements.txt…]()

**Comment by songjunming13** [comment]
[requirements.txt](https://github.com/PaddlePaddle/PaddleNLP/files/14823083/requirements.txt)
这个是新搭建环境的.txt文件

**Comment by w5688414** [comment]
我没有找到您的faiss,这是我的faiss版本，仅供参考：

```
faiss-cpu                      1.7.4
```

**Comment by songjunming13** [comment]
感谢您提供的建议，这么简单的问题还麻烦您了，对不起&nbsp;（有点内疚）但是模型还是有上次的问题（更新和没更新piplines我都尝试了），给您发送了一个附加word的文档详细的说明了我的操作，帮助您更快的定位到我的错误。&nbsp; 万分感谢~~~！&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 晚上8:26
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
我没有找到您的faiss,这是我的faiss版本，仅供参考：
 faiss-cpu                      1.7.4

**Comment by songjunming13** [comment]
[wenti.docx](https://github.com/PaddlePaddle/PaddleNLP/files/14823745/wenti.docx)

**Comment by songjunming13** [comment]
这个是操作详细步骤的文档  
[wenti.docx](https://github.com/PaddlePaddle/PaddleNLP/files/14823750/wenti.docx)

**Comment by w5688414** [comment]
源码安装：
```
cd PaddleNLP/pipelines
pip install -e .
```

**Comment by songjunming13** [comment]
按照这样更新环境的话，又出现了一个错误。
<img width="522" alt="10" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/d3f3a14e-6e5d-4f91-aa9f-9ddf69d3227b">

**Comment by songjunming13** [comment]
上述的错误安装是可以解决的，就是模型是可以跑通。现在的问题主要是 再对模型进行问答的时候，是一次成功一次失败。[如果可以的话，要不您登陆我的华为云服务器上面查看一下，看看是哪里的问题？]


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月1日(星期一) 晚上10:47
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
源码安装：
 cd PaddleNLP/pipelines pip install -e .

**Comment by songjunming13** [comment]
模型现在已经跑通了，但是就是完成了这一步以后，以后还是没有解决
<img width="702" alt="226" src="https://github.com/PaddlePaddle/PaddleNLP/assets/134507217/4fbfccc7-0d19-45a7-8ecc-80d5f6d6ab2a">
。

> 把我最新合入的pr拉一下，重新安装一下pipelines

**Comment by w5688414** [comment]
_static_mode=False 把静态图关掉

**Comment by songjunming13** [comment]
_static_mode=False 把静态图关掉，这个已经考虑到了，但是还是一次成功一次失败&nbsp; &gt;.<


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月2日(星期二) 晚上7:14
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
_static_mode=False 把静态图关掉

**Comment by w5688414** [comment]
你确定你装上去了？下载最新的pipelines源代码，把原来的pipelines卸载掉，重新安装

**Comment by songjunming13** [comment]
就是如果我使用咱们的指令再装包的时候，运行模型会出现缺失某些模块，导致模型运行失败，然后我需要将部分包给卸载，再重新装，这样的话,可以正常运行模型，但是会导致模型问答一次成功一次失败的冲突。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月3日(星期三) 中午11:37
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
你确定你装上去了？下载最新的pipelines源代码，把原来的pipelines卸载掉，重新安装

**Comment by w5688414** [comment]
可以留个微信联系方式，我帮您看一下环境

**Comment by songjunming13** [comment]
微信号:Sjm15617911752&nbsp; &nbsp;这是我第一次感受儿到陌生人来的善意，特别特别感谢您！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月3日(星期三) 下午5:58
***@***.***&gt;;
抄送:&nbsp;"Sadness  and  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: FAQ模型部署成功以后，经过异常捕获处理后，在多轮次问答过程中，出现一次成功一次失败的现象。 (Issue #8175)





 
可以留个微信联系方式，我帮您看一下环境

**Comment by w5688414** [comment]
已私下远程解决
