### ISSUE TITLE
[Question]: FAQ

### ISSUE THREAD

**Issue by xt12345667** [PaddlePaddle/PaddleNLP#8176]
### 请提出你的问题

FAQ正在训练模型的时候为什么只能在linux上跑，在windows环境下却报错

**Comment by guoshengCS** [comment]
请问具体是哪个模型了，可否贴下链接

**Comment by xt12345667** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines/examples/FAQ   居然是这个链接的模型

**Comment by w5688414** [comment]
请升级到最新的pipelines试一下：

```
cd PaddleNLP/pipelines
pip install -e .
```
如果还有问题，贴一下windows上的错误
