### ISSUE TITLE
如何使用SimpleServer进行自定义任务？

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8183]
### 请提出你的问题

我现在有一个任务，其中用到两个算法模型文本分类和信息抽取，paddlenlp给到的app.register_taskflow只能注册一个任务，如何自定义任务，将文本分类和信息抽取放在一起任务中，然后启动一个服务呢

**Comment by wawltor** [comment]
目前暂不支持这种方式来处理，Taskflow主要是针对单任务；看起来这种使用方式有点类似 pipelines，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/pipelines

**Comment by watertianyi** [comment]
@wawltor 我进行代码改造，如下是可行的，
from pprint import pprint
from paddlenlp import SimpleServer, Taskflow
from paddlenlp.server import BaseTaskflowHandler
import json
class TaskflowHandler(BaseTaskflowHandler):
    def init(self):
        self._name = "taskflow_handler"

    @classmethod
    def process(cls, predictor, data, parameters):
        if data is None:
            return {}
        text = None
        res_list=[]
       
        if "text" in data:
            text = data["text"]
            results=my_cls(text)
            results=my_ie(text)
        return res_list


schema = ["",""]
my_cls = Taskflow("zero_shot_text_classification", model="utc-base", schema=schema, task_path='')
schema2 = []
my_ie = Taskflow("information_extraction", schema=schema2, pred_threshold=0.1,task_path='')

taskflowhandler=TaskflowHandler()

app = SimpleServer()

app.register_taskflow("my_cls", my_cls,taskflow_handler=taskflowhandler)
如果我在生产环境中多个任务应该如何使用taskflow？

**Comment by w5688414** [comment]
最好的方式是用Docker部署多个任务，然后再写一个后台做一些串联
