### ISSUE TITLE
关于ERNIE-Layout中的NER模型问题

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleNLP#8188]
### 请提出你的问题

在ERNIE-Layout使用[文档](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-layout/deploy/python/README_ch.md)中的关于NER的推理，其中参数--model_path_prefix ../../ner_export/inference 这里有开源的训练好的模型吗

**Comment by wj-Mcat** [comment]
我们已经提供了内置的模型，你只需要安装文档来执行就行了：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-layout

下面有提供示例代码，执行它就行了。

如果你想看具体哪些模型的话，建议你看看：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/taskflow/taskflow.py#L436

我们已经支持了 docprompt 的模型。
