### ISSUE TITLE
增加新模型：悟道·天鹰（Aquila2）

### ISSUE THREAD

**Issue by w4yne** [PaddlePaddle/PaddleNLP#8190]
### 简要描述

背景：
悟道·天鹰（Aquila2）是由智源研究院（BAAI）开源的具备中英双语知识、支持商用许可协议、国内数据合规需求的开源语言大模型。
其继承了GPT-3、LLaMA等的架构设计，并基于中英文语料库上从头开始训练

期望：
参照 Baichuan 的 PR，增加对 Aquila2 模型的支持。

问题：
已线下自行测试，通过修改 config.json 和 tokenizer_config.json，并参照 [大模型预训练文档](https://paddlenlp.readthedocs.io/zh/latest/llm/pretraining/index.html) 中的数据集和配置，可以启动 pretrain 任务
但是，[贡献新模型](https://paddlenlp.readthedocs.io/zh/latest/community/contribute_models/contribute_new_models.html) 的文档内容为空
所以，想了解下如何贡献这个新模型，需要提交哪些文件？具体的：
1. 修改过的适配 paddlenlp 的 `config.json` 和 `tokenizer_config.json` 应该提交到哪里？
2. 修改 `llm/llama/README.md` ？
3. 增加 `llm/llama/pretrain-Aquila2_7b-xxx.json` ?

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

https://huggingface.co/BAAI/Aquila2-7B
https://github.com/FlagAI-Open/Aquila2

**Comment by wawltor** [comment]
1. PaddleNLP的模型目前并没有提供bos上传的方式，如需要上传模型，可以提供联系方式，我们来上传模型 
2. 可以新增一个新模型目录，放天鹰相关的模型 
3. 需要支持SFT、LoRA、Pretrain的方式，需要需要新增3个相关json配置文件
