### ISSUE TITLE
LAUNCH INFO 2024-03-27 01:54:27,777 Exit code -7

### ISSUE THREAD

**Issue by SiqinLv** [PaddlePaddle/PaddleNLP#8193]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/70061450/865728d6-8f58-4142-ae75-06f72d2a4d8e)
这是什么问题呀，弄了两天了还没解决，┭┮﹏┭┮

**Comment by lugimzzz** [comment]
使用什么paddle和paddlenlp版本？
