### ISSUE TITLE
[Question]: Windows环境下部署语义检索系统semantic-search的过程中遇到问题

### ISSUE THREAD

**Issue by Z1huatanej0** [PaddlePaddle/PaddleNLP#8197]
### 请提出你的问题

按照[官方文档](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/pipelines/examples/semantic-search/Install_windows.md)在Windows环境下搭建语义检索系统semantic-search的过程中：
在执行python examples/semantic-search/semantic_search_example.py --device gpu时无法返回检索结果
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/108441768/d1c3d3d1-b3f1-43d5-be50-96217d8c5f23)
再次执行后运行报错：D:\Anaconda3\envs\paddlenlp\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
INFO - pipelines.document_stores.faiss -  document_cnt:0        embedding_cnt:1398
Traceback (most recent call last):
  File "D:\pythonProject\pipeline_test\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 209, in <module>
    semantic_search_tutorial()
  File "D:\pythonProject\pipeline_test\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 181, in semantic_search_tutorial
    retriever = get_faiss_retriever(use_gpu)
  File "D:\pythonProject\pipeline_test\PaddleNLP\pipelines\examples\semantic-search\semantic_search_example.py", line 51, in get_faiss_retriever
    document_store = FAISSDocumentStore.load(args.index_name)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\pipelines\document_stores\faiss.py", line 711, in load
    return cls(faiss_index_path=index_path, faiss_config_path=config_path)
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\pipelines\document_stores\faiss.py", line 127, in __init__
    self.__class__.__init__(self, **init_params)  # pylint: disable=non-parent-init-called
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\pipelines\document_stores\faiss.py", line 191, in __init__
    self._validate_index_sync()
  File "D:\Anaconda3\envs\paddlenlp\lib\site-packages\pipelines\document_stores\faiss.py", line 211, in _validate_index_sync
    raise ValueError(
ValueError: The number of documents present in the SQL database does not match the number of embeddings in FAISS. Make sure your FAISS configuration file correctly points to the same database that was used when creating the original index.
我尝试在update_embeddings执行后，打印出document_store.get_all_documents()消息，发现embedding为none
使用的系统信息及软件版本：
系统版本：Windows11 23H2
python版本：3.9.19
CUDA版本：11.6
aiohttp                        3.9.3
aiosignal                      1.3.1
aistudio-sdk                   0.1.7
anyio                          3.7.1
argon2-cffi                    23.1.0
argon2-cffi-bindings           21.2.0
astor                          0.8.1
async-timeout                  4.0.3
attrdict                       2.0.1
attrs                          23.2.0
azure-core                     1.29.1
azure-storage-blob             12.19.1
Babel                          2.14.0
bce-python-sdk                 0.9.5
beautifulsoup4                 4.12.3
blis                           0.7.11
boilerpy3                      1.0.7
Brotli                         1.1.0
cachetools                     5.3.3
catalogue                      2.0.10
certifi                        2024.2.2
cffi                           1.16.0
charset-normalizer             3.3.2
click                          8.0.0
cloudpathlib                   0.16.0
colorama                       0.4.6
coloredlogs                    15.0.1
colorlog                       6.8.2
confection                     0.1.4
contourpy                      1.2.0
cryptography                   42.0.5
cssselect                      1.2.0
cssutils                       2.9.0
cuda-python                    12.4.0
cycler                         0.12.1
cymem                          2.0.8
Cython                         3.0.9
datasets                       2.18.0
decorator                      5.1.1
dill                           0.3.4
elasticsearch                  7.11.0
environs                       9.5.0
et-xmlfile                     1.1.0
Events                         0.5
exceptiongroup                 1.2.0
faiss-cpu                      1.8.0
fastapi                        0.103.2
filelock                       3.13.3
fire                           0.6.0
Flask                          2.2.5
flask-babel                    4.0.0
flatbuffers                    24.3.25
fonttools                      4.50.0
frozenlist                     1.4.1
fsspec                         2024.2.0
future                         1.0.0
gevent                         24.2.1
geventhttpclient               2.0.2
greenlet                       3.0.3
grpcio                         1.60.0
h11                            0.14.0
htbuilder                      0.6.2
httpcore                       1.0.4
httpx                          0.27.0
huggingface-hub                0.22.1
humanfriendly                  10.0
idna                           3.6
imageio                        2.34.0
imgaug                         0.4.0
importlib_metadata             7.1.0
importlib_resources            6.4.0
isodate                        0.6.1
itsdangerous                   2.1.2
jieba                          0.42.1
Jinja2                         3.1.3
joblib                         1.3.2
kiwisolver                     1.4.5
langcodes                      3.3.0
langdetect                     1.0.9
lazy_loader                    0.3
llvmlite                       0.42.0
lmdb                           1.4.1
lxml                           5.1.0
Markdown                       3.6
markdown-it-py                 3.0.0
MarkupSafe                     2.1.5
marshmallow                    3.21.1
matplotlib                     3.8.3
mdurl                          0.1.2
minio                          7.2.5
mmh3                           4.1.0
more-itertools                 10.2.0
mpmath                         1.3.0
multidict                      6.0.5
multiprocess                   0.70.12.2
murmurhash                     1.0.10
networkx                       3.2.1
nltk                           3.8.1
numba                          0.59.1
numpy                          1.26.4
onnx                           1.16.0
onnxconverter-common           1.14.0
onnxruntime-gpu                1.17.1
opencv-contrib-python          4.6.0.66
opencv-contrib-python-headless 4.9.0.80
opencv-python                  4.6.0.66
opencv-python-headless         4.9.0.80
openpyxl                       3.1.2
opt-einsum                     3.3.0
packaging                      24.0
paddle-pipelines               0.6.2
paddle2onnx                    1.0.6
paddlefsl                      1.1.0
paddlenlp                      2.6.1
paddleocr                      2.6.1.3
paddlepaddle-gpu               2.6.0.post116
pandas                         2.2.1
pdf2docx                       0.5.8
pdf2image                      1.17.0
pdfminer.six                   20231228
pdfplumber                     0.11.0
pillow                         10.2.0
pip                            23.3.1
premailer                      3.10.0
preshed                        3.0.9
protobuf                       3.20.2
psutil                         5.9.8
pyarrow                        15.0.2
pyarrow-hotfix                 0.6
pyclipper                      1.3.0.post5
pycparser                      2.21
pycryptodome                   3.20.0
pydantic                       1.10.14
Pygments                       2.17.2
pymilvus                       2.4.0
PyMuPDF                        1.20.2
pyparsing                      3.1.2
pypdfium2                      4.28.0
pyreadline3                    3.4.1
python-dateutil                2.9.0.post0
python-docx                    1.1.0
python-dotenv                  1.0.1
python-rapidjson               1.16
pytz                           2024.1
PyYAML                         6.0.1
rapidfuzz                      3.7.0
rarfile                        4.1
regex                          2023.12.25
requests                       2.31.0
rich                           13.7.1
safetensors                    0.4.2
scikit-image                   0.22.0
scikit-learn                   1.4.1.post1
scipy                          1.12.0
sentencepiece                  0.2.0
seqeval                        1.2.2
setuptools                     68.2.2
shapely                        2.0.3
six                            1.16.0
smart-open                     6.4.0
sniffio                        1.3.1
soupsieve                      2.5
spacy                          3.7.4
spacy-legacy                   3.0.12
spacy-loggers                  1.0.5
SQLAlchemy                     1.4.52
SQLAlchemy-Utils               0.41.2
srsly                          2.4.8
sseclient-py                   1.7.2
starlette                      0.27.0
sympy                          1.12
termcolor                      2.4.0
thinc                          8.2.3
threadpoolctl                  3.4.0
tifffile                       2024.2.12
tqdm                           4.66.2
tritonclient                   2.41.1
typer                          0.9.4
typing_extensions              4.5.0
tzdata                         2024.1
ujson                          5.9.0
urllib3                        1.26.18
uvicorn                        0.29.0
visualdl                       2.5.3
wasabi                         1.1.2
weasel                         0.3.4
Werkzeug                       3.0.1
wheel                          0.41.2
wordcloud                      1.8.2.2
xxhash                         3.4.1
yarl                           1.9.4
zipp                           3.18.1
zope.event                     5.0
zope.interface                 6.2

烦请大佬帮助 谢谢

**Comment by w5688414** [comment]
请安装最新版本的pieplines再试一下：

```
cd PaddlenLP/pipelines
pip install -e .
```

**Comment by Z1huatanej0** [comment]
> 请安装最新版本的pieplines再试一下：
> 
> ```
> cd PaddlenLP/pipelines
> pip install -e .
> ```
感谢帮助！
