### ISSUE TITLE
增加 facebook/nllb-200-distilled-600M   facebook/nllb-moe-54b

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/PaddleNLP#8201]
### 简要描述

翻译模型，想解决翻译效率慢问题

### 是否已开源

- [X] 已开源
- [ ] 未开源

### 模型详细信息

https://huggingface.co/facebook/nllb-200-distilled-600M
https://huggingface.co/facebook/nllb-moe-54b
https://github.com/facebookresearch/fairseq/issues

**Comment by DesmonDay** [comment]
收到，我们会与内部同学讨论看是否需要接入。
