### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8203]
### 请提出你的问题

https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/text_classification/multi_class/retrieval_based#%E6%A8%A1%E5%9E%8B%E8%AE%AD%E7%BB%83
对着步骤操作时，出现上述bug，环境如下：
paddle-bfloat                  0.1.7
paddle-serving-client          0.9.0
paddle2onnx                    1.1.0
paddlefsl                      1.1.0
paddlenlp                      2.7.2
paddlepaddle-gpu               2.6.1
python3.9

**Comment by wawltor** [comment]
可以降低PaddlePaddle的版本到2.5.0或者2.4.2版本

**Comment by watertianyi** [comment]
问题是安装的cuda11.8+paddlepaddle-gpu2.6.1，没有paddlepaddle-gpu2.5.0对应的cuda11.8

**Comment by w5688414** [comment]
可以去这里面找一些合适的：

https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
