### ISSUE TITLE
百科知识树

### ISSUE THREAD

**Issue by Doloxetine** [PaddlePaddle/PaddleNLP#8206]
### Feature request

百科知识树正式版什么时候发布

### Motivation

需要细粒度链路推断

### Your contribution

能帮使用

**Comment by wawltor** [comment]
百科知识树后续不再更新，如有一些知识树相关的工作可以使用开源相关大模型进行处理，我们现在更关注大模型来来解决NLP传统任务。

**Comment by Doloxetine** [comment]
那能否把TermTree的全集发布了，让之前的工作有传承，让之前的工作能被后人看见。


wawltor ***@***.***> 于2024年3月29日周五 10:11写道：

**Comment by w5688414** [comment]
这个涉及到多方的协调问题，有一定的困难
