### ISSUE TITLE
PaddleNLP/applications/text_classification/multi_class /retrieval_based/中milvus1.1.2替换为milvus2.4报错

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8215]
### 请提出你的问题

from pymilvus import (
    MilvusClient,DataType
)

MILVUS_HOST = 'localhost'
MILVUS_PORT = '19530'
output_emb_size = 0
collection_param = {
    "dimension": output_emb_size if output_emb_size > 0 else 768,
    "index_file_size": 256,
    "metric_type": "L2"
}
index_param = {
    "index_type": "IVF_FLAT",
    "nlist": 1000,
}
index_type = "IVF_FLAT"
search_param = {
    "nprobe": 20
}
top_k = 20

collection_name = "text"
partition_tag = "partition_2"

class VecToMilvus:
    def __init__(self):
        # self.client = Milvus(host=MILVUS_HOST, port=MILVUS_PORT)
        self.client = MilvusClient("http://localhost:19530")
    def has_collection(self, collection_name):
        try:
            status = self.client.has_collection(collection_name)
            return status
        except Exception as e:
            print("Milvus has_table error:", e)
    
    #创建集合
    def creat_collection(self, collection_name):
        try:
            # collection_param["collection_name"] = collection_name
            # status = self.client.create_collection(collection_param)
            dim = output_emb_size if output_emb_size > 0 else 768
            schema = MilvusClient.create_schema(auto_id=False,enable_dynamic_field=False)

            # 2. Add fields to schema
            schema.add_field(field_name="my_id", datatype=DataType.INT64, is_primary=True)
            schema.add_field(field_name="my_vector", datatype=DataType.FLOAT_VECTOR, dim=768)

            status = self.client.create_collection(collection_name=collection_name, schema=schema,consistency_level="Strong")
            print(status)
            return status
        except Exception as e:
            print("Milvus create collection error:", e)
    #创建索引
    def create_index(self, collection_name):
        try:
            # status = self.client.create_index(collection_name, index_type, index_param)
            index_params = self.client.prepare_index_params()
            index_params.add_index(field_name="my_id",index_type="STL_SORT")
            index_params.add_index(field_name="my_vector", 
                                   index_type="IVF_FLAT",
                                   metric_type="L2",
                                   params={ "nlist": 1000 }
                                   )
            status = self.client.create_index(collection_name, index_params)
            print(status)
            return status
        except Exception as e:
            print("Milvus create index error:", e)

    def has_partition(self, collection_name, partition_tag):
        try:
            # status, ok = self.client.has_partition(collection_name, partition_tag)
            status, ok =  self.client.has_partition(collection_name, partition_tag)
            return ok
        except Exception as e:
            print("Milvus has partition error: ", e)
    
    #删除集合
    def delete_partition(self, collection_name, partition_tag):
        try:
            # status = self.client.drop_collection(collection_name)
            status = self.client.release_collection(collection_name)
            self.client.release_partitions(collection_name, partition_names = partition_tag)
            self.client.drop_partition(collection_name, partition_name = partition_tag)
            return status
        except Exception as e:
            print("Milvus has partition error: ", e)
    
    #创建分区
    def create_partition(self, collection_name, partition_tag):
        try:
            # status = self.client.create_partition(collection_name, partition_tag)
            status = self.client.create_partition(collection_name, partition_name = partition_tag)
            print("create partition {} successfully".format(partition_tag))
            return status
        except Exception as e:
            print("Milvus create partition error: ", e)
    #插入向量
    def insert(self, vectors, collection_name, ids=None, partition_tag=None):
        try:
            if not self.has_collection(collection_name):
                self.creat_collection(collection_name)
                self.create_index(collection_name)
                print("collection info: {}".format(self.client.describe_collection(collection_name)[1]))
            if (partition_tag is not None) and (not self.has_partition(collection_name, partition_tag)):
                self.create_partition(collection_name, partition_tag)
            # status, ids = self.client.insert(
            #     collection_name=collection_name, records=vectors, ids=ids, partition_tag=partition_tag
            # )
            
            rows=[]
            for id in ids:
                print(id)
                dict_row={"my_id":id,"my_vector":vectors[id]}
                # print(dict_row)
                rows.append(dict_row)
            # print("rows:",rows)
            ids=self.client.insert(collection_name, ids,vectors, partition_name = partition_tag)
            # print(ids)
            #数据刷新
            self.client.refresh_load(collection_name)
            print(
                "Insert {} entities, there are {} entities after insert data.".format(
                    len(ids), collection_name
                )
            )
            return ids
        except Exception as e:
            print("Milvus insert error:", e)

class RecallByMilvus:
    def __init__(self):
        self.client = MilvusClient("http://localhost:19530")
    
    #搜索向量
    def search(self, vectors, collection_name, partition_tag=None):
        try:
            results=self.client.search(collection_name, vectors, limit=top_k, partition_names = partition_tag)
            # status, results = self.client.search(
            #     collection_name=collection_name,
            #     query_records=vectors,
            #     top_k=top_k,
            #     params=search_param,
            #     partition_tag=partition_tag,
            # )
            return results
        except Exception as e:
            print("Milvus recall error: ", e)
源码如上述编码错误，可以帮忙看看吗？

**Comment by w5688414** [comment]
请问环境是什么呢？

可以参考Milvus的最新文档试试：https://milvus.io/docs/quickstart.md

**Comment by watertianyi** [comment]
The code is modified as follows. It runs correctly, but the results are incorrect and the retrieval accuracy is reduced.
from config import (
    MILVUS_HOST,
    MILVUS_PORT,
    top_k,
)

from pymilvus import (
     connections,
     utility,
     FieldSchema, CollectionSchema, DataType,
     Collection,Partition
 )


class VecToMilvus:
    def __init__(self):
        connections.connect(host='localhost', port='19530')
        # self.client2 = MilvusClient("http://localhost:19530")
        print(f"\nList connections:")
        print(connections.list_connections())
    def has_collection(self, collection_name):
        try:
            ok = utility.has_collection(collection_name)
            return ok
        except Exception as e:
            print("Milvus has_table error:", e)

    def creat_collection(self, collection_name):
        try:
            field_1 = FieldSchema(name="id", dtype=DataType.INT64, is_primary=True, auto_id=False)
            field_2 = FieldSchema(name="vector", dtype=DataType.FLOAT_VECTOR, dim=768)
            schema = CollectionSchema(fields=[field_1, field_2])

            collection = Collection(collection_name, schema)
            # collection.load()
            print("collection created")

            return True
        except Exception as e:
            print("Milvus create collection error:", e)

    def create_index(self, collection_name):
        try:
            collection = Collection(collection_name)
            vector_index = {
                'metric_type': "L2",
                'index_type': "IVF_FLAT",
                'params': {"nlist": 1000}
            }
            collection.create_index("vector", vector_index)
            collection.load()
            return True
        except Exception as e:
            print("Milvus create index error:", e)

    def has_partition(self, collection_name, partition_tag):
        try:
            ok = utility.has_collection(collection_name)
            if not ok:
                return ok

            ok = utility.has_partition(collection_name=collection_name, partition_name=partition_tag)
            return ok
        except Exception as e:
            print("Milvus has partition error: ", e)

    def delete_partition(self, collection_name, partition_tag):
        try:
            print("delete.......")
            collection = Collection(collection_name)
            partition = Partition(collection, name=partition_tag)     # Get an existing partition.
            partition.release()
            partition.drop()
            collection.drop_partition(partition_name=partition_tag)
            collection.release()
            collection.drop()

            return True
        except Exception as e:
            print("Milvus has partition error: ", e)

    def create_partition(self, collection_name, partition_tag):
        try:
            
            collection = Collection(collection_name)
            collection.create_partition(partition_name=partition_tag)
            print("create partition {} successfully".format(partition_tag))
            return True
        except Exception as e:
            print("Milvus create partition error: ", e)

    def insert(self, vectors, collection_name, ids=None, partition_tag=None):
        try:
            if not self.has_collection(collection_name):
                self.creat_collection(collection_name)
                self.create_index(collection_name)
                print("collection info: {}".format(self.client.get_collection_info(collection_name)[1]))
            if (partition_tag is not None) and (not self.has_partition(collection_name, partition_tag)):
                self.create_partition(collection_name, partition_tag)

            collection = Collection(collection_name)
            data = [
                ids,
                vectors,
            ]
            partition = Partition(collection, name=partition_tag)
            partition.insert(data)
            # collection.insert(data)
            print("type:",len(data[1]))
            collection.flush()
            print(
                "Insert {} entities, there are {} entities after insert data.".format(
                    len(data[1]), collection.num_entities
                )
            )
            return data
        except Exception as e:
            print("Milvus insert error:", e)


class RecallByMilvus:
    def __init__(self):
        connections.connect(host=MILVUS_HOST, port=MILVUS_PORT)
        print(f"\nList connections:")
        print(connections.list_connections())

    def search(self, vectors, collection_name, partition_tag=None):
        try:
            collection = Collection(collection_name)
            
            partition_names = [] if partition_tag is None else [partition_tag]
            partition = Partition(collection, name=partition_tag)
            partition.load()
            search_params = {"metric_type": "L2", "params": {"nprobe": 20}}
            results = partition.search(vectors,"vector",search_params,top_k)
            # results = collection.search(
            #     data=vectors,
            #     anns_field="vector",
            #     param={"metric_type": "L2", "params": {"nprobe":20}},
            #     limit=top_k,
            # )
            print("results:",results)
            return results
        except Exception as e:
            print("Milvus recall error: ", e)

**Comment by w5688414** [comment]
可以咨询一下milvus的人员，或者重新建库试试
