### ISSUE TITLE
wordtag模型如何自定义添加命名实体及对应词类

### ISSUE THREAD

**Issue by Desperado-Jia** [PaddlePaddle/PaddleNLP#822]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.7，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如MacOS，python3.7版本

问题背景：现有算子未正确识别出很多影视作品名称，e.g., 小兵张嘎，现有算子识别结果是：(小兵，张嘎)；风犬少年的天空情非得已第几集，现有算子识别结果是：（风犬少年的天空情非得已，第几集），应当识别结果为：（风犬少年的天空，情非得已，第几集）
需求描述：
需要自定义添加实体及对应wordtag_label

**Comment by wawltor** [comment]
这个依赖于二次构造数据来进行finetune，同时要更新termtree信息。wordtag分为两个步骤
1）通过BIOES体系进行分词
2）将分词后的信息和TermTree进行匹配
因此需要做以下两个事情
1）需要分词正确，这里可能依赖于wordtag的finetune数据，来让分词正确
2）wordtag里面也需要把分词正确后term打上相应的知识信息 

finetune的部分可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_to_knowledge/ernie-ctm

**Comment by Desperado-Jia** [comment]
done

**Comment by SOVLOOKUP** [comment]
@wawltor 看了您的回答后理解了，但是还没完全理解，希望能再向您请教一些问题：

#### 自定义词项的流程是这样的吗?

1. 纠正 wordtag 结果给出正确的分词
2. 给这些分词打上知识信息
3. 将这些分词补充到知识树上
4. 重新运行 wordtag 得到正确结果

**其中有一些细节问题：**

1. 下面 wordtag 结果的每个字段的含义具体是什么？如果 wordtag 给出的结果是错误的，按什么标准纠正其结果？

```
{
     "item": "美人鱼",
     "offset": 0,
      "wordtag_label": "作品类_实体",
      "length": 3,
      "termid": "作品与出版物_eb_美人鱼"
}
```

2. 如何给 term 打上知识信息？

wordtag 的结果是这样的：

```
{
     "item": "美人鱼",
     "offset": 0,
      "wordtag_label": "作品类_实体",
      "length": 3,
      "termid": "作品与出版物_eb_美人鱼"
}
```

知识树上的一个词条是这样的，如何进行转换呢？

```
{
    "termid": "人物_eb_林昭亮",
    "term": "林昭亮",
    "src": "eb",
    "termtype": "人物",
    "subtype": [
        "人物_cb_小提琴演奏家",
        "人物_cb_音乐人"
    ],
    "subterms": [],
    "subterms_num": 0,
    "alias": [],
    "alias_ext": [],
    "links": [
        {
            "bdbkUrl": [
                "http://baike.baidu.com/item/%E6%9E%97%E6%98%AD%E4%BA%AE/2862998"
            ]
        }
    ],
    "id": "ca5e98056e017d354da1990a1464f3b6"
}
```

3. 补充知识树具体是如何实施的？可以在 python 中动态补充知识树吗？
4. 如何定义知识树中知识的树状层级关系？是在 subterms 字段中定义吗？

**Comment by qhpeklh5959** [comment]
目前的方式是只能按照格式修改源文件和termtype体系，把term挂接到特定的termtype下面，挂接正确且wordtag标注正确的情况下可以完成linking。近期我们会开发一个termtree相关接口，辅助进行定制化知识整合、结构校验等功能

**Comment by SOVLOOKUP** [comment]
期待～加油！
