### ISSUE TITLE
[Question]: ImportError: Please install the dependencies first, pip install LAC --upgrade

### ISSUE THREAD

**Issue by moosewoler** [PaddlePaddle/PaddleNLP#8225]
### 请提出你的问题

按照[依存句法分析](https://github.com/PaddlePaddle/PaddleNLP/blob/v2.6.1/docs/model_zoo/taskflow.md#%E4%BE%9D%E5%AD%98%E5%8F%A5%E6%B3%95%E5%88%86%E6%9E%90)的示例代码：

```python
from paddlenlp import Taskflow
ddp = Taskflow("dependency_parsing")
ddp("2月8日谷爱凌夺得北京冬奥会第三金")
```

运行时出现：

```shell
ImportError: Please install the dependencies first, pip install LAC --upgrade
```

![图片](https://github.com/PaddlePaddle/PaddleNLP/assets/526821/13812938-986b-4994-982c-b99834668de2)

环境：

- windows 10.0.19045
- python = 3.10.14
- paddlepaddle-gpu = 2.6.1.post117
- paddlenlp = 2.6.1
- LAC = 2.1.2

**更新：**

将python更改为3.7，paddlepaddle更改为2.5之后，错误消除。具体环境如下：

- windows 10.0.19045
- python = 3.7.16
- paddlepaddle-gpu = 2.5.2.post117
- paddlenlp = 2.6.1
- LAC = 2.1.2

**Comment by w5688414** [comment]
您好，paddle2.6以后移除了fluid的API，您可以使用2.5或者更早版本的paddle来使用这个功能

**Comment by moosewoler** [comment]
谢谢
