### ISSUE TITLE
[Bug]:  None Type Error

### ISSUE THREAD

**Issue by leftthomas** [PaddlePaddle/PaddleNLP#8229]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.6.1.post117
- paddlenlp: 2.7.2
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
Class WordSubstitute and CharSubstitute must encounter the None Type Error when used with aug_n=1
```

### 稳定复现步骤 & 代码

The below code could produce the error:
```python
from paddlenlp.dataaug import WordSubstitute, CharSubstitute
# word_sub = WordSubstitute(aug_type=["synonym", "embedding", "homonym"], create_n=6)
char_sub = CharSubstitute(aug_type=["synonym", "embedding", "homonym"], create_n=6)
sentence = "我是人"
# msg = word_sub.augment(msg)
msg = char_sub.augment(msg)
```
And I have debugged, the error is raised by `_augment_single(seq_tokens, aug_indexes, p)` method, the arg `p` is passed as `None` (line 133 of char.py) and `p` is used in line 227:
```python
pp.append(p[i] / len(self.dict[seq_tokens[aug_index]]))
```
so it raised the None type Error, this should be fixed by given `p` a default int value or not use the arg `p`.

**Comment by leftthomas** [comment]
@wj-Mcat hello, can you confirm this bug and fix this quickly?

**Comment by lugimzzz** [comment]
please provide your paddlepaddle paddlenlp version

**Comment by lugimzzz** [comment]
可以给我们提一个pr修复这个问题

**Comment by leftthomas** [comment]
@lugimzzz 额，我看你们代码的逻辑那个地方涉及到结果的产生，需要用到随机数，还是你们自己看看怎么设计比较好
