### ISSUE TITLE
tansformer translation服务器部署时怎么利用tensorRT加速？

### ISSUE THREAD

**Issue by dlkht** [PaddlePaddle/PaddleNLP#824]
目前能利用吗？怎么用呢？谢谢！

**Comment by wawltor** [comment]
您好，目前我们在tansformer类的模型上，使用tensorrt的精度还有问题，还不能利用tesnorrt做加速。精度的问题我们正在测试，有结论反馈给您！

**Comment by dlkht** [comment]
谢谢！

**Comment by guoshengCS** [comment]
如果是希望加速的话也可以试下PaddleNLP中集成的FasterTransformer https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/machine_translation/transformer/faster_transformer

**Comment by chenxiaozeng** [comment]
您好，根据你提出的需求，我们想进一步和您沟通下需求背景以及使用场景，以便更好得解答您的问题。这是我们的联系方式：邮箱Paddle-better@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
