### ISSUE TITLE
How to optimizer "document_intelligence", using fast tokenizer

### ISSUE THREAD

**Issue by Dineshkumar-Anandan-ZS0367** [PaddlePaddle/PaddleNLP#8242]
### 请提出你的问题

How to optimizer "document_intelligence", its take 20 minutes to complete 30 question in GPU, Is there any fast ernie layout tokenizer available or any params and configurations available for this feature.

use_fast=True, also not impact performance.

**Comment by w5688414** [comment]
Hello, fast_tokenizer is no longer matained, because we have too much work for LLMs, we will be thankful if you will contribute
