### ISSUE TITLE
UIE无法分离相同事件的属性

### ISSUE THREAD

**Issue by zealYOU** [PaddlePaddle/PaddleNLP#8245]
### 问题描述

我注意到PaddleNLP的UIE算法应该是反复运行大模型再通过算法构建出来的嵌套结构，我想要了解下为什么采用这种算法？
当前这种算法会导致无法分离相同事件的属性，例如：
schema：```{"地震触发词":["地区","震级"]}```
输入：```"去年A国发生了震级为7.3级的大地震，今天B国也发生了一次地震，震级约6.5级"```
输出（略去部分内容）：
```
[{
    "地震触发词": [
      {
        "text": "地震",
        "relations": {
          "地区": [
            {"text": "B国"},
            {"text": "A国"}
          ],
          "震级": [
            {"text": "6.5级"},
            {"text": "7.3级"}]
        }
      },
      {
        "text": "地震",
        "relations": {
          "地区": [
            {"text": "B国"},
            {"text": "A国"}
          ],
          "震级": [
            {"text": "6.5级"},
            {"text": "7.3级"}]}
      }
    ]
}]
```
有没有考虑过模仿Liu的那篇论文，通过设计提示词的方式完成任务（例如直接将数组作为提示词），是因为精度仍不够理想吗？还是说上面这种多目标复杂场景在实际业务环境中不常见

**Comment by w5688414** [comment]
UIE相关的工作已经停止更新了，欢迎使用大模型解决您的业务问题。https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm
