### ISSUE TITLE
[Question]: InferenceModel类中Dynamic Batching的作用

### ISSUE THREAD

**Issue by lausannel** [PaddlePaddle/PaddleNLP#8263]
您好！

在浏览paddlenlp目录时，我注意到存在两种模型实现方式，对此，我有一些疑问希望得到解答~

我想了解[InferenceModel](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/experimental/transformers/qwen/modeling.py)这个类与PaddleNLP中其他[常规模型类](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/qwen/modeling.py)之间的**主要区别**是什么？在文档中，我看到了“**Dynamic Batching**”的相关描述，但对其具体含义还不太清楚。请问这里提到的dynamic batching是否与[Orca](https://www.usenix.org/conference/osdi22/presentation/yu)文章中描述的概念相同？如果有所不同，能否详细解释一下它的具体含义？

感谢！

**Comment by w5688414** [comment]
dynamic batching在哪个地方？
inferenceModel做了fuse加速，只支持推理：

https://github.com/PaddlePaddle/PaddleNLP/blob/662feb16927fd0bd0c07479854b3dcabbe09d779/paddlenlp/experimental/transformers/qwen/modeling.py#L45

普通的网络推理和训练都行：

https://github.com/PaddlePaddle/PaddleNLP/blob/662feb16927fd0bd0c07479854b3dcabbe09d779/paddlenlp/transformers/qwen/modeling.py#L1048

**Comment by lausannel** [comment]
@w5688414 

https://github.com/PaddlePaddle/PaddleNLP/blob/0d055448c3a65644fa842f89431ece9441df67d0/paddlenlp/experimental/transformers/llama/modeling.py#L857

这个文件里有一个dynamic batching的说法

**Comment by w5688414** [comment]
哦，是的，不过这个要结合服务化来做

**Comment by lausannel** [comment]
哦哦，也就是说，离线情况下不存在Dynamic Batching，在线服务化部署可以实现token-level scheduling嘛

**Comment by xiaoxiaohehe001** [comment]
> 哦哦，也就是说，离线情况下不存在Dynamic Batching，在线服务化部署可以实现token-level scheduling嘛

Dynamic Batching 需要结合服务化部署才能实现，目前这部分并没有相关开源

**Comment by lausannel** [comment]
理解了，感谢！
