### ISSUE TITLE
 In the example of UIE information extraction zero sample, how many pieces of training data can be supported by a small sample at most? Isn’t it a bad idea to have more data?

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8270]
### 请提出你的问题

I want to first train a batch of 200 A-label data with a small number of samples, and then add a batch of B-label data for training. Finally, both the A and B labels for inference must be identified. Is this feasible? If so, how can I use it based on the original model? Are you training?

**Comment by w5688414** [comment]
based on your description, it's related to continual Learning/incremental learning to overcome the catastrophic forgetting, but we don't provide the solutions, here I google some materials for you. 

https://github.com/xialeiliu/Awesome-Incremental-Learning
