### ISSUE TITLE
uie训练的checkpoint存储的内存一直在增加，有办法不存储这么多checkpoint吗？

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8273]
### 请提出你的问题

我的训练参数是：
```
export finetuned_model=./checkpoint/model_best

python finetune.py  \
    --device gpu \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --seed 42 \
    --model_name_or_path uie-base \
    --output_dir $finetuned_model \
    --train_path data/train.txt \
    --dev_path data/dev.txt  \
    --max_seq_length 512  \
    --per_device_eval_batch_size 8 \
    --per_device_train_batch_size  8 \
    --num_train_epochs 20 \
    --learning_rate 1e-5 \
    --label_names "start_positions" "end_positions" \
    --do_train \
    --do_eval \
    --do_export \
    --export_model_dir $finetuned_model \
    --overwrite_output_dir \
    --disable_tqdm True \
    --metric_for_best_model eval_f1 \
    --load_best_model_at_end  True \
    --save_total_limit 1
```
为什么--num_train_epochs 20
checkpoint已经到了checkpoint-8700，占用125G内存，这个能不能不保存这么多？
训练+测试+dev数据在doccanno数据1814条需要多久才可以结束呢

**Comment by w5688414** [comment]
可以调整save_steps，比如调整成1000:

```
 --save_steps 1000 \
```
save_total_limit也能控制保存模型的数量，可以看看是什么原因。

https://github.com/PaddlePaddle/PaddleNLP/blob/f4a8f4cb7e762d77af42ff129d0b63d91c812edd/paddlenlp/trainer/training_args.py#L432

**Comment by watertianyi** [comment]
已经设置了--save_total_limit 1

**Comment by watertianyi** [comment]
https://github.com/PaddlePaddle/PaddleNLP/issues/2608#issuecomment-2055577697
我有提问这个，谢谢你及时回答

**Comment by w5688414** [comment]
现在由于精力有限，UIE这部分会逐渐停止维护，如果是代码的问题，需要提供最小复现代码方便复现，如果是调优问题，我给出的建议如下：

1.ETL数据清洗，对数据做一些分析和清洗。

2.参数调优，一般调学习率等参数。

3.是否使用大模型可以解决？https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm

如果需要帮忙调优，则需要提供代码和数据，我们在工作方便的时候，给您做一些反馈。

**Comment by watertianyi** [comment]
谢谢你的建议

**Comment by watertianyi** [comment]
我做了数据清洗，确实好了很多，但是出现如下这种情况是什么原因呢？
![2024-04-17 11-40-51 的屏幕截图](https://github.com/PaddlePaddle/PaddleNLP/assets/29244715/1aab7a67-2d56-413f-b432-9826f6636ddc)

**Comment by lili-changjiang** [comment]
我遇到跟你一样的问题，我用的最新的paddlepaddle-gpu==2.6.1.post112 cuda11.2 cudnn8.21 ,checkpoint会一直保存，是paddlepaddle-gpu版本的问题吗

**Comment by lili-changjiang** [comment]
就是paddlepaddle-gpu版本问题，或者paddlenlp ,我用回paddlepaddle-gpu==2.4.2.post112 paddlenlp==2.5.2 保存就没问题了，不会一直增加

**Comment by w5688414** [comment]
> 我做了数据清洗，确实好了很多，但是出现如下这种情况是什么原因呢？ ![2024-04-17 11-40-51 的屏幕截图](https://private-user-images.githubusercontent.com/29244715/323063754-1aab7a67-2d56-413f-b432-9826f6636ddc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjEwMTQsIm5iZiI6MTcxMzM2MDcxNCwicGF0aCI6Ii8yOTI0NDcxNS8zMjMwNjM3NTQtMWFhYjdhNjctMmQ1Ni00MTNmLWI0MzItOTgyNmY2NjM2ZGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEzMzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZGU5MWEzY2JjM2Y3MmMzMzJjMTZiMzVmOGM5NzJhYTM5YThkNWQxNjNkYWMxMDA4NmQ4ZjcyOTU3NTRlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sLPB7VJ1s-Ec9Hk0KSF1auuJn5fvBG_MODbmG9z1iI8)

没看出什么大问题，可以调一下学习率和数据分布。
