### ISSUE TITLE
fluid operator conditional_block_infer 问题

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleNLP#8275]
### 问题描述

fluid operator 算子 conditional_block_infer 即将移除，https://github.com/PaddlePaddle/Paddle/pull/63507

CI测试中 tests/llm/test_predictor.py tests/llm/test_prefix_tuning.py 等有依赖，不知道是否能解除依赖

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10494626/job/25923766 
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/4617245/cbdf5e88-2e23-4b7e-a06c-b1b926cf4312)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/4617245/0629ae0c-09c5-44c0-a60a-399f401b1a16)

**Comment by w5688414** [comment]
这个我们得内部考虑一下，是有什么需求吗？

**Comment by co63oc** [comment]
fluid 下的算子需要移除或迁移，conditional_block_infer 计划是移除

**Comment by w5688414** [comment]
欢迎提个PR贡献
