### ISSUE TITLE
[Question]: 我想使用UIE模型去进行关系或实体抽取的zero-shot，我想使用我的数据然后使用我定义的标签去完成，这些都可以实现，但是结果给到的是具体的实体和关系，我想问下UIE模型中有对zero-shot的f1、precision、recall值得计算程序吗，在哪里呢？的计算程序嘛

### ISSUE THREAD

**Issue by 741060686** [PaddlePaddle/PaddleNLP#8280]
### 请提出你的问题

我想使用UIE模型去进行关系或实体抽取的zero-shot，我想使用我的数据然后使用我定义的标签去完成，这些都可以实现，但是结果给到的是具体的实体和关系，我想问下UIE模型中有对zero-shot的f1、precision、recall值得计算程序吗，在哪里呢？的计算程序嘛

**Comment by w5688414** [comment]
可以看看这个：

https://github.com/PaddlePaddle/PaddleNLP/blob/beb433a9aef8a4f8575c866be0bca2660dee2039/model_zoo/uie/evaluate.py#L58

**Comment by 741060686** [comment]
谢谢您的回答，但是我还是不能搞清楚UIE模型的Zero-shot这个怎么启动。因为我做few-shot时，使用doccano.py可以按照比例划分出三个数据集，但是zero-shot中我使用doccano.py划分不了数据集，显示为空。zero-shot的启动和few-shot一样吗，期待您的回答。

**Comment by w5688414** [comment]
zero-shot是直接进行抽取，不进行训练，可以参考文档。

https://github.com/PaddlePaddle/PaddleNLP/blob/beb433a9aef8a4f8575c866be0bca2660dee2039/docs/model_zoo/taskflow.md?plain=1#L949C1-L949C74 

直接使用这个函数就能算zero-shot的指标。

https://github.com/PaddlePaddle/PaddleNLP/blob/beb433a9aef8a4f8575c866be0bca2660dee2039/model_zoo/uie/evaluate.py#L35
