### ISSUE TITLE
[Question]: 在llama预训练中，paddlenlp是否支持在customdevice（比如mlu、npu）使用flashattention

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/PaddleNLP#8284]
### 请提出你的问题

这是paddle的源码，我认为源码的逻辑是只支持在gpu上开启flashattention。请问是否是这样的？
如果是的话，请问paddle后续有没有在customdevice上支持flashattention的计划？
![20240418134445](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/bd55af9e-fd56-4f72-8e1e-fde39874c971)

![20240418134516](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/9acf5205-2d55-4ff9-8bfb-2027a22e4871)

**Comment by gongel** [comment]
是的，其他的设备还在支持中。
