### ISSUE TITLE
[Question]: FAQ pipeline能否给个能运行的说明？

### ISSUE THREAD

**Issue by morego123** [PaddlePaddle/PaddleNLP#8291]
### 请提出你的问题

试了很多次，都是在这一步报错：
https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.8/pipelines/examples/FAQ#343-%E5%90%AF%E5%8A%A8-restapi-%E6%A8%A1%E5%9E%8B%E6%9C%8D%E5%8A%A1
前面的几步都是OK的，paddle-pipelines都是按照说明从源码安装的。
而且[dense_faq_example.py] 这个使用Faiss做索引的代码也是OK的，

报错是：
Exception: Exception while running node `Retriever` with input `{'root_node': 'Query', 'params': {'Retriever': {'top_k': 5, 'debug': False}, 'Ranker': {'top_k': 5}, 'Query': {'debug': False}}, 'query': '企业如何办理养老保险?', 'node_id': 'Retriever'}`: RequestError(400, 'search_phase_execution_exception', 'runtime error'), full stack trace: Traceback (most recent call last):

我怀疑这个代码repo链接ES的地方有问题，建议你们check一下

**Comment by w5688414** [comment]
检查一下模型是否搞混了，然后检查一下索引名，是否和下面的人碰见的问题类似？

https://github.com/PaddlePaddle/PaddleNLP/issues/8262

**Comment by w5688414** [comment]
我尝试修复了一下，您先测一下：

https://github.com/PaddlePaddle/PaddleNLP/pull/8292

**Comment by morego123** [comment]
好的，已试了今天看到的最新的commit版本的README，是可以的。
对了，那个离线建立索引的地方，估计还得更新一下，这个issue https://github.com/PaddlePaddle/PaddleNLP/issues/8247#issuecomment-2050888042

**Comment by w5688414** [comment]
欢迎开发者贡献
