### ISSUE TITLE
Paddle在单卡上是否支持并行推理？

### ISSUE THREAD

**Issue by RyanOvO** [PaddlePaddle/PaddleNLP#8296]
### 问题描述

在单卡A10，内存足够，显存24G的情况下；假设机器的硬件允许并行5个推理请求；Paddle是否支持这种打卡并行？如果支持的话，可以在哪看文档说明？

**Comment by w5688414** [comment]
您是指在线的dynamic batch的推理吗，如果是的话，需要有服务端组batch，如果是离线的，直接提升batch size即可。

**Comment by RyanOvO** [comment]
> 您是指在线的dynamic batch的推理吗，如果是的话，需要有服务端组batch，如果是离线的，直接提升batch size即可。

是的。类似dynamic batch，就类似VLLM那样的。

**Comment by w5688414** [comment]
这部分目前没有开源
