### ISSUE TITLE
【Bug】EFL模型训练代码中output_dir创建失败

### ISSUE THREAD

**Issue by LangDaoAI** [PaddlePaddle/PaddleNLP#831]
> python train.py --task_name "tnews"
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
100.0%
[2021-08-02 13:16:42,623] [    INFO] - Already cached /root/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
W0802 13:16:42.624711 18335 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0802 13:16:42.631032 18335 device_context.cc:422] device: 0, cuDNN Version: 8.1.
[2021-08-02 13:16:46,412] [    INFO] - Found /root/.paddlenlp/models/ernie-1.0/vocab.txt
global step 10, epoch: 1, batch: 10, loss: 0.70893, speed: 8.15 step/s
epoch:1, dev_accuracy:22.587, total_num:2010
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    do_train()
  File "train.py", line 266, in do_train
    write_fn[args.task_name](args.task_name, output_file, y_pred_labels)
  File "/home/data/pvoc/efl/predict.py", line 135, in write_tnews
    with open(output_file, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './predict_output/1tnewsf_predict.json'

**Comment by LangDaoAI** [comment]
正确修补如下：

 output_dir = os.path.join(args.output_dir)
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
        output_file = os.path.join(args.output_dir,
                                   str(epoch) + predict_file[args.task_name])

**Comment by tianxin1860** [comment]
已提 PR 修复: https://github.com/PaddlePaddle/PaddleNLP/pull/840/files， 感谢指出，也欢迎向我们提交 PR ~
