### ISSUE TITLE
[Bug]: 权重加载导致的主机内存不足

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/PaddleNLP#8316]
### 软件环境

- paddlepaddle:fbf852dd832bc0e63ae31cd4aa37defd829e4c03
- paddlenlp: e67fd7881db35ddffda3cf554309ce7bcf77fd66

### 重复问题

- [X] I have searched the existing issues

### 错误描述

`paddlenlp/transformers/conversion_utils.py`中`convert_tensor_parallel`函数使用了`paddle.load`函数，这个操作如果在多进程的场景会导致多次权重加载，如果模型权重较大并且主机侧内存较小。则会导致程序莫名退出并且没有任何报错信息。

期望优化这一内存加载逻辑，只进行一次内存加载，避免小内存机器产生程序异常退出的问题。

### 稳定复现步骤 & 代码

见上方描述

**Comment by w5688414** [comment]
请问你们是什么场景，为什么不能内存扩大一点呢？

**Comment by ShawnNew** [comment]
> 请问你们是什么场景，为什么不能内存扩大一点呢？

假设不能保证用户测试主机内存足够加载一定模型，上述错误导致程序异常推出，没有足够多的信息定位。

期望或许可以从两个方面解决：
1. 优化权重加载的逻辑
2. 给出正确的报错信息，引导用户调试

**Comment by DrownFish19** [comment]
> > 请问你们是什么场景，为什么不能内存扩大一点呢？
> 
> 假设不能保证用户测试主机内存足够加载一定模型，上述错误导致程序异常推出，没有足够多的信息定位。
> 
> 期望或许可以从两个方面解决：
> 
> 1. 优化权重加载的逻辑
> 2. 给出正确的报错信息，引导用户调试

paddlenlp中已经尽可能优化了权重加载过程，但是目前大模型套件更加关注加载效率，因此采用了多线程加载的方式实现。如果期望单独加载，可以考虑增加线程顺序控制，按照顺序加载模型，将内存需求降低为一份模型的大小。

**Comment by ZHUI** [comment]
你好，可以使用 加载 safetensors 格式的模型，可以避免此问题
