### ISSUE TITLE
[Question]: 无法安装paddlenlp2.7及2.8版

### ISSUE THREAD

**Issue by Sinoftj** [PaddlePaddle/PaddleNLP#8344]
### 请提出你的问题

Mac M2芯片，python3.9
使用命令 pip3 install paddlenlp 安装的时候会安装2.6的版本。
使用pycham安装最新版，会提示ERROR: No matching distribution found for tool-helpers
哪怕用pip 安装whl也不行

**Comment by w5688414** [comment]
您好，感谢反馈，可以下载源代码，删除如下的tool_helper(只在linxu进行了编译)包即可。

https://github.com/PaddlePaddle/PaddleNLP/blob/db52319a0cf8d1677e480e5626060bf25f1a5ad9/requirements.txt#L23

```
git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP
pip install -e .
```

**Comment by w5688414** [comment]
提了一个修复的PR： https://github.com/PaddlePaddle/PaddleNLP/pull/8336

**Comment by Sinoftj** [comment]
> 您好，感谢反馈，可以下载源代码，删除如下的tool_helper(只在linxu进行了编译)包即可。
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/db52319a0cf8d1677e480e5626060bf25f1a5ad9/requirements.txt#L23
> 
> ```
> git clone https://github.com/PaddlePaddle/PaddleNLP.git
> cd PaddleNLP
> pip install -e .
> ```

感谢您的帮助，但是我是新手，这些我不会（或者需要一点时间进行学习），只能等着你们修复了

**Comment by w5688414** [comment]
已经合入了，可以使用develop分支
