### ISSUE TITLE
[Question]: 怎么查看文本分类的训练日志

### ISSUE THREAD

**Issue by dghlnvyps** [PaddlePaddle/PaddleNLP#8347]
### 请提出你的问题

我想看文本训练的过程日志，应该怎么看。

我看 runs 文件夹下面的 vdlrecords.1714356952.log 文件会乱码，utf-8可以看到最多的日志信息，但是还是有很多地方不知道为啥显示不出来，如下图：

![paddlenlp日志截图1](https://github.com/PaddlePaddle/PaddleNLP/assets/69330046/66e73a8c-9cc2-4e5f-b804-9f314f4a027f)
![paddlenlp日志截图2](https://github.com/PaddlePaddle/PaddleNLP/assets/69330046/c2114c7f-cf20-4260-8d03-8afdc3d9afe0)

**Comment by w5688414** [comment]
使用visualdl查看日志。

```
visualdl --logdir your_log_path
```
https://github.com/PaddlePaddle/VisualDL
