### ISSUE TITLE
[Question]:在xpu上使用taskflow预测时间过长

### ISSUE THREAD

**Issue by ruoclio** [PaddlePaddle/PaddleNLP#8349]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/80383121/20dde8d5-34cc-4eb3-817d-29e13866f4bd)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/80383121/307e8a8f-ad0b-4c6e-9a0e-40e58eb83225)
使用xpu进行一键UIE预测，平均预测时间约为12秒，请问是否有方法缩短这部分的时间

**Comment by ruoclio** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/80383121/d6add602-852b-4805-988e-c2b7bfc74127)
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/80383121/aaa5017a-7d05-41b9-bba4-ee37cccf26a3)
昆仑R200 32G

**Comment by w5688414** [comment]
UIE技术已经停止更新了，想要加速可以使用轻量化版本
