### ISSUE TITLE
paddlenlp使用预训练模型实现快递单信息抽取中CrossEntropyLoss()指定weight报错

### ISSUE THREAD

**Issue by geekChinaMaster** [PaddlePaddle/PaddleNLP#835]
- 版本、环境信息
1）**PaddleNLP和PaddlePaddle版本：paddlenlp==2.0.7 paddlepaddle-gpu==2.1.0.post101**

2）系统环境：aistudio
**paddlenlp使用预训练模型实现快递单信息抽取中CrossEntropyLoss()指定weight，出现报错**
损失函数为：paddle.nn.loss.CrossEntropyLoss(weight=weight)
其中的weight为：
Tensor(shape=[13], dtype=float64, place=CUDAPlace(0), stop_gradient=True,
       [0.20000000, 0.20000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000, 0.10000000])

**具体错误：**
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-27-a5ebf0e17586> in <module>
      3     for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
      4         logits = model(input_ids, token_type_ids)
----> 5         loss = paddle.mean(loss_fn(logits, labels))
      6         loss.backward()
      7         optimizer.step()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py in forward(self, input, label)
    403             axis=self.axis,
    404             use_softmax=self.use_softmax,
--> 405             name=self.name)
    406 
    407         return ret
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py in cross_entropy(input, label, weight, ignore_index, reduction, soft_label, axis, use_softmax, name)
   1418                         'Expected 0 <= label_value < class_dimension({}), but got {} <= label_value <= {} '.
   1419                         format(input.shape[-1],
-> 1420                                label_min.numpy(), label_max.numpy()))
   1421                 weight_gather = core.ops.gather_nd(weight, label)
   1422                 input_shape = list(label.shape)
ValueError: Expected 0 <= label_value < class_dimension(13), but got [-1] <= label_value <= [12] 

代码：
https://aistudio.baidu.com/bdvgpu/user/535371/2250258/notebooks/2250258.ipynb
`
from paddle.utils.download import get_path_from_url
URL = "https://paddlenlp.bj.bcebos.com/paddlenlp/datasets/waybill.tar.gz"
get_path_from_url(URL, "./")

from functools import partial

import paddle
from paddlenlp.datasets import MapDataset
from paddlenlp.data import Stack, Tuple, Pad
from paddlenlp.transformers import ErnieTokenizer, ErnieForTokenClassification
from paddlenlp.metrics import ChunkEvaluator
from utils import convert_example, evaluate, predict, load_dict

def load_dataset(datafiles):
    def read(data_path):
        with open(data_path, 'r', encoding='utf-8') as fp:
            next(fp)  # Skip header
            for line in fp.readlines():
                words, labels = line.strip('\n').split('\t')
                words = words.split('\002')
                labels = labels.split('\002')
                yield words, labels

    if isinstance(datafiles, str):
        return MapDataset(list(read(datafiles)))
    elif isinstance(datafiles, list) or isinstance(datafiles, tuple):
        return [MapDataset(list(read(datafile))) for datafile in datafiles]

train_ds, dev_ds, test_ds = load_dataset(datafiles=(
        './data/train.txt', './data/dev.txt', './data/test.txt'))

label_vocab = load_dict('./data/tag.dic')
tokenizer = ErnieTokenizer.from_pretrained('ernie-1.0')

trans_func = partial(convert_example, tokenizer=tokenizer, label_vocab=label_vocab)

train_ds.map(trans_func)
dev_ds.map(trans_func)
test_ds.map(trans_func)
print (train_ds[0])

ignore_label = -1
batchify_fn = lambda samples, fn=Tuple(
    Pad(axis=0, pad_val=tokenizer.pad_token_id),  # input_ids
    Pad(axis=0, pad_val=tokenizer.pad_token_type_id),  # token_type_ids
    Stack(),  # seq_len
    Pad(axis=0, pad_val=ignore_label)  # labels
): fn(samples)

train_loader = paddle.io.DataLoader(
    dataset=train_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)
dev_loader = paddle.io.DataLoader(
    dataset=dev_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)
test_loader = paddle.io.DataLoader(
    dataset=test_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)

model = ErnieForTokenClassification.from_pretrained("ernie-1.0", num_classes=len(label_vocab))

import numpy as np
weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],dtype='float64'))
metric = ChunkEvaluator(label_list=label_vocab.keys(), suffix=True)
loss_fn = paddle.nn.loss.CrossEntropyLoss(weight=weight, ignore_index=ignore_label)
optimizer = paddle.optimizer.AdamW(learning_rate=2e-5, parameters=model.parameters())

step = 0
for epoch in range(10):
    for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
        logits = model(input_ids, token_type_ids)
        loss = paddle.mean(loss_fn(logits, labels))
        loss.backward()
        optimizer.step()
        optimizer.clear_grad()
        step += 1
        print("epoch:%d - step:%d - loss: %f" % (epoch, step, loss))
    evaluate(model, metric, dev_loader)

    paddle.save(model.state_dict(),
                './ernie_result/model_%d.pdparams' % step)

`

**Comment by joey12300** [comment]
@geekChinaMaster 您好，目前CrossEntropyLoss不支持含有ignore_index的label序列进行weight设置。目前一个解决方案是：
1. 将ignore_label设为len(label_list)，即13。
2. 将weight的长度从13改为14，第14个weight设为0

```python
weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
```

**Comment by geekChinaMaster** [comment]
> @geekChinaMaster 您好，目前CrossEntropyLoss不支持含有ignore_index的label序列进行weight设置。目前一个解决方案是：
> 
>     1. 将ignore_label设为len(label_list)，即13。
> 
>     2. 将weight的长度从13改为14，第14个weight设为0
> 
> 
> ```python
> weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
> ```

有两个问题：
1. 这块如果ignore_label如果设为13，也就是还代表是’O‘标签是吗
2. 就是如果我想正常运行的话要同时将ignore_label设为13，将weight的长度从13改为14，第14个weight设为0，是吗，这样修改模型的效果会不会收到影响

**Comment by joey12300** [comment]
> > @geekChinaMaster 您好，目前CrossEntropyLoss不支持含有ignore_index的label序列进行weight设置。目前一个解决方案是：
> > ```
> > 1. 将ignore_label设为len(label_list)，即13。
> > 
> > 2. 将weight的长度从13改为14，第14个weight设为0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
> > ```
> 
> 有两个问题：
> 
> 1. 这块如果ignore_label如果设为13，也就是还代表是’O‘标签是吗
> 2. 就是如果我想正常运行的话要同时将ignore_label设为13，将weight的长度从13改为14，第14个weight设为0，是吗，这样修改模型的效果会不会收到影响

1. 不是。'O'标签应该是12吧，因为是从0开始的。所以13就是label表以外的数了。
2. 不会，因为13这个label的weight设为0，不参与loss计算，反向不会更新相对应的embedding，不影响模型效果

**Comment by geekChinaMaster** [comment]
> > > @geekChinaMaster 您好，目前CrossEntropyLoss不支持含有ignore_index的label序列进行weight设置。目前一个解决方案是：
> > > ```
> > > 1. 将ignore_label设为len(label_list)，即13。
> > > 
> > > 2. 将weight的长度从13改为14，第14个weight设为0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```python
> > > weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
> > > ```
> > 
> > 
> > 有两个问题：
> > 
> > 1. 这块如果ignore_label如果设为13，也就是还代表是’O‘标签是吗
> > 2. 就是如果我想正常运行的话要同时将ignore_label设为13，将weight的长度从13改为14，第14个weight设为0，是吗，这样修改模型的效果会不会收到影响
> 
>     1. 不是。'O'标签应该是12吧，因为是从0开始的。所以13就是label表以外的数了。
> 
>     2. 不会，因为13这个label的weight设为0，不参与loss计算，反向不会更新相对应的embedding，不影响模型效果

好的，谢谢你啊~

**Comment by geekChinaMaster** [comment]
> > > @geekChinaMaster 您好，目前CrossEntropyLoss不支持含有ignore_index的label序列进行weight设置。目前一个解决方案是：
> > > ```
> > > 1. 将ignore_label设为len(label_list)，即13。
> > > 
> > > 2. 将weight的长度从13改为14，第14个weight设为0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```python
> > > weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
> > > ```
> > 
> > 
> > 有两个问题：
> > 
> > 1. 这块如果ignore_label如果设为13，也就是还代表是’O‘标签是吗
> > 2. 就是如果我想正常运行的话要同时将ignore_label设为13，将weight的长度从13改为14，第14个weight设为0，是吗，这样修改模型的效果会不会收到影响
> 
>     1. 不是。'O'标签应该是12吧，因为是从0开始的。所以13就是label表以外的数了。
> 
>     2. 不会，因为13这个label的weight设为0，不参与loss计算，反向不会更新相对应的embedding，不影响模型效果

刚才试了一下
按照上面所说，将ignore_label设为了13
将weight设为了weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
运行代码报错：
```
import numpy as np
weight = paddle.to_tensor(np.array([0.2,0.2,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.0],dtype='float64'))
metric = ChunkEvaluator(label_list=label_vocab.keys(), suffix=True)
loss_fn = paddle.nn.loss.CrossEntropyLoss(weight=weight, ignore_index=13)
optimizer = paddle.optimizer.AdamW(learning_rate=2e-5, parameters=model.parameters())

step = 0
for epoch in range(10):
    for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
        logits = model(input_ids, token_type_ids)
        loss = paddle.mean(loss_fn(logits, labels))
        loss.backward()
        optimizer.step()
        optimizer.clear_grad()
        step += 1
        print("epoch:%d - step:%d - loss: %f" % (epoch, step, loss))
    evaluate(model, metric, dev_loader)

    paddle.save(model.state_dict(),
                './ernie_result/model_%d.pdparams' % step)


---------------------------------------------------------------------------SystemError                               Traceback (most recent call last)<ipython-input-10-a5ebf0e17586> in <module>
      3     for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
      4         logits = model(input_ids, token_type_ids)
----> 5         loss = paddle.mean(loss_fn(logits, labels))
      6         loss.backward()
      7         optimizer.step()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    896                 self._built = True
    897 
--> 898             outputs = self.forward(*inputs, **kwargs)
    899 
    900             for forward_post_hook in self._forward_post_hooks.values():
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py in forward(self, input, label)
    403             axis=self.axis,
    404             use_softmax=self.use_softmax,
--> 405             name=self.name)
    406 
    407         return ret
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py in cross_entropy(input, label, weight, ignore_index, reduction, soft_label, axis, use_softmax, name)
   1414                 label_min = paddle.min(label)
   1415                 label_max = paddle.max(label)
-> 1416                 if label_min < 0 or label_max >= input.shape[-1]:
   1417                     raise ValueError(
   1418                         'Expected 0 <= label_value < class_dimension({}), but got {} <= label_value <= {} '.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py in __impl__(self, other_var)
    248             axis = -1
    249             math_op = getattr(core.ops, op_type)
--> 250             return math_op(self, other_var, 'axis', axis)
    251 
    252         comment = OpProtoHolder.instance().get_op_proto(op_type).comment
SystemError: (Fatal) Operator less_than raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```

**Comment by joey12300** [comment]
@geekChinaMaster 看看完整代码？是不是前面pad_val没有设置13

**Comment by geekChinaMaster** [comment]
> @geekChinaMaster 看看完整代码？是不是前面pad_val没有设置13

谢谢您的解答，问题解决了~
确实，除了修改pad_val的修改和weight的修改，还需要在tag文件里面的最后加我们需要的pad_val值，这样就可以正确运行了

**Comment by sdwangqingru** [comment]
@geekChinaMaster 您好，以cityscapes数据集为例，label为0-18，要ignore的label是255。此时根据您的建议是ignore_index=19？
weight =19+1=20？
但是会出现以下问题：
(Pdb) n
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[8193] expected >= 0 and < 19, or == 19,but got 255. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[8193] expected >= 0 and < 19, or == 19,but got 255. Please check input value.
SystemError: (Fatal) Operator less_than raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
> /home/aistudio/work/PaddleSeg/paddleseg/models/losses/focal_loss.py(83)forward()
-> weight=self.weight)
(Pdb)

**Comment by sdwangqingru** [comment]
@geekChinaMaster 您好，以cityscapes数据集为例，label为0-18，要ignore的label是255。此时根据您的建议是ignore_index=19？
weight =19+1=20？
但是会出现以下问题：
(Pdb) n
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[8193] expected >= 0 and < 19, or == 19,but got 255. Please check input value.
Error: /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[8193] expected >= 0 and < 19, or == 19,but got 255. Please check input value.
SystemError: (Fatal) Operator less_than raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
> /home/aistudio/work/PaddleSeg/paddleseg/models/losses/focal_loss.py(83)forward()
-> weight=self.weight)
(Pdb)

**Comment by sdwangqingru** [comment]
已解决。
解决方法：将paddle由2.1.2升级到2.2.1版本即可，推测是官方在新版本中修复了该bug。
