### ISSUE TITLE
[Question]: 无法安装tool_helpers依赖

### ISSUE THREAD

**Issue by Alex37882388** [PaddlePaddle/PaddleNLP#8350]
### 请提出你的问题

ERROR: Could not find a version that satisfies the requirement tool_helpers (from versions: none)
我注意到pypi指向 [PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/data_tools/helpers.cpp) 的一个cpp文件，win11系统，paddlepaddle==2.6，我应该如何安装这个依赖呢？

**Comment by w5688414** [comment]
已修复，请参考：
https://github.com/PaddlePaddle/PaddleNLP/pull/8336
