### ISSUE TITLE
[Bug]: 汽车说明书跨模态智能问答例子报错

### ISSUE THREAD

**Issue by whysirier** [PaddlePaddle/PaddleNLP#8368]
### 软件环境

```Markdown
paddlepaddle == 2.3.2
paddlenlp == 2.5.2
paddleocr == 2.6.1.3
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
1. 如果版本是paddlepaddle是2.3.2， 则报错：这个错误 ModuleNotFoundError: No module named 'paddle.nn.layer.layers' 表示 Python 模块系统无法找到名为 'paddle.nn.layer.layers' 的模块。
2. 如果版本是paddlepaddle是最新版，则报错：通过上述步骤，你应该能够解决 ModuleNotFoundError: No module named 'paddle.fluid' 错误，并成功导入所需的 PaddlePaddle 模块。
```

### 稳定复现步骤 & 代码

究竟安装哪个版本才能运行该例子

**Comment by whysirier** [comment]
问了chatgpt也无法给出解决方案

**Comment by w5688414** [comment]
docvqa使用了fluid的API，建议使用PaddlePaddle 2.5.2以下的版本。

https://github.com/PaddlePaddle/PaddleNLP/blob/9f3cf822c669c0d97476e6ed96e2afcd6f8d57b5/applications/document_intelligence/doc_vqa/Extraction/model.py#L22C27-L22C32
