### ISSUE TITLE
[Question]: 对于paddlenlp模型库中不存在的大模型，但pytorch中已有实现，如何快速搭建模型？

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/PaddleNLP#8391]
### 请提出你的问题

1、请问有没有比较好的思路？

2、如果权重文件已经转换为paddle的形式，对于paddlenlp模型库中不存在的大模型，我们是否可以使用快速验证？
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/26a93b99-ffc1-4dff-b83c-78189ba5e67f)

3、将权重从pytorch转为paddle的格式，https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/convert_from_pytorch/nlp_fast_explore_cn.html#quanzhongzhuanhuan    
权重转换是根据这个文档操作吧？转换时遇到一个报错
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/1d58000b-6e17-40ca-b05c-d33a140533bb)

**Comment by ZHUI** [comment]
https://paddlenlp.readthedocs.io/zh/latest/llm/torch2paddle.html 试试这个教程

**Comment by zhaogf01** [comment]
> https://paddlenlp.readthedocs.io/zh/latest/llm/torch2paddle.html 试试这个教程
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/b85e54c3-6bc1-4d32-8f91-d054134cef7c)

会有这样的报错，请问您知道怎么回事吗？
而且我看这个链接下有一个支持的模型列表，我所需要转换的模型不在这个列表中，也可以使用这个脚本吗？

**Comment by zhaogf01** [comment]
还想请问一个问题，如何将pytorch中使用的.bin格式的权重转换为paddle中.safetensors格式的权重？
此外，sentencepiece.bpe.model应该如何转换的，或者如化生成的，这个文件的作用是什么？
