### ISSUE TITLE
[Question]: 进行实体抽取时，能否获得各个schema的bbox

### ISSUE THREAD

**Issue by huahuoer** [PaddlePaddle/PaddleNLP#8398]
### 请提出你的问题

![question](https://github.com/PaddlePaddle/PaddleNLP/assets/122615253/c0c7552f-df02-496c-a281-91b2a8cba587)
比如“件数”的bbox，或者其他任何schema的bbox

**Comment by w5688414** [comment]
没明白您的问题，这个输出里面有bbox，是想画在图片上吗？如果是这样的话，可以使用pillow或者opencv画一下方框
