### ISSUE TITLE
paddlenlp有没有处理加密文本的一套方案？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleNLP#84]
原始文本已经转为了数字，要从头训练模型，有没有处理这类问题的相关教程？

**Comment by ZeyuChen** [comment]
@bbbxixixixi 请问是那种NLP任务，文本分类还是文本匹配或者序列标注？

**Comment by bbbxixixixi** [comment]
> @bbbxixixixi 请问是那种NLP任务，文本分类还是文本匹配或者序列标注？

文本语义匹配和文本分类

**Comment by ZeyuChen** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1283423
@bbbxixixixi 可以了解下这个教程，里头有关于数据Pipeline的使用教程。
也可以使用ERNIE和BERT等预训练模型，这种方式建议使用明文的方式来输入，效果更好，无需考虑太多切词的复杂流程。
具体可以参考这个教程：https://aistudio.baidu.com/aistudio/projectdetail/1294333
