### ISSUE TITLE
[Question]: pipelines的faiss如何根据条件删除向量

### ISSUE THREAD

**Issue by MaxHouxu** [PaddlePaddle/PaddleNLP#8404]
### 请提出你的问题

delete_documents()中的filters如何使用？

**Comment by w5688414** [comment]
可以参考文档：

https://paddle-pipelines.readthedocs.io/en/latest/package/docstore/faiss/#pipelines.pipelines.document_stores.faiss.FAISSDocumentStore.delete_documents
