### ISSUE TITLE
如何对长文本进行抽取

### ISSUE THREAD

**Issue by minboo** [PaddlePaddle/PaddleNLP#8434]
### 问题描述

我的业务上有一个需求，就是将一篇完整的判决文书进行结构化分成小段，类似于分类，效果如下
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/69302396/de831e1d-8cc1-43fb-8efc-8ec3c415da8a)
我想问paddlenlp可以做到这样的抽取吗

**Comment by w5688414** [comment]
欢迎使用文心一言大模型，用小模型做比较麻烦，还包含很多hand engineering的内容

**Comment by minboo** [comment]
> 欢迎使用文心一言大模型，用小模型做比较麻烦，还包含很多hand engineering的内容

小模型做不到吗，必须要上大模型？

**Comment by w5688414** [comment]
小模型做比较麻烦，并且小模型的技术都陆续停止更新了。
