### ISSUE TITLE
uie可以做嵌套抽取吗？ 

### ISSUE THREAD

**Issue by gggdroa** [PaddlePaddle/PaddleNLP#8436]
### 问题描述

只能单关系吗？

**比如：**
schema = {'姓名': ['年龄', '住址', '性别', '检测指标']}
ie.set_schema(schema)
sen = """
张三,56岁，男，现住:北京
实验室及器械检查:血生化: 总胆固醇 3.81mmo1/d1，甘油三酯:2.07mmol/dl;血压180/110mmHg 心电图示:窦性心律过缓，心电轴正常:
"""
抽取结果如下：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/106646583/15d938f8-40fc-4bc1-badd-674815ba51ac)

**还想抽取到指标对应的值，比如：总胆固醇-指标值- 3.81mmo1/d1**  ，这个可以做到吗？

**Comment by w5688414** [comment]
不支持的，需要自己后处理，另外，推荐使用大模型

**Comment by gggdroa** [comment]
> 不支持的，需要自己后处理，另外，推荐使用大模型

'竞赛名称': ['主办方', '承办方', '已举办次数']  只能抽一个类别的关系吗？   大模型准确度也堪忧呀

**Comment by lastrei** [comment]
> > 不支持的，需要自己后处理，另外，推荐使用大模型
> 
> '竞赛名称': ['主办方', '承办方', '已举办次数'] 只能抽一个类别的关系吗？ 大模型准确度也堪忧呀

llm使用高质量prompts在单纯抽取方面可行，本地运行的小参数版本(2b，6b结合多agent亦可
