### ISSUE TITLE
文档公式有误

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/PaddleNLP#8441]
### 软件环境

```Markdown
- paddlepaddle:当前最新版
- paddlepaddle-gpu: 当前最新版
- paddlenlp: 当前最新版
有问题文档链接：https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.metrics.rouge.html
问题描述：这个公式给错了
好像不能上传图片，我就文字叙述了，上面链接给出了三个公式，其中第三个Flcs给错了，你们的形式和论文中的并不一样，也不等价，而我现在需要进行与其他模型进行rouge对比，无法使用该api。
```

### 详细描述

```Markdown
- paddlepaddle:当前最新版
- paddlepaddle-gpu: 当前最新版
- paddlenlp: 当前最新版
有问题文档链接：https://paddlenlp.readthedocs.io/zh/latest/source/paddlenlp.metrics.rouge.html
问题描述：这个公式给错了
好像不能上传图片，我就文字叙述了，上面链接给出了三个公式，其中第三个Flcs给错了，你们的形式和论文中的并不一样，也不等价，而我现在需要进行与其他模型进行rouge对比，无法使用该api。
```

**Comment by ZACP-DERMATOLOGY** [comment]
正确的公式应该是
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/48373656/ab846834-1649-49a3-b37a-068e44ebfb00)
这个才对

**Comment by ZACP-DERMATOLOGY** [comment]
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/48373656/4c395792-4537-4313-b4f1-099934647ba8)

上式是你们提供的计算公式，并不等价，我该怎么办呢？

**Comment by DesmonDay** [comment]
我确认一下实际实现是否是正确的吧

**Comment by DesmonDay** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/21eb6bdcac0d52c18fb8525dad6a2bb3680050d4/paddlenlp/metrics/rouge.py#L198 我们的实际实现其实是正确的，公式可能是之前同学在写的时候写错了。后续我们修改一下

**Comment by ZACP-DERMATOLOGY** [comment]
ok，感谢大佬，实现确实是对的
