### ISSUE TITLE
动态图参数导出为静态图参数时报错numpy.AxisError: axis 0 is out of bounds for array of dimension 0

### ISSUE THREAD

**Issue by ColaFei** [PaddlePaddle/PaddleNLP#848]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
-

**Comment by ColaFei** [comment]
paddle 版本：v2.1.0
paddlenlp：develop  147a943383efe23593c20d1d104a6c3591bd628b
模型：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/lexical_analysis
![image](https://user-images.githubusercontent.com/37499167/128177302-f7367770-9971-4917-bce3-3118fbec5597.png)

**Comment by ColaFei** [comment]
主要的修改是：paddle.reverse算子转paddlelite时候不支持，所以我自己重写了reverse函数，先把tensor转成numpy，flip之后再转成tensor
![image](https://user-images.githubusercontent.com/37499167/128179049-1f809aa2-e8fa-41a6-a434-97d5c412cf5d.png)

**Comment by joey12300** [comment]
@ColaFei 您好，动转静要求模型代码里面不能调用numpy的api。理论上你可以试试[paddle.flip](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flip_cn.html#flip)，看看能不能解决您的问题

**Comment by ColaFei** [comment]
@joey12300 就是想重写paddle.flip，不能调用这个算子

**Comment by joey12300** [comment]
@ColaFei 您好，请问您在什么平台上部署呢？paddlelite最近在develop合入了新的pr，支持reverse api，您试试使用develop分支能否成功部署？ PR：https://github.com/PaddlePaddle/Paddle-Lite/pull/6556

**Comment by ColaFei** [comment]
@joey12300 请问下：paddle.jit.save报这个错是什么原因啊？ValueError: Incompatible return values of true_fn and false_fn in cond: true_fn returns non-None while false_fn returns None

**Comment by joey12300** [comment]
> @joey12300 请问下：paddle.jit.save报这个错是什么原因啊？ValueError: Incompatible return values of true_fn and false_fn in cond: true_fn returns non-None while false_fn returns None

辛苦贴出可复现的代码或者关键的代码片段。

**Comment by ColaFei** [comment]
@joey12300 代码训练时重写了paddle.reverse
![image](https://user-images.githubusercontent.com/37499167/128306119-01cb282f-caf9-4267-9dc2-59c7dfdd2651.png)

**Comment by joey12300** [comment]
@ColaFei `if len(s) > axis` 假如这个分支条件不成立就返回了None值，无法进行动转静。尝试在else的时候返回一个out。

目前paddlelite在develop分支上已经支持reverse api，你可以试试使用paddlelite的develop版本看看能不能直接解决你的问题。

**Comment by ColaFei** [comment]
@joey12300  现在是支持reverse，但是部署会有空指针的报错

**Comment by joey12300** [comment]
> @joey12300 现在是支持reverse，但是部署会有空指针的报错

嗯嗯，你可以先试试自己实现的版本是否能解决你的问题。

另外，可以详细讲一下运行环境吗（硬件、操作系统（arm或者其他））？我将这个问题报给相关的人员排期解决。感谢反馈！

**Comment by ColaFei** [comment]
@joey12300 你好，再请教下哈，我把BiGruCrf中Gru换成lstm之后导出为静态图还是报错，麻烦帮忙看看啥原因呗，多谢！
![image](https://user-images.githubusercontent.com/37499167/128317595-0df49ca4-8d38-4ad5-a403-881249ebf15c.png)
