### ISSUE TITLE
[Bug]:UIE-X-base模型微调报错

### ISSUE THREAD

**Issue by lululiu2323** [PaddlePaddle/PaddleNLP#8489]
### 软件环境

```Markdown
- paddlepaddle:2.6.1
- paddlepaddle-gpu: A5000
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
我在使用UIE-X-base模型做微调时，报错如下： 
 File "/home/paddlepaddle/PaddleNLP-develop/model_zoo/uie/utils.py", line 673, in convert_example
    "token_type_ids": encoded_inputs["token_type_ids"],
KeyError: 'token_type_ids'
```

### 稳定复现步骤 & 代码

λ 0c5ed3f0e08d /home/paddlepaddle/PaddleNLP-develop/model_zoo/uie python finetune.py     --device gpu    --logging_steps 100    --save_steps 100    --eval_steps 25    --seed 42     --model_name_or_path /home/paddlepaddle/PaddleNLP-develop/model_zoo/uie/UIE-X-Base    --output_dir ./checkpointUieX/model_best  --train_path document/train.txt     --dev_path document/dev.txt      --per_device_train_batch_size  8     --per_device_eval_batch_size 8    --num_train_epochs 5     --learning_rate 1e-5     --label_names 'start_positions' 'end_positions'     --do_train    --do_eval     --do_export     --export_model_dir /home/paddlepaddle/PaddleNLP-develop/model_zoo/uie/UIE-X-Base    --overwrite_output_dir    --disable_tqdm True     --metric_for_best_model eval_f1    --load_best_model_at_end  True     --save_total_limit 1

**Comment by w5688414** [comment]
降低一下paddle版本试一下，比如2.5.2

**Comment by soooo6** [comment]
可以尝试使用applications/information_extraction/document默认用的uie-x-base，我在使用applications/information_extraction/text时遇到了你上述问题
