### ISSUE TITLE
[Question]: PaddleOCR detection and recognition models for PaddleNLP UIE

### ISSUE THREAD

**Issue by piarosebelledelapaz** [PaddlePaddle/PaddleNLP#8496]
### 请提出你的问题

is it possible to integrate paddleOCR detection and recognition models for UIE relation extraction model from paddleNLP? or how can we train paddleNLP ocr models to recognize text in different languages?

**Comment by w5688414** [comment]
we don't have much time to maintain UIE and PaddleOCR, but we will feel very thankful if you can contribute it, here are some materials:

1. https://github.com/PaddlePaddle/PaddleOCR/blob/92c59844f7d0c698e5a9a498399ec53a662e9a9f/doc/doc_en/training_en.md
2. https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/uie
