### ISSUE TITLE
导入paddlenlp后无法进入debug

### ISSUE THREAD

**Issue by zhoukaiwei66** [PaddlePaddle/PaddleNLP#850]
在python3.6，paddlenlp2.0.7环境下，当import paddlenlp后，无法进入debug，报错(<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'cv2'",), <traceback object at `0x000001DEA74F2B88>)，环境内没有安装也用不到opencv
代码为：
```
from paddlenlp.datasets import load_dataset
from paddlenlp.transformers import SkepForSequenceClassification, SkepTokenizer

model = SkepForSequenceClassification.from_pretrained('skep_ernie_1.0_large_ch')
tokenizer = SkepTokenizer.from_pretrained('skep_ernie_1.0_large_ch')
train_ds, dev_ds, test_ds = load_dataset("chnsenticorp", splits=["train", "dev", "test"])
```
望知道原因的的大哥们能指教一下

**Comment by wawltor** [comment]
你好，是如何进行debug的？

**Comment by zhoukaiwei66** [comment]
> 你好，是如何进行debug的？

我是在使用pddlenlp做情感分析的时候，发现打断点不能进debug的，然后就写了上面的几行代码，在model处打上断点，发现进不了断点。

**Comment by wawltor** [comment]
> > 你好，是如何进行debug的？
> 
> 我是在使用pddlenlp做情感分析的时候，发现打断点不能进debug的，然后就写了上面的几行代码，在model处打上断点，发现进不了断点。

具体是用了什么工具打了断点了，以及具体的PaddlePaddle的版本是什么？ 我这边尝试用了pdb之后是有没有这个问题的

**Comment by zhoukaiwei66** [comment]
> > > 你好，是如何进行debug的？
> > 
> > 
> > 我是在使用pddlenlp做情感分析的时候，发现打断点不能进debug的，然后就写了上面的几行代码，在model处打上断点，发现进不了断点。
> 
> 具体是用了什么工具打了断点了，以及具体的PaddlePaddle的版本是什么？ 我这边尝试用了pdb之后是有没有这个问题的

很奇怪，我给opencv安装上居然就好了，但是我没有用到opencv，不知道哪里出了问题，用的pycharm打的断点，paddlepaddle版本为2.1.0，但是总归是解决了，多谢大哥
