### ISSUE TITLE
[Bug]: Temperature参数似乎没有生效

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/PaddleNLP#8500]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 
- paddlenlp:
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
https://github.com/PaddlePaddle/PaddleNLP/blob/d4edd19194aef7ce8f9fee936395bc279b2fd606/paddlenlp/experimental/transformers/generation_utils.py#L330-335

先计算了softmax，然后才对logit除以temperature，实质上temperature参数未生效
```

### 稳定复现步骤 & 代码

-

**Comment by parap1uie-s** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/d4edd19194aef7ce8f9fee936395bc279b2fd606/paddlenlp/experimental/transformers/generation_utils.py#L330-L335

**Comment by w5688414** [comment]
请参考huggingface的配置：

https://github.com/huggingface/transformers/blob/9d35edbb30625489bf286a9b15aed0c5a3119c1c/src/transformers/generation/logits_process.py#L291

```
Strictly positive float value used to modulate the logits distribution. A value smaller than `1` decreases
            randomness (and vice versa), with `0` being equivalent to shifting all probability mass to the most likely
            token.
```

**Comment by ZHUI** [comment]
嗯嗯，好像有问题。这个是我们原版代码
https://github.com/PaddlePaddle/PaddleNLP/blob/d4edd19194aef7ce8f9fee936395bc279b2fd606/paddlenlp/generation/utils.py#L1202-L1212

**Comment by carryyu** [comment]
一般情况下这里是走不到的，我们会走到GenerationBlockInferenceModel这个类，逻辑与原版是对齐的；

这里也提了PR进行修复：https://github.com/PaddlePaddle/PaddleNLP/pull/8502

感谢～

**Comment by parap1uie-s** [comment]
> 一般情况下这里是走不到的，我们会走到GenerationBlockInferenceModel这个类，逻辑与原版是对齐的；
> 
> 这里也提了PR进行修复：#8502
> 
> 感谢～

这个PR好像还没有通过
