### ISSUE TITLE
[Question]:如何设置多卡pipline并行推理？

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/PaddleNLP#8501]
### 请提出你的问题

 strategy = fleet.DistributedStrategy()
 strategy.hybrid_configs = {
                 "dp_degree": 1,
                "mp_degree": 1,
                "pp_degree": 4,
                 "sharding_degree": 1,
            }
 fleet.init(is_collective=True, strategy=strategy)
 hcg = fleet.get_hybrid_communicate_group()
 tensor_parallel_rank = hcg.get_model_parallel_rank()
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(model_path, tensor_parallel_rank=tensor_parallel_rank, dtype="float32")

python  -m paddle.distributed.launch \
    --devices "12,13,14,15" \
    test.py \

我采用了这种方式，但从显存占用上来看好像是开启了数据并行，并未开启流水线并行。请问如何开启流水线并行

**Comment by gongel** [comment]
不建议用流水线并行来进行推理，比较复杂。

**Comment by zhaogf01** [comment]
> 不建议用流水线并行来进行推理，比较复杂。
复杂没关系，
有相关示例吗？
