### ISSUE TITLE
paddlepaddle/paddle:2.6.1-gpu-cuda11.2-cudnn8.2-trt8.0容器太大了多大21G，有什么办法进行瘦身

### ISSUE THREAD

**Issue by watertianyi** [PaddlePaddle/PaddleNLP#8506]
### 请提出你的问题

paddlepaddle/paddle:2.6.1-gpu-cuda11.2-cudnn8.2-trt8.0容器太大了多大21G，有什么办法进行瘦身

**Comment by w5688414** [comment]
可以使用cpu的docker。另外，可以在paddle的框架下面提这个issue哈。

https://github.com/PaddlePaddle/Paddle

**Comment by DrownFish19** [comment]
补充方法：使用runtime类型的docker，重新安装paddle，可以实现一定减小，不过不方便开发使用。
```bash
docker pull nvidia/cuda:11.8.0-runtime-ubuntu22.04
```
