### ISSUE TITLE
UIE-X训练时候支持自定义OCR

### ISSUE THREAD

**Issue by tianchiguaixia** [PaddlePaddle/PaddleNLP#8520]
### Feature request

训练时候，可以提供自定义ocr结果训练，而不是paddleocr的结果

### Motivation

因为paddleocr文字识别很差，使用这个训练不好

### Your contribution

暂时没有

**Comment by w5688414** [comment]
目前uie-x因为人力紧张，已经停止更新，欢迎开发者贡献。

**Comment by tianchiguaixia** [comment]
暂时贡献不了，老是报错。希望你们添加字符集的ocr训练
