### ISSUE TITLE
[Question]: 在语义检索中使用in batch negative训练

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#8525]
### 请提出你的问题

在语义检索中使用in batch negative训练，使用大batch size 会显著提升模型效果，但显存资源有限，会out of memory。请问有什么方法可以在显存资源有限情况下，提高batch size，增强模型效果

**Comment by w5688414** [comment]
可以使用recompute, gradientcache等技术
