### ISSUE TITLE
[Question]: 关于微调和推理时max_seq_len参数的设置问题

### ISSUE THREAD

**Issue by ZHANG-GangHan** [PaddlePaddle/PaddleNLP#8537]
### 请提出你的问题

我这边需要对长文本数据（长度都大于5000）进行微调，在微调时设置了max_seq_len参数为1536，微调过程中打印出来的各项指标也不会很差，有80%左右。在推理的时候，给TaskFlow的初始化参数max_seq_len也设置为1536，但返回的结果是空的，设置为512便能返回正常的结果

**Comment by yangguoer** [comment]
> ### 请提出你的问题
> 我这边需要对长文本数据（长度都大于5000）进行微调，在微调时设置了max_seq_len参数为1536，微调过程中打印出来的各项指标也不会很差，有80%左右。在推理的时候，给TaskFlow的初始化参数max_seq_len也设置为1536，但返回的结果是空的，设置为512便能返回正常的结果

请问解决了吗，我也遇到了长度的问题
