### ISSUE TITLE
text_summarization文本摘要算法分布式训练错误

### ISSUE THREAD

**Issue by Avalon244** [PaddlePaddle/PaddleNLP#855]
- 版本、环境信息
1）PaddleNLP 2.0.3，PaddlePaddle2.1.0
2）系统环境：请您描述系统类型，例如Linux，python版本3.7.5
- 复现信息：在docker容器里使用text_summarization的train.py进行分布式训练，指令为python -m paddle.distributed.launch --gpus=0,1 train.py，,在log文件中生成的workerlog.1中报错：(Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor.

**Comment by wawltor** [comment]
看起来你安装的版本是一个cpu的版本，可以尝试安装一下GPU版本

**Comment by wawltor** [comment]
> 看起来你安装的版本是一个cpu的版本，可以尝试安装一下GPU版本

**Comment by wawltor** [comment]
> 看起来你安装的版本是一个cpu的版本，可以尝试安装一下GPU版本

**Comment by Avalon244** [comment]
> 看起来你安装的版本是一个cpu的版本，可以尝试安装一下GPU版本

版本没写清楚，是paddlepadfle-gpu2.1.0post101

**Comment by gongel** [comment]
1. 麻烦看一下你的cuda版本，参照官网安装PaddlePaddle：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
2. 另外麻烦你单卡试试看，并提供完整的错误截图。

**Comment by Avalon244** [comment]
> 
> 
>     1. 麻烦看一下你的cuda版本，参照官网安装PaddlePaddle：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> 
>     2. 另外麻烦你单卡试试看，并提供完整的错误截图。

> cuda应该是正常安装的，因为之前跑别的也没有问题，单机也能跑。对原始文件增加fleet.init()等操作后再运行是可以正常跑的，但是感觉是两个worker各跑各的，各自保存了模型。未对源码做修改，直接使用paddle.distributed.launch的报错如图
![e82b0d610c69a0d0455e37c8988ff3b](https://user-images.githubusercontent.com/54314261/128585676-875ecc23-1e45-47ec-b88c-b3209036f48f.jpg)
![9ba6d920f493d4d913cc5fb22dcba5f](https://user-images.githubusercontent.com/54314261/128585682-6efce625-e738-408a-80f2-391b58987abb.jpg)

**Comment by gongel** [comment]
你好，目前已确认，train.py目前没有实现多卡训练。如需多卡，模型层面需要加`paddle.DataParallel`，可参考：[here](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/train.py#L100)，数据层面batch sampler需要加`shard`，可参考：[here](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/simultaneous_translation/stacl/reader.py#L110)

**Comment by chenxiaozeng** [comment]
@Avalon244 您好，根据你提出的需求，我们想进一步和您沟通下需求背景以及使用场景，以便更好得解答您的问题。这是我们的联系方式：邮箱paddlenlp@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
