### ISSUE TITLE
[Bug]: llm merge_lora_params 合并后不保存 merge权重

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleNLP#8575]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu:  develop 
- paddlenlp: lastest 162d8d31c84f60b804a0abeee8f4f1e4b32308ef
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
使用 llm merge_lora_params.py，合并一个 QLora 训练好的模型，但是没有合并后的模型结果，输出文件夹什么都没出现
```

### 稳定复现步骤 & 代码

python merge_lora_params.py \
    --model_name_or_path FlagAlpha/Llama2-Chinese-7b-Chat \
    --lora_path /home/aistudio/data/checkpoints/llama_lora_ckpts/checkpoint-286 \
    --merge_lora_model_path /home/aistudio/data/llama_lora_merge \
    --device "gpu" \
    --low_gpu_mem True

似乎一直卡在加载的阶段，然后过一阵子后直接结束进程。（怀疑内存不够，但应该不至于吧 ，aistudio 32g v100 开发机）

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/96160062/480f1398-9879-40cc-9c0c-b6f481042856)

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/96160062/e5da0200-81b1-44c3-a7ce-c36d28759adf)

但并非是 lora 问题，因为可以动态图加载推理

```python
python predictor.py --model_name_or_path FlagAlpha/Llama2-Chinese-7b-Chat \
                    --data_file /home/aistudio/data/dummy/dev.json --dtype float16 \
                    --lora_path /home/aistudio/data/checkpoints/llama_lora_ckpts/checkpoint-286
```

**Comment by DesmonDay** [comment]
<img width="681" alt="截屏2024-06-12 13 48 44" src="https://github.com/PaddlePaddle/PaddleNLP/assets/20554008/80d66537-3f4d-474d-9506-2435ac2725fc">

能否把代码单独拎出来，如果你只是加载llama参数可以正常加载么？from_pretrained。

**Comment by sanbuphy** [comment]
> <img alt="截屏2024-06-12 13 48 44" width="681" src="https://private-user-images.githubusercontent.com/20554008/338838067-80d66537-3f4d-474d-9506-2435ac2725fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzU3MDQsIm5iZiI6MTcxODE3NTQwNCwicGF0aCI6Ii8yMDU1NDAwOC8zMzg4MzgwNjctODBkNjY1MzctM2Y0ZC00NzRkLTk1MDYtMjQzNWFjMjcyNWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA2NTY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNGIyM2ZhMTY5ZTBmMWE2ZDMxNzFhNTA1YmIwN2EyMmE2YmE5ZWZhYzgyYWIyYTVlYWMwZjM3Yjk2YTM3OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AhSItaYdoYFI2Jp93qNf40cG9OVgMrVTmSWIEis3BjY">
> 能否把代码单独拎出来，如果你只是加载llama参数可以正常加载么？from_pretrained。

我试试看，不过我怀疑是直接被kill了 ，不过不至于 32G都不够用？ 很神奇

**Comment by DesmonDay** [comment]
嗯嗯，Killed不排除你环境问题，可能是有别人也在使用机器。

**Comment by sanbuphy** [comment]
> 嗯嗯，Killed不排除你环境问题，可能是有别人也在使用机器。

我知道问题在哪了。带上 model_name_or_path 字段就不能正常保存，只会存一个 json；

去掉后就可以正常 merge， Qlora应该不会对这个有影响吧；感觉是 字段导致的问题
