### ISSUE TITLE
[Question]: 在aistudio上执行精调Llama-2-7b-chat时，执行单卡训练命令，出现分布式的错误

### ISSUE THREAD

**Issue by Farewell-CK** [PaddlePaddle/PaddleNLP#8576]
### 请提出你的问题

执行命令如下：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/101492509/6b1636e4-c64b-48cf-995e-f76b7c8efc0f)
出现如下问题：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/101492509/45122758-acc0-4704-a956-6808078801c5)

========================
环境：PaddlePaddle 2.6.1 
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/101492509/f147bd2e-a633-4423-8c5a-14dc35c672d1)
部分pip安装的包版本：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/101492509/e85ba2f4-f5c1-48e8-89a9-03a33183ee61)
非常期待诸位的回复

**Comment by DrownFish19** [comment]
在aistudio上暂时无法复现问题。
是不是在`./llama/lora_argument.json`中有修改parallel相关设置？如没有，能否提供复现脚本和配置文件？

**Comment by DesmonDay** [comment]
@8baby8 想问问你的代码是什么时候的？这个问题我们在这个PR已修复：https://github.com/PaddlePaddle/PaddleNLP/pull/8549/files

**Comment by Farewell-CK** [comment]
我再git一下新的试试~ 应该是上周三的代码。谢谢佬~&nbsp;


My,drame
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月12日(星期三) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Question]: 在aistudio上执行精调Llama-2-7b-chat时，执行单卡训练命令，出现分布式的错误 (Issue #8576)














 
@8baby8 想问问你的代码是什么时候的？这个问题我们在这个PR已修复：https://github.com/PaddlePaddle/PaddleNLP/pull/8549/files

**Comment by Farewell-CK** [comment]
佬~ 不好意思又麻烦您了。我在studio上执行到推理那一块了出现了如下错误，我刚在paddle仓库下看了个issue 说是paddle应该用develop版本的才可以。
那我想问下如何在studio上如何使用develop版本的paddle&nbsp;






My,drame
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] [Question]: 在aistudio上执行精调Llama-2-7b-chat时，执行单卡训练命令，出现分布式的错误 (Issue #8576)





 
@8baby8 想问问你的代码是什么时候的？这个问题我们在这个PR已修复：https://github.com/PaddlePaddle/PaddleNLP/pull/8549/files

**Comment by DrownFish19** [comment]
当前查询aistudio中cuda版本为11.8（具体环境请自行检查），可以先卸载paddle-2.6.1，后安装develop版本。
具体命令可以参考官网，选择develop (Nightly build)，linux， cuda11.8，如下：
```bash
python -m pip install paddlepaddle-gpu==0.0.0.post118 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
```
