### ISSUE TITLE
[Bug]: AutoModelForCausalLM.from_pretrained 转换 huggingface 模型显存不足

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/PaddleNLP#8578]
### 软件环境

```Markdown
- paddlepaddle: 
- paddlepaddle-gpu:  develop 
- paddlenlp: lastest 162d8d31c84f60b804a0abeee8f4f1e4b32308ef
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
想要使用llama3-8B 以及 qwen2，但是发现在V100 32G上进行转换，显存不够用。。。请问有cpu上转换的方法吗？或者说是否能估算出需要多少显存进行转换呢？谢谢！(官方资源库里应该没有覆盖这个预转换
```

### 稳定复现步骤 & 代码

```
huggingface-cli download FlagAlpha/Llama3-Chinese-8B-Instruct --local-dir=/home/aistudio/data/llama3 --local-dir-use-symlinks=False --resume-download
```
```
from paddlenlp.transformers import AutoModelForCausalLM
AutoModelForCausalLM.from_pretrained("/home/aistudio/Sdata/llama3", convert_from_torch=True, dtype="float16")
```

**Comment by DrownFish19** [comment]
后续会支持自动转换模型参数，当前先给出转换脚本，临时使用。具体使用步骤根据模型不同，需要进行修改，请参考以下说明：

1. 模型前缀。paddlenlp中使用的模型前缀为模型名称，例如Qwen2使用qwen2.，LLaMA使用llama.，HF使用的model.或者transformer.。可查看paddlenlp.transformers.XXX.modeling.LlamaPretrainedModel中的base_model_prefix。
2. linear参数转置。Paddle和torch的linear实现不同，参数互为转置关系。需根据不同模型进行判断，具体可查找paddlenlp.transformers.XXX.modeling.XXXPretrainedModel中的mappings参数，其标注了需要进行转置的参数。例如llama模型为paddlenlp.transformers.llama.modeling.LlamaPretrainedModel

脚本：https://gist.github.com/DrownFish19/80b43383c9205ee1cf7cf35445009488

**Comment by sanbuphy** [comment]
> 后续会支持自动转换模型参数，当前先给出转换脚本，临时使用。具体使用步骤根据模型不同，需要进行修改，请参考以下说明：
> 
> 1. 模型前缀。paddlenlp中使用的模型前缀为模型名称，例如Qwen2使用qwen2.，LLaMA使用llama.，HF使用的model.或者transformer.。可查看paddlenlp.transformers.XXX.modeling.LlamaPretrainedModel中的base_model_prefix。
> 2. linear参数转置。Paddle和torch的linear实现不同，参数互为转置关系。需根据不同模型进行判断，具体可查找paddlenlp.transformers.XXX.modeling.XXXPretrainedModel中的mappings参数，其标注了需要进行转置的参数。例如llama模型为paddlenlp.transformers.llama.modeling.LlamaPretrainedModel
> 
> 脚本：https://gist.github.com/DrownFish19/80b43383c9205ee1cf7cf35445009488

Thanks !
