### ISSUE TITLE
[Question]: 进行chatglm2 lora微调时，设置pipeline parallel:4，报错 module 'paddlenlp.transformers.chatglm_v2.modeling' has no attribute 'ChatGLMv2ForCausalLMPipe'

### ISSUE THREAD

**Issue by shanyuaa** [PaddlePaddle/PaddleNLP#8593]
### 请提出你的问题

- 前提条件：单机单卡已经跑通chatglm2的lora微调训练代码；llama的多卡pp并行训练已跑通。

- 问题场景：想进一步尝试单机多卡，设置/chatglm2/lora_argument.json配置文件中的 "pipeline_parallel_degree": 4，然后参照官网样例，启动命令行：`srun --gres=gpu:4 python3 -u  -m paddle.distributed.launch --gpus "0,1,2,3" finetune_generation.py ./chatglm2/lora_argument.json`

- 所遇问题：跑chatglm2的多卡pp并行时会报错找不到ChatGLMv2ForCausalLMPipe类，错误代码行显示在：
 ```
File "/home/LAB/wangzy/paddle/PaddleNLP/llm/finetune_generation.py", line 183, in main
    model = AutoModelForCausalLMPipe.from_pretrained(
```

**Q：请问paddlenlp支持chatglm2的pp并行/tp并行策略吗？以及如何解决该问题？（错误截图如下）谢谢！**

<img width="793" alt="截屏2024-06-13 00 20 09" src="https://github.com/PaddlePaddle/PaddleNLP/assets/54535300/ebfde875-6e23-4895-8db7-7d053e8934dd">
<img width="792" alt="截屏2024-06-13 00 20 26" src="https://github.com/PaddlePaddle/PaddleNLP/assets/54535300/b41f5971-313e-482d-9826-3828335c752a">

**Comment by DrownFish19** [comment]
当前chatglm_v2当前未接入TP/PP

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。

**Comment by shanyuaa** [comment]
你好，我已收到信件，在阅读后会尽快给回复。祝好。
