### ISSUE TITLE
run_ernie_crf.py最新代码训练过程中loss变为0了

### ISSUE THREAD

**Issue by ImComingyo** [PaddlePaddle/PaddleNLP#860]
All required modules installed.
[TRAIN] Epoch:0 - Step:1 - Loss: 77.990662
[TRAIN] Epoch:0 - Step:2 - Loss: 85.036980
[TRAIN] Epoch:0 - Step:3 - Loss: 75.353294
[TRAIN] Epoch:0 - Step:4 - Loss: 77.342087
[TRAIN] Epoch:0 - Step:5 - Loss: 62.213589
[TRAIN] Epoch:0 - Step:6 - Loss: 54.894947
[TRAIN] Epoch:0 - Step:7 - Loss: 52.430214
[TRAIN] Epoch:0 - Step:8 - Loss: 50.360401
[TRAIN] Epoch:0 - Step:9 - Loss: 44.065796
[TRAIN] Epoch:0 - Step:10 - Loss: 41.043488
[TRAIN] Epoch:0 - Step:11 - Loss: 40.073395
[TRAIN] Epoch:0 - Step:12 - Loss: 38.306221
[TRAIN] Epoch:0 - Step:13 - Loss: 30.485165
[TRAIN] Epoch:0 - Step:14 - Loss: 30.255508
[TRAIN] Epoch:0 - Step:15 - Loss: 24.963469
[TRAIN] Epoch:0 - Step:16 - Loss: 32.179306
[TRAIN] Epoch:0 - Step:17 - Loss: 25.288597
[TRAIN] Epoch:0 - Step:18 - Loss: 38.880569
[TRAIN] Epoch:0 - Step:19 - Loss: 23.920746
[TRAIN] Epoch:0 - Step:20 - Loss: 27.521164
[TRAIN] Epoch:0 - Step:21 - Loss: 27.588886
[TRAIN] Epoch:0 - Step:22 - Loss: 29.162006
[TRAIN] Epoch:0 - Step:23 - Loss: 30.821171
[TRAIN] Epoch:0 - Step:24 - Loss: 23.041290
[TRAIN] Epoch:0 - Step:25 - Loss: 28.937603
[TRAIN] Epoch:0 - Step:26 - Loss: 19.745628
[TRAIN] Epoch:0 - Step:27 - Loss: 18.543766
[TRAIN] Epoch:0 - Step:28 - Loss: 26.770668
[TRAIN] Epoch:0 - Step:29 - Loss: 25.095497
[TRAIN] Epoch:0 - Step:30 - Loss: 22.306688
[TRAIN] Epoch:0 - Step:31 - Loss: 25.539768
[TRAIN] Epoch:0 - Step:32 - Loss: 18.044374
[TRAIN] Epoch:0 - Step:33 - Loss: 24.411209
[TRAIN] Epoch:0 - Step:34 - Loss: 21.527960
[TRAIN] Epoch:0 - Step:35 - Loss: 22.886284
[TRAIN] Epoch:0 - Step:36 - Loss: 22.142139
[TRAIN] Epoch:0 - Step:37 - Loss: 17.632294
[TRAIN] Epoch:0 - Step:38 - Loss: 20.936903
[TRAIN] Epoch:0 - Step:39 - Loss: 22.378334
[TRAIN] Epoch:0 - Step:40 - Loss: 20.694481
[TRAIN] Epoch:0 - Step:41 - Loss: 20.938242
[TRAIN] Epoch:0 - Step:42 - Loss: 19.018227
[TRAIN] Epoch:0 - Step:43 - Loss: 27.266531
[TRAIN] Epoch:0 - Step:44 - Loss: 16.735725
[TRAIN] Epoch:0 - Step:45 - Loss: 17.264526
[TRAIN] Epoch:0 - Step:46 - Loss: 16.398335
[TRAIN] Epoch:0 - Step:47 - Loss: 16.198792
[TRAIN] Epoch:0 - Step:48 - Loss: 15.761089
[TRAIN] Epoch:0 - Step:49 - Loss: 19.724930
[TRAIN] Epoch:0 - Step:50 - Loss: 13.213045
[TRAIN] Epoch:0 - Step:51 - Loss: 13.686309
[TRAIN] Epoch:0 - Step:52 - Loss: 15.416010
[TRAIN] Epoch:0 - Step:53 - Loss: 23.911816
[TRAIN] Epoch:0 - Step:54 - Loss: 14.244841
[TRAIN] Epoch:0 - Step:55 - Loss: 17.870157
[TRAIN] Epoch:0 - Step:56 - Loss: 13.628450
[TRAIN] Epoch:0 - Step:57 - Loss: 14.805258
[TRAIN] Epoch:0 - Step:58 - Loss: 23.238861
………………
[TRAIN] Epoch:0 - Step:7797 - Loss: 0.000000
[TRAIN] Epoch:0 - Step:7798 - Loss: 0.075277
[TRAIN] Epoch:0 - Step:7799 - Loss: 0.017018
[TRAIN] Epoch:0 - Step:7800 - Loss: 0.014934
[TRAIN] Epoch:0 - Step:7801 - Loss: 0.065942
[TRAIN] Epoch:0 - Step:7802 - Loss: 0.150444
[TRAIN] Epoch:0 - Step:7803 - Loss: 0.008615
[TRAIN] Epoch:0 - Step:7804 - Loss: 0.128409
[TRAIN] Epoch:0 - Step:7805 - Loss: 0.090106
[TRAIN] Epoch:0 - Step:7806 - Loss: 0.050090
[TRAIN] Epoch:0 - Step:7807 - Loss: 0.024830
[TRAIN] Epoch:0 - Step:7808 - Loss: 0.019273
[TRAIN] Epoch:0 - Step:7809 - Loss: 0.008083
[TRAIN] Epoch:0 - Step:7810 - Loss: 0.028684
[TRAIN] Epoch:0 - Step:7811 - Loss: 0.000000
[TRAIN] Epoch:0 - Step:7812 - Loss: 0.000000
[TRAIN] Epoch:0 - Step:7813 - Loss: 0.020308
[TRAIN] Epoch:0 - Step:7814 - Loss: 0.051970
[TRAIN] Epoch:0 - Step:7815 - Loss: 0.028791
[TRAIN] Epoch:0 - Step:7816 - Loss: 0.005758
[TRAIN] Epoch:0 - Step:7817 - Loss: 0.017688
[TRAIN] Epoch:0 - Step:7818 - Loss: 0.879222

训练过程loss变为0了，precision和F1都狠差，请问这是什么原因呢？
但是用run_ernie.py是没问题的。

**Comment by joey12300** [comment]
@ImComingyo 您好，请问是哪个项目？

**Comment by ImComingyo** [comment]
> @ImComingyo 您好，请问是哪个项目？

https://github.com/PaddlePaddle/PaddleNLP/tree/28a95901ea107a65bdf3bf5d5d2c37998ee8f7e9/examples/information_extraction/waybill_ie
是这个，麻烦帮看看吧

**Comment by joey12300** [comment]
您好，请问您的paddle版本以及paddlenlp版本是多少？我这边复现的环境是：
```
paddlepaddle-gpu: 2.1.1
paddlenlp: 2.0.8
```

我运行的命令为：`python run_ernie_crf.py`，从结果来看loss和F1值都挺正常的。

日志如下：
```
W0809 10:17:52.674479 26598 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0809 10:17:52.680492 26598 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[TRAIN] Epoch:0 - Step:1 - Loss: 108.525391
[TRAIN] Epoch:0 - Step:2 - Loss: 101.100555
[TRAIN] Epoch:0 - Step:3 - Loss: 90.237144
[TRAIN] Epoch:0 - Step:4 - Loss: 85.194283
[TRAIN] Epoch:0 - Step:5 - Loss: 78.866997
[TRAIN] Epoch:0 - Step:6 - Loss: 74.022293
[TRAIN] Epoch:0 - Step:7 - Loss: 69.617622
[TRAIN] Epoch:0 - Step:8 - Loss: 65.385666
[EVAL] Precision: 0.032564 - Recall: 0.040370 - F1: 0.036050
[TRAIN] Epoch:1 - Step:9 - Loss: 62.513165
[TRAIN] Epoch:1 - Step:10 - Loss: 60.184441
[TRAIN] Epoch:1 - Step:11 - Loss: 55.425217
[TRAIN] Epoch:1 - Step:12 - Loss: 53.711914
[TRAIN] Epoch:1 - Step:13 - Loss: 50.705132
[TRAIN] Epoch:1 - Step:14 - Loss: 48.516304
[TRAIN] Epoch:1 - Step:15 - Loss: 46.660706
[TRAIN] Epoch:1 - Step:16 - Loss: 44.153160
[EVAL] Precision: 0.121156 - Recall: 0.109336 - F1: 0.114943
[TRAIN] Epoch:2 - Step:17 - Loss: 42.454868
[TRAIN] Epoch:2 - Step:18 - Loss: 40.662781
[TRAIN] Epoch:2 - Step:19 - Loss: 37.678467
[TRAIN] Epoch:2 - Step:20 - Loss: 36.359745
[TRAIN] Epoch:2 - Step:21 - Loss: 34.177010
[TRAIN] Epoch:2 - Step:22 - Loss: 32.602493
[TRAIN] Epoch:2 - Step:23 - Loss: 31.111809
[TRAIN] Epoch:2 - Step:24 - Loss: 28.794855
[EVAL] Precision: 0.676471 - Recall: 0.715728 - F1: 0.695546
[TRAIN] Epoch:3 - Step:25 - Loss: 27.515997
[TRAIN] Epoch:3 - Step:26 - Loss: 25.893497
[TRAIN] Epoch:3 - Step:27 - Loss: 23.757687
[TRAIN] Epoch:3 - Step:28 - Loss: 22.417593
[TRAIN] Epoch:3 - Step:29 - Loss: 21.192295
[TRAIN] Epoch:3 - Step:30 - Loss: 19.795197
[TRAIN] Epoch:3 - Step:31 - Loss: 18.614086
[TRAIN] Epoch:3 - Step:32 - Loss: 17.097870
[EVAL] Precision: 0.920165 - Recall: 0.940286 - F1: 0.930116
[TRAIN] Epoch:4 - Step:33 - Loss: 16.396446
[TRAIN] Epoch:4 - Step:34 - Loss: 15.093613
[TRAIN] Epoch:4 - Step:35 - Loss: 13.786798
[TRAIN] Epoch:4 - Step:36 - Loss: 12.562286
[TRAIN] Epoch:4 - Step:37 - Loss: 11.924860
[TRAIN] Epoch:4 - Step:38 - Loss: 10.784462
[TRAIN] Epoch:4 - Step:39 - Loss: 9.746884
[TRAIN] Epoch:4 - Step:40 - Loss: 8.946723
[EVAL] Precision: 0.941371 - Recall: 0.958789 - F1: 0.950000
[TRAIN] Epoch:5 - Step:41 - Loss: 8.279366
[TRAIN] Epoch:5 - Step:42 - Loss: 7.477924
[TRAIN] Epoch:5 - Step:43 - Loss: 6.782437
[TRAIN] Epoch:5 - Step:44 - Loss: 5.934315
[TRAIN] Epoch:5 - Step:45 - Loss: 5.926703
[TRAIN] Epoch:5 - Step:46 - Loss: 5.250775
[TRAIN] Epoch:5 - Step:47 - Loss: 4.429095
[TRAIN] Epoch:5 - Step:48 - Loss: 3.873993
[EVAL] Precision: 0.951118 - Recall: 0.965517 - F1: 0.958264
[TRAIN] Epoch:6 - Step:49 - Loss: 3.708544
[TRAIN] Epoch:6 - Step:50 - Loss: 3.104369
[TRAIN] Epoch:6 - Step:51 - Loss: 2.711524
[TRAIN] Epoch:6 - Step:52 - Loss: 2.164511
[TRAIN] Epoch:6 - Step:53 - Loss: 2.484719
[TRAIN] Epoch:6 - Step:54 - Loss: 1.754705
[TRAIN] Epoch:6 - Step:55 - Loss: 1.351668
[TRAIN] Epoch:6 - Step:56 - Loss: 1.181521
[EVAL] Precision: 0.964226 - Recall: 0.974769 - F1: 0.969469
[TRAIN] Epoch:7 - Step:57 - Loss: 1.019193
[TRAIN] Epoch:7 - Step:58 - Loss: 0.797387
[TRAIN] Epoch:7 - Step:59 - Loss: 0.889881
[TRAIN] Epoch:7 - Step:60 - Loss: 0.744268
[TRAIN] Epoch:7 - Step:61 - Loss: 0.905669
[TRAIN] Epoch:7 - Step:62 - Loss: 0.552196
[TRAIN] Epoch:7 - Step:63 - Loss: 0.433461
[TRAIN] Epoch:7 - Step:64 - Loss: 0.420233
[EVAL] Precision: 0.970858 - Recall: 0.980656 - F1: 0.975732
[TRAIN] Epoch:8 - Step:65 - Loss: 0.367983
[TRAIN] Epoch:8 - Step:66 - Loss: 0.290611
[TRAIN] Epoch:8 - Step:67 - Loss: 0.315963
[TRAIN] Epoch:8 - Step:68 - Loss: 0.426605
[TRAIN] Epoch:8 - Step:69 - Loss: 0.562480
[TRAIN] Epoch:8 - Step:70 - Loss: 0.401650
[TRAIN] Epoch:8 - Step:71 - Loss: 0.282679
[TRAIN] Epoch:8 - Step:72 - Loss: 0.332794
[EVAL] Precision: 0.975813 - Recall: 0.984020 - F1: 0.979899
[TRAIN] Epoch:9 - Step:73 - Loss: 0.151925
[TRAIN] Epoch:9 - Step:74 - Loss: 0.180754
[TRAIN] Epoch:9 - Step:75 - Loss: 0.176573
[TRAIN] Epoch:9 - Step:76 - Loss: 0.333212
[TRAIN] Epoch:9 - Step:77 - Loss: 0.340979
[TRAIN] Epoch:9 - Step:78 - Loss: 0.293251
[TRAIN] Epoch:9 - Step:79 - Loss: 0.234918
[TRAIN] Epoch:9 - Step:80 - Loss: 0.310234
[EVAL] Precision: 0.982456 - Recall: 0.989066 - F1: 0.985750
The results have been saved in the file: ernie_crf_results.txt, some examples are shown below: 
('黑龙江省', 'A1')('双鸭山市', 'A2')('尖山区', 'A3')('八马路与东平行路交叉口北40米', 'A4')('韦业涛', 'P')('18600009172', 'T')
('广西壮族自治区', 'A1')('桂林市', 'A2')('雁山区', 'A3')('雁山镇西龙村老年活动中心', 'A4')('17610348888', 'T')('羊卓卫', 'P')
('15652864561', 'T')('河南省', 'A1')('开封市', 'A2')('顺河回族区', 'A3')('顺河区', 'A4')('公园路32号', 'A4')('赵本山', 'P')
('河北省', 'A1')('唐山市', 'A2')('玉田县', 'A3')('无终大街159号', 'A4')('18614253058', 'T')('尚汉生', 'P')
('台湾', 'A1')('台中市', 'A2')('北区', 'A3')('北区锦新街18号', 'A4')('18511226708', 'T')('蓟丽', 'P')
('廖梓琪', 'P')('18514743222', 'T')('湖北省', 'A1')('宜昌市', 'A2')('长阳土家族自治县', 'A3')('贺家坪镇贺家坪村一组临河1号', 'A4')
('江苏省', 'A1')('南通市', 'A2')('海门市', 'A3')('孝威村孝威路88号', 'A4')('18611840623', 'T')('计星仪', 'P')
('17601674746', 'T')('赵春丽', 'P')('内蒙古自治区', 'A1')('乌兰察布市', 'A2')('凉城县', 'A3')('新建街', 'A4')
('云南省', 'A1')('临沧市', 'A2')('耿马傣族佤族自治县', 'A3')('鑫源路法院对面', 'A4')('许贞爱', 'P')('18510566685', 'T')
('四川省', 'A1')('成都市', 'A2')('双流区', 'A3')('东升镇北仓路196号', 'A4')('耿丕岭', 'P')('18513466161', 'T')

```
