### ISSUE TITLE
[Question]: 如何使用LoRA

### ISSUE THREAD

**Issue by carbonatedbeverages** [PaddlePaddle/PaddleNLP#8647]
### 请提出你的问题

model=ppnlp.transformers.NeZhaForSequenceClassification.from_pretrained('nezha-large-wwm-chinese', num_classes=14)
tokenizer = ppnlp.transformers.NeZhaTokenizer.from_pretrained('nezha-large-wwm-chinese')
lora_config = LoRAConfig(
    r=16,
    target_modules=['query', 'value'],
    lora_alpha=32,
    lora_dropout=0.05,
)
lora_model = LoRAModel(model, lora_config)
model = lora_model
运行后显示[2024-06-21 21:58:38,253] [    INFO] - Frozen parameters: 0.00e+00 || Trainable parameters:3.25e+08 || Total parameters:3.25e+08|| Trainable:100.00%
LoRA没有起作用是为什么呢？以上写法的问题在哪

**Comment by DrownFish19** [comment]
target_modules: List of module names or regex expression of the module names to replace with Lora.
`target_modules=['query', 'value'],`应该使用完整的参数名称或者正则表达式，如`target_modules=['*query*', '*value*'],`
[可参考target_module写法](https://github.com/PaddlePaddle/PaddleNLP/blob/25d21402d7dea0170bde225ba999a7231ae5d33c/llm/utils/utils.py#L115C1-L206C26)
