### ISSUE TITLE
ADE和DGU模型能否提供预训练模型

### ISSUE THREAD

**Issue by Tellyang7** [PaddlePaddle/PaddleNLP#865]
您好，请问对话系统 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/legacy/dialogue_system
中的ADE和DGU模型是否有可供直接进行预测的预训练模型进行验证或使用，目前无法找到中文数据集进行自主训练啊。

**Comment by Tellyang7** [comment]
在 ./ade/prepare_data_and_model.py `找到了

`DATA_MODEL_PATH = {
    "DATA_PATH":
    "https://baidu-nlp.bj.bcebos.com/auto_dialogue_evaluation_dataset-1.0.0.tar.gz",
    "TRAINED_MODEL":
    "https://baidu-nlp.bj.bcebos.com/auto_dialogue_evaluation_models.3.0.0.tar.gz"
}`

请问，这个就是可直接下载使用的PTM吗？

**Comment by Tellyang7** [comment]
请问，提供的Aistudio的Demo中的 [IPython Notebook demo](https://aistudio.baidu.com/aistudio/projectDetail/122301) 预处理部分的文件，能够提供下载吗？

**Comment by smallv0221** [comment]
Sorry. `/legacy/dialogue_system` has been deprecated. Please see https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/dgu for the new DGU example.

**Comment by Tellyang7** [comment]
> Sorry. `/legacy/dialogue_system` has been deprecated. Please see https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/dgu for the new DGU example.

Thanks for your kindly reply, but the aims of DGU and [ADEM](https://github.com/PaddlePaddle/models/tree/release/1.7/PaddleNLP/dialogue_system/auto_dialogue_evaluation) (Auto Dialogue Evaluation Model) are not same, is there a better alternative projects?

Besides, what has confused me is the data format described in the [IPython Notebook demo](https://aistudio.baidu.com/aistudio/projectDetail/122301). Can it be translated back, the ids sequence,  into nature language, as the sequence make no sense when ref. to the word.dic?  And, I only got the segments not ids after running the tokenizer.py from "https://github.com/PaddlePaddle/models/tree/release/1.7/PaddleNLP/shared_modules/preprocess".  How to preprocess the data to match the input format. 

Thanks again. And hope to get your reply soon.

**Comment by smallv0221** [comment]
Sorry for the delay. The project in `aistudio` is an old PaddlePaddle implementation. In PaddleNLP, we now have `Dialogue Evaluation` such as BLEU4 and Distinct in unified_transformer example. https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/unified_transformer
Is this what you are looking for?
