### ISSUE TITLE
[Question]: Why is PaddleNLP /applications/ not available anymore?

### ISSUE THREAD

**Issue by wwwstudyeveryday** [PaddlePaddle/PaddleNLP#8660]
### 请提出你的问题

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/128448644/749a9d8b-8682-44f7-a999-4e2ed9d8d3d9)
Why is PaddleNLP /applications/ not available anymore?

**Comment by edkair** [comment]
It has moved to the `legacy` folder: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/legacy/applications
