### ISSUE TITLE
[Question]: 无法安装PaddleNLP

### ISSUE THREAD

**Issue by wenqian-cai-tuya** [PaddlePaddle/PaddleNLP#8673]
### 请提出你的问题

caiyukuideMacBook-Pro:PaddleNLP caiyukui$ pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
ERROR: Could not find a version that satisfies the requirement paddlenlp (from versions: none)
ERROR: No matching distribution found for paddlenlp

[notice] A new release of pip is available: 23.1.2 -> 24.1
[notice] To update, run: pip install --upgrade pip
caiyukuideMacBook-Pro:PaddleNLP caiyukui$ 
caiyukuideMacBook-Pro:PaddleNLP caiyukui$ pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/paddlenlp/
ERROR: Could not find a version that satisfies the requirement paddlenlp (from versions: none)
ERROR: No matching distribution found for paddlenlp

**Comment by DrownFish19** [comment]
建议更换pip源，例如使用清华源 `-i https://pypi.tuna.tsinghua.edu.cn/simple`。
或者使用源码安装
```
git clone https://github.com/PaddlePaddle/PaddleNLP.git
cd PaddleNLP && python setup.py install
```

**Comment by wenqian-cai-tuya** [comment]
Thanks for your message
