### ISSUE TITLE
[Bug]: 示例程序出错

### ISSUE THREAD

**Issue by echo0218** [PaddlePaddle/PaddleNLP#8725]
### 软件环境

```Markdown
- paddlepaddle:3.0.0b0
- paddlepaddle-gpu: 
- paddlenlp: 3.0.0b0.post0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
示例程序第三行报错：
Exception has occurred: AttributeError
module 'mmap' has no attribute 'MAP_PRIVATE'
```

### 稳定复现步骤 & 代码

from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-0.5B")
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B", dtype="float16")
input_features = tokenizer("你好！请自我介绍一下。", return_tensors="pd")
outputs = model.generate(**input_features, max_length=128)
tokenizer.batch_decode(outputs[0])
['我是一个AI语言模型，我可以回答各种问题，包括但不限于：天气、新闻、历史、文化、科学、教育、娱乐等。请问您有什么需要了解的吗？']

**Comment by DrownFish19** [comment]
非常抱歉出现这个问题，问题原因现已确定，修改PR为https://github.com/PaddlePaddle/PaddleNLP/pull/8734 （暂未合入），辛苦参照修改内容进行修改。

具体原因：mmap在windows和unix上存在两种API，其中windows api不支持flag传入。
```
Windows: mmap(fileno, length[, tagname[, access[, offset]]])
Unix: mmap(fileno, length[, flags[, prot[, access[, offset]]]])
```

**Comment by echo0218** [comment]
按#8734 修改了文件代码，示例代码仍出错。不再报mmap错误，新错误是：
Exception has occurred: PermissionError
[WinError 5] 拒绝访问。
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-0.5B", dtype="float16")
