### ISSUE TITLE
tp推理，内存溢出问题    #8656

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/PaddleNLP#8736]
我想进行tp推理，我在模型from_pretrained是否需要进行相应的tp配置，然后再调用save_pretrained方法来保存

_Originally posted by @zhaogf01 in https://github.com/PaddlePaddle/PaddleNLP/issues/8656#issuecomment-2216685129_

**Comment by zhaogf01** [comment]
上一个issue已经关闭了，我好像不能reopen，所以在这重新提问

上次您说可以save_pretrained成safetensor格式的权重，就不会有权重被复制多份的问题了。我在save_pretrained之前的from_pretrained进行了相应的tp配置，此时在AutoModelForCausalLM.from_pretrained中还是会出现权重在内存中被复制多份的问题，因此还是出现了内存溢出的问题。所以转换成safetensor格式的权重也是不可行的。
请问还有其他解决办法吗？@DesmonDay

**Comment by DesmonDay** [comment]
你转换成Safetensors格式的逻辑和from_pretrained逻辑发出来，正常情况下不会oom，除非你内存不足。

**Comment by zhaogf01** [comment]
脚本如下：

test.sh
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
PYTHONPATH=../../:python -m paddle.distributed.launch --devices 0,1,2,3,4,5,6,7 test.py
```

test.py
```
from paddle.distributed import fleet
from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
from paddlenlp.transformers.llama import LlamaTokenizer
strategy = fleet.DistributedStrategy()
strategy.hybrid_configs = {
                "dp_degree": 1,
                "mp_degree": 8,
                "pp_degree": 1,
                "sharding_degree": 1,
            }
fleet.init(is_collective=True, strategy=strategy)
hcg = fleet.get_hybrid_communicate_group()
tensor_parallel_rank = hcg.get_model_parallel_rank()
model_path = "/workspace/51B_fp32_tp8"
tokenizer = LlamaTokenizer.from_pretrained(model_path, add_eos_token=False, add_bos_token=False, eos_token='<eod>')
model = AutoModelForCausalLM.from_pretrained(model_path,tensor_parallel_degree= 8,tensor_parallel_rank=tensor_parallel_rank, dtype="float32")
model.save_pretrained("./51checkpointfp32",safe_serialization=True )
````
结果如下：
![image](https://github.com/PaddlePaddle/PaddleNLP/assets/148510471/4072443b-4f95-4d8a-b5a5-4a7228ac45bd)

权重大小是198GB，服务器内存是1000GB，最终的现象是内存占用持续上涨，最终内存溢出

**Comment by DesmonDay** [comment]
保存下来的Safetensors文件截图我看下

**Comment by DesmonDay** [comment]
看起来你加载的依然是pdparams格式

**Comment by zhaogf01** [comment]
不是，我可能说的不太明白。
您看一下上面的代码，我是说在pdparams转换为Safetensors的过程就会内存溢出
在在save_pretrained之前的from_pretrained就会爆内存，所以根本保存不下来

**Comment by DesmonDay** [comment]
直接单卡from_pretrained，然后再保存成safetensors就行！不要多卡加载。

**Comment by DesmonDay** [comment]
from paddle.distributed import fleet
from paddlenlp.transformers import AutoTokenizer, AutoModelForCausalLM
from paddlenlp.transformers.llama import LlamaTokenizer
model = AutoModelForCausalLM.from_pretrained(model_path, dtype="float32")
model.save_pretrained("./model_safetensors", safe_serialization=True)

**Comment by DesmonDay** [comment]
输入的model_path需要是一个完整的pdparams文件，直接python xxx.py执行就行，不需要多卡环境。

**Comment by zhaogf01** [comment]
好的，单卡的话可以使用cpu嘛？显卡只有40G显存。

**Comment by DesmonDay** [comment]
可以的，就是速度慢一些了

**Comment by zhaogf01** [comment]
可以了！
但还有一个问题想请教，以前我调用torch的权重是先使用https://github.com/PaddlePaddle/PaddleNLP/blob/2723138738fe179acb32bf619c54a9315acdabe0/legacy/examples/torch_migration/pipeline/weights/torch2paddle.py#L66 这个文件先转换权重再调用推理。最近发现，下面这行代码
```AutoModelForCausalLM.from_pretrained("/path/to/pytorch/model", convert_from_torch=True, dtype="bfloat16")```
可以直接使用torch的权重，但我验证并不能推理出正确的结果。我对比了一下，使用第二种方法好像并没有第一种方法的transpose操作，请问我的理解是正确的吗？

**Comment by zhaogf01** [comment]
work！！！
万分感谢

**Comment by zhaogf01** [comment]
您好，上周我使用的是fp32的权重，使用cpu转换没有问题。
现在有一个194G的bf16的权重，使用cpu会有以下错误，
![image](https://github.com/user-attachments/assets/4589f5f6-9a50-45ee-b376-f66920ae7fbb)
这个问题应该怎么解决？
我的需求是把bf16的tbin权重转为safetensors，或者有没有其他办法解决我的需求？

**Comment by DesmonDay** [comment]
from_pretrained的时候加一个配置，设置 low_cpu_mem_usage = True

**Comment by zhaogf01** [comment]
![image](https://github.com/user-attachments/assets/ea3319d9-56f5-4075-8831-eb7db20cc80f)
应该是设置low_cpu_mem_usage = True导致越界了。。。。
还有其他办法吗？QAQ

**Comment by DesmonDay** [comment]
那就尝试另一种方法，参考这里qwen2的转换逻辑：https://gist.github.com/DrownFish19/80b43383c9205ee1cf7cf35445009488 看是否可以参考着改一下。

**Comment by DesmonDay** [comment]
”我的需求是把bf16的tbin权重转为safetensors，或者有没有其他办法解决我的需求？“  要使用上面的脚本的话，我理解你可以先用torch的相关函数把你的tbin权重转成safetensors，然后再用上面的权重转换。绕过越界的问题。
