### ISSUE TITLE
[Question]: 在V100上实现WINT8量化性能降低

### ISSUE THREAD

**Issue by wojiaoshihua** [PaddlePaddle/PaddleNLP#8738]
### 请提出你的问题

软件环境
paddle-bfloat          0.1.7
paddle2onnx            1.2.4
paddlefsl              1.1.0
paddlemix              0.1.0
paddlenlp              2.8.1
paddlenlp-ops          0.0.0
paddlepaddle-gpu       0.0.0.post118
paddlesde              0.2.5
ppdiffusers            0.24.0        /root/baidu/personal-code/llava_paddle_static/ppdiffusers
当前的csrc文件中自定义算子似乎并不支持V100等显卡，手动修改了下csrc里的自定义算子，参照https://github.com/PaddlePaddle/PaddleNLP/pull/7785 对bfloat进行一个判断，实现了静态图的WINT8量化，但经测试发现虽然降低了显存，但并不会提升推理速度，对比fp16速度反而会下降。请问下降速度的原因是什么，我在整体模型推理用到的数据类型均为fp16

**Comment by vivienfanghuagood** [comment]
wint8量化相比float16仅在bsz * seq较小的场景有性能优势，请问你的输入长度是什么规模呢？

**Comment by wojiaoshihua** [comment]
> wint8量化相比float16仅在bsz * seq较小的场景有性能优势，请问你的输入长度是什么规模呢？
我推理过程中不会超过4096，此外，在A100上进行实验不会出现这个问题。因此我推测可能跟我修改后的csrc算子有关。我重新测试了下，发现基于paddlenlp2.7版本更改自定义算子的推理速度要远低于paddelnlp2.8版本的。然而我看更新日志更多的是支持blockattention推理。

最终问题现定义在如何在V100上实行WINT8量化方案

我做了一些修改，把2.8版本算子中关于bf16中去掉(因为V100不支持bf16)，模型量化并不会执行(即仍按fp16进行存储)。如果我需要新版(至少2.8)算子在V100上的支持，那么我需要做些什么更改，你能提供一个方向吗。

**Comment by wojiaoshihua** [comment]
> wint8量化相比float16仅在bsz * seq较小的场景有性能优势，请问你的输入长度是什么规模呢？


我推理过程中不会超过4096，此外，在A100上进行实验不会出现这个问题。因此我推测可能跟我修改后的csrc算子有关。我重新测试了下，发现基于paddlenlp2.7版本更改自定义算子的推理速度要远低于paddelnlp2.8版本的。然而我看更新日志更多的是支持blockattention推理。

最终问题现定义在如何在V100上实行WINT8量化方案

我做了一些修改，把2.8版本算子中关于bf16中去掉(因为V100不支持bf16)，模型量化并不会执行(即仍按fp16进行存储)。如果我需要新版(至少2.8)算子在V100上的支持，那么我需要做些什么更改，你能提供一个方向吗

**Comment by wojiaoshihua** [comment]
> > wint8量化相比float16仅在bsz * seq较小的场景有性能优势，请问你的输入长度是什么规模呢？
> 
> 我推理过程中不会超过4096，此外，在A100上进行实验不会出现这个问题。因此我推测可能跟我修改后的csrc算子有关。我重新测试了下，发现基于paddlenlp2.7版本更改自定义算子的推理速度要远低于paddelnlp2.8版本的。然而我看更新日志更多的是支持blockattention推理。
> 
> 最终问题现定义在如何在V100上实行WINT8量化方案
> 
> 我做了一些修改，把2.8版本算子中关于bf16中去掉(因为V100不支持bf16)，模型量化并不会执行(即仍按fp16进行存储)。如果我需要新版(至少2.8)算子在V100上的支持，那么我需要做些什么更改，你能提供一个方向吗


现在我已经找到问题所在，实现了V100的WINT8量化，但WINT8的静态图量化并没有带来速度上的提高。具体来说，经过实验，输出的结果为短token时(如20左右)，模型的总共推理时间要比fp16还要慢，但长token时，WINT8模型的推理时间对推理速度带来了提升。猜测可能是由于首token带来的固定损耗，这个损耗具体是什么，可以指明一下吗 @DesmonDay @vivienfanghuagood
