### ISSUE TITLE
[Question]: ddp = Taskflow("dependency_parsing")

### ISSUE THREAD

**Issue by zbximo** [PaddlePaddle/PaddleNLP#8753]
### 请提出你的问题

paddle2onnx              1.2.1
paddlefsl                1.1.0
paddlenlp                2.6.0
paddlepaddle-gpu         2.6.1.post112

运行ddp = Taskflow("dependency_parsing")需要安装LAC，安装LAC后
from LAC import LAC
出现ModuleNotFoundError: No module named 'paddle.fluid'，网上查询后说是paddle2.5之后移除了fluid，请问这怎么办？

**Comment by wawltor** [comment]
可以安装2.5版本的paddlepaddle版本
