### ISSUE TITLE
[Question]: 示例代码出错

### ISSUE THREAD

**Issue by yimuu** [PaddlePaddle/PaddleNLP#8771]
### 请提出你的问题

tokenizer = AutoTokenizer.from_pretrained("linly-ai/chinese-llama-2-7b") 这一行代码出错
OSError: Can't load the model for 'linly-ai/chinese-llama-2-7b'. If you were trying to load it from 'BOS', make sure you don't have a local directory with the same name. Otherwise, make sure 'linly-ai/chinese-llama-2-7b' is the correct path to a directory containing one of the ['tokenizer_config.json']

**Comment by DrownFish19** [comment]
我们在本地和[星河社区](https://aistudio.baidu.com)执行都是正常的。
原因：本地文件默认存储在`~/.paddlenlp`，可能是由于`tokenizer_config.json`下载失败导致
解决方案：建议删除`~/.paddlenlp/models/linly-ai/chinese-llama-2-7b`文件夹后再次尝试
