### ISSUE TITLE
在V100上的WINT8量化

### ISSUE THREAD

**Issue by wojiaoshihua** [PaddlePaddle/PaddleNLP#8774]
> > wint8量化相比float16仅在bsz * seq较小的场景有性能优势，请问你的输入长度是什么规模呢？
> 
> 我推理过程中不会超过4096，此外，在A100上进行实验不会出现这个问题。因此我推测可能跟我修改后的csrc算子有关。我重新测试了下，发现基于paddlenlp2.7版本更改自定义算子的推理速度要远低于paddelnlp2.8版本的。然而我看更新日志更多的是支持blockattention推理。
> 
> 最终问题现定义在如何在V100上实行WINT8量化方案
> 
> 我做了一些修改，把2.8版本算子中关于bf16中去掉(因为V100不支持bf16)，模型量化并不会执行(即仍按fp16进行存储)。如果我需要新版(至少2.8)算子在V100上的支持，那么我需要做些什么更改，你能提供一个方向吗

现在我已经找到问题所在，实现了V100的WINT8量化，但WINT8的静态图量化并没有带来速度上的提高。具体来说，经过实验，输出的结果为短token时(如20左右)，模型的总共推理时间要比fp16还要慢，但长token时，WINT8模型的推理时间对推理速度带来了提升。猜测可能是由于首token带来的固定损耗，这个损耗具体是什么，可以指明一下吗 @DesmonDay @vivienfanghuagood

https://github.com/PaddlePaddle/PaddleNLP/issues/8738#issuecomment-2232344532_

**Comment by wojiaoshihua** [comment]
虽然V100和A100性能有差距，但我认为差距不应该这么大，在V100上这个固定损耗约为1s+，而在A100上仅约为0.2s。

**Comment by wojiaoshihua** [comment]
> 虽然V100和A100性能有差距，但我认为差距不应该这么大，在V100上这个固定损耗约为1s+，而在A100上仅约为0.2s。

我用llama-13b进行实验，更改了predictor.py中的prompt长度，按照inference.md文档中的指令运行，得到了如下数据(均为首token输出时间)。可以明显看出在进行weight only量化后，随着prompt长度增加，在V100上带来的首token时间爆炸式增长，我认为这是不合理的，除了本身算力差距似乎还有别的问题的影响。

prompt长度为600个汉字(约1300-1400token)
         fp16(paddle).      WINT8
V100.         0.4                 1.96
A100          0.16                0.17

prompt长度为5个汉字(约10+token)
         fp16(paddle).      WINT8
V100.         0.0498           0.048
A100          0.053             0.036

**Comment by vivienfanghuagood** [comment]
我们跟进下这个问题

**Comment by wojiaoshihua** [comment]
> 我们跟进下这个问题


感谢
