### ISSUE TITLE
[Question]: 模型下载路径？

### ISSUE THREAD

**Issue by zhangxiangchn** [PaddlePaddle/PaddleNLP#8775]
### 请提出你的问题

原来可以在https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/question_answering/faq_finance 路径下学习paddle金融知识问答的，现在这个代码是否已经移除？另外想问一下如何下载rocketqa-zh-base-query-encoder模型？是否有下载路径

**Comment by DrownFish19** [comment]
1. 3.0版本已经移除faq_finance，如需学习和参考可使用[PaddleNLP2.8版本](https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.8/applications/question_answering/supervised_qa/faq_finance).
2. 当前暂无直接下载链接，但可使用PaddleNLP直接下载，代码如下，下载后可在`~/.paddlenlp/models/rocketqa-zh-base-query-encoder`找到已下载模型。
```python
from paddlenlp.transformers import AutoModel
model = AutoModel.from_pretrained("rocketqa-zh-base-query-encoder")
```

**Comment by zhangxiangchn** [comment]
> 1. 3.0版本已经移除faq_finance，如需学习和参考可使用[PaddleNLP2.8版本](https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.8/applications/question_answering/supervised_qa/faq_finance).
> 2. 当前暂无直接下载链接，但可使用PaddleNLP直接下载，代码如下，下载后可在`~/.paddlenlp/models/rocketqa-zh-base-query-encoder`找到已下载模型。
> 
> ```python
> from paddlenlp.transformers import AutoModel
> model = AutoModel.from_pretrained("rocketqa-zh-base-query-encoder")
> ```

在华为昇腾910B上使用官方镜像跑金融知识问答代码遇到了一下问题，这个主要是什么问题呢？
依赖包：
paddle-custom-npu   3.0.0
paddle2onnx         1.0.5
paddlefsl           1.1.0
paddlenlp           2.6.1
paddlepaddle        3.0.0.dev20240905
报错日志：
dl-edd96eea66903dc68c36d81a1d07983c-r0-e7e8890eef90-0 ~/work/paddle_finance_qa ./scripts/train.sh 
I0906 12:52:16.025509 48723 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.9/dist-packages/paddle_custom_device
I0906 12:52:16.025570 48723 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I0906 12:52:16.597659 48723 custom_device.cc:1099] Succeed in loading custom runtime in lib: /usr/local/lib/python3.9/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I0906 12:52:16.611999 48723 custom_kernel.cc:63] Succeed in loading 355 custom kernel(s) from loaded lib(s), will be used like native ones.
I0906 12:52:16.612232 48723 init.cc:157] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I0906 12:52:16.612347 48723 init.cc:242] CustomDevice: npu, visible devices count: 1
LAUNCH INFO 2024-09-06 12:52:17,398 -----------  Configuration  ----------------------
LAUNCH INFO 2024-09-06 12:52:17,398 auto_cluster_config: 0
LAUNCH INFO 2024-09-06 12:52:17,398 auto_parallel_config: None
LAUNCH INFO 2024-09-06 12:52:17,398 auto_tuner_json: None
LAUNCH INFO 2024-09-06 12:52:17,398 devices: None
LAUNCH INFO 2024-09-06 12:52:17,398 elastic_level: -1
LAUNCH INFO 2024-09-06 12:52:17,398 elastic_timeout: 30
LAUNCH INFO 2024-09-06 12:52:17,398 enable_gpu_log: True
LAUNCH INFO 2024-09-06 12:52:17,398 gloo_port: 6767
LAUNCH INFO 2024-09-06 12:52:17,398 host: None
LAUNCH INFO 2024-09-06 12:52:17,398 ips: None
LAUNCH INFO 2024-09-06 12:52:17,398 job_id: default
LAUNCH INFO 2024-09-06 12:52:17,398 legacy: False
LAUNCH INFO 2024-09-06 12:52:17,398 log_dir: log
LAUNCH INFO 2024-09-06 12:52:17,398 log_level: INFO
LAUNCH INFO 2024-09-06 12:52:17,398 log_overwrite: False
LAUNCH INFO 2024-09-06 12:52:17,399 master: None
LAUNCH INFO 2024-09-06 12:52:17,399 max_restart: 3
LAUNCH INFO 2024-09-06 12:52:17,399 nnodes: 1
LAUNCH INFO 2024-09-06 12:52:17,399 nproc_per_node: None
LAUNCH INFO 2024-09-06 12:52:17,399 rank: -1
LAUNCH INFO 2024-09-06 12:52:17,399 run_mode: collective
LAUNCH INFO 2024-09-06 12:52:17,399 server_num: None
LAUNCH INFO 2024-09-06 12:52:17,399 servers: 
LAUNCH INFO 2024-09-06 12:52:17,399 sort_ip: False
LAUNCH INFO 2024-09-06 12:52:17,399 start_port: 6070
LAUNCH INFO 2024-09-06 12:52:17,399 trainer_num: None
LAUNCH INFO 2024-09-06 12:52:17,399 trainers: 
LAUNCH INFO 2024-09-06 12:52:17,399 training_script: train.py
LAUNCH INFO 2024-09-06 12:52:17,399 training_script_args: ['--device', 'npu', '--model_name_or_path', 'rocketqa-zh-base-query-encoder', '--save_dir', './checkpoints/', '--batch_size', '64', '--learning_rate', '5E-5', '--epochs', '3', '--save_steps', '50', '--eval_steps', '50', '--max_seq_length', '64', '--dropout', '0.2', '--output_emb_size', '256', '--dup_rate', '0.1', '--rdrop_coef', '0.1', '--train_set_file', './data/train_aug.csv']
LAUNCH INFO 2024-09-06 12:52:17,399 with_gloo: 1
LAUNCH INFO 2024-09-06 12:52:17,399 --------------------------------------------------
LAUNCH INFO 2024-09-06 12:52:17,403 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2024-09-06 12:52:17,421 Run Pod: sdngdt, replicas 1, status ready
LAUNCH INFO 2024-09-06 12:52:17,517 Watching Pod: sdngdt, replicas 1, status running
I0906 12:52:18.521728 49192 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.9/dist-packages/paddle_custom_device
I0906 12:52:18.521785 49192 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I0906 12:52:19.034915 49192 custom_device.cc:1099] Succeed in loading custom runtime in lib: /usr/local/lib/python3.9/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I0906 12:52:19.040978 49192 custom_kernel.cc:63] Succeed in loading 355 custom kernel(s) from loaded lib(s), will be used like native ones.
I0906 12:52:19.041185 49192 init.cc:157] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I0906 12:52:19.041232 49192 init.cc:242] CustomDevice: npu, visible devices count: 1
/usr/local/lib/python3.9/dist-packages/_distutils_hack/__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
/usr/local/lib/python3.9/dist-packages/paddle/jit/dy2static/program_translator.py:763: UserWarning: full_graph=False don't support input_spec arguments. It will not produce any effect.
You can set full_graph=True, then you can assign input spec.

  warnings.warn(
[2024-09-06 12:52:22,091] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.modeling.ErnieModel'> to load 'rocketqa-zh-base-query-encoder'.
[2024-09-06 12:52:22,092] [    INFO] - Loading weights file rocketqa-zh-base-query-encoder/model_state.pdparams
[2024-09-06 12:52:22,396] [    INFO] - Loaded weights file from disk, setting weights to model.
[2024-09-06 12:52:41,513] [ WARNING] - Some weights of the model checkpoint at rocketqa-zh-base-query-encoder were not used when initializing ErnieModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing ErnieModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ErnieModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[2024-09-06 12:52:41,514] [    INFO] - All the weights of ErnieModel were initialized from the model checkpoint at rocketqa-zh-base-query-encoder.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ErnieModel for predictions without further training.
[2024-09-06 12:52:41,522] [    INFO] - We are using (<class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'>, False) to load 'rocketqa-zh-base-query-encoder'.
[2024-09-06 12:52:41,523] [    INFO] - Already cached rocketqa-zh-base-query-encoder/ernie_3.0_base_zh_vocab.txt
[2024-09-06 12:52:41,594] [    INFO] - tokenizer config file saved in rocketqa-zh-base-query-encoder/tokenizer_config.json
[2024-09-06 12:52:41,597] [    INFO] - Special tokens file saved in rocketqa-zh-base-query-encoder/special_tokens_map.json
/usr/local/lib/python3.9/dist-packages/paddle/distributed/parallel.py:441: UserWarning: The program will return to single-card operation. Please check 1, whether you use spawn or fleetrun to start the program. 2, Whether it is a multi-card program. 3, Is the current environment multi-card.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/paddlenlp/transformers/tokenizer_utils_base.py:2293: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/paddlenlp/transformers/tokenizer_utils_base.py:1865: UserWarning: Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/paddle/jit/dy2static/program_translator.py:763: UserWarning: full_graph=False don't support input_spec arguments. It will not produce any effect.
You can set full_graph=True, then you can assign input spec.

  warnings.warn(
-
\
Traceback (most recent call last):
  File "/root/work/paddle_finance_qa/train.py", line 222, in <module>
    do_train()
  File "/root/work/paddle_finance_qa/train.py", line 182, in do_train
    loss, kl_loss = model(
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1532, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/distributed/parallel.py", line 561, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/nn/layer/layers.py", line 1532, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/work/paddle_finance_qa/model.py", line 114, in forward
    query_cls_embedding = self.get_pooled_embedding(
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/dy2static/program_translator.py", line 551, in __call__
    return self._perform_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/dy2static/program_translator.py", line 792, in _perform_call
    return traced_fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/sot/translate.py", line 119, in impl
    return impl_sot(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/sot/translate.py", line 103, in impl_sot
    raise e
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/sot/translate.py", line 101, in impl_sot
    outs = fn(*args, **kwargs)
  File "/root/work/paddle_finance_qa/model.py", line 56, in #get_pooled_embedding_84ae0
    sequence_output, cls_embedding = self.ptm(input_ids, token_type_ids, position_ids, attention_mask)
  File "/root/work/paddle_finance_qa/model.py", line 45, in #$resume_1@get_pooled_embedding_af1a0
    @paddle.jit.to_static(
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/sot/symbolic/compile_cache.py", line 152, in __call__
    outputs = self.partial_program.sot_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/jit/dy2static/partial_program.py", line 258, in sot_call
    _legacy_C_ops.run_program(
RuntimeError: (NotFound)  interface not found.
  [Hint: Expected dev_impl_map.find(device_type) != dev_impl_map.end(), but received dev_impl_map.find(device_type) == dev_impl_map.end().] (at /paddle/paddle/phi/backends/device_manager.cc:296)
  [operator < run_program > error]
