### ISSUE TITLE
[Bug]: information_extraction 任务报错 attention_mask全为1 会导致异常

### ISSUE THREAD

**Issue by LuckyPick** [PaddlePaddle/PaddleNLP#8802]
### 软件环境

```Markdown
- paddlepaddle-gpu: 2.5.2.post112
- paddlenlp: 2.6.1
- paddle2onnx 1.1.0
- paddlefsl 1.1.0
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
当PaddleNLP/paddlenlp/taskflow/information_extraction.py 中 839行处 当attention_mask全为1时 报错 导致程序无法正常运行。
```

### 稳定复现步骤 & 代码

使用taskflow('information_extraction') 从 xxxxxx[1]xx(xx)xxxxxx中提取特定字段没有问题但是xxxxxx【1】xx（xx）xxxxxx变中文标点后报错，经检查发现第二次调用attention_mask全为1 导致c_sep_index = attention_mask.index(0) 该语句报错 
<img width="749" alt="image" src="https://github.com/user-attachments/assets/b0eed00a-131e-41ac-9bb8-02b32117db16">
内网错误拷不出来 见谅～～

**Comment by LuckyPick** [comment]
短了还触发不了 文本还得大概500多字以上才行。。。。。。。

**Comment by Cynthia-ly** [comment]
hello.你怎么解决了这个问题？
