### ISSUE TITLE
[Question]:  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/kernels/funcs/blas/blas_impl.cu.h:41)   [operator < linear > error]

### ISSUE THREAD

**Issue by zhanghengjiayou** [PaddlePaddle/PaddleNLP#8808]
### 请提出你的问题

paddle 2.5.2.post11.2
 [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/kernels/funcs/blas/blas_impl.cu.h:41)
  [operator < linear > error]
![aeaba52d21e501854c0f4ff6e566109](https://github.com/user-attachments/assets/1cc63061-f133-42de-9530-6802c4b7c16f)

**Comment by zhanghengjiayou** [comment]
请问这个问题要怎么解决啊，是版本不对还是cuda不支持，切换了好多次一直是这个错，以为是数据集的问题，用官方数据也是这样

**Comment by wawltor** [comment]
请尝试执行下面的代码，看看是否针正常执行，如果能正常执行表示paddle安装无问题；如果安装有问题，请按照特定的cuda安装paddle  
![Uploading image.png…]()

```python
import paddle 
paddle.utils.run_check()
```

**Comment by zhanghengjiayou** [comment]
谢谢，已经解决了，paddle和cuda的冲突，重新换了虚拟环境安装就可以了
