### ISSUE TITLE
用户自定义添加新token

### ISSUE THREAD

**Issue by luckysheep861** [PaddlePaddle/PaddleNLP#881]
PaddleNLP有没有类似transformers中的add_special_tokens方法？

需求：添加某些特殊token，如<title>,<chunk>等，让tokenizer在tokenize时自动将新的token识别成新的token id

**Comment by smallv0221** [comment]
Sorry we don't have such function for now. Maybe we would add this in a future version.

**Comment by pfchai** [comment]
这个功能实现了吗？
