### ISSUE TITLE
[Bug]:     if negative_mask.sum() > 0: AttributeError: 'bool' object has no attribute 'sum'

### ISSUE THREAD

**Issue by DAAworld** [PaddlePaddle/PaddleNLP#8835]
### 软件环境

```Markdown
paddle-bfloat         0.1.7
paddle2onnx           1.2.6
paddlefsl             1.1.0
paddlenlp             2.8.1
paddleocr             2.8.1
paddlepaddle-gpu      2.6.1.post120
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
if negative_mask.sum() > 0:
AttributeError: 'bool' object has no attribute 'sum'
执行kie推理时候报错
python3 ./tools/infer_kie_token_ser_re.py   -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml   -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy   Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg   -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml   -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy
```

### 稳定复现步骤 & 代码

python3 ./tools/infer_kie_token_ser_re.py   -c configs/kie/vi_layoutxlm/re_vi_layoutxlm_xfund_zh.yml   -o Architecture.Backbone.checkpoints=./pretrained_model/re_vi_layoutxlm_xfund_pretrained/best_accuracy   Global.infer_img=./train_data/XFUND/zh_val/image/zh_val_42.jpg   -c_ser configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml   -o_ser Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy

**Comment by kezidanbao** [comment]
这个问题解决了吗？我也遇到了这个问题
