### ISSUE TITLE
ERNIE-Doc 官方源代码在aistudio运行失败，也不报错

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#885]
运行 sh scripts/run_imdb.sh

提示以下信息，但是没有进入训练，直接退出了。
current_node_ip: 172.29.180.233
node_id: 0
node_ips: 172.29.180.233
nproc_per_node: 2
print_config: True
selected_gpus: 0,1
split_log_path: log
training_script: ./run_classifier.py
training_script_args: ['--use_cuda', 'true', '--is_distributed', 'true', '--use_fast_executor', 'true', '--tokenizer', 'BPETokenizer', '--use_amp', 'False', '--do_train', 'true', '--do_val', 'true', '--do_test', 'false', '--batch_size', '16', '--init_checkpoint', '', '--init_pretraining_params', '', '--train_set', './data/imdb//train.txt', '--dev_set', './data/imdb//test.txt', '--test_set', './data/imdb//test.txt', '--vocab_path', './configs/base/en/vocab.txt', '--checkpoints', './output', '--save_steps', '100000', '--weight_decay', '0.01', '--warmup_proportion', '0.1', '--validation_steps', '700', '--epoch', '3', '--max_seq_len', '512', '--ernie_config_path', './configs/base/en/ernie_config.json', '--learning_rate', '7e-5', '--skip_steps', '10', '--num_iteration_per_drop_scope', '10', '--layer_decay_ratio', '1', '--num_labels', '2', '--is_zh', 'False', '--use_vars', 'False', '--init_loss_scaling', '32768', '--use_recompute', 'False', '--random_seed', '1']
------------------------------------------------
all_trainer_endpoints:  172.29.180.233:6170,172.29.180.233:6171 , node_id:  0 , current_ip:  172.29.180.233 , num_nodes:  1 , node_ips:  ['172.29.180.233'] , gpus_per_proc:  1 , selected_gpus_per_proc:  [['0'], ['1']] , nranks:  2
aistudio@j

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc

请手动安装paddlenlp develop版本（python setup.py install) 然后再尝试下，这是paddlenlp对应的ernie-doc动态图版本。

**Comment by AI-Mart** [comment]
ernie-doc我可以在你这边提供的最新的目录找到最新的模型，其他的几个ernie相关的模型能否也提供下最新动态图模型案例呢？
包括ernie-gram ernie-unimo ernie-gen ernie-vil等



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-doc 官方源代码在aistudio运行失败，也不报错 (#885)





 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc
 
请手动安装paddlenlp develop版本（python setup.py install) 然后再尝试下，这是paddlenlp对应的ernie-doc动态图版本。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AI-Mart** [comment]
ernie-doc我可以在你这边提供的最新的目录找到最新的模型，其他的几个ernie相关的模型能否也提供下最新动态图模型案例呢？
包括ernie-gram ernie-unimo ernie-gen ernie-vil等

**Comment by ZeyuChen** [comment]
Issues Solved

> ernie-doc我可以在你这边提供的最新的目录找到最新的模型，其他的几个ernie相关的模型能否也提供下最新动态图模型案例呢？
> 包括ernie-gram ernie-unimo ernie-gen ernie-vil等

会陆陆续续提供的，stay tuned.
