### ISSUE TITLE
[Question]: 使用examples/machine_translation/transformer下的机器翻译案例时应该使用哪个版本的paddlenlp

### ISSUE THREAD

**Issue by cccusername** [PaddlePaddle/PaddleNLP#8854]
### 请提出你的问题

使用examples/machine_translation/transformer下的机器翻译案例时，训练没有问题，但是使用predict.py时提示ImportError: cannot import name 'TransformerGenerator' from 'paddlenlp.ops'，我应该使用哪个版本的paddlenlp呢

**Comment by DrownFish19** [comment]
可以试试2.8版本，3.0版本移除了部分应用
