### ISSUE TITLE
[Question]: AttributeError: module 'fused_ln' has no attribute 'fused_rms_norm'

### ISSUE THREAD

**Issue by RayneYael** [PaddlePaddle/PaddleNLP#8859]
### 请提出你的问题

按照paddlenlp预训练模型要求，在目录paddlenlp/model_zoo/gpt-3/external_ops 下使用python setup.py install从而安装了fused_ln,但遇到了AttributeError: module 'fused_ln' has no attribute 'fused_rms_norm'

**Comment by ZHUI** [comment]
可能是安装的python 和 训练用的python 不一致。或者是 你 本地目录那里有一个 `fused_ln` 的文件夹。

**Comment by RayneYael** [comment]
> 可能是安装的python 和 训练用的python 不一致。或者是 你 本地目录那里有一个 `fused_ln` 的文件夹。

我这里是用的是linux服务器。请问如何确认使用的python版本应该为哪个呢？使用python setup.py build后，貌似只在/paddlenlp/model_zoo/gpt-3/external_ops/build下产生了fused_ln文件，其他地方貌似没有找到。

**Comment by RayneYael** [comment]
解决了。我
把external/build/fused_ln/bdist.linux-x86_64/egg 路径下的fused_ln.py放在了build文件下，并将该文件83行左右的so_path手动设置为.....external/build/fused_ln/bdist.linux-x86_64/egg/fused_ln.so 就可以运行了。
注意，还要在原始运行的py文件（我这里是run_pretrain.py)的开头加上
```
import sys
sys.path.append('此处填写build文件绝对路径，如/home/username/PaddleNLP/model_zoo/gpt-3/external_ops/build')
```
其中我一开始试图把so文件和py文件一起放在build文件下，但貌似会出现路径读取错误，只是把它们分开放路径读取也有问题，所以需要在py文件里把so_path赋值为so文件的路径。
