### ISSUE TITLE
ERNIE-Doc只开源了静态图的版本吗，有没有开源最新的动态度的版本

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#886]
English | 简体中文

** 欢迎试用动态图实现的ERNIE，请checkout 分支:dygraph **

官方reademe这个分支名字没找到，能否告知下，最新版本，谢谢

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc

请手动安装paddlenlp develop版本然后尝试哈

**Comment by AI-Mart** [comment]
下载这个路径后在aistudio运行还是报错了


***@***.***:~/77_language_model/ernie-doc$ python run_classifier.py --batch_size 8 --model_name_or_path ernie-doc-base-en




报错信息：


Traceback (most recent call last):
&nbsp; File "run_classifier.py", line 29, in <module&gt;
&nbsp; &nbsp; from paddlenlp.transformers import ErnieDocModel
ImportError: cannot import name 'ErnieDocModel' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)
***@***.***:~/77_language_model/ernie-doc$&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] ERNIE-Doc只开源了静态图的版本吗，有没有开源最新的动态度的版本 (#886)





 
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc
 
请手动安装paddlenlp develop版本然后尝试哈
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by joey12300** [comment]
@AI-Mart 需要先执行以下步骤安装相关依赖包：

1. 手动安装PaddleNLP

```
cd PaddleNLP/
python setup.py install
```

2. 按照[readme](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-doc)下载相关依赖

```
pip install re nltk beautifulsoup4
```

**Comment by AI-Mart** [comment]
还是报错 aistudio@jupyter-271421-2286718:~/PaddleNLP/examples/language_model/ernie-doc$ python run_classifier.py --batch_size 8 --model_name_or_path ernie-doc-base-en
Traceback (most recent call last):
  File "run_classifier.py", line 29, in <module>
    from paddlenlp.transformers import ErnieDocModel
ImportError: cannot import name 'ErnieDocModel' from 'paddlenlp.transformers' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py)你那边能试下吗

**Comment by joey12300** [comment]
你先更新最新版基于develop分支的PaddleNLP，然后安装。或者你提供一下aistudio的项目吧

**Comment by AI-Mart** [comment]
是直接把最新版的下载，然后按你说的步骤做的，还是报错，这边由于aistudio的限制生成不了版本，不能设置公共项目。你那边能否直接git clone到aistuidio试下看


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] ERNIE-Doc只开源了静态图的版本吗，有没有开源最新的动态度的版本 (#886)





 
你先更新最新版基于develop分支的PaddleNLP，然后安装。或者你提供一下aistudio的项目吧
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AI-Mart** [comment]
![image](https://user-images.githubusercontent.com/63343847/129552744-0ab147d5-337c-46c9-bb34-24ad05901472.png)
![image](https://user-images.githubusercontent.com/63343847/129552766-ad5c0754-51d9-481e-915b-428f5fc73299.png)
是直接把最新版的下载，然后按你说的步骤做的，还是报错，这边由于aistudio文件数量的限制生成不了版本，不能设置公共项目。你那边能否直接git clone到aistuidio试下看

**Comment by AI-Mart** [comment]
按照大佬的提示卸载aistudio底层的安装包，重新安装，可以运行了，谢谢

**Comment by ZeyuChen** [comment]
Issues Solved.
