### ISSUE TITLE
[Question]:  RuntimeError: (NotFound) Operator (one_hot) is not registered.   [

### ISSUE THREAD

**Issue by 77bw** [PaddlePaddle/PaddleNLP#8861]
### 请提出你的问题

conda install paddlepaddle-gpu==2.6.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
python -m pip install paddleocr==2.7.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
python -m pip install paddleclas==2.5.2
python -m pip install paddlenlp==2.6.1

我的版本是以上，因为我有其他项目有用的这个版本，我如何更改paddlenlp的版本使其不报错呢？

**Comment by DrownFish19** [comment]
paddlenlp降级到2.5或者2.4呢？或者检查出现问题的算子，paddlenlp仅为python代码，可以直接修改试试
