### ISSUE TITLE
[Question]: 训练ernie文本分类时，checkpoint文件夹内没有模型，只有个setting.txt文件

### ISSUE THREAD

**Issue by zqszqszqstvt** [PaddlePaddle/PaddleNLP#8865]
### 请提出你的问题

这是训练指令python train.py \
    --dataset_dir "data" \
    --device "gpu" \
    --max_seq_length 128 \
    --model_name "ernie-3.0-medium-zh" \
    --batch_size 32 \
    --epochs 10

日志上也没有报错，不过500条数据一分钟就训练完了且checkpoint内没有保存模型文件

**Comment by zqszqszqstvt** [comment]
有个问题就是micro f1 score:0.00000   ,macro f1 score:0.00000,经过测试，应该是train.py文件里的最后保存模型的判断没有执行，即if macro_f1_score>best_f1_score:判断为false，我增加以下训练批次试试

**Comment by zqszqszqstvt** [comment]
我的训练数据是自己标注的，按照README描述，
label.txt就是按照这个格式：
人生
人生##死亡
灾害/意外
灾害/意外##坍/垮塌
灾害/意外##车祸
产品行为
产品行为##召回
train.txt按照这个格式：
上海一改建厂房坍塌已救出19人其中5人死亡    人生,人生##死亡,灾害/意外,灾害/意外##坍/垮塌
车闻：广本召回9万余辆；领动上市，10.98万起；艾力绅混动    产品行为,产品行为##召回
86岁老翁过马路遭挖掘机碾压身亡警方：正在侦办中    灾害/意外,灾害/意外##车祸,人生,人生##死亡

**Comment by zqszqszqstvt** [comment]
我增加训练批次到100后micro f1 score和macro f1 score终于不是0了，但是仍旧很低，前者只有0.40000，后者0.2255

**Comment by wawltor** [comment]
这里说的训练批次是epoch还是step？

**Comment by zqszqszqstvt** [comment]
是epoch，这个问题可能是训练数据太少了？

**Comment by wawltor** [comment]
> 是epoch，这个问题可能是训练数据太少了？

需要关注数据量和数据质量；数据量足够多的话，原则上训练2-3 epoch就能达到不错的效果。

**Comment by zqszqszqstvt** [comment]
明白了，多谢兄台

**Comment by wawltor** [comment]
OK，有问题可以继续提issue。
