### ISSUE TITLE
[Bug]: 情感分析textcnn示例程序出错

### ISSUE THREAD

**Issue by ZhibangYue** [PaddlePaddle/PaddleNLP#8871]
### 软件环境

```Markdown
pip list | findstr paddle
-paddle2onnx              1.0.6
-paddlefsl                1.1.0
-paddlenlp                3.0.0b0
-paddlepaddle-gpu         3.0.0b1
其他可能有用的信息：
wmic os get Caption, Version, OSArchitecture
>>Microsoft Windows 11 家庭中文版  64 位           10.0.22631
python -V
>> Python3.10.14
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在某轮次训练的最后会出现如下错误，轮次不定，但报错时机相同
step 140/151 - loss: 0.3798 - acc: 0.8452 - avg_reader_cost: 0.00000 sec - avg_batch_cost: 0.00855 sec - ips: 7484.94164 samples/sec - 9ms/step
step 150/151 - loss: 0.5582 - acc: 0.8452 - avg_reader_cost: 0.00000 sec - avg_batch_cost: 0.00804 sec - ips: 7955.52890 samples/sec - 9ms/step
Traceback (most recent call last):
  File "e:\Python_craft\文本情感分析\textcnn\train.py", line 105, in <module>
    model.fit(train_loader, dev_loader, epochs=args.epochs, save_dir=args.save_dir, callbacks=callback)
  File "E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\model.py", line 1981, in fit
    cbks.on_epoch_end(epoch, logs)
  File "E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py", line 118, in on_epoch_end
    self._call('on_epoch_end', epoch, logs)
  File "E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py", line 95, in _call
    func(*args)
  File "E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py", line 440, in on_epoch_end
    self._updates(logs, 'train')
  File "E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py", line 405, in _updates
    % (samples / (timer['data_time'] + timer['batch_time'])),
ZeroDivisionError: float division by zero
```

### 稳定复现步骤 & 代码

代码即为[https://github.com/PaddlePaddle/PaddleNLP/blob/develop/legacy/examples/sentiment_analysis/textcnn/train.py](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/legacy/examples/sentiment_analysis/textcnn/train.py)

区别在于使用了提供的预训练模型，词表与训练数据均按照文档下载。
```Python
# 恢复模型训练
parser.add_argument("--init_from_ckpt", type=str, default="./textcnn.pdparams", help="The path of checkpoint to be loaded.")
```

**Comment by wawltor** [comment]
看起来这个问题是由Paddle框架中的hapi API导致的，建议直接修改这里的代码来临时解决问题 `"E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py"`

`(timer['data_time'] + timer['batch_time']) ` 时间为0.0导致的

**Comment by ZhibangYue** [comment]
> 看起来这个问题是由Paddle框架中的hapi API导致的，建议直接修改这里的代码来临时解决问题 `"E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py"`
> 
> `(timer['data_time'] + timer['batch_time']) ` 时间为0.0导致的

是的，修改此处代码可以避免这个错误，能够成功地完成模型的训练。不知道这里计算出的ips是否还影响其他地方。
```Python
            values.append(
                (
                    'ips',
                    "%.5f samples/sec"
                    % (samples / (timer['data_time'] + timer['batch_time'])),
                )
            )
```

**Comment by wawltor** [comment]
> > 看起来这个问题是由Paddle框架中的hapi API导致的，建议直接修改这里的代码来临时解决问题 `"E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py"`
> > `(timer['data_time'] + timer['batch_time']) ` 时间为0.0导致的
> 
> 是的，修改此处代码可以避免这个错误，能够成功地完成模型的训练。不知道这里计算出的ips是否还影响其他地方。
> 
> ```python
>             values.append(
>                 (
>                     'ips',
>                     "%.5f samples/sec"
>                     % (samples / (timer['data_time'] + timer['batch_time'])),
>                 )
>             )
> ```

看代码没有什么的影响

**Comment by ZhibangYue** [comment]
> > > 看起来这个问题是由Paddle框架中的hapi API导致的，建议直接修改这里的代码来临时解决问题 `"E:\anaconda3\envs\paddle\lib\site-packages\paddle\hapi\callbacks.py"`
> > > `(timer['data_time'] + timer['batch_time']) ` 时间为0.0导致的
> > 
> > 
> > 是的，修改此处代码可以避免这个错误，能够成功地完成模型的训练。不知道这里计算出的ips是否还影响其他地方。
> > ```python
> >             values.append(
> >                 (
> >                     'ips',
> >                     "%.5f samples/sec"
> >                     % (samples / (timer['data_time'] + timer['batch_time'])),
> >                 )
> >             )
> > ```
> 
> 看代码没有什么的影响

好的，感谢您的回复。既然此问题能够解决，我将关闭本issue。
希望开发者们能在下一版中修复这个小bug。
