### ISSUE TITLE
[Question]: uie抽取不出来两个类似的标签吗

### ISSUE THREAD

**Issue by zqszqszqstvt** [PaddlePaddle/PaddleNLP#8899]
### 请提出你的问题

使用model_zoo里面的uie进行文本信息抽取，数据集为doccano标注，其中有两个标签分别是"事发时间"和"事发地点"，除了这两个标签以外，还有"时间"和"地点"标签，"事发时间"和"事发地点"的训练数据分别有270多条和170多条，但是训练之后抽取时，10000多条数据，全都没有抽取出"事发时间"和"事发地点"，这个是为啥（其他标签都抽取出了数据）

**Comment by wawltor** [comment]
在样本分布上是否有偏差，例如大部分的样本抽取的都是时间和地点，而不是"事发时间"和"事发地点"

**Comment by zqszqszqstvt** [comment]
数据集总共400多条，包含"事发时间"和"事发地点"的训练数据分别有270多条和170多条，而“时间”只在98个数据中有，“地点”在131条数据中出现，应该不是样本分布的问题
