### ISSUE TITLE
PaddleNLP/examples/language_model/transformer-xl/gen_data.sh 下载数据太慢

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#890]
![image](https://user-images.githubusercontent.com/63343847/129561107-029d14a1-c06d-42c5-9610-bfeb82000a3e.png)
运行gen_data.sh下载数据集，提示需要2天才能下载完，想运行tansformer-xl，有没有其他便捷的方式获取数据集。

**Comment by FrostML** [comment]
这是官方的下载源，国内下载可能会慢一点，可以使用代理。
或者看看能否提供下邮箱什么的，我直接发您。

**Comment by AI-Mart** [comment]
***@***.*** 这是我邮箱，麻烦我发下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月17日(星期二) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] PaddleNLP/examples/language_model/transformer-xl/gen_data.sh 下载数据太慢 (#890)





 
这是官方的下载源，国内下载可能会慢一点，可以使用代理。
 或者看看能否提供下邮箱什么的，我直接发您。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FrostML** [comment]
![image](https://user-images.githubusercontent.com/7160927/130002930-37e0b8cf-9076-431c-ad30-f2179288aa3c.png)
邮箱信息似乎是被屏蔽了

**Comment by AI-Mart** [comment]
1955521136@qq.com这是我邮箱.另外我想咨询下大佬，一般的NLP相关任务的数据集去哪里下载呢，有没有一个通用的网站包含了大部分是NLP相关的数据集，就是论文里面经常拿来做实验的数据，通过这个网站我们可以便捷的找到，能否提供下相关的数据集下载网址

**Comment by ZeyuChen** [comment]
> [1955521136@qq.com](mailto:1955521136@qq.com)这是我邮箱.另外我想咨询下大佬，一般的NLP相关任务的数据集去哪里下载呢，有没有一个通用的网站包含了大部分是NLP相关的数据集，就是论文里面经常拿来做实验的数据，通过这个网站我们可以便捷的找到，能否提供下相关的数据集下载网址

没有的哈，多搜索搜索，多看点综述。

**Comment by AI-Mart** [comment]
@ FrostML  发我邮箱了吗，谢谢
