### ISSUE TITLE
[Bug]: paddlenlp 的 Taskflow使用 Taskflow("text_classification", mode='finetune')下载文件时路径组合有错导致无法正确下载。

### ISSUE THREAD

**Issue by starhot** [PaddlePaddle/PaddleNLP#8906]
### 软件环境

```Markdown
- paddlepaddle:2.6.1
- paddlenlp: 2.6.1
  Windows平台。
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
paddlenlp 的 Taskflow使用 Taskflow("text_classification", mode='finetune')下载文件时路径组合有错：
[2024-08-08 21:39:36,130] [    INFO] - Downloading tokenizer_config.json from https://bj.bcebos.com/paddlenlp/models/community/C:\Users\username\.paddlenlp\taskflow\text_classification\finetune/tokenizer_config.json
```

### 稳定复现步骤 & 代码

    from paddlenlp import Taskflow
    cls = Taskflow("text_classification", mode='finetune')

**Comment by wawltor** [comment]
如果使用finetune后的模型来预测，需要设置
` task_path='./checkpoint/model_best/plm'  `

**Comment by starhot** [comment]
> 如果使用finetune后的模型来预测，需要设置 `task_path='./checkpoint/model_best/plm' `

不是使用finetune后的模型，想先用自带的。就是无法成功下载。
