### ISSUE TITLE
[Question]: uie模型训练时max_seq_length 512报太小 1024又爆显存

### ISSUE THREAD

**Issue by yangguoer** [PaddlePaddle/PaddleNLP#8913]
### 请提出你的问题

uie模型训练时max_seq_length 512报太小：
![微信图片_20240811193938](https://github.com/user-attachments/assets/fc2b547a-d723-4c62-8a09-9673b3dad711)
max_seq_length 设置为1024：
![image](https://github.com/user-attachments/assets/4ef55149-d236-497d-8d31-089571fbf441)

**Comment by wawltor** [comment]
麻烦发下AIStudio的链接

**Comment by yangguoer** [comment]
https://aistudio.baidu.com/projectdetail/8232968
已经解决了，把下面两行注掉
![image](https://github.com/user-attachments/assets/1a7e6b71-c8f0-40a7-9961-a1275cc05865)
现在有另一个问题想问，训练时中断了怎么再从中断的地方开始训练？

**Comment by wawltor** [comment]
> https://aistudio.baidu.com/projectdetail/8232968 已经解决了，把下面两行注掉 ![image](https://private-user-images.githubusercontent.com/39733821/356927934-1a7e6b71-c8f0-40a7-9961-a1275cc05865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDM4NTEsIm5iZiI6MTcyMzQ0MzU1MSwicGF0aCI6Ii8zOTczMzgyMS8zNTY5Mjc5MzQtMWE3ZTZiNzEtYzhmMC00MGE3LTk5NjEtYTEyNzVjYzA1ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA2MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZjY5ZWMwMmZmYTBkNDBhMGM1NzM2OThjMjg1MTQxZDI1NzZiOGM0YTkxMjE0YzY3YWZhMTE4YTNhZWVhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YhGdwIGX4ahrvi9EKHpn_ysW4vY677J_Ths6l8rmEhA) 现在有另一个问题想问，训练时中断了怎么再从中断的地方开始训练？

麻烦将项目公开下，我们看看代码

**Comment by yangguoer** [comment]
> > https://aistudio.baidu.com/projectdetail/8232968 已经解决了，把下面两行注掉 ![image](https://private-user-images.githubusercontent.com/39733821/356927934-1a7e6b71-c8f0-40a7-9961-a1275cc05865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDM4NTEsIm5iZiI6MTcyMzQ0MzU1MSwicGF0aCI6Ii8zOTczMzgyMS8zNTY5Mjc5MzQtMWE3ZTZiNzEtYzhmMC00MGE3LTk5NjEtYTEyNzVjYzA1ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA2MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZjY5ZWMwMmZmYTBkNDBhMGM1NzM2OThjMjg1MTQxZDI1NzZiOGM0YTkxMjE0YzY3YWZhMTE4YTNhZWVhMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YhGdwIGX4ahrvi9EKHpn_ysW4vY677J_Ths6l8rmEhA) 现在有另一个问题想问，训练时中断了怎么再从中断的地方开始训练？
> 
> 麻烦将项目公开下，我们看看代码

已公开
