### ISSUE TITLE
[Bug]: paddlenlp/transformers/layoutxlm/modeling.py line：1183-1188 测试下来代码存在bug，negative_mask一直为False的bool值

### ISSUE THREAD

**Issue by kezidanbao** [PaddlePaddle/PaddleNLP#8915]
### 软件环境

```Markdown
- paddlepaddle:
- paddlepaddle-gpu: 2.6.1
- paddlenlp: 3.0.0b0.post20240810
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
paddlenlp/transformers/layoutxlm/modeling.py line：1183-1188
测试下来代码存在bug，negative_mask一直为False的bool值，使用sum()函数指定报错。
```

### 稳定复现步骤 & 代码

            mask = paddle.all(all_possible_relations_repeat == positive_relations_repeat, axis=2)
            negative_mask = paddle.any(mask, axis=1) is False
            negative_relations = all_possible_relations[negative_mask]

            positive_mask = paddle.any(mask, axis=0) is True
            positive_relations = positive_relations[positive_mask]
            if negative_mask.sum() > 0:
                reordered_relations = paddle.concat([positive_relations, negative_relations])
            else:
                reordered_relations = positive_relations

**Comment by dioif** [comment]
我是这么解决的：
1. 降级paddlenlp到2.8.1
2. 把 错误处前几行的        negative_mask = paddle.any(mask, axis=1) is False 改为        negative_mask = paddle.any(mask, axis=1) == False，positive mask同理
