### ISSUE TITLE
[Bug]: run_finetune.py ./config/qwen/lora_argument.json 参数解析错误

### ISSUE THREAD

**Issue by WhuanY** [PaddlePaddle/PaddleNLP#8917]
### 软件环境

```Markdown
- paddlepaddle:/
- paddlepaddle-gpu: 3.0.0b1
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
在paddlenlp/llm/ 执行python run_finetune.py ./config/qwen/lora_argument.json 时。脚本参数解析和配置json文件不一致。
```

## 编辑器环境
使用VSCode IDE的python debugger.
![Screenshot 2024-08-12 at 13 32 29](https://github.com/user-attachments/assets/a273c69b-7855-49d0-86b6-4ba4e868a8fa)
./config/qwen/lora_argument.json配置如上图右侧所示。

## 具体问题代码行
运行run_finetune.py进入主函数main()，执行到如下图所示代码行时，调试面板显示train_args.do_eval = true.
![Screenshot 2024-08-12 at 13 35 30](https://github.com/user-attachments/assets/6d0262d8-f43e-4700-aae4-6f51c9133a16)
这和我已经保存好的lora_argument.json参数设置不一致！（.json文件中do_eval=false)

这导致后面解析数据文件时，主函数进入错误的分支。

希望能够提供建议！

**Comment by lugimzzz** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/0a5de127b75246eae3784fd6dbbf4a88c2b7a734/paddlenlp/trainer/training_args.py#L875 如果要保证do_eval为False，请设置evaluation_strayegy:"no"

**Comment by WhuanY** [comment]
Thanks
