### ISSUE TITLE
[Question]: llama多卡高性能推理

### ISSUE THREAD

**Issue by wojiaoshihua** [PaddlePaddle/PaddleNLP#8923]
### 请提出你的问题

我用的是llama静态图WINT 8量化推理，但由于显存原因，我需要多卡推理。我应该如何修改以使得导出的静态图以让存在静态图的模型参数可以分布到多张卡上，并进行通信

**Comment by vivienfanghuagood** [comment]
这个功能暂未支持，预计在8月底之前会提供。

**Comment by wojiaoshihua** [comment]
> 这个功能暂未支持，预计在8月底之前会提供。


好的，谢谢回复，期待功能完善。

**Comment by wojiaoshihua** [comment]
> 这个功能暂未支持，预计在8月底之前会提供。

好的，谢谢回复，期待功能完善。
