### ISSUE TITLE
ernie-develop本地数据预训练后效果变差

### ISSUE THREAD

**Issue by Zengpr** [PaddlePaddle/PaddleNLP#895]
请问ernie-develop按照说明进行本地数据预训练后效果变差，训练越久效果越差是什么原因呢？不管是字粒度还是词粒度都是

**Comment by ZeyuChen** [comment]
@ZHUI 提供下ERNIE-1.0版本的预训练流程代码 @Zengpr 试试PaddleNLP下的ernie预训练流程。

**Comment by ZHUI** [comment]
> 请问ernie-develop按照说明进行本地数据预训练后效果变差，训练越久效果越差是什么原因呢？不管是字粒度还是词粒度都是

你好，我们PaddleNLP这边提供了新版的数据处理流程+预训练流程。https://github.com/PaddlePaddle/PaddleNLP/pull/816 目前文档还是不是很完善，欢迎试用，有问题随时反馈给我 @Zengpr
