### ISSUE TITLE
[Question]: 在使用UIE 进行事件提取时,我想在自己的数据上进行训练, 但是没有触发词的标注. 请问UIE在是否能够支持无触发词数据的模型训练?

### ISSUE THREAD

**Issue by dinobot22** [PaddlePaddle/PaddleNLP#8951]
### 请提出你的问题

在使用UIE 进行事件提取时,我想在自己的数据上进行训练, 但是没有触发词的标注. 请问UIE在是否能够支持无触发词数据的模型训练?

**Comment by wawltor** [comment]
不支持无触发词的事件抽取，因为事件抽取比较依赖触发词；如果不希望有触发词可以看看能不能用一些关系抽取来替代。
