### ISSUE TITLE
paddle3.0与paddlenlp兼容问题

### ISSUE THREAD

**Issue by c123853648** [PaddlePaddle/PaddleNLP#8959]
### bug描述 Describe the Bug

`from paddlenlp import Taskflow`
`docprompt = Taskflow("document_intelligence")`
这段代码在paddle2.5.1+paddlenlp2.6.1中运行正常，现在因为要适配寒武纪mlu370想升级paddle3.0时发现，升级后，无论paddlenlp版本是2.6.1还是3.0.0b0，都会报错
`RuntimeError: (NotFound) Operator (fill_zeros_like) is not registered.
  [Hint: op_info_ptr should not be null.] (at ..\paddle/fluid/framework/op_info.h:152)`
![微信截图_20240819143311](https://github.com/user-attachments/assets/aadc73c1-6b43-4045-b5a2-e4e708b78811)

### 其他补充信息 Additional Supplementary Information

一个题外话：我如果想在寒武纪mlu370上运行Taskflow("document_intelligence")这个任务，是否需要升级paddle3.0呢？

**Comment by wawltor** [comment]
有可能是paddle 3.0对mlu370硬件支持有问题，建议到paddlepaddle的issue上提出问题；同时Taskflow("document_intelligence")不依赖paddle 3.0的升级

**Comment by c123853648** [comment]
> 有可能是paddle 3.0对mlu370硬件支持有问题，建议到paddlepaddle的issue上提出问题；同时Taskflow("document_intelligence")不依赖paddle 3.0的升级

现在paddlenlp是否支持mlu的芯片？看到paddlenlp/utils/tools.py 119行的get_env_device中没有mlu的支持项
