### ISSUE TITLE
[Question]: 数据集加载失败，老是报错。

### ISSUE THREAD

**Issue by Jakin-huang** [PaddlePaddle/PaddleNLP#8960]
### 请提出你的问题

![image](https://github.com/user-attachments/assets/887fce84-d1bd-4372-b60c-9a509295944c)

就加载普通的json数据
![image](https://github.com/user-attachments/assets/2fa1b8f4-474d-4f34-a819-e708fdbc03b2)

**Comment by wawltor** [comment]
麻烦提供下复现代码以及paddlenlp的版本信息
