### ISSUE TITLE
[Question]: 参考roberta文档进行fine-tune，发现没有对应脚本

### ISSUE THREAD

**Issue by a31413510** [PaddlePaddle/PaddleNLP#9036]
### 请提出你的问题

参考文档：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/legacy/model_zoo/roberta/README.md#fine-tune
![image](https://github.com/user-attachments/assets/17792fab-77ea-412a-8262-46a98ecc69b5)
但是该目录下没有对应的run_glue.py

**Comment by wawltor** [comment]
可以使用下面的链接 https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.8/examples/benchmark/glue/run_glue.py，同时修复下相关问题。
