### ISSUE TITLE
[Question]: utc模型是否有关于输入长度限制的说明？如何处理长度超过2048的字符串输入

### ISSUE THREAD

**Issue by fakelucy** [PaddlePaddle/PaddleNLP#9065]
### 请提出你的问题

设置max_seq_length 512的情况下，报错：

[ WARNING]  -Token indices sequence length is longer than the specified maximum sequence length for this model (5172 > 2048). Running this sequence through the model will result in indexing errors

是否意味着utc模型最高支持2048的输出，设置更大的max_seq_length是否有效

**Comment by wawltor** [comment]
UTC的底座模型是支持支持2048，但是UTC训练过程中只针对了512长度数据进行了训练，所以建议不要超过512的数据长度。超过512的长度建议通过一些数据清洗和数据策略将长度进行裁剪。
