### ISSUE TITLE
[Bug]: Taskflow预测二分类问题，多线程预测程序崩溃

### ISSUE THREAD

**Issue by zhangdd3537** [PaddlePaddle/PaddleNLP#9066]
### 软件环境

```Markdown
- paddlepaddle:2.6.1
- paddlepaddle-gpu: 2.6.1
- paddlenlp: 2.6.1
```

### 重复问题

- [X] I have searched the existing issues

### 错误描述

```Markdown
按照这个教程（https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.6/applications/text_classification/multi_class）训练完成的模型，使用Taskflow进行预测， 单进程运行没有问题，但是多进程或者多线程（进程或者线程数大于2）程序就会崩溃（主要报错Segmentation fault）
```

### 稳定复现步骤 & 代码
https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.6/applications/text_classification/multi_class 训练完成的模型，使用Taskflow进行多线程预测，程序会崩溃（主要报错Segmentation fault）

**Comment by wawltor** [comment]
能发下报错截图吗？

**Comment by zhangdd3537** [comment]
@wawltor![image](https://github.com/user-attachments/assets/f0be326b-8b58-490c-b46a-ac364518831f)

**Comment by zhangdd3537** [comment]
已经解决，加线程锁，参考代码https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.6/paddlenlp/server/taskflow_manager.py
