### ISSUE TITLE
[Question]: 如何使用PaddleNlp的albert模型进行训练

### ISSUE THREAD

**Issue by a31413510** [PaddlePaddle/PaddleNLP#9078]
### 请提出你的问题

如何使用PaddleNlp的albert模型进行训练，在model_zoo里似乎没有找到albert模型

**Comment by wawltor** [comment]
albert和bert的训练方式基本一致，可以参考bert模型的训练方式，可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/70da48252f2828534862424cfba9a48f60970c5e/legacy/model_zoo/bert/run_glue_trainer.py#L60  

同时稍微改动几行代码，支持albert训练，传入传入albert的Class名字，具体的Class名字可以参考 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/albert/modeling.py

**Comment by a31413510** [comment]
请问是这么添加吗

**Comment by a31413510** [comment]
请问是这么添加吗
"albert": (AlbertForSequenceClassification, AlbertTokenizer),
除此之外，还有什么需要修改的吗

**Comment by tianchiguaixia** [comment]
你使用torch就10行代码就可以微调albert
