### ISSUE TITLE
[Question]: 关于uie微调

### ISSUE THREAD

**Issue by maymay1982** [PaddlePaddle/PaddleNLP#9096]
### 请提出你的问题

为什么找不到uie微调相关的代码了，比如https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.py这些网页都打不开了。

**Comment by tammy-na** [comment]
[PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/legacy/model_zoo/uie)

**Comment by JoshonSmith** [comment]
2.8等之前版本有这个代码
