### ISSUE TITLE
PaddleNLP/examples/text_matching/question_matching/  竞赛网址链接无效，数据集没法下载

### ISSUE THREAD

**Issue by AI-Mart** [PaddlePaddle/PaddleNLP#910]
数据准备
本项目使用竞赛提供的 LCQMC、BQ、OPPO 这 3 个数据集的训练集合集作为训练集，使用这 3 个数据集的验证集合集作为验证集。

运行如下命令生成本项目所使用的训练集和验证集，您在参赛过程中可以探索采取其它的训练集和验证集组合，不需要和基线方案完全一致。

cat ./data/train/LCQMC/train ./data/train/BQ/train ./data/train/OPPO/train > train.txt
cat ./data/train/LCQMC/dev ./data/train/BQ/dev ./data/train/OPPO/dev > dev.txt

竞赛网址链接无效，以上数据集没法下载，能否提供下正确的数据集下载网址

**Comment by tianxin1860** [comment]
> 数据准备
> 本项目使用竞赛提供的 LCQMC、BQ、OPPO 这 3 个数据集的训练集合集作为训练集，使用这 3 个数据集的验证集合集作为验证集。
> 
> 运行如下命令生成本项目所使用的训练集和验证集，您在参赛过程中可以探索采取其它的训练集和验证集组合，不需要和基线方案完全一致。
> 
> cat ./data/train/LCQMC/train ./data/train/BQ/train ./data/train/OPPO/train > train.txt
> cat ./data/train/LCQMC/dev ./data/train/BQ/dev ./data/train/OPPO/dev > dev.txt
> 
> 竞赛网址链接无效，以上数据集没法下载，能否提供下正确的数据集下载网址

此竞赛暂未正式开始，正式开始前会于近期发布数据集，感谢关注~

**Comment by chenxiaozeng** [comment]
竞赛地址：https://aistudio.baidu.com/aistudio/competition/detail/116/0/introduction
