### ISSUE TITLE
[Question]: 层次分类方案区别（文本分类hierarchical、通用文本分类UTC）

### ISSUE THREAD

**Issue by wuys1** [PaddlePaddle/PaddleNLP#9104]
### 请提出你的问题

【场景】：层次分类/多标签分类。最底层级label数有2000+
【方案】：
1、文本分类（层次分类hierarchical）。理解下来就是可以基于ernie-3.0-medium-zh或其他预训练模型，然后用下游任务数据集来更新模型参数，在label上的做法就是”拍平“做多标签分类。https://github.com/PaddlePaddle/PaddleNLP/blob/release/2.9/applications/text_classification/hierarchical/README.md
2、通用文本分类UTC。https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.9/applications/zero_shot_text_classification

【问题】：
1、UTC也可以做层次分类（https://github.com/PaddlePaddle/PaddleNLP/issues/4973）。UTC和第一种文本分类在架构上的核心区别是什么？
2、这两种文本分类方式各适用什么场景？
3、如果像我业务场景label数非常多，适合用哪一种方案？

**Comment by wawltor** [comment]
1. UTC可以做层次分类，UTC采用的是一种类似Prompt 信息抽取的方式来做文本分类，而第一种是常规分类方式来做文本分类。
2. UTC比较适合小样本场景(具备一定的zero-shot能力)，常规文本分类比较适合数据量比较充分的场景。
3. 数据label比较适合常规文本分类的场景，UTC是将label拼接在prompt前面，如果label比较多建议使用常规文本分类的方式。
