### ISSUE TITLE
[Question]: 将一些发票的ocr识别结果用llm提取关键信息，需要微调大模型？OCR识别结果没有语义，如果区微调有意义？

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/PaddleNLP#9142]
### 请提出你的问题

question：请帮我提取提取座位号
input：7788.com Z57A001950 杭州东售 2013年07月07日13:39开 06车12B号 二等座 G7512次 杭州东 上海虹桥 HangZhouDong ShangHaiHongQiao ￥73.00元 限乘当日当次车 余友红 检票口16 3623301993****0941 9004-1300-5707-08A0-0195-0 和谐号 CanonPowerShotA3400 ISF2.8 1/20s IS0400
output： 06车12B号

这种没有语义的数据微调大模型是否有效？

**Comment by JoshonSmith** [comment]
有解决吗

**Comment by cqray1990** [comment]
> 有解决吗

没有好的方法，你也想微调？

**Comment by JoshonSmith** [comment]
> > 有解决吗
> 
> 没有好的方法，你也想微调？

我看到 PPchatOCR 可以实现类似功能

**Comment by cqray1990** [comment]
> > > 有解决吗
> > 
> > 
> > 没有好的方法，你也想微调？
> 
> 我看到 PPchatOCR 可以实现类似功能

 我也看了，不知道她是否用了的文心的通用能力，还是于训练加了此类数据，或者是否哦微调，但是微调感觉不太可能
