### ISSUE TITLE
'dict' object is not callable

### ISSUE THREAD

**Issue by cheeryoung79** [PaddlePaddle/PaddleNLP#917]
我用model=paddle.load('ernie_result/model_380.pdparams')加载模型，结果预测报错：

---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-9-4e4d9f987eba> in <module>
      1 #模型预测
----> 2 preds = predict(model, test_loader, test_ds, label_vocab)
      3 print(preds[0:10])
      4 file_path = "ernie_results.txt"
      5 with open(file_path, "w", encoding="utf8") as fout:
<ipython-input-8-3275ced3c794> in predict(model, data_loader, ds, label_vocab)
      3     len_list = []
      4     for input_ids, seg_ids, lens, labels in data_loader:
----> 5         logits = model(input_ids, seg_ids)
      6         pred = paddle.argmax(logits, axis=-1)
      7         pred_list.append(pred.numpy())
TypeError: 'dict' object is not callable

我该怎么解决？

**Comment by guoshengCS** [comment]
`model=paddle.load('ernie_result/model_380.pdparams')` 会返回一个以模型参数名为key、参数值为value的dict，并非直接load进来一个模型，需要重新创建一个模型对象并通过`model.set_dict`方法来载入刚才load的参数来进行预测

**Comment by cheeryoung79** [comment]
谢谢。按这个方法好用了。
