### ISSUE TITLE
run_ernie.py 训练自有数据 loss NAN

### ISSUE THREAD

**Issue by 44show** [PaddlePaddle/PaddleNLP#919]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤
import paddle
import paddlenlp
paddle.version
'2.1.1'
paddlenlp.version
'2.0.7'
Linux python3.6

paddlenlp的同学，你们好。
发现一个奇怪的现象：用自有数据训练 run_ernie.py 训一训 loss 就NAN 然后把shuffle关掉，固定batch_size 为8 发现总是在训到某个固定的iter loss 变为nan，以为是那个iter的数据问题  检查数据 没发现啥问题， 于是把前面的iter跳过 直接到nan 的iter或者从它前面几个iter开始 又不是nan了 感觉是什么状态被累计了 然后导致的问题。 如下面日志所示：不是在step:8198 就是在step:8199 出现nan 多次实验 都是在这两个step出现nan

8198 [TRAIN] Epoch:0 - Step:8194 - Loss: 0.406097
8199 [TRAIN] Epoch:0 - Step:8195 - Loss: 0.323664
8200 [TRAIN] Epoch:0 - Step:8196 - Loss: 0.215757
8201 [TRAIN] Epoch:0 - Step:8197 - Loss: 0.238531
8202 [TRAIN] Epoch:0 - Step:8198 - Loss: nan
8203 [TRAIN] Epoch:0 - Step:8199 - Loss: nan

 8197 [TRAIN] Epoch:0 - Step:8193 - Loss: 0.000708
 8198 [TRAIN] Epoch:0 - Step:8194 - Loss: 0.469333
 8199 [TRAIN] Epoch:0 - Step:8195 - Loss: 0.272361
 8200 [TRAIN] Epoch:0 - Step:8196 - Loss: 0.195206
 8201 [TRAIN] Epoch:0 - Step:8197 - Loss: 0.223975
 8202 [TRAIN] Epoch:0 - Step:8198 - Loss: 0.140920
 8203 [TRAIN] Epoch:0 - Step:8199 - Loss: nan
 8204 [TRAIN] Epoch:0 - Step:8200 - Loss: nan

**Comment by guoshengCS** [comment]
可否使用develop版本的Paddle，参考这里 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/flags/check_nan_inf_cn.html 使用check nan inf工具来检查下呢

**Comment by wawltor** [comment]
能提供一下训练脚本的位置吗？

**Comment by 44show** [comment]
> 能提供一下训练脚本的位置吗？
在waybill_ie例子下面。
PaddleNLP/examples/information_extraction/waybill_ie

**Comment by 44show** [comment]
@guoshengCS 具体要怎么操作呢，我paddle是通过，pip安装的，现在是需要clone源码 然后切换到dev分支，源码编译安装，才能使用“FLAGS_check_nan_inf” 是吧？

**Comment by 44show** [comment]
@wawltor 我现在是把batch_size设置为1和2 是不会出现nan.

**Comment by guoshengCS** [comment]
> 我paddle是通过，pip安装的，现在是需要clone源码 然后切换到dev分支，源码编译安装

也可以从Paddle官网选择dev的whl包安装
![image](https://user-images.githubusercontent.com/14105589/130759890-6bf38f4d-df8b-4b8b-b1bf-396f1c65a0c4.png)
