### ISSUE TITLE
[GPT pretrain] gpt: create_pretraining_data 速度慢。

### ISSUE THREAD

**Issue by duchengyao** [PaddlePaddle/PaddleNLP#922]
正在处理 openwebtext 数据，执行到 create_pretraining_data 时需要处理 8013769 个文件，大约250个小时。

请问有提速的办法吗？
或者是否有Megatron的npz转paddle npz的方法？
十分感谢。

**Comment by ZHUI** [comment]
等我的PR，预计明天更新。
最新版本的数据流程已经大大优化了速度 https://github.com/PaddlePaddle/PaddleNLP/pull/816 。可以用这个PR的最新数据流先处理数据，https://github.com/ZHUI/PaddleNLP/blob/pretraining_data/examples/language_model/data_tools/README.md 

等这个PR  https://github.com/PaddlePaddle/PaddleNLP/pull/816 合入了，我再提一个适配GPT到新版数据流的PR，就可以用GPT训练最新格式的数据了。

**Comment by duchengyao** [comment]
谢谢大佬！

**Comment by ZHUI** [comment]
新版GPT数据流程来了 https://github.com/PaddlePaddle/PaddleNLP/pull/930 
我这边自测，使用 https://openwebtext2.readthedocs.io/en/latest/index.html 的 Download Plug and Play Version 版本openwebtext2 数据：
```
17,103,059 documents
65.86 GB uncompressed text
28 GB compressed including text and metadata
```
预处理速度约20MB/s，总共约耗时1小时左右。

**Comment by duchengyao** [comment]
> 新版GPT数据流程来了 #930
> 我这边自测，使用 https://openwebtext2.readthedocs.io/en/latest/index.html 的 Download Plug and Play Version 版本openwebtext2 数据：
> 
> ```
> 17,103,059 documents
> 65.86 GB uncompressed text
> 28 GB compressed including text and metadata
> ```
> 
> 预处理速度约20MB/s，总共约耗时1小时左右。

牛啊牛啊
