### ISSUE TITLE
昆仑芯R200跑paddlenlp快速开始失败

### ISSUE THREAD

**Issue by Newcomer-CL** [PaddlePaddle/PaddleNLP#9227]
### 请提出你的问题

环境：
1）CPU：Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
2）XPU：R200
3）系统环境：ubuntu20.04
4）gcc/g++ ：8.4
5）python版本：3.10
6）paddle-xpu：paddlepaddle_xpu-3.0.0.dev20240925-cp310-cp310
7）paddlenlp：3.0.0b1.post20240929

![image](https://github.com/user-attachments/assets/8da97d20-8b55-41c9-a67b-bda7641ec66d)

**Comment by DrownFish19** [comment]
暂时Qwen2还未测试对国产硬件的支持情况，正在支持中。之后会在主页展示不同模型对国产芯片的支持能力。
