### ISSUE TITLE
wordtag 问题

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/PaddleNLP#927]
- 版本、环境信息
PaddleNLP 2.0.8，PaddlePaddle2.1.1
win10
python3.7

- 复现信息：如为报错，请给出复现环境、复现步骤
使用wordtag中predict.py脚本，输出Process finished with exit code -1073741819 (0xC0000005)，不返回预测结果

**Comment by wawltor** [comment]
from paddlenlp.taskflow import TaskFlow
task = TaskFlow("text2knowledge", model="wordtag")
task(["热梅茶是一道以梅子为主要原料制作的茶饮",
      "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
task("热梅茶是一道以梅子为主要原料制作的茶饮")


@zhentaoCoding  可以尝试使用taskflow API 后续我们会将predict脚本用taskflow api替换 
如有问题，麻烦再反馈

**Comment by ZTurboX** [comment]
> from paddlenlp.taskflow import TaskFlow
> task = TaskFlow("text2knowledge", model="wordtag")
> task(["热梅茶是一道以梅子为主要原料制作的茶饮",
> "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
> task("热梅茶是一道以梅子为主要原料制作的茶饮")
> 
> @zhentaoCoding 可以尝试使用taskflow API 后续我们会将predict脚本用taskflow api替换
> 如有问题，麻烦再反馈

也是同样的问题

**Comment by wawltor** [comment]
> > from paddlenlp.taskflow import TaskFlow
> > task = TaskFlow("text2knowledge", model="wordtag")
> > task(["热梅茶是一道以梅子为主要原料制作的茶饮",
> > "《孤女》是2010年九州出版社出版的小说，作者是余兼羽"])
> > task("热梅茶是一道以梅子为主要原料制作的茶饮")
> > @zhentaoCoding 可以尝试使用taskflow API 后续我们会将predict脚本用taskflow api替换
> > 如有问题，麻烦再反馈
> 
> 也是同样的问题

麻烦提供一下内存，GPU型号和显存配置

如果只是有CPU的机器 看起来是内存不足导致的
