### ISSUE TITLE
[Question]: from eval import evaluate 这个怎么用？为什么这个包没有找到？

### ISSUE THREAD

**Issue by xiaohaifen** [PaddlePaddle/PaddleNLP#9284]
### 请提出你的问题

from eval import evaluate 这个怎么用？为什么这个包没有找到？

**Comment by xiaohaifen** [comment]
求指导，谢谢各位

**Comment by wawltor** [comment]
> 求指导，谢谢各位

具体是使用哪个教程遇到的问题了？

**Comment by xiaohaifen** [comment]
谢谢您，我找到问题所在了，这个eval是在aistudio环境里面的eval.py，之前一直以为是官方的第三方库
