### ISSUE TITLE
[Question]: 如何使用PaddleNLP，使用LoRA微调LLama 3.1 8B的模型

### ISSUE THREAD

**Issue by yaphet266** [PaddlePaddle/PaddleNLP#9285]
### 请提出你的问题

如何使用PaddleNLP，使用LoRA微调LLama 3.1 8B的模型，有没有参考文档和视频教程提供

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm   相关训练的工作在这里
这个是使用lora方法的例子，如果需要切换不同的模型和训练配置，需要修改 llama/lora_argument.json  配置文件
