### ISSUE TITLE
[Question]: 本地只有4张4090显卡是否可以使用LoRA训练LLama 3.1 8b的模型

### ISSUE THREAD

**Issue by yaphet266** [PaddlePaddle/PaddleNLP#9293]
### 请提出你的问题

我现在只有4张4090显卡，单卡显存24G，总显存只有96G，是否可以训练LLama 3.1 8b的模型，我现在按照官网文档无法运行成功，请问如何调整参数可以在比较少显存的情况下进行训练

**Comment by DrownFish19** [comment]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/1cbcf2ba-3ad7-48ab-bddf-7fdc9ee55001">

如计算，model state最少需要104GB，4张24G显卡仅有96G，无法使用SFT进行计算。可以考虑使用LoRA方法进行微调。

**Comment by yaphet266** [comment]
如果使用LoRA微调大概需要多大的显存，我看有很多种量化方式，各有什么区别

**Comment by DrownFish19** [comment]
LoRA暂时没有计算数据和统计信息。给一个计算公式
```
# llama3.1-8B
model_state = 16L * (2H + (2+2/G)(HR+RH) + 3(HR+RH_))
H = 4096, H_=14336, L=32, R=128, G=4

SFT : 16*32*(2*4096+2.5*4096*4096+3*4096*14336)/2^30 = 104GB
LoRA: 16*32*(2*4096+2.5*(4096*128+128*4096)+3*(4096*128+128*14336))/2^30 = 4.62GB 
```
激活值变化比较小，主要看seq_len，根据你们需求调整就可以了。

量化教程可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/docs/quantization.md

**Comment by yaphet266** [comment]
好的，明白了，多谢支持

**Comment by DrownFish19** [comment]
> LoRA暂时没有计算数据和统计信息。给一个计算公式
> 
> ```
> # llama3.1-8B
> model_state = 16L * (2H + (2+2/G)(HR+RH) + 3(HR+RH_))
> H = 4096, H_=14336, L=32, R=128, G=4
> 
> SFT : 16*32*(2*4096+2.5*4096*4096+3*4096*14336)/2^30 = 104GB
> LoRA: 16*32*(2*4096+2.5*(4096*128+128*4096)+3*(4096*128+128*14336))/2^30 = 4.62GB 
> ```
> 
> 激活值变化比较小，主要看seq_len，根据你们需求调整就可以了。
> 
> 量化教程可以参考这里：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/docs/quantization.md

此处勘误LoRA的显存占用分析，还需要加上非训练参数的模型参数显存占用，计算公式如下：

```
# llama3.1-8B
model_state = 16L * (2H + (2+2/G)(HR+RH) + 3(HR+RH_)) + 2L *  (2H + (2+2/G)H^2 + 3HH_)
H = 4096, H_=14336, L=32, R=128, G=4

LoRA: 16*32*(2*4096+2.5*(4096*128+128*4096)+3*(4096*128+128*14336)) / 2^30 
           + 2*32*(2*4096+2.5*4096*4096+3*4096*14336) / 2^30
           = 17.63GB 
```

**Comment by yaphet266** [comment]
@DrownFish19 感谢提供参考。17.63那个是比较符合实际占用的，我想知道
H、H_、L、R、G分别对应的中文名称是什么，分别表示什么含义

**Comment by DrownFish19** [comment]
> @DrownFish19 感谢提供参考。17.63那个是比较符合实际占用的，我想知道 H、H_、L、R、G分别对应的中文名称是什么，分别表示什么含义

H: hidden_size
H_: intermediate_size
L: num_hidden_layes
R: LoRA r_size
G: GQA的组数
