### ISSUE TITLE
[Question]: [关于开源贡献者]如何执行特定的单元测试？

### ISSUE THREAD

**Issue by WhuanY** [PaddlePaddle/PaddleNLP#9302]
### 请提出你的问题

目前我正在开发[LoKrModel](https://github.com/PaddlePaddle/PaddleNLP/pull/9269)。目前自己开发的模型希望仅执行LoKrModel部分的单测，请问有无方便开源贡献者参考的单测和集成测试的相应文档描述，谢谢？

**Comment by WhuanY** [comment]
Found. But suggest to add .md under PaddleNLP/test

**Comment by ZHUI** [comment]
pytest tests/xxx.py 可以测试
