### ISSUE TITLE
[Question]: 使用taskflow模型在arm机器上训练限制cpu为半数核以上才能性能正常

### ISSUE THREAD

**Issue by Serenagirl** [PaddlePaddle/PaddleNLP#9308]
### 请提出你的问题

使用taskflow的ner模型直接进行推理，多次测试时发现执行推理时限制cpu为半数以下cpu时性能很差是为什么？

**Comment by Serenagirl** [comment]
推理的时候不管给多少cpu，htop命令查看，cpu的占比都是满的

**Comment by wawltor** [comment]
https://github.com/PaddlePaddle/PaddleNLP/blob/75517304a73e6725cb7bd6815d8c2217ada64d8d/paddlenlp/taskflow/task.py#L56  目前taskflow默认是使用cpu核数一半来进行推理，这里代码可能使用是物理核数一半来推理，当容器内核数不够时可能会对性能产出影响。

**Comment by Serenagirl** [comment]
> https://github.com/PaddlePaddle/PaddleNLP/blob/75517304a73e6725cb7bd6815d8c2217ada64d8d/paddlenlp/taskflow/task.py#L56
> 
> 目前taskflow默认是使用cpu核数一半来进行推理，这里代码可能使用是物理核数一半来推理，当容器内核数不够时可能会对性能产出影响。

好的，请问如何查看paddlenlp在linux的安装位置并修改源码，或者如何在使用taskflow模型的时候加上num_threads参数

**Comment by wawltor** [comment]
pip show paddlenlp 可以看 `Location`，Location就是安装位置

**Comment by Serenagirl** [comment]
已解决感谢
