### ISSUE TITLE
examples代码疑似错误

### ISSUE THREAD

**Issue by iamqiz** [PaddlePaddle/PaddleNLP#938]
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/information_extraction/DuIE/data_loader.py
这个文件152-164行这段代码 语法很奇怪(如下), 162-164这几行看不懂,else和if 不是同一列,还有164行的break 也看懵逼了
而且更奇怪的是,我模仿写了类似的代码,居然没有报错 

```python
    for (i, token) in enumerate(sub_text):
        orig_to_tok_index.append(len(tokens))
        sub_tokens = tokenizer._tokenize(token)
        text_tmp += token
        for sub_token in sub_tokens:
            tok_to_orig_start_index.append(len(text_tmp) - len(token))
            tok_to_orig_end_index.append(len(text_tmp) - 1)
            tokens.append(sub_token)
            if len(tokens) >= max_length - 2:
                break
        else:        //162行,这个else和if 怎么没对齐
            continue
        break       //164行
```

**Comment by libertatis** [comment]
代码没有错，这是 `Python3` 的语法：
[https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops](https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops)
`for/while ... else` ，其中 `for/while` 为正常的循环语句，后面的 `else` 子句，当 `for` 循环正常迭代完毕，或 `while` 循环条件为假时执行，当 `for/while` 循环是由 `beak` 语句跳出，`else` 语句则不执行。 如果这里不使用 `else` 子句，你需要设置一个 `flag` 标志位。

**Comment by iamqiz** [comment]
> 使用 `else` 子句

啊 卧槽, _(:з」∠)_这样啊, 谢谢你 ~
python3语法变化好大呀,前几天遇到一个关于dict元素顺序的问题,结果有人告诉我py3的字典元素是有顺序的, 当时也震惊了
再次感谢, 老铁早点休息~

**Comment by iamqiz** [comment]
> 代码没有错，这是 `Python3` 的语法：
> https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops
> `for/while ... else` ，其中 `for/while` 为正常的循环语句，后面的 `else` 子句，当 `for` 循环正常迭代完毕，或 `while` 循环条件为假时执行，当 `for/while` 循环是由 `beak` 语句跳出，`else` 语句则不执行。 如果这里不使用 `else` 子句，你需要设置一个 `flag` 标志位。

啊 卧槽, _(:з」∠)_这样啊, 谢谢你 ~
python3语法变化好大呀,前几天遇到一个关于dict元素顺序的问题,结果有人告诉我py3的字典元素是有顺序的, 当时也震惊了
再次感谢, 老铁早点休息~
