### ISSUE TITLE
[Question]: TaskFlow推理报错: AssertionError: The models name: /checkpoint/model_best is not in task:[information_extraction]

### ISSUE THREAD

**Issue by fxb392** [PaddlePaddle/PaddleNLP#9383]
### 请提出你的问题

- paddlepaddle-gpu: 2.5.2
- paddlenlp: 2.5.2

TaskFlow推理报错:
AssertionError: The models name: /checkpoint/model_best is not in task:[information_extraction]

推理代码
from pprint import pprint
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称'] # Define the schema for entity extraction
ie = Taskflow('information_extraction', schema=schema,model="./uie-base")
pprint(ie("2月8日上午北京冬奥会自由式滑雪女子大跳台决赛中中国选手谷爱凌以188.25分获得金牌！"))

**Comment by wawltor** [comment]
model="./uie-base"  可以 改成  model="uie-base"，上面的问题是把"./uie-base" 认为是一个模型目录，然后这个目录又不存在。
