### ISSUE TITLE
您好，请问ernie预训练相关问题请您讲解。

### ISSUE THREAD

**Issue by shaitaiyangmie** [PaddlePaddle/PaddleNLP#940]
您好，请问在ernie预训练过程中，如果不采用sop任务，在pretraining_ds_mlm.py文件中，sample_negative负采样的目的是什么呢？为何还要采用build_pair操作呢？还请您指点一二，感谢！

**Comment by ZHUI** [comment]
应该是为了中间 插入sep，形成 [cls, sentence_a,  sep, sentence_b, seq] 的输入格式。

**Comment by shaitaiyangmie** [comment]
> 应该是为了中间 插入sep，形成 [cls, sentence_a, sep, sentence_b, seq] 的输入格式。

谢谢您，我想再请问您一下，代码数据格式是什么呢？doc和doc_seg分别指代什么含义呢？

**Comment by ZHUI** [comment]
应该是 doc文本 和 doc断句信息，如果想研究ernie预训练，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0

目前 language_model/ernie/ 这套代码，后续将不再维护。language_model/ernie-1.0/ 这一套是我们最新维护的预训练版本。

**Comment by shaitaiyangmie** [comment]
> 应该是 doc文本 和 doc断句信息，如果想研究ernie预训练，可以参考 https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/ernie-1.0
> 
> 目前 language_model/ernie/ 这套代码，后续将不再维护。language_model/ernie-1.0/ 这一套是我们最新维护的预训练版本。
好的好的，谢谢您了。
