### ISSUE TITLE
[Question]: 运行run_finetune.py产生的问题

### ISSUE THREAD

**Issue by lcesd** [PaddlePaddle/PaddleNLP#9496]
### 请提出你的问题

Traceback (most recent call last):
  File "/mnt/workspace/PaddleNLP/llm/run_finetune.py", line 46, in <module>
    from paddlenlp.peft.reft import (
ModuleNotFoundError: No module named 'paddlenlp.peft.reft'

查看了一下paddlenlp.peft，发现没有.reft

(python39) /mnt/workspace/PaddleNLP/llm> ls /usr/local/lib/python3.11/dist-packages/paddlenlp/peft
__init__.py  lora  prefix  __pycache__  vera

**Comment by wawltor** [comment]
请更新到最新的develop版本的paddlenlp，安装方式 
`pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html
`

**Comment by lcesd** [comment]
> 请更新到最新的develop版本的paddlenlp，安装方式 `pip install --pre --upgrade paddlenlp -f https://www.paddlepaddle.org.cn/whl/paddlenlp.html `

**Comment by lcesd** [comment]
谢谢您，已经解决了，多谢大佬，

**Comment by lcesd** [comment]
谢谢您，这个问题用您的方法已经解决了，谢谢大佬。我还有一个问题，想麻烦问您一下。我使用Lora微调了Qwen2-7B，在合并参数的时候，在Begin to save merged model之后，大概两行以后，出现了 Killed（可能是内存不够）。这样的话，是不是合并到主干参数没有成功，如果直接调用模型Qwen2-7B，这个时候，是微调后的模型还是没有微调的模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月26日(星期二) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleNLP] [Question]: 运行run_finetune.py产生的问题 (Issue #9496)















请更新到最新的开发版本的paddlenlp，安装方式
pip install --pre --upgrade paddlenlp -fhttps://www.paddlepaddle.org.cn/whl/paddlenlp.html

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;
