### ISSUE TITLE
请问paddlenlp中如何实现文本多标签分类，没有看到样例

### ISSUE THREAD

**Issue by Clearloveplus7** [PaddlePaddle/PaddleNLP#953]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by linjieccc** [comment]
你好！多标签文本分类用例请参考这里
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification/multi_label

**Comment by ZeyuChen** [comment]
@linjieccc 更新下主页README进行引导。

**Comment by linjieccc** [comment]
> @linjieccc 更新下主页README进行引导。

好的

**Comment by linjieccc** [comment]
PR: https://github.com/PaddlePaddle/PaddleNLP/pull/955  已更新多标签文本分类至范例清单

**Comment by ZeyuChen** [comment]
@Clearloveplus7 Issue solved.
