### ISSUE TITLE
希望能增加关键词提取功能及相关示例

### ISSUE THREAD

**Issue by qurikuduo** [PaddlePaddle/PaddleNLP#9546]
### Feature request

希望能增加类似于文本摘要一样的、具备关键词提取功能的模型，或者如果已有模型，能给出示例，比如使用 SimpleServing服务化部署的示例。文档：[SimpleServing服务化部署](https://github.com/PaddlePaddle/PaddleNLP/tree/release/2.8/applications/text_summarization/finetune/deploy/simple_serving)。
我目前使用的服务方法：
``` 
from paddlenlp import SimpleServer, Taskflow

# 使用指定目录加载模型
ts = Taskflow("text_summarization", task_path="/root/.paddlenlp/models/PaddlePaddle/Randeng-Pegasus-523M-Summary-Chinese-SSTIA/")
app = SimpleServer()
app.register_taskflow("taskflow/text_summarization", ts)
```
然后使用：
```paddlenlp server server:app --workers 1 --host 0.0.0.0 --port 8189``` 即可启动服务。多谢。

### Motivation

构建nlp各任务的微服。

### Your contribution

暂无。

**Comment by wawltor** [comment]
关键词的提取的功能相对是一个发散的功能，因为不同用户对关键词的提取不一致；可以看看信息抽取的功能是否符合预期。

**Comment by qurikuduo** [comment]
ok，多谢。
