### ISSUE TITLE
unified_transformer有英文版本的吗？

### ISSUE THREAD

**Issue by wht0948** [PaddlePaddle/PaddleNLP#967]
如题，我想试一下英文对话的效果，但是没找到英文版的
用这个函数的时候UnifiedTransformerLMHeadModel.from_pretrained('unified_transformer-12L')得到了下面的报错
ValueError: Calling UnifiedTransformerLMHeadModel.from_pretrained() with a model identifier or the path to a directory instead. The supported model identifiers are as follows: dict_keys(['unified_transformer-12L-cn', 'unified_transformer-12L-cn-luge'])

**Comment by ZeyuChen** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/dialogue/plato-2
英文的对话模型可以试试PLATO-2 @wanghaotian233
