### ISSUE TITLE
找不到ppnlp.dataset里面的数据集（chnsenticorp）

### ISSUE THREAD

**Issue by mostShadowless** [PaddlePaddle/PaddleNLP#972]
加载 chnsenticorp 数据集失败，下午2点的时候还是可以正常加载的，现在就不行了，请问这个数据集被删除了吗
![image](https://user-images.githubusercontent.com/43037642/132119144-c99a3d83-0e0a-42c1-9ee4-28e40ef659d9.png)

![image](https://user-images.githubusercontent.com/43037642/132119164-6200cb78-c49e-4cb8-b04d-429eb9409c27.png)

**Comment by ZeyuChen** [comment]
@mostShadowless 请升级paddlenlp到最新版本，这种错误是paddlenlp不是最新版本导致的。
