### ISSUE TITLE
请问如何使用多核cpu进行推理

### ISSUE THREAD

**Issue by d049** [PaddlePaddle/PaddleNLP#976]
欢迎您反馈PaddleNLP使用问题，非常感谢您对PaddleNLP的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleNLP和PaddlePaddle版本：请提供您的PaddleNLP和PaddlePaddle版本号，例如PaddleNLP 2.0.4，PaddlePaddle2.1.1
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by FrostML** [comment]
请问应用场景是什么？Paddle Inference，PaddleLite 或是...？

**Comment by gjj123** [comment]
> 请问应用场景是什么？Paddle Inference，PaddleLite 或是...？

paddle paddle layoutxlm 推理 cpu利用率只有100% 以内，怎么设置多核？支持多核吗？
