### ISSUE TITLE
example里面的例子代码 

### ISSUE THREAD

**Issue by zhoukaiwei66** [PaddlePaddle/PaddleNLP#987]
PaddleNLP/examples/language_model/bert/run_pretrain.py 文件里的第336行的train_data_loader在do_train函数里面在该行之前没有定义，反而在后面定义了，代码会显示该变量未定义。环境windows paddlenlp版本为2.0.7，paddelpaddle版本为2.1.2。麻烦查看一下呢

**Comment by guoshengCS** [comment]
好的，我们这边修复下，感谢指出~

**Comment by Yanxing-Shi** [comment]
> 好的，我们这边修复下，感谢指出~

hi，请问这个问题修复好了吗？

**Comment by Yanxing-Shi** [comment]
> 好的，我们这边修复下，感谢指出~

你好，请问这个问题修复好了吗？
