### ISSUE TITLE
快递单信息抽取预测都是用test数据集，如果用未标注数据来预测这个预测代码该怎么改呢？？

### ISSUE THREAD

**Issue by cfy42584125** [PaddlePaddle/PaddleNLP#994]
preds = predict(model, test_loader, test_ds, label_vocab)
file_path = "ernie_results.txt"
with open(file_path, "w", encoding="utf8") as fout:
    fout.write("\n".join(preds))
# Print some examples
print(
    "The results have been saved in the file: %s, some examples are shown below: "
    % file_path)
print("\n".join(preds[:10]))

用未标注数据俩预测这个代码怎么改呢？？

**Comment by joey12300** [comment]
你好，快递单信息抽取暂无预测未标注数据。可以暂时先参考lac的预测代码：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/lexical_analysis/deploy/predict.py

**Comment by yangy996** [comment]
改这两个位置就可以了
![image](https://user-images.githubusercontent.com/15188456/145789499-14f0dd15-24c9-4669-91bd-a56b0d85896f.png)
![image](https://user-images.githubusercontent.com/15188456/145789535-a859256b-3763-4b1b-9352-81ba6c27823e.png)
