### ISSUE TITLE
GPT3 hang when mp_degree > 1

### ISSUE THREAD

**Issue by sneaxiy** [PaddlePaddle/PaddleNLP#996]
1）PaddleNLP和PaddlePaddle版本：PaddleNLP 2.0.8, PaddlePaddle develop
2）系统环境：Linux，Python 3.8
直接跑 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/gpt-3/static/run_static.sh 这个脚本就会hang。

**Comment by JiaojiaoYe1994** [comment]
遇到了一样的问题。请问你的gpt3可以运行了吗？

**Comment by ZHUI** [comment]
> 遇到了一样的问题。请问你的gpt3可以运行了吗？

嗯嗯，目前看sharding 和 mp 遇到了一些兼容性问题。可以先设置 mp_degree=1，不使用mp。

**Comment by JiaojiaoYe1994** [comment]
> > 遇到了一样的问题。请问你的gpt3可以运行了吗？
> 
> 嗯嗯，目前看sharding 和 mp 遇到了一些兼容性问题。可以先设置 mp_degree=1，不使用mp。
好的，我再试试～

**Comment by FeixLiu** [comment]
最新develop分支已经可以运行了

**Comment by ZHUI** [comment]
> 最新develop分支已经可以运行了

经验证，可以运行，loss 正常下降。 @sneaxiy

**Comment by ZeyuChen** [comment]
Issue resolved.
